### ISSUE TITLE
MultiTask Model - Keypoint and Segmentation

### ISSUE THREAD

**Issue by stedavkle** [ultralytics/ultralytics#6949]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi there!
I need a single model for the keypoint and segmentation task. I've found 2 other issues stating similar questions: #5949 and #2639.

I already implemented most of the stuff to make this possible. However I need some further advice on what exactly to do.
Please let me know if I missed something or if you have any ideas on what would be a better implementation.
If you need some actual code to look at let me know, i'll be happy to provide my implementation.

Tasks:

1. Implement a MultiTask head - [ultralytics\nn\modules\head.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/modules/head.py)
Should it be a head that just utilizes a segmentation + pose head or a custom head implementing the behavior of both?
```
class MultiTask(nn.Module):
...
    self.segment_head = Segment(nc, nm, npr, ch)
    self.pose_head = Pose(nc, kpt_shape, ch)
...
```
This question is also relevant for the appropriate .yaml model file.
Can the head be modified like this or would it need a complete second head attached to the backbone?
```
head:
...
 #- [[15, 18, 21], 1, Segment, [nc, 32, 256]]  # Segment(P3, P4, P5)
 #- [[15, 18, 21], 1, Pose, [nc, kpt_shape]]  # Pose(P3, P4, P5)
  - [[15, 18, 21], 1, MultiTask, [nc, 32, 256, kpt_shape]] # MultiTask(P3, P4, P5)
```
3. Implement the MultiTaskModel in [ultralytics\nn\tasks.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/tasks.py)
4. Implement the v8MultiTaskLoss in  [ultralytics\utils\loss.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/loss.py)
5. Implement the MultiTaskMetrics in [ultralytics\utils\loss.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/metrics.py)
6. Implement MultiTaskPredictor, MultiTaskTrainer, MultiTaskValidator in ultralytics\models\yolo\multitask and add to [ultralytics\models\yolo\model.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/models/yolo/model.py)
7. Important is the right dataset format. My idea is a modified YOLO format which combines pose and segmentation annotations:
`<class-index> <px1> <py1> <p1-visibility> ... <pxn> <pyn> <pn-visibility> <x1> <y1> ... <xn> <yn>`
This would require the YAML to contain the following:
```
path: ../datasets/coco8-seg  # dataset root dir
train: images/train  # train images (relative to 'path') 4 images
val: images/val  # val images (relative to 'path') 4 images
test:  # test images (optional)

# Keypoints
kpt_shape: [17, 3]  # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)
flip_idx: [0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15]

# Classes dictionary
kpt_names:
  0: person

# Classes (80 COCO classes)
names:
  0: person
  # ...
  79: toothbrush
```
Now the YOLODataset class in [ultralytics\data\dataset.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/data/dataset.py) has to be extended to handle pose/segments simultaneously.
**Question**: is there always only one class with keypoint labels? Then we could get rid of kpt_names mentioned above and just assume that class 0 has keypoints.

9. Small adjustments to plot_results()
What do these indexes do exactly? Is this the right way?
```
elif segment:
    fig, ax = plt.subplots(2, 8, figsize=(18, 6), tight_layout=True)
    index = [1, 2, 3, 4, 5, 6, 9, 10, 13, 14, 15, 16, 7, 8, 11, 12]
elif pose:
    fig, ax = plt.subplots(2, 9, figsize=(21, 6), tight_layout=True)
    index = [1, 2, 3, 4, 5, 6, 7, 10, 11, 14, 15, 16, 17, 18, 8, 9, 12, 13]
elif multitask:
    fig, ax = plt.subplots(2, 10, figsize=(24, 6), tight_layout=True)
    index = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
```

### Use case

Perform keypoint detection and segmentation simultaneously using the same backbone. This will reduce inference time and might be useful for certain tasks.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@stedavkle hello!

You're on an interesting path toward multitask learning with YOLOv8 for keypoint and segmentation tasks. It's great to see your initiative and the detailed plan you've outlined.

For a multitask head, using a combination of segmentation and pose heads is a reasonable approach, especially if you want to leverage existing architectures and their strengths. Creating a new MultiTask head that aggregates functionalities might be more elegant, and you could start with separate heads for faster prototyping and then unify them.

Modifying the `.yaml` file as you proposed seem logical. You would define a new head combining the necessary parameters to handle both tasks. Ensure the head parameters match the adjusted head module you implement.

Regarding the loss function, metrics, predictor, trainer, and validator updates, make sure that each component accommodates the nuances of both tasks and handles their outputs cohesively.

The modified YOLO dataset format you proposed for accommodating pose and segmentation annotations makes sense. Making sure the YOLODataset class can parse and utilize these annotations jointly is crucial. If you only have one class with keypoint labels, simplifying the format as you've hinted could be beneficial, but consider the flexibility for future use cases that might require more classes.

For the` plot_results()` indexes, they typically control the subplot arrangement. Your adjusted indexes for simultaneous display of segmentation and pose results should reflect the multitask combination with an appropriate layout that represents both tasks clearly.

Remember to test each integration point thoroughly to ensure your modifications don't affect other functionalities. Also, keep in mind maintainability and readability since this seems to be a substantial addition.

We’re looking forward to your contribution. Don’t hesitate to reach out if you have specific questions as you work through your PR. Happy coding! 😊

**Comment by stedavkle** [comment]
Hi!
Thank you for your fast reply, it is good to know that I am on the right path implementing the modelhead.

Regarding the pose model for multiple classes. Is this a thing that has already be done?
I don't see how kpt_shape and flip_idx can be used to define the keypoints for multiple classes.

**Comment by glenn-jocher** [comment]
Hello @stedavkle,

Yes, you're on the right track with the model head.

Concerning pose estimation for multiple classes, it's typically managed by defining keypoints separately for each class and customizing the dataset annotations accordingly. The `kpt_shape` is designed for a single class's keypoints in the current setup. Multiple classes would require a way to associate each keypoint set with its corresponding class, either by extending the `kpt_shape` and annotation format or by using a mapping strategy. 

`flip_idx` applies to keypoints that are symmetrical and should be flipped during augmentation for a single class. For multiple classes, you might need different `flip_idx` for each class.

No direct multi-class keypoint mechanism is in place within the current YOLOv8 design as it often focuses on a single predominant class like 'person' for pose estimation. Adapting it to handle multiple classes would indeed be an innovative addition.

**Comment by stedavkle** [comment]
Hi @glenn-jocher,
i came pretty far with my implementation.
The model is building properly and I can load the customized `coco8-multitask` dataset.
However there persists a problem in the validator at the following lines:

[ultralytics\engine\validator.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/validator.py)
```
182: # Postprocess
182: with dt[3]:
183:    preds = self.postprocess(preds)
184:
185: self.update_metrics(preds, batch)

```

The output from the `.forward()` function my MultiTask head looks like this:
`return (torch.cat([x, mc, pred_kpt], 1), p) if self.export else (torch.cat([x[0], mc, pred_kpt], 1), (x[1], mc, p, kpt))`

The validator obtains the result.
`preds = model(batch['img'], augment=augment)`
then updates the loss of the model.

**Question:**
What exactly should `.postprocess(preds)` do for the MultiTask Head?
This is my code:
```
def postprocess(self, preds):
        """Post-processes YOLO predictions and returns output detections with proto."""
        p = ops.non_max_suppression(preds**[0]**,
                                    self.args.conf,
                                    self.args.iou,
                                    labels=self.lb,
                                    multi_label=True,
                                    agnostic=self.args.single_cls,
                                    max_det=self.args.max_det,
                                    nc=self.nc)
        proto = preds[1][-2] if len(preds[1]) == 4 else preds[1]  # second output is len 4 if pt, but only 1 if exported
        return p, proto
```
`Question:` It first applies non max suppression since this is done in the Segment and Pose case. however should it use `preds` or `preds[0]`?

Then it extracts the proto masks using:
`proto = preds[1][-2] if len(preds[1]) == 4 else preds[1]  # second output is len 4 if pt, but only 1 if exported`
Note the index -2 at the beginning, this is because the tuple returned by `.forward()` is `(x[1], mc, p, kpt)`
This is fine right?

The main problem starts in `update_metrics(preds, batch)` `ultralytics\models\yolo\multitask\val.py`.
This is my code to extract both predictions:
```
# Masks
midx = [si] if self.args.overlap_mask else idx
gt_masks = batch['masks'][midx]
pred_masks = self.process(proto, pred[:, 6:], pred[:, :4], shape=batch['img'][si].shape[1:])

# Predictions
if self.args.single_cls:
    pred[:, 5] = 0
predn = pred.clone()
ops.scale_boxes(batch['img'][si].shape[1:], predn[:, :4], shape,
                ratio_pad=batch['ratio_pad'][si])  # native-space pred
pred_kpts = predn[:, 6:].view(npr, nk, -1)
ops.scale_coords(batch['img'][si].shape[1:], pred_kpts, shape, ratio_pad=batch['ratio_pad'][si])

```
**Traceback:** 
```
  File "C:\Users\david\projects\ultralytics\ultralytics\engine\validator.py", line 186, in __call__
    self.update_metrics(preds, batch)
  File "C:\Users\david\projects\ultralytics\ultralytics\models\yolo\multitask\val.py", line 121, in update_metrics
    pred_masks = self.process(proto, pred[:, 6:], pred[:, :4], shape=batch['img'][si].shape[1:])
  File "C:\Users\david\projects\ultralytics\ultralytics\utils\ops.py", line 657, in process_mask
    masks = (masks_in @ protos.float().view(c, -1)).sigmoid().view(-1, mh, mw)  # CHW
RuntimeError: mat1 and mat2 shapes cannot be multiplied (300x83 and 32x28224)
```

I believe the problem is that at
`pred_masks = self.process(proto, pred[:, 6:], pred[:, :4], shape=batch['img'][si].shape[1:])`
proto contains both, segmentation detections and keypoints. This results in a faulty mask extraction.

Can you give me any advice what is wrong? I can't find a solution since i'm not too familiar with the code.
I can provide you with more information or the whole code if that helps.
Thanks in advance!

Here the code of the head and the validator:
[ultralytics\models\yolo\multitask\val.py](https://github.com/ultralytics/ultralytics/files/13742469/head.txt)
[ultralytics\nn\modules\head.py](https://github.com/ultralytics/ultralytics/files/13742461/multitask-val.txt)

**Comment by glenn-jocher** [comment]
Hello @stedavkle,

Great progress on your multitask implementation!

The `.postprocess(preds)` function is intended to transform the raw network predictions into a properly structured output. For a multitask scenario, where both segmentation masks and keypoints are predicted, you will need to separately process these components.

For non-max suppression (NMS), you’re correct in applying it to the detection component (boxes and class confidences)—`preds[0]`. For the multitask head's output structure, ensure that the predictions are correctly accessed.

The handling of `proto` masks seems right, given that `preds[1]` carries the mask predictions. Just ensure that `proto` represents the segmentation outputs exclusively, possibly having another variable for keypoints if they are also output by the head.

Regarding your RuntimeError during mask processing, the shapes don’t align because the predictions seem to contain more than just segmentation data. The error suggests you are trying to multiply a tensor meant for semantic segmentation with data that contains keypoints as well.

You need to delineate segmentation and keypoint predictions before passing them into their respective processing functions. Check the dimensions and contents thoroughly to ensure they match expectations. Keywise, review your model's forward pass to ensure segmentation and keypoints outputs are structured in a way that facilitates easy extraction during validation.

If you continue to encounter issues with mismatched shapes in `pred_masks` and `pred_kpts`, you may need to refactor how predictions are unpacked and provided to each processing function to ensure each receives only the relevant data.

Lastly, consider implementing unit tests for individual components to catch issues early and isolate problems more effectively—the head output, postprocessing, and metrics update.

Keep up the good work, and I'm looking forward to seeing your multitask model in action!

**Comment by stedavkle** [comment]
Hi @glenn-jocher,

thanks again for the good hints. I was able to get the model to train properly.
I changed the output format of the multitask head 
now to a tuple of segmentation and pose predictions.
`return ((torch.cat([x, mc], 1), p), torch.cat([x, pred_kpt], 1)) if self.export else ((torch.cat([x[0], mc], 1), torch.cat([x[0], pred_kpt], 1)), (x[1], mc, p, kpt))`
This way I can access the segmentation predictions as `preds[0][1]` and the keypoint predicitons as `preds[0][1]`.

`postprocess(preds)` now processes both predictions seperately.
```
def postprocess(self, preds):
        """Post-processes YOLO predictions and returns output detections with proto."""
        p_seg = ops.non_max_suppression(preds[0][0],
                                    self.args.conf,
                                    self.args.iou,
                                    labels=self.lb,
                                    multi_label=True,
                                    agnostic=self.args.single_cls,
                                    max_det=self.args.max_det,
                                    nc=self.nc)
        p_pose = ops.non_max_suppression(preds[0][1],
                                    self.args.conf,
                                    self.args.iou,
                                    labels=self.lb,
                                    multi_label=True,
                                    agnostic=self.args.single_cls,
                                    max_det=self.args.max_det,
                                    nc=self.nc)
        proto = preds[1][-2] if len(preds[1]) == 4 else preds[0][1]  # second output is len 4 if pt, but only 1 if exported
        return (p_seg, p_pose), proto
```

in `update_metrics(preds, batch)` we zip and iterate over the whole output as followed:
`for si, (pred_seg, pred_kpt, proto) in enumerate(zip(preds[0][0], preds[0][1], preds[1])):`
In the following code all references of `preds `got changed to to the corresponding `pred_seg, pred_kpt`.

Everything works fine until the validator plots the results.
In `plot_images()` of [ultralytics\utils\plotting.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/plotting.py) I get the following error:
```
Traceback (most recent call last):
  File "c:\Users\david\miniconda3\envs\ultralytics\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "c:\Users\david\miniconda3\envs\ultralytics\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\david\projects\ultralytics\ultralytics\utils\plotting.py", line 455, in plot_images
    kpts_ = kpts[idx].copy()
IndexError: boolean index did not match indexed array along dimension 0; dimension is 926 but corresponding boolean dimension is 60
```

This is how my `plot_predictions()` function in [ultralytics\models\yolo\multitask\val.py](https://github.com/ultralytics/ultralytics/files/13742469/head.txt) looks like now:
```def plot_predictions(self, batch, preds, ni):
        """Plots batch predictions with masks and bounding boxes."""
        pred_kpts = torch.cat([p[:, 6:].view(-1, *self.kpt_shape) for p in preds[0][1]], 0)
        plot_images(
            batch['img'],
            *output_to_target(preds[0][1], max_det=15),  # not set to self.args.max_det due to slow plotting speed
            torch.cat(self.plot_masks, dim=0) if len(self.plot_masks) else self.plot_masks,
            kpts=pred_kpts,
            paths=batch['im_file'],
            fname=self.save_dir / f'val_batch{ni}_pred.jpg',
            names=self.names,
            on_plot=self.on_plot)  # pred
        self.plot_masks.clear()```

I believe this happens because `batch_idx` which gets unpacked from the `pred_seg` using `*output_to_target(preds[0][1], max_det=15)` does not match the `batch_idx` of `pred_kpt`.
Would you agree on that?

Do you have any suggestions on how to handle this, any solution without changing `plot_predictions`?

Thanks again and have a great new years eve!

**Comment by glenn-jocher** [comment]
Hi @stedavkle,

I'm pleased to hear that you've made significant progress and the model is now training properly with the adjusted multitask head output format.

Regarding the `plot_images()` function error, it seems like there's a mismatch in the dimensions. The error indicates that `kpts[idx]` is accessing `kpts` with a boolean index array (`idx`) whose length does not match the dimension of `kpts` along the first axis. This can happen if the index array does not correlate directly to the keypoint predictions being passed.

The issue may indeed stem from different `batch_idx` used for segmentation and keypoints due to separate non-max suppression processes. If that's the case, the subsets of keypoints do not correctly correspond to the images being plotted.

One way to handle this without altering `plot_predictions` is by ensuring that the same `batch_idx` generated from `pred_seg` is applied to both segmentation and keypoint predictions. You could synchronize the NMS steps for both tasks or align the indexing post-NMS.

You may need to trace back where `batch_idx` is generated and how it is used between both tasks to ensure the indexing remains consistent.

Happy to help, and wishing you a successful new year in advancing your work with the multitask model! 🎉

**Comment by 0iui0** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.
> 
> ### Description
> Hi there! I need a single model for the keypoint and segmentation task. I've found 2 other issues stating similar questions: #5949 and #2639.
> 
> I already implemented most of the stuff to make this possible. However I need some further advice on what exactly to do. Please let me know if I missed something or if you have any ideas on what would be a better implementation. If you need some actual code to look at let me know, i'll be happy to provide my implementation.
> 
> Tasks:
> 
> 1. Implement a MultiTask head - [ultralytics\nn\modules\head.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/modules/head.py)
>    Should it be a head that just utilizes a segmentation + pose head or a custom head implementing the behavior of both?
> 
> ```
> class MultiTask(nn.Module):
> ...
>     self.segment_head = Segment(nc, nm, npr, ch)
>     self.pose_head = Pose(nc, kpt_shape, ch)
> ...
> ```
> 
> This question is also relevant for the appropriate .yaml model file. Can the head be modified like this or would it need a complete second head attached to the backbone?
> 
> ```
> head:
> ...
>  #- [[15, 18, 21], 1, Segment, [nc, 32, 256]]  # Segment(P3, P4, P5)
>  #- [[15, 18, 21], 1, Pose, [nc, kpt_shape]]  # Pose(P3, P4, P5)
>   - [[15, 18, 21], 1, MultiTask, [nc, 32, 256, kpt_shape]] # MultiTask(P3, P4, P5)
> ```
> 
> 3. Implement the MultiTaskModel in [ultralytics\nn\tasks.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/tasks.py)
> 4. Implement the v8MultiTaskLoss in  [ultralytics\utils\loss.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/loss.py)
> 5. Implement the MultiTaskMetrics in [ultralytics\utils\loss.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/metrics.py)
> 6. Implement MultiTaskPredictor, MultiTaskTrainer, MultiTaskValidator in ultralytics\models\yolo\multitask and add to [ultralytics\models\yolo\model.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/models/yolo/model.py)
> 7. Important is the right dataset format. My idea is a modified YOLO format which combines pose and segmentation annotations:
>    `<class-index> <px1> <py1> <p1-visibility> ... <pxn> <pyn> <pn-visibility> <x1> <y1> ... <xn> <yn>`
>    This would require the YAML to contain the following:
> 
> ```
> path: ../datasets/coco8-seg  # dataset root dir
> train: images/train  # train images (relative to 'path') 4 images
> val: images/val  # val images (relative to 'path') 4 images
> test:  # test images (optional)
> 
> # Keypoints
> kpt_shape: [17, 3]  # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)
> flip_idx: [0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15]
> 
> # Classes dictionary
> kpt_names:
>   0: person
> 
> # Classes (80 COCO classes)
> names:
>   0: person
>   # ...
>   79: toothbrush
> ```
> 
> Now the YOLODataset class in [ultralytics\data\dataset.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/data/dataset.py) has to be extended to handle pose/segments simultaneously. **Question**: is there always only one class with keypoint labels? Then we could get rid of kpt_names mentioned above and just assume that class 0 has keypoints.
> 
> 9. Small adjustments to plot_results()
>    What do these indexes do exactly? Is this the right way?
> 
> ```
> elif segment:
>     fig, ax = plt.subplots(2, 8, figsize=(18, 6), tight_layout=True)
>     index = [1, 2, 3, 4, 5, 6, 9, 10, 13, 14, 15, 16, 7, 8, 11, 12]
> elif pose:
>     fig, ax = plt.subplots(2, 9, figsize=(21, 6), tight_layout=True)
>     index = [1, 2, 3, 4, 5, 6, 7, 10, 11, 14, 15, 16, 17, 18, 8, 9, 12, 13]
> elif multitask:
>     fig, ax = plt.subplots(2, 10, figsize=(24, 6), tight_layout=True)
>     index = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
> ```
> 
> ### Use case
> Perform keypoint detection and segmentation simultaneously using the same backbone. This will reduce inference time and might be useful for certain tasks.
> 
> ### Additional
> _No response_
> 
> ### Are you willing to submit a PR?
> * [x]  Yes I'd like to help by submitting a PR!

 FYI #5073 
https://github.com/yermandy/ultralytics/tree/multi-task-model

**Comment by 0iui0** [comment]
Hi, @stedavkle may be this is a good reference for  you. https://github.com/yermandy/ultralytics/tree/multi-task-model

#5073

**Comment by stedavkle** [comment]
Hi @glenn-jocher,

my custom model is now finished.
The data loading is working correctly, distinguishing between objects with and without keypoints.

Because of the model architecture I decided that the keypoint head will work with the maximum number of keypoints defined in the  `.yaml` by `kpt_shape`.
For object which are not in `kpt_names` or have less than `kpt_shape[0]` keypoints, ALL not present keypoints should be labeled `(0,0,0)`. this way the model head will be kept simple and does not have to be of different shape for all classes.

For evaluation I trained the YOLO-Pose, YOLO-Segment and YOLO-MultiTask on the same dataset.
The results are great, the MultiTask model performs both tasks simultaneously equally well. I just needed to tune the `pose loss gain` for training so that the pose estimation gets weight equally.
The evalaution and visualization works and the metrics also get plotted correctly.

If your are interested in merging the codebase, please let me know what has to be provided and ensured from my side.
And if any special requirements have to be fullfilled.
I will open a fork and upload my code.

@0iui0 thanks for the Info! It was quite helpful in comparing and double checking my own approach.

**Comment by glenn-jocher** [comment]
Hi @stedavkle,

Fantastic news on completing your custom multitask model and achieving great results! It's impressive that you've managed to train a model that performs both keypoint detection and segmentation tasks effectively.

Your approach to handle keypoints by using a maximum number defined in `.yaml` and labeling non-present keypoints as `(0,0,0)` is a smart solution to maintain a consistent model architecture.

We're definitely interested in community contributions that enhance the capabilities of YOLOv8. To proceed with a potential merge:

1. Ensure your code is well-documented and follows the existing coding style for readability and maintainability.
2. Write unit tests for your new features to verify their functionality and robustness.
3. Update the documentation to reflect your new multitask features, including how to use them and any changes to the dataset format.
4. Open a pull request from your fork with a clear description of the changes, the benefits, and any potential impacts on existing functionality.

Once you've opened a PR, we'll review the changes, provide feedback, and discuss any necessary adjustments.

Thank you for your willingness to contribute, and we look forward to seeing your work! 🚀

**Comment by stedavkle** [comment]
Hi @glenn-jocher,

i am happy that I can contribute something to a great project like this!

Regarding the documentation.
I will write the documentation of the task "multitask" [ultralytics/docs/en/tasks](https://github.com/ultralytics/ultralytics/tree/main/docs/en/tasks) similar to the segmentation and keypoint doc.
The new task will also be mentioned in [/ultralytics/docs/en/models/yolov8.md](https://github.com/ultralytics/ultralytics/blob/main/docs/en/models/yolov8.md)
Also I will provide a documentation for the dataset format "multitask" in [ultralytics//docs/en/datasets](https://github.com/ultralytics/ultralytics/tree/main/docs/en/datasets).

I created a `COCO8-multitask` with the related `coco8-multitask.yaml` for testing. I can provide you with that.
Do you need me to merge the COCO-pose and COCO-seg labels to get a big `COCO-multitask` dataset?

I wrote a small script for merging `Keypoint` and `Segmentation` datasets in YOLO format to a single dataset in the multitask YOLO format mentioned earlier in this issue.
For the segmentation labels of classes which should also have keypoints, it calculates the bounding boxes and compares them to the boxes of the keypoint labels. If a box matches, it assumes both labels are from the same object and combines them.
Where should that script be placed if you want it included?

I can not provide you with a pretrained `yolov8n-multitask.pt` model and I can not include any metrics in the documentation.
Neither can I verify all export formats.

Please let me know if this will suits your needs on documentation.

**Comment by glenn-jocher** [comment]
Hi @stedavkle,

It's wonderful to hear about your enthusiasm and readiness to contribute to the project!

Your plan for the documentation sounds comprehensive. Including the new `Multitask` task in the tasks section and mentioning it in the YOLOv8 model documentation will certainly help users understand and utilize your contribution effectively.

The `COCO8-multitask` dataset and corresponding `.yaml` file for testing will be a valuable addition. As for merging COCO-pose and COCO-seg labels, it would be beneficial to have a larger `COCO-multitask` dataset for more extensive testing and potential future training, but it's not a strict requirement for the initial contribution.

Your script for merging datasets could be a useful tool for the community. Consider placing it in a `tools` or `scripts` directory within the repository, and ensure it's mentioned in the documentation where relevant.

While a pretrained `yolov8n-multitask.pt` model and verified metrics would be ideal, we understand that these may not be feasible for you to provide. The community or the Ultralytics team can work on these aspects later.

Your planned contributions already go a long way in enhancing the YOLOv8 ecosystem. Please proceed with the pull request when you're ready, and we'll review it for integration into the main codebase.

Thank you for your dedication to improving YOLOv8! 🌟

**Comment by stedavkle** [comment]
Hi @glenn-jocher,

I just opened the two pull requests, I hope ultralytics/hub is the right place for the dataset, I noticed in the code, that all of the `coco8` datasets are downloaded from there.

thanks for assisting me throughout this development.
Have a nice weekend!

Regards
David

**Comment by glenn-jocher** [comment]
@stedavkle hi David,

Thank you for opening the pull requests. Yes, `ultralytics/hub` is the correct place for the dataset. We'll review your contributions and get back to you with feedback or any further steps needed.

I appreciate your kind words and am glad I could assist you. Have a wonderful weekend as well!

**Comment by Bekbo01** [comment]
hi! I tried train own multitask models with 15 class and 1 class with keypoints (pose estimation). But model don't correctly predicts keypoins in pose) There are pretrained model (yolov8n-multitask.pt or else [segmentation+pose]) for traiding?

**Comment by glenn-jocher** [comment]
Hi there! 👋

For training multitask models that combine segmentation and pose estimation, ensuring that each task gets the appropriate attention during training is crucial. We currently don't have a pretrained `yolov8n-multitask.pt` model available for direct use. However, to improve keypoint detection, you might consider adjusting the loss weights for the pose estimation task in your training configuration to give more importance to keypoint predictions.

Here's a small code snippet that shows how you can modify the loss weights in your `.yaml` configuration file:

```yaml
# In your model.yaml file
loss_weights:
  box: 0.05
  obj: 0.4
  cls: 0.5
  kpt: 1.0  # Increase keypoint loss weight
```

This adjustment can help the model learn keypoint locations more effectively. Remember, finding the right balance for these weights might require some experimentation.

Good luck with your model training! If you have more specific issues or questions as you proceed, feel free to ask.

**Comment by hu874** [comment]
> Hi [@glenn-jocher](https://github.com/glenn-jocher),
> 
> I just opened the two pull requests, I hope `ultralytics/hub` is the right place for the dataset, I noticed in the code, that all of the `coco8` datasets are downloaded from there.
> 
> thanks for assisting me throughout this development. Have a nice weekend!
> 
> Regards David
Hello, I would like to add an output category for key points. How can I achieve this?

**Comment by glenn-jocher** [comment]
Hi, keypoints aren’t a separate “category” output—YOLO Pose predicts a fixed set of keypoints per detection defined by kpt_shape [num_kpts, dims]. To add keypoints, update kpt_shape (and flip_idx) in both your model and data YAMLs, ensure labels include (x,y,vis) for each keypoint, then retrain. If only some classes have keypoints, set missing ones to (0,0,0); true per-class keypoint schemas aren’t supported out of the box and would require a custom head/dataloader. See the Pose task guide and head behavior in the Ultralytics Docs: PoseModel usage and Pose head forward/kpts_decode.

**Comment by hu874** [comment]
Why do the dimensions of len(preds[1]) and len(preds[0]) change when I modify the batchsize, causing me to need to modify the length of len(preds[1]) myself to continue running?
`    def plot_predictions(self, batch, preds, ni):
        """Plots batch predictions with keypoints, masks and bounding boxes."""
        print("batch",batch)
        print("len(preds[1]):",len(preds[1]))
        print("len(preds[0]):",len(preds[0]))
        if len(preds[1]) == 17:
            print("preds[0]",preds[0])
            print("preds[0][1]",preds[0][1],preds[0][1][0].shape)
            for i, p in enumerate(preds[0][1]):
                print(f'preds[0][1][{i}].shape =', tuple(p.shape))
                cols_after6 = p.shape[1] - 6
                need = self.kpt_shape[0] * self.kpt_shape[1]
                print(f'cols_after6={cols_after6}, need={need}, remainder={cols_after6 % need}')
            pred_kpts = torch.cat([p[:, 6:].contiguous().view(-1, *self.kpt_shape) for p in preds[0][1]], 0)
            batch_idx, cls, bboxes, confs = output_to_target(preds[0][1], max_det=self.args.max_det)
            print("batch_idx",batch_idx)
            print("cls",cls)
            print("bboxes",bboxes)
            print("confs",confs)
            print("pred_kpts",pred_kpts)

        else:
            print("preds[0]",preds[0])
            for i, p in enumerate(preds[1]):
                print(f'preds[1][{i}].shape =', tuple(p.shape))
                cols_after6 = p.shape[1] - 6
                need = self.kpt_shape[0] * self.kpt_shape[1]
                print(f'cols_after6={cols_after6}, need={need}, remainder={cols_after6 % need}')
                # assert cols_after6 % need == 0, \
                #     f"Head输出与kpt_shape不匹配: got {cols_after6}, need multiple of {need}"

            pred_kpts = torch.cat([p[:, 6:].contiguous().view(-1, *self.kpt_shape) for p in preds[1]], 0)
            batch_idx, cls, bboxes, confs = output_to_target(preds[1], max_det=self.args.max_det)`

**Comment by glenn-jocher** [comment]
Hi @hu874, this usually happens when mixing pre-NMS tensors and post-NMS lists and then branching on container length. After NMS you should always have per-image lists of predictions with length equal to `batch['img'].shape[0]`; if you see `len(preds[1]) == 17` you’re likely iterating over the keypoint channel dimension, not the batch. Keep a stable contract: run NMS separately for seg and pose, use the seg aux `proto` per image, and derive `batch_idx` and `kpts` from the same pose list so indices align, e.g.:

```python
# preds from your multitask forward/postprocess
preds_seg, aux_seg = preds_seg_tuple  # preds_seg: (B, N, 6+nm), aux_seg: (feats, mc, proto)
preds_pose, aux_pose = preds_pose_tuple  # preds_pose: (B, N, 6+nk*ndim)

p_seg = ops.non_max_suppression(preds_seg, self.args.conf, self.args.iou, nc=self.nc, max_det=self.args.max_det)
p_pose = ops.non_max_suppression(preds_pose, self.args.conf, self.args.iou, nc=self.nc, max_det=self.args.max_det)
proto = aux_seg[-1]  # (B, C, H, W)

# plotting (use the same source list for both kpts and batch_idx)
kpts = torch.cat([pi[:, 6:].contiguous().view(-1, *self.kpt_shape) for pi in p_pose], 0)
batch_idx, cls, bboxes, confs = output_to_target(p_pose, max_det=self.args.max_det)
```

Avoid branching on `len(preds[1])`; instead use `bs = batch['img'].shape[0]` and treat NMS outputs as lists of length `bs`. For reference, see how seg and pose validators structure outputs in their postprocess functions in the docs: Segment postprocess and Pose postprocess in the [Ultralytics Docs](https://docs.ultralytics.com). If issues persist, please open a new issue with a minimal reproducible snippet and the exact tensor/list shapes you’re seeing.
