### ISSUE TITLE
Latest docker images hang during training

### ISSUE THREAD

**Issue by sstainba** [ultralytics/ultralytics#695]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

The current docker images for both yolov8 and yolov5 hang during training.  I have previously trained this same dataset with both yolov5 and v8 without issue.  Now, at some arbitrary step during training, the GPU memory is all released and there's no processing.  The terminal output stops.  I can't stop the image or anything.  

### Environment

Yolov8 Docker image (and yolov5 image)
Windows 11, docker via WSL2
Nvidia 3060/12GB

### Minimal Reproducible Example

Run custom train on dataset

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@sstainba hi there! 👋 It sounds like you're encountering a hang during training with both YOLOv8 and YOLOv5 Docker images, where the GPU memory is released and there's no processing after an arbitrary training step.

To investigate this, can you provide more details about the specific command or script you are using to start the training? Also, have you observed any error messages or warnings before the hang occurs?

Additionally, I'd recommend checking the NVIDIA driver version and ensuring it's compatible with the Docker images and your GPU.

In the meantime, you can try updating to the latest Docker images and checking the resource allocation to ensure the GPU memory is being utilized properly during training.

Let's work together to get this resolved! 😊
