### ISSUE TITLE
labels, coordinates = results.xyxyn[0][:, -1], results.xyxyn[0][:, :-1] not working in yolov8 but was working with yolov5

### ISSUE THREAD

**Issue by akashlinux10may** [ultralytics/ultralytics#696]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

While trying to retrieve labels and bounding box coordinates using below code:

labels, coordinates = results.xyxyn[0][:, -1], results.xyxyn[0][:, :-1]

error:
AttributeError: 'list' object has no attribute 'x1y1x2y2'

The same code was working in yolov5.

Please suggest the solution.

**Comment by AyushExel** [comment]
results is a list of `Results` object. Each element of the list represents the output of each image/frame. So results[0] will give you result of first image and so on. See exmample here - https://docs.ultralytics.com/predict/
