### ISSUE TITLE
Incorrect behavior of show_boxes=False in YOLOv8

### ISSUE THREAD

**Issue by MZaid101** [ultralytics/ultralytics#6961]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

#### **Problem:**

I am using YOLOv8 trained on custom dataset for instance segmentation of multiple objects in an image. I am trying to hide the bounding boxes but still retrieve the confidence scores and labels. However, the current implementation doesn't work as expected.

#### **Expected behavior:**

When using the show_boxes=False parameter in the predict function, the bounding boxes should be hidden from the output image. However, the confidence scores and labels for each detected object should still be accessible.

#### **Actual behavior:**

When using show_boxes=False, the bounding boxes are not hidden. 
the code:

```
from ultralytics import YOLO
import cv2

# Load YOLOv8 models
model1 = YOLO("models/model_parts.pt")
model2 = YOLO("models/damage_parts.pt")
vehicle_img = cv2.imread("TestImages/toy_rav4.jpg")
parts_seg_res = model1.predict(vehicle_img, show_boxes=False)
damge_seg_res = model2.predict(vehicle_img, show_boxes=False)
```

![image](https://github.com/ultralytics/ultralytics/assets/53510596/ee2e17c9-f943-4434-a978-28c27afc8a1a)

### Environment

```
Ultralytics YOLOv8.0.227 🚀 Python-3.9.13 torch-2.0.0+cu118 CUDA:0 (NVIDIA GeForce MX450, 2048MiB)
Setup complete ✅ (8 CPUs, 7.7 GB RAM, 170.0/234.4 GB disk)
```

### Minimal Reproducible Example

```
from ultralytics import YOLO
import cv2

# Load YOLOv8 models
model1 = YOLO("models/model_parts.pt") #you may load segmentation model here
model2 = YOLO("models/damage_parts.pt")
vehicle_img = cv2.imread("TestImages/toy_rav4.jpg")
parts_seg_res = model1.predict(vehicle_img, show_boxes=False)
damge_seg_res = model2.predict(vehicle_img, show_boxes=False)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MZaid101 thank you for the detailed bug report! Indeed, when setting `show_boxes=False` in the predict function, one would expect the bounding boxes to be hidden, while still having access to confidence scores and labels. Your observed behavior, where bounding boxes are not hidden, is not the intended functionality.

The issue you're experiencing seems like a bug that needs to be addressed. As for accessing the confidence scores and labels, even when boxes are not shown, they should still be present in the prediction results object (`parts_seg_res`, `damge_seg_res`) returned from the predict method.

We will look into this and resolve it. Your valuable feedback helps us improve. For now, please follow the progress on fixing this issue through the updates on our repository issues section. If you have further insights or additional details, feel free to add them to the issue thread.

Thanks for contributing to the YOLOv8 community! 🌟

**Comment by Laughing-q** [comment]
@MZaid101 not able to reproduce:
![pic-231215-1730-43](https://github.com/ultralytics/ultralytics/assets/61612323/371368b6-b485-43b5-a9ed-2b9dd08af7d5)

**Comment by MZaid101** [comment]
> @MZaid101 not able to reproduce: ![pic-231215-1730-43](https://private-user-images.githubusercontent.com/61612323/290783529-371368b6-b485-43b5-a9ed-2b9dd08af7d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzMxODMsIm5iZiI6MTcwMjYzMjg4MywicGF0aCI6Ii82MTYxMjMyMy8yOTA3ODM1MjktMzcxMzY4YjYtYjQ4NS00M2I1LWE5ZWQtMmI5ZGQwOGFmN2Q1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA5MzQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NDAyNTk2MzEwNWQ5OGJkMWJhMGY1YWZmNjM3NTkzNDhkZmY5MTVkYTBiYTNhMzIwNTAxNzE2MjJkYWQwZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L3HtSisYoA42B_AZjsOeAV8fVKVbNcGRRhaAMdMe_F4)

The labels should be visible, shouldn't they? You are only setting `show_boxes=False`

**Comment by Laughing-q** [comment]
@MZaid101 oh sorry just took a quick peek and thought you were expecting the hidden score and label but it still showed up.
The logic behind this is that score and label are bound to boxes, so these would be hidden together with boxes.

**Comment by Laughing-q** [comment]
@MZaid101 it's more like designed this way rather than a bug, but actually you could plot these stuffs by yourself as you want since you can get masks and scores and labels of predicted objects:
```python
results = model.predict(source)
for r in results:
    scores = r.boxes.conf
    labels = r.boxes.cls
    masks = r.masks.data
```

**Comment by MZaid101** [comment]
Yes I could get labels and mask, etc. but I thought having an option that is built-in should work.

**Comment by glenn-jocher** [comment]
Apologies for the confusion, @MZaid101. The built-in options should indeed work as documented. We acknowledge the discrepancy and will ensure the intended functionality is matched. Your feedback is crucial in refining YOLOv8, and we're on it. Thank you for your patience! 🛠️✨

**Comment by Shaksham22** [comment]
I faced the same issue as these parameters show_labels=False, show_conf=False, show_boxes=False do not work with model.predict.

**Comment by pderrenger** [comment]
@Shaksham22 thank you for bringing this to our attention. Please ensure you are using the latest version of the Ultralytics YOLOv8 package, as updates often include bug fixes and improvements. If the issue persists, we will investigate further to address this behavior. Your feedback is invaluable in helping us improve.
