### ISSUE TITLE
The difference between YOLOv8-pose inference and YOLOv8-ONNX Runtime on the same image.

### ISSUE THREAD

**Issue by myeonghunkim00** [ultralytics/ultralytics#6964]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I trained a custom YOLOv8-pose model, generated an ONNX file from the trained best.pt file, and modified the postprocess function in the YOLOv8-ONNX Runtime example to apply the ONNX file.

I ran the YOLOv8-pose model's inference and YOLOv8 - ONNX Runtime on the same image using both the best.pt and best.onnx files.

In the postprocess function of the inference, the number of candidate predictions (preds) was initially 5040, but after passing through the non-maximum suppression (NMS), the final result yielded 20 predictions.

**This is the postprocess part of the YOLOv8-pose inference code.**

```
    def postprocess(self, preds, img, orig_imgs):
        """Return detection results for a given input image or list of images."""
        preds = ops.non_max_suppression(preds,
                                        self.args.conf,
                                        self.args.iou,
                                        agnostic=self.args.agnostic_nms,
                                        max_det=self.args.max_det,
                                        classes=self.args.classes,
                                        nc=len(self.model.names))

        if not isinstance(orig_imgs, list):  # input images are a torch.Tensor, not a list
            orig_imgs = ops.convert_torch2numpy_batch(orig_imgs)

        results = []
        for i, pred in enumerate(preds):
            orig_img = orig_imgs[i]
            pred[:, :4] = ops.scale_boxes(img.shape[2:], pred[:, :4], orig_img.shape).round()
            pred_kpts = pred[:, 6:].view(len(pred), *self.model.kpt_shape) if len(pred) else pred[:, 6:]
            pred_kpts = ops.scale_coords(img.shape[2:], pred_kpts, orig_img.shape)
            img_path = self.batch[0][i]
            results.append(
                Results(orig_img, path=img_path, names=self.model.names, boxes=pred[:, :6], keypoints=pred_kpts))
        return results
```

In the ONNX Runtime, the number of candidates was initially 8400. After passing through the condition **if confidence >= self.confidence_thres:**, it reduced to 103. Following the non-maximum suppression (NMS), the final count became 14.

**This is the postprocess part of the YOLOv8-ONNX Runtime code.**

```
    def postprocess(self, input_image, output):
        """
        Performs post-processing on the model's output to extract bounding boxes, scores, and class IDs.

        Args:
            input_image (numpy.ndarray): The input image.
            output (numpy.ndarray): The output of the model.

        Returns:
            numpy.ndarray: The input image with detections drawn on it.
        """

        # Transpose and squeeze the output to match the expected shape
        outputs = np.transpose(np.squeeze(output[0]))
        # Get the number of rows in the outputs array
        rows = outputs.shape[0]

        # Lists to store the bounding boxes, scores, and class IDs of the detections
        boxes = []
        scores = []
        # class_ids = []
        keypoints_list = []

        # Calculate the scaling factors for the bounding box coordinates
        x_factor = self.img_width / self.input_width
        y_factor = self.img_height / self.input_height

        # Iterate over each row in the outputs array
        for i in range(rows):

            confidence = outputs[i][4]

            # If the maximum score is above the confidence threshold
            if confidence >= self.confidence_thres:
                # Extract the class scores from the current row
                # classes_id = outputs[i][5:]
                # Extract the bounding box coordinates from the current row
                x, y, w, h = outputs[i][0], outputs[i][1], outputs[i][2], outputs[i][3]

                keypoints = outputs[i][5:]

                # Calculate the scaled coordinates of the bounding box
                left = int((x - w / 2) * x_factor)
                top = int((y - h / 2) * y_factor)
                width = int(w * x_factor)
                height = int(h * y_factor)

                # Add the class ID, score, and box coordinates to the respective lists
                # class_ids.append(classes_id)
                scores.append(confidence)
                boxes.append([left, top, width, height])
                keypoints_list.append(keypoints)

        # Apply non-maximum suppression to filter out overlapping bounding boxes
        indices = cv2.dnn.NMSBoxes(boxes, scores, self.confidence_thres, self.iou_thres)

        # Iterate over the selected indices after non-maximum suppression
        for i in indices:
            # Get the box, score, and class ID corresponding to the index
            box = boxes[i]
            score = scores[i]
            # class_id = class_ids[i]
            keypoints = keypoints_list[i]

            # Draw the detection on the input image
            self.draw_detections(input_image, box, score, class_id=0)

            for i in range(0, len(keypoints), 3):
                x, y, conf = keypoints[i:i + 3]
                x = round(x * x_factor)
                y = round(y * y_factor)
                cv2.circle(input_image, (x, y), 5, (0, 255, 0), -1)

        # Return the modified input image
        return input_image
```

The conf is consistent at 0.3, and no specific modifications have been made to other parts.

1. I'd like to understand why there is a difference in the number of candidates between the two, considering that the same image was used.
2. What is the reason for the difference in the results?
3. Please provide detailed feedback or point out any issues beyond the previous questions.

**Comment by glenn-jocher** [comment]
@myeonghunkim00 hello! 👋 It seems you're experiencing a disparity in the detection results between your custom YOLOv8-pose model inference and the ONNX Runtime after exporting the model. Here's a brief explanation to address your concerns:

1. Candidate Discrepancy: This could be due to the difference in pre-processing steps or the model configuration when exporting to ONNX. Ensure that the input normalization and any resizing are consistent across both the native inference and ONNX Runtime.

2. Result Differences: The discrepancy in final detections post-NMS could be stemming from differences in the implementation or configuration of NMS between the two runtimes. Differences in confidence threshold parameters, despite being set the same, could behave differently in the ONNX framework.

3. Suggestions for Feedback: Double-check that all configurations match exactly between the two runtimes, and that the ONNX export is not changing any model dynamics or suppressing outputs unexpectedly. Also, verify the environment and dependency versions for consistency.

Don't hesitate to review the model's export parameters or peer into the NMS functions to ensure alignment. For further details, our documentation at https://docs.ultralytics.com can provide more insights into configuration and exporting. Keep exploring, and the YOLO community is here to support! 🚀

**Comment by gautamHCSCV** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> ### Question
> I trained a custom YOLOv8-pose model, generated an ONNX file from the trained best.pt file, and modified the postprocess function in the YOLOv8-ONNX Runtime example to apply the ONNX file.
> 
> I ran the YOLOv8-pose model's inference and YOLOv8 - ONNX Runtime on the same image using both the best.pt and best.onnx files.
> 
> In the postprocess function of the inference, the number of candidate predictions (preds) was initially 5040, but after passing through the non-maximum suppression (NMS), the final result yielded 20 predictions.
> 
> **This is the postprocess part of the YOLOv8-pose inference code.**
> 
> ```
>     def postprocess(self, preds, img, orig_imgs):
>         """Return detection results for a given input image or list of images."""
>         preds = ops.non_max_suppression(preds,
>                                         self.args.conf,
>                                         self.args.iou,
>                                         agnostic=self.args.agnostic_nms,
>                                         max_det=self.args.max_det,
>                                         classes=self.args.classes,
>                                         nc=len(self.model.names))
> 
>         if not isinstance(orig_imgs, list):  # input images are a torch.Tensor, not a list
>             orig_imgs = ops.convert_torch2numpy_batch(orig_imgs)
> 
>         results = []
>         for i, pred in enumerate(preds):
>             orig_img = orig_imgs[i]
>             pred[:, :4] = ops.scale_boxes(img.shape[2:], pred[:, :4], orig_img.shape).round()
>             pred_kpts = pred[:, 6:].view(len(pred), *self.model.kpt_shape) if len(pred) else pred[:, 6:]
>             pred_kpts = ops.scale_coords(img.shape[2:], pred_kpts, orig_img.shape)
>             img_path = self.batch[0][i]
>             results.append(
>                 Results(orig_img, path=img_path, names=self.model.names, boxes=pred[:, :6], keypoints=pred_kpts))
>         return results
> ```
> 
> In the ONNX Runtime, the number of candidates was initially 8400. After passing through the condition **if confidence >= self.confidence_thres:**, it reduced to 103. Following the non-maximum suppression (NMS), the final count became 14.
> 
> **This is the postprocess part of the YOLOv8-ONNX Runtime code.**
> 
> ```
>     def postprocess(self, input_image, output):
>         """
>         Performs post-processing on the model's output to extract bounding boxes, scores, and class IDs.
> 
>         Args:
>             input_image (numpy.ndarray): The input image.
>             output (numpy.ndarray): The output of the model.
> 
>         Returns:
>             numpy.ndarray: The input image with detections drawn on it.
>         """
> 
>         # Transpose and squeeze the output to match the expected shape
>         outputs = np.transpose(np.squeeze(output[0]))
>         # Get the number of rows in the outputs array
>         rows = outputs.shape[0]
> 
>         # Lists to store the bounding boxes, scores, and class IDs of the detections
>         boxes = []
>         scores = []
>         # class_ids = []
>         keypoints_list = []
> 
>         # Calculate the scaling factors for the bounding box coordinates
>         x_factor = self.img_width / self.input_width
>         y_factor = self.img_height / self.input_height
> 
>         # Iterate over each row in the outputs array
>         for i in range(rows):
> 
>             confidence = outputs[i][4]
> 
>             # If the maximum score is above the confidence threshold
>             if confidence >= self.confidence_thres:
>                 # Extract the class scores from the current row
>                 # classes_id = outputs[i][5:]
>                 # Extract the bounding box coordinates from the current row
>                 x, y, w, h = outputs[i][0], outputs[i][1], outputs[i][2], outputs[i][3]
> 
>                 keypoints = outputs[i][5:]
> 
>                 # Calculate the scaled coordinates of the bounding box
>                 left = int((x - w / 2) * x_factor)
>                 top = int((y - h / 2) * y_factor)
>                 width = int(w * x_factor)
>                 height = int(h * y_factor)
> 
>                 # Add the class ID, score, and box coordinates to the respective lists
>                 # class_ids.append(classes_id)
>                 scores.append(confidence)
>                 boxes.append([left, top, width, height])
>                 keypoints_list.append(keypoints)
> 
>         # Apply non-maximum suppression to filter out overlapping bounding boxes
>         indices = cv2.dnn.NMSBoxes(boxes, scores, self.confidence_thres, self.iou_thres)
> 
>         # Iterate over the selected indices after non-maximum suppression
>         for i in indices:
>             # Get the box, score, and class ID corresponding to the index
>             box = boxes[i]
>             score = scores[i]
>             # class_id = class_ids[i]
>             keypoints = keypoints_list[i]
> 
>             # Draw the detection on the input image
>             self.draw_detections(input_image, box, score, class_id=0)
> 
>             for i in range(0, len(keypoints), 3):
>                 x, y, conf = keypoints[i:i + 3]
>                 x = round(x * x_factor)
>                 y = round(y * y_factor)
>                 cv2.circle(input_image, (x, y), 5, (0, 255, 0), -1)
> 
>         # Return the modified input image
>         return input_image
> ```
> 
> The conf is consistent at 0.3, and no specific modifications have been made to other parts.
> 
> 1. I'd like to understand why there is a difference in the number of candidates between the two, considering that the same image was used.
> 2. What is the reason for the difference in the results?
> 3. Please provide detailed feedback or point out any issues beyond the previous questions.
> 
> ### Additional
> _No response_

Could you provide your entire code for the onnx pose model inference.

**Comment by glenn-jocher** [comment]
Hello @gautamHCSCV,

The difference in the number of candidate predictions between the YOLOv8-pose model inference and the ONNX Runtime could be due to variations in the preprocessing or postprocessing steps, or differences in the NMS implementation. Ensure that the input normalization, image scaling, and NMS configurations are consistent across both methods.

For a more detailed analysis, please ensure that all settings and model parameters are aligned and consider reviewing the ONNX export process. If the issue persists, you might want to delve into the ONNX model's intermediate outputs to check for discrepancies.

For further guidance, our documentation at https://docs.ultralytics.com can provide additional insights into the model's configuration and usage. Keep up the good work, and remember that the community is here to help! 🌟
