### ISSUE TITLE
How can I set threshold when inference segmentation with YOLOv8?

### ISSUE THREAD

**Issue by seon-creator** [ultralytics/ultralytics#6969]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

```
from ultralytics import YOLO

test_root = '/data/home/seondeok/Project/skin_spot/Tutorial/Test_img/Crop_images_2x2/Single 10/D10/'

# Load a model
model = YOLO('yolov8n-seg.pt')  # load an official model
model = YOLO('/data/home/seondeok/runs/segment/weight_train89_test10_1018/weights/best.pt')  # load a custom model

# Predict with the model
results = model(test_root, save=True, save_txt=True)  # predict on an image
```

This is my code that works with inference.
And I want to set threshold value 0.7. But I don't know how to set.
Any other method? or command?

**Comment by glenn-jocher** [comment]
@seon-creator hi there! 🌟

To set the confidence threshold for segmentation inference with YOLOv8, simply pass the `conf` parameter to your model call with the desired threshold value. Here's how you modify your existing code:

```python
# Set the confidence threshold to 0.7
results = model(test_root, conf=0.7, save=True, save_txt=True)
```

This tells the model to only consider detections with a confidence score of 0.7 or higher during inference. Enjoy working with YOLOv8 and happy experimenting with different threshold values! For more details on other parameters, feel free to check the [Segmentation documentation](https://docs.ultralytics.com/tasks/segment) on the Ultralytics Docs site. 😊

Keep forging ahead!

**Comment by Yuanchihwei** [comment]
@seon-creator 
Hi, Im beginner. I want to compare recall, precision, F1-score on different threshold of yolov7-seg, I would like to know how to change code in "train.py", could you please give me some direction, thank you so much.

**Comment by AISTALK** [comment]
@Yuanchihwei did you find the answer on how to choose best threshold?

**Comment by AISTALK** [comment]
@Yuanchihwei did you find the answer on how to choose best threshold?
