### ISSUE TITLE
Training error: qt.qpa.plugin: could not load the QT platform plugin "xcd"... even though it was found

### ISSUE THREAD

**Issue by mynobody** [ultralytics/ultralytics#697]
I got the following error during training

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/chiyl/anaconda3/envs/yolo/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**Comment by AyushExel** [comment]
Qt is a GUI toolkit for python. That is causing problems. It might be a dependency for cv2 based on the error although I'm not sure about that. Try reinstalling Qt plugin.

**Comment by glenn-jocher** [comment]
@mynobody should be resolved in PR #1078. Please re-open if this PR does not solve this for you, thank you!
