### ISSUE TITLE
yolov8 not working properly with .tflite 

### ISSUE THREAD

**Issue by aryan51k** [ultralytics/ultralytics#6984]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug
I am try to apply tracking on a .tflite file but the code is giving me the following error can you please help me out with this one. (The same code works properly with the .pt file its just not working with the .tflite file)

Also I checked out the ultralytics mobile application the detections are really quick can you please share what architecture do you use for this app. 

WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', or 'pose'.
Loading yolov8m.onnx for ONNX Runtime inference...
WARNING ⚠️ Metadata not found for 'model=yolov8m.onnx'

0: 640x640 2 class2s, 2 class7s, 424.3ms
Speed: 27.9ms preprocess, 424.3ms inference, 49.8ms postprocess per image at shape (1, 3, 640, 640)
Traceback (most recent call last):
  File "/Users/aryan/Desktop/Logicwind/Object-Counter/object_counter.py", line 25, in <module>
    im0 = counter.start_counting(im0, tracks)
  File "/Users/aryan/opt/anaconda3/envs/yolov8/lib/python3.9/site-packages/ultralytics/solutions/object_counter.py", line 165, in start_counting
    self.extract_and_process_tracks(tracks)
  File "/Users/aryan/opt/anaconda3/envs/yolov8/lib/python3.9/site-packages/ultralytics/solutions/object_counter.py", line 120, in extract_and_process_tracks
    self.annotator.box_label(box, label=self.names[cls], color=colors(int(cls), True))  # Draw bounding box
TypeError: 'NoneType' object is not subscriptable

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@aryan51k hi there,

For the issue regarding `.tflite` compatibility, YOLOv8's tracking functionality is optimized for `.pt` (PyTorch) files, as these contain necessary model architecture and weights metadata. Converting to `.tflite` can strip out some of this necessary information, and as such, tracking may not perform as expected. The error messages you're encountering hint at missing metadata, which is essential for model operation in different scenarios.

Regarding our mobile application's performance, we focus on optimizing models and inference processes for mobile deployment. We may use various techniques such as model quantization, pruning, and use of efficient architecture variants suitable for mobile environments. The specific methods are consistently iterated upon and improved as part of our commitment to delivering high-performance applications.

For in-depth guidance on model optimization and deployment, our documentation at https://docs.ultralytics.com might provide you with more insights — particularly the Export mode section on converting models to other formats and the Benchmark mode for assessing model performances.

Your enthusiasm is appreciated, and I encourage your continued engagement with the YOLOv8 community for the best possible outcomes with your projects! 🚀

**Comment by aryan51k** [comment]
@glenn-jocher 

Thanks for the response sorry I was occupied somewhere so I couldn't respond. 

I have gone through the code and have figured out what went wrong. So when we convert export the model to `.tflite` the `.tflite` version strips the names of classes so while running the script Nonetype object is found and that causes the problem. 

`counter.set_args(view_img=True,
                 reg_pts=region_points,
                 classes_names=model.names,
                 draw_tracks=True)`

In this part of script model.names returns None (Because I think its stripped out in `.tflite` conversion). But if you somehow provide it the proper dictionary it works properly. Can you or anyone from the team fix this so that everyone in the community can use existing script even if the model is exported to `.tflite`. 

Apart from this the tracking capability of YOLOv8 works just fine with `.tflite` as well. 

Thanks in advance please feel free to reach out.

**Comment by glenn-jocher** [comment]
@aryan51k, thanks for the follow-up and for diving into the issue. You are correct; when exporting to `.tflite`, class names may not be preserved which requires a manual fix. We'll take this into consideration for future updates to improve the user experience. 

In the meantime, your workaround of supplying the class names dictionary manually is the recommended approach when working with `.tflite` models.

We appreciate your input and are glad to hear tracking works well with `.tflite` once the names issue is resolved. Community insights like yours help us make YOLOv8 better for everyone. Thank you for contributing to the continued improvement! Keep experimenting and sharing your findings! 😊👍

**Comment by aryan51k** [comment]
@glenn-jocher Happy to help.

**Comment by glenn-jocher** [comment]
@aryan51k, thank you for your insight and for contributing to the improvement of the YOLOv8 community. Your willingness to explore and resolve such issues is invaluable. Happy coding! 😊🚀
