### ISSUE TITLE
What is the meaning of `np.size(prevPoints, 0) == np.size(prevPoints, 0)` in `applySparseOptFlow`

### ISSUE THREAD

**Issue by twotwoiscute** [ultralytics/ultralytics#6985]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

https://github.com/ultralytics/ultralytics/blob/765b98f44eb662c012e3470546bf95ea39345ee3/ultralytics/trackers/utils/gmc.py#L346

I do not see the reason for comparing two same things, Could anyone please explain ?

**Comment by Laughing-q** [comment]
@twotwoiscute that's a good question, actually most code in this file was copied from the bot-sort repo I think, so this line remains the same, but probably we should remove it as it looks meaningless
