### ISSUE TITLE
Openvino expoorts are broken with pose and non square images

### ISSUE THREAD

**Issue by Fireronin** [ultralytics/ultralytics#6993]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

I tried to export using

`model = YOLO(f'yolov8n-pose.pt')
model.export(format='openvino',imgsz=(480,480),half=False, int8=True,dynamic=False,data="coco-pose.yaml")
`
and I also tried
`model = YOLO(f'yolov8n.pt')
model.export(format='openvino',imgsz=(480,640),half=False, int8=True,dynamic=False,data="coco128.yaml")
`

Both fail one with issues regarding coco-pose.yaml outputs being incompatible with something in openvino 
second one produces [ GENERAL_ERROR ] Can't set input blob with name: images, because model input (shape=[1,3,480,640]) and blob (shape=(1.3.480.480)) are incompatible

### Environment

Ultralytics YOLOv8.0.227 🚀 Python-3.10.12 torch-2.1.1+cu121 CPU (Intel Core(TM) i9-9980HK 2.40GHz)
Setup complete ✅ (16 CPUs, 31.0 GB RAM, 114.2/456.9 GB disk)

### Minimal Reproducible Example

```
from ultralytics import YOLO
model = YOLO(f'yolov8n-pose.pt')
model.export(format='openvino',imgsz=(480,480),half=False, int8=True,dynamic=False,data="coco-pose.yaml")


model = YOLO(f'yolov8n.pt')
model.export(format='openvino',imgsz=(480,640),half=False, int8=True,dynamic=False,data="coco128.yaml")
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Fireronin thank you for bringing this to our attention, and apologies for the inconvenience you're experiencing. It seems that there might be a discrepancy between the expected input dimensions for OpenVino exports and the image size you're providing, especially when dealing with non-square images and specific tasks like pose/keypoint estimation. We will look into the compatibility issues between YOLOv8's pose estimation outputs and the OpenVino export process, as well as the mentioned shape mismatch error.

In the interim, please ensure you're using the latest version of YOLOv8 and check the Ultralytics Docs, specifically the Export mode section, for any notes on format compatibility and known issues. If possible, try exporting with default square image sizes and without the `int8` flag set, as quantization might complicate the export process.

We appreciate your patience and understanding as we work to resolve this. Meanwhile, keep an eye out for updates or fixes related to your issue in the repo's issues section. If you have further details that could aid our investigation, please feel free to share them. 🛠️
