### ISSUE TITLE
Training Yolov8 without zooming/cropping batch images 

### ISSUE THREAD

**Issue by dontfindavailablename** [ultralytics/ultralytics#6996]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello everyone!

I am working on a custom dataset with blurred images and very small objects to detect (20-40px large).

My goal is to detect these tiny objects and measure their size.

-> As images are blurred and objects tiny, I think it is bad that yolo zooms out training images to create a training batch. A zoomed out object looks like a simple white spot like many other non-object defects on the image.
-> Moreover, yolo crops certain training images to create this training batch. So a few objects are cutted and yolo learns to recognize cutted objects. But I want yolo to recognize only full objects, because the aim is to measure objects full size as.

=> How to I manage yolo to keep training images as they are? (no zoom, no crop to create training batches) 

Precisions:
Pictures were taken with a 64MP camera. I decided to continue with the images cropped to 224x224 px.
I annotated only full objects and painted non-full objects (i mean objects partially appearing on image borders for example). So images contain only full objects, annotated.

Note that images look very similar and objects to detect are quite similar (objects are 2D, always at the same distance, same color, almost the same shape but objects length can vary up to double from one to another).

I trained from scratch yolov8m 100 epochs on 30 images (224x224) for training and 30 images for validation (224x224 as well), only 1 object class to detect (about 500 annotations in the 60 images).

First results are already quite good (for the last epoch: box_loss   cls_loss   dfl_loss =  2.001     0.8558      1.232 respectively, mAP50 = 0.917), but containing big prediction mistakes on new images.

Dataset is small, it is the main reason for detection errors. But could detection errors be introduced by the way yolo creates batches to train: resizing and cropping randomly the training images?
Should I work with larger images?

Thank you very much for your advice!

**Comment by glenn-jocher** [comment]
@dontfindavailablename hello!

Thank you for your detailed question regarding training on images with tiny objects. 

To train YOLOv8 without zooming or cropping the batch images, you'll need to adjust your data-loading configuration. Specifically, you'll want to set the augmentation parameters related to scaling and cropping to ensure that your images are not modified during the batch creation process.

Ensure that your dataset is pre-processed to the input dimensions expected by the YOLOv8 model you're using. This will help bypass any automatic resizing or cropping operations. Additionally, you might want to experiment with different anchor box sizes that better match the scale of your small objects.

Considering your dataset consists of small and similar-looking objects, using a high-resolution input could help the model discern finer details, but this comes with the trade-off of increased computational overhead.

Finally, remember that a small dataset can lead to overfitting; gathering more diverse data and using various data augmentation techniques, excluding image zooming and cropping, could improve generalization.

Refer to our documentation on data loading and configuring augmentations for detailed instructions on how to customize these settings.

Good luck with your training! 🚀😊

**Comment by dontfindavailablename** [comment]
Thank you very much for your help!

1/ Reading the default.yaml file in the repository, i should just specify the following in my yaml file:
degrees: 0.0  # (float) image rotation (+/- deg)
translate: 0.0  # (float) image translation (+/- fraction)
scale: 0.0  # (float) image scale (+/- gain)
shear: 0.0  # (float) image shear (+/- deg)
perspective: 0.0  # (float) image perspective (+/- fraction), range 0-0.001
flipud: 0.4  # (float) image flip up-down (probability)
fliplr: 0.4  # (float) image flip left-right (probability)
mosaic: 1
mixup: 0

2/ What do you mean by "Ensure that your dataset is pre-processed to the input dimensions expected by the YOLOv8 model you're using." ?
I specify imgsz = 224
Isn't it enough?
Should I rather train with 640x640 images?

3/ For sure higher resolution would help. But this means investing in a optics, which is not currently the plan...

4/ Concerning anchor boxes, I still don't understand how we provide anchor boxes dimensions to yolo, or maybe yolo does create anchor boxes by itself?

Thank you for any further help!

**Comment by glenn-jocher** [comment]
@dontfindavailablename 1. If you want to disable certain augmentations, set those values in your YAML file as you've outlined. However, for 'mosaic,' use `mosaic: 0` if you wish to disable it as well.

2. The `imgsz` parameter specifies the input size for the model. If you set `imgsz = 224`, the model expects each image to be 224x224 pixels, so your images should be pre-processed to this size before training. Training with larger dimensions like 640x640 could potentially improve performance since it provides the model with more information, but it will also increase computational requirements.

3. Understood. Working with the available equipment often requires trade-offs in model performance and computational costs.

4. YOLOv8 will auto-learn anchor box dimensions during training suitable for your dataset. Manual specification of anchor boxes is typically not required unless you're optimizing for very specific use cases.

By following the guides provided in our documentation, you should be able to configure your training appropriately. Happy training!
