### ISSUE TITLE
Export ONNX with NMS

### ISSUE THREAD

**Issue by piotr-sikora-v** [ultralytics/ultralytics#6998]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Export with onnx NMS to other file.
i.e. filename-nms.onnx

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@piotr-sikora-v thank you for your feature request! Currently, YOLOv8 does not natively export models with NMS (Non-Max Suppression) integrated into the ONNX file. However, we appreciate you bringing this to our attention. The post-processing steps, like NMS, are usually handled separately after the detection output. We will consider this feature for future updates.

For more information on the existing export capabilities, please refer to the Export section of our documentation. If you have further questions or suggestions, feel free to discuss them here or contribute to the repo discussions. Your input is valuable to the Ultralytics community! 👍
