### ISSUE TITLE
show_labels and show_conf parameters to False, the labels and confidence scores are still being displayed.

### ISSUE THREAD

**Issue by ImSuMyatNoe** [ultralytics/ultralytics#7004]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I am encountering an issue while using the model.track function from the Ultralytics library. Despite explicitly setting the show_labels and show_conf parameters to False, the labels and confidence scores are still being displayed.

results = model.track(source=frame, tracker="botsort.yaml", persist=True, show_labels=False, show_conf=False)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@ImSuMyatNoe I tested with the same code but can't reproduce
```python
model = YOLO("yolov8n.pt")
results = model.track(source="/home/laughing/Videos/test_person.mp4", tracker="botsort.yaml", persist=True, show_labels=False, show_conf=False, save=True)
```
![pic-231215-1717-40](https://github.com/ultralytics/ultralytics/assets/61612323/b3d3f969-b12b-4ad5-b26c-f021703f156b)

**Comment by ImSuMyatNoe** [comment]
@Laughing-q  May be u are running in command line? I am running on the pycharm .py file. it is not possible.

**Comment by Laughing-q** [comment]
@ImSuMyatNoe I was running it by the code block in my last comment. 
Or maybe you could show me more your code, so I can try to reproduce the issue.

**Comment by ImSuMyatNoe** [comment]
from ultralytics import YOLO
import cv2
import os

# Load the YOLOv8n model with segmentation capability
model = YOLO('yolov8x-seg.pt')

# Set the input video source
video_path = "my_video.mp4"
video = cv2.VideoCapture(video_path)

# Define the output video filename
output_video_path = "my_video_output.mp4"

# Set the video writer parameters
fourcc = cv2.VideoWriter_fourcc(*"XVID")
fps = 30  # Set the desired output video frame rate
width = 1920  # Set the output video width (adjust according to your input video resolution)
height = 1080  # Set the output video height (adjust according to your input video resolution)

# Create the video writer object
video_writer = cv2.VideoWriter(output_video_path, fourcc, fps, (width, height))



frame_number = 0
while video.isOpened():
    success, frame = video.read()
    frame_number += 1
    if not success:
        break

    if success:
        results = model.track(source=frame, tracker="botsort.yaml", persist=True, show_labels=False, show_conf=False)

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Define the output frame filename with the folder path
        frame_filename = os.path.join('output/output_frames', f'frame_{frame_number:06d}.png')

        cv2.imwrite(frame_filename, annotated_frame)

        video_writer.write(annotated_frame)

video_writer.release()

Here is my .py file. When I run it this .py file from the command line this doesnot work. But when I only run this command "model = YOLO("yolov8n.pt")
results = model.track(source="/home/laughing/Videos/test_person.mp4", tracker="botsort.yaml", persist=True, show_labels=False, show_conf=False, save=True) from the command line, it works. I do not know what's the difference.

**Comment by Laughing-q** [comment]
@ImSuMyatNoe ok I see, setting `labels=False` in `results[0].plot()` should work in your case.
The arg `show_labels` is for the out-of-box usage on top-level which internally call `plot()` to draw images, you'll need to set args directly in `plot()` if you want to draw images by your own.
