### ISSUE TITLE
No value for confusion matrix (both confusion_matrix_normalized and confusion_matrix.png)

### ISSUE THREAD

**Issue by hariouat** [ultralytics/ultralytics#7005]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I have recently been training the YoloV8 model with my own dataset. Everything seems to run smoothly until the end of the execution, but I am facing an issue with the confusion matrices: although they should display results, they appear empty. Interestingly, the expected values are clearly visible in my command prompt at the end of the run.

Attached, you will find the configuration of my dataset and the outcomes obtained. Could you assist me in understanding why the confusion matrices are not populating as anticipated?

Thank you in advance for your attention to my request.

data.yaml 

![image](https://github.com/ultralytics/ultralytics/assets/117453280/209bac3a-f669-43e6-9e15-a0958d7b6779)

For the training 

![image](https://github.com/ultralytics/ultralytics/assets/117453280/70e593d0-0872-408c-80ab-5f412f4105ec)
After the training (the results in command line) 

<img width="612" alt="image" src="https://github.com/ultralytics/ultralytics/assets/117453280/65fd592b-dc7c-453e-8bde-1a1f2945be4a">

And the confusions matrix.

![confusion_matrix_normalized(3)](https://github.com/ultralytics/ultralytics/assets/117453280/67a4b814-0b46-4c91-be8c-a552a6ebf0f7)
![confusion_matrix](https://github.com/ultralytics/ultralytics/assets/117453280/b8516667-e50b-4a96-b788-4a80548d1e27)

**Comment by RizwanMunawar** [comment]
Thank you, @hariouat, for furnishing the comprehensive information. Could you kindly provide the confusion matrix for better support?

Thanks
Ultralytics Team!

**Comment by hariouat** [comment]
> Thank you, @hariouat, for furnishing the comprehensive information. Could you kindly provide the confusion matrix for better support?
> 
> Thanks Ultralytics Team!

Done

**Comment by RizwanMunawar** [comment]
@hariouat Can you please provide the 'confusion_matrix.png`?

Thanks
Ultralytics Team!

**Comment by RizwanMunawar** [comment]
@hariouat, the issue appears to be tied to your data splitting and annotation. Insufficient images are available for the `seed` and `root` classes.

Here are key points to address and potentially resolve the issue:
- The instances for `seed` and `root` are limited, with only 14 instances for seed and 128 instances for root. This is notably low compared to instances in other classes. Consider augmenting the size of images/annotations for each class.
- Your dataset exhibits significant imbalance, with the `leaf` class having substantially more instances than other classes, some of which aren't even half as numerous as the `leaf` class.
- Within your dataset, 745 images are designated as background and are not utilized in training. Verify the annotations for class IDs -1 in certain annotation files."

I hope this helps. If you have further questions or need clarification, feel free to ask.

Thanks
Ultralytics Team!

**Comment by hariouat** [comment]
> @hariouat, the issue appears to be tied to your data splitting and annotation. Insufficient images are available for the `seed` and `root` classes.
> 
> Here are key points to address and potentially resolve the issue:
> 
>     * The instances for `seed` and `root` are limited, with only 14 instances for seed and 128 instances for root. This is notably low compared to instances in other classes. Consider augmenting the size of images/annotations for each class.
> 
>     * Your dataset exhibits significant imbalance, with the `leaf` class having substantially more instances than other classes, some of which aren't even half as numerous as the `leaf` class.
> 
>     * Within your dataset, 745 images are designated as background and are not utilized in training. Verify the annotations for class IDs -1 in certain annotation files.
> 
> 
> I hope this helps. If you have further questions or need clarification, feel free to ask.
> 
> Thanks Ultralytics Team!

Thank you for your replay. 
Yes, i know for my umbalanced data; I checked all my dataset, and i can't detect the 745 images which are not used in the training. 

But i will try again. 
I have a question, why when i trained it with yolo V7, i obtained this confusion matrix. [
![confusion_matrix(2)](https://github.com/ultralytics/ultralytics/assets/117453280/1f52e19e-d499-406f-889c-ae57ad008700)
](url)

**Comment by hariouat** [comment]
> @hariouat, the issue appears to be tied to your data splitting and annotation. Insufficient images are available for the `seed` and `root` classes.
> 
> Here are key points to address and potentially resolve the issue:
> 
>     * The instances for `seed` and `root` are limited, with only 14 instances for seed and 128 instances for root. This is notably low compared to instances in other classes. Consider augmenting the size of images/annotations for each class.
> 
>     * Your dataset exhibits significant imbalance, with the `leaf` class having substantially more instances than other classes, some of which aren't even half as numerous as the `leaf` class.
> 
>     * Within your dataset, 745 images are designated as background and are not utilized in training. Verify the annotations for class IDs -1 in certain annotation files.
> 
> 
> I hope this helps. If you have further questions or need clarification, feel free to ask.
> 
> Thanks Ultralytics Team!

Thanks a lot for your reply. I updated Ultralytics and everything is working now, thank you.

**Comment by RizwanMunawar** [comment]
Alright, excellent! I'm marking this issue as closed. Please don't hesitate to reopen it if the issue persists.

Thanks
Ultralytics Team!

**Comment by Jordan-Pierce** [comment]
@RizwanMunawar I'm seeing a similar issue, but no values are provided (in non- / normalized matrices). However, I'm seeing values as I would expect in other datasets (the same, just subsampled). Is there a cut-off such that if there are too many samples, values in the matrix are displayed?
