### ISSUE TITLE
Prediction using  CLI is not taking pre-loaded model and everytime loaded.

### ISSUE THREAD

**Issue by kajal1598** [ultralytics/ultralytics#7009]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

       model = YOLO(os.path.join(os.getcwd(), 'yolov8n.pt'))
        
        os.system(f"yolo detect predict source={os.path.join(imagePath,i)} model={model} device=0 save_conf=True conf=0.7 project={os.path.join(mainPath, 'runs', 'detect')} name=new save_txt=True")

so this throws the error
`yolo detect predict source=/images model=YOLO(`

and If I used 

     os.system(f"yolo detect predict source={os.path.join(imagePath,i)} model=yolov8n.pt device=0 save_conf=True conf=0.7 project={os.path.join(mainPath, 'runs', 'detect')} name=new save_txt=True")
     
    it loaded model every time

**Comment by RizwanMunawar** [comment]
@kajal1598, Thanks for sharing the details! Indeed, you're correct; initializing the model just once via the CLI can not be possible. However, if you prefer, you can achieve a single model initialization using the Python code provided below.

```python
import os
from ultralytics import YOLO
model = YOLO("yolov8n.pt")

img_folder = "ultralytics"
project=f"{os.path.join('runs', 'detect')}"

for i in os.listdir(img_folder):
    results = model.predict(source=f"{os.path.join(img_folder, i)}",
                            device=0, save_conf=True, conf=0.7,
                            project=project, exist_ok=True,
                            name="new", save_txt=True)

```

Hope this helps! Let me know if you have any additional questions.

Thanks and Regards
Ultralytics Team!

**Comment by kajal1598** [comment]
Got it & Thanks for the response in short time.

**Comment by glenn-jocher** [comment]
@kajal1598 you're welcome! If you have more questions in the future, feel free to ask. 😊👍 

– Ultralytics Team
