### ISSUE TITLE
How to change the predict bbox color and thickness?

### ISSUE THREAD

**Issue by wenjunx** [ultralytics/ultralytics#701]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want change the predict output color in the predict.py.But it didn't work!
![QQ截图20230129172300](https://user-images.githubusercontent.com/83592255/215317125-96f23d12-c690-4714-bfd2-8690aac336cb.png)

### Additional

the command yolo cfg=ultralytics/yolo/cfg/predict.yaml

**Comment by Laughing-q** [comment]
@wenjunx perhaps you missed the correct file? let's say if you're going to modify the color of detection then you have to go [https://github.com/ultralytics/ultralytics/blob/aecd17d455d71dab12069e4b5aa2ffad4b9b94fe/ultralytics/yolo/v8/detect/predict.py#L74](https://github.com/ultralytics/ultralytics/blob/aecd17d455d71dab12069e4b5aa2ffad4b9b94fe/ultralytics/yolo/v8/detect/predict.py#L74).
I tried to modify the color this way and it works to me:
![image](https://user-images.githubusercontent.com/61612323/215375550-ffadbf87-50e6-4487-b7b4-fd1581353720.png)
![bus](https://user-images.githubusercontent.com/61612323/215375834-540ade75-29f4-4499-9c43-67e201f2cb1c.jpg)

**Comment by wenjunx** [comment]
@Laughing-q Yes, I changed it under this file.
![QQ截图20230130152717](https://user-images.githubusercontent.com/83592255/215413871-58c449a9-dcd5-4c14-97da-a7af09fad5aa.png)
but it didn't work. Is it caused by running the command？The running command I use is **yolo cfg=ultralytics/yolo/cfg/predict.yaml**

**Comment by Laughing-q** [comment]
@wenjunx this is my test command:
```bash
yolo detect predict model=weights/yolov8n.pt
```
can you try this? alsoI think probably the file you've modified is not the package file you're using.

**Comment by wenjunx** [comment]
@Laughing-q thank you! It is ultralytics package problem. I uninstall ultralytics and replace command with 
![QQ截图20230130172535](https://user-images.githubusercontent.com/83592255/215438095-48541d5d-f9cd-4cb0-9eff-891a0251eaae.png)
and it work!
