### ISSUE TITLE
Failed to export .pt to .engine file

### ISSUE THREAD

**Issue by DA-II** [ultralytics/ultralytics#7016]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I trained a YOLOv8s network and wanted to convert it into a TensorRT structure, but it always restarts the terminal halfway through without generating any new files. Therefore, after failing in Visual Studio Code, I used Spyder to print the running results, which are as follows:

Windows fatal exception: access violation
Main thread:
Current thread 0x00004eb0 (most recent call first):
  File "D:\anaconda3\envs\yolo8\Lib\site-packages\torch\onnx\utils.py", line 1015 in _create_jit_graph
  File "D:\anaconda3\envs\yolo8\Lib\site-packages\torch\onnx\utils.py", line 1135 in _model_to_graph
  File "D:\anaconda3\envs\yolo8\Lib\site-packages\torch\onnx\utils.py", line 1596 in _export
  File "D:\anaconda3\envs\yolo8\Lib\site-packages\torch\onnx\utils.py", line 516 in export
  File "D:\anaconda3\envs\yolo8\Lib\site-packages\ultralytics\engine\exporter.py", line 335 in export_onnx
  File "D:\anaconda3\envs\yolo8\Lib\site-packages\ultralytics\engine\exporter.py", line 117 in outer_func
  File "D:\anaconda3\envs\yolo8\Lib\site-packages\ultralytics\engine\exporter.py", line 588 in export_engine
  File "D:\anaconda3\envs\yolo8\Lib\site-packages\ultralytics\engine\exporter.py", line 117 in outer_func
  File "D:\anaconda3\envs\yolo8\Lib\site-packages\ultralytics\engine\exporter.py", line 254 in __call__
  File "D:\anaconda3\envs\yolo8\Lib\site-packages\torch\utils\_contextlib.py", line 115 in decorate_context
  File "D:\anaconda3\envs\yolo8\Lib\site-packages\ultralytics\engine\model.py", line 310 in export
  File "d:\codes\yolo_apex\export.py", line 8 in <module>
  File "D:\anaconda3\envs\yolo8\Lib\site-packages\spyder_kernels\py3compat.py", line 356 in compat_exec
  File "D:\anaconda3\envs\yolo8\Lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 473 in exec_code
  File "D:\anaconda3\envs\yolo8\Lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 615 in _exec_file
  File "D:\anaconda3\envs\yolo8\Lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 528 in runfile
  File "D:\tempfiles\ipykernel_26744\3764267875.py", line 1 in <module>

Restarting kernel...

![image](https://github.com/ultralytics/ultralytics/assets/52708877/8412312a-e7eb-47e5-9a64-2306678d0a8a)

### Environment

"My computer is equipped with 32GB of memory, a GTX 4070 Ti graphics card（with 12G memory）, and an i7 12700k CPU. The CUDA version is 12.3. I tried both Python 3.9 and Python 3.11, but encountered the same problem. It's worth noting that after installing the requirements listed in the documentation and Ultralytics, I had to manually install PyTorch (since the requirements installed the CPU version). I used pip commands to install ONNX, TensorRT, ONNX Runtime-GPU, and ONNXSIM.
Here is the list of requirements after my installation:
[requirements.txt](https://github.com/ultralytics/ultralytics/files/13688487/requirements.txt)

### Minimal Reproducible Example

from ultralytics import YOLO

model = YOLO('bests.pt')

# Train the model
model.export(format='engine')

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by DA-II** [comment]
it seems like https://github.com/ultralytics/ultralytics/issues/6861    i cloud export .onnx file,  but can not export an .engine flie

**Comment by DA-II** [comment]
when i followed https://github.com/ultralytics/ultralytics/issues/6861 and use TensorRT-8.6.1.6 trtexec to build engine. the problem occured 
![image](https://github.com/ultralytics/ultralytics/assets/52708877/b87e32c0-6b05-41dc-bae8-12d9b2e3f097) which is just like https://github.com/ultralytics/ultralytics/issues/1225  and i dont know how to repair it

**Comment by glenn-jocher** [comment]
@DA-II i'm sorry to hear you're experiencing issues while exporting to a `.engine` file. The `access violation` error along with the restarts you're experiencing could imply a memory issue or an environment setup problem. 

Please ensure that the CUDA version you have is compatible with the PyTorch and TensorRT versions installed on your system. Mismatches between these dependencies can sometimes lead to unexpected behavior. 

Additionally, consider simplifying the process by using a dedicated environment for YOLOv8 which has only the necessary packages installed as the heavy list of requirements might introduce some conflicts. 

As for the issue with TensorRT-8.6.1.6 trtexec indicated in the second post, it's critical to make sure the ONNX model is properly exported and compatible with TensorRT. Review the recommended TensorRT practices as per the documentation and ensure that there are no unsupported layers or operations. 

If you refine your setup and you're still facing difficulties, please provide us with the minimal code, error logs, and environmental setup for further investigation. For more in-depth troubleshooting, you may consider visiting our docs page on export mode and ensuring each step is methodically followed.

Keep in mind to regularly pull the latest commits from our repository, as updates may have resolved previously encountered issues.

**Comment by DA-II** [comment]
I have set up a dedicated virtual environment for yolo, and my cuda version is compatible with pytorch and tensorrt versions. I have provided my environment settings in the requirements.txt above. My test code is as follows:

from ultralytics import YOLO
model = YOLO('bests.pt')
model.export(format='engine')

and

from ultralytics import YOLO
model = YOLO('bests.engine').predict(device=0)

**Comment by DA-II** [comment]
@glenn-jocher Can you tell me your tensor RT version? I was able to successfully export the onnx file but could not export the engine file through the official website and the .engine exported through trtexec was unavailable. i want to try and fix it by reloading tensor RT

**Comment by glenn-jocher** [comment]
@DA-II i'm glad to hear that you were able to export the ONNX file successfully. As for the TensorRT version, it's crucial to match it with your PyTorch and CUDA versions. I recommend checking our documentation to ensure your setup meets the requirements for compatibility. Remember that the latest documentation will provide guidance on supported versions and any additional steps you may need to take during the export process. If after aligning your versions you still experience issues, consider revisiting the docs for export mode, and make sure to stay updated with the latest commits from our repository for any fixes or improvements that might help resolve your issue.
