### ISSUE TITLE
YOLOv8 tracking with servo using mouse click to select object

### ISSUE THREAD

**Issue by freestuffasd** [ultralytics/ultralytics#7021]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

my yolov8 tracking with servo takes class and id to track particular object using bounding box centre but i want to track only that object tracked with tracker on which i click and i can switch objects to track with another click .
                        bbox_left = output[0]
                        bbox_top = output[1]
                        bbox_w = output[2] - output[0]
                        bbox_h = output[3] - output[1]

                        print(f"cls : {cls}, id : {id}")
                        if(names[int(cls)] == "cat" and id == 1):

                            c_x = bbox_left + int(bbox_w/2)
                            c_y = bbox_top + int(bbox_h/2)

**Comment by glenn-jocher** [comment]
@freestuffasd hello! It seems like you're interested in implementing a feature that allows you to manually select an object for tracking purposes using a mouse click, and also have the flexibility to switch the target object with another click.

In YOLOv8's tracking mode, object tracking is automated, and it doesn't natively support manual selection of objects to track. For custom functionality like interactive object selection, you will need to integrate additional code that handles mouse events and updates the tracker with the coordinates of the selected object.

Your implementation would need to include:
1. A mouse event listener to capture the coordinates of the mouse click.
2. Logic to determine which object's bounding box contains the click coordinates.
3. Updating the tracking mechanism to follow the selected object based on its unique identifier (ID).

Feel free to refer to the docs for a deeper understanding of YOLOv8's capabilities and how to work with the tracking mode. Keep exploring and good luck with your project! 👍🔍
