### ISSUE TITLE
How does YOLOv8 tracker assign new ID numbers?

### ISSUE THREAD

**Issue by omar-abdelgawad** [ultralytics/ultralytics#7028]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am using YOLOv8-pose model with tracker for a project and I wanted to understand how does it assign new ID numbers to tracked objects. My original assumption was that It increments the ID counter everytime it "finds" a new object but that didn't happen as the output video skipped A LOT of IDs. Does it maybe skip ID based on the length of the video?

Here is an image of some folders that is basically the output of the track_history_dict. I have watched the video output and it did really skip all of those IDs.
![image](https://github.com/ultralytics/ultralytics/assets/113486195/a5260d42-4136-40f6-a8fe-600fdfc09168)

### Additional

I'd be happy to clarify any question regarding this topic and perhaps provide images of my project's output that shows this ID skipping.

**Comment by glenn-jocher** [comment]
@omar-abdelgawad yOLOv8's tracker assigns new ID numbers based on the first available unique identifier that is not currently assigned to any existing, visible, or recently seen objects. It doesn't simply increment IDs for each new detection. IDs may be skipped for various reasons, such as objects that were detected but then quickly lost, or due to filtering mechanisms that may disregard certain detections deemed unreliable. The ID assignment process is designed to minimize ID switches and track object identities consistently. If you find the ID assignment behavior does not meet your expectations, consider exploring the tracking hyperparameters and object detection thresholds as tuning these may improve tracking robustness. 👁️🔍🔄

**Comment by omar-abdelgawad** [comment]
I am kind of confused!. How does skipping IDs help with anything :confused:. If I understood you correctly some IDs may pop on the output but then may get lost quickly (may be due to weak detection of that specific object) but that is not what is happening with me. Some IDs JUST DON"T APPEAR AT ALL. This seems really confusing as I don't see how skipping an ID without even assigning it to something first could make a difference. Of course, I don't know how the filtering mechanisms you mentioned work so I may be wrong after all. I just want your confirmation that some IDs get entirely skipped without ever appearing in the output tensors. If that is true then I got my answer. Thanks in advance :smile:

**Comment by glenn-jocher** [comment]
@omar-abdelgawad indeed, some IDs might get entirely skipped without appearing in your output. This usually stems from the tracker's internal mechanisms filtering out detections it considers spurious or insufficiently confident before they are ever assigned an ID. It's aimed at ensuring that only objects detected with a strong confidence level are tracked, which helps maintain clean and reliable track histories. 😌👍

**Comment by MrWei282** [comment]
A bit late but one possible contributing reason is that you have changed "vid_stride" to values other than 1 and this become quite common, from my uses it rarely skip id unless I have put vid_stride to like 10 or sth.

**Comment by glenn-jocher** [comment]
@MrWei282 That's a good point! Adjusting the `vid_stride` parameter can indeed result in skipped IDs, as it changes the frequency at which frames are processed for tracking. A higher `vid_stride` value means fewer frames are evaluated, potentially leading to less continuity in ID assignment. Keeping `vid_stride` at 1 ensures all frames are considered, which can help with maintaining sequential ID assignments. 😊👍
