### ISSUE TITLE
bouding box coordinates label wise

### ISSUE THREAD

**Issue by Sairahul07-25** [ultralytics/ultralytics#7031]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to save the coordinates of the bounding boxes separated by labels
![how](https://github.com/ultralytics/ultralytics/assets/98158320/45fd5ac5-fe39-447a-91d6-8b2b10c30760)

**Comment by glenn-jocher** [comment]
@Sairahul07-25 to save the coordinates of the bounding boxes separately for each label after running inference with YOLOv8, you can utilize the output of the `Predict` mode, which includes both bounding box coordinates and class labels. After the model makes predictions on your images, the results are typically stored in a data structure that contains this information. By iterating over the predictions, you can filter and save the bounding box coordinates based on the associated class labels according to your requirements. The specifics of accessing and handling this data are covered in our documentation, particularly in the section pertaining to predictions. Please refer to the Predict mode documentation on our Ultralytics Docs page for additional details.

**Comment by Sairahul07-25** [comment]
Thanks a lot man

**Comment by glenn-jocher** [comment]
@Sairahul07-25 you're welcome! If you have any more questions or need further assistance, don't hesitate to reach out. Happy detecting! 😊🚀
