### ISSUE TITLE
'str' object has no attribute 'train'

### ISSUE THREAD

**Issue by xN1ckuz** [ultralytics/ultralytics#7035]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Hello, my code was working 9 months ago, now if i go to run it it doesnt work.

I load my model like that:

```
from ultralytics import YOLO

epochs = 300 #@param {type:"slider", min:100, max:1000, step:10}
training_option = "Train new CNN" #@param ["Train new CNN", "Resume an interrupted Training"]
weight = 'yolov8m.pt' #@param["yolov8n.pt","yolov8s.pt","yolov8m.pt","yolov8l.pt", "yolov8x"]
batch = 32 #@param {type:"slider", min:1, max:64, step:1}

model = YOLO(weight)
data =  "/content/gdrive/MyDrive/"+folder+"/training/training_dataset/data.yaml"
project = "/content/gdrive/MyDrive/"+folder+"/training/training_results/"
model = "/content/gdrive/MyDrive/"+folder+"/training/training_results/train/weights/last.pt"
```
But at this point model is a type string. So when i do that: 

```
if training_option == 'Train new CNN':
  model.train(data=data, epochs=epochs, imgsz=512, batch=batch, cache=True, patience=50, project=project)
else:
  model.train(data=data, epochs=epochs, imgsz=512, batch=batch, cache=True, patience=50, project=project, resume=True, model=model)
```
it gaves me `AttributeError: 'str' object has no attribute 'train'`

So the code was working before in this enironment:
Ultralytics YOLOv8.0.53 🚀 Python-3.9.16 torch-1.13.1+cu116 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 25.5/78.2 GB disk)

BTW i install YOLOv8 like that:
```
%pip install ultralytics
import ultralytics
ultralytics.checks()
```

### Environment

Ultralytics YOLOv8.0.227 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 26.3/78.2 GB disk)

Colab Environment

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by willyfh** [comment]
@xN1ckuz  Hi, it seems that you are assigning a string to the variable `model` after initializing it as a YOLO model. This might be causing the AttributeError. 
```
model = "/content/gdrive/MyDrive/"+folder+"/training/training_results/train/weights/last.pt"
```

**Comment by xN1ckuz** [comment]
> @xN1ckuz Hi, it seems that you are assigning a string to the variable `model` after initializing it as a YOLO model. This might be causing the AttributeError.
> 
> ```
> model = "/content/gdrive/MyDrive/"+folder+"/training/training_results/train/weights/last.pt"
> ```

Yeah i found it last week! I must have been careless in renaming the variables before publishing everything. Cheers and merry christmas!

**Comment by glenn-jocher** [comment]
@xN1ckuz Great to hear you found the solution! Variable naming can indeed be a tricky business. Happy coding and merry Christmas to you too! 🎄✨ If you have any more questions or need further assistance down the line, feel free to reach out. Cheers! 🚀
