### ISSUE TITLE
YOLOv8 pose training on COCO keypoint dataset is having error

### ISSUE THREAD

**Issue by AndywithCV** [ultralytics/ultralytics#7036]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello team,
I want to train a custom model on COCO-keypoints for human pose estimation, I got the error as below: 
![image](https://github.com/ultralytics/ultralytics/assets/94813960/1ae692e0-856b-4f39-82a7-3dba352ab5db)
train: WARNING ▒▒ /root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581789.jpg: ignoring corrupt image/label: [Errno 2] No such file or directory: '/root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581789.jpg'
train: WARNING ▒▒ /root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581795.jpg: ignoring corrupt image/label: [Errno 2] No such file or directory: '/root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581795.jpg'
train: WARNING ▒▒ /root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581827.jpg: ignoring corrupt image/label: [Errno 2] No such file or directory: '/root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581827.jpg'
train: WARNING ▒▒ /root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581831.jpg: ignoring corrupt image/label: [Errno 2] No such file or directory: '/root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581831.jpg'
train: WARNING ▒▒ /root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581839.jpg: ignoring corrupt image/label: [Errno 2] No such file or directory: '/root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581839.jpg'
train: WARNING ▒▒ /root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581857.jpg: ignoring corrupt image/label: [Errno 2] No such file or directory: '/root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581857.jpg'
train: WARNING ▒▒ /root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581860.jpg: ignoring corrupt image/label: [Errno 2] No such file or directory: '/root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581860.jpg'
train: WARNING ▒▒ /root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581880.jpg: ignoring corrupt image/label: [Errno 2] No such file or directory: '/root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581880.jpg'
train: WARNING ▒▒ /root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581881.jpg: ignoring corrupt image/label: [Errno 2] No such file or directory: '/root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581881.jpg'
train: WARNING ▒▒ /root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581886.jpg: ignoring corrupt image/label: [Errno 2] No such file or directory: '/root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581886.jpg'
train: WARNING ▒▒ /root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581887.jpg: ignoring corrupt image/label: [Errno 2] No such file or directory: '/root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581887.jpg'
train: WARNING ▒▒ /root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581899.jpg: ignoring corrupt image/label: [Errno 2] No such file or directory: '/root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581899.jpg'
train: WARNING ▒▒ /root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581900.jpg: ignoring corrupt image/label: [Errno 2] No such file or directory: '/root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581900.jpg'
train: WARNING ▒▒ /root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581904.jpg: ignoring corrupt image/label: [Errno 2] No such file or directory: '/root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581904.jpg'
train: WARNING ▒▒ /root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581921.jpg: ignoring corrupt image/label: [Errno 2] No such file or directory: '/root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/images/train2017/000000581921.jpg'
WARNING ▒▒ No images found in /root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/labels/train2017.cache, training may not work correctly. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
Traceback (most recent call last):
  File "main_pose.py", line 12, in <module>
    results = model.train(data= "/root/data/andy/newyolov8/ultralytics/ultralytics/cfg/coco-pose/coco-pose.yaml", epochs = 50, device = 0)
  File "/root/data/andy/newyolov8/ultralytics/ultralytics/engine/model.py", line 334, in train
    self.trainer.train()
  File "/root/data/andy/newyolov8/ultralytics/ultralytics/engine/trainer.py", line 195, in train
    self._do_train(world_size)
  File "/root/data/andy/newyolov8/ultralytics/ultralytics/engine/trainer.py", line 293, in _do_train
    self._setup_train(world_size)
  File "/root/data/andy/newyolov8/ultralytics/ultralytics/engine/trainer.py", line 258, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
  File "/root/data/andy/newyolov8/ultralytics/ultralytics/models/yolo/detect/train.py", line 46, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode, batch_size)
  File "/root/data/andy/newyolov8/ultralytics/ultralytics/models/yolo/detect/train.py", line 40, in build_dataset
    return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == 'val', stride=gs)
  File "/root/data/andy/newyolov8/ultralytics/ultralytics/data/build.py", line 74, in build_yolo_dataset
    return YOLODataset(
  File "/root/data/andy/newyolov8/ultralytics/ultralytics/data/dataset.py", line 40, in __init__
    super().__init__(*args, **kwargs)
  File "/root/data/andy/newyolov8/ultralytics/ultralytics/data/base.py", line 72, in __init__
    self.labels = self.get_labels()
  File "/root/data/andy/newyolov8/ultralytics/ultralytics/data/dataset.py", line 122, in get_labels
    len_cls, len_boxes, len_segments = (sum(x) for x in zip(*lengths))
ValueError: not enough values to unpack (expected 3, got 0)

I have use coco-pose.yaml dataset by default provided by the repo, it uses all labels in one txt file but not seperate txt file as usual: 
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco-pose  # dataset root dir
train: train2017.txt  # train images (relative to 'path') 118287 images
val: val2017.txt  # val images (relative to 'path') 5000 images
test: test-dev2017.txt  # 20288 of 40670 images, submit to https://competitions.codalab.org/competitions/20794

# Keypoints
kpt_shape: [17, 3]  # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)
flip_idx: [0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15]

# Classes
names:
  0: person

Can you help elaborate on the problem and what should I do with it? Thank you so much!

**Comment by xbkaishui** [comment]
I have the same issue too. use the main branch

**Comment by xbkaishui** [comment]
yolo task=pose mode=train data=tiger-pose.yaml model=yolov8n-pose.pt epochs=100 imgsz=640

**Comment by glenn-jocher** [comment]
@xbkaishui to begin training a YOLOv8 model for pose estimation on your custom dataset, ensure that your YAML file is correctly formatted and reflects the specifics of your dataset (i.e., `tiger-pose.yaml`). The file should define the path to your images and labels, the number and dimensions of keypoints, and class names if applicable.

Set your task to `pose`, mode to `train`, and specify the data file, model checkpoint, number of epochs, and input image size according to your needs. If you encounter any issues, please refer to the Pose/Keypoint Estimation documentation for guidance, and verify that your dataset is organized as expected by YOLOv8 for the pose estimation task. If problems persist, you can reach out with specific error messages for further assistance. 🚀

**Comment by AndywithCV** [comment]
@glenn-jocher please help me with the error in my post, I am training my custom model on COCO keypoint dataset, but not custom dataset, i am using default coco-pose.yaml....

**Comment by glenn-jocher** [comment]
@AndywithCV hi there! It appears that there might be an issue with the file paths or the dataset integrity. Make sure that the image files and corresponding label files exist at the specified paths in your `coco-pose.yaml`. Also, verify your dataset cache file to ascertain it's not corrupted. If necessary, delete the cache file to force a rebuild upon the next training attempt.

For pose estimation, remember to use the appropriate YAML configuration file that matches the structure of a keypoint dataset. It is crucial for the `kpt_shape` and `names` fields to reflect your own dataset properties. If you continue to face issues, take a look at our Pose/Keypoint Estimation documentation for detailed guidance on setting up your dataset correctly. 😊

If the problem persists after these checks, please provide any additional error messages you receive after the dataset verification. This will help narrow down the potential causes.
