### ISSUE TITLE
MPS is now supporting slice with Pytorch 2.1.2

### ISSUE THREAD

**Issue by johnnynunez** [ultralytics/ultralytics#7046]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Related with this bug https://github.com/ultralytics/ultralytics/pull/6694
Pytorch release: https://github.com/pytorch/pytorch/releases/tag/v2.1.2

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@johnnynunez that's great news that MPS supports slice with PyTorch 2.1.2 now! This update may help us resolve that bug in our repo more efficiently. I'll bring this to the attention of the team, and we'll look into incorporating this improvement in a future release. Thank you for sharing this information with us, it's greatly appreciated! Keep an eye on our repo for updates. If there's anything else you come across that might enhance YOLOv8, feel free to let us know 😊.
