### ISSUE TITLE
Does Yolov8 export tflite will support the org-tensorflow-lite-tensorflow-lite.gpu&org-tensorflow-lite-tensorflow-lite-task-vision in android?

### ISSUE THREAD

**Issue by NakiriYuuzu** [ultralytics/ultralytics#7047]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When export tflite file and test on the code, will get the error:
Error occurred when initializing ObjectDetector: Input tensor has type kTfLiteFloat32: it requires specifying NormalizationOptions metadata to preprocess input images.

After I fixed the issue, now getting another problem is:
error occurred when initializing objectdetector: mobile ssd models are expected to have exactly 4 outputs, found 1

TFLite Model: (1, 640, 640, 3), (1,7,8400)
export command:
yolo task=detect mode=export model=runs/detect/train5/weights/best.pt format=tflite int8=True

![image](https://github.com/ultralytics/ultralytics/assets/72718339/a39e9474-cf23-48a7-ac93-2c34c33c1fda)

![image](https://github.com/ultralytics/ultralytics/assets/72718339/031a95ca-bd05-49b9-a0d6-08429bdf645b)

```kotlin
import android.content.Context
import android.graphics.Bitmap
import android.util.Log
import net.yuuzu.plasticdetection.domain.Classification
import net.yuuzu.plasticdetection.domain.ObjectDetectionClassifier
import org.tensorflow.lite.support.image.ImageProcessor
import org.tensorflow.lite.support.image.TensorImage
import org.tensorflow.lite.support.image.ops.Rot90Op
import org.tensorflow.lite.task.core.BaseOptions
import org.tensorflow.lite.task.vision.detector.ObjectDetector

class TfliteObjectDetectionClassifier(
    private val context: Context,
    private val threshold: Float = 0.5f,
    private val numThreads: Int = 2,
    private val maxResults: Int = 3
): ObjectDetectionClassifier {
    private var objectDetector: ObjectDetector? = null

    init {
        setupObjectDetector()
    }

    private fun setupObjectDetector(model: String = "model.tflite") {
        val baseOptions = BaseOptions.builder()
            .setNumThreads(numThreads)
            .build()

        val options = ObjectDetector.ObjectDetectorOptions.builder()
            .setBaseOptions(baseOptions)
            .setScoreThreshold(threshold)
            .setMaxResults(maxResults)
            .build()

        try {
            objectDetector = ObjectDetector.createFromFileAndOptions(context, model, options)
        } catch (e: IllegalStateException) {
            e.printStackTrace()
            Log.e("Yuuzu", "setupObjectDetector: ${e.message}")
        }
    }

    override fun detect(bitmap: Bitmap, rotation: Int): List<Classification> {
        if (objectDetector == null) {
            setupObjectDetector()
        }

        val imageProcessor = ImageProcessor.Builder().add(Rot90Op(-rotation / 90)).build()
        val tensorImage = imageProcessor.process(TensorImage.fromBitmap(bitmap))

        val results = objectDetector?.detect(tensorImage)

        return results?.flatMap { classifications ->
            classifications.categories.map { category ->
                Classification(
                    label = category.label,
                    displayName = category.displayName,
                    score = category.score,
                    box = classifications.boundingBox
                )
            }
        }?.distinctBy { it.label } ?: emptyList()
    }
}
```

**Comment by glenn-jocher** [comment]
@NakiriYuuzu it seems you're facing compatibility issues with TensorFlow Lite's expectations for the exported YOLO model. YOLOv8 models have a different output tensor structure than the SSD models TensorFlow Lite (TFLite) expects, which is why you're seeing messages about the number of outputs.

For the first issue, where the `NormalizationOptions` metadata was missing, YOLOv8 `.tflite` exports indeed may not include this metadata, so you've correctly identified that you'd need to implement the preprocessing steps manually or add the necessary metadata to the exported model.

Regarding the second issue, since YOLO models don't conform to the SSD output format by default, you won't be able to use them directly with the higher-level TensorFlow Lite Task Library APIs (`org-tensorflow-lite-tensorflow-lite-task-vision`) without modification. The Task Library expects a certain structure as it's designed for plug-and-play simplicity with models following specific patterns.

To resolve this, consider writing your own custom object detection logic to handle YOLOv8's output tensors, or alternatively, find a conversion process that adapts the YOLO model output to the SSD format expected by TensorFlow Lite's Task Library.

For more details on these processes, refer to the Export section of our documentation. Our team and the broader community continue to refine export support, so we appreciate your feedback and any contributions or insights you wish to share on these matters. 

Good luck with your implementation! 👍

**Comment by NakiriYuuzu** [comment]
Thank you for giving me direction

**Comment by glenn-jocher** [comment]
@NakiriYuuzu you're welcome! If you have any further questions or need assistance, feel free to reach out. I'm glad to help. Happy coding! 😊

**Comment by lImFsheng** [comment]
Hi @NakiriYuuzu , I'm also encountering the same issue. May I ask if you have found any solutions for it?

**Comment by brian-mortimer** [comment]
Hi @NakiriYuuzu and @lImFsheng , I have also encountered the same issue. Have either of you found a solution to this? Currently I am looking into using Onnx Runtime as a possilbe solution,  here is a link to a sample app I found using a YOLOv8 model [https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/object_detection/android](link).

**Comment by NakiriYuuzu** [comment]
I using the tensorflow keras to train the model

Brian Mortimer ***@***.***>於 2024年1月23日 週二，18:54寫道：

**Comment by brian-mortimer** [comment]
Okay Thank you

**Comment by glenn-jocher** [comment]
@brian-mortimer you're welcome! If you have any more questions or need further assistance, don't hesitate to ask. Good luck with your project!

**Comment by NaumanHSA** [comment]
Hi @glenn-jocher,

I really appreciate Ultralytics team for being responsive. I've a question for you related to running a YOLO segmentation model on Android. I've successfully got the outputs by writing custom preprocessing and postprocessing code in one of my Android app. However, the model is currently running on CPU and I'm unable to run on GPU. Please find the code snippet below how I run on GPU. I'm not an Android developer, so may be I'm doing something wrong but I've tried every possible solution and tried with different devices. This can be the issue that some operations/layers in YOLO architecture are not yet supported by the tflite GPU delegate? I need your assistance in this regard.

Thanks.

![image](https://github.com/ultralytics/ultralytics/assets/22982600/e2328159-b20c-4838-ab71-74ab9592bdff)

**Comment by NaumanHSA** [comment]
Hi @glenn-jocher,

Thank you for the response. I'm still digging down to figure out the exact issue. 

One more thing I'd like to ask. I installed the ultralytics app from Play Store and noticed that the integrated yolov8-n detection model was giving around 30 FPS. However, in my project I'm using **tflite-integer-quant** yolov8-n segmentation model which is custom trained on only one class. The inference speed without any post-processing is just 9 FPS on galaxy S24 Ultra. Can you give any assistance how I can improve the inference speed? As the model is quantized, is there anything else to optimize e.g. pruning? Also, can you give some insights which ml library is ultralytics using in their app? 

Thank you.

**Comment by glenn-jocher** [comment]
@NaumanHSA yOLOv8 does support exporting models to TensorFlow Lite (TFLite) format, which can be used in Android applications. However, the error you're encountering seems to be related to the metadata and output expectations of the TFLite model when used with the TensorFlow Lite Task Library (`org.tensorflow-lite-tensorflow-lite-task-vision`).

The first error about `NormalizationOptions` metadata suggests that the TFLite model requires additional metadata to preprocess input images correctly. This can often be resolved by ensuring that the model export includes the necessary metadata for input normalization.

The second error regarding the number of outputs indicates that the TensorFlow Lite Task Library expects a specific output format from the model, typically associated with SSD (Single Shot Multibox Detector) models, which have 4 outputs. YOLO models usually have a different output structure, which might not be directly compatible with the Task Library's ObjectDetector API without additional processing or conversion.

To resolve these issues, you might need to:
1. Ensure that the exported TFLite model includes the required metadata for input normalization.
2. Modify the Android code to handle the YOLO model's output format, or convert the YOLO model's outputs to a format compatible with the Task Library's expectations.

It's also worth noting that the TensorFlow Lite Task Library is designed to work with a specific set of model architectures, and custom models like those from YOLOv8 might require additional steps to be compatible.

If you continue to face issues, consider opening an issue on the Ultralytics YOLOv8 GitHub repository with detailed information about the error and the steps you've taken to resolve it. The community and maintainers can provide more targeted assistance.

**Comment by glenn-jocher** [comment]
@pahotari hi there! 😊

Indeed, integrating YOLOv8 models with the TensorFlow Lite Task Library can be tricky due to the output format differences. One approach to make YOLO outputs compatible is to add a custom layer or processing step in your app that translates YOLO's output to the expected SSD format.

For attaching metadata, TensorFlow provides a tool called `TensorFlow Lite Metadata Writer API` that you can use. Here's a quick example of how you might add metadata to your model:

```python
from tflite_support import metadata

writer = metadata.MetadataWriter.create_for_inference(
    model_buffer, input_norm_mean=[0], input_norm_std=[255], label_file_paths=[label_path])
model_with_metadata = writer.populate()
```

Remember to replace `model_buffer`, `label_path` with your model and label file paths. This should help with the NormalizationOptions error.

Hope this helps! Let us know if you have more questions.

**Comment by SarjuHansaliya** [comment]
@pahotari @NaumanHSA Here is how I solved it for my usecase, in case it helps you.

I am very new to Yolo.

## Model Preparation Steps

This is what I did based on my requirements.
1. Fine-tuned a model using YOLOv8n as the base
2. Exported the fine-tuned model to TFLite format with int8 quantization and NMS enabled
3. Added metadata to the TFLite model:

   First, created a `labels.txt` file with my class labels:
   ```txt
   car
   bike
   ```

   Then, added metadata to the TFLite model:
   ```python
    from tflite_support.metadata_writers import object_detector
    from tflite_support.metadata_writers import writer_utils

    MODEL_PATH = "yolov8n.best_int8.tflite"
    LABEL_FILE = "labels.txt"
    OUTPUT_PATH = "model_with_metadata.tflite"

    writer = object_detector.MetadataWriter.create_for_inference(
        writer_utils.load_file(MODEL_PATH),
        [0],
        [255],
        [LABEL_FILE]
    )

    writer_utils.save_file(writer.populate(), OUTPUT_PATH)
   ```

## The Problem

When trying to use the `model_with_metadata.tflite` in Android with the `ObjectDetector` class, got this error:

```
INVALID_ARGUMENT: Mobile SSD models are expected to have exactly 4 outputs, found 1.
```

This happens because YOLO models have a single output tensor, but the `ObjectDetector` class expects 4 outputs like in SSD models.

## The Solution

Used the TFLite `Interpreter` class directly instead, with these steps:

1. Loaded the model using the `Interpreter` class
2. Processed the image by:
   - Resizing to the model's input size (In my case it is 640×640)
   - Loading with `TensorImage`
   - Processing with `ImageProcessor`
3. Ran inference to get the output tensor
4. Parsed the results to get detections

Here's the entire code:

```java
package com.objectdetection;

import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.ImageFormat;
import android.graphics.Rect;
import android.graphics.YuvImage;
import android.media.Image;
import android.util.Log;
import android.content.Context;

import org.tensorflow.lite.Interpreter;
import org.tensorflow.lite.support.common.FileUtil;
import org.tensorflow.lite.support.common.ops.NormalizeOp;
import org.tensorflow.lite.support.image.ImageProcessor;
import org.tensorflow.lite.support.image.TensorImage;

import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.nio.MappedByteBuffer;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * A TensorFlow Lite-based object detection implementation.
 */
public class ObjectDetector {
    private static final String TAG = "ObjectDetector";
    private static final int INPUT_SIZE = 640; // TFLite model input image size
    private static final float CONFIDENCE_THRESHOLD = 0.5f;
    // Model output is [1, 300, 6]
    private static final int OUTPUT_PREDICTIONS = 300;
    private static final int OUTPUT_BATCH = 1;
    private static final int VALUES_PER_DETECTION = 6;
    private static final String[] LABELS = new String[]{"car", "bike"};
    
    private final Interpreter interpreter;

    public ObjectDetector(Context context) {
        try {
            MappedByteBuffer modelBuffer = FileUtil.loadMappedFile(context, "detection_model.tflite");
            Interpreter.Options interpretOptions = new Interpreter.Options();
            interpretOptions.setNumThreads(2);
            this.interpreter = new Interpreter(modelBuffer, interpretOptions);
            Log.d(TAG, "TFLite interpreter initialized successfully");
        } catch (Exception e) {
            Log.e(TAG, "Failed to load TFLite model", e);
            throw new RuntimeException("Failed to load TFLite model", e);
        }
    }

    /**
     * Processes an image and returns object detections.
     * 
     * @param image The input image to process
     * @return List of detection results with coordinates in original image space
     */
    public List<Map<String, Object>> processImage(Image image) {
        try {
            Bitmap bitmap = imageToBitmap(image);

            if (bitmap == null) {
                Log.e(TAG, "Failed to convert image to bitmap");
                throw new RuntimeException("Failed to convert image to bitmap");
            }

            int originalWidth = bitmap.getWidth();
            int originalHeight = bitmap.getHeight();

            Bitmap scaleFitImage = resizeToScaleFit(bitmap, INPUT_SIZE);

            TensorImage tensorImage = new TensorImage();
            tensorImage.load(scaleFitImage);

            ImageProcessor imageProcessor = new ImageProcessor.Builder()
                    .add(new NormalizeOp(0f, 255f)) // Normalize to [0,1]
                    .build();
            tensorImage = imageProcessor.process(tensorImage);

            float[][][] output = new float[OUTPUT_BATCH][OUTPUT_PREDICTIONS][VALUES_PER_DETECTION];
            interpreter.run(tensorImage.getBuffer(), output);

            return parseDetections(output, originalWidth, originalHeight);
        } catch (Exception e) {
            Log.e(TAG, "Error processing image: " + e.getMessage(), e);
            throw new RuntimeException("Error processing image: " + e.getMessage(), e);
        }
    }

    /**
     * Resizes the image to a square with padding (letterbox/scale-fit).
     */
    private Bitmap resizeToScaleFit(Bitmap source, int targetSize) {
        int width = source.getWidth();
        int height = source.getHeight();

        ScaleFitInfo info = new ScaleFitInfo(width, height, targetSize);

        Bitmap scaled = Bitmap.createScaledBitmap(source, info.scaledWidth, info.scaledHeight, true);
        Bitmap output = Bitmap.createBitmap(targetSize, targetSize, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(output);
        canvas.drawColor(Color.BLACK);

        canvas.drawBitmap(scaled, info.dx, info.dy, null);

        return output;
    }

    private Bitmap imageToBitmap(Image image) {
        Image.Plane[] planes = image.getPlanes();
        ByteBuffer yBuffer = planes[0].getBuffer();
        ByteBuffer uBuffer = planes[1].getBuffer();
        ByteBuffer vBuffer = planes[2].getBuffer();

        int ySize = yBuffer.remaining();
        int uSize = uBuffer.remaining();
        int vSize = vBuffer.remaining();

        byte[] nv21 = new byte[ySize + uSize + vSize];

        yBuffer.get(nv21, 0, ySize);
        vBuffer.get(nv21, ySize, vSize);
        uBuffer.get(nv21, ySize + vSize, uSize);

        YuvImage yuvImage = new YuvImage(nv21, ImageFormat.NV21, image.getWidth(), image.getHeight(), null);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        yuvImage.compressToJpeg(new Rect(0, 0, yuvImage.getWidth(), yuvImage.getHeight()), 100, out);

        byte[] imageBytes = out.toByteArray();
        return BitmapFactory.decodeByteArray(imageBytes, 0, imageBytes.length);
    }

    /**
     * Converts the model output to a list of detections with the original image dimensions.
     */
    private List<Map<String, Object>> parseDetections(float[][][] output, int originalWidth, int originalHeight) {
        List<Map<String, Object>> detections = new ArrayList<>();

        // Calculate scale and padding offsets using the helper class
        ScaleFitInfo info = new ScaleFitInfo(originalWidth, originalHeight, INPUT_SIZE);
        float scale = info.scale;
        int dx = info.dx;
        int dy = info.dy;
        int targetSize = INPUT_SIZE;

        for (float[] prediction : output[0]) {
            float confidence = prediction[4];
            if (confidence < CONFIDENCE_THRESHOLD) continue;

            // Get normalized coordinates relative to the INPUT_SIZE x INPUT_SIZE image
            float nx1 = clamp(prediction[0], 0f, 1f); // x1
            float ny1 = clamp(prediction[1], 0f, 1f); // y1
            float nx2 = clamp(prediction[2], 0f, 1f); // x2
            float ny2 = clamp(prediction[3], 0f, 1f); // y2

            // Convert normalized coordinates to pixel coordinates in the padded image (INPUT_SIZE x INPUT_SIZE)
            float paddedX1 = nx1 * targetSize;
            float paddedY1 = ny1 * targetSize;
            float paddedX2 = nx2 * targetSize;
            float paddedY2 = ny2 * targetSize;

            // Remove padding offsets to get coordinates relative to the scaled image
            float scaledX1 = paddedX1 - dx;
            float scaledY1 = paddedY1 - dy;
            float scaledX2 = paddedX2 - dx;
            float scaledY2 = paddedY2 - dy;

            // Scale back to original image dimensions
            double originalX1 = scaledX1 / scale;
            double originalY1 = scaledY1 / scale;
            double originalX2 = scaledX2 / scale;
            double originalY2 = scaledY2 / scale;

            // Clamp coordinates to original image bounds
            originalX1 = Math.max(0, Math.min(originalWidth, originalX1));
            originalY1 = Math.max(0, Math.min(originalHeight, originalY1));
            originalX2 = Math.max(0, Math.min(originalWidth, originalX2));
            originalY2 = Math.max(0, Math.min(originalHeight, originalY2));

            // Calculate width and height in original image pixels
            double originalBoxWidth = originalX2 - originalX1;
            double originalBoxHeight = originalY2 - originalY1;

            int classId = (int) prediction[5];

            Map<String, Object> result = new HashMap<>();
            result.put("label", (classId >= 0 && classId < LABELS.length) ? LABELS[classId] : "unknown");
            result.put("confidence", (double) confidence);

            Map<String, Object> origin = new HashMap<>();
            origin.put("x", originalX1);
            origin.put("y", originalY1);

            Map<String, Object> size = new HashMap<>();
            size.put("width", originalBoxWidth);
            size.put("height", originalBoxHeight);

            result.put("origin", origin);
            result.put("size", size);

            detections.add(result);
        }

        return detections;
    }

    private float clamp(float value, float min, float max) {
        return Math.max(min, Math.min(max, value));
    }

    /**
     * Helper class to manage scale fit calculations.
     */
    private static class ScaleFitInfo {
        public final float scale;
        public final int scaledWidth;
        public final int scaledHeight;
        public final int dx;
        public final int dy;

        public ScaleFitInfo(int originalWidth, int originalHeight, int targetSize) {
            this.scale = Math.min((float) targetSize / originalWidth, (float) targetSize / originalHeight);
            this.scaledWidth = Math.round(originalWidth * scale);
            this.scaledHeight = Math.round(originalHeight * scale);
            // Calculate padding to center the scaled image in the target size
            this.dx = (targetSize - scaledWidth) / 2;
            this.dy = (targetSize - scaledHeight) / 2;
        }
    }
}
```

Hope this helps anyone struggling with the same issue!
