### ISSUE TITLE
Detecting bounding boxes and keypoints

### ISSUE THREAD

**Issue by quancore** [ultralytics/ultralytics#7051]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I will process tissue Doppler images, and for each tissue Doppler I need to detect different phases in signal (with bounding box) and for each phase, there would be several key points to detect. There can be n number of phases and n number of key points. How should I approach this task with this model? I thought that there should be one model for phase detection with bounding boxes with just a single class. Then there should be another model trained on cropped phases and detect key points.

**Comment by glenn-jocher** [comment]
@quancore hi there!

For your task of detecting phases with bounding boxes and then key points within those phases, I’d recommend a two-stage approach using the YOLOv8 model.

In the first stage, you can train a YOLOv8 model to detect phases in your tissue Doppler images as a single class. Once this model is trained, it can localize each phase with a bounding box.

For the second stage, you would use the outputs (cropped bounding box images of phases) from the first model and then train another YOLOv8 model to detect multiple key points within these phases. This model would require a dataset with annotated key points.

To get started, visit our documentation on training YOLOv8 on a custom dataset (under the 'Train' section), and move on to keypoint annotation (under the 'Pose/Keypoint Estimation' section). Keep in mind that proper data preparation and annotation are crucial for the success of your models.

Best of luck with your imaging analysis! 🧬💻
