### ISSUE TITLE
Track function in the yolov8

### ISSUE THREAD

**Issue by komalkotra1** [ultralytics/ultralytics#7055]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I am doing object detection with yolov8, where can I find the source code of the .track function.i need to calibrate it a little bit so that it shows the frame numbers it's  tracking and also it counts how many frames it has tracked  and I didn't seem to find it anywhere on the documentation.
Please help me with this 
Regards
Komal

**Comment by glenn-jocher** [comment]
@komalkotra1 hello Komal,

The `.track` function you're referring to is part of the YOLOv8's object tracking capabilities. The source code for the tracking component is integrated within the repository and can be found in the relevant files that handle tracking tasks.

For customization like displaying frame numbers and counting the tracked frames, you would need to delve into the tracking code and modify the display or logging functionality accordingly.

While the tracking functionality is not explicitly separated as a standalone `.track` function, you can find the tracking-related code within the inference and post-processing sections of the codebase, which handle object detection and association across frames.

If you're new to modifying the source, I recommend proceeding with caution and making sure you have a good understanding of how the tracking algorithm works. This will help ensure any changes you make are effective and do not degrade the existing capabilities.

For a deeper understanding of how tracking is implemented and integrated within YOLOv8, please consider exploring the codebase further, focusing particularly on the sections that involve generating and updating bounding boxes across frames.
