### ISSUE TITLE
Questions about using headless opencv

### ISSUE THREAD

**Issue by langong347** [ultralytics/ultralytics#7056]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I have two questions regarding using `opencv-python-headless` instead of the default `opencv-python` dependency.

1) Enabling a build with `opencv-python-headless` : I have read about similar requests from other issues, for example #3480 proposed a way to fix this which didn't work out. Could you please give an update about any on-going efforts or what do you see as the proper way to enable this in the future?

2) Do you know if a CUDA build of opencv-python( or the  headless version) will be compatible with the YOLOv8 model? For example, I can see some benefits of using a CUDA build to resize the images during preprocessing [here](https://github.com/ultralytics/ultralytics/blob/b206b68ac65f3341749205d49da98da83e22cc6d/ultralytics/data/augment.py#L723-L726), but that requires additional changes to the cv2 API as well as the image type according to [ref](https://www.simonwenkel.com/notes/software_libraries/opencv/resizing-images-using-nvidia-gpus-opencv-pytorch-tensorflow.html). So even if I manage to build a CUDA version, it won't work out-of-box with Ultralytics, am I right?

### Use case

I am using Ultralytics YOLOv8 model in a production environment that does not have the graphics library required by `opencv-python`:

```
>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/layers/com.bloomberg.ds.buildpacks.pip/requirements/lib/python3.10/site-packages/cv2/{}init{}.py", line 181, in <module>
    bootstrap()
  File "/layers/com.bloomberg.ds.buildpacks.pip/requirements/lib/python3.10/site-packages/cv2/{}init{}.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/opt/bb/lib/python3.10/importlib/{}init{}.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@langong347 hello! Thank you for reaching out with your questions regarding the use of `opencv-python-headless`.

1) For building with `opencv-python-headless`, there are currently no active efforts in the Ultralytics repository to change the default `opencv-python` dependency. That said, we appreciate the community's feedback and contributions. If you're prepared to assist with this initiative, a pull request with any proposed changes to better support `opencv-python-headless` would certainly be welcome.

2) Regarding the CUDA build of `opencv-python`, while the benefits for image preprocessing are understood, the integration with YOLOv8 is not straightforward. Direct compatibility with Ultralytics codebase using a CUDA-enabled OpenCV build for image resizing or other operations would indeed require adaptations to the existing API calls and image data handling. Such integration is not out of the box and would involve a non-trivial amount of custom work.

The use case you've described highlights the need for such adaptations in certain production environments. If you're keen and able to provide a solution through a pull request, we would be happy to review the contribution.

It's excellent to hear of your willingness to submit a PR. Your collaboration helps improve the versatility and robustness of YOLOv8 for different use cases. 🚀

Please don't hesitate to visit our [Ultralytics Docs](https://docs.ultralytics.com) for guidance on contributing to the repository. Your efforts will benefit the entire YOLO community!

**Comment by langong347** [comment]
@glenn-jocher  Thank you for your reply! Your answer regarding the CUDA build OpenCV makes sense to me.

According to #1270 looks like it's not recommended to swap `opencv-python` with `opencv-python-headless` in the requirements.txt due to impact to other functionalities in Ultralytics that requires the graphic library, is that correct? (although I'm not sure why the CI is still passing in the linked PR above).

Could you also elaborate on which functionalities may be impacted by using the headless version?

**Comment by glenn-jocher** [comment]
Hello @langong347!

You are correct; replacing `opencv-python` with `opencv-python-headless` is not advised due to dependencies on the full OpenCV package for certain functionalities within the YOLOv8 repository. The continuous integration (CI) may pass as basic tests that don't require these functionalities can still execute without issues.

Potentially impacted functionalities include any operations that involve GUI capabilities, such as displaying images or videos during processing, which are inherently dependent on system-level graphics libraries not included in the headless version. For a production environment where these functionalities are not required, using the headless version may not pose a problem.

If you choose to use `opencv-python-headless`, ensure that your use case doesn't leverage these GUI-related features. 🛠️

**Comment by glenn-jocher** [comment]
Hi @langong347,

Appreciate your proposal on creating two versions of `ultralytics`. The idea of having a default non-GUI version and an extended GUI version is interesting and could serve different user needs well.

However, we must be cautious with the potential conflicts that could arise from having both `opencv-python` and `opencv-python-headless` installed in the environment, as this isn't a standard or recommended approach. The precedence of packages might lead to unpredictable behavior and complicate the user experience and package maintenance.

Currently, the flexibility for users to customize their installation by manually replacing `opencv-python` with `opencv-python-headless` when GUI features aren't necessary would still be our suggested method. This allows for a more controlled and explicit environmental setup without complicating the distribution and potential conflicts.

We're indeed always considering ways to simplify and improve the accessibility of `ultralytics` for various use cases, and feedback like yours is invaluable. 🌟 For now, it might be best to retain a single version while we continue to explore the best strategies to accommodate both sets of functionalities without compromising stability. Thank you for your input and willingness to contribute! 👍

**Comment by langong347** [comment]
Hi @glenn-jocher ,

Thank you for your thoughtful response and considerations. I completely understand the potential challenges and complexities that could arise from having both `opencv-python` and `opencv-python-headless` coexisting in the environment. Your caution is well noted.

I completely understand your decision to retain a single version for now while continuing to explore the best strategies. 

Looking forward to any future developments and improvements. Thank you again for your time; it has been a great conversation!

**Comment by glenn-jocher** [comment]
Hello @langong347,

I'm glad you found a workaround that fits into your automated workflow and that you're able to prioritize the `opencv-python-headless` where needed. Your experiences and insights are indeed valuable, and sharing such approaches can benefit others in similar situations.

We appreciate your willingness to contribute and your enthusiasm for a headless build option. We will certainly consider this in our future development roadmap. 🛤️

Thank you for the productive dialogue, and don't hesitate to reach out again with further questions, suggestions, or contributions! Happy coding! 🚀

**Comment by Tschak77** [comment]
Hi @langong347  ,
> 
> Thank you for your thoughtful response and considerations. I completely understand the potential challenges and complexities that could arise from having both `opencv-python` and `opencv-python-headless` coexisting in the environment. I agree that retaining a single version for now makes sense as you explore the best strategies.
> 
> Given my automated workflow, manually uninstalling and reinstalling the correct opencv version isn't feasible. However, I've found a workaround within my build system's specific configuration. I can install `opencv-python-headless` after installing `ultralytics`, ensuring the headless version takes precedence. While this workaround may not be universally applicable, I thought it could be a helpful reference. Nevertheless, I look forward to accessing a dedicated headless build of `ultralytics` in the future, and I'll be happy to contributing to that effort.
> 
> Thank you again for your time; it has been a great conversation!

I have the same problem, could you please give more details how you solve the problem?

at the moment I have to manually uninstall opencv-python and install opencv-python-headless at main runtime venv folder and also ALPR venv.

Thanks in advance.
