### ISSUE TITLE
_pickle.PicklingError: Can't pickle <built-in function imshow>: it's not found as __main__.imshow

### ISSUE THREAD

**Issue by fry404006308** [ultralytics/ultralytics#7059]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Val

### Bug

During my training, I encountered the following bug:

Every time I finish a training epoch and save the model, I run into the following pickle error:

`_pickle.PicklingError: Can't pickle <built-in function imshow>: it's not found as __main__.imshow`

Once I comment out the line `_imshow = cv2.imshow` in `ultralytics.utils.patches.py` on line 11, the model saves without any issues during training. However, during the final evaluation, when I attempt to load the model, I encounter a module not found error.

Could you please advise on how to resolve this issue?

Thanks.

### Bug Info

```

Starting training for 2 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        1/2      3.42G       4.74       22.4       4.27          1        768: 100%|██████████| 2/2 [00:03<00:00,  1.74s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  2.62it/s]
                   all          5          5    0.00133        0.4    0.00177   0.000177
Traceback (most recent call last):
  File "D:\_231012_1614_SF_Algo_Platform\algorithm-platform\labelme\231016_1013_DL_test.py", line 8, in <module>
    DetectC6Img5.main()
  File "D:\_231012_1614_SF_Algo_Platform\algorithm-platform\labelme\SF_DL_Algo\SF_DL_Algo_test\detection\detect_c6_img5_231125.py", line 137, in main
    returnObj = FryDetectTest.train(trainDict)
  File "D:\_231012_1614_SF_Algo_Platform\algorithm-platform\labelme\SF_DL_Algo\SF_DL_Algo_test\detection\detect_c6_img5_231125.py", line 14, in train
    returnObj = ModelFactory.train(trainDict)
  File "D:\_231012_1614_SF_Algo_Platform\algorithm-platform\labelme\SF_DL_Algo\modelFactory.py", line 96, in train
    returnObj = detectModel.train(paramsDict)
  File "D:\_231012_1614_SF_Algo_Platform\algorithm-platform\labelme\SF_DL_Algo\detection\_100_detect_model.py", line 19, in train
    returnObj = model.train(paramsDict)
  File "D:\_231012_1614_SF_Algo_Platform\algorithm-platform\labelme\SF_DL_Algo\detection\yolov8_detect\main.py", line 50, in train
    paramsDict = YoloDetectTrain.trainMain(paramsDict)
  File "D:\_231012_1614_SF_Algo_Platform\algorithm-platform\labelme\SF_DL_Algo\detection\yolov8_detect\train.py", line 31, in trainMain
    paramsDict = YoloTrain_support.real_train(paramsDict,model)
  File "D:\_231012_1614_SF_Algo_Platform\algorithm-platform\labelme\SF_DL_Algo\segmentation\yolov8seg\trainSupport.py", line 96, in real_train
    results = model.train(**yolo_realTrain_paramDict)
  File "D:\_231012_1614_SF_Algo_Platform\algorithm-platform\labelme\SF_DL_Algo\base\ultralytics_fry\engine\model.py", line 361, in train
    self.trainer.train()
  File "D:\_231012_1614_SF_Algo_Platform\algorithm-platform\labelme\SF_DL_Algo\base\ultralytics_fry\engine\trainer.py", line 218, in train
    self._do_train(world_size)
  File "D:\_231012_1614_SF_Algo_Platform\algorithm-platform\labelme\SF_DL_Algo\base\ultralytics_fry\engine\trainer.py", line 456, in _do_train
    self.save_model()
  File "D:\_231012_1614_SF_Algo_Platform\algorithm-platform\labelme\SF_DL_Algo\base\ultralytics_fry\engine\trainer.py", line 564, in save_model
    torch.save(ckpt, self.last)
  File "C:\Users\FanRenyi\.conda\envs\SF_Algo2\lib\site-packages\ultralytics\utils\patches.py", line 75, in torch_save
    return _torch_save(*args, **kwargs)
  File "D:\_231012_1614_SF_Algo_Platform\algorithm-platform\labelme\SF_DL_Algo\base\ultralytics_fry\utils\patches.py", line 84, in torch_save
    return _torch_save(*args, **kwargs)
  File "C:\Users\FanRenyi\.conda\envs\SF_Algo2\lib\site-packages\torch\serialization.py", line 441, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "C:\Users\FanRenyi\.conda\envs\SF_Algo2\lib\site-packages\torch\serialization.py", line 653, in _save
    pickler.dump(obj)

.......

  File "C:\Users\FanRenyi\.conda\envs\SF_Algo2\lib\pickle.py", line 998, in _batch_setitems
    save(v)
  File "C:\Users\FanRenyi\.conda\envs\SF_Algo2\lib\site-packages\dill\_dill.py", line 412, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Users\FanRenyi\.conda\envs\SF_Algo2\lib\pickle.py", line 589, in save
    self.save_global(obj, rv)
  File "C:\Users\FanRenyi\.conda\envs\SF_Algo2\lib\pickle.py", line 1071, in save_global
    raise PicklingError(
_pickle.PicklingError: Can't pickle <built-in function imshow>: it's not found as __main__.imshow


```

### Error Code position

Running the code `torch.save(ckpt, self.last)`  will result in an error

```
    def save_model(self):
        """Save model training checkpoints with additional metadata."""
        import pandas as pd  # scope for faster startup
        metrics = {**self.metrics, **{'fitness': self.fitness}}
        results = {k.strip(): v for k, v in pd.read_csv(self.csv).to_dict(orient='list').items()}
        ckpt = {
            'epoch': self.epoch,
            'best_fitness': self.best_fitness,
            'model': deepcopy(de_parallel(self.model)).half(),
            'ema': deepcopy(self.ema.ema).half(),
            'updates': self.ema.updates,
            'optimizer': self.optimizer.state_dict(),
            'train_args': vars(self.args),  # save as dict
            'train_metrics': metrics,
            'train_results': results,
            'date': datetime.now().isoformat(),
            'version': __version__}


        # Save last and best
        torch.save(ckpt, self.last)
        if self.best_fitness == self.fitness:
            torch.save(ckpt, self.best)
            self.fryParamsDict['best_pt']={}
            self.fryParamsDict['best_pt']['epoch'] = int(self.epoch)+1
            self.fryParamsDict['best_pt']['metrics'] = metrics

        if (self.save_period > 0) and (self.epoch > 0) and (self.epoch % self.save_period == 0):
            torch.save(ckpt, self.wdir / f'epoch{self.epoch}.pt')

```

### Pictures

![1702949651995](https://github.com/ultralytics/ultralytics/assets/33335064/091f4ce0-c55c-4bfb-ac16-c9ae3e713370)

![1702949812296](https://github.com/ultralytics/ultralytics/assets/33335064/303981fd-cb4c-466a-9fbf-c952c7668975)

### Environment

Ultralytics 
YOLOv8.0.188  
Python-3.10.13 
torch-2.0.0+cu118 
CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 8188MiB)
Setup complete  (16 CPUs, 63.7 GB RAM, 614.2/886.4 GB disk)

### Minimal Reproducible Example

Running the code `torch.save(ckpt, self.last)`  will result in an error

```
def save_model(self):
        """Save model training checkpoints with additional metadata."""
        import pandas as pd  # scope for faster startup
        metrics = {**self.metrics, **{'fitness': self.fitness}}
        results = {k.strip(): v for k, v in pd.read_csv(self.csv).to_dict(orient='list').items()}
        ckpt = {
            'epoch': self.epoch,
            'best_fitness': self.best_fitness,
            'model': deepcopy(de_parallel(self.model)).half(),
            'ema': deepcopy(self.ema.ema).half(),
            'updates': self.ema.updates,
            'optimizer': self.optimizer.state_dict(),
            'train_args': vars(self.args),  # save as dict
            'train_metrics': metrics,
            'train_results': results,
            'date': datetime.now().isoformat(),
            'version': __version__}


        # Save last and best
        torch.save(ckpt, self.last)
        if self.best_fitness == self.fitness:
            torch.save(ckpt, self.best)
            self.fryParamsDict['best_pt']={}
            self.fryParamsDict['best_pt']['epoch'] = int(self.epoch)+1
            self.fryParamsDict['best_pt']['metrics'] = metrics

        if (self.save_period > 0) and (self.epoch > 0) and (self.epoch % self.save_period == 0):
            torch.save(ckpt, self.wdir / f'epoch{self.epoch}.pt')

```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by fry404006308** [comment]
Once I comment out the line `_imshow = cv2.imshow` in `ultralytics.utils.patches.py` on line 11, the model saves without any issues during training. However, during the final evaluation, when I attempt to load the model, I encounter a module not found error.

The error is as follows:

![1702951148950](https://github.com/ultralytics/ultralytics/assets/33335064/67092aa7-e24c-49f0-82bc-8bfc19c9db9d)

**Comment by glenn-jocher** [comment]
@fry404006308 the error you're experiencing with pickling might be due to attempting to serialize a function that isn't meant to be serialized, like the `cv2.imshow`. This is not typical behavior, and altering the `ultralytics.utils.patches.py` isn't recommended as it could lead to other issues like the module not found errors you're encountering afterward.

One way to troubleshoot this issue is to ensure that no non-serializable objects (like functions, file handles, or database connections) are included in the data you're trying to save with `torch.save`. Double-check the elements within your model checkpoint dict (`ckpt`) before saving, and remove or modify any entries that could be causing serialization issues. Also, please ensure that your environment matches the requirements specified in our documentation.

For further investigation and support, please open an issue on the Ultralytics YOLOv8 GitHub repository with the full error traceback, and we'll look into it more deeply. Remember to provide any specific details about changes you've made to the original repository's code.

**Comment by fry404006308** [comment]
Thank you for your valuable advice. I will follow your suggestion to investigate this bug.

**Comment by fry404006308** [comment]
@glenn-jocher  I have successfully resolved the issue and would like to thank you for your suggestions. To address the problem, I made the following changes:
1. I removed all dependencies on the ultralytics library, meaning I no longer need to use `pip install ultralytics`. This allows me to easily modify the code to suit my needs without worrying about any environmental conflicts.
2. I eliminated the use of `IterableSimpleNamespace` in `ultralytics/utils/__init__.py`. It turns out that the error was mainly caused by operations involving `IterableSimpleNamespace`.

Everything is now running smoothly, and I really appreciate your help.

**Comment by glenn-jocher** [comment]
@fry404006308 that's fantastic to hear you've resolved the issue! 🎉 I'm glad the suggestions were helpful. It's always encouraging to see the community find innovative solutions. Should you encounter any more challenges or have further questions, feel free to reach out. Happy coding, and best of luck with your continued work on object detection with YOLOv8! 🚀

**Comment by chinhong11** [comment]
> @glenn-jocher I have successfully resolved the issue and would like to thank you for your suggestions. To address the problem, I made the following changes:
> 
> 1. I removed all dependencies on the ultralytics library, meaning I no longer need to use `pip install ultralytics`. This allows me to easily modify the code to suit my needs without worrying about any environmental conflicts.
> 2. I eliminated the use of `IterableSimpleNamespace` in `ultralytics/utils/__init__.py`. It turns out that the error was mainly caused by operations involving `IterableSimpleNamespace`.
> 
> Everything is now running smoothly, and I really appreciate your help.

@fry404006308 Hi there, unfortunately I am facing this problem too. May I know about how you resolve this issue as I am not sure about what you mentioned that eliminated the use of ```IterableSimpleNamespace``` mean?

**Comment by glenn-jocher** [comment]
@chinhong11 Great to hear you've sorted out the issue and thanks for sharing your solution! 😊 Simplifying dependencies can indeed make managing your project easier and more straightforward.

Regarding your question about `IterableSimpleNamespace`, it looks like @fry404006308 found that removing or modifying the usage of `IterableSimpleNamespace` in `ultralytics/utils/__init__.py` resolved their pickling error. This custom namespace might have contained non-serializable objects, leading to issues when saving/loading models with `torch.save` or `torch.load`. 

A simplified approach might involve replacing `IterableSimpleNamespace` with a standard Python dictionary or another serializable type, ensuring all objects you're dealing with can be easily pickled or unpickled. Here's a quick example of what such a modification could look like:

```python
# Original code using IterableSimpleNamespace
# from ultralytics.utils import IterableSimpleNamespace

# Modified code using a standard dictionary
config_dict = {'param1': value1, 'param2': value2}
```

Remember, the key is to ensure all the data structures you're using are compatible with PyTorch's serialization methods. Hope this clarifies things a bit! 🚀
