### ISSUE TITLE
NotImplementedError: '' model loading not implemented" - will this be implemented?

### ISSUE THREAD

**Issue by dmddmd** [ultralytics/ultralytics#706]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I want to load a self-trained model but get the NotImplementedError.

when I try to load a '.pt'-file, I get 

> NotImplementedError: '' model loading not implemented"

and when I try to load an exported model as '.onnx', Iget

> NotImplementedError: '.onnx' model loading not implemented

When can we expect this to be implemented?

### Additional

ultralytics version 8.0.23

**Comment by Laughing-q** [comment]
@dmddmd Can you provide the command line you use?

**Comment by dmddmd** [comment]
`model = YOLO('../model.onnx') `and 
`model = YOLO('../runs/detect/train4/weights/best.pt')
`

**Comment by AyushExel** [comment]
onnx loading is not supported yet but .pt should be supported. Can you confirm that loading a model.pt file is still broken for you?

**Comment by dmddmd** [comment]
I tried again, loading a .pt works :)

**Comment by RwGrid** [comment]
Sir Ayush, first off, thanks for the titanic work god bless your noble soul, I am receiving this
 yolo task=detect mode=predict model=yolov8n.engine -WARNING ⚠️ not yet supported for YOLOv8 exported models
when exported models will have loading, predict?
Estimated time Sir, please(it can take as long as it can)

**Comment by dmddmd** [comment]
how should we export then to import later ? tourchscript also does not work

**Comment by rusvagzur** [comment]
are there updates about this?

**Comment by AyushExel** [comment]
Hey all, this should be supported now in the latest release. Please let us know if you see this issue still
