### ISSUE TITLE
how to finetune yolov8-rtdetr

### ISSUE THREAD

**Issue by huilin66** [ultralytics/ultralytics#7060]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

how to run yolov8-rtdetr with pretrained weight? I cannot find this pretrained weight. Thanks

**Comment by glenn-jocher** [comment]
@huilin66 hello and thank you for reaching out!

To finetune the YOLOv8-RTDETR model with pretrained weights, you'll start by initializing the model with the weights provided in our repo. You can find the weights in the releases section or they'll be automatically downloaded when you begin training with the provided commands in the documentation.

Using our train mode documented at our Ultralytics Docs, you'll set the weights flag to the specific RTDETR pretrained weight file. From there, follow the instructions for training with the dataset of your choice, ensuring the data is properly configured.

During finetuning, keep in mind to adjust your hyperparameters as necessary to avoid overfitting your pretrained model on your new dataset. Happy finetuning! 😊

**Comment by huilin66** [comment]
> @huilin66 hello and thank you for reaching out!
> 
> To finetune the YOLOv8-RTDETR model with pretrained weights, you'll start by initializing the model with the weights provided in our repo. You can find the weights in the releases section or they'll be automatically downloaded when you begin training with the provided commands in the documentation.
> 
> Using our train mode documented at our Ultralytics Docs, you'll set the weights flag to the specific RTDETR pretrained weight file. From there, follow the instructions for training with the dataset of your choice, ensuring the data is properly configured.
> 
> During finetuning, keep in mind to adjust your hyperparameters as necessary to avoid overfitting your pretrained model on your new dataset. Happy finetuning! 😊

Thanks very much for your kind reply. Actrually, I have looked thourgh the https://github.com/ultralytics/assets/releases. But I didn't find YOLOv8-RTDETR weights. I can only find rtdetr-l, rtdetr-x and other yolo8 related weights instead of yolo8-rtdetr. Accordint the "yolov8-rtdetr.yaml", it should be a yolo8 architecture with a rtdetr head. So I think rtdetr-l, rtdetr-x and other yolo8 related weights cannot finish the finetune.


Besides, I also try to start the fintune with 
    model = YOLO('yolov8-rtdetr.yaml')
    results = model.train(data='bdd_select.yaml', epochs=300, imgsz=640, batch=32, val=True, patience=300, device=1)
There is a error:
C:\Users\Huilin\.conda\envs\yolov8\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed to load image Python extension: Could not find module 'C:\Users\Huilin\.conda\envs\yolov8\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "E:\Huilin\2308_concretespalling\seperate_env\yolov8\ultralytics\engine\model.py", line 414, in _smart_load
    return self.task_map[self.task][key]
KeyError: None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Huilin\2308_concretespalling\seperate_env\yolov8\run_cp.py", line 45, in <module>
    model = YOLO('yolov8-rtdetr.yaml')
  File "E:\Huilin\2308_concretespalling\seperate_env\yolov8\ultralytics\engine\model.py", line 90, in __init__
    self._new(model, task)
  File "E:\Huilin\2308_concretespalling\seperate_env\yolov8\ultralytics\engine\model.py", line 119, in _new
    self.model = (model or self._smart_load('model'))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "E:\Huilin\2308_concretespalling\seperate_env\yolov8\ultralytics\engine\model.py", line 418, in _smart_load
    raise NotImplementedError(
NotImplementedError: WARNING  'YOLO' model does not support '_new' mode for 'None' task yet.

I successfuly run with
    model = RTDETR('yolov8-rtdetr.yaml')
    results = model.train(data='bdd_select.yaml', epochs=300, imgsz=640, batch=32, val=True, patience=300, device=1)
I think I didn't load the pretrained weight. How should I load it and load which weight? Thank you very much.

**Comment by glenn-jocher** [comment]
@huilin66 apologies for the confusion. It appears there might be an oversight in our release of pretrained weights for YOLOv8-RTDETR. If you're unable to find the specific weights for this architecture in the releases, it's possible they haven't been published yet.

Regarding your code execution error, it seems there could be an issue with your environment setup or an incompatibility with the torchvision package. Please ensure that all dependencies are correctly installed and that your Python environment is properly configured.

For finetuning the YOLOv8-RTDETR model, you should use the architecture-specific weights designed for the RTDETR head. Without the specific pretrained weights available, you may need to train from scratch or use a closely related pretrained model as a starting point, if compatible.

Keep an eye on our releases for updates on pretrained weights, and feel free to reach out if you have further issues or questions. 🛠️
