### ISSUE TITLE
NCNN export fails due to `system` variable value

### ISSUE THREAD

**Issue by KWiecko** [ultralytics/ultralytics#7061]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

Index out of bound error when attempting to export model to NCNN

PNNX recently broke the release name convention `ubuntu` -> `linux`:
` pnnx-20231127-ubuntu.zip ` ->  `pnnx-20231218-linux.zip` 

This means that the following line (463) from `ultralytics/engine/exporter.py`:

```{python}
asset = [x for x in assets if 'linux' in x or system in x][0] if assets else \
                f'https://github.com/pnnx/pnnx/releases/download/20230816/pnnx-20230816-{system}.zip'  # fallback
```

will err out with no valid error other than: `IndexError: list index out of range`

Dirty trick to fix the breaking change from PNNX -> replace line above with the line below:

```{python}
asset = [x for x in assets if 'linux' in x or system in x][0] if assets else \
                f'https://github.com/pnnx/pnnx/releases/download/20230816/pnnx-20230816-{system}.zip'  # fallback
```

Please note that in `else ` clause the link is not the latest one while there is an attempt to download latest PNNX version.

### Environment

Ultralytics YOLOv8.0.211 🚀 Python-3.10.13 torch-2.1.2+cu121 CUDA:0 (NVIDIA GeForce RTX 4060 Ti, 16061MiB)
Setup complete ✅ (32 CPUs, 125.5 GB RAM, 391.5/1832.2 GB disk)

System has 2 identical GPUs

### Minimal Reproducible Example

```
from argparse import ArgumentParser
import os
import warnings

from ultralytics import YOLO

from config import TARGET_DIM


def do_export(model_path, target_dim):
    model_dir = os.sep.join(model_path.split(os.sep)[:-1])
    os.chdir(model_dir)
    m = YOLO('best.pt')
    m.export(format='ncnn', half=True, imgsz=target_dim, int8=True)


if __name__ == '__main__':

    ap = ArgumentParser()
    ap.add_argument('--model_path', type=str, required=True)
    ap.add_argument('--target_dim', type=int, default=TARGET_DIM)

    pa = ap.parse_args()
    model_path = pa.model_path
    target_dim = int(pa.target_dim)
    assert model_path

    if target_dim != TARGET_DIM:
        warnings.warn(f'Provided CLI param: `target_dim` -> {target_dim} differs from config.py param `TARGET_DIM`: {TARGET_DIM}\n'
                      f'Using CLI param: {target_dim}.\n'
                      f'Please note that this will cause NCNN inference to fail if input image shape is different from {target_dim}')

    do_export(model_path=model_path, target_dim=target_dim)

```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@KWiecko thank you for the detailed bug report. We're aware of the recent change in PNNX release naming convention that affects the NCNN export functionality. Your observation about the `system` variable and fallback URL is correct. We appreciate your suggestion for a temporary solution. Our team will review the situation and update the `export.py` script accordingly. 

For now, please continue using your workaround, and keep an eye on the repository for updates regarding this issue. If you come across any further issues or have additional insights, please don't hesitate to share. Your contributions help enhance the YOLOv8 experience for everyone! 🚀🛠️

**Comment by glenn-jocher** [comment]
@KWiecko great news 😃! Your original issue may now be resolved ✅ in PR #7050. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by KWiecko** [comment]
Awesome news, thanks!

**Comment by nihui** [comment]
Because we changed the pnnx binary compilation environment and reduced the dependency on glibc version to make it compatible with more Linux distributions, we changed the name of ubuntu in the package name to linux

In addition, we have released the pnnx python package, which makes it easier to use pnnx

- convert torch model to ncnn format
- optimize torch model (yeah, you get an optimized torch module from pnnx)

pip install -U pnnx

```python
import torch
import torchvision
import pnnx

model = torchvision.models.swin_t(pretrained=True)

x = torch.rand(1, 3, 224, 224)

opt_model = pnnx.export(model, "swin_t", x)

# now you got all pnnx generated files in current directory

# we can check if pnnx optimized model produce the same result with torch model
a = model(x)
b = opt_model(x)
print(torch.allclose(a, b, 1e-4, 1e-4))

# we can even export onnx from the pnnx optimized model
torch.onnx.export(model, x, "swin_t.onnx", opset_version=17)
torch.onnx.export(opt_model, x, "swin_t-opt.onnx", opset_version=17)
```

**Comment by glenn-jocher** [comment]
@nihui thank you for the update on the PNNX binary compilation and the introduction of the PNNX Python package. This change ensures broader compatibility across Linux distributions. Also, it's great to hear that the Python package streamlines the process for converting Torch models to NCNN format and allows for model optimization directly through PNNX.

For those interested in using the new PNNX Python package, you can install it using `pip install -U pnnx`. The provided code snippet demonstrates how to export and optimize a model with PNNX, as well as verifying the optimized model's results and exporting to ONNX format.

This simplification is a valuable improvement for the community and we'll be sure to explore these enhancements within the YOLOv8 workflows. 🚀🔧

**Comment by nihui** [comment]
updated pnnx readme here :D

https://github.com/pnnx/pnnx

**Comment by glenn-jocher** [comment]
@nihui thank you for notifying us about the updated PNNX README! 📘🎉 We'll take a look and make sure to align our documentation and processes with the latest guidelines provided. Appreciate the heads-up! 🚀
