### ISSUE TITLE
Regarding results.py

### ISSUE THREAD

**Issue by namanshankar2021** [ultralytics/ultralytics#7071]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am working with a pretrained model and now I want to return text and store it in a list but each time when i predict, the run file changes and I have to access the label manually.

**Comment by glenn-jocher** [comment]
@namanshankar2021 hello! It sounds like you'd like to collect text predictions from a pretrained YOLOv8 model continuously into a list.

In the standard operation of YOLOv8, predictions are saved as text files within individual run directories for each inference session. To gather these results programmatically into a list, consider implementing a custom function in your Python script which reads the contents of each new `labels` text file generated after prediction and appends the data to your preferred in-memory list.

This would provide you with a centralized collection of results which you can further manipulate as required. Remember to check the documentation under the "Predict" mode for guidance on how to properly handle outputs. 😊🚀
