### ISSUE TITLE
Yolov8 uses tensoeboard for segment training

### ISSUE THREAD

**Issue by 8410ttt** [ultralytics/ultralytics#7075]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to use TensorBoard's Image Summary API during yolov8 training ，I want to see a live training image for each epoch.

**Comment by glenn-jocher** [comment]
@8410ttt hi there! 👋 During YOLOv8 training, the TensorBoard logging is already integrated and will automatically log scalar metrics. However, we don't support direct logging of images through the TensorBoard Image Summary API currently.

To view training progress, you can still use the TensorBoard scalar logs for loss and performance metrics. Live images per epoch are not provided out of the box, but the validation results after each epoch will include sample images with predictions that you can inspect.

For further insights on training and validation processes, please refer to our documentation on the Train and Val modes. Thanks for your interest in YOLOv8 and for contributing to our community with your question! Happy coding! 😊

**Comment by 8410ttt** [comment]
> 嘿，你好！👋 在 YOLOv8 训练期间，已经集成了 TensorBoard 日志记录，并会自动记录标量指标。但是，我们目前不支持通过 TensorBoard Image Summary API 直接记录图像。
> 
> 要查看训练进度，您仍然可以使用 TensorBoard 标量日志来查看损失和性能指标。每个 epoch 的实时图像不是现成的，但每个 epoch 之后的验证结果将包括示例图像以及您可以检查的预测。
> 
> 有关训练和验证过程的更多见解，请参阅我们关于 Train 和 Val 模式的文档。感谢您对 YOLOv8 的关注，并感谢您向我们的社区提出您的问题！祝您编码愉快！😊

Sorry, I made a mistake before, I want to see the validation results after each epoch, including the effect of the validation set, can you tell me how to achieve this?
![image](https://github.com/ultralytics/ultralytics/assets/114403347/ae0e1062-ead2-4af3-9ece-ed149d38b13d)

**Comment by glenn-jocher** [comment]
Hi @8410ttt! 😊 To view validation results after each epoch, including sample images with predictions, ensure you have set up validation correctly during training. The validation results are saved in the `runs` directory by default, where you can find labeled example images from each epoch.

Currently, the TensorBoard support within YOLOv8 does not extend to the direct visualization of these validation images, hence the difficulties you're encountering.

After each training epoch, refer to the saved images in the `runs` directory for visual inspection. For more details on setting up validation and interpreting results, please check the Val mode documentation.

If you're encountering errors while setting up or accessing these images, please ensure your environment is correctly configured and that you have the latest version of the repo installed. Thanks for engaging with YOLOv8!
