### ISSUE TITLE
How to detect some object among many objects ? 

### ISSUE THREAD

**Issue by KAkhoa12** [ultralytics/ultralytics#7078]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm working with my street traffic dataset, which includes 500 images and labeled 5 objects, how do I feed the image into the model and only want to detect 2 out of 5 objects? statue in it
Ex: Normally if I put an image in it will detect at least 5 objects, but what if I want to detect 2 of those objects?

**Comment by bit-scientist** [comment]
you use `classes` argument as described [here](https://docs.ultralytics.com/modes/predict/#inference-arguments):

> `filter results by class, i.e. classes=0, or classes=[0,2,3]`

**Comment by glenn-jocher** [comment]
@bit-scientist certainly! When you wish to focus on detecting a subset of classes from your dataset, you can use the `classes` argument during prediction. You can specify it with the class indices you're interested in. For instance, if you want to detect only two out of your five objects, you would set `classes` to the indices of those two objects, such as `classes=[0,2]` where '0' and '2' are the class indices corresponding to the objects you wish to detect. This will filter the results and only the specified classes will be detected and returned by the model. For more details on inference arguments, please refer to the Predict section in the Ultralytics Docs. 😊
