### ISSUE TITLE
Proposal to Add CherryChevre Dataset for Goat Detection Benchmark

### ISSUE THREAD

**Issue by Phirxian** [ultralytics/ultralytics#7083]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I would like to propose the inclusion of the CherryChevre dataset for goat detection as a benchmark in Ultralytics. This dataset, detailed in the following [paper](https://www.nature.com/articles/s41597-023-02555-8), consists of 6160 annotated images captured under varying environmental conditions. The annotations were meticulously performed by experts in computer vision, ensuring high accuracy and consistency. The dataset is intended for developing machine learning algorithms for goat detection, with applications in precision agriculture, animal welfare, behavior analysis, and animal husbandry.

## Dataset Details

- Number of Images: 6160
- Annotations: Expert-annotated for high accuracy
- Applications: Precision agriculture, animal welfare, behavior analysis, animal husbandry
- Public Availability: The dataset is publicly available and can be accessed for benchmarking purposes.

## How to Access the Dataset

The dataset can be obtained from the following link:
- [CherryChevre VGG Dataset](https://entrepot.recherche.data.gouv.fr/dataset.xhtml?persistentId=doi:10.57745/QEZBNA) in VGG format
- [CherryChevre Yolo Dataset](https://entrepot.recherche.data.gouv.fr/dataset.xhtml?persistentId=doi:10.57745/4C03OG) in yolo format with train/val/test split

### Use case

Including the CherryChevre dataset in Ultralytics can advance research in computer vision for agriculture, providing a valuable benchmark for evaluating existing algorithms.

### Additional

I believe that integrating this dataset into Ultralytics will contribute significantly to the community's research efforts in computer vision for agriculture. Your consideration of this proposal is greatly appreciated.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Phirxian thank you for your proposal to incorporate the CherryChevre dataset for goat detection into Ultralytics benchmarks. It's always exciting to see community engagement and suggestions for enhancing the applicability of our models in diverse domains such as agriculture.

The integration of additional datasets for benchmarking is indeed valuable. They contribute significantly to broadening the research and application horizons of our models. While we strive to stay up-to-date with the latest datasets and applications, we have to carefully prioritize which datasets to include based on our current roadmap, community demand, and the resources available to us.

We will certainly take your recommendation into consideration for future updates. If you or anyone in the community is enthusiastic about accelerating this process, we welcome contributions through pull requests. Contributions are a fantastic way for the community to directly influence the growth and evolution of YOLOv8.

Please keep an eye on our repository updates for any news regarding benchmarks and dataset integrations. Your input is an invaluable part of our community's collective effort to advance the field of computer vision. 🚀
