### ISSUE TITLE
Does tracker take into account object property?

### ISSUE THREAD

**Issue by FiksII** [ultralytics/ultralytics#7088]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Does the tracker take into account object property or, it use only boxes?
For example, if I have a video with 2 balls: red and black, they move, collide, fly through, and so on.
So, will the tracker always assign object_1 to the red ball and object_2 to the black ball or it confuse them?

**Comment by glenn-jocher** [comment]
@FiksII the tracker primarily relies on bounding boxes for object tracking. Although it doesn't explicitly account for object properties like color, the YOLOv8 tracker uses motion and other frame-to-frame changes in detection parameters to maintain consistent object identities over time. However, in scenarios with occlusions or highly dynamic interactions, such as collisions or overlapping paths, there can be instances where the tracker might confuse the objects. Optimization for these complex scenarios is an ongoing area of improvement. For more details on the tracking capabilities, please refer to the Track mode documentation. 😊🚀
