### ISSUE TITLE
Multiple predictions for one box

### ISSUE THREAD

**Issue by Evgl1** [ultralytics/ultralytics#709]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

YOLOV5

Can you please tell me how to get several predictions for one box? model.multi_label = True doesn't work

### Additional

YOLOV5

**Comment by JustasBart** [comment]
Hi @Evgl1 I'm not entirely sure what do you mean by this, but are you perhaps thinking of the iou (Intersection over union) value?

That's what controls whether you should have 2/3/5 etc.. boxes next to each other or should you join them into one etc...
Have you tried that?

Hope that helps! :rocket:

**Comment by JustasBart** [comment]
Oh, I understand now, unfortunately I'm a C++ dev so I can't offer you any Python based solutions, but yeah it just sounds like you need to code up some custom logic to achieve that, doesn't sound too bad overall though so I wish you all the best!

**Comment by pderrenger** [comment]
@JustasBart it sounds like you're looking to obtain a list of the most similar drinks when the model mistakenly recognizes one of them. If I understand correctly, you would like to provide the option for a person to choose the correct item from this list.

In the YOLOv8 model, this functionality isn't directly built-in, but you can achieve this by incorporating custom logic. One approach could involve running inference on the model, obtaining the bounding boxes for each recognized drink, and then using a similarity metric to generate a list of closest matches.

Given the similarity in the drinks, a technique like nearest neighbor search or similarity comparison using features derived from the bounding boxes could be useful here. Once you have the list, you can present it to the user for selection.

I hope this points you in the right direction! If you have further questions, feel free to ask. Good luck with your implementation!
