### ISSUE TITLE
Why doesn't export to TensorRT support int8 format?

### ISSUE THREAD

**Issue by alsozatch** [ultralytics/ultralytics#7095]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

TensorRT supports int8 quantization but the YOLO export method does not. Why?

**Comment by glenn-jocher** [comment]
@alsozatch hey there, thank you for reaching out!

The current implementation of YOLOv8 export to TensorRT is focused on achieving a balance between optimization and broad compatibility. While TensorRT does indeed support int8 quantization for further acceleration, it requires a calibration step to maintain accuracy, which introduces additional complexity. We prioritize features based on community demand and impact, so int8 support might be added in future releases if there's substantial interest and it aligns with our development goals. For the latest updates and feature support, always keep an eye on our documentation and release notes. Appreciate your understanding! 😊🚀

**Comment by umitkacar** [comment]
Did you look it?
https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP#int8-inference

**Comment by junho2000** [comment]
I want Int8 ... haha

**Comment by glenn-jocher** [comment]
@junho2000, great enthusiasm! Int8 support is definitely on the radar but not yet integrated into our YOLOv8 export pipeline. We value such feedback as it helps us prioritize future enhancements. Keep an eye on our updates! 😄👍

**Comment by alsozatch** [comment]
> @junho2000, great enthusiasm! Int8 support is definitely on the radar but not yet integrated into our YOLOv8 export pipeline. We value such feedback as it helps us prioritize future enhancements. Keep an eye on our updates! 😄👍

Thanks ChatGPT. Whether it's actually on the radar remains a mystery

**Comment by junho2000** [comment]
> @alsozatch Did you look it?
> 
> https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP#int8-inference
@umitkacar
I tried that but I can't get significant increase at inference speed(slightly.. and decreased accuracy even I finetuned with coco dataset)

I am not sure, INT8 quantization is that powerful? I didn't feel that much

**Comment by alsozatch** [comment]
INT8 quantization needs a calibration dataset which I’m not familiar with yet. It seems like it is more trouble than it’s worth, most things I see online only compare FP16 quantization anyways. It seems that FP16 already starts to lose a bit of accuracy but it’s still good enough, INT8 might just be really bad for accuracy so it needs a special calibration dataset. I don’t know the specifics but I wonder why INT8 needs the calibration dataset but FP16 doesn’t.
