### ISSUE TITLE
yolov8如何每个epoch训练完验证的时候显示处每个类的mAP ?

### ISSUE THREAD

**Issue by Dennis-Chen2021** [ultralytics/ultralytics#7097]
### Search before asking

- [ ] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

yolov8显示单个类的mAP ?

**Comment by glenn-jocher** [comment]
@Dennis-Chen2021 您好！在使用YOLOv8时，如果您想查看单个类别的mAP，可以在训练完成之后进行验证（Val）阶段，模型会输出每个类别的mAP值。请访问我们的文档进行详细了解关于验证（Val）模式的信息。希望这能帮助到您！ 😊👍
