### ISSUE TITLE
Time Progress information during training

### ISSUE THREAD

**Issue by dmddmd** [ultralytics/ultralytics#710]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Can You provide sth like this during training? 

>   16% |/---| 10836/68957 [10.1m elapsed, 53.8m remaining, 19.0 images/s]  

### Use case

It helps to estimate the time it needs and schedule further steps

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@dmddmd you mean this? it's already here.
![xMuGuJzEia](https://user-images.githubusercontent.com/61612323/215373896-f05a7755-2096-4fae-92bb-7462629580d3.jpg)

**Comment by Laughing-q** [comment]
@dmddmd closing the issue as we already have `tqdm` to show the schedule. Feel free to reopen it if you still have related issues. :)
