### ISSUE TITLE
Results trained on VOC dataset were lower than YOLOv5

### ISSUE THREAD

**Issue by kazu-gra** [ultralytics/ultralytics#7101]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

You trained your model on the VOC dataset. However, mAP_0.5 is now 0.738, which is lower than the 0.91286 you trained with YOLOv5. I think the cause is that the hyperparameters are different from the defaults in YOLOv8.
Please let me know if there are other causes.

Also, if you have any .pt files or hyperparameters of YOLOv8 trained with VOC dataset, please share them with us as soon as possible.

Best regards.

**Comment by kazu-gra** [comment]
YOLOv8 training with the VOC dataset is from scratch.

**Comment by glenn-jocher** [comment]
@kazu-gra understanding that YOLOv8 performance on the VOC dataset may not currently match the YOLOv5 results you've mentioned, it's important to recognize that model performance is influenced by many factors. This may include differences in default hyperparameters, model architectures, and data preprocessing.

When transitioning from YOLOv5 to YOLOv8, it's recommended to experiment with adjusting the hyperparameters to better suit the dataset and training procedure for YOLOv8. You can consult our documentation for guidelines on hyperparameter tuning which may help improve your training results.

Regarding pretrained models or hyperparameter settings specifically for VOC on YOLOv8, we continuously work on improving and sharing such resources with the community. Therefore, keep an eye on the repository and the Ultralytics Docs for updates and newly released models. 

Thank you for your involvement with YOLOv8, and we appreciate your contribution to the ongoing enhancement of the project! If you further refine your model and obtain improved results, your insights would be highly valuable to the community. 🚀
