### ISSUE TITLE
yolov8 train model	path to model file  doesn't work

### ISSUE THREAD

**Issue by lonngxiang** [ultralytics/ultralytics#7102]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Why the local model path doesn't work;still need to download the model online?

yolo task=detect mode=train model=/data/yolov8n.pt

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by lonngxiang** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/40717349/c30b777d-33a1-4e72-8514-6953e5d520c9)

**Comment by WangQvQ** [comment]
@lonngxiang You need to place your training script and yolov8n.pt in the same path.

**Comment by lonngxiang** [comment]
> @lonngxiang You need to place your training script and yolov8n.pt in the same path.

yep, but why the model doesn't work in any other directory,Path specify it

**Comment by glenn-jocher** [comment]
Hi @lonngxiang, thanks for reaching out! It's expected that the model should work from any directory if the path is specified correctly. Verify that the path to `yolov8n.pt` is the absolute path or the correct relative path from where you are running the script. Incorrect path specifications could be the reason for your issues. If everything looks good and you still encounter problems, please refer to the Documentation for detailed guidance or share more details so we can assist you better. 👍

**Comment by lonngxiang** [comment]
> Hi @lonngxiang, thanks for reaching out! It's expected that the model should work from any directory if the path is specified correctly. Verify that the path to `yolov8n.pt` is the absolute path or the correct relative path from where you are running the script. Incorrect path specifications could be the reason for your issues. If everything looks good and you still encounter problems, please refer to the Documentation for detailed guidance or share more details so we can assist you better. 👍

yes, `yolov8n.pt` is the absolute path ,but still dowloading
![image](https://github.com/ultralytics/ultralytics/assets/40717349/4534ef24-cf3d-4677-b6a9-0c6d801457dd)
![image](https://github.com/ultralytics/ultralytics/assets/40717349/a42636f0-72c0-41ce-8cb0-e6fdaba4c01e)

**Comment by glenn-jocher** [comment]
Hello @lonngxiang, if the path to `yolov8n.pt` is indeed correct and the model is still attempting to download, please make sure that the file isn't corrupted or incorrectly named. Double-check the file permissions as well. If the issue persists, consult our Documentation or open a new issue with detailed logs for further assistance. Thank you for your patience! 🙏

**Comment by filancer** [comment]
@lonngxiang guess you forget to disable AMP, you can turn off in default.yaml
`try:
        from ultralytics import YOLO
        assert amp_allclose(YOLO('yolov8n.pt'), im
        LOGGER.info(f'{prefix}checks passed ✅')
    except ConnectionError:
        LOGGER.warning(f'{prefix}checks skipped ⚠️, offline and unable to download YOLOv8n. {warning_msg}')
    except (AttributeError, ModuleNotFoundError):
        LOGGER.warning(f'{prefix}checks skipped ⚠️. '
                       f'Unable to load YOLOv8n due to possible Ultralytics package modifications. {warning_msg}')
    except AssertionError:
        LOGGER.warning(f'{prefix}checks failed ❌. Anomalies were detected with AMP on your system that may lead to '
                       f'NaN losses or zero-mAP results, so AMP will be disabled during training.')
        return False
    return  #True`

**Comment by glenn-jocher** [comment]
@filancer, it seems like you're encountering an issue related to Automatic Mixed Precision (AMP). To disable AMP, you can adjust the settings in the `default.yaml` configuration file. If AMP is causing the problem, turning it off should help. If you continue to face issues, please refer to our Documentation for further troubleshooting steps. 🛠️
