### ISSUE TITLE
npy files in object detection mission in yolov8

### ISSUE THREAD

**Issue by wesalawida** [ultralytics/ultralytics#7105]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i have .npy images and and annotation for this files , and its order on yolov8 dataset  like this :
- dataset
  - images
    - img1.npy
    - img2.npy
    - ...
  - labels
    - img1.txt
    - img2.txt
    - ...

how can i train object detection model that take this files ?

**Comment by glenn-jocher** [comment]
@wesalawida hi there! 👋

To train YOLOv8 with `.npy` image files and matching `.txt` annotation files, you'll first need to convert your `.npy` images to a common image format like JPG or PNG, as YOLOv8 directly supports these formats for training.

Once you have your images and annotations in the appropriate formats and directory structure, you can proceed with the training process using the YOLOv8 Train mode. Remember to ensure your annotation files are in the expected YOLO format, which is documented in our Guidelines for Training Custom Data.

If you need further assistance with the preparation of your dataset or the training process, please head to our documentation. 😊

Happy training! 🚀
