### ISSUE TITLE
stop making the bbox on each classes for predict.py when using save_crop=True

### ISSUE THREAD

**Issue by Zahak-Anjum** [ultralytics/ultralytics#711]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to stop making bounding boxes on the other classes when I say save_crop=True for the predictions?
![image](https://user-images.githubusercontent.com/71014321/215336606-61666c8d-025a-4ed0-8f85-bf9219c55edf.png). If I remember correctly that was not happening in Yolov5.

**Comment by Laughing-q** [comment]
@Zahak-Anjum hi thanks for the reporting! already made a PR #714  to fix this which would be merged later today. :)
