### ISSUE TITLE
How to crop and save masks

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#7121]
How to crop and save masks
uncrop_masks_PNG

Instance Segmentation
![微信截图_20231222104433](https://github.com/ultralytics/ultralytics/assets/6490927/c89427dd-0c6c-4241-b117-21d6001f4119)

**Comment by glenn-jocher** [comment]
@monkeycc hello!

For instance segmentation and saving the resulting masks, after running predictions with the `Segment Anything Model (SAM)` using YOLOv8, you'll have the segmentation masks available in the model output. To crop and save these masks, you would typically extract each mask using the coordinates of the detected objects and then apply the mask to the image to extract the segment. Finally, save each segment as an individual image or mask file.

Our documentation provides comprehensive instructions for various modes, including the predict mode, which you'll find useful for running the segmentation task. After predicting, you may refer to the post-processing part to manage the mask cropping and saving.

For detailed steps and further information about segmentation tasks, you can refer to our docs under the 'Segment' section.  😊📖
