### ISSUE TITLE
Val period's input size isn't square

### ISSUE THREAD

**Issue by housen007** [ultralytics/ultralytics#7122]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val

### Bug

When training, the input size is correctly 640*640
![image](https://github.com/ultralytics/ultralytics/assets/87907354/4a2db9d6-a8fc-4541-b6b3-8e12873ec179)
But, when the val period, the input size become unsquare
![image](https://github.com/ultralytics/ultralytics/assets/87907354/fd659463-04a2-46f2-b676-8e87f9af51f2)
Because i have modify the YOLOv8's bottleneck, and have downsample and upsample to recover. this bug bring error
![image](https://github.com/ultralytics/ultralytics/assets/87907354/b3997a89-848a-4dac-9ac1-ea36521dc849)

### Environment

CUDA 11.8
Pytorch 2.01
RTX4060Ti 16GB
Windows11

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@housen007 hello! Thanks for reporting this issue with the validation input size not being square. YOLOv8 should maintain the same input size for both training and validation phases by default.

It appears that there may be a configuration that is leading to the changed input size during validation. As you've modified the bottleneck and incorporated downsampling and upsampling layers, please ensure that your custom layers are able to handle the non-square input sizes that could result from validation data that does not match the training aspect ratio.

For addressing this issue in the model you have modified, make sure that any hardcoded dimensions are flexible to adapt to both square and non-square inputs. In the original model implementation, the dimensions automatically adjust to the specified input size in the configuration file.

Refer to the YOLOv8 documentation on the Val mode for specifics on configuring the input sizes and adapting model architecture to support variable input dimensions. And remember to verify that any changes in the architecture do not conflict with the expected input size for both training and validation.

If you continue experiencing issues, please provide detailed information about the changes you've made to the model's architecture, so we can better assist you in resolving this. Thank you for contributing to the YOLOv8 community! 🚀

**Comment by housen007** [comment]
> @housen007 hello! Thanks for reporting this issue with the validation input size not being square. YOLOv8 should maintain the same input size for both training and validation phases by default.
> 
> It appears that there may be a configuration that is leading to the changed input size during validation. As you've modified the bottleneck and incorporated downsampling and upsampling layers, please ensure that your custom layers are able to handle the non-square input sizes that could result from validation data that does not match the training aspect ratio.
> 
> For addressing this issue in the model you have modified, make sure that any hardcoded dimensions are flexible to adapt to both square and non-square inputs. In the original model implementation, the dimensions automatically adjust to the specified input size in the configuration file.
> 
> Refer to the YOLOv8 documentation on the Val mode for specifics on configuring the input sizes and adapting model architecture to support variable input dimensions. And remember to verify that any changes in the architecture do not conflict with the expected input size for both training and validation.
> 
> If you continue experiencing issues, please provide detailed information about the changes you've made to the model's architecture, so we can better assist you in resolving this. Thank you for contributing to the YOLOv8 community! 🚀

oh，I only change the model's cfg. And then, I also test the original YOLOv8's cfg, when validation, the input size is also not square. I suspect is there any bug in Resize's code that lead to not square input?

**Comment by glenn-jocher** [comment]
@housen007 Thanks for the update and for checking the original YOLOv8 as well. If the issue persists even with the unchanged config, there might indeed be an unexpected behavior in the resize operation during validation. I recommend revisiting the configuration settings related to image resizing, and ensure that they are set to maintain aspect ratio or to enforce square inputs as needed.

Should the problem continue, please raise an issue with detailed reproduction steps on our GitHub so that we can investigate further. Double-check the dataset and validation settings to make sure they align with the square input assumption. Your contributions are valuable for improving YOLOv8.🛠️

**Comment by housen007** [comment]
> @housen007 Thanks for the update and for checking the original YOLOv8 as well. If the issue persists even with the unchanged config, there might indeed be an unexpected behavior in the resize operation during validation. I recommend revisiting the configuration settings related to image resizing, and ensure that they are set to maintain aspect ratio or to enforce square inputs as needed.
> 
> Should the problem continue, please raise an issue with detailed reproduction steps on our GitHub so that we can investigate further. Double-check the dataset and validation settings to make sure they align with the square input assumption. Your contributions are valuable for improving YOLOv8.🛠️

Could you tell me where the source code related to Resize Image? I want to check the code.

**Comment by glenn-jocher** [comment]
@housen007 For investigating the resize behavior during validation, please refer to the image processing and augmentation section in the YOLOv8 source code. Look for the part of the code where input images are resized before being passed to the model for validation. If you encounter any further issues, do not hesitate to report back with your findings. Happy coding! 🧐🔍

**Comment by housen007** [comment]
> @housen007 For investigating the resize behavior during validation, please refer to the image processing and augmentation section in the YOLOv8 source code. Look for the part of the code where input images are resized before being passed to the model for validation. If you encounter any further issues, do not hesitate to report back with your findings. Happy coding! 🧐🔍

I locate the Class LetterBox in data/augment.py. I try to copy the code in a jupyter notebook and process my dataset, and it runs normally (square 640*640)......... But, strangely, when I run the whole programme, in valid period, the image size become unsquare!!!
here is the code
`from ultralytics import YOLO`
`import os`
`os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"`
`import torch`
`if __name__ == '__main__':`
`         model = YOLO(r'/media/housen/0854962754961810/ultralytics-main/ultralytics/cfg/models/v8/yolov8s_EPCblock.yaml')`
`         model.load('yolov8s.pt')`
`         model.train(cfg = '/media/housen/0854962754961810/ultralytics-main/ultralytics/cfg/run.yaml', data = '/media/housen/0854962754961810/ultralytics-main/ultralytics/cfg/datasets/data_linux.yaml', imgsz = 640)`
I also print the size in Class LetterBox
![图片](https://github.com/ultralytics/ultralytics/assets/87907354/79ae5c7e-8bab-4b2d-aafd-f091ed5f89f9)
When the valid period, the print output like this:
![图片](https://github.com/ultralytics/ultralytics/assets/87907354/accc4a87-9e08-4bdf-ab90-b2dea78c2985)
It looks like the letterbox is put too much? But when I run the code alone with the jupyter notebook, it runs normally

**Comment by housen007** [comment]
> > @housen007 For investigating the resize behavior during validation, please refer to the image processing and augmentation section in the YOLOv8 source code. Look for the part of the code where input images are resized before being passed to the model for validation. If you encounter any further issues, do not hesitate to report back with your findings. Happy coding! 🧐🔍
> 
> I locate the Class LetterBox in data/augment.py. I try to copy the code in a jupyter notebook and process my dataset, and it runs normally (square 640*640)......... But, strangely, when I run the whole programme, in valid period, the image size become unsquare!!! here is the code `from ultralytics import YOLO` `import os` `os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"` `import torch` `if __name__ == '__main__':` ` model = YOLO(r'/media/housen/0854962754961810/ultralytics-main/ultralytics/cfg/models/v8/yolov8s_EPCblock.yaml')` ` model.load('yolov8s.pt')` ` model.train(cfg = '/media/housen/0854962754961810/ultralytics-main/ultralytics/cfg/run.yaml', data = '/media/housen/0854962754961810/ultralytics-main/ultralytics/cfg/datasets/data_linux.yaml', imgsz = 640)` I also print the size in Class LetterBox ![图片](https://private-user-images.githubusercontent.com/87907354/292762954-79ae5c7e-8bab-4b2d-aafd-f091ed5f89f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MTQ5MTYsIm5iZiI6MTcwMzUxNDYxNiwicGF0aCI6Ii84NzkwNzM1NC8yOTI3NjI5NTQtNzlhZTVjN2UtOGJhYi00YjJkLWFhZmQtZjA5MWVkNWY4OWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDE0MzAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2OWQ1N2Q5ZDMxYjRiMTFlNWViMDhiZmQwYWM0ZjI3Njk2MjczMzkzZDM3OWJmMDZkZjllMDU4M2I1MzdkNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JsMmdFUHZwNbe5K3jZVr3qwlh60aHgT6tUx2_S6mVT8) When the valid period, the print output like this: ![图片](https://private-user-images.githubusercontent.com/87907354/292763210-accc4a87-9e08-4bdf-ab90-b2dea78c2985.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MTQ5MTYsIm5iZiI6MTcwMzUxNDYxNiwicGF0aCI6Ii84NzkwNzM1NC8yOTI3NjMyMTAtYWNjYzRhODctOWUwOC00YmRmLWFiOTAtYjJkZWE3OGMyOTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDE0MzAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNDQ5YjIyMmJkOTMwNTAyOGRhNDc4MzQ4ZWMwM2VjODg1NDFmNjIwM2FhODc1MDkwMDNiMTNlY2MxNDQ4Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aAVf8sWs6PoPXgphipt8AG7g7C-N0DW5_ANIvet4frc) It looks like the letterbox is put too much? But when I run the code alone with the jupyter notebook, it runs normally

![图片](https://github.com/ultralytics/ultralytics/assets/87907354/e624bd7e-d45b-4254-87da-92eda8d785b2)
here is the jupyter notebook's output

**Comment by glenn-jocher** [comment]
@housen007 It appears this might be an intricate issue as the behavior is inconsistent between your standalone tests and the full program execution. Since the `LetterBox` functionality is working as expected in isolation, the issue could be related to how the data is batched or preprocessed during validation within the complete training script.

It would be beneficial to verify the image processing flow during the validation phase within the training script. Investigate if anything differs in the handling of the batched data or the preprocessing steps for the validation dataset that could affect the image dimensions.

If troubleshooting within the codebase does not resolve the situation, please report this with all the necessary details as a GitHub issue to assist you more effectively. The printout statements you've provided are helpful; ensure that as much context as possible is included in your report to aid in replicating and diagnosing the issue. 🛠️🧐

**Comment by housen007** [comment]
> @housen007 It appears this might be an intricate issue as the behavior is inconsistent between your standalone tests and the full program execution. Since the `LetterBox` functionality is working as expected in isolation, the issue could be related to how the data is batched or preprocessed during validation within the complete training script.
> 
> It would be beneficial to verify the image processing flow during the validation phase within the training script. Investigate if anything differs in the handling of the batched data or the preprocessing steps for the validation dataset that could affect the image dimensions.
> 
> If troubleshooting within the codebase does not resolve the situation, please report this with all the necessary details as a GitHub issue to assist you more effectively. The printout statements you've provided are helpful; ensure that as much context as possible is included in your report to aid in replicating and diagnosing the issue. 🛠️🧐

Oh my god! I already found that, in Class LetterBox in Augment.py. 
There is a line of code:
![图片](https://github.com/ultralytics/ultralytics/assets/87907354/82855def-9177-46b0-96cf-6b2f2805e1fd)
`new_shape = labels.pop('rect_shape', self.new_shape)`
This code will change valid input's target shape, And I print the attribute of labels:
![图片](https://github.com/ultralytics/ultralytics/assets/87907354/b354b02b-df97-4e0c-a415-fc1e29c34044)
and found the bottom has the attribute of rect shape(672,384) that is my unsquare valid input.
So, I want to ask why the label has such attribute? Is it wrong?

**Comment by housen007** [comment]
That's why the code run normally isolate

> > @housen007 It appears this might be an intricate issue as the behavior is inconsistent between your standalone tests and the full program execution. Since the `LetterBox` functionality is working as expected in isolation, the issue could be related to how the data is batched or preprocessed during validation within the complete training script.
> > It would be beneficial to verify the image processing flow during the validation phase within the training script. Investigate if anything differs in the handling of the batched data or the preprocessing steps for the validation dataset that could affect the image dimensions.
> > If troubleshooting within the codebase does not resolve the situation, please report this with all the necessary details as a GitHub issue to assist you more effectively. The printout statements you've provided are helpful; ensure that as much context as possible is included in your report to aid in replicating and diagnosing the issue. 🛠️🧐
> 
> Oh my god! I already found that, in Class LetterBox in Augment.py. There is a line of code: ![图片](https://private-user-images.githubusercontent.com/87907354/293055231-82855def-9177-46b0-96cf-6b2f2805e1fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTA0NzEsIm5iZiI6MTcwMzY5MDE3MSwicGF0aCI6Ii84NzkwNzM1NC8yOTMwNTUyMzEtODI4NTVkZWYtOTE3Ny00NmIwLTk2Y2YtNmIyZjI4MDVlMWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE1MTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmODIxYTYyMzZkNGM0MmFkZDcxM2I2MmY3Zjc1OWU4M2IwYTg1N2VjOTg5MTkzNGVmOTUzNWMzMzRkZTA1YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jmbPLsyEtwn9jjjxKxpbrNDOdzJCXBnDaoSC-FCGqp0) `new_shape = labels.pop('rect_shape', self.new_shape)` This code will change valid input's target shape, And I print the attribute of labels: ![图片](https://private-user-images.githubusercontent.com/87907354/293055542-b354b02b-df97-4e0c-a415-fc1e29c34044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTA0NzEsIm5iZiI6MTcwMzY5MDE3MSwicGF0aCI6Ii84NzkwNzM1NC8yOTMwNTU1NDItYjM1NGIwMmItZGY5Ny00ZTBjLWE0MTUtZmMxZTI5YzM0MDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE1MTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5YjhiOTgwNDc2MGIyOWY4ZDI2YjBiMmJlN2ZiYTdiYTRjNGQyMmQwZDYwNDAzN2Y0NThjMjdjZmM0ZTZmMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._sHYLwrsw-xXJV8rjlwGenEADGDxBDqE8RVo2J2kYSs) and found the bottom has the attribute of rect shape(672,384) that is my unsquare valid input. So, I want to ask why the label has such attribute? Is it wrong?

**Comment by glenn-jocher** [comment]
@housen007 the presence of the 'rect_shape' attribute within the labels data suggests that your dataset contains annotations for images with non-square aspect ratios. This attribute is typically used to preserve the aspect ratio of images when resizing them—hence why it comes into play during validation. The original dimensions of your dataset images may be influencing the validation image shape. To maintain square input sizes, you may need to adjust your dataset preprocessing or the configuration controlling the resizing behavior for validation images. If issues continue, consider reviewing the validation dataset and configuration or opening a detailed GitHub issue for further assistance. 🧐

**Comment by housen007** [comment]
> @housen007 the presence of the 'rect_shape' attribute within the labels data suggests that your dataset contains annotations for images with non-square aspect ratios. This attribute is typically used to preserve the aspect ratio of images when resizing them—hence why it comes into play during validation. The original dimensions of your dataset images may be influencing the validation image shape. To maintain square input sizes, you may need to adjust your dataset preprocessing or the configuration controlling the resizing behavior for validation images. If issues continue, consider reviewing the validation dataset and configuration or opening a detailed GitHub issue for further assistance. 🧐

my dataset are not square(but it should not influence) and my configuration use default yaml.......
And, I have seen that in def load image in Class Basedataset in base.py, you first resize the long size of image to 640, and then add  the letterbox. I think the bounding box's coord should be easily adjusted to square 640 without resize to rect shape......... Is it right?

**Comment by glenn-jocher** [comment]
@housen007 the 'rect_shape' attribute is indeed designed to resize images while preserving the aspect ratio. If your dataset contains non-square images and you're using default configurations, the images are likely being resized to the long side of 640 while maintaining aspect ratio, hence the non-square shape.

Your understanding is correct that a square resize could be achieved without maintaining the original aspect ratio, but that may not be the default behavior if aspect ratio preservation is prioritized in the configurations.

If you require square images without aspect ratio preservation, you may need to specifically adjust or override the default settings to enforce square resizing. Ensure your configurations match your requirement and adjust as needed. If you still run into difficulties, please outline the issue on GitHub for more tailored support.

**Comment by housen007** [comment]
> @housen007 the 'rect_shape' attribute is indeed designed to resize images while preserving the aspect ratio. If your dataset contains non-square images and you're using default configurations, the images are likely being resized to the long side of 640 while maintaining aspect ratio, hence the non-square shape.
> 
> Your understanding is correct that a square resize could be achieved without maintaining the original aspect ratio, but that may not be the default behavior if aspect ratio preservation is prioritized in the configurations.
> 
> If you require square images without aspect ratio preservation, you may need to specifically adjust or override the default settings to enforce square resizing. Ensure your configurations match your requirement and adjust as needed. If you still run into difficulties, please outline the issue on GitHub for more tailored support.

I try to override the variable 'new_shape' in Class Letterbox in augment.py to maintain the correct size of valid input
![图片](https://github.com/ultralytics/ultralytics/assets/87907354/cbf4be08-faf3-4872-ad60-d7d6a859cef8)
And I also know that the label will be changed at the same time in these codes in the Class Letterbox, right?
![图片](https://github.com/ultralytics/ultralytics/assets/87907354/9c722aea-10a5-4e21-9c80-9cc1231b6944)
So I locate the last add padding code and print resized bbox coord in Class Instance and Bboxes in instance.py
![图片](https://github.com/ultralytics/ultralytics/assets/87907354/082810fb-e384-4384-8539-806e968351f8)
![图片](https://github.com/ultralytics/ultralytics/assets/87907354/d9827acd-4f6d-46bb-b5e4-d790df790aed)
When valid, I get the resized bbox coord and letterboxed image.
And I use jupyter notebook to follow your way to load the image, resize the image's long side to 640, and then add letterbox to test, And found that without the 'rect shape'(nonsquare), my letterboxed image can still maintain the aspect ratio and correct resized Bbox coord (my study is fire detection)
![图片](https://github.com/ultralytics/ultralytics/assets/87907354/04e1ef20-9419-4617-84a9-bec9b3b098d3)
![图片](https://github.com/ultralytics/ultralytics/assets/87907354/f6f3c0d1-3179-4c1d-831f-7a576f86b267)
Is it prove that the 'rect shape'(unsquare like 672*384) is unhelpful to maintain square input while origin aspect ratio?
I just want to know the meaning of this code
![图片](https://github.com/ultralytics/ultralytics/assets/87907354/d8994aeb-4599-47ee-95cf-0c086d2fd2b8)
`new_shape = labels.pop('rect_shape', self.new_shape)`

**Comment by glenn-jocher** [comment]
@housen007 Overriding 'new_shape' to maintain square inputs during validation is a viable approach. Yes, adjusting this variable not only changes the image but also the corresponding bounding box coordinates accordingly.

Regarding the 'rect_shape' attribute, it seems like your analysis has shown that removing the nonsquare 'rect_shape' preserves the aspect ratio without requiring the image to be reshaped into a nonsquare form. This could indicate that the use of 'rect_shape' may not be strictly necessary for your case, where you prioritize square inputs.

The line `new_shape = labels.pop('rect_shape', self.new_shape)` aims to provide flexibility, allowing images with annotations that specify a 'rect_shape' to be resized to that shape. If not specified, it defaults to 'self.new_shape'. In essence, this enables the model to handle datasets with annotations that might favor a particular input shape.

If maintaining a square shape consistently across training and validation is essential for your application, you might consider ensuring that 'rect_shape' is either not added to the labels or not used by modifying the corresponding configuration or code.

To resolve your issue, it could be worth ensuring that your dataset annotations and configurations align with the desired square sizing, or adjust the image processing pipeline accordingly. If further clarification or assistance is needed, please consider opening a specific GitHub issue detailing your findings and steps taken so far.

**Comment by housen007** [comment]
> @housen007 Overriding 'new_shape' to maintain square inputs during validation is a viable approach. Yes, adjusting this variable not only changes the image but also the corresponding bounding box coordinates accordingly.
> 
> Regarding the 'rect_shape' attribute, it seems like your analysis has shown that removing the nonsquare 'rect_shape' preserves the aspect ratio without requiring the image to be reshaped into a nonsquare form. This could indicate that the use of 'rect_shape' may not be strictly necessary for your case, where you prioritize square inputs.
> 
> The line `new_shape = labels.pop('rect_shape', self.new_shape)` aims to provide flexibility, allowing images with annotations that specify a 'rect_shape' to be resized to that shape. If not specified, it defaults to 'self.new_shape'. In essence, this enables the model to handle datasets with annotations that might favor a particular input shape.
> 
> If maintaining a square shape consistently across training and validation is essential for your application, you might consider ensuring that 'rect_shape' is either not added to the labels or not used by modifying the corresponding configuration or code.
> 
> To resolve your issue, it could be worth ensuring that your dataset annotations and configurations align with the desired square sizing, or adjust the image processing pipeline accordingly. If further clarification or assistance is needed, please consider opening a specific GitHub issue detailing your findings and steps taken so far.

ok i will further train and valid the model( in the above test, the valid set only have 1 image haha) and check is there any bug with my way to override the variable new shape, thank you!

**Comment by glenn-jocher** [comment]
@housen007 Sounds like a plan! Keep an eye on the model performance with the changes and if anything unusual arises during your larger scale validation tests, do reach out with a GitHub issue. Good luck with your training and validation, looking forward to hearing about your results with the square input strategy. Happy experimenting! 🚀🧑‍🔬
