### ISSUE TITLE
Sam error and question about drawing result mask

### ISSUE THREAD

**Issue by spacewalk01** [ultralytics/ultralytics#7126]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

1. Bug: I got this error when exporting sam_b.pt model 
command : `yolo export model=sam_b.pt format=onnx`
error message : `AttributeError: 'Sam' object has no attribute 'args' `
2. Question: will you provide example on how to use sam result on masking images thanks

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by spacewalk01** [comment]
And nice work adding original sam model to your framework.

**Comment by glenn-jocher** [comment]
@spacewalk01 thank you for your kind words! The collaborative effort of the entire community and the Ultralytics team has made integrating the SAM model possible. 🚀

Regarding the bug you encountered, it seems there's an issue with the `Sam` class handling in the export function. We'll investigate this and address it promptly. Please follow the updates on our GitHub issues page for a fix or further instructions.

For your question on using the SAM model results for image masking, the SAM model in YOLOv8 is designed for segmentation tasks, which includes creating masks based on detected objects. While we don't have a direct example in our documentation, applying the masks generally involves overlaying the segmentation output on your images. This process usually involves accessing the model's output channels corresponding to each class and applying a threshold to create a binary mask, which you then overlay onto the original image.

You can find some more detailed functionalities for tasks like segmentation in our specialized docs. For more specific guidance on using the SAM mask outputs, keep an eye on the repository updates as we'll be enhancing our documentation with more use cases and examples based on user feedback and development progression. 📚

We appreciate your patience and contribution to improving YOLOv8!
