### ISSUE TITLE
Backbone with Transformer

### ISSUE THREAD

**Issue by ohjunee** [ultralytics/ultralytics#7128]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there a model in the YOLOv8 model zoo that uses a backbone with a transformer like [yolov5s-transfomer.yaml](https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5s-transformer.yaml) ?

```# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3TR, [1024]],  # 9 <--- C3TR() Transformer module
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]```

**Comment by glenn-jocher** [comment]
@ohjunee hi there,

Currently, YOLOv8 does not include a model with a transformer-based backbone akin to the 'yolov5s-transformer.yaml' from the YOLOv5 repository. Our YOLOv8 model zoo is continuously evolving, though, so be sure to keep an eye on our updates for any new model architectures that may incorporate transformer components in the future.

For the latest capabilities of YOLOv8 and its models, I recommend checking out our documentation, particularly the sections about [Export](https://docs.ultralytics.com/modes/export) which outlines how we prepare models for various deployment scenarios.

Stay tuned for updates and enhancements! 😊

— Glenn Jocher
