### ISSUE TITLE
Augmentation settings in yolo v5 and v8

### ISSUE THREAD

**Issue by blackcement** [ultralytics/ultralytics#713]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Where are the rotation, reflection (left to right) settings adjusted when training OD?

### Additional

How can this be configured, what are the defaults?

**Comment by JustasBart** [comment]
Hi @blackcement, I'm not sure if this is what you're looking for, but whenever I train a yolov5 model I create a custom augmentations .hyp file and for yolov8 I just have a .sh script that launches the trainer for me like so:

**customTrain.sh**
```
yolo detect train \
data=10Class.yaml \
model=yolov8s.pt \
epochs=300 \
imgsz=1280 \
rect=True \
device=0 \
batch=-1 \
plots=True \
hsv_h=0.015 \
hsv_s=0.5 \
hsv_v=0.3 \
degrees=0.0 \
translate=0.1 \
scale=0.2 \
shear=1.0 \
flipud=0.5 \
fliplr=0.5 
```

I hope this is of any use to you, good luck! :rocket:
