### ISSUE TITLE
AttributeError: 'YOLO' object has no attribute 'tune'

### ISSUE THREAD

**Issue by letessarini** [ultralytics/ultralytics#7130]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Hyperparameter Tuning

### Bug

I'm trying to use hyperparameter tuning. Use the command specified here: 
`https://docs.ultralytics.com/guides/hyperparameter-tuning/#repeat`
But when I run it, this error appears. I cloned the repository correctly. I don't know what could be causing this error: 
AttributeError: 'YOLO' object has no attribute 'tune'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by letessarini** [comment]
I tried this now

`# Install and update Ultralytics and Ray Tune packages
pip install -U ultralytics "ray[tune]"

# Optionally install W&B for logging
pip install wandb`

`from ultralytics import YOLO

# Load a YOLOv8n model
model = YOLO('yolov8n.pt')

# Start tuning hyperparameters for YOLOv8n training on the COCO8 dataset
result_grid = model.tune(data='coco8.yaml', use_ray=True`


And now I get this error:
`WARNING ⚠️ Ultralytics settings reset to default values. This may be due to a possible problem with your settings or a recent ultralytics package update. 
View settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.yaml'
Update settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'.
💡 Learn about RayTune at https://docs.ultralytics.com/integrations/ray-tune
2023-12-22 12:48:18,476	INFO worker.py:1724 -- Started a local Ray instance.
WARNING ⚠️ search space not provided, using default search space.
2023-12-22 12:48:22,309	INFO tune.py:592 -- [output] This will use the new output engine with verbosity 1. To disable the new output and use the legacy output engine, set the environment variable RAY_AIR_NEW_OUTPUT=0. For more information, please see https://github.com/ray-project/ray/issues/36949
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-7-5011cbd061a1>](https://localhost:8080/#) in <cell line: 7>()
      5 
      6 # Start tuning hyperparameters for YOLOv8n training on the COCO8 dataset
----> 7 result_grid = model.tune(data='/content/drive/MyDrive/TAMS_AMII_seg/YOLOv8-transfer-learning/dataset_carga_imp.yaml', use_ray=True)

9 frames
[/usr/local/lib/python3.10/dist-packages/ray/air/integrations/wandb.py](https://localhost:8080/#) in _set_api_key(api_key_file, api_key)
    321         os.environ[WANDB_ENV_VAR] = api_key
    322     elif not os.environ.get(WANDB_ENV_VAR):
--> 323         raise ValueError(
    324             "No WandB API key found. Either set the {} environment "
    325             "variable, pass `api_key` or `api_key_file` to the"

ValueError: No WandB API key found. Either set the WANDB_API_KEY environment variable, pass `api_key` or `api_key_file` to the`WandbLoggerCallback` class as arguments, or run `wandb login` from the command line`

**Comment by letessarini** [comment]
I tried this now:

# Install and update Ultralytics and Ray Tune packages
pip install -U ultralytics "ray[tune]"

# Optionally install W&B for logging
pip install wandb

from ultralytics import YOLO

# Load a YOLOv8n model
model = YOLO('yolov8n.pt')

# Start tuning hyperparameters for YOLOv8n training on the COCO8 dataset
result_grid = model.tune(data='coco8.yaml', use_ray=True)

According to this link: https://docs.ultralytics.com/integrations/ray-tune/#installation

But another error:

WARNING ⚠️ Ultralytics settings reset to default values. This may be due to a possible problem with your settings or a recent ultralytics package update. 
View settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.yaml'
Update settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'.
💡 Learn about RayTune at https://docs.ultralytics.com/integrations/ray-tune
2023-12-22 12:48:18,476	INFO worker.py:1724 -- Started a local Ray instance.
WARNING ⚠️ search space not provided, using default search space.
2023-12-22 12:48:22,309	INFO tune.py:592 -- [output] This will use the new output engine with verbosity 1. To disable the new output and use the legacy output engine, set the environment variable RAY_AIR_NEW_OUTPUT=0. For more information, please see https://github.com/ray-project/ray/issues/36949
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-7-5011cbd061a1>](https://localhost:8080/#) in <cell line: 7>()
      5 
      6 # Start tuning hyperparameters for YOLOv8n training on the COCO8 dataset
----> 7 result_grid = model.tune(data='/content/drive/MyDrive/TAMS_AMII_seg/YOLOv8-transfer-learning/dataset_carga_imp.yaml', use_ray=True)

9 frames
[/usr/local/lib/python3.10/dist-packages/ray/air/integrations/wandb.py](https://localhost:8080/#) in _set_api_key(api_key_file, api_key)
    321         os.environ[WANDB_ENV_VAR] = api_key
    322     elif not os.environ.get(WANDB_ENV_VAR):
--> 323         raise ValueError(
    324             "No WandB API key found. Either set the {} environment "
    325             "variable, pass `api_key` or `api_key_file` to the"

ValueError: No WandB API key found. Either set the WANDB_API_KEY environment variable, pass `api_key` or `api_key_file` to the`WandbLoggerCallback` class as arguments, or run `wandb login` from the command line

**Comment by glenn-jocher** [comment]
@letessarini it seems like you are encountering an issue related to Weights & Biases (WandB) API key configuration when attempting to use hyperparameter tuning with YOLOv8.

The error message is indicating that WandB cannot find an API key, which is necessary for logging and tracking experiments. Here's what you need to do:
1. Ensure you have an account with WandB and have generated an API key.
2. Log in to WandB using the terminal by typing `wandb login`, and when prompted, enter your API key.

Regarding your initial attempt that resulted in the AttributeError, make sure you are using the latest version of our software. Hyperparameter tuning may not be available in all versions of YOLOv8, or the method signature could have changed.

To learn more about hyperparameter tuning and potential troubleshooting steps, please refer to our detailed documentation on hyperparameter tuning with Ray Tune. If the issue persists after following these steps, please provide your environment details and a minimal reproducible example when reporting the issue. This information will greatly assist in diagnosing the problem more effectively. 🛠️
