### ISSUE TITLE
Yolov8 training using data stored in Mongodb

### ISSUE THREAD

**Issue by vishnusharma03** [ultralytics/ultralytics#7131]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can I train the Yolov8 using tensors or bytes or images directly instead of using a yaml file with defined data path as I want to connect the model to database which will bring data in real time & train or test it

**Comment by glenn-jocher** [comment]
@vishnusharma03 hello! While YOLOv8 typically trains models using datasets defined in a YAML file, training directly from tensors or bytes when pulling data from external sources like MongoDB isn't the standard workflow we support out of the box. However, you can achieve this by implementing a custom data loader that retrieves your data from MongoDB, converts it to the appropriate format, and integrates with the YOLOv8 training loop.

For your use case, you would need to write a script that interfaces with your database, performs any necessary preprocessing to convert your data into tensors, and then feeds those into the model for training or validation. Keep in mind that this requires a good understanding of how YOLOv8 expects the data to be formatted and how the training process works.

If you're looking to frequently update your model with new real-time data, you may also explore approaches like incremental learning or continuous learning, though these strategies go beyond the basic usage of YOLOv8 and would require custom implementation. Remember to carefully manage the balance between model stability and incorporating new data.

Refer to our documentation for more information on the standard training and validation processes. Good luck with your project! 😊🚀

**Comment by vishnusharma03** [comment]
Thank You for the suggestion, much appreciated

**Comment by glenn-jocher** [comment]
@vishnusharma03 You're welcome! If you have further questions or need assistance as you progress, don't hesitate to reach out. Happy coding and best of luck with your project! 😊👍
