### ISSUE TITLE
Using GPU for training, excessive CPU utilization becomes a bottleneck

### ISSUE THREAD

**Issue by wjzh159-0301** [ultralytics/ultralytics#7134]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When using YOLOv8 for model training, the GPU utilization is low. The reason for the investigation may be that the CPU takes a lot of time to preprocess. My GPU is 2080Ti, and the CPU is Intel (R) Xeon (R) CPU E5-2678 v3. I would like to know if it is due to my unreasonable experimental configuration or other reasons.
![3](https://github.com/ultralytics/ultralytics/assets/61640535/b62799e7-5e5d-416a-b6f8-a36aba2e481f)
![2](https://github.com/ultralytics/ultralytics/assets/61640535/40f0e79a-ef28-4c75-8d57-660a1d0f1a8a)
![1](https://github.com/ultralytics/ultralytics/assets/61640535/baef1732-9422-4d86-96ee-e3a6c1e87c97)

**Comment by glenn-jocher** [comment]
@wjzh159-0301 high CPU utilization during model training with low GPU usage is often indicative of a bottleneck in data loading or preprocessing. It's important to ensure that your CPU is able to keep up with the GPU to provide a consistent data stream. Here are some potential ways to mitigate this:

1. **Data Loader Workers**: Increase the number of workers in your data loader if it's set too low. This allows more parallelism in data preprocessing.
2. **Batch Size**: Experiment with the batch size. Sometimes a smaller batch size can reduce CPU load, but this also depends on how effectively your GPU can be utilized.
3. **Input Resolution**: High input resolutions can cause more CPU load during preprocessing. Consider if a change in resolution is feasible for your needs.
4. **Augmentations**: Complex augmentations can be CPU-intensive. Review your augmentation pipeline to pinpoint any potential issues.

Visit our documentation and ensure your setup aligns with recommended practices for training, especially around data loading and preprocessing. Sometimes system-specific constraints may require a balance between the CPU and GPU resources to optimize the training workflow. It's also worthwhile to monitor system performance to uncover any non-ML processes that could be impacting your training. 😊🚀

**Comment by acceleratelch** [comment]
@glenn-jocher  Hi, I'm facing a similar problem.
In my case, I try to train yolov8m for 200 epochs.
batch size is 128, rest configuration is as same as the defult.yaml.
GPU ~ 20G and The CPU utilization rate is particularly high which has already influenced others' experiment.
I wonder whether this is a rensonable phenomenon and what I can do to reduce CPU utilization

**Comment by glenn-jocher** [comment]
@acceleratelch hi there! High CPU utilization with low GPU usage during training can occur if the CPU is struggling to preprocess data quickly enough for the GPU. To reduce CPU load, consider the following:

1. **Reduce Batch Size**: A smaller batch size may lessen the CPU load.
2. **Adjust Workers**: Decrease or increase the number of data loader workers to find a balance that suits your system.
3. **Review Augmentations**: Simplify your augmentation pipeline if it's too complex.

Ensure your system's other processes aren't competing for resources. For more detailed guidance, please refer to our documentation on training best practices. Keep in mind that some level of high CPU usage is normal, but it shouldn't consistently impede other tasks. 😊👍

**Comment by acceleratelch** [comment]
Thanks for your quick reply!   
I see that you mention that Simplify augmentations may work on reducing the CPU utilization.
However, I didn't notice there are any augmentation tricks used in default.yaml(The default configuration in detect task), **since the augment is False.**
Are there any settings refer to data augmentation in yaml file?  Is there any tutorial to data augmentation settings?
Looking forward to your reply.
<img width="410" alt="微信图片_20240105183727" src="https://github.com/ultralytics/ultralytics/assets/127832342/d459fe3f-3b0b-4739-a260-59ecb2e5d58f">

**Comment by glenn-jocher** [comment]
@acceleratelch, if augmentations are already disabled (`augment: False`), then they aren't contributing to CPU load. No additional settings in the YAML file would impact this if augmentations are not being used. For further optimization, consider adjusting the batch size and number of workers as previously suggested. Our documentation provides more insights into training configurations and system performance tuning. 😊📚
