### ISSUE TITLE
TensorRT - multiple streams

### ISSUE THREAD

**Issue by geiche735** [ultralytics/ultralytics#7135]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I am trying to use TensorRT to speed up inference on multiple streams at once. I have it working on a single stream but when I try to predict using the typical YOLOv8 method of passing in a source text file with 8 streams, I get the following error:

AssertionError: input size torch.Size([8, 3, 1920, 1920]) not equal to max model size (1, 3, 640, 640)

As the engine is only configured for 1 stream, is there a way to configure it for multiple without using say the Deepstreams YOLO implementation? As that would require switching to Linux which I would like to avoid at the moment, if possible.

**Comment by geiche735** [comment]
Closing. I needed a batch=8 in the arguments for generating the engine.

**Comment by glenn-jocher** [comment]
@geiche735 glad to hear you've resolved the issue! For future reference and others who might encounter the same challenge, remember that specifying the batch size is crucial when generating TensorRT engines, especially when dealing with multiple streams. The capabilities of YOLOv8 allow for flexibility in handling multiple input streams, as long as the engine is configured correctly for the intended workload. Don't hesitate to reach back out if you have more questions or need further assistance. Happy coding! ✨🚀

**Comment by xzlhcx** [comment]
@geiche735 hi. Did you run batch=8 inference? Is there any time difference between running batch8 infer or batch1 infer 8 times.

**Comment by glenn-jocher** [comment]
@xzlhcx, running inference with batch=8 can be more efficient than running batch=1 inference 8 times due to better utilization of the GPU resources. The time difference can be significant, as batching allows for parallel processing of the images, reducing the per-image processing time. However, the actual time savings can vary based on the specific hardware and model configuration. It's always a good idea to benchmark both approaches in your environment to see which performs best for your needs. 🚀💡

**Comment by pinoc5** [comment]
> Closing. I needed a batch=8 in the arguments for generating the engine.

Hi @geiche735 , having the same issue but generating the TRT with the following command did not work, did I misunderstood where to use the batch=8 argument? my command => yolo export model=myModel.pt format=engine imgsz=640 half=True batch=8 device=0 Thanks

**Comment by glenn-jocher** [comment]
Hi @pinoc5, it looks like you're on the right track! However, ensure that the `batch=8` argument is correctly recognized by the YOLOv8 export process. It's possible specific versions or configurations might handle arguments differently. Here's a slightly modified version of your command that should work:

```bash
yolo export model=myModel.pt format=engine imgsz=640 half=True device=0 --batch-size 8
```

Note: if `--batch-size` doesn't work, sticking with `batch=8` as you've done is the next best step. If issues persist, ensure your YOLOv8 installation is up-to-date, as support for batched inference might vary across versions. Let us know how it goes! 🚀
