### ISSUE TITLE
If it´s possible i woul´d love to see Re identification (reid) in yolov8

### ISSUE THREAD

**Issue by Rasantis** [ultralytics/ultralytics#7137]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

This module should enhance YOLOv8's ability to not only detect but also reidentify individuals across different frames or camera feeds. or even detect if someones get out of the video frame and then back... could even implement inside of Vision eye mapping feature

### Use case

Retail Security: In retail environments, the ability to track and reidentify individuals can help in detecting and preventing shoplifting or unauthorized access to restricted areas.

distinguish employees from customers

Employee Efficiency Analysis: In retail or manufacturing environments, distinguishing between employees and customers allows for the analysis of employee efficiency, task completion times, and movement patterns, leading to optimized workflows and better resource allocation.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Rasantis thank you for your interest and suggestion regarding Re-identification (ReID) capabilities in YOLOv8. We appreciate users like you who contribute ideas for enhancing our model's functionality! 🌟

As of now, ReID is not a built-in feature of YOLOv8. The current focus of YOLOv8 is on object detection, segmentation, classification, and pose/keypoint estimation. However, your use case scenarios for retail security, employee-customer distinction, and efficiency analysis are interesting and highlight the utility of such a feature.

We encourage you and the community to explore possibilities for integrating ReID with YOLOv8 as a custom extension. Contributions are always welcome, but if you're not prepared to submit a PR, we'll definitely keep track of this suggestion for potential future enhancements. Tracking improvements are constantly on our radar. 🚀

For more detailed documentation on what YOLOv8 currently offers, you can explore the specialized sections on our [Ultralytics Docs](https://docs.ultralytics.com).

Once again, thank you for your contribution, and let's keep making YOLOv8 even better together! 🤝
