### ISSUE TITLE
how to use multi threading for inference on multiple video streams 

### ISSUE THREAD

**Issue by Umraz-Hussain-MyWorld** [ultralytics/ultralytics#7139]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Dear ultralytics Team,

I am currently using YOLOv8 for detecting humans in multiple video streams. In my case, I am processing 10 video streams simultaneously to expedite the process. From all 10 videos, I am solely detecting humans and extracting the human-detected boxes.

Now, I am seeking guidance on how to process all 10 videos in parallel and run inference. I would greatly appreciate it if you could provide a sample code or any instructions on how to achieve this. **(I want to use multi-threading using dask)**

Thank you for your assistance.

Sincerely,
Umraz Hussain

### Additional

I want to use Dask threading here

**Comment by glenn-jocher** [comment]
@Umraz-Hussain-MyWorld hello Umraz,

Great to hear you're applying YOLOv8 to multi-stream human detection!

To run inferences in parallel across multiple video streams, you can utilize multithreading or multiprocessing in your Python environment. While we don't provide explicit code examples, here's a general approach:

1. Set up individual threads or processes in your Python application.
2. For each thread, load the YOLOv8 model using the standard loading procedure.
3. Process each video stream in its dedicated thread by sending frames to the model's `predict` function.
4. Collect the results from each thread as they complete processing.

Remember that the GIL (Global Interpreter Lock) in Python may limit the speedup gained from multithreading, so multiprocessing might be a better fit for CPU-bound tasks.

Regarding Dask, you can create a Dask `ThreadPool` and map your inference function across the video streams. Ensure your environment is properly configured to handle the concurrent workloads.

Please consult the YOLOv8 documentation for more detailed instructions on using the `predict` mode and explore Python's threading/multiprocessing or Dask's documentation for specifics on these parallel execution frameworks.

The Ultralytics team wishes you success with your human detection project! 😊

**Comment by Umraz-Hussain-MyWorld** [comment]
Hi @glenn-jocher, 

thank you for the prompt response and your suggestions. I have followed your recommendations and attempted to apply them independently to each thread. However, it has proven to be quite costly, and I am encountering a code dump error (segmentation error).

![image](https://github.com/ultralytics/ultralytics/assets/74203625/a448c6c6-1fdf-4d80-ba0f-bf39e2993094)

**Comment by Umraz-Hussain-MyWorld** [comment]
I'm using yolov8m which uses around 5GB of GPU, so in my case **10 threads = 5GB * 10  = ~50GB GPU** 

My system Config is below:
RAM: 64GB
cores: 16
GPU: RTX 3090

**Comment by glenn-jocher** [comment]
@Umraz-Hussain-MyWorld hello again!

When running multiple inference threads each with a loaded YOLOv8 model, it's crucial to account for the combined GPU memory usage. As running 10 instances of a model that requires 5GB each indeed demands approximately 50GB of GPU memory, it would exceed the capacity of an RTX 3090, which typically has 24GB.

To address the GPU memory constraint, you have a few options:

1. Run fewer video streams in parallel to ensure the total memory required does not exceed your GPU's capacity.
2. Use a model with a smaller footprint, if available, that still meets your accuracy needs.
3. If processing is not time-sensitive, consider queueing the videos and processing them sequentially or in smaller batches.

In case the segmentation fault persists, it might not be related to memory issues alone; it could stem from incorrect threading implementation or issues within the model loading process.

Reduce the workload to fit within your GPU's memory and review your multithreading/multiprocessing setup to ensure safe parallel execution. Remember to follow Python best practices for concurrency to prevent segmentation faults.

Warm regards and best of luck with your stream processing!

**Comment by Umraz-Hussain-MyWorld** [comment]
Hi @glenn-jocher ,

I am following all threading standards and approaches. I also tried using the ONNX format, but I am facing the same issue. Therefore, I have concluded that YOLOv8 is not useful in my test case because the main task here is processing time parallelism. Previously, I was using YOLOv7 with the darknet format (i.e., .weights and .cfg files), and it was working perfectly fine. I was considering adopting YOLOv8 due to its performance.

If YOLOv8 is available in darknet format, I would like to test it to see if it also encounters the same issue. However, I have been unable to find YOLOv8 in darknet format. if any suggestions here would be a great help. 

Thank you for your time and suggestions.

**Comment by glenn-jocher** [comment]
@Umraz-Hussain-MyWorld hello,

YOLOv8 is designed for efficiency and performance, but currently, it does not come in the darknet format. If threading with YOLOv8 in its native or ONNX format isn’t aligning with your hardware constraints, you may consider the following:

1. Use a smaller YOLOv8 model variant that fits your GPU memory when multiplied by the number of streams.
2. Process the streams in a sequence or smaller batches that fit your GPU capacity.
3. Optimize your current YOLOv8 pipeline to ensure that memory is managed efficiently.

We encourage you to continue to observe best practices in multithreading and explore ways to optimize your GPU usage for parallel processing.

Thank you for considering YOLOv8, and we hope you find a configuration that works for your needs.

Best regards.

**Comment by Umraz-Hussain-MyWorld** [comment]
Thank you @glenn-jocher 


Closing the issue

**Comment by glenn-jocher** [comment]
You're welcome, @Umraz-Hussain-MyWorld-MyWorld. If you have any more questions in the future, feel free to reach out. Good luck with your project! 👍

Issue closed.
