### ISSUE TITLE
How to modify the backbone section in yaml for better performance on detecting small object

### ISSUE THREAD

**Issue by jet-c-21** [ultralytics/ultralytics#7142]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am planing to start to modify the backbone section in [yolov8.yaml](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/models/v8/yolov8.yaml), my intension is to increase the resolution of each layer, but I don't know how to modify the yaml.

My task is detecting object around 25 x 25 in a 3840 * 2160 image

**Comment by glenn-jocher** [comment]
@jet-c-21 to enhance small object detection performance, you can modify the backbone of the YOLOv8 model to increase the resolution at each layer. This involves tweaking the configuration in the model's YAML file. You will want to experiment with altering the number of layers, layer sizes, and possibly introducing skip connections to retain fine-grained features that are beneficial for detecting small objects.

Consider these steps:
1. Increase layer resolutions by lowering the stride or enlarging the kernel size in the early convolutional layers to maintain higher spatial resolution for longer in the network.
2. Introduce additional connections between layers (e.g., residual connections) to facilitate feature reuse.
3. Upsample earlier features and concatenate them with deeper layers (similar to an FPN structure) to enrich the feature maps with fine details.
4. Be mindful of the computational cost – higher resolution layers increase memory and computation requirements.

As you refine the backbone configuration, remember to monitor the model's performance on a validation set that contains small objects, and iteratively adjust the architecture for the best trade-off between accuracy and efficiency.

Happy coding, and best of luck with your object detection task! 🚀😊

**Comment by jet-c-21** [comment]
Original backbone setting of `yolov8.yaml` :
```yaml
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9
```

First, I try to increase the repeat argument and decrease the stride:
```
backbone:
  # [from, repeats, module, args]
  - [-1, 6, Conv, [64, 3, 1]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 1]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9
```

I meet following bugs:
```python
Traceback (most recent call last):
  File "/home/puff/my_home/target_project/AIBR-DSB/train_gpl_nano.py", line 39, in <module>
    model = YOLO(str(model_yaml_path), task='detect')
  File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/model.py", line 104, in __init__
    self._new(model, task)
  File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/model.py", line 137, in _new
    self.model = TASK_MAP[self.task][0](cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 243, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in forward(torch.zeros(1, ch, s, s))])  # forward
  File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 242, in <lambda>
    forward = lambda x: self.forward(x)[0] if isinstance(m, (Segment, Pose)) else self.forward(x)
  File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 45, in forward
    return self.predict(x, *args, **kwargs)
  File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 62, in predict
    return self._predict_once(x, profile, visualize)
  File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 82, in _predict_once
    x = m(x)  # run
  File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/modules/conv.py", line 38, in forward
    return self.act(self.bn(self.conv(x)))
  File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [16, 3, 3, 3], expected input[1, 16, 256, 256] to have 3 channels, but got 16 channels instead
```

**Comment by glenn-jocher** [comment]
@jet-c-21 the error message "expected input to have 3 channels, but got 16 channels instead" suggests there's a mismatch between the number of input channels expected by the convolutional layer and the actual number of input channels provided.

When you increase the repeats argument from 1 to 6 for the first Conv layer, this modification also requires you to ensure the subsequent layers match the correct input dimension. If a convolution expects 3 input channels but receives 16, it indicates that the layer configuration does not align with the modified architecture of the backbone.

Please carefully check the 'from' keys in your YAML file, which determine the input tensors to each layer, especially after increasing the number of repetitions. Adjusting the strides, filters and ensuring continuity in the channel dimensions while preserving feature map sizes throughout the backbone stages is crucial to maintaining a functional architecture. When dealing with small objects, reconsider the balance between computational resources and performance, and evaluate other strategies mentioned in our documentation under guidelines for small object detection.

**Comment by jet-c-21** [comment]
how can I debug to print each layer's input and output? which python file should I modify to log the detail of each layer?

**Comment by glenn-jocher** [comment]
@jet-c-21 you can insert print statements in the `forward` methods of the convolutional layer classes within the model definition Python files to log inputs and outputs of each layer. Specifically, look into the `forward` method of the base module class (`nn.Module`) where custom layers are defined and modify as required to print the shapes or tensor values as they pass through. If your model is structured with naming conventions, you can also print layer names alongside the tensor information for clarity. Remember to remove or comment out these debug statements once you have finished debugging to avoid performance degradation due to excessive logging. 😊🛠️

**Comment by jet-c-21** [comment]
I am trying to understand the src code before I truly modified the layer, I want to ask some questions about the function `parse_model` in `nn.task.py`, at line 698:

How can I understand the variable `c1` and `c2`:
```python
c1, c2 = ch[f], args[0]
```

**Comment by glenn-jocher** [comment]
@jet-c-21-21, in the `parse_model` function within `nn/task.py`, the `c1` and `c2` variables represent the number of input channels and output channels, respectively, for a particular layer in the model architecture.

- `c1` (input channels) is fetched by indexing the `ch` list using `f`, where `f` is the index designating from which previous layer (or feature map) the current layer is receiving its input.
- `c2` (output channels) is obtained from the `args` list, which holds arguments specific to the layer definition in the model's YAML file.

This parameter setup is part of the dynamic definition of layers and their connections, which are specified in the YAML configuration.🔍🧠

**Comment by jet-c-21** [comment]
@glenn-jocher, thanks for your explaination, it's very clear.

I have some questions about the comment in the head section in the yaml:

```yaml
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 12

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 21 (P5/32-large)

  - [[15, 18, 21], 1, Detect, [nc]]  # Detect(P3, P4, P5)
```

it writes `P3/8-small`, `P4/16-medium`, `P5/32-large`, what does small medium and large mean here?

I hope they are representing the size of the feature in the input image

**Comment by glenn-jocher** [comment]
@jet-c-21-21, indeed, the terms 'small', 'medium', and 'large' in the head section of the YOLOv8 configuration file refer to the size of the objects that the corresponding layers of feature maps are designed to detect. 

- `P3/8-small` designates feature maps responsible for detecting small objects.
- `P4/16-medium` designates feature maps for detecting medium-sized objects.
- `P5/32-large` designates feature maps aimed at detecting large objects.

This multi-scale approach allows the model to effectively detect objects of various sizes across its feature maps. 😊🔍

**Comment by jet-c-21** [comment]
@glenn-jocher That's a great news! I tried to only keep the small object parts in the model. I tried to follow the existed logic to edit the yaml file. I want to ask if I am on the right track.

My custom model yaml: (Hope someone can read the comment and correct them if needed)
```yaml
backbone:
  # [from, repeats(*depth_multiple), module, args]
  # Conv Args: [out_ch(*width_multiple), kernel_size, stride]
  - [-1, 1, Conv, [64, 3, 2]]  # 0 P0/2
  - [-1, 1, Conv, [128, 3, 2]] # 1 P1/4
  - [-1, 1, Conv, [128, 3, 2]]  # 2 P2/8

  - [-1, 8, C2f, [128, True]] # 3
  - [-1, 1, Conv, [256, 3, 2]]  # 4 P3/16

  - [-1, 3, C2f, [256, True]] # 5
  - [-1, 1, Conv, [512, 3, 2]]  # 6 P4/32

  - [-1, 2, C2f, [512, True]] # 7
  - [-1, 1, SPPF, [1024, 5]]  # 8

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']] # 9
  - [[-1, 4], 1, Concat, [1]]  # 10 cat backbone P3
  - [-1, 3, C2f, [256]]  # 11 (P3/8-small)
  - [[11], 1, Detect, [nc]]  # Detect(P3)
```
I add an additional Conv block `#1`, and I counted the layer index of the head C2f, found that it is `#11`. So I modify the last block to `[11]`, did I miss anything here?

**Comment by glenn-jocher** [comment]
@jet-c-21-21-21, your custom YAML looks focused on small object detection with a backbone designed to retain higher-resolution features and a detection head targeting the small feature map from P3/8. 

You're on the right track with the modifications. To reiterate, ensure your detection head receives the correct layer output by correctly indexing the feature maps. If layer `#4` is your intended output layer for small object detection, ensure your `[[-1, 4], ...]` concatenation references are accurate. 

Keep in mind that these changes will shift the balance of your model towards detecting small objects at the cost of less focus on medium and large objects, which is suitable if small objects are your primary interest. 🛠️😊

**Comment by ohj666** [comment]
> Thanks for ur reply @glenn-jocher !
> 
> I am trying to train my model under scale , and I want to modify the first layer of backbone.`n`
> 
> The Original backbone setting of :`yolov8.yaml`
> 
> ```yaml
> backbone:
>   # [from, repeats, module, args]
>   - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
>   - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
>   - [-1, 3, C2f, [128, True]]
>   - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
>   - [-1, 6, C2f, [256, True]]
>   - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
>   - [-1, 6, C2f, [512, True]]
>   - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
>   - [-1, 3, C2f, [1024, True]]
>   - [-1, 1, SPPF, [1024, 5]]  # 9
> ```
> 
> First, I try to increase the repeat argument and decrease the stride:
> 
> ```yaml
> backbone:
>   # [from, repeats, module, args]
>   - [-1, 6, Conv, [64, 3, 1]]  # 0-P1/2
>   - [-1, 1, Conv, [128, 3, 1]]  # 1-P2/4
>   - [-1, 3, C2f, [128, True]]
>   - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
>   - [-1, 6, C2f, [256, True]]
>   - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
>   - [-1, 6, C2f, [512, True]]
>   - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
>   - [-1, 3, C2f, [1024, True]]
>   - [-1, 1, SPPF, [1024, 5]]  # 9
> ```
> 
> I meet following bugs:
> 
> ```python
> Traceback (most recent call last):
>   File "/home/puff/my_home/target_project/AIBR-DSB/train_gpl_nano.py", line 39, in <module>
>     model = YOLO(str(model_yaml_path), task='detect')
>   File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/model.py", line 104, in __init__
>     self._new(model, task)
>   File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/model.py", line 137, in _new
>     self.model = TASK_MAP[self.task][0](cfg_dict, verbose=verbose and RANK == -1)  # build model
>   File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 243, in __init__
>     m.stride = torch.tensor([s / x.shape[-2] for x in forward(torch.zeros(1, ch, s, s))])  # forward
>   File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 242, in <lambda>
>     forward = lambda x: self.forward(x)[0] if isinstance(m, (Segment, Pose)) else self.forward(x)
>   File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 45, in forward
>     return self.predict(x, *args, **kwargs)
>   File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 62, in predict
>     return self._predict_once(x, profile, visualize)
>   File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 82, in _predict_once
>     x = m(x)  # run
>   File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
>     input = module(input)
>   File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/modules/conv.py", line 38, in forward
>     return self.act(self.bn(self.conv(x)))
>   File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
>     return self._conv_forward(input, self.weight, self.bias)
>   File "/home/puff/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
>     return F.conv2d(input, weight, bias, self.stride,
> RuntimeError: Given groups=1, weight of size [16, 3, 3, 3], expected input[1, 16, 256, 256] to have 3 channels, but got 16 channels instead
> ```
> 
> However, if repeat args is , there's no error, I don't know why`<=``4`

Hey friends, I also encountered this problem, why when my repeats are less than or equal to 4, the code runs normally, but the GFLOPs do not send changes. But when it is greater than 5, your error will appear. Do you have any ideas or methods to solve it? Thank you.

**Comment by glenn-jocher** [comment]
@ohj666 hello! It seems like you're encountering a channel mismatch error when modifying the first layer's repeat argument in the backbone. This error typically occurs when the number of output channels from one layer does not match the expected number of input channels for the subsequent layer.

When you increase the `repeats` argument, you're effectively adding more convolutional layers with the same number of input and output channels as defined by the first layer in the sequence. If the subsequent layers expect a different number of input channels, you'll encounter this error.

The reason you don't see an error with `repeats` less than or equal to 4 could be due to the model architecture still being compatible with the rest of the network. However, once you exceed a certain threshold (in this case, 4), the architecture becomes incompatible, leading to the error you're seeing.

To resolve this, you'll need to ensure that the output channels of the last repeated layer match the expected input channels of the following layer. This might involve adjusting the `args` of the subsequent Conv or C2f layers to accept the correct number of input channels.

Keep in mind that significant changes to the model architecture can also affect the model's performance and computational requirements, so it's important to test and validate your changes thoroughly.

**Comment by jet-c-21** [comment]
@glenn-jocher for the debugging purpose, i'd like to run the training process first on CPU, how can I set the device as cpu?

**Comment by glenn-jocher** [comment]
@jet-c-21, to train on the CPU, you can set the device to 'cpu' in your training script by specifying `--device cpu` when running your training command. Ensure that your environment is set up correctly to perform training without a GPU. Keep in mind that training on the CPU will be significantly slower compared to using a GPU. Happy debugging! 😊👨‍💻

**Comment by ohj666** [comment]
> @ohj666 hello! It seems like you're encountering a channel mismatch error when modifying the first layer's repeat argument in the backbone. This error typically occurs when the number of output channels from one layer does not match the expected number of input channels for the subsequent layer.
> 
> When you increase the argument, you're effectively adding more convolutional layers with the same number of input and output channels as defined by the first layer in the sequence. If the subsequent layers expect a different number of input channels, you'll encounter this error.`repeats`
> 
> The reason you don't see an error with less than or equal to 4 could be due to the model architecture still being compatible with the rest of the network. However, once you exceed a certain threshold (in this case, 4), the architecture becomes incompatible, leading to the error you're seeing.`repeats`
> 
> To resolve this, you'll need to ensure that the output channels of the last repeated layer match the expected input channels of the following layer. This might involve adjusting the of the subsequent Conv or C2f layers to accept the correct number of input channels.`args`
> 
> Keep in mind that significant changes to the model architecture can also affect the model's performance and computational requirements, so it's important to test and validate your changes thoroughly.

Thank you reply.
After reading the document and issue, I found that args is related to width, so when it is 4, I use nx0.25 or 1 (I didn’t read the information before asking the question~~~), but I found a new problem. When I use the L model When I modified the network, the GFLOPs dropped. The modified network is as follows

# Parameters
nc: 80  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]  # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024]  # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768]   # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512]   # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512]   # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # **0-P1/2**
  - [-1, 1, Conv, [64, 3, 2]]  # add this layers
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 7], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 12

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 5], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 13], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 10], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 21 (P5/32-large)

  - [[16, 19, 22], 1, Detect, [nc]]  # Detect(P3, P4, P5)

**Comment by glenn-jocher** [comment]
@ohj666, the drop in GFLOPs after adding a layer with fewer channels (`64` instead of `128`) is expected because GFLOPs is a measure of computational complexity, and fewer channels generally mean less computation. When you modify the network, especially by changing the number of channels, it directly impacts the computational load. 

To maintain or increase GFLOPs while still achieving your goal, consider the impact of each layer's channel count and the computational cost it introduces. Ensure that the modifications align with your objectives, whether it's to reduce complexity or to enhance the model's ability to detect certain features. Remember to validate the performance of your modified model to ensure it meets your requirements.
