### ISSUE TITLE
Default.yaml        and      predictor.py

### ISSUE THREAD

**Issue by Alisoltan82** [ultralytics/ultralytics#7143]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

1 - during my search i realized that i can change the activation function of default yolo. However, I didn’t got the exact steps specially I didn’t notice activation function in the default.yaml, should I create new one? Or just Update the default.yaml

2 - I’m working on a dataset and I want to make a special image preprocessing function by Open-CV and noticed in discussions it’s possible via predictor.py and line #111. But again, I prepared the function and don’t know the exact steps, should I include directly to the im processing lines?

im = im.to(self.device)
        im = im.half() if self.model.fp16 else im.float()  # uint8 to fp16/32
        if not_tensor:
            im /= 255  # 0 - 255 to 0.0 - 1.0
            im = function(im) <- - - -
        return im

Thanks

**Comment by glenn-jocher** [comment]
@Alisoltan82 hello,

1 - To change the activation function in YOLOv8, you don't need to edit the `default.yaml` directly. You can create a custom YAML file that inherits the default settings and override the activation you wish to change. You might be looking for the model's configuration YAML file, where the architecture is defined, which is separate from the `default.yaml`.

2 - For custom image preprocessing in Python, you're on the right track! Create your image preprocessing function and call it where appropriate in `predictor.py`. Just ensure that the preprocessing function accepts the input image tensor and returns the modified tensor as per your requirements. Remember to respect the tensor shape and data type to maintain compatibility with the rest of the pipeline.

Hope that helps, and happy coding with YOLOv8! 🚀

**Comment by Alisoltan82** [comment]
Thanks @glenn-jocher for your instant informative response, appreciated.

**Comment by glenn-jocher** [comment]
@Alisoltan82 you're welcome! I'm glad the information was helpful. If you have any more questions or need further clarification, feel free to reach out. Best of luck with your YOLOv8 project! 😊👍
