### ISSUE TITLE
NMS is not working properly?

### ISSUE THREAD

**Issue by R-N** [ultralytics/ultralytics#7145]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

NMS doesn't seem to be working in some cases. Here I have this detection, which seems fine at a glance.

![image](https://github.com/ultralytics/ultralytics/assets/1442761/92a8acd6-1f24-4f04-996b-d3d01d35cb07)

However, I'm using the data, not the image. I'm using YOLO as a parser to identify the objects, specially the heroes of left and right team. When I check the data, it actually detected 6 heroes on the left.

```
'left_heroes': ['Irithel', 'Gusion', 'Gloo', 'Julian', 'Kadita', 'Claude'],
```

It got an additional Irithel, but it's not visible anywhere on the plotted image! So I checked the bounding boxes and found Irithel and Gusion to be overlapping almost perfectly.

```
[['Irithel', array([     0.1314,     0.30052,    0.063511,     0.10832], dtype=float32)]]
[['Gusion', array([    0.13128,     0.30062,    0.063872,     0.10771], dtype=float32)]]
```

Then I hacked around the plotting code to enable filtering classes. Here I excluded the Gusion class (68) and plot the image.

![image](https://github.com/ultralytics/ultralytics/assets/1442761/ffd77773-5715-402d-89b7-cac693ed4bc6)

There. It's exactly where Gusion is, but with significantly lower confidence. I know I can just raise the confidence threshold, but shouldn't NMS have prevented this?

It doesn't happen often. I've only encountered this twice from 1100 test images. They seem to be only happen on the left? Anyway, here's the other one.

```
left_heroes': ['Fredrinn',
  'X.Borg',
  'Benedetta',
  'Estes',
  'Lesley',
  'Kagura'],
```
```
[['X.Borg', array([    0.13138,     0.42579,    0.063678,     0.10889], dtype=float32)]]
[['Benedetta', array([    0.13134,     0.42611,    0.063495,     0.10816], dtype=float32)]]
```
![image](https://github.com/ultralytics/ultralytics/assets/1442761/828ee4bf-cf12-44d9-839d-481de5e4b051)
![image](https://github.com/ultralytics/ultralytics/assets/1442761/376a3afe-d75a-423e-9ad6-489b9a00b6ac)

### Environment

Ultralytics YOLOv8.0.223 🚀 Python-3.10.12 torch-2.0.0 CUDA:0 (Tesla P100-PCIE-16GB, 16281MiB)
Setup complete ✅ (4 CPUs, 31.4 GB RAM, 5312.3/8062.4 GB disk)

### Minimal Reproducible Example

Sorry there are none. But I can share the notebook
[ml-yolo-2 (6).zip](https://github.com/ultralytics/ultralytics/files/13761124/ml-yolo-2.6.zip)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by R-N** [comment]
Sorry I just remembered NMS only works for the same class

**Comment by glenn-jocher** [comment]
@R-N hello! Your observations about NMS (Non-Maximum Suppression) are correct. NMS operates to eliminate redundancies within the *same* class. Overlapping detections of *different* classes could both be valid, depending on the scenario.

The overlapping detections of heroes with similar bounding boxes could happen if the features are closely related. For such rare cases, you might consider adjusting the confidence threshold or applying additional post-processing tailored to your specific use case.

It's always good to cross-verify with the data, as you've done. Thanks for diving into it, and please let us know if there are any other patterns or recurring issues you identify with NMS in your tests!
