### ISSUE TITLE
"probs" equivalent for detection

### ISSUE THREAD

**Issue by davidhuangal** [ultralytics/ultralytics#7149]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When performing predictions with a classification model, the `Results` object that is returned has information about the class probabilities for a given prediction.

However, this is not the case for the Detect task which has a `probs` value of `None`. How can I get the class probabilities for each bounding box detection (not just the single confidence for the bounding box) when predicting with a Detect model?

**Comment by glenn-jocher** [comment]
@davidhuangal hello! 👋 In YOLOv8's detection tasks, the class probabilities are embedded within the object confidence score itself, which represents the model's confidence that the detected bounding box indeed contains an object of a certain class. Unlike classification tasks where you may get a probability per class, YOLOv8 detection outputs only provide the highest confidence score for the most likely class of each detection.

If you're interested in the underlying class scores that contribute to the final detection confidence, you can access this information by working with the raw model outputs prior to the application of non-maximum suppression (NMS), which selects the best bounding boxes and their associated scores. To explore these raw outputs, you'll need to customize the postprocessing step where NMS is applied to extract per-class scores.

For detailed guidance on how to implement this, you can refer to our documentation at https://docs.ultralytics.com. Please note that this may require a more advanced understanding of the model's structure and postprocessing pipeline.

Happy modeling! 😊🚀
