### ISSUE TITLE
input size torch.Size([1, 3, 640, 640]) not equal to max model size (1, 3, 160, 160)

### ISSUE THREAD

**Issue by Parideboy** [ultralytics/ultralytics#7151]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, as the title says, I'm getting this error when feeding an image to a 160x160 v8 model. The image is of course 160x160.

I've generated the model with the following line of  code in python:

`yolo export model=yolov8n.pt format=engine device=0 half=true imgsz=160 simplify`

This is how I load the image to the model:

```
npImg = np.array(npImg)

# Detecting
results = model(npImg, classes=0, half=True, verbose=False, stream=False)
```

Do I have to convert the image somehow? 
I can use the same image in a 160x160 v5 model and it works perfectly.

**Comment by Parideboy** [comment]
I think I've found the issue. Unlike yolov5, the size has to be specified even in the results.

So, in the code above I had to add the following:

results = model(npImg, **_imgsz=160_**, classes=0, half=True, verbose=False, stream=False)

**Comment by glenn-jocher** [comment]
@Parideboy glad to hear you've identified the solution! 👍 Indeed, with YOLOv8, you need to explicitly specify the `imgsz` parameter when making predictions to ensure the input image is the correct size. Keep that in mind when switching between different YOLO versions or models, and happy detecting with YOLOv8! If you encounter any further issues or have questions, feel free to reach out. Enjoy your YOLOv8 experience! 😊
