### ISSUE TITLE
What should I do if I want to save_txt about occlusion pose keypoints?

### ISSUE THREAD

**Issue by divided7** [ultralytics/ultralytics#7153]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I get the txt like:
x , y, v = 0, 0 ,0
but this keypoint gt label is xxx, xxx, 1
Can I get the keypoint x,y ?

**Comment by glenn-jocher** [comment]
@divided7 if you'd like to save keypoint information such as occlusion pose keypoints with both the `(x, y)` coordinates and visibility flag `(v)`, you will need to modify the part of your code where keypoints are being processed and saved. Ensure that when keypoints are occluded and `(x, y)` are `(0, 0)`, the visibility flag `(v)` correctly reflects this state, such as with a `1` for visible and `0` for not visible if that's your intended schema.

When saving to `.txt`, you should be able to save all three values `(x, y, v)` per keypoint as long as your code captures and writes these values properly. If a keypoint's ground truth label is `(xxx, xxx, 1)`, make sure this information is correctly parsed from your dataset and properly transferred into the txt files.

For further guidance on customizing aspects of data processing in YOLOv8, please refer to the Pose/Keypoint Estimation section in our docs. 📄🔍

And remember, a supportive community and plenty of resources are available if you run into snags. Keep up the great work! 💡🚀
