### ISSUE TITLE
Having trouble detecting bounds for multiple classes, getting very low confidence scores etc.

### ISSUE THREAD

**Issue by SouljaVR** [ultralytics/ultralytics#7155]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! I am currently trying to implement YOLOV8 detection into my C# program but right now it is giving me an issue I cannot wrap my head around. I have been trying for hours to fix it. For some reason I cannot accurately get the bounding information for multiple classes. I can reliably get the first class (0) but anything else is just not outputted. I have attached two screenshots of the issue. First screenshot is the detection from my C# application.

As you can see it only draws a box around the people. Ignore the stacked boxes, I temporarily disabled IOU implementation to add less variables to my issue. The second screenshot is the exact same model, but using yolov8 in python instead. The python output very reliably draws bounds around the entire body and head of the person. But I cannot reliably draw any boxes around peoples heads or boxes for any other class besides 0 in my C# application with my current implementation.

Some help with this would be greatly appreciated. I have asked around on the Ultralytics discord and other places but nobody was able to help me. My exact code for gathering bounding information is below. Thanks again!

```

        private const int IMAGE_SIZE = 640;
        private const int NUM_DETECTIONS = 8400;

        public float ConfidenceThreshold = 0.6f;
        public float classConfidenceThreshold = 0.25f;

        public async Task<List<Prediction>> GetAllDetectionsAsync()
        {
            int detectionBoxSize = 640;
            Rectangle detectionBox = new Rectangle((ScreenInfo.ScreenWidth / 2) - detectionBoxSize / 2,
                                                   (ScreenInfo.ScreenHeight / 2) - detectionBoxSize / 2,
                                                   detectionBoxSize,
                                                   detectionBoxSize);

            Bitmap frame = ScreenGrab(detectionBox);
            CurrentFrame = frame;

            float[] inputArray = BitmapToFloatArray(frame);
            if (inputArray == null) return new List<Prediction>();

            Tensor<float> inputTensor = new DenseTensor<float>(inputArray, new int[] { 1, 3, frame.Height, frame.Width });
            var inputs = new List<NamedOnnxValue> { NamedOnnxValue.CreateFromTensor("images", inputTensor) };
            var results = _onnxModel.Run(inputs, _outputNames, _modeloptions);

            var outputTensor = results[0].AsTensor<float>();

            int numberOfClasses = 10;

            var predictions = new List<Prediction>();

            for (int i = 0; i < NUM_DETECTIONS; i++)
            {
                float objectness = outputTensor[0, 4, i];
                if (objectness < ConfidenceThreshold) continue;

                // Bounding box coordinates
                float x_center = outputTensor[0, 0, i];
                float y_center = outputTensor[0, 1, i];
                float width = outputTensor[0, 2, i];
                float height = outputTensor[0, 3, i];

                float x_min = x_center - width / 2;
                float y_min = y_center - height / 2;
                float x_max = x_center + width / 2;
                float y_max = y_center + height / 2;

                for (int classIndex = 0; classIndex < numberOfClasses; classIndex++)
                {
                    float classProbability = outputTensor[0, 4 + classIndex, i]; // Adjust index based on your output tensor
                    float combinedConfidence = objectness * classProbability;
                    if (combinedConfidence > classConfidenceThreshold)
                    {
                        predictions.Add(new Prediction
                        {
                            Rectangle = new RectangleF(x_min, y_min, x_max - x_min, y_max - y_min),
                            Confidence = combinedConfidence,
                            ClassId = classIndex
                        });
                    }
                }
            }
                return predictions;
        }
```

C# output 

![image](https://github.com/ultralytics/ultralytics/assets/97592971/4e574274-4114-480d-a319-da81f5eb2df3)

Python output

![image](https://github.com/ultralytics/ultralytics/assets/97592971/19d81cb7-bd05-4b46-8809-ac35b5aaaa96)

**Comment by sehrawatushar** [comment]
Hey! I think that you should check "Bounding box coordinates". After looking at your output it seems that you should try with different "Bounding box coordinates" value. 
Hoping that you will find it helpful :)

**Comment by glenn-jocher** [comment]
@sehrawatushar hi there! It looks like there may be an issue with how you're interpreting the model's output tensor in your C# application. Make sure that the indexing of the output tensor matches the expected format of YOLOv8 model outputs. Also, verify that you're applying the correct post-processing steps to convert raw output to actual bounding box coordinates and classes. For further guidance, you could review the post-processing steps detailed in YOLOv8's documentation. Good luck! 🤞

**Comment by jamjamjon** [comment]
@SouljaVR I don't known C#, but I can see that the problem is that you didn't firgure out the YOLOv8 outputs `prediction`.

``` var outputTensor = results[0].AsTensor<float>(); ```
The shape of `outputTensor` should be like `(1, 4 + numberOfClasses, num_anchors)`, if the model input size is `640x640`, the `num_anchor` will be `8400`.   And `4` means `cx, cy, w, h`,  the `numberOfClasses` is each class score(probability). 

You should
1. Get the bbox candidates(class_id, xy_accrodinates, score) from predictions. => `if (outputTensor[0, 4, i] < ConfidenceThreshold) continue`;
2. Perform NMS.
3. Annotate the rest of the candidates.

Note that YOLOv8 outputs has no `objectness` concept. 
No need to do => `float combinedConfidence = objectness * classProbability;`
You should get `class_id` and `class_score` by finding the highest score among the `numberOfClasses`.

**Comment by SouljaVR** [comment]
> @SouljaVR I don't known C#, but I can see that the problem is that you didn't firgure out the YOLOv8 outputs `prediction`.
> 
> `var outputTensor = results[0].AsTensor<float>();` The shape of `outputTensor` should be like `(1, 4 + numberOfClasses, num_anchors)`, if the model input size is `640x640`, the `num_anchor` will be `8400`. And `4` means `cx, cy, w, h`, the `numberOfClasses` is each class score(probability).
> 
> You should
> 
>     1. Get the bbox candidates(class_id, xy_accrodinates, score) from predictions. => `if (outputTensor[0, 4, i] < ConfidenceThreshold) continue`;
> 
>     2. Perform NMS.
> 
>     3. Annotate the rest of the candidates.
> 
> 
> Note that YOLOv8 outputs has no `objectness` concept. No need to do => `float combinedConfidence = objectness * classProbability;` You should get `class_id` and `class_score` by finding the highest score among the `numberOfClasses`.

Thank you so much! This is exactly what I needed to understand. I have now fixed the problem and I am able to get bounds for each class correctly with high confidence scores per class. Thank you for taking the time to help me Jamjamjon.

**Comment by glenn-jocher** [comment]
@SouljaVR glad to hear you've resolved the issue! 🎉 If you have any more questions or run into further challenges, feel free to reach out. Remember, the YOLOv8 docs are there to assist you with details on model outputs and post-processing. Best of luck with your project!
