### ISSUE TITLE
ByteTrack Tracking Outputs vs Detection Outputs

### ISSUE THREAD

**Issue by SwEngine** [ultralytics/ultralytics#7162]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

While using ByteTrack as a tracker, the visualized bounding boxes sometimes do not precisely match the detection results. Are there any methods to assign tracking IDs to detections without altering the bounding box coordinates? I am asking this question because the tracking bounding boxes are sometimes too wide for my specific case.

**Comment by glenn-jocher** [comment]
@SwEngine hello! 👋

When you're using ByteTrack with YOLOv8 for object tracking, it's normal to occasionally see differences between the tracking and detection bounding boxes. ByteTrack optimizes for temporal consistency, which can slightly modify bounding boxes across frames to maintain stable tracking IDs.

There isn't a direct method to assign tracking IDs to detections without potential adjustments to bounding box coordinates, as the tracker may alter these slightly for improved temporal stability. However, you might consider reducing the `--track-buffer` parameter to minimize these adjustments, at a possible cost to track stability.

Adjusting tracker parameters for your specific use case is often an iterative process, balancing the precision of detection with the needs of accurate tracking. Please refer to the Track mode documentation at Ultralytics Docs for customization options.

**Comment by SwEngine** [comment]
Please add an option to not corrupt given bboxes to tracker. @glenn-jocher

**Comment by glenn-jocher** [comment]
@SwEngine, understood! We'll consider your feedback for future updates. Maintaining original bounding box coordinates while assigning tracking IDs is a valid request. For now, tweaking tracker parameters is the best approach to minimize alterations. Thank you for your input! 🚀

**Comment by saicharan2570** [comment]
I am using super vision inbuilt byte tracker for my own detection model. I want to know the tracked bounding boxes for a particular detected object for the next frame. I am unable to find them. Can anyone suggest how to know this?
