### ISSUE TITLE
YOLOV8 in gpu

### ISSUE THREAD

**Issue by tjdwo8577** [ultralytics/ultralytics#7167]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi I'm trying to use GPU on real-time detection

My code below  :  

import cv2
import numpy as np
from ultralytics import YOLO
from math import atan2, degrees
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'using device : {device}')
model = YOLO('명진커넥트/Busbar_hook_best.pt').to(device)

cap = cv2.VideoCapture(1)

while True:
    _, img = cap.read()

    h, w, c = img.shape

    results = model.predict(source=img, save=False, save_txt=False, device="0")
    result = results[0]
    segmentation = []

    bboxes = np.array(result.boxes.xyxy.cpu(), dtype="int")
    class_ids = np.array(result.boxes.cls.cpu(), dtype="int")
    scores = np.array(result.boxes.conf.cpu(), dtype="float").round(2)

    confidence_threshold = 0.9

    max_y = -1
    max_y_point = None

    max_x = -1
    max_x_point = None

    min_x = w
    min_x_point = None
    
    smallest_x_gripPoint = None
    smallest_x = float('inf')
    
    try:
        for seg in result.masks.xyn:
            seg[:, 0] *= w
            seg[:, 1] *= h
            segment = np.array(seg, dtype=np.int32)
            segmentation.append(segment)

        for bbox, class_id, seg, score in zip(bboxes, class_ids, segmentation, scores):
            if score < confidence_threshold:
                continue

            (x, y, x2, y2) = bbox
            cv2.rectangle(img, (x, y), (x2, y2), (255, 0, 0), 2)
            cv2.polylines(img, [seg], True, (0, 255, 0), 2)
            cv2.putText(img, f"{class_id}", (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)

            if class_id == 0:
                max_y_segment = np.argmax(seg[:, 1])
                max_y_point = (seg[max_y_segment, 0], seg[max_y_segment, 1])

                max_x_segment = np.argmax(seg[:, 0])
                max_x_point = (seg[max_x_segment, 0], seg[max_x_segment, 1])

                midpoint_x = (max_x_point[0] + max_y_point[0]) // 2
                midpoint_y = (max_x_point[1] + max_y_point[1]) // 2

                gripPoint = (midpoint_x, midpoint_y)

                cv2.circle(img, (gripPoint), 5, (0, 0, 0), -1)

                if gripPoint[0] < smallest_x:
                    smallest_x = gripPoint[0]
                    smallest_x_gripPoint = gripPoint
                
                print(f"busbar smallest midpoint is : ({smallest_x_gripPoint})")

            else:
                
                min_x_segment = np.argmin(seg[:, 0])
                min_x_point = (seg[min_x_segment, 0], seg[min_x_segment, 1])

                max_x_segment = np.argmax(seg[:, 0])
                max_x_point = (seg[max_x_segment, 0], seg[max_x_segment, 1])

                max_y_segment = np.argmax(seg[:, 1])
                max_y_point = (seg[max_y_segment, 0], seg[max_y_segment, 1])
                
                cv2.circle(img, (max_y_point[0], max_y_point[1]), 5, (0, 0, 255), -1)

                mid_point_x = (min_x_point[0] + max_x_point[0]) // 2

                offset = 20

                hook_point = (max_y_point[0]) - offset

                cv2.circle(img,(mid_point_x, hook_point), 5, (0,0,0), -1)

                print(f" hook point is : ({hook_point})")

    except AttributeError:
        print("detect fail")

    cv2.imshow('img', img)

    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

it works at the beginning but it stop when I move my camera and this error message pops up.

0: 480x640 (no detections), 11.5ms
Speed: 0.0ms preprocess, 11.5ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)
detect fail

Traceback (most recent call last):
  File "c:/Users/JIN/vsworksapce/명진커넥트/cudatest.py", line 29, in <module>
    results = model.predict(source=img, save=False, save_txt=False, device="0")
  File "C:\Users\JIN\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\engine\model.py", line 239, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "C:\Users\JIN\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\engine\predictor.py", line 198, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "C:\Users\JIN\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\JIN\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\engine\predictor.py", line 269, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "C:\Users\JIN\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\models\yolo\segment\predict.py", line 30, in postprocess
    p = ops.non_max_suppression(preds[0],
  File "C:\Users\JIN\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\utils\ops.py", line 238, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
  File "C:\Users\JIN\AppData\Local\Programs\Python\Python38\lib\site-packages\torchvision\ops\boxes.py", line 41, in nms
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
  File "C:\Users\JIN\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

CPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\cpu\nms_kernel.cpp:112 [kernel]
QuantizedCPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\quantized\cpu\qnms_kernel.cpp:124 [kernel]
BackendSelect: fallthrough registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\PythonFallbackKernel.cpp:153 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\functorch\DynamicLayer.cpp:498 [backend fallback]
Functionalize: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\FunctionalizeFallbackKernel.cpp:290 [backend fallback]
Named: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\NegateFallback.cpp:19 [backend fallback]
ZeroTensor: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:86 [backend fallback]
AutogradOther: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:53 [backend fallback]
AutogradCPU: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:57 [backend fallback]
AutogradCUDA: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:65 [backend fallback]
AutogradXLA: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:69 [backend fallback]
AutogradMPS: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:77 [backend fallback]
AutogradXPU: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:61 [backend fallback]
AutogradHPU: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:90 [backend fallback]
AutogradLazy: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:73 [backend fallback]
AutogradMeta: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:81 [backend fallback]
Tracer: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\autograd\TraceTypeManual.cpp:296 [backend fallback]
AutocastCPU: fallthrough registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\autocast_mode.cpp:382 [backend fallback]
AutocastCUDA: fallthrough registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\autocast_mode.cpp:249 [backend fallback]
FuncTorchBatched: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\functorch\LegacyBatchingRegistrations.cpp:710 [backend fallback]
FuncTorchVmapMode: fallthrough registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\functorch\VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\LegacyBatchingRegistrations.cpp:1075 [backend fallback]
VmapMode: fallthrough registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\functorch\TensorWrapper.cpp:203 [backend fallback]
PythonTLSSnapshot: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\PythonFallbackKernel.cpp:161 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\functorch\DynamicLayer.cpp:494 [backend fallback]
PreDispatch: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\PythonFallbackKernel.cpp:165 [backend fallback]
PythonDispatcher: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\PythonFallbackKernel.cpp:157 [backend fallback]

Any suggests for using GPU?

**Comment by glenn-jocher** [comment]
@tjdwo8577 hello! It looks like you're experiencing an issue with GPU acceleration, specifically with the Non-Maximum Suppression (NMS) operation which is part of the postprocessing in object detection. This error typically indicates a mismatch between the installed versions of PyTorch and torchvision, or an incomplete installation that doesn't include CUDA support for torchvision.

Here's what you can do to resolve this:

1. Ensure that your PyTorch and torchvision installations are compatible and support CUDA. PyTorch should have been installed with CUDA support.
2. Confirm that both PyTorch and torchvision are updated to versions that support your CUDA version.
3. Reinstall torchvision with CUDA support if necessary.
4. Ensure that CUDA is properly installed on your system and that the `nvidia-smi` command in the terminal shows the expected output.

Finally, in your code, when you instantiate the YOLO model, you've correctly sent it to the device using `.to(device)`. However, when you call `model.predict`, you shouldn't need to specify the device again as the model is already on the GPU.

Remember that for further issues and usage guidance, you can refer to the Documentation at https://docs.ultralytics.com for more information.

I hope this helps! 🚀
