### ISSUE TITLE
Unable to specify gpu for inference

### ISSUE THREAD

**Issue by sybest1259** [ultralytics/ultralytics#7169]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

There are two predictors in the program, each specifying a GPU for inference, but the second predictor cannot infer on the specified GPU

### Environment

ultralytics==8.0.124
torch==1.7.1+cu110
nvidia-tensorrt==8.4.3.1

### Minimal Reproducible Example

**code:**
from ultralytics.yolo.engine.model import TASK_MAP, YOLO

model_1 = YOLO('./best1.pt', task='detect')
model_1.predictor = TASK_MAP[model_1.task][3](overrides=model_1.overrides.copy(), _callbacks=model_1.callbacks)
model_1.predictor.args.device = '0'

model_2 = YOLO('./best2.pt', task='detect')
model_2.predictor = TASK_MAP[model_2.task][3](overrides=model_2.overrides.copy(), _callbacks=model_2.callbacks)
model_2.predictor.args.device = '1'

model_1.predict('/opt/car.jpg', imgsz=640)
model_2.predict('/opt/car.jpg', imgsz=640)

**Program running results:**
Ultralytics YOLOv8.0.124 🚀 Python-3.8.10 torch-1.7.1+cu110 CUDA:0 (GeForce RTX 2080 Ti, 11019MiB)
Loading /opt/flask_yolov8/App/static/model/yolov8/vehicle/det/best0.engine for TensorRT inference...
[12/26/2023-15:19:23] [TRT] [I] The logger passed into createInferRuntime differs from one already provided for an existing builder, runtime, or refitter. Uses of the global logger, returned by nvinfer1::getLogger(), will return the existing value.
[12/26/2023-15:19:23] [TRT] [I] [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 3058, GPU 2963 (MiB)
[12/26/2023-15:19:23] [TRT] [I] Loaded engine size: 15 MiB
[12/26/2023-15:19:23] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1, GPU +34, now: CPU 3084, GPU 3011 (MiB)
[12/26/2023-15:19:23] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.0.5
[12/26/2023-15:19:23] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
[12/26/2023-15:19:23] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1, GPU +32, now: CPU 3069, GPU 3013 (MiB)
[12/26/2023-15:19:23] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.0.5
[12/26/2023-15:19:23] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
image 1/1 /opt/car.jpg: 640x640 1 driver, 1 plate, 2.3ms
Speed: 2.4ms preprocess, 2.3ms inference, 1.7ms postprocess per image at shape (1, 3, 640, 640)

Ultralytics YOLOv8.0.124 🚀 Python-3.8.10 torch-1.7.1+cu110 CUDA:1 (GeForce RTX 2080 Ti, 11019MiB)
Loading /opt/flask_yolov8/App/static/model/yolov8/vehicle/det/best1.engine for TensorRT inference...
[12/26/2023-15:19:17] [TRT] [I] [MemUsageChange] Init CUDA: CPU +315, GPU +0, now: CPU 393, GPU 1515 (MiB)
[12/26/2023-15:19:17] [TRT] [I] Loaded engine size: 15 MiB
[12/26/2023-15:19:18] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +371, GPU +172, now: CPU 809, GPU 1703 (MiB)
[12/26/2023-15:19:18] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.0.5
[12/26/2023-15:19:18] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
[12/26/2023-15:19:18] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +32, now: CPU 794, GPU 1703 (MiB)
[12/26/2023-15:19:18] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.0.5
[12/26/2023-15:19:18] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
image 1/1 /opt/car.jpg: 640x640 1 driver, 1 plate, 2.3ms
Speed: 4.9ms preprocess, 2.3ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

![git_issue](https://github.com/ultralytics/ultralytics/assets/41052224/687e4671-b034-492a-9de5-c0b119e46340)

model_2 should have used gpu1, but not

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sybest1259 hello! Thanks for providing the detailed information on the issue you're encountering.

The intended functionality is indeed for separate predictors to utilize the specified GPUs independently. Based on your description, the behavior you're experiencing seems unintended.

As an initial check, please verify that each of your GPUs is visible and accessible by running basic PyTorch commands, such as `torch.cuda.device_count()` and `torch.cuda.get_device_name(i)` where `i` iterates over the range returned by `device_count()`.

If everything looks good on the PyTorch side, and you've confirmed it's not a resource contention or a device access issue, I'd recommend updating both PyTorch and the Ultralytics package to their latest versions, if possible, to rule out any fixed bugs or compatibility problems.

In the event that the problem persists, please provide a detailed report on our Ultralytics GitHub issues page so that our team can investigate further. We appreciate your collaboration to improve YOLOv8. Thanks for your efforts, and we're looking forward to resolving this together! 🚀

**Comment by sybest1259** [comment]
Thks. @glenn-jocher 

I have tested according to what you said.
**code:**
import torch
print(torch.cuda.device_count())
for i in range(torch.cuda.device_count()):
    print(torch.cuda.get_device_name(i))

**result:**
4
GeForce RTX 2080 Ti
GeForce RTX 2080 Ti
GeForce RTX 2080 Ti
GeForce RTX 2080 Ti


I got an error after upgrading ultralytics to 8.0.230
ModuleNotFoundError: No module named 'ultralytics.yolo'

**Comment by glenn-jocher** [comment]
@sybest1259 Thanks for the update and for checking the device accessibility and updating your packages.

Given that you've verified the presence of multiple GPUs and have updated your environment, yet the issue persists, it suggests that there might be an underlying issue with the device assignment within the YOLOv8 model's predict method or environment configuration.

I would encourage you to report this behavior with all the details you've provided to our Ultralytics GitHub issues page. This way, our team can take a closer look and provide a solution. Your report will help us to improve YOLOv8 for all users.

Thanks for your patience and assistance! 🌟

**Comment by bigmover** [comment]
> @sybest1259 Thanks for the update and for checking the device accessibility and updating your packages.
> 
> Given that you've verified the presence of multiple GPUs and have updated your environment, yet the issue persists, it suggests that there might be an underlying issue with the device assignment within the YOLOv8 model's predict method or environment configuration.
> 
> I would encourage you to report this behavior with all the details you've provided to our Ultralytics GitHub issues page. This way, our team can take a closer look and provide a solution. Your report will help us to improve YOLOv8 for all users.
> 
> Thanks for your patience and assistance! 🌟

hi glenn-jocher! Whether I can use cpu to do infer even if cuda is avalible.

**Comment by sybest1259** [comment]
Thks. @glenn-jocher 
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/autobackend.py line192

with open(w, 'rb') as f, trt.Runtime(logger) as runtime:
    meta_len = int.from_bytes(f.read(4), byteorder='little')  # read metadata length
    metadata = json.loads(f.read(meta_len).decode('utf-8'))  # read metadata
    model = runtime.deserialize_cuda_engine(f.read())  # read engine

Can this code specify which GPU to use？

**Comment by glenn-jocher** [comment]
@sybest1259 Yes, you can perform inference using the CPU even when CUDA is available. To do so, you'll need to set the appropriate device to `'cpu'` in the model's predictor arguments before running the predict method. This will instruct the model to use the CPU for inference tasks.

Regarding your question about specifying GPU for TensorRT inference, the code you referenced indeed creates a TensorRT runtime for deserialization of the engine. However, to control on which GPU the TensorRT engine runs, you would normally manage the device context externally using PyTorch's `torch.cuda.set_device(device_id)` before this code starts executing, where `device_id` is the ID of the desired GPU.

For more detailed support or code-specific inquiries, please create an issue on the Ultralytics GitHub repository where our development team can provide in-depth assistance. 🛠️

**Comment by sybest1259** [comment]
Thks. @glenn-jocher 
I tried your suggestion and added `torch.cuda.set_device(device_id)` before this part of the code, but a new error occurred

[12/28/2023-08:32:32] [TRT] [E] 1: [convolutionRunner.cpp::execute::213] Error Code 1: Cask (Cask convolution execution)
[12/28/2023-08:32:32] [TRT] [E] 1: [checkMacros.cpp::catchCudaError::278] Error Code 1: Cuda Runtime (invalid resource handle)
0: 640x640 1 brand, 1 plate, 43.1ms
Speed: 12.6ms preprocess, 43.1ms inference, 2.9ms postprocess per image at shape (1, 3, 640, 640)

**Comment by glenn-jocher** [comment]
@sybest1259 It appears that the error you're encountering is related to a CUDA context or resource issue on the TensorRT side. This could occur if there are conflicts in device contexts or if the handle to a certain CUDA resource isn't valid.

I recommend ensuring that your CUDA and TensorRT environments are set up correctly and compatible with each other. Additionally, you might want to check that all GPU resources are appropriately allocated and released during your inference workflow. If the problem persists, please create an issue on our Ultralytics GitHub repository for a more thorough investigation.

Your collaboration helps us to keep improving YOLOv8, and we appreciate your detailed feedback. 🌐🛠️

**Comment by sybest1259** [comment]
Thks. @glenn-jocher 
I solved this problem with multithreading. Specify one GPU per thread.

**Comment by glenn-jocher** [comment]
@sybest1259 Great to hear you've found a solution using multithreading to specify a dedicated GPU per thread! If you encounter any other issues or have further questions, feel free to reach out. Happy coding! 🎉🚀
