### ISSUE TITLE
Very bad prediction

### ISSUE THREAD

**Issue by M-Zubair10** [ultralytics/ultralytics#717]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My image size is 126x126x3, i reshaped it to 128x128x3 and 320x320x3 and 640x640x3 nothing worked

model: yolov8s
It works on images with larger size
yolov5s works on my dataset

I am just making inference from pretrained

**Comment by AyushExel** [comment]
126x126 is too small. Try using larger resolution images

**Comment by knoppmyth** [comment]
Since your model works w/ v5, it might be a good idea to stick with it for now. Not everything is v5 has been implemented in v8 as of yet. [Source](https://www.youtube.com/watch?v=IPcpYO5ITa8)

**Comment by sezer-muhammed** [comment]
You may try use superresolution over training set

**Comment by pderrenger** [comment]
@sezer-muhammed super-resolution training could potentially help enhance the model's performance when working with smaller images. While YOLOv8 is designed to handle larger input sizes more effectively, implementing super-resolution techniques during the training process may improve the model's ability to accurately process smaller images. Feel free to explore this approach to see if it positively impacts your results.
