### ISSUE TITLE
how to add a class label for a key point and how to specify a variable number of points in the config

### ISSUE THREAD

**Issue by Halacky** [ultralytics/ultralytics#7171]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have an image markup where there is a box of one class and key points of 5 classes. There may be a different number of dots on the image. And I don't quite understand how to specify class labels for each point in yolo format. Also in the example there was a kpt_shape field with the value [17,3]. Do I understand correctly that there should be the same number of dots on each photo? If I do not know what is the number of dots I have in the image, what is the first number I need to specify? Also, can I specify the second number, let's say 4 and then I will have, x,y,visible,labels or how should I specify the class label for each point?

**Comment by Halacky** [comment]
I have cars as objects and I have set points for them (left_front, right_front, top, left_back, right_back). And sometimes some of these dots are not visible in the image. As I understand it, each object should have the same number of points. Since it is possible to set the value of visible for a point, I have a question whether the coordinates of the points that are visible are important : 0. or can I just count their coordinates (0,0)?

**Comment by glenn-jocher** [comment]
@Halacky for keypoints associated with objects like cars, you can annotate visible points with their actual (x,y) coordinates. If a keypoint is not visible in an image, you can simply mark it as not visible, using the visible flag. Coordinates for invisible points can be annotated as (0,0) or left at the actual coordinates, depending on your preference; both methods are acceptable as the visibility flag will indicate whether the model should consider those points or not during training. Be consistent with the method you choose throughout your dataset. The `kpt_shape` in the config denotes the maximum number of keypoints you expect for an object and the additional attributes for each keypoint (like visibility), so you can decide on these values based on your use case. Remember, consistency in annotation is the key for accurate keypoint detection models.
