### ISSUE TITLE
Crop the mask from Segmentation results 

### ISSUE THREAD

**Issue by Talhaz** [ultralytics/ultralytics#7177]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

**crop the masks like it does for the bounding bxoes** 

mask is a polygon we can use shapely library to read the polygon 

```
from shapely.geometry import Polygon
import cv2
from ultralytics import YOLO

model=YOLO("yolov8x-seg.pt")
results=model(source="img.jpg")
masks=results[0].masks.xy

for mask in masks:
  # Example polygon coordinates (replace with actual polygon coordinates)
  polygon_coords = mask
  
  # Create a Shapely Polygon object
  polygon = Polygon(polygon_coords)
  
  # Assuming `image` is your original image
  image = cv2.imread('4.jpg')
  
  # Create a mask image with the same shape as the original image
  mask = np.zeros_like(image[:, :, 0], dtype=np.uint8)
  
  # Draw the filled polygon on the mask
  cv2.fillPoly(mask, [np.array(polygon_coords, dtype=np.int32)], color=255)
  
  # Bitwise AND operation to get the cropped region
  cropped_image = cv2.bitwise_and(image, image, mask=mask)
  
  # Display the result
  cv2.imwrite('crop_mask.jpg',cropped_image)
  cv2.imshow('Cropped Image', cropped_image)
  cv2.waitKey(0)
  cv2.destroyAllWindows()
  ```

### Use case

In some cases we have to use masks beacuse bouding boxes always intersects with other boxes and it can damanage the accuracy of the work, 

### Additional

from shapely.geometry import Polygon
import cv2
from ultralytics import YOLO

model=YOLO("yolov8x-seg.pt")
results=model(source="img.jpg")
masks=results[0].masks.xy

for mask in masks:
# Example polygon coordinates (replace with actual polygon coordinates)
polygon_coords = mask

# Create a Shapely Polygon object
polygon = Polygon(polygon_coords)

# Assuming `image` is your original image
image = cv2.imread('4.jpg')

# Create a mask image with the same shape as the original image
mask = np.zeros_like(image[:, :, 0], dtype=np.uint8)

# Draw the filled polygon on the mask
cv2.fillPoly(mask, [np.array(polygon_coords, dtype=np.int32)], color=255)

# Bitwise AND operation to get the cropped region
cropped_image = cv2.bitwise_and(image, image, mask=mask)

# Display the result
cv2.imwrite('crop_mask.jpg',cropped_image)
cv2.imshow('Cropped Image', cropped_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Talhaz hello there! 👋

Thanks for your feature suggestion to crop segmentation masks directly from the YOLOv8 segmentation results. Your approach with the Shapely library and OpenCV seems sound for creating and applying a mask to obtain the cropped region from each segmentation polygon.

Presently, YOLOv8 does not include a built-in function to crop masks, although you can certainly use post-processing procedures, like the one you've described, to achieve this functionality. Your method helps bridge the gap until any potential integration in the future.

We welcome contributions from our community! While you've indicated you're not currently keen on submitting a PR, if you change your mind or if anyone else reading this is inspired to enhance the YOLOv8 library with such a feature, we would be excited to review the updates.

For any further details on YOLOv8 and its capabilities with segmentation, check out the segment task guide in our docs.

Happy coding, and thank you for participating in the YOLOv8 community! 🚀
