### ISSUE TITLE
converting torch model to yolov8 yaml format

### ISSUE THREAD

**Issue by gorkemguzeler** [ultralytics/ultralytics#7178]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I am working on changing the backbone of yolov8 detection model. 

First, i wanted to directly give my torch model (different backbone + yolo detection head) as parameter without having corresponding yaml file which did not work because my model did not have the [from,repeats,..] information or regarding yaml file representing my model. 

Then, I started working on writing the custom yaml file manually but of course it is not straight forward because I am defining new blocks (not present in the modules, blocks files) special to the backbone I would like to integrate. I wonder is there any feature/easy way that converts a pytorch model into the yolov8 yaml file format? Thanks!

Best,

**Comment by glenn-jocher** [comment]
@gorkemguzeler hello!

Transforming a PyTorch model into YOLOv8 YAML format is unfortunately not automated within our framework. However, custom modifications to your backbone and the inclusion of new blocks can indeed be manually added into a YAML file. For doing this, the YAML file will need to define the architecture by enumerating all necessary modules and parameters.

You'll have to define the custom backbone in a similar way to how standard backbones are defined in the existing YAML files included with YOLOv8. Make sure to specify the layers, filters, and any architectural nuances of your model, while adhering to the configuration pattern used by our YOLOv8 models. This requires a thorough understanding of the model architecture and conversion to the appropriate YOLOv8 structure.

If you're innovating with new block types that are not present in YOLOv8, you may also need to integrate the corresponding code within the model definition to ensure it interprets the YAML file correctly.

Refer to our documentation at https://docs.ultralytics.com for guidance on the structure and syntax expected in YAML files for models. Should you encounter any bumps along the way, feel free to reach out on our discussions page for community or team support. Good luck with your custom model! 🚀

**Comment by gorkemguzeler** [comment]
Hi @glenn-jocher, 

Thanks a lot for your reply and good wishes..

**Comment by glenn-jocher** [comment]
You're welcome, @gorkemguzeler! If any more questions arise, don't hesitate to ask. Best of luck with your project! 😊👍
