### ISSUE TITLE
return torch.grid_sampler(input.float(), grid.float(), mode_enum, padding_mode_enum, align_corners)

### ISSUE THREAD

**Issue by DeMar-DeRozan** [ultralytics/ultralytics#7183]
![image](https://github.com/ultralytics/ultralytics/assets/90699640/fccb6431-814d-4aa4-b5fc-ec6fc492e860)

**Comment by glenn-jocher** [comment]
@DeMar-DeRozan hello! It seems you're encountering an issue possibly related to grid sampling in PyTorch. While your snippet and attached image give some context, could you please provide a bit more detailed information on the issue? Specifically, which file or function within the YOLOv8 codebase you're working on, and what behavior or error you are encountering. This will help us understand the context and assist you more effectively.

For general assistance with using YOLOv8 for tasks like training, validation, predictions, or exporting models, don't hesitate to check out our comprehensive documentation at https://docs.ultralytics.com. Thanks for reaching out, and we’re here to help you resolve this! 🚀
