### ISSUE TITLE
Add new angle DFL function - about oriented bounding box (OBB) task

### ISSUE THREAD

**Issue by iscyy** [ultralytics/ultralytics#7187]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Our main goal in solving this problem is to help Oriented Bounding Box (OBB) tasks be trained using the new angle DFL Loss, integrated into our YOLOv8 training pipeline, with a focus on Oriented Bounding Box (OBB) tasks.  From OBB branch

I have completed the functional code for the new angular DFL loss to train the Oriented Bounding Box (OBB) task, and conduct experiments to verify that it has some advantages in some tasks

I can submit a PR to integrate this functionality.

Thanks

@glenn-jocher @Laughing-q 

### Use case

Similar to
![image](https://github.com/ultralytics/ultralytics/assets/24501320/435fbe54-ee2d-4262-bb22-1b615229ad2c)

```python
if self.use_dfl:
target_ltrb = bbox2dist(anchor_points, xywh2xyxy(target_bboxes[..., :4]), self.reg_max)
  ...
```

By passing in parameters
```python
if self.use_angle_dfl:
  ...
```
Instructions for using new functions
![image](https://github.com/ultralytics/ultralytics/assets/24501320/b85c88b4-db64-4be6-9dda-64e292822ac9)

You can use the new angle DFL loss training strategy

It can be controlled as easily as use_dfl, which is in line with the philosophy of Ultralytics

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@iscyy hi there! 👋

It's awesome that you've developed a new angular DFL loss function to enhance OBB tasks with YOLOv8. We're excited to see community contributions that can help improve the library!

If you've already run experiments and found some benefits, we indeed welcome a PR! When submitting, please ensure that your code is well-documented and aligns with the coding style and structure of the existing YOLOv8 repo. It will go through review, and we might discuss potential adjustments to make it fit seamlessly into the pipeline.

Once we see your PR, we and the community will have a better look at your implementation and provide feedback accordingly. Thank you for being willing to contribute and help improve YOLOv8! 🚀
