### ISSUE TITLE
Handle multiple streams with list.streams

### ISSUE THREAD

**Issue by VM8198** [ultralytics/ultralytics#7192]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

If any stream from the list is unreachable, script gets stopped.

### Additional

Hello @glenn-jocher 

I have around 8 streams to work with so I'm using list.streams as a source. Now the issue is sometimes because of connectivity or some other issues, if one of the stream is anyhow not reachable, the script throws Failed to connect error and the script stops to run. 

What I want is if any of the stream is not reachable it should stop running for that partucular stream not all the streams. Meaning the script should run for all other streams and script does not get stopped. Currently if one stream get is unreachable, the whole script gets interupted. 

Is there any direct way to approach this? or have to implement something custom?

**Comment by RizwanMunawar** [comment]
@VM8198 Thanks for providing the detailed information. We will test this internally and update you on the progress.

Thanks
Ultralytics Team!
