### ISSUE TITLE
How to train customized YoloV8 model with video dataset instead of images 

### ISSUE THREAD

**Issue by lenka-79** [ultralytics/ultralytics#7206]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I am able to train customized yolo v8 model with images & yolo.txt as maintain in datasets & detect the objects,
But I need to train the customized model with huge hours of data for our on going activities.
so , if I kept/extract multiple frames of images with in video having huge folder size.

![image](https://github.com/ultralytics/ultralytics/assets/152685134/ca53fc77-62f8-4256-b8b8-3939cd601b1e)

 How to create the customized model with video files as an input instead of images in data base??
I want to maintain video files & yolo.txt(annotated output) as a dataset instead of images & yolo.txt,
can I do/maintain like that??

Regards,
Giri.

**Comment by glenn-jocher** [comment]
@lenka-79 hi Giri,

Training YOLOv8 with video directly isn't supported out of the box. Instead, you should convert your videos into frames (images). Once you've extracted frames, annotate them with bounding boxes in a corresponding `yolo.txt` file (one per frame). 

After prepping your dataset of images and annotations, use the same training process as with image datasets. The model doesn't differentiate between images sourced from videos or other means, as long as they are correctly annotated.

Refer to the Ultralytics Docs for further guidance on the [Train](https://docs.ultralytics.com/modes/train) mode.
