### ISSUE TITLE
[Question] Is it possible to train using 90 classes in YOLOv8?

### ISSUE THREAD

**Issue by soribido** [ultralytics/ultralytics#7208]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Dear Author.
Thank you for great repo.

I want to perform instance segmentation on COCO 90 classes using the yolov8-seg model.
When I run the code below,
```
from ultralytics import YOLO
model = YOLO('./cfg/models/yolov8m-seg.yaml')
result = model.train(data = "cfg/datasets/coco2017-seg.yaml", epochs=3, device=0)
```

The following error occurs:
```
RuntimeError: Dataset 'cfg/datasets/coco2017-seg.yaml' error ❌ '80-class dataset requires class indices 0-79, but you have invalid class indices 0-89 defined in your dataset YAML.'
```

Below is coco2017-seg.yaml.
```
# Classes
names:
  0: person
  1: bicycle
  2: car
  3: motorcycle
  ...
  87: teddy bear
  88: hair drier
  89: toothbrush
```

Below is yolov8m-seg.yaml
```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8-seg instance segmentation model. For Usage examples see https://docs.ultralytics.com/tasks/segment

# Parameters
nc: 90  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n-seg.yaml' will call yolov8-seg.yaml with scale 'n'
  # [depth, width, max_channels]
  m: [0.67, 0.75, 768]

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 12

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 21 (P5/32-large)

  - [[15, 18, 21], 1, Segment, [nc, 32, 256]]  # Segment(P3, P4, P5)
```

Even if nc is set to 90, the head segment is output as 80. If I replace it with a model such as s or l, the number of parameters changes, but it does not seem to overwrite the nc I specified. Is there any way to train 90 classes? (If nc is less than 80, the segmentation head appears to be replaced when executing model.train())

**Comment by glenn-jocher** [comment]
@soribido hello! Thanks for reaching out.

Yes, you can definitely train YOLOv8 on a dataset with 90 classes, such as the full COCO dataset. The error message you're encountering suggests there may be a mismatch between your dataset configuration and the model configuration.

Make sure you specify `nc: 90` in your model configuration file (`yolov8m-seg.yaml`) accurately, and your dataset yaml (`coco2017-seg.yaml`) corresponds to those 90 classes correctly. If the configuration file is set up with 90 classes and the dataset yaml is also consistent with that, you shouldn't face this issue.

Ensure you're editing the correct config files and that your dataset's annotation files indeed contain class indices ranging from 0 to 89. Then try to run `model.train()` again.

If the problem persists, feel free to check our documentation on training for more detailed guidance, and let us know if you face any further issues. Best of luck with your instance segmentation task! 👍

**Comment by soribido** [comment]
Thank you for your answering.

As you can see above, nc:90 is specified correctly in the yaml file.

When I load model using code below,
```
from ultralytics import YOLO
model = YOLO('cfg/models/yolov8m-seg.yaml').load('weights/yolov8m-seg.pt') 
```

The following message is printed.
It appears to have a fixed segmentation head regardless of nc.
```
                   from  n    params  module                                       arguments                     
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]                 
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]                
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]             
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]               
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]           
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]              
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]           
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]              
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]           
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]                 
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]                 
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]                 
 22        [15, 18, 21]  1   5205344  ultralytics.nn.modules.head.Segment          [80, 32, 192, [192, 384, 576]]
YOLOv8m-seg summary: 331 layers, 27285968 parameters, 27285952 gradients, 110.6 GFLOPs

Transferred 537/537 items from pretrained weights
```

**Comment by glenn-jocher** [comment]
@soribido Hello again!

The message you're seeing indicates that the weights file `weights/yolov8m-seg.pt` you're attempting to load is pre-trained with the number of classes set to 80, which is the standard number of classes for COCO. Therefore, even if you've set `nc: 90` in your YAML file, the pre-trained weights have their segmentation head tailored for 80 classes.

To train with 90 classes, you may need to train the model from scratch without loading the pre-trained 80-class weights, as these weights include the classification layers specific to the original number of classes.

By starting the training from scratch, the model will initialize with your updated configuration and respect the `nc: 90` setting in your model's YAML file. This ensures the model's head is adapted to the correct number of classes based on your dataset.

Good luck with your training! If you have any more questions or need further clarification, please let us know. 👍

**Comment by soribido** [comment]
I've already tried training from scratch.
```
from ultralytics import YOLO
model = YOLO('cfg/models/yolov8s-seg.yaml')  
```

The following message is printed.
As you can see, If the model changes m to s, the number of parameters are changed.
But, It appears to have a fixed segmentation head regardless of nc.
```
                   from  n    params  module                                       arguments                     
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]                 
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]             
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]           
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]              
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]           
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]                 
 22        [15, 18, 21]  1   2801504  ultralytics.nn.modules.head.Segment          [80, 32, 128, [128, 256, 512]]
YOLOv8s-seg summary: 261 layers, 11821056 parameters, 11821040 gradients, 42.9 GFLOPs
```

In this situation, if nc in seg.yaml is 1 and there is only one class in the dataset, the segmentation head changes to 1 when executing model.train().
There was no problem when I changed the coco 90 class by matching the class corresponding to the 80 class.
However, if nc>80, an error occurs.
I wonder if there is an error in the code that overwrites internally if nc>80. 
Yolov8 is easy to use because it is a Python package, but it seems to be a little bit difficult to modify (ex. albumentation) or examine the internal logic.

**Comment by glenn-jocher** [comment]
Hello @soribido,

Thank you for the additional details. It appears there may be a specific issue with the model training configuration that requires further examination. Your observation regarding the override behavior for `nc>80` might pinpoint an inherent limitation or a bug in the way the current package handles class numbers beyond the standard COCO dataset size.

If you suspect a code error related to how `nc` is handled, and if it is replicable beyond one-off occurrences, this could warrant a deeper investigation by our development team. I recommend opening a detailed issue on our GitHub repo, articulating the observed behavior along with the steps to reproduce it.

We appreciate your input as it helps improve YOLOv8 for everyone. Thank you for your understanding and patience while we look into this matter. Meanwhile, feel free to explore our documentation for any temporary workarounds or further insights. Your feedback is invaluable to us.
