### ISSUE TITLE
Yolov8 network output parsing with OpenCV ONNX C++

### ISSUE THREAD

**Issue by JustasBart** [ultralytics/ultralytics#721]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi guys,

I've recently got some good feedback from @wvalcke at #671 on how the yolov8.onnx can be parsed via ONNX Runtime, but I'd still like to figure out how to parse the network via OpenCV's DNN API.

That is I need help trying to figure out how to change the following in order to read yolov8 network outputs.
What I currently have is a setup in Qt via OpenCV that looks like this:
```
QVector<Detection> Inference::runInference(const cv::Mat &input)
{
    cv::Mat blob;
    cv::Mat inputImage = formatToSquare(input.clone());

    cv::dnn::blobFromImage(inputImage, blob, 1.0/255.0, modelShape, cv::Scalar(), true, false);
    net.setInput(blob);

    std::vector<cv::Mat> outputs;
    net.forward(outputs, net.getUnconnectedOutLayersNames());
    
    float x_factor = inputImage.cols / modelShape.width;
    float y_factor = inputImage.rows / modelShape.height;

    float *data = (float *)outputs[0].data;

    // Number of Classes + 5
    const int dimensions = outputs[0].size[2];
    // Natural number of the YOLO detections (Usually 25200 @640x640)
    const int rows = outputs[0].size[1];

    std::vector<int> class_ids;
    std::vector<float> confidences;
    std::vector<cv::Rect> boxes;

    for (int i = 0; i < rows; ++i)
    {
        float confidence = data[4];

        if (confidence >= modelConfidenseThreshold)
        {
            float *classes_scores = data + 5;
            cv::Mat scores(1, classes.size(), CV_32FC1, classes_scores);
            cv::Point class_id;
            double max_class_score;

            minMaxLoc(scores, 0, &max_class_score, 0, &class_id);

            if (max_class_score > modelScoreThreshold)
            {
                confidences.push_back(confidence);
                class_ids.push_back(class_id.x);

                float x = data[0];
                float y = data[1];
                float w = data[2];
                float h = data[3];

                int left = int((x - 0.5 * w) * x_factor);
                int top = int((y - 0.5 * h) * y_factor);

                int width = int(w * x_factor);
                int height = int(h * y_factor);

                boxes.push_back(cv::Rect(left, top, width, height));
            }
        }

        data += dimensions;
    }

    std::vector<int> nms_result;
    cv::dnn::NMSBoxes(boxes, confidences, modelScoreThreshold, modelNMSThreshold, nms_result);

    QVector<Detection> detections{};

    for (unsigned long i = 0; i < nms_result.size(); ++i)
    {
        int idx = nms_result[i];

        Detection result;
        result.class_id = class_ids[idx];
        result.confidence = confidences[idx];
        result.color = colors[result.class_id];
        result.className = classes[result.class_id];
        result.box = boxes[idx];

        detections.push_back(result);
    }

    return detections;
}
```

Let's take the **yolov5s.onnx** and **yolov8s.onnx** as an example.

Currently the network expects an output of: float32[1,25200,85]
Where as the yolov8 version would look like this: float32[1,84,8400]

Now I can see that indexes 1 and 2 have been swapped around, but also the output went down from 25200 to 8400, so does that mean that there are extra post-processing steps involved now?

Ultimately I just want to be able to adapt my function **'runInference'** to work with yolov8 based models. And so any explanation or especially code snippets or anything like that would be beneficial for me to mess about, I just need to understand what's changed exactly and then obviously figure out how to read/interpret the new outputs.

Thanks a mil guys :rocket: 

### Additional

Based on #671 @wvalcke was kind enough to provide a functional example: https://github.com/wvalcke/onnxruntimetests.git
But unfortunately I wasn't able to figure out a direct translation towards what I'm doing.

At least now I have that as a backup, but as mentioned I'd still love to be able to do both options and so hence I still need help...

Edit: This issue ties in really well with #350

**Comment by knoppmyth** [comment]
Take a look at #457. I have Python code that works w/ the ONNX output of v5 - v8. Specifically look at `if model == "yolov8":` for how I handle v8. I know a few folks have look at it to get their C++ code working.

**Comment by triple-Mu** [comment]
https://github.com/triple-Mu/YOLOv8-TensorRT，
You can get postprocess code in csrc/detect/norm.
Although this repository is used for tensorrt inference.

**Comment by JustasBart** [comment]
Hi @knoppmyth I have actually seen your Python code during my exploration stages, but there's just some things in it that I cannot quite understand the function of, in particular this line right here:
```
if model == "yolov8":
    preds = preds.transpose((0, 2, 1))
```
Would you be able to comment on what's that meant to be doing?

**Comment by knoppmyth** [comment]
Hi @JustasBart, yes, it reorders the outputted array of the detection so it matches earlier version.

**Comment by JustasBart** [comment]
@knoppmyth So is it only swapping these indexes: **float32[1,84,8400]** to look like this **float32[1,8400,84]** which is a match when compared to yolov5 which is **float32[1,25200,85]** or is it actually swapping the elements within the physical output array?

**Comment by knoppmyth** [comment]
@JustasBart The first.

**Comment by JustasBart** [comment]
@knoppmyth Okay, sorry, yeah, that makes sense, however the issue then is that reading in the dimensions and rows is an easy task:
```
const int dimensions = outputs[0].size[2];
const int rows = outputs[0].size[1];
```
(Literally just swap the two indexes for yolov8)

But the challenge is to normalise this guy to also reflect on this change:

`float *data = (float *)outputs[0].data;`

**Comment by JustasBart** [comment]
Solved it!

[yolov8 / yolov8 inference with C++](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX.git)

@AyushExel @glenn-jocher Feel free to add this to the yolov8 repository as a guide for others :rocket:

**Comment by wvalcke** [comment]
@JustasBart 

Nice to share this implementation, but there is a very inefficient piece of code in inference.cpp.
The transpose of the data is implemented with a dual for loop, making a linear copy of all the data.
This can be easily avoided, use cv:Mat to do the transpose, this is way more efficient as the data looks like copied, but never is. 
In OpenCV they use some clever tricks to avoid the copy, but still be able to walk through a transposed matrix. 
the implementation i've shared does this, have a look and you'll burn less CPU time, always good for the planet :-)

**Comment by JustasBart** [comment]
@wvalcke Yes, I'm aware of it, but the issue that I kept on running into is that I can't transpose a (1, 84, 8400) (3D) Mat with OpenCV in C++, I need to figure out how to reshape to (84, 8400) and then do what you're saying which yes, it would be a lot more efficient and also more simple and nicer to read as well, I'm just excited to have something going for now though but that's the next in line upgrade for it :rocket:

**Comment by jayer95** [comment]
@JustasBart 
Thanks bro, the problem I encountered has been solved by you, and I also agree with transposen[0,2,1]

https://github.com/ultralytics/ultralytics/issues/751#issuecomment-1412332114

**Comment by JustasBart** [comment]
@jayer95 @wvalcke Just tried running inference on a custom trained (10 Class) ONNX exported model and found that it only runs inference on class 0 and nothing else...

**Comment by jayer95** [comment]
@JustasBart Are there no bboxes in other classes (custom class 1~9)?

**Comment by JustasBart** [comment]
@jayer95 Unfortunately so, and even on the default exported models it only detects the class 'Person' hence no tie/bus but it works through the .pt model just fine at the same configuration, I'm reading in the class scores / class ids wrong, so there are still more changes to be made when going from yolov5 to yolov8, I'll try and uncover this ASAP, but yeah it's unfortunate for now, I thought I had already :cry:

**Comment by sonOfAnton29** [comment]
> @jayer95 Unfortunately so, and even on the default exported models it only detects the class 'Person' hence no tie/bus but it works through the .pt model just fine at the same configuration, I'm reading in the class scores / class ids wrong, so there are still more changes to be made when going from yolov5 to yolov8, I'll try and uncover this ASAP, but yeah it's unfortunate for now, I thought I had it already 😢

exactly. I'm trying to figure this out but I'm stuck for now. any progress?

**Comment by jayer95** [comment]
@sonOfAnton29 he has solved.

**Comment by JustasBart** [comment]
Hi @sonOfAnton29 yes, thankfully I was finally able to crack it in the end and now have a sample for running both v5 and v8 models interchangeably. Check it out [here](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX).

**Comment by sonOfAnton29** [comment]
> Hi @sonOfAnton29 yes, thankfully I was finally able to crack it in the end and now have a sample for running both v5 and v8 models interchangeably. Check it out [here](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX).

thank you that was helpful for c++ inference but I still don't understand the general output format of yolov8 onnx. it seems even different exported models produce different outputs (nano, small, ....).

**Comment by JustasBart** [comment]
@sonOfAnton29 I've tried answering that question [here](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX/issues/1), perhaps that might be of any use to you?

Good luck :rocket:
