### ISSUE TITLE
Empty weights folder after tuning

### ISSUE THREAD

**Issue by madhurivenkatesh** [ultralytics/ultralytics#7212]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, we are using YOLO for training and predicting certain classes of images. We recently triedusing hyperparameter Tuning in order to make our model better, using the docs in [](https://docs.ultralytics.com/guides/hyperparameter-tuning/)
The docs say that the best model will be saved in the weights folder as best.pt and last.pt.
However, after tuning, I found the weights folder to be empty.
Is this a bug? or is there something that we are doing wrong.
The tuning code is as follows:
```
from ultralytics import YOLO
model = YOLO("yolov8m.pt")
model.tune(data = "custom_data.yaml", imgsz=1280, epochs=30, iterations=300, optimizer = 'AdamW', plots =False,save=True, val=False, device=[0,1])
```
The code ran, and printed the output as follows:
````
Tuner: 300/300 iterations complete ✅ (6487.68s)
Tuner: Results saved to runs/detect/tune4
Tuner: Best fitness=0.0 observed at iteration 1
Tuner: Best fitness metrics are {}
Tuner: Best fitness model is runs/detect/train605
Tuner: Best fitness hyperparameters are printed below.

Printing 'runs/detect/tune4/best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.0
copy_paste: 0.0
```
So, again, where are the models? Why is the wieghts folder empty?

### Additional

_No response_

**Comment by glenn-jocher** [comment]
@madhurivenkatesh hello! It seems like there might be a bit of confusion with the output directories resulting from hyperparameter tuning. After the tuning process, the model weights won't typically be saved in the `weights` folder. Instead, as indicated by your console output, they are saved in a run-specific directory within the `runs/detect/` folder, which is mentioned as `runs/detect/train605` in your case.

So, to locate your tuned model weights (`best.pt` and `last.pt`), please navigate to the `runs/detect/train605` directory. You should find them there, along with any other related training artifacts. If you have set the `save` flag to `True` during tuning and the runs directory is still empty, this could indicate an unexpected behavior, and further investigation might be necessary.

Make sure to also check if there might have been a permission issue or an interruption during the saving process that could prevent the files from being written.

If these suggestions don't resolve the issue, please share more details or error logs if available, so we can assist you more effectively. 🛠️
