### ISSUE TITLE
Different Inference Output Depending on Backend Choice when Inferencing from ONNX

### ISSUE THREAD

**Issue by dawson-friesenhahn** [ultralytics/ultralytics#7216]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict, Export, Integrations, Other

### Bug

I'm comparing the performance of different versions of YOLO in a c++ application for my research. I've written some software to abstract away some of the pain of parsing ONNX files that differ between versions: https://github.com/dawson-friesenhahn/YOLO_CPP 

I've discovered that when using YOLOv8-Object Detection, I get different results depending on whether I use the CUDA or CPU Backend. 
```
//Excerpt from https://github.com/dawson-friesenhahn/YOLO_CPP/blob/main/src/YOLO_Abstract.cpp
//net is a unique_ptr to a cv::dnn::dnn4_v20230620::Net
if( useCUDABackend ) {
      this->net->setPreferableBackend( cv::dnn::DNN_BACKEND_CUDA ); //these should make things faster, but for some reason v8 obj Detection doesn't work with CUDA? v5 and v8 Pose seem to be working fine. 
      this->net->setPreferableTarget( cv::dnn::DNN_TARGET_CUDA );
   }
   else {
      this->net->setPreferableBackend( cv::dnn::DNN_BACKEND_OPENCV );
      this->net->setPreferableTarget( cv::dnn::DNN_TARGET_CPU );
   }
```
When useCUDABackend is set to true in the code above, I get only one detection, and its located at the top-left of the image (garbage). When not set, the image is detected properly:
![image](https://github.com/ultralytics/ultralytics/assets/35878220/cb897364-be39-4574-b508-83c6223e9821)

I'm exporting with the following command, from my python training script
```
model.export(format='onnx', opset=12, dynamic=False, simplify=True, imgsz=(640,640))
```

Any help is much appreciated!

 

### Environment

Inferencing Environment:
OpenCV4.8.0 with cuDNN - CUDA 12.1.1

Training Environment:
$ yolo checks
Ultralytics YOLOv8.0.227 🚀 Python-3.11.7 torch-2.1.1+cpu CPU (AMD Ryzen Threadripper 3970X 32-Core Processor)
Setup complete ✅ (64 CPUs, 63.9 GB RAM, 3667.6/3725.4 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.11.7
Install             git
RAM                 63.88 GB
CPU                 AMD Ryzen Threadripper 3970X 32-Core Processor
CUDA                None

matplotlib          ✅ 3.8.2>=3.3.0
numpy               ✅ 1.26.2>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 2.1.1>=1.8.0
torchvision         ✅ 0.16.1>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.1.4>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

https://github.com/dawson-friesenhahn/YOLO_CPP/tree/backendErrorDemo

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@dawson-friesenhahn hello! Thanks for your detailed issue report. 

Different inference outputs when switching between CUDA and CPU backends might be related to discrepancies in ONNX export or the backend's ONNX model interpretation. 

For YOLOv8, the ONNX export is optimized and tested primarily for CPU inference. When switching to CUDA, some ONNX layers or CUDA versions may not be fully compatible, causing issues like the one you're experiencing. 

Here's a checklist to troubleshoot the problem:

1. Update OpenCV to the latest version, ensuring compatibility with CUDA.
2. Check that you have the correct cuDNN version for your CUDA setup.
3. Verify that you're using the same pre-processing steps in both CPU and CUDA inference.
4. Confirm that there aren't any known issues with the CUDA backend for the specific OpenCV and cuDNN versions you are using.

Additionally, refer to the ONNX `opset` compatibility with CUDA in the OpenCV documentation. Some `opsets` might have limited or incomplete implementations that could lead to such issues.

I suggest trying to export the model again without the `simplify=True` flag, as this can sometimes introduce subtle changes in the graph that affect inference on different platforms.

If you still face issues, you may want to report this as a potential compatibility bug to OpenCV, particularly if YOLOv8 is the only model causing this discrepancy.

For further guidance, please visit the Predict and Export sections in our docs, and if you have any more insights or questions, don't hesitate to ask for further assistance. Good luck with your research! 🚀
