### ISSUE TITLE
How to make Precision-Recall plot from the result.scv?

### ISSUE THREAD

**Issue by seon-creator** [ultralytics/ultralytics#7218]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I'm using YOLOv8 for instance segmentation.
After training model I get result.scv and many graphs.
From the result, I want to plot Precision-Recall graph.
How to make it?

This is the part of result.scv.
![image](https://github.com/ultralytics/ultralytics/assets/118324988/62fd59c6-eccd-40f6-a677-ea1d5c30a060)

**Comment by glenn-jocher** [comment]
@seon-creator hello! After completing a training run with YOLOv8, the Precision-Recall curve is among the automatically generated plots. If you need to generate this plot from `results.csv` again, or create a customized version, you can utilize the data in `results.csv` which records the precision, recall, and other metrics across epochs.

To produce the Precision-Recall plot, you can use a python script to read the `results.csv` and plot the corresponding columns. Consider using libraries like `matplotlib` for plotting, where you can extract precision and recall values from the `.csv` file to plot them. The curve can be generated by plotting recall on the x-axis and precision on the y-axis for different confidence thresholds.

For detailed instructions on analyzing results and plotting graphs, you may refer to the documentation at https://docs.ultralytics.com. Specifically, check sections under "Tutorials" that deal with results and plotting for more insights.

Keep exploring and happy plotting! 😊📊

**Comment by seon-creator** [comment]
Thank you for your advice!
But from the result.csv these value is calculated by each epoch so the precision-recall plot result strange.
How to find Precision-Recall graph?
Or how to get plot graph from the train result?
This is the result graphs. These graphs has values by each epoch.
![results](https://github.com/ultralytics/ultralytics/assets/118324988/354d4a2d-9db2-496a-8ff2-dfb2f1b24107)

And this is labels graphs.
![labels](https://github.com/ultralytics/ultralytics/assets/118324988/d678c170-7c55-4746-98ae-6f75fa7a14fb)

**Comment by seon-creator** [comment]
Thank you so much! I found

**Comment by glenn-jocher** [comment]
@seon-creator you're welcome! If you have any more questions or need further assistance, feel free to reach out. Happy to help! 😊🚀

**Comment by DanyelR3199** [comment]
> Thank you so much! I found

Where you found it?

**Comment by DanyelR3199** [comment]
> After completing a training run with YOLOv8, the Precision-Recall curve is among the automatically generated plots. If you need to generate this plot from `results.csv` again, or create a customized version, you can utilize the data in `results.csv` which records the precision, recall, and other metrics across epochs.
> 
> To produce the Precision-Recall plot, you can use a python script to read the `results.csv` and plot the corresponding columns. Consider using libraries like `matplotlib` for plotting, where you can extract precision and recall values from the `.csv` file to plot them. The curve can be generated by plotting recall on the x-axis and precision on the y-axis for different confidence thresholds.

I dont get it. How u you extract from the results.csv the precision-recall graph?

**Comment by glenn-jocher** [comment]
Hello! To extract and plot the Precision-Recall graph from `results.csv`, you can use Python along with libraries like `pandas` for data handling and `matplotlib` for plotting. Here's a quick guide:

1. **Load the CSV file using pandas:**
   ```python
   import pandas as pd
   data = pd.read_csv('results.csv')
   ```

2. **Extract the Precision and Recall columns:**
   Assuming your CSV has columns named 'Precision' and 'Recall':
   ```python
   precision = data['Precision']
   recall = data['Recall']
   ```

3. **Plot using matplotlib:**
   ```python
   import matplotlib.pyplot as plt
   
   plt.figure(figsize=(10, 5))
   plt.plot(recall, precision, marker='o')
   plt.xlabel('Recall')
   plt.ylabel('Precision')
   plt.title('Precision-Recall Curve')
   plt.grid(True)
   plt.show()
   ```

This script will generate a simple Precision-Recall curve. Adjust the column names and plot settings as needed based on your CSV file's specific format and your visualization preferences. 📊
