### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by GDbbq** [ultralytics/ultralytics#722]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/86715812/215459336-062fc997-9643-4b2f-845c-623fc63f1381.png)
![image](https://user-images.githubusercontent.com/86715812/215459398-853df428-3bb1-481f-86a7-c4d37d6d4e88.png)
yolo task=detect mode=train model=ultralytics/models/v8/toolbrake_yolov8n.yaml 
 data=ultralytics/yolo/data/datasets/toolbrake.yaml

### Additional

![image](https://user-images.githubusercontent.com/86715812/215459593-5a60366b-d6a7-48cf-9158-c25a3ab2fad2.png)

**Comment by pderrenger** [comment]
@GDbbq it looks like there might be an issue with the training command you are using for YOLOv8. The `yolo task=detect mode=train` command indicates that you are trying to train a YOLOv8 model for detection using a specific configuration file and dataset.

By looking at the provided images, it seems that the error is related to parsing the provided YAML file and possibly a configuration mismatch within the `toolbrake_yolov8n.yaml` file.

To troubleshoot this, I would recommend checking the syntax and content of the `toolbrake_yolov8n.yaml` file to ensure it aligns with the expected format for YOLOv8 configuration files. Additionally, review the `toolbrake.yaml` dataset file to ensure it's properly formatted and accessible from the specified path.

Let me know if you need further assistance with this or if you have any other questions related to YOLOv8!
