### ISSUE TITLE
Mismatched model embeddings for fastsam on different frameworks 

### ISSUE THREAD

**Issue by aman-agar** [ultralytics/ultralytics#7223]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

![image](https://github.com/ultralytics/ultralytics/assets/108113929/5b3ad8bf-7b9b-45db-8140-3ac2c5b39f06)
The above image is a result of the model.embed function in fastsam. The shape of embeddings is 512 using the fastsam-s.pt model. This is however not the same when using the ONNX inference i.e., using fastsam-s.onnx model (exported by ultralytics itself using opset as 13)
![image](https://github.com/ultralytics/ultralytics/assets/108113929/cbc46317-70cb-4380-ab20-d44e5d298efe)
The output is (1,37,8400) for the same image input

### Environment

Ultralytics YOLOv8.0.230 🚀 Python-3.8.18 torch-2.1.2 CPU (Intel Xeon Gold 6226R 2.90GHz)
Setup complete ✅ (15 CPUs, 43.1 GB RAM, 85.5/387.5 GB disk)

## Using .pt model
```from ultralytics.models.fastsam import FastSAM, FastSAMPrompt
model = FastSAM('path/to/model/FastSAM-s.pt')
IMAGE_PATH = 'path/to/images/image.jpg'
embedding = model.embed(IMAGE_PATH)
print(embedding)
```

## Using .onnx model
```model = FastSAM('path/to/model/FastSAM-s.onnx')
IMAGE_PATH = 'path/to/images/image.jpg'
embedding = model.embed(IMAGE_PATH)
print(embedding) 
```
### Additional

Also the embed function was producing some errors with the length of model using the onnx format so I had to explicitly mention the layer number there (21)
![image](https://github.com/ultralytics/ultralytics/assets/108113929/6fc7cfe7-260d-4d7f-92db-d1793c6095eb)

Both the .pt and .onnx function call outputs are based on this change

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@aman-agar hi there! Thanks for the thorough issue report and for ensuring that a similar report was not already filed. 😊

It sounds like you're experiencing a discrepancy in embeddings between the FastSAM model in the .pt format and the ONNX-exported .onnx format. This is indeed unusual, as the intention is for the ONNX model to replicate the .pt behavior as closely as possible.

The difference in shapes and the need to manually specify the layer when using the ONNX model suggest that the export process may not have translated the network precisely, or there may be an issue with the processing logic for the ONNX version. The ONNX standard does have its own set of compatibility considerations, especially when it comes to custom layers and specific functionalities.

Would you mind revisiting the exporting procedure you followed and ensuring that all steps align with our recommended practices in the Export section of the Ultralytics Docs? Additionally, let's check that the ONNX inference code is accessing the appropriate layer for the embedding.

As for the error you mentioned when using the `.onnx` model's `embed` function, it would be beneficial to examine the error details further. It's important for us to understand whether this is a model-specific issue or a more general ONNX incompatibility. If it's a bug, we will need to address it promptly.

For now, let's align the export and inference procedures with our documentation and see if the issue persists. If it does, we may need to dig deeper into the embed function handling between the two formats.

We're here to help, so please keep us posted on your progress!

**Comment by aman-agar** [comment]
@glenn-jocher Thank you for your quick response! I reviewed the export process again and it indeed aligns with the Ultralytics docs. I am adding the export code snippet that i used for the export below
```
from ultralytics import FastSAM
from ultralytics.models.fastsam import FastSAMPrompt
model = FastSAM('FastSAM-s.pt')  # pretrained YOLOv8n model
model.export(format='onnx', opset=13, imgsz=[640,640])
```
Apart from this, during inference, no matter what model layer i specify (i.e., 21, 30, 50 etc.) it always provides an output with the shape [1,37,8400].

**Comment by glenn-jocher** [comment]
Hello again @aman-agar, and thanks for following up with the details of your export procedure. 🛠️ 

It's good to hear that your process aligns with our documentation. The consistency in output shape [1,37,8400] across different specified layers during ONNX inference is quite odd and suggests there might indeed be an issue. Since the issue persists even with the correct export practices, this might require a deeper inspection on our end.

Could you please make sure that you're using the latest version of the Ultralytics YOLOv8 repository and the necessary dependencies? If the issue continues with the latest version, I would encourage you to open a new issue on our repo with these updated details so that our team can further investigate the discrepancy you are noticing. Include any error outputs you're receiving as they might provide valuable clues.

We appreciate you bringing this to our attention, and we'll do our best to get to the bottom of it. Thanks for your patience and commitment to help improve YOLOv8! 🌟

**Comment by aman-agar** [comment]
@glenn-jocher Hi, I've cross verified that i am using the latest ultralytics version along with other dependencies and have created a new issue accordingly. [https://github.com/ultralytics/ultralytics/issues/7268]()

**Comment by glenn-jocher** [comment]
@aman-agar, thank you for updating to the latest version and for creating a new issue. We'll take a look at the details you've provided and continue the investigation there. Your efforts to help us improve YOLOv8 are greatly appreciated! 🌟
