### ISSUE TITLE
What is the default Optimizer in YOLOv8?

### ISSUE THREAD

**Issue by seon-creator** [ultralytics/ultralytics#7224]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to check the default YOLOv8 hyperparameters.
How to check?

**Comment by OceanWong1991** [comment]
the default YOLOv8 hyperparameters : ultralytics/cfg/default.yaml

**Comment by seon-creator** [comment]
Thank you so much!!

**Comment by glenn-jocher** [comment]
@seon-creator you're most welcome! I'm glad I could assist you. If you have any more questions or need further help, don't hesitate to reach out. Happy coding! 😊🚀
