### ISSUE TITLE
This bug always exists for yolov8-pose：valueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by whysirier** [ultralytics/ultralytics#7226]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

![企业微信截图_20231229171127](https://github.com/ultralytics/ultralytics/assets/142364107/7ac2a73c-7faa-46ec-98af-22a8e1ef9a6f)

**the bug is no fixed, my data.yaml as:**

path: ../datasets/antenna2023-pose # dataset root dir
train: images/train2023 # train images (relative to 'path') 118287 images
val: images/train2023 # val images (relative to 'path') 5000 images
test: # 20288 of 40670 images, submit to https://competitions.codalab.org/competitions/20794
kpt_shape: [2, 3] # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)
flip_idx: [0, 1]
names:
0: antenna
![企业微信截图_20231229171247](https://github.com/ultralytics/ultralytics/assets/142364107/84c02d87-6e6c-49d2-9869-b4ee0cd601cd)

**my sample txt as:**
0 0.396514 0.477679 0.388519 0.955357 0.340774 0.03683 2.000000 0.318452 0.683036 2.000000

**obviously, my dataset has one class and two keypoints, but also has this error.**

### Environment

ENV: YOLOV8
NVIDIA: TESLA-V100

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@whysirier hello! Thank you for the detailed bug report. It seems like there might be a misunderstanding with the keypoints specification in your `data.yaml`. The `kpt_shape` should detail the total number of keypoints for all classes combined, and the number of dimensions should typically be 3 for (x,y,visibility). If you only have one class but two keypoints, your `kpt_shape` should represent the total keypoints, and your annotation format in the txt file must mirror this structure correctly. For the error you're experiencing, ensure that:

- Your `data.yaml` correctly defines the `kpt_shape` with respect to your dataset specification.
- Each line in your annotation txt files adheres to the format that YOLOv8 expects, with the visibility flag for keypoints included.
- Validate that your images and label paths are correctly specified and accessible.

For a more detailed guide on annotations and the expected format, please visit our Pose/Keypoint Estimation documentation. If the issue persists, we invite you to open a GitHub issue with the necessary details, or contribute a PR if you believe you've identified a fix. Your collaboration is much appreciated! 😊👍

**Comment by whysirier** [comment]
> @whysirier hello! Thank you for the detailed bug report. It seems like there might be a misunderstanding with the keypoints specification in your `data.yaml`. The `kpt_shape` should detail the total number of keypoints for all classes combined, and the number of dimensions should typically be 3 for (x,y,visibility). If you only have one class but two keypoints, your `kpt_shape` should represent the total keypoints, and your annotation format in the txt file must mirror this structure correctly. For the error you're experiencing, ensure that:
> 
> * Your `data.yaml` correctly defines the `kpt_shape` with respect to your dataset specification.
> * Each line in your annotation txt files adheres to the format that YOLOv8 expects, with the visibility flag for keypoints included.
> * Validate that your images and label paths are correctly specified and accessible.
> 
> For a more detailed guide on annotations and the expected format, please visit our Pose/Keypoint Estimation documentation. If the issue persists, we invite you to open a GitHub issue with the necessary details, or contribute a PR if you believe you've identified a fix. Your collaboration is much appreciated! 😊👍

thanks very much, I am ensure it is a file path problem, now it is running well.

**Comment by glenn-jocher** [comment]
@whysirier Great to hear that the issue was resolved and it's running well now! If you encounter any further problems or have questions, feel free to reach out. Happy coding! 😊🚀
