### ISSUE TITLE
YOLO-NAS TypeError: CustomizableDetector.forward() got an unexpected keyword argument 'augment'

### ISSUE THREAD

**Issue by rkuo2000** [ultralytics/ultralytics#7227]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], line 2
      1 # Run inference with the YOLO-NAS-s model on the 'bus.jpg' image
----> 2 results = model('/kaggle/input/input-images/horses.jpg')

File /opt/conda/lib/python3.10/site-packages/ultralytics/engine/model.py:98, in Model.__call__(self, source, stream, **kwargs)
     96 def __call__(self, source=None, stream=False, **kwargs):
     97     """Calls the predict() method with given arguments to perform object detection."""
---> 98     return self.predict(source, stream, **kwargs)

File /opt/conda/lib/python3.10/site-packages/ultralytics/engine/model.py:257, in Model.predict(self, source, stream, predictor, **kwargs)
    255 if prompts and hasattr(self.predictor, 'set_prompts'):  # for SAM-type models
    256     self.predictor.set_prompts(prompts)
--> 257 return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)

File /opt/conda/lib/python3.10/site-packages/ultralytics/engine/predictor.py:198, in BasePredictor.__call__(self, source, model, stream, *args, **kwargs)
    196     return self.stream_inference(source, model, *args, **kwargs)
    197 else:
--> 198     return list(self.stream_inference(source, model, *args, **kwargs))

File /opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py:35, in _wrap_generator.<locals>.generator_context(*args, **kwargs)
     32 try:
     33     # Issuing `None` to a generator fires it up
     34     with ctx_factory():
---> 35         response = gen.send(None)
     37     while True:
     38         try:
     39             # Forward the response to our caller and get its next request

File /opt/conda/lib/python3.10/site-packages/ultralytics/engine/predictor.py:248, in BasePredictor.stream_inference(self, source, model, *args, **kwargs)
    246 # Warmup model
    247 if not self.done_warmup:
--> 248     self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
    249     self.done_warmup = True
    251 self.seen, self.windows, self.batch, profilers = 0, [], None, (ops.Profile(), ops.Profile(), ops.Profile())

File /opt/conda/lib/python3.10/site-packages/ultralytics/nn/autobackend.py:489, in AutoBackend.warmup(self, imgsz)
    487 im = torch.empty(*imgsz, dtype=torch.half if self.fp16 else torch.float, device=self.device)  # input
    488 for _ in range(2 if self.jit else 1):
--> 489     self.forward(im)

File /opt/conda/lib/python3.10/site-packages/ultralytics/nn/autobackend.py:356, in AutoBackend.forward(self, im, augment, visualize, embed)
    353     im = im.permute(0, 2, 3, 1)  # torch BCHW to numpy BHWC shape(1,320,192,3)
    355 if self.pt or self.nn_module:  # PyTorch
--> 356     y = self.model(im, augment=augment, visualize=visualize, embed=embed)
    357 elif self.jit:  # TorchScript
    358     y = self.model(im)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

TypeError: CustomizableDetector.forward() got an unexpected keyword argument 'augment'

### Minimal Reproducible Example

[https://www.kaggle.com/rkuo2000/yolo-nas](https://www.kaggle.com/rkuo2000/yolo-nas)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@rkuo2000 hello! Thanks for reporting this issue. It seems that there might be an argument compatibility problem with the `CustomizableDetector.forward()` method. This method does not expect an 'augment' keyword argument.

When using the predict mode with YOLO-NAS or any other YOLOv8-supported model, you should ensure that the input to the forward pass aligns with the expected arguments of the model's `forward()` function. If you're trying a feature such as 'augment' that works with one model, it may not necessarily work with another, like YOLO-NAS, as its architecture or implementation might not support it.

Please check the YOLO-NAS model documentation or source code if available to understand the required arguments and ensure they match your usage. In general, you might want to omit the 'augment' parameter if it's not supported. For further information on model-specific functionalities, please refer to our documentation: https://docs.ultralytics.com.

If the issue persists or if you have further questions, feel free to reach out again. We're here to help! 😊

**Comment by aryehw** [comment]
I have this problem. I am not providing the argument. All I have is

model = NAS('yolo_nas_l.pt') # problem occurs also with yolo_nas_s and yolo_nas_m
.
.
.
results = model.predict(image)

That produces:

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> Cell In[30], [line 2](vscode-notebook-cell:?execution_count=30&line=2)
>       [1](vscode-notebook-cell:?execution_count=30&line=1) #results = model.predict(image)
> ----> [2](vscode-notebook-cell:?execution_count=30&line=2) results=model(image)
> 
> File [~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/model.py:100](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/model.py:100), in Model.__call__(self, source, stream, **kwargs)
>      [98](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/model.py:98) def __call__(self, source=None, stream=False, **kwargs):
>      [99](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/model.py:99)     """Calls the predict() method with given arguments to perform object detection."""
> --> [100](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/model.py:100)     return self.predict(source, stream, **kwargs)
> 
> File [~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/model.py:273](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/model.py:273), in Model.predict(self, source, stream, predictor, **kwargs)
>     [271](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/model.py:271) if prompts and hasattr(self.predictor, "set_prompts"):  # for SAM-type models
>     [272](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/model.py:272)     self.predictor.set_prompts(prompts)
> --> [273](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/model.py:273) return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
> 
> File [~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:204](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:204), in BasePredictor.__call__(self, source, model, stream, *args, **kwargs)
>     [202](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:202)     return self.stream_inference(source, model, *args, **kwargs)
>     [203](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:203) else:
> --> [204](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:204)     return list(self.stream_inference(source, model, *args, **kwargs))
> 
> File [~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/utils/_contextlib.py:35](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/utils/_contextlib.py:35), in _wrap_generator.<locals>.generator_context(*args, **kwargs)
>      [32](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/utils/_contextlib.py:32) try:
>      [33](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/utils/_contextlib.py:33)     # Issuing `None` to a generator fires it up
>      [34](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/utils/_contextlib.py:34)     with ctx_factory():
> ---> [35](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/utils/_contextlib.py:35)         response = gen.send(None)
>      [37](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/utils/_contextlib.py:37)     while True:
>      [38](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/utils/_contextlib.py:38)         try:
>      [39](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/utils/_contextlib.py:39)             # Forward the response to our caller and get its next request
> 
> File [~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:283](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:283), in BasePredictor.stream_inference(self, source, model, *args, **kwargs)
>     [281](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:281) # Inference
>     [282](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:282) with profilers[1]:
> --> [283](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:283)     preds = self.inference(im, *args, **kwargs)
>     [284](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:284)     if self.args.embed:
>     [285](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:285)         yield from [preds] if isinstance(preds, torch.Tensor) else preds  # yield embedding tensors
> 
> File [~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:140](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:140), in BasePredictor.inference(self, im, *args, **kwargs)
>     [134](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:134) """Runs inference on a given image using the specified model and arguments."""
>     [135](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:135) visualize = (
>     [136](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:136)     increment_path(self.save_dir [/](https://file+.vscode-resource.vscode-cdn.net/) Path(self.batch[0][0]).stem, mkdir=True)
>     [137](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:137)     if self.args.visualize and (not self.source_type.tensor)
>     [138](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:138)     else False
>     [139](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:139) )
> --> [140](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/engine/predictor.py:140) return self.model(im, augment=self.args.augment, visualize=visualize, embed=self.args.embed, *args, **kwargs)
> 
> File [~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1518](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1518), in Module._wrapped_call_impl(self, *args, **kwargs)
>    [1516](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1516)     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
>    [1517](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1517) else:
> -> [1518](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1518)     return self._call_impl(*args, **kwargs)
> 
> File [~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1527](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1527), in Module._call_impl(self, *args, **kwargs)
>    [1522](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1522) # If we don't have any hooks, we want to skip the rest of the logic in
>    [1523](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1523) # this function, and just call forward.
>    [1524](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1524) if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
>    [1525](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1525)         or _global_backward_pre_hooks or _global_backward_hooks
>    [1526](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1526)         or _global_forward_hooks or _global_forward_pre_hooks):
> -> [1527](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1527)     return forward_call(*args, **kwargs)
>    [1529](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1529) try:
>    [1530](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1530)     result = None
> 
> File [~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/nn/autobackend.py:384](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/nn/autobackend.py:384), in AutoBackend.forward(self, im, augment, visualize, embed)
>     [381](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/nn/autobackend.py:381)     im = im.permute(0, 2, 3, 1)  # torch BCHW to numpy BHWC shape(1,320,192,3)
>     [383](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/nn/autobackend.py:383) if self.pt or self.nn_module:  # PyTorch
> --> [384](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/nn/autobackend.py:384)     y = self.model(im, augment=augment, visualize=visualize, embed=embed)
>     [385](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/nn/autobackend.py:385) elif self.jit:  # TorchScript
>     [386](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/ultralytics/nn/autobackend.py:386)     y = self.model(im)
> 
> File [~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1518](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1518), in Module._wrapped_call_impl(self, *args, **kwargs)
>    [1516](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1516)     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
>    [1517](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1517) else:
> -> [1518](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1518)     return self._call_impl(*args, **kwargs)
> 
> File [~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1527](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1527), in Module._call_impl(self, *args, **kwargs)
>    [1522](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1522) # If we don't have any hooks, we want to skip the rest of the logic in
>    [1523](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1523) # this function, and just call forward.
>    [1524](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1524) if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
>    [1525](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1525)         or _global_backward_pre_hooks or _global_backward_hooks
>    [1526](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1526)         or _global_forward_hooks or _global_forward_pre_hooks):
> -> [1527](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1527)     return forward_call(*args, **kwargs)
>    [1529](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1529) try:
>    [1530](https://file+.vscode-resource.vscode-cdn.net/home/amw/git/YOLOv8/practice/~/anaconda3/envs/YOLOv8/lib/python3.8/site-packages/torch/nn/modules/module.py:1530)     result = None
> 
> TypeError: forward() got an unexpected keyword argument 'augment'

**Comment by glenn-jocher** [comment]
@aryehw hello! It appears there's an issue with the `forward()` method receiving an unexpected 'augment' argument. This could be due to an internal call within the `predict()` method that is not compatible with the YOLO-NAS model.

To resolve this, please ensure you are using the latest version of the YOLOv8 repository, as updates may have addressed this issue. If the problem persists after updating, it might be necessary to review the internal implementation of the YOLO-NAS model or wait for a fix to be released.

For now, you can also try using the model in a more manual way, by directly calling the `forward()` method without the 'augment' argument, but this would require handling the data preprocessing and postprocessing steps yourself.

If you need further assistance, please provide more details on the environment and the exact steps to reproduce the issue, and we'll be glad to help. Thank you for your patience! 😊

**Comment by aryehw** [comment]
Thank you for your reply,
I just installed YOLOv8 with pip install ultralytics.
The yolo version is 8.2.1
I am attaching the conda list output.
[condaList.txt](https://github.com/ultralytics/ultralytics/files/13972291/condaList.txt)
Note that I had to pip install super-gradients separately.

How can I use the model in a more manual way? Can you direct me to an example, 
and is there  a lower level API for using YOLO?

So far I am trying it based on this link
https://inside-machinelearning.com/en/yolov8-how-to-use/

I am still very much a beginner, and my main strategy for learning is find code that does something close to what I need and then modify it.

**Comment by glenn-jocher** [comment]
@aryehw, thanks for the update and for providing your environment details. It's great to hear you're using YOLOv8 version 8.2.1.

For a more manual approach, you would typically load the model, process your input data to match the model's expected format, perform a forward pass, and then interpret the output. However, since we aim to keep things simple and user-friendly, I recommend sticking with the high-level API provided by the `predict()` method.

If you're encountering issues with the `predict()` method, it might be due to a compatibility problem with the YOLO-NAS model. We're continuously working on improving our models and documentation. For the most up-to-date usage examples and guidance, please refer to our official documentation at https://docs.ultralytics.com.

As a beginner, it's a good strategy to start with existing code examples. Our documentation includes various examples and is designed to help users at all levels. If you're still facing difficulties, please open an issue on the GitHub repository with details of the error and your environment, and our team will assist you further.

Keep experimenting and learning, and don't hesitate to reach out for help when needed! 😊

**Comment by hanicornelia** [comment]
Hello, im facing the same issue while using Yolo-Nas model to predict image

`TypeError: forward() got an unexpected keyword argument 'augment'`

I am currently using `ultralytics==8.1.13`, and Yolo-Nas model downloaded from [here](https://docs.ultralytics.com/models/yolo-nas/#supported-tasks-and-modes)

Is there any update on this issue?

**Comment by glenn-jocher** [comment]
@hanicornelia it seems that you are encountering a `TypeError` when attempting to run inference with the YOLO-NAS model using the Ultralytics YOLOv8 library. The error message indicates that the `CustomizableDetector.forward()` method received an unexpected keyword argument `augment`.

This issue could be due to a mismatch between the expected arguments of the `forward()` method in the `CustomizableDetector` class and the arguments provided during the call. The `augment` argument is not expected by the `forward()` method of the `CustomizableDetector` class.

To resolve this issue, you can try the following steps:

1. Ensure that you are using the correct version of the Ultralytics YOLOv8 library that is compatible with the YOLO-NAS model. It's possible that the `augment` argument was introduced or removed in a different version of the library.

2. If you have access to the source code of the `CustomizableDetector` class, check the definition of the `forward()` method to see what arguments it expects. If the `augment` argument is not used, you may need to remove it from the call.

3. If you are using a custom model or a modified version of the YOLOv8 library, ensure that any customizations are compatible with the rest of the library's API.

4. If the issue persists, consider reaching out to the maintainers of the Ultralytics YOLOv8 library or the authors of the YOLO-NAS model for further assistance. They may provide insights or updates that address this specific issue.

Since you mentioned that you have already searched the YOLOv8 issues and found no similar bug report, it might be helpful to open a new issue in the Ultralytics YOLOv8 GitHub repository with the details you've provided here. This will alert the developers to the problem and allow them to investigate and provide a fix or guidance.

Remember to include the full error message, the steps to reproduce the issue, and any relevant details about your environment (such as the version of the Ultralytics YOLOv8 library you are using) when reporting the issue.
