### ISSUE TITLE
v8.0.231 yolo predict segmentation fault (core dumped)

### ISSUE THREAD

**Issue by sandriverfish** [ultralytics/ultralytics#7236]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

# yolo detect predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'
Ultralytics YOLOv8.0.231 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla P100-PCIE-16GB, 16281MiB)
Segmentation fault (core dumped)

### Environment

# yolo checks
Ultralytics YOLOv8.0.231 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla P100-PCIE-16GB, 16281MiB)
Setup complete ✅ (8 CPUs, 15.5 GB RAM, 1185.5/3928.3 GB disk)

OS                  Linux-5.19.0-50-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             git
RAM                 15.53 GB
CPU                 Intel Core(TM) i7-6700K 4.00GHz
CUDA                11.8

matplotlib          ✅ 3.8.2>=3.3.0
numpy               ✅ 1.24.1>=1.22.2
pillow              ✅ 9.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.28.1>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.7
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.1.4>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by sandriverfish** [comment]
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from ultralytics import YOLO
>>> 
>>> # Load the model
>>> model = YOLO("yolov8n.pt")
>>> 
>>> # Load a 0-channel image
>>> image = torch.rand(1, 0, 640, 640)
>>> 
>>> # Run the model
>>> results = model(image)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ultralytics/ultralytics/engine/model.py", line 98, in __call__
    return self.predict(source, stream, **kwargs)
  File "/ultralytics/ultralytics/engine/model.py", line 257, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/ultralytics/ultralytics/engine/predictor.py", line 198, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/ultralytics/ultralytics/engine/predictor.py", line 240, in stream_inference
    self.setup_source(source if source is not None else self.args.source)
  File "/ultralytics/ultralytics/engine/predictor.py", line 215, in setup_source
    self.dataset = load_inference_source(source=source,
  File "/ultralytics/ultralytics/data/build.py", line 162, in load_inference_source
    dataset = LoadTensor(source)
  File "/ultralytics/ultralytics/data/loaders.py", line 442, in __init__
    self.im0 = self._single_check(im0)
  File "/ultralytics/ultralytics/data/loaders.py", line 459, in _single_check
    if im.max() > 1.0 + torch.finfo(im.dtype).eps:  # torch.float32 eps is 1.2e-07
RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.

**Comment by glenn-jocher** [comment]
@sandriverfish the error you're encountering is caused by attempting to run an image through the model with a 0-channel dimension, which is an invalid input format. YOLO models typically operate on 3-channel RGB images. The input tensor you created with `torch.rand(1, 0, 640, 640)` has a size that indicates 1 image with 0 channels, a height of 640, and a width of 640.

To resolve this issue, ensure that your input tensor has the correct number of channels (3 for RGB). For instance, you might create an input tensor for a single RGB image with random pixels as follows:
```python
image = torch.rand(1, 3, 640, 640)
```
Make sure that the images you are passing to the model have the proper dimensions. Additionally, ensure that the image data is within the valid range (typically 0-1 for normalized images or 0-255 for standard RGB images).

Furthermore, it's worth noting that for actual predictions, you should pass in real image data, not random tensors, unless you are simply conducting a test for the data pipeline.

**Comment by sandriverfish** [comment]
> @sandriverfish the error you're encountering is caused by attempting to run an image through the model with a 0-channel dimension, which is an invalid input format. YOLO models typically operate on 3-channel RGB images. The input tensor you created with `torch.rand(1, 0, 640, 640)` has a size that indicates 1 image with 0 channels, a height of 640, and a width of 640.
> 
> To resolve this issue, ensure that your input tensor has the correct number of channels (3 for RGB). For instance, you might create an input tensor for a single RGB image with random pixels as follows:
> 
> ```python
> image = torch.rand(1, 3, 640, 640)
> ```
> 
> Make sure that the images you are passing to the model have the proper dimensions. Additionally, ensure that the image data is within the valid range (typically 0-1 for normalized images or 0-255 for standard RGB images).
> 
> Furthermore, it's worth noting that for actual predictions, you should pass in real image data, not random tensors, unless you are simply conducting a test for the data pipeline.

@glenn-jocher thanks for your quick reply, yes you are right. I built ultralytics from source and also built opencv from source using gstreamer, but yolov8 prediction has core dump issues as below:

# yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'
Ultralytics YOLOv8.0.231 🚀 Python-3.10.12 torch-2.1.1+cu118 CUDA:0 (Tesla P100-PCIE-16GB, 16281MiB)
Segmentation fault (core dumped)

**Comment by Burhan-Q** [comment]
@sandriverfish perhaps try with another version of `torch`?

## On Windows 10

```sh
yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'

>>> Ultralytics YOLOv8.0.231 🚀 Python-3.10.9 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3080, 12288MiB)
>>> YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

>>> Found https://ultralytics.com/images/bus.jpg locally at bus.jpg
>>> image 1/1 C:\Users\User\python_proj\pytorch_and_yolo\bus.jpg: 640x480 4 persons, 1 bus, 1 stop sign, 18.0ms
>>> Speed: 5.0ms preprocess, 18.0ms inference, 5.0ms postprocess per image at shape (1, 3, 640, 480)
>>> Results saved to runs\detect\predict4

>>> 💡 Learn more at https://docs.ultralytics.com/modes/predict
```

## On Linux

```sh
yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'

>>> Ultralytics YOLOv8.0.231 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce RTX 2060, 5924MiB)
>>> YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

>>> Found https://ultralytics.com/images/bus.jpg locally at bus.jpg
>>> image 1/1 /home/h4mmer/Documents/_code/ultra_testing/bus.jpg: 640x480 4 persons, 1 bus, 1 stop sign, 59.0ms
>>> Speed: 2.2ms preprocess, 59.0ms inference, 470.0ms postprocess per image at shape (1, 3, 640, 480)
>>> Results saved to runs/detect/predict2

>>> 💡 Learn more at https://docs.ultralytics.com/modes/predict
```

**Comment by sandriverfish** [comment]
> @sandriverfish perhaps try with another version of `torch`?
> 
> ## On Windows 10
> ```shell
> yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'
> 
> >>> Ultralytics YOLOv8.0.231 🚀 Python-3.10.9 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3080, 12288MiB)
> >>> YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
> 
> >>> Found https://ultralytics.com/images/bus.jpg locally at bus.jpg
> >>> image 1/1 C:\Users\User\python_proj\pytorch_and_yolo\bus.jpg: 640x480 4 persons, 1 bus, 1 stop sign, 18.0ms
> >>> Speed: 5.0ms preprocess, 18.0ms inference, 5.0ms postprocess per image at shape (1, 3, 640, 480)
> >>> Results saved to runs\detect\predict4
> 
> >>> 💡 Learn more at https://docs.ultralytics.com/modes/predict
> ```
> 
> ## On Linux
> ```shell
> yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'
> 
> >>> Ultralytics YOLOv8.0.231 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce RTX 2060, 5924MiB)
> >>> YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
> 
> >>> Found https://ultralytics.com/images/bus.jpg locally at bus.jpg
> >>> image 1/1 /home/h4mmer/Documents/_code/ultra_testing/bus.jpg: 640x480 4 persons, 1 bus, 1 stop sign, 59.0ms
> >>> Speed: 2.2ms preprocess, 59.0ms inference, 470.0ms postprocess per image at shape (1, 3, 640, 480)
> >>> Results saved to runs/detect/predict2
> 
> >>> 💡 Learn more at https://docs.ultralytics.com/modes/predict
> ```

Thanks! Finally the problem is identified and fixed - opencv build from source under container cause the segement fault.

**Comment by glenn-jocher** [comment]
@sandriverfish Great to hear that you've identified the issue with the OpenCV build causing the segmentation fault. If you encounter any further issues or have questions about YOLOv8, feel free to reach out. Happy coding! 🚀
