### ISSUE TITLE
Error "'Annotator' object has no attribute 'seg_bbox' " when run the code on "Instance Segmentation and Tracking using Ultralytics YOLOv8" docs

### ISSUE THREAD

**Issue by LithiraAponsu2** [ultralytics/ultralytics#7237]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In the official docs the given code gives the above error. Also, inspection of the Annotator class proved that there is no such object named seg_bbox. Do I have to manually implement or the object is on beta release? [https://docs.ultralytics.com/guides/instance-segmentation-and-tracking/](url)

**Comment by LithiraAponsu2** [comment]
Just update the version and it worked.

**Comment by glenn-jocher** [comment]
@LithiraAponsu2 great to hear that updating the version resolved the issue! Remember, it's always a good idea to ensure you are on the latest version of the software for the most recent features and fixes. If you encounter any further issues or have questions, feel free to check out our documentation or reach out again. Happy coding! 😊🚀

**Comment by hrbjoern** [comment]
I think the problem here is that there are several different code examples on this page. 

1) In https://docs.ultralytics.com/guides/instance-segmentation-and-tracking/?h=annotator.seg_bbox#__tabbed_1_2, the code is 
```annotator.seg_bbox(mask=mask, mask_color=color, label=str(track_id), txt_color=txt_color)```, which works. 

2) In https://docs.ultralytics.com/guides/instance-segmentation-and-tracking/?h=annotator.seg_bbox#how-can-i-implement-object-tracking-using-ultralytics-yolov8, 
the code is 
```annotator.seg_bbox(mask=mask, mask_color=colors(track_id, True), track_label=str(track_id))```, 
which does **not** work.

**Comment by glenn-jocher** [comment]
@hrbjoern thank you for pointing this out. We'll review the documentation to ensure consistency. If you have any further questions, feel free to ask!

**Comment by AkshayLaddha943** [comment]
> Just update the version and it worked.

Hi, Update the version of what

**Comment by glenn-jocher** [comment]
@AkshayLaddha943 update the Ultralytics package version with `pip install -U ultralytics` to get the latest features and bug fixes.
