### ISSUE TITLE
Support for Segmentation Crop and Rotate Albumentations 

### ISSUE THREAD

**Issue by sarmientoj24** [ultralytics/ultralytics#724]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Raised this [issue](https://github.com/ultralytics/yolov5/issues/10860) I found in YOLOv5 lack of support on Albumentations augmentations that affect masks. Does YOLOv8 support this?

**Comment by JustasBart** [comment]
Hi @sarmientoj24, have you came across #10841 in yolov5 before? I believe that things aren't any better for yolov8 for now...

But someone do correct me if I'm wrong!

Good luck! :rocket:
