### ISSUE TITLE
Where is the yolov8x.yaml and yolov8n.yaml download ?

### ISSUE THREAD

**Issue by toplinuxsir** [ultralytics/ultralytics#7246]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Where is the yolov8x.yaml and yolov8n.yaml download ?

### Additional

Where is the yolov8x.yaml and yolov8n.yaml download ? Thanks ! 
the cfg folder only contain: yolov8.yaml yolov8-p2... yolv8-6.yaml etc.

**Comment by glenn-jocher** [comment]
@toplinuxsir hey there! 👋 The `yolov8x.yaml` and `yolov8n.yaml` files should be present in the `models` directory of the YOLOv8 repository. Please make sure you have the latest version of the repo. If you're still unable to find them, they might have been renamed or modified as part of an update. For the most accurate and up-to-date model configurations, I recommend checking out the documentation for guidance on configuring your model. If these specific files are necessary for your work and you can't locate them, feel free to open an issue in the repository for further assistance. Happy detecting! 😊
