### ISSUE TITLE
Does YOLOv8 utilize transformer layers?

### ISSUE THREAD

**Issue by jinyoonok2** [ultralytics/ultralytics#7252]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, currently I am trying to understand how YOLOv8 architecture operates and utilize its layers. However, I faced some confusion while I am investigating it.

1.
Does YOLOv8 utilize transformer layer in any of its layers? I found some writings that mention about transformer and YOLOv8 model together but when I look into the source code of the **ultralytics/nn/modules/transformer.py** and I found out that AIFI and other transformer based layers are only used by RT-DETR model.

So can I assume that transformer concept is only used by the RT-DETR model and YOLOv8 is purely CNN based object detection model that does not utilize any transformer concept? or is there a part that I am missing?

if there is any part that YOLOv8 utilize transformer concept, can you enlighten me what part of the layers does it utilize it and how it is different from RT-DETR transformer?

2.
Does YOLOv8 and RT-DETR share any methodology or features in the feature extraction layers of their backbones? or RT-DETR is seperate stand alone model from YOLOv8 that does not share any structural components?

Thank you for your works and time,

**Comment by iscyy** [comment]
You can understand it this way, the default YOLov8 model does not use the transformer, the transformer is only used by the RT-DETR model

The default YOLOv8 and RT-DETR backbone parts use CNN components to extract features

**Comment by glenn-jocher** [comment]
@jinyoonok2 you're welcome! I'm glad I could help clarify that for you. If you have any more questions about YOLOv8 or other models, feel free to reach out. Happy to assist! 😊

**Comment by kanis777** [comment]
@iscyy hi. So I was trying to add biformer to yolov8 architecture. To do that - I created a class in transformer.py and then I included that in head.py and init.py. After adding them - I made changes to task.py - particularly in importing and in parse_model . after doing these both - I tried using it in yolov8 yaml file - but I am getting the error 
PS D:\Yavar\pest_tea> yolo detect mode=train data="D:/Yavar/pest_tea/ultralytics/ultralytics/cfg/datasets/coco.yaml" model="D:/Yavar/pest_tea/ultralytics/ultralytics/cfg/models/v8/yolov8n.yaml" epochs=1 imgsz=640

> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Scripts\yolo.exe\__main__.py", line 7, in <module> 
>   File "c:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\cfg\__init__.py", line 556, in entrypoint
>     model = YOLO(model, task=task)
>             ^^^^^^^^^^^^^^^^^^^^^^
>   File "c:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
>     super().__init__(model=model, task=task, verbose=verbose)
>   File "c:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\engine\model.py", line 150, in __init__
>     self._new(model, task=task, verbose=verbose)
>   File "c:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\engine\model.py", line 219, in _new
>     self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model    
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "c:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\nn\tasks.py", line 287, in __init__
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "c:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\nn\tasks.py", line 855, in parse_model
>     m = getattr(torch.nn, m[3:]) if "nn." in m else globals()[m]  # get module
>                                                     ~~~~~~~~~^^^        
> KeyError: 'BiFormer'

I would find it really helpful if you have any idea on why this is happening
