### ISSUE TITLE
Yolov8 TensorRT cannot predict or val

### ISSUE THREAD

**Issue by Savior5130** [ultralytics/ultralytics#7254]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I am not able to perform
`model=YOLO('yolov8n_custom.engine').val(data='lidc-idri.yaml', imgsz=512)` or
`model=YOLO('yolov8n_custom.engine').predict(source=IMAGES_PATH[0], imgsz=512)` as it shows the following error 
![image](https://github.com/ultralytics/ultralytics/assets/54888619/82eb4974-86de-403e-b4da-b74fcbe0f75e)

I'm able though, however, to do it with another syntax, via:
`!yolo val model=yolov8n_custom.engine data=lidc-idri.yaml imgsz=512`

Do you guys know what may be the potential reason?

**Comment by Burhan-Q** [comment]
You need to load the model first and let it initialize, _then_ run `val()` or `predict()` methods. Additionally, you'll need to add a value for the `task` argument with initializing your model, the example below assumes you're using the basic object detection task.

```py
from ultralytics import YOLO

... # any other code you're using

model=YOLO('yolov8n_custom.engine', task='detect')
results = model.val(data='lidc-idri.yaml', imgsz=512)

# OR 

model=YOLO('yolov8n_custom.engine', task='detect')
results = model.predict(source=IMAGES_PATH[0], imgsz=512)
```

This screenshot from my interactive terminal shows that it is feasible to execute inference using TensorRT when first initializing the model.

![image](https://github.com/ultralytics/ultralytics/assets/62214284/fb5a2daf-8e4c-4038-92c3-eb82c6f0ef44)

**Comment by Savior5130** [comment]
@Burhan-Q Hello sir, thank you for the response. I used that syntax before and it didnt work, but somehow /i rerun my old code today and it works miraculouslu. I supposed it has something to do with the dependencies (tensorrt), but regardless, thanks!

**Comment by Burhan-Q** [comment]
@Savior5130 glad to hear you were able to get it working! Unfortunately I have no news or updates regarding the YOLOv8 paper, sorry. If by chance you're looking to cite YOLOv8, you can use [this](https://docs.ultralytics.com/models/yolov8/#citations-and-acknowledgements)

**Comment by Petros626** [comment]
Note for me: specify the task when using `TensorRT` FP16 or INT8 models.

**Comment by glenn-jocher** [comment]
Great to hear your TensorRT model is working now! For future reference, specifying the `task` parameter when loading exported models like TensorRT engines helps ensure proper initialization. 

Regarding YOLOv8 citations, we maintain a [YOLOv8 citation guide](https://docs.ultralytics.com/models/yolov8/#citations-and-acknowledgements) in our documentation with the recommended BibTeX format since we haven't published a formal paper. Let us know if you need any other TensorRT tips! 🚀
