### ISSUE TITLE
how to convert .pt -> ONNX -> NCNN for android deployment???

### ISSUE THREAD

**Issue by apanand14** [ultralytics/ultralytics#726]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello everyone,

I have trained yolov8n-seg on my custom dataset and would like to do inference using NCNN framework. For thaT, I have to convert model to ONNX and then to NCNN supported param and bin files. 

Anyone has tried to run on NCNN then can you please help me out how to deploy it?

Thank you in advance.

**Comment by apanand14** [comment]
> Hi @apanand14 while I can't really help you I can show you a way to convert to ONNX if it's any good to you:
> 
> ```
> yolo export \
> model=yolov8n-seg.pt \
> imgsz=640,640 \
> format=onnx \
> opset=12
> ```
> 
> Good luck! 🚀

Thank you for the quick response. Yes. I have converted into ONNX and then to NCNN supported param and bin files but my files are different than this implementation (mentioned link below) and won't able to deploy properly. 
https://github.com/FeiGeChuanShu/ncnn-android-yolov8

**Comment by apanand14** [comment]
> ChatGPT suggested this:
> 
> To convert an ONNX model to NCNN, follow these steps:
> 
> Install the ONNX and NCNN tools. Use the ONNX tools to convert the ONNX model to a Caffe prototxt file and a Caffe model file. Use the NCNN tools to convert the Caffe model file to an NCNN model file. Use the NCNN model in your project.
> 
> I'm not sure if any of that makes sense though...



> ChatGPT suggested this:
> 
> To convert an ONNX model to NCNN, follow these steps:
> 
> Install the ONNX and NCNN tools. Use the ONNX tools to convert the ONNX model to a Caffe prototxt file and a Caffe model file. Use the NCNN tools to convert the Caffe model file to an NCNN model file. Use the NCNN model in your project.
> 
> I'm not sure if any of that makes sense though...

LoL. thank you.

**Comment by JustasBart** [comment]
@apanand14 You might get some help quicker if you can provide any error output logs or the steps to reproduce your issue etc...

All the best! :rocket:

**Comment by apanand14** [comment]
[best.txt](https://github.com/ultralytics/ultralytics/files/10545806/best.txt)
[yolov8-seg.txt](https://github.com/ultralytics/ultralytics/files/10545807/yolov8-seg.txt)
Best.txt is my param file after generating from ONNX to NCNN, which is different than yolov8-seg (https://github.com/FeiGeChuanShu/ncnn-android-yolov8/blob/main/ncnn-yolov8s-seg/models/yolov8s-seg.param) produced by @FeiGeChuanShu. 

Let me know if you find something what's missing in my procedure. Thank you in advance

**Comment by lyb36524** [comment]
参考一下这个：https://github.com/FeiGeChuanShu/ncnn-android-yolov8/issues/8#issuecomment-1553399271

**Comment by glenn-jocher** [comment]
Hi @lyb36524, 

I have looked into the issue you're facing to deploy ultralytics YOLOv8 on Android using NCNN, and I see that you have converted your trained YOLOv8 model to ONNX and then to NCNN format, but the resulting param file that you have generated is different from the one available in this implementation (https://github.com/FeiGeChuanShu/ncnn-android-yolov8/blob/main/ncnn-yolov8s-seg/models/yolov8s-seg.param) which might be the reason you're facing issues while deploying.

I would recommend you to check if the conversion process is followed correctly, as small deviations in the process might result in different target files. Also, if you are using the latest version of the NCNN tools, you might want to try and use the older version which seems to have worked for other users.

I hope this helps, and if you have any further questions feel free to ask!

**Comment by glenn-jocher** [comment]
@apanand14 @JustasBart great news 😃! Your original issue may now be resolved ✅ in Ultraltyics PR https://github.com/ultralytics/ultralytics/pull/3529 which is part of `ultralytics==8.0.129`. This release adds official support for Ultralytics YOLOv8 NCNN export! You can export with CLI:
```
yolo export model=yolov8n.pt format=ncnn
```

or Python:
```python
from ultralytics import YOLO

# Create a model
model = YOLO('yolov8n.pt')

# Export the model to NCNN with arguments
model.export(format='ncnn', half=True, imgsz=640)
```

Output is a `yolov8n_ncnn_model/` directory containing `model.bin`, `model.param` and `metadata.yaml`, along with extra PNNX files. For details see https://github.com/pnnx/pnnx


To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by vjsyong** [comment]
I just tried running the latest version through docker and tried to export an ncnn file. I get an export failed error that has this output

```
NCNN: starting export with NCNN 1.0.20230517...
NCNN: running '/usr/src/ultralytics/ultralytics/pnnx runs/detect/train/weights/best.torchscript pnnxparam=runs/detect/train/weights/best_ncnn_model/model.pnnx.param pnnxbin=runs/detect/train/weights/best_ncnn_model/model.pnnx.bin pnnxpy=runs/detect/train/weights/best_ncnn_model/model_pnnx.py pnnxonnx=runs/detect/train/weights/best_ncnn_model/model.pnnx.onnx ncnnparam=runs/detect/train/weights/best_ncnn_model/model.ncnn.param ncnnbin=runs/detect/train/weights/best_ncnn_model/model.ncnn.bin ncnnpy=runs/detect/train/weights/best_ncnn_model/model_ncnn.py fp16=0 device=cpu inputshape="[1, 3, 640, 640]"'
/usr/src/ultralytics/ultralytics/pnnx: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/src/ultralytics/ultralytics/pnnx)
/usr/src/ultralytics/ultralytics/pnnx: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/src/ultralytics/ultralytics/pnnx)
NCNN: export failure ❌ 0.0s: Command '['/usr/src/ultralytics/ultralytics/pnnx', 'runs/detect/train/weights/best.torchscript', 'pnnxparam=runs/detect/train/weights/best_ncnn_model/model.pnnx.param', 'pnnxbin=runs/detect/train/weights/best_ncnn_model/model.pnnx.bin', 'pnnxpy=runs/detect/train/weights/best_ncnn_model/model_pnnx.py', 'pnnxonnx=runs/detect/train/weights/best_ncnn_model/model.pnnx.onnx', 'ncnnparam=runs/detect/train/weights/best_ncnn_model/model.ncnn.param', 'ncnnbin=runs/detect/train/weights/best_ncnn_model/model.ncnn.bin', 'ncnnpy=runs/detect/train/weights/best_ncnn_model/model_ncnn.py', 'fp16=0', 'device=cpu', 'inputshape="[1, 3, 640, 640]"']' returned non-zero exit status 1.
```

**Comment by glenn-jocher** [comment]
@vjsyong i understand that you encountered an issue while trying to export an NCNN file using the latest version of the repository through Docker. The error message states that there is a missing GLIBC version (`GLIBC_2.29`) and `GLIBCXX_3.4.26` in the current environment. However, you were able to resolve the problem by manually downloading an older version of `pnnx` that supports `glibc_2.27` instead.

It's great to hear that you were able to find a solution to the issue by using an older version of `pnnx`. This highlights that the compatibility with certain GLIBC versions may vary in different environments, and it's essential to have the appropriate version installed for successful exports.

Please let us know if you have any further questions or encounter any other issues. We're here to assist you!
