### ISSUE TITLE
brackets misaligned - execution with custom predictor

### ISSUE THREAD

**Issue by uwer** [ultralytics/ultralytics#7266]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

When providing a custom predictor to model.predict, the assignment in
https://github.com/ultralytics/ultralytics/blob/6218b820723b9e8647c582589c536c63c1f473f3/ultralytics/engine/model.py#L249
is incorrect.
error case:
Wrongly executes the  predictor with the conf arguments if one is provided. 
It is correct if no exisiting one is provided and a new one is created.

The second brackets after self._smart_load('predictor')) needs to move to the outside of the statement
before 
`self.predictor = (predictor or self._smart_load('predictor'))(overrides=args, _callbacks=self.callbacks)`
after
`self.predictor = (predictor or self._smart_load('predictor')(overrides=args, _callbacks=self.callbacks))`

There is no failure or stack trace that warrants environment dumps, simply a logic error (when one types too fast :))

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@uwer thank you for bringing this to our attention! It seems you've identified a potential issue with the custom predictor assignment logic in the `model.predict` method. We appreciate your willingness to help by submitting a PR. Please ensure that the PR clearly describes the problem and the proposed solution. Your contribution is valuable, and we look forward to reviewing it. If you have any questions or need further clarification on the contribution process, feel free to consult our documentation or ask. Happy coding! 😊👍

**Comment by uwer** [comment]
no worries,
do you really want me to put a PR on moving a bracket ? ...
Cheers
Uwe

PS- great development!!

**Comment by glenn-jocher** [comment]
@uwer hi Uwe,

Absolutely, even small contributions like moving a bracket can have a significant impact on the functionality and user experience. We value every contribution, no matter the size. If you're up for it, please go ahead with the PR. And thank you for the kind words – it's a team effort! 😄🚀
