### ISSUE TITLE
YOLO detect the lesion in 1 slice, but fail to detect the similar lesion in next continuous slice 

### ISSUE THREAD

**Issue by frabob2017** [ultralytics/ultralytics#727]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello yolov8 team, 

I used YOLOv8 to detect bone fracture in CT images. I found that YOLO can detect a fracture in one slice but fail to detect a similar lesion in the continuous next slice.  Do you know why? I think use nn.conv3d to replace nn.conv2d will work better for medical imaging. May I ask if there is a technical difficulty to implement it? If it is difficult, what else I can do to make such improvement?     

![image](https://user-images.githubusercontent.com/57141860/215544154-ac63cb08-9dee-4e63-8f4d-74ff29b14e6b.png)

**Comment by knoppmyth** [comment]
I cannot speak about nn.conv3d. Given the confidence is so low, I wonder about the quality of and number of samples used in your dataset for training. Additionally, are you using transfer learning?

**Comment by frabob2017** [comment]
> I cannot speak about nn.conv3d. Given the confidence is so low, I wonder about the quality of and number of samples used in your dataset for training. Additionally, are you using transfer learning?

Hello. My training data is not too much (around 210). I used the transfer learning because I used the yolo.yaml as my starting point. I really hope that in the future, YOLO team can implement  nn.conv3d into this algorithm.

**Comment by frabob2017** [comment]
No one can further answer this question?

**Comment by glenn-jocher** [comment]
@pderrenger, your initiative in applying YOLOv8 to medical imaging is commendable! 🚀 With a dataset of around 210, increasing the diversity and quality of your samples could indeed bolster the model's ability to generalize, especially across similar continuous slices. Leveraging transfer learning, as you've done, is a solid approach. While nn.conv3d isn't currently a feature of YOLOv8, your suggestion is valuable and noted for potential future enhancements. Keep pushing the boundaries, and don't hesitate to share further questions or progress with the community! 🌟
