### ISSUE TITLE
Bug model.predict()+pyinstaller+HTTPServer/flask: not executing

### ISSUE THREAD

**Issue by fridary** [ultralytics/ultralytics#7273]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I set up http server and when doing model.predict() in the route after packing python with pyinstaller it sets up a new server again instead of printing prediction results. Without pyinstaller everything works fine.

Tests were made both on flask and plain HTTPServer, the same error. So problem is in packing pyinstaller I suppose.

Let's send post request on pure http server. Response from webserver:
```
starting server..
127.0.0.1 - - [02/Jan/2024 11:35:04] "POST /enter HTTP/1.1" 200 -
starting..
model loaded

0: 150x150 correct 0.51, labelname 0.49, 110.8ms
Speed: 0.0ms preprocess, 110.8ms inference, 0.0ms postprocess per image at shape (1, 3, 150, 150)
model predicted
aborted
```

Results from post script:
```
sending post..
<Response [200]> ok
```

Now, let's wrap with pyinstaller. It does not matter `--onedir` or `--onefile`, the same results:
`$ pyinstaller --onedir --hidden-import 'torch.jit' --collect-all ultralytics --collect-all torch --collect-all torchvision webserver_simple_minimal.py`
I got webserver_simple_minimal.exe. Execute it. If you have an error with missing `cfg/default.yaml` file, just download it https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/default.yaml and put in root (here is an issue https://github.com/ultralytics/ultralytics/issues/1158).

So, sending post to executed from .exe web server gives an error that a new server is starting up:
```
starting server..
127.0.0.1 - - [02/Jan/2024 11:49:16] "POST /enter HTTP/1.1" 200 -
starting..
model loaded
starting server..
```
For send post script I get timeout error.
Then, when I press Ctrl+C to abort web server, I got this:
```
aborted
aborted
```

**Any ideas what's wrong and how to fix? It's very extremely important question, because I must wrap my script to .exe file for exporting.
What tests I can also make to figure out the problem? Maybe convert .pt model to other?**

### Environment

OS: Windows 11 x64
python: 3.9.18 (latest), installed with miniconda
torch: 1.9.0
torchvision: 0.10.0
pyinstaller: 6.3.0 (latest)
ultralytics: 8.0.231 (latest)
---
UPDATE: I tested on python: 3.11.15 (latest), torch: 2.1.2 (latest), torchvision: 0.16.2 (latest) - the same problem.

Ultralytics YOLOv8.0.231 🚀 Python-3.9.18 torch-1.9.0+cpu CPU (Intel Core(TM) i9-9880H 2.30GHz)
Setup complete ✅ (4 CPUs, 6.0 GB RAM, 687.7/931.5 GB disk)

### Minimal Reproducible Example

```
$ conda create --name myenv python=3.9
$ conda activate myenv
$ conda install libpng
$ conda install jpeg
$ conda install pytorch==1.9.0 torchvision==0.10.0 -c pytorch
$ pip install ultralytics
```

webserver on flask with minimal code:

```python
import cv2
import numpy as np
import base64
import time
from flask import Flask
from flask import request
app = Flask(__name__)
from ultralytics import YOLO

@app.route("/enter", methods=["POST"])
def enter():
    img = request.json['img']
    nparr = np.frombuffer(base64.b64decode(img), np.uint8)
    img_np = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
    if img_np is None:
        return 'error_img'

    print('starting enter()')
    model = YOLO('best.pt')
    print('model loaded')
    results = model.predict(source=img_np, show=False, save=False, save_conf=False, show_conf=False, save_txt=False)
    print('model predicted')

    return 'ok'

if __name__ == '__main__':
    print('starting server..')
    try:
        app.run(port=5000)
    finally:
        print('aborted')
        time.sleep(2)
```

plain webserver (webserver_simple_minimal.py):
```python
from http.server import BaseHTTPRequestHandler, HTTPServer
import json
import cv2
import numpy as np
import base64
import time
from ultralytics import YOLO

class MyServer(BaseHTTPRequestHandler):
    def do_POST(self):
        self.send_response(200)
        self.send_header("Content-type", "text/html")
        self.end_headers()

        content_length = int(self.headers['Content-Length'])
        post_data = json.loads(self.rfile.read(content_length))
        img = post_data['img']

        nparr = np.frombuffer(base64.b64decode(img), np.uint8)
        img_np = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
        
        print('starting..')
        model = YOLO('best.pt')
        print('model loaded')
        results = model.predict(source=img_np, show=False, save=False, save_conf=False, show_conf=False, save_txt=False)
        print('model predicted')

        self.wfile.write(bytes(f"ok", "utf-8"))

if __name__ == "__main__":    
    print('starting server..')    
    webServer = HTTPServer(('localhost', 5000), MyServer)
    try:
        webServer.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        print('aborted')
        time.sleep(2)
    webServer.server_close()
```

send post:
```python
import requests
import base64
import time

with open('img.png', 'rb') as f:
    image_data_binary = f.read()
    img = (base64.b64encode(image_data_binary)).decode('ascii')

print('sending post..')
response = requests.post('http://127.0.0.1:5000/enter', json={'img': img}, headers={'Content-type': 'application/json'}, timeout=10)
print(response, response.text)
```

**Comment by fridary** [comment]
Solution here https://github.com/pyinstaller/pyinstaller/issues/8210

**Comment by glenn-jocher** [comment]
@fridary thank you for the detailed report. It seems like you've encountered an issue related to PyInstaller rather than YOLOv8 itself. I recommend checking the solution provided in the PyInstaller issue you've linked to. If the problem persists after trying the suggested fixes, it might be beneficial to open an issue on the PyInstaller GitHub repository, as they might be able to offer more targeted assistance for packaging-related problems. Good luck, and I hope you're able to resolve the issue soon! 🛠️

**Comment by thinhemb** [comment]
@fridary  exp:  you can --add-data "C:/Users/KNT21818/AppData/Roaming/Python/Python39/site-packages/ultralytics;ultralytics/" I tried it and it worked.
