### ISSUE TITLE
Is it possible to return a mosaic with probabilities when detecting objects?

### ISSUE THREAD

**Issue by blackcement** [ultralytics/ultralytics#728]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Very often, when finding articles on YOLO, I saw this picture. Circled in red.
![box2](https://user-images.githubusercontent.com/61663301/215578916-878b8d53-595b-47d8-9978-316dc22d37a9.JPG)
Is it possible to implement a similar result in YOLO?

**Comment by dmddmd** [comment]
I kindly want to ask this question again, since I am also interested in such a mosaic

**Comment by pderrenger** [comment]
@dmddmd yes, it's possible to return a mosaic with probabilities when detecting objects in YOLOv8. This can be done by visualizing the object detection results along with their respective class probabilities and bounding boxes. You can achieve a similar output as the one in the image you provided by accessing the class probabilities and drawing the bounding boxes around the detected objects. If you need guidance on how to implement this, feel free to ask for more details!
