### ISSUE TITLE
Yolov8 no GPU usages and running stops before epochs

### ISSUE THREAD

**Issue by MargotDriessen** [ultralytics/ultralytics#7281]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hi, I am trying to train a model with yolov8 on my GPU (on CPU it is working but I want to learn about GPU training and play around with larger datasets if I get this working).  When I run my code to train the model it does start but will not continue to run any epochs and freezes (I pasted the output at the end after spyder console output). I have no idea why this is not working, especially since torch.cuda.is_available() returns True and it outputs the correct GPU name. 

I installed:
- Cudnn 8.9.7
-  Cuda toolkit 12.1
I checked them in a compatibility table before installing and followed the instructions (also for my quadro p1000) 

I installed via conda with: conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia

I used this to check if the GPU is available and if it can find the quadro gpu:
torch.cuda.is_available(): True
torch._C._cuda_getDeviceCount(): 1
torch.cuda.current_device(): 0
torch.cuda.device_count(): 1
device name:  Quadro P1000

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.99 Driver Version: 537.99 CUDA Version: 12.2 |
|-----------------------------------------+----------------------+----------------------+
| GPU Name TCC/WDDM | Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap | Memory-Usage | GPU-Util Compute M. |
| | | MIG M. |
|=========================================+======================+======================|
| 0 Quadro P1000 WDDM | 00000000:01:00.0 Off | N/A |
| N/A 53C P8 N/A / ERR! | 762MiB / 4096MiB | 0% Default |
| | | N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes: |
| GPU GI CI PID Type Process name GPU Memory |
| ID ID Usage |
|=======================================================================================|
| 0 N/A N/A 33124 C ...g\anaconda3\envs\venvgpu\python.exe N/A |
+---------------------------------------------------------------------------------------+

Spyder console output:
runfile('C:/Users/SID-Drebbelweg/SMR2Landuwasco/untitled0.py', wdir='C:/Users/SID-Drebbelweg/SMR2Landuwasco')
torch.cuda.is_available(): True
torch._C._cuda_getDeviceCount(): 1
torch.cuda.current_device(): 0
torch.cuda.device_count(): 1
device name:  Quadro P1000
Traceback (most recent call last):

  File ~\anaconda3\envs\venvgpu\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\sid-drebbelweg\smr2landuwasco\untitled0.py:14
    print(ultralytics.check())

AttributeError: module 'ultralytics' has no attribute 'check'

runfile('C:/Users/SID-Drebbelweg/SMR2Landuwasco/untitled0.py', wdir='C:/Users/SID-Drebbelweg/SMR2Landuwasco')
torch.cuda.is_available(): True
torch._C._cuda_getDeviceCount(): 1
torch.cuda.current_device(): 0
torch.cuda.device_count(): 1
device name:  Quadro P1000
Ultralytics YOLOv8.0.230 🚀 Python-3.10.11 torch-2.1.2 CUDA:0 (Quadro P1000, 4096MiB)
Setup complete ✅ (12 CPUs, 15.8 GB RAM, 469.1/474.5 GB disk)
None

runfile('C:/Users/SID-Drebbelweg/SMR2Landuwasco/train-validate-predict_copy.py', wdir='C:/Users/SID-Drebbelweg/SMR2Landuwasco')
Train images path: C:\Users\SID-Drebbelweg\SMR2Landuwasco\dataset6\train/images
Validation images path: C:\Users\SID-Drebbelweg\SMR2Landuwasco\dataset6\valid/images
Number of training images: 376
Number of validation images: 37
Current cuda device: 0
Count of using GPUs: 1
True
New https://pypi.org/project/ultralytics/8.0.232 available 😃 Update with 'pip install -U ultralytics'
engine\trainer: task=detect, mode=train, model=yolov8n.pt, data=dataset6yaml.yaml, epochs=1, time=None, patience=50, batch=4, imgsz=640, save=True, save_period=-1, cache=False, device=cuda:0, workers=8, project=None, name=yolov8n_toweltrainingV712, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\yolov8n_toweltrainingV712
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]           
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]                  
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]                
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]                 
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]           
Model summary: 225 layers, 3011043 parameters, 3011027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning C:\Users\SID-Drebbelweg\SMR2Landuwasco\dataset6\train\labels.cache... 376 images, 1 backgrounds, 0 corrupt: 100%|██████████| 376/376 [00:00<?, ?it/s]    <- from here it just freezes

### Environment

Ultralytics YOLOv8.0.230 🚀 Python-3.10.11 torch-2.1.2 CUDA:0 (Quadro P1000, 4096MiB)
Setup complete ✅ (12 CPUs, 15.8 GB RAM, 469.1/474.5 GB disk)
None

### Minimal Reproducible Example

from ultralytics import YOLO
import glob
import os
import yaml 
import torch

# Verify paths in dataset.yaml
dataset_yaml_path = 'C:/Users/SID-Drebbelweg/SMR2Landuwasco/dataset6yaml.yaml'
with open(dataset_yaml_path, 'r') as yaml_file:
    dataset_config = yaml.safe_load(yaml_file)

train_images_path = os.path.join(dataset_config['path'], dataset_config['train'])
valid_images_path = os.path.join(dataset_config['path'], dataset_config['val'])

print(f"Train images path: {train_images_path}")
print(f"Validation images path: {valid_images_path}")

# Check image directories
train_images_list = glob.glob(os.path.join(train_images_path, '*.jpg'))
valid_images_list = glob.glob(os.path.join(valid_images_path, '*.jpg'))

print(f"Number of training images: {len(train_images_list)}")
print(f"Number of validation images: {len(valid_images_list)}")

#parameters
EPOCHS = 1  # training cycles/iterations over training data
BATCH = 4  # how many images to train on at a time
IMG_SIZE = 640

#"""train

model = YOLO('yolov8n.pt')

print('Current cuda device:', torch.cuda.current_device())
print('Count of using GPUs:', torch.cuda.device_count())
print(torch.cuda.is_available())

results = model.train(
    data='dataset6yaml.yaml',
    imgsz=IMG_SIZE,
    epochs=EPOCHS,
    batch=BATCH,
    name='yolov8n_toweltrainingV7',
    device = torch.device('cuda:0'),
    save=True
)

#"""

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MargotDriessen** [comment]
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0


+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.99                 Driver Version: 537.99       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Quadro P1000                 WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   53C    P8              N/A / ERR! |    762MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     33124      C   ...g\anaconda3\envs\venvgpu\python.exe    N/A      |
+---------------------------------------------------------------------------------------+

**Comment by MargotDriessen** [comment]
It is working now. 
I had a few mistakes in my installation. print(torch.version.cuda) returned an older version of cuda. I don't know exactly how this works or what was wrong but tried using pip install method from https://docs.ultralytics.com/quickstart/#conda-docker-image instead of conda and did an fresh install of everything in a new enviroment.  

I also added workers=0  to the training and this seems to be working. It is training at about 20-30% of the GPU with batch size 8 and 100 epochs. 

results = model.train(
    data='dataset6yaml.yaml',
    imgsz=IMG_SIZE,
    epochs=EPOCHS,
    batch=BATCH,
    name='yolov8n_toweltrainingV7',
    device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu'),
    #device = torch.device('cpu'),
    workers=0,
    save=True
)

**Comment by glenn-jocher** [comment]
@MargotDriessen i'm glad to hear that you've resolved the issue and your YOLOv8 model is now training on your GPU! It sounds like ensuring the correct CUDA version and setting up a fresh environment helped. Also, adjusting the number of workers can indeed influence the training process, especially in environments with specific GPU configurations. Great job troubleshooting and finding a solution that works for your setup. If you have any further questions or run into more issues, feel free to reach out. Happy training! 🚀👍
