### ISSUE TITLE
Consider using another license that is not AGPL

### ISSUE THREAD

**Issue by Sharpz7** [ultralytics/ultralytics#7284]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I totally understand why you have chosen it - you want to make sure that if people make additions to the ultralytics codebase, they have to share those changes, even if providing it as an API. But the requirement for me to release all my code under the same license is extremely challenging - I am virtually guaranteed that no corporate entity will agree to use my work if it is under AGPL.

Is this something that you would consider if there was wider support for it? Or is it out of the question? I feel another copy-left GPL license would also be suitable.

**Comment by glenn-jocher** [comment]
@Sharpz7 thank you for your input on the licensing of YOLOv8. We appreciate your understanding of our choice to use the AGPL-3.0 license, which indeed aims to ensure that enhancements to the codebase remain open and benefit the community.

While we recognize the challenges that the AGPL-3.0 license may pose in certain corporate environments, it is a deliberate choice to align with our goals for open collaboration. However, for those requiring more flexibility for commercial product development, we offer an Enterprise License that allows integration of Ultralytics software in commercial products without the open-source requirements of AGPL-3.0.

At this time, we are not considering a change to the licensing of YOLOv8, but we are always listening to the community and evaluating how we can best serve its needs while maintaining our values. Your feedback is valuable, and we encourage you to explore the Enterprise License if it better suits your use case.

For more details on licensing and available options, please refer to our documentation. 📚

**Comment by Sharpz7** [comment]
@glenn-jocher appreciate you getting back to me.

>While we recognize the challenges that the AGPL-3.0 license may pose in certain corporate environments, it is a deliberate choice to align with our goals for open collaboration. However, for those requiring more flexibility for commercial product development, we offer an Enterprise License that allows integration of Ultralytics software in commercial products without the open-source requirements of AGPL-3.0.

How would this work if I integrate Ultralytics into my open source code that I also release under AGPL-3.0, would I also need to have an "Enterprise License" Option, and then pass them to you to get one for your codebase as well?

That is my confusion - I am not sure how that process would work with the extra step of my code also being open source.

Thanks!

**Comment by glenn-jocher** [comment]
@Sharpz7 If you're releasing your open-source code under AGPL-3.0 and integrating Ultralytics software, you wouldn't need an Enterprise License for your project. The AGPL-3.0 license for YOLOv8 is designed to be compatible with other AGPL-3.0 projects. Users of your AGPL-3.0 project would only need to comply with the AGPL-3.0 terms, just as you have with YOLOv8. The Enterprise License is an option for those who cannot comply with AGPL-3.0, typically in closed-source commercial scenarios. Hope this clarifies your query! 😊

**Comment by Sharpz7** [comment]
@glenn-jocher, sorry this isn't quite what I mean.

If I create my code under AGPL, release it publicly, and then a corporate entity wishes to use MY code, which contains yours, how would that work?

**Comment by glenn-jocher** [comment]
@Sharpz7 If a corporate entity wishes to use your AGPL-3.0 licensed code which includes YOLOv8, they would need to comply with the AGPL-3.0 terms for both your code and YOLOv8. If they are unable to comply with AGPL-3.0, they would need to obtain an Enterprise License from Ultralytics for the use of YOLOv8. You would handle the licensing for your own code independently. The Enterprise License from Ultralytics would cover the YOLOv8 portion of the codebase, allowing the corporate entity to use it under different terms than AGPL-3.0.

**Comment by Sharpz7** [comment]
Great! Thank you :))

**Comment by glenn-jocher** [comment]
@Sharpz7 you're welcome! 😊 If you have any more questions, feel free to ask. Happy coding!
