### ISSUE TITLE
Yolov8-seg masks are being cutoff by the bounding boxes.

### ISSUE THREAD

**Issue by NawoyaSarah** [ultralytics/ultralytics#7288]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello
I am working with yolov8-seg, and i am interested in the mask area. However, the mask area is being reduced by the effect of the bounding box. How do i solve this. Attached is the image, you can view one side to be flattened out with the box line.  
<img width="77" alt="image" src="https://github.com/ultralytics/ultralytics/assets/140705677/39efe1db-eceb-433a-b7e6-03cdfb134a0e">

**Comment by NawoyaSarah** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> ### Question
> Hello I am working with yolov8-seg, and i am interested in the mask area. However, the mask area is being reduced by the effect of the bounding box. How do i solve this. Attached is the image, you can view one side to be flattened out with the box line. <img alt="image" width="77" src="https://private-user-images.githubusercontent.com/140705677/293897981-39efe1db-eceb-433a-b7e6-03cdfb134a0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMDgxMjUsIm5iZiI6MTcwNDMwNzgyNSwicGF0aCI6Ii8xNDA3MDU2NzcvMjkzODk3OTgxLTM5ZWZlMWRiLWVjZWItNDMzYS1iN2U2LTAzY2RmYjEzNGEwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QxODUwMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjA5ZWNjOGRkNTc2Y2U5ZGMzMTk4MmUzNDU1ZmQ2M2UzZTIzYmMxOGZhNmI4Y2FlMDliZmMxY2FjOWFhMzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pQQH7DERe-8FUEHFV6oM-kVIF4a2c8GjzNiui-K408M">
> 
> ### Additional
> _No response_

@glenn-jocher could you be having any idea about this, please?

**Comment by Laughing-q** [comment]
@NawoyaSarah try predict with arg `retina_masks=True`
