### ISSUE TITLE
How can I get excel file from plot_pr_curve?

### ISSUE THREAD

**Issue by seon-creator** [ultralytics/ultralytics#7297]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I'm using YOLOv8n-seg model for instance segmentation.
I used this code
```
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n-seg.pt')  # load an official model
model = YOLO('/runs/segment/weight_train89_test10_1018/weights/best.pt')  # load a custom model

# Validate the model
metrics = model.val()  # no arguments needed, dataset and settings remembered
```
The code only show the plot images and not make excel file.
![image](https://github.com/ultralytics/ultralytics/assets/118324988/6b576e92-b400-48e3-9d88-1b7f4da1e8fc)

I want to get recall & precision value of the pr-curve.
So I check the code of Ultralytics and found plot_pr_curve function code from ultralytics/ultralytics/utils/metrics.py.

```
@plt_settings()
def plot_pr_curve(px, py, ap, save_dir=Path('pr_curve.png'), names=(), on_plot=None):
    """Plots a precision-recall curve."""
    fig, ax = plt.subplots(1, 1, figsize=(9, 6), tight_layout=True)
    py = np.stack(py, axis=1)

    if 0 < len(names) < 21:  # display per-class legend if < 21 classes
        for i, y in enumerate(py.T):
            ax.plot(px, y, linewidth=1, label=f'{names[i]} {ap[i, 0]:.3f}')  # plot(recall, precision)
    else:
        ax.plot(px, py, linewidth=1, color='grey')  # plot(recall, precision)

    ax.plot(px, py.mean(1), linewidth=3, color='blue', label='all classes %.3f mAP@0.5' % ap[:, 0].mean())
    ax.set_xlabel('Recall')
    ax.set_ylabel('Precision')
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.legend(bbox_to_anchor=(1.04, 1), loc='upper left')
    ax.set_title('Precision-Recall Curve')
    fig.savefig(save_dir, dpi=250)
    plt.close(fig)
    
    if on_plot:
        on_plot(save_dir)
```

From this code I want to make excel file including Recall and Precision value.
How can I do for this?
Is any other method for make excel file?

**Comment by glenn-jocher** [comment]
@seon-creator hello! To extract recall and precision values from the `plot_pr_curve` function for use in an Excel file, you would need to access the `px` (recall) and `py` (precision) variables directly. These variables contain the data points for the precision-recall curve.

Currently, the `plot_pr_curve` function is designed to plot and save the curve as an image, and does not include functionality to export data to an Excel file. However, you can modify your local copy of the function or create a new function to save `px` and `py` to a CSV file, which can then be easily opened in Excel.

You would use Python's built-in `csv` module or the `pandas` library to write the recall and precision values to a CSV file. Once you have the CSV file, you can open it with Excel and manipulate the data as needed.

Remember to follow the guidelines of the AGPL-3.0 license when modifying and using the code from the Ultralytics repository. If you need further assistance with the implementation, please refer to the Ultralytics Docs for more information on the available functions and their usage. 📘🚀
