### ISSUE TITLE
GPU memory usage continuously increases when training a YOLOv8 model.

### ISSUE THREAD

**Issue by RyanDoesMath** [ultralytics/ultralytics#730]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

When training any YOLOv8 model, the memory usage on my GPU continues to get higher and higher as training continues.

My most recent model began around 2.8 gigabytes of VRAM at epoch 2-5, but slowly increased to 3.92 gigabytes by epoch 58.

Could this be a memory leak, or is this behavior intentional? When I begin training a model, how do I know I won't run out of GPU memory hours into training?

### Environment

- Ultralytics YOLOv8.0.18  Python-3.9.13 torch-1.13.0 CUDA:0 (NVIDIA GeForce RTX 3090, 24576MiB)
- OS Windows 10
- Python 3.9.13

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@RyanDoesMath hi, The cuda memory is instances-related while training, the more instances you got the more memory would be occupied. So the OOM could happen when you got more instances for a sudden in one batch. You have to reduce batch-size or reduce imgsz or use small model to solve this OOM issue.

related issue #467.

**Comment by w013nad** [comment]
@RyanDoesMath In addition to the previous response, another thing you might have to do is get rid of some of the images with too many targets. If your images have 1000 targets, it doesn't matter how small the image is.

**Comment by Ss-shuang123** [comment]
> @RyanDoesMath 除了前面的响应之外，您可能要做的另一件事是删除一些目标过多的图像。如果您的图像有 1000 个目标，则图像有多小并不重要。
I also have this problem，and my images sometimes actually have more than 1000 instances. When I have yolov5, this case does not appear. But I don't know the reason.
