### ISSUE TITLE
Validation for image classification not working

### ISSUE THREAD

**Issue by soumik12345** [ultralytics/ultralytics#7302]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val

### Bug

I'm using the following code from the [docs](https://docs.ultralytics.com/tasks/pose/#val):

```python
from ultralytics import YOLO

model = YOLO('yolov8n-cls.pt')
results = model.train(data='mnist160', epochs=5, imgsz=64)
metrics = model.val()
```

On running this on [Google Colab](https://colab.research.google.com/drive/1YChwzDoqf_rnUypAzxrS8iEDRfQpuxKm?usp=sharing), I'm getting the following error at `model.val`:

```
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### Environment

Ultralytics YOLOv8.0.234 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 26.3/166.8 GB disk)

### Minimal Reproducible Example

```python
from ultralytics import YOLO

model = YOLO('yolov8n-cls.pt')
results = model.train(data='mnist160', epochs=5, imgsz=64)
metrics = model.val()
```

[Google Colab](https://colab.research.google.com/drive/1YChwzDoqf_rnUypAzxrS8iEDRfQpuxKm?usp=sharing)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@soumik12345 I'm not able to reproduce it.
![pic-240105-1056-15](https://github.com/ultralytics/ultralytics/assets/61612323/bbc61d99-9555-4194-928a-225813d358c9)
