### ISSUE TITLE
How to resume the previous training while also resuming the logs to be added to the original training logs ?

### ISSUE THREAD

**Issue by SunnyGrocery** [ultralytics/ultralytics#7303]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question
```python
model = YOLO('runs/detect/train/weights/last.pt')
results = model.train(resume=True)
```
The codes just resuming the `trainN`，the folder for `trainN+1` will be recreated to record laste logs. But I want to be added to the original training logs，can you help me?

**Comment by sunmooncode** [comment]
Does it mean the TensorBoard log files are being recreated?

**Comment by glenn-jocher** [comment]
@sunmooncode yes, when resuming training, TensorBoard log files are typically recreated in a new directory. To continue logging in the original directory, you can specify the `--project` and `--name` flags with the paths to the original project and run name when resuming training. This will ensure that logs are appended to the original TensorBoard log files. 📊
