### ISSUE TITLE
Corrupted data corrupts the training

### ISSUE THREAD

**Issue by theATM** [ultralytics/ultralytics#731]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I found that when one uses custom dataset with some corrupted labels. The program while saving the label cache omits them. Therefore second and every later training with loaded cached labels is corrupted since the labels are wrong.  Problem is in (get_labels function in the dataset.py file) -while commenting the cache loading part  or providing the uncorrupted data fixes the issue. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@theATM that is expected as we don't want to use corrupted labels for training.

**Comment by AyushExel** [comment]
@theATM also you can delete the .cache files to force recache

**Comment by theATM** [comment]
Of course when cache is removed it works just fine. The problem is that there are more images than labels (as corrupted labels are omitted) in cache file and therefore most images get wrong labels from cache. Is should be a warning or something so people know that something is wrong - just an idea :/

**Comment by Laughing-q** [comment]
@theATM don't worry, the logic of handling corrupted labels is omitting both the labels and related images so there's no wrong labels here.
