### ISSUE TITLE
Why does he still need to download the yolov8n.pt file when I don’t need to train the pre-trained model?

### ISSUE THREAD

**Issue by JustinGYF** [ultralytics/ultralytics#7312]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I set up the training model, I used the initial yaml file model, but during the running process, I was always asked to download the yolov8n.pt file, and in the process of training the data set, I also used the pre-trained model to train.
How do I ensure that my trained model is the initial model?

**Comment by ExtReMLapin** [comment]
Show us your cmd line

**Comment by glenn-jocher** [comment]
@ExtReMLapin to clarify, the `yolov8n.pt` file is a pre-trained checkpoint that helps to accelerate the training process and improve the final model's performance, even if you're starting with a custom dataset. If you wish to train from scratch without any pre-trained weights, you can do so by specifying `--weights ''` in your training command. This will initiate training with randomly initialized weights. However, training from scratch typically requires more time and data to converge to a similar level of accuracy as a model initialized with pre-trained weights. If you have further questions, please refer to our documentation on the Train mode. 📘🚀
