### ISSUE TITLE
When drawing the picture, it exceeds the right boundary

### ISSUE THREAD

**Issue by sunmooncode** [ultralytics/ultralytics#7324]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In the function [box_label](https://github.com/ultralytics/ultralytics/blob/072291bc78da3a6ebff5c2a84eed49cb4547d50b/ultralytics/utils/plotting.py#L103), only the exceeding of the label box beyond the upper boundary of the image is considered, and not the exceeding of the label beyond the right boundary of the image. Is this considered a bug or do you believe the current state is satisfactory?

Now!
![1704425417905](https://github.com/ultralytics/ultralytics/assets/86471590/5e56af64-2b20-402b-af95-1bf1933b044d)

New!
![1704425471505](https://github.com/ultralytics/ultralytics/assets/86471590/4327c7eb-f181-4a20-ac2f-20f8ab5c2c83)

**Comment by glenn-jocher** [comment]
@sunmooncode hello! Thank you for bringing this to our attention. It seems you've identified a potential issue with the label box drawing function not accounting for the right boundary of the image. This could indeed be considered a bug, as the label box should ideally not exceed any boundaries of the image. We appreciate your diligence in spotting this, and we'll look into addressing it to ensure the label boxes are correctly positioned within the image frame in all cases. If you have any further observations or questions, feel free to share them. Your contributions help us improve! 😊🛠️
