### ISSUE TITLE
yolov8obb models not update

### ISSUE THREAD

**Issue by KTXKIKI** [ultralytics/ultralytics#7326]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Do I need to train myself or will I upload the YOLOv8 OBB model later

**Comment by KTXKIKI** [comment]
@Laughing-q @glenn-jocher

**Comment by Laughing-q** [comment]
@KTXKIKI Thanks for the attention! We'll officially launch the ultralytics 8.1.0 version and obb models in January 10th. Currently we just released the train/val/predict/export functionalities. :) Ideally you could train obb on your custom dataset from scratch and val/predict/export.

**Comment by KTXKIKI** [comment]
> 感谢您的关注！我们将在 1 月 10 日正式推出 ultralytics 8.1.0 版本和 obb 型号。目前，我们刚刚发布了 train/val/predict/export 功能。:)理想情况下，您可以从头开始在自定义数据集上训练 obb 并 val/predict/export。
Thank you very much for your reply. Yolov8 is so strong!!!! @Laughing-q

**Comment by 954028118** [comment]
> > 我们将在 1 月 10 日正式推出 ultralytics 8.1.0 版本和 obb 型号。目前，我们刚刚发布了 train/val/predict/export 功能。:)理想情况下，您可以从头开始在自定义数据集上训练 obb 并 val/predict/export。非常感谢您的回复。Yolov8 太强大了!!!

Will the version to be released use the real obb training method (the predicted information includes Angle, category, xywh), because I saw that the current data processing method takes the horizontal external rectangular box composed of four points, x1y1x2y2x3y3x4y4, in fact, it still uses the hbb training method

**Comment by glenn-jocher** [comment]
@954028118 the upcoming release will indeed support the true OBB (Oriented Bounding Box) training method, where the model predicts angles, categories, and bounding box dimensions. The current data processing approach you mentioned is an interim solution. The full OBB capabilities will be part of the 8.1.0 release, allowing for more accurate object detection in images where orientation is important. Stay tuned for the update! 🚀

**Comment by Laughing-q** [comment]
@KTXKIKI closing the issue as obb models have been released! Please feel free to reopen it if you have any related questions!
