### ISSUE TITLE
Nvidia Triton Inference Server

### ISSUE THREAD

**Issue by sazzadhrz** [ultralytics/ultralytics#733]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Could you please share an implementation of yolov8 to run on Nvidia Triton Inference Server?

**Comment by AyushExel** [comment]
Triton server inference is not yet supported on ultralytics repo. We'll work on it soon

**Comment by mltoml** [comment]
I'm also facing the same issue, do you have any updates or a timeline for such implementation?
I see some possible starting points*; I tried it but for some reason the output looks strange (tested it with an onnx model deployed on triton and python tritonclient used for inference). 

*https://github.com/dinhkt/triton-trt-object-detection

**Comment by mltoml** [comment]
@AyushExel @glenn-jocher

**Comment by glenn-jocher** [comment]
@AyushExel @mltoml triton server is actually in our supported AutoBackend formats, but this is inherited from YOLOv5 as part of our work with OctoML and not tested yet for YOLOv8.

**Comment by mltoml** [comment]
yeah @gaziqbal did a very nice work integrating YOLOv5 detect with triton*, hopefully we see that replicated in YOLOv8 soon.
  *https://github.com/ultralytics/yolov5/pull/9228

**Comment by mltoml** [comment]
@AyushExel @glenn-jocher Would it be possible to reopen this issue again?

**Comment by glenn-jocher** [comment]
@mltoml certainly! We apologize for any confusion - this issue can absolutely be reopened if you have further questions or if an update to the status of Triton support is desired. As Glenn mentioned previously, Triton server inference is supported as part of our work with OctoML and YOLOv5, but it has not been tested yet for YOLOv8. However, we are always looking to expand and improve the capabilities of our software, so we encourage you to stay tuned for future updates! In the meantime, please feel free to check out the Ultralytics Docs and HUB for additional resources, and don't hesitate to ask any further questions you may have.

**Comment by marunava21** [comment]
@glenn-jocher may i know if the inference is available for yolov8 yet? as i don't see any further comment for this thread.

**Comment by glenn-jocher** [comment]
Yes we have a PR open for this now , please check PR section and leave any comment in the Triton Server PR.
