### ISSUE TITLE
What does the runtime prompt about image size mean

### ISSUE THREAD

**Issue by Sparklexa** [ultralytics/ultralytics#7332]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I set the image size to imgsz=[1280, 720], why do 416x736 prompts appear, what does this mean
Specific prompt content：
WARNING ⚠️ imgsz=[1280, 720] must be multiple of max stride 32, updating to [1280, 736]
0: 416x736 (no detections), 11.5ms
Speed: 2.0ms preprocess, 11.5ms inference, 1.0ms postprocess per image at shape (1, 3, 416, 736)

**Comment by Kayzwer** [comment]
@Sparklexa both width and height have to be multiple of 32.

**Comment by Sparklexa** [comment]
@Kayzwer I know this point, now the focus of the problem is not the problem of 32 times round, but I set the size is [1280, 720], but the prompt information is 416x736, I do not understand what 416x736 means
