### ISSUE TITLE
How do I save all my results in one folder in YOLOv8

### ISSUE THREAD

**Issue by Olivia-Seo** [ultralytics/ultralytics#7333]
I want to save all my predicted images in "media/results" folder under name "detected_image_0.png", next image will be "detected_image_1.png", "detected_image_.png", etc. 
Below is my current result and code. It creates sub-folder to contain the predicted image .
[
![file_structure](https://github.com/ultralytics/ultralytics/assets/76605525/8b4cbc29-e420-46cd-a13d-b29fc13bec84)
](url)

**Comment by NguyenDucQuan12** [comment]
I remember its keyword is save_dir='xxx\xxx', try searching for this keyword in the document to see

**Comment by glenn-jocher** [comment]
@NguyenDucQuan12 to save all your predicted images in a specific directory with a custom naming convention like "detected_image_0.png", you can set the `save_dir` parameter to your desired path, such as "media/results". The filenames will automatically increment for each new image. For more details on how to customize the output directory and filenames, please refer to the documentation on the Predict mode at https://docs.ultralytics.com/modes/predict. Happy detecting! 😊📸

**Comment by glenn-jocher** [comment]
@Olivia-Seo i'm glad to hear from you again! If the results are not as expected, ensure that the `project` and `name` parameters are correctly set in your code. The `project` should be the directory where you want to save the results, and `name` should be set to an empty string if you want to avoid creating a subdirectory. This will save all the images directly to the specified `project` directory with incrementing filenames. For further guidance, please review the documentation on the Predict mode. Keep up the great work! 😊👍

**Comment by GTziolas** [comment]
@Olivia-Seo @glenn-jocher I'm having the same problem for the .train() method. The line of code is:
`model.train(data=dataset_path, epochs=EPOCHS, project='.', name='run_results', device=DEVICE, save=True)`. So if I train this for 3 EPOCHS, I have the folders `run_results`, `run_results2`, `run_results3` created and the results are in there. How can I just save all results in one folder, as described in the `train()` method call?

**Comment by glenn-jocher** [comment]
Hi @GTziolas,

Thank you for reaching out! To save all your training results in a single folder without creating multiple subdirectories, you can set the `exist_ok` parameter to `True` in your `model.train()` method. This will prevent the creation of new directories for each run and save all results in the specified folder.

Here's how you can modify your code:

```python
model.train(data=dataset_path, epochs=EPOCHS, project='.', name='run_results', device=DEVICE, save=True, exist_ok=True)
```

With `exist_ok=True`, all results will be saved in the `run_results` folder, and subsequent runs will overwrite the existing files if they have the same names.

If you have any further questions or need additional assistance, feel free to ask. Happy training! 😊
