### ISSUE TITLE
How to enable Albumentations in yolov8 train?

### ISSUE THREAD

**Issue by PelkiuBebras** [ultralytics/ultralytics#7339]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to enable Albumentations in yolov8 train?
Did set augment=True, but terminal output does not show a line with a albumentations information

`model = YOLO('yolov8n.pt')

results = model.train(data='data/data.yaml',
                      epochs=200,
                      patience=30,
                      imgsz=(320, 320),
                      batch=64,
                      augment=True)
`

**Comment by glenn-jocher** [comment]
@PelkiuBebras hello! To enable Albumentations in YOLOv8 training, you don't need to set `augment=True` as this is not the correct parameter. Instead, you should specify your desired Albumentations augmentations within your dataset configuration file (`data.yaml`). There, you can define a variety of augmentation strategies under the `albumentations` key.

Please refer to the Ultralytics Docs for detailed instructions on how to configure your `data.yaml` with Albumentations. If you follow the guidelines there, the augmentations should be applied during training, and you'll be able to see the effects in your training results. Happy training! 😊

**Comment by PelkiuBebras** [comment]
Search for a while, but did not find instructions on enabling Albumentations. Would it be possible to provide a link?
Thanks!

**Comment by glenn-jocher** [comment]
@PelkiuBebras certainly! You can find the instructions for configuring Albumentations in the YOLOv8 documentation under the 'Train' section. Please visit the Ultralytics Docs and navigate to the 'Train' page for detailed guidance. 😊

**Comment by PelkiuBebras** [comment]
Could not find Albumentations setup instructions in the ["Train" section ](https://docs.ultralytics.com/modes/train/) :D  How to procced?

**Comment by glenn-jocher** [comment]
@PelkiuBebras apologies for the confusion. The Albumentations setup instructions are indeed not directly mentioned in the "Train" section. For YOLOv8, augmentations are configured within the `data.yaml` file, but we currently do not support Albumentations directly. Instead, YOLOv8 uses a built-in augmentation system that is automatically applied when training. If you're looking to customize augmentations beyond what's provided, you would need to modify the source code. Keep an eye on our updates, as we're always working to improve and potentially include more features like Albumentations in the future. 😊

**Comment by PelkiuBebras** [comment]
Thanks for information!

**Comment by glenn-jocher** [comment]
@PelkiuBebras You're welcome! If you have any more questions or need further assistance, feel free to ask. Happy training! 😊

**Comment by lushikai** [comment]
@glenn-jocher Hello, contributors！I have a small number of detection datasets, so I want to do data augmentation to increase the number of images, so that there are enough images for training, I learned about the albumentations library, how do I work in the source code, thank you！

**Comment by glenn-jocher** [comment]
Hello @lushikai! Currently, YOLOv8 doesn't directly support Albumentations out of the box. However, you can manually integrate Albumentations by modifying the dataset loading and preprocessing code. You would need to adjust the part where images are loaded and transformed in the training loop. Here's a basic example of how you might apply an Albumentations augmentation:

```python
from albumentations import Compose, RandomCrop, HorizontalFlip, Rotate
from albumentations.pytorch import ToTensorV2

def get_train_transform():
    return Compose([
        RandomCrop(width=450, height=450),
        HorizontalFlip(p=0.5),
        Rotate(limit=45, p=0.5),
        ToTensorV2(),
    ])

# Then apply get_train_transform() to your images as they are loaded
```

You'll need to integrate this into the data loading part of your YOLOv8 training pipeline. This might involve some familiarity with the codebase and possibly overriding some default behaviors. Good luck, and happy coding! 😊

**Comment by lushikai** [comment]
@glenn-jocher thanks, i got it!

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance as you work with YOLOv8, just let us know. Happy coding! 😊

**Comment by lushikai** [comment]
@glenn-jocher Hello! I divide the dataset into a training set and a validation set. Which dataset should the data augmentation be applied to, or both?

**Comment by lushikai** [comment]
```
import albumentations as A
import cv2
import os

transform = A.Compose([
    A.GaussNoise(var_limit=(10.0, 50.0), p=0.5),
    A.GaussianBlur(blur_limit=(3, 7), p=0.5),
    A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, p=0.5),
    A.RandomGamma(gamma_limit=(80, 120), p=0.5),
    A.ISONoise(color_shift=(0.01, 0.05), intensity=(0.1, 0.5), p=0.5),
    A.ToGray(p=0.5),
    A.HueSaturationValue(hue_shift_limit=20, sat_shift_limit=30, val_shift_limit=20, p=0.5)
])

def read_yolo_labels(label_path):
    with open(label_path, 'r') as f:
        labels = [line.strip() for line in f.readlines()]
    return labels

def write_yolo_labels(label_path, labels):
    with open(label_path, 'w') as f:
        for label in labels:
            f.write(f"{label}\n")

def main(image_path, label_path, output_image_dir, output_label_dir, augmented_num):
    # Read image
    image = cv2.imread(image_path)
    # Read labels
    labels = read_yolo_labels(label_path)
    base_name = os.path.splitext(os.path.basename(image_path))[0]
    for i in range(augmented_num):
        # Apply data augmentation
        transformed = transform(image=image)
        transformed_image = transformed['image']
        
        output_image_path = os.path.join(output_image_dir, f"{base_name}_{i}.jpg")
        output_label_path = os.path.join(output_label_dir, f"{base_name}_{i}.txt")

        # Save augmented image and labels
        cv2.imwrite(output_image_path, transformed_image)
        write_yolo_labels(output_label_path, labels)

if __name__ == "__main__":
    # Define directories
    input_image_dir = '/mnt/e/datasets/train/images'
    input_label_dir = '/mnt/e/train/labels'
    output_image_dir = '/mnt/e/augmented/train/images'
    output_label_dir = '/mnt/e/augmented/train/labels'
    
    if not os.path.exists(output_image_dir):
        os.makedirs(output_image_dir)
    if not os.path.exists(output_label_dir):
        os.makedirs(output_label_dir)

    for image_name in os.listdir(input_image_dir):
        if image_name.endswith('.jpg') or image_name.endswith('.png'):
            base_name = os.path.splitext(image_name)[0]
            image_path = os.path.join(input_image_dir, image_name)
            label_path = os.path.join(input_label_dir, base_name + '.txt')
            
            if os.path.exists(label_path):
                main(image_path, label_path, output_image_dir, output_label_dir, augmented_num=5)

```
@glenn-jocher and Here is my data augmentation method using albumentations Library. Could review my code if you will? This method is to augment the dataset before training to generate more augmented images. Whether 'read_yolo_labels' method and 'write_yolo_labels' method have been implemented in ultralytics?

**Comment by glenn-jocher** [comment]
Hello @lushikai! Your approach to data augmentation using the Albumentations library looks solid. It's great to see you leveraging these powerful augmentations to enhance your dataset. Here are a few points and suggestions to consider:

1. **Augmentation Application**:
   - Data augmentation should generally be applied to the training set only. The purpose of augmentation is to introduce variability and help the model generalize better. Applying it to the validation set could lead to misleading performance metrics since the validation set should represent real-world data as closely as possible.

2. **Label Handling**:
   - Your `read_yolo_labels` and `write_yolo_labels` methods are well-implemented for reading and writing YOLO format labels. Currently, Ultralytics does not provide built-in methods for these specific tasks, so your custom implementation is necessary and looks correct.

3. **Code Review**:
   - Your code for reading, augmenting, and saving images and labels is clear and well-structured. Here are a few minor suggestions for improvement:
     - Ensure that the augmented images and labels are correctly aligned. Your current implementation maintains the original labels, which is correct if the augmentations do not alter the bounding box coordinates.
     - Consider adding more comments or docstrings for better readability and maintainability.

Here's a slightly refined version of your code with some additional comments:

```python
import albumentations as A
import cv2
import os

# Define the augmentation pipeline
transform = A.Compose([
    A.GaussNoise(var_limit=(10.0, 50.0), p=0.5),
    A.GaussianBlur(blur_limit=(3, 7), p=0.5),
    A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, p=0.5),
    A.RandomGamma(gamma_limit=(80, 120), p=0.5),
    A.ISONoise(color_shift=(0.01, 0.05), intensity=(0.1, 0.5), p=0.5),
    A.ToGray(p=0.5),
    A.HueSaturationValue(hue_shift_limit=20, sat_shift_limit=30, val_shift_limit=20, p=0.5)
])

def read_yolo_labels(label_path):
    """Read YOLO format labels from a file."""
    with open(label_path, 'r') as f:
        labels = [line.strip() for line in f.readlines()]
    return labels

def write_yolo_labels(label_path, labels):
    """Write YOLO format labels to a file."""
    with open(label_path, 'w') as f:
        for label in labels:
            f.write(f"{label}\n")

def main(image_path, label_path, output_image_dir, output_label_dir, augmented_num):
    # Read image
    image = cv2.imread(image_path)
    # Read labels
    labels = read_yolo_labels(label_path)
    base_name = os.path.splitext(os.path.basename(image_path))[0]
    for i in range(augmented_num):
        # Apply data augmentation
        transformed = transform(image=image)
        transformed_image = transformed['image']
        
        output_image_path = os.path.join(output_image_dir, f"{base_name}_{i}.jpg")
        output_label_path = os.path.join(output_label_dir, f"{base_name}_{i}.txt")

        # Save augmented image and labels
        cv2.imwrite(output_image_path, transformed_image)
        write_yolo_labels(output_label_path, labels)

if __name__ == "__main__":
    # Define directories
    input_image_dir = '/mnt/e/datasets/train/images'
    input_label_dir = '/mnt/e/train/labels'
    output_image_dir = '/mnt/e/augmented/train/images'
    output_label_dir = '/mnt/e/augmented/train/labels'
    
    if not os.path.exists(output_image_dir):
        os.makedirs(output_image_dir)
    if not os.path.exists(output_label_dir):
        os.makedirs(output_label_dir)

    for image_name in os.listdir(input_image_dir):
        if image_name.endswith('.jpg') or image_name.endswith('.png'):
            base_name = os.path.splitext(image_name)[0]
            image_path = os.path.join(input_image_dir, image_name)
            label_path = os.path.join(input_label_dir, base_name + '.txt')
            
            if os.path.exists(label_path):
                main(image_path, label_path, output_image_dir, output_label_dir, augmented_num=5)
```

Feel free to reach out if you have any more questions or need further assistance. Happy training! 😊

**Comment by lushikai** [comment]
@glenn-jocher Thanks for your detailed explanation and suggestions again! You're so friendly! I have some doubts. Shouldn't it be that the test set is closer to the real world? Generally, it does not provide labels and does not participate in training.  Because the existing dataset is small, it is only divided into a train set and a val set without a test set. In the training step, The model only loads the train and val set.  As you mentioned, I should only do data augmentation on the train set, not the val set? By the way, do you suggest that the test set should be divided for small datasets? If that's the case, what should I do with data augmentation for the train set, the val set and the test set? 😸 😄

**Comment by glenn-jocher** [comment]
Hello @lushikai!

Thank you for your kind words! 😊 You're absolutely right that the test set should be closer to real-world data and generally does not provide labels or participate in training. The test set is used to evaluate the final performance of the model after training is complete, ensuring that the model generalizes well to unseen data.

Given your situation with a small dataset, it's common practice to split the data into just a training set and a validation set. Here's how you should handle data augmentation:

1. **Training Set**: Apply data augmentation to the training set. This helps increase the variability of the training data, allowing the model to generalize better and avoid overfitting. Your current approach using Albumentations is perfect for this.

2. **Validation Set**: Do not apply data augmentation to the validation set. The validation set should represent real-world data as closely as possible to provide an accurate measure of the model's performance during training. Augmenting the validation set could lead to misleading performance metrics.

3. **Test Set**: If you decide to create a test set, it should also not be augmented. The test set should remain untouched and only be used for the final evaluation of the model after training is complete.

Regarding whether to split a small dataset into a training, validation, and test set, it depends on the size of your dataset. If your dataset is very small, you might want to stick with just a training and validation set to ensure you have enough data for both training and validation. However, if you can afford to, having a small test set can still be beneficial for final evaluation.

Here's a quick summary of the data splits and augmentation:

- **Training Set**: Apply data augmentation.
- **Validation Set**: No augmentation.
- **Test Set**: No augmentation (if you decide to create one).

Feel free to reach out if you have any more questions or need further assistance. Happy training! 😄

**Comment by lushikai** [comment]
Hi @glenn-jocher ! I found class Albumentations in ultralytics, the path is 'ultralytics/data/augment.py'. But it seems that it did the data augmentation in training step, and it will be shown in the training log. When I searched for these methods in the Ultralytics library, I had to consult the reference section of the documentation. https://docs.ultralytics.com/zh/reference/data/augment/ But the translation is not very accurate, and it is a bit difficult to read. Can I help with the documentation for ZH if possible?

**Comment by glenn-jocher** [comment]
Hello @lushikai!

Thank you for your keen observation and for pointing out the location of the `Albumentations` class in the Ultralytics library. You're correct that data augmentation is applied during the training step and should be reflected in the training logs.

Regarding the documentation translation, we truly appreciate your willingness to help improve the ZH documentation. Contributions from the community are invaluable in making our resources more accessible and accurate for everyone.

To get started with contributing to the documentation, you can follow these steps:

1. **Fork the Repository**: Fork the Ultralytics GitHub repository to your account.
2. **Clone the Repository**: Clone the forked repository to your local machine.
3. **Make Changes**: Navigate to the documentation files and make the necessary translations and improvements.
4. **Submit a Pull Request**: Once you're satisfied with your changes, submit a pull request to the main repository. Our team will review your contributions and merge them if everything looks good.

For detailed instructions on how to contribute, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing).

If you encounter any issues or have further questions while contributing, feel free to reach out. We're here to help!

Thank you again for your support and contributions to the Ultralytics community. 😊

**Comment by glenn-jocher** [comment]
Hello @lushikai!

Thank you for your enthusiasm and willingness to contribute to the community! Your improved code for data augmentation using Albumentations looks great and is a valuable addition. Here are a few points and suggestions to further enhance your implementation:

1. **Integration with Ultralytics**:
   - If you are looking to integrate this directly with Ultralytics YOLOv8, you can leverage the built-in `Albumentations` class found in `ultralytics/data/augment.py`. This ensures that your augmentations are seamlessly integrated with the training pipeline.

2. **Code Review**:
   - Your code is well-structured and clear. Here are a few minor suggestions:
     - Ensure that the bounding boxes are correctly transformed and remain within the image boundaries after augmentation.
     - Consider adding error handling for file operations to make the script more robust.

3. **Documentation Contribution**:
   - We appreciate your offer to help with the ZH documentation. Contributions from the community are invaluable. You can start by forking the Ultralytics GitHub repository, making your changes, and then submitting a pull request. For detailed instructions, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing).

Here's a slightly refined version of your code with some additional comments and error handling:

```python
import albumentations as A
import cv2
import os

# Define the augmentation pipeline
transform = A.Compose([
    A.GaussNoise(var_limit=(10.0, 50.0), p=0.5),
    A.GaussianBlur(blur_limit=(3, 7), p=0.5),
    A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, p=0.5),
    A.RandomGamma(gamma_limit=(80, 120), p=0.5),
    A.ISONoise(color_shift=(0.01, 0.05), intensity=(0.1, 0.5), p=0.5),
    A.ToGray(p=0.5),
    A.HueSaturationValue(hue_shift_limit=20, sat_shift_limit=30, val_shift_limit=20, p=0.5),
    A.RandomRotate90(p=0.5),
    A.ShiftScaleRotate(shift_limit=0.0625, scale_limit=0.2, rotate_limit=45, p=0.5)
], bbox_params=A.BboxParams(format='yolo', label_fields=['class_labels']))

def read_yolo_labels(label_path):
    """Read YOLO format labels from a file."""
    with open(label_path, 'r') as f:
        labels = f.readlines()
    bboxes = []
    class_labels = []
    for label in labels:
        parts = label.strip().split()
        class_id = int(parts[0])
        x_center = float(parts[1])
        y_center = float(parts[2])
        width = float(parts[3])
        height = float(parts[4])
        bboxes.append([x_center, y_center, width, height])
        class_labels.append(class_id)
    return bboxes, class_labels

def write_yolo_labels(label_path, bboxes, class_labels):
    """Write YOLO format labels to a file."""
    with open(label_path, 'w') as f:
        for bbox, class_id in zip(bboxes, class_labels):
            x_center = round(bbox[0], 6)
            y_center = round(bbox[1], 6)
            width = round(bbox[2], 6)
            height = round(bbox[3], 6)
            f.write(f"{class_id} {x_center} {y_center} {width} {height}\n")

def main(input_image_dir, input_label_dir, output_image_dir, output_label_dir, augmentations_per_image):
    if not os.path.exists(output_image_dir):
        os.makedirs(output_image_dir)
    if not os.path.exists(output_label_dir):
        os.makedirs(output_label_dir)
    
    for image_name in os.listdir(input_image_dir):
        if image_name.endswith(('.jpg', '.png')):
            image_path = os.path.join(input_image_dir, image_name)
            label_name = os.path.splitext(image_name)[0] + '.txt'
            label_path = os.path.join(input_label_dir, label_name)

            # Read image
            image = cv2.imread(image_path)
            if image is None:
                print(f"Error reading image {image_path}")
                continue
            image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

            # Read labels
            bboxes, class_labels = read_yolo_labels(label_path)
            
            for i in range(augmentations_per_image):
                # Apply data augmentation
                transformed = transform(image=image, bboxes=bboxes, class_labels=class_labels)
                transformed_image = transformed['image']
                transformed_bboxes = transformed['bboxes']
                transformed_class_labels = transformed['class_labels']

                # Generate output paths
                output_image_path = os.path.join(output_image_dir, os.path.splitext(image_name)[0] + f'_aug_{i}.jpg')
                output_label_path = os.path.join(output_label_dir, os.path.splitext(image_name)[0] + f'_aug_{i}.txt')

                # Save augmented image and labels
                cv2.imwrite(output_image_path, cv2.cvtColor(transformed_image, cv2.COLOR_RGB2BGR))
                write_yolo_labels(output_label_path, transformed_bboxes, transformed_class_labels)

if __name__ == "__main__":
    # Define directories
    input_image_dir = '/mnt/e/train/images'
    input_label_dir = '/mnt/e/train/labels'
    output_image_dir = '/mnt/e/augmented-train/images'
    output_label_dir = '/mnt/e/augmented-train/labels'
    
    # Process images and labels with multiple augmentations
    main(input_image_dir, input_label_dir, output_image_dir, output_label_dir, augmentations_per_image=5)
```

Feel free to reach out if you have any more questions or need further assistance. Happy coding and thank you for your contributions to the Ultralytics community! 😊

**Comment by lushikai** [comment]
@glenn-jocher Thanks for your suggestion and code review! If i use built-in Albumentations in ultralytics, I want to add a different augment method or increase the augment probability, I should directly increase it or increase the size of p in the following position, but it cannot exceed the default value of 1.0？
![image](https://github.com/ultralytics/ultralytics/assets/121033683/e2a9c114-84bf-4255-b345-5677a93ddfd2)
By the way, about the training log, I noticed that there was a detail when loading the dataset. What does the 'background' and ‘corrupt’ mean？
···
train: Scanning /mnt/e/workspace/datasets/train/labels.cache... 523 images, 0 backgrounds, 0 corrupt: 100%|██████████| 523/523 [00:00<?, ?it/s]
/home/lushikai/miniconda3/envs/yolo/lib/python3.8/site-packages/albumentations/core/composition.py:144: UserWarning: Got processor for bboxes, but no transform to process it.
  self._set_keys()
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
val: Scanning /mnt/e/workspace/datasets/val/labels.cache... 79 images, 0 backgrounds, 0 corrupt: 100%|██████████| 79/79 [00:00<?, ?it/s]
···

I have forked the repository and start to set up the local environment! 😄

**Comment by glenn-jocher** [comment]
Hello @lushikai!

Thank you for your thoughtful questions and for diving into the details of data augmentation with Albumentations in Ultralytics. I'm glad to see your enthusiasm and initiative in contributing to the community! 😊

### Adjusting Augmentation Probability

When using the built-in Albumentations in Ultralytics, you can indeed adjust the probability `p` for each augmentation method to control how often it is applied. The value of `p` should be between 0 and 1, where 1 means the augmentation will always be applied, and 0 means it will never be applied. Here’s an example of how you can adjust the probabilities:

```python
import albumentations as A

transform = A.Compose([
    A.GaussNoise(var_limit=(10.0, 50.0), p=0.5),  # 50% probability
    A.GaussianBlur(blur_limit=(3, 7), p=0.7),     # 70% probability
    A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, p=0.8),  # 80% probability
    # Add more augmentations as needed
])
```

Feel free to add or modify the augmentations and their probabilities according to your needs. Just ensure that the total probability for each augmentation does not exceed 1.0.

### Understanding Training Log Details

In the training log, the terms 'background' and 'corrupt' refer to specific conditions of the dataset images:

- **Background**: This indicates images that do not contain any objects of interest (i.e., images without any labeled objects). In your case, it shows `0 backgrounds`, meaning all images have at least one labeled object.
- **Corrupt**: This refers to images that are unreadable or damaged. The log shows `0 corrupt`, indicating that all images in your dataset are intact and readable.

The warning message from Albumentations (`UserWarning: Got processor for bboxes, but no transform to process it.`) suggests that you have defined bounding box parameters but no transformations that apply to bounding boxes. Ensure that your augmentation pipeline includes transformations that handle bounding boxes if you are working with object detection tasks.

### Setting Up Your Local Environment

It's fantastic to hear that you've forked the repository and are setting up your local environment! If you encounter any issues or have further questions while setting up, feel free to reach out. We're here to help!

Thank you again for your contributions and for being an active member of the Ultralytics community. Happy coding! 🚀

**Comment by lushikai** [comment]
Hello@glenn-jocher ! I recently looked at the composition of the brain tumor dataset provided by Ultralytics, can you explain whether there is a connection between the naming and data of the training set and the validation set, because the validation set is in the val_1 (x) format, x represents the number of images, and the training set uses a different naming method, and the training set has several images as backgrounds, without providing labels, is there any explanation for the choice of background images?
![image](https://github.com/ultralytics/ultralytics/assets/121033683/25eaf608-ac03-4ce6-8b01-7fd270402703)

**Comment by lushikai** [comment]
Hello @glenn-jocher I recently looked at the composition of the brain tumor dataset provided by Ultralytics, can you explain whether there is a connection between the naming and data of the training set and the validation set, because the validation set is in the val_1 (x) format, x represents the number of images, and the training set uses a different naming method, and the training set has several images as backgrounds, without providing labels, is there any explanation for the choice of background images?
![image](https://github.com/ultralytics/ultralytics/assets/121033683/7418a2b7-38e6-40b9-ad08-5201d1a8e1c0)

**Comment by glenn-jocher** [comment]
Hello @lushikai,

Thank you for your detailed question and for your interest in the brain tumor dataset provided by Ultralytics!

### Dataset Naming and Structure
The naming conventions for the training and validation sets may differ to help distinguish between the two sets easily. The `val_1(x)` format for the validation set is designed to clearly indicate the image number, while the training set uses a different method to avoid confusion during the training process.

### Background Images
Regarding the background images in the training set, these images are included intentionally to help the model learn to distinguish between relevant objects (e.g., brain tumors) and irrelevant background. This can improve the model's robustness and accuracy by reducing false positives. Background images do not contain any labeled objects, which is why they do not have corresponding labels.

### Providing a Reproducible Example
If you encounter any issues or have specific concerns, providing a minimum reproducible example can greatly help us diagnose and address the problem more effectively. You can find guidelines on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

### Latest Versions
Please ensure you are using the latest versions of the Ultralytics packages, as updates often include important bug fixes and improvements.

Feel free to reach out if you have any more questions or need further assistance. We're here to help! 😊

**Comment by lushikai** [comment]
@glenn-jocher Thanks for your reply. For the dataset, whether the images are collected first and then divided into the training set and the validation set, that is, whether they are the same batch of images? Or whether the training set and the validation set are collected separately, the verification set is closer to the real application scenario?

**Comment by lushikai** [comment]
@glenn-jocher Thanks for your reply! For the dataset, whether the images are collected first and then divided into the training set and the validation set, that is, whether they are the same batch of images? Or whether the training set and the validation set are collected separately, the validation set is closer to the real application scenario?

**Comment by sharramallah** [comment]
Hi there,

I want to ask for your help. Currently, I am working on a project to detect motorcycle helmets using YOLOv8. Here is the structure of my dataset:

```
dataset/
├── yolov8-helmet-final-use-no-augmentation-3/
│   ├── train/
│   │     ├── augmented_images
│   │     ├── augmented_labels
│   │     ├── images
│   │     ├── labels
│   ├── val/
│   │     ├── images
│   │     ├── labels
└── data.yaml
```

As you can see, I have two additional folders: augmented_images and augmented_labels. I used Albumentations to apply Cutout augmentation to my training dataset, and all augmented images were saved in the augmented_images folder.

To train on the augmented images, I modified the data.yaml file in my dataset structure as follows:

```
train: dataset/yolov8-helmet-final-use-no-augmentation-3/train/augmented_images
val: dataset/yolov8-helmet-final-use-no-augmentation-3/val/images
```

Then, I ran the YOLOv8 training script, pointing to my updated data.yaml:

`yolo task=detect mode=train data=dataset/yolov8-helmet-final-use-no-augmentation-3/data.yaml epochs=100 imgsz=640`

However, the result was not as expected. The box_loss, cls_loss, and dfl_loss were all zero (0), and mAP50 and mAP50-95 were also zero (0) for each epoch.

Am I doing something wrong? Could you please help me understand what might be going wrong?

Thank you.

**Comment by pderrenger** [comment]
Hi there,

It looks like you're on the right track with your dataset structure and augmentation process. However, the zero losses and mAP values suggest that the model might not be finding any objects to train on. Here are a few things to check:

1. Ensure that the paths in your `data.yaml` file are correct and point to the actual locations of your images and labels.
2. Verify that the augmented images and their corresponding labels are correctly formatted and aligned. Each image should have a corresponding label file with the same name but a `.txt` extension.
3. Confirm that the label files contain valid annotations in the YOLO format (class, x_center, y_center, width, height).
4. Make sure you're using the latest version of the Ultralytics package to avoid any potential bugs.

If the issue persists after these checks, please let us know.

**Comment by sharramallah** [comment]
Dear @pderrenger 

Thank you for respond me

Yes, I have ensured everything is as instructed. I have tried multiple times according to my predictions/scenarios:

First attempt: I changed the path in the data.yaml file from images to augmented_images, keeping the original labels.
Second attempt: I deleted the original images and labels, renamed augmented_images to images, and augmented_labels to labels, and ensured the paths were correct in the data.yaml file.
Third attempt: I deleted the original images, renamed augmented_images to images, kept the original labels, and added the augmented_labels. and ensured the paths images were correct in the data.yaml file


The results were still zero.

should I send my gcollab here? May I?

**Comment by pderrenger** [comment]
Dear @sharramallah,

Thank you for your detailed response. It appears that you've taken thorough steps to address the issue. To further diagnose the problem, please ensure that your label files in the augmented set are correctly formatted and aligned with the corresponding images. Additionally, verify that the annotations are valid and not empty.

If the issue persists, please try updating to the latest version of the Ultralytics package to rule out any potential bugs. Unfortunately, we cannot review your gcollab directly here. However, you can share a minimal reproducible example of your dataset structure and a few sample images and labels for further assistance.

**Comment by sharramallah** [comment]
Okay, thank you so much

**Comment by lushikai** [comment]
@pderrenger Hello! Thank you for your attentive answers. For the brain tumor dataset provided by Ultralytics, there are ten images that are not labeled as backgrounds, can I think that brain tumor detection is getting closer to a semi-supervised learning task instead of traditional supervised learning?

**Comment by pderrenger** [comment]
Hello! Thank you for your question. The inclusion of unlabeled background images in the brain tumor dataset is intended to help the model distinguish between relevant and irrelevant content, improving its robustness. While this does introduce an element similar to semi-supervised learning, the primary training approach remains supervised. The background images serve to enhance the model's ability to generalize and reduce false positives. If you have further questions or need more details, feel free to ask!

**Comment by pderrenger** [comment]
@lushikai supervised learning relies entirely on labeled data for both training and validation, ensuring the model learns from known inputs and outputs. In contrast, semi-supervised learning combines a small amount of labeled data with a larger amount of unlabeled data, leveraging the latter to improve learning efficiency. In supervised learning, validation sets are used to evaluate model performance and must contain labels. If you have further questions, feel free to ask!

**Comment by glenn-jocher** [comment]
Thank you for your contribution! Your improvements to the code are appreciated. If you're interested in further contributing to the Ultralytics community, consider submitting a pull request with your enhancements. This way, others can benefit from your work. If you have any questions about the process, feel free to ask!

**Comment by glenn-jocher** [comment]
Thank you for your contribution! Your improvements to the augmentation code are appreciated. If you'd like to contribute further, consider submitting a pull request to the Ultralytics GitHub repository. Let us know if you have any questions!

**Comment by cafermutluozkan** [comment]
Hi,
Does Yolov8 still not support albumentations directly, or is there a simple way to use it?

**Comment by sharramallah** [comment]
I used Coarse Dropout Image Augmentation from the Albumentations library in my project: YOLO V8 Helmet Detection. I followed only this tutorial for installation and setup: https://albumentations.ai/docs/getting_started/installation/

YOLOv8 does support Albumentations directly.

**Comment by cafermutluozkan** [comment]
What should I do if I don't want to use Albumentation?
I did augment = False but it didn't work.

**Comment by lushikai** [comment]
@cafermutluozkan Just uninstall `Albumentation` repository in `conda` environment. `augment = False` is not a correct argument. 😄

**Comment by cafermutluozkan** [comment]
@lushikai Thank you.
