### ISSUE TITLE
Segmentation results showed as contours

### ISSUE THREAD

**Issue by Case2903** [ultralytics/ultralytics#7341]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

After detecting with segmentation I would like to get as a result the prediction highlighted with contours instead of masks. Is it possible? 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Case2903 hello! 😀

Yes, segmenting with contours is possible. You would typically start with a segmented mask and then find contours using image processing techniques. While our current implementation provides segmentation masks, you can process these masks to obtain contours. After you've used YOLOv8 for segmentation, you can employ functions from image processing libraries such as OpenCV to find and draw contours.

It's great to hear you're willing to help by submitting a PR! Contributions are always welcome, and it would be excellent to see this feature from a member of the community. Please, be sure to adhere to the contributing guidelines in the repo and document the feature clearly.

For more details on the segment feature, visit our documentation on segmentation. If you have any further queries, feel free to ask. Good luck with your contribution! 👍
