### ISSUE TITLE
Cuda error with 9.2 cuda version

### ISSUE THREAD

**Issue by devendraswamy** [ultralytics/ultralytics#735]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype)) in train.py of detection mode.

RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc)`

I am facing the problem with training of with 2k images dataset , while i am kept batch=16 , the training works fine but if i increase the batch size to 32 or above its throwing Runtime cuda error.

### Environment

Ultralytics YOLOv8.0.8 🚀 Python-3.7.13 torch-1.7.1+cu92 CUDA:0 (Tesla K80, 11441MiB) - AWS platform
python 3.7.13
linux

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by sureshk328** [comment]
Please make sure you are using cuda 11.2. If you are using any cuda version above 11.2 (which is supported by the latest version of torch), be sure to downgrade to 11.2 (or suitable version compatible with your torch version)

**Comment by pderrenger** [comment]
@sureshk328 it seems like you are encountering a CUDA error while training with YOLOv8. The issue could be related to the CUDA version compatibility with your PyTorch version. YOLOv8 is compatible with CUDA 11.1 and higher, and PyTorch 1.7.1 works well with CUDA 11.2. If you are using a different CUDA version, it's recommended to ensure compatibility with your PyTorch version, and if needed, consider aligning your CUDA version with PyTorch's requirements. This should help resolve the CUDA error you are experiencing when increasing the batch size during training. Good luck with your PR submission, and thank you for helping improve YOLOv8!
