### ISSUE TITLE
How to use the results of YOLO 8 in my own code? 

### ISSUE THREAD

**Issue by haqueshenas** [ultralytics/ultralytics#7353]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thank you for developing such a valuable tool. As a beginner, I have three questions:

1. How can I export or use the model's output, specifically the pixel data belonging to the segmented part, in my own code (e.g., for cropping or further processing of the segment in the original image)? What options are available in this case? Additionally, is there a way to prevent the code from printing the process and results in the terminal/console, especially when creating an .exe file using tools like PyInstaller or similar?

2. In the context of releasing an open-source freeware that includes YOLO model predictions, what are the copyright considerations? Should I include a version of the copyright notice obviously somewhere within the .exe file? Or is it sufficient to mention it once in the Python code?

3. After running the model, the images saved in the "predict" folder have lower resolutions compared to the input images. This issue doesn't occur when no class is detected in the image. Is there a way to retain the bounding box, label, and mask produced by YOLO on the image without any changes in image size, color quality, format, etc.?

Thanks.

**Comment by glenn-jocher** [comment]
@haqueshenas hello! I'm glad you're finding YOLOv8 valuable. Let's address your questions:

1. To use the segmented pixel data, you can access the model's outputs after running predictions. These outputs typically include coordinates for bounding boxes and segmentation masks. You can then use this data to crop or process the image as needed. To suppress terminal output, you would handle this within your own code by redirecting stdout or controlling the verbosity of the logging.

2. When releasing open-source freeware that includes YOLO model predictions, you must comply with the AGPL-3.0 license. This generally means including the copyright notice and license in your distribution. For an .exe file, you might include this information in an about or documentation section accessible to the end user.

3. To retain the original image resolution and quality in the "predict" folder, ensure you're using the correct settings during the prediction process. YOLOv8 allows you to maintain the original image size and quality; you might need to adjust the output settings or post-processing steps in your code.

For more detailed guidance on these topics, please refer to our documentation at https://docs.ultralytics.com. 😊

**Comment by haqueshenas** [comment]
Thank you. Regarding the third point, I am confident that displaying labels, bounding boxes, or segments results in a reduction of the overall resolution. I precisely utilized the code lines provided in the respective link without any additional settings:
```from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n-seg.pt')  # load an official model
model = YOLO('path/to/best.pt')  # load a custom model

# Predict with the model
results = model('https://ultralytics.com/images/bus.jpg')  # predict on an image
```
As mentioned earlier, if no class is detected in the image, there is no reduction in image resolution. Please take a look at the two sample images of output (which have similar dimensions and resolution, but not quality).
![Time_S7_V 2](https://github.com/ultralytics/ultralytics/assets/43292075/df3dd11b-28f1-475a-a93a-2f9a39d872db)
![Time_S7_VI 9](https://github.com/ultralytics/ultralytics/assets/43292075/4ac14eb4-3b70-4e96-97c9-59f157571df5)

**Comment by glenn-jocher** [comment]
@haqueshenas, I appreciate your follow-up. The resolution should indeed remain unchanged when using YOLOv8 for predictions. If you're experiencing a reduction in resolution when labels or segments are present, this could be an unintended behavior. We'll investigate this issue with the sample images you've provided. In the meantime, please ensure you're using the latest version of the repository and check if there are any additional parameters that might affect the output resolution. Your feedback is valuable in improving YOLOv8. Thank you! 🛠️

**Comment by haqueshenas** [comment]
Thanks once again. I found the reason. When running the model with the 'retina_masks=True' argument, the original resolution is retained. I had assumed that this option was set as True by default.

**Comment by glenn-jocher** [comment]
@haqueshenas, fantastic to hear you've resolved the resolution issue! For information on handling and extracting data from the segmentation model's output, please refer to our documentation on the Predict mode and the Segmentation task. These sections provide insights into working with model outputs, including segmentation masks. If you have further questions, don't hesitate to reach out. Happy coding! 😄👨‍💻

**Comment by haqueshenas** [comment]
> 2\. When releasing open-source freeware that includes YOLO model predictions, you must comply with the AGPL-3.0 license. This generally means including the copyright notice and license in your distribution. For an .exe file, you might include this information in an about or documentation section accessible to the end user.

Could you please provide an example of how this license is included in currently published software or packages? I've checked this link: (https://github.com/ultralytics/ultralytics/blame/main/LICENSE), but I'm still uncertain about whether I should include the entire text of the license in the About window or code. Can you point me to an existing software or package that demonstrates this effectively?
Thank you.

**Comment by glenn-jocher** [comment]
@haqueshenas, the format you've provided is a good example of how to include license information in your software. It's important to include the full text of the AGPL-3.0 license when distributing software that includes AGPL-3.0 licensed code. You can typically find examples of license inclusion in the documentation or about sections of other open-source software. Remember to also include any additional notices or acknowledgments required by the AGPL-3.0 license. Keep up the good work! 👍📜

**Comment by haqueshenas** [comment]
Thanks you very much.

**Comment by glenn-jocher** [comment]
@haqueshenas you're welcome! If you have any more questions, feel free to ask. Happy coding! 😊🚀
