### ISSUE TITLE
About the current training methods of obb branches

### ISSUE THREAD

**Issue by 954028118** [ultralytics/ultralytics#7358]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to know whether the future version will use the real obb training mode (the predicted information includes Angle, category and xywh), because I see that the current data processing mode is a horizontal external rectangular box composed of four points, x1y1x2y2x3y3x4y4, in fact, the training mode of hbb is still used, which makes me very confused
![Snipaste_2024-01-06_23-25-19](https://github.com/ultralytics/ultralytics/assets/53371726/042f8aca-23a6-4d51-a810-c7861b70b913)

**Comment by glenn-jocher** [comment]
@954028118 hello! Thanks for reaching out with your question. As of now, YOLOv8 does not natively support oriented bounding box (OBB) annotations with angles directly in the training pipeline. The current implementation indeed uses horizontal bounding boxes (HBB), which are represented by the four corner points you mentioned, without explicit angle information.

We are always looking to improve and expand the capabilities of our models, and the inclusion of real OBB training methods is an interesting direction for future updates. However, I cannot provide a specific timeline for when or if this feature will be implemented. Keep an eye on our repository updates and release notes for any news on this front.

For now, if you require OBB support, you might need to look into custom modifications or other solutions that can handle OBB annotations. Your feedback is valuable, and we appreciate your interest in the development of YOLOv8. If you have further questions or suggestions, feel free to share them in our discussions section. 😊
