### ISSUE TITLE
windows path exception in mlflow callback

### ISSUE THREAD

**Issue by userdev43** [ultralytics/ultralytics#7366]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Pathlib throws an error on windows here:
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/callbacks/mlflow.py#L77

```python
        if Path(uri).is_dir():
            LOGGER.info(f"{PREFIX}view at http://127.0.0.1:5000 with 'mlflow server --backend-store-uri {uri}'")
```
We can use os.path.isdir(uri) instead

```python
        if os.path.isdir(uri):
            LOGGER.info(f"{PREFIX}view at http://127.0.0.1:5000 with 'mlflow server --backend-store-uri {uri}'")
```

### Environment

N/A

### Minimal Reproducible Example

```python
from pathlib import Path
import os
uri = r"http://127.0.0.1:8080"

try:
    # if os.path.isdir(uri):
    if Path(uri).is_dir():
        print(f"view at http://127.0.0.1:5000 with 'mlflow server --backend-store-uri {uri}'")
except Exception as e:
    print(f'WARNING ⚠️ Failed to initialize: {e}\n')
```

Exception: [WinError 123] syntax error

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@userdev43 thank you for reporting this issue with the `mlflow` callback on Windows. It seems like the `Path` object is not handling the URI string as expected on the Windows platform. We appreciate your suggestion to use `os.path.isdir(uri)` as an alternative. We'll look into this and consider the best cross-platform solution that maintains functionality without causing exceptions on Windows. Your input is valuable, and we aim to resolve this in a future update. If you have any further details or suggestions, please feel free to share them. Keep an eye on the repository for updates! 👀🛠️
