### ISSUE TITLE
NotImplementedError: '.onnx' model loading not implemented

### ISSUE THREAD

**Issue by devendraswamy** [ultralytics/ultralytics#738]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

  File "C:\Users\a0398\.conda\envs\YOLOV8_py3.7_exp\lib\site-packages\ultralytics\yolo\engine\model.py", line 63, in __init__
    raise NotImplementedError(f"'{suffix}' model loading not implemented")
    
NotImplementedError: '.onnx' model loading not implemented

Please help me to debug this issue , Thank you in advance.

### Additional

(YOLOV8_py3.7_exp) D:\raghavi\YOLOV8_exp\ultralytics>yolo detect predict model=D:\raghavi\YOLOV8_exp\ultralytics\runs\detect\ASB_V1_2861imgs\weights\ASB_exp.onnx source="D:\raghavi\YOLOV8\ultralytics\datasets\sample_test\20_V23_val.jpg" project=D:\raghavi\YOLOV8_exp\ultralytics\runs\predict max_det=1 device=cpu
Traceback (most recent call last):
  File "C:\Users\a0398\.conda\envs\YOLOV8_py3.7_exp\Scripts\yolo-script.py", line 33, in <module>
    sys.exit(load_entry_point('ultralytics==8.0.8', 'console_scripts', 'yolo')())
  File "C:\Users\a0398\.conda\envs\YOLOV8_py3.7_exp\lib\site-packages\ultralytics\yolo\cfg\__init__.py", line 243, in entrypoint
    model = YOLO(model)
  File "C:\Users\a0398\.conda\envs\YOLOV8_py3.7_exp\lib\site-packages\ultralytics\yolo\engine\model.py", line 63, in __init__
    raise NotImplementedError(f"'{suffix}' model loading not implemented")
NotImplementedError: '.onnx' model loading not implemented

**Comment by AyushExel** [comment]
Loading onnx model in python interface is not implemented yet. It currently only supports pytorch (.pt) models or model.yamls

**Comment by devendraswamy** [comment]
But I converted the pt file to onnx and its working fine with opset=12 in python interface but while i convert the model from pt to onnx with opset=17 was throwing error like "NotImplementedError: '.onnx' model loading not implemented"

packages for opset=12:
onnx                    1.12.0
onnxconverter-common    1.13.0
onnxruntime             1.10.0

**Comment by dmddmd** [comment]
how should we export then to import later ? tourchscript also does not work

**Comment by devendraswamy** [comment]
in my case , onnx with opset=12 is working but with opset=17 was not worked , you try with opset=12 , onnx 1.12.0
onnxconverter-common 1.13.0
onnxruntime 1.10.0

**Comment by AyushExel** [comment]
This should be resolved now. You can run inference in exported models. Please reopen the issue if you face any problems
