### ISSUE TITLE
Any tips on counting instances and maintaining separate counter for each class ?

### ISSUE THREAD

**Issue by felipnrv** [ultralytics/ultralytics#7389]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I am using these libraries. 
How can I count when they go through a line, separating the classes, and have a counter for each of them?

from ultralytics import YOLO
from ultralytics.solutions import object_counter
import cv2

**Comment by glenn-jocher** [comment]
@felipnrv hello! To count instances and maintain a separate counter for each class as they cross a line, you can utilize the `object_counter` solution provided by Ultralytics. This tool is designed to track objects and increment class-specific counters when they intersect with a predefined line in the frame.

Here's a high-level overview of how you can approach this:

1. Define a line or zone in your video frame where you want to count the objects passing through.
2. Use the `object_counter` with your YOLOv8 model to detect objects in each frame.
3. The `object_counter` will keep track of the objects and their classes as they cross the line.
4. Access the counter values for each class to get your desired counts.

For detailed guidance on setting up and using the `object_counter` with YOLOv8, please refer to the documentation at https://docs.ultralytics.com. The documentation will provide you with the necessary information to configure the counting line and integrate the counting logic into your application. Happy counting! 😊🔢

**Comment by felipnrv** [comment]
Hello @glenn-jocher , Do you have any guide that could help me with this point you mentioned, access the counter values for each class to get your desired counts.?

**Comment by glenn-jocher** [comment]
@felipnrv hello! Yes, you can access the counter values for each class by referencing the output of the `object_counter` after processing each frame. The counter will provide a dictionary or similar data structure with class names as keys and their respective counts as values. For step-by-step instructions and examples, please check the relevant section in our documentation at https://docs.ultralytics.com. This will guide you through the process of utilizing the counter outputs effectively. Happy coding! 😊👍

**Comment by felipnrv** [comment]
@glenn-jocher  I've been trying in various ways, but I couldn't do it. Can you be more specific to have a counter for each class of the model?

**Comment by glenn-jocher** [comment]
@felipnrv, to have a counter for each class, after running your YOLOv8 model with the `object_counter`, you'll receive an output that includes the counts per class. This output is typically a dictionary where keys are class names and values are the counts. You can access these counts by iterating over the dictionary. For more specific instructions, please refer to the 'Object Tracking and Counting' section in our documentation at https://docs.ultralytics.com. 😊📊

**Comment by felipnrv** [comment]
At which part do I have to iterate over the dictionary of classes?
![image](https://github.com/ultralytics/ultralytics/assets/77867598/06d2dcd6-80e9-4452-bced-667084f1ec17)

**Comment by glenn-jocher** [comment]
@felipnrv after processing each frame with the `object_counter`, you'll receive the dictionary of counts. Iterate over this dictionary at the point in your code where you handle the output, typically after the detection and counting for the current frame are complete. This is where you can log, display, or store the count for each class. Please refer to the 'Object Tracking and Counting' section in our documentation for more details on handling the outputs. 😊👍

**Comment by felipnrv** [comment]
Hi, thanks for helping me, I still don't understand where I have to iterate the class dictionary, is it before the #count objects?

**Comment by glenn-jocher** [comment]
@felipnrv, you should iterate over the class dictionary after the `# count objects` comment, where the counting has already occurred, and the results are available for you to use. 😊🔄

**Comment by felipnrv** [comment]
it's something like iterating over the 'classes_name'".


# Display counts based on user choice
       
        def count_classes(self):
            counter = defaultdict(int)
            for class_name in self.classes_names:
                counter[class_name] += 1

            for class_name, count in counter.items():
                print(f"{class_name}: {count}")

        counts_label = None
        if not self.view_in_counts and not self.view_out_counts:
            counts_label = None
        elif not self.view_in_counts:
            counts_label = outcount_label
        elif not self.view_out_counts:
            counts_label = incount_label
        else:
            counts_label = f"{incount_label} {outcount_label}"

        if counts_label is not None:
            self.annotator.count_labels(
                counts=counts_label,
                count_txt_size=self.count_txt_thickness,
                txt_color=self.count_txt_color,
                color=self.count_color,
            )

**Comment by glenn-jocher** [comment]
@felipnrv, yes, you're on the right track. The `count_classes` method iterates over `self.classes_names` to accumulate counts for each class. After counting, it iterates over the `counter` dictionary to print out the counts for each class. This is typically done after object detection and tracking, where `self.classes_names` would be populated with the detected class names. 😊👍

**Comment by felipnrv** [comment]
I iterate over it with self.names because I understand that's where classes_names is stored, and because self.classes_names gave me an error. However, it only prints the values of the classes, for example: 0 person, 1 dog, 2 car ,....

# self.names = classes_names

# Display counts based on user choice
        counts_label = None
        if not self.view_in_counts and not self.view_out_counts:
            counts_label = None
        elif not self.view_in_counts:
            counts_label = outcount_label
        elif not self.view_out_counts:
            counts_label = incount_label
        else:
            counts_label = f"{incount_label} {outcount_label}"

        if counts_label is not None:
            self.annotator.count_labels(
                counts=counts_label,
                count_txt_size=self.count_txt_thickness,
                txt_color=self.count_txt_color,
                color=self.count_color,
            )

        for key, value in self.names.items():
            print(key, value)

**Comment by glenn-jocher** [comment]
@felipnrv, it seems there might be a misunderstanding. `self.names` likely contains the class labels, not the counts. You should have a separate structure that holds the counts for each class. Ensure you're updating this structure with the counts after each detection. Then, iterate over this structure to print the counts for each class. The code snippet you've provided seems to be for displaying counts, not for updating them. Make sure to update the counts correctly before attempting to display them. 😊🔍

**Comment by felipnrv** [comment]
Thank you very much, I understand how to do it now.

**Comment by glenn-jocher** [comment]
@felipnrv you're welcome! I'm glad to hear that you understand how to proceed. If you have any more questions, feel free to ask. Happy coding! 😊🚀

**Comment by NandiniLReddy** [comment]
@felipnrv, I'm working on similar case to count based on the classes; could please guide me?
