### ISSUE TITLE
Can I use it on m1 Mac?

### ISSUE THREAD

**Issue by jiho9702** [ultralytics/ultralytics#739]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can I use it on m1 Mac?
Do you have any plans to make it without CUDA?

**Comment by joelwebb** [comment]
I could run the CPU version on my M1 mac.

**Comment by AyushExel** [comment]
Yes cpu on mac should work. We'll work on M1 support later this quarter

**Comment by 1659258639** [comment]
I could run the CPU version on my 2019 mac

**Comment by AyushExel** [comment]
yes

**Comment by pranavchaturved** [comment]
Any news?

**Comment by pderrenger** [comment]
@pranavchaturved we're working on M1 support later this quarter! Thank you for your patience!
