### ISSUE TITLE
Yolo to COCO format conversion

### ISSUE THREAD

**Issue by Sadat75** [ultralytics/ultralytics#7398]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I am currently utilizing predict.py to obtain predictions and corresponding labels in YOLO format for human pose estimation. However, I'm interested in finding out if there's a method to transform these labels from YOLO format into COCO format (.json file). This is because I aim to train Yolox-pose models using the annotations derived from the output of Yolov8-pose models.

**Comment by glenn-jocher** [comment]
@Sadat75 hello!

To convert labels from YOLO format to COCO format, you would typically need to write a custom script that maps YOLO annotations to the COCO JSON structure. This involves creating a JSON file with the required fields such as `images`, `annotations`, `categories`, etc., and populating them with data converted from YOLO format.

While YOLOv8 does not provide a built-in utility for this specific conversion, you can refer to our documentation for information on the output format of predictions and how to work with them. You may also find community-contributed tools or scripts by searching through discussions or asking for assistance from the community in our discussions section.

For pose estimation tasks, ensure that the keypoints and their order match the COCO format expectations. Good luck with your training! 😊

**Comment by Sadat75** [comment]
@glenn-jocher 
Thank you for the response.
Initially, I used **https://app.trainyolo.com/** to generate the annotation, it uses Yolov8 in the backend to predict the output. 

I have written the script below to convert from Yolo to COCO:

`# Initialize COCO dataset structure
coco_dataset = {
    "info": {},
    "licenses": [],
    "images": [],
    "annotations": [],
    "categories": [
        {
            "id": 1,
            "name": "person",
            "supercategory": "person",
            "keypoints": ["nose", "left_eye", "right_eye", "left_ear", "right_ear", "left_shoulder", "right_shoulder",
                          "left_elbow", "right_elbow", "left_wrist", "right_wrist", "left_hip", "right_hip",
                          "left_knee", "right_knee", "left_ankle", "right_ankle"],
            "skeleton": [(16, 14), (14, 12), (17, 15), (15, 13), (12, 13), (6, 12),
                        (7, 13), (6, 7), (6, 8), (7, 9), (8, 10), (9, 11), (2, 3),
                        (1, 2), (1, 3), (2, 4), (3, 5), (4, 6), (5, 7)]
        }
    ]
}

# Function to convert YOLO annotations to COCO format
def yolo_to_coco(yolo_annotation, image_id, img_width, img_height, ann_id_start):
    annotations = []
    for ann_line in yolo_annotation.splitlines():
        parts = ann_line.strip().split()
        bbox = [float(x) for x in parts[1:5]]
        keypoints = [float(x) for x in parts[5:]]

        
        x_center, y_center, bbox_width, bbox_height = bbox
        x_top_left = (x_center - bbox_width / 2) * img_width
        y_top_left = (y_center - bbox_height / 2) * img_height
        width = bbox_width * img_width
        height = bbox_height * img_height

        
        coco_keypoints = []
        for i in range(0, len(keypoints), 3):
            x, y, v = keypoints[i:i+3]
            coco_keypoints += [x * img_width, y * img_height, int(v)]

        annotations.append({
            "id": ann_id_start,
            "image_id": image_id,
            "category_id": 1,  
            "bbox": [x_top_left, y_top_left, width, height],
            "area": width * height,
            "iscrowd": 0,
            "keypoints": coco_keypoints,
            "num_keypoints": int(len(coco_keypoints) / 3)
        })
        ann_id_start += 1

    return annotations, ann_id_start


annotation_id = 1  
for label_file in glob.glob(os.path.join(yolo_labels_dir, "*.txt")):
    
    match = re.search(r'img(\d+)', os.path.basename(label_file))
    if match:
        image_id = int(match.group(1))  
    else:
        raise ValueError(f"No numeric part found in the filename after 'img': {label_file}")

    
    img_width, img_height = 640, 640  

    # Read YOLO format annotations from file
    with open(label_file, 'r') as file:
        yolo_annotation = file.read()

    # Convert YOLO annotations to COCO format
    coco_anns, annotation_id = yolo_to_coco(yolo_annotation, image_id, img_width, img_height, annotation_id)
    coco_dataset["annotations"].extend(coco_anns)

    # Add image information to COCO dataset (you need to fill in the actual values)
    coco_dataset["images"].append({
        "id": image_id,
        "width": img_width,
        "height": img_height,
        "file_name": os.path.basename(label_file).replace('.txt', '.png') 
    })
`
It does work for converting the annotation I receive from the website mentioned above, but doesn't work as expected when I use the annotations from Yolov8 provided by Ultralytics.

Thank you once again, I'll ask for assistance from the community.

**Comment by glenn-jocher** [comment]
@Sadat75, glad to hear you've made progress with your script. If the conversion isn't working as expected with YOLOv8 annotations, it's possible there may be differences in the annotation format or keypoints between what's provided by the website and the YOLOv8 output.

Double-check the structure and values in the YOLOv8 annotations. Ensure that the keypoints are correctly mapped and that the bounding box coordinates are being transformed accurately. Differences in the expected input format or the annotation details can lead to discrepancies in the conversion process.

If you continue to face issues, reaching out to the community with specific examples of the discrepancies might help pinpoint the problem. Good luck! 😊

**Comment by Sadat75** [comment]
Hello @glenn-jocher,

I'd like to extend my gratitude for your response. I've developed a script to convert from YOLO to COCO format, tailored specifically for the output of the YOLOv8-pose model. It's functioning smoothly.

I've created a pull request for this script, which can be found here: https://github.com/ultralytics/ultralytics/pull/7458. 
I hope it aligns with the project's standards and look forward to the possibility of it being merged.

Thank you once again for your support.

**Comment by glenn-jocher** [comment]
Hello @Sadat75,

Thank you for your contribution! We appreciate your efforts in creating a script that could benefit the community. The team will review your pull request and provide feedback or further actions based on our standards and current project needs.

Keep up the great work, and we're glad to have you as part of the YOLOv8 community! 😊👍
