### ISSUE TITLE
OBB label box problem

### ISSUE THREAD

**Issue by lengdanlexin** [ultralytics/ultralytics#7403]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question
Today I saw that you have updated the OBB detection, so I couldn’t wait to test it. The OBB data set I prepared according to the segment annotation method only marked four points. As shown in the figure below, the right side is what I marked, and the left side is the image generated in val_batch0_labels.jpg. I tested that it is not the smallest enclosing rectangle of the four points I marked.
![NV_}6% %J D5H(BNRE9IPT1](https://github.com/ultralytics/ultralytics/assets/85054712/b64e1296-b69d-4e51-adc8-239567304a20)

The label format is cls xy1 xy2 xy3 xy4
`0 0.41 0.61 0.48 0.11 0.79 0.24 0.72 0.74`
I would like to ask if this is the correct way to prepare this label?

**Comment by lengdanlexin** [comment]
I tested it again according to the minimum circumscribed rectangle. There seems to be a problem with val_batch0_labels.jpg. Train_batch0.jpg should be fine.
![image](https://github.com/ultralytics/ultralytics/assets/85054712/9f4a422f-9349-482e-82fc-9da9487d8efc)
Please help me see if there is any problem with this way of preparing the data set. Is it processed according to the minimum enclosing rectangle of four points?

**Comment by Laughing-q** [comment]
@lengdanlexin the format of your dataset seems fine, could you upload one of your image and label here so I'm able to test it. :) Thanks!

**Comment by lengdanlexin** [comment]
> @lengdanlexin您的数据集的格式看起来不错，您可以在此处上传您的图像和标签之一，以便我能够对其进行测试。：） 谢谢！

![OBB](https://github.com/ultralytics/ultralytics/assets/85054712/e156d6d1-8fa1-42e9-bd12-79ab79ece6d0)

**Comment by lengdanlexin** [comment]
> @lengdanlexin the format of your dataset seems fine, could you upload one of your image and label here so I'm able to test it. :) Thanks!

Thank you very much for your reply.Below are the images and labels from my dataset.
![OBB](https://github.com/ultralytics/ultralytics/assets/85054712/68f6aae4-8eaf-467b-b504-a19fe82b2eca)
[OBB.txt](https://github.com/ultralytics/ultralytics/files/13859498/OBB.txt)
I just wonder if the labels in val_batch0_labels.jpg. are different from my labels. Also, if I prepare according to the segment annotation, will the label obtained in this way be the smallest enclosing rectangle of four points?

**Comment by lengdanlexin** [comment]
> @lengdanlexin
> 
> > I'm just wondering why there is a discrepancy between the annotations in val_batch0_labels.jpg and my annotations. Also, if I prepare according to the segment annotation, does this mean that the labels obtained are the smallest bounding rectangles defined by four points?
> 
> yes!
> 
> I launched a training with your image but the `val_batch0_labels.jpg` and `train_batch0.jpg` looks good to me. val_batch0_labels.jpg: ![val_batch0_labels](https://private-user-images.githubusercontent.com/61612323/294906039-50d876b9-8011-4c43-a950-2e5ec37c06bc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MTkyNTUsIm5iZiI6MTcwNDcxODk1NSwicGF0aCI6Ii82MTYxMjMyMy8yOTQ5MDYwMzktNTBkODc2YjktODAxMS00YzQzLWE5NTAtMmU1ZWMzN2MwNmJjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEzMDIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYTBiNmY5ZDFhZmYxYmZiMmQ1YzRlOTQ3M2MyMzRjOTY1MWJiNjkzNjExMzNjOTE1MTAwODJhNTAxNDhmNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6yotVoUkPR58e1cDcn4c-DTsdg4huEhVT3AG95dXq7U) train_batch0.jpg ![train_batch0](https://private-user-images.githubusercontent.com/61612323/294906054-19da2517-5309-4274-ad79-bab0f3f69dec.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MTkyNTUsIm5iZiI6MTcwNDcxODk1NSwicGF0aCI6Ii82MTYxMjMyMy8yOTQ5MDYwNTQtMTlkYTI1MTctNTMwOS00Mjc0LWFkNzktYmFiMGYzZjY5ZGVjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEzMDIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMDczNjkzNzczMWI2OTFlMDViZWU4ZGUxZWM4Y2MxN2M1MWNhZDA1MzA2MjEwZmU3MzYxNWRiZmQ0Zjg5MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._BYSp2BgUeHLZLOFu4ypAeoTZ17q7RjsHt-cwk_YqXE)

Thank you so much. Which border in val_batch0_labels.jpg does not pass through the lips, and which border in train_batch0.jpg passes through the lips.

**Comment by Laughing-q** [comment]
@lengdanlexin oh I see, there could be slight difference of this as the format switch of `xywhr` to `xyxyxyxy` and `xyxyxyxy` to `xywhr`, and also due to the augmentation. I'll investigate this deeply. :) THANKS for the reporting!!!
