### ISSUE TITLE
It doesn't work when you give a directory as a subdirectory in the classification.

### ISSUE THREAD

**Issue by sarpx** [ultralytics/ultralytics#7405]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

It doesn't work when you give a directory as a subdirectory in the classification.
It is necessary to export subfolders separately. This creates problems when I want to check the data I provided for training. Please allow us to export the folders and subfolders in a single way.

my folder x is:
x/train/green/...jpg
x/train/black/...jpg
x/train/yellow/...jpg

This doesn't work but I want it to work:
`yolo classify predict model=.\x\weights\best.pt source=.\x\train save=False save_txt=True save_conf=True 
name='x-a'`

This is work:
`yolo classify predict model=.\x\weights\best.pt source=.\x\train\green save=False save_txt=True save_conf=True 
name='x-a'`

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sarpx hello! Thank you for bringing this to our attention. Currently, the `classify predict` command expects a single directory containing images or a specific image file as the source. It does not recursively process subdirectories within the given source directory.

We understand the convenience of processing an entire directory tree with subfolders in one go, and we appreciate your willingness to contribute. If you're interested in implementing this feature, we encourage you to submit a PR. Your contribution would be a valuable addition to the YOLOv8 community.

For guidelines on contributing, please refer to our documentation on how to contribute effectively. If you need any assistance while working on the PR, feel free to reach out. Thanks again for your support! 🚀

**Comment by sarpx** [comment]
@glenn-jocher  Thank you very much for your trust. I don't feel confident enough to change the code yet. I just wanted to give feedback on how we experienced such a problem and what difficulties we experienced in practical application.

**Comment by glenn-jocher** [comment]
@sarpx, your feedback is greatly appreciated! Understanding practical challenges helps us improve. If you decide to tackle code changes in the future, we're here to support you. Meanwhile, we'll take note of your experience for potential enhancements. Keep the feedback coming, and thank you for being part of our community! 🌟
