### ISSUE TITLE
coco128-seg format

### ISSUE THREAD

**Issue by AlyShmahell** [ultralytics/ultralytics#741]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, 

I know this team is not responsible for yolov7, but I was using the same coco-seg `label.txt` format I used for yolov7, in order to train **yolov8**:

```sh
cls, x, y, w, h, *mask
```
everything is normalized to the `width, height` of the images I'm using, the `imgsz` param is set to the size of my images.  

However, the train_batch images of yolov8 are something out of a horror movie:  

![train_batch0](https://user-images.githubusercontent.com/6887917/215906410-efb979c4-7bc8-4126-9862-b7bc565cd1c5.jpg)
![train_batch1](https://user-images.githubusercontent.com/6887917/215906433-7285acc8-ae52-46b6-8614-773ba366e220.jpg)
![train_batch2](https://user-images.githubusercontent.com/6887917/215906516-11aa8f0a-b26f-4e3b-8bd6-6e3b482e30a4.jpg)  

can somebody please shed some light on what I am doing wrong?
Most importantly, is the `label` format correct?

**Comment by Laughing-q** [comment]
@AlyShmahell hi the labels format should be like:
```bash
cls, *mask
```
no need to use `x,y,w,h` here. :)

**Comment by AlyShmahell** [comment]
> @AlyShmahell hi the labels format should be like:
> 
> ```shell
> cls, *mask
> ```
> 
> no need to use `x,y,w,h` here. :)

Thank you, this solved the problem.
