### ISSUE TITLE
Export to ONNX Failure

### ISSUE THREAD

**Issue by NiranjanRavi1993** [ultralytics/ultralytics#742]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

  I am trying to export yolov8n.pt model to onnx by using the below script:

from ultralytics import YOLO
model = YOLO("yolov8n.pt")  
success = model.export(format="onnx")  

I get the below error:

Unsupported ONNX opset Version: 17 . 

But when I try yolov5s.pt file with yolov5 codebase, export.py works perfectly. 

It would be helpful to know if I am missing something. I tried it a couple of different ways and still fails. 

Thank you.

**Comment by Laughing-q** [comment]
@NiranjanRavi1993 please try lower the onnx opset version .i.e 12:
```python
from ultralytics import YOLO
model = YOLO("yolov8n.pt")
success = model.export(format="onnx", opset=12)
```

**Comment by NiranjanRavi1993** [comment]
Thank you, it worked.

**Comment by pderrenger** [comment]
You're welcome, @NiranjanRavi1993! I'm glad to hear that it worked for you. If you have any more questions or need further assistance, feel free to ask! Happy coding!
