### ISSUE TITLE
Source is PIL image or image path. 

### ISSUE THREAD

**Issue by xtqxk** [ultralytics/ultralytics#7420]
https://github.com/ultralytics/ultralytics/blob/783033fa6b12318bfa2f2e87f696f0ba94fb5b5e/ultralytics/models/fastsam/prompt.py#L315C9-L315C9

When the source type is PIL.Image? What's the point to check isdir? 

`TypeError: stat: path should be string, bytes, os.PathLike or integer, not JpegImageFile`

**Comment by glenn-jocher** [comment]
@xtqxk hello! It looks like you've encountered an issue where the code expects a file path but is receiving a PIL image object instead. The `isdir` check is indeed redundant when the source is a PIL image. This seems to be a bug, and we appreciate you bringing it to our attention. We'll investigate this and aim to resolve it in an upcoming release. In the meantime, please ensure that you're passing a file path as the source when using this function. Thank you for your contribution to improving YOLOv8! 🛠️👀

**Comment by jimwormold** [comment]
Will this be fixed? It's often not possible to pass a path (ie I don't want to have to save off a temporary file just so I can pass it to this) when the Image has already been partly processed

**Comment by glenn-jocher** [comment]
Hello! Thank you for your feedback. We understand the inconvenience of having to save images to disk before passing them to the model. We're looking into enhancing the functionality to directly accept PIL images without requiring a file path. This update aims to streamline the process, especially for scenarios involving image preprocessing. Keep an eye on future releases for this improvement! 🚀
