### ISSUE TITLE
Import "ultralytics" could not be resolved

### ISSUE THREAD

**Issue by NguyenDucQuan12** [ultralytics/ultralytics#7421]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi all, 
today I'm working on google colab, I want to "show=True" in ggcolb but it fails, then I return to vs code, but get the error: WARNING ⚠️ Environment does not support cv2.imshow() or PIL Image.show() in vs code, then I restarted the computer and opened vscode and the error appeared: Import "ultralytics" could not be resolved. Apparently yesterday I was still using it normally, today I tried pip install ultralytics but it didn't work. Please help me
I solved the error, but now the error below appears again, I still can't solve it, I don't know what I accidentally pressed or edited to get this error.
![ảnh](https://github.com/ultralytics/ultralytics/assets/68120446/764e17c0-b2f9-4c29-8ebf-83ff46fc1e4e)
![ảnh](https://github.com/ultralytics/ultralytics/assets/68120446/295ab6cc-8f61-4787-abc1-54c4b4607f77)

**Comment by NguyenDucQuan12** [comment]
i found to fix it:
pip uninstall opencv-python-headless -y 

pip install opencv-python --upgrade
Hope it helps everyone

**Comment by glenn-jocher** [comment]
@NguyenDucQuan12 hello! I'm glad to hear you've found a solution to the issue you were experiencing. It seems that the problem was related to the `opencv-python-headless` package, and reinstalling `opencv-python` resolved it. Your contribution is valuable, and sharing your fix can indeed be helpful to others in the community facing similar issues. If you encounter any further problems or have questions specifically about YOLOv8, feel free to reach out. Happy coding! 😊👍

**Comment by SamarthRajj** [comment]
> i found to fix it: pip uninstall opencv-python-headless -y
> 
> pip install opencv-python --upgrade Hope it helps everyone

it does not work for me 
as i get WARNING: Skipping opencv-python-headless as it is not installed. while uninstalling

**Comment by glenn-jocher** [comment]
Thanks for sharing your solution! If you're still facing display issues in VS Code, ensure you have `opencv-python` installed (not headless) and try saving predictions to file instead with `model.predict(..., save=True)`. For environment issues, we recommend creating a clean virtual environment as shown in our [Installation Guide](https://docs.ultralytics.com/quickstart/). If problems persist, please create a [Minimum Reproducible Example](https://docs.ultralytics.com/guides/yolo-common-issues/#how-to-create-a-minimum-reproducible-example) using our template.
