### ISSUE TITLE
What's the diferrence between lr/pg0, lr/pg1 & lr/pg2?

### ISSUE THREAD

**Issue by JasseurHadded1** [ultralytics/ultralytics#7424]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm doing a fine-tuning starting from pre-trained model, I have used `lr0: 0.000001`

In the result.csv file I see that `lr/pg0` is equal to `0.066672` after the first epoch, and the `lr/pg1` & `lr/pg2` start from `lr0` as I expected

Can you give me the differences between those learning rates? (detailed answer please, because I have found an answer but it's not clear at all!)

Thanks,

**Comment by madhavanvgts** [comment]
in my case lr/pg0, lr/pg1, lr/pg2 all this values are start in '0' in 2nd epoch it's 0.01 up to 51 epoch after that thous 3 values are 0. 
what is it mean ?
