### ISSUE TITLE
wrong report of classes on the txt file for the segmentation detection

### ISSUE THREAD

**Issue by mehran66** [ultralytics/ultralytics#743]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

When running the segmentation detection for a multi-class segmentation, the class plotted on the image (correct) does not match the class saved in the text file. 

### Minimal Reproducible Example

yolo task=segment mode=predict model=best.pt data=data.yaml save_txt=True imgsz=1152 save_conf=True line_thickness=1 retina_masks=True conf=0.25 iou=0.45 name=full_data source=./images

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mehran66** [comment]
removed the `reversed` from line 80 and the issue got resolved.

https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/v8/segment/predict.py#:~:text=for%20j%2C%20d%20in%20enumerate(reversed(det))%3A

**Comment by Laughing-q** [comment]
@mehran66 thanks! I'll fix this soon. :)

**Comment by mehran66** [comment]
resolved!

**Comment by pderrenger** [comment]
@mehran66 glad to hear that the issue has been resolved! If you have any more questions or need further assistance, feel free to ask. 😊

**Comment by glenn-jocher** [comment]
Great to hear, @pderrenger! If anything else comes up, just let us know. Happy coding! 😄
