### ISSUE TITLE
model.tune is set up with a hard-coded number of "iterations" 

### ISSUE THREAD

**Issue by stephansturges** [ultralytics/ultralytics#7430]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I have been testing the use of Ray Tuner to automate hyperparm-search. I wanted to test a very wide search with 100 iterations on a single param as a test case, but couldn't find a way to pass this usind the default model.tune format. The reason is that the number of iterations is hardcoded in model.py here:
```

def tune(self, use_ray=False, iterations=10, *args, **kwargs):
        """
        Runs hyperparameter tuning, optionally using Ray Tune. See ultralytics.utils.tuner.run_ray_tune for Args.

        Returns:
            (dict): A dictionary containing the results of the hyperparameter search.
        """
        self._check_is_pytorch_model()
        if use_ray:
            from ultralytics.utils.tuner import run_ray_tune
            return run_ray_tune(self, max_samples=iterations, *args, **kwargs)
        else:
            from .tuner import Tuner

            custom = {}  # method defaults
            args = {**self.overrides, **custom, **kwargs, 'mode': 'train'}  # highest priority args on the right
            return Tuner(args=args, _callbacks=self.callbacks)(model=self, iterations=iterations)
```

This means that no matter what args / kwargs are passed to the tuner you will get 10 iterations. 

It might be worth updating the docs (here https://docs.ultralytics.com/integrations/ray-tune/ ) to explain where people can change the number of experiments :wink: 

### Environment

Ultralytics YOLOv8.0.227 🚀 Python-3.10.13 torch-2.1.0 CUDA:0 (NVIDIA RTX A6000, 48674MiB)
Setup complete ✅ (24 CPUs, 125.6 GB RAM, 1512.9/1832.2 GB disk)

OS                  Linux-6.2.0-37-generic-x86_64-with-glibc2.31
Environment         Linux
Python              3.10.13
Install             git
RAM                 125.63 GB
CPU                 12th Gen Intel Core(TM) i9-12900F
CUDA                12.1

matplotlib          ✅ 3.8.2>=3.3.0
numpy               ✅ 1.23.5>=1.22.2
opencv-python       ✅ 4.7.0.72>=4.6.0
pillow              ✅ 10.0.1>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 2.1.0>=1.8.0
torchvision         ✅ 0.16.0>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
pandas              ✅ 2.1.4>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@stephansturges this is pretty funny. In Python there are functions, and functions have arguments that a user can set, i.e. you can set any value you have here.

You are misunderstanding a default value as a "hardcoded" value. You can set any value you want here rather than raise a bug report:

```python
model.tune(iterations=30)
```
