### ISSUE TITLE
Packing with Pyinstaller

### ISSUE THREAD

**Issue by listpplo** [ultralytics/ultralytics#7439]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have tried packing it with pyinstaller(vanilla) and also tied packing with the datas passing the folder loacation in (provided in another thread). When I tried starting the exe build with the second method ( i.e. with the datas providing the folders) it produces the following error **FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Swapnil Diwakar\\AppData\\Local\\Temp\\_MEI278722\\ultralytics\\cfg\\default.yaml'
[25836] Failed to execute script 'main' due to unhandled exception!**

**This is the code : **
`from PySide6.QtWidgets import QApplication, QMainWindow
from PySide6.QtGui import QCloseEvent, QImage, QPixmap
from PySide6.QtCore import Signal, Slot
from ui import Ui_MainWindow
from threading import Thread
import cv2
from ultralytics import YOLO
from pyzbar.pyzbar import decode

class MyApp(QMainWindow, Ui_MainWindow):
    detected_barcode = Signal(str)

    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.model = YOLO("Models/best_1.pt")
        self.run = True
        self.pushButton.clicked.connect(lambda _: Thread(target=self.getVideo).start())
        self.pushButton_2.clicked.connect(self.stopVideo)
        self.detected_barcode.connect(self.setValues)

    def stopVideo(self):
        self.run = False
        self.label_3.clear()
        self.textEdit.clear()

    def getVideo(self):
        path = self.lineEdit.text()
        if path == "":
            print("Please Enter Path")
        else:
            cap = cv2.VideoCapture(path)
            while self.run:
                ret, frame = cap.read()
                if not ret:
                    break
                values = self.model.predict(frame, conf=0.5, verbose=False)
                boxes = values[0].boxes.xywh.cpu()

                self.detected_barcode.emit("---")

                for box in boxes:
                    center_x, center_y, width, height = box
                    x = int(center_x - width / 2)
                    y = int(center_y - height / 2)
                    w = int(width)
                    h = int(height)

                    # Ensure that the coordinates are within the image bounds
                    x = max(0, x)
                    y = max(0, y)
                    w = min(frame.shape[1] - x, w)
                    h = min(frame.shape[0] - y, h)

                    cropped_image = frame[y : y + h, x : x + w]
                    height, width, _ = cropped_image.shape
                    if height < 200 or width < 200:
                        cropped_image = cv2.resize(cropped_image, (400, 400))

                    results = decode(cropped_image)
                    for result in results:
                        # print(result)
                        if result == []:
                            pass
                        else:
                            self.detected_barcode.emit(result.data.decode("utf-8"))
                            # height, width, _ = cropped_image.shape
                            # bytes_per_line = 3 * width
                            # q_image = QImage(
                            #     cropped_image.data,
                            #     width,
                            #     height,
                            #     bytes_per_line,
                            #     QImage.Format.Format_RGB888,
                            # )
                            # q_pixmap = QPixmap.fromImage(q_image.rgbSwapped())
                            # self.label_4.setPixmap(q_pixmap)

                frame = cv2.resize(frame, (720, 480))
                height, width, _ = frame.shape
                bytes_per_line = 3 * width
                q_image = QImage(
                    frame.data,
                    width,
                    height,
                    bytes_per_line,
                    QImage.Format.Format_RGB888,
                )
                q_pixmap = QPixmap.fromImage(q_image.rgbSwapped())
                self.label_3.setPixmap(q_pixmap)

    @Slot(str)
    def setValues(self, rec):
        self.textEdit.setText(rec)

    def closeEvent(self, event: QCloseEvent) -> None:
        self.run = False

app = QApplication()
window = MyApp()
window.show()
app.exec()
`

---
**This is the main.spec file :**
`
# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[(r'C:\Users\Swapnil Diwakar\Documents\PYTHON\Gui Projects\ML\venv\Lib\site-packages\ultralytics' , '.')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
`
Please Tell me the proper steps, I have already tried the methods provided in the previous thread releated to this.
Thanks in As

### Additional

Pyinstaller code :
pyinstaller main.py --onefile

then,
pyinstaller main.spec

**Complete Error : **
`Traceback (most recent call last):
  File "main.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ultralytics\__init__.py", line 5, in <module>
    from ultralytics.data.explorer.explorer import Explorer
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ultralytics\data\__init__.py", line 3, in <module>
    from .base import BaseDataset
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ultralytics\data\base.py", line 17, in <module>
    from ultralytics.utils import DEFAULT_CFG, LOCAL_RANK, LOGGER, NUM_THREADS, TQDM
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ultralytics\utils\__init__.py", line 386, in <module>
    DEFAULT_CFG_DICT = yaml_load(DEFAULT_CFG_PATH)
  File "ultralytics\utils\__init__.py", line 356, in yaml_load
    with open(file, errors='ignore', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Swapnil Diwakar\\AppData\\Local\\Temp\\_MEI271082\\ultralytics\\cfg\\default.yaml'
[21760] Failed to execute script 'main' due to unhandled exception!`

**Comment by listpplo** [comment]
Just Found the solution just copying the 'ultralytics'  folder from the 'venv/lib/python3.11/site-packages/" to the internal folder solved  the error.

**Comment by glenn-jocher** [comment]
@listpplo great to hear you've resolved the issue! 🎉 If you encounter any further problems or have questions about YOLOv8, feel free to reach out. Happy coding!

**Comment by thinhemb** [comment]
@listpplo you can  --add-data "C:/Users/KNT21818/AppData/Roaming/Python/Python39/site-packages/ultralytics;ultralytics/"     I tried it and it worked
