### ISSUE TITLE
Problem with Utils/plotting.py file 

### ISSUE THREAD

**Issue by complete-dope** [ultralytics/ultralytics#7441]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Didnt want to create a pull request but I guess there is a possible error in :

https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/plotting.py

in Line 907 and above where the file save

one possible fix is :

f = save_dir + f"stage{stage}_{module_type.split('.')[-1]}_features.png"  # filename
....
....
np.save(str(PurePath(f).with_suffix('.npy')), x[0].cpu().numpy())  # npy save

Do let me know if I am going wrong or its correct !! 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@complete-dope hello! Thank you for bringing this to our attention and for your willingness to help with a PR. 🌟

It's great to see community members actively engaging with the codebase and suggesting improvements. If you believe there's an error in the `utils/plotting.py` file, we encourage you to submit a PR with the proposed fix. Our team will review it as part of our continuous efforts to improve YOLOv8.

Before you do, please ensure that the change doesn't affect other parts of the code and that it follows the project's contribution guidelines. If you have any questions or need further clarification on the contribution process, feel free to consult the documentation at https://docs.ultralytics.com.

Thanks again for your contribution! 🚀
