### ISSUE TITLE
Yolov8 availability in the new MLX framework

### ISSUE THREAD

**Issue by AhmedHamadto** [ultralytics/ultralytics#7451]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Are there any plans to make Yolov8 available on the MLX framework that was released last month by the Apple Research Team? It would be interesting to see how the performance would be on a framework optimised for Apple Silicon.

**Comment by glenn-jocher** [comment]
@AhmedHamadto hello! Thanks for your interest in YOLOv8 and its potential integration with the MLX framework. As of now, we don't have immediate plans to make YOLOv8 available on MLX. Our current focus is on improving and optimizing YOLOv8 within the environments and frameworks it already supports. However, we're always monitoring the landscape for new opportunities to enhance performance and compatibility, especially on platforms optimized for specific hardware like Apple Silicon. Keep an eye on our updates, and feel free to contribute to the discussions on this topic in our GitHub community! 🚀

**Comment by YouROS12** [comment]
Any updates ? any new plans to support MLX ?

**Comment by glenn-jocher** [comment]
Thanks for checking in—no change: MLX isn’t supported right now; for Apple Silicon please use our CoreML export path as shown in the [CoreML integration guide](https://docs.ultralytics.com/integrations/coreml/), and if you’d like to track MLX interest, open a new feature request for visibility since this issue is closed/stale.
