### ISSUE TITLE
Need to infer the predictions from the yolov8 model 

### ISSUE THREAD

**Issue by complete-dope** [ultralytics/ultralytics#7466]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am looking for the post processing code after passing it to a small yolo model ( yolov8n.pt ) and the forward pass to the model returns :
A list of size 2
list[0] = torch.tensor(1,84,8400)
list[1] = list of lists of size 
list[1][0] = torch.tensor(1 , 144 , 80 , 80)
list[1][1] =torch.tensor(1 , 144 , 40 , 40)
list[1][2] = torch.tensor(1 , 144 , 20 , 20)

Can someone explain these output and I want to visualise these using custom code !! 
I also need to understand the significance between these numbers 84 , 8400 , 144 .. etc and what do these represents and the correct makeup of these numbers like 144 = combination of 80 classes + 1 objectiness score + rest ( 4 * dimension) 

Please link the required documents that can be useful in understand !!

**Comment by glenn-jocher** [comment]
@complete-dope hello! It looks like you're delving into the outputs of the YOLOv8 model. The outputs you're seeing are raw predictions from the model's different detection heads, which operate at various scales.

The first tensor in your list, `torch.tensor(1, 84, 8400)`, represents the flattened detection predictions for all grid cells across all scales. The `84` here typically includes the number of classes (e.g., 80 for COCO), plus the objectness score, and bounding box attributes (4 for x, y, width, height).

The tensors in `list[1]` are feature maps from three different scales, which the model uses for detecting objects of various sizes. Each feature map has a depth of `144`, which, as you correctly mentioned, includes class probabilities, objectness score, and bounding box attributes. The spatial dimensions of these tensors (`80x80`, `40x40`, `20x20`) correspond to the grid size of the feature map.

To visualize these predictions and understand the post-processing steps, you can refer to the Predict mode documentation in the Ultralytics Docs. This will guide you through the process of converting these raw predictions into bounding boxes and class scores that can be visualized on the image.

For a deeper understanding of the output tensor structure and the significance of the numbers, the Detection task documentation provides insights into how the model processes images and generates detections.

If you're looking to write custom code for visualization, the documentation will be your best resource to understand the necessary transformations from raw model outputs to interpretable results. Happy coding! 😊

**Comment by complete-dope** [comment]
@glenn-jocher Can I get help with ultralytics team on the same issue ? As I am unable to find relevant resources for the post-processing steps ? Or could you please tell me relevant link to read regarding the above issue
