### ISSUE TITLE
How to match tensors with extra added convolution blocks?

### ISSUE THREAD

**Issue by ChrisLearningIT** [ultralytics/ultralytics#7467]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hi there,

I'd like to add 3 convolutional blocks to the original Yolov8 object detection model. The hyperparamaters of the convolutional blocks are adjusted in a way to detect small objects betters. See screenshot below.

![image](https://github.com/ultralytics/ultralytics/assets/156187575/516f277d-917b-4d87-8f0e-ab6327c974e3)

However, when I add the 3 block the tensors don't match, because when a sanity check is performed I will get the error below. I have the feeling I miss some basic understanding of the architecture, but couldn't find something helpful in the docs.

My question is: How do I add these blocks and match the tensors. Does it work the same way with the bottleneck blocks and how does it influence the head and neck configuration?

PS C:\Users\chris\OneDrive\Documents\Thesis\Yolov8> & C:/Users/chris/AppData/Local/Programs/Python/Python311/python.exe c:/Users/chris/OneDrive/Documents/Thesis/Yolov8/Testrun/sanitycheck.py
WARNING ⚠️ no model scale passed. Assuming scale='n'.

                   from  n    params  module                                       arguments
  0                  -1  1       232  ultralytics.nn.modules.conv.Conv             [3, 8, 3, 1]
  1                  -1  1      1184  ultralytics.nn.modules.conv.Conv             [8, 16, 3, 2]
  2                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  3                  -1  1      4640  ultralytics.nn.modules.conv.Conv             [32, 16, 3, 2]
  4                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  5                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  6                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  7                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  8                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  9                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
 10                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
 11                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
 12                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    140032  ultralytics.nn.modules.block.C2f             [320, 128, 1]
 16                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 17             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1     35200  ultralytics.nn.modules.block.C2f             [160, 64, 1]
 19                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 20            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    140032  ultralytics.nn.modules.block.C2f             [320, 128, 1]
 22                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 23             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 24                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1]
 25        [15, 18, 21]  1   1151680  ultralytics.nn.modules.head.Detect           [80, [128, 64, 128]]
Traceback (most recent call last):
  File "c:\Users\chris\OneDrive\Documents\Thesis\Yolov8\Testrun\sanitycheck.py", line 7, in <module>
    model = YOLO('C:/Users/chris/OneDrive/Documents/Thesis/Yolov8/ultralytics-main/ultralytics/cfg/models/v8/yolov8test.yaml')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 92, in __init__
    self._new(model, task)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 128, in _new
    self.model = (model or self._smart_load('model'))(cfg_dict, verbose=verbose and RANK == -1)  # build model
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 242, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in forward(torch.zeros(1, ch, s, s))])  # forward
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 241, in <lambda>
    forward = lambda x: self.forward(x)[0] if isinstance(m, (Segment, Pose)) else self.forward(x)
                                                                                  ^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 42, in forward
    return self.predict(x, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 59, in predict
    return self._predict_once(x, profile, visualize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 79, in _predict_once
    x = m(x)  # run
        ^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\nn\modules\conv.py", line 315, in forward
    return torch.cat(x, self.d)
           ^^^^^^^^^^^^^^^^^^^^
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 4 but got size 8 for tensor number 1 in the list.
PS C:\Users\chris\OneDrive\Documents\Thesis\Yolov8>

**Comment by ChrisLearningIT** [comment]
Update, I figured out how to match the input channels with the ouput channels after adding 3 blocks. 

However, i am still unsure about 
1. Which layers I should select for the Detect module and for the concat modules.
2. Should I add an extra concat block because of my first 4 added blocks?

![image](https://github.com/ultralytics/ultralytics/assets/156187575/d5484c61-5a8d-4b82-8220-9583c0523ae5)

**Comment by glenn-jocher** [comment]
@ChrisLearningIT great to hear you've managed to match the input and output channels for your additional blocks! 🎉

1. For the Detect module, you typically want to select layers that provide a good mix of high-level semantic information and low-level detail. This often means choosing layers from different depths in the network. Look at the original configuration for guidance on which types of layers are used.

2. The need for an additional concat block depends on whether your new blocks introduce new pathways that need to be merged with existing ones. If your added blocks are parallel to existing layers and you want to merge their outputs, then yes, you might need an extra concat block. Otherwise, if they are simply extensions of the current layers, you may not need one.

Remember to ensure that the feature map dimensions align when using concat blocks, as they require the spatial dimensions to match. Good luck with your modifications! 🛠️
