### ISSUE TITLE
Cannot do inference on a model AttributeError: 'Image' object has no attribute 'shape'. Did you mean: 'save'?

### ISSUE THREAD

**Issue by Medkallel** [ultralytics/ultralytics#7473]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

When trying to make a prediction from a model, I get the following error:
![image](https://github.com/ultralytics/ultralytics/assets/26349357/878bdf36-9d53-4561-a1fe-de48ee52ec44)

### Environment

Ultralytics YOLOv8.0.233 🚀 Python-3.11.6 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 5938MiB)
Setup complete ✅ (16 CPUs, 19.4 GB RAM, 125.0/170.4 GB disk)

OS                  Linux-6.5.0-14-generic-x86_64-with-glibc2.38
Environment         Linux
Python              3.11.6
Install             pip
RAM                 19.38 GB
CPU                 AMD Ryzen 7 5800H with Radeon Graphics
CUDA                12.1

matplotlib          ✅ 3.8.0>=3.3.0
numpy               ✅ 1.26.2>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.0.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 2.1.0>=1.8.0
torchvision         ✅ 0.16.0>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.1.1>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0

### Minimal Reproducible Example

`def perform_inference(image_path,model_path):
    model = YOLO("Models/ClassificationInitiale.pt")
    results = model.predict(image_path)
    final = int(model.names[results[0].probs.top1])
    return final

model_initial = YOLO(model_initial)
Sous_classe1 = perform_inference(image_path,model_initial)`
I unfortunately cannot provide the model for confidentiality reasons

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by tksod22** [comment]
Hello,

I would like to add a comment about the same issue, specifically when using the classification model from `ultralytics`. The error I encounter is:

```
AttributeError: 'Image' object has no attribute 'shape'
```
The code is:
```
from ultralytics import YOLO
model = YOLO(r'runs\classify\train7\weights\best.pt')
results = model('1.jpg')
```
This error occurs when attempting to pass images to the classification model, both as a NumPy array and as a PIL and cv2 Image object. I have tried different methods of loading and preprocessing images.

It's important to note that this problem seems to occur only when using CUDA for GPU executions. When I run the model on a CPU with Torch, I do not encounter this issue. Additionally, it is worth mentioning that I have only experienced this error with the classification model; I have not had any issues with the detection model.

Is there any guidance or recommended solution for this issue? Could it be a bug related to the CUDA implementation in the classification model that is being addressed in a future update?

I appreciate any help or additional information you can provide.

**Environment**
Ultralytics YOLOv8.1.0 🚀 Python-3.9.13 torch-2.0.1+cu118 CUDA:0 (NVIDIA GeForce RTX 3050)

**Comment by Medkallel** [comment]
Found a "Solution" here; Don't really understand the problem but this works.
Changed the following code in the  "lib/python3.11/site-packages/ultralytics/models/yolo/classify/predict.py" file on line 42:
`
if is_legacy_transform:  # to handle legacy transforms
        img = torch.stack([self.transforms(im) for im in img], dim=0)
else:
        img = torch.stack([self.transforms(Image.fromarray(cv2.cvtColor(im,cv2.COLOR_BGR2RGB))) for im in img], dim=0)

`
to:
`
try:
    if is_legacy_transform:  # to handle legacy transforms
        img = torch.stack([self.transforms(im) for im in img], dim=0)
    else:
        img = torch.stack([self.transforms(Image.fromarray(cv2.cvtColor(im,cv2.COLOR_BGR2RGB))) for im in img], dim=0)
except:
         img = torch.stack([self.transforms(im) for im in img], dim=0)
`
I was using a model trained in a different environment and don't know what version of ulralytics it was trained on but the one I was doing inference on was the latest. Apparently the "is_leagacy_transform" condition doesn't get triggered while it should be.
If anyone has an explanation as to what is the problem or what happened It would be great.
@tksod22 let me know if this solves your problem too

**Comment by tksod22** [comment]
> Hi, I'm using a classification model as well Found a "Solution" here; Don't really understand the problem but this works. Changed the following code in the "lib/python3.11/site-packages/ultralytics/models/yolo/classify/predict.py" file on line 42: ` if is_legacy_transform: # to handle legacy transforms img = torch.stack([self.transforms(im) for im in img], dim=0) else: img = torch.stack([self.transforms(Image.fromarray(cv2.cvtColor(im,cv2.COLOR_BGR2RGB))) for im in img], dim=0)
> 
> `to:` try: if is_legacy_transform: # to handle legacy transforms img = torch.stack([self.transforms(im) for im in img], dim=0) else: img = torch.stack([self.transforms(Image.fromarray(cv2.cvtColor(im,cv2.COLOR_BGR2RGB))) for im in img], dim=0) except: img = torch.stack([self.transforms(im) for im in img], dim=0) ` I was using a model trained in a different environment and don't know what version of ulralytics it was trained on but the one I was doing inference on was the latest. Apparently the "is_leagacy_transform" condition doesn't get triggered while it should be. If anyone has an explanation as to what is the problem or what happened It would be great. @tksod22 let me know if this solves your problem too

It works, thank you very much

**Comment by Medkallel** [comment]
You're welcome.
If anyone can give us an explanation that would be great.

**Comment by StuZh** [comment]
This bug occurs when using ultralytics>8.0.230. Use ultralytics<=8.0.230 to avoid this problem
`pip install ultralytics==8.0.230`

**Comment by glenn-jocher** [comment]
@StuZh thank you for sharing your findings. It seems there might be an issue with the preprocessing step in versions after 8.0.230. We'll look into this and aim to address it in a future update. In the meantime, using version 8.0.230 as a temporary workaround is a good approach. Your input is valuable to the community, and we appreciate your contribution to improving YOLOv8. 🙌

**Comment by glenn-jocher** [comment]
@fcakyon take a look at this please

**Comment by glenn-jocher** [comment]
@Medkallel also when you say you can't provide a model for confidentiality reasons, all YOLOv8 models are licensed under AGPL-3.0, including any custom models you train, which by definition must be made public under the same license.

**Comment by giannhskp** [comment]
@glenn-jocher @fcakyon any update on this? I have the same problem and at the same time i need to use v8.1.0 as i also need the bug fix of [#7457](https://github.com/ultralytics/ultralytics/pull/7457)

**Comment by glenn-jocher** [comment]
@giannhskp the team is aware of the issue and is working on a fix. Please keep an eye on the repository for updates. Your patience is appreciated! 🛠️

**Comment by Crafter3149** [comment]
It seems that the incorrect path is causing this problem. To resolve it, you need to update the _legacy_transform_name variable in predict.py to match the correct path you've identified, which is ultralytics.data.augment.ToTensor. By making this change, the is_legacy_transform check will function correctly based on the updated path.

Here is my adjustment:
in ultralytics.yolo.model.classify.predict.py line 34  
From
self._legacy_transform_name = "ultralytics.yolo.data.augment.ToTensor"
To 
self._legacy_transform_name = "ultralytics.data.augment.ToTensor

After making this change, is_legacy_transform will correctly identify whether the transform is a legacy one based on the updated path.

**Comment by glenn-jocher** [comment]
@Crafter3149 thank you for pinpointing the issue and providing a solution. Your adjustment to the `_legacy_transform_name` seems correct and should help the `is_legacy_transform` check to function as intended. We'll review this internally and consider incorporating it into the next update. Your contribution is greatly appreciated! 🌟

**Comment by yinweinidongle** [comment]
you can try this  :  
1. change your python3.11 to python3.10 ;
2. pip install ultralytics==8.0.230;
then  it works!!!

**Comment by glenn-jocher** [comment]
@yinweinidongle thanks for sharing this workaround! 🚀 Switching to Python 3.10 and installing Ultralytics version 8.0.230 seems like a quick fix. For those who might need it, here's how you can do it in your terminal:

```bash
# Switch to Python 3.10 (make sure it's installed)
pyenv global 3.10

# Install the specified Ultralytics version
pip install ultralytics==8.0.230
```

Appreciate your input! Keep the feedback coming. 😊

**Comment by deep2810** [comment]
> Hi, I'm using a classification model as well Found a "Solution" here; Don't really understand the problem but this works. Changed the following code in the "lib/python3.11/site-packages/ultralytics/models/yolo/classify/predict.py" file on line 42: ` if is_legacy_transform: # to handle legacy transforms img = torch.stack([self.transforms(im) for im in img], dim=0) else: img = torch.stack([self.transforms(Image.fromarray(cv2.cvtColor(im,cv2.COLOR_BGR2RGB))) for im in img], dim=0)
> 
> `to:` try: if is_legacy_transform: # to handle legacy transforms img = torch.stack([self.transforms(im) for im in img], dim=0) else: img = torch.stack([self.transforms(Image.fromarray(cv2.cvtColor(im,cv2.COLOR_BGR2RGB))) for im in img], dim=0) except: img = torch.stack([self.transforms(im) for im in img], dim=0) ` I was using a model trained in a different environment and don't know what version of ulralytics it was trained on but the one I was doing inference on was the latest. Apparently the "is_leagacy_transform" condition doesn't get triggered while it should be. If anyone has an explanation as to what is the problem or what happened It would be great. @tksod22 let me know if this solves your problem too

I tried this and now I am getting different error 
 File Upload error: local variable 'im' referenced before assignment
 
 Any insight would be appreciated, thanks!

**Comment by janardan-ds** [comment]
@glenn-jocher 

_I'm using two models at the same time first one is of classifier and second is of obb, when I'm running the script with the Ultrlytics version of 8.1.28 then I'm getting the error for classification model throwing the error :_

> File "/home/techvamp/anaconda3/envs/yolov5/lib/python3.9/site-packages/ultralytics/engine/model.py", line 155, in __call__
>     return self.predict(source, stream, **kwargs)
>   File "/home/techvamp/anaconda3/envs/yolov5/lib/python3.9/site-packages/ultralytics/engine/model.py", line 406, in predict
>     return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
>   File "/home/techvamp/anaconda3/envs/yolov5/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 204, in __call__
>     return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
>   File "/home/techvamp/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
>     response = gen.send(None)
>   File "/home/techvamp/anaconda3/envs/yolov5/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 279, in stream_inference
>     im = self.preprocess(im0s)
>   File "/home/techvamp/anaconda3/envs/yolov5/lib/python3.9/site-packages/ultralytics/models/yolo/classify/predict.py", line 46, in preprocess
>     [self.transforms(Image.fromarray(cv2.cvtColor(im, cv2.COLOR_BGR2RGB))) for im in img], dim=0
>   File "/home/techvamp/anaconda3/envs/yolov5/lib/python3.9/site-packages/ultralytics/models/yolo/classify/predict.py", line 46, in <listcomp>
>     [self.transforms(Image.fromarray(cv2.cvtColor(im, cv2.COLOR_BGR2RGB))) for im in img], dim=0
>   File "/home/techvamp/anaconda3/envs/yolov5/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
>     img = t(img)
>   File "/root/miniconda3/envs/v8/lib/python3.9/site-packages/ultralytics/data/augment.py", line 1114, in __call__
> AttributeError: 'Image' object has no attribute 'shape'

_And if I'm downgrading the ultralytics version 8.0.222 so that the classifier model will work then getting the error for obb as obb was not present in the older version and it is throwing the error:_

> File "/home/techvamp/anaconda3/envs/yolo_test/lib/python3.8/site-packages/ultralytics/engine/model.py", line 94, in __init__
>     self._load(model, task)
>   File "/home/techvamp/anaconda3/envs/yolo_test/lib/python3.8/site-packages/ultralytics/engine/model.py", line 146, in _load
>     self.model, self.ckpt = attempt_load_one_weight(weights)
>   File "/home/techvamp/anaconda3/envs/yolo_test/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 628, in attempt_load_one_weight
>     ckpt, weight = torch_safe_load(weight)  # load ckpt
>   File "/home/techvamp/anaconda3/envs/yolo_test/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 567, in torch_safe_load
>     return torch.load(file, map_location='cpu'), file  # load
>   File "/home/techvamp/anaconda3/envs/yolo_test/lib/python3.8/site-packages/torch/serialization.py", line 1026, in load
>     return _load(opened_zipfile,
>   File "/home/techvamp/anaconda3/envs/yolo_test/lib/python3.8/site-packages/torch/serialization.py", line 1438, in _load
>     result = unpickler.load()
>   File "/home/techvamp/anaconda3/envs/yolo_test/lib/python3.8/site-packages/torch/serialization.py", line 1431, in find_class
>     return super().find_class(mod_name, name)
> AttributeError: Can't get attribute 'OBBModel' on <module 'ultralytics.nn.tasks' from '/home/techvamp/anaconda3/envs/yolo_test/lib/python3.8/site-packages/ultralytics/nn/tasks.py'>
> 
> 

_Using only one version as of now I didn't found any stable version on which both are working, I have only one option now if I have to use both simultaneously then I have to create two different docker images.

**Apart from that is there any stable version available where the issue with the classifier has been resolved with the one where obb is also working?**_

**Comment by rob-safi** [comment]
@glenn-jocher I'm still getting this error when trying to update to ultralytics>8.0.230 (ex: 8.1.37), is this bug fixed?

**Comment by glenn-jocher** [comment]
@rob-safi hi there! 😊 We've been actively working on this issue, and it should be resolved in our latest updates. Please make sure you're using the very latest version of the library. You can update ultralytics using:

```bash
pip install ultralytics --upgrade
```

If the problem persists after updating, could you please provide a small snippet of your code and the exact error message? This will help us diagnose and address the issue more efficiently. Thanks for your patience and for highlighting this!

**Comment by glenn-jocher** [comment]
@Medkallel when you say this, be advised that all AGPL-3.0 usage of Ultralytics models must be public. The only alternative is purchasing an Ultrlaytics Enterprise License. There is no legal "confidential" usage of AGPL-3.0 model.

> I unfortunately cannot provide the model for confidentiality reasons

**Comment by rob-safi** [comment]
> @rob-safi hi there! 😊 We've been actively working on this issue, and it should be resolved in our latest updates. Please make sure you're using the very latest version of the library. You can update ultralytics using:
> 
> ```shell
> pip install ultralytics --upgrade
> ```
> 
> If the problem persists after updating, could you please provide a small snippet of your code and the exact error message? This will help us diagnose and address the issue more efficiently. Thanks for your patience and for highlighting this!

@glenn-jocher still seeing this on 8.1.40
```
$ poetry show ultralytics
 name         : ultralytics                                                                                                                           
 version      : 8.1.40                                                                                                                                
 description  : Ultralytics YOLOv8 for SOTA object detection, multi-object tracking, instance segmentation, pose estimation and image classification.
```

Here is a snippet and the weight which should recreate the error (I had to zip the weights because github wouldn't let me uplaod a .pt:
```
from ultralytics import YOLO

# Load a model
model = YOLO('dirt_best.pt')  # p
[dirt_best.zip](https://github.com/ultralytics/ultralytics/files/14822102/dirt_best.zip)
retrained YOLOv8n model

# Run batched inference on a list of images
result = model.predict(source='https://ultralytics.com/images/bus.jpg')[0]  # return a list of Results objects
```

Thanks

**Comment by glenn-jocher** [comment]
Hi @rob-safi, thanks for the detailed follow-up and for sharing your code snippet along with the model weights! 👍

It looks like you've taken all the right steps. If you're still encountering issues with ultralytics 8.1.40, we'll need to look into this further. In the meantime, could you please confirm the error message you're receiving?

Also, as a temporary workaround, you might want to try rolling back to a version where you didn't experience this issue, just until we get a fix out:

```shell
pip install ultralytics==8.0.230
```

Let's stay in touch on this, and I'll do my best to help you resolve it. 🛠️

**Comment by rob-safi** [comment]
> Hi @rob-safi, thanks for the detailed follow-up and for sharing your code snippet along with the model weights! 👍
> 
> It looks like you've taken all the right steps. If you're still encountering issues with ultralytics 8.1.40, we'll need to look into this further. In the meantime, could you please confirm the error message you're receiving?
> 
> Also, as a temporary workaround, you might want to try rolling back to a version where you didn't experience this issue, just until we get a fix out:
> 
> ```shell
> pip install ultralytics==8.0.230
> ```
> 
> Let's stay in touch on this, and I'll do my best to help you resolve it. 🛠️

@glenn-jocher 
Here is the full error message:

```
(remote-inspection-env-py3.10) robin@robin-PC5x-7xHP-HR-HS:~/tc/remote-inspection$ python yolo_test.py 

Found https://ultralytics.com/images/bus.jpg locally at bus.jpg
Traceback (most recent call last):
  File "/home/robin/tc/remote-inspection/yolo_test.py", line 7, in <module>
    result = model.predict(source='https://ultralytics.com/images/bus.jpg')[0]  # return a list of Results objects
  File "/home/robin/tc/remote-inspection/.venv/lib/python3.10/site-packages/ultralytics/engine/model.py", line 451, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/robin/tc/remote-inspection/.venv/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/robin/tc/remote-inspection/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/robin/tc/remote-inspection/.venv/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 244, in stream_inference
    im = self.preprocess(im0s)
  File "/home/robin/tc/remote-inspection/.venv/lib/python3.10/site-packages/ultralytics/models/yolo/classify/predict.py", line 46, in preprocess
    [self.transforms(Image.fromarray(cv2.cvtColor(im, cv2.COLOR_BGR2RGB))) for im in img], dim=0
  File "/home/robin/tc/remote-inspection/.venv/lib/python3.10/site-packages/ultralytics/models/yolo/classify/predict.py", line 46, in <listcomp>
    [self.transforms(Image.fromarray(cv2.cvtColor(im, cv2.COLOR_BGR2RGB))) for im in img], dim=0
  File "/home/robin/tc/remote-inspection/.venv/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
  File "/home/robin/tc/remote-inspection/.venv/lib/python3.10/site-packages/ultralytics/data/augment.py", line 1346, in __call__
    imh, imw = im.shape[:2]
  File "/home/robin/tc/remote-inspection/.venv/lib/python3.10/site-packages/PIL/Image.py", line 528, in __getattr__
    raise AttributeError(name)
AttributeError: shape. Did you mean: 'save'?
```

Yea we really wanted to take advantage of some of the new cool things in 8.1, it would be great if you guys could get a fix for this out :)

**Comment by glenn-jocher** [comment]
Hey @rob-safi, thank you for promptly providing the full error log! It indeed sheds more light on the issue. It seems like there's a minor mismatch in handling the image data. 🕵️‍♂️

One quick thing to try is ensuring your images are in the correct format expected by the model's preprocess method. Since the error points to a missing `.shape` attribute, it's likely that the input is not being recognized as a NumPy array (which `cv2` images are) but instead as a PIL Image, which doesn't directly support `.shape`.

To address this, you might ensure conversion to a NumPy array is happening as expected, or manage the conversion manually before passing it to `model.predict()`. For instance:
```python
import cv2
from PIL import Image
import numpy as np

source = 'https://ultralytics.com/images/bus.jpg'
image = Image.open(source)  # Assuming 'source' is a path to your image
image_np = np.array(image)  # Convert PIL Image to NumPy array

result = model.predict(source=image_np)[0]
```

This approach ensures the input is in the expected format, complementing the updated method you've used.

We're thrilled you're excited about the new features in 8.1! Our team is on this, aiming to get a fix rolled out asap. Stay tuned for updates, and we really appreciate your engagement with our library and your help in improving it. 🚀

**Comment by rob-safi** [comment]
@glenn-jocher yea I tried loading the image as numpy array but I'm still getting the same error. I'm guessing one of the preprocessors converts the numpy array to an Image object.

Also not sure if this helps but I only get this error on yolo classification models, I didn't have any issues with detection models.

**Comment by rob-safi** [comment]
@glenn-jocher any update on this?

**Comment by poojatambe** [comment]
Hi @glenn-jocher, Thanks for your work.
Adjusting input before prediction is not working.
Using both OBB and classification is not possible due to this issue. I would like to know if there is any fix.
Input: 
```
Input type and shape:  <class 'numpy.ndarray'> (4396, 3819, 3)
```
Version: **8.1.45**

**Comment by glenn-jocher** [comment]
Hi there! 👋 Thanks for reaching out and providing the details of the issue you've encountered. We're sorry for any inconvenience this has caused.

For the issue with using both OBB and classification, it sounds like there might be specific intricacies due to the model processing requirements. As a quick suggestion, can you please ensure that your input images are correctly preprocessed to fit the model's input specification? 

Regarding a direct fix to this issue, our team is continuously working on improving YOLOv8, and we appreciate your patience. We will make sure to keep the community updated through our release notes and GitHub issues.

In the meantime, here's a snippet ensuring your input image is correctly sized for the model:
```python
import cv2
from ultralytics import YOLO

# Load a model
model = YOLO('path/to/your/model.pt')  # Be it OBB or Classification

# Read and resize your image
img = cv2.imread('path/to/your/image.jpg')
img_resized = cv2.resize(img, (640, 640))  # Adjust size as per model requirements

# Predict
results = model.predict(source=img_resized)
```
This ensures that your image is the right size for the model, but keep in mind, model-specific preprocessing might also be required depending on the model's training.

Stay tuned for updates, and thank you for your support and for using YOLOv8!

**Comment by poojatambe** [comment]
Hi, @glenn-jocher , Thank you.
Tried with preprocessing input and converted image to tensor format. This way the issue has resolved.

![image](https://github.com/ultralytics/ultralytics/assets/64680838/4c0d40e3-b433-4b49-94a1-c494a25a45ac)

Wanted to verify is this correct way?

**Comment by glenn-jocher** [comment]
Hi there! 🌟 I'm glad to hear the preprocessing approach has helped resolve the issue! Yes, converting the image to a tensor format before prediction is indeed a standard and correct way to prepare your input for a model in PyTorch-based frameworks like Ultralytics YOLOv8. This ensures that the input matches the expected format and dimensions the model was trained with.

In case you need a quick reference, here's a simple way to convert your image into a tensor:
```python
import torch
from torchvision import transforms
from PIL import Image

# Load your image
image = Image.open('path/to/your/image.jpg')

# Convert to tensor
transform = transforms.Compose([
    transforms.ToTensor(),
])
image_tensor = transform(image)

# Now you can pass image_tensor to your model
```
Keep up the great work, and if you have any more questions, feel free to ask!

**Comment by jet-c-21** [comment]
@glenn-jocher I still encounter this issue on version `8.2.3`

**Comment by glenn-jocher** [comment]
Hi there! 🙌 Sorry to hear you're still experiencing issues with version `8.2.3`. Could you try updating to the latest version to see if the problem persists? Sometimes, bugs get fixed in newer releases. Here's how you can update:

```bash
pip install ultralytics --upgrade
```

If the issue remains, please share a bit more context or a minimal code snippet demonstrating the problem. This will help us pinpoint the cause more effectively. Thanks for reaching out!

**Comment by guillaume-safi** [comment]
> es, converting the image to a tensor



> Hi there! 🌟 I'm glad to hear the preprocessing approach has helped resolve the issue! Yes, converting the image to a tensor format before prediction is indeed a standard and correct way to prepare your input for a model in PyTorch-based frameworks like Ultralytics YOLOv8. This ensures that the input matches the expected format and dimensions the model was trained with.
> 
> In case you need a quick reference, here's a simple way to convert your image into a tensor:
> 
> ```python
> import torch
> from torchvision import transforms
> from PIL import Image
> 
> # Load your image
> image = Image.open('path/to/your/image.jpg')
> 
> # Convert to tensor
> transform = transforms.Compose([
>     transforms.ToTensor(),
> ])
> image_tensor = transform(image)
> 
> # Now you can pass image_tensor to your model
> ```
> 
> Keep up the great work, and if you have any more questions, feel free to ask!

I have tried the above solution and when a model is called for inference:

`
   result = yolo_model.predict(source=image_tensor)
`
The preprocess gets skipped (which leads to errors as the image is no longer square), see the snapshot taken from models/yolo/classify/predict.py:

 
![image](https://github.com/ultralytics/ultralytics/assets/146853227/9648ae88-daa9-4a26-b5a9-05e18b99d995)


Can you detail how to call the .predict using your example such that the preprocess is called correctly.

**Comment by glenn-jocher** [comment]
Hey there! 👋 It looks like the preprocessing step needs a slight adjustment when using the `.predict()` method directly with tensors. To ensure the preprocessing isn't skipped and your image tensor is correctly processed, you might consider passing the image path or PIL image directly to the `source` parameter. The preprocessing (including resizing) is then automatically handled by YOLOv8. Here's how you can do it:

```python
from ultralytics import YOLO
from PIL import Image

# Load your model
yolo_model = YOLO('path/to/your/model.pt')

# Load and directly pass the image
image_path = 'path/to/your/image.jpg'
image_pil = Image.open(image_path)

# Use the path or PIL image for prediction
result = yolo_model.predict(source=image_path)  # or source=image_pil
```

This approach ensures that the image goes through the complete preprocessing pipeline. Let us know how this goes, and we're here to help if you have any further questions!
