### ISSUE TITLE
Custom data augmentation 

### ISSUE THREAD

**Issue by lavanyanemani96** [ultralytics/ultralytics#7474]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I add an additional augmentation (not present in yolov8 data/hyp) technique while training yolov8?

**Comment by glenn-jocher** [comment]
@lavanyanemani96 hello! To add a custom data augmentation technique to YOLOv8 training, you'll need to modify the augmentation pipeline in the source code. Specifically, you can look into the dataset and augmentation files where transformations are applied. Integrate your custom augmentation by defining it and including it in the sequence of transformations. Ensure that your augmentation is compatible with the existing pipeline and that it receives and returns data in the correct format. After implementing your custom augmentation, you can train your model with the updated code to include the new augmentation in the training process. For detailed guidance on the code structure and augmentation pipeline, please refer to the documentation at https://docs.ultralytics.com. Happy coding! 😊🚀

**Comment by lavanyanemani96** [comment]
Once the changes are made to augment and dataset file, how to load them in model.train() so it doesn't use the default augmentations but the new custom ones?

**Comment by glenn-jocher** [comment]
@lavanyanemani96 after updating the augmentation and dataset files with your custom augmentation, the changes will be automatically used by `model.train()` when you start the training process. There's no need to manually load them; the training function will utilize the modified pipeline as defined in your code. Ensure your custom augmentations are correctly integrated into the dataset's `__getitem__` method or the augmentation pipeline. 🛠️🚀
