### ISSUE TITLE
yolov8 classification model .pt convert to .onnx, results are different

### ISSUE THREAD

**Issue by Captain1986** [ultralytics/ultralytics#7490]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict, Export

### Bug

I convert yolov8n-cls.pt to yolov8n-cls.onnx and check their results are big different, this is not reasonable.
To repeat my result with 3 lines as follows
1. yolo export model=yolov8n-cls.pt format=onnx opset=13
2. yolo predict task=classify model=yolov8n-cls.onnx imgsz=224
3. yolo predict task=classify model=yolov8n-cls.pt imgsz=224

Below is my screenshots of the bug

<img width="1163" alt="image" src="https://github.com/ultralytics/ultralytics/assets/47138645/0f4e0322-0662-4741-a369-3f867a7858da">
<img width="1163" alt="image" src="https://github.com/ultralytics/ultralytics/assets/47138645/585cbd43-6332-4cba-8353-1864bed7b704">

### Environment

<img width="828" alt="image" src="https://github.com/ultralytics/ultralytics/assets/47138645/14ba754a-fe83-43c9-85e4-596dc4642df3">

### Minimal Reproducible Example

1. yolo export model=yolov8n-cls.pt format=onnx opset=13
2. yolo predict task=classify model=yolov8n-cls.onnx imgsz=224
3. yolo predict task=classify model=yolov8n-cls.pt imgsz=224
4. check the results of 2 and 3 are different in scores and classes

### Additional

I find similar bug report in #2134, but she said the result in her classification model NOT yolov8 official model, my bug is occurs in yolov8 official model yolov8n-cls.pt

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Captain1986** [comment]
It's a version bug, I downgrade my ultralytics from 8.0.239 to 8.0.206, bug fixed

**Comment by glenn-jocher** [comment]
@Captain1986 thank you for reporting this issue and for your willingness to help with a PR! It seems you've identified a potential regression between versions 8.0.239 and 8.0.206 that affects the classification results after exporting to ONNX. We appreciate your diligence in pinpointing the problem.

Could you please open a new issue with the details of your findings, including the version discrepancy and any relevant output comparisons? This will help us track and address the regression more effectively. Your contribution is valuable to the YOLOv8 community, and we look forward to resolving this together. 🛠️

For further guidance on contributing, you can refer to our documentation on how to submit a PR. Thanks again for your support! 🌟
