### ISSUE TITLE
How to split validation dataset during training

### ISSUE THREAD

**Issue by ZongXR** [ultralytics/ultralytics#7494]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to split validation dataset during training automaticlly via a hyperparameter? Like validation_split in keras. Thanks a lot.
如何在训练过程中，通过一个超参数自动划分验证集？就像keras里面的validatrion_split.

**Comment by glenn-jocher** [comment]
@ZongXR hello! During training with YOLOv8, the dataset is typically split into training and validation sets beforehand. The framework itself doesn't include a hyperparameter for automatic splitting like `validation_split` in Keras. You would need to manually split your dataset into separate training and validation folders before initiating the training process.

For guidance on how to prepare your data, you can refer to the documentation on dataset organization. If you're using a standard dataset like COCO or VOC, YOLOv8 will handle the download and setup automatically, including the predefined splits for training and validation.

If you have any further questions or need assistance with dataset preparation, feel free to ask. Happy training! 😊
