### ISSUE TITLE
validation results differs from prediction results

### ISSUE THREAD

**Issue by LLsmile** [ultralytics/ultralytics#7496]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

validation scripts:
```
from ultralytics import YOLO
model = YOLO(model="epoch300.pt")
model.val(data="sa.yaml", \
            epochs=100, \
            batch=8, \
            imgsz=640, \
            device='0',\
            project='fastsam', \
            name='val',
            val=False,
            save_json=True, \
            save_hybrid=True, \
            conf=0.5, \
            iou=0.9, \
            plots=True, \
            max_det=100, \
            )
```

predict scripts:
```
from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO('truck/20240108_base/epoch300.pt')

# Run inference on 'bus.jpg' with arguments
import os
images = './images/val'
for root,dirs,files in os.walk(images):
    for file in files:
        model.predict(os.path.join(images,file), save=True, imgsz=640, conf=0.5, show_labels=True, half=False, show_conf=True, iou=0.9)
    break

```

datasets and models is on [google drive ](https://drive.google.com/drive/folders/1leqLoYxMQ0c5ibOe7-TSlrOnu48cCXfr)

Visualized image is [here](https://github.com/ultralytics/ultralytics/issues/7459)

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by LLsmile** [comment]
It seems validation results is much better than prediction results. So I want to know what validation has done for inference.

**Comment by glenn-jocher** [comment]
@LLsmile this is a duplicate bug report. There is no bug, there is a user error on your part. `save_hybdrid` is for generating hybrid labels, not for computing mAP. If you want accurate mAp don't use this argument.

**Comment by LLsmile** [comment]
Yes, you're right. And how can I get all mAP of iou 0.5~0.95, such as mAP90?

**Comment by LLsmile** [comment]
I found it. Thanks.

**Comment by glenn-jocher** [comment]
@LLsmile great to hear you found what you were looking for! If you have any more questions or need further assistance, feel free to ask. Happy detecting! 😊🚀
