### ISSUE TITLE
is it possible to run inference with pre-trained yolov8 without installing ultralytics?

### ISSUE THREAD

**Issue by aaalexlit** [ultralytics/ultralytics#7497]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

is it possible to run inference with pre-trained yolov8 without installing ultralytics?
my guess is it's not possible (unless I'm eager to copy all the inference code...) but double-checking never hurts.
Use case: submission to Kaggle in a competition with no internet access
Thanks

**Comment by aaalexlit** [comment]
never mind, found a solution

**Comment by glenn-jocher** [comment]
@aaalexlit great to hear you found a solution! If you have any further questions or need assistance in the future, feel free to reach out. Happy coding and best of luck with your Kaggle competition! 😊🚀

**Comment by gameveloster** [comment]
@aaalexlit Can you share your solution please?

**Comment by aaalexlit** [comment]
@gameveloster 
sure
the way I solved this for Kaggle is to create a notebook that downloads ultralytics with 
``` 
!pip download ultralytics
```

and then using its output in a submission notebook without internet access
eg like this (you'll need to change the paths)
```
!pip install --no-index -f /kaggle/input/download-ultralytics /kaggle/input/download-ultralytics/ultralytics-8.1.5-py3-none-any.whl
```

you can see the examples here 

Notebook that downloads ultralytics (in this instance I also needed SAM model, so I installed ultralytics and downloaded the model as well):
https://www.kaggle.com/code/aaalexlit/download-ultralytics

Notebook that uses the output of the previous one (with no internet access):
https://www.kaggle.com/code/aaalexlit/yolo-followed-by-sam
