### ISSUE TITLE
YOLOv8  Docs Sample dataset

### ISSUE THREAD

**Issue by magau123** [ultralytics/ultralytics#750]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is the training data set corresponding to the sample images of classification, detection and segmentation in https://docs.ultralytics.com/tasks/detection/ open? 
Can I share it? 
Thank you very much

**Comment by pderrenger** [comment]
@magau123 hello! 😊 The training datasets like COCO, VOC, and ImageNet, which are used in the YOLOv8 documentation samples for tasks such as detection, segmentation, and classification, are open and can be freely shared. These datasets are commonly used in the computer vision community for benchmarking and research purposes. If you have any specific questions about using these datasets with YOLOv8, feel free to ask!
