### ISSUE TITLE
When i use yolov8-p2.yaml, Why does the parameter of the Detect module decrease when the p2 detection head is added?

### ISSUE THREAD

**Issue by syz247179876** [ultralytics/ultralytics#7501]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I have a question, when i use yolov8-p2.yaml, why does the parameter of the Detect module decrease when the p2 detection head is added? Shouldn't the number of parameters increase with the addition of additional modules?

**Comment by syz247179876** [comment]
The problem has been solved, thank you!

**Comment by syz247179876** [comment]
The problem has been solved, thank you!

**Comment by glenn-jocher** [comment]
@syz247179876 you're welcome! I'm glad to hear that your issue has been resolved. If you have any more questions or need further assistance in the future, don't hesitate to reach out. Happy coding! 😊🚀
