### ISSUE TITLE
[tcp @ 0x558ca03370] Connection to tcp://192.168.0.151:554?timeout=0 failed: No route to host rtsp://admin:satech1234@192.168.0.151:554/udp/av0_0: No route to host

### ISSUE THREAD

**Issue by jetsonmom** [ultralytics/ultralytics#7505]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

(py38) dli@dli-desktop:~/Jetson-Nano2/V8$ python3 detectY8.py
WARNING ⚠️ Ultralytics settings reset to defaults. This is normal and may be due to a recent ultralytics package update, but may have overwritten previous settings. 
View and update settings with 'yolo settings' or at '/home/dli/.config/Ultralytics/settings.yaml'
Ultralytics YOLOv8.0.42 🚀 Python-3.8.13 torch-1.11.0a0+gitbc2c6ed CUDA:0 (NVIDIA Tegra X1, 3963MiB)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

[tcp @ 0x558ca03370] Connection to tcp://192.168.0.151:554?timeout=0 failed: No route to host
rtsp://admin:satech1234@192.168.0.151:554/udp/av0_0: No route to host
Traceback (most recent call last):
  File "detectY8.py", line 120, in <module>
    predict(use_python = True)
  File "detectY8.py", line 112, in predict
    YOLO(cfg.model)(**args)(cfg)
  File "/home/dli/Jetson-Nano2/V8/ultralytics/yolo/engine/model.py", line 104, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/dli/Jetson-Nano2/V8/ultralytics/yolo/engine/model.py", line 215, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)

### Environment

(py38) dli@dli-desktop:~/Jetson-Nano2/V8$ python3 --version
Python 3.8.13

>>> print(torch.__version__)
1.11.0a0+gitbc2c6ed

>>> print(torchvision.__version__)
0.12.0a0+9b5a3fe
>>> 

### Minimal Reproducible Example

(py38) dli@dli-desktop:~/Jetson-Nano2/V8$ python3 detectY8.py
WARNING ⚠️ Ultralytics settings reset to defaults. This is normal and may be due to a recent ultralytics package update, but may have overwritten previous settings. 
View and update settings with 'yolo settings' or at '/home/dli/.config/Ultralytics/settings.yaml'
Ultralytics YOLOv8.0.42 🚀 Python-3.8.13 torch-1.11.0a0+gitbc2c6ed CUDA:0 (NVIDIA Tegra X1, 3963MiB)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

[tcp @ 0x558ca03370] Connection to tcp://192.168.0.151:554?timeout=0 failed: No route to host
rtsp://admin:satech1234@192.168.0.151:554/udp/av0_0: No route to host
Traceback (most recent call last):
  File "detectY8.py", line 120, in <module>
    predict(use_python = True)
  File "detectY8.py", line 112, in predict
    YOLO(cfg.model)(**args)(cfg)
  File "/home/dli/Jetson-Nano2/V8/ultralytics/yolo/engine/model.py", line 104, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/dli/Jetson-Nano2/V8/ultralytics/yolo/engine/model.py", line 215, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jetsonmom hello! It looks like you're experiencing a connection issue where the host is not reachable. This is typically a network-related error, not specific to YOLOv8. Please ensure that the device you're trying to connect to is on the same network and that the IP address and port are correct and accessible. Also, check if any firewalls or network configurations might be blocking the connection. If the issue persists, verifying the network setup and connectivity outside of YOLOv8 might help isolate the problem. Good luck! 🤞
