### ISSUE TITLE
maybe split_dota will error if os.sep in img2label_paths is not '/'.

### ISSUE THREAD

**Issue by wpNZC** [ultralytics/ultralytics#7519]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

maybe split_dota will error if os.sep in img2label_paths is not '/',load_yolo_dota use os.path.join(data_root, f"images/{split}/*") and img2label_paths make error:
![1705026520751](https://github.com/ultralytics/ultralytics/assets/75358739/a12edeaa-3f8e-4649-bfa8-0abaa463acd2)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wpNZC thank you for bringing this to our attention. It seems you're suggesting that there might be an issue with path separators in the `split_dota` function, particularly when the expected separator is not '/'. We'll look into this potential cross-platform compatibility issue. If you have any more details or error logs, feel free to share them to help us better understand the problem. Your contribution to improving YOLOv8 is much appreciated! 🛠️

**Comment by wpNZC** [comment]
> @wpNZC谢谢你让我们注意到这一点。您似乎建议函数中的路径分隔符可能存在问题`split_dota`，特别是当预期的分隔符不是“/”时。我们将研究这个潜在的跨平台兼容性问题。如果您有更多详细信息或错误日志，请随时分享，以帮助我们更好地理解问题。非常感谢您对改进 YOLOv8 所做的贡献！🛠️

yes,when I change '/' to '\\' in f-string of load_yolo_dota, the code run normally, I think you can change it be more intelligent or use other idea to achieve img2label_paths

**Comment by glenn-jocher** [comment]
@wpNZC acknowledged, and thanks for the additional info! We'll consider making the path handling more robust to accommodate different file system conventions. Your feedback is valuable in enhancing YOLOv8's usability. 👍

**Comment by glenn-jocher** [comment]
@Laughing-q it looks like we need to update this script for OS-agnostic capability, and use pathlib package instead of us package.

**Comment by glenn-jocher** [comment]
All done in #7552!
