### ISSUE TITLE
Error when using non max suppression in post processing - Instance segmentation YOLOv8l-seg

### ISSUE THREAD

**Issue by himansh1314** [ultralytics/ultralytics#752]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I've trained a YOLOv8l-seg model and now I'm trying to write my own function that takes the pytorch model and inferences the image along with post processing. However, I'm getting some error

My dataset had 5 classes. The number of mask (nm) parameter in non max suppression is kept 32 because as I figured out that in segmentation tasks it is 32 (This is what I had discovered from working on yolov5.

However, I'm getting this error
/Users/himansh.mulchandani/Desktop/yolov8/yolov8_eval.ipynb Cell 9 in <cell line: 1>()
----> [1](vscode-notebook-cell:/Users/himansh.mulchandani/Desktop/yolov8/yolov8_eval.ipynb#ch0000013?line=0) p = ops.non_max_suppression(preds[0],
      [2](vscode-notebook-cell:/Users/himansh.mulchandani/Desktop/yolov8/yolov8_eval.ipynb#ch0000013?line=1)                             nm=32,
      [3](vscode-notebook-cell:/Users/himansh.mulchandani/Desktop/yolov8/yolov8_eval.ipynb#ch0000013?line=2)                             classes=5)

File /opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.9/site-packages/ultralytics/yolo/utils/ops.py:199, in non_max_suppression(prediction, conf_thres, iou_thres, classes, agnostic, multi_label, labels, max_det, nm)
    195 output = [torch.zeros((0, 6 + nm), device=prediction.device)] * bs
    196 for xi, x in enumerate(prediction):  # image index, image inference
    197     # Apply constraints
    198     # x[((x[:, 2:4] < min_wh) | (x[:, 2:4] > max_wh)).any(1), 4] = 0  # width-height
--> 199     x = x.transpose(0, -1)[xc[xi]]  # confidence
    201     # Cat apriori labels if autolabelling
    202     if labels and len(labels[xi]):

IndexError: The shape of the mask [32, 36] at index 0 does not match the shape of the indexed tensor [36, 32, 69] at index 0

### Additional

Here's my code
`
```
import cv2
import numpy as np
import matplotlib.pyplot as plt


import torch
model = torch.load("/Users/himansh.mulchandani/Desktop/yolov8/best.pt", map_location="cpu")["model"].float()
preds = model(torch.rand(1,3,256,288))

p = ops.non_max_suppression(preds[0],
                            nm=32,
                            classes=5)
```
`

**Comment by AyushExel** [comment]
@himansh1314 the model already runs nms and returns returns result. You can still run it again but you need to pass a different input format.
See https://docs.ultralytics.com/reference/ops/, NMS expects a tensor.
You can get the tensor from results object like this.  See detailed usage here - https://docs.ultralytics.com/predict/
```
res = preds[0]
boxes = res.boxes.data
masks = res.masks.data
p = ops.non_max_suppression(boxes,
                            nm=32,
                            classes=5)
```
