### ISSUE TITLE
Is useful to add images without labels in obb?

### ISSUE THREAD

**Issue by wpNZC** [ultralytics/ultralytics#7520]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is useful to add images without labels in obb?I have some images without the object I need,and the split_trainval cant run if images without labels.txt,so add labels.txt or del images without the object is better?

**Comment by ArthurHakobyann** [comment]
Yes, you can create empty text files for images without objects in them, which will help decrease the false positive rate.

**Comment by wpNZC** [comment]
> 是的，您可以为不含对象的图像创建空文本文件，这将有助于降低误报率。

ok,thank you!

**Comment by glenn-jocher** [comment]
@wpNZC you're welcome! If you have any more questions, feel free to ask. Happy training! 😊🚀
