### ISSUE TITLE
Training does not work on multi-GPUs

### ISSUE THREAD

**Issue by Juwankim** [ultralytics/ultralytics#7523]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Training works well on a single GPU. 
However, when applying MULTI GPUs in the same environment, it stops progressing after displaying the following message.

```
Transferred 469/475 items from pretrained weights
DDP: debug command /home/miniconda3/envs/new_deid/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 34081 /home/.config/Ultralytics/DDP/_temp_ix0i3psu139926573938128.py
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

Ultralytics YOLOv8.1.0 🚀 Python-3.11.5 torch-2.1.2+cu118 CUDA:0 (NVIDIA GeForce RTX 4090, 24217MiB)
                                                          CUDA:1 (NVIDIA GeForce RTX 4090, 24217MiB)
Overriding model.yaml nc=80 with nc=2
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
```

**Comment by glenn-jocher** [comment]
@Juwankim hello! It seems like you're encountering an issue with multi-GPU training using YOLOv8. The message you've posted indicates that the process starts but doesn't proceed after initializing DDP (Distributed Data Parallel) and AMP (Automatic Mixed Precision).

To troubleshoot this, please ensure that you're following the recommended setup for multi-GPU training as outlined in our documentation. Check that your environment is correctly configured for DDP, and that there are no system-level bottlenecks or misconfigurations that might be causing the hang-up.

If the issue persists, consider providing more details in a new issue, such as the full command you're using to initiate training, any modifications to the default configuration, and the complete output log up to the point where it stops progressing. This will help us better understand the context and provide more targeted assistance.

The YOLOv8 community and the Ultralytics team are here to support you, and we appreciate your efforts in using our models. 🚀
