### ISSUE TITLE
Stop training manually?

### ISSUE THREAD

**Issue by Cestovatels** [ultralytics/ultralytics#7528]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I stop with ctrl+c, the training is not completed and the size of the best.pt model is too large. Is there any way to finish this training other than stopping it forcibly? For example, the 900 epoch training is at epoch 272, can I pull it to 275 and stop it?

**Comment by glenn-jocher** [comment]
@Cestovatels hello! If you wish to stop training at a specific epoch, you can modify the `epochs` parameter in your training configuration file to the desired epoch number (e.g., 275). This way, the training will naturally conclude at that epoch. If you've already started training and wish to adjust the stopping point, you'll need to interrupt the training with `ctrl+c` and then restart it with the modified `epochs` parameter. Remember to use the last saved weights to resume training smoothly. Happy training! 😊🚀
