### ISSUE TITLE
streams.streams

### ISSUE THREAD

**Issue by kaundinya-sr** [ultralytics/ultralytics#754]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

when tried with multiple web cam streams using .streams extension for the streaming file, below error is shown after streaming first frame from the first cam. kindly suggest.

ultralytics>yolo task=detect mode=predict model=yolov8n.pt source=list.streams
Ultralytics YOLOv8.0.4  Python-3.10.8 torch-1.13.1 CUDA:0 (Quadro T2000 with Max-Q Design, 4096MiB)
Fusing layers...
YOLOv8n summary: 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
['1', '0']
2
1/2: 1...  Success (inf frames 640x480 at 30.00 FPS)
2/2: 0...  Success (inf frames 640x480 at 30.00 FPS)

Error executing job with overrides: ['task=detect', 'mode=predict', 'model=yolov8n.pt', 'source=list.streams']
Traceback (most recent call last):
  File "D:\anaconda\envs\yv8\lib\site-packages\ultralytics\yolo\cli.py", line 56, in cli
    func(cfg)
  File "D:\anaconda\envs\yv8\lib\site-packages\hydra\main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "D:\anaconda\envs\yv8\lib\site-packages\ultralytics\yolo\v8\detect\predict.py", line 95, in predict
    predictor.predict_cli()
  File "D:\anaconda\envs\yv8\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 220, in predict_cli
    for _ in (self.__call__(source, model, return_outputs)):
  File "D:\anaconda\envs\yv8\lib\site-packages\torch\autograd\grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "D:\anaconda\envs\yv8\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 188, in __call__
    path, im0s = path[i], im0s[i]
IndexError: string index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

### Environment

Windows 10
Ultralytics YOLOv8.0.4  Python-3.10.8 torch-1.13.1 CUDA:0 (Quadro T2000 with Max-Q Design, 4096MiB)

### Minimal Reproducible Example

yolo task=detect mode=predict model=yolov8n.pt source=list.streams

### Additional

list.streams file contain:

0
1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@Laughing-q @glenn-jocher I guess we don't support this yet right ? Does v5 support this?

**Comment by kaundinya-sr** [comment]
> 

Yes v5 supports this. apparently v8 seems to have something similar but not working.

**Comment by Laughing-q** [comment]
@kaundinya-sr @AyushExel yes we support this and actually I remember I've solved this bug before, and I noticed you were using `Ultralytics YOLOv8.0.4`, please upgrade the package and try again. :)
```
pip install --upgrade ultralytics
```

**Comment by kaundinya-sr** [comment]
> @kaundinya-sr @AyushExel yes we support this and actually I remember I've solved this bug before, also I noticed you were using `Ultralytics YOLOv8.0.4`, please upgrade the package and try again. :)
> 
> ```
> pip install --upgrade ultralytics
> ```

Thank you so much @Laughing-q ! this worked. I am closing the issue.

**Comment by kaundinya-sr** [comment]
Thank you @Laughing-q ! this works like charm!
