### ISSUE TITLE
Segmentation mask scaling

### ISSUE THREAD

**Issue by subhankardori** [ultralytics/ultralytics#7547]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

for yolov8, results = self.model.predict(img, imgsz=self.imgsz, rect=self.rect). the in-built preprocessing function of ultralytics is able to handle the bounding box rescaling efficiently, let's say model was trained on 1088, and the imgsz passed is 3840, after yolo.predict, it scales the predictions back to imgsz 3840. But the same is not happening for the segmentation mask.

Kindly have a look at these logs
`
2024-01-12 12:24:24,929  DEBUG 67 plugin_inference.py  186  __init__        Frame shape:(2160, 3840, 3)
2024-01-12 12:24:24,945  DEBUG 67 plugin_inference.py  659  custom_inference    COORDS:[616, 1784, 668, 1900]
2024-01-12 12:24:24,945  DEBUG 67 plugin_inference.py  660  custom_inference    segmentation:[(679680, 1123200), (675840, 1125360), (675840, 1185840), (683520, 1190160), (721920, 1190160), (725760, 1188000), (729600, 1188000), (729600, 1185840), (721920, 1181520), (721920, 1177200), (718080, 1175040), (718080, 1125360), (714240, 1123200)]`

Here's my interpretation of the results, highlighting the out-of-bounds segmentation points:

Image and Model Information:

Image Dimensions: 2160 pixels (height) x 3840 pixels (width)
Model Training Size (assumed): 1088 pixels (common for YOLOv8)
Key Observations:

Bounding Box Coordinates: Correctly within image bounds (616, 1784, 668, 1900)
Segmentation Polygon Points: Extend beyond image boundaries, abnormally high
Potential Causes:
Missing Mask Scaling: As discussed earlier, YOLOv8 might not automatically scale masks, leading to incorrect coordinates.

@glenn-jocher is there any parameter which needs to be passed in the inference call which can handle mask rescaling, or do we need to rely on ultralytics.ops for a manual implementation? Eagerly waiting for your response !

**Comment by glenn-jocher** [comment]
@subhankardori hello! It seems like you've encountered an issue where the segmentation masks are not being scaled back to the original image size after prediction when using a different inference size. Currently, YOLOv8's predict function is designed to handle bounding box scaling, but it appears that the same automatic scaling may not be applied to segmentation masks.

For now, you would need to manually scale the segmentation masks to match the original image dimensions. This can be done by calculating the scaling factor from the model's training size to the inference size and applying it to the mask coordinates. We appreciate you bringing this to our attention, and we'll consider this behavior for future updates.

Please refer to the Ultralytics Docs for more information on handling predictions and post-processing steps. Your feedback is valuable, and we'll keep working to improve the functionality and usability of YOLOv8. Thank you for your support and patience! 🙏🚀

**Comment by PushpakBhoge** [comment]
is this issue fixed ?

the problem I found while rescaling things is that it's not just a simple resize 
for example we get an original size in `result.masks.orig_shape` but the `result.masks.data` is center padded so simply resizing the (640x640) scale the mask incorrectly so the rescaling of mask is a pain

this is handled in `result.plot` cause there the mask is handled properly

**Comment by pderrenger** [comment]
@PushpakBhoge thank you for your detailed observation. The issue with mask rescaling and center padding is indeed a known challenge. As of now, the `result.plot` method handles this correctly, but manual rescaling can be tricky due to the padding.

To address your question, please ensure you are using the latest version of the Ultralytics package, as updates may include fixes and improvements for such issues. If the problem persists in the latest version, your custom function is a good workaround for handling mask rescaling manually.

We appreciate your contribution and detailed explanation, which will be helpful for others facing similar issues. If you encounter further problems or have additional insights, please feel free to share.
