### ISSUE TITLE
Saving YOLO and OpenCV Live Camera Output to a .txt File

### ISSUE THREAD

**Issue by felipnrv** [ultralytics/ultralytics#7553]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I save the live camera output results in a .txt file using YOLOv8 and OpenCV?

**Comment by glenn-jocher** [comment]
@felipnrv hello! To save live camera output results to a `.txt` file using YOLOv8, you can run the detection in Predict mode and handle the results within your Python script. After obtaining the detections, you can format the output as desired and write it to a `.txt` file using standard Python file I/O operations, such as `open()` and `write()`. The results from YOLOv8 will include the bounding box coordinates, class IDs, and confidence scores, which you can iterate over and save to your file. For more details on handling outputs, please refer to the Predict mode documentation on our Ultralytics Docs. Keep in mind to manage file writing efficiently to avoid I/O bottlenecks that could slow down your real-time processing. Happy coding! 😊
