### ISSUE TITLE
If I want to modify it to use map50 as the criterion for judging the best model, where do I need to modify it?

### ISSUE THREAD

**Issue by xunfeng233** [ultralytics/ultralytics#7555]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

If I want to modify it to use map50 as the criterion for judging the best model, where do I need to modify it?

**Comment by glenn-jocher** [comment]
Hello! To use mAP @xunfeng233.5 (map50) as the criterion for selecting the best model during training, you'll need to adjust the evaluation metric in the training configuration. Specifically, look for the section in the code where the best model checkpoint is saved based on the evaluation metric. You'll want to change the metric from the default (which might be mAP@0.5:0.95 or another metric) to mAP@0.5. This will ensure that the model with the highest mAP@0.5 during validation is saved as the best model.

For detailed guidance on how to make this modification, please refer to the documentation at https://docs.ultralytics.com, which provides comprehensive information on configuring and customizing the training process. 😊👍
