### ISSUE TITLE
Mosaic automatically get applied when training custom dataset on yolov8?

### ISSUE THREAD

**Issue by khanhthanhh9** [ultralytics/ultralytics#7559]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Does training the yolov8 model on a custom dataset apply mosaic by default? If yes, how to disable it? I'm curious of this because data annotation websites such as roboflow offer mosaic augmentation. It could be a potential redundancy and hurt the performance of the model by applying mosaic twice.

**Comment by glenn-jocher** [comment]
@khanhthanhh9 yes, mosaic data augmentation is applied by default when training YOLOv8 on a custom dataset. If you wish to disable it, you can adjust the augmentation settings in the YAML configuration file for your dataset by setting the `mosaic` parameter to `0`. This will prevent the mosaic augmentation from being applied during training, avoiding any redundancy if you've already used a service like Roboflow to preprocess your data with mosaic augmentation. For more details on configuring your training, please refer to the Training section in our documentation. 📘
