### ISSUE TITLE
error in documentation 

### ISSUE THREAD

**Issue by lamoboos223** [ultralytics/ultralytics#756]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

i found the command for training the model has the task `detect` in it. I believe this is a mistake, isn't it?

page url: https://docs.ultralytics.com/cli/

![image](https://user-images.githubusercontent.com/35597031/216050762-ae98af24-317c-4bf8-902f-f951d45a821d.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Andulka97** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.
> 
> ### YOLOv8 Component
> _No response_
> 
> ### Bug
> i found the command for training the model has the task `detect` in it. I believe this is a mistake, isn't it?
> 
> page url: https://docs.ultralytics.com/cli/
> 
> ![image](https://user-images.githubusercontent.com/35597031/216050762-ae98af24-317c-4bf8-902f-f951d45a821d.png)
> 
> ### Environment
> _No response_
> 
> ### Minimal Reproducible Example
> _No response_
> 
> ### Additional
> _No response_
> 
> ### Are you willing to submit a PR?
> * [ ]  Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
No its not a bug. `yolo detect train..` will train a model for detection task. `yolo segment train ..` will train for segment task.
The syntax is this:
```
yolo {TASK} {MODEL} ...
```
