### ISSUE TITLE
Convert YoloV8 to Tflite in colab

### ISSUE THREAD

**Issue by PEEMTM** [ultralytics/ultralytics#7567]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want convert model to Tflite. But when I run

model = YOLO('/content/runs/detect/train52/weights/best.pt')
model.export(format='tflite')
 
i got

TensorFlow SavedModel: starting export with tensorflow 2.15.0...
WARNING ⚠️ tensorflow<=2.13.1 is required, but tensorflow==2.15.0 is currently installed https://github.com/ultralytics/ultralytics/issues/5161
Downloading https://github.com/ultralytics/assets/releases/download/v8.1.0/calibration_image_sample_data_20x128x128x3_float32.npy.zip to 'calibration_image_sample_data_20x128x128x3_float32.npy.zip'...
100%|██████████| 1.11M/1.11M [00:00<00:00, 6.16MB/s]
Unzipping calibration_image_sample_data_20x128x128x3_float32.npy.zip to /content/calibration_image_sample_data_20x128x128x3_float32.npy...: 100%|██████████| 1/1 [00:00<00:00, 28.42file/s]

ONNX: starting export with onnx 1.15.0 opset 17...
ONNX: simplifying with onnxsim 0.4.35...
ONNX: export success ✅ 2.8s, saved as '/content/runs/detect/train52/weights/best.onnx' (11.7 MB)
TensorFlow SavedModel: running 'onnx2tf -i "/content/runs/detect/train52/weights/best.onnx" -o "/content/runs/detect/train52/weights/best_saved_model" -nuo --non_verbose'
TensorFlow SavedModel: export failure ❌ 47.8s: generic_type: cannot initialize type "StatusCode": an object with that name is already defined
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-18-c5b245ed7118>](https://localhost:8080/#) in <cell line: 2>()
      1 # Export the model
----> 2 model.export(format='tflite') # export the model to tflite format

10 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow_lite_support/python/task/vision/core/tensor_image.py](https://localhost:8080/#) in <module>
     17 
     18 from tensorflow_lite_support.python.task.vision.core import color_space_type
---> 19 from tensorflow_lite_support.python.task.vision.core.pybinds import image_utils
     20 
     21 

ImportError: generic_type: cannot initialize type "StatusCode": an object with that name is already defined

**Comment by glenn-jocher** [comment]
@PEEMTM hello! It seems like you're encountering an issue with TensorFlow compatibility during the export process to TFLite. The warning indicates that TensorFlow version 2.15.0 is installed, but a version <=2.13.1 is required for successful export with our current setup.

To resolve this, you should downgrade TensorFlow to a compatible version (<=2.13.1) before attempting the export again. This should help avoid the `ImportError` you're experiencing.

For detailed steps on model export, please refer to our documentation on the Export mode at https://docs.ultralytics.com/modes/export. If you continue to face issues, feel free to open an issue in the repo with the details, and we'll be glad to assist you further. Good luck with your model conversion! 🚀
