### ISSUE TITLE
in the line counter solution, how to change in and out name ?

### ISSUE THREAD

**Issue by Rasantis** [ultralytics/ultralytics#7569]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to change the names (in & out )in the line counter solution, im using this code:
from ultralytics import YOLO
from ultralytics.solutions import object_counter
import cv2

model = YOLO("yolov8n.pt")
cap = cv2.VideoCapture("HOME/cam_certa.mp4")
assert cap.isOpened(), "Error reading video file"
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

line_points = [(170, 120), (380, 120)]  # line or region points
classes_to_count = [0]  # person classes for count

# Video writer
video_writer = cv2.VideoWriter("object_counting_output3.avi",
                       cv2.VideoWriter_fourcc(*'mp4v'),
                       fps,
                       (w, h))

# Init Object Counter
counter = object_counter.ObjectCounter()
counter.set_args(view_img=True,
                 reg_pts=line_points,
                 classes_names=model.names,
                 draw_tracks=True)

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break
    tracks = model.track(im0, persist=True, show=False,
                         classes=classes_to_count)

    im0 = counter.start_counting(im0, tracks)
    video_writer.write(im0)

cap.release()
video_writer.release()
cv2.destroyAllWindows()

**Comment by glenn-jocher** [comment]
@Rasantis hello! To change the names displayed for the "in" and "out" counts in the line counter solution, you can modify the `classes_names` argument when initializing the `ObjectCounter`. This argument accepts a list of class names corresponding to the indices of the classes you wish to count.

For example, if you want to change the name for class index 0 from "person" to "visitor", you would update the `classes_names` parameter to include "visitor" at index 0. Here's how you can do it:

```python
counter.set_args(view_img=True,
                 reg_pts=line_points,
                 classes_names=['visitor'],  # Change 'person' to 'visitor'
                 draw_tracks=True)
```

Make sure that the list you provide to `classes_names` matches the indices of `classes_to_count`. If you have multiple classes, ensure each name in the list corresponds to the class index you want to rename.

Happy coding! 😊👨‍💻
