### ISSUE TITLE
How to extract class ids from detected objects?

### ISSUE THREAD

**Issue by CatfishedCow** [ultralytics/ultralytics#757]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I'm new to YOLO and object detection in general. I am wondering how to extract class ids from detected objects?
```
from ultralytics import YOLO
from ultralytics.yolo.v8.detect.predict import DetectionPredictor
import cv2

model = YOLO("x")
model.predict(source="0", show=True, conf=0.5)
```

How do I extract the data from that? What variable do I print?

**Comment by AyushExel** [comment]
See - https://docs.ultralytics.com/predict/
```
result = model(img)
cls = result[0].boxes.cls
```

**Comment by CatfishedCow** [comment]
How do I implement that to detect data from a webcam?

**Comment by AyushExel** [comment]
set source="0"
see the docs that I've linked above

**Comment by CatfishedCow** [comment]
ok thanks!

**Comment by pderrenger** [comment]
@CatfishedCow you're welcome! If you have any more questions or need further assistance, feel free to ask. Happy coding!
