### ISSUE TITLE
Exception thrown: read access violation. this was 0xFFFFFFFFFFFFFFFF.

### ISSUE THREAD

**Issue by TreySongw** [ultralytics/ultralytics#7570]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I use YOLOv8-ONNXRuntime-CPP ,I have this exception:Exception thrown: read access violation. this was 0xFFFFFFFFFFFFFFFF in onnxruntime_cxx_inline.h.
![image](https://github.com/ultralytics/ultralytics/assets/153568256/3150f6d1-cda1-43cf-b351-e206e53ef9f7)

```
//onnxruntime_cxx_inline.h.
template <typename T>
inline void SessionImpl<T>::Run(const RunOptions& run_options, const char* const* input_names, const Value* input_values, size_t input_count,
                                const char* const* output_names, Value* output_values, size_t output_count) {
  static_assert(sizeof(Value) == sizeof(OrtValue*), "Value is really just an array of OrtValue* in memory, so we can reinterpret_cast safely");
  auto ort_input_values = reinterpret_cast<const OrtValue* const*>(input_values);
  auto ort_output_values = reinterpret_cast<OrtValue**>(output_values);
  ThrowOnError(GetApi().Run(this->p_, run_options, input_names, ort_input_values, input_count, output_names, output_count, ort_output_values));// the exception happended here
}
```
I have tried to debug :
```
//main.cpp
void new_QT_python::ClsTest()
{
    YOLO_V8* yoloDetector = new YOLO_V8;
    std::string model_path = "D:/ai/yolov8s-cls.onnx";
    ReadCocoYaml(yoloDetector);
    DL_INIT_PARAM params{ model_path, YOLO_CLS, {224, 224} };
    yoloDetector->CreateSession(params);// when I debug,I found the exception happend from here
    Classifier(yoloDetector);
}
```
```
//inference.cpp
const char* YOLO_V8::CreateSession(DL_INIT_PARAM& iParams) {
    const char* Ret = RET_OK;
    std::regex pattern("[\u4e00-\u9fa5]");
    bool result = std::regex_search(iParams.modelPath, pattern);
    if (result)
    {
        Ret = "[YOLO_V8]:Your model path is error.Change your model path without chinese characters.";
        std::cout << Ret << std::endl;
        return Ret;
    }
    try
    {
        rectConfidenceThreshold = iParams.rectConfidenceThreshold;
        iouThreshold = iParams.iouThreshold;
        imgSize = iParams.imgSize;
        modelType = iParams.modelType;
        env = Ort::Env(ORT_LOGGING_LEVEL_WARNING, "Yolo");
        Ort::SessionOptions sessionOption;
        if (iParams.cudaEnable)
        {
            cudaEnable = iParams.cudaEnable;
            OrtCUDAProviderOptions cudaOption;
            cudaOption.device_id = 0;
            sessionOption.AppendExecutionProvider_CUDA(cudaOption);
        }
        sessionOption.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);
        sessionOption.SetIntraOpNumThreads(iParams.intraOpNumThreads);
        sessionOption.SetLogSeverityLevel(iParams.logSeverityLevel);

#ifdef _WIN32
        int ModelPathSize = MultiByteToWideChar(CP_UTF8, 0, iParams.modelPath.c_str(), static_cast<int>(iParams.modelPath.length()), nullptr, 0);
        wchar_t* wide_cstr = new wchar_t[ModelPathSize + 1];
        MultiByteToWideChar(CP_UTF8, 0, iParams.modelPath.c_str(), static_cast<int>(iParams.modelPath.length()), wide_cstr, ModelPathSize);
        wide_cstr[ModelPathSize] = L'\0';
        const wchar_t* modelPath = wide_cstr;
#else
        const char* modelPath = iParams.modelPath.c_str();
#endif // _WIN32

        session = new Ort::Session(env, modelPath, sessionOption);//the exception happended here
        Ort::AllocatorWithDefaultOptions allocator;
        size_t inputNodesNum = session->GetInputCount();
        for (size_t i = 0; i < inputNodesNum; i++)
        {
            Ort::AllocatedStringPtr input_node_name = session->GetInputNameAllocated(i, allocator);
            char* temp_buf = new char[50];
            strcpy(temp_buf, input_node_name.get());
            inputNodeNames.push_back(temp_buf);
        }
        size_t OutputNodesNum = session->GetOutputCount();
        for (size_t i = 0; i < OutputNodesNum; i++)
        {
            Ort::AllocatedStringPtr output_node_name = session->GetOutputNameAllocated(i, allocator);
            char* temp_buf = new char[10];
            strcpy(temp_buf, output_node_name.get());
            outputNodeNames.push_back(temp_buf);
        }
        options = Ort::RunOptions{ nullptr };
        WarmUpSession();
        return RET_OK;
    }
    catch (const std::exception& e)
    {
        const char* str1 = "[YOLO_V8]:";
        const char* str2 = e.what();
        std::string result = std::string(str1) + std::string(str2);
        char* merged = new char[result.length() + 1];
        std::strcpy(merged, result.c_str());
        std::cout << merged << std::endl;
        delete[] merged;
        return "[YOLO_V8]:Create session failed.";
    }

}
```
# Environment
vs2019 and I have added these dependencies as follows manually(I created a QT project not cmake project)
Dependency | Version
-- | --
Onnxruntime(,windows) |onnxruntime-win-x64-gpu-1.15.1
OpenCV | opencv4.5.3
C++ Standard | 17
Cuda  | 11.8
cuDNN (Cuda required) | =8

**Comment by glenn-jocher** [comment]
@TreySongw hello! It seems you're encountering a read access violation when using YOLOv8 with ONNXRuntime in C++. This type of error often indicates that there's an issue with memory access, such as dereferencing a null or invalid pointer.

Here are a few steps you might consider to troubleshoot the issue:

1. **Check Model Path**: Ensure that the model path is correct and the model file is accessible.
2. **Validate ONNX Model**: Verify that the ONNX model is not corrupted and is compatible with the ONNXRuntime version you're using.
3. **ONNXRuntime Version**: Make sure that the ONNXRuntime version is compatible with your system and other dependencies.
4. **Memory Management**: Review the memory allocation and deallocation in your code to ensure there are no memory leaks or invalid accesses.
5. **Debugging**: Use a debugger to step through the code and inspect variables, especially around the point where the exception is thrown.
6. **Error Messages**: Pay attention to any error messages or exceptions thrown by the ONNXRuntime API, as they can provide clues about what's going wrong.

If after these steps the issue persists, consider opening an issue on the Ultralytics YOLOv8 repo with detailed information about the error and the steps you've taken to resolve it. The community and maintainers can then provide more targeted assistance.

Remember to keep your environment up to date and ensure compatibility between all the components you're using. Good luck! 🍀

**Comment by qingjiudd** [comment]
our computer is configured with CUDA, but onnxruntime does use a CPU version that causes the session to be unable to be created successfully, change params.cudaEnable = true; to params.cudaEnable =false in line 158 of main.cpp.

**Comment by qingjiudd** [comment]
Your computer is configured with CUDA, but onnxruntime does use a CPU version that causes the session to be unable to be created successfully, change params.cudaEnable = true; to params.cudaEnable =false in line 158 of main.cpp.

**Comment by glenn-jocher** [comment]
Hello @qingjiudd,

Thank you for your detailed report and for sharing your insights! It seems like the issue might be related to the ONNXRuntime configuration with CUDA.

To ensure we can effectively troubleshoot this, could you please provide a minimum reproducible example of your code? This will help us better understand the context and pinpoint the issue. You can refer to our guide on creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please verify that you are using the latest versions of ONNXRuntime, CUDA, and other dependencies. Compatibility issues can often be resolved by updating to the latest versions.

Here's a quick checklist to help you further debug the issue:
1. **Model Path**: Ensure the model path is correct and accessible.
2. **ONNX Model**: Validate that the ONNX model is not corrupted and is compatible with the ONNXRuntime version.
3. **CUDA Compatibility**: Confirm that your CUDA installation is correctly set up and compatible with your ONNXRuntime version.
4. **Environment Variables**: Ensure that your environment variables are correctly set for CUDA.

If the issue persists, please share the updated code snippet and any error messages you encounter. This will help us provide more targeted assistance.

Thank you for your cooperation and patience! 😊

**Comment by ThangQT2606** [comment]
tôi đã thực hiện suy luận yolov8 sử dụng onnx cpp nhưng bị lỗi như sau:
[YOLO_V8]:Your model path is error.Change your model path without chinese characters.
tôi đã convert yolov8.pt bằng câu lệnh: !yolo export model=yolov8n.pt opset=12 simplify=True dynamic=False format=onnx imgsz=640,640
Cho tôi hỏi là có cách nào giải quyết vấn đề này không?

**Comment by glenn-jocher** [comment]
Cảm ơn bạn đã chia sẻ vấn đề. Lỗi này xuất phát từ việc đường dẫn model chứa ký tự tiếng Trung, gây lỗi trong ONNXRuntime khi tạo session. Hãy đảm bảo rằng đường dẫn model không chứa ký tự tiếng Trung hoặc ký tự đặc biệt. Ngoài ra, bạn có thể thử đổi tên file hoặc di chuyển file model vào một thư mục có đường dẫn đơn giản hơn (chỉ chứa các ký tự ASCII). Nếu vấn đề vẫn chưa được giải quyết, vui lòng kiểm tra lại quá trình xuất model để đảm bảo các tham số đúng.

**Comment by ThangQT2606** [comment]
![ubuntu](https://github.com/user-attachments/assets/43b04bef-b654-41aa-ad17-13951988a0b7)
tôi đã chạy được nhưng việc detection bằng C++ có vẻ không được, tôi cũng đã debug các bước in ra
cũng là model onnx đó bằng python thì cho kết quả tốt, bạn có thể giúp tôi xử lý vấn đề này không?
![test_out](https://github.com/user-attachments/assets/12a68bf1-9fae-493e-9d7e-5417dae6213e)

**Comment by glenn-jocher** [comment]
Cảm ơn bạn đã chia sẻ chi tiết vấn đề. Nếu model ONNX hoạt động tốt bằng Python nhưng không hoạt động như mong đợi trong C++, có thể nguyên nhân nằm ở cách xử lý đầu vào hoặc đầu ra trong mã C++. Hãy kiểm tra rằng:

1. Đầu vào được chuẩn hóa (normalize) và định dạng giống hệt như trong Python, bao gồm kích thước ảnh và cách chuẩn hóa giá trị pixel.
2. Tên input/output nodes trong ONNX khớp với mã C++ của bạn.
3. Kết quả đầu ra từ inference được giải mã (decode) chính xác, bao gồm việc áp dụng NMS (Non-Maximum Suppression) nếu cần.

Nếu vẫn gặp lỗi, hãy thử so sánh từng bước pre-processing và post-processing giữa Python và C++. Nếu cần thêm hỗ trợ, bạn có thể chia sẻ đoạn mã C++ liên quan để mình hỗ trợ chi tiết hơn.

**Comment by ThangQT2606** [comment]
đoạn mã này tôi đã clone từ github, tôi gửi trực tiếp đoạn mã ở đây như sau
tôi có cấu trúc dự án trong config.conf, hi vọng bạn có thể giúp tôi. Thank you so much!!!
https://drive.google.com/drive/folders/1WJ-9XiBYO5lc3srtTT8ZsFdCFjjYHPhg?fbclid=IwAR1fljDPNgrFqJqzwE0Z3dUoPndpBIoWkUDxcAfKkzKenVWO4I0T8jad39Y

**Comment by glenn-jocher** [comment]
Cảm ơn bạn đã chia sẻ thông tin. Tuy nhiên, chúng tôi không thể hỗ trợ các yêu cầu liên quan đến mã nguồn hoặc cấu trúc dự án được lưu trữ trên các liên kết bên ngoài như Google Drive. Để nhận được sự trợ giúp hiệu quả, vui lòng chia sẻ trực tiếp đoạn mã liên quan đến vấn đề trong bình luận, hoặc đơn giản hóa vấn đề thành một MRE (Minimum Reproducible Example) theo hướng dẫn [tại đây](https://docs.ultralytics.com/help/minimum_reproducible_example/).

Nếu bạn gặp lỗi cụ thể, vui lòng cung cấp chi tiết lỗi, đoạn mã liên quan, và các bước để tái hiện vấn đề. Điều này sẽ giúp chúng tôi hỗ trợ bạn tốt hơn. Cảm ơn bạn!
