### ISSUE TITLE
Can yolov8 do polygon detection tasks?

### ISSUE THREAD

**Issue by whysirier** [ultralytics/ultralytics#7579]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

There is a question: the traditional yolo can do the detect tasks or segment tasks. However, I have a polygon detect tasks with 4 points, if I use the yolov8-seg although it has a high performance, it may be
output the points which I don't need. Thus, is there a way for achieve this task like yolov8-det but for  polygon  detection tasks. Thanks.

**Comment by glenn-jocher** [comment]
@whysirier hello! YOLOv8 is primarily designed for object detection with bounding boxes and does not natively support polygon detection tasks out of the box. However, you can use the segmentation capabilities of YOLOv8 to create masks for objects, which can then be post-processed to approximate polygon shapes by fitting polygons to the segmented masks. This would require additional steps beyond the standard YOLOv8 pipeline. For more details on segmentation with YOLOv8, you can refer to our documentation on the Segment mode. Keep in mind that custom post-processing for polygon detection would be something you'd need to implement on your own. 😊🔍

**Comment by loucif01** [comment]
Hi @glenn-jocher . Thank you for your insights on YOLOv8's mask scaling. I'm facing a related issue where the model in some cases gives correct bounding boxes but empty segmentation masks ([]). I'm using yolov8l-seg.pt, and this problem persists across various images. When I change the image size during inference, the issue resolves for some images but then appears in others.

Is this related to the mask scaling issue you mentioned, or could it be a different problem? 
Thanks.

**Comment by glenn-jocher** [comment]
@loucif01 hi there! It sounds like you're encountering an issue where the segmentation masks are not consistently generated. This could be related to mask scaling, but it might also be due to other factors such as the threshold settings or the characteristics of the images themselves. I recommend checking your confidence and mask thresholds to ensure they're set appropriately. If the problem persists, please open an issue on our repo with details so we can investigate further. Thanks for reaching out! 😊🛠️

**Comment by loucif01** [comment]
Thanks for your response. After adjusting the conf threshold, I still face issues with segmentation masks being empty, particularly when bounding boxes are outside the image boundaries .

Is there a specific threshold for mask generation? Also, could the out-of-bounds bounding boxes be causing the empty masks?

Thanks.

**Comment by whysirier** [comment]
> Thanks for your response. After adjusting the conf threshold, I still face issues with segmentation masks being empty, particularly when bounding boxes are outside the image boundaries .
> 
> Is there a specific threshold for mask generation? Also, could the out-of-bounds bounding boxes be causing the empty masks?
> 
> Thanks.

I remember the size of marks is (160, 160), the boxes should be scaled as the marks ?

**Comment by glenn-jocher** [comment]
@whysirier It's possible that bounding boxes extending beyond image boundaries could lead to empty segmentation masks, as masks are typically computed within the confines of the image. There is indeed a separate threshold for mask generation, which you might need to adjust. Also, ensure that the bounding boxes are correctly scaled in relation to the mask size. If issues persist, please provide details in a new issue on our repo for further assistance. Thank you! 😊🔧

**Comment by loucif01** [comment]
@glenn-jocher Thanks, but I didn't find the threshold for mask generation in the list of arguments, I just found the conf argument which is object confidence threshold for detection based on the documentation: https://docs.ultralytics.com/modes/predict/#inference-arguments

**Comment by loucif01** [comment]
@glenn-jocher My conf is set to 0.25 which is the default value, but still got empty masks associated with bounding boxes outside the image boundaries. Note that I'm using polygons as masks in my image training data not free-shape masks.

**Comment by glenn-jocher** [comment]
@loucif01 If you're using polygonal masks in training and encountering empty masks during inference, it's important to ensure that the model's output aligns with your training data format. Bounding boxes outside image boundaries can indeed result in empty masks. You may need to clip or adjust bounding boxes during post-processing to ensure they fit within the image. If the issue persists, please open an issue on our repo with details for further assistance. 😊🛠️
