### ISSUE TITLE
Logging customisation

### ISSUE THREAD

**Issue by rusmux** [ultralytics/ultralytics#758]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Is there any way to allow for more logging customisation? Currently, `project` and `name` seem to be the only parameters for logging. However, when using ClearML I don't want ClearML experiment path to coincide with my local experiment path. I could use `experiments` folder in my repository and `Detection project/yolov8n` folder in ClearML.

### Use case

To separate local experiment path and ClearML experiment path

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mbenami** [comment]
+1 on this 
I would like to add some args for the training that will be saved on clearml configuration 
currently, I can only use the `trainer.args` and cannot add more 
(same as it was when lunch train on yolov5 with `run()` )
Thanks

**Comment by pderrenger** [comment]
@mbenami thanks for reaching out! YOLOv8 currently supports logging with the `project` and `name` parameters. To achieve custom logging configurations, you can modify the logging behavior by customizing the `train.py` script to include additional arguments for the ClearML configuration. This can be done by incorporating the desired args within the script and adjusting the logging functions to accommodate these new parameters. This will allow for separate local and ClearML experiment paths. If you have any further questions on how to implement this, feel free to ask!
