### ISSUE TITLE
If a corner of the rotate rectangle is out of the image range, How to annotate the image?

### ISSUE THREAD

**Issue by JimXu1989** [ultralytics/ultralytics#7581]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

the document says that the value of the corner is in range (0,1) , but when if a corner of the rotate rectangle is out of the image range, How to annotate the image?

**Comment by glenn-jocher** [comment]
@JimXu1989 when annotating rotated rectangles where a corner extends beyond the image range, you should still normalize the corner coordinates to be within the (0,1) range based on the image dimensions. If a corner falls outside the image boundaries, it should be clipped to 0 or 1 accordingly. This ensures that all annotations remain consistent with the expected input format for YOLOv8. For more details on annotation formats and guidelines, please refer to our documentation on data preparation at https://docs.ultralytics.com. 😊📏

**Comment by JimXu1989** [comment]
> @JimXu1989 when annotating rotated rectangles where a corner extends beyond the image range, you should still normalize the corner coordinates to be within the (0,1) range based on the image dimensions. If a corner falls outside the image boundaries, it should be clipped to 0 or 1 accordingly. This ensures that all annotations remain consistent with the expected input format for YOLOv8. For more details on annotation formats and guidelines, please refer to our documentation on data preparation at https://docs.ultralytics.com. 😊📏

If I clip the point to (0,1), the points set is not a rectangle anymore. is yolov8-obb accept more than 4 points as annotation?

**Comment by glenn-jocher** [comment]
@JimXu1989, YOLOv8-obb annotations should be provided with exactly four points defining the rotated rectangle. If a corner extends beyond the image, clip it to (0,1), and the model will interpret the annotation as best as possible. YOLOv8 does not accept more than four points for a single object's annotation. For further guidance on annotations, please see our documentation on data preparation. 📐✂️

**Comment by JimXu1989** [comment]
> @JimXu1989, YOLOv8-obb annotations should be provided with exactly four points defining the rotated rectangle. If a corner extends beyond the image, clip it to (0,1), and the model will interpret the annotation as best as possible. YOLOv8 does not accept more than four points for a single object's annotation. For further guidance on annotations, please see our documentation on data preparation. 📐✂️

Thanks for reply, the best way is do not let this happen

**Comment by glenn-jocher** [comment]
@JimXu1989, indeed, ensuring that all corners of the rotated rectangle are within the image boundaries is the best practice for annotations. If it's unavoidable, clipping to (0,1) is the correct approach. Happy annotating! 😊👍
