### ISSUE TITLE
The Metric of Small Object Detection

### ISSUE THREAD

**Issue by jiaduob** [ultralytics/ultralytics#7583]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Thanks to the author for the excellent code repository. There is a request for the small object detection tasks. How can I get the AP and AR for small, medium and large objects in training? Thanks very much.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jiaduob hello! Thank you for your kind words and for reaching out with your question.

To obtain the Average Precision (AP) and Average Recall (AR) for small, medium, and large objects during training with YOLOv8, you can use the `--object-sizes` argument when running the `val` mode after training. This will provide you with a breakdown of performance metrics across different object sizes.

For more detailed instructions on how to use the `val` mode and the various arguments you can specify, please refer to our documentation on the Val mode at https://docs.ultralytics.com/modes/val.

If you have any further questions or need additional assistance, feel free to ask. Happy detecting! 😊

**Comment by Kevinskr** [comment]
> @jiaduob hello! Thank you for your kind words and for reaching out with your question.
> 
> To obtain the Average Precision (AP) and Average Recall (AR) for small, medium, and large objects during training with YOLOv8, you can use the `--object-sizes` argument when running the `val` mode after training. This will provide you with a breakdown of performance metrics across different object sizes.
> 
> For more detailed instructions on how to use the `val` mode and the various arguments you can specify, please refer to our documentation on the Val mode at https://docs.ultralytics.com/modes/val.
> 
> If you have any further questions or need additional assistance, feel free to ask. Happy detecting! 😊

I got the error : 'object-sizes' is not a valid YOLO argument
