### ISSUE TITLE
ERROR: IndexError: list index out of range

### ISSUE THREAD

**Issue by andysingal** [ultralytics/ultralytics#7585]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-23-e77b0b7740f7>](https://localhost:8080/#) in <cell line: 1>()
      1 if training_option == 'Train new CNN':
----> 2   model.train(data=data, epochs=epochs, imgsz=200, batch=batch, cache=True, patience=50)
      3 else:
      4   model.train(data=data, epochs=epochs, imgsz=200, batch=batch, cache=True, patience=50, resume=True, model=model)

6 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/detect/val.py](https://localhost:8080/#) in get_stats(self)
    144         if len(stats) and stats[0].any():
    145             self.metrics.process(*stats)
--> 146         self.nt_per_class = np.bincount(stats[-1].astype(int), minlength=self.nc)  # number of targets per class
    147         return self.metrics.results_dict
    148 

IndexError: list index out of range
```

### Environment

```
Ultralytics YOLOv8.0.186 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 26.7/78.2 GB disk)
```

### Minimal Reproducible Example

```
if training_option == 'Train new CNN':
  model.train(data=data, epochs=epochs, imgsz=640, batch=batch, cache=True, patience=50)
else:
  model.train(data=data, epochs=epochs, imgsz=640, batch=batch, cache=True, patience=50, resume=True, model=model)
```
ERROR:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-23-e77b0b7740f7>](https://localhost:8080/#) in <cell line: 1>()
      1 if training_option == 'Train new CNN':
----> 2   model.train(data=data, epochs=epochs, imgsz=200, batch=batch, cache=True, patience=50)
      3 else:
      4   model.train(data=data, epochs=epochs, imgsz=200, batch=batch, cache=True, patience=50, resume=True, model=model)

6 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/detect/val.py](https://localhost:8080/#) in get_stats(self)
    144         if len(stats) and stats[0].any():
    145             self.metrics.process(*stats)
--> 146         self.nt_per_class = np.bincount(stats[-1].astype(int), minlength=self.nc)  # number of targets per class
    147         return self.metrics.results_dict
    148 

IndexError: list index out of range
```

### Additional

Here is the notebook for reference:
https://colab.research.google.com/drive/1xq03OEdbcLnjKuJvS8_UDGx6k7MabTSl?usp=sharing

Data.yaml
```
names:
- person
- person-like
nc: 2
test: /content/data/Test/Test/JPEGImages
train: /content/data/Train/Train/JPEGImages
val: /content/data/Val/Val/JPEGImages
```

Dataset used: https://www.kaggle.com/datasets/karthika95/pedestrian-detection/data 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@andysingal hello! It looks like you're encountering an `IndexError` during training, which typically suggests an issue with the data indexing or processing. Here are a few steps you can take to troubleshoot this error:

1. **Data Integrity**: Ensure that your dataset is correctly labeled and that the annotations match the format expected by YOLOv8. Verify that there are no missing or corrupt files.

2. **Data Configuration**: Double-check your `data.yaml` file to ensure the paths to `train`, `val`, and `test` are correct and accessible. Also, confirm that the `nc` (number of classes) matches the actual number of unique classes in your dataset.

3. **Batch Size**: If you're using a very small dataset, make sure that your batch size is not larger than the number of images in your dataset.

4. **Model Configuration**: When resuming training with a pre-trained model, ensure that the model configuration is compatible with your dataset, particularly the number of classes.

If the issue persists after checking these points, consider reviewing the relevant sections in our documentation for more detailed guidance on training and data preparation. If you're still unable to resolve the problem, feel free to open a new issue with the full error log and details about the steps you've taken so far. Our community is always here to help! 😊

**Comment by andysingal** [comment]
Thanks for your reply, The dataset used has annotations and images. I have
shared the data.yaml file
Love to understand what seems to be the issue, i have shared the notebook,
kaggle data used. let me know if you need any further information.
Thanks,
Andy

**Comment by Laughing-q** [comment]
@andysingal hi, I noticed the package version you are using is outdated, it indeed has some potential issues, please try to update to the latest version 8.1.1. :)

**Comment by andysingal** [comment]
Thank you, I am using that package since Wandb only works on that version.
Cheers :)

**Comment by Laughing-q** [comment]
@andysingal no worries, wandb has been supported for a long time, you can try to update and check if it works to you. :)

**Comment by andysingal** [comment]
> names:
> - person
> - person-like
> nc: 2
> test: /content/data/Test/Test/JPEGImages
> train: /content/data/Train/Train/JPEGImages
> val: /content/data/Val/Val/JPEGImages

@Laughing-q Thanks for your reply, Now the error is different: 

Here is the notebook: https://colab.research.google.com/drive/1xq03OEdbcLnjKuJvS8_UDGx6k7MabTSl?usp=sharing

<img width="863" alt="Screenshot 2024-01-15 at 7 46 22 PM" src="https://github.com/ultralytics/ultralytics/assets/20493493/3141b8b8-9a07-4823-89aa-3f7ea2841165">

**Comment by andysingal** [comment]
Thank you, I have labels in .xml and images in .jpg format. So i need to
change the labels to .txt and images --pic1.jpg?
 [image: Screenshot 2024-01-15 at 8.17.24 PM.png]

**Comment by glenn-jocher** [comment]
Yes, @andysingal, you'll need to convert your .xml label files to .txt format following the YOLO format, and your images should be named consistently (e.g., `pic1.jpg`). Each .txt label file should correspond to an image file with the same name. Our documentation provides detailed instructions on how to prepare your dataset. 😊
