### ISSUE TITLE
save_conf=True predict parameters not behaving as expected  

### ISSUE THREAD

**Issue by alexandercronin** [ultralytics/ultralytics#760]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

1 .save_conf command line option is not behaving as expected. File containing confidences not present.  

- Directly in a Python environment.
     - save_conf=True - no visible difference in output between setting True/False 
- CLI 
     - save_conf=True - no visible difference in output between setting True/False 

Source of information on valid arguments: https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/cfg/default.yaml 

### Environment

- Ultralytics YOLOv8.0.25 🚀 Python-3.8.10 torch-1.13.1+cu117 CPU

### Minimal Reproducible Example

```
from ultralytics import YOLO
import subprocess

# Load a model
model = YOLO("yolov8n.pt")  # load an official model

# Predict with the model
results_detection = model(source="https://ultralytics.com/images/bus.jpg", 
                            show=True,        # only works in standard python environment
                            save_txt=True,    # works correctly: generates the labels folder with text files,  
                                                #  the name of the file is the same as the name of the image with the extension .txt,
                                                #  the file contains the class number and the 4 co-ords for the bounding box
                            save_conf=True,   # has no effect if set to True or False
                            save_crop=True,   # works correctly 
                            # visualize=True, # not yet supported
                            classes=0,        # works correcly by filtering for the person class
                            boxes=True        # has no effect if set to True or False
                         )
yolo_command = 'yolo predict model=yolov8n.pt source="https://ultralytics.com/images/bus.jpg" save_conf=True save_txt=True, save_crop=True'
subprocess.check_output([yolo_command], shell=True)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by alexandercronin** [comment]
@PanchumarthiAbhinav thank you very much for looking into it. I think you could be right. I think you are referring to line 67 [here](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/v8/detect/predict.py) . 

This area of the code was updated via a [pull](https://github.com/ultralytics/ultralytics/pull/584) request a short time ago.  

I think reporting on findings in the frame as json dict like the following might make it easier. And then querying with [jmespath](https://jmespath.org/) or similar. But I do not understand the full architecture of the system. 
[ 
   object1:{
    bounding_box: x , y, x, y   
    confidences:{
      cls: conf
      cls: conf
  }, 
   object2:{
    bounding_box: x , y, x, y   
    confidences:{
      cls: conf
      cls: conf
  } 

I am sure @glenn-jocher  will do something awesome here :)

**Comment by glenn-jocher** [comment]
@theyurtman hello! Thanks for reaching out. It looks like you're doing everything correctly in your code snippet. If the confidence scores are not being saved as expected, it might be due to a version-specific issue or a minor bug in the codebase.

As a quick workaround, you can manually extract and save the confidence scores from the `results` object. Here's a small snippet on how you might do it:

```python
# Assuming 'results' is your model prediction output
for i, (pred) in enumerate(results.pred):
    with open(f'./dataset_for_yolo/test/labels/{i}_conf.txt', 'w') as f:
        for *xyxy, conf, cls in pred:
            f.write(f'{cls} {conf} {" ".join(map(str, xyxy))}\n')
```

This will save a separate file with class and confidence scores along with bounding box coordinates for each prediction.

Meanwhile, I'd recommend checking if you're using the latest version of the Ultralytics YOLOv8 repository, as updates and bug fixes are regularly made. If the issue persists, it might be helpful to raise an issue on the [GitHub repository](https://github.com/ultralytics/ultralytics/issues) with detailed information so it can be addressed directly by the development team. 

Hope this helps! Let us know if you have any more questions. 😊

**Comment by theyurtman** [comment]
thank you for answer but ı give a error again, results is not have a pred attribute

**Comment by glenn-jocher** [comment]
@theyurtman hello! 😊 It seems there was a misunderstanding in my previous suggestion. My apologies for the confusion. If `results` doesn't have a `pred` attribute, you should access predictions using `results.prediction`. Here's a corrected snippet:

```python
# Assuming 'results' is your model prediction output
for i, pred in enumerate(results.prediction):
    with open(f'./dataset_for_yolo/test/labels/{i}_conf.txt', 'w') as f:
        for *xyxy, conf, cls in pred:
            f.write(f'{cls.item()} {conf.item()} {" ".join(map(str, map(int, xyxy)))}\n')
```

This should help you save the confidence scores correctly. If you encounter any more issues, feel free to ask. Happy coding! 🚀
