### ISSUE TITLE
如何保存预测结果为jason格式？？？？？？？

### ISSUE THREAD

**Issue by 52chengcheng** [ultralytics/ultralytics#7602]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

尝试了resutls.tojason()
提示错误，AttributeError: 'list' object has no attribute 'tojson'

尝试了model.predict(path,save_json=True)
发现不能生成

**Comment by glenn-jocher** [comment]
@52chengcheng 您好！要保存预测结果为JSON格式，您可以使用 `predict` 模式，并设置 `save_json=True` 参数。如果遇到错误，确保您使用的是最新版本的 YOLOv8，并且正确地调用了函数。如果问题仍然存在，请参考我们的文档中的 [Predict](https://docs.ultralytics.com/modes/predict) 部分，它提供了有关如何使用模型进行预测和保存结果的详细信息。如果您在文档中找不到解决方案，请在GitHub issues中提供完整的错误信息和代码片段，我们的团队会乐意帮助您解决问题。🙂
