### ISSUE TITLE
validation vs testing in context of data.yaml

### ISSUE THREAD

**Issue by IgorGoldberg** [ultralytics/ultralytics#7604]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In the data.yaml there can be 3 sections: "Train" "Val" and "Test"
1)Do I understand right that: 
during the **training** validation is done each epoch and the MAP is calculated using the paths in the "Val" section (NOT the "Test"). Am I right?
2) If I am right, so when are the "Test" paths being used?
3) If I run:
 metrics = model.val(data = path_to_data_yaml)  what sections of the data.yaml file are used in this case? Is it again only the "val" section,  or is it in the tests section or maybe both?

Thanks

**Comment by meixiangzhang** [comment]
I also think so. There is a split parameter in default.yaml, which is set to "val" by default. If you want to obtain the metrics of the model on the test set, you can modify the above parameter to set it to "test".

**Comment by glenn-jocher** [comment]
@meixiangzhang hello! Your understanding is correct:

1) During training, the model is validated on the "Val" section of the `data.yaml` file after each epoch, and the mAP is calculated using this data.

2) The "Test" paths are used when you explicitly want to evaluate your model on a separate test dataset that has not been seen during the training or validation phases. This is typically done after training to assess the model's performance on completely new data.

3) When you run `model.val(data=path_to_data_yaml)`, it uses only the "Val" section of the `data.yaml` file by default. If you want to evaluate the model on the "Test" section, you would need to adjust the configuration accordingly.

For more detailed information on how to configure and use these sections, please refer to our documentation at https://docs.ultralytics.com. 😊

**Comment by IgorGoldberg** [comment]
@glenn-jocher 
Thanks! But it seems to me there is a contradiction between your part of an answer 2 and 3
In 2 you explain when (not how) to use test section: and you say
I do it when "want to evaluate your model on a separate test dataset that has not been seen during the training or validation phases"  Ok lets say this moment arrived. I thought I should do it using the 
model.val(data=path_to_data_yaml) ... But yoyu say that model.val(data=path_to_data_yaml) uses the val section

**Comment by glenn-jocher** [comment]
@IgorGoldberg apologies for any confusion. Let's clarify:

1) The `model.val(data=path_to_data_yaml)` function is typically used to evaluate the model on the validation dataset during or after training to monitor and assess the model's performance.

2) To evaluate the model on the test dataset, you would typically modify the configuration to specify that you want to use the "Test" section of the `data.yaml` file. This is not done with the `model.val()` function but through a different evaluation script or function that is designed to use the "Test" paths.

The test dataset is used to evaluate the model's performance after all training and validation have been completed, providing an unbiased assessment of the model's ability to generalize to new data.

For specific commands and examples on how to use the test section, please refer to our documentation at https://docs.ultralytics.com.
