### ISSUE TITLE
mosaic visualization

### ISSUE THREAD

**Issue by gisagisa** [ultralytics/ultralytics#7606]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hi, @glenn-jocher  YOLOv8 employs mosaic data augmentation, is there any way to visualize some of the training data after the mosaic augmentation is applied? I wanted to see the augmentation output

**Comment by glenn-jocher** [comment]
@gisagisa hello! 👋

Yes, YOLOv8 does use mosaic data augmentation. To visualize the augmented training data, you can enable the `--show` flag during training. This will display the mosaic images during the training process. Additionally, you can set the `--save-crop` flag to save these visualizations to disk. For more details on how to use these flags, please refer to the Training section in our documentation.

Happy training! 🚀
