### ISSUE TITLE
Create annotated images with confidence, bounding box and class using SDK without wrapping it in a a PIL.Image first

### ISSUE THREAD

**Issue by alexandercronin** [ultralytics/ultralytics#761]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In the code below from https://docs.ultralytics.com/python/ -> Predict -> From Source, it is in indicated that when using the SDK images which contain annotations of bounding box and confidence can be created if the supplied source is a PIL.Image. 

```
from ultralytics import YOLO
from PIL import Image
import cv2

model = YOLO("model.pt")
# accepts all formats - image/dir/Path/URL/video/PIL/ndarray. 0 for webcam
results = model.predict(source="0")
results = model.predict(source="folder", show=True) # Display preds. Accepts all YOLO predict arguments

# from PIL
im1 = Image.open("bus.jpg")
results = model.predict(source=im1, save=True)  # save plotted images

# from ndarray
im2 = cv2.imread("bus.jpg")
results = model.predict(source=im2, save=True, save_txt=True)  # save predictions as labels

# from list of PIL/ndarray
results = model.predict(source=[im1, im2])
```

In the CLI version this annotated image is created if you supply a URL to a jpg as source e.g. 
```
 yolo predict model=yolov8n.pt source="https://ultralytics.com/images/bus.jpg" save_txt=True save_conf=True save_crop=True classes=0
```
Is there a way to get annotated images from the SDK without wrapping it in a a PIL.Image first? 

It would be great if the directory could be passed as an argument and an option for the creation of images was present.

**Comment by alexandercronin** [comment]
It appears that I should have paid more attention to the documentation. 

See https://docs.ultralytics.com/predict/ in the "Plotting results" section 

you can simply make an image using the result object and the cv2 library. This will show the image, the bounding box, the object label and the confidence.  

```
res = model(img)
res_plotted = res[0].plot()
cv2.imshow("result", res_plotted)
```

**Comment by pderrenger** [comment]
@alexandercronin you're absolutely right! 😊 The `plot()` method from the result object along with the `cv2` library enables you to easily create an annotated image directly without needing to wrap it in a PIL.Image first. This allows you to display the image, bounding boxes, object labels, and confidences using the result object. Thank you for sharing this helpful information!
