### ISSUE TITLE
Yolov8 seems to use both trackers at the same time?

### ISSUE THREAD

**Issue by MrWei282** [ultralytics/ultralytics#7614]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am using yolov8 detection&tracking in combination with some reid components, and I need to rewrite the code so I can change the tracking id after people reenters a camera, I can use reid program to detect its the same identity as to certain certain individual appeared before, who have already been assigned a tracking_id to), as yolov8 often just reassigns a new tracking_id to an individual it doesnt recognise. 
And when I was tring to implement such feature, I was having trouble understanding the logic of how yolov8 use trackers. I got to stream_inference in predictor.py and got quite confused. So I tried to use print function to trace how the program goes, I put print("bot") in bot_sort.py's update function and "print("byte")" in byte_tracker.py's update function, and to my surprise the terminal outputs "bot" and "byte" in alternation repetitively. I am not sure if this is intended or a bug.

For more context, the video path is a rtsp stream,
I use "results = model.track(video_path, persist=True, stream=True, stream_buffer=False, classes=[0], verbose=False, vid_stride=1, device=0)" and "for result in results" to let yolov8 track human in the stream

**Comment by glenn-jocher** [comment]
@MrWei282 hello! It's great to see you're integrating YOLOv8 tracking with re-identification (ReID) components. YOLOv8's tracking functionality is designed to be robust, but it's understandable that you might want to modify the tracking IDs based on ReID to maintain identity consistency.

Regarding the use of multiple trackers, YOLOv8 is indeed capable of utilizing different tracking algorithms, which can be selected based on the task requirements. The alternating "bot" and "byte" prints you're observing suggest that both SORT and ByteTrack trackers might be getting called in sequence. This could be part of the logic to leverage the strengths of both trackers, but without seeing the specific code, it's hard to provide a definitive answer.

If you're looking to customize the tracking ID assignment, you might need to delve deeper into the tracking logic and potentially override or modify the tracker update functions to incorporate your ReID matching. This can be a complex task, but it's certainly feasible with a good understanding of both the tracking and ReID algorithms.

For more detailed information on how tracking is implemented in YOLOv8, you can refer to the Track mode documentation. If you have further questions or need more clarification, feel free to reach out to the community on our discussions page. Good luck with your project! 😊

**Comment by MrWei282** [comment]
I see, I havent modified the tracker functions(or any parts in relation to track/predict) though and I am running yolov8 with version 8.0.229 if it helps. I also tried to select tracker with "tracker='./ultralytics/cfg/trackers/botsort.yaml' as an argument in model.track() but it would still call for update function with both bot_sort and byte_tracker and it confuses me why the program is behaving as such.
![Weixin Image_20240117091631](https://github.com/ultralytics/ultralytics/assets/108318437/2ee060a1-099b-401f-829d-384bfd45d520)
![Weixin Image_20240117091636](https://github.com/ultralytics/ultralytics/assets/108318437/2b3910a9-3012-4d8b-b1b3-50294b75e4c1)

**Comment by MrWei282** [comment]
Also checked the tracker.md but it seems the document just goes over how to use of trackers but not much explanations on how the tracking logic is implemented in yolov8

**Comment by MrWei282** [comment]
Ok I have delve a bit deeper into the code and find a possible bug(or that I just havent figure out how the tracker works)
![Weixin Image_20240117105244](https://github.com/ultralytics/ultralytics/assets/108318437/b8a95cf3-3d87-4b06-b1f5-e28c5bdf9df3)
So tracks = predictor.trackers[i].update(det, im0s[i]) in track.py calls for the update function in byte_tracker.py first, but oddly enough the update function would then call for the update function in bot_sort.py and leaving me lil confused.

This behaviour is consistent whether I put "tracker='./ultralytics/cfg/trackers/botsort.yaml'" in model.track() or not

**Comment by glenn-jocher** [comment]
@MrWei282, it sounds like you've encountered unexpected behavior with the tracker selection in YOLOv8. If specifying the tracker configuration through `model.track()` does not isolate the tracker to either ByteTrack or BotSort as intended, this could indeed indicate a bug or a configuration issue within the tracking logic.

The behavior you're describing, where both `byte_tracker.py` and `bot_sort.py` update functions are called regardless of the specified tracker, is not expected. The tracker should adhere to the configuration provided, and if it doesn't, this warrants further investigation.

I recommend raising this as an issue on the GitHub repository with the details you've provided, including the version number (8.0.229) and your observations. The development team will be able to look into this more closely and provide a fix or clarification on the tracker's behavior.

Thank you for bringing this to our attention, and we appreciate your efforts in improving YOLOv8. Your detailed feedback is invaluable to the community and helps us enhance the robustness of the models and tracking logic.
