### ISSUE TITLE
Trying to get the accuracy per image

### ISSUE THREAD

**Issue by JBurtonBarr** [ultralytics/ultralytics#7615]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Currently when I run the validation for ultralytics it returns the accuracy across the whole dataset. However, I need the accuracy for each individual image (my current project requires this for coloration with image features), is there any way to do this?

Thanks :)

**Comment by glenn-jocher** [comment]
@JBurtonBarr hello! 😊

For obtaining accuracy on a per-image basis during validation with YOLOv8, you would need to modify the validation code to save the results for each image separately. This isn't a feature provided out-of-the-box, as the standard validation process aggregates statistics over the entire dataset to provide overall metrics.

If you're comfortable with diving into the code, you can look into the validation function and adjust it to log the desired metrics for each image. The results would then need to be stored in a structured format, such as a CSV or JSON file, for your analysis.

For more details on the validation process, you can refer to our documentation on the Val mode. Keep in mind that any modifications to the code would be specific to your project's needs and would require a good understanding of the codebase.

Good luck with your project! If you have further questions or need assistance, feel free to reach out.
