### ISSUE TITLE
Why is there a massive speedup when not acessing inference results

### ISSUE THREAD

**Issue by WHBSmith** [ultralytics/ultralytics#7619]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to do pose estimation on a video with yolov8n. I have two simple approaches to do this (shown below), the first one gets 'N' frames per second, the second also gets 'N' frames per second, however when I don't 'access' the results in the second approach there is a an FPS increase of 5x, but doing the same in the first approach results in no FPS gain. I believe this behaviour is linked to the stream argument in the predict mode because setting it to False in the second approach removes this speedup. For more details see commented code below. I therefore have several questions:

- Why does this behaviour exist?
- Is there some way to access the results while maintaining this much faster FPS number?
- Do the FPS numbers quoted on this repository include accessing the results?

Any answers appreciated, thank you!

Approach 1:

```
import statistics
import time
from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n-pose.pt")

n = 0
times = []

prev_time = time.time()

# Perform inference on video
for results in model.predict("./people.mp4", stream=True, verbose=False):

    if n < 100:
        # 'Access' results
        # Commenting the following two lines out results in no FPS increase
        for r in results:
            pass
        
        # Skip first frame because it is very slow and skews results
        if n > 0:
            times.append(time.time() - prev_time)
        prev_time = time.time()
        n += 1

    else:
        break
 
# Calculate FPS
print(1 / statistics.mean(times))
```

Approach 2
```
import statistics
import time
import cv2
from ultralytics import YOLO 

# Load a model
model = YOLO("yolov8n-pose.pt")

# Load video
cap = cv2.VideoCapture("./people.mp4")
if cap.isOpened() == False:
    print("Error opening video stream or file")

n = 0
times = []

while True:

    prev_time = time.time()
    ret, frame = cap.read()
    
    # Perform inference on each video frame
    if ret == True and n < 100:
        results = model.predict(source=frame, device=0, verbose=False, stream=True)
  
        # 'Access' results
        # Commenting the following two lines out results in a 5x FPS increase
        for result in results:
            pass

        # Skip first frame because it is very slow and skews results
        if n > 0:
            times.append(time.time() - prev_time)
        prev_time = time.time()
        n += 1

    else:
        break
 
# Calculate FPS
print(1 / statistics.mean(times))
```

**Comment by glenn-jocher** [comment]
@WHBSmith hello! Thanks for reaching out with your observations on the inference speed.

The behavior you're noticing is related to how the Python Global Interpreter Lock (GIL) works. When you don't access the results, Python can optimize away the GIL acquisition, which can lead to a significant speedup, especially in multi-threaded environments. This is likely why you see a speed increase when you don't access the results.

Accessing the results introduces overhead as each result must be processed and the GIL must be acquired for each operation, which can slow down the overall inference speed.

The FPS numbers quoted in our repository are typically measured without accessing the results to showcase the maximum throughput of the model. However, in real-world applications, you would need to access the results for further processing, which would reduce the FPS.

To maintain a higher FPS while accessing results, you could look into optimizing your post-processing pipeline, using batched inference if possible, or leveraging multiprocessing to handle result processing in parallel with inference.

I hope this clarifies your questions! If you need further assistance, feel free to reach out. Happy coding! 😊

**Comment by WHBSmith** [comment]
Thank you so much for your helpful reply, that's really appreciated, I just have two follow up questions. 

Given this slow down is caused by the GIL would you recommend multi-processing over multi-threading to help increase the FPS while accessing the results?

FPS in this case is reduced to a fifth of its original value, would you say this reduction can be applied to the FPS numbers quoted by this repository when considering accessing the results?

**Comment by glenn-jocher** [comment]
You're welcome, @WHBSmith!

1. Yes, multi-processing can often bypass the GIL limitations and may increase FPS when accessing results, as each process has its own memory space and GIL.

2. The reduction to a fifth is specific to your case and may not directly apply to the FPS numbers quoted by the repository. The actual reduction when accessing results can vary based on the complexity of the post-processing and the system used.

Keep experimenting and optimizing for the best performance in your specific use case! 😊
