### ISSUE TITLE
Export trained model to multiple formats at once

### ISSUE THREAD

**Issue by rkabealo** [ultralytics/ultralytics#7623]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello! I have just started using YoloV8 and do not see anywhere in the documentation an option to export a trained model to multiple formats, for example "onnx" AND "engine", via a single command. It appears that the "format" parameter in the configuration file only takes in a string. The ability to export to multiple different formats in a single pass was a feature in YoloV5's export functionality. I am curious whether it is really here or not. If it is present in YoloV8, may I please have an example of how to do so?

**Comment by glenn-jocher** [comment]
@rkabealo hello! Thanks for reaching out with your question. In YOLOv8, the export functionality is designed to handle one format at a time. This is to ensure clarity and simplicity in the export process. If you need to export your trained model to multiple formats, you would need to run the export command separately for each format you're interested in. While this may not be as convenient as exporting to multiple formats in a single pass, it does provide you with the flexibility to handle each format individually and ensure each export process is tailored to the specific requirements of that format. For detailed guidance on how to use the export mode, please refer to our documentation on the Export mode. 😊🚀
