### ISSUE TITLE
About train

### ISSUE THREAD

**Issue by ziyaxuanyi** [ultralytics/ultralytics#763]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

 I have trained yolov8m-seg on my dataset. My dataset has 4 classes. I used all default training parameters.
It works well and mask map50 is about 0.52 on both train and val dataset at last.

but when I only change the training imgz to 960(default:640), it doesn't seem to converge.
The mask map50 is only about 0.15 on both train and val dataset at last.

What are the possible reasons？Should I modify some training parameters？
How to solve this problem?

**Comment by ziyaxuanyi** [comment]
well, I seem to find the problem.

The first train, it will generate the dataset cache: train.cache and val.cache.
Then second train, it will use the cache file to use

When I delete the cache,then it works normally.

**Comment by pderrenger** [comment]
@ziyaxuanyi glad to hear you found the issue! 😊 It seems that when you changed the training image size, the cache file from the previous train impacted the convergence. Deleting the cache and retraining resolved the problem. If you encounter any more issues, feel free to reach out!
