### ISSUE TITLE
Yolov8 .pt model to FP32, INT8 IR conversion

### ISSUE THREAD

**Issue by AshishRaghani23** [ultralytics/ultralytics#7631]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I've used YOLOv8 classification model to train and test custom classification model. After training the model, when I test the .pt model it gives proper results but FP32, FP16 and INT8 models don't give proper predictions. 

### Minimal Reproducible Example

from ultralytics import YOLO

model = YOLO("best.pt")

model.export(format="openvino", half=True, int=True)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AshishRaghani23** [comment]
![Screenshot 2024-01-17 134419](https://github.com/ultralytics/ultralytics/assets/98545345/72897de0-699d-477a-904b-1c19ce600557)

I got this error for INT8 IR conversion.
@glenn-jocher

**Comment by glenn-jocher** [comment]
@AshishRaghani23 hello! It seems you're encountering issues with exporting your trained YOLOv8 classification model to different precision formats. When exporting to OpenVINO formats such as FP32, FP16, and INT8, it's important to ensure that the environment is correctly set up with all necessary dependencies and that the model is compatible with the desired precision.

For INT8 quantization, additional calibration steps are typically required to maintain accuracy. This process involves using a representative dataset to fine-tune the quantization parameters. If these steps are not followed, it could lead to the poor performance you're experiencing.

Please refer to our documentation on the Export mode for detailed instructions on how to properly export your model to different formats and precision levels. If the issue persists after following the documentation, consider opening an issue on our GitHub repository with the full error log and details about your environment for further assistance. 🛠️

Remember, the community and the Ultralytics team are here to help!

**Comment by AshishRaghani23** [comment]
@glenn-jocher Thank you for your response. I have refer to Export mode for detailed instructions. But it don't give instructions for INT8 conversion. Would really like to have some more clarity and references for same.

**Comment by glenn-jocher** [comment]
@AshishRaghani23, I'm glad you've checked the Export mode documentation. For INT8 quantization, it's a more complex process that requires a calibration step with a representative dataset. Unfortunately, detailed instructions for INT8 conversion are beyond the scope of our current documentation.

I recommend reviewing OpenVINO's documentation on model optimization and INT8 calibration for guidance. If you encounter specific issues related to YOLOv8 during this process, please feel free to open a detailed issue on our GitHub repository, and we'll do our best to assist you. Thank you for your understanding and for being part of the YOLO community! 🌟

**Comment by AshishRaghani23** [comment]
@IrDIE Thank you for sharing. Will look into it and do let you know.
