### ISSUE TITLE
Specify the model, but have to download the model again

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#7635]
```python
from ultralytics import YOLO

# Load a model
model = YOLO( r"E:\Detect\yolov8n.pt")  # load a pretrained model (recommended for training)

# Train the model
results = model.train(data='coco128.yaml', epochs=100, imgsz=640)

```

```
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Downloading https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8n.pt to 'yolov8n.pt'...
⚠️ Download failure, retrying 1/3 https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8n.pt...
```

I have specified a model

Why do we still need to download the model？

How to Not Download Models？

If it is necessary to load the default
Or specify a default model directory?
This allows for offline operations

Can I specify a directory
Load model

**Comment by glenn-jocher** [comment]
@monkeycc hello! It seems like you're trying to load a local model but the system is still attempting to download it. This can happen if the path to the local model is incorrect or the file is not found. Please ensure that the path to your `.pt` file is correct and the file exists at that location. If the path is correct and the file is present, the model should load without attempting to download. If you continue to face issues, please check our documentation for further guidance on model loading and training. 📘🚀
