### ISSUE TITLE
Async Training Callbacks

### ISSUE THREAD

**Issue by mario-dg** [ultralytics/ultralytics#7641]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey everybody,
I'm developing a training server that uses gRPC as the backend.
I want to leverage the possibility to add custom callbacks to the training loop to send training metrics to my own gRPC client to create graphs comparable to Weights & Biases. 
For my Server-Streaming RPC I need to use await to send a response back to client (happens in one of the callback).
Unfortunately this doesn't seem to be possible, since async callbacks are not awaited, leading to no response being sent.

Am I overseeing something or might there be a better solution to send the metrics back to my client?

**Comment by glenn-jocher** [comment]
@mario-dg, it sounds like you're facing a complex challenge integrating multiprocessing with YOLOv8's training loop. While the model and training process are not designed with built-in support for passing custom attributes like a multiprocessing queue, your approach of modifying the training loop is on the right track.

If you're unable to modify the BaseTrainer to include the queue as an attribute, consider using a different inter-process communication (IPC) method that doesn't rely on passing the queue directly to the model or trainer. For instance, you could use a Manager from the `multiprocessing` library to create a server process that manages shared objects, which can be accessed by different processes.

Another option could be to use a database or a file-based logging system where the training process writes the metrics, and your main process reads from it asynchronously.

Remember, any custom modifications to handle asynchronous operations will need careful handling to ensure thread safety and data integrity.

Keep exploring the possibilities, and I'm confident you'll find a solution that fits your setup. Your efforts to extend YOLOv8's functionality are commendable. Keep up the good work! 👍🔧

**Comment by mario-dg** [comment]
For anyone having a similar problem, I finally found a solution!
You can view it in the repository or as a short summary:

Create a custom Trainer that has the specified existing Trainer as the base class.
In the constructor of the trainer pop the needed payload (in my example a Queue) from the overrides dict before calling the super constructor, otherwise the [check_dict_alignment](https://github.com/ultralytics/ultralytics/blob/a2222b428376e9207915caf848e523be7b7f080e/ultralytics/cfg/__init__.py#L210) will raise a SyntaxError.
To pass any payload to the trainer, just specify it as a kwarg to the model.train() function call.

```python
class CustomDetectionTrainer(DetectionTrainer):
    def __init__(self, cfg=DEFAULT_CFG, overrides=None, _callbacks=None):
        self.progress_queue = overrides.pop("progress_queue", None)
        super().__init__(cfg, overrides, _callbacks)

...

model = YOLO("yolov8m.pt")
model.train(CustomDetectionTrainer, data="data.yaml", epochs=15, device=0, progress_queue=progress_queue)
```
Now you can access the progress_queue in the callbacks.

**Comment by glenn-jocher** [comment]
@mario-dg, fantastic to hear you've resolved the issue! Your solution of creating a custom Trainer class and popping the payload from the overrides dictionary is a clever way to integrate additional functionality without disrupting the existing training process. This approach of passing the queue as a keyword argument to `model.train()` is a neat trick that others in the community may find useful. Thanks for sharing your findings, and best of luck with your project! 🎉👨‍💻
