### ISSUE TITLE
How to load and run a predict task on YOLO with a TensorRT ".engine" model without CLI?

### ISSUE THREAD

**Issue by uniquadev** [ultralytics/ultralytics#7644]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello! I am currently encountering an issue while attempting to load and forward an exported .engine model without utilizing the CLI, (CLI which work properly). Below is the code where I am trying to load and subsequently run the model with a numpy array image:

```py
def predict(model:YOLO, img:np.ndarray) -> YoloResults:
    cimg = cvtColor(img, COLOR_RGBA2RGB)
    return model.predict(
        source=cimg,
        # settings
        verbose=False,
        conf=0.30,
        classes=[1],
        max_det=10,
        amp=True,
        imgsz=736,
        device=0
    )[0]

def load_model():
    return YOLO(MODEL_PATH, task='detect').cuda(0) # MODEL_PATH = bestv8.engine
```
However I'm getting the following TypeError message:
```
TypeError: model='C:\Repository\epic\model/bestv8.engine' should be a *.pt PyTorch model to run this method, but is a different format. PyTorch models can train, val, predict and export, i.e. 'model.train(data=...)', but exported formats like ONNX, TensorRT etc. only support 'predict' and 'val' modes, i.e. 'yolo predict model=yolov8n.onnx'.
To run CUDA or MPS inference please pass the device argument directly in your inference command, i.e. 'model.predict(source=..., device=0)'
```
> NOTE: my code work fine when loading and running my pytorch model

Env:
- os: win 11
- python: 3.9
- tensorrt: 8.4.1.5
- torch: 2.0.1+cu118
- torchvision: 0.15.2+cu118
- ultralytics: 8.1.2

My bestv8.engine model has been exported through the following CLI command:
`yolo export model=bestv8.pt format=engine half=True imgsz=736`
And I tested it correctly with this CLI command:
`yolo predict task=detect model=bestv8.engine imgsz=736 half source=...`

I would like to inquire whether it's possible to execute predictions without relying on the CLI. Thank you in advance!

**Comment by glenn-jocher** [comment]
@uniquadev hello! It looks like you're trying to load a TensorRT `.engine` file directly in Python, which isn't supported by the `YOLO` class as it expects a PyTorch `.pt` model. To run predictions with a `.engine` model, you'll need to use the TensorRT Python API directly. The `YOLO` class and associated methods are designed to work with PyTorch models, which allow for training, validation, prediction, and export tasks.

For running predictions with a TensorRT `.engine` file, you'll need to handle the loading and inference process manually using TensorRT's Python bindings. This involves creating a TensorRT runtime, deserializing the engine, and managing the input and output buffers for inference.

Please refer to the TensorRT documentation for guidance on how to perform these steps. If you need further assistance, our documentation at https://docs.ultralytics.com might provide additional insights into the process. Good luck with your project! 😊

**Comment by Burhan-Q** [comment]
@uniquadev I have found that this works well:

```py
from ultralytics import YOLO

model = YOLO("path/to/model.engine", task="detect")

results = model.predict("path/to/source") # The device gets selected automatically
```

I tried specifying the device using `model.to("cuda")` and got the same error you shared, so I'd recommend trying without.

**Comment by uniquadev** [comment]
Thank you!! I ended up using the yolov8 AutoBackend to load and then forward the model, I'm surprised that this simple thing broke my old code :/

**Comment by glenn-jocher** [comment]
@uniquadev Glad to hear you've resolved the issue using the AutoBackend! Changes in the codebase can sometimes lead to unexpected behavior in existing code. If you encounter any more issues or have questions, feel free to reach out. Happy coding! 😊
