### ISSUE TITLE
prdict not predicting segment gives same images without any prediction.

### ISSUE THREAD

**Issue by hanumanraje** [ultralytics/ultralytics#765]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i have train model on custom dataset for segmentation, its training well. all train batch images shows segments but val predict not predicting any results same for test data not predicting any segment.

i am using polygon annotation for segmentation

**Comment by pderrenger** [comment]
@hanumanraje hi there! It sounds like you've trained a YOLOv8 model on a custom dataset for segmentation, but you're experiencing issues with prediction. When you mention that the validation and test predictions are not showing any segments, it could be related to the format of your annotation or the configuration settings during training and prediction.

For segmentation tasks, make sure to check that your polygon annotation format aligns with the expected input for YOLOv8. Additionally, verifying that the model is loaded properly and the prediction parameters are correctly set might also help resolve this issue.

If you've verified these aspects and the problem persists, let's check the training and prediction configurations to ensure they align with the segmentation task requirements.

Feel free to provide additional details about your training and prediction setup, and I'd be happy to assist further! 🤖
