### ISSUE TITLE
when I use model to predict and set stream = True, how can I get the Processed images

### ISSUE THREAD

**Issue by 4everImmortality** [ultralytics/ultralytics#7654]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

`
 ```
   def run(self):
        vid = cv2.VideoCapture(self.vid_path)
        self.model = YOLO(self.model)
        while vid.isOpened() and not self._stop_event:
            success, frame = vid.read()
            if success:
                if self.active_mode:
                    res = self.model(frame, verbose=False)
                    ann = res[0].plot()
                    # Calculate FPS
                    self.cal_fps()
                    # Put the FPS text on the frame top-left corner
                    cv2.putText(ann, f"FPS: {round(self.fps, 2)}", (0, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255),
                                2)
                    cv2.putText(ann, f"Object detected in {self.window_name}!", (0, 45), cv2.FONT_HERSHEY_SIMPLEX, 0.8,
                                (0, 255, 0), 2)
                    # Put the processed frame into the rendering queue
                    self.render_queue.put(ann)
                else:
                    # Put the original frame into the rendering queue
                    self.render_queue.put(frame)
            else:
                self.stop()
                vid.release()
                break
            # press to stop
            if cv2.waitKey(1) & 0xFF == ord('q'):
                self.stop()
                break
        vid.release()
```

`
`

    def run(self):
        self.model = YOLO(self.model)
        result = self.model.predict(self.vid_path, show=False, verbose=False, stream=True)
        for res in result:
            if self.active_mode:
                # gain original image
                ann = res.orig_img
                # Calculate FPS
                self.cal_fps()
                # Put the FPS text on the frame top-left corner
                cv2.putText(ann, f"FPS: {round(self.fps, 2)}", (0, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255),
                            2)
                cv2.putText(ann, f"Object detected in {self.window_name}!", (0, 45), cv2.FONT_HERSHEY_SIMPLEX, 0.8,
                            (0, 255, 0), 2)
                # Put the processed frame into the rendering queue
                self.render_queue.put(ann)
            else:
                # Put the original frame into the rendering queue
                self.render_queue.put(res.orig_img)
            if self._stop_event:
                break

`
    when I use OpenCV to read video frame and use yolov8 to predict, I found that it has a very low fps cause I know the bottleneck is in my use of OpenCV(it uses low memory). So I read the docs and use the second style use more memory and 2 times faster to predict, however, it seem that I can not get processed image from result when i use stream = True.

**Comment by 4everImmortality** [comment]
well it is my fault
just user res.plot() to get processed image

**Comment by glenn-jocher** [comment]
@4everImmortality no worries at all! You've got it right. When using `stream=True`, you can indeed call `res.plot()` on each result object to get the processed image with the annotations. This method will return the image with the drawn predictions, which you can then use as needed in your application. Keep up the great work, and if you have any more questions, feel free to reach out! 😊👍
