### ISSUE TITLE
How custom trained pose model work?

### ISSUE THREAD

**Issue by VM8198** [ultralytics/ultralytics#7663]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello @glenn-jocher 

I've trained a custom pose model for Yoga poses detection. I wanted to know how this work. What should I give the model as an input? Would that be an image or the keypoints? 

I'm confused here because at the time of training we are providing labels as keypoints than how an image as an input would it recognize which pose is it?

Let me explain it with an example. Suppose I've trained custom model with Warrior Pose with arount 500 images and it's keypoints. Now at the time of inference if I provide an image to it than how it will recognize that which type of pose is it? Or how should I know that the pose is correct or not. Or I have to provide the keypoints as an input. 

Can you please clarify this? Thanks.

**Comment by VM8198** [comment]
Thanks @glenn-jocher for your reply. So, that means to get the correct pose I have to compare the keypoints right? What I did is created a class for warrior pose and than train it. so, after the inference will it directly give me the identified pose or I have to compare the predicted keypoints with correct one?

**Comment by glenn-jocher** [comment]
@VM8198, after inference, your model will directly provide the identified keypoints for the pose in the image. There's no need for you to manually compare keypoints; the model's output will indicate the pose it has recognized based on the training it received. If you've trained it with a class for the Warrior Pose, it will attempt to predict the keypoints of that pose when presented with a new image. 😊

**Comment by VM8198** [comment]
Understood. Thanks @glenn-jocher

**Comment by glenn-jocher** [comment]
You're welcome, @VM8198! If you have any more questions, feel free to ask. Happy posing! 🧘‍♂️✨
