### ISSUE TITLE
Cropping detected image

### ISSUE THREAD

**Issue by Bhargav230m** [ultralytics/ultralytics#7664]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey, i was working on a project. License Plate detection, But i think i have run into a problem.
I did find one question similar to this but that didn't help me out!

So, to detect the license plates i am using a custom training yolov8 model and easyOcr to extract text. I have a probem i wanted to crop the detections. So i can preprocess it better and provide it to easyOcr for better detections. But i can't find any methods to crop the detection.

My current code to do this

```python
import cv2 as cv
from ultralytics import YOLO
from ultralytics.utils.plotting import Annotator
import easyocr
import json

model = YOLO("./dec.pt")

source = "./test.jpg" #Add a camera (using 0) or specify a source
image = cv.imread(source)
results = model.predict(image, stream=True)

for r in results:
    data_string = r.tojson()
    data_json = json.loads(data_string)
    data = data_json[0]["box"]
    image[int(data["x2"]):int(data["x1"]), int(data["y2"]):int(data["y1"])]
    cv.imshow("Content", image)
    cv.waitKey(0)

reader = easyocr.Reader(['en'])
result = reader.readtext(e)
```

I thought this would work, but it didn't. It just shows the full image, Please help me fix this

### Additional

It would be really helpfull how to fix this.

If you want to run the code yourself. You should have a yolov8 model and a image and link the path to your model and image in the code and see

**Comment by Burhan-Q** [comment]
@Bhargav230m check out the [docs guide on object cropping](https://docs.ultralytics.com/guides/object-cropping/), the [prediction argument `save_crops`](https://docs.ultralytics.com/modes/predict/#inference-arguments), and [working with results](https://docs.ultralytics.com/modes/predict/#working-with-results). You can also join our [Discord server](https://ultralytics.com/discord) where you can find others who might be able to help you troubleshoot issues or figure out how to accomplish your intended outcome.

**Comment by Bhargav230m** [comment]
okay mate, thanks for the help.

**Comment by glenn-jocher** [comment]
@Bhargav230m you're welcome! If you have any more questions or need further assistance, feel free to reach out. Happy coding! 😊👍

**Comment by farukalamai** [comment]
> @Bhargav230m you're welcome! If you have any more questions or need further assistance, feel free to reach out. Happy coding! 😊👍

Hey, how can crop object for specific class?

**Comment by Burhan-Q** [comment]
@farukalamai you can use an `if` statement with the class value returned with `boxes` in the results, or you can filter _all_ detections using the `classes` argument with the `predict()` method. See the [Working with Results](https://docs.ultralytics.com/modes/predict/#working-with-results) and [Inference Arguments](https://docs.ultralytics.com/modes/predict/#inference-arguments) sections of the docs for additional details.

**Comment by farukalamai** [comment]
> @farukalamai you can use an `if` statement with the class value returned with `boxes` in the results, or you can filter _all_ detections using the `classes` argument with the `predict()` method. See the [Working with Results](https://docs.ultralytics.com/modes/predict/#working-with-results) and [Inference Arguments](https://docs.ultralytics.com/modes/predict/#inference-arguments) sections of the docs for additional details.

Thank you!

**Comment by farukalamai** [comment]
> @farukalamai you can use an `if` statement with the class value returned with `boxes` in the results, or you can filter _all_ detections using the `classes` argument with the `predict()` method. See the [Working with Results](https://docs.ultralytics.com/modes/predict/#working-with-results) and [Inference Arguments](https://docs.ultralytics.com/modes/predict/#inference-arguments) sections of the docs for additional details.

I have another question, like how can I crop those images without drawing the bounding box?

**Comment by glenn-jocher** [comment]
You're welcome, @farukalamai! If you need more help, just let us know. Happy to assist! 😊🚀
