### ISSUE TITLE
yolov8 obb onnx cpp  demo

### ISSUE THREAD

**Issue by ldepn** [ultralytics/ultralytics#7667]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I can‘t  find the demo in YOLOv8-ONNXRuntime-CPP of the obb
I try to export the model of yolov8s_obb to onnx, and run with cpp. I  modify the code of YOLOv8-ONNXRuntime-CPP for obb.
But the results is error.

**Comment by ldepn** [comment]
I export ONNX with yolov8s-obb.pt download from https://docs.ultralytics.com/tasks/obb/#models. The export code is
`from ultralytics import YOLO

pt_file = r'D:\data\code\DOTAv1.5\yolov8s-obb.pt'
# Load a model
# model = YOLO('yolov8n-obb.pt')  # load an official model
model = YOLO(pt_file)  # load a custom trained model

# Export the model
model.export(format='onnx',imgsz=640)`
And run the example in YOLOv8-ONNXRuntime-CPP

The result show error.
as follows
![Uploading 20240118233125.png…]()

**Comment by glenn-jocher** [comment]
@ldepn hello! It seems like you're trying to export a YOLOv8 model with oriented bounding box (OBB) support to ONNX and then run it using a C++ demo. If you're encountering errors, it's important to ensure that the C++ code is compatible with the OBB output format of the model. The YOLOv8-ONNXRuntime-CPP demo is designed for standard axis-aligned bounding boxes, so modifications would be necessary to handle OBB.

Please double-check the following:
1. Ensure that the ONNX model has been exported correctly with the correct input size and model weights.
2. Verify that the C++ code has been adapted to parse the OBB output, which includes additional parameters for orientation and extent compared to regular bounding boxes.

If the issue persists, please provide specific error messages and descriptions of the steps you've taken. This will help us better understand the problem and assist you further. For more detailed guidance on OBB, you can refer to our documentation on oriented bounding boxes. 📘

Remember, the community and the Ultralytics team are here to help!

**Comment by ldepn** [comment]
1.Ensure that the ONNX model has been exported correctly with the correct input size and model weights.

The onnx open with netron show as:
![20240119065917](https://github.com/ultralytics/ultralytics/assets/15522634/0adb91c3-e4f4-4180-942e-60a377aaf564)
2. Verify that the C++ code has been adapted to parse the OBB output, which includes additional parameters for orientation and extent compared to regular bounding boxes.
I modify the c++ code to parse the OBB output as follows：
`
template<typename N>
char* YOLO_V8::TensorProcess(clock_t& starttime_1, cv::Mat& iImg, N& blob, std::vector<int64_t>& inputNodeDims,
    std::vector<DL_RESULT>& oResult)
{
    Ort::Value inputTensor = Ort::Value::CreateTensor<typename std::remove_pointer<N>::type>(
        Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU), blob, 3 * imgSize.at(0) * imgSize.at(1),
        inputNodeDims.data(), inputNodeDims.size());
#ifdef benchmark
    clock_t starttime_2 = clock();
#endif // benchmark
    auto outputTensor = session->Run(options, inputNodeNames.data(), &inputTensor, 1, outputNodeNames.data(),
        outputNodeNames.size());
#ifdef benchmark
    clock_t starttime_3 = clock();
#endif // benchmark

    Ort::TypeInfo typeInfo = outputTensor.front().GetTypeInfo();
    auto tensor_info = typeInfo.GetTensorTypeAndShapeInfo();
    std::vector<int64_t> outputNodeDims = tensor_info.GetShape();
    auto output = outputTensor.front().GetTensorMutableData<typename std::remove_pointer<N>::type>();
    delete[] blob;
    switch (modelType)
    {
    case YOLO_DETECT_V8:
    case YOLO_DETECT_V8_HALF:
    {
        int strideNum = outputNodeDims[2];//8400
        int signalResultNum = outputNodeDims[1];//20
        std::vector<int> class_ids;
        std::vector<float> confidences;
        std::vector<cv::Rect> boxes;
        cv::Mat rawData;
        if (modelType == YOLO_DETECT_V8)
        {
            // FP32
            rawData = cv::Mat(strideNum, signalResultNum, CV_32F, output);
        }
        else
        {
            // FP16
            rawData = cv::Mat(strideNum, signalResultNum, CV_16F, output);
            rawData.convertTo(rawData, CV_32F);
        }
        //Note:
        //ultralytics add transpose operator to the output of yolov8 model.which make yolov8/v5/v7 has same shape
        //https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8n.pt
        //rowData = rowData.t();

        float* data = (float*)rawData.data;

        for (int i = 0; i < strideNum; ++i)
        {
            float* classesScores = data + 4;
            float angle = data[signalResultNum - 1];

            cv::Mat scores(1, this->classes.size(), CV_32FC1, classesScores);
            cv::Point class_id;
            double maxClassScore;
            cv::minMaxLoc(scores, 0, &maxClassScore, 0, &class_id);
            if (maxClassScore > rectConfidenceThreshold)
            {
                confidences.push_back(maxClassScore);
                class_ids.push_back(class_id.x);
                float x = data[0];
                float y = data[1];
                float w = data[2];
                float h = data[3];

                int left = int((x - 0.5 * w) * resizeScales);
                int top = int((y - 0.5 * h) * resizeScales);

                int width = int(w * resizeScales);
                int height = int(h * resizeScales);

                boxes.push_back(cv::Rect(left, top, width, height));
            }
            data += signalResultNum;
        }
        std::vector<int> nmsResult;
        cv::dnn::NMSBoxes(boxes, confidences, rectConfidenceThreshold, iouThreshold, nmsResult);
        for (int i = 0; i < nmsResult.size(); ++i)
        {
            int idx = nmsResult[i];
            DL_RESULT result;
            result.classId = class_ids[idx];
            result.confidence = confidences[idx];
            result.box = boxes[idx];
            oResult.push_back(result);
        }

#ifdef benchmark
        clock_t starttime_4 = clock();
        double pre_process_time = (double)(starttime_2 - starttime_1) / CLOCKS_PER_SEC * 1000;
        double process_time = (double)(starttime_3 - starttime_2) / CLOCKS_PER_SEC * 1000;
        double post_process_time = (double)(starttime_4 - starttime_3) / CLOCKS_PER_SEC * 1000;
        if (cudaEnable)
        {
            std::cout << "[YOLO_V8(CUDA)]: " << pre_process_time << "ms pre-process, " << process_time << "ms inference, " << post_process_time << "ms post-process." << std::endl;
        }
        else
        {
            std::cout << "[YOLO_V8(CPU)]: " << pre_process_time << "ms pre-process, " << process_time << "ms inference, " << post_process_time << "ms post-process." << std::endl;
        }
#endif // benchmark

        break;
    }
    case YOLO_CLS:
    {
        DL_RESULT result;
        for (int i = 0; i < this->classes.size(); i++)
        {
            result.classId = i;
            result.confidence = output[i];
            oResult.push_back(result);
        }
        break;
    }
    default:
        std::cout << "[YOLO_V8]: " << "Not support model type." << std::endl;
    }
    return RET_OK;

}
`
The results show as 
![20240119070742](https://github.com/ultralytics/ultralytics/assets/15522634/4ff7cbc1-30a8-4131-87b0-8230429d7550)

**Comment by glenn-jocher** [comment]
@ldepn it looks like you've made an effort to adapt the C++ code for OBB output. The error in the results suggests there might be an issue with how the output data is being interpreted. Here are a few concise steps to troubleshoot:

1. Confirm the output layer format from the ONNX model matches the expected format in your C++ code.
2. Ensure that the parsing of the OBB data (orientation, width, height, etc.) aligns with the output tensor's structure.
3. Check for any discrepancies in the pre-processing or post-processing steps that might affect the output.

If the problem persists, consider providing a clear description of the error and the output you're receiving. This will help us pinpoint the issue more effectively. Keep in mind that handling OBB requires careful alignment between the model's output and the post-processing code. 🛠️

**Comment by ldepn** [comment]
The code is here
[code.zip](https://github.com/ultralytics/ultralytics/files/13983679/code.zip)
the onnx file and the pt file in here.
[https://1drv.ms/f/s!AjQdReWl4ccMdM8bXvCD0p6RyZg?e=1OOa8j](url)

**Comment by LemonWang0110** [comment]
@ldepn The post-processing of the code is clearly incorrect, one needs to rotate the horizontal prediction box according to the angle and then go for the NMS operation of rotating the box.It is recommended that the relevant work be dealt with after clarification.

**Comment by ldepn** [comment]
> @ldepn The post-processing of the code is clearly incorrect, one needs to rotate the horizontal prediction box according to the angle and then go for the NMS operation of rotating the box.It is recommended that the relevant work be dealt with after clarification.

I think NMS  operation  is not very important. If the output tensor has no problem, the bbox will not concentrated in the upper left corner. And the confidence value of class is not  greater than 1. I find the confidence value of class is very large, more 100.

**Comment by ldepn** [comment]
I run this example [https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-CPP-Inference], the result is show right.
when export onnx, the code is 
```
from ultralytics import YOLO

pt_file = r'D:\data\yaohe\part_all\cpp_demo\best.pt'
# Load a model
# model = YOLO('yolov8n-obb.pt')  # load an official model
model = YOLO(pt_file)  # load a custom trained model

# Export the model
model.export(format='onnx',imgsz=[480,640],opset=12)
```

**Comment by glenn-jocher** [comment]
@ldepn It's great to hear that the example provided in the YOLOv8-CPP-Inference is working correctly for you. When exporting your model to ONNX, the code snippet you've provided seems appropriate for a custom trained model. If you're experiencing issues with the confidence values being greater than 1, this could indicate a problem with the model's output processing in the C++ code.

Please ensure that the output tensor is being interpreted correctly, and that the confidence scores are being scaled appropriately. It's also important to verify that the model's output format is consistent with the expectations of your post-processing code. If the Python inference is correct, then the issue likely lies within the C++ post-processing logic rather than the ONNX export.

If you need further assistance, please provide a clear description of the error and the output you're receiving, and we'll do our best to help you resolve the issue.

**Comment by ZeonlungPun** [comment]
> I run this example [https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-CPP-Inference], the result is show right. when export onnx, the code is
> 
> ```
> from ultralytics import YOLO
> 
> pt_file = r'D:\data\yaohe\part_all\cpp_demo\best.pt'
> # Load a model
> # model = YOLO('yolov8n-obb.pt')  # load an official model
> model = YOLO(pt_file)  # load a custom trained model
> 
> # Export the model
> model.export(format='onnx',imgsz=[480,640],opset=12)
> ```

what does it 

> I run this example [https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-CPP-Inference], the result is show right. when export onnx, the code is
> 
> ```
> from ultralytics import YOLO
> 
> pt_file = r'D:\data\yaohe\part_all\cpp_demo\best.pt'
> # Load a model
> # model = YOLO('yolov8n-obb.pt')  # load an official model
> model = YOLO(pt_file)  # load a custom trained model
> 
> # Export the model
> model.export(format='onnx',imgsz=[480,640],opset=12)
> ```

what does it mean? this code is for horizontal object detection ,not for oriented object detection,and the c++ code your provided is also abviously for   horizontal object detection

**Comment by glenn-jocher** [comment]
@ZeonlungPun it appears there's a misunderstanding regarding the model's capabilities and the corresponding C++ code. The code snippet you've provided is indeed for exporting a model trained for horizontal object detection, not oriented object detection (OBB). If you're attempting to work with OBB, you'll need to ensure that both the model and the C++ inference code are compatible with oriented bounding boxes. The C++ code you've mentioned is not designed for OBB and will require significant modifications to handle the additional angle parameter and perform the correct NMS operation for rotated boxes. Please review your model and code to align them with the task of oriented object detection. 🔄

**Comment by ZeonlungPun** [comment]
the problem i have met is that the NMS do not work at all. After NMS, there is still huge amount of bounding boxs (for 20000+ to 2000+); at the same time , the class score (propability of object exceed 1):
void porcess_with_one_image(std::string& onnxpath,cv::Mat& frame,float modelinput_height, float modelinput_width)
{
    float modelScoreThreshold=0.9;
    float modelNMSThreshold=0.2;
    // load the onnx model 
    auto net = cv::dnn::readNetFromONNX(onnxpath);
    net.setPreferableBackend(cv::dnn::DNN_BACKEND_OPENCV);
    net.setPreferableTarget(cv::dnn::DNN_TARGET_CPU);

    //image preprocess
    int w = frame.cols;
    int h = frame.rows;
    int _max = std::max(h, w);
    cv::Mat image = cv::Mat::zeros(cv::Size(_max, _max), CV_8UC3);
    cv::Rect roi(0, 0, w, h);
    frame.copyTo(image(roi));

    float x_factor = image.cols / modelinput_width;
    float y_factor = image.rows / modelinput_height;

    // inference using model
    cv::Mat blob;
    cv::dnn::blobFromImage(image,blob,1 / 255.0, cv::Size(modelinput_height, modelinput_width), cv::Scalar(), true, false);
    net.setInput(blob);
    std::vector<cv::Mat> outputs;
    net.forward(outputs, net.getUnconnectedOutLayersNames());

    // postprocess the image 
    // yolov8-obb has an output of shape (batchSize, 15,  21504) ( box[x,y,w,h,theta]+Num classes=15 )
    int rows = outputs[0].size[2]; //21504
    int dimensions =outputs[0].size[1]; //20
    std::cout<<"rows is:"<<rows<<std::endl;
    std::cout<<"dim is:"<<dimensions<<std::endl;

    //(1,15,21504)-->(15,21504)
    outputs[0] = outputs[0].reshape(1, dimensions);
    //(15,21504) --> (21504,15)
    cv::transpose(outputs[0], outputs[0]);

    //get the first data pointer;finaaly will get all 21504 bounding box
    float *data = (float *)outputs[0].data;

    // the storage to save the results
    
    //std::vector<RotatedBOX> boxes;
    std::vector<cv::RotatedRect> boxes;
    std::vector<float> confidences;

    //rows stand for the total number of bounding box
    for (int i = 0; i < rows; ++i)
    {
        RotatedBOX BOX;
        //skip the x,y,w,h,theta
        float *classes_scores = data+5;

        cv::Mat scores(1, class_names.size(), CV_32FC1, classes_scores);
        cv::Point class_id;
        double maxClassScore;

        minMaxLoc(scores, 0, &maxClassScore, 0, &class_id);
        cout<<maxClassScore<<endl;

        if (maxClassScore > modelScoreThreshold)
        {
           

            float x = data[0]* x_factor;
            float y = data[1]* y_factor;
            float w = data[2]* x_factor;
            float h = data[3]* y_factor;
            // between [-pi/4,3/4 pi)
            float angle=data[4];
          
        
            if (angle >= 0.5*pi && angle<0.75*pi)
            {
                //[-pi/4,3/4 pi) --》 [-pi/2,pi/2)
                angle=angle-pi;
            }
            
            if (angle>=-pi/2 && angle<0)
            {
                continue;
            }
            else
            {
                // [-pi/2,pi/2) --> [-pi/2,0)
                angle=angle-pi/2;
                float temp;
                temp=w;
                w=h;
                h=temp;
            }
            //[-pi/2,0) --> (-pi/2,0]
            if (angle==-pi/2)
            {
                angle=0;
            }
            //rad to degree
            //angle=angle*180/pi;

            cv:RotatedRect box=cv::RotatedRect(Point2f(x, y), Size2f(w, h), angle);
            BOX.box=box;
            BOX.Classindex=class_id.x;
            BOX.score=maxClassScore;
            
            boxes.push_back(box);
            confidences.push_back(maxClassScore);


           
        }
        
        
        //pointer to next 15  group
        data += dimensions;
        
    }


    //rotatedbox NMS
    
    
    //nms_angle(boxes,modelNMSThreshold);
    std::vector<int> indices;
    cv::dnn::NMSBoxes(boxes, confidences,modelScoreThreshold, modelNMSThreshold, indices)

       
    cout<<boxes.size()<<endl;
    cout<<indices.size()<<endl;




}

**Comment by ldepn** [comment]
> the problem i have met is that the NMS do not work at all. After NMS, there is still huge amount of bounding boxs (for 20000+ to 2000+); at the same time , the class score (propability of object exceed 1):
> 
> `void porcess_with_one_image(std::string& onnxpath,cv::Mat& frame,float modelinput_height, float modelinput_width) { float modelScoreThreshold=0.9; float modelNMSThreshold=0.2; // load the onnx model auto net = cv::dnn::readNetFromONNX(onnxpath); net.setPreferableBackend(cv::dnn::DNN_BACKEND_OPENCV); net.setPreferableTarget(cv::dnn::DNN_TARGET_CPU);
> 
> ```
> //image preprocess
> int w = frame.cols;
> int h = frame.rows;
> int _max = std::max(h, w);
> cv::Mat image = cv::Mat::zeros(cv::Size(_max, _max), CV_8UC3);
> cv::Rect roi(0, 0, w, h);
> frame.copyTo(image(roi));
> 
> float x_factor = image.cols / modelinput_width;
> float y_factor = image.rows / modelinput_height;
> 
> // inference using model
> cv::Mat blob;
> cv::dnn::blobFromImage(image,blob,1 / 255.0, cv::Size(modelinput_height, modelinput_width), cv::Scalar(), true, false);
> net.setInput(blob);
> std::vector<cv::Mat> outputs;
> net.forward(outputs, net.getUnconnectedOutLayersNames());
> 
> // postprocess the image 
> // yolov8-obb has an output of shape (batchSize, 15,  21504) ( box[x,y,w,h,theta]+Num classes=15 )
> int rows = outputs[0].size[2]; //21504
> int dimensions =outputs[0].size[1]; //20
> std::cout<<"rows is:"<<rows<<std::endl;
> std::cout<<"dim is:"<<dimensions<<std::endl;
> 
> //(1,15,21504)-->(15,21504)
> outputs[0] = outputs[0].reshape(1, dimensions);
> //(15,21504) --> (21504,15)
> cv::transpose(outputs[0], outputs[0]);
> 
> //get the first data pointer;finaaly will get all 21504 bounding box
> float *data = (float *)outputs[0].data;
> 
> // the storage to save the results
> 
> //std::vector<RotatedBOX> boxes;
> std::vector<cv::RotatedRect> boxes;
> std::vector<float> confidences;
> 
> //rows stand for the total number of bounding box
> for (int i = 0; i < rows; ++i)
> {
>     RotatedBOX BOX;
>     //skip the x,y,w,h,theta
>     float *classes_scores = data+5;
> 
>     cv::Mat scores(1, class_names.size(), CV_32FC1, classes_scores);
>     cv::Point class_id;
>     double maxClassScore;
> 
>     minMaxLoc(scores, 0, &maxClassScore, 0, &class_id);
>     cout<<maxClassScore<<endl;
> 
>     if (maxClassScore > modelScoreThreshold)
>     {
>        
> 
>         float x = data[0]* x_factor;
>         float y = data[1]* y_factor;
>         float w = data[2]* x_factor;
>         float h = data[3]* y_factor;
>         // between [-pi/4,3/4 pi)
>         float angle=data[4];
>       
>     
>         if (angle >= 0.5*pi && angle<0.75*pi)
>         {
>             //[-pi/4,3/4 pi) --》 [-pi/2,pi/2)
>             angle=angle-pi;
>         }
>         
>         if (angle>=-pi/2 && angle<0)
>         {
>             continue;
>         }
>         else
>         {
>             // [-pi/2,pi/2) --> [-pi/2,0)
>             angle=angle-pi/2;
>             float temp;
>             temp=w;
>             w=h;
>             h=temp;
>         }
>         //[-pi/2,0) --> (-pi/2,0]
>         if (angle==-pi/2)
>         {
>             angle=0;
>         }
>         //rad to degree
>         angle=angle*180/pi;
> 
>         cv:RotatedRect box=cv::RotatedRect(Point2f(x, y), Size2f(w, h), angle);
>         BOX.box=box;
>         BOX.Classindex=class_id.x;
>         BOX.score=maxClassScore;
>         
>         boxes.push_back(box);
>         confidences.push_back(maxClassScore);
> 
> 
>        
>     }
>     
>     
>     //pointer to next 15  group
>     data += dimensions;
>     
> }
> 
> 
> //rotatedbox NMS
> 
> 
> //nms_angle(boxes,modelNMSThreshold);
> std::vector<int> indices;
> cv::dnn::NMSBoxes(boxes, confidences,modelScoreThreshold, modelNMSThreshold, indices)
> 
>    
> cout<<boxes.size()<<endl;
> cout<<indices.size()<<endl;
> ```
> 
> }`
float angle=data[class_names.size()-1];
maybe export onnx has error.

**Comment by glenn-jocher** [comment]
@ldepn, if you're experiencing issues with NMS not filtering out enough bounding boxes and class scores exceeding 1, it's likely that there's a problem with the post-processing logic in your C++ code. Here are a few things to check:

1. Verify that the confidence scores are being calculated correctly before NMS is applied.
2. Ensure that the NMS threshold is set appropriately to filter out overlapping boxes.
3. Confirm that the class scores are being interpreted correctly from the model's output.

If the class scores are indeed greater than 1, this suggests that the output from the ONNX model is not being processed correctly. Double-check the model's output format and ensure that your code is handling it properly. If the issue persists, you may need to revisit the ONNX export process to ensure that the model is exporting correctly, especially if the ONNX model is expected to handle oriented bounding boxes (OBB).

**Comment by ZeonlungPun** [comment]
I have yet solved this problem successfully. The main problem is that the output of yolov8 exported onnx model is [batch_size,20,21504] ,and 
21504×20  =128×128×20+64×64×20+32×32×20
=128×128×(4+15+1)+64×64×(4+15+1)+32×32×(4+15+1),
where 4 is center point ,width ,height ; 15 is probability of different objects , and the angle is 1 (at the last dimension).

the main process of the c++ code is :

`std::vector<RotatedBOX> detect_one_image(const cv::Mat &input_image,std::vector<std::string>& classes,cv::dnn::Net& net)
{
    cv::Mat modelInput = input_image;
    modelInput = formatToSquare(modelInput);
    cv::Mat blob;
    cv::dnn::blobFromImage(modelInput, blob, 1.0/255.0, cv::Size {640, 640}, cv::Scalar(), true, false);
    net.setInput(blob);

    std::vector<cv::Mat> outputs;
    net.forward(outputs, net.getUnconnectedOutLayersNames());

    int rows = outputs[0].size[2];
    int dimensions = outputs[0].size[1];
    cout<<"r:"<<rows<<endl;
    cout<<"d:"<<dimensions<<endl;
    outputs[0] = outputs[0].reshape(1, dimensions);
    cv::transpose(outputs[0], outputs[0]);
    float *data = (float *)outputs[0].data;

    float x_factor = modelInput.cols / 640.0;
    float y_factor = modelInput.rows / 640.0;

   
    std::vector<cv::RotatedRect> boxes;
    std::vector<RotatedBOX>BOXES;
    std::vector<float> confidences;

    for (int i = 0; i < rows; ++i)
    {
        float *classes_scores = data+4;
        cv::Mat scores(1, classes.size(), CV_32FC1, classes_scores);
        cv::Point class_id;
        double maxClassScore;
        minMaxLoc(scores, 0, &maxClassScore, 0, &class_id);
        RotatedBOX BOX;
        
        if (maxClassScore > modelScoreThreshold)
        {
            confidences.push_back(maxClassScore);  
            float x = data[0]* x_factor;
            float y = data[1]* y_factor;
            float w = data[2]* x_factor;
            float h = data[3]* y_factor;

            float angle=data[dimensions-1];
            //angle in [-pi/4,3/4 pi) --》 [-pi/2,pi/2)
            if (angle>=pi && angle <= 0.75*pi)
            {
                angle=angle-pi;
            } 

            BOX.Classindex=class_id.x;
            BOX.score=maxClassScore; 
            cv::RotatedRect box=cv::RotatedRect(cv::Point2f(x,y),cv::Size2f(w,h),angle*180/pi);
            BOX.box=box;
            boxes.push_back(box);
            BOXES.push_back(BOX);
                
        }
        data += dimensions;
    }
    cout<<boxes.size()<<endl;
    //postprocess
    std::vector<int> nms_result;
    cv::dnn::NMSBoxes(boxes, confidences, modelScoreThreshold, modelNMSThreshold, nms_result);
    cout<<nms_result.size()<<endl;
    std::vector<RotatedBOX> Remain_boxes;
    for (unsigned long i = 0; i < nms_result.size(); ++i)
    {
        int idx = nms_result[i];
        RotatedBOX Box_=BOXES[idx];
        Remain_boxes.push_back(Box_);
    }

    return Remain_boxes;
    
}`
​
 And the complete code is on my github using opencv 4.8: https://github.com/ZeonlungPun/YoloDeploymentWithOnnxruntimeAndOpencv/blob/main/yolov8obbOPENCV/yolov8obb.cpp

if you think my code is helpful ,please give me a star.
the onnxruntime version will be coming soon. Thans you guys for helping me !

**Comment by glenn-jocher** [comment]
I'm glad to hear you've successfully resolved the problem, @ZeonlungPun. It looks like you've done a thorough job understanding the output structure of the YOLOv8 model and adapting your C++ code to handle the oriented bounding boxes correctly. Your contribution to the community by sharing your code is appreciated, and it's great to see active collaboration and support within the YOLO community. Keep up the good work, and I'm sure others will find your repository useful. Best of luck with your onnxruntime version! 🌟👍

**Comment by ZeonlungPun** [comment]
my complete onnxruntime 1.16.3 code in Linux system:https://github.com/ZeonlungPun/YoloDeploymentWithOnnxruntimeAndOpencv/tree/main/onnxruntimeYOLOV8OBB

**Comment by glenn-jocher** [comment]
@ZeonlungPun, it's fantastic to see you've implemented YOLOv8 OBB with ONNX Runtime 1.16.3 on Linux and shared it with the community. Your initiative to contribute is highly valuable. Thank you for your efforts, and I encourage those interested in ONNX Runtime deployment to check out your repository. 🚀👏

**Comment by ARCHANGELOVE** [comment]
Hi just a quick question when i try to run the script in my windows visual studio i face an error as an assertion handler is this my opencv version problem or the network

[ INFO:0@1.053] global c:\build\master_winpack-build-win64-vc15\opencv\modules\core\src\utils\plugin_loader.impl.hpp (67) cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_openmp460_64d.dll => FAILED
OpenCV(4.6.0) Error: Assertion failed (start <= (int)shape.size() && end <= (int)shape.size() && start <= end) in cv::dnn::dnn4_v20220524::total, file c:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\include\opencv2\dnn\shape_utils.hpp, line 171

**Comment by ZeonlungPun** [comment]
> Hi just a quick question when i try to run the script in my windows visual studio i face an error as an assertion handler is this my opencv version problem or the network
> 
> [ INFO:0@1.053] global c:\build\master_winpack-build-win64-vc15\opencv\modules\core\src\utils\plugin_loader.impl.hpp (67) cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_openmp460_64d.dll => FAILED OpenCV(4.6.0) Error: Assertion failed (start <= (int)shape.size() && end <= (int)shape.size() && start <= end) in cv::dnn::dnn4_v20220524::total, file c:\build\master_winpack-build-win64- vc15\opencv\modules\dnn\include\opencv2\dnn\shape_utils.hpp, line 171
> 
> > opencv_world460d.dll!cv::dnn::dnn4_v20220524::total(const std::vector<int,std::allocator> & shape, int start, int end) Line 170	C++
> 
> at first i thought the blob size problem but when i check it the output was(1,3,640,640) which suite the input of the network shape need some hand over here ![image](https://private-user-images.githubusercontent.com/103873237/362186864-0391da81-16c4-4766-9bc0-f2401fa0a294.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTI4NDAsIm5iZiI6MTcyNDg5MjU0MCwicGF0aCI6Ii8xMDM4NzMyMzcvMzYyMTg2ODY0LTAzOTFkYTgxLTE2YzQtNDc2Ni05YmMwLWYyNDAxZmEwYTI5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwMDQ5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODlkOTI0NTEwM2QyYWQzNWFjMzExMWFhOGI2MzdhMDhkM2E3ZjRlZTc5NTdmYmMyNjdiNDg0NGE0OTUwNTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gd3pLWk_14G609Hn4QOcEIqe44ZyaFk-SOCY5LUQxQ4)

you may try at least opencv 4.8; lower version doesn't support loading the onnx model

**Comment by glenn-jocher** [comment]
@ZeonlungPun please try using OpenCV 4.8 or later, as earlier versions may not support loading the ONNX model correctly.

**Comment by mosamar** [comment]
Will the same code work for yolo 11n obb ?

**Comment by glenn-jocher** [comment]
Yes, the same code should work for YOLO11n OBB with adjustments for the output format and post-processing specific to oriented bounding boxes. Ensure you handle the additional angle parameter appropriately in your inference pipeline.

**Comment by glenn-jocher** [comment]
The network output shape `(1,12,21504)` suggests 12 parameters per detection, likely including `[x, y, w, h, angle, class probabilities...]`. To handle this, you would:

1. Parse `x, y, w, h` for the bounding box, `angle` for rotation, and the remaining values for class probabilities.
2. Use a softmax function on the class probabilities to normalize them.
3. Perform NMS considering the rotated bounding boxes (including the angle).

Ensure your inference pipeline is updated for YOLO11-OBB-specific outputs. For more details, refer to the [YOLO11 OBB documentation](https://docs.ultralytics.com/tasks/obb/).

**Comment by mosamar** [comment]
> The network output shape `(1,12,21504)` suggests 12 parameters per detection, likely including `[x, y, w, h, angle, class probabilities...]`. To handle this, you would:
> 
> 1. Parse `x, y, w, h` for the bounding box, `angle` for rotation, and the remaining values for class probabilities.
> 2. Use a softmax function on the class probabilities to normalize them.
> 3. Perform NMS considering the rotated bounding boxes (including the angle).
> 
> Ensure your inference pipeline is updated for YOLO11-OBB-specific outputs. For more details, refer to the [YOLO11 OBB documentation](https://docs.ultralytics.com/tasks/obb/).

Thanks a lot for detail. However in my case the following is the row output 

`
Row Value [210.81755, 115.39537, 271.55103, 66.269661, 4.1484833e-05, 1.8358231e-05, 4.7087669e-05, 5.5193901e-05, 2.1576881e-05, 1.4305115e-06, 2.5033951e-06, 1.469698]
Row Value [226.84813, 121.15681, 263.86276, 117.4715, 1.013279e-05, 6.1988831e-06, 1.502037e-05, 3.4451485e-05, 9.4175339e-06, 5.9604645e-07, 7.1525574e-07, 0.80072117]
Row Value [240.16782, 120.72007, 236.64917, 147.86389, 7.7486038e-06, 6.1988831e-06, 5.1259995e-06, 1.3589859e-05, 4.2915344e-06, 3.5762787e-07, 7.1525574e-07, 0.85299277]
Row Value [257.60675, 121.29781, 242.65808, 182.2253, 6.7949295e-06, 4.2915344e-06, 4.4107437e-06, 1.0371208e-05, 2.2649765e-06, 2.3841858e-07, 4.7683716e-07, 0.93772876]
Row Value [275.33032, 123.25716, 232.77536, 231.36435, 4.6491623e-06, 5.364418e-06, 2.6226044e-06, 5.4836273e-06, 1.1920929e-06, 1.1920929e-07, 2.3841858e-07, 0.57261282]
`

Could you suggest if the values look ok?

**Comment by glenn-jocher** [comment]
The output values you provided look mostly correct for a YOLO OBB task, where `[x, y, w, h, angle, class probabilities...]` are expected. However, it seems the **angle** parameter is not directly apparent in your rows—this could imply either the angle is encoded differently or there's an issue with the ONNX export or inference pipeline. The confidence scores (e.g., `0.93772876` in the last column) and class probabilities do appear valid.

To proceed:
1. Confirm the **angle** (likely in radians) is correctly extracted if it's part of the output.
2. Verify your ONNX model architecture matches the expected output format for YOLO11-OBB.
3. Ensure proper post-processing, including softmax for class probabilities and NMS for rotated bounding boxes.

Refer to the [YOLO11 OBB documentation](https://docs.ultralytics.com/tasks/obb/) for further clarification on the expected output structure.

**Comment by mosamar** [comment]
> The output values you provided look mostly correct for a YOLO OBB task, where `[x, y, w, h, angle, class probabilities...]` are expected. However, it seems the **angle** parameter is not directly apparent in your rows—this could imply either the angle is encoded differently or there's an issue with the ONNX export or inference pipeline. The confidence scores (e.g., `0.93772876` in the last column) and class probabilities do appear valid.
> 
> To proceed:
> 
> 1. Confirm the **angle** (likely in radians) is correctly extracted if it's part of the output.
> 2. Verify your ONNX model architecture matches the expected output format for YOLO11-OBB.
> 3. Ensure proper post-processing, including softmax for class probabilities and NMS for rotated bounding boxes.
> 
> Refer to the [YOLO11 OBB documentation](https://docs.ultralytics.com/tasks/obb/) for further clarification on the expected output structure.

Thanks again. The class probabilities are more than 1.0. Do you think that is valid? I've followed the above thread and modelled the pipeline but still the class probabilities are greater than 1? Any suggestions?

**Comment by glenn-jocher** [comment]
Class probabilities or confidence scores exceeding 1 are not valid and suggest a problem in post-processing or the model export pipeline. Ensure that the class probabilities are normalized using a softmax function, and verify the integrity of the ONNX export process to match the expected output format of YOLO11-OBB. If the issue persists, consider re-exporting the model or debugging the inference pipeline for discrepancies. For more details, refer to the [YOLO11 OBB documentation](https://docs.ultralytics.com/tasks/obb/).
