### ISSUE TITLE
Feature Request: Add export_type property to benchmark

### ISSUE THREAD

**Issue by kadirnar** [ultralytics/ultralytics#7668]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I just want to test the torchscript model. I do not want other export formats.

### Use case

```
from ultralytics.utils.benchmarks import benchmark

# Benchmark on GPU
benchmark(model='weights\yolov8m_1280_75_epoch.pt', data='data.yaml', imgsz=1280, half=False, device=0, model_type=torchscipt)   
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kadirnar thank you for the feature request! We appreciate your interest in enhancing the benchmarking capabilities of YOLOv8. Your suggestion to add an `export_type` property to the benchmark function, allowing users to specify the model format they wish to test, is a valuable one. This would indeed streamline the process for users who are only interested in benchmarking a particular export format like TorchScript.

We'll consider this for future updates. If you or anyone else is willing to contribute to this feature, we welcome pull requests. Your feedback helps us improve, and we're grateful for your involvement in the YOLO community! 🚀
