### ISSUE TITLE
Using the test dataset

### ISSUE THREAD

**Issue by Rafaelca70x** [ultralytics/ultralytics#7671]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How is the test dataset, which is placed in the .yaml file, used during network training? I couldn't find any information about this in the documentation, only that it is optional. Is it used in conjunction with validation as well?

**Comment by glenn-jocher** [comment]
@Rafaelca70x hello! The test dataset specified in the `.yaml` file is not used during the training process of YOLOv8. It's optional and is intended for evaluating the model after training is complete. The primary datasets used during training are the training and validation datasets. The validation dataset is used to monitor the model's performance and to perform hyperparameter tuning. If you include a test dataset, you can use it after training to assess the model's generalization to new, unseen data. For more details on how datasets are used in different modes, please refer to our documentation on [Train](https://docs.ultralytics.com/modes/train) and [Val](https://docs.ultralytics.com/modes/val) modes. 😊
