### ISSUE TITLE
Albumentations in yolov8-obb (8.1.1)

### ISSUE THREAD

**Issue by rkinas** [ultralytics/ultralytics#7672]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Augmentation

### Bug

Albumentations geometrical transformation (e.g. RandomRotate90) do not work. in Albumentations Yolo box tansformation format is implemented which is different from OBB. As a result, boxes are not transferred correctly.

```self.transform = A.Compose(T, bbox_params=A.BboxParams(format="yolo", label_fields=["class_labels"]))```

I realize that this is an external library, but I am letting you know in order to introduce information in the documentation that this kind of augmentation will not function properly.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@rkinas thank you for bringing this to our attention. We acknowledge the issue with Albumentations' geometrical transformations not correctly handling the OBB format in YOLOv8-obb. We appreciate your suggestion and will consider updating our documentation to reflect this limitation. Your input is valuable to the community, and we aim to provide the most accurate information possible. If you have further insights or suggestions, please feel free to share. 📚🛠️
