### ISSUE TITLE
Slow training on NVIDIA A100 with yolov8.1

### ISSUE THREAD

**Issue by bog** [ultralytics/ultralytics#7673]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I don't have specific output or space to provide this before next week, but wanted to share our experience.

I have tested training the same dataset of about 2300 images using both yolov8.1.2 and yolov8.0.200. When training using a batch size of 16 with 100 epochs, it took over 24 hours to train the dataset on yolov8.1.2. Only downgrading to yolov8.0.200, training takes on the order of 4 hours and there is a visible difference watching the process in `nvtop`.

Happy to gather more real data on this next week.

### Environment

```
yolo checks
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.0.7) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Ultralytics YOLOv8.0.200 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (NVIDIA A10G, 22513MiB)
Setup complete ✅ (4 CPUs, 15.4 GB RAM, 67.6/96.7 GB disk)

OS                  Linux-6.2.0-1017-aws-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 15.43 GB
CPU                 AMD EPYC 7R32
CUDA                12.1

matplotlib          ✅ 3.8.1>=3.3.0
numpy               ✅ 1.26.1>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.25.1>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 2.1.0>=1.8.0
torchvision         ✅ 0.16.0>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.1.2>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
```

### Minimal Reproducible Example

I'm happy to try and come up with this if it helps, but do not have time to do so until next week at the earliest.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by bog** [comment]
A reboot of the system involved may be addressing this. Will update with more details if not.

**Comment by glenn-jocher** [comment]
@bog great to hear that a system reboot might be resolving the issue. If the problem persists, please gather more detailed information when convenient, and we'll be happy to look into it further. Your insights are valuable to the YOLO community and the continuous improvement of YOLOv8. 😊👍
