### ISSUE TITLE
[Question] Can the pose tasks without rectangle boxes?

### ISSUE THREAD

**Issue by whysirier** [ultralytics/ultralytics#7677]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to only give some points to models without rectangle boxes, the yolov8-pose also can run ? thanks

**Comment by glenn-jocher** [comment]
@whysirier yes, YOLOv8 supports pose/keypoint estimation tasks which can provide points without the need for bounding boxes. The pose estimation functionality will detect specific keypoints on objects, which is useful for tracking movement or estimating poses. For more details on how to use this feature, please refer to the Pose/Keypoint Estimation section in our documentation. 😊👍

**Comment by whysirier** [comment]
> @whysirier yes, YOLOv8 supports pose/keypoint estimation tasks which can provide points without the need for bounding boxes. The pose estimation functionality will detect specific keypoints on objects, which is useful for tracking movement or estimating poses. For more details on how to use this feature, please refer to the Pose/Keypoint Estimation section in our documentation. 😊👍

well done, thank u

**Comment by glenn-jocher** [comment]
You're welcome, @whysirier! If you have any more questions or need further assistance as you work with pose estimation, feel free to reach out. Happy coding! 😄🚀

**Comment by whysirier** [comment]
> You're welcome, @whysirier! If you have any more questions or need further assistance as you work with pose estimation, feel free to reach out. Happy coding! 😄🚀

If I remove the class, it has the errors. So the pose task must run with at least class and points?
![Uploading 企业微信截图_20240123150350.png…]()

**Comment by whysirier** [comment]
> You're welcome, @whysirier! If you have any more questions or need further assistance as you work with pose estimation, feel free to reach out. Happy coding! 😄🚀
![企业微信截图_20240123150350](https://github.com/ultralytics/ultralytics/assets/142364107/5f50120b-913f-4ceb-9b63-ca7f54df869e)

If I remove the class, it has the errors. So the pose task must run with at least class and points?

**Comment by glenn-jocher** [comment]
@whysirier yes, for pose estimation tasks, YOLOv8 requires at least one class label along with the keypoints. The class label is necessary for the model to associate the detected keypoints with a specific object category. If you remove the class label, the model won't be able to perform the task correctly, which leads to errors. Make sure to include class labels in your dataset for successful pose estimation. 😊👌

**Comment by whysirier** [comment]
> @whysirier yes, for pose estimation tasks, YOLOv8 requires at least one class label along with the keypoints. The class label is necessary for the model to associate the detected keypoints with a specific object category. If you remove the class label, the model won't be able to perform the task correctly, which leads to errors. Make sure to include class labels in your dataset for successful pose estimation. 😊👌

In my tasks, the rectangle boxes is not important,  so I paint optionally will cause the performance of the pose estimation? For results, I find the pose estimation is not well.

**Comment by glenn-jocher** [comment]
@whysirier, the bounding boxes are not critical for pose estimation, but consistent and accurate keypoint annotations are essential. Inconsistent bounding box annotations should not significantly impact pose estimation performance as long as the keypoints are correctly labeled. If you're experiencing suboptimal results, it could be due to other factors such as the quality of the keypoint annotations or the training data itself. Ensure your keypoints are accurately and consistently annotated for the best pose estimation results. 😊🎯
