### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by SivaBodapati** [ultralytics/ultralytics#7683]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I want to print Accuracy for the trained mode 
Accuracy: 0.90836372672 
provide code for this .......................................

### Use case

![o](https://github.com/ultralytics/ultralytics/assets/126906353/f8f9f820-d55b-4c22-8e19-e1df06ace79c)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@SivaBodapati hello! To print the accuracy of your trained YOLOv8 model, you can use the `Val` mode which will evaluate the model on the validation dataset and provide you with various metrics including precision, recall, and mAP (mean Average Precision). The accuracy metric, as commonly referred to in classification tasks, is analogous to the mAP in object detection tasks.

After running the validation, you'll see the mAP score displayed in the terminal, which represents the model's accuracy over the entire validation dataset. For a detailed breakdown of performance metrics, you can refer to the results saved in the `runs/val` directory, which includes a `results.csv` file containing all the metrics.

For more information on how to use the `Val` mode and interpret the results, please visit our documentation on the Val mode. Keep in mind that while we don't use the term "Accuracy" explicitly for object detection tasks, mAP is the standard metric for evaluating the performance of models like YOLOv8. 😊📊
