### ISSUE TITLE
Data set annotation

### ISSUE THREAD

**Issue by Adam4444444** [ultralytics/ultralytics#7685]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, may I ask how to mark the data set of custom target detection so that the training segment model can be trained?

**Comment by glenn-jocher** [comment]
@Adam4444444 👋 Hi there,

For labeling your custom dataset for object detection with YOLOv8, you should annotate your images in a format that is compatible with the model. Typically, this involves drawing bounding boxes around the objects of interest in each image and assigning a class label to each box.

The annotation format usually includes:
- One annotation file per image.
- Each line in an annotation file corresponds to one bounding box, with the format `class x_center y_center width height`, normalized to the image size.

Make sure to follow the guidelines in the Docs for preparing your dataset, and ensure that your annotations are accurate to get the best training results. Happy training! 🚀
