### ISSUE TITLE
RT-DETR

### ISSUE THREAD

**Issue by waangyuhai** [ultralytics/ultralytics#7687]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why is the FPS of RT-DETR so low? It does not meet the requirements for real-time detection.

**Comment by glenn-jocher** [comment]
@waangyuhai hello! The FPS of RT-DETR can vary based on several factors such as the complexity of the model, the resolution of the input data, the hardware it's running on, and the level of optimization. RT-DETR is designed with a focus on balancing accuracy and speed, but it may not reach the high FPS of less complex models on all systems. For real-time detection requirements, you might want to consider using a lighter model or optimizing your setup. Check out our documentation on Benchmark mode for profiling different models and Export mode for optimizing model deployment. If you need further assistance, feel free to reach out! 😊
