### ISSUE TITLE
Triton Inference is slow when client does not have access to a GPU

### ISSUE THREAD

**Issue by cesarandreslopez** [ultralytics/ultralytics#7695]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I've followed the procedure to export a standard YOLOv8 model into ONNX Format as described here:

https://docs.ultralytics.com/guides/triton-inference-server/#prerequisites

It runs fine but seems very slow (taking over a second per inference when other models work much faster).

The bottleneck, though, does not seem to be on Triton itself. Here are the metrics from Triton, where every inference takes about 0.10 seconds or so ( 2072014 us / 20 requests).

```
  "yolov8l": {
    "nv_inference_request_success": 20,
    "nv_inference_request_failure": 0,
    "nv_inference_count": 20,
    "nv_inference_exec_count": 20,
    "nv_inference_request_duration_us": 2072014,
    "nv_inference_request_duration_s_per_inference": 0.103601,
    "nv_inference_queue_duration_us": 2270,
    "nv_inference_queue_duration_s_per_inference": 0.000113,
    "nv_inference_compute_input_duration_us": 25124,
    "nv_inference_compute_input_duration_s_per_inference": 0.001256,
    "nv_inference_compute_infer_duration_us": 2014037,
    "nv_inference_compute_infer_duration_s_per_inference": 0.100702,
    "nv_inference_compute_output_duration_us": 8063,
    "nv_inference_compute_output_duration_s_per_inference": 0.000403,
    "nv_cache_num_hits_per_model": 0,
    "nv_cache_hit_lookup_duration_per_model": 0,
    "nv_cache_num_misses_per_model": 0,
    "nv_cache_miss_lookup_duration_per_model": 0,
    "nv_cache_miss_insertion_duration_per_model": 0
  },
  ```

However, counting the time spent from the client side takes quite a long time. Here is the code that I am using.  Note that MODEL_INFERENCE_GRPC is the URL towards the docker container running triton, and model_name is "yolov8l" as mounted into triton.

```
    my_url = MODEL_INFERENCE_GRPC + model_name
    # Load the Triton Server model
    start_time = time.time()
    model = YOLO(my_url, task="detect")
    logging.info(f"Time taken for line 1: {time.time() - start_time} seconds")
    start_time = time.time()
    results = model(img)
    logging.info(f"Time taken for line 2: {time.time() - start_time} seconds")
```
The results are as follows:

```
Time taken for line 1: 0.00015354156494140625 seconds
0: 640x640 1 class0, 1 class27, 42.1ms
Speed: 1.9ms preprocess, 42.1ms inference, 0.5ms postprocess per image at shape (1, 3, 640, 640)
Time taken for line 2: 1.1901066303253174 seconds
```

In particular, the line:

```
results = model(img)
```

Is reporting 1.20 seconds, while triton and the Yolo ms inference time will report much less.

I've also tested it against the REST Triton endpoint, with similar speeds.

I don't believe that the added time is just network latency, as I have other models also running on Triton being called with much more consistency in times reported by Triton vs. times seen by the client (using triton_client.Client)

.

### Environment

Client machine (which has a docker with no access to GPU)

```
Ultralytics YOLOv8.1.2 🚀 Python-3.10.12 torch-2.1.2+cu121 CPU (AMD Ryzen 7 5800H with Radeon Graphics)
Setup complete ✅ (16 CPUs, 31.2 GB RAM, 742.9/837.3 GB disk)
```

Triton Machine (where I don't use ultralytics but installed it anyway to allow to get this environment stats) with GPU access

```
Ultralytics YOLOv8.1.2 🚀 Python-3.8.10 torch-2.1.2+cu121 CUDA:0 (NVIDIA GeForce RTX 3070 Laptop GPU, 7949MiB)
Setup complete ✅ (16 CPUs, 31.2 GB RAM, 743.1/837.3 GB disk)
```

My Triton server version is as follows:

```
nvcr.io/nvidia/tritonserver:22.07-py3
```

### Additional

The client docker does not have a GPU. 

Is Ultralytics running something on the client side that better performs on the GPU? 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by cesarandreslopez** [comment]
#### UPDATE

To test, i've now converted the client docker image to have access to the GPU. 

Results are as follows:

```
Time taken for line 1: 0.000141143798828125 seconds
0: 640x640 1 class0, 1 class27, 38.4ms
Speed: 2.1ms preprocess, 38.4ms inference, 0.6ms postprocess per image at shape (1, 3, 640, 640)
Time taken for line 2: 0.09628677368164062 seconds

```
Which is a saving of over 1 second of inference time when the client has access to a GPU.

I would have thought that since the model processing is offloaded to Triton that a GPU or a CPU would not make a difference on the client side.

Any ideas on how to keep the performance when the client does not have access to a GPU but the Triton Server does?

**Comment by glenn-jocher** [comment]
@cesarandreslopez hello! Thank you for the detailed information and for conducting further tests to isolate the issue.

When you observe a significant difference in inference time between a GPU-enabled client and a CPU-only client, even though the inference is offloaded to Triton, it suggests that some part of the pre-processing or post-processing might be leveraging the GPU on the client side. This can happen if the client environment has GPU support and certain operations are automatically optimized to run on the GPU.

Since YOLOv8 is designed to take advantage of GPU acceleration when available, it's possible that operations such as image resizing, normalization, or data transfer to the Triton server are more efficient on the GPU. Similarly, after receiving the inference results, the post-processing steps like non-maximum suppression or bounding box adjustments could also be faster with GPU acceleration.

To maintain performance on a CPU-only client, you might want to ensure that the client-side operations are as efficient as possible. This could involve optimizing the CPU-based pre-processing and post-processing routines or looking into whether the client library used for communicating with Triton can be further optimized for CPU use.

Keep in mind that network latency can also play a role, although you've indicated that this is unlikely the main issue in your case. It's always good to check that the client-server communication is not a bottleneck.

If you need further assistance, please refer to our documentation on Predict mode and consider reaching out through the appropriate channels for more in-depth support.

**Comment by cesarandreslopez** [comment]
@glenn-jocher  I understand. So, the Triton Server would also need to handle pre-processing and post-processing. An ensemble like the one that would make sense. https://github.com/omarabid59/yolov8-triton

I'll work on that and submit a PR if your team is not already working on that.

**Comment by glenn-jocher** [comment]
@cesarandreslopez, indeed, offloading pre-processing and post-processing to the Triton server could help mitigate the performance impact on CPU-only clients. An ensemble model that integrates these steps could be a good solution. We appreciate your initiative and look forward to your PR. If you have any questions or need guidance, feel free to reach out. Happy coding! 🚀

**Comment by frandoLin** [comment]
Following the offical guide, I ran the script for Triton inferencing and also took a look the sourc code of triton.py. It seems like the onnx model is loaded into Triton sever using its onnx backend but there is no the conversion of pt model and TensorRT. Do I understand it correctly?

**Comment by glenn-jocher** [comment]
@frandoLin yes, you understand correctly. The official guide demonstrates how to load an ONNX model into the Triton server using its ONNX backend. Conversion of a `.pt` model to TensorRT is a separate process and is not covered in that particular guide. If you're interested in using TensorRT for inference, you would need to convert the model to TensorRT format before deploying it to Triton. For more details on different export formats, please refer to our Export mode documentation. 📚

**Comment by frandoLin** [comment]
@glenn-jocher Thanks for your reply. I actually converted .pt to TensorRT using yolo's codebase and can also using the TensorRT backend in the autobackend to inference, but it doesn't work when I load the converted trt model into triton server. However, it works with the trt models I converted from the trtexec. I posted the question before, I am sure I installed the python tensorrt package triton server uses. Here is the question I posted before. https://github.com/ultralytics/ultralytics/issues/3088

**Comment by frandoLin** [comment]
@glenn-jocher No problem! I am actually a big fan of yolo (from v5 to v8) LOL . I hope you guys can finally get it work. I noticed yolo also integrates transformer. That's cool if it also includes how to use kubernetes to spin up multiple instances.

**Comment by glenn-jocher** [comment]
@frandoLin, thank you for your support! We're glad to hear you're a fan of YOLO. 😊 We're continuously working on improvements and integrations. The inclusion of transformers is indeed an exciting development. As for Kubernetes, we appreciate your suggestion and will consider it for future enhancements. Stay tuned for updates! 🌟
