### ISSUE TITLE
reloading 'last.pt' model from previous runs for predictions

### ISSUE THREAD

**Issue by navjotzubler** [ultralytics/ultralytics#7706]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I load 'last.pt' saved in /runs/segment/train/weights directory and run predictions using this reloaded model? Thanks for help

**Comment by glenn-jocher** [comment]
@navjotzubler hello! To load the 'last.pt' model from the `/runs/segment/train/weights` directory for predictions, you can use the `Predict` mode with the path to your 'last.pt' file. Simply specify the weights file when running your prediction command, and the model will be loaded for inference. For detailed instructions on using the `Predict` mode, please refer to the Predict section in our documentation at https://docs.ultralytics.com/modes/predict. Happy predicting! 😊🚀
