### ISSUE TITLE
AGROVERSE DATA SET CODE PROBLEM(ULTRALYTICS HUB _ BETA

### ISSUE THREAD

**Issue by taaha42777** [ultralytics/ultralytics#7710]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

https://hub.ultralytics.com/datasets/1acHqFVdvc0pRRDLS9EQ?tab=overview
![Screenshot (25)](https://github.com/ultralytics/ultralytics/assets/157221804/06aaf6ff-323c-4e1b-bd4e-b07aca81949b)
1.i had to train the model of dataset of Argoverse
2 i opted for collab 
3. the code i ran
hub.login('MY KEY')

model = YOLO('https://hub.ultralytics.com/models/DctpYztGfvqWUpVIVzR6')
results = model.train()

the error or bug is :
Ultralytics HUB: New authentication successful ✅
Ultralytics HUB: View model at https://hub.ultralytics.com/models/DctpYztGfvqWUpVIVzR6 🚀
Ultralytics YOLOv8.1.3 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=Argoverse.yaml, epochs=100, time=None, patience=100, batch=-1, imgsz=640, save=True, save_period=-1, cache=ram, device=0, workers=8, project=None, name=train6, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train6

Dataset 'Argoverse.yaml' images not found ⚠️, missing path '/content/datasets/Argoverse/Argoverse-1.1/images/val'
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py](https://localhost:8080/#) in __init__(self, cfg, overrides, _callbacks)
    132             elif self.args.data.split(".")[-1] in ("yaml", "yml") or self.args.task in ("detect", "segment", "pose"):
--> 133                 self.data = check_det_dataset(self.args.data)
    134                 if "yaml_file" in self.data:

4 frames
<string> in <module>

FileNotFoundError: [Errno 2] No such file or directory: '/content/datasets/Argoverse/Argoverse-1.1/tracking' -> '/content/datasets/Argoverse/Argoverse-1.1/images'

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py](https://localhost:8080/#) in __init__(self, cfg, overrides, _callbacks)
    135                     self.args.data = self.data["yaml_file"]  # for validating 'yolo train data=url.zip' usage
    136         except Exception as e:
--> 137             raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
    138 
    139         self.trainset, self.testset = self.get_dataset(self.data)

RuntimeError: Dataset 'Argoverse.yaml' error ❌ [Errno 2] No such file or directory: '/content/datasets/Argoverse/Argoverse-1.1/tracking' -> '/content/datasets/Argoverse/Argoverse-1.1/images'

4. please answer in steps and as detailed as possible for ne comer's like me 

### Environment

collab

### Additional

a

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by taaha42777** [comment]
STILL THE ERROR AND BUG IS THERE

**Comment by taaha42777** [comment]
![Screenshot (26)](https://github.com/ultralytics/ultralytics/assets/157221804/05ccdf8e-b385-4722-b7df-012a081fb4b0)
![Screenshot (27)](https://github.com/ultralytics/ultralytics/assets/157221804/934818ea-66c9-4f37-a6ba-88d8cad18ec0)
![Screenshot (28)](https://github.com/ultralytics/ultralytics/assets/157221804/ae0939ff-253a-4082-9a83-36ce71c2ce32)
![Screenshot (29)](https://github.com/ultralytics/ultralytics/assets/157221804/2d3517fd-1219-4ade-90e2-73e0b01dafe3)

**Comment by glenn-jocher** [comment]
@taaha42777 it appears that the dataset path is incorrect or the dataset has not been properly downloaded and extracted. Please ensure that the dataset is correctly placed in the `/content/datasets/Argoverse/Argoverse-1.1/` directory with the expected subdirectories and file structure. If the dataset is not present, you may need to download and extract it manually to the correct location before training. For further guidance on dataset setup and troubleshooting, please refer to the documentation on data preparation and usage at https://docs.ultralytics.com.

**Comment by glenn-jocher** [comment]
@taaha42777 Argoverse is no longer hosted by Argo AI, which has gone out of business, but we've placed this dataset on Google Drive for manual download, so to train on it you must first manually download this dataset from URL indicated on your screenshots, same as this here:
https://drive.google.com/uc?export=download&id=1st9qW3BeIwQsnR0t8mRpvbsSWIo16ACi

**Comment by glenn-jocher** [comment]
@taaha42777 I've added a warning for future users now in https://github.com/ultralytics/ultralytics/pull/7725/commits/341c72b2dcaff8d9d0f567efd757ed093c5ee368

**Comment by taaha42777** [comment]
Thank you for your response

**Comment by glenn-jocher** [comment]
You're welcome, @taaha42777! If you have any more questions or need further assistance, feel free to reach out. Happy coding! 🚀

**Comment by codename-cn** [comment]
@glenn-jocher Why don't you provide pre-trained models for all the [listed datasets](https://docs.ultralytics.com/datasets/), especially for Argoverse 1 and 2?

**Comment by glenn-jocher** [comment]
@codename-cn hi there! We focus on providing models pre-trained on widely-used datasets like COCO to offer a strong and versatile foundation for users to fine-tune on their specific datasets. For Argoverse or other specialized datasets, we encourage users to fine-tune our pre-trained models to their specific needs. This approach allows for greater flexibility and customization for your unique use cases. If you need guidance on fine-tuning, our docs and tutorials are a great place to start! 😊👨‍💻
