### ISSUE TITLE
230-yolov8-object-detection.ipynb 

### ISSUE THREAD

**Issue by ptiszai** [ultralytics/ultralytics#7712]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I converted Yolov8n -pose/seg/normal models  xml/bin in OpenVino (Intel). 
I using GPU device.
Detection.
def detect(image:np.ndarray, model:ov.Model):  function in Python
......
Very cool is the GPU performace in %,
But CPU 80-90%, very wrong,
I tested. The OpenVino GPU functions is good.
One function bad, think because of in CPU running.
from ultralytics.utils import ops
    preds = ops.non_max_suppression(
        torch.from_numpy(pred_boxes),
        min_conf_threshold,
        nms_iou_threshold,
        nc=1,
        **nms_kwargs
    )
 https://github.com/ultralytics/ultralytics/tree/main/ultralytics/utils/ops.py : 
line  : 164
def non_max_suppression(...):
This function runnig in CPU.
How can I overwrite the def non_max_suppression(...) function to the GPU processor?
230-yolov8-optimization:
https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/230-yolov8-optimization/230-yolov8-keypoint-detection.ipynb
In [9]

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ptiszai** [comment]
Error image:
![ops non_max_supression](https://github.com/ultralytics/ultralytics/assets/844768/b57d2a6a-8bec-4c43-b866-691086fd4eb0)

**Comment by glenn-jocher** [comment]
@ptiszai it appears that you're experiencing high CPU usage with the `non_max_suppression` function from our utils when running YOLOv8 models with OpenVino on a GPU. This function is indeed designed to run on the CPU, which might explain the usage you're observing.

To offload `non_max_suppression` to the GPU, you would need to modify the function to utilize GPU-compatible operations. However, this is not a trivial task as it involves ensuring that all operations within the function are compatible with GPU execution, which may require significant changes to the codebase.

For now, you might want to profile your application to identify any other potential bottlenecks and optimize those. If the CPU usage is a critical issue for your use case, you might consider reaching out to the OpenVino community for guidance on how to best integrate their GPU functions with our models.

Keep in mind that any modifications to the function would need to comply with the AGPL-3.0 license if you plan to distribute the modified software. If you require assistance with a commercial product, consider exploring our Enterprise License for more flexibility.

For further details on YOLOv8 and its usage, please refer to our documentation at https://docs.ultralytics.com.

**Comment by ptiszai** [comment]
Thanks for the quick reply glenn-jocher.

**Comment by glenn-jocher** [comment]
@ptiszai you're welcome! If you have any more questions or need further assistance, feel free to reach out. Happy coding! 😊👍
