### ISSUE TITLE
Seting up custom config.yaml - YOLO V8

### ISSUE THREAD

**Issue by FlorianRakos** [ultralytics/ultralytics#7715]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I would like to use a custom yaml configuration file, instead of the default.yaml. How can I configure yolo to use my own .yaml file?

I tried using `yolo --config-name=conf.yaml`  as in the following post:
https://github.com/ultralytics/ultralytics/issues/247

but only get the error:  'config-name' is not a valid YOLO argument. 

Always changing the default.yaml would be a big hassle, as I have multiple containers training different models.
I've got Ultralytics Version 8.0.229 running.

Thanks in advance!

**Comment by glenn-jocher** [comment]
@FlorianRakos hello!

To use a custom configuration file with YOLOv8, you should specify the path to your `.yaml` file directly when running your training command. For example, if your custom config file is named `conf.yaml`, you would include it in your training command like so:

```shell
yolo train --data conf.yaml
```

This tells YOLOv8 to use `conf.yaml` for the training configuration. Make sure your custom `.yaml` file is structured correctly and located in a directory that's accessible to YOLOv8.

Happy training! 😊🚀

**Comment by FlorianRakos** [comment]
Hey and thank you for the quick answer.

Maybe I have not formulated my question clear enough. I don't mean the data.yaml file with which you set the paths to the dataset and annotations.

My question is how to set up a custom yaml configuration file that contains all the training params like learning rate and data augmentation settings. Or is it only possible to edit these settings inside the default.yaml (in /ultralytics/cfg) and you can not set up your own config file?

Thank you and best regards
Florian

**Comment by glenn-jocher** [comment]
@FlorianRakos hello Florian,

Apologies for the confusion. To use a custom model configuration file containing your training parameters, you can indeed create your own `.yaml` file and specify it when running the training command. Place your custom `.yaml` file in a directory of your choice and then reference it directly:

```shell
yolo train --cfg custom_model.yaml
```

Replace `custom_model.yaml` with the path to your custom configuration file. This will override the default settings with those specified in your file.

**Comment by djmoffat** [comment]
>To use a custom model configuration file containing your training parameters, you can indeed create your own `.yaml` file and specify it when running the training command. Place your custom `.yaml` file in a directory of your choice and then reference it directly:
> 
> ```shell
> yolo train --cfg custom_model.yaml
> ```
> 
> Replace `custom_model.yaml` with the path to your custom configuration file. This will override the default settings with those specified in your file.

This does not work.

Running
```shell
$ yolo train --cfg custom_config.yaml
WARNING ️ '--cfg' does not require leading dashes '--', updating to 'cfg'.
Printing '/usr/src/ultralytics/ultralytics/cfg/default.yaml'
...
```
With YOLO version 8.1.9

Are there any other suggestions for how to use a custom config file, to override [default augmentations parameters](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/default.yaml)

**Comment by djmoffat** [comment]
I was able to find the answer somewhere in the documentation
https://docs.ultralytics.com/usage/cli/#overriding-default-arguments

```shell
yolo cfg=custom_config.yaml
```

**Comment by glenn-jocher** [comment]
@djmoffat, that's correct! You can override the default arguments by specifying your custom configuration file without the leading dashes, as shown in the documentation. Your command should look like this:

```shell
yolo cfg=custom_config.yaml
```

Make sure your `custom_config.yaml` is properly formatted and contains the parameters you wish to adjust. Happy training! 😊👍

**Comment by Petros626** [comment]
@djmoffat how to do that for python, instead of CLI? Default case is, that default_cfg.yaml is choose, even when you specify custom config.yaml
