### ISSUE TITLE
It will be stuck for a long time when verifying

### ISSUE THREAD

**Issue by xunfeng233** [ultralytics/ultralytics#7718]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I do the verification,from the Model summary...... To Val: Scanning...... It will be stuck for a long time,before I used Ubuntu22.04 without this problem,I am using ubuntu20.04 now.

**Comment by glenn-jocher** [comment]
@xunfeng233 hello! It seems you're experiencing a delay during the validation phase with YOLOv8 on Ubuntu 20.04, whereas previously on Ubuntu 22.04, you did not encounter this issue. This could be related to differences in system configuration or dependencies between the two Ubuntu versions.

To address this, please ensure that your environment is set up correctly with all the necessary dependencies installed. Also, check if there are any system resource constraints that might be causing the process to hang. If you're using a custom dataset, verify that the dataset is correctly formatted and accessible.

For further troubleshooting, you can refer to the [Val documentation](https://docs.ultralytics.com/modes/val) for guidance on the validation process. If the issue persists, please provide more details on your setup, such as hardware specifications and any error messages you might be receiving, so we can assist you more effectively. 🛠️

**Comment by DnEcing** [comment]
I had the same problem and the load before training took a long time.
Another problem is that plots=True in the default.yaml, but val_batch0_pred and val_batch0_labels labels have not been plotted. Their corresponding functions are plot_val_samples/plot_predictions

**Comment by glenn-jocher** [comment]
@DnEcing hello! If you're experiencing slow load times before training and missing plots despite `plots=True` in `default.yaml`, consider checking your system's I/O performance and ensure you have the latest updates from the YOLOv8 repo. For the plotting issue, ensure that your validation dataset is properly set up and that there are no issues with the visualization libraries. For detailed guidance on validation and plotting, please refer to the [Val documentation](https://docs.ultralytics.com/modes/val). If the problem persists, provide details about your setup and any error logs for further assistance. 📊🔍
