### ISSUE TITLE
yolov8-rtdetr.yaml issue

### ISSUE THREAD

**Issue by Alarmod** [ultralytics/ultralytics#7720]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I checked yolov8-rtdetr for detection: 

`
  File "C:\anaconda3\lib\site-packages\ultralytics\nn\tasks.py", line 338, in init_criterion
    return v8DetectionLoss(self)
  File "C:\anaconda3\lib\site-packages\ultralytics\utils\loss.py", line 154, in __init__
    self.stride = m.stride  # model strides
  File "C:\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'RTDETRDecoder' object has no attribute 'stride'
`

### Environment

Ultralytics YOLOv8.1.3 🚀 Python-3.9.18 torch-2.1.2+cu118

### Minimal Reproducible Example

model = YOLO("yolov8m-rtdetr.yaml", task="detect")
model.train(
             name="gestures_boxes_with_rtdetr", 
             data="data_gestures.yaml", 
             imgsz=960, 
             batch=7, 
             lr0=0.0001, 
             lrf=0.001, 
             half=False, 
             optimizer="AdamW", 
             single_cls=False, 
             cos_lr=True, 
             dnn=False, 
             amp=True, 
             device="0", 
             epochs=2000, 
             patience=100, 
             workers=0, 
             augment=False, 
             cache=True, 
             nms=True, 
             seed=777, 
             deterministic=True, 
             hsv_h=0.6, hsv_s=0.7, hsv_v=0.4, degrees=15.0, translate=0.25, scale=0.5, shear=3.0, perspective=0.0002, flipud=0, fliplr=0.5, mosaic=0.0, mixup=0.0, copy_paste=0.0, 
             rect=True
   )

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Alarmod this is user error, RTDETR models are not rectangular training nor inference capable, but you've passed `rect=True`.

**Comment by glenn-jocher** [comment]
@Alarmod I'm able to reproduce an error based on the MRE below

```python
from ultralytics import YOLO

model = YOLO("yolov8m-rtdetr.yaml", task='detect')
model.train(data='coco8.yaml')
```

@Laughing-q

**Comment by Alarmod** [comment]
Also tested code from @glenn-jocher :) same error

I saw modification of `self.stride = m.stride` a month or two ago when I was looking at the Yolo code changes

**Comment by glenn-jocher** [comment]
Apologies for the confusion, @Alarmod. It seems there's an issue with the RTDETR model configuration. The 'stride' attribute error indicates a mismatch between the model architecture and the loss function expectations. We'll investigate this and address it in an upcoming update. For now, please ensure you're using the latest version and check the documentation for any updates on RTDETR usage. Thank you for bringing this to our attention! 🛠️

**Comment by Laughing-q** [comment]
@Alarmod @glenn-jocher hi guys! any model related to rtdetr should be created by `RTDETR` instead of `YOLO`. :)
The following code works to me.
```python
from ultralytics import RTDETR

model = RTDETR("yolov8m-rtdetr.yaml")
model.train(data='coco128.yaml', batch=2)
```

**Comment by Alarmod** [comment]
I run my code as YOLO(...) becouse model be in v8 folder... Also now exist rt-detr folder (ultralytics/cfg/models/rt-detr)

**Comment by Laughing-q** [comment]
@Alarmod got it! please use `RTDETR` to create the model, probably we'll move `yolov8-rtdetr` to `rt-detr` folder in the future. :)

**Comment by ahmedfarouk99** [comment]
@Alarmod @Laughing-q sorry for bothering but i still have the same error after 13 epochs and i got confused how to resolve it..
anyone can help?

**Comment by ahmedfarouk99** [comment]
@glenn-jocher @Alarmod @Laughing-q can you answer my question ?

**Comment by Alarmod** [comment]
@ahmedfarouk99 check it https://github.com/ultralytics/ultralytics/issues/2183#issuecomment-2041294437

**Comment by ahmedfarouk99** [comment]
@Alarmod thanks for your response but #2183 is a different issue or you meant to add "pretrained=False" in my cli hyperparameters?

**Comment by ahmedfarouk99** [comment]
@Alarmod can you answer my question please?
