### ISSUE TITLE
Print bbox in predict mode

### ISSUE THREAD

**Issue by tjasmin111** [ultralytics/ultralytics#7727]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can we specify to print bounding box information during predict mode in CLI?

So for instance, when I use this command:
`yolo task=detect mode=predict model=best.pt source=test imgsz=800`
This is the current output. I need it to print bbox info as well. 
```
Ultralytics YOLOv8.1.2 🚀 Python-3.10.9 torch-2.0.1+cpu CPU (12th Gen Intel Core(TM) i7-1255U)
Model summary (fused): 168 layers, 11138742 parameters, 0 gradients, 28.5 GFLOPs

image 1/50 home\test\sample1.jpg: 544x800 1 cat, 522.7ms
```

**Comment by glenn-jocher** [comment]
@tjasmin111 hello! To print bounding box (bbox) information during predict mode in the CLI, you can use the `--save-txt` flag. This will save the bbox coordinates to a `.txt` file for each image or frame processed. The files will be saved in the `runs/detect/exp*/labels` directory by default. Each line in the `.txt` file corresponds to one detected object and contains class ID, bbox center x, y coordinates, width, and height, all normalized to the image size.

Here's how you can modify your command:
```
yolo task=detect mode=predict model=best.pt source=test imgsz=800 --save-txt
```

After running this command, you'll find the bbox information saved as described above. Happy detecting! 😊
