### ISSUE TITLE
How to get wrong/missed predictions in val mode

### ISSUE THREAD

**Issue by Holsonn** [ultralytics/ultralytics#7732]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I am using yolov8 for training. When I use val mode, I cannot get the verification of all pictures. In the val folder, there are only some data analysis pictures and 3 batch pictures, but I want is the wrong/missed predictions of all images in the entire val file.
I noticed that someone had asked the same question before, but I still couldn't solve my problem based on the corresponding answers.
This is my code in google colab.
`!yolo task=segment mode=val model=/content/drive/MyDrive/Train-Polygen-Scratch-Deep/train/weights/best.pt data=/content/Train_data/data.yaml save_json=true`
![image](https://github.com/ultralytics/ultralytics/assets/57980841/fffcaf4c-f663-49ad-9589-9ad78b94d5fa)

**Comment by glenn-jocher** [comment]
@Holsonn hello! To review wrong or missed predictions during validation in YOLOv8, you can enable the `--save-conf` and `--save-txt` flags when running the validation. This will save the confidence scores and prediction details for each image in text files within the `runs/val` directory. You can then analyze these files to identify which predictions were incorrect or missed. For a more visual inspection, you can use the `--save-crop` flag to save cropped images of each prediction, which can be helpful for reviewing specific cases. Remember to check the documentation for more details on these flags and how to use them effectively. Happy validating! 😊
