### ISSUE TITLE
Yolov8 pose keypoint

### ISSUE THREAD

**Issue by giter915** [ultralytics/ultralytics#7738]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

May I ask where the 17 keypoint detection points in YOLO Pose specifically are located? That is, what part of the body does 0 represent, and what part does 1 represent? Thank you.

### Additional

no

**Comment by daniilpastukhov** [comment]
The YOLOv8 was trained on COCO dataset, where keypoints correspond to this image ([src](https://learnopencv.com/human-pose-estimation-using-keypoint-rcnn-in-pytorch/)):
![image](https://github.com/ultralytics/ultralytics/assets/29576467/94e5eb8a-9c78-49b8-91ab-21aff0247a5d)

**Comment by giter915** [comment]
Thank you very much!

**Comment by glenn-jocher** [comment]
@giter915 you're welcome! If you have any more questions or need further assistance, feel free to reach out. Happy to help! 😊🚀

**Comment by ialertt** [comment]
Por favor donde hay documentación de como utilizar los 17 puntos claves, gracias. Deseo utilizarlos para detección de caídas, detección de manos arriba, detección de personan corriendo, otros.

**Comment by glenn-jocher** [comment]
¡Hola @ialertt! 🙌 Estamos encantados de saber que estás interesado en utilizar los 17 puntos clave para detección de poses con YOLOv8. Puedes encontrar más información sobre cómo trabajar con los keypoints en nuestra documentación [aquí](https://docs.ultralytics.com/tasks/pose).

Para un ejemplo rápido, después de ejecutar la predicción:

```python
from ultralytics import YOLO

model = YOLO('yolov8n-pose.pt')  # Asegúrate de cargar el modelo correcto
results = model.predict('tus_imagenes.jpg')

for result in results:
    keypoints = result.keypoints  # Aquí tienes los keypoints
    print(keypoints)
```

Esto te permitirá acceder y manipular los keypoints detectados para tus aplicaciones específicas, como detección de caídas, manos arriba, o personas corriendo.

¡Espero que esto ayude y mucho éxito en tu proyecto! 😄🚀
