### ISSUE TITLE
Question about Yolov8 architecture and Layers in details ?

### ISSUE THREAD

**Issue by moahaimen** [ultralytics/ultralytics#775]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

@glenn-jocher 
hi Glenn, i used yolov8 in my thesis and i need to know What is the detailed architecture of Yolov8 and can you explain the purpose and function of each layer in the network? so i can write perfectly, i need your help  with that, also  is there any ability to contact you directly please?
thank you

**Comment by dmddmd** [comment]
same here. I use it in my thesis and actually need a citable source

**Comment by salwaalkhatib** [comment]
I'm trying to incorporate v8 into my project and would appreciate a citable source as well

**Comment by AyushExel** [comment]
<img width="1423" alt="Screenshot 2023-02-05 at 10 20 11 PM" src="https://user-images.githubusercontent.com/15766192/216832714-e9547b16-7820-4b77-90e2-c9e8883849f2.png">
Citation is available on the repo

**Comment by dmddmd** [comment]
in the citation, the version is 8.0.0

**Comment by moahaimen** [comment]
> <img alt="Screenshot 2023-02-05 at 10 20 11 PM" width="1423" src="https://user-images.githubusercontent.com/15766192/216832714-e9547b16-7820-4b77-90e2-c9e8883849f2.png">
> 
> Citation is available on the repo

thank you , but i need a scientific paper

**Comment by dmddmd** [comment]
will there be scientific paper and when?

**Comment by pderrenger** [comment]
@dmddmd currently, there isn't a scientific paper detailing the YOLOv8 architecture. However, the architecture and functionalities of YOLOv8 are detailed in the Ultralytics documentation. If you need specific details for your thesis or project, I recommend referring to the official Ultralytics documentation for YOLOv8 and citing it as a reliable source for the architecture and layer functionalities. As for the availability of a scientific paper, I cannot provide a specific timeline for its release, but any updates or announcements regarding this can be found on the official Ultralytics repository.

**Comment by olawalejuwonm** [comment]
> will there be scientific paper and when?

Co-asking?

**Comment by glenn-jocher** [comment]
@olawalejuwonm thank you for your interest. Currently, there is no scientific paper available for YOLOv8. We recommend citing the GitHub repository as shown in the citation section. If a paper is published in the future, it will be announced on the repository.

**Comment by olawalejuwonm** [comment]
> @olawalejuwonm thank you for your interest. Currently, there is no scientific paper available for YOLOv8. We recommend citing the GitHub repository as shown in the citation section. If a paper is published in the future, it will be announced on the repository.

Alright. Thank you!

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to ask.
