### ISSUE TITLE
Mention in docs that OpenCV numThreads is set to 0

### ISSUE THREAD

**Issue by rzf16** [ultralytics/ultralytics#7750]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Not really a feature, but I think it should be mentioned in the docs somewhere that importing Ultralytics sets OpenCV numThreads to 0 (via line 103 of `ultralytics/utils/__init__.py`). For applications that don’t utilize Torch dataloaders and want to use multi-threaded OpenCV functions, this can be quite a tough bug to find.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@rzf16 thank you for bringing this to our attention. We appreciate your suggestion to clarify the behavior of OpenCV's `numThreads` setting within our documentation. Your feedback is valuable, and we'll consider adding a note about this in the relevant section of our docs to inform users of the default threading behavior when using Ultralytics YOLOv8. This should help prevent any confusion for those not utilizing Torch dataloaders and looking to leverage multi-threaded capabilities of OpenCV in their applications. Keep an eye on the documentation updates, and thanks again for your contribution to the YOLOv8 community! 📚🔧
