### ISSUE TITLE
Support for RTMO 

### ISSUE THREAD

**Issue by Gaozhongpai** [ultralytics/ultralytics#7753]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

This RTMO in MMPose: https://github.com/open-mmlab/mmpose/tree/main/projects/rtmo

### Use case

Better performance than YOLO-Pose

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Gaozhongpai thank you for the suggestion regarding RTMO support. We're always looking to improve and appreciate community input. While we currently don't have RTMO integrated into YOLOv8, we do offer pose/keypoint estimation capabilities that are optimized for performance and accuracy. We'll take note of your interest in RTMO for future updates. If you have any further insights or comparisons that could help us understand the benefits, feel free to share them in the discussions section. Your contributions to the community are valuable! 🌟
