### ISSUE TITLE
Streamlit can not install ultralytics

### ISSUE THREAD

**Issue by NBTailee** [ultralytics/ultralytics#7755]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Integrations

### Bug

ImportError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
Traceback:
File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "/mount/src/driver_safety_ai/app.py", line 5, in <module>
    from ultralytics import YOLO
File "/home/adminuser/venv/lib/python3.9/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
File "/home/adminuser/venv/lib/python3.9/site-packages/ultralytics/models/__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
File "/home/adminuser/venv/lib/python3.9/site-packages/ultralytics/models/rtdetr/__init__.py", line 3, in <module>
    from .model import RTDETR
File "/home/adminuser/venv/lib/python3.9/site-packages/ultralytics/models/rtdetr/model.py", line 10, in <module>
    from ultralytics.engine.model import Model
File "/home/adminuser/venv/lib/python3.9/site-packages/ultralytics/engine/model.py", line 8, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
File "/home/adminuser/venv/lib/python3.9/site-packages/ultralytics/cfg/__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
File "/home/adminuser/venv/lib/python3.9/site-packages/ultralytics/utils/__init__.py", line 18, in <module>
    import cv2

### Environment

Window 11
RAM: 16 GB
CUDA: RTX 3050

### Minimal Reproducible Example

# this is my app.py
import streamlit as st
import pandas as pd
import numpy as np
from PIL import Image
from ultralytics import YOLO
import torch

if "conf" not in st.session_state:
    st.session_state["conf"] = 0
if "detect" not in st.session_state:
    st.session_state["detect"] = False

st.title("Seatbelt & Sleepy Driver Detection")

st.header("Detection Type")
option = st.selectbox("Choose Detection Type", ("drowsy","seatbelt"), index=None, placeholder="Select contact method...")
st.write("Type Chosen: ", option)
 -----------------------------------------------------------------------------------------------------------------------------------------
#this is my requirements.txt
ultralytics==8.0.232
numpy==1.25.0
pandas==2.0.2
Pillow==10.1.0
streamlit==1.30.0
torch==2.1.1+cu118
opencv-python==4.8.1.78
git+https://github.com/ultralytics/yolov5

### Additional

i dont no why when i deploy my app with streamlit it is not install ultralytics packages although i have include it in requirement.txt file

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@NBTailee hello! It seems like you're encountering an ImportError when trying to use the Ultralytics YOLO package within a Streamlit app. The error message indicates there might be an issue with the installation or import of the required packages.

Firstly, ensure that your `requirements.txt` file specifies the correct version of the `ultralytics` package that is compatible with your environment. Also, it's important to note that the `ultralytics` package should be installed from PyPI, and not directly from the GitHub repository as you have done with `yolov5`. The `git+https://github.com/ultralytics/yolov5` line in your `requirements.txt` is unnecessary for YOLOv8 and should be removed.

Additionally, the error message suggests there could be an issue with the `cv2` module, which is part of the `opencv-python` package. Make sure that `opencv-python` is installed correctly in your environment.

If you continue to face issues, please refer to our documentation at https://docs.ultralytics.com for guidance on installation and setup. If the problem persists, consider providing the full error log for more detailed assistance. Remember to check that all dependencies are correctly installed and that there are no conflicts between package versions.

Keep in mind that the YOLOv8 model and its associated utilities are designed to be user-friendly, and we're here to help you get your application up and running! 🚀

**Comment by NBTailee** [comment]
this is my repo: https://github.com/NBTailee/driver_safety_AI
it is just like streamlit ignores to install ultralytics when deploy the app. As i see the build logs, it installs all dependencies except ultralytics.
![Screenshot 2024-01-24 125554](https://github.com/ultralytics/ultralytics/assets/87483288/f9ef137b-4769-429e-b136-a72fd59eda25)

**Comment by HudaibahLab** [comment]
Is there any solution workaround done?

**Comment by HudaibahLab** [comment]
Change the library in requirements.txt 
from `opencv-python==4.8.1.78` to `opencv-contrib-python-headless` . @NBTailee

**Comment by SaviAnn** [comment]
> Change the library in requirements.txt from `opencv-python==4.8.1.78` to `opencv-contrib-python-headless` . [@NBTailee](https://github.com/NBTailee)

Thanks a lot! Still works:)

**Comment by glenn-jocher** [comment]
@SaviAnn you're welcome! Glad to hear it worked for you. If you have any further questions or issues, feel free to ask.
