### ISSUE TITLE
Hyperparameters Tuning Problem.

### ISSUE THREAD

**Issue by 2019331099-Rabbi** [ultralytics/ultralytics#7757]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Hyperparameter Tuning

### Bug

I have followed the docs of [Hyperparameter Tuning with Ray Tune](https://docs.ultralytics.com/integrations/ray-tune/)

I have given the exact same commands. But the following errors generated.

2024-01-23 04:27:04,415	ERROR services.py:1329 -- Failed to start the dashboard , return code -11
2024-01-23 04:27:04,418	ERROR services.py:1354 -- Error should be written to 'dashboard.log' or 'dashboard.err'. We are printing the last 20 lines for you. See 'https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure' to find where the log file is.
2024-01-23 04:27:04,419	ERROR services.py:1398 -- 
The last 20 lines of /tmp/ray/session_2024-01-23_04-27-01_852449_26/logs/dashboard.log (it contains the error message from the dashboard): 
2024-01-23 04:27:04,381	INFO head.py:254 -- Starting dashboard metrics server on port 44227

2024-01-23 04:27:04,595	INFO worker.py:1724 -- Started a local Ray instance.

### Minimal Reproducible Example

!pip install -U ultralytics "ray[tune]"
!pip install -U wandb
!pip install -U ipywidgets

from ultralytics import YOLO
model = YOLO('yolov8n.pt')
result_grid = model.tune(data='coco8.yaml', use_ray=True)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@2019331099-Rabbi hello! It seems like you're encountering an issue with Ray Tune integration while trying to tune hyperparameters for YOLOv8. The error messages you've posted indicate a problem starting the Ray dashboard, which is a separate component from YOLOv8.

This issue might be related to your environment setup or a specific problem with Ray's dashboard component. I recommend checking the `dashboard.log` or `dashboard.err` files for more detailed error messages as suggested by the error output. These logs might provide insights into what's causing the dashboard to fail.

If the logs do not clarify the issue, you might want to reach out to the Ray community or their support channels, as they would be better equipped to help you troubleshoot Ray-specific problems.

In the meantime, ensure that your environment meets all the requirements for running Ray Tune and that there are no conflicts with other packages or system configurations.

If you continue to experience issues specifically related to YOLOv8's integration with Ray Tune, please provide more details about your environment and any additional error messages you encounter, and we'll do our best to assist you further. 🛠️
