### ISSUE TITLE
Better use of YOLOv8

### ISSUE THREAD

**Issue by JustChenk** [ultralytics/ultralytics#7762]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to hide these outputs
![1](https://github.com/ultralytics/ultralytics/assets/136715410/3143570b-0a11-4236-a90c-6051a88e32e7)

**Comment by sunmooncode** [comment]
Set the parameter verbose to False.
`verbose=False`

**Comment by glenn-jocher** [comment]
@sunmooncode to suppress the outputs you're referring to, you can set the `verbose` parameter to `False` when calling the relevant function in your code. This should help keep your console output clean and focused on the information you need. 😊👍

**Comment by JustChenk** [comment]
> @sunmooncode to suppress the outputs you're referring to, you can set the `verbose` parameter to `False` when calling the relevant function in your code. This should help keep your console output clean and focused on the information you need. 😊👍

Oh！I remembered that it was also written in the introductory document. This is so convenient, thank you！

**Comment by JustChenk** [comment]
> Set the parameter verbose to False. `verbose=False`

Thank you！ problem solved。
just like 
![image](https://github.com/ultralytics/ultralytics/assets/136715410/a8ef6b1f-041f-4185-913a-8a38d2dc7fb3)
