### ISSUE TITLE
Object detection in polygon zone

### ISSUE THREAD

**Issue by kewchi** [ultralytics/ultralytics#7763]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have read other questions similar to this but was unable to get it to work using the solutions given. 
I am trying to do an object detection in a polygon zone using my custom model but received this error
 `     20     # Detect
     21     results = model(frame, imgsz=640)[0]
---> 22     detections = sv.Detections.from_yolov8(results)
     23     detections = detections[detections.class_id == 0]
     24     zone.trigger(detections=detections)

AttributeError: type object 'Detections' has no attribute 'from_yolov8'`

I am unsure on how to fix this, please help

**Comment by glenn-jocher** [comment]
@kewchi hello! It seems like you're encountering an issue with a custom implementation for detecting objects within a polygon zone. The error message indicates that the `Detections` class does not have a `from_yolov8` method, which suggests that there might be a mismatch between the code you are using and the YOLOv8 API.

To resolve this, please ensure that you are using the correct method to process the results from the YOLOv8 model. The results returned by the model should be in a format that you can directly manipulate or filter according to your polygon zone logic. You might need to write a custom function to handle the conversion of YOLOv8 results to your desired `Detections` format.

For further guidance on handling model outputs and integrating custom post-processing steps, please refer to our documentation at https://docs.ultralytics.com. If you continue to face issues, consider opening an issue in the repo with a detailed description of the problem and the steps you've taken so far. Our community is always here to help! 😊
