### ISSUE TITLE
旋转的数据增强无效，8.0和8.1都无效。图片旋转了，label没做对应的改变

### ISSUE THREAD

**Issue by liuyiche** [ultralytics/ultralytics#7765]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Augmentation

### Bug

这是不带旋转的训练加载显示图片：
![yolov8_bug-不带旋转](https://github.com/ultralytics/ultralytics/assets/64673194/2b3fc479-d4d4-4502-8c2d-cf2be884a21b)
这是带旋转的训练加载显示图片：
![yolov8_bug-带旋转](https://github.com/ultralytics/ultralytics/assets/64673194/14ae22d8-4e21-4b06-94ee-09b167c99f6b)

### Environment

版本：8.1.5

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@liuyiche 感谢您的报告！我们了解到在使用旋转数据增强时，标签可能没有正确地与旋转后的图片对应。我们将会调查这个问题，并寻找解决方案。请持续关注我们的更新，我们会在修复后通知您。同时，如果您有任何进一步的信息或细节，欢迎补充到这个问题报告中。谢谢您对YOLOv8的支持！🛠️🔄
