### ISSUE TITLE
SAHI in yolo.eval?

### ISSUE THREAD

**Issue by johnnynunez** [ultralytics/ultralytics#7768]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

It could be interesting if in yolo eval exists the sahi option.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@johnnynunez hello! Thank you for your interest in YOLOv8 and for the feature suggestion regarding the integration of SAHI in the evaluation process. While SAHI (Slice and Herd Inference) is a great tool for handling large images by slicing them into smaller pieces, it's not currently a part of the YOLOv8 evaluation pipeline.

We always appreciate community feedback and ideas for improving the functionality and capabilities of YOLOv8. If you believe this feature would be beneficial, we encourage you to share more details about your use case in the issues section. This will help us understand the demand and potential impact of such an integration.

Although you've indicated that you're not willing to submit a PR, anyone in the community who feels confident in implementing this feature is welcome to contribute. We value collaborative development and contributions that enhance the YOLOv8 experience for all users. 🚀

For further discussions or to follow updates on this topic, please keep an eye on the issues section. Thanks again for your suggestion!
