### ISSUE TITLE
Add OpenVINO benchmarking code

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/ultralytics#777]
@glenn-jocher yes, it does! It's called benchmark_app and the example usage is in [this notebook](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/230-yolov8-optimization/230-yolov8-optimization.ipynb) under "Compare Performance of the Original and Quantized Models" section.
![image](https://user-images.githubusercontent.com/4547501/216338992-78cb2a9a-1724-48e5-b698-5245e3f58455.png)
I can see you measure latency, so you would need to add an additional flag `-hint latency`. More info [here](https://docs.openvino.ai/latest/openvino_inference_engine_samples_benchmark_app_README.html).

_Originally posted by @adrianboguszewski in https://github.com/ultralytics/ultralytics/issues/771#issuecomment-1413762950_

**Comment by adrianboguszewski** [comment]
@glenn-jocher I also recommend trying THROUGHPUT mode, as there are more features supporting more FPS. I'm attaching the comparison between latency and throughput modes.
![image](https://user-images.githubusercontent.com/4547501/216581203-2b5d0370-c3f5-446e-b224-544279df0463.png)
![image](https://user-images.githubusercontent.com/4547501/216581514-3c3aa96b-e5b0-4b79-bde3-ea8e5c5e70fe.png)
