### ISSUE TITLE
Default value of warmup_bias_lr with lr0 doesn't make sense

### ISSUE THREAD

**Issue by relotonp** [ultralytics/ultralytics#7782]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How warmup should work:
- At the start of the training, we use a low learning rate and increase it until it reaches the starting learning rate after `warmup_epochs`. The we use the regular scheduling of the learning rate.
 https://paperswithcode.com/method/linear-warmup
![](https://i.stack.imgur.com/Ujhvo.png)

How warmup is implemented in yolov8 (with default values):
- Default values are `warmup_bias_lr = 0.1` and `lr0=0.01` for SGD
-  If we analyze the code responsible for warmup in [trainer.py](https://github.com/ultralytics/ultralytics/blob/3c1170769a63068185a17f56229906440bee188e/ultralytics/engine/trainer.py#L367): 
` x['lr'] = np.interp(ni, xi, [self.args.warmup_bias_lr if j == 0 else 0.0, x['initial_lr'] * self.lf(epoch)])
`
This means, our initial learning rate at step 0 is `warmup_bias_lr `and for the following steps we interpolate to `lr0`. But in default values, `warmup_bias_lr `is larger than `lr0 `so the warmup is doing the opposite of what it should do, it starts large, at `0.1` and then goes down to `0.01`. 

Here is code implementation in colab where you can see that in default implementation, warmup is doing the opposite of what it should do
https://colab.research.google.com/drive/1QFIIWSSz8ydT5ExR-DXBuPbUfQDwpC8o?usp=sharing

**Comment by glenn-jocher** [comment]
@relotonp hello! Thank you for bringing this to our attention. The warmup phase is indeed intended to gradually increase the learning rate from a lower value to the base learning rate (`lr0`). The default values for `warmup_bias_lr` and `lr0` should reflect this behavior, with `warmup_bias_lr` being less than `lr0` to allow for a proper warmup.

It seems there might be a discrepancy in the default settings that you've pointed out. We will review the warmup implementation and the default values to ensure they align with the expected warmup strategy. Your feedback is valuable, and we appreciate the time you took to analyze and report this issue.

Please keep an eye on the repository for updates, and feel free to contribute further if you have additional insights or suggestions. The YOLO community and the Ultralytics team are always working together to improve the models and training procedures. 🚀
