### ISSUE TITLE
How to use Diou in the predict ?

### ISSUE THREAD

**Issue by htthienbrycen** [ultralytics/ultralytics#7787]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to use Diou instead of iou, what should I do?

**Comment by glenn-jocher** [comment]
@htthienbrycen hello! To use DIOU for bounding box regression during prediction with YOLOv8, you'll need to adjust the model's configuration file where the loss function is specified. Look for the `box` section in your YAML file and change the `loss` parameter to `CIoU`. This will enable the use of Complete Intersection over Union (CIoU), which includes DIOU. After making this change, retrain your model for the adjustments to take effect. For more details on configuring your model, please refer to our documentation at https://docs.ultralytics.com. Happy coding! 😊🚀
