### ISSUE TITLE
Train new data without forgetting old trained data

### ISSUE THREAD

**Issue by ngocducdim** [ultralytics/ultralytics#7790]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I have a question similar to this one ([https://github.com/ultralytics/yolov5/issues/11640](https://github.com/ultralytics/yolov5/issues/11640)), I have train the model to detect car plate with 300 images and saved as ``best.pt``, now I have new 800 car plate images, so how can I train model with new 800 car plate images without forgetting previous 300 trained images? thanks

**Comment by glenn-jocher** [comment]
@ngocducdim hello! To train your YOLOv8 model on the new 800 car plate images without forgetting the knowledge from the previous 300 images, you can perform what's known as "fine-tuning." You'll use the `best.pt` file from your initial training as a starting point for further training with the new dataset. This way, the model retains the learned features from the original dataset and continues to improve with the additional data.

When setting up your training command, make sure to specify the path to your `best.pt` file as the weights to load for training. This will initialize the model with the weights you've already trained, and it will continue to update from there. Remember to combine your old and new datasets or sequentially fine-tune on the new dataset after the old one. Check out our documentation on the Train mode for more details on how to proceed with fine-tuning your model. 😊🚗🔍
