### ISSUE TITLE
val does not seem to honor batch size

### ISSUE THREAD

**Issue by CySlider** [ultralytics/ultralytics#7798]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val

### Bug

I pass batch size 8 and try to evaluate an as .engine exported model for that batch size (dynamic=false, half=true)

But I end up getting this error:
`AssertionError: input size torch.Size([1, 3, 832, 832]) not equal to max model size (8, 3, 832, 832) `

Which seems to indicate that only a single image is being passed instead of a full batch.

Now writing this, I wonder if this is maybe because the images to evaluate are not a multiple of 8, so the last batch to be sent is not a full 8 image batch?

### Environment

Ultralytics YOLOv8.1.5 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (NVIDIA RTX A4000, 16109MiB)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CySlider** [comment]
Yes, looking at the code, I think this is the reason. I can easily fix this in my case by simply sticking with batch size 1 for evaluation, they are not time critical.

But may I suggest to either add a check, if the dataset is divisible by batch size and print an appropriate error message and mentioning the limitation, or better, add some padding data to fill the last batch to full size?

**Comment by glenn-jocher** [comment]
@CySlider, glad to hear you've found a workaround by using a batch size of 1 for evaluation. Your suggestion for improving user experience is appreciated. We'll consider adding a more informative error message or implementing a padding mechanism for the last batch in future updates. Thank you for your input, and please continue to share any further feedback or ideas you have! 🌟

**Comment by CySlider** [comment]
I found some free time and created a pull request after all, at least for the warning itself: https://github.com/ultralytics/ultralytics/pull/7846

**Comment by glenn-jocher** [comment]
@CySlider, thank you for taking the initiative to create a pull request! Your contribution is valuable to the community, and we'll review it soon. Keep up the great work! 🚀
