### ISSUE TITLE
How do I get the predicted class 

### ISSUE THREAD

**Issue by blahh6999** [ultralytics/ultralytics#7803]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

def yolo_prediction(video_path, stream=True):
    # Perform YOLO prediction
    results = model(video_path, stream=stream)

    # Extract relevant information from the Results object
    for result in results:
        id = result.probs.top1
    return id
    
This is the code that I am using. I want to get the predicted class in object classification Could you please provide me the code what I need to add. Thanks.

### Additional

I have to deploy this model on GCP.

**Comment by asebaq** [comment]
You can use something like this:
```
for result in results:
    id = result.probs.top1
    name = result.names[id]
```

**Comment by glenn-jocher** [comment]
@asebaq to obtain the predicted class names from your YOLOv8 model predictions, you can access the `names` attribute of the `results` object, which contains the class names indexed by their respective class IDs. After you retrieve the top1 class ID from `result.probs.top1`, you can use it to index into `results.names` to get the corresponding class name.

Remember to iterate over `results.xyxy` to get individual predictions, as `results` itself is a structured object containing various attributes. Each prediction in `results.xyxy` will have an associated class ID, which you can then use to find the class name.

For deployment on GCP or any other platform, ensure you comply with the licensing terms and choose the appropriate license for your use case. Good luck with your deployment! 🚀
