### ISSUE TITLE
Cannot Load YOLOv8 Model After torch.save(model, "model.pt")

### ISSUE THREAD

**Issue by paulguerrie** [ultralytics/ultralytics#7805]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Here's the order of operations that leads to an error: train model > load best.pt from trained model > save to a new pt file via `torch.save(...)` > attempt to load model with `YOLO(...)` > `AttributeError: 'YOLO' object has no attribute 'get'`

Full Stack Trace
```
Traceback (most recent call last):
  File "dev.py", line 21, in <module>
    model = YOLO("torch_saved.pt")
  File "/home/paguerrie/roboflow-train-env/lib/python3.8/site-packages/ultralytics/engine/model.py", line 96, in __init__
    self._load(model, task=task)
  File "/home/paguerrie/roboflow-train-env/lib/python3.8/site-packages/ultralytics/engine/model.py", line 162, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/home/paguerrie/roboflow-train-env/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 701, in attempt_load_one_weight
    args = {**DEFAULT_CFG_DICT, **(ckpt.get("train_args", {}))}  # combine model and default args, preferring model args
  File "/home/paguerrie/roboflow-train-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'YOLO' object has no attribute 'get'
```

### Environment

Ultralytics YOLOv8.1.5 🚀 Python-3.8.2 torch-2.1.2+cu121 CUDA:0 (Tesla T4, 14930MiB)
Setup complete ✅ (8 CPUs, 29.4 GB RAM, 187.3/491.9 GB disk)

OS                  Linux-4.19.0-26-cloud-amd64-x86_64-with-glibc2.28
Environment         Linux
Python              3.8.2
Install             pip
RAM                 29.45 GB
CPU                 Intel Xeon 2.30GHz
CUDA                12.1

matplotlib          ✅ 3.7.4>=3.3.0
numpy               ✅ 1.24.4>=1.22.2
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.1.2>=1.8.0
torchvision         ✅ 0.16.2>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.7
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.1>=0.11.0

### Minimal Reproducible Example

```
from ultralytics import YOLO
import torch

model = YOLO("yolov8n.pt")

model.train(
    data=f"PATH/TO/data.yaml",
    epochs=3,
    imgsz=640,
)

model = YOLO("./runs/detect/train/weights/best.pt")

torch.save(model, "torch_saved.pt")

model = YOLO("torch_saved.pt") # <<< This line yields "AttributeError: 'YOLO' object has no attribute 'get'"
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by paulguerrie** [comment]
Just noticed this is similar to a different unsolved issue: https://github.com/ultralytics/ultralytics/issues/6522

**Comment by glenn-jocher** [comment]
@paulguerrie hello! It seems like the issue you're encountering is related to the way the model is being saved and subsequently loaded. When you use `torch.save()` directly on the `YOLO` object, it doesn't save the model in the expected format that `YOLO()` is designed to load from.

Instead of using `torch.save()` on the `YOLO` object, you should save only the state dictionary of the model. This can be done by accessing the `.state_dict` attribute of the underlying model within the `YOLO` object. Then, when loading the model, you should create a new `YOLO` object and load the state dictionary into it.

Please refer to the documentation at https://docs.ultralytics.com for the correct way to save and load models using the YOLOv8 API. This will ensure compatibility and prevent the `AttributeError` you're experiencing. If the issue persists after following the documented procedures, please let us know, and we'll be happy to assist further. Thank you for your contribution to the YOLOv8 community! 🚀

**Comment by paulguerrie** [comment]
The code above uses the save/load methods referenced here: https://github.com/ultralytics/ultralytics/issues/5163#issuecomment-1741469327 so it seems like what I posted should work.

**Comment by glenn-jocher** [comment]
@paulguerrie ok got it, I'll take a look!

**Comment by glenn-jocher** [comment]
@paulguerrie yes I'm able to reproduce. I'll see what I can do here. Seems like it might make sense to provide a model.save() method also to facilitate saving, like PIL's .save() method.

**Comment by glenn-jocher** [comment]
The strange thing is this code works correctly:

```python
import torch
from ultralytics import YOLO

model = YOLO("yolov8n.pt")
torch.save(model, "torch_saved1.pt")
model2 = torch.load("torch_saved1.pt")
```

**Comment by paulguerrie** [comment]
Hey @glenn-jocher , that seems to fix it for me! My dev script runs without error now.

**Comment by glenn-jocher** [comment]
@paulguerrie Great to hear that the fix worked for you! If you encounter any more issues or have further questions, feel free to reach out. Happy coding! 🚀
