### ISSUE TITLE
Trying to get X and Y coordinate values from the top left of the bounding boxes

### ISSUE THREAD

**Issue by arjunnirgudkar** [ultralytics/ultralytics#7806]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

This is my code: 

from ultralytics import YOLO

model = YOLO('yolov8n.pt')

results = model.predict(source="0", show=True, classes=0, conf=0.7)

results.show()

I tried extracting the x and y value but the output still remained the same like this:

0: 384x640 1 person, 49.2ms
0: 384x640 1 person, 50.5ms
0: 384x640 1 person, 50.3ms
0: 384x640 1 person, 48.5ms
0: 384x640 1 person, 53.6ms
0: 384x640 1 person, 57.5ms
0: 384x640 1 person, 55.4ms
0: 384x640 1 person, 54.3ms
0: 384x640 1 person, 52.0ms
0: 384x640 1 person, 55.4ms

I want it to output the x and y value along with this information for each person in the frame
Thanks!

**Comment by glenn-jocher** [comment]
@arjunnirgudkar hello! To extract the X and Y coordinate values from the top left of the bounding boxes, you'll want to access the `xyxy` attribute of the `results` object. This attribute contains the bounding box coordinates in the format `(x1, y1, x2, y2, confidence, class)`, where `(x1, y1)` represents the top-left corner of the bounding box.

After running `model.predict()`, you can iterate over `results.xyxy[0]` to get the coordinates for each detection. Here's a brief explanation:

- Iterate over `results.xyxy[0]` to get each detection.
- For each detection, extract the first two values, which correspond to the X and Y coordinates of the top-left corner.

This will give you the desired X and Y values for each person detected in the frame. For more details on working with the results, you can refer to the Predict mode documentation on our Ultralytics Docs. 😊
