### ISSUE TITLE
Does yolov8 support multi-datasets training?

### ISSUE THREAD

**Issue by Mactarvish** [ultralytics/ultralytics#7808]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Usually we have multi datasets for training, does yolov8 support multi datasets training like mmdetection ? e.g. given a list of train paths:
```
path: [coco128, coco256]
```

### Use case

Supporting multi datasets training will be pretty convenient for real project develop as we shall receive new annotated-data as time goes by and we're not supposed to put them all together because it would be hard to manage.

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Mactarvish yes, YOLOv8 does support multi-dataset training. You can combine different datasets by specifying their paths in your training configuration file. This allows you to incrementally add new datasets as they become available, facilitating easier data management and more robust model training. If you're ready to contribute, we welcome a PR to enhance this functionality further. For detailed instructions on setting up your training configuration, please refer to our documentation on the Train mode. Happy training! 😊🚀
