### ISSUE TITLE
Why does RT-DETR only have l and x models? How do I get the models I need for s and m?

### ISSUE THREAD

**Issue by Sparklexa** [ultralytics/ultralytics#7811]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why does RT-DETR only have l and x models? How do I get the models I need for s and m?

### Additional

![image](https://github.com/ultralytics/ultralytics/assets/150432487/0df39481-75dd-4e32-a027-5be8813bca4d)

**Comment by glenn-jocher** [comment]
@Sparklexa hello! The RT-DETR currently offers 'l' (large) and 'x' (extra-large) models to cater to use cases requiring higher accuracy and complexity. If you're looking for 's' (small) and 'm' (medium) variants, these are not provided at the moment. However, you can train your own 's' and 'm' models using the provided training scripts and your dataset to fit your specific requirements. For guidance on training your own models, please refer to our training documentation at https://docs.ultralytics.com/modes/train. 😊🚀

**Comment by n0ngalaxy** [comment]
Hi, did you manage to resolve this?

**Comment by glenn-jocher** [comment]
@n0ngalaxy hi there! If you're still encountering the issue, could you provide a bit more detail on what you're experiencing? I'm here to help! 😊🛠️

**Comment by Sparklexa** [comment]
no
&nbsp;


Sparkle
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月20日(星期二) 晚上6:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ultralytics/ultralytics] Why does RT-DETR only have l and x models? How do I get the models I need for s and m? (Issue #7811)






你解决了吗

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
你收到这个是因为你被提到了。消息ID:<超分析学/超分析/问题/ 7811 / ***@***.***和&gt;

**Comment by glenn-jocher** [comment]
@Sparklexa hey Sparkle! 🌟

It looks like there might have been a bit of confusion in the communication. If you're asking about obtaining 's' (small) and 'm' (medium) models for RT-DETR, as mentioned earlier, these specific sizes are not directly available. However, you can train models tailored to your needs using our training scripts. If you need further assistance or have more questions, feel free to ask!

Happy coding! 😊
