### ISSUE TITLE
Yolov8-OBB save_crop is not supported

### ISSUE THREAD

**Issue by KTXKIKI** [ultralytics/ultralytics#7812]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hello, may I ask if there will be an update to the yolov8 rotation box cropping image save in the future_ Crap? Currently, the company's project needs to be joined. It would be really great if we could join

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@KTXKIKI hello! Thank you for reaching out with your feature request regarding the `save_crop` functionality for oriented bounding boxes (OBB) in YOLOv8.

As of now, YOLOv8 does not support `save_crop` for rotation boxes directly within the repository. However, we are always looking to improve and add features that the community finds valuable. Your suggestion has been noted, and while I can't provide a specific timeline for this feature, we do consider community feedback as part of our development process.

In the meantime, you might consider implementing a custom solution for cropping OBBs from your detection results. We appreciate your understanding and are glad to see the interest in extending YOLOv8's capabilities. Keep an eye on our updates, and feel free to check out our documentation for the latest features and enhancements. 😊🚀

**Comment by Houangnt** [comment]
@KTXKIKI You can try the code below, which will crop all objects detected by YOLOv8OBB to vertical or horizontal images.
![Uploading image.png…]()

**Comment by Houangnt** [comment]
https://github.com/Houangnt/yolov8_tracking/blob/main/save_crop_obb.py. Full code is here
