### ISSUE TITLE
yolov8 obb post-processing part

### ISSUE THREAD

**Issue by zhangshabao** [ultralytics/ultralytics#7817]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My post-processing code is as follows ：     
        float *data = (float *)result.data;
        std::vector<int> class_ids;
        std::vector<float> confidences;

        for (int i = 0; i < dimensions; ++i)
        {
            float* classesScores = data + 4;
            cv::Mat scores(1, num_class, CV_32FC1, classesScores);
            cv::Point class_id;
            double maxClassScore;
            cv::minMaxLoc(scores, 0, &maxClassScore, 0, &class_id);
            
            if (maxClassScore < conf_thr)
                continue;
            TextBox object_;
            // confidences.push_back(maxClassScore);
            // class_ids.push_back(class_id.x);

            double x = data[0];
            double y = data[1];
            double w = data[2];
            double h = data[3];
            int left = int((x - 0.5 * w) * scaleParam.ratioWidth);
            int top = int((y - 0.5 * h) * scaleParam.ratioWidth);
            int width = int(w * scaleParam.ratioWidth);
            int height = int(h * scaleParam.ratioWidth);
            // float theta_pred = data[5];
            float r=data[rows-1];            
            if (r>=pi && r <= 0.75*pi)
            {
                r=r-pi;
            } 
            cv::RotatedRect rotatedRect=cv::RotatedRect(cv::Point2f(x,y),cv::Size2f(w,h),r*180/pi);
            cv::Point2f points[4];
            rotatedRect.points(points);

            // Convert the corner points to a vector of cv::Point
            std::vector<cv::Point> cornerPoints;
            for (int i = 0; i < 4; i++) {
                cornerPoints.push_back(points[i]);
            }
            object_.score = 0.1;
            object_.idx = class_id.x;
            object_.x1 = left;
            object_.y1 = top;
            object_.w = width;
            object_.h = height;
            object_.r = r;
            // object_.boxPoint = points;
            object_.boxPoint = cornerPoints;
            obj_vec.push_back(object_);

            data += rows;
        }
        sort(obj_vec.begin(), obj_vec.end(), compareObjByScore);
        std::vector<int> picked;
        nms_rotated(obj_vec, picked, iou_thr);
        DEBUG_LOG("picked:%d",picked.size());
         // 旋转目标检测
    void convariance_matrix(float w, float h, float r, float &a, float &b, float &c)
    {
        float a_val = w * w / 12.0f;
        float b_val = h * h / 12.0f;
        float cos_r = cosf(r);
        float sin_r = sinf(r);

        a = a_val * cos_r * cos_r + b_val * sin_r * sin_r;
        b = a_val * sin_r * sin_r + b_val * cos_r * cos_r;
        c = (a_val - b_val) * sin_r * cos_r;
    }

    // float box_probiou(
    //     float cx1, float cy1, float w1, float h1, float r1,
    //     float cx2, float cy2, float w2, float h2, float r2,
    //     float eps = 1e-7)
    float box_probiou(const TextBox &obj1, const TextBox &obj2)
    {
        float eps = 1e-7;
        float cx1 = obj1.x1, cy1 = obj1.x2, w1 = obj1.w, h1 = obj1.h, r1 = obj1.r;
        float cx2 = obj2.x1, cy2 = obj2.x2, w2 = obj2.w, h2 = obj2.h, r2 = obj2.r;
        // Calculate the prob iou between oriented bounding boxes, https://arxiv.org/pdf/2106.06072v1.pdf.
        float a1, b1, c1, a2, b2, c2;
        convariance_matrix(w1, h1, r1, a1, b1, c1);
        convariance_matrix(w2, h2, r2, a2, b2, c2);

        float t1 = ((a1 + a2) * powf(cy1 - cy2, 2) + (b1 + b2) * powf(cx1 - cx2, 2)) / ((a1 + a2) * (b1 + b2) - powf(c1 + c2, 2) + eps);
        float t2 = ((c1 + c2) * (cx2 - cx1) * (cy1 - cy2)) / ((a1 + a2) * (b1 + b2) - powf(c1 + c2, 2) + eps);
        float t3 = logf(((a1 + a2) * (b1 + b2) - powf(c1 + c2, 2)) / (4 * sqrtf(fmaxf(a1 * b1 - c1 * c1, 0.0f)) * sqrtf(fmaxf(a2 * b2 - c2 * c2, 0.0f)) + eps) + eps);
        float bd = 0.25f * t1 + 0.5f * t2 + 0.5f * t3;
        bd = fmaxf(fminf(bd, 100.0f), eps);
        float hd = sqrtf(1.0f - expf(-bd) + eps);
        return 1 - hd;
    }
but i can't get correct result

**Comment by glenn-jocher** [comment]
@zhangshabao hello! It seems like you're working on post-processing for oriented bounding boxes (OBB) with YOLOv8 detections. If you're not getting the correct results, here are a few things to consider:

1. **Validation of Inputs**: Ensure that the input data to your post-processing function is correct. This includes the bounding box coordinates, class scores, and any other model outputs.

2. **Coordinate System**: Verify that the coordinate system used by the model matches the one expected by your post-processing code. YOLOv8 typically outputs normalized coordinates, which you may need to scale to your image dimensions.

3. **Thresholds**: Double-check your confidence and IoU thresholds. If they are set too high, you might be filtering out valid detections.

4. **Angle Representation**: Make sure the angle 'r' is being interpreted correctly. The model might output angles in a different range or format than your post-processing expects.

5. **NMS Algorithm**: Ensure that your Non-Maximum Suppression (NMS) algorithm is adapted for OBBs. Traditional NMS is for axis-aligned boxes and might not work correctly for rotated rectangles.

6. **Mathematical Operations**: Review all mathematical operations, especially those involving angles and trigonometry, for potential errors or assumptions.

For further guidance, you might want to refer to the documentation on the Predict and Export modes, which could provide additional insights into handling model outputs. If the issue persists, consider providing more context or examples (without code) in the discussions section for community support. Good luck! 🚀

**Comment by zhangshabao** [comment]
Is there a c++ version of onnx inference that provides the obb version?

**Comment by glenn-jocher** [comment]
@zhangshabao hello! Currently, we do not provide a C++ version of ONNX inference specifically for OBB (oriented bounding boxes) in the YOLOv8 repository. However, you can use the ONNX model with a C++ ONNX runtime and implement the OBB post-processing manually. For guidance on exporting models and understanding outputs, please refer to the Export mode documentation. 📘

**Comment by kaunghtetsan275** [comment]
When I try to print the output from YOLOv8-OBB head, the bounding box coordinates are not normalized (they are not within 0 t0 1). When you trained OBB model, do you just use x,y,w,h,r without any normalization?

**Comment by kaunghtetsan275** [comment]
>     2. **Coordinate System**: Verify that the coordinate system used by the model matches the one expected by your post-processing code. YOLOv8 typically outputs normalized coordinates, which you may need to scale to your image dimensions.

When I try to print the output from YOLOv8-OBB head, the bounding box coordinates are not normalized (they are not within 0 to 1). When you trained OBB model, do you just use x,y,w,h,r without any normalization?

**Comment by glenn-jocher** [comment]
@kaunghtetsan275 hello! 😊 For the YOLOv8-OBB model, the outputs, including the oriented bounding box (OBB) parameters (x, y, w, h, r), are indeed designed to be directly usable and correspond to the actual dimensions in the image space, rather than being normalized to the range [0, 1]. This approach simplifies post-processing steps, allowing you to work with the coordinates without the need for additional scaling based on image dimensions. 

If you're working with these outputs and need them in a normalized form for any reason, you can easily normalize them by dividing by the respective image width or height. Here's a quick example:

```cpp
// Assuming 'x', 'y', 'w', and 'h' are your OBB outputs, and 'img_width' & 'img_height' are the dimensions of your image
float normalized_x = x / img_width;
float normalized_y = y / img_height;
float normalized_w = w / img_width;
float normalized_h = h / img_height;
```

Hope this clears things up! Let us know if you have any more questions.
