### ISSUE TITLE
Resize failure when running custom model on image data

### ISSUE THREAD

**Issue by wjnicol** [ultralytics/ultralytics#7825]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I am trying to run a custom YOLOv8 model trained on 1024x1024 jpg images.

I am now trying to run inferences on 1024x1024 mrc files. My current code opens the mrc file stack:

`with mrcfile.open(atlas, permissive=True) as mrc:
    # Access the data in the MRC file
    npAtlas = mrc.data`

I then have a npArray of size 49, 1024, 1024 (49 images of size 1024x1024)

When I run the model on this array, it throws an array that seems to be complaining about ""!dsize.empty().":

`error                                     Traceback (most recent call last)
Cell In[50], [line 2](vscode-notebook-cell:?execution_count=50&line=2)
      [1](vscode-notebook-cell:?execution_count=50&line=1) Model = WGModel()
----> [2](vscode-notebook-cell:?execution_count=50&line=2) results = Model.model(npAtlas)

File [c:\Users\William](file:///C:/Users/William) J Nicolas\miniconda3\envs\Pytorch\Lib\site-packages\ultralytics\engine\model.py:102, in Model.__call__(self, source, stream, **kwargs)
    [100](file:///C:/Users/William%20J%20Nicolas/miniconda3/envs/Pytorch/Lib/site-packages/ultralytics/engine/model.py:100) def __call__(self, source=None, stream=False, **kwargs):
    [101](file:///C:/Users/William%20J%20Nicolas/miniconda3/envs/Pytorch/Lib/site-packages/ultralytics/engine/model.py:101)     """Calls the predict() method with given arguments to perform object detection."""
--> [102](file:///C:/Users/William%20J%20Nicolas/miniconda3/envs/Pytorch/Lib/site-packages/ultralytics/engine/model.py:102)     return self.predict(source, stream, **kwargs)

File [c:\Users\William](file:///C:/Users/William) J Nicolas\miniconda3\envs\Pytorch\Lib\site-packages\ultralytics\engine\model.py:275, in Model.predict(self, source, stream, predictor, **kwargs)
    [273](file:///C:/Users/William%20J%20Nicolas/miniconda3/envs/Pytorch/Lib/site-packages/ultralytics/engine/model.py:273) if prompts and hasattr(self.predictor, "set_prompts"):  # for SAM-type models
    [274](file:///C:/Users/William%20J%20Nicolas/miniconda3/envs/Pytorch/Lib/site-packages/ultralytics/engine/model.py:274)     self.predictor.set_prompts(prompts)
--> [275](file:///C:/Users/William%20J%20Nicolas/miniconda3/envs/Pytorch/Lib/site-packages/ultralytics/engine/model.py:275) return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)

File [c:\Users\William](file:///C:/Users/William) J Nicolas\miniconda3\envs\Pytorch\Lib\site-packages\ultralytics\engine\predictor.py:204, in BasePredictor.__call__(self, source, model, stream, *args, **kwargs)
    [202](file:///C:/Users/William%20J%20Nicolas/miniconda3/envs/Pytorch/Lib/site-packages/ultralytics/engine/predictor.py:202)     return self.stream_inference(source, model, *args, **kwargs)
    [203](file:///C:/Users/William%20J%20Nicolas/miniconda3/envs/Pytorch/Lib/site-packages/ultralytics/engine/predictor.py:203) else:
--> [204](file:///C:/Users/William%20J%20Nicolas/miniconda3/envs/Pytorch/Lib/site-packages/ultralytics/engine/predictor.py:204)     return list(self.stream_inference(source, model, *args, **kwargs))

File [c:\Users\William](file:///C:/Users/William) J Nicolas\miniconda3\envs\Pytorch\Lib\site-packages\torch\utils\_contextlib.py:35, in _wrap_generator.<locals>.generator_context(*args, **kwargs)
     [32](file:///C:/Users/William%20J%20Nicolas/miniconda3/envs/Pytorch/Lib/site-packages/torch/utils/_contextlib.py:32) try:
     [33](file:///C:/Users/William%20J%20Nicolas/miniconda3/envs/Pytorch/Lib/site-packages/torch/utils/_contextlib.py:33)     # Issuing `None` to a generator fires it up
     [34](file:///C:/Users/William%20J%20Nicolas/miniconda3/envs/Pytorch/Lib/site-packages/torch/utils/_contextlib.py:34)     with ctx_factory():
...
    [728](file:///C:/Users/William%20J%20Nicolas/miniconda3/envs/Pytorch/Lib/site-packages/ultralytics/data/augment.py:728) top, bottom = int(round(dh - 0.1)) if self.center else 0, int(round(dh + 0.1))
    [729](file:///C:/Users/William%20J%20Nicolas/miniconda3/envs/Pytorch/Lib/site-packages/ultralytics/data/augment.py:729) left, right = int(round(dw - 0.1)) if self.center else 0, int(round(dw + 0.1))

error: OpenCV(4.9.0) [D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:3789](file:///D:/a/opencv-python/opencv-python/opencv/modules/imgproc/src/resize.cpp:3789): error: (-215:Assertion failed) !dsize.empty() in function 'cv::hal::resize'`

I thought it could be because I'm feeding mrc files but they are converted to an np.array so this shouldn't be the issue. I do not how to proceed further and format my images properly for YOLO to be happy.

Please help.

William J Nicolas

**Comment by glenn-jocher** [comment]
@wjnicol hello William,

It seems like you're encountering an issue with image resizing during inference with your custom YOLOv8 model. The error message you're seeing typically indicates that OpenCV is expecting a certain image size but is receiving something different.

When you're preparing your images for inference, ensure that each image is individually formatted as expected by the model. YOLOv8 expects images to be in a certain shape and format, typically as a single image or a batch of images with the shape `(batch_size, height, width, channels)`.

Since you're working with a numpy array of shape `(49, 1024, 1024)`, you might need to add a channel dimension to it, assuming these are grayscale images. You can do this by reshaping your array to `(49, 1024, 1024, 1)` before passing it to the model.

Also, make sure that the images are properly normalized if required by your model's training configuration.

If the issue persists, you might want to check the documentation on the Predict mode for further guidance on how to properly format your images for inference.

**Comment by wjnicol** [comment]
Hello,

Thank you for the response. It is helpful in unuderstanding the structure needed and I did go through the predict page quite thoroughly. I however, haven't fixed my problem.

I will explain my code a little better.

I am currently loading a stack of .mrc images using the mrcfile module:

> with mrcfile.open(atlas, permissive=True) as mrc:
>     # Access the data in the MRC file
>     npAtlas = mrc.data where "atlas" is a path pointing to the .mrc file.

There is a software out there doing something similar to what I'm trying to do so I've been looking into how they are doing it. Before feeding the .mrc tiles to the model, they apply dstack to it and I don't understand the intent behind this

> tile = np.dstack((tile,tile,tile))

When I look at the structure of my imported data and try to replicate the np.dstack step:

> print(f"shape of npAtlas is {npAtlas.shape}")
> print(f"shape of the third dimension of npAtlas is {npAtlas.shape[2]}")
> print(f"type of data in npAtlas is {npAtlas.dtype}")
> plt.imshow(npAtlas[0], cmap = 'gray') --> Shows the image with index 0
> 
> npAtlas_dstack = np.dstack((npAtlas, npAtlas, npAtlas))
> print(f"shape of npAtlas_dstack is {npAtlas_dstack.shape}")
> print(f"shape of the third dimension of npAtlas_dstack is {npAtlas_dstack.shape[2]}")

The output is: 

> shape of npAtlas is (49, 1024, 1024)
> shape of the third dimension of npAtlas is 1024
> type of data in npAtlas is int16
> shape of npAtlas_dstack is (49, 1024, 3072)
> shape of the third dimension of npAtlas_dstack is 3072

Looking up the doc of dstack function and the result of my command, it seems it just replicated the 3D array along the third dimension making it another 3D array with the third dimension 3 times as long. I don't understand the use of this step.

Now when I feed this to the model, I get the same error I mentionned in the original post.

I also tried adding an additional channel as you suggested for the gray scale channel. I wasn't sure how to do this and ended up doing this:

> npAtlas_new = npAtlas_dstack[:, :, :,np.newaxis]
> print(npAtlas_new.shape)
> print(npAtlas_new[3].shape)

The output being:

> (49, 1024, 3072, 1)
> (1024, 3072, 1)

Running the model on this new array still creates the same error. I have the feeling I am not creating the channel array in a correct manner.

Thanks,

**Comment by wjnicol** [comment]
**Update**

After converting the array to uint8 (it was originally int16):

> #Normalizing the int16 values in npAtlas
> npAtlas_norm = (npAtlas - np.min(npAtlas))/(np.max(npAtlas) - np.min(npAtlas))
> 

> #Convert to uint8
> npAtlas_uint8 = (npAtlas_norm * 255).astype(np.uint8)
> 
> print(npAtlas_norm.shape)
> print(npAtlas_norm.dtype)
> 
> print(npAtlas_uint8.shape)
> print(npAtlas_uint8.dtype)
> 
> plt.imshow(npAtlas_uint8[0], cmap = 'gray')

I still get the same error.

Now If instead of passing the whole array, I specify only one image (`npAtlas_uint8[0]`), I get a slightly different error where it seems it is confused with the axies of the array.

> {
> 	"name": "ValueError",
> 	"message": "axes don't match array",
> 	"stack": "---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> Cell In[31], line 1
> ----> 1 results = Model.model(npAtlas_uint8[0])
> 
> File c:\\Users\\William J Nicolas\\miniconda3\\envs\\Pytorch\\Lib\\site-packages\\ultralytics\\engine\\model.py:102, in Model.__call__(self, source, stream, **kwargs)
>     100 def __call__(self, source=None, stream=False, **kwargs):
>     101     \"\"\"Calls the predict() method with given arguments to perform object detection.\"\"\"
> --> 102     return self.predict(source, stream, **kwargs)
> 
> File c:\\Users\\William J Nicolas\\miniconda3\\envs\\Pytorch\\Lib\\site-packages\\ultralytics\\engine\\model.py:275, in Model.predict(self, source, stream, predictor, **kwargs)
>     273 if prompts and hasattr(self.predictor, \"set_prompts\"):  # for SAM-type models
>     274     self.predictor.set_prompts(prompts)
> --> 275 return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
> 
> File c:\\Users\\William J Nicolas\\miniconda3\\envs\\Pytorch\\Lib\\site-packages\\ultralytics\\engine\\predictor.py:204, in BasePredictor.__call__(self, source, model, stream, *args, **kwargs)
>     202     return self.stream_inference(source, model, *args, **kwargs)
>     203 else:
> --> 204     return list(self.stream_inference(source, model, *args, **kwargs))
> 
> File c:\\Users\\William J Nicolas\\miniconda3\\envs\\Pytorch\\Lib\\site-packages\\torch\\utils\\_contextlib.py:35, in _wrap_generator.<locals>.generator_context(*args, **kwargs)
>      32 try:
>      33     # Issuing `None` to a generator fires it up
>      34     with ctx_factory():
> ---> 35         response = gen.send(None)
>      37     while True:
>      38         try:
>      39             # Forward the response to our caller and get its next request
> 
> File c:\\Users\\William J Nicolas\\miniconda3\\envs\\Pytorch\\Lib\\site-packages\\ultralytics\\engine\\predictor.py:279, in BasePredictor.stream_inference(self, source, model, *args, **kwargs)
>     277 # Preprocess
>     278 with profilers[0]:
> --> 279     im = self.preprocess(im0s)
>     281 # Inference
>     282 with profilers[1]:
> 
> File c:\\Users\\William J Nicolas\\miniconda3\\envs\\Pytorch\\Lib\\site-packages\\ultralytics\\engine\\predictor.py:123, in BasePredictor.preprocess(self, im)
>     121 if not_tensor:
>     122     im = np.stack(self.pre_transform(im))
> --> 123     im = im[..., ::-1].transpose((0, 3, 1, 2))  # BGR to RGB, BHWC to BCHW, (n, 3, h, w)
>     124     im = np.ascontiguousarray(im)  # contiguous
>     125     im = torch.from_numpy(im)
> 
> ValueError: axes don't match array"

}

**Comment by glenn-jocher** [comment]
@wjnicol, it appears that the issue is related to the image dimensions and data type expected by the model. When you pass a single image (`npAtlas_uint8[0]`), ensure that it has the correct shape `(height, width, channels)`. For a grayscale image, you should add a channel dimension to make it `(1024, 1024, 1)` before passing it to the model. Also, ensure that the image is in the correct format (uint8) and normalized if necessary.

If you're still encountering errors, it might be helpful to verify that each image is preprocessed in the same way as your training data was prepared. This includes resizing, normalization, and adding a channel dimension for grayscale images. The model expects a batch of images with the shape `(batch_size, channels, height, width)`, so you may need to adjust the dimensions accordingly before inference.

**Comment by wjnicol** [comment]
Hello,

So I reran it just now: `results = Model.model(npAtlas_channel[0])` npAtlas_channel[0] being of type uint8 and of format (1024,1024,1) and the data is normalized between 1 and 255 (the npAltas_uint8 array)

I get the same output error as shown above (axes don't match error).

The model was trained on png images of different formats, converted from grayscale .mrc. I just checked and the training images are all 8bit. 
I thought the model was agnostic of the channels and could generalize to any kind of image/tensor.

There is a project that did something similar to what I'm trying to do (SPACEtomo - https://github.com/eisfabian/SPACEtomo), I tested and it works and they trained the model on png images and it works when it's fed .mrc files.

> If you're still encountering errors, it might be helpful to verify that each image is preprocessed in the same way as your training data was prepared.

The training data comes from a variety of different sources (at least 2) so image acquisition, formats and perhaps pre-processing is different. This doesn't seem to be a problem in the above mentioned project (SPACEtomo).

> This includes resizing, normalization, and adding a channel dimension for grayscale images. The model expects a batch of images with the shape (batch_size, channels, height, width), so you may need to adjust the dimensions accordingly before inference.

Here you say the model expects images in the shape BCHW. i thought by reading docs and your previous answer that it should be formatted BHWC. I am confused as to how it should be formatted. I'll try formatting it BCHW to see if it works.

Thank you for your help,

William J Nicolas

**Comment by glenn-jocher** [comment]
@wjnicol hello William,

The error you're encountering suggests that the image tensor is not in the expected format for the model. YOLOv8 indeed expects the input tensor to be in the BCHW format (batch size, channels, height, width) when passed to the model for inference.

Since your model was trained on 8-bit PNG images, ensure that your input images are also 8-bit and follow the same preprocessing steps as during training. If the training data came from various sources with different preprocessing, it's crucial to apply the same preprocessing to your new data before inference.

If you're still facing issues, consider revisiting the preprocessing steps used in the SPACEtomo project and ensure that your preprocessing pipeline is consistent with theirs, as model performance can be sensitive to these details.
