### ISSUE TITLE
Some NCCL operations have failed or timed out.

### ISSUE THREAD

**Issue by tamanna-mostafa** [ultralytics/ultralytics#7829]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I got the following error when running supervised fine tuning of LLAMA2-7b model on P4 instance.
Command run:

`deepspeed trainer_sft.py --configs llama2-7b-sft-RLAIF  --wandb-entity tammosta  --show_dataset_stats --deepspeed`

Error: 
```
Loading extension module cpu_adam...
Time to load cpu_adam op: 31.37122869491577 seconds
[E ProcessGroupNCCL.cpp:475] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=880, OpType=BROADCAST, NumelIn=131137536, NumelOut=131137536, Timeout(ms)=1800000) ran for 1800648 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:475] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=880, OpType=BROADCAST, NumelIn=131137536, NumelOut=131137536, Timeout(ms)=1800000) ran for 1800798 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:475] [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=880, OpType=BROADCAST, NumelIn=131137536, NumelOut=131137536, Timeout(ms)=1800000) ran for 1800799 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:475] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=880, OpType=BROADCAST, NumelIn=131137536, NumelOut=131137536, Timeout(ms)=1800000) ran for 1800782 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:475] [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=880, OpType=BROADCAST, NumelIn=131137536, NumelOut=131137536, Timeout(ms)=1800000) ran for 1800927 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:475] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=880, OpType=BROADCAST, NumelIn=131137536, NumelOut=131137536, Timeout(ms)=1800000) ran for 1800816 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:475] [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=880, OpType=BROADCAST, NumelIn=131137536, NumelOut=131137536, Timeout(ms)=1800000) ran for 1800840 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:489] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:495] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:916] [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=880, OpType=BROADCAST, NumelIn=131137536, NumelOut=131137536, Timeout(ms)=1800000) ran for 1800816 milliseconds before timing out.
terminate called after throwing an instance of 'std::runtime_error'
```
I tried creating a new venv and running the command there, but got the same error. I also tried the methods suggested [here ](https://github.com/ultralytics/ultralytics/issues/1439) with no luck. Any idea what's causing this?

### Environment

transformers version: 4.35.2
Platform: Linux-5.15.0-1050-aws-x86_64-with-glibc2.31
Python version: 3.10.12
Huggingface_hub version: 0.20.2
Safetensors version: 0.4.1
Accelerate version: 0.26.1
Accelerate config: not found
PyTorch version (GPU?): 2.1.2+cu121 (True)
Tensorflow version (GPU?): not installed (NA)
Flax version (CPU?/GPU?/TPU?): not installed (NA)
Jax version: not installed
JaxLib version: not installed

### Minimal Reproducible Example

`deepspeed trainer_sft.py --configs llama2-7b-sft-RLAIF  --wandb-entity tammosta  --show_dataset_stats --deepspeed`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@tamanna-mostafa hello! It seems you're encountering a timeout issue with NCCL during your fine-tuning process. This error typically indicates that the collective operations across your GPUs are not synchronizing within the expected time frame. Here are a few steps you might consider:

1. **Check GPU Utilization**: Ensure that all GPUs are properly utilized and that there's no GPU that's disproportionately slow or unresponsive.
2. **Network Bandwidth**: If you're running on a multi-node setup, verify that the interconnect bandwidth is sufficient and not causing bottlenecks.
3. **NCCL Debugging**: You can set the environment variable `NCCL_DEBUG=INFO` to get more detailed logs from NCCL which might help pinpoint the issue.
4. **Software Versions**: Ensure that the versions of NCCL, CUDA, and PyTorch are compatible and up-to-date.
5. **Resource Limits**: Check if there are any system resource limits that might be causing the operations to timeout, such as ulimits or other system quotas.

If the issue persists, please provide additional context regarding your setup, such as the number of nodes and GPUs being used, and any other relevant configuration details. This will help us better understand the problem and assist you further.

For more detailed guidance on each mode and task supported by YOLOv8, you can refer to our documentation at https://docs.ultralytics.com.

**Comment by tamanna-mostafa** [comment]
Thanks for your comment. Could you please tell me how I can do #1, #2, and #4?

**Comment by glenn-jocher** [comment]
@tamanna-mostafa certainly! Here's how you can address points #1, #2, and #4:

1. **Check GPU Utilization**: Use the command `nvidia-smi` to monitor GPU utilization and memory usage in real-time. Look for any GPUs that are not being fully utilized or have memory issues.

2. **Network Bandwidth**: If you're using a multi-node setup, check the network bandwidth using tools like `ibstat` for InfiniBand or `ifconfig` for Ethernet to ensure there are no network bottlenecks.

4. **Software Versions**: Verify the compatibility of your software stack by checking the versions of NCCL, CUDA, and PyTorch. Use commands like `nvcc --version` for CUDA, `nvidia-smi` for driver version, and `python -c 'import torch; print(torch.__version__)'` for PyTorch. Update them if necessary to ensure they are compatible with each other.

For further details on each step, you can refer to the documentation and troubleshooting guides provided by the respective software or hardware vendors.

**Comment by tamanna-mostafa** [comment]
@glenn-jocher 
When I check GPU utilization while a fine-tuning is running, I see this:

```
ubuntu@ip-172-31-43-11:~$ nvidia-smi
Mon Jan 29 23:17:37 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.12             Driver Version: 535.104.12   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-40GB          On  | 00000000:10:1C.0 Off |                    0 |
| N/A   26C    P0              70W / 400W |   2987MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM4-40GB          On  | 00000000:10:1D.0 Off |                    0 |
| N/A   25C    P0              77W / 400W |   2529MiB / 40960MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM4-40GB          On  | 00000000:20:1C.0 Off |                    0 |
| N/A   27C    P0              87W / 400W |   2529MiB / 40960MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM4-40GB          On  | 00000000:20:1D.0 Off |                    0 |
| N/A   24C    P0              78W / 400W |   2529MiB / 40960MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   4  NVIDIA A100-SXM4-40GB          On  | 00000000:90:1C.0 Off |                    0 |
| N/A   27C    P0              77W / 400W |   2529MiB / 40960MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   5  NVIDIA A100-SXM4-40GB          On  | 00000000:90:1D.0 Off |                    0 |
| N/A   24C    P0              75W / 400W |   2529MiB / 40960MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   6  NVIDIA A100-SXM4-40GB          On  | 00000000:A0:1C.0 Off |                    0 |
| N/A   26C    P0              80W / 400W |   2529MiB / 40960MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   7  NVIDIA A100-SXM4-40GB          On  | 00000000:A0:1D.0 Off |                    0 |
| N/A   25C    P0              83W / 400W |   2385MiB / 40960MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A    114838      C   /opt/conda/envs/ml_v2/bin/python3.10       2974MiB |
|    1   N/A  N/A    114839      C   /opt/conda/envs/ml_v2/bin/python3.10       2514MiB |
|    2   N/A  N/A    114841      C   /opt/conda/envs/ml_v2/bin/python3.10       2514MiB |
|    3   N/A  N/A    114842      C   /opt/conda/envs/ml_v2/bin/python3.10       2514MiB |
|    4   N/A  N/A    114843      C   /opt/conda/envs/ml_v2/bin/python3.10       2514MiB |
|    5   N/A  N/A    114844      C   /opt/conda/envs/ml_v2/bin/python3.10       2514MiB |
|    6   N/A  N/A    114845      C   /opt/conda/envs/ml_v2/bin/python3.10       2514MiB |
|    7   N/A  N/A    114846      C   /opt/conda/envs/ml_v2/bin/python3.10       2370MiB |
+---------------------------------------------------------------------------------------+ 
```
It looks rank 0 is not being utilized. I'm not sure why this is happening.

**Comment by glenn-jocher** [comment]
@tamanna-mostafa It appears that GPU 0 is not being utilized in your fine-tuning process, as indicated by the 0% GPU utilization. This could be due to a misconfiguration or an issue with the data distribution across GPUs. Please ensure that your data is evenly distributed and that all GPUs are correctly recognized by your training script. Also, verify that there are no processes unintentionally occupying GPU 0, which could prevent it from being used by your training job. If the problem persists, consider restarting the training process after ensuring all GPUs are free and properly configured for distributed training.

**Comment by tamanna-mostafa** [comment]
>Please ensure that your data is evenly distributed

How can I do this?

>verify that there are no processes unintentionally occupying GPU 0, which could prevent it from being used by your training job. 

How can I verify this?

**Comment by glenn-jocher** [comment]
@tamanna-mostafa to ensure even data distribution, check your training script or deepspeed configuration for data parallelism settings that control how data is batched and distributed across GPUs.

To verify no processes are occupying GPU 0, use the command `nvidia-smi` to list active processes on each GPU. If you find unrelated processes on GPU 0, you can terminate them using the `kill` command with the process ID.

**Comment by tamanna-mostafa** [comment]
@glenn-jocher 
Thanks. If I run `nvidia-smi`, I get output as I pasted above, and I'm not sure where it's listing active processes on each GPU. Under `Process name `, it has the same value for all the GPUs. Do I need to use any additional argument?

**Comment by glenn-jocher** [comment]
@tamanna-mostafa The `nvidia-smi` output you provided does list the active processes under the "Processes" section. Each GPU shows a Python process running, which likely corresponds to your training job. If these are the only processes listed and they all belong to your training, then there are no extraneous processes occupying GPU 0. The issue with GPU 0 utilization may lie elsewhere, possibly in the training script or data distribution logic.

**Comment by JakobLS** [comment]
I'd argue that using `watch -n 1 nvidia-smi` is more informative as it's continuously updated (every 1 second in this case). `nvidia-smi` rather gives you a window into the GPU utilisation at the time of running the command. 

Given that GPU 0's memory usage is roughly the same as for the other GPUs, it's fair to suspect that the utilisation might be non-zero.

**Comment by glenn-jocher** [comment]
@JakobLS absolutely, `watch -n 1 nvidia-smi` is indeed a great suggestion for real-time monitoring of GPU utilization! It provides a dynamic view that can be more insightful, especially during training sessions. 🚀

Regarding GPU 0, you're right; similar memory usage across GPUs suggests that it should be actively participating. It might be worth exploring the training script or configuration for any specific settings that could affect GPU 0's workload distribution. Sometimes, subtle configuration nuances can lead to such behaviors. Happy debugging! 😊
