### ISSUE TITLE
Implementation of resizing bboxes with imgsz argument 

### ISSUE THREAD

**Issue by mandal4** [ultralytics/ultralytics#7833]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thanks for the nice codes! 
I see that following function resize the input image with imgsz argument.
https://github.com/ultralytics/ultralytics/blob/ef141af4b837e0a1c34ff187ac40ef36af56c135/ultralytics/data/base.py#L145

And i'd like to know where the bboxes are resized. I searched hard but i couldn't see that :-)

Thanks,

**Comment by mandal4** [comment]
Oh i see that bboxes are normalized value. close this issue :)

**Comment by glenn-jocher** [comment]
@mandal4 great to hear you found the answer! Indeed, the bounding boxes are normalized relative to the image size, which makes them resolution-independent. If you have any more questions or need further clarification, feel free to ask. Happy coding! 😊👍
