### ISSUE TITLE
Object Counting using Ultralytics YOLOv8 🚀

### ISSUE THREAD

**Issue by koftee** [ultralytics/ultralytics#7834]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hi i tried this code but it gives me this errors
Cannot find reference 'solutions' in 'init.py'
Unresolved reference 'object_counter'
Unresolved attribute reference 'track' for class 'YOLO'

**Comment by RizwanMunawar** [comment]
@koftee Hi, Thanks for reaching out :)

Can you please update the ultralytics package with the following command and give it another try:

```pip install -U ultralytics```

Feel free to reach out if you have any more questions.

Best regards,
Ultralytics Team!
