### ISSUE TITLE
AttributeError in WandBUltralyticsCallback with Disabled Training Validation Logging

### ISSUE THREAD

**Issue by Buckler89** [ultralytics/ultralytics#7839]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I am encountering an `AttributeError` during the configuration of the `WandBUltralyticsCallback` in our model. The error raise from `on_val_end` callback. Specifically, the error message states:
`AttributeError: 'WandBUltralyticsCallback' object has no attribute 'model'`
This issue arises because the attribute in question is only assigned within the `on_fit_epoch_end` callback. However, this callback is removed (pop) from the list when I set enable_train_validation_logging=False.

Here’s the configuration I used:

```
add_wandb_callback(
    model,
    enable_model_checkpointing=False,
    enable_train_validation_logging=False,
    enable_validation_logging=True,
    enable_prediction_logging=True,
    max_validation_batches=1,
    visualize_skeleton=False
)
```

The need to set `enable_train_validation_logging=False` is crucial for our process, as it's intended to prevent unnecessary time expenditure in logging images at every epoch. It seems that this configuration inadvertently leads to the absence of the required attribute in the `WandBUltralyticsCallback` object.

Could you please provide guidance on how to resolve this `AttributeError` without compromising on the efficiency of the logging process? Your insights or any workaround to maintain efficient logging while preventing this error would be greatly appreciated.

### Environment

Found existing installation: wandb 0.16.2   
Uninstalling wandb-0.16.2: ---->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>**Why!?!?!?**
  Successfully uninstalled wandb-0.16.2
Ultralytics YOLOv8.1.6 🚀 Python-3.10.12 torch-2.1.2+cu121 CUDA:0 (NVIDIA GeForce RTX 3070 Ti Laptop GPU, 7974MiB)
Setup complete ✅ (20 CPUs, 31.0 GB RAM, 126.3/280.5 GB disk)

### Minimal Reproducible Example

```
model_name = "yolov8n" #@param {type:"string"}
dataset_name = "coco128.yaml" #@param {type:"string"}

# Initialize YOLO Model
model = YOLO(f"{model_name}.pt")

# Add W&B callback for Ultralytics
add_wandb_callback(
    model,
    enable_model_checkpointing=False,
    enable_train_validation_logging=False,
    enable_validation_logging=True,
    enable_prediction_logging=True,
    max_validation_batches=1,
    visualize_skeleton=False
)

# Train/fine-tune your model
# At the end of each epoch, predictions on validation batches are logged
# to a W&B table with insightful and interactive overlays for
# computer vision tasks
model.train(project="ultralytics", data=dataset_name, epochs=5, imgsz=640)
model.val()

# Finish the W&B run
wandb.finish()
```

### Additional

I must reinstall wandb since ultralytics.checks() uninstalled it. I'm wondering why this happened. I'm not running it in a notebook; it's a script in PyCharm.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by karl-joan** [comment]
Same issue but had `enable_train_validation_logging=True`

**Comment by glenn-jocher** [comment]
@karl-joan it appears that the `WandBUltralyticsCallback` object is expecting a `model` attribute that isn't being set due to the `enable_train_validation_logging` being set to `False`. This is likely an oversight in the callback's design, where it assumes that certain attributes are always present.

As a temporary workaround, you might consider setting `enable_train_validation_logging=True` but controlling the frequency of logging to reduce overhead. This way, the necessary attributes are set without logging at every epoch.

Regarding the reinstallation of `wandb`, it's possible that a version conflict or a dependency check within the `ultralytics.checks()` function triggered the uninstallation. Ensure that you have the correct version of `wandb` installed that is compatible with YOLOv8.

If the issue persists, please open a new issue on the YOLOv8 GitHub repository with the details, and we'll look into it further. Your feedback helps us improve the library for everyone. Thank you for bringing this to our attention.

**Comment by Buckler89** [comment]
I'm seeking clarification on configuring the batch limit for train validation logging. Could you provide detailed instructions on how to adjust this setting effectively? I understand that managing this aspect is crucial for optimizing the logging process without compromising efficiency. Any guidance or workaround to achieve this would be greatly appreciated.

**Comment by glenn-jocher** [comment]
@Buckler89 it appears that you're encountering an issue with the WandB callback configuration when certain logging features are disabled. This seems to be a specific case that might not have been fully accounted for in the current implementation of the `WandBUltralyticsCallback`. 

For the time being, as a workaround, you could try manually setting the `model` attribute on the `WandBUltralyticsCallback` object after initialization but before training starts. This way, the attribute is present even if `enable_train_validation_logging` is set to `False`.

Regarding the reinstallation of wandb, it's possible that the `ultralytics.checks()` function performs a check that leads to the reinstallation of the wandb package. This behavior might be intended to ensure that the correct version of wandb is installed, but without more context, it's difficult to provide a precise reason.

If you continue to experience issues or if the workaround does not suffice, please consider opening an issue on the YOLOv8 GitHub repository with the details provided here. The Ultralytics team or the community could then look into this and potentially provide a fix in a future update.

For now, here's a modified version of your script with the suggested workaround:

```python
import wandb
from ultralytics import YOLO, add_wandb_callback

model_name = "yolov8n"
dataset_name = "coco128.yaml"

# Initialize YOLO Model
model = YOLO(f"{model_name}.pt")

# Add W&B callback for Ultralytics
wandb_callback = add_wandb_callback(
    model,
    enable_model_checkpointing=False,
    enable_train_validation_logging=False,
    enable_validation_logging=True,
    enable_prediction_logging=True,
    max_validation_batches=1,
    visualize_skeleton=False
)

# Manually set the model attribute on the WandBUltralyticsCallback object
wandb_callback.model = model

# Train/fine-tune your model
model.train(project="ultralytics", data=dataset_name, epochs=5, imgsz=640)
model.val()

# Finish the W&B run
wandb.finish()
```

Please note that this is a temporary solution and it would be best to have the underlying issue addressed in the library itself.

**Comment by Buckler89** [comment]
Sorry, but the add_wandb_callback actually returns model and not a WandBUltralyticsCallback, according to: [callback.py#L525](https://github.com/wandb/wandb/blob/2518040a6de2f311a5497200a82377bed8e0bcc8/wandb/integration/ultralytics/callback.py#L525). Am I mistaken?

**Comment by glenn-jocher** [comment]
@Buckler89 hello! Thank you for bringing this issue to our attention and for providing detailed information about the problem you're facing. It seems like there might be a dependency in the `WandBUltralyticsCallback` that requires the `model` attribute to be set even when certain logging features are disabled.

As a temporary workaround, you could try manually setting the `model` attribute on the `WandBUltralyticsCallback` object after it's created but before training starts. This way, the attribute is available for the `on_val_end` callback to use.

Regarding the wandb reinstallation issue, it's possible that the `ultralytics.checks()` function is performing environment checks that include uninstalling and reinstalling certain packages. This behavior is not typical, and we will investigate why this might be happening.

For now, you can manually reinstall wandb after running `ultralytics.checks()` using `pip install wandb`.

If you continue to experience issues or have further questions, please feel free to reach out. We're here to help! 🚀

And no worries about submitting a PR, we appreciate your offer to help and will look into resolving this issue in the YOLOv8 repository.
