### ISSUE TITLE
Is model.track conf setting overriden by tracker threshold settings?

### ISSUE THREAD

**Issue by johnohagan** [ultralytics/ultralytics#7849]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Summary: 

It seems the confidence setting passed to `model.track` has no effect if it is lower than either of the `'new_track_thresh'` or `'track_high_thresh'` settings in botsort.yaml or bytetrack.yaml. 

My questions are 

- whether this is intended, 
- whether this is consistent with documentation, and 
- whether a feature request would be considered that would expose the tracker settings in the yaml files to the `model.track` interface.

Detail:

I noticed that with tracking I was getting a much smaller number of detections than with detection only. I understand there are reasons for this and it's not a problem. 

In my project, responsiveness is more important than accuracy, and I expected that I would be able increase the number of detections while tracking by passing a lower confidence value to `model.track`. However this seemed to have no effect.

To find out why, I used an image with one large object (me) in the foreground, and a lot of smaller objects (books) in the background. I ran tracking on the image and tried changing all the settings in each tracker's config file (botsort.yaml or bytetrack.yaml. I found that `conf` settings lower than  `'new_track_thresh'` and `'track_high_thresh'` settings had no effect on the number of detections.

Here's code that demonstrates this. For each of the two tracker threshold settings above (with the other threshold set to 0), it counts detections with confidence levels from 0.3 to 0.0 against threshold values from 0.0 to 0.3:

```
import os
from ultralytics import YOLO
from yaml import full_load, dump

model = YOLO()
im = '/home/john/Desktop/test.jpg'

print('\nWithout tracking:\n')
for i in reversed(range(4)):
    conf = i/10
    dets = model(im, conf=conf, verbose=False)[0].boxes.data
    print(f'conf: {conf} detections: {len(dets)}')

print('\nWith tracking:')
configfile = ('/home/john/.ultralytics/lib/python3.11/site-packages'
                '/ultralytics/cfg/trackers/botsort.yaml')
tracker = 'my_tracker.yaml'
my_configfile = f'{os.path.dirname(configfile)}/{tracker}'
d = full_load(open(configfile))
for k in ('new_track_thresh', 'track_high_thresh'):
    if k == 'new_track_thresh':
        d['track_high_thresh'] = 0
    else:
        d['new_track_thresh'] = 0
    for i in range(4):
        v = i/10
        d[k] = v
        dump(d, open(my_configfile, 'w'))
        print(f'\n{k} = {v}:')
        for j in reversed(range(4)):
            conf = j/10
            dets = model.track(im, conf=conf, verbose=False,
                                tracker=tracker)[0].boxes.data
            print(f'conf: {conf} detections: {len(dets)}')
```
And the output:

```
Without tracking:

conf: 0.3 detections: 1
conf: 0.2 detections: 3
conf: 0.1 detections: 16
conf: 0.0 detections: 300

With tracking:

new_track_thresh = 0.0:
conf: 0.3 detections: 1
conf: 0.2 detections: 3
conf: 0.1 detections: 16
conf: 0.0 detections: 16

new_track_thresh = 0.1:
conf: 0.3 detections: 1
conf: 0.2 detections: 3
conf: 0.1 detections: 16
conf: 0.0 detections: 16

new_track_thresh = 0.2:
conf: 0.3 detections: 1
conf: 0.2 detections: 3
conf: 0.1 detections: 3
conf: 0.0 detections: 3

new_track_thresh = 0.3:
conf: 0.3 detections: 1
conf: 0.2 detections: 1
conf: 0.1 detections: 1
conf: 0.0 detections: 1

track_high_thresh = 0.0:
conf: 0.3 detections: 1
conf: 0.2 detections: 3
conf: 0.1 detections: 16
conf: 0.0 detections: 16

track_high_thresh = 0.1:
conf: 0.3 detections: 1
conf: 0.2 detections: 3
conf: 0.1 detections: 16
conf: 0.0 detections: 16

track_high_thresh = 0.2:
conf: 0.3 detections: 1
conf: 0.2 detections: 3
conf: 0.1 detections: 3
conf: 0.0 detections: 3

track_high_thresh = 0.3:
conf: 0.3 detections: 1
conf: 0.2 detections: 1
conf: 0.1 detections: 1
conf: 0.0 detections: 1
```
As you can see, as the conf setting decreases, the number of detections stops increasing once the conf value is equal to or less than either of the tracker threshold settings. (There is also possibly a hard minimum threshold built in to the trackers, as the 300 detections at conf=0.0 without tracking at is never reached with tracking, even with everything set to 0.0, but I'm not likely to use conf=0.0).

To make the conf setting effective while tracking, I can work around this by using code similar to the above, to write to the tracker yaml file and ensure that the two threshold values are no higher than the the conf value.

However, the [documentation](https://docs.ultralytics.com/modes/track/) says:

> Tracking configuration shares properties with Predict mode, such as conf, iou, and show.

but I think given the above, this is not strictly true in a practical sense, as the conf setting will not always be effective.

Also, it would be more convenient if it were possible to write, e.g. 

`model.track(im, new_track_thresh=0.25, track_high_thresh=0.4)`

Would this be considered for a feature request?

**Comment by glenn-jocher** [comment]
@johnohagan hello! Thank you for the detailed inquiry. 👍

Yes, the behavior you're observing is intended. The `model.track` confidence setting is indeed subject to the minimum thresholds defined in the tracker configuration files (`botsort.yaml` or `bytetrack.yaml`). This is to ensure that the tracker operates with a sensible default that balances responsiveness with accuracy.

The documentation could be clearer on this interaction between `model.track` and the tracker configuration thresholds. We appreciate your feedback and will consider updating the documentation to better reflect this behavior.

Regarding your feature request to expose tracker settings directly in the `model.track` interface, it's a valid suggestion that could enhance usability. We'll take this into consideration for future updates. Feature requests like this are valuable as they help us understand the needs of our community and improve the tooling accordingly.

For now, your workaround of programmatically adjusting the tracker configuration file is the recommended approach to tailor the tracker thresholds to your specific use case.

Thank you for contributing to the discussion and helping us improve YOLOv8! 🚀
