### ISSUE TITLE
training error when imgsz is set to tuple

### ISSUE THREAD

**Issue by menggui1993** [ultralytics/ultralytics#785]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Traceback (most recent call last):
  File "/home/twc/anaconda3/envs/ultralytics/bin/yolo", line 33, in <module>
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())
  File "/home/twc/ddisk/ultralytics/ultralytics/yolo/cfg/__init__.py", line 266, in entrypoint
    getattr(model, mode)(**vars(cfg))
  File "/home/twc/ddisk/ultralytics/ultralytics/yolo/engine/model.py", line 208, in train
    self.trainer.train()
  File "/home/twc/ddisk/ultralytics/ultralytics/yolo/engine/trainer.py", line 182, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/home/twc/ddisk/ultralytics/ultralytics/yolo/engine/trainer.py", line 247, in _do_train
    self._setup_train(rank, world_size)
  File "/home/twc/ddisk/ultralytics/ultralytics/yolo/engine/trainer.py", line 233, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=rank, mode="train")
  File "/home/twc/ddisk/ultralytics/ultralytics/yolo/v8/detect/train.py", line 43, in get_dataloader
    build_dataloader(self.args, batch_size, img_path=dataset_path, stride=gs, rank=rank, mode=mode)[0]
  File "/home/twc/ddisk/ultralytics/ultralytics/yolo/data/build.py", line 85, in build_dataloader
    use_keypoints=cfg.task == "keypoint")
  File "/home/twc/ddisk/ultralytics/ultralytics/yolo/data/dataset.py", line 46, in __init__
    single_cls)
  File "/home/twc/ddisk/ultralytics/ultralytics/yolo/data/base.py", line 73, in __init__
    self.transforms = self.build_transforms(hyp=hyp)
  File "/home/twc/ddisk/ultralytics/ultralytics/yolo/data/dataset.py", line 141, in build_transforms
    transforms = v8_transforms(self, self.imgsz, hyp)
  File "/home/twc/ddisk/ultralytics/ultralytics/yolo/data/augment.py", line 663, in v8_transforms
    Mosaic(dataset, imgsz=imgsz, p=hyp.mosaic, border=[-imgsz // 2, -imgsz // 2]),
TypeError: bad operand type for unary -: 'list'

### Environment

-YOLO: yolov8.0.26

### Minimal Reproducible Example

```
yolo detect train model=ultralytics/models/v8/yolov8m.yaml data=ultralytics/yolo/data/datasets/coco128.yaml imgsz=640,480
```

### Additional

It seems like that the data augmentation doesn't process the imgsz properly, when it's a tuple.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by JustasBart** [comment]
Hi @menggui1993 have you tried **imgsz=[480,640]**? That's what I use and it works just fine for me.

Good luck! :rocket:

**Comment by menggui1993** [comment]
@JustasBart Thanks for your advice. But I got the same error.
https://github.com/ultralytics/ultralytics/blob/fa8811dcee7db0c0b8de1fffca91e8d54554535c/ultralytics/yolo/data/augment.py#L663
The error came from this part. For the 'border' value, if imgsz is a tuple or list, it causes an error.

**Comment by JustasBart** [comment]
@menggui1993 This is my custom train call:

```
yolo detect train \
data=10Class.yaml \
model=yolov8s.pt \
epochs=300 \
imgsz=1280 \
rect=True \
device=0 \
batch=-1 \
plots=True
```

Note how I have my **model** set to a .pt file, whereas you have it set as **yolov8m.yaml**, can you just confirm why is that?

**Comment by menggui1993** [comment]
@JustasBart Either way to load the model is fine according to the [documentation](https://docs.ultralytics.com/cfg/). I also tried with a .pt file. For both methods, model is loaded successfully from the log. And I don't think this error is related to the model cause it happend in the data preprocessing part.

**Comment by JustasBart** [comment]
@menggui1993 I see, well that's all that I could think of, I hope you can resolve this sooner rather than later, good luck! :rocket:

**Comment by AyushExel** [comment]
@menggui1993 We currently don't support imgsz as a list for training. @glenn-jocher can comment more about that

**Comment by Laughing-q** [comment]
@menggui1993 also the mosaic augmentation needs square images, please set `rect=True` if you want to start a training with rectangle images. :)

**Comment by menggui1993** [comment]
OK, I see. Thanks for your help. By the way, can you please modify your [documentation ](https://docs.ultralytics.com/cfg/) as it describes the 'imgsz' to be 'size of input images as integer or w,h'.

**Comment by glenn-jocher** [comment]
@menggui1993 yes that's right, you should train with an integer imgsz, i.e. `yolo train 640`

You can use lists for predict/export though: `yolo export imgsz=640,480`

**Comment by glenn-jocher** [comment]
I'll add a warning when this happens to let users know since it's probably happening to more than 1 person

**Comment by glenn-jocher** [comment]
Warning added in #789 for list imgsz types passed to train or val:

```bash
yolo train imgsz=640,480

WARNING ⚠️ 'train' and 'val' imgsz types must be integer, updating to 'imgsz=640'. 'predict' and 'export' imgsz may be list or integer, i.e. 'yolo export imgsz=640,480' or 'yolo export imgsz=640'
```

**Comment by JustasBart** [comment]
@glenn-jocher That was fast... This will surely save some headaches down the line! :rocket:

**Comment by sadimoodi** [comment]
@glenn-jocher would training yoloV8 models using imgsz = 1280 improve detection percision on small objects? 
i assume that the number of params of the model wont change because it was already trainned on 640 resolution.
otherwise, what can i do to improve detection on smaller objects other than playing with the anchors?

**Comment by glenn-jocher** [comment]
@sadimoodi Yes, training YOLOv8 models with higher resolutions such as 1280 can improve detection precision on small objects. 
This is because using a higher resolution enhances the network's ability to detect smaller objects within the image. 

Although increasing the image resolution doesn't change the number of model parameters, it will increase the amount of memory required to store images and therefore training may take longer.

Other methods to improve detection on smaller objects include adding more anchors or changing the anchor scale and aspect ratios, using H-swish activation function or testing transfer learning.

**Comment by kylekam** [comment]
> @menggui1993 also the mosaic augmentation needs square images, please set `rect=True` if you want to start a training with rectangle images. :)

Is it possible to train mosaic with 'rect=True'? I'm getting a warning that says "--rect is incompatible with DataLoader shuffle, setting shuffle=False" which I think is causing the mosaic images to only take a single image.
