### ISSUE TITLE
Traceback error when running model.predict()

### ISSUE THREAD

**Issue by KowenWoo** [ultralytics/ultralytics#7850]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I am very new to yolov8 and am trying to run a object detection yolov8 model with streamlit to predict images. Here is the issue that arises in line 54:

Traceback (most recent call last):
  File "C:\Users\kowen\anaconda3\envs\slTestEnv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\kowen\OneDrive\Desktop\Streamlit_test\object_detection.py", line 54, in <module>
    res = model.predict(uploaded_image,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kowen\anaconda3\envs\slTestEnv\Lib\site-packages\ultralytics\engine\model.py", line 268, in predict        
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "C:\Users\kowen\anaconda3\envs\slTestEnv\Lib\site-packages\ultralytics\engine\predictor.py", line 341, in setup_model
    self.model = AutoBackend(
                 ^^^^^^^^^^^^
  File "C:\Users\kowen\anaconda3\envs\slTestEnv\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kowen\anaconda3\envs\slTestEnv\Lib\site-packages\ultralytics\nn\autobackend.py", line 123, in __init__     
    fp16 &= pt or jit or onnx or xml or engine or nn_module or triton  # FP16
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for &=: 'bool' and 'str'

### Environment

Ultralytics YOLOv8.1.6 🚀 Python-3.11.7 torch-2.1.2 CPU (AMD Ryzen 7 4700U with Radeon Graphics)
Setup complete ✅ (8 CPUs, 15.4 GB RAM, 282.2/475.7 GB disk)

### Minimal Reproducible Example

# Import required libraries
import PIL

import streamlit as st
from ultralytics import YOLO

# Replace the relative path to your weight file
model_path = "C:/Users/kowen/OneDrive/Desktop/Streamlit_test/weights"

# Setting page layout
st.set_page_config(
    page_title="Object Detection using YOLOv8",  # Setting page title
    page_icon="🤖",     # Setting page icon
    layout="wide",      # Setting layout to wide
    initial_sidebar_state="expanded"    # Expanding sidebar by default
)

# Creating sidebar
with st.sidebar:
    st.header("Image/Video Config")     # Adding header to sidebar
    # Adding file uploader to sidebar for selecting images
    source_img = st.file_uploader(
        "Choose an image...", type=("jpg", "jpeg", "png", 'bmp', 'webp'))

    # Model Options
    confidence = float(st.slider(
        "Select Model Confidence", 25, 100, 40)) / 100

# Creating main page heading
st.title("Object Detection using YOLOv8")

# Creating two columns on the main page
col1, col2 = st.columns(2)

# Adding image to the first column if image is uploaded
with col1:
    if source_img:
        # Opening the uploaded image
        uploaded_image = PIL.Image.open(source_img)
        # Adding the uploaded image to the page with a caption
        st.image(source_img,
                 caption="Uploaded Image",
                 use_column_width=True
                 )

try:
    model = YOLO(model_path)
except Exception as ex:
    st.error(
        f"Unable to load model. Check the specified path: {model_path}")
    st.error(ex)

if st.sidebar.button('Detect Objects'):
    res = model.predict(uploaded_image,
                        stream = True,
                        task = "detect",
                        conf=confidence
                        )
    boxes = res[0].boxes
    res_plotted = res[0].plot()[:, :, ::-1]
    with col2:
        st.image(res_plotted,
                 caption='Detected Image',
                 use_column_width=True
                 )
        try:
            with st.expander("Detection Results"):
                for box in boxes:
                    st.write(box.xywh)
        except Exception as ex:
            st.write("No image is uploaded yet!")

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@KowenWoo hello! It looks like you're encountering a TypeError during the prediction phase with YOLOv8 in your Streamlit application. The error message suggests there might be an issue with the handling of data types in the `AutoBackend` initialization.

To resolve this, please ensure that all the parameters passed to the `predict` method are of the correct type. Specifically, check the `conf` parameter to ensure it's a float, as it seems to be derived from a Streamlit slider and might be causing the issue if not properly converted.

If the problem persists after verifying the parameter types, consider checking if there are any updates or known issues with the version of the YOLOv8 package you're using. Sometimes, updating to the latest version can resolve such issues.

For further guidance, you can refer to our documentation on the Predict mode at https://docs.ultralytics.com/modes/predict, which provides detailed information on how to use the `predict` method correctly.

If you continue to experience difficulties, please provide a more detailed error log and the exact environment setup, and we'll be happy to assist you further. Thank you for using YOLOv8, and we appreciate your contribution to the community! 🚀

**Comment by KowenWoo** [comment]
Hi @glenn-jocher, I tried all the things you said:
- ran with and without confidence parameter and ensured it was a float
- checked yolov8 for version ( I am using Ultralytics YOLOV8.1.6)
none of these fixed the error.
I am using a conda environment with python 3.11.7, not sure what details you need specifically.

**Comment by glenn-jocher** [comment]
Hello @KowenWoo, thank you for the update and for trying out the suggested steps. Since the issue persists, it might be related to compatibility with Python 3.11.7. YOLOv8 is tested extensively with certain versions of Python, and sometimes newer versions can introduce unexpected issues.

As a next step, I recommend setting up a new environment with a Python version that is known to be compatible with YOLOv8, such as Python 3.8 or 3.9, and then reinstalling the YOLOv8 package within that environment.

If the error still occurs after trying this, please open an issue on the Ultralytics YOLOv8 GitHub repository with the full traceback and details of your environment setup. This will help us to reproduce and address the problem more effectively. Thank you for your cooperation! 🛠️

**Comment by KowenWoo** [comment]
I still received the same error using python 3.9.18 in a new environment. The full traceback error is above as well as all my code.

**Comment by glenn-jocher** [comment]
@KowenWoo, I'm sorry to hear the issue persists with Python 3.9.18. Since the error remains unresolved, could you please open a new issue on the Ultralytics YOLOv8 GitHub repository with the full details? Include the complete traceback, your environment specifications, and the code snippet that's causing the problem. This will allow us to investigate further and assist you more effectively. Thank you for your patience and collaboration. 🤝
