### ISSUE TITLE
counting moving object

### ISSUE THREAD

**Issue by koftee** [ultralytics/ultralytics#7851]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I wrote the code below the question section. I want to count moving and unmoving objects it works with videos but when i want to use this with real time it gives me this error:

raceback (most recent call last):
  File "C:\Users\muham\PycharmProjects\teknogi\a.py", line 33, in <module>
    track_ids = results[0].boxes.id.int().cpu().tolist()
AttributeError: 'NoneType' object has no attribute 'int' 

### Additional

from collections import defaultdict

import cv2
import numpy as np

from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('yolov8n.pt')

# Open the video file
video_path = "C:\\Users\\muham\\PycharmProjects\\opencv_fotolar\\body.mp4"
cap = cv2.VideoCapture(video_path)

# Store the track history and detected IDs
track_history = defaultdict(lambda: [])
detected_ids = set()

# Initialize human count

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 tracking on the frame, persisting tracks between frames
        results = model.track(frame, persist=True,conf=0.4,classes=0)
        human_count = 0
        uhuman_count = 0
        # Get the boxes and track IDs
        boxes = results[0].boxes.xywh.cpu()
        track_ids = results[0].boxes.id.int().cpu().tolist()

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Update detected IDs
        detected_ids.update(track_ids)

        # Plot the tracks
        for box, track_id in zip(boxes, track_ids):
            x, y, w, h = box
            track = track_history[track_id]
            track.append((int(x + w / 2), int(y + h / 2)))  # x, y center point
            if len(track) > 30:  # retain 30 tracks for 30 frames
                track.pop(0)

            # Draw the tracking lines
            points = np.hstack(track).astype(np.int32).reshape((-1, 1, 2))
            cv2.polylines(annotated_frame, [points], isClosed=False, color=(230, 230, 230), thickness=10)
            # Calculate the length of the tracking line
            line_length = cv2.arcLength(points, closed=False)

            # Check if the length is greater than 0
            if line_length > 0:
                human_count+=1
            else:
                uhuman_count+=1

        # Count humans if there are any detected points that haven't been counted before
        new_detected_ids = detected_ids.difference(set(track_history.keys()))
        #human_count += len(new_detected_ids)
        detected_ids.difference_update(new_detected_ids)

        # Display human count

        cv2.putText(annotated_frame, f"moving: {human_count}", (40, 40), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 0), 2)
        cv2.putText(annotated_frame, f"unmoving: {uhuman_count}", (350, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 0),
                    2)
        # Display the annotated frame
        cv2.imshow("YOLOv8 Tracking", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()

**Comment by glenn-jocher** [comment]
@koftee hello! It seems like you're encountering an issue where the `results[0].boxes` object is `None`, which indicates that no detections were made in the frame you're processing. This can happen if there are no objects detected with a confidence above the threshold you've set, or if the frame is empty or corrupted.

When working with real-time video streams, you might occasionally get frames with no detectable objects, or the video feed might momentarily be disrupted. To handle this, you should check if `results[0].boxes` is not `None` before attempting to access its attributes. This way, you can avoid the `AttributeError` you're seeing.

Additionally, ensure that your real-time video stream is providing frames in a format that is compatible with the YOLO model, and that the lighting and conditions are suitable for object detection.

For more information on tracking and handling different scenarios, you can refer to our documentation on the Track mode. Keep experimenting and happy coding! 😊🚀
