### ISSUE TITLE
Yolov8 tracker issues

### ISSUE THREAD

**Issue by IgorGoldberg** [ultralytics/ultralytics#7852]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi 
1) My goal is to calculate for each instance the length of the path it did over the scene (in pixels units). 
I could write a code that processes my_results and for each instance calculates the distance from the previous Bounding Box coordinates to the new ones. But maybe you have something built that already does it that I have missed?

2)While tracking: if there is some instance that accidentally was not detected in the Nth frame,  but it was again detected in the frame N+1 frame, it gets another ID. Of course, this situation is not wanted. Maybe in the botsort.yaml there is a parameter that can improve this situation? If not, what can?

3)The described above is done for the "object detection model". Does the tracker with the same syntax work also, for the "instance segmentation models"?

Thank you

**Comment by glenn-jocher** [comment]
@IgorGoldberg hello!

1) For path length calculation, we don't have a built-in feature in YOLOv8 to compute the distance traveled by each instance. Your approach of processing `my_results` and calculating distances between bounding boxes is currently the way to go.

2) Regarding tracking consistency across frames, you can adjust the `track_thresh` and `track_buffer` parameters in the `botsort.yaml` to potentially improve tracking stability. These parameters control the detection threshold for tracking and the number of frames to keep an ID without detection, respectively.

3) Yes, the tracker can be used with instance segmentation models as well. The syntax remains consistent, and the tracker will handle the segmented instances with their unique IDs.

I hope this helps, and thank you for being part of the YOLO community! 🚀

**Comment by IgorGoldberg** [comment]
Thank you very much sir!

**Comment by glenn-jocher** [comment]
@IgorGoldberg you're welcome! If you have any more questions, feel free to ask. Happy tracking! 😊👍
