### ISSUE TITLE
save wrong project

### ISSUE THREAD

**Issue by kyoko9000** [ultralytics/ultralytics#7857]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

this is my code:
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')  # load an official model
# model = YOLO('path/to/best.pt')  # load a custom model

# Predict with the model
results = model('https://ultralytics.com/images/bus.jpg', save=True)

and it save like this one:
"D:\2. Python projects\81. yolov8 project\.venv\Scripts\python.exe" "D:\2. Python projects\81. yolov8 project\2.yolo8_OBB.py" 

Found https://ultralytics.com/images/bus.jpg locally at bus.jpg
image 1/1 D:\2. Python projects\81. yolov8 project\bus.jpg: 640x480 4 persons, 1 bus, 1 stop sign, 69.0ms
Speed: 3.0ms preprocess, 69.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 480)
Results saved to D:\2. Python projects\75.-yolov8-pyqt5\runs\detect\predict

Process finished with exit code 0

-------------------------
all things is project 81 but it save file in project 75
how can i fix that?

**Comment by glenn-jocher** [comment]
@kyoko9000 hello! It seems like your results are being saved to a different project directory than expected. This can happen if the working directory is set to a different location when you run your script. To ensure that your results are saved in the correct directory, you can specify the `project` and `name` arguments in the `model()` call to control the save directory. For example:

```python
results = model('path/to/image.jpg', save=True, project='desired/project/path', name='run_name')
```

Replace `'desired/project/path'` with the path to the directory where you want to save the results, and `'run_name'` with a custom run name. This will create a new folder within the specified project path where your results will be stored.

For more details on how to control the output directories, please refer to the documentation at https://docs.ultralytics.com. 😊

**Comment by kyoko9000** [comment]
Thank you for your answer. I will try it. But last time i make new project but that problem not solve. That problem not happen in the past

**Comment by glenn-jocher** [comment]
@kyoko9000 You're welcome! If the issue persists even after specifying the `project` and `name` arguments, it could be related to environment variables or cached paths. Make sure to run your script from the correct project directory and check if there are any hardcoded paths in your environment or script that might redirect the output. If you need further assistance, feel free to reach out again. Good luck! 👍
