### ISSUE TITLE
About training custom data on obb

### ISSUE THREAD

**Issue by Galaxy-Ding** [ultralytics/ultralytics#7858]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello author, thank you for your contribution to the open source community!
I encountered a problem when training the obb model. I always need to download the yolov8n-obb.pt file from the official website. I tried to download it locally and then upload it to the server for training, and it always downloaded.
The code I use is as follows

```
from ultralytics import YOLO
 
def main():
    model = YOLO('yolov8s-obb.yaml').load('yolov8s-obb.pt')  # build from YAML and transfer weights
    model.train(data='dota8-obb.yaml', epochs=100, imgsz=1024, batch=4, workers=4)
if __name__ == '__main__':
    main()
```

and also try like this:

```
from ultralytics import YOLO
 
def main():
    model = YOLO('./yolov8s-obb.pt')  
    model.train(data='dota8-obb.yaml', epochs=100, imgsz=1024, batch=4, workers=4)
if __name__ == '__main__':
    main()
```

but all failed!
![image](https://github.com/ultralytics/ultralytics/assets/54030287/1c0cdf01-4eff-46ef-a4cd-2d06a354a906)

**Comment by glenn-jocher** [comment]
@Galaxy-Ding hello! Thanks for reaching out and for your kind words. It seems like you're experiencing issues with local weight file usage. When you initialize the `YOLO` object with a weights file path, ensure the path is correct and accessible. If the file is in the same directory as your script, using `'./yolov8s-obb.pt'` should work. If it's still attempting to download the file, double-check the file name and path.

If the issue persists, it might be helpful to clear any cached weights to prevent automatic downloading. Also, ensure that the weights file is not corrupted. If you continue to face difficulties, please provide the error message you're receiving, and we can troubleshoot further. Keep up the great work with your custom training! 🚀

**Comment by keeper-jie** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> ### Question
> Hello author, thank you for your contribution to the open source community! I encountered a problem when training the obb model. I always need to download the yolov8n-obb.pt file from the official website. I tried to download it locally and then upload it to the server for training, and it always downloaded. The code I use is as follows
> 
> ```
> from ultralytics import YOLO
>  
> def main():
>     model = YOLO('yolov8s-obb.yaml').load('yolov8s-obb.pt')  # build from YAML and transfer weights
>     model.train(data='dota8-obb.yaml', epochs=100, imgsz=1024, batch=4, workers=4)
> if __name__ == '__main__':
>     main()
> ```
> 
> and also try like this:
> 
> ```
> from ultralytics import YOLO
>  
> def main():
>     model = YOLO('./yolov8s-obb.pt')  
>     model.train(data='dota8-obb.yaml', epochs=100, imgsz=1024, batch=4, workers=4)
> if __name__ == '__main__':
>     main()
> ```
> 
> but all failed! ![image](https://private-user-images.githubusercontent.com/54030287/300240129-1c0cdf01-4eff-46ef-a4cd-2d06a354a906.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2Mjg3MzcsIm5iZiI6MTcwNjYyODQzNywicGF0aCI6Ii81NDAzMDI4Ny8zMDAyNDAxMjktMWMwY2RmMDEtNGVmZi00NmVmLWE0Y2QtMmQwNmEzNTRhOTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE1MjcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NTI1NDliNWExM2JkN2U5ZTQwM2JmNTRhZTRiNjcxNDM3Yzg2Zjk4YWEyODE1NGJlNDAwNzhmMGRiMzViMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xDGoDYTX16X1hvQJjq2w49_rftluAneRUtqbMBjANyU)
> 
> ### Additional
> _No response_

have you solve it? I have the same problem with absolute path and chmod 777 but always download form github, My  eenv is Ultralytics YOLOv8.1.8 🚀 Python-3.10.13 torch-2.0.1+cu117 CUDA:1 (NVIDIA RTX A6000, 48677MiB)

**Comment by Galaxy-Ding** [comment]
> > ### Search before asking
> > 
> > * [x]   I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> > 
> > ### Question
> > Hello author, thank you for your contribution to the open source community! I encountered a problem when training the obb model. I always need to download the yolov8n-obb.pt file from the official website. I tried to download it locally and then upload it to the server for training, and it always downloaded. The code I use is as follows
> > ```
> > from ultralytics import YOLO
> >  
> > def main():
> >     model = YOLO('yolov8s-obb.yaml').load('yolov8s-obb.pt')  # build from YAML and transfer weights
> >     model.train(data='dota8-obb.yaml', epochs=100, imgsz=1024, batch=4, workers=4)
> > if __name__ == '__main__':
> >     main()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and also try like this:
> > ```
> > from ultralytics import YOLO
> >  
> > def main():
> >     model = YOLO('./yolov8s-obb.pt')  
> >     model.train(data='dota8-obb.yaml', epochs=100, imgsz=1024, batch=4, workers=4)
> > if __name__ == '__main__':
> >     main()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but all failed! ![image](https://private-user-images.githubusercontent.com/54030287/300240129-1c0cdf01-4eff-46ef-a4cd-2d06a354a906.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2Mjg3MzcsIm5iZiI6MTcwNjYyODQzNywicGF0aCI6Ii81NDAzMDI4Ny8zMDAyNDAxMjktMWMwY2RmMDEtNGVmZi00NmVmLWE0Y2QtMmQwNmEzNTRhOTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE1MjcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NTI1NDliNWExM2JkN2U5ZTQwM2JmNTRhZTRiNjcxNDM3Yzg2Zjk4YWEyODE1NGJlNDAwNzhmMGRiMzViMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xDGoDYTX16X1hvQJjq2w49_rftluAneRUtqbMBjANyU)
> > ### Additional
> > _No response_
> 
> have you solve it? I have the same problem with absolute path and chmod 777 but always download form github, My eenv is Ultralytics YOLOv8.1.8 🚀 Python-3.10.13 torch-2.0.1+cu117 CUDA:1 (NVIDIA RTX A6000, 48677MiB)

No, it has not been resolved yet. For now, the project has been put on hold. I will look at it in two weeks.

**Comment by glenn-jocher** [comment]
@Galaxy-Ding hello! It seems you're still facing the issue with the model weights downloading even when you have them locally. This is unusual behavior and might be related to a path or permissions issue. When you revisit the problem, ensure the local path to the weights is correct and the file is not corrupted. If the problem persists, please open a new issue with the error logs, and we'll be happy to help you troubleshoot further. Good luck with your project, and we look forward to assisting you when you're ready! 🛠️
