### ISSUE TITLE
Overwrite/replace saved model's output video

### ISSUE THREAD

**Issue by VPpexis** [ultralytics/ultralytics#7864]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

**Question**
How do I configure to automatically replace/overwrite output? I have set my project to folder and named it `output`. If I rerun it will create a new folder called  `output2`. Is there a way to replace/overwrite the file in the older `output` folder?

**Here is my code**

    from ultralytics import YOLO
    import numpy as np
    
    model = YOLO('yolov8s-pose.pt')
    
    results = model(source='output.mp4', 
                    conf=0.3, 
                    show=True, 
                    save=True,
                    project='runs',
                    name='output'
                    )

### Additional

None

**Comment by glenn-jocher** [comment]
@VPpexis hello! To overwrite the output in the same folder without creating a new one like `output2`, you can set the `exist_ok` parameter to `True` when calling the model. This will allow the model to save the results in the existing directory, overwriting any previous output files with the same name. Just add `exist_ok=True` to your function call, and you should be good to go! 😊

For more details on the parameters and usage, you can refer to our documentation at https://docs.ultralytics.com.

**Comment by glenn-jocher** [comment]
@VPpexis you're welcome! Happy to hear it's working for you now. If you have any more questions, feel free to reach out. Happy detecting! 😄🚀
