### ISSUE TITLE
requirements.txt文件缺失

### ISSUE THREAD

**Issue by YouBeiZhenL** [ultralytics/ultralytics#7869]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

pip install -r requirements.txt失败，发现项目文件内没有requirements.txt

### Additional

我

**Comment by Kayzwer** [comment]
@YouBeiZhenL use the command `pip install -e .` to install the project.
