### ISSUE TITLE
Object365

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [ultralytics/ultralytics#787]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello there :wave: 

I hope you'll do great. I'll train yolov8 on Object365, any advice/tips from your past experience? The goal is not to maximize mAP on the test (like it was done here) but to create a robust model to serve more real-life scenarios

Thanks :) 

Cheers,

Fra

**Comment by FrancescoSaverioZuppichini** [comment]
F

**Comment by pderrenger** [comment]
@FrancescoSaverioZuppichini hi Fra :wave:,

Training YOLOv8 on Object365 for real-life scenarios sounds like an exciting project! To create a robust model, consider augmenting your dataset with diverse real-world examples, striking a balance between quality and quantity. You may also want to focus on optimizing for generalization by carefully tuning hyperparameters and conducting thorough model validation.

Wishing you all the best with your YOLOv8 training!

Cheers!
Paula
