### ISSUE TITLE
YOLO V8 Training with polylines, not polygons

### ISSUE THREAD

**Issue by TreyPark** [ultralytics/ultralytics#7872]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is YOLO V8 able to train polylines, and not polygons?

1. If able, then would I need to use detection or only segmentation models? (Am I correct in assuming detection works only with b-boxes, and not polygons or polylines?)
2. If able, what would be the annotation format for the polylines? (Do I designate class index, and just the start and end points, or can I add as many coordinates as I like?)
3. If able, would the prediction results return polygon masks (and polygon txt labels), or would it return polyline masks(?) and labels? I guess this is the critical question.
4. If able, are there separate setting/configurations for po'ylines specifically? (arguments, yamls, cfg, etc.)

Thank you in advance :)

PS. I tried training with what are supposed to be polyline annotations, and the training results and predictions results are attached. Also, an image generated with the output labels(labels given by the yolo model after running prediction).
![plotting_output_lables](https://github.com/ultralytics/ultralytics/assets/158024077/cb80dc59-34ae-486b-836f-bb2eea24c55f)

![val_batch0_labels](https://github.com/ultralytics/ultralytics/assets/158024077/7d17deb2-c24c-4f7c-87f6-1d9e791daacc)
![P23-1-01_v003440000](https://github.com/ultralytics/ultralytics/assets/158024077/f65c1ab0-edb1-4c03-a6a8-9cd54323301d)

input annotation example:
0 0.4253066912526119 0.49043707173738704 0.41518647972109896 0.49448202430556615 0.389885950892317 0.5070663211843455 0.3658504485049739 0.5187517397146406 0.32663462882036165 0.5380776242070517 0.24263687310880508 0.5821226632827794 0.12281797074322724 0.6492683994579156 0.04034668027100719 0.6961998367859982 0.0008035742984796375 0.718695644871823
0 0.25427879906882933 0.7846929786144392 0.3255709454591819 0.6598331580203004 0.363548038522438 0.5998199820810577 0.39783982251230576 0.549936010539966 0.41080049677619274 0.5297905604945252 0.42889143793620177 0.5091654568765738 0.44050204196426723 0.4957351568462798

output(after running prediction) annotation example:
0 0.535247 0.652616 0.535247 0.653706 0.535974 0.653706 0.535974 0.653161 0.53561 0.652616
0 0.663154 0.64444 0.663154 0.644985 0.663881 0.644985 0.664244 0.645531 0.664608 0.645531 0.664971 0.646076 0.666061 0.646076 0.666424 0.646621 0.666788 0.646621 0.667151 0.647166 0.667878 0.647166 0.668241 0.647711 0.669331 0.647711 0.669695 0.648256 0.670785 0.648256 0.671148 0.648801 0.671875 0.648801 0.672238 0.649346 0.673328 0.649346 0.673692 0.649891 0.674419 0.649891 0.674782 0.650436 0.675509 0.650436 0.675872 0.650981 0.676599 0.650981 0.676962 0.651526 0.677689 0.651526 0.678052 0.652071 0.679506 0.652071 0.679869 0.652616 0.680596 0.652616 0.680959 0.653161

**Comment by glenn-jocher** [comment]
@TreyPark hello! Thanks for reaching out with your questions about training with polylines in YOLOv8. Here's some guidance:

1. YOLOv8 is primarily designed for object detection with bounding boxes. For polylines, you would typically use segmentation models. However, YOLOv8 does not natively support polyline annotations.
   
2. Since YOLOv8 is not designed for polylines, there isn't a specific annotation format for them. Annotations are expected to be for bounding boxes or segmentation masks.

3. Predictions from YOLOv8 will return bounding boxes or segmentation masks, not polylines. The model is not currently set up to handle polyline predictions.

4. There are no separate settings or configurations for polylines in YOLOv8, as this is not a supported feature.

For tasks involving polylines, you might need to look into other models or frameworks that support such annotations. If you have further questions or need more details, feel free to check our documentation at https://docs.ultralytics.com. 😊

**Comment by TreyPark** [comment]
> @TreyPark hello! Thanks for reaching out with your questions about training with polylines in YOLOv8. Here's some guidance:
> 
> 1. YOLOv8 is primarily designed for object detection with bounding boxes. For polylines, you would typically use segmentation models. However, YOLOv8 does not natively support polyline annotations.
> 2. Since YOLOv8 is not designed for polylines, there isn't a specific annotation format for them. Annotations are expected to be for bounding boxes or segmentation masks.
> 3. Predictions from YOLOv8 will return bounding boxes or segmentation masks, not polylines. The model is not currently set up to handle polyline predictions.
> 4. There are no separate settings or configurations for polylines in YOLOv8, as this is not a supported feature.
> 
> For tasks involving polylines, you might need to look into other models or frameworks that support such annotations. If you have further questions or need more details, feel free to check our documentation at https://docs.ultralytics.com. 😊

Okay, thank you so much for this clarification. Helps a bunch!

**Comment by huynhkhoa44** [comment]
@TreyPark Can I ask you what method did you use to detect polyline? If you still use YOLOv8, it would be great. Thanks a lot.

**Comment by fattypiggy** [comment]
@TreyPark Hi, I have the same situation as yours, which model do you use to check the lines in the image?
