### ISSUE TITLE
Resutn invalid value  when inferring with my own trained model

### ISSUE THREAD

**Issue by hajime-te** [ultralytics/ultralytics#7874]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

# question
When I run  YOLOv8 sample code "YOLOv8-CPP-Inference" with my trained model, code returens invalid value  -1073741819.
How can I solve this problem?

# my model
Trained with bmp image of size(1280, 640).
I confirmed that the Python script using pt files can be correctly inferred.
Then, convert pt file to onnx file by run yolo tool.
```
yolo export model=my_best.pt imgsz=1280, 640 format=onnx opset=12
```
When I ran this command I got the following warning message.
>yolo val task=detect model=my_best.onnx imgsz=1280,640 data=data.yaml  WARNING ⚠️ non-PyTorch val requires square images, 'imgsz=[1280, 640]' will not work. Use export 'imgsz=1280' if val is required.

When I try to infer from C++ code using this model, it returns incorrect values.

# environment
Python   3.9.13
torch      2.1.2
OpenCV 4.7.0

# what I did
- Exporte the model by specifying (1280,1280) as the image size -> return invalid value
- Use a black image of the same size instead of the image -> return invalid value 
- Use a black image and sample model in .\venv\Lib\site-packages\onnx\examples\resources -> pop up black window

**Comment by glenn-jocher** [comment]
@hajime-te hello! It seems like you're encountering an issue with the inference using a custom-trained model in C++. The error code -1073741819 is often related to a segmentation fault or similar crash in Windows.

Here are a few steps you can take to troubleshoot the problem:

1. **Square Image Size**: Ensure you're using a square image size for the export, as non-PyTorch inference requires square images. Try exporting your model with `imgsz=1280,1280` and validate if the ONNX model works with the Python script.

2. **Model Compatibility**: Verify that the ONNX model is compatible with the version of the inference engine you're using in C++. Sometimes, discrepancies between the export environment and the inference environment can cause issues.

3. **Dependencies**: Check that all dependencies, especially OpenCV, are correctly installed and are compatible with the ONNX model.

4. **ONNX Model Validation**: Use ONNX tools to validate the exported ONNX model to ensure there are no export-related issues.

5. **Error Logs**: Look for detailed error logs or stack traces that occur during the crash to pinpoint the source of the issue.

6. **Simplify**: As a test, try running the C++ inference with a simpler model or a pre-trained model provided by Ultralytics to ensure that the inference code is working correctly.

If the issue persists, consider opening an issue on the Ultralytics YOLOv8 repo with detailed error logs and the steps you've taken. The community and maintainers can provide more targeted assistance. Remember to check the [Ultralytics Docs](https://docs.ultralytics.com) for more information on model export and troubleshooting. Good luck! 🤞

**Comment by hajime-te** [comment]
@glenn-jocher 
Thank you for your reply.
Finally, I solved it in the following way.
- version up opencv 4.7.0 -> 4.8.0
- specify square size when exporting to onnx

**Comment by glenn-jocher** [comment]
@hajime-te Fantastic to hear that you've resolved the issue! Upgrading OpenCV and exporting with a square image size are both solid steps to ensure compatibility and stability. If you have any more questions or run into further issues, feel free to reach out. Happy coding with YOLOv8! 🚀
