### ISSUE TITLE
Resuming Model Train

### ISSUE THREAD

**Issue by 2019331099-Rabbi** [ultralytics/ultralytics#7875]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have run the training process for 200 epochs. After 32 epochs, I saved the **last.pt**  and turned off the session. 
Then after sometimes I restart the session and resume from the last epoch. using **last.pt**. But the **best.pt** is not saving after resuming the process. How can I save best.pt? 

model = YOLO('/kaggle/input/last-weight1/last.pt')
model.train(resume = True)

**Comment by 2019331099-Rabbi** [comment]
Issue solved.

**Comment by glenn-jocher** [comment]
@2019331099-Rabbi great to hear your issue is resolved! If you have any more questions or need further assistance in the future, feel free to reach out. Happy training with YOLOv8! 🚀
