### ISSUE TITLE
WandB Integration with yolov8

### ISSUE THREAD

**Issue by RanaShiva** [ultralytics/ultralytics#7882]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Integrations

### Bug

WARNING  'ultralytics.yolo.v8' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.models.yolo' instead.
WARNING  'ultralytics.yolo.utils' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.utils' instead.
Note this warning may be related to loading older models. You can update your model to current structure with:
    import torch
    ckpt = torch.load("model.pt")  # applies to both official and custom models
    torch.save(ckpt, "updated-model.pt")

WARNING  'ultralytics.yolo.v8' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.models.yolo' instead.
WARNING  'ultralytics.yolo.utils' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.utils' instead.
Note this warning may be related to loading older models. You can update your model to current structure with:
    import torch
    ckpt = torch.load("model.pt")  # applies to both official and custom models
    torch.save(ckpt, "updated-model.pt")

WARNING  'ultralytics.yolo.v8' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.models.yolo' instead.
WARNING  'ultralytics.yolo.utils' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.utils' instead.
Note this warning may be related to loading older models. You can update your model to current structure with:
    import torch
    ckpt = torch.load("model.pt")  # applies to both official and custom models
    torch.save(ckpt, "updated-model.pt")

WARNING  'ultralytics.yolo.v8' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.models.yolo' instead.
WARNING  'ultralytics.yolo.utils' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.utils' instead.
Note this warning may be related to loading older models. You can update your model to current structure with:
    import torch
    ckpt = torch.load("model.pt")  # applies to both official and custom models
    torch.save(ckpt, "updated-model.pt")

### Environment

Ultralytics YOLOv8.0.186  Python-3.9.16 torch-2.0.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3050 Ti Laptop GPU, 4096MiB)
Setup complete  (16 CPUs, 15.7 GB RAM, 893.8/910.6 GB disk)

OS                  Windows-10-10.0.22621-SP0
Environment         Windows
Python              3.9.16
Install             pip
RAM                 15.71 GB
CPU                 11th Gen Intel Core(TM) i7-11800H 2.30GHz
CUDA                11.8

matplotlib           3.7.1>=3.3.0
numpy                1.24.3>=1.22.2
opencv-python        4.6.0.66>=4.6.0
pillow               9.5.0>=7.1.2
pyyaml               6.0>=5.3.1
requests             2.31.0>=2.23.0
scipy                1.9.1>=1.4.1
torch                2.0.0+cu118>=1.8.0
torchvision          0.15.1+cu118>=0.9.0
tqdm                 4.65.0>=4.64.0
pandas               1.5.3>=1.1.4
seaborn              0.12.2>=0.11.0
psutil               5.9.4
py-cpuinfo           9.0.0

### Minimal Reproducible Example

from ultralytics import YOLO
from wandb.integration.ultralytics import add_wandb_callback
import wandb

if __name__=="__main__":
    model = YOLO("yolov8n.pt")
    add_wandb_callback(model, enable_model_checkpointing=True)
    results = model.train(project='Project', data='data.yaml', epochs=100, imgsz=1024, device=0, resume=True, save=True)
    wandb.finish()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@RanaShiva hello! Thanks for reaching out with your issue regarding WandB integration with YOLOv8.

The warnings you're seeing indicate that certain modules have been deprecated and will be removed in future versions. To resolve these warnings, you should update your code to use the new module paths as suggested. Replace `ultralytics.yolo.v8` with `ultralytics.models.yolo` and `ultralytics.yolo.utils` with `ultralytics.utils`.

Regarding the WandB integration, ensure that you're using the latest version of the YOLOv8 repository and the WandB library. If you continue to encounter issues after making the recommended changes, please refer to our documentation for the most up-to-date information on integrations and feel free to open a new issue with updated details if necessary.

Your environment setup looks good, and the minimal reproducible example you provided should work once you update the module paths. If you have further questions or need additional assistance, don't hesitate to ask. Happy training! 😊
