### ISSUE TITLE
video is not playable

### ISSUE THREAD

**Issue by nitish9413** [ultralytics/ultralytics#790]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

hello 
I was trying to detect some object but when I pass video to it 
after the processing video, video is not playable 

```
model = YOLO(model='yolov8x.pt')
model.fuse()
model.predict(source=video,save=True)
```

platform : Windows , streamlit cloud , WSL

### Environment

- Python : 3.10
- windows : 8GB RAM , 250 GB SSD , intel i5 10th Gen

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AyushExel @Laughing-q video results are not saving correctly with python inference. CLI works correctly though.

CLI (good results):
```
yolo predict source=https://ultralytics.com/assets/decelera_landscape.mov
```

Python (saved video does not load/play):
```
from ultralytics import YOLO
model = YOLO(model='yolov8n.pt')
model.fuse()
model.predict(source='https://ultralytics.com/assets/decelera_landscape.mov', save=True)
```

**Comment by glenn-jocher** [comment]
@nitish9413 @AyushExel @Laughing-q resolved in https://github.com/ultralytics/ultralytics/pull/800/commits/b7984166b753e270d3a402e4a1101e1fb32a90fc which will mege to main and be part of 8.0.28 tonight. 

Thanks for raising this bug report. Please let us know if there are any other problems you spot!
