### ISSUE TITLE
Export ByteTrack with YOLOv8 model to CoreML

### ISSUE THREAD

**Issue by darylhood** [ultralytics/ultralytics#7908]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi Glenn + Ultralytics team!

Have search endlessly for a solution on this (have even read through issue # 3642 where you walk someone through it).

Didn't seem to solve the issue & I also spoke directly with the individual - he confirmed did not work.

So for clarity:
- can export yolov8 & function on coreml + iOS testflight app
- need to export yolov8 WITH the tracker (ideally ByteTrack)

Could someone please provide guidance here?

Thanks in advance,
Daryl

**Comment by darylhood** [comment]
Ayush mentioned to tag @Laughing-q

**Comment by Laughing-q** [comment]
@darylhood you mean integrate tracker with model while exporting model?
For what I can tell, it's not possible to do that, you either could to use exported model and our tracker implementation in a python env:
```python
from ultralytics import YOLO
model = YOLO('yolov8n.pt')
model.export(format='coreml', nms=True)
model = YOLO('yolov8n.mlpackage')
results = model.track("path/to/source", tracker="bytetrack")
```
or customize tracker implementation by the hardware language, mostly it's cpp but for IOS I think is Swift. :)
