### ISSUE TITLE
Why are segmentation masks cropped to the bounding box in yolo-seg models?

### ISSUE THREAD

**Issue by bruno-hoermann** [ultralytics/ultralytics#7909]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I found that my model outputs "boxy" looking masks, looked into the source code and found that masks are cropped to the bounding box [in the loss](https://github.com/ultralytics/ultralytics/blob/465df3024f44fa97d4fad9986530d5a13cdabdca/ultralytics/utils/loss.py#L308) and [prediction](https://github.com/ultralytics/ultralytics/blob/465df3024f44fa97d4fad9986530d5a13cdabdca/ultralytics/utils/ops.py#L665). What is the reasoning behind this? If I monkeypatch the crop_mask function to an identity operation would that break training?

**Comment by glenn-jocher** [comment]
@bruno-hoermann segmentation masks are cropped to the bounding box in YOLO-seg models to focus the model's attention on the area of interest, reducing computational complexity and noise from the background. This approach helps in learning more accurate masks by concentrating on the pixels within the object's vicinity. Modifying the `crop_mask` function to an identity operation might not break training, but it could lead to less precise segmentation and increased computational cost, as the model would have to handle more background information. It's always a balance between precision and efficiency. 🎯🛠️
