### ISSUE TITLE
ultralytics will greatly affect the request time of requests.

### ISSUE THREAD

**Issue by ziyaxuanyi** [ultralytics/ultralytics#791]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

When I use ultralytics in my code. I find that ultralytics will greatly affect the request time of requests.

my original code:
```
img = cv2.imread("roi.png")
t = time.time()
result = mywork(img)   # mywork() use requests.post() to do something
print(time.time()-t)
```
then it print: 0.2850244

add ultralytics to the code and the codes of ultratics and requests are irrelevant：
```
from ultralytics import YOLO
model = YOLO("yolov8m-seg.pt")
model.predict("test.png")

img = cv2.imread("roi.png")
t = time.time()
result = mywork(img)   # mywork() use requests.post() to do something
print(time.time()-t)
```
then, it print: 10.9758024

why the model.predict() can affect the running speed of request. post(), which has nothing to do with it?

### Environment

windows10
ultralytics 8.0.25
requests 2.28.2
python3.7.9

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Thanks for reporting. We'll try to reproduce and fix this.
@glenn-jocher this could be due to sentry?

**Comment by glenn-jocher** [comment]
@AyushExel maybe. I'll try to reproduce, something seems wrong.

**Comment by glenn-jocher** [comment]
@ziyaxuanyi @AyushExel just took another look at this. Without the contents of the mywork() this issue is not reproducible and there is no action for us to take. 

@ziyaxuanyi if you can submit a fully reproducible example then we can use that to debug, otherwise debugging your custom function is up to you.

**Comment by ziyaxuanyi** [comment]
@glenn-jocher sorry, due to my work reasons, I can't provide specific details of mywork().
But I test it on another computer again.

the environment:
Linux
ultralytics 8.0.25
requests 2.28.2
python3.7.10

for this time, it works normally.

So, this may be due to the operating system(windows) or python version.
Can you test whether it can be replicated under different operating systems or python versions？
Also I will test whether it can be replicated in other versions of python on my windows to determine whether it is due to the python version.

**Comment by ziyaxuanyi** [comment]
@glenn-jocher I tested some situations

for windows：
low version python 3.7.9 or 3.7.11, it costs a lot of time.
hight version python 3.10.6, it works normally.

for linux:
low version python 3.7.10, it works normally.
hight version python, I haven't tested yet.

The situation may be:
on windows, the low version python may have some bugs.
on the linux, for all version python, it works well.

Maybe you can check the compatibility of ultralytics with lower versions of python on Windows.

**Comment by ziyaxuanyi** [comment]
@glenn-jocher I think I find the problem.

It is due to this code:
ultralytics/hub/utils.py, 182 line
```
smart_request(f'{HUB_API_ROOT}/v1/usage/anonymous',
                          json=trace,
                          headers=None,
                          code=3,
                          retry=0,
                          verbose=False)
```

The above code will be executed every time model. predict() is run. It will use requests.post() to send request.
By the way, my network is an internal network, so the network cannot connect with the external network.
So it may cause the long time. When I comment out the above code, then it works normally.

How can I not use the above code？When using the local model, there is no need to send online requests.

**Comment by ch-hristov** [comment]
I'm also getting problems with 

```

smart_request(f'{HUB_API_ROOT}/v1/usage/anonymous',
                          json=trace,
                          headers=None,
                          code=3,
                          retry=0,
                          verbose=False)
```

Is there a way to disable the anonymous reporting?

**Comment by theotherp** [comment]
You can set `sync: false` in your `settings.yaml`.

**Comment by glenn-jocher** [comment]
@ch-hristov @theotherp @ziyaxuanyi thanks for the feedback! I'll take a look at this.

**Comment by akx** [comment]
I think the whole `sync` option should be very prominently documented (not just in a docstring introduced in #125), because it's pretty surprising that a library would quietly send pseudonymous (not anonymous, since the `settings['uuid']` value is deterministic) data to an arbitrary location.

`sync` also seems to enable posting error reports to [Sentry](https://sentry.io/); this seems to have been added in #449 (and #568, etc.). IANAL, but this could have some GDPR consequences since Sentry is a third party.

**Comment by pderrenger** [comment]
@akx thanks for bringing this up! The `sync` option is indeed an important feature to be documented clearly, and your insights about the potential implications of error reporting to third-party services are valid. I'll make sure to escalate this for discussion with our team to ensure that this aspect is appropriately addressed in the documentation and to consider any necessary updates to the error reporting functionality. Thank you for your valuable input!
