### ISSUE TITLE
Is yolov8 able to do instance segmentation in obb box?

### ISSUE THREAD

**Issue by RalphGuo** [ultralytics/ultralytics#7918]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

First ,thanks for your wonderful job in OBB det! I found that in instance segmentation demo, both masks and boxed could be shown in the same time, while in obb det demo, there are only rotated boxes shown and not any mask. Is it possible that both instance segmentation and OBB det done in the same time in dataset like DOTA?

**Comment by glenn-jocher** [comment]
@RalphGuo hello! Thank you for reaching out and for your kind words. YOLOv8 does indeed support object detection with bounding boxes, including oriented bounding boxes (OBB). However, instance segmentation with OBB is not directly supported in the current implementation. Instance segmentation in YOLOv8 provides axis-aligned masks, not rotated ones.

For a dataset like DOTA, which requires OBB, you would be able to detect objects with rotated bounding boxes, but the segmentation masks would be axis-aligned. Combining OBB detection with instance segmentation in one step is an area for potential future development.

For more details on the capabilities of YOLOv8, please refer to our documentation on detection and segmentation tasks. 😊📚

**Comment by RalphGuo** [comment]
> @RalphGuo hello! Thank you for reaching out and for your kind words. YOLOv8 does indeed support object detection with bounding boxes, including oriented bounding boxes (OBB). However, instance segmentation with OBB is not directly supported in the current implementation. Instance segmentation in YOLOv8 provides axis-aligned masks, not rotated ones.
> 
> For a dataset like DOTA, which requires OBB, you would be able to detect objects with rotated bounding boxes, but the segmentation masks would be axis-aligned. Combining OBB detection with instance segmentation in one step is an area for potential future development.
> 
> For more details on the capabilities of YOLOv8, please refer to our documentation on detection and segmentation tasks. 😊📚

Thanks for your explanation! Is it already in your development plan already?

**Comment by RalphGuo** [comment]
> @RalphGuo hello! Thank you for reaching out and for your kind words. YOLOv8 does indeed support object detection with bounding boxes, including oriented bounding boxes (OBB). However, instance segmentation with OBB is not directly supported in the current implementation. Instance segmentation in YOLOv8 provides axis-aligned masks, not rotated ones.
> 
> For a dataset like DOTA, which requires OBB, you would be able to detect objects with rotated bounding boxes, but the segmentation masks would be axis-aligned. Combining OBB detection with instance segmentation in one step is an area for potential future development.
> 
> For more details on the capabilities of YOLOv8, please refer to our documentation on detection and segmentation tasks. 😊📚

Thanks for the explanation! Is it already in your development plan already?

**Comment by glenn-jocher** [comment]
@RalphGuo, glad to clarify! Combining OBB detection with instance segmentation is not currently in our immediate development roadmap. We appreciate the suggestion and will consider it for future updates. Keep an eye on our repository for any announcements regarding new features! 😊🚀

**Comment by RalphGuo** [comment]
No problem!

**Comment by RalphGuo** [comment]
No Problem!

**Comment by glenn-jocher** [comment]
@RalphGuo glad to help! If you have any more questions, feel free to ask. 😊👍
