### ISSUE TITLE
add a function in classify: topn_acc

### ISSUE THREAD

**Issue by xingshuoli** [ultralytics/ultralytics#7919]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

when i want to print top 3 acc, i need to add a new function in code. But i think we can set an arg for print top acc what you want. 

### Use case

for some tasks for a few classes, we can see the top2 or top3 acc.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@xingshuoli thank you for the feature request! Introducing a `topn_acc` function to display the top-N accuracy for classification tasks is indeed a valuable suggestion. It would allow users to evaluate model performance more comprehensively, especially in cases with a small number of classes where top-2 or top-3 accuracy metrics are meaningful.

We'll consider this for future updates. Meanwhile, if you're interested in contributing to the project, we welcome pull requests. Your input helps us improve and cater to the community's needs. Keep an eye on the updates! 😊🚀
