### ISSUE TITLE
Keypoint cordinate and detect specific special pose only

### ISSUE THREAD

**Issue by AISoltani** [ultralytics/ultralytics#7920]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Dear YOLOv8.

Thanks for Your great job.

First How to extract only the coordinates of keypoints?
The next question is whether it is possible to recognize only special pose?
for example, if the hands were raised model accept this pose. would it be acceptable? I can write its conditions on the output of the keypoints, but I want these conditions to be in the model, is it possible? my mean when i input image to the model without any condition it calculate and return me the results.

**Comment by glenn-jocher** [comment]
@AISoltani hello! Thank you for reaching out and for your kind words.

To extract only the coordinates of keypoints, you would use the Pose/Keypoint Estimation task supported by YOLOv8. This task will provide you with the locations of specific keypoints in your images.

Regarding the recognition of special poses, such as raised hands, YOLOv8 does not natively distinguish between poses. However, you can post-process the keypoint coordinates to determine if a specific pose is present. This would involve writing your own logic outside the model to analyze the keypoints and decide if the pose matches your criteria.

For implementing pose-specific conditions directly within the model, you would need to train the model on a dataset labeled with the poses of interest. YOLOv8 itself does not include functionality for training on pose data, so you would need to adapt the model or use additional software that specializes in pose estimation.

For more details on the tasks and capabilities of YOLOv8, please refer to our documentation at https://docs.ultralytics.com.

**Comment by AISoltani** [comment]
> @AISoltani hello! Thank you for reaching out and for your kind words.
> 
> To extract only the coordinates of keypoints, you would use the Pose/Keypoint Estimation task supported by YOLOv8. This task will provide you with the locations of specific keypoints in your images.
> 
> Regarding the recognition of special poses, such as raised hands, YOLOv8 does not natively distinguish between poses. However, you can post-process the keypoint coordinates to determine if a specific pose is present. This would involve writing your own logic outside the model to analyze the keypoints and decide if the pose matches your criteria.
> 
> For implementing pose-specific conditions directly within the model, you would need to train the model on a dataset labeled with the poses of interest. YOLOv8 itself does not include functionality for training on pose data, so you would need to adapt the model or use additional software that specializes in pose estimation.
> 
> For more details on the tasks and capabilities of YOLOv8, please refer to our documentation at https://docs.ultralytics.com.

Dear @glenn-jocher , Thank you for your answer,
With what comment  I can extract the keypoints and their pixel locations on the image?

**Comment by glenn-jocher** [comment]
Hello @AISoltani! To extract keypoints and their pixel locations, you'll use YOLOv8's Pose/Keypoint Estimation task. After running your images through the model, you'll receive the keypoint coordinates as part of the output. For recognizing specific poses, you'll need to implement custom logic based on these coordinates. Please refer to our Pose/Keypoint Estimation documentation for guidance on using this feature. 🚀
