### ISSUE TITLE
Detecting a certain existing class in the base model plus some new classes

### ISSUE THREAD

**Issue by mirshaadrayiz** [ultralytics/ultralytics#7922]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I am building a model to detect persons, headwear, masks and weapons. I noticed that the YOLOv8 base model detects persons really well and would like to use it. Is there any way I can preserve the models performance on person detection while training for the additional classes. My annotated dataset for headwear,masks and weapons have people instances, but they are not annotated.

**Comment by glenn-jocher** [comment]
@mirshaadrayiz hello! To preserve the performance on person detection while adding new classes, you can perform what's known as "transfer learning." Start by training YOLOv8 on your new classes (headwear, masks, and weapons) using a dataset that includes these annotations. When setting up your training configuration, make sure to include the class for 'person' even though it's not annotated in your new dataset. This way, the model retains its ability to detect persons from the pre-trained weights while learning to identify the new classes.

During training, the model will update the weights for the new classes while attempting to maintain its proficiency in detecting persons. It's a balancing act, but YOLOv8 is designed to handle such scenarios effectively. For detailed guidance on how to set up your training process, please refer to our documentation on the Train mode. Good luck with your model training! 🚀

**Comment by mirshaadrayiz** [comment]
My images for headwear, masks and weapons contains many instances of person which are NOT annotated, only the objects are annotated. Won't this affect the model's ability to detect persons as this implies particular person detections as background?

Should i take the hard way and manually annotate all person instances in my headwear, masks, and weapon images too?

**Comment by glenn-jocher** [comment]
@mirshaadrayiz if your dataset only annotates headwear, masks, and weapons without annotating persons, the model might indeed start to consider persons as background, which could degrade its ability to detect persons over time. To maintain performance on person detection, it would be beneficial to annotate person instances in your images. This extra effort can help the model to accurately detect both the new classes and the person class. 🎯

**Comment by mirshaadrayiz** [comment]
Thank you very much for your response. Since the YOLOv8 base model detects 'person' very well. I am currently trying to annotate persons in other images using the base model (i.e. a model assisted annotation method). I have extracted the x, y, w and h values from the output. However, I am slightly confused on whether I should normalize the values. 

![image](https://github.com/ultralytics/ultralytics/assets/147004775/56ef84f7-5326-4e17-83f2-263dd7fe7e1b)

**Comment by glenn-jocher** [comment]
@mirshaadrayiz, when preparing annotations for YOLOv8, it's important to normalize the bounding box coordinates (x, y, w, h) relative to the image width and height. This ensures that the model can understand the annotations regardless of the image size. So, yes, you should normalize these values between 0 and 1 for the model to train correctly. 🎨

**Comment by mirshaadrayiz** [comment]
Thank you. I would also like to know whether I should download 'person' class instance images from the COCO dataset and include it when i train my model? Will that have a significant? impact on the model's performance? Or, is annotating person instances in my other datasets sufficient?

**Comment by glenn-jocher** [comment]
@mirshaadrayiz annotating person instances in your existing dataset should generally be sufficient, especially if your dataset is representative of your use case. Adding 'person' class images from COCO can potentially improve performance if your dataset is limited, but it's not strictly necessary if you have a diverse and ample set of annotated images. 📊
