### ISSUE TITLE
Add new tracking method -  UCMCTrack

### ISSUE THREAD

**Issue by geoxpert0001** [ultralytics/ultralytics#7942]
I just read an article about a new tracking method that supports yolov8. 
Please incorporate it into the ultralytics model. 
Here's the link:
https://github.com/corfyi/UCMCTrack

And this new tracking method outperforms any other methods, such as Botsort, Bytetrack, etc.

**Comment by glenn-jocher** [comment]
@geoxpert0001 thank you for bringing UCMCTrack to our attention! We're always interested in exploring new methods that could enhance the capabilities of YOLOv8. While we can't promise immediate integration, we'll certainly consider this for future updates. The performance of tracking methods can vary based on the use case, so we appreciate insights from the community on what's working well. Keep an eye on our updates for any news on tracking improvements! 🚀

**Comment by Burhan-Q** [comment]
@Laughing-q what are your thoughts? If/when you've got bandwidth, please add the `TODO` label if you think we should add this.

**Comment by glenn-jocher** [comment]
I haven't read the paper but based on the ground plane estimation they show this may not be as robust to every environment as the current trackers, i.e. it may only outperform in certain restricted environments where all the objects are constrained to a 2D plane, but again not sure, just first impressions.

Anytime you constrain an answer with a Bayesian prior you should outperform naive answers, but only to the extent that your prior is accurate.

**Comment by khanfarhan10** [comment]
Well for cases I've seen UCMC is the best!

@glenn-jocher can we please integrate this in YOLO somehow?

**Comment by glenn-jocher** [comment]
Thank you for the suggestion. We'll review UCMCTrack's performance and consider it for future updates to YOLO.
