### ISSUE TITLE
Commercial use of oriented bounding box (OBB) using of yolov8

### ISSUE THREAD

**Issue by karantai** [ultralytics/ultralytics#7953]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello everyone!

I am highly interested in using the oriented bounding box mode of yolov8 in my project. I saw that this specific model is trained on DOTAv1. Based on this [link](https://captain-whu.github.io/DOTA/dataset.html)  _"All images and their associated annotations in DOTA can be used for academic purposes only, but any commercial use is prohibited_".

So just to clarify, `yolov8-obb.pt` cannot be used for commercial use, right?

Thanks in advance!

**Comment by glenn-jocher** [comment]
@karantai hello!

You're correct in noting that the `yolov8-obb.pt` model is trained on the DOTAv1 dataset, which is restricted to academic use only. For commercial applications, you would need to train YOLOv8 on a dataset that allows for commercial use. Our Enterprise License offers the flexibility needed for commercial product development without the open-source requirements of AGPL-3.0. This would be the appropriate path for embedding YOLOv8 in commercial products and applications.

For further guidance on licensing and commercial use, please refer to our documentation at https://docs.ultralytics.com. Thank you for your interest in YOLOv8, and we're here to support you in your project's needs! 😊

**Comment by karantai** [comment]
I am truly thankful for your immediate response!! Keep up the good work

**Comment by glenn-jocher** [comment]
@karantai, thank you for your kind words! If you have any more questions or need further assistance, feel free to reach out. Wishing you success with your projects! 😊🚀
