### ISSUE TITLE
show the accuracy for each class

### ISSUE THREAD

**Issue by osamaalschame** [ultralytics/ultralytics#7958]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to the accuracy after each epoch, I have set the verbose=True , but it does not show the accuracy for each class.

regards,

**Comment by glenn-jocher** [comment]
@osamaalschame hello! To view the accuracy for each class after training epochs, you can check the results CSV file that's saved in the `runs/train/exp*/` directory. This file logs metrics including class-wise precision, recall, and mAP (mean Average Precision) after each epoch. The verbose flag controls the print statements during training but does not affect the logging of class-wise metrics. For a detailed breakdown, you can also review the logs in TensorBoard, which is automatically enabled during training. For more information on metrics and logging, please refer to our documentation on the [Val](https://docs.ultralytics.com/modes/val) mode. 😊📊
