### ISSUE TITLE
'Forcing --batch-size 1 square inference (1,3,{imgsz},{imgsz}) for non-PyTorch models' in detection validation

### ISSUE THREAD

**Issue by dbogunowicz** [ultralytics/ultralytics#796]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

As mentioned in my question: https://github.com/ultralytics/ultralytics/issues/792, as far as I understand there is no clear way to enforce detection validation on images with shape `(B, 3, imgsz, imgsz)`. This would be very helpful, e.g. for the users that would like to run evaluation on non-Pytorch models. 

I have noticed that there is a pathway in the code that actually gets us there: https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/engine/validator.py#L109

But to "unblock" the pathway, the expression `not pt` must evaluate to True. This is never going to be the case, as long as only torch models are supported for eval - which is the state of things now.

Could you change the logic (or verbally guide me, I would love to help out with a PR), so that e.g. explicitly setting `imgsz = (640,640)` "unlocks" this pathway even when we evaluate the PyTorch model?

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by dbogunowicz** [comment]
Great job @Laughing-q , I will validate your PR asap

**Comment by dbogunowicz** [comment]
@Laughing-q's patch solved my problem

**Comment by glenn-jocher** [comment]
@yellowjs0304 hello,

The current implementation of YOLOv8 in our repository is optimized for PyTorch models and utilizes features inherently supported in PyTorch for efficient batch processing. ONNX and other non-PyTorch models, by their nature, do not directly support some PyTorch functionalities which this batch validation relies upon.

That said, extending this functionality to non-PyTorch models such as ONNX models requires a considerable amount of changes in the codebase to ensure compatibility. Given the architectural and operational differences between PyTorch and ONNX, imposing efficient batch validation for non-PyTorch models poses a significant challenge.

We are continually working towards improving and expanding the features of YOLOv8, and we appreciate your inquiry as it helps in guiding our efforts. However, at this moment, we do not have a timeline for when this feature might be available for non-PyTorch models.

Thank you for your understanding and support.
