### ISSUE TITLE
Traceback Error when running model.predict()

### ISSUE THREAD

**Issue by KowenWoo** [ultralytics/ultralytics#7962]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

when I run model.predict() I receive an error.  I was recommended to open a new issue from the previous one (https://github.com/ultralytics/ultralytics/issues/7850).

2024-02-01 20:20:31.174 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\kowen\anaconda3\envs\slTestEnv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\kowen\OneDrive\Documents\Object-Detection\test\object_detection.py", line 53, in <module>
    res = model.predict(uploaded_image)
  File "C:\Users\kowen\anaconda3\envs\slTestEnv\lib\site-packages\ultralytics\engine\model.py", line 399, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "C:\Users\kowen\anaconda3\envs\slTestEnv\lib\site-packages\ultralytics\engine\predictor.py", line 341, in setup_model
    self.model = AutoBackend(
  File "C:\Users\kowen\anaconda3\envs\slTestEnv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\kowen\anaconda3\envs\slTestEnv\lib\site-packages\ultralytics\nn\autobackend.py", line 123, in __init__
    fp16 &= pt or jit or onnx or xml or engine or nn_module or triton  # FP16
TypeError: unsupported operand type(s) for &=: 'bool' and 'str'

### Environment

I am using a conda environment with 3.9.18 python, pafy, ultralytics, streamlit, and pytorch installed.

### Minimal Reproducible Example

 I have tried changing the arguments for predict and ensuring confidence is a int.

Here is the code for my app: 

import PIL
import streamlit as st
from ultralytics import YOLO

# Replace the relative path to your weight file
model_path = "C:/Users/kowen/OneDrive/Documents/Object-Detection/test/weights"

# Setting page layout
st.set_page_config(
    page_title="Object Detection using YOLOv8",  # Setting page title
    page_icon="🤖",     # Setting page icon
    layout="wide",      # Setting layout to wide
    initial_sidebar_state="expanded"    # Expanding sidebar by default
)

# Creating sidebar
with st.sidebar:
    st.header("Image/Video Config")     # Adding header to sidebar
    # Adding file uploader to sidebar for selecting images
    source_img = st.file_uploader(
        "Choose an image...", type=("jpg", "jpeg", "png", 'bmp', 'webp'))

    # Model Options
    confidence = float(st.slider(
        "Select Model Confidence", 25, 100, 40)) / 100

# Creating main page heading
st.title("Object Detection using YOLOv8")

# Creating two columns on the main page
col1, col2 = st.columns(2)

# Adding image to the first column if image is uploaded
with col1:
    if source_img:
        # Opening the uploaded image
        uploaded_image = PIL.Image.open(source_img)
        # Adding the uploaded image to the page with a caption
        st.image(source_img,
                 caption="Uploaded Image",
                 use_column_width=True
                 )

try:
    model = YOLO(model_path, task = "detect")
except Exception as ex:
    st.error(
        f"Unable to load model. Check the specified path: {model_path}")
    st.error(ex)

if st.sidebar.button('Detect Objects'):
    res = model.predict(uploaded_image)
    boxes = res[0].boxes
    res_plotted = res[0].plot()[:, :, ::-1]
    with col2:
        st.image(res_plotted,
                 caption='Detected Image',
                 use_column_width=True
                 )
        try:
            with st.expander("Detection Results"):
                for box in boxes:
                    st.write(box.xywh)
        except Exception as ex:
            st.write("No image is uploaded yet!")

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@KowenWoo hello! Thank you for the detailed report. It seems like there's a type error in the `predict` method, possibly due to a configuration issue with the input arguments or environment setup.

To resolve this, please ensure that:
1. Your environment is set up correctly with compatible versions of the required libraries.
2. The `model_path` is correct and points to a valid YOLOv8 weights file.
3. The `confidence` value is being correctly passed as a float between 0 and 1.

If the issue persists, consider isolating the problem by running a minimal example outside of Streamlit to see if `model.predict()` works in a simpler environment. If it does, the issue might be related to how Streamlit is handling the model or the input data.

Since you're willing to submit a PR, you might want to look into the `autobackend.py` file where the error is originating and ensure that all logical operations are performed with compatible data types.

If you need further assistance, please provide more details on the issue tracker, and we'll be happy to help. Thank you for your contribution to the YOLOv8 community! 🚀

**Comment by KowenWoo** [comment]
@glenn-jocher I tried running predict with new weights and setup in google colab and still received the same error. I believe it has something to do with model.predict() itself and not streamlit or my environment used previously. Is there anything else I can do to fix this?

**Comment by KowenWoo** [comment]
After looking through autobackend.py I think I pin pointed the line that is causing the errors:
 @staticmethod
    def _model_type(p="path/to/model.pt"):
        """
        This function takes a path to a model file and returns the model type. Possibles types are pt, jit, onnx, xml,
        engine, coreml, saved_model, pb, tflite, edgetpu, tfjs, ncnn or paddle.

        Args:
            p: path to the model file. Defaults to path/to/model.pt

        Examples:
            >>> model = AutoBackend(weights="path/to/model.onnx")
            >>> model_type = model._model_type()  # returns "onnx"
        """
        from ultralytics.engine.exporter import export_formats

        sf = list(export_formats().Suffix)  # export suffixes
        if not is_url(p, check=False) and not isinstance(p, str):
            check_suffix(p, sf)  # checks
        name = Path(p).name
        types = [s in name for s in sf]
        types[5] |= name.endswith(".mlmodel")  # retain support for older Apple CoreML *.mlmodel formats
        types[8] &= not types[9]  # tflite &= not edgetpu
        if any(types):
            triton = False
        else:
            from urllib.parse import urlsplit

            url = urlsplit(p)
            triton = url.netloc and url.path and url.scheme in {"http", "grpc"}

        **return types + [triton]**

On the last line here where the function is returning types + [triton] it isreturning a list of boolean values along with 'triton' as the last element, rather than a single boolean value when the model type is .pt. I believe changing this to **return any(types) or triton** would fix this error as this returns a single boolean rather than a list if the model type is .pt

**Comment by KowenWoo** [comment]
@glenn-jocher how do I go about submitting a pull request to fix this issue?

**Comment by glenn-jocher** [comment]
Hello @KowenWoo! Great catch on identifying the potential fix! 🌟 To submit a pull request:

1. Fork the [Ultralytics repository](https://github.com/ultralytics/ultralytics) on GitHub.
2. Clone your fork locally and create a new branch for your fix.
3. Implement your fix and commit the changes.
4. Push the changes to your fork.
5. Go to the original Ultralytics repository on GitHub and click on 'Pull requests'.
6. Click 'New pull request', select your fork and branch, then submit it with a clear description of the fix.

Thanks for contributing to the improvement of YOLOv8! If you need any more help, feel free to ask.
