### ISSUE TITLE
On the Detection of Small Objects under Low Pixel Conditions

### ISSUE THREAD

**Issue by 050603** [ultralytics/ultralytics#7971]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I have a question to ask. I am a beginner at YOLO. In my project, my training dataset and final application scenario are both for detecting images with a pixel size of approximately 84 * 143, with the target being prototype bubble objects of several pixel sizes.
Do you have any suggestions for modifying the YOLOv8 network or for training methods and parameters for this application scenario?

Additionally
I have seen other issues that mention using yolov8-p2 to detect small objects, but I am not sure if it can currently be defined as a small object in my application scenario (because the image pixels themselves are not high).

**Comment by 050603** [comment]
My dataset looks like this.
![001](https://github.com/ultralytics/ultralytics/assets/97741452/a123cec4-8f3e-41df-8db1-3b66b300d013)

**Comment by glenn-jocher** [comment]
@050603 hello! For detecting small objects in low-resolution images like yours, it's crucial to focus on a few key aspects:

1. **Data Augmentation**: Enhance your dataset with various augmentations that simulate the conditions your model will face in the real world. This can help the model generalize better to small objects.

2. **Model Selection**: Consider using a model variant designed for small object detection. While I can't provide specific model names, look for those with finer feature maps early in the network.

3. **Hyperparameters**: Tuning hyperparameters such as anchor sizes can be beneficial for small object detection. Ensure that the anchors are appropriate for the scale of objects in your dataset.

4. **Training Strategy**: Start training on a pre-trained model if possible, as this can provide a good feature extraction base. Then, fine-tune the model on your specific dataset.

5. **Resolution**: Training at a higher resolution can sometimes help, but be mindful of the trade-off with computational cost.

For detailed guidance on each of these points, please refer to our documentation on training and model selection. Good luck with your project! 🚀

**Comment by 050603** [comment]
> @050603 hello! For detecting small objects in low-resolution images like yours, it's crucial to focus on a few key aspects:
> 
> 1. **Data Augmentation**: Enhance your dataset with various augmentations that simulate the conditions your model will face in the real world. This can help the model generalize better to small objects.
> 2. **Model Selection**: Consider using a model variant designed for small object detection. While I can't provide specific model names, look for those with finer feature maps early in the network.
> 3. **Hyperparameters**: Tuning hyperparameters such as anchor sizes can be beneficial for small object detection. Ensure that the anchors are appropriate for the scale of objects in your dataset.
> 4. **Training Strategy**: Start training on a pre-trained model if possible, as this can provide a good feature extraction base. Then, fine-tune the model on your specific dataset.
> 5. **Resolution**: Training at a higher resolution can sometimes help, but be mindful of the trade-off with computational cost.
> 
> For detailed guidance on each of these points, please refer to our documentation on training and model selection. Good luck with your project! 🚀

@glenn-jocher Thank you for your reply. But I still have a question. In my usage scenario, can using YOLOv8-p2 help improve my model recognition performance.

Also, does the fifth point you mentioned refer to the imgsz parameter during training?

**Comment by Burhan-Q** [comment]
Yes the YOLOv8-p2 could be useful. Before trying that, I would recommend trying a YOLOv8s model and setting `imgsz=320`. You will really need to ensure your dataset annotations are well placed and consistent, otherwise the model will have difficulty during training and not perform well. If you're looking for additional support, consider joining the [Ultralytics Discord Server](https://ultralytics.com/discord)

**Comment by 050603** [comment]
> Yes the YOLOv8-p2 could be useful. Before trying that, I would recommend trying a YOLOv8s model and setting `imgsz=320`. You will really need to ensure your dataset annotations are well placed and consistent, otherwise the model will have difficulty during training and not perform well. If you're looking for additional support, consider joining the [Ultralytics Discord Server](https://ultralytics.com/discord)

@Burhan-Q Thank you very much for your reply. I would like to confirm again, as I misunderstood your suggestion. Do I need to use yolov8-p2 to train my dataset on top of the pre trained model YOLOv8s? Like this:`model = YOLO('yolov8s-p2.yaml').load('yolov8s.pt')`
Also, I am wondering if using a pre trained model is a good choice, considering that my dataset and the dataset used by the pre trained model have almost no similarity?

**Comment by Burhan-Q** [comment]
@050603 just using `model = YOLO("yolov8s.pt")` is sufficient to start with testing. If you find that the detection is not as good as you'd like, you can try using the p2 model instead by simply creating a model using`model = YOLO(yolov8s-p2.pt")`. Using the pretrained weights is not going to be an issue when completely training a model.

**Comment by 050603** [comment]
@Burhan-Q Sincere thanks for your help！
