### ISSUE TITLE
OBB-Add angle information to the forecast map

### ISSUE THREAD

**Issue by Zzzxi** [ultralytics/ultralytics#7972]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When using OBB for rotating target prediction, I want to label the angle information in the prediction plot, how do I go about this?

**Comment by glenn-jocher** [comment]
@Zzzxi hello! For adding angle information to the prediction plot in an Oriented Bounding Box (OBB) scenario, you would need to modify the visualization code to extract and display the angle data. This typically involves adjusting the function responsible for drawing the predictions to also read angle information from the detection outputs and include it in the plotted annotations. Please refer to the documentation on the Predict mode for guidance on how predictions are handled. If you need further assistance, feel free to ask more specific questions in the discussions section. Happy coding! 😊📐

**Comment by Zzzxi** [comment]
> @Zzzxi hello! For adding angle information to the prediction plot in an Oriented Bounding Box (OBB) scenario, you would need to modify the visualization code to extract and display the angle data. This typically involves adjusting the function responsible for drawing the predictions to also read angle information from the detection outputs and include it in the plotted annotations. Please refer to the documentation on the Predict mode for guidance on how predictions are handled. If you need further assistance, feel free to ask more specific questions in the discussions section. Happy coding! 😊📐

Thank you, I will go and give it a try.😊

**Comment by glenn-jocher** [comment]
You're welcome, @Zzzxi! If you have any more questions or need further guidance, the discussions section is always open. Good luck with your implementation! 😊👍
