### ISSUE TITLE
YOLO classification model in val() mode stuck after scanning / cache creation only on GPU

### ISSUE THREAD

**Issue by tdewaard** [ultralytics/ultralytics#7975]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

val

### Bug

I am validating a YOLO classification model on a test set in a local directory using model.val(). 
Running the validation in CPU mode works fine.
When in GPU mode it successfully checks the train, val and test splits, creates a test.cache if not already present, then gets indefinitely stuck: no batches are loaded in and the output validation directory remains empty. There is no error or exception being thrown. GPU usage remains at 0%. Model.predict() in GPU mode works fine.

### Environment

Ultralytics YOLOv8.1.8 🚀 Python-3.11.7 torch-2.2.0+cu118 CUDA:0 (NVIDIA GeForce GTX 1650 with Max-Q Design, 4096MiB)
Setup complete ✅ (8 CPUs, 15.7 GB RAM, 190.5/475.5 GB disk)

### Minimal Reproducible Example

```
   metrics = model.val(
        data="path/to/some/classification/dataset", # must contain train, test and val splits
        plots=True,
        save_json=True,
        save_hybrid=True,
        batch=10,
        project="path/to/some/output/dir",
        name="val_out",
        split="test",
    )
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Burhan-Q** [comment]
@tdewaard have you tested with the `imagenet-10` classification dataset? This runs successfully for me, so I would recommend testing this out on your system as well to confirm that it's not a system level issue.

```shell
Ultralytics YOLOv8.1.8 🚀 Python-3.11.6 torch-2.2.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3080, 12288MiB)
Setup complete ✅ (12 CPUs, 31.9 GB RAM, 196.0/1863.0 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.11.6
Install             pip
RAM                 31.86 GB
CPU                 Intel Core(TM) i5-10600K 4.10GHz
CUDA                12.1

matplotlib          ✅ 3.8.2>=3.3.0
numpy               ✅ 1.24.1>=1.22.2
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 9.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.28.1>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.2.0+cu121>=1.8.0
torchvision         ✅ 0.17.0+cu121>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.0>=1.1.4
seaborn             ✅ 0.13.1>=0.11.0
```

```py
from ultralytics import YOLO

model = YOLO("yolov8n-cls.pt")
results = model.train(data="imagenet10", epochs=16, device='cuda')
```
![image](https://github.com/ultralytics/ultralytics/assets/62214284/a1ec30ea-e26e-4f55-b8ab-18774f9724b5)

**Comment by Burhan-Q** [comment]
Also, since you have a GTX-1650, try using `amp=False` if you run into issues with training. There's something about these GPUs that doesn't seem to work well with the PyTorch Automatic Mixed Precision (AMP) functionality

**Comment by tdewaard** [comment]
@Burhan-Q thanks for your reply,
I tried the training method with amp=True and amp=False:
`model = YOLO("yolov8n-cls.pt")
results = model.train(
    data="imagenet10",
    amp=False,
    batch=2,
    epochs=2,
    device="cuda",
)`
Both fail at 0% of the first epoch as it seems it runs out of memory with:
`RuntimeError: DataLoader worker (pid(s) 21984, 22124, 22224) exited unexpectedly`
A similar thing happens when I try val():
`
results = model.val(
    data="imagenet10",
    amp=False,
    batch=2,
    epochs=2,
    device="cuda",
)
`

**Comment by tdewaard** [comment]
@Burhan-Q 
Indeed, running this on Windows:
![image](https://github.com/ultralytics/ultralytics/assets/19609564/6c6e3952-f9ed-4481-a841-c422976d5841)
I am well aware of the hardware requirements of training YOLO - the model I want to validate is trained in an AzureML compute cluster, though I want to a validate a small dataset locally (which should work with my specs).
I will report back with using your suggested parameters.

**Comment by tdewaard** [comment]
@Burhan-Q 
Tested with the imagenet10 dataset: all now seems to work fine on CUDA when I use `workers=0` !

**Comment by Neuroick** [comment]
@Burhan-Q Thanks. I was in similar situation, stucking after the scanning stage, and it do work for me setting `workers=0`
