### ISSUE TITLE
Improving yolov8-obb detections at different orientations.

### ISSUE THREAD

**Issue by poojatambe** [ultralytics/ultralytics#7977]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, 
Have trained yolov8s-obb model on custom data of approx 700 images for 1500 epochs. On validation data model's performance is 
<img width="479" alt="image" src="https://github.com/ultralytics/ultralytics/assets/64680838/901458b5-809e-47a7-a180-fb908fef242d">
The no of detections at orientations other than vertical and horizontal are less and the one's that are detected sometimes have incorrect bounding box alignment.

How to improve model's performance at different orientations and correct alignment of the bounding box? Any parameters while training that can set to get improvement?
Thanks in advance!

**Comment by Burhan-Q** [comment]
@poojatambe I replied to your message in Discord as well, so I'm going to mirror the answer here.

- make certain that your dataset has bounding boxes that are tight to the object boundaries; minimal non-object pixels inside of boxes and no object pixels outside of bounding boxes
- add more samples to training data
- use `degrees=N` hyperparameter to randomly vary rotation of images `+/- N degrees` during training to help with model robustness
