### ISSUE TITLE
yolo train CLI: add augmentation hyperparameters

### ISSUE THREAD

**Issue by MalteEbner** [ultralytics/ultralytics#7984]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I would like to tune the training augmentations when using the `yolo train` CLI.

### Use case

Currently, I can use the `yolo train CLI` like this:
```
yolo detect train \
    data=yolo.yaml \
    model=yolov8n.pt \
    name=some_name \
    epochs=100 \
    ... 
    imgsz=1280
```
The available parameters are documented [here](https://docs.ultralytics.com/usage/cfg/).

However, I would also like to tune some augmentation hyperparameters from the CLI.
By far most important for me would be the `random_crop_size`, as it would allow to process very large images (e.g. 4k or 8k images) with small objects efficiently.
Wished parameters are e.g.
```
random_crop_size: 640              # Size of the input images in pixels.
min_scale: 0.15             # Minimum size of random crop relative to input_size.
vf_prob: 0.0                # Probability that vertical flip is applied.
hf_prob: 0.5                # Probability that horizontal flip is applied.

random_gray_scale: 0.2      # Probability of converting image to gray scale.
cj_prob: 0.8                # Probability that color jitter is applied.
cj_bright: 0.7              # Color_jitter intensity for brightness,
cj_contrast: 0.7            # contrast,
cj_sat: 0.7                 # saturation,
cj_hue: 0.2                 # and hue.
```

**Comment by glenn-jocher** [comment]
@MalteEbner hello! Thank you for your interest in enhancing the `yolo train` CLI with additional augmentation hyperparameters. 🚀

Your suggestion for including parameters like `random_crop_size`, `min_scale`, `vf_prob`, `hf_prob`, and others related to color jitter and grayscale conversion is noted. These parameters can indeed be useful for fine-tuning the augmentation process, especially when dealing with large images and small objects.

Currently, these specific augmentation settings are not directly adjustable via the CLI. However, they can be modified in the YAML configuration files. We understand the convenience that CLI-accessible hyperparameters can provide and will consider this feature for future updates.

For now, please refer to the documentation on how to customize your training configuration file to adjust these settings. Your feedback is valuable, and we appreciate your contribution to the YOLOv8 community! Keep an eye on the repository for updates on this feature. 🌟

**Comment by MalteEbner** [comment]
I just found that the configuration values in the `Augmentation ` section of the [configuration docs](https://docs.ultralytics.com/usage/cfg/#export) can be used as well, thus I can set them directly.

Perhaps you can make this clearer in the docs. E.g. tell in the `Training` Section that all the arguments in the `Augmentation` section can be used as well via CLI.

Alternatively, merge the two together, it is not 100% clear to me why some parameters belong to the `Training`and some to the `Augmentation` section.

Furthermore, the grouping in the docs [configuration docs](https://docs.ultralytics.com/usage/cfg/#export) and in the [default.yaml](https://github.com/ultralytics/ultralytics/blob/da408394510f536cffc429ce680e22b910033c29/ultralytics/cfg/default.yaml#L89-L119) should be the same

**Comment by glenn-jocher** [comment]
@MalteEbner thank you for your interest in enhancing the `yolo train` CLI with additional augmentation hyperparameters! 🚀

Currently, the CLI does not support direct input of augmentation parameters like `random_crop_size`. However, you can modify these settings in the `hyp.yaml` file associated with your dataset or model configuration. Once you've adjusted the augmentation settings in the `hyp.yaml` file, you can then reference this file in your CLI command using the `hyp` argument:

```bash
yolo detect train \
    data=yolo.yaml \
    model=yolov8n.pt \
    name=some_name \
    epochs=100 \
    imgsz=1280 \
    hyp=path/to/your/hyp.yaml
```

In your `hyp.yaml`, you can specify the augmentation parameters you mentioned:

```yaml
random_crop_size: 640
min_scale: 0.15
vf_prob: 0.0
hf_prob: 0.5
random_gray_scale: 0.2
cj_prob: 0.8
cj_bright: 0.7
cj_contrast: 0.7
cj_sat: 0.7
cj_hue: 0.2
```

This way, you can control the augmentations used during training without needing to pass each parameter individually through the CLI. If you have any further questions or need assistance, feel free to open an issue in the [Ultralytics YOLOv8 repo](https://github.com/ultralytics/ultralytics/issues), and we'll be happy to help! 🛠️

Happy training! 🎉

**Comment by beenotung** [comment]
Update: yolo cli no longer takes the `hyp` argument, the config file should be specified by `cfg` instead.

**Comment by glenn-jocher** [comment]
@beenotung thank you for the update. You are correct, the `cfg` argument should now be used to specify the configuration file instead of `hyp`. For more details, you can refer to the [configuration documentation](https://docs.ultralytics.com/usage/cfg/).
