### ISSUE TITLE
Where can I find the yolov8 YAML files?

### ISSUE THREAD

**Issue by JDang-At-Festo** [ultralytics/ultralytics#7990]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I am currently trying to train a yolov8 OBB model from scratch and not use any pretrained weights or transfer learning. Specifically I am looking to do something of the like:
```
from ultralytics import YOLO 
model = YOLO("path/yolov8n-obb.yaml")
res = model.train()
```
However during object instantiation of the model variable, the yaml file cannot be found and throws an error. I am able to find trained weights files on the [ultralytics OBB page](https://docs.ultralytics.com/tasks/obb/) already online however the base yaml file does not seem to exist with the pip installation. 

I then proceeded to clone the [YOLOV8 Repo](https://github.com/ultralytics/ultralytics) hoping potentially there may be a copy of the desired yaml file. When searching my entire machine via command line, it was able to find the ultralytics folder however no instance of the yaml file could be found. Below is the search done via CMD on Windows:
![FindingYaml](https://github.com/ultralytics/ultralytics/assets/114007918/2fecdc03-d259-4716-989e-ff32aae67562)

Due to this fact I believe that the yaml file is not located within the pip installation or the main branch of the repository. I was able to find a branch that did contain yaml files however just not the one I was looking for. This is the branch [model_yaml_args](https://github.com/ultralytics/ultralytics/tree/model_yaml_args) located under ultralytics/ultralytics/models/v8/ directory. 

I have found similar questions to this one such as [issue 5183](https://github.com/ultralytics/ultralytics/issues/5183), as well as [issue 6640](https://github.com/ultralytics/ultralytics/issues/6640) but they did not offer too much resolution to my question. 

My question: Where can I find and obtain the base yolov8n-obb.yaml file? 

### Additional

Thank you for taking the time to address this. I very much enjoy using ultralytics and continue to refer this repo to everyone within my circles!

**Comment by glenn-jocher** [comment]
@JDang-At-Festo hello! Thank you for reaching out and for your support of Ultralytics. 🙌

The YAML files for YOLOv8 models, including the `yolov8n-obb.yaml` you're looking for, are typically located within the `models` directory of the YOLOv8 repository. If you've cloned the repository and can't find the specific YAML file, it's possible that it has not been pushed to the main branch or is located in a different branch or directory.

For the most up-to-date information on model configuration files, please refer to our documentation at https://docs.ultralytics.com. If the file is not present there or within the repository, it may not be available at this time. In such cases, we encourage users to adapt existing YAML files to their needs or reach out to us through the repository's issues or discussions for further assistance.

We appreciate your enthusiasm and recommendations, and we're here to help with any further questions you might have! 😊

**Comment by Burhan-Q** [comment]
In the repo go to [main/ultralytics/cfg/models/v8](https://github.com/ultralytics/ultralytics/tree/main/ultralytics/cfg/models/v8). Generally you should load the `.pt` file instead `model = YOLO("yolov8n-obb.pt")` and these files will automatically download in the working directory.

**Comment by fincoder468** [comment]
Hi @glenn-jocher, I'm unable to find yolov8m.yaml file on github or site. Could you please help me find it?

**Comment by glenn-jocher** [comment]
@fincoder468 hi there! 👋 The `yolov8m.yaml` file, like other model configuration files, should be located within the `models` directory of the YOLOv8 repository. If you're having trouble finding it, it's possible it might not be available or named differently. For training or modifying models, you can use other YAML files as a template and adjust them according to your needs. 

For example, to load a model for training, you might use:
```python
from ultralytics import YOLO
model = YOLO('path/to/your_model.yaml')
```

If you're specifically looking for pretrained weights or a particular setup, using the `.pt` file directly is often more straightforward:
```python
model = YOLO('yolov8m.pt')
```

This will automatically download the weights to your working directory. If you have further questions or need more specific guidance, feel free to ask! 🚀

**Comment by Burhan-Q** [comment]
@fincoder468 there is no _dedicated_ `yolov8m.yaml` file. The `yolov8.yaml` contains **all** configurations for YOLOv8 `n`, `s`, `m`, `l`, and `x` as the layer structure is the same, the differences are in the layer depth, width, and max channels. https://github.com/ultralytics/ultralytics/blob/014f0b4b8d97b356246673f652ecbfc4e332cec2/ultralytics/cfg/models/v8/yolov8.yaml#L8-L12
