### ISSUE TITLE
Yolov8_format_question

### ISSUE THREAD

**Issue by 01fe20bcs018** [ultralytics/ultralytics#7997]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Does yolov8 support object detection of 3GP video or only MP4 formats ?

### Additional

no thanks

**Comment by glenn-jocher** [comment]
@01fe20bcs018 hello! YOLOv8 primarily supports MP4 video formats for object detection tasks. However, you can easily convert 3GP videos to MP4 using various video conversion tools before running predictions with YOLOv8. Happy detecting! 😊🚀

**Comment by Burhan-Q** [comment]
@01fe20bcs018 you can find all directly supported image and video formats [here in the docs](https://docs.ultralytics.com/modes/predict/#image-and-video-formats)
