### ISSUE TITLE
Can't hide boxes boxes with Pose

### ISSUE THREAD

**Issue by Carsoncantcode** [ultralytics/ultralytics#8000]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi!  I can't hide confidence score/ boxes in my cv capture for some reason despite sending the arguments. This is what my code looks like:

`import cv2
from ultralytics import YOLO

model = YOLO('yolov8n-pose.pt')

cap = cv2.VideoCapture(0)

assert cap.isOpened(), "Error reading video file"
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

fourcc = cv2.VideoWriter_fourcc('a', 'v', 'c', '1')
out = None
recording = False
index=0

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break

    # Visualize the results on the frame
    results = model.predict(im0,classes=0, conf=0.85, show_labels=False, show_conf=False, show_boxes=False, save=True)
        
    annotated_frame = results[0].plot()

    cv2.imshow("Biomechs", annotated_frame)

    key = cv2.waitKey(1) & 0xFF
    if key == ord('r') and not recording:
        out = cv2.VideoWriter(f'output{index}.mp4', fourcc, fps, (w, h))
        recording = True
        print("recording started")
    elif key == ord('s') and recording:
        recording = False
        out.release()
        print("Recording stopped")
        index = index + 1
    
    if recording:
        out.write(annotated_frame)
    
    if key == ord('q'):
        break

if recording:
    out.release()
cap.release()     
cv2.destroyAllWindows()
`

And I also altered my default.yaml file in cfg.

Was wondering if there was anything else I need to do to hide it because I can't figure it out/maybe save my .yaml settings.

**Comment by glenn-jocher** [comment]
@Carsoncantcode hello! It looks like you're trying to hide the confidence scores and bounding boxes in your pose estimation task using YOLOv8. If you've already set `show_labels=False`, `show_conf=False`, and `show_boxes=False` in your `model.predict()` call and are still seeing the boxes and scores, it's possible that the issue might be with the `plot()` method, which by default may display the annotations.

Instead of using `plot()`, you could directly use the `results.render()` method, which respects the flags you've set in the `predict()` call and should give you the clean output you're looking for. The `render()` method will return the frame with the applied settings, so you can display it using `cv2.imshow()` without additional annotations.

If you've made changes to the `default.yaml` file and they're not being applied, ensure that the model is loading the correct configuration file. If the issue persists, please refer to the Pose/Keypoint Estimation section in our documentation for more detailed guidance on configuring the visualization settings. 😊

**Comment by Carsoncantcode** [comment]
@glenn-jocher I appreciate the feedback.

However, I've had to use plot because when I've done results.render() I get this error:

Traceback (most recent call last):
  File "c:\work\OpenCV\yolo\yolopose.py", line 25, in <module>
    annotated_frame = results.render()
                      ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'render'

**Comment by glenn-jocher** [comment]
@Carsoncantcode, it seems there's a misunderstanding with the usage of `results.render()`. The `predict()` method returns a list of `Result` objects, one for each image or frame processed. To use `render()`, you need to access the first `Result` object in the list. Try the following:

```python
annotated_frame = results[0].render()
```

This should give you the frame without the annotations, as `render()` will adhere to the flags you've set in `predict()`. If you encounter any further issues, please consult the Pose/Keypoint Estimation documentation for additional details. 🛠️

**Comment by Burhan-Q** [comment]
```py
results = model.predict(im0, classes=0, conf=0.85, save=True) # NOTE this will save all annotated images with default config
results = model.predict(im0, classes=0, conf=0.85) # this does not save images automatically
    
annotated_frame = results[0].plot(show_labels=False, show_conf=False, show_boxes=False) # this will include your options
```

Note you will need to save `annotated_frame` in code using `cv2.imwrite` or whatever method you choose

**Comment by FelipeAmaral13** [comment]
Hi, you can comment line 189 and 191-204 in ultralytics\utils\plotting.py

**Comment by glenn-jocher** [comment]
@FelipeAmaral13 hi there! Thanks for reaching out. 😊

To address your suggestion, commenting out those lines in `plotting.py` will indeed remove certain visual elements from the output. However, for a more flexible approach, consider using the `plot()` method's arguments like `show_labels=False`, `show_conf=False`, and `show_boxes=False` when calling `model.predict()` or directly on `results.plot()`. This way, you can easily toggle these elements without modifying the source code.

For example:

```python
results = model.predict(img, show_labels=False, show_conf=False, show_boxes=False)
```

Or, if you already have your results:

```python
frame = results[0].plot(show_labels=False, show_conf=False, show_boxes=False)
```

Hope this helps! Let us know if you have any more questions.

**Comment by FelipeAmaral13** [comment]
@glenn-jocher Hi!! Thanks for reply!
When I try use this method's arguments (show_labels=False, show_conf=False and show_boxes=False) doesn't works in pose estimation predict.

**Comment by Burhan-Q** [comment]
@FelipeAmaral13 for working with `results[0].plot` you can use `labels=False, conf=False, boxes=False`. I always recommend referencing the [documentation page](https://docs.ultralytics.com/modes/predict/#plotting-results)
