### ISSUE TITLE
No Attribute XYXY

### ISSUE THREAD

**Issue by anorakthegreat** [ultralytics/ultralytics#8006]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! I'm trying to access the xyxy part of the box and it will throw an error

The Code:

from ultralytics import YOLO
import cv2

# Load a model
model = YOLO('YOLOv8nNO.pt')  # load an official model
# model.fuse()

# Predict with the model
results = model("note.jpg")  

for result in results:
    box = result.boxes.cpu().numpy

    print(box.xyxy)

Error:
Traceback (most recent call last):
  File "c:\Users\Documents\Note\detect.py", line 18, in <module>
    print(box.xyxy)
AttributeError: 'function' object has no attribute 'xyxy'

What am i doing wrong?

**Comment by Kayzwer** [comment]
`box = result.boxes.cpu().numpy()`, you miss the `()`

**Comment by glenn-jocher** [comment]
@Kayzwer it looks like you're missing the parentheses to call the `numpy` method. Try updating your code to `box = result.boxes.cpu().numpy()` and then access the attributes of the resulting numpy array. 😊

**Comment by Burhan-Q** [comment]
The ordering is important, once converted to a `numpy` array, the object will not have the `.xyxy` attribute. 

```py
results = model("note.jpg")

for result in results:
   box = result.boxes.xyxy.cpu().numpy()

print(box)
```
