### ISSUE TITLE
How do I use both .yaml and .pt when building a model?

### ISSUE THREAD

**Issue by xiaoxiaomichong** [ultralytics/ultralytics#801]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In YOLOv8, the model can only choose one of yolov8n.yaml and yolov8n.pt.
# Load a model
model = YOLO("yolov8n.yaml") # build a new model from scratch
model = YOLO("yolov8n.pt") # load a pretrained model (recommended for training)
In YOLOv5, if the model structure in yolov5s.yaml is modified, this modified .yaml and yolov5s.pt can also be used at the same time.
    parser.add_argument('--weights', type=str, default=ROOT/ 'pretrained/yolov5s.pt', help='initial weights path')
    parser.add_argument('--cfg', type=str, default=ROOT/'models/yolov5s.yaml', help='model.yaml path')
If I want to build models in YOLOv8 using both .yaml and .pt, how can I solve it?

**Comment by theotherp** [comment]
model = YOLO("best.pt")  
model.train(data="data.yaml") 

It's in the readme...

**Comment by xiaoxiaomichong** [comment]
> data=data.yaml contains information about the dataset. I want the modified YOLOv8.yaml and yolov8n.pt to work at the same time, how can I solve it?

**Comment by GangPingZ** [comment]
l have a question. how do l use my net structure（.yaml），meanwhile  use yolov8 preweight in a python env? can you help me write the train command in python env? thank you!😊😊😊

**Comment by yangtao0422** [comment]
Have you solved the problem?

**Comment by pderrenger** [comment]
@yangtao0422 yes, you can definitely use your custom `.yaml` file for your net structure along with the YOLOv8 pretrained weights in a Python environment. To achieve this, you can load the YOLOv8 model with your custom `.yaml` file and then load the pretrained weights using the `model.load_weights("yolov8n.pt")` method in Python.

Here's a simple example of the training command in Python environment using the custom `.yaml` file and the pretrained weights:

```python
from models import YOLOv8  # import the YOLOv8 model
from utils import torch_utils

# Create the YOLOv8 model from your custom .yaml file
model = YOLOv8('your_custom.yaml')

# Load the pretrained weights
model.load_weights('yolov8n.pt')

# Start training with your data
model.train(data="data.yaml")
```

This example assumes that there's a `YOLOv8` class in the `models` module and a `torch_utils` module with the `load_weights` method. Adjust the import statements and method names to match your actual code structure.

I hope this helps! Let me know if you have further questions or need more assistance. 😊
