### ISSUE TITLE
How to install CLI

### ISSUE THREAD

**Issue by tinca** [ultralytics/ultralytics#8017]
### Discussed in https://github.com/orgs/ultralytics/discussions/8014

<div type='discussions-op-text'>

<sup>Originally posted by **tinca** February  4, 2024</sup>
Hi,
I am aware that pip install is the recommended way to get access for ultralytics tools. However I do not want to use them as long as I really need them. The CLI would be the choice of tool for me at the beginning.
The docs talk about using CLI commands, but I am really feeling dumb, because I fail to find a description about how to install it.
I did a pip3 install ultralytics, but 'yolo' from the commad line gives:
-bash: yolo: command not found

Your help is appreciated!</div>

**Comment by glenn-jocher** [comment]
@tinca hello **tinca**,

To use the YOLOv8 CLI, you'll need to install the package via pip with the following command:

```bash
pip install ultralytics
```

After installation, the CLI commands are available under `ultralytics`, not `yolo`. So, to access YOLOv8 functionalities, you would use commands starting with `ultralytics`, such as `ultralytics train`, `ultralytics val`, `ultralytics predict`, etc.

For detailed documentation on each command and its usage, please refer to our documentation at https://docs.ultralytics.com. If you have any further questions or run into issues, feel free to reach out!

Happy coding! 😊
