### ISSUE TITLE
How to evaluate model using "test-dev2017"

### ISSUE THREAD

**Issue by ohjunee** [ultralytics/ultralytics#8024]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I followed the process as described below and submitted it to the Codalab server, but the evaluation result was close to 0, and there was a significant discrepancy with the results produced by the Ultralytics code.

The evaluation process for "test-dev2017" dataset using the specified steps is as follows:

1. Set `save_json=True` and `split=test` in the `coco.yaml` file. 
```
    # Load a model
    model = YOLO("/ultralytics/runs/detect/mymodel/weights/last.pt")
    # Validate the model
    metrics = model.val(data='coco.yaml', save_json=True, split='test')
```
2. Run the evaluation, which will produce a `prediction.json` file.
3. Compress the generated `prediction.json` file as `detections_test-dev2017_<model_name>_results.json.zip`.

- In my case, "detections_test-dev2017_mymodel_results.json.zip"

4. Submit the compressed file to the Codalab evaluation server for result verification.

Since "test-dev2017" does not have label information, the test results need to be submitted to the test server for verification. The provided steps seem to be correct based on [the referenced issue](https://github.com/ultralytics/yolov5/issues/2649).

### Additional
I am sharing the JSON file submitted to the evaluation server and weight file. 
[predictions.zip](https://github.com/ultralytics/ultralytics/files/14162246/predictions.zip)
[pretrained weight file](https://drive.google.com/file/d/1S-KGUO3UETegQT4OLaQyZsf4ldg6K3Uk/view?usp=drive_link)
The results displayed through the Python prompt using the above code are as follows.
```
YOLOv8s-cspvitcspp
+nestedcspp summary: 264 layers, 29924032 parameters, 0 gradients, 55.1 GFLOPs
val: Scanning /media/nas/82_databases/COCO/labels/val2017.cache... 4952 images, 48 backgrounds, 0 corrupt: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 5000/5000 [01:44<00:00, 48.07it/s]
                   all       5000      36335      0.639       0.51      0.551      0.398
                person       5000      10777      0.799      0.679       0.77      0.541
...(omttied)...
Speed: 0.2ms preprocess, 15.5ms inference, 0.0ms loss, 0.9ms postprocess per image
Saving runs/detect/val/predictions.json...
Results saved to runs/detect/val
```

_No response_

**Comment by wangtao0219** [comment]
@glenn-jocher I had the same problem.
My weight is downloaded yolov5n, and I can also get val verification result normally. The problem is only in: compression prediction.json file uploaded to the server to get 0 result.
model = YOLO("/ultralytics/runs/detect/mymodel/weights/last.pt")
metrics = model.val(data='coco.yaml', save_json=True, split='test')
Isn't there anything missing?

**Comment by glenn-jocher** [comment]
Hey there! It seems like you've got the basics down, but if you're getting 0 results after uploading, here are a couple of quick checks:

1. **Format and Structure**: Ensure your `prediction.json` is in the correct format expected by the server. Sometimes, discrepancies in formatting can lead to such issues.
2. **File Integrity**: Double-check the compressed file to make sure it hasn't been corrupted or altered. A quick way to validate is to decompress it and check if the JSON structure remains intact.

Also, here's a simplified code snippet to ensure everything's set up correctly for generating `prediction.json`:

```python
from ultralytics import YOLO

model = YOLO('path/to/yolov5n.pt')
metrics = model.val(data='coco.yaml', save_json=True, split='test')
```

Just a tiny reminder to replace `'path/to/yolov5n.pt'` with the actual path to your weight file. If everything seems right and you're still facing the same issue, it might be beneficial to verify the submission guidelines of the server you're uploading to for any specific requirements we might be missing here. 🤓

Keep pushing, and don't hesitate to drop more questions if you have any!
