### ISSUE TITLE
where can we get rtdetr (n,s,m) weights?

### ISSUE THREAD

**Issue by SoulProficiency** [ultralytics/ultralytics#8025]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

we find rtdetr-l/-xl but it is too large for some device(such as  jetson),where can we get rtdetr(n,s,m) and train on own datasets?

**Comment by glenn-jocher** [comment]
@SoulProficiency hello! The RT-DETR (n, s, m) weights are not currently provided in the Ultralytics YOLOv8 repository. However, you can train these smaller models on your own datasets by following the training instructions in our documentation. Please refer to the Train section in the Ultralytics Docs for guidance on how to train a model on your custom dataset. If you have any further questions or need assistance during the process, feel free to reach out on our issues page. Happy training! 😊🚀

**Comment by n0ngalaxy** [comment]
Hi, did you manage to resolve this?

**Comment by glenn-jocher** [comment]
@n0ngalaxy hi there! If you're still encountering the issue, could you provide a bit more detail on what you're experiencing? I'd be happy to help you sort it out! 😊🛠️

**Comment by SoulProficiency** [comment]
> Hi, did you manage to resolve this?

sorry, i plan to test pre-trained rtdetr(n,s,m) model and i cant find it .folloing @glenn-jocher reply, we should modify model config.yaml before training, but i have no idea about rtdetr(n,s,m) so i dont focus on this work now.
wish ultralytics would provide us more detail about rtdetr and this issue would closed when rtdetr(n,s,m) is provided by offical.

**Comment by glenn-jocher** [comment]
Hello @SoulProficiency! I understand you're looking to test the smaller RT-DETR models. As of now, we don't have the pre-trained weights for RT-DETR (n, s, m) available. We appreciate your patience and interest in these models. Rest assured, we'll update our community as soon as they become available. In the meantime, if you need any assistance with model configurations or training on your dataset, feel free to ask. We're here to help! 😊🚀
