### ISSUE TITLE
Ultralytics add integration for YOLO-World

### ISSUE THREAD

**Issue by Burhan-Q** [ultralytics/ultralytics#8039]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Add functionality for YOLO-World: Real-Time Open-Vocabulary Object Detection

[Publication](https://arxiv.org/abs/2401.17270)
[Project website](https://www.yoloworld.cc/)
[GitHub](https://github.com/AILAB-CVC/YOLO-World)

## Examples from publication

![vis_lvis](https://github.com/ultralytics/ultralytics/assets/62214284/daa842cb-2aca-47a4-8cd2-b361313f3a59)
> (a) Visualization Results on Zero-shot Inference on LVIS

![user_vocab](https://github.com/ultralytics/ultralytics/assets/62214284/cb19a8c6-458a-46a7-8593-42e02e5cb69e)
> (b) Visualization Results on User’s Vocabulary

![vis_referring](https://github.com/ultralytics/ultralytics/assets/62214284/3712f3de-1e1a-4bee-9c18-5b594cd419e9)
> (c) Visualization Results on Referring Object Detection

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by FreedomLiX** [comment]
This is going to be a breakthrough

**Comment by glenn-jocher** [comment]
@FreedomLiX yes this is really cool!

**Comment by Burhan-Q** [comment]
Target for `ultralytics 8.2.0`
