### ISSUE TITLE
There is no Python demo specifically for OBB inference using ONNX in the example.

### ISSUE THREAD

**Issue by zqj5213** [ultralytics/ultralytics#8043]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I did not see a demo about using OpenCV to infer Oriented Bounding Boxes (OBB) from an ONNX model in the example. Could you provide a Python version demo for OBB inference?

**Comment by glenn-jocher** [comment]
@zqj5213 hello! Thanks for reaching out. Currently, we don't have a specific Python demo for OBB inference using ONNX models in the YOLOv8 repository. However, you can use the general ONNX inference code and modify the post-processing steps to extract OBB information from the model's outputs. For guidance on how to work with ONNX models and post-processing, please refer to our documentation at https://docs.ultralytics.com. If you have further questions or need assistance with the implementation, feel free to open a discussion in the repo. Happy coding! 😊🚀

**Comment by APeFerreira** [comment]
@zqj5213 did you manage to build a script for OBB inference with ONNXRUNTIME?
