### ISSUE TITLE
yolov8-pose onnx to int8 tensorrt?

### ISSUE THREAD

**Issue by ChenJian7578** [ultralytics/ultralytics#8049]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can you provide a script file that quantifies the onnx model to int8's tensorrt model

**Comment by glenn-jocher** [comment]
@ChenJian7578 hello! Thanks for reaching out. Currently, we don't provide a dedicated script for quantizing YOLOv8 models to INT8 with TensorRT. However, you can use the `Export` mode to convert your model to ONNX and then follow TensorRT's documentation for further quantization. Please refer to our documentation on the `Export` mode for guidance on exporting your model. For the INT8 quantization process, you'll need to use TensorRT's tools and set up a calibration process with your dataset. Keep an eye on our updates, as we're continuously working on improving the capabilities of YOLOv8. 😊
