### ISSUE TITLE
Not supported yet for YOLOv8 exported model

### ISSUE THREAD

**Issue by meryemsakin** [ultralytics/ultralytics#805]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

<img width="1108" alt="Ekran Resmi 2023-02-05 01 31 47" src="https://user-images.githubusercontent.com/101323802/216792271-c3d48905-4f53-4d5b-823d-006676cefa25.png">

I am trying to export my yolov8 model yolov8n.pt İnto yolov8n.engine but it shows me this message.
I have tried some suggested solutions but it is not working for me.

Predict:         yolo task=detect mode=predict model=yolov8n.engine -WARNING ⚠️ not yet supported for YOLOv8 exported models
Validate:        yolo task=detect mode=val model=yolov8n.engine -WARNING ⚠️ not yet supported for YOLOv8 exported models
How can I run yolov8.engine?

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
We'll work on supporting it soon

**Comment by meryemsakin** [comment]
Thanks for your answer.

**Comment by glenn-jocher** [comment]
@meryemsakin exported model inference may or may not work. It's not officially supported yet.

**Comment by theotherp** [comment]
FWIW, works well for me.

**Comment by pderrenger** [comment]
@theotherp that's great! Your positive experience is valuable feedback for the community.
