### ISSUE TITLE
yolov8-pose onnxruntime error

### ISSUE THREAD

**Issue by 1343464520** [ultralytics/ultralytics#8051]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

After training the yolov8n-pose model and obtaining the model, inference directly using PyTorch is normal, and it can output correct predictions for keypoints. However, when I convert the model to the ONNX format (checked the structure using Netron and inferred that it contains bounding box information based on the output dimensions), I encountered an error when performing inference using the ONNX Runtime framework. After debugging, I found that the output coordinates of predicted keypoints are negative. Is it necessary to include bounding boxes during annotation? Thank you!

**Comment by glenn-jocher** [comment]
@1343464520 hello! It seems like you've encountered an issue with the ONNX Runtime inference for the `yolov8n-pose` model. Negative keypoint coordinates are unexpected after conversion. When annotating for pose estimation, bounding boxes are not strictly necessary, as the model focuses on keypoint locations.

To address this, ensure that the ONNX export is done correctly and that the preprocessing steps match between the PyTorch and ONNX Runtime environments. Discrepancies in preprocessing can lead to different outputs. Also, verify that the ONNX Runtime version you're using is compatible with the exported model.

For further assistance, please refer to the [Export](https://docs.ultralytics.com/modes/export) documentation for guidelines on model conversion and consider opening an issue with detailed error logs and steps to reproduce the problem. Our team will be glad to help you resolve this. 😊
