### ISSUE TITLE
a bug related to convert_dota_to_yolo_obb function

### ISSUE THREAD

**Issue by enekuie** [ultralytics/ultralytics#8053]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

there's bug in `converter.py` for  `convert_dota_to_yolo_obb` function at line 408:
     
```python
if image_path.suffix != ".png":
    continue
```
these lines prevent converting all types of image file format from converting to yolo obb format and as I checked dota dataset after being downloaded from the link mentioned in yaml file, all images in this dataset are .jpg format

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@enekuie thank you for reporting this issue with the `convert_dota_to_yolo_obb` function. It seems like the code is indeed limiting the conversion to `.png` files only, which is not ideal for datasets with `.jpg` images like DOTA. We appreciate your diligence in identifying this bug. 🐞

The team will look into this and work on a fix. In the meantime, if you're comfortable with making temporary changes to the code, you could adjust the conditional check to include `.jpg` files as well. Your contribution to improving YOLOv8 is valued, and we welcome any further input or suggestions you might have. Keep an eye on the repository for updates on this issue. 🛠️

For more detailed guidance on YOLOv8 usage and troubleshooting, please refer to our documentation at https://docs.ultralytics.com.
