### ISSUE TITLE
Integrating yolov8 with other models

### ISSUE THREAD

**Issue by YouROS12** [ultralytics/ultralytics#8057]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello community, 

I'm new to the field of ML/DL/CV and started learning about few weeks ago.. 

One of the things that I wanna perform is using **yolov8 as feature extractor** for other ML techniques (e.g. SVM, Decision tree.. etc).  there is a guy who used yolov8 as feature extractor [here](https://github.com/ultralytics/ultralytics/issues/1724) but I didn't really get his way, cuz he integrated with his own model which is quite complicated for a someone like me. **Anyone here have done this before to help me through this ?** 
 
2nd thing, is this model here [ResNet](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/models/v8/yolov8-cls-resnet50.yaml) used ResNet as a **feature extractor for yolov8** ? if yes, how can I duplicate the same thing with other models like VGG19, MobileNetV2.. ?   

For the 2nd part I created this code duplicating the logic of [ResNet](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/models/v8/yolov8-cls-resnet50.yaml) | **if I continued like that, will I achieve what I want for the other models as well ?** 
```
class VGGBlock(nn.Module):
    ""VGG block with convolutional layers and max pooling.""

    def __init__(self, in_channels, out_channels, num_conv=2):
        """Initializes the VGG block with specified channels and layers."""
        super().__init__()
        layers = []
        for _ in range(num_conv):
            layers.append(nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1))
            layers.append(nn.ReLU(inplace=True))
            in_channels = out_channels
        layers.append(nn.MaxPool2d(kernel_size=2, stride=2))
        self.layer = nn.Sequential(*layers)

    def forward(self, x):
        """Forward pass through the VGG block."""
        return self.layer(x)

class VGG19(nn.Module):
    """VGG19 model architecture."""

    def __init__(self, num_classes=1000):
        """Initializes the VGG19 model with specified number of classes."""
        super().__init__()
        self.features = nn.Sequential(
            VGGBlock(3, 64),  # B1
            VGGBlock(64, 128),  # B2
            VGGBlock(128, 256, num_conv=3),  # B3
            VGGBlock(256, 512, num_conv=3),  # B4
            VGGBlock(512, 512, num_conv=3),  # B5
        )
        self.classifier = nn.Sequential(
            nn.Linear(512 * 7 * 7, 4096),
            nn.ReLU(inplace=True),
            nn.Dropout(),
            nn.Linear(4096, 4096),
            nn.ReLU(inplace=True),
            nn.Dropout(),
            nn.Linear(4096, num_classes),
        )

    def forward(self, x):
        """Forward pass through the VGG19 model."""
        x = self.features(x)
        x = x.view(x.size(0), -1)
        x = self.classifier(x)
        return x
```

**Comment by glenn-jocher** [comment]
@YouROS12 hello! Welcome to the ML/DL/CV community. 😊

Using YOLOv8 as a feature extractor for other ML techniques is indeed possible. You can extract features from intermediate layers of the YOLOv8 model and use them as input for classifiers like SVM or Decision Trees. This process typically involves accessing the internal layers of the network, which can be done by modifying the model's forward function or by creating a new model that only includes the desired layers for feature extraction.

Regarding your second question, the ResNet model you mentioned is configured as a backbone for YOLOv8, which means it's used to extract features that are then passed to the rest of the YOLOv8 network for object detection. To use other models like VGG19 or MobileNetV2 as feature extractors within YOLOv8, you would need to define a similar configuration file that specifies the architecture of the new backbone. The code you've started could be a step in the right direction for creating a VGG19 backbone.

For more detailed guidance on integrating different models and modifying YOLOv8, please refer to our documentation at https://docs.ultralytics.com. The documentation provides insights into the model architecture and how to customize it for your specific needs.

Keep experimenting and don't hesitate to reach out to the community for support. Good luck with your ML journey! 🚀

**Comment by Maelic** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> ### Question
> Hello community,
> 
> I'm new to the field of ML/DL/CV and started learning about few weeks ago..
> 
> One of the things that I wanna perform is using **yolov8 as feature extractor** for other ML techniques (e.g. SVM, Decision tree.. etc). there is a guy who used yolov8 as feature extractor [here](https://github.com/ultralytics/ultralytics/issues/1724) but I didn't really get his way, cuz he integrated with his own model which is quite complicated for a someone like me. **Anyone here have done this before to help me through this ?**
> 
> 2nd thing, is this model here [ResNet](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/models/v8/yolov8-cls-resnet50.yaml) used ResNet as a **feature extractor for yolov8** ? if yes, how can I duplicate the same thing with other models like VGG19, MobileNetV2.. ?
> 
> For the 2nd part I created this code duplicating the logic of [ResNet](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/models/v8/yolov8-cls-resnet50.yaml) | **if I continued like that, will I achieve what I want for the other models as well ?**
> 
> ```
> class VGGBlock(nn.Module):
>     ""VGG block with convolutional layers and max pooling.""
> 
>     def __init__(self, in_channels, out_channels, num_conv=2):
>         """Initializes the VGG block with specified channels and layers."""
>         super().__init__()
>         layers = []
>         for _ in range(num_conv):
>             layers.append(nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1))
>             layers.append(nn.ReLU(inplace=True))
>             in_channels = out_channels
>         layers.append(nn.MaxPool2d(kernel_size=2, stride=2))
>         self.layer = nn.Sequential(*layers)
> 
>     def forward(self, x):
>         """Forward pass through the VGG block."""
>         return self.layer(x)
> 
> class VGG19(nn.Module):
>     """VGG19 model architecture."""
> 
>     def __init__(self, num_classes=1000):
>         """Initializes the VGG19 model with specified number of classes."""
>         super().__init__()
>         self.features = nn.Sequential(
>             VGGBlock(3, 64),  # B1
>             VGGBlock(64, 128),  # B2
>             VGGBlock(128, 256, num_conv=3),  # B3
>             VGGBlock(256, 512, num_conv=3),  # B4
>             VGGBlock(512, 512, num_conv=3),  # B5
>         )
>         self.classifier = nn.Sequential(
>             nn.Linear(512 * 7 * 7, 4096),
>             nn.ReLU(inplace=True),
>             nn.Dropout(),
>             nn.Linear(4096, 4096),
>             nn.ReLU(inplace=True),
>             nn.Dropout(),
>             nn.Linear(4096, num_classes),
>         )
> 
>     def forward(self, x):
>         """Forward pass through the VGG19 model."""
>         x = self.features(x)
>         x = x.view(x.size(0), -1)
>         x = self.classifier(x)
>         return x
> ```
> 
> ### Additional
> _No response_

If you want to use Yolov8 as a feature extractor, you can use the `embed` variable to customize the forward function and retrieve features from specific layers, see https://github.com/ultralytics/ultralytics/blob/b53a3989ab216f04e2cd8eb5503703897eb05457/ultralytics/nn/tasks.py#L132-L135

This will flatten the features into one unique tensor, if you want to extract features from multiple levels (for instance to perform ROI Pooling on bounding boxes) you will have to modify the forward as follows:

```
def forward(self, x, profile=False, visualize=False, embed=None):
        y, feature_maps = [], []  # outputs
        for i, m in enumerate(self.model):
            if m.f != -1:  # if not from previous layer
                x = y[m.f] if isinstance(m.f, int) else [x if j == -1 else y[j] for j in m.f]  # from earlier layers
            x = m(x)  # run
            y.append(x if m.i in self.save else None)  # save output
            """
            We extract features from the following layers:
            15: 80x80
            18: 40x40
            21: 20x20
            For different object scales, as in the original YOLOV8 implementation.
            """
            if embed:
                if i in {15, 18, 21}:  # if current layer is one of the feature extraction layers
                    feature_maps.append(x)
        if embed:
            return x, feature_maps
        else:
            return x
```

Keep in mind that the Yolov8 architecture is designed to process features at 3 different scales: small (20x20), medium (40x40) and large (80x80) which is different than other feature extractors.
