### ISSUE TITLE
Odd size box for detection

### ISSUE THREAD

**Issue by karunakr** [ultralytics/ultralytics#8059]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

We are using yolo model for object detection. In one of the recent articles, i read that it is possible to get odd size boxes( rather than rectangle) as part of inference. I am using pretrained model, and how can i get that?

Thanks
Karunakar

**Comment by glenn-jocher** [comment]
@karunakr hi Karunakar,

Thanks for reaching out! YOLOv8, like its predecessors, primarily outputs axis-aligned bounding boxes, which are rectangular in shape. If you're referring to rotated or arbitrary-shaped bounding boxes, YOLOv8 does not natively support this feature.

However, for segmentation tasks, YOLOv8 can output pixel-wise masks that can conform to odd shapes of objects. This is different from detection and requires a model trained specifically for segmentation.

For more details on the capabilities of YOLOv8 and how to use it for various computer vision tasks, please refer to our documentation at https://docs.ultralytics.com.

**Comment by karunakr** [comment]
Thanks @glenn-jocher 
I checked the segmentation, it seems it fits my requirements. Is it possible to get bottom left and bottom right coordinates of the mask. 

Thanks
Karunakar

**Comment by glenn-jocher** [comment]
@karunakr hello Karunakar 👋,

If you're looking to obtain non-rectangular bounding boxes, such as rotated rectangles or polygons, you would need a model that supports such outputs. The standard YOLOv8 models output axis-aligned rectangular bounding boxes.

However, YOLOv8 does support oriented bounding boxes (OBB) with the `-obb` models, which can detect rotated rectangles. To use this feature, you would need to load a pretrained model that has been trained for OBB detection, such as `yolov8n-obb.pt`.

Here's how you can load and use an OBB model:

```python
from ultralytics import YOLO

# Load a pretrained OBB model
model = YOLO('yolov8n-obb.pt')

# Run inference
results = model('path/to/image.jpg')

# Access the oriented bounding boxes
obb_results = results.obb
```

The `obb_results` will contain the rotated bounding boxes, which you can then use for your application.

If you need more complex shapes like polygons, you might need to look into instance segmentation models, which YOLOv8 also supports with the `-seg` models.

Let us know if you need further assistance! 🚀
