### ISSUE TITLE
how to print the bounding box current position in this code ?

### ISSUE THREAD

**Issue by Rasantis** [ultralytics/ultralytics#8062]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

from ultralytics import YOLO
from ultralytics.solutions import object_counter3
import cv2
import os

model = YOLO("yolov8n.pt")
cap = cv2.VideoCapture("completo.mp4")
#cap = cv2.VideoCapture('rtsp://admin:169300vigillare@10.4.67.168:554/cam/realmonitor?channel=16&subtype=0')

assert cap.isOpened(), "Error reading video file"
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

# Defina os pontos do retângulo (A e B)
# Assumindo ponto A como canto superior esquerdo e ponto B como canto inferior direito
region_points = [(150, 150), (420, 150), (420, 213), (150, 213)]
classes_to_count = [0]  # Person class for count

# Init Object Counter
counter = object_counter3.ObjectCounter()
counter.set_args(view_img=True,
                 reg_pts=region_points,
                 classes_names=model.names,
                 draw_tracks=True)

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break
    tracks = model.track(im0, persist=True, show=False,
                         classes=classes_to_count)

    im0 = counter.start_counting(im0, tracks)

cap.release()
cv2.destroyAllWindows()

### Additional

The challenge I'm facing is that I need to count groups of people (+2 people entering together), my idea was if the bounding boxes are very close to each other within the region of interest, they will be counted as a group. ...
but how to access the coordinates of these boxes...

**Comment by glenn-jocher** [comment]
@Rasantis to access the bounding box coordinates in your code, you can iterate over the `tracks` variable, which contains the tracking information for each detected object. Each track in `tracks` is a dictionary that includes the bounding box coordinates under the keys `'xmin'`, `'ymin'`, `'xmax'`, and `'ymax'`.

Here's a concise way to print the bounding box coordinates for each track:

```python
for track in tracks:
    bbox = track['bbox']
    print(f"Bounding box coordinates: xmin={bbox[0]}, ymin={bbox[1]}, xmax={bbox[2]}, ymax={bbox[3]}")
```

Insert this snippet right after you obtain the `tracks` from the `model.track()` call. This will print the coordinates of each bounding box on every frame processed. You can then use these coordinates to determine the proximity of the bounding boxes to each other and count groups accordingly.

For more details on tracking and other functionalities, please refer to our documentation at https://docs.ultralytics.com.
