### ISSUE TITLE
IOU for segmentation 

### ISSUE THREAD

**Issue by osamaalschame** [ultralytics/ultralytics#8064]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to get the iou metrics for segmentation.

regards,

**Comment by glenn-jocher** [comment]
@osamaalschame hello! 👋

For segmentation tasks using YOLOv8, the Intersection over Union (IoU) metric is automatically computed during the validation phase. To obtain IoU metrics, simply run the validation mode after training your model with segmentation data. The results will include IoU for each class and the mean IoU (mIoU) for the dataset.

For more details on how to use the validation mode, please refer to our documentation on the Val mode. If you need further assistance, feel free to ask!

**Comment by osamaalschame** [comment]
after running the validation, I got f-score, precision, recall , or you mean the values on confusion matrix are iou metrics for each class.

**Comment by glenn-jocher** [comment]
@osamaalschame the values you're seeing (f-score, precision, recall) are related but different metrics. IoU specifically measures the overlap between predicted and ground truth segments. If IoU is not displayed, it may not be included in the default metrics for your segmentation task. Please check the segmentation task documentation for more details on output metrics and ensure your dataset is properly formatted for segmentation. If IoU is a required metric for your use case, you might need to implement a custom metric calculation or adjust the validation settings.

**Comment by joshua-atolagbe** [comment]
@glenn-jocher The IoU metrics was not displayed on validation. How can I utilize the ‘mask_iou’ function in the metrics.py for this.

**Comment by glenn-jocher** [comment]
@joshua-atolagbe to obtain Intersection over Union (IoU) metrics for segmentation using Ultralytics YOLOv8, you can follow these steps:

1. **Train a Segmentation Model**: First, ensure that you have trained a segmentation model using YOLOv8. If you haven't done so, you can train a model using the `train` mode with a segmentation dataset.

2. **Validate the Model**: After training, use the `val` mode to validate your model on a segmentation dataset. During validation, the IoU metric will be calculated for each class and overall.

3. **Access IoU Metrics**: The IoU metrics are part of the validation results. You can access them programmatically in Python or view them in the logs if you're using the CLI.

Here's an example of how to access IoU metrics programmatically in Python:

```python
from ultralytics import YOLO

# Load your trained segmentation model
model = YOLO('path/to/your/segmentation-model.pt')

# Validate the model on your segmentation dataset
metrics = model.val(data='path/to/your/segmentation-dataset.yaml')

# Access IoU metrics
iou_metrics = metrics.iou
print("IoU metrics:", iou_metrics)
```

The `metrics` object will contain the IoU metrics for each class and the mean IoU across all classes. The exact structure of the `metrics` object and how the IoU is presented may vary, so you should refer to the documentation or inspect the `metrics` object to understand how to extract the specific IoU values you need.

If you're using the CLI, the IoU metrics will be printed to the console during the validation process, and they may also be saved to a results file depending on your configuration.

Please note that the exact commands and code may vary depending on the version of YOLOv8 you are using and any updates to the repository. Always refer to the official documentation or the repository's GitHub issues and discussions for the most up-to-date information.

**Comment by joshua-atolagbe** [comment]
@glenn-jocher . I have tried that. It doesn't work. Here's the error 

![image](https://github.com/ultralytics/ultralytics/assets/99275929/6a1fcde6-ef14-43fa-afda-f0d9464b2955)

When I tried to do `iou_metrics = metrics.seg`. I had this :

![image](https://github.com/ultralytics/ultralytics/assets/99275929/2b566962-645c-44c0-b84c-a31945321791)

From the list of metrics, the `iou` was not included. Any way around this?

**Comment by glenn-jocher** [comment]
@joshua-atolagbe to calculate Intersection over Union (IoU) metrics for segmentation tasks using Ultralytics YOLOv8, you can follow these steps:

1. **Train a Segmentation Model**: First, ensure that you have trained a segmentation model using YOLOv8. If you haven't done so, you can train a model using the `train` mode with a segmentation dataset.

2. **Validate the Model**: After training, use the `val` mode to validate your model on a segmentation dataset. During validation, the IoU metric is automatically calculated for each class and the mean IoU (mIoU) is reported.

3. **Custom IoU Calculation**: If you need to calculate IoU for segmentation outside of the standard validation process, you can do so by comparing the predicted segmentation masks with the ground truth masks. IoU is calculated as the area of overlap between the predicted mask and the ground truth mask divided by the area of union.

Here's a Python example of how to calculate IoU for segmentation:

```python
import numpy as np

def calculate_iou(pred_mask, gt_mask):
    """
    Calculate Intersection over Union (IoU) for a single pair of predicted and ground truth masks.

    Args:
        pred_mask (np.ndarray): Predicted segmentation mask.
        gt_mask (np.ndarray): Ground truth segmentation mask.

    Returns:
        float: IoU score.
    """
    intersection = np.logical_and(pred_mask, gt_mask).sum()
    union = np.logical_or(pred_mask, gt_mask).sum()
    iou = intersection / union if union != 0 else 0
    return iou

# Example usage:
# Assuming `results` is a list of Results objects from YOLOv8 prediction
for result in results:
    for i, (pred_mask, gt_mask) in enumerate(zip(result.masks.data, ground_truth_masks)):
        iou = calculate_iou(pred_mask, gt_mask)
        print(f"IoU for object {i}: {iou}")
```

In this example, `ground_truth_masks` should be a list or array of ground truth masks corresponding to the predicted masks in `result.masks.data`. The `calculate_iou` function computes the IoU for a single pair of masks.

Please note that the `val` mode in YOLOv8 automatically calculates and reports IoU metrics during model evaluation. If you need to calculate IoU for custom purposes or on individual images, you can use the approach outlined above.

If you have any further questions or need additional assistance, feel free to ask!

**Comment by joshua-atolagbe** [comment]
@glenn-jocher , Is the `ground_truth_masks` the `labels.txt` (annotations in yolo format) or `mask.png` (the image of the mask)? And again, the `val` mode in YOLOv8 does not calculates and reports IoU metrics during model evaluation. I have tried your earlier approach. Note that I am using the latest version of yolov8. You could probably try it on your end and confirm

**Comment by glenn-jocher** [comment]
@joshua-atolagbe to calculate Intersection over Union (IoU) metrics for segmentation tasks using Ultralytics YOLO models, you can follow these general steps:

1. **Prepare Your Dataset**: Ensure that your dataset contains ground truth segmentation masks for the objects of interest. These masks should be in a format that the model can interpret, such as binary masks where the object pixels are set to 1 and the background to 0.

2. **Train Your Model**: If you haven't already, train your segmentation model (such as YOLOv8 with segmentation capabilities) on your dataset. Make sure to use a model configuration that supports segmentation.

3. **Run Validation**: Use the `val` mode to validate your model on a validation dataset. During validation, the model will predict segmentation masks for the given input images.

4. **Calculate IoU**: After prediction, compare the predicted masks with the ground truth masks to calculate the IoU for each object class. IoU is calculated as the area of overlap between the predicted mask and the ground truth mask divided by the area of union between them.

Here's an example of how you might calculate IoU in Python using the results from your model:

```python
from ultralytics import YOLO

# Load your trained segmentation model
model = YOLO('path/to/your/segmentation/model.pt')

# Validate the model on your validation dataset
results = model.val(data='your_validation_dataset.yaml')

# Assuming results contain both predicted masks and ground truth
for result in results:
    # Get predicted masks and ground truth masks
    pred_masks = result.masks.pred  # Predicted masks from the model
    gt_masks = result.masks.gt  # Ground truth masks from the dataset

    # Calculate IoU for each class
    ious = []
    for i, (pred_mask, gt_mask) in enumerate(zip(pred_masks, gt_masks)):
        intersection = (pred_mask & gt_mask).sum()  # Logical AND
        union = (pred_mask | gt_mask).sum()  # Logical OR
        iou = intersection / union if union > 0 else 0
        ious.append(iou)
        print(f"Class {i}: IoU = {iou:.4f}")

    # Calculate mean IoU across all classes
    mean_iou = sum(ious) / len(ious)
    print(f"Mean IoU: {mean_iou:.4f}")
```

Please note that the above code is a simplified example. The actual implementation may vary depending on the format of your dataset and the specific details of your model's output. You may need to adjust the code to match the data structures used by your model and dataset.

If you're using a custom script or a different framework for validation, you'll need to adapt the IoU calculation accordingly. The key is to ensure that the predicted masks and ground truth masks are aligned and in a compatible format for bitwise operations.

**Comment by Creatancient** [comment]
> @glenn-jocher , Is the `ground_truth_masks` the `labels.txt` (annotations in yolo format) or `mask.png` (the image of the mask)? And again, the `val` mode in YOLOv8 does not calculates and reports IoU metrics during model evaluation. I have tried your earlier approach. Note that I am using the latest version of yolov8. You could probably try it on your end and confirm

Hello, do you now know how to calculate the Intersection over Union (IoU) metric for a segmentation task using Ultralytics YOLOv8? I'm also having trouble calculating this.

**Comment by glenn-jocher** [comment]
Hello @Creatancient! 😊 For segmentation tasks in YOLOv8, the `ground_truth_masks` refer to the actual mask images (e.g., `mask.png`) that delineate the object areas, not the `labels.txt` annotations used for bounding boxes in detection tasks.

Regarding the IoU metrics during model evaluation, you're correct that the `val` mode primarily focuses on detection metrics and might not directly output IoU for segmentation tasks. However, you can manually calculate IoU by comparing the predicted masks against the ground truth masks. Here's a quick example on how you might approach this:

```python
import numpy as np

def calculate_iou(pred_mask, gt_mask):
    intersection = np.logical_and(pred_mask, gt_mask).sum()
    union = np.logical_or(pred_mask, gt_mask).sum()
    iou = intersection / union if union > 0 else 0
    return iou
```

In this function, `pred_mask` and `gt_mask` should be binary numpy arrays where the object pixels are 1 and the background is 0. You'd need to loop through your dataset to apply this function to each image/mask pair.

I hope this helps! Let me know if you have any more questions. 🚀

**Comment by VicB18** [comment]
Hello @glenn-jocher, thank you for support.

I tried to run the code that you proposed,
```
from ultralytics import YOLO

# Load your trained segmentation model
model = YOLO('path/to/your/segmentation/model.pt')

# Validate the model on your validation dataset
results = model.val(data='your_validation_dataset.yaml')

# Assuming results contain both predicted masks and ground truth
for result in results:
    # Get predicted masks and ground truth masks
    pred_masks = result.masks.pred  # Predicted masks from the model
    gt_masks = result.masks.gt  # Ground truth masks from the dataset
```

and got this error:

`TypeError: 'DetMetrics' object is not iterable`

Is it possible to add the calculation of the IoU to all the rest of metrics in `results.box`? After all, you wrote in the Docs that "It plays a fundamental role in evaluating the accuracy of object localization". But currently it must be calculated separately.

Thank you

**Comment by glenn-jocher** [comment]
Hello @VicB18! 😄

Thank you for reaching out and sharing your issue! It looks like there might have been a misunderstanding regarding the output structure of `model.val()` for segmentation tasks in YOLOv8.

For segmentation tasks, YOLOv8 doesn't directly return an iterable of results per image but rather aggregates performance metrics across the validation dataset. Therefore, to calculate and examine IoU metrics specifically for segmentation, it's necessary to extend our approach a little.

Although the current implementation doesn't directly include IoU for segmentation in `results`, here's a quick snippet demonstrating how you could dive into calculating IoU with a slight adjustment:

```python
# This would be more of a manual process where you need to
# access your predictions and ground truth for each image,
# then calculate IoU. Here's a conceptual snippet for guidance:

iou_scores = []
for image_path in dataset_images:
    pred_mask = model.predict(image_path)
    gt_mask = load_gt_mask(image_path)  # Define this function based on your dataset
    
    iou = calculate_iou(pred_mask, gt_mask)  # Function as in the previous example
    iou_scores.append(iou)

mean_iou = np.mean(iou_scores)
print(f"Mean IoU for the validation dataset: {mean_iou}")
```

Please note that direct access to individual `pred` and `gt` masks will vary based on your dataset handling, so you might need to adapt the code to fit your exact scenario.

I hope this helps guide you in the right direction! If further clarification is needed or you encounter any more issues, feel free to ask. We're here to help! 🚀

**Comment by prakharjadaun** [comment]
@VicB18 
@Creatancient 
@joshua-atolagbe 

This code runs only for: **Single segmented object in an image (you can modify for your own)**
**Approach:** I have approached calculation of IOU using polygon vectors because model.predict() returns a polygon vector. I have computed the ground truth polygon from the labels.txt files.

Img format: png
labels: txt format
Example of one label.txt :

![image](https://github.com/ultralytics/ultralytics/assets/78482329/2abed4cd-d3bf-4473-9893-d09cb805b1fb)

Follow these steps to approach calculating IOU: 

```
# required imports
from ultralytics import YOLO
from shapely.geometry import Polygon
import cv2
import numpy as np
from random import randint
import os

def calculate_iou(ground_truth, predicted):
    """
  	Calculates Intersection-over-Union (IoU) between two polygons.

  	Args:
      	ground_truth: A numpy array representing the ground truth polygon vertices.
      	predicted: A numpy array representing the predicted polygon vertices.

  	Returns:
      	The IoU value between the two polygons.
    """
    ground_truth_polygon = Polygon(ground_truth)
    predicted_polygon = Polygon(predicted)
    intersection = ground_truth_polygon.intersection(predicted_polygon).area
    union_area = ground_truth_polygon.union(predicted_polygon).area
    if union_area == 0:
        return 0  # Avoid division by zero
    return intersection / union_area

def solve(path_to_weight_pt_file,path_to_image,path_to_label_txt):
    # loading the trained segmentation model
    model = YOLO(path_to_weight_pt_file)
    # read the image
    img = cv2.imread(path_to_image)
    h,w = img.shape[:2]

    f = open(path_to_label_txt,"r")
    labels = f.read().splitlines()[0]
    class_id, *poly = labels.split(' ')

    poly = np.asarray(poly,dtype=np.float16).reshape(-1,2) # Read poly, reshape
    poly *= [w,h] # Unscale
    # ground truth polygon vector prepared
    poly.astype(int)
    

    # now compute the predicted vector
    res = model.predict(path_to_image)
    for r in res:
        pred_vector = r.masks.xy[0]
    
    pred_vector.astype('int')
    print(calculate_iou(pred_vector, poly))

solve(path_to_weight_file,path_to_image,path_to_label_txt)
```
