### ISSUE TITLE
Torchscript with tracking

### ISSUE THREAD

**Issue by ahmadmughees** [ultralytics/ultralytics#8067]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, 

I have trained a custom model with default values on two classes. After that, I exported it to the `torchscript` format. When I load that and run it, I get the model outputs as [bs, 6, 5040] and 6 represents the bbox coordinates. but now I want to use the tracker with this model as well. 

I have not found anything in the docs about how I can use the tracker with `torchscript` variant and if there is any, can anyone refer me to that. 

Also, if I want to use my custom tracker and I only need features from v8 model which I can pass into my tracker, how I can achieve that? 

Thanks alot.,

**Comment by glenn-jocher** [comment]
@ahmadmughees hello!

For integrating tracking with a `torchscript` exported model, you can utilize the tracking functionality provided by YOLOv8 by following the Track mode documentation. However, the tracking is not directly supported in the `torchscript` export format, as it is primarily designed for inference.

If you're looking to implement your custom tracker and require features from the YOLOv8 model, you would typically extract the necessary features from the model's intermediate layers. This process is not straightforward with the `torchscript` format, as it's optimized for end-to-end inference. You might need to work with the model in its native PyTorch format to access these intermediate features.

For more detailed guidance on tracking and feature extraction, please refer to the Track mode documentation and consider exploring the model's architecture to identify suitable feature extraction points.

**Comment by ahmadmughees** [comment]
Hi @glenn-jocher 
Thanks alot for your response. I appreciate that.

Is there any way I can have a confidence score in the output? currently, it is outputing [xywh+classes, boxes] but no confidence score. 


Thanks.

**Comment by glenn-jocher** [comment]
@ahmadmughees hello! 👋

For using tracking with a `torchscript` exported model, you would typically need to handle the tracking logic separately, as the `torchscript` export is primarily for inference. Currently, the tracking functionality is integrated within the Python environment and not directly available in the `torchscript` format.

If you want to use your custom tracker with the features from the YOLOv8 model, you can extract the features from the intermediate layers of the model before exporting to `torchscript`. You would need to modify the model to return not only the final detection outputs but also the desired feature maps. Then, you can pass these features to your custom tracker.

For more specific guidance on implementing this, you might want to look into the model architecture and identify which layers' outputs are relevant for your tracking application. Once identified, you can create a new model definition that returns both the detection results and the required features.

If you need further assistance, feel free to ask more questions in the [discussions](https://github.com/ultralytics/ultralytics/discussions) section, where our community can provide more interactive help. 

Good luck with your custom tracking implementation! 🚀

**Comment by ahmadmughees** [comment]
@glenn-jocher seems like a bot is responding on your behalf and did not responding to exact problem,

**Comment by glenn-jocher** [comment]
@ahmadmughees hello! 👋

For using the tracker with a `torchscript` model, you can load the model and perform tracking in Python as you would with a `.pt` model. The tracking functionality is independent of the export format and should work with `torchscript` as well. Here's a basic example:

```python
from ultralytics import YOLO

# Load your torchscript model
model = YOLO('path/to/your/model.torchscript')

# Perform tracking on a video source
results = model.track(source='path/to/your/video.mp4')
```

Regarding custom trackers and feature extraction, YOLOv8 models do not directly output features for tracking. However, you can modify the model's forward pass to return intermediate features that you can then pass to your custom tracker. This would require some understanding of the model's architecture and possibly modifying the source code.

If you need further assistance with custom trackers or feature extraction, please feel free to open a discussion in our [GitHub Discussions](https://github.com/ultralytics/ultralytics/discussions) where the community and maintainers can provide more in-depth support. 😊

Best regards!
