### ISSUE TITLE
How to display confidence score when using Yolov8 object counting

### ISSUE THREAD

**Issue by Hanming555** [ultralytics/ultralytics#8068]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,
I am using the code from 
https://docs.ultralytics.com/guides/object-counting/
and
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/solutions/object_counter.py
to try to count vehicles. However, I noticed that there is no confidence score displayed in the video. I am wondering how to display the confidence score and show it on the tracking box. For example, currently only the ID and class name are shown on the box. I would like to display the confidence score for each box. Can you help me with this?
![image](https://github.com/ultralytics/ultralytics/assets/122944900/e9a95d41-3a79-48bf-881c-d706a2a3b637)

**Comment by glenn-jocher** [comment]
@Hanming555 hello! To display the confidence score alongside the ID and class name on the tracking boxes, you'll need to modify the part of the code responsible for drawing the boxes and text overlay on the video frames. Specifically, you'll want to access the confidence score from the detection results and include it in the string that's being put on the image.

Look for the section in the `object_counter.py` where bounding boxes and text are drawn. You'll find a line of code that constructs the text string to be displayed (usually containing the ID and class name). Here, append the confidence score, which is typically available in the detection results. Format it to your preference (e.g., as a percentage) and add it to the text overlay.

Remember to keep the display concise to maintain readability, especially if there are multiple detections. Good luck with your vehicle counting project! 😊🚗🔢
