### ISSUE TITLE
How to change the classes when predicting or tracking?

### ISSUE THREAD

**Issue by PiBigStar5712** [ultralytics/ultralytics#8078]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

**My dataset is a custom dataset and the classes I set in the yaml file of the dataset are as follows:**
```
# Classes
names:
  0: Feasible Area
  1: Infeasible Area
  2: AMR
```
**But when I tried to run the sample code given in the official documentation about segment and track， I found that the `classes` in the predicted results were `0, 1, 2`**
![image](https://github.com/ultralytics/ultralytics/assets/102813129/35ed1b7c-7d38-40ef-a45e-3a11bc0c1da8)

**How should I modify the `classes` so that they can be aligned with the ones I trained with?**

**Also, if I want to both segment and track and output the track trail, do I need to resort to `boxes = results[0].boxes.xywh.cpu()`?**
**Plot the trajectory with this code below?**
```
        for box, track_id in zip(boxes, track_ids):
            x, y, w, h = box
            track = track_history[track_id]
            track.append((float(x), float(y)))  # x, y center point
            if len(track) > 30:  # retain 90 tracks for 90 frames
                track.pop(0)

            # Draw the tracking lines
            points = np.hstack(track).astype(np.int32).reshape((-1, 1, 2))
            cv2.polylines(annotated_frame, [points], isClosed=False, color=(230, 230, 230), thickness=10)
```
**Thank you very much for maintaining this project for a long time and I look forward to getting your answers!**

**Comment by glenn-jocher** [comment]
@PiBigStar5712 to align the predicted class IDs with your custom names, ensure the `names` list in your dataset YAML file matches the order of classes used during training. The model uses this list to map class IDs to names during prediction and tracking.

For tracking and plotting trails, your approach with `boxes = results[0].boxes.xywh.cpu()` is correct. Use the `track_id` from `results[0].boxes.id` to associate detections over time and plot the trajectories as you've shown.

If you have further questions or need assistance, feel free to reach out! 😊👍

**Comment by PiBigStar5712** [comment]
> @PiBigStar5712 to align the predicted class IDs with your custom names, ensure the `names` list in your dataset YAML file matches the order of classes used during training. The model uses this list to map class IDs to names during prediction and tracking.
> 
> For tracking and plotting trails, your approach with `boxes = results[0].boxes.xywh.cpu()` is correct. Use the `track_id` from `results[0].boxes.id` to associate detections over time and plot the trajectories as you've shown.
> 
> If you have further questions or need assistance, feel free to reach out! 😊👍

**Yes, I'm sure. I've set the correct `names` in the `yaml` file.**
![image](https://github.com/ultralytics/ultralytics/assets/102813129/d722fe97-7234-4756-8352-fc745837299e)

**I use the following parameters for training.**

```
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO('F:/yolov8_8.0.228_official/ultralytics/cfg/models/v8/yolov8n-seg.yaml')
    model.train(data='F:/yolov8_8.0.228_official/ultralytics/cfg/datasets/mydata_seg.yaml',
                task='segment',
                epochs=100,
                batch=8,
                imgsz=640,
                save=True,
                save_period=10,
                cache=False,
                device=0,
                workers=1,
                project='F:/yolov8_8.0.228_official/runs',
                pretrained=False,
                name='train',
                amp=True,
                close_mosaic=100,
                optimizer='SGD'
                )
```

**When I use track, the parameters are set as follows：**

```
    model = YOLO('F:/yolov8_8.0.228_official/ultralytics/cfg/models/v8/yolov8n-seg.yaml')
    model.load('F:/yolov8_8.0.228_official/runs/yolov8n-seg/weights/best.pt')
```

**I don't know what went wrong.**

**Comment by Burhan-Q** [comment]
What about if you use `model.names` instead? Most times, this is how I reference these with something like:

```py
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.predict("path/to/image.jpeg")

for box in results[0].boxes:
   ...
   name = model.names.get(box.cls.cpu().int())
   ... 
```

Sorry trying to do this from memory, so you might need to make some minor changes to get it working.

**Comment by PiBigStar5712** [comment]
> What about if you use `model.names` instead? Most times, this is how I reference these with something like:
> 
> ```python
> from ultralytics import YOLO
> 
> model = YOLO("yolov8n.pt")
> 
> results = model.predict("path/to/image.jpeg")
> 
> for box in results[0].boxes:
>    ...
>    name = model.names.get(box.cls.cpu().int())
>    ... 
> ```
> 
> Sorry trying to do this from memory, so you might need to make some minor changes to get it working.

**Thank you for your reply. I tried this code you provided, but it doesn't work.**

![image](https://github.com/ultralytics/ultralytics/assets/102813129/559a569d-75fd-411f-9bb2-d8a531cb6cf7)

**This same piece of code works fine when using `model.predict`**

![image](https://github.com/ultralytics/ultralytics/assets/102813129/34a9991a-c82e-449b-9f25-4f16f8038c10)

**The version of the code I'm using is `8.0.228`, and I'm not sure if this is an unknown `bug` or not. Maybe there is some special way to load `names` when using `model.track`?**

**Comment by glenn-jocher** [comment]
@PiBigStar5712 to align the predicted class IDs with the names you trained with, ensure that the `names` list in your dataset YAML file matches the class IDs. The model uses this list to map class IDs to human-readable class names. If the `names` list is correct, the predictions should automatically display the correct class names.

For segmenting and tracking while outputting the track trail, you can indeed use `boxes = results[0].boxes.xywh.cpu()` to get the bounding boxes and then plot the trajectories as you described. The code snippet you provided is a good starting point for drawing tracking lines.

If you have further questions or need assistance, feel free to reach out. Happy tracking! 🚀

**Comment by PiBigStar5712** [comment]
> @PiBigStar5712 to align the predicted class IDs with the names you trained with, ensure that the `names` list in your dataset YAML file matches the class IDs. The model uses this list to map class IDs to human-readable class names. If the `names` list is correct, the predictions should automatically display the correct class names.
> 
> For segmenting and tracking while outputting the track trail, you can indeed use `boxes = results[0].boxes.xywh.cpu()` to get the bounding boxes and then plot the trajectories as you described. The code snippet you provided is a good starting point for drawing tracking lines.
> 
> If you have further questions or need assistance, feel free to reach out. Happy tracking! 🚀
@glenn-jocher @Burhan-Q 
**After I debugged it several times, I found that the problem may be in `line 326` of `ultralytics/nn/autobackend.py`.**
![image](https://github.com/ultralytics/ultralytics/assets/102813129/ec2b27f0-bb56-48f3-a0d1-ad5c37592e77)

**It seems to be due to the `data` content not being received at runtime, causing the `default_class_names` function to output the class name numerically.**
![image](https://github.com/ultralytics/ultralytics/assets/102813129/d3c16579-8b40-4485-90e5-24f67b4d249e)

**If I wish to assign a value to `data` in the `track` task, can I do it directly in `model.track` using `data=xxxx` like in the `train` task?**
![image](https://github.com/ultralytics/ultralytics/assets/102813129/7cf1b922-cbaa-44ef-aca9-1228aef42974)
![image](https://github.com/ultralytics/ultralytics/assets/102813129/cb84bd32-9766-4d8d-8202-a2c69c15b8ae)

**If so, is it a direct assignment to the `yaml` file of the dataset I trained on? For example, if the dataset I'm using now is `mydata_seg.yaml`, should I make `data=mydata_seg.yaml`?**
![image](https://github.com/ultralytics/ultralytics/assets/102813129/3f3ea37b-79d6-4eaf-ad26-c50efe204eda)
![image](https://github.com/ultralytics/ultralytics/assets/102813129/7c827808-42f3-4f20-8cc6-cc75793c2e1d)

**Comment by Burhan-Q** [comment]
@PiBigStar5712 try updating your Ultralytics install. Looks like you're running `8.0.228` and a more recent version may have addressed this issue. Recent versions after January 2024 will start with 8.1
