### ISSUE TITLE
Create COCO pretrained model for obb task

### ISSUE THREAD

**Issue by Burhan-Q** [ultralytics/ultralytics#8096]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Using same `train_args` from DOTAv2 pretrained model for OBB. Target for `ultralytics 8.2.0`

### Additional

Coordinate with @Laughing-q as needed

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SwEngine** [comment]
This would be super beneficial! Do you have any plan to release coco pretrained model for OBB? Thank you so much!

**Comment by glenn-jocher** [comment]
We're glad you're interested! 🚀 We are indeed planning to release a COCO pretrained model for OBB tasks in an upcoming update. Keep an eye on our releases page for the latest updates. Thanks for your support!

**Comment by Burhan-Q** [comment]
@SwEngine like Glenn said, we still plan on releasing these, but other tasks have taken priority. You'll see a notification from this issue when we have more updates 🚀
