### ISSUE TITLE
If I train with single_cls=True for single class train, where does the network structure of YOLO changed? 

### ISSUE THREAD

**Issue by SunnyGrocery** [ultralytics/ultralytics#8097]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

What is the difference between the new network structure and [yolov8.yaml](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/models/v8/yolov8.yaml)? What optimization has been done? Where can I find the changes for `single_cls=True` in the source code? Thank you very much!

**Comment by glenn-jocher** [comment]
@SunnyGrocery when you pass `single_cls=True` the model head layers are updated to output a single class neuron rather than an array of neurons that would otherwise match your class count, i.e. 80 outputs for COCO.
