### ISSUE TITLE
Confidence threshold used for precision and recall

### ISSUE THREAD

**Issue by DVa2022** [ultralytics/ultralytics#8098]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

What's the confidence threshold used to calculate the precision and recall values that are found in the results.csv file that is found in the folder of the training session? These values are the same ones that are used to plot the precision per epoch curve that is found in the results.png file.
And generally is there a confidence threshold that is commonly used to calculate the precision and recall values that are found in some published papers in the field of computer vision?

David.

**Comment by glenn-jocher** [comment]
@DVa2022 hello David 👋,

The default confidence threshold used for calculating precision and recall in the results.csv file is 0.25 during training. However, during validation (`val` mode), a lower threshold of 0.001 is used to ensure all potential detections are considered. This threshold can be adjusted using the `conf` argument if needed.

As for published papers, there isn't a universally adopted confidence threshold; it often varies based on the dataset and the specific task. Researchers typically choose a threshold that balances precision and recall effectively for their use case.

Hope this helps! If you have further questions or need assistance with anything else, feel free to ask.
