### ISSUE TITLE
Separate tensor for each class at the output.

### ISSUE THREAD

**Issue by DroneAIRecognition** [ultralytics/ultralytics#8100]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

We need the trained model to be saved after training with separate tensors for each class at the output, instead of the current model where there is one output for all classes. Could you please advise on how to implement this?

**Comment by glenn-jocher** [comment]
@DroneAIRecognition hello! 👋 To modify the YOLOv8 model to have separate output tensors for each class, you would need to customize the model architecture and the post-processing code. This involves altering the final detection layer to produce separate outputs per class and adjusting the non-maximum suppression (NMS) to handle these outputs accordingly.

As this is a significant change, it's recommended to have a strong understanding of the model's architecture and the inference pipeline. If you're comfortable with PyTorch and neural network design, you can start by examining the model definition files (`.yaml`) and the corresponding forward methods in the code.

If you need further guidance, feel free to open a discussion in the [Ultralytics GitHub Discussions](https://github.com/ultralytics/ultralytics/discussions) for community input or consider reaching out for professional support. Good luck with your implementation! 🚀
