### ISSUE TITLE
Issue with Kaggle , While installing ultralytics. 

### ISSUE THREAD

**Issue by shreya123jadhav** [ultralytics/ultralytics#8108]
I Have an issue with Kaggle , While installing ultralytics.It is giving error and warning
What is this issue , i cant figure out.  Please help me .
![Error](https://github.com/ultralytics/ultralytics/assets/108461336/fc965a60-6793-4215-83df-313a96f28caf)

**Comment by glenn-jocher** [comment]
@shreya123jadhav hi there! 👋 It looks like there might be an issue with the installation process on Kaggle. To better assist you, could you please share the exact error message or warning you're receiving? Also, ensure you're using the correct installation command:

```bash
!pip install ultralytics
```

If you're still facing issues, please provide the full error log so we can help you troubleshoot the problem more effectively. 🛠️

**Comment by glenn-jocher** [comment]
@shreya123jadhav Kaggle is running an out-of-date, very old version of Python 3.7, which has passed it's end of life date and is not supported by Ultralytics. Please raise a bug report directly on Kaggle for the to resolve their problem here.

**Comment by shreya123jadhav** [comment]
Okay, Thank you @glenn-jocher

**Comment by glenn-jocher** [comment]
@shreya123jadhav hello! To better assist you, could you please provide the exact error message or warning you're encountering when trying to install Ultralytics on Kaggle? The image link you've provided seems to be broken, and I'm unable to view the error details.

In the meantime, ensure that you're using the correct installation command for Ultralytics YOLOv8, which is typically:

```bash
!pip install ultralytics
```

If you're still facing issues, please copy and paste the error message here, and I'll do my best to help you resolve it. 😊🛠️

**Comment by namnguyen2103** [comment]
Hi there @glenn-jocher, I just want to say that I have the same problem when using Kaggle:
![image](https://github.com/ultralytics/ultralytics/assets/89676371/ff7cbd78-ebaf-4be9-9dc8-ff8b0119a77e)
So what should I do, below is the error message:
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x79118aae1ff0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/ultralytics/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x79118aae22f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/ultralytics/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x79118aae2590>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/ultralytics/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x79118aae2740>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/ultralytics/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x79118aae28f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/ultralytics/
ERROR: Could not find a version that satisfies the requirement ultralytics (from versions: none)
ERROR: No matching distribution found for ultralytics

**Comment by namnguyen2103** [comment]
Never mind it's actually a silly mistake, just make sure that "Internet" is enabled in the Settings pane to the right of the Editor
![image](https://github.com/ultralytics/ultralytics/assets/89676371/287afb99-eee5-448b-8c5d-9a3f46b14c67)

**Comment by glenn-jocher** [comment]
@namnguyen2103 ah, that happens to the best of us! 😄 Glad you figured it out. Turning on "Internet" in Kaggle's settings is indeed a key step for accessing external packages. If you have any more questions or bump into another hiccup, feel free to reach out. Happy coding! 🚀

**Comment by bryukhanovA1488** [comment]
hi, I have this kind of problem. I also tried to install Ultralytics directly through the console and everything worked out for me, but the error remained the same, tell me how to solve this problem
![image](https://github.com/ultralytics/ultralytics/assets/90636646/edf26d52-8943-42f9-bf1d-fba035caf066)

**Comment by glenn-jocher** [comment]
Hello! From the error message in the screenshot, it looks like there's an issue with your installation or environment setup that's persisting. Although it's hard to give precise guidance without seeing the specific error message, a common troubleshooting step is to ensure you are using a virtual environment and that all dependencies are correctly installed. Here’s how you can set up a new virtual environment and reinstall Ultralytics YOLOv8:

```bash
# Create a new virtual environment
python -m venv ultralytics-env

# Activate the environment
# On Windows
ultralytics-env\Scripts\activate
# On MacOS/Linux
source ultralytics-env/bin/activate

# Install Ultralytics YOLOv8
pip install ultralytics
```

If the issue is still unresolved, could you share the exact error message or any other details provided in the console output? This will help diagnose the problem more effectively. 😊🛠️

**Comment by bryukhanovA1488** [comment]
I tried to take your advice (that's what came up in the console).
![image](https://github.com/ultralytics/ultralytics/assets/90636646/e29a3640-d233-404f-8a34-c6839cea462d)
As you can see, the installation was successful
![image](https://github.com/ultralytics/ultralytics/assets/90636646/8695385e-38d7-4774-9974-6d75b3aa42f1)
 However, the problem remained the same- no error notification popped up
![image](https://github.com/ultralytics/ultralytics/assets/90636646/489fe58d-d172-4578-af1b-ce159a8bc719)
I have a few suggestions as to why this problem might occur. First of all, my region is not served for verification in Kaggle, so I cannot enable the Internet function as described above. Well, the second is an error in the installation path, I think I'll try another environment, for example Jupiter

**Comment by bryukhanovA1488** [comment]
In general, I am very interested in your technology, and I am using it to write an application for my graduate university work.😊😊😊

**Comment by glenn-jocher** [comment]
@bryukhanovA1488 that's great to hear! 😊 We're thrilled that you're incorporating YOLOv8 into your graduate work. If you encounter any specific questions or need assistance along the way, don't hesitate to reach out. Good luck with your application, and we're here to help you succeed!

**Comment by Techgeeekrobo** [comment]
Hey I am still getting this type of error message when installing ultralytics on kaggle . the error is " WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ec4f2134250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/ultralytics/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ec4f2134550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/ultralytics/."  so can you help with that !

**Comment by glenn-jocher** [comment]
Hello! 👋

Thank you for reaching out. It looks like you're encountering a network connectivity issue while trying to install the `ultralytics` package on Kaggle. Here are a few steps to help resolve this:

1. **Enable Internet Access**: Ensure that the "Internet" option is enabled in the Kaggle notebook settings. This is crucial for accessing external packages. You can find this option in the Settings pane to the right of the Editor.

2. **Check Network Settings**: Sometimes, network issues can be temporary. You might want to try running the installation command again after a short while.

3. **Update Packages**: Make sure you are using the latest versions of `pip` and `setuptools`. You can update them using the following commands:
    ```bash
    !pip install --upgrade pip setuptools
    ```

4. **Alternative Installation**: If the issue persists, you can try installing the package directly from the GitHub repository:
    ```bash
    !pip install git+https://github.com/ultralytics/ultralytics.git
    ```

If you continue to experience issues, please provide a minimum reproducible example of your code and confirm that you are using the latest versions of `torch` and `ultralytics`. This will help us investigate further. You can find more details on creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions or need further assistance. Happy coding! 😊

**Comment by Techgeeekrobo** [comment]
Solved the issue thankyou :)

**Comment by glenn-jocher** [comment]
Hello @Techgeeekrobo,

I'm glad to hear that your issue has been resolved! 🎉 If you have any more questions or run into any other issues, feel free to reach out. We're here to help!

Happy coding and best of luck with your graduate work! 😊

**Comment by BentaherNoureddine** [comment]
i'm having a problem with kaggle , I install ultralytics check the version in a new cell it say that it s installed but when I try this code
it say  no module named ultralytics

from ultralytics import YOLO

# Load model
model = YOLO("yolov8s.pt")

# Start training
results = model.train(
    data="fire-detection-5/data.yaml",
    epochs=100,
    imgsz=640,
    patience=20,
    batch=16,
    name="fire_detection_train"
)

**Comment by BentaherNoureddine** [comment]
Thanks! I solved the problem i was installing ultralytics the switch to gpu acceleration so when i switch to gpu aceleration it creates a nesession i think .
So i solved this by using the gpu acceleration before installing anything .

**Comment by glenn-jocher** [comment]
That's great to hear @BentaherNoureddine! You've identified an important workflow consideration with Kaggle - selecting GPU acceleration before installing packages ensures everything stays in the same runtime environment. This is actually a common issue since Kaggle creates separate environments when switching between CPU and GPU runtimes. Thanks for sharing your solution, as it will help others who might encounter the same situation in their Kaggle notebooks.

**Comment by ousaghro** [comment]
the solution is cloc on turn on internet on the menu of kaggle.com website

**Comment by glenn-jocher** [comment]
Thanks for confirming; if anyone still hits install/import issues after enabling Internet, please run the diagnostics below and open a new issue with the text output for visibility—there’s also a step-by-step reference in our [Kaggle integration guide](https://docs.ultralytics.com/integrations/kaggle/).

```bash
!yolo checks
```

**Comment by Banhhcuon** [comment]
<img width="1000" height="484" alt="Image" src="https://github.com/user-attachments/assets/a409de34-6427-452b-ac54-6bca873e2824" />

i got issues when install ultralytics

**Comment by glenn-jocher** [comment]
Hi @panhcuonn—this thread is closed as Stale; please [open a new issue](https://github.com/ultralytics/ultralytics/issues/new/choose) and paste text logs (no screenshots) plus the diagnostics below; installation tips are also in our [Troubleshooting Common YOLO Issues](https://docs.ultralytics.com/guides/yolo-common-issues/).

```bash
!pip -V
!python --version
!pip install -U pip setuptools wheel
!pip install ultralytics -vv
!yolo checks
```

If `yolo` isn’t available, include the full `pip install ultralytics -vv` error text and:
```bash
!pip debug -v
```
