### ISSUE TITLE
Yolo Segmentation Inference Post Processing Not Optimized

### ISSUE THREAD

**Issue by brr53** [ultralytics/ultralytics#811]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I've noticed that Yolo Segmentation Inference processing is not optimized.

Time for inference (sending tensor to model) 34ms
Time for post processing (process the output tensor from the inference to mask, etc.) 27ms

The speed of the image inference is almost the same as the processing for it. 
**Too much time/effort/resources are spent on processing the inference.** 

It is very unusual for post processing to need to take this long. I think there may be some logic which is slow or the model perhaps can output the tensor in a more simplified way. Is this really a common problem with segmentation, or is this something I can contribute to improving in the Ultralytics repository?

If it is something that can/needs to be improved, please let me know which portion I should look at (simplify the inference tensor output or optimize the post processing). Thank you.

### Environment

- OS: MacOS Monterey M1 CPU
- Python 3.9

### Minimal Reproducible Example

Default seg/predict.py run.
Tried .py and .ONNX converted model yolov8n-seg.pt -> yolov8n-seg.onnx

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@brr53 when you say it is very unusual for post-processing to need to take this long, which methods are you comparing it with? I'd be interested in knowing that because according to our analysis our methods are the fastest.
Also, my results are different from yours:
```
# segmentation
Speed: 0.5ms pre-process, 69.5ms inference, 1.9ms postprocess per image at shape (1, 3, 640, 640)
```
```
# detection
Speed: 0.4ms pre-process, 50.4ms inference, 0.5ms postprocess per image at shape (1, 3, 640, 640)
```
This shows that postprocessing isn't a significant factor in latency. Maybe you haven't run model.fuse(), in which case the 1st prediction is slower. But it should not be the case with postprocessing. Maybe be reproducing this on a stream

**Comment by glenn-jocher** [comment]
@brr53 @AyushExel postprocessing time is the same as detection, just NMS, unless you are saving/showing results, in which case the masks naturally take time to render and save/show.

<img width="951" alt="Screenshot 2023-02-06 at 00 58 29" src="https://user-images.githubusercontent.com/26833433/216845441-db2f0ef8-8a15-4e26-81f2-34e0c7a3ffb1.png">

**Comment by w013nad** [comment]
How many targets is the model detecting? The segmentation models are very memory hungry when you have lots of targets.

**Comment by AyushExel** [comment]
@w013nad yes segmentation task is memory hungry in general. We've reduced the memory footprint by a lot with our optimizations. On an avg you might see masks upto 4x less memory usage than an unoptimized implementation.
