### ISSUE TITLE
How to continue training of model

### ISSUE THREAD

**Issue by Pensarfeo** [ultralytics/ultralytics#812]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, maybe this is a dumb question, but I just can't figure out how to continue the training of a model after it has finished its original training. 

Thanks

**Comment by pderrenger** [comment]
@Pensarfeo hey there! Not a dumb question at all! To continue training a YOLOv8 model after its original training, you can simply run the **Train** mode again with the `--weights` flag pointing to the original trained model's weights file and the `--resume` flag set to `True`. This will start the training from the point where it left off. If you need further assistance, feel free to ask! 😊
