### ISSUE TITLE
YOLOv8-Seg models don't train Boxes when built from yaml

### ISSUE THREAD

**Issue by jboyle1013** [ultralytics/ultralytics#8129]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I have been using YOLOv8-Seg to train models for a while now, and for the last few weeks, whenever I try to train  a new one,  it doesn't seem to train the boxes. They always come out with perfect or near perfect metrics, see images below. And when i try to run predictions with those models, I get this error message: "AttributeError: Segmentation Object has no attribute "decode_bboxes""

Metrics From Training (I was using the COCO8-Seg Dataset for Testing on these)
![Screenshot 2024-02-10 144205](https://github.com/ultralytics/ultralytics/assets/58829335/a7e0cb8e-48b6-4a49-bbe7-0c059be6a63c)

These are the Mask Metrics From the last time I trained my custom dataset 
![Screenshot 2024-02-09 174924](https://github.com/ultralytics/ultralytics/assets/58829335/dd789673-fa5a-436f-a5b6-183ddd1ed6d5)

These are the BoxMetrics From the last time I trained my custom dataset 
![Screenshot 2024-02-09 174650](https://github.com/ultralytics/ultralytics/assets/58829335/ee25e210-9237-4f5e-aab6-2bb0bda9d761)

### Environment

Ultralytics YOLOv8.1.11 🚀 Python-3.9.13 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3060, 12022MiB)
Setup complete ✅ (12 CPUs, 31.3 GB RAM, 624.3/915.3 GB disk)

### Minimal Reproducible Example

Training:
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n-seg.yaml') # build new model

# Train the model
results = model.train(data='coco8-seg.yaml', batch=-1, verbose=True, imgsz=640, visualize=True, epochs=10, plots=True, dnn=True)

r1 = model.val()

Testing:
from ultralytics import YOLO
import cv2
import traceback

# Initialize the YOLO model
model = YOLO("path/to/model")

def get_vals(img):
    try:
        results = model(img, stream=True)
        for r in results:
            masks = r.masks
            boxes = r.boxes
            # Additional code to process masks and boxes can be added here if necessary
    except Exception as e:
        tb = traceback.format_exc()
        print("An error occurred:", e)
        print("Traceback:", tb)

# Start video capture from the default camera
cap = cv2.VideoCapture(0)

while True:
    success, img = cap.read()
    if success:
        get_vals(img)
    else:
        print("Failed to capture image")

    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jboyle1013 it seems like there might be an issue with the segmentation model not training bounding boxes correctly. We appreciate the detailed report and the code snippets you've provided. Could you please open a new issue on the YOLOv8 GitHub repository with the details you've shared here? This will allow our team to track and address the problem more effectively. In the meantime, ensure that your dataset annotations include both segmentation masks and bounding boxes, as missing bounding box data could lead to such training issues. 🛠️

For the `AttributeError: Segmentation Object has no attribute "decode_bboxes"` error, it looks like the model is expecting bounding box information that isn't present. This could be related to the initial training issue. When you open the new issue, please include this error message as well.

Thank you for bringing this to our attention, and we'll aim to resolve it promptly! 👍
