### ISSUE TITLE
How To Perform MLflow Integration with YOLOv8 for Gitlab

### ISSUE THREAD

**Issue by phsilvarepo** [ultralytics/ultralytics#8134]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello there, 
I am training Yolov8 in Colab. I was wondering if there is a known method to store the training metrics of YOLOv8 into Gitlab model registry. Since Gitlab operate as the MLflow backend, how can I connect MLflow from YOLO to the Gitlab. So far from my attempts, I can connect the Mlflow to Gitlab by doing so:

```
import os
from mlflow.store.artifact.runs_artifact_repo import RunsArtifactRepository
from mlflow import MlflowClient
from mlflow.models import infer_signature
from mlflow import MlflowClient

os.environ["MLFLOW_TRACKING_TOKEN"]='glpat-...'
os.environ["MLFLOW_TRACKING_URI"]="https://gitlab.com/api/v4/projects/54730890/ml/mlflow"

client = MlflowClient()

model_name='Model'
model=client.create_registered_model(model_name)

mv = client.create_model_version(model_name,source="")
```
And it create a a model and its version in Gitlab. I was wondering if anyone could provide some insight into how to connect Yolov8. For now I have:

```
!export MLFLOW_TRACKING_TOKEN="glpat-..."
!export MLFLOW_TRACKING_URI="https://gitlab.com/api/v4/projects/54730890/ml/mlflow"

!yolo task=detect mode=train model=yolov8s.pt data=/content/drive/MyDrive/yolov8/screws.yaml epochs=2 imgsz=640 plots=True project=my_project name=my_name
```
And this the output of that run: 
```
New https://pypi.org/project/ultralytics/8.1.11 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.196 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
engine/trainer: task=detect, mode=train, model=yolov8s.pt, data=/content/drive/MyDrive/yolov8/screws.yaml, epochs=2, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=my_project, name=my_name, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=my_project/my_name2
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments                     
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]                 
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]             
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]           
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]              
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]           
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]                 
 22        [15, 18, 21]  1   2116435  ultralytics.nn.modules.head.Detect           [1, [128, 256, 512]]          
Model summary: 225 layers, 11135987 parameters, 11135971 gradients, 28.6 GFLOPs

Transferred 349/355 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir my_project/my_name2', view at http://localhost:6006/
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning /content/Screws_Dataset/labels/train.cache... 313 images, 0 backgrounds, 0 corrupt: 100% 313/313 [00:00<?, ?it/s]
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
val: Scanning /content/Screws_Dataset/labels/val.cache... 79 images, 0 backgrounds, 0 corrupt: 100% 79/79 [00:00<?, ?it/s]
Plotting labels to my_project/my_name2/labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
2024/02/11 19:57:41 INFO mlflow.tracking.fluent: Experiment with name 'my_project' does not exist. Creating a new experiment.
2024/02/11 19:57:42 INFO mlflow.tracking.fluent: Autologging successfully enabled for transformers.
2024/02/11 19:57:43 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2024/02/11 19:57:44 INFO mlflow.tracking.fluent: Autologging successfully enabled for statsmodels.
2024/02/11 19:57:44 WARNING mlflow.utils.autologging_utils: You are using an unsupported version of tensorflow. If you encounter errors during autologging, try upgrading / downgrading tensorflow to a supported version, or try upgrading MLflow.
2024/02/11 19:57:44 INFO mlflow.tracking.fluent: Autologging successfully enabled for tensorflow.
MLFlow: Using run_id(01d28795-afe5-420a-a0ff-e4b0d822cb43) at https://gitlab.com/api/v4/projects/54730890/ml/mlflow
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to my_project/my_name2
Starting training for 2 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        1/2      4.15G       2.72      7.159       1.07        146        640: 100% 20/20 [02:28<00:00,  7.43s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% 3/3 [00:03<00:00,  1.30s/it]
                   all         79        641      0.644      0.632      0.614      0.199

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        2/2      4.38G      1.695      1.275     0.8394        108        640: 100% 20/20 [02:00<00:00,  6.01s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% 3/3 [00:01<00:00,  2.06it/s]
                   all         79        641      0.841      0.747      0.818       0.41

2 epochs completed in 0.081 hours.
Optimizer stripped from my_project/my_name2/weights/last.pt, 22.5MB
Optimizer stripped from my_project/my_name2/weights/best.pt, 22.5MB

Validating my_project/my_name2/weights/best.pt...
Ultralytics YOLOv8.0.196 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
Model summary (fused): 168 layers, 11125971 parameters, 0 gradients, 28.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% 3/3 [00:34<00:00, 11.37s/it]
                   all         79        641      0.849      0.743      0.816      0.409
Speed: 0.2ms preprocess, 4.8ms inference, 0.0ms loss, 2.7ms postprocess per image
Results saved to my_project/my_name2
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mlflow/utils/request_utils.py", line 63, in augmented_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://gitlab.com/api/v4/projects/54730890/packages/generic/ml_experiment_4/4/my_name2/val_batch2_pred.jpg

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 445, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 341, in train
    self.trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 191, in train
    self._do_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 415, in _do_train
    self.run_callbacks('on_train_end')
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 156, in run_callbacks
    callback(self)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/utils/callbacks/mlflow.py", line 59, in on_train_end
    run.log_artifact(trainer.save_dir)
  File "/usr/local/lib/python3.10/dist-packages/mlflow/tracking/fluent.py", line 1010, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/usr/local/lib/python3.10/dist-packages/mlflow/tracking/client.py", line 1149, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/usr/local/lib/python3.10/dist-packages/mlflow/tracking/_tracking_service/client.py", line 527, in log_artifact
    artifact_repo.log_artifacts(local_path, path_name)
  File "/usr/local/lib/python3.10/dist-packages/mlflow/store/artifact/http_artifact_repo.py", line 80, in log_artifacts
    self.log_artifact(os.path.join(root, f), artifact_dir)
  File "/usr/local/lib/python3.10/dist-packages/mlflow/store/artifact/http_artifact_repo.py", line 66, in log_artifact
    augmented_raise_for_status(resp)
  File "/usr/local/lib/python3.10/dist-packages/mlflow/utils/request_utils.py", line 66, in augmented_raise_for_status
    raise HTTPError(
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://gitlab.com/api/v4/projects/54730890/packages/generic/ml_experiment_4/4/my_name2/val_batch2_pred.jpg. Response text: {"error":"package_version is invalid"}
```

**Comment by glenn-jocher** [comment]
@phsilvarepo hey there! 👋

It looks like you've made good progress with MLflow and GitLab integration. For connecting YOLOv8 to GitLab via MLflow, you might consider using MLflow's Python API within your training script to log metrics, parameters, and models directly to your MLflow server backed by GitLab.

Here's a simplified example of how you could integrate MLflow logging into your YOLOv8 training workflow:

```python
import mlflow
from ultralytics import YOLO

# Set MLflow tracking URI and token
mlflow.set_tracking_uri("https://gitlab.com/api/v4/projects/54730890/ml/mlflow")
mlflow.set_experiment("YOLOv8 Experiment")

# Start an MLflow run
with mlflow.start_run():
    # Load and train your YOLOv8 model
    model = YOLO('yolov8n.pt')
    results = model.train(data='coco128.yaml', epochs=3)

    # Log parameters, metrics, and model
    mlflow.log_params({"epochs": 3, "model": "yolov8n.pt", "data": "coco128.yaml"})
    mlflow.log_metrics({"mAP_0.5": results.map50, "mAP_0.5:0.95": results.map})
    mlflow.pytorch.log_model(model, "model")

    # End the run
    mlflow.end_run()
```

Make sure to replace the placeholders with your actual tracking URI, project ID, and personal access token. Also, adjust the parameters and metrics to match those you want to track.

For the error you're encountering, it seems like there might be an issue with the artifact logging. Double-check the artifact path and ensure it's valid. If the problem persists, consider reaching out to GitLab support or checking the MLflow documentation for more details on artifact logging with Gitlab.

Hope this helps! Keep us posted on your progress. 😊

**Comment by phsilvarepo** [comment]
Hey there @glenn-jocher, 
I tried to implement that way but the error persists, even with `settings.update({'mlflow': False})`, the autologging of mlfow still occurs and it crashes when it attempts to send the images. Any other suggestion to ensure only metrics and parameters I want are sent? As shown in your example? 
```
mlflow.log_params({"epochs": 3, "model": "yolov8n.pt", "data": "coco128.yaml"})
mlflow.log_metrics({"mAP_0.5": results.map50, "mAP_0.5:0.95": results.map})
mlflow.pytorch.log_model(model, "model")
```

**Comment by glenn-jocher** [comment]
@phsilvarepo it appears that you've made significant progress in integrating MLflow with YOLOv8 and GitLab. The error you're encountering at the end of your training run seems to be related to logging artifacts to GitLab's package registry via MLflow.

The error message `{"error":"package_version is invalid"}` suggests that there might be an issue with the way the package version is being specified or handled when MLflow attempts to log the artifact.

Here are a few steps you can take to troubleshoot and potentially resolve this issue:

1. **Check Package Versioning:**
   Ensure that the package version you're trying to log is valid and adheres to the versioning scheme expected by GitLab's package registry. It might be helpful to manually create a package version in GitLab to understand the expected format.

2. **MLflow Configuration:**
   Double-check your MLflow configuration to ensure that it's correctly set up to interact with GitLab. This includes the `MLFLOW_TRACKING_URI` and `MLFLOW_TRACKING_TOKEN`.

3. **Artifact Path:**
   Verify that the artifact path used in the `log_artifact` call is correct. The path should be relative to the location of the `MLproject` file if you're using one.

4. **MLflow Version:**
   Ensure that you're using a version of MLflow that is compatible with GitLab's package registry. If necessary, try upgrading or downgrading MLflow to a version that is known to work well with GitLab.

5. **GitLab Permissions:**
   Confirm that the token you're using has the necessary permissions to create and manage packages in the GitLab project.

6. **Manual Artifact Logging:**
   As a test, try manually logging an artifact to GitLab using MLflow's Python API outside of the YOLOv8 training script to isolate the issue.

7. **MLflow Callback:**
   If you're using a custom MLflow callback with YOLOv8, review the callback code to ensure that it's correctly handling the artifact logging process.

8. **GitLab Documentation:**
   Review the [GitLab package registry documentation](https://docs.gitlab.com/ee/user/packages/package_registry/) for any specific requirements or limitations that might affect artifact logging.

9. **MLflow Issues:**
   Search the [MLflow GitHub issues](https://github.com/mlflow/mlflow/issues) for similar problems reported by other users. There might be a known issue or workaround available.

10. **Contact Support:**
    If you're unable to resolve the issue, consider reaching out to GitLab support or the MLflow community for assistance.

By systematically going through these steps, you should be able to identify the root cause of the error and integrate MLflow with YOLOv8 and GitLab successfully.

**Comment by MoellerAI** [comment]
I have the same error when trying to log a PyTorch model in mlflow on gitlab. Seems like there is a bug with the mlflow.pytorch.log_model and gitlab?

**Comment by eduardobonet-gitlab** [comment]
I am the developer for the MLflow compatibility on GitLab side (thanks @MoellerAI for the ping). This is likely a problem on GitLab side, because `mlflow.pytorch.log_model` is trying to log folders, and GitLab model experiments do not support folder structure. As an alternative, you can use GitLab Model registry, create a model and use the `[model]model name` as the experiment name: logging artifacts to GitLab model registry do support folder structure (https://gitlab.com/gitlab-org/gitlab/-/issues/417437), see docs on https://docs.gitlab.com/ee/user/project/ml/experiment_tracking/mlflow_client.html#logging-candidates-to-a-model.

**Comment by Alberto706** [comment]
> I am the developer for the MLflow compatibility on GitLab side (thanks @MoellerAI for the ping). This is likely a problem on GitLab side, because `mlflow.pytorch.log_model` is trying to log folders, and GitLab model experiments do not support folder structure. As an alternative, you can use GitLab Model registry, create a model and use the `[model]model name` as the experiment name: logging artifacts to GitLab model registry do support folder structure (https://gitlab.com/gitlab-org/gitlab/-/issues/417437), see docs on https://docs.gitlab.com/ee/user/project/ml/experiment_tracking/mlflow_client.html#logging-candidates-to-a-model.

Hello @eduardobonet-gitlab, after testing your suggestion I encounter the same error. I believe the experiments linked to a model are internally also treated the same as other experiments with regards to how the storage works. Could this be possible? I am very interested in using the model registry feature of Gitlab so thanks for your great work.

**Comment by MoAbbasid** [comment]
hi @glenn-jocher how can I log my runs to mlflow from the CLI ? is it possiple or does it have to be done in python?

**Comment by glenn-jocher** [comment]
Hi @MoAbbasid,

Great question! You can indeed log your runs to MLflow directly from the CLI. Here's how you can do it:

1. **Set the MLflow Tracking URI and Token:**
   ```bash
   export MLFLOW_TRACKING_URI="https://gitlab.com/api/v4/projects/54730890/ml/mlflow"
   export MLFLOW_TRACKING_TOKEN="your_token_here"
   ```

2. **Enable MLflow Logging in YOLOv8 Settings:**
   ```bash
   yolo settings mlflow=True
   ```

3. **Run Your Training Command:**
   ```bash
   yolo detect train model=yolov8s.pt data=coco128.yaml epochs=50 project=my_project name=my_run
   ```

This setup will log your training metrics, parameters, and artifacts to MLflow. If you encounter any issues, feel free to reach out. Happy training! 🚀

**Comment by MoAbbasid** [comment]
@glenn-jocher , setting yolo settings mlflow=True, and running mlflow ui --backend-store-uri runs/mlflow, does work and shows the training runs, params and metrics, but the mlflow.db sqlite file generated by ultralytics is empty when I do "SELECT * FROM experiments;" the table is empty, it appears YOLOv8 correctly logs to a folder directory but not to an sqlite db,
I need to log YOLOv8 runs, params, metrics and in sqlite format and using CLI, any ideas?

**Comment by glenn-jocher** [comment]
Hi @MoAbbasid,

It sounds like you're facing an issue where the MLflow SQLite database isn't capturing the logs as expected, despite the UI displaying the training runs correctly. This could be due to how the file paths or URIs are configured, or possibly a discrepancy in how the data is being written to the SQLite database versus the directory structure.

Here are a couple of steps you might consider:
1. Ensure that the `MLFLOW_TRACKING_URI` is set correctly to point to your SQLite database file, for example, `mlflow set-tracking-uri sqlite:///mlflow.db`.
2. Verify that the directory for SQLite database has the correct permissions to allow writing.

If these steps don't resolve the issue, it might be helpful to check the MLflow and YOLOv8 integration settings or consider logging this as an issue on the Ultralytics GitHub page for more dedicated troubleshooting.

Hope this helps! Let us know how it goes.

**Comment by MoAbbasid** [comment]
@glenn-jocher I checked and the mlflow tracking uri is set correctly and points to the sqlite database, but the database created by ultralytics after the training run is empty and has no experiments or runs, is this an YOLOv8/Ultralytics package issue?

**Comment by glenn-jocher** [comment]
Hi @MoAbbasid,

Thank you for checking the MLflow tracking URI and confirming its setup. It seems unusual for the SQLite database to remain empty if the URI is correctly pointed and the MLflow UI is showing the runs. This might indicate an issue with how the data is being committed to the database in the Ultralytics integration.

Could you please ensure that all environment variables are set correctly and that there are no errors in the logs that might suggest why the database isn't populating? If everything seems in order, this might indeed be a bug or a limitation in the current integration.

I recommend opening an issue on the Ultralytics GitHub repository with detailed information about your setup and any relevant logs. This will allow the development team to replicate the issue and provide a fix or guidance.

Thanks for your patience and for bringing this to our attention!

**Comment by MoAbbasid** [comment]
@glenn-jocher ,  you were right, the mlflow tracking uri kept resetting for some reason in my case and that caused the databases to be unpopulated, after setting it and checking it before every run the runs were logged correctly to the database?

**Comment by glenn-jocher** [comment]
Hi @MoAbbasid,

That's great news! I'm glad to hear that ensuring the MLflow tracking URI was set correctly before each run resolved the issue with the unpopulated databases. It sounds like there might have been a configuration reset happening in your environment. Keeping an eye on the URI settings before running your experiments is a good practice to ensure consistent logging.

If you encounter any more issues or have further questions, feel free to reach out. Happy training! 🚀
