### ISSUE TITLE
Excluding Employees from People Counting System Using Badge Detection

### ISSUE THREAD

**Issue by Rasantis** [ultralytics/ultralytics#8138]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I implement logic in my people counting system to exclude employees identified by badges? I use your counting solution by crossing lines, where the model was trained to recognize two classes: "person" and "badge". My goal is that whenever a badge is detected next to a person, this "person" detection is ignored, preventing it from being counted. What would be the best approach to perform this exclusion in the counting script I am using?

### Additional

MY CODE:
from ultralytics import YOLO
from ultralytics.solutions import object_counter
import cv2
import os

model = YOLO("yolov8n.pt")
#cap = cv2.VideoCapture("completo.mp4")
cap = cv2.VideoCapture('rtsp:')

assert cap.isOpened(), "Error reading video file"
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

# Defina os pontos do retângulo (A e B)
# Assumindo ponto A como canto superior esquerdo e ponto B como canto inferior direito
region_points = [(150, 150), (420, 150), (420, 213), (150, 213)]
classes_to_count = [0]  # Person class for count

# Init Object Counter
counter = object_counter.ObjectCounter()
counter.set_args(view_img=True,
                 reg_pts=region_points,
                 classes_names=model.names,
                 draw_tracks=True)

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break
    tracks = model.track(im0, persist=True, show=False,
                         classes=classes_to_count)

    im0 = counter.start_counting(im0, tracks)

cap.release()
cv2.destroyAllWindows()

**Comment by glenn-jocher** [comment]
@Rasantis hi there! 👋 To exclude employees with badges from your people counting system, you can modify the tracking logic to check for overlapping detections of "person" and "badge" classes. If a badge is detected within or near the bounding box of a person, you can skip counting that person. Here's a simplified code snippet to illustrate the concept:

```python
while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break

    # Track all classes
    tracks = model.track(im0, persist=True, show=False)

    # Filter out persons with badges
    persons_with_badges = []
    for track in tracks:
        if track.cls == model.names.index('badge'):
            for person_track in tracks:
                if person_track.cls == model.names.index('person'):
                    if iou(track.boxes.xyxy, person_track.boxes.xyxy) > threshold:
                        persons_with_badges.append(person_track.id)

    # Update classes_to_count to exclude persons with badges
    classes_to_count = [track for track in tracks if track.cls == model.names.index('person') and track.id not in persons_with_badges]

    im0 = counter.start_counting(im0, classes_to_count)

cap.release()
cv2.destroyAllWindows()
```

In this snippet, `iou` is a function that calculates the Intersection Over Union of two bounding boxes, and `threshold` is the IOU threshold to consider a badge as belonging to a person. You'll need to implement the `iou` function based on your specific requirements.

Hope this helps! Let us know if you have any more questions. 😊

**Comment by Rasantis** [comment]
Thanks for the feedback, Glen, but I haven't been able to implement this yet, could you give me an example in a basic inference script like this, same idea, if there are these 2 classes "together", it cancels the detection of one of them. I have separated an example that can work with a standard yolov8n.pt model.  The idea would be to detect if a dog is present alongside a person, and then cancel the detection of the dog class for that person. If I truly understand this logic, I can adapt it to my counting script.
from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO('yolov8n.pt')

# Run inference on an image
results = model(source='video.mp4', show=True)  # results list


https://github.com/ultralytics/ultralytics/assets/76708662/86be71b6-a5fc-4f00-8f0f-cb9499c496c1

**Comment by glenn-jocher** [comment]
@Rasantis to exclude employees from the people counting system when a badge is detected next to a person, you can modify the counting logic to check for the proximity of a "badge" detection to a "person" detection. If a badge is detected close enough to a person, you can assume that the person is an employee and exclude them from the count.

Here's a modified version of your code that includes this logic:

```python
from ultralytics import YOLO
from ultralytics.solutions import object_counter
import cv2
import numpy as np

model = YOLO("yolov8n.pt")
cap = cv2.VideoCapture('rtsp:')

assert cap.is_opened(), "Error reading video file"

# Define the points of the rectangle (A and B)
# Assuming point A as the top left corner and point B as the bottom right corner
region_points = [(150, 150), (420, 150), (420, 213), (150, 213)]
classes_to_count = [0]  # Person class for count

# Init Object Counter
counter = object_counter.ObjectCounter()
counter.set_args(view_img=True,
                 reg_pts=region_points,
                 classes_names=model.names,
                 draw_tracks=True)

def is_close(detection1, detection2, threshold=50):
    # Calculate the Euclidean distance between the centers of two detections
    center1 = np.array([detection1[0] + detection1[2] / 2, detection1[1] + detection1[3] / 2])
    center2 = np.array([detection2[0] + detection2[2] / 2, detection2[1] + detection2[3] / 2])
    distance = np.linalg.norm(center1 - center2)
    return distance < threshold

while cap.is_opened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break

    # Track all classes (persons and badges)
    tracks = model.track(im0, persist=True, show=False)

    # Filter out person detections that are close to badge detections
    filtered_tracks = []
    for track in tracks:
        if track.boxes.cls[0] == 0:  # Check if it's a person
            exclude = False
            for other_track in tracks:
                if other_track.boxes.cls[0] != 0:  # Check if it's not a person (i.e., a badge)
                    if is_close(track.boxes.xyxy[0], other_track.boxes.xyxy[0]):
                        exclude = True
                        break
            if not exclude:
                filtered_tracks.append(track)

    # Update the image with filtered tracks
    im0 = counter.start_counting(im0, filtered_tracks)

cap.release()
cv2.destroyAllWindows()
```

In this code, we define a function `is_close` that calculates the Euclidean distance between the centers of two detections. If the distance is less than a specified threshold, it returns `True`, indicating that the detections are close to each other.

During the tracking loop, we track all classes and then filter out any person detections that are close to badge detections. The `filtered_tracks` list only includes person detections that are not close to any badge detections. We then pass this filtered list to the `start_counting` method to update the count.

Please adjust the `threshold` value in the `is_close` function according to your specific scenario. This value determines how close a badge must be to a person for the person to be excluded from the count.
