### ISSUE TITLE
Object Counting in best possible implementation.

### ISSUE THREAD

**Issue by ayushraj2349** [ultralytics/ultralytics#8139]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

@glenn-jocher Sir, 
I want to count instances of my object class in the current frame (whole frame) and when someone enters or leaves, the count gets changed.

Most solutions are for a line where monitoring is done on objects crossing that line.
My query is not that.

I want that If say, there are 4 persons in the video, then it should display 4 objects and someone leaves in the current, then it should display me 3 persons.

How to implement code for this problem?
Please let me know.

![266832416-a1057b86-fcd7-412c-b7b0-583101cf91b6](https://github.com/ultralytics/ultralytics/assets/97942801/2399bbd6-8b71-478b-8f5e-d88a24131c8f)

**Comment by prince0310** [comment]
@ayushraj2349 one of the possible solution would be calculating number of boxes in the frame, when you just calculate the length of boxes in result you would be able to find the number of objects in the frame.
for example :
`boxes = detection_results[0].boxes.xyxy.cpu().tolist()`
`print(len(boxes))`

**Comment by ayushraj2349** [comment]
@prince0310 but I want to be dynamic, if a person leaves in the video then the person count should decrease, which doesn't happen by my code.
Whatever it calculates once, it just displays that all the video duration.
That's the problem..
Please suggest if you have a possible solution, and it would be much better if you could provide the code also.

Thanks again.

**Comment by prince0310** [comment]
![2](https://github.com/ultralytics/ultralytics/assets/85225054/b416a917-f0c1-4333-a8d3-4abe26a68ea5)
@ayushraj2349 try this 
![1](https://github.com/ultralytics/ultralytics/assets/85225054/ee59a889-c04a-499a-9d99-4b57f85f5d5d)


```import cv2
from ultralytics import YOLO
cap = cv2.VideoCapture("20240110_163949.mp4")
detection_model = YOLO("yolov8m.pt")
while True:
    ret, frame = cap.read()

    if not ret:
        break

   ``` detection_results = detection_model.predict(frame,classes = 0, conf = 0.25)
    boxes = detection_results[0].boxes.xyxy.cpu().tolist()
    classes = detection_results[0].boxes.cls.cpu().tolist()
    scores = detection_results[0].boxes.conf.cpu().tolist()
    cv2.putText(frame, "Person "f'{len(boxes)}', (10, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 255), 2, cv2.LINE_AA)
    frame = cv2.resize(frame,(1280,720))
    cv2.imshow('frame', frame)

    if cv2.waitKey(1) == ord('q'):
        break
```

**Comment by ayushraj2349** [comment]
@prince0310  Thanks alot. but i want this back also in the video and for that i implemented using DeepSORT library. it would be very helpful if you could help me in the same context in which i m interested.
thanks again.

**Comment by ayushraj2349** [comment]
> ![2](https://private-user-images.githubusercontent.com/85225054/304030493-b416a917-f0c1-4333-a8d3-4abe26a68ea5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NjAzMjgsIm5iZiI6MTcwNzc2MDAyOCwicGF0aCI6Ii84NTIyNTA1NC8zMDQwMzA0OTMtYjQxNmE5MTctZjBjMS00MzMzLWE4ZDMtNGFiZTI2YTY4ZWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDE3NDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMzIzZDQ3NDhjNTM4MzMyOTQ0MTY1MGUwOWNjYmQ4NzNhM2ZjMDMzNTdmNzU3OTZlOTk5ZGQyZDZkM2I0ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5zzNa6tV1FxVWAMPP9O0NWrynGBi_hF155867cHL6Wg) @ayushraj2349 try this ![1](https://private-user-images.githubusercontent.com/85225054/304030189-ee59a889-c04a-499a-9d99-4b57f85f5d5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NjAzMjgsIm5iZiI6MTcwNzc2MDAyOCwicGF0aCI6Ii84NTIyNTA1NC8zMDQwMzAxODktZWU1OWE4ODktYzA0YS00OTlhLTlkOTktNGI1N2Y4NWY1ZDVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDE3NDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NGI0OWMxYzMxMTJjYWY2ZTg0NmZkYmFhYmQ0NDZmMWJjMGE5ZDdkNjJlODI3Y2NiODBiODZjYjEzNjE4NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DcQjWYYazZw0Hf04K0xRTk5wdUAcLvmNJSg090bu1SI)
> 
> ```
> from ultralytics import YOLO
> cap = cv2.VideoCapture("20240110_163949.mp4")
> detection_model = YOLO("yolov8m.pt")
> while True:
>     ret, frame = cap.read()
> 
>     if not ret:
>         break
> 
>     detection_results = detection_model.predict(frame,classes = 0, conf = 0.25)
>     boxes = detection_results[0].boxes.xyxy.cpu().tolist()
>     classes = detection_results[0].boxes.cls.cpu().tolist()
>     scores = detection_results[0].boxes.conf.cpu().tolist()
>     cv2.putText(frame, "Person "f'{len(boxes)}', (10, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 255), 2, cv2.LINE_AA)
>     frame = cv2.resize(frame,(1280,720))
>     cv2.imshow('frame', frame)
> 
>     if cv2.waitKey(1) == ord('q'):
>         break
> ```

prince just check it, it has given the no. of count, no doubt but it isn't making the bboxes.

**Comment by prince0310** [comment]
@ayushraj2349 ADD this line for bbox
```
for i in range(len(boxes)):
     box = boxes[i]
     cls = classes[i]
     score = scores[i]

     x1, y1, x2, y2 = int(box[0]), int(box[1]), int(box[2]), int(box[3])
     cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)```

**Comment by ayushraj2349** [comment]
@prince0310 prince, i have a question then, if the purpose can be solved simply, then whar's the use of DeepSORT? why are we using such libraries?

**Comment by prince0310** [comment]
while counting can be a simple task, tracking objects in videos involves more complex challenges that DeepSORT addresses. Its ability to track objects, maintain identities, handle occlusions and noise, (which may not be possible by this simple logic) and perform in real-time makes it a valuable tool in various applications such as video surveillance, traffic monitoring, and autonomous systems.

**Comment by ayushraj2349** [comment]
@prince0310  so this can also be implemented using DeepSORT? if yes, then please provide me the specific code with the same library bcoz it would be good for me for showcasing, if i implement using DeepSORT. hope you understand and thank u for helping. i think this'll be the last time i will be disturbing you. sorry for that. but thanks alot.

**Comment by prince0310** [comment]
@ayushraj2349 you can take [refrence ](https://github.com/MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking) from . . please reach out if you have further question. Thank you
