### ISSUE TITLE
Automatically connecting to ultralytics hub

### ISSUE THREAD

**Issue by creativename00** [ultralytics/ultralytics#8140]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm currently trying to train yolov8 locally, but it fails after trying to upload a checkpoint to ultralytics hub. It was working fine locally before trying out using the ultralytics hub as a way to launch it. my laptop, which I never used ultralytics hub, still works ok with the exact same code. I tried deleting the account, but it still automatically wants to sync. Anyway to disconnect it?

**Comment by glenn-jocher** [comment]
@creativename00 hello! It seems like your local setup is attempting to sync with the Ultralytics Hub, which isn't the behavior you're looking for. To disconnect from the Ultralytics Hub and prevent automatic syncing, you can set the `hub` argument to `False` in your training script. Here's a quick example of how you can modify your training command:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('yolov8n.yaml')

# Train your model with hub syncing disabled
results = model.train(data='coco128.yaml', epochs=3, hub=False)
```

This should stop the automatic checkpoint uploads. If you continue to face issues, please let us know! 😊
