### ISSUE TITLE
How to generate evaluation metrics for tracking, such as MOTA, IDF1, HOTA, etc. ?	

### ISSUE THREAD

**Issue by Simeon340703** [ultralytics/ultralytics#8142]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Detection metrics such as mAP0.5, mAP[0.5,0.95], etc., can be generated for the object detection models of YOLO. Is there a method to generate evaluations for tracking results, such as MOTA, IDF1, HOTA, etc.? How to measure the performance of the tracking method, such as Bytetrack after training the YOLOv8 model for detection?

**Comment by glenn-jocher** [comment]
@Simeon340703 hi there! 👋

Currently, YOLOv8 does not natively generate tracking-specific metrics like MOTA, IDF1, or HOTA. However, you can use the tracking outputs from YOLOv8 with external tools like [TrackEval](https://github.com/JonathonLuiten/TrackEval) to compute these metrics.

Here's a quick example of how you might save your tracking results in a format compatible with such tools:

```python
from ultralytics import YOLO

# Load your trained model
model = YOLO('path/to/your/model.pt')

# Perform tracking on your video or image sequence
results = model.track(source='path/to/your/video.mp4')

# Save results in MOTChallenge format (frame, id, bbox, conf)
with open('track_results.txt', 'w') as f:
    for frame_id, result in enumerate(results):
        for box in result.boxes:
            bbox = box.xyxy[0].tolist()  # Convert from tensor to list
            track_id = box.id.item()  # Get track id
            conf = box.conf.item()  # Get confidence score
            f.write(f'{frame_id+1},{track_id},{bbox[0]},{bbox[1]},{bbox[2]-bbox[0]},{bbox[3]-bbox[1]},-1,-1,{conf}\n')
```

After saving your results, you can follow the instructions of the external tool to evaluate the tracking performance.

Hope this helps! If you have any more questions or need further assistance, feel free to ask. Happy tracking! 😊

**Comment by Simeon340703** [comment]
@glenn-jocher  Thanks for the quick reply. I will generate results compatible with the tools and then use the tools to generate the metrics. 
Thanks,
Sim~

**Comment by Simeon340703** [comment]
@glenn-jocher  I don't know why the track_id is None. However, it caused the following error when I tried to generate a compatible result using the above code. Here is the error says "  track_id = box.id.item()  # Get track id
AttributeError: 'NoneType' object has no attribute 'item' ".
 I have also printed out the box information and here is the output "  box: ultralytics.engine.results.Boxes object with attributes:

cls: tensor([113.], device='cuda:0')
conf: tensor([0.3676], device='cuda:0')
data: tensor([[3.8108e+02, 1.1646e+02, 4.3690e+02, 1.6851e+02, 3.6762e-01, 1.1300e+02]], device='cuda:0')
id: None
is_track: False
orig_shape: (1200, 1920)
shape: torch.Size([1, 6])
xywh: tensor([[408.9898, 142.4863,  55.8274,  52.0488]], device='cuda:0')
xywhn: tensor([[0.2130, 0.1187, 0.0291, 0.0434]], device='cuda:0')
xyxy: tensor([[381.0761, 116.4619, 436.9035, 168.5107]], device='cuda:0')
xyxyn: tensor([[0.1985, 0.0971, 0.2276, 0.1404]], device='cuda:0')
". 
Any suggestions? I am using my dataset and it works fine on tracking. 
Thanks!

**Comment by Simeon340703** [comment]
@glenn-jocher I don't know why the track_id is None. However, it caused the following error when I tried to generate a compatible result using the above code. Here is the error says " track_id = box.id.item() # Get track id
AttributeError: 'NoneType' object has no attribute 'item' ".
I have also printed out the box information and here is the output " box: ultralytics.engine.results.Boxes object with attributes:

cls: tensor([113.], device='cuda:0')
conf: tensor([0.3676], device='cuda:0')
data: tensor([[3.8108e+02, 1.1646e+02, 4.3690e+02, 1.6851e+02, 3.6762e-01, 1.1300e+02]], device='cuda:0')
id: None
is_track: False
orig_shape: (1200, 1920)
shape: torch.Size([1, 6])
xywh: tensor([[408.9898, 142.4863, 55.8274, 52.0488]], device='cuda:0')
xywhn: tensor([[0.2130, 0.1187, 0.0291, 0.0434]], device='cuda:0')
xyxy: tensor([[381.0761, 116.4619, 436.9035, 168.5107]], device='cuda:0')
xyxyn: tensor([[0.1985, 0.0971, 0.2276, 0.1404]], device='cuda:0')
".
Any suggestions? I am using my dataset and it works fine on tracking.
Thanks!

**Comment by glenn-jocher** [comment]
@Simeon340703 currently, Ultralytics YOLOv8 does not provide built-in functionality for calculating advanced multi-object tracking (MOT) metrics such as MOTA, IDF1, or HOTA directly within the repository. These metrics are typically used to evaluate the performance of tracking algorithms and require specialized evaluation scripts that take into account factors like track initialization, termination, identity switches, and other aspects specific to tracking.

However, you can still evaluate your tracking results using these metrics by following these general steps:

1. **Generate Tracking Results**: Use your trained YOLOv8 model with a tracking method like ByteTrack to process a video or dataset and generate tracking results. The results should include the frame number, track ID, bounding box coordinates, and object classes for each detected object in every frame.

2. **Format Results**: Ensure that your tracking results are formatted according to the requirements of the evaluation toolkit you plan to use. Common formats include the MOTChallenge format or a custom format that the evaluation script can process.

3. **Use an Evaluation Toolkit**: Utilize an external evaluation toolkit that supports the calculation of MOT metrics. One such toolkit is the [MOTChallenge EvalKit](https://github.com/JonathonLuiten/TrackEval), which is widely used in the tracking community. This toolkit can calculate a variety of metrics, including MOTA, IDF1, and HOTA.

4. **Run Evaluation**: Provide your formatted tracking results and the ground truth annotations to the evaluation toolkit. Run the evaluation script to calculate the desired metrics.

5. **Analyze Results**: Review the output from the evaluation toolkit to understand the performance of your tracking algorithm. The toolkit will typically provide detailed metrics that can help you identify areas for improvement.

Here's an example of how you might use the MOTChallenge EvalKit with your YOLOv8 tracking results:

```bash
# Clone the TrackEval repository
git clone https://github.com/JonathonLuiten/TrackEval.git

# Navigate to the TrackEval directory
cd TrackEval

# Install the required dependencies
pip install -r requirements.txt

# Run the evaluation script with your tracking results and ground truth data
python scripts/run_mot_challenge.py --BENCHMARK MOT20 --TRACKERS_TO_EVAL MyTracker --SPLIT_TO_EVAL train --TRACKERS_FOLDER path/to/trackers --GT_FOLDER path/to/gt --OUTPUT_FOLDER path/to/output
```

Replace `path/to/trackers` with the directory containing your tracking results, `path/to/gt` with the directory containing the ground truth annotations, and `path/to/output` with the directory where you want to save the evaluation results. Adjust the `--BENCHMARK` and `--SPLIT_TO_EVAL` flags as needed for your specific dataset.

By following these steps, you can evaluate the tracking performance of your YOLOv8 model using standard MOT metrics.

**Comment by Simeon340703** [comment]
@glenn-jocher Thank you so much. That's helpful.

**Comment by glenn-jocher** [comment]
@Simeon340703 currently, Ultralytics YOLOv8 does not provide built-in functionality for calculating advanced multi-object tracking (MOT) metrics like MOTA, IDF1, or HOTA directly within the repository. These metrics are typically used to evaluate the performance of tracking algorithms and require additional tools or libraries that specialize in MOT evaluation.

However, you can use external tools such as the [MOTChallenge](https://motchallenge.net/) evaluation toolkit or [TrackEval](https://github.com/JonathonLuiten/TrackEval) to calculate these metrics. These tools require the tracking output to be saved in a specific format, usually as text files with one row per object instance per frame, containing IDs and bounding box coordinates.

Here's a general approach to evaluate your tracking results using external tools:

1. **Run Tracking**: Use the YOLOv8 model to perform tracking on your dataset and save the tracking results in the required format. This typically involves saving a `.txt` file for each video sequence with frame number, track ID, bounding box coordinates, and confidence scores.

2. **Prepare Ground Truth**: Ensure you have the ground truth data for your dataset in the same format as your tracking results. The ground truth data is necessary for comparison during evaluation.

3. **Use Evaluation Toolkit**: Choose an evaluation toolkit like MOTChallenge or TrackEval. Follow the instructions provided by the toolkit to run the evaluation. This usually involves pointing the toolkit to the directory containing your tracking results and the corresponding ground truth data.

4. **Analyze Results**: The toolkit will process the tracking results and ground truth data to compute the MOT metrics. Analyze these metrics to understand the performance of your tracking algorithm.

For example, if you're using TrackEval, the process might look like this:

```bash
git clone https://github.com/JonathonLuiten/TrackEval.git
cd TrackEval
python -m pip install -r requirements.txt
python scripts/run_mot_challenge.py --BENCHMARK MOT20 --TRACKERS_TO_EVAL my_tracker --SPLIT_TO_EVAL train --DO_PREPROC False --TRACKER_SUB_FOLDER my_results_folder --GT_FOLDER path_to_ground_truth --SKIP_SPLIT_FOLDS True
```

In this example, replace `my_tracker` with the name of your tracker, `my_results_folder` with the folder containing your tracking results, and `path_to_ground_truth` with the path to the ground truth annotations.

Remember to check the specific instructions and requirements of the evaluation toolkit you choose to use.

**Comment by Simeon340703** [comment]
@glenn-jocher  Thank you for the detailed explanation. I will follow the instructions.

**Comment by glenn-jocher** [comment]
@pppppsb hello there! 😊 It looks like you're trying to access the `id` attribute for an object detection result where tracking IDs aren't available (`id: None`). This usually indicates that tracking was not performed, hence no `id` is assigned.

To ensure tracking IDs are generated and accessible, confirm you've used a tracking method like ByteTrack with your model. Here's an example of how to initiate tracking with YOLOv8, assuming you're working with the correct setup:

```python
from ultralytics import YOLO

# Initialize model with tracking enabled (make sure you have the right model)
model = YOLO('path/to/your/model.pt', tracker='bytetrack.yaml')

# Run tracking on your video or dataset
results = model.track('path/to/your/video.mp4')
```

Remember, the tracking ID (`id`) is only present when running tracking-specific methods (`model.track()`) and not during standard detection (`model.predict()`). If you're already doing this and still facing issues, there might be specific reasons based on your dataset or configuration that need closer investigation. 🧐

Feel free to share more details if you continue to encounter challenges. Happy tracking!

**Comment by pppppsb** [comment]
@glenn-jocher 
Hello, below is my tracking code
The code error is the same as that of the friend above, AttributeError: 'NoneType' object has no attribute 'item' ". What should I do next? I have no choice. Has your team measured this indicator?

from ultralytics import YOLO
# Configure the tracking parameters and run the tracker
model = YOLO("/home/ubuntu/Downloads/yolov8/runs/detect/train25/weights/[best.pt](http://best.pt/)")
results = model.track(source="loc_video_test/DJI_20230512175152_0171_T.MP4",
                      conf=0.25, iou=0.45, show=True, save=True, tracker="ultralytics/cfg/trackers/bytetrack.yaml")
# results = model.track(source="loc_video_test/DJI_20230512175152_0171_T.MP4",
#                       conf=0.25, iou=0.45, show=True, save=True, tracker="ultralytics/cfg/trackers/botsort.yaml")
Save results in MOTChallenge format (frame, id, bbox, conf)
with open('track_results.txt', 'w') as f:
    for frame_id, result in enumerate(results):
        for box in result.boxes:
            bbox = box.xyxy[0].tolist()  # Convert from tensor to list
            track_id = box.id.item()  # Get track id
            conf = box.conf.item()  # Get confidence score
            f.write(f'{frame_id+1},{track_id},{bbox[0]},{bbox[1]},{bbox[2]-bbox[0]},{bbox[3]-bbox[1]},-1,-1,{conf}\n')

**Comment by glenn-jocher** [comment]
Hello @pppppsb! It looks like the `track_id` is `None` because the tracking IDs aren't being generated. This usually happens if the model isn't set up correctly for tracking or if the `tracker` configuration isn't applied properly.

Make sure that the `tracker` path in your code points to a valid tracker configuration file. Also, ensure that your model is capable of tracking (i.e., it has been trained with tracking annotations if necessary).

Here's a quick check to ensure your tracker is set up correctly:

```python
from ultralytics import YOLO

# Ensure the tracker path is correct and the model is appropriate for tracking
model = YOLO("/home/ubuntu/Downloads/yolov8/runs/detect/train25/weights/best.pt", tracker="ultralytics/cfg/trackers/bytetrack.yaml")

# Run tracking
results = model.track(source="loc_video_test/DJI_20230512175152_0171_T.MP4", conf=0.25, iou=0.45, show=True, save=True)

# Check if tracking IDs are being generated
if results[0].boxes.id is not None:
    print("Tracking IDs are available.")
else:
    print("Tracking IDs are not generated. Check your model and tracker configuration.")
```

This should help you verify if the tracking setup is correct. If the problem persists, it might be worth revisiting the model or the tracker configuration details.

**Comment by Ares-cz** [comment]
Hi @glenn-jocher, I am trying to do the tracking evaluation for the masks, while like some evaluation tools you mentioned in TrackEval, they need the confidence value in result, while I found the document in Ultralytics [mask result](https://docs.ultralytics.com/reference/engine/results/#ultralytics.engine.results.Masks), there are not confidence value. Are there any plan for the tracking evaluation in segmentation (MOTS task). And how can we solve this problem at this time, before the officially feature.
Thank you.

**Comment by glenn-jocher** [comment]
Hi @Ares-cz,

Thank you for your question! Currently, the Ultralytics YOLOv8 framework does not directly provide confidence values for mask results in the segmentation (MOTS) task. This is a known limitation when using external evaluation tools like TrackEval that require confidence values.

### Workaround
To address this issue temporarily, you can use the confidence values from the bounding boxes associated with the masks. Here's a code snippet to help you extract and save these values:

```python
from ultralytics import YOLO

# Load your model
model = YOLO("/home/ubuntu/Downloads/yolov8/runs/detect/train25/weights/best.pt")

# Run tracking
results = model.track(source="loc_video_test/DJI_20230512175152_0171_T.MP4", conf=0.25, iou=0.45, show=True, save=True, tracker="ultralytics/cfg/trackers/bytetrack.yaml")

# Save results in MOTChallenge format (frame, id, bbox, conf)
with open('track_results.txt', 'w') as f:
    for frame_id, result in enumerate(results):
        for box in result.boxes:
            bbox = box.xyxy[0].tolist()  # Convert from tensor to list
            track_id = box.id.item()  # Get track id
            conf = box.conf.item()  # Get confidence score
            f.write(f'{frame_id+1},{track_id},{bbox[0]},{bbox[1]},{bbox[2]-bbox[0]},{bbox[3]-bbox[1]},-1,-1,{conf}\n')
```

### Future Plans
We understand the importance of having confidence values for mask results in tracking evaluations. While there is no official feature for this yet, we are continuously working on improving the framework and appreciate your feedback.

### Next Steps
Please ensure you are using the latest version of the Ultralytics YOLOv8 framework. If the issue persists, providing a minimum reproducible example would be very helpful for us to investigate further. You can find more details on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions or need further assistance. Happy tracking! 😊

**Comment by glenn-jocher** [comment]
It seems like your results are not aligning with expectations. Ensure that your model and tracker configurations are correctly set up, and consider verifying your evaluation process against the official guidelines. If issues persist, reviewing the dataset and annotations might help identify discrepancies.

**Comment by Y-T-G** [comment]
Try using `f.write(f'{frame_id+1},{track_id},{bbox[0]},{bbox[1]},{bbox[2]-bbox[0]},{bbox[3]-bbox[1]},{conf},-1,-1,-1\n')`

**Comment by FayalaMohamed** [comment]
Thanks !

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions, feel free to ask.

**Comment by glenn-jocher** [comment]
@FayalaMohamed you're welcome! If you have any more questions, feel free to ask.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions, feel free to ask.

**Comment by FayalaMohamed** [comment]
Thanks @glenn-jocher I have no more questions ! My error was putting the confidence at the end of the string and downloading the MOT20-train videos via model.track() using a url. I had to download the full dataset from the MOTChallenge website.

**Comment by glenn-jocher** [comment]
@FayalaMohamed you're welcome! If you have any more questions, feel free to ask.

**Comment by amarnathreddy0201** [comment]
Hi Everyone,

I am Evaluating on MOT17 and MOT20.

In ground truth  they given values like this 
1,1,199,813,140,268,1,1,0.83643
1,2,347,814,124,267,1,1,0.88469
1,3,399,789,104,259,1,1,0.33773
1,4,1651,831,100,250,1,1,0.99602
1,5,667,686,97,221,1,1,1.0
1,6,759,691,93,206,1,1,0.93617

What are the Column names?


Thanks in advance.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions, feel free to ask.

**Comment by amarnathreddy0201** [comment]
@glenn-jocher 
Thanks for sharing snippet for creating detection values.
MOT17/20 Data set labels different then yolov8 labels. 

How to evaluate 2 different types of labels(MOT and YOLO). With TracEval.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions, feel free to ask.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to ask.

**Comment by mugunthjhs** [comment]
How to merge the yolo detector to a MOT tracker like Fairmot, boosttrack, adaptrack?

**Comment by glenn-jocher** [comment]
To integrate YOLO with trackers like FairMOT, BoT-SORT, or similar, you would need to use YOLO for detection and feed its outputs (bounding boxes and confidence scores) into the tracker as input. Each tracker has its own format requirements, so you'll need to adapt YOLO's outputs accordingly. For further guidance, consult the respective tracker documentation for integration details.

**Comment by mugunthjhs** [comment]
> To integrate YOLO with trackers like FairMOT, BoT-SORT, or similar, you would need to use YOLO for detection and feed its outputs (bounding boxes and confidence scores) into the tracker as input. Each tracker has its own format requirements, so you'll need to adapt YOLO's outputs accordingly. For further guidance, consult the respective tracker documentation for integration details.

Can you provide any demo file or references of implementing yolo with MOT trackers like Fairmot or Boosttract in a video, I have lots of doubt...

**Comment by glenn-jocher** [comment]
@mugunthjhs currently, Ultralytics does not provide specific demo files for integrating YOLO with external trackers like FairMOT or BoT-SORT. However, you can adapt YOLO's detection outputs (bounding boxes, confidence scores, etc.) to the required format of the tracker. For guidance, refer to the tracker documentation and the [Ultralytics track mode documentation](https://docs.ultralytics.com/modes/track/), which outlines how to use YOLO models for tracking.

**Comment by duong0411** [comment]
how can evaluate for Mutiple Class Object Tracking ?

**Comment by duong0411** [comment]
with HOTA ?
and format grouth truth data and tracker data. How can i save type data ?

**Comment by duong0411** [comment]
And how can I annoatate data for object tracking ? what tool for grouth data ?

**Comment by glenn-jocher** [comment]
@duong0411 to annotate data for object tracking, tools like CVAT (Computer Vision Annotation Tool) and LabelImg can be used. CVAT is particularly effective for tracking as it supports frame-by-frame annotations and interpolation techniques, making it easier to label video sequences. Once annotated, ensure the output aligns with the tracking dataset format, such as MOT or YOLO formats, for compatibility with your model.

**Comment by Petros626** [comment]
@Simeon340703 updates regarding the metrics? I found some repost containing the code for your requested tracking metrics.
