### ISSUE TITLE
How change epoch number to apply albumentation?

### ISSUE THREAD

**Issue by koluzaeva** [ultralytics/ultralytics#8147]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! I found that albumentation is always applied to data during the last 10 epochs. How to change this value?

**Comment by prince0310** [comment]
@koluzaeva have a look `ultralytics/utils/tuner.py`

**Comment by koluzaeva** [comment]
@prince0310, sorry, I don't understand why should I look tuner.py? I want to change training parameters to apply albumentation earlier than at the last 10 epochs
