### ISSUE TITLE
How to train segmentation if the dataset consists of paired images

### ISSUE THREAD

**Issue by blackcement** [ultralytics/ultralytics#815]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a dataset where each original JPG image has a masked PNG image, where each object is marked with a different color. What should be the directory structure and how to write it to .yalm file?

**Comment by pderrenger** [comment]
@blackcement to train segmentation with paired images in YOLOv8, you can organize your dataset where each original JPG image has a corresponding masked PNG image. The directory structure should have the original JPG images and the corresponding masked PNG images separated into two different folders. Then, you can create a .yaml file to specify the train and val paths for the images and annotations, including the classes and colors used for the segmentation.

In the .yaml file, you need to define the paths to the original images and their corresponding masks, as well as the classes and colors used for segmentation. This allows YOLOv8 to understand and train on the paired images for segmentation tasks.

**Comment by glenn-jocher** [comment]
@pderrenger For training segmentation with YOLOv8, arrange your dataset with JPG images in one folder and their corresponding masked PNGs in another. In your .yaml file, specify the paths for the 'train' and 'val' directories for both images and masks. Also, list the 'nc' (number of classes) and a 'names' list with class names. Ensure that the 'colors' field is populated with the color values used in your masks, corresponding to each class. This setup will enable YOLOv8 to train on your paired images for segmentation. For more detailed instructions, please refer to the segmentation section in our documentation. 📘🎨
