### ISSUE TITLE
CI tests quota fails

### ISSUE THREAD

**Issue by Burhan-Q** [ultralytics/ultralytics#8161]
Perhaps it would be optimal to change `tests/test_python.py` to use the [GitHub Asset link](https://ultralytics.com/assets/coco8.zip) instead of Google Drive to avoid failures due to quota limits? Noticed on #8160

https://github.com/ultralytics/ultralytics/blob/e9ab4de354e34c7cf292b25e5dd5c1a6d4f3ae10/tests/test_python.py#L447

@glenn-jocher what are your thoughts on this? Does this need to use a Google Drive link or could it be any other link that might not throw a quota limit error?

**Comment by glenn-jocher** [comment]
@Burhan-Q should be resolved in #8163
