### ISSUE TITLE
Validate simultaneously while training from scratch

### ISSUE THREAD

**Issue by BirATMAN** [ultralytics/ultralytics#8168]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi I was training the yolov8n-seg model from scratch with "yolov8n-seg.yaml", at the end of training I saw that the metrics and validation are only recorded for the final epoch. Is there a way to incorporate it in the training itself without having to call a separate val instace for all epochs? 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@BirATMAN hi there! 👋

Absolutely, you can validate your model during training by setting the `val` argument to `True` in your training command. This will run validation at the end of each training epoch and log the metrics for you. Here's an example of how to do it:

```bash
yolo detect train data='coco128.yaml' model='yolov8n-seg.yaml' val=True
```

This will train your `yolov8n-seg` model on the `coco128.yaml` dataset and perform validation after each epoch. The results will be saved in your run directory for review. Happy training! 😊🚀
