### ISSUE TITLE
annotation format issue

### ISSUE THREAD

**Issue by ZeroAct** [ultralytics/ultralytics#817]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thank you for your great work!

I have some question.
When training with my custom data, I formatted bounding boxes as cxcywh like yolov5.
And I checked roboflow exports bounding boxes like i did.

But, your default dataloader assumes the bounding box format as xyxy,
and never set it to xywh.
https://github.com/ultralytics/ultralytics/blob/7a7c8dc7b70cf4bc0be18763a6b66805974ecbe6/ultralytics/yolo/utils/instance.py#L35

Did I miss something?
Thank you!

**Comment by Laughing-q** [comment]
@ZeroAct no need to worry. here is setting `bbox_format` to `xywh`:
[https://github.com/ultralytics/ultralytics/blob/09265b17d7bbe0f7d45d25086347fe8197cb6970/ultralytics/yolo/data/augment.py#L596](https://github.com/ultralytics/ultralytics/blob/09265b17d7bbe0f7d45d25086347fe8197cb6970/ultralytics/yolo/data/augment.py#L596)

**Comment by ZeroAct** [comment]
Oh, I missed that part..
I'm sorry to bother you.
Thank you!

**Comment by pderrenger** [comment]
@ZeroAct no bother at all! 😊 If you have any more questions or need further assistance, feel free to ask. Good luck with your custom dataset, and happy training!
