### ISSUE TITLE
Is it possiable to output a position estimation instead of 0's when using a YOLOv8-Pose?

### ISSUE THREAD

**Issue by cyu2023** [ultralytics/ultralytics#8175]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thank for your great work!

I am using YOLOv8-Pose to detect skeletons of persons in pictures. But I found that when a keypoint is unseen, the model will output 0's as result. I wonder if there is a parameter or something to make the model output a position estimation when a keypoint is unseen. 

(I used YOLO-Pose which based on YOLOv5 before. It outputs guessed positions when a keypoint is unseen. )

**Comment by glenn-jocher** [comment]
@cyu2023 hi there! 👋

Thanks for reaching out and for your kind words! In YOLOv8-Pose, keypoints that are not visible are indeed marked with zeros. Currently, there isn't a built-in parameter to estimate the position of unseen keypoints directly within the model's output.

However, you can post-process the output to estimate the positions of unseen keypoints. One common approach is to use interpolation or a kinematic model based on the visible keypoints. Here's a simple example using interpolation:

```python
import numpy as np

def estimate_unseen_keypoints(keypoints):
    # keypoints is a numpy array of shape (num_keypoints, 2)
    # Replace zeros with np.nan for unseen keypoints
    keypoints[keypoints == 0] = np.nan
    
    # Estimate positions (simple example using mean of visible keypoints)
    mean_position = np.nanmean(keypoints, axis=0)
    keypoints[np.isnan(keypoints)] = mean_position[np.newaxis, :]
    
    return keypoints

# Example usage
keypoints = np.array([[100, 200], [0, 0], [150, 250]])  # Example keypoints
estimated_keypoints = estimate_unseen_keypoints(keypoints)
```

This is a very basic example, and for more accurate estimations, you might consider more sophisticated methods like temporal smoothing if you're working with video data.

If you have any further questions or need assistance, feel free to ask. Happy coding! 😊

**Comment by zyy-xy** [comment]
@glenn-jocher Hi! Excuse me,
The visibility feature of keypoints is used in the annotation file during model training, but there is no such feature in the model output, only the confidence of keypoints. If I want to use the model output to assist with annotation, I currently need to manually add visibility features for each keypoint, which is a huge boring project. Could you please tell me how to solve this problem? Can I get the visibility feature from model output? Thanks for your help!

**Comment by glenn-jocher** [comment]
@zyy-xy hi there! 👋

Thanks for reaching out with your question. Currently, the visibility feature of keypoints isn't directly provided in the model's output, which primarily includes the keypoints' positions and their confidence scores. 

For automating the visibility annotation process, one approach could be to set a confidence threshold below which keypoints are considered invisible. Here's a quick example:

```python
def mark_visibility(keypoints_confidence, threshold=0.5):
    # keypoints_confidence is an array of confidence scores for each keypoint
    visibility = (keypoints_confidence >= threshold).astype(int)
    return visibility

# Example usage
keypoints_confidence = np.array([0.8, 0.4, 0.6])  # Example confidence scores
visibility = mark_visibility(keypoints_confidence)
```

This method treats keypoints with confidence below a certain threshold as not visible. Adjust the threshold based on your specific needs or dataset characteristics.

Hope this helps! If you have more questions or need further assistance, feel free to ask. Happy annotating! 😊

**Comment by krstevskipetar** [comment]
One workaround I used for this, albeit not ideal, is to monkeypatch the Keypoints class in ultralytics.engine.results and remove the 0 assignment in the __init__.
`class MyKeypoints(Keypoints, BaseTensor):
    @smart_inference_mode()
    def __init__(self, keypoints, orig_shape) -> None:
        if keypoints.ndim == 2:
            keypoints = keypoints[None, :]
        BaseTensor.__init__(self, keypoints, orig_shape)
        self.has_visible = self.data.shape[-1] == 3
ultralytics.engine.results.Keypoints = MyKeypoints
`
It would be nice if there was a built-in option for this.

**Comment by glenn-jocher** [comment]
Thank you for sharing your workaround. We appreciate your feedback and will consider it for future updates. For now, customizing the code as you've done is a practical approach. If you have any other suggestions or need further assistance, feel free to reach out.
