### ISSUE TITLE
class-agnostic NMS support in CoreML exports

### ISSUE THREAD

**Issue by filipwojtasik** [ultralytics/ultralytics#8177]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

As been said in  [https://github.com/ultralytics/ultralytics/issues/8118](url) there is no support for class-agnostic nms in CoreML models. This feature would significantly enhance the functionality and flexibility of CoreML models.
**Benefits**

- Enhanced Efficiency and Accuracy: By reducing the need for separate NMS operations for each class, class-agnostic NMS can improve the computational efficiency and accuracy of object detection models for some tasks.
- Streamlined Deployment: Integrating this feature directly into CoreML exports simplifies the deployment of models, particularly for iOS and macOS applications, by reducing the complexity of the inference pipeline.
- Increased Flexibility: Offering both class-aware and class-agnostic NMS options within CoreML would provide developers with greater flexibility in optimizing their models for different applications and use cases.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@filipwojtasik hi there! 👋

Thanks for bringing up the idea of class-agnostic NMS support for CoreML exports. We understand how this feature could streamline the deployment process and enhance model performance, especially for iOS and macOS applications. 

While it's not currently supported, we'll certainly consider its potential benefits for future updates. If you have any specific use cases or examples where this would be particularly beneficial, feel free to share them as it could help prioritize the feature.

In the meantime, if you're comfortable with contributing and have an implementation in mind, we're always open to community contributions, even though I see you've opted out of submitting a PR for now.

Keep an eye on our updates, and thanks again for your suggestion! 🚀
