### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by Magmus-maker** [ultralytics/ultralytics#8184]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When launching neural network training, I get this error:
`NotImplementedError                       Traceback (most recent call last)
Cell In[1], line 5
      1 from ultralytics import YOLO
      3 model = YOLO('yolov8m.pt')
----> 5 results = model.train(data='dataset_yolo8/data.yaml', epochs=100, imgsz=640) #, model='yolov8m.pt')

File c:\Users\Mugmazoid\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\engine\model.py:601, in Model.train(self, trainer, **kwargs)
    598             pass
    600 self.trainer.hub_session = self.session  # attach optional HUB session
--> 601 self.trainer.train()
    602 # Update model and cfg after training
    603 if RANK in (-1, 0):

File c:\Users\Mugmazoid\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\engine\trainer.py:208, in BaseTrainer.train(self)
    205         ddp_cleanup(self, str(file))
    207 else:
--> 208     self._do_train(world_size)

File c:\Users\Mugmazoid\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\engine\trainer.py:322, in BaseTrainer._do_train(self, world_size)
    320 if world_size > 1:
    321     self._setup_ddp(world_size)
--> 322 self._setup_train(world_size)
    324 nb = len(self.train_loader)  # number of batches
    325 nw = max(round(self.args.warmup_epochs * nb), 100) if self.args.warmup_epochs > 0 else -1  # warmup iterations
...
PythonTLSSnapshot: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:162 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:494 [backend fallback]
PreDispatch: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:166 [backend fallback]
PythonDispatcher: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:158 [backend fallback]  `

All file paths are correct. Here's the entire code:
`from ultralytics import YOLO

model = YOLO('yolov8m.pt')

results = model.train(data='dataset_yolo8/data.yaml', epochs=100, imgsz=640, batch = 40) #, model='yolov8m.pt')`

Please advise what could be the issue and how to fix it?

I have no idea how I can fix it

### Environment

Ultralytics YOLOv8.1.13 🚀 Python-3.12.2 torch-2.2.0+cu118 CUDA:0 (NVIDIA GeForce RTX 2060, 6144MiB)
Setup complete ✅ (16 CPUs, 15.9 GB RAM, 212.0/232.3 GB disk)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Burhan-Q** [comment]
@Magmus-maker try using python 3.11 instead of 3.12.

**Comment by Magmus-maker** [comment]
> @Magmus-maker try using python 3.11 instead of 3.12.

I will try it, thanks

**Comment by Burhan-Q** [comment]
Sure thing. I have a very similar system and it works with `coco128.yaml`  on Python 3.10 and `torch 2.1.0`

```
Ultralytics YOLOv8.1.13 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce RTX 2060, 5924MiB)
Setup complete ✅ (12 CPUs, 15.6 GB RAM, 82.3/101.0 GB disk)

OS                  Linux-6.6.10-76060610-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 15.56 GB
CPU                 AMD Ryzen 5 1600 Six-Core Processor
CUDA                12.1

matplotlib          ✅ 3.8.1>=3.3.0
numpy               ✅ 1.26.2>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 2.1.0>=1.8.0
torchvision         ✅ 0.16.0>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.1.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
```

**Comment by Magmus-maker** [comment]
> @Magmus-maker try using python 3.11 instead of 3.12.

Ye, It works. Thanks!

Now I using it:
`Ultralytics YOLOv8.1.13 🚀 Python-3.11.5 torch-2.2.0+cu118 CUDA:0 (NVIDIA GeForce RTX 2060, 6144MiB)
Setup complete ✅ (16 CPUs, 15.9 GB RAM, 213.6/232.3 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.11.5
Install             pip
RAM                 15.95 GB
CPU                 AMD Ryzen 7 3700X 8-Core Processor
CUDA                11.8

matplotlib          ✅ 3.8.2>=3.3.0
numpy               ✅ 1.26.4>=1.22.2
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.2.0+cu118>=1.8.0
torchvision         ✅ 0.17.0+cu118>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.0>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0`
