### ISSUE TITLE
How to do the Patch-based predictions

### ISSUE THREAD

**Issue by kajal1598** [ultralytics/ultralytics#8201]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to do predictions(for object detection) on large images.
so how to do using patch-based predictions?

### Additional

I trained model on images of x height and inference images are 2x or 3x larger(in height) than trained one.

**Comment by glenn-jocher** [comment]
@kajal1598 hello! For patch-based predictions on large images, you can divide your large image into smaller, overlapping patches that match the training size or aspect ratio, run predictions on each patch, and then merge the results. Here's a simple example using Python:

```python
from PIL import Image
from ultralytics import YOLO

# Load your trained model
model = YOLO('path/to/your/model.pt')

# Open your large image
large_image = Image.open('path/to/your/large/image.jpg')

# Define patch size (should match training size or aspect ratio)
patch_size = (model.imgsz, model.imgsz)

# Define stride for overlapping patches
stride = patch_size[0] // 2

# List to store results
results = []

# Generate patches
for top in range(0, large_image.height, stride):
    for left in range(0, large_image.width, stride):
        # Define the bottom and right coordinates for the patch
        bottom = min(top + patch_size[1], large_image.height)
        right = min(left + patch_size[0], large_image.width)
        # Crop the patch from the large image
        patch = large_image.crop((left, top, right, bottom))
        # Run prediction on the patch
        patch_results = model(patch)
        # Store or process the patch results here
        results.append(patch_results)

# Now, results contain predictions for all patches
# You can merge these results considering the overlaps and the original image size
```

Remember to adjust the `patch_size` and `stride` according to your specific needs. Also, consider the overlap between patches to avoid missing or duplicating detections. Happy detecting! 😊🔍

**Comment by deepukr007** [comment]
@kajal1598  You can also use SAHI for tiled inference 
https://github.com/obss/sahi
