### ISSUE TITLE
Add a batch size parameter to the inference mode

### ISSUE THREAD

**Issue by erickrf** [ultralytics/ultralytics#8204]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

When running `model.predict` on a collection of images, it would be great to be able to set the inference batch size, so that memory usage stays under control.

### Use case

Anyone running inference on a large number of images at once.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@erickrf hi there! 👋

Thanks for the suggestion! You can actually set the batch size for inference by using the `batch` argument in the `predict` method. Here's a quick example on how to do it:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('yolov8n.pt')

# Set the batch size for inference
batch_size = 16  # Set your desired batch size
results = model.predict(source='path/to/images', batch=batch_size)
```

This will ensure that your memory usage is optimized during inference. If you have any more questions or need further assistance, feel free to ask. And we're always happy to review and merge PRs that improve the project! 😊

**Comment by erickrf** [comment]
Thanks for the answer. I tried that, but there is something suboptimal with the implementation, at least on CPU.

I ran a fine-tuned Yolo nano model on batches of 32 (roughly) 1024x1024 images. Using the `batch` parameter of `predict`, RAM usage spiked to 9 GB. When I manually gave batches of 32 images, it stayed at 4 GB or less.

**Comment by glenn-jocher** [comment]
@erickrf thank you for your feature request and your willingness to contribute to the YOLOv8 repository with a PR. Adding a batch size parameter to the inference mode is indeed a valuable feature that can help manage memory usage more effectively, especially when processing a large number of images.

To implement this feature, you would need to modify the `predict` method in the YOLO class to accept a `batch_size` argument and then process the images in batches of the specified size. Here's a high-level outline of the steps you might take:

1. Fork the Ultralytics YOLOv8 repository if you haven't already.
2. Clone your fork locally.
3. Create a new branch for your feature.
4. Modify the `predict` method in the YOLO class to include a `batch_size` parameter.
5. Update the method to handle image inputs in batches, ensuring that memory usage is optimized.
6. Test your changes thoroughly with different batch sizes and input sizes.
7. Update the documentation to reflect the new `batch_size` parameter.
8. Commit your changes with a clear and descriptive commit message.
9. Push your changes to your fork on GitHub.
10. Submit a pull request to the Ultralytics YOLOv8 repository with a clear description of the changes and the benefits of the new feature.

Make sure to follow the contribution guidelines provided by Ultralytics for submitting PRs. If you need any assistance or have questions while implementing the feature, feel free to reach out to the community or maintainers for support.

Once again, thank you for your contribution to the YOLOv8 project!

**Comment by Bhavay-2001** [comment]
Hi @glenn-jocher, I would like to work on this issue. 
Thanks

**Comment by glenn-jocher** [comment]
Hi @Bhavay-2001! 👋

That's fantastic! We're thrilled to have you contribute to the YOLOv8 project. If you need any guidance or have questions as you work on this issue, please don't hesitate to ask. Happy coding! 🚀

**Comment by Bhavay-2001** [comment]
Hi @glenn-jocher, I am currently viewing this [file](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/models/yolo/model.py). I couldn't find the predict function implemented in here. Could you please tell if I am viewing the correct file?
Thanks

**Comment by Bhavay-2001** [comment]
Hi @glenn-jocher, I am able to understand the working/flow of the model till this part. 
```python
  if not self.predictor:
      self.predictor = predictor or self._smart_load("predictor")(overrides=args, _callbacks=self.callbacks)
      self.predictor.setup_model(model=self.model, verbose=is_cli)
  else:  # only update args if predictor is already setup
      self.predictor.args = get_cfg(self.predictor.args, args)
      if "project" in args or "name" in args:
          self.predictor.save_dir = get_save_dir(self.predictor.args)
  if prompts and hasattr(self.predictor, "set_prompts"):  # for SAM-type models
      self.predictor.set_prompts(prompts)
  return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
``` 
I understand that the code will enter the if block but I am not able to understand how will it move forward? Where will the batch size parameter work?

**Comment by glenn-jocher** [comment]
Hi @Bhavay-2001! 👋

Great to hear you're diving into the code! The snippet you've shared is part of the setup process for the predictor, which prepares the model for inference. The actual handling of the batch size for predictions typically occurs within the `predict` or `predict_cli` method called at the end of your snippet.

The batch size parameter is used to control how many images are processed at once during inference. If you're looking to modify or understand how batch size is implemented, you'd want to look into the `predict` method implementation. This method should be responsible for dividing the input data into batches of the specified size and then processing each batch through the model.

Unfortunately, the file you're looking at (`model.py`) doesn't directly handle the prediction logic. The `predict` function might be part of a different module that deals with inference tasks specifically. I'd recommend checking in the `predictor` class or similar, where the inference steps, including batching, are more likely to be defined.

If you're implementing or modifying the batch size functionality, you'd typically adjust how the input data is sliced into batches and ensure each batch is separately passed through the model for inference. Here's a very simplified example:

```python
def predict(self, images, batch_size=32):
    # Example logic for handling batches
    for i in range(0, len(images), batch_size):
        batch = images[i:i+batch_size]
        # Process the batch through the model
        results = self.model(batch)
        # Handle results
```

This is a simplified view, and the actual implementation might involve more steps, especially regarding tensor operations and moving data to the correct device (CPU/GPU).

Hope this helps clarify things a bit! If you have more questions or need further assistance, feel free to ask. Happy coding! 🚀

**Comment by Bhavay-2001** [comment]
```python
self.run_callbacks("on_predict_start")
            for batch in self.dataset:
                self.run_callbacks("on_predict_batch_start")
                self.batch = batch
                path, im0s, vid_cap, s = batch

                # Preprocess
                with profilers[0]:
                    im = self.preprocess(im0s)

                # Inference
                with profilers[1]:
                    preds = self.inference(im, *args, **kwargs)
                    if self.args.embed:
                        yield from [preds] if isinstance(preds, torch.Tensor) else preds  # yield embedding tensors
                        continue

                # Postprocess
                with profilers[2]:
                    self.results = self.postprocess(preds, im, im0s)

                self.run_callbacks("on_predict_postprocess_end")
                # Visualize, save, write results
                n = len(im0s)
                for i in range(n):
                    self.seen += 1
                    self.results[i].speed = {
                        "preprocess": profilers[0].dt * 1e3 / n,
                        "inference": profilers[1].dt * 1e3 / n,
                        "postprocess": profilers[2].dt * 1e3 / n,
                    }
                    p, im0 = path[i], None if self.source_type.tensor else im0s[i].copy()
                    p = Path(p)

                    if self.args.verbose or self.args.save or self.args.save_txt or self.args.show:
                        s += self.write_results(i, self.results, (p, im, im0))
                    if self.args.save or self.args.save_txt:
                        self.results[i].save_dir = self.save_dir.__str__()
                    if self.args.show and self.plotted_img is not None:
                        self.show(p)
                    if self.args.save and self.plotted_img is not None:
                        self.save_preds(vid_cap, i, str(self.save_dir / p.name))

                self.run_callbacks("on_predict_batch_end")
                yield from self.results

                # Print time (inference-only)
                if self.args.verbose:
                    LOGGER.info(f"{s}{profilers[1].dt * 1E3:.1f}ms")

        # Release assets
        if isinstance(self.vid_writer[-1], cv2.VideoWriter):
            self.vid_writer[-1].release()  # release final video writer

        # Print results
        if self.args.verbose and self.seen:
            t = tuple(x.t / self.seen * 1e3 for x in profilers)  # speeds per image
            LOGGER.info(
                f"Speed: %.1fms preprocess, %.1fms inference, %.1fms postprocess per image at shape "
                f"{(1, 3, *im.shape[2:])}" % t
            )
        if self.args.save or self.args.save_txt or self.args.save_crop:
            nl = len(list(self.save_dir.glob("labels/*.txt")))  # number of labels
            s = f"\n{nl} label{'s' * (nl > 1)} saved to {self.save_dir / 'labels'}" if self.args.save_txt else ""
            LOGGER.info(f"Results saved to {colorstr('bold', self.save_dir)}{s}")

        self.run_callbacks("on_predict_end")

``` 

Hi @glenn-jocher, sorry for late replying. I think that the `for batch in self.dataset:` is the above code will be used to optimise the batch_size parameter. Please let me know if I am going the correct path or not? 
Thanks

**Comment by glenn-jocher** [comment]
@Bhavay-2001 hi there! 👋

No worries about the timing. You're on the right track! The loop `for batch in self.dataset:` indeed iterates over batches of data from the dataset, which is a key part of handling different batch sizes efficiently during inference. This loop allows the model to process each batch sequentially, applying preprocessing, inference, and postprocessing steps to each batch.

If you're looking to optimize or adjust the batch size, you'd typically configure the dataset loader to yield batches of your desired size. The batch size can significantly impact both the speed and memory usage of the inference process, so it's great that you're considering it.

Keep up the good work, and if you have more questions or need further clarification, feel free to ask. Happy coding! 😊
