### ISSUE TITLE
object_ids, bounding boxes of tracking

### ISSUE THREAD

**Issue by Shuaib11-Github** [ultralytics/ultralytics#8208]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am having a problem to get objects_ids bounding boxes

### Additional

I am getting this 
0: 384x640 3 cars, 13.7ms
Speed: 8.0ms preprocess, 13.7ms inference, 1.9ms postprocess per image at shape (1, 3, 384, 640)
QObject::moveToThread: Current thread (0xc929ac0) is not the object's thread (0xba36250).
Cannot move to target thread (0xc929ac0)
qt.qpa.plugin: Could not load the Qt platform plugin "offscreen" in "/home/rmarri/anaconda3/envs/yoloft/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: xcb, eglfs, minimal, minimalegl, offscreen, vnc, webgl.
Aborted (core dumped)

**Comment by glenn-jocher** [comment]
@Shuaib11-Github hey there! 👋 It looks like you're trying to access the object IDs and bounding boxes from the tracking output. Here's a quick example of how you can retrieve that information from the `Results` object after running the tracker:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('path/to/your/model.pt')

# Run tracking on your source
results = model.track(source='path/to/your/video.mp4')

# Access object IDs and bounding boxes
for result in results:
    object_ids = result.boxes.id
    bounding_boxes = result.boxes.xyxy
    print("Object IDs:", object_ids)
    print("Bounding Boxes:", bounding_boxes)
```

Regarding the error you're encountering, it seems like there's an issue with Qt platform plugin initialization. This could be related to your environment setup. You might want to try setting the environment variable `QT_QPA_PLATFORM` to `offscreen` if you're running in a headless environment or reinstalling the Qt plugin as suggested by the error message.

Let me know if this helps or if you need further assistance! 😊

**Comment by Shuaib11-Github** [comment]
So do I need to reinstall it(qt package). For a video it is tracking ythe
objects but it is giving error sometimes attribute error, list object has
no attribute boxes etc.,

Could you please provide an example for this. I need to compare MOTA, MOTP
for ground truth and tracking ones. I have frame number, object_ids,
bounding boxes for ground truth but I am not getting for tracking part. I
need to get these metrics.

Could you provide an example of how to do that.

Thank you

**Comment by ankit14331** [comment]
@glenn-jocher  I'm not getting any object ID here, although I'm getting the bounding boxes.
Below is the output :
0: 384x640 2 No helmets, 189.7ms
Speed: 7.4ms preprocess, 189.7ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)
Object IDs: None
Bounding Boxes: tensor([[1736.1722,  240.5074, 1811.9447,  333.5307],
        [ 520.4196,   85.9099,  584.0240,  144.3433]])

**Comment by glenn-jocher** [comment]
@ankit14331 it looks like you're encountering two separate issues here:

1. You're having trouble accessing object IDs and bounding boxes from the tracking results.
2. There's an error related to Qt platform plugins when trying to visualize the results.

Let's address these issues one by one:

### Accessing Object IDs and Bounding Boxes

When using the Ultralytics YOLOv8 model for tracking, the results should include object IDs along with the bounding boxes. Here's how you can access them:

```python
from ultralytics import YOLO

# Load a model for tracking
model = YOLO('yolov8n.pt')  # Replace with your model path if different

# Track objects in a video
results = model.track(source="path/to/video.mp4", show=True)

# Iterate over the results
for result in results:
    # Access the bounding boxes and object IDs
    boxes = result.boxes.xyxy  # Bounding boxes in xyxy format
    object_ids = result.boxes.id  # Object IDs

    # Do something with the bounding boxes and object IDs
    # ...
```

Make sure you're using the correct model that supports tracking, and you have the tracking mode enabled.

### Qt Platform Plugin Error

The error message you're seeing is related to the Qt platform plugin initialization. This is typically a problem with the environment setup, particularly when using OpenCV with a GUI on a headless server (a server without a display).

Here are a few steps you can try to resolve this issue:

1. **Reinstall Qt Plugins**: Sometimes, reinstalling the application or the relevant Qt plugins can resolve the issue.

2. **Use a Virtual Display**: If you're running this on a headless server, you might need to use a virtual display software like `Xvfb` to emulate a display.

3. **Set the Platform**: You can set the platform to `offscreen` if you don't need to display the window. Before running your Python script, execute the following command in the terminal:
   ```bash
   export QT_QPA_PLATFORM='offscreen'
   ```
   Alternatively, you can set this environment variable within your Python script before importing any other modules:
   ```python
   import os
   os.environ['QT_QPA_PLATFORM'] = 'offscreen'
   ```

4. **Avoid GUI Functions**: If you don't need to visualize the results, you can avoid using functions that create a GUI window (like `cv2.imshow`). Instead, you can save the results to a file and analyze them later.

5. **Check OpenCV Installation**: Ensure that OpenCV is installed correctly with the Qt backend if you need GUI functionalities. You might need to reinstall OpenCV with the appropriate flags for Qt support.

Try these solutions to see if they resolve the Qt platform plugin error. If the problem persists, you may need to provide more details about your environment, such as the operating system, whether you're using a virtual environment, and how OpenCV was installed.

**Comment by Shuaib11-Github** [comment]
Thanks, I'll check it out.

I havethe ground truth labels have in the below format
Frame_no, object_ids, x_min, y_min, x_max, y_max
41, 334710, 952.0,0.0,79.0,14.0

But when I ran your suggested code,
I am getting
List of object_ids intensor([1,2,3,4,5,....,23])
List of list for bounding boxes

How do I go ahead and compare to calculate MOTA and MOTP.

**Comment by Shuaib11-Github** [comment]
I have for tracking for a single output I have 300 such instances
Object IDs: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,
12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])
Bounding Boxes: tensor([[1746.5852,  532.9240, 1919.6624,  752.6738],
        [ 671.1702,  433.9525,  746.4346,  495.2292],
        [ 631.0151,  388.8817,  681.9429,  427.3249],
        [ 750.9922,  409.3558,  809.0884,  456.6566],
        [1128.0063,  430.8089, 1202.2113,  484.1173],
        [1794.8990,  446.9329, 1918.4865,  507.2599],
        [1163.6973,  349.8423, 1202.3220,  381.4899],
        [1065.2070,  413.3709, 1131.9819,  464.2481],
        [ 852.6096,  404.4958,  911.0833,  446.3598],
        [1215.1777,  381.8876, 1265.1753,  421.5816],
        [1368.8850,  399.9973, 1424.5498,  440.3634],
        [ 957.9658,  404.4436, 1029.3635,  465.9520],
        [1518.6152,  334.2286, 1562.8381,  368.8765],
        [1609.2129,  333.2341, 1690.6794,  460.3948],
        [1027.0447,  340.4250, 1060.4711,  368.0705],
        [ 609.4783,  363.4427,  644.3919,  386.9360],
        [1131.8442,  349.2545, 1160.5519,  374.2233],
        [ 972.8117,  342.3387, 1005.2701,  366.1255],
        [ 908.2639,  302.0847,  956.2980,  336.6221],
        [1579.6724,  410.7565, 1613.2292,  459.0648],
        [1202.4021,  317.7359, 1228.8746,  340.8892],
        [ 761.5058,  364.0521,  793.8737,  388.1438],
        [ 842.4190,  361.6234,  886.5723,  391.3627]])

For ground truth
Frame_number, object_id, bounding boxes
41 34710 952.0 0.0 79.0 14.0

Now how do I calculate MOTA and MOTP for the above
