### ISSUE TITLE
MLFlow cannot register model

### ISSUE THREAD

**Issue by puranss** [ultralytics/ultralytics#8214]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I am using MLflow as described in this guide https://docs.ultralytics.com/integrations/mlflow/ for logging yolov8 models. I can track experiments nicely. But normally there is a register model button in MLFlow to add the trained model in the model registry. It would be neat to have this option in the mlflow integration of ultralytics

### Use case

To track the models and add them to a model registry to deploy the models later in production, it would be nice to have the option to register the yolo models, as it is standard in MLFlow

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@puranss hi there! 👋

Thanks for bringing this to our attention. Currently, the integration with MLflow is designed primarily for experiment tracking. The model registration feature is indeed a valuable addition for a complete MLOps cycle.

As a workaround, you can manually log the model artifact within your training script using MLflow's `log_artifact` or `log_model` functions after your training is complete. Here's a quick example of how you might do this:

```python
import mlflow
from ultralytics import YOLO

# Your training code
model = YOLO('yolov8n.yaml')
results = model.train(data='coco128.yaml', epochs=3)

# Log the model
with mlflow.start_run():
    mlflow.pytorch.log_model(model, "model")
```

This will save the model in MLflow's artifact storage, and you should be able to register it from there. We'll consider adding a more streamlined process for model registration in future updates.

Keep an eye on our GitHub repo for any announcements related to this feature! 🚀

**Comment by puranss** [comment]
When I do this I get the error ErrorMessage "TypeError: cannot pickle 'torch._C.Generator' object", is that because of the way yolo is returning the model?

**Comment by glenn-jocher** [comment]
@puranss thank you for bringing this to our attention. The ability to register models directly from the MLflow UI is indeed a standard feature in MLflow and can be very useful for managing the lifecycle of models, including staging and production deployment.

Currently, the integration guide for MLflow with Ultralytics YOLOv8 focuses on experiment tracking, which includes logging parameters, metrics, and artifacts. However, model registration is a separate process that typically involves additional steps after the model artifacts are logged.

To enable model registration for YOLOv8 models within MLflow, you would typically need to log the model in a format that MLflow recognizes as a model, such as a Python function, ONNX, or using MLflow's built-in flavors. Once the model is logged in one of these formats, the "Register Model" button should appear in the MLflow UI for that run.

Here's a general approach to how you might extend the current MLflow integration to support model registration:

1. After training your YOLOv8 model, export it to a format compatible with MLflow, such as ONNX.
2. Log the model to MLflow using `mlflow.<flavor>.log_model()`, where `<flavor>` is the appropriate MLflow model flavor for your exported model.
3. Once the model is logged, you should be able to see the "Register Model" button in the MLflow UI for that run.

For example, if you have exported your YOLOv8 model to ONNX format, you could use the following code snippet to log the model to MLflow:

```python
import mlflow
import mlflow.onnx

# Assuming 'model_onnx_path' is the path to your exported ONNX model
with mlflow.start_run() as run:
    # Log parameters, metrics, etc.
    # ...

    # Log the ONNX model
    mlflow.onnx.log_model(onnx_model=model_onnx_path, artifact_path="model")

    # Now the "Register Model" button should be available in the MLflow UI for this run
```

Please note that the exact implementation may vary depending on your setup and the specifics of how you're using MLflow and Ultralytics YOLOv8. If you're not familiar with the process of logging models in MLflow or need further assistance, I recommend checking the [MLflow documentation](https://www.mlflow.org/docs/latest/models.html) on model logging and registration.

If there's a strong demand for this feature, we might consider adding direct support for model registration in future updates to the Ultralytics YOLOv8 MLflow integration guide. Meanwhile, if you're willing to contribute to this feature, we welcome community contributions and pull requests.

**Comment by greviewer-edt** [comment]
```
class TrainerWrapper:
    config = {}
    GPU_USE = 0.6  # procentaje de uso de GPU

    def __init__(self, model, config: dict):
        self.model = model
        self.config = config

        # Configura los callbacks
        self.model.add_callback("on_train_start", self.on_train_start)
        self.model.add_callback("on_train_end", self.on_train_end)

    def on_train_end(self, trainer):
        pytorch_model = trainer.model
        mlflow.pytorch.log_model(pytorch_model, "model")

        mlflow.log_metrics(trainer.metrics)
        mlflow.log_metrics(trainer.metrics)

    def on_train_start(self, trainer):
        # optimal_batch = autobatch(
        #     model=self.model,
        #     imgsz=self.config["train"]["imgsz"],
        #     fraction=self.GPU_USE,
        #     batch_size=-1,
        # )

        # remove batch of self.config
        config_copy = self.config.copy()
        config_copy["train"].pop("batch")

        mlflow.log_params(config_copy["train"])
        mlflow.set_tag(
            "mlflow.note.content", self.config.get("metadata", {}).get("content")
        )
        mlflow.set_tag(
            "documentation", self.config.get("metadata", {}).get("documentation", "NA")
        )

        mlflow.set_tag("author", self.config.get("metadata", {}).get("author", "NA"))

        mlflow.set_tag("experiment_type", trainer.model._get_name())
        mlflow.set_tag("version", self.config.get("sweeper", {}).get("version", "NA"))
        mlflow.log_artifact(self.config["config_path"])

        mlflow.set_tag("data_source", self.config.get("train", {}).get("data", "NA"))

    def train(self, config_train: dict):
        return self.model.train(**config_train)
```





```
def train_yolo(request_config: dict, trial_number: int):

    # Configurar las variables de entorno necesarias para MLflow
    os.environ["MLFLOW_S3_ENDPOINT_URL"] = request_config["minio"]["MINIO_ENDPOINT"]
    os.environ["AWS_ACCESS_KEY_ID"] = request_config["minio"]["MINIO_ID"]
    os.environ["AWS_SECRET_ACCESS_KEY"] = request_config["minio"]["MINIO_SECRET_KEY"]
    os.environ["MLFLOW_TRACKING_URI"] = request_config["mlflow"][
        "MLFLOW_TRACKING_URI"
    ]  # URI del servidor MLflow
    os.environ["MLFLOW_ARTIFACT_URI"] = "s3://mlflow-artifacts/"  # Bucket en MinIO

    # Configurar el nombre del experimento y el nombre de la ejecución
    os.environ["MLFLOW_EXPERIMENT_NAME"] = request_config.get("sweeper").get(
        "study_name"
    )
    os.environ["MLFLOW_RUN_NAME"] = request_config.get("task_id")

    logger.info(f"🚀 Iniciando entrenamiento con la configuración: {request_config}")

    # Prepared and train model
    model_name = request_config["model"]

    if request_config["type"] == "yolo":
        model = YOLO(model_name)
    elif request_config["type"] == "rtdetr":
        model = RTDETR(model_name)
    else:
        raise ValueError("Invalid model type specified.")

    # Directorio de resultados
    if "task_id" not in request_config:
        return float("nan")

    timestamp = get_datetime()
    request_config["timestamp"] = timestamp

    RESULT_PATH = f'/models/{request_config.get("experiment_name")}/{request_config["type"]}/{request_config["task_id"]}/'
    os.makedirs(f"{RESULT_PATH}/trail_history", exist_ok=True)

    request_config["path_results"] = f"{RESULT_PATH}/{trial_number}/"

    # Entrenamiento
    if "train" in request_config:
        request_config["train"]["project"] = f"{RESULT_PATH}/{trial_number}/"
        request_config["train"]["name"] = f"train_{request_config.get('task_id')}"
        request_config["train"]["verbose"] = True
        request_config["train"]["plots"] = True
        request_config["train"]["exist_ok"] = True

        # Custom method
        mlflow.set_experiment(request_config.get("experiment_name"))
        trainer = TrainerWrapper(config=request_config, model=model)
        results = trainer.train(config_train=request_config["train"])

        # traidcional method
        # results = trainer.train(**request_config["train"])

        request_config["experiment_type"] = str(results.task)
        request_config["train"]["results"] = results.results_dict

```



De está manera se puede registrar el modelo en MLflow (ademas de otras metricas interesantes), me parece raro que no se haya incluido ya, pero por lo pronto así es como lo he solucionado, si alguno tiene una mejor forma, estaŕa encantado de mejorar el código.


[mi proyecto de uso](https://github.com/wisrovi/wyoloservice/blob/main/services/worker_utils/train_yolo.py)

**Comment by glenn-jocher** [comment]
Thank you for sharing your MLflow integration approach! For model registration, we recommend exporting the model to ONNX format first to avoid serialization issues with PyTorch's internal objects. Here's a concise solution:

```python
def on_train_end(trainer):
    # Export to ONNX
    model_path = f"{trainer.save_dir}/weights/best.pt"
    onnx_path = model_path.replace(".pt", ".onnx")
    trainer.model.export(format="onnx", imgsz=trainer.args.imgsz)
    
    # Log ONNX model
    mlflow.log_artifact(onnx_path)
```

This avoids the Generator pickling error while maintaining compatibility with MLflow's model registry. The Ultralytics team will consider adding native model registration support in a future release. For more details, see the MLflow integration documentation.

**Comment by wuhanstudio** [comment]
A minimum code snippet to add model logging:

```
import mlflow
from ultralytics import YOLO
from ultralytics import settings

# Log the model here
def on_train_end(trainer):
    mlflow.pytorch.log_model(trainer.model, "model")

# Build a new model from scratch
settings.update({"mlflow": True})
model = YOLO("yolov8n.yaml")

# Add callbavk to log the model
model.add_callback("on_train_end", on_train_end)

model.train(project="cilia", name="my_exp_name", data="my_train.yaml", epochs=5, patience=0, optimizer="AdamW", lr0=0.001, lrf=0.1, weight_decay=1.0, batch=32)  
```

**Comment by glenn-jocher** [comment]
Thank you for sharing your implementation. To resolve the serialization error when logging YOLO models with MLflow, we recommend exporting the model to ONNX format first. Here's a concise solution based on the MLflow integration documentation:

```python
def on_train_end(trainer):
    model_path = trainer.best  # Path to best.pt
    onnx_path = model_path.with_suffix('.onnx')
    trainer.model.export(format='onnx')  # Export to ONNX
    mlflow.log_artifact(onnx_path)  # Log ONNX model
```

This approach avoids PyTorch generator pickling issues while maintaining MLflow compatibility. For production deployments, consider the Ultralytics Enterprise License.
