### ISSUE TITLE
Output from YOLOv8 inference on OpenCV 4.7.0 (OpenCVSharp) is weird

### ISSUE THREAD

**Issue by JustBrandonLim** [ultralytics/ultralytics#822]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to do object detection with YOLOv8 via a custom trained model exported to ONNX with opset = 12.

![image](https://user-images.githubusercontent.com/93673724/216887300-329cf9f6-9726-44de-acd0-c3354e484a8d.png)
I can see that the 1x9x8400 seems correct as I have 5 classes trained.

However, inspecting the model shows that the class scores are weird.

```
Index: 1887, CX: 93.18381, CY: 93.52275, W: 93.68494, H: 94.316376, P1: 94.52374, P2: 94.699615, P3: 94.679016, P4: 95.2211, P5: 95.38255
Index: 1888, CX: 95.42944, CY: 95.351715, W: 96.07124, H: 96.61951, P1: 96.89496, P2: 96.84729, P3: 97.14171, P4: 97.2341, P5: 97.23956
Index: 1889, CX: 97.39581, CY: 97.85187, W: 98.19159, H: 98.1749, P1: 98.2153, P2: 98.13907, P3: 98.159424, P4: 98.13864, P5: 98.35278
Index: 1890, CX: 98.390045, CY: 98.47699, W: 98.628296, H: 98.82849, P1: 98.957855, P2: 98.94318, P3: 98.95825, P4: 98.91727, P5: 98.819214
Index: 1891, CX: 98.84033, CY: 99.069916, W: 99.10333, H: 99.92572, P1: 100.60089, P2: 100.969086, P3: 100.33362, P4: 99.55722, P5: 98.57248
```

```
Index: 8395, CX: 1.6498852E-06, CY: 2.3298694E-06, W: 1.5181334E-06, H: 1.1279211E-06, P1: 5.349977E-07, P2: 2.0664154E-06, P3: 3.4469601E-06, P4: 2.9687562E-06, P5: 1.9636097E-06
Index: 8396, CX: 2.4768424E-06, CY: 1.9474778E-06, W: 1.2156288E-06, H: 9.621629E-07, P1: 1.2140938E-06, P2: 1.074214E-06, P3: 6.062919E-07, P4: 1.6234933E-06, P5: 2.6205164E-06
Index: 8397, CX: 1.2301002E-06, CY: 9.770771E-07, W: 2.3061584E-06, H: 5.1234233E-06, P1: 3.3261704E-06, P2: 2.7959459E-06, P3: 1.2703805E-06, P4: 3.070906E-06, P5: 2.2054724E-06
Index: 8398, CX: 2.330954E-06, CY: 1.8274393E-06, W: 1.940633E-06, H: 1.1914459E-06, P1: 1.1482779E-06, P2: 9.819177E-07, P3: 1.0707395E-06, P4: 1.1397788E-06, P5: 8.302745E-07
Index: 8399, CX: 9.4383284E-07, CY: 9.2989154E-07, W: 1.0047584E-06, H: 1.484146E-06, P1: 1.5403855E-06, P2: 2.2498593E-06, P3: 2.148441E-06, P4: 2.12625E-06, P5: 1.7743324E-06
```

How can the class scores be above 1? Or am I doing something wrong here?

I also made sure that I checked that my reshaping is correct.

```csharp
using Mat detections = output.Reshape(0, output.Size(2), output.Size(1));
```

**Comment by boussad83** [comment]
What is also weird is the dimension: it must be 1 x (5 + 4 + 1) x (8400) ==> [1, 10, 8400]. With coco 80 classes, I got [1, 84, 8400] which seems not correct either. Something is wrong there.

**Comment by JustBrandonLim** [comment]
@boussad83 I managed to fix the issue!

First you reshape it to remove the **1**x?x8400.
```csharp
using Mat detections = output.Reshape(0, output.Size(1), output.Size(2));
```

Next, you will have to transpose it to rotate it 90 degrees counter clockwise, which makes it go from ? rows and 8400 columns,  to 8400 rows and ? columns.

```csharp
Cv2.Transpose(detections, detections);
```

You should be able to read the correct values now.

OpenCvSharp should be pretty similar to Python and C++.

**Comment by JustBrandonLim** [comment]
Hope that the team can standardize the output to match that of YOLOv5.

**Comment by boussad83** [comment]
@JustBrandonLim 
Changing the shape is not the issue but the dimensions of the model output. We have to get a [1, 1 + 4 + C, 8400], not [1, 4 + C, 8400],
with C being the number of classes.

**Comment by JustBrandonLim** [comment]
@boussad83 are you talking about the confidence that was in YOLOv5? I think it is removed in YOLOv8, you only have to look for the highest class scores now.
