### ISSUE TITLE
What's the right fps for yolov8 medium version?

### ISSUE THREAD

**Issue by ayushraj2349** [ultralytics/ultralytics#8220]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Sir, in my recent project i used yolov8m version and implemented it on a Colab GPU which was Tensor T4, i calculated it, it comes out to be 83 FPS. sir, just wanted to know is it correct? because i have to prepare my paper.

actually i calculated it by taking avg speed on inference which was in my case 12ms, so i take 1/12 and it comes out to be 83fps. 
am i correct?
thanks.

**Comment by glenn-jocher** [comment]
@ayushraj2349 hello! Your method for calculating the FPS seems reasonable. If your inference time per frame is averaging 12ms, then calculating the FPS as 1 / 0.012 would indeed give you approximately 83 FPS. Keep in mind that FPS can vary based on factors like input resolution, system load, and specific hardware capabilities. For your paper, it might be helpful to mention these conditions under which you measured the FPS. Good luck with your publication! 😊📝

**Comment by ayushraj2349** [comment]
Okay, got it!
Thanks glenn!

**Comment by glenn-jocher** [comment]
@ayushraj2349 the frames per second (FPS) metric for object detection models like YOLOv8 is a measure of how many images the model can process in one second. The FPS can vary depending on several factors, including the model version, the hardware it's running on, the image resolution, and the specific configuration of the model.

Based on your description, if the average inference time per image is 12 milliseconds (ms), your calculation method to determine FPS is correct. You can calculate FPS as follows:

FPS = 1 / (Inference Time per Image in seconds)

Given that 12ms is equal to 0.012 seconds, the calculation would be:

FPS = 1 / 0.012 ≈ 83.33

So, if you're consistently getting an average inference time of 12ms per image on a Tesla T4 GPU with the YOLOv8 medium model, then stating that the model runs at approximately 83 FPS in your paper would be correct.

However, it's important to note that FPS can fluctuate, and it's often a good idea to run multiple inferences and take an average to get a more reliable measurement. Additionally, when reporting performance metrics in a paper, it's also beneficial to provide details about the testing conditions, such as the input image resolution, the hardware specifications, and any other relevant configuration details that could affect performance. This information helps to ensure that your results are reproducible and comparable to other works.

**Comment by glenn-jocher** [comment]
@ayushraj2349 you're welcome! If you have any more questions or need further assistance, feel free to reach out. Happy coding! 😊🚀
