### ISSUE TITLE
Flood Segmentation Model Coordinaters

### ISSUE THREAD

**Issue by tristanfivaz** [ultralytics/ultralytics#8221]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi Everyone!
I was wondering if there was any support for the following query of mine:

I am using a custom trained instance segmentation water detection model and have combined this with the object counter code using regions of interests from here: https://docs.ultralytics.com/guides/object-counting/#advantages-of-object-counting

I have modified the counter to show when the detection is within the region of interest so that it can identify flooded roads. However, when using this code with the tracker as supposed to, it seems to only base its identifications from the center mass rather than any part being within the region of interest.

How can I base these detections whether part of the instance segmentation is in the region of interest? Can I get the individual polygon coordinates?

Thankyou so much for your help and I'm a massive fan of your work,
Tristan

I have attached images to show the current output. (The issue is when the Green tracking coords aren't in the region of interest but the segmentation still is.)  

![image](https://github.com/ultralytics/ultralytics/assets/42950803/d8f4efa2-1dd1-4fc8-aee0-ea6ea79f247c)
![image](https://github.com/ultralytics/ultralytics/assets/42950803/06879b0f-ef53-4683-a7d4-88add53e7e26)
![image](https://github.com/ultralytics/ultralytics/assets/42950803/cb203591-d5f6-4641-a87a-2bd843859349)

**Comment by glenn-jocher** [comment]
@tristanfivaz hi Tristan! 👋

Great to hear about your innovative use of YOLOv8 for flood segmentation and tracking! To check if any part of your segmented instance is within a region of interest (ROI), you can indeed access the individual polygon coordinates of the segmentation masks.

Here's a quick example of how you might achieve this:

```python
from ultralytics import YOLO

# Load your custom trained model
model = YOLO('path/to/your/custom-model.pt')

# Run prediction
results = model('path/to/your/image.jpg')

# Iterate over each detected object
for i, mask in enumerate(results.masks.data):
    # Get the polygon coordinates for the mask
    polygon = mask['polygon'].numpy()

    # Check if any point of the polygon is within your ROI
    # (You'll need to define the `is_within_roi` function based on your ROI logic)
    if any(is_within_roi(point) for point in polygon):
        print(f"Object {i} is within the ROI!")
```

Make sure to replace `'path/to/your/custom-model.pt'` and `'path/to/your/image.jpg'` with the actual paths to your model and image.

This should allow you to determine if any part of the segmentation is within your defined ROI. Keep up the fantastic work, and if you have any more questions, feel free to ask!

**Comment by tristanfivaz** [comment]
Hi Glenn!

Thankyou so much for your quick reply, unfortunately even with the first segment of the code, (I commented out the if any algorithm) when attempting to print the polygon or even work with the values I get the following error.

Traceback (most recent call last):
  File "C:\Users\trist\Desktop\Machine Learning\FloodID\test.py", line 13, in <module>
    for i, mask in enumerate(results.masks.data):
AttributeError: 'list' object has no attribute 'masks'
image 1/1 C:\Users\trist\Desktop\Machine Learning\FloodID\examples\frame907.jpg: 640x640 5 floodings, 231.2ms
Speed: 3.0ms preprocess, 231.2ms inference, 3.9ms postprocess per image at shape (1, 3, 640, 640)

Is there any solution to this?

Thanks! Tristan

**Comment by glenn-jocher** [comment]
@tristanfivaz hi Tristan,

It looks like you're trying to access the `masks` attribute directly from the list of results. Instead, you should access the `masks` attribute from each `Results` object within the list. Here's a corrected snippet:

```python
# Assuming 'results' is a list of Results objects
for result in results:
    if hasattr(result, 'masks'):
        for mask in result.masks:
            polygon = mask.polygons.numpy()  # Accessing polygon coordinates
            print(polygon)  # Now you can work with the polygon coordinates
```

This should resolve the AttributeError you're encountering. Let me know if this helps or if you run into any more issues!

**Comment by tristanfivaz** [comment]
@glenn-jocher Thankyou so much for your help!

You're incredible :)

Here's what my output looks like now after some debugging and more research.

![image](https://github.com/ultralytics/ultralytics/assets/42950803/adcafab0-226b-44f6-b707-9f81e6fb4766)

Best of luck with your projects!! Your whole team is amazing.

**Comment by glenn-jocher** [comment]
@tristanfivaz That's fantastic to see – your output looks great! 🌟

I'm thrilled to hear that you've made progress. If you have any more questions or need further assistance down the line, don't hesitate to reach out. Keep up the awesome work, and best of luck with your flood segmentation project!

And thank you for the kind words – it's truly a team effort here at Ultralytics. 😊
