### ISSUE TITLE
Yoloc8-Pose

### ISSUE THREAD

**Issue by JANARDHANAREDDYMS** [ultralytics/ultralytics#8226]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying out Yolo pose models, and I want to extract key points from the result i have obtained, 
This is the code I am running.

```from ultralytics import YOLO
     model = YOLO('yolov8n-pose.pt')
     results = model("/Users/janardhanareddyms/Downloads/biles.jpg", show=True)
     result_keypoint = results.keypoints.xyn.cpu().numpy()[0]
```

But there is an attribute error, telling me that there is no attribute as 'keypoints'.

when u print just results value it shows that key points can be accessed using 
keypoints: ultralytics.engine.results.Keypoints object

it would be great to learn how can i access the coordinates for key points 

### Additional

.

**Comment by JANARDHANAREDDYMS** [comment]
Found it :)

**Comment by JANARDHANAREDDYMS** [comment]
> @JANARDHANAREDDYMS it looks like you're trying to access the keypoints from the `Results` object returned by the model prediction, but encountering an attribute error. The issue might be due to the way you're trying to access the keypoints. Let's correct that.
> 
> When you perform a prediction with a YOLO pose model, the `Results` object contains a `keypoints` attribute if the model supports pose estimation. To access the keypoints, you should first ensure that the `Results` object contains the `keypoints` attribute and then access the keypoints for each detected object.
> 
> Here's how you can modify your code to correctly access the keypoints:
> 
> ```python
> from ultralytics import YOLO
> 
> # Load the YOLO pose model
> model = YOLO('yolov8n-pose.pt')
> 
> # Perform prediction on an image
> results = model("/Users/janardhanareddyms/Downloads/biles.jpg", show=True)
> 
> # Check if the keypoints attribute is present in the results
> if hasattr(results[0], 'keypoints'):
>     # Access the keypoints for the first detected object
>     keypoints = results[0].keypoints
>     # Convert keypoints to numpy array and access the keypoints for the first detected object
>     keypoints_numpy = keypoints.xyn.cpu().numpy()[0]
>     print(keypoints_numpy)
> else:
>     print("No keypoints attribute found in the results.")
> ```
> 
> Please note the following:
> 
> * The `Results` object returned by the model prediction is a list, where each element corresponds to a detected object. Therefore, you should index into this list to access the results for a specific object (e.g., `results[0]` for the first object).
> * The `keypoints` attribute is an instance of the `Keypoints` class, which contains the keypoints information. You can access the `xyn` attribute of the `Keypoints` object to get the keypoints in the normalized xy coordinates along with the confidence scores.
> * The `cpu()` method is used to ensure that the tensor is moved to the CPU before converting it to a numpy array with `numpy()`.
> 
> Make sure that the image you're using contains detectable poses and that the model is correctly loaded and capable of pose estimation. If the model does not detect any poses, the `keypoints` attribute may not be present, and you should handle this case accordingly.

``

**Comment by JANARDHANAREDDYMS** [comment]
Thanks a lot...I resolved the issue :)

**Comment by glenn-jocher** [comment]
@JANARDHANAREDDYMS it looks like you're trying to access the keypoints attribute directly from the `results` object, which is a list of `Results` objects. Each `Results` object contains the keypoints for the corresponding image or frame processed. To access the keypoints, you need to iterate over the `results` list and then access the `keypoints` attribute from each `Results` object.

Here's how you can modify your code to extract keypoints:

```python
from ultralytics import YOLO

# Load the model
model = YOLO('yolov8n-pose.pt')

# Run inference on an image
results = model("/Users/janardhanareddyms/Downloads/biles.jpg", show=True)

# Iterate over the results list (even if there's only one image)
for result in results:
    # Access the keypoints from the result
    keypoints = result.keypoints.xyn.cpu().numpy()
    print(keypoints)
```

This code will print out the keypoints for each detected object in the image. The keypoints are returned as a NumPy array with the shape `(num_objects, num_keypoints, 3)`, where the last dimension contains `(x, y, n)` for each keypoint, with `x` and `y` being the coordinates and `n` being the confidence score.

If you want to access keypoints for a specific object, you can index into the keypoints array. For example, to get the keypoints for the first detected object, you would use `keypoints[0]`.

Remember that if you're processing a batch of images, the `results` list will contain one `Results` object for each image in the batch, so you'll need to iterate over `results` accordingly.

**Comment by yildizyakup** [comment]
I would like to ask which indexes correspond to what. There are a bunch of points. Could you please explain, for example, which keypoint index represents the left shoulder?

**Comment by glenn-jocher** [comment]
@yildizyakup absolutely, happy to clarify! 🌟 In YOLOv8 pose models, keypoints are typically aligned with standard pose estimation datasets like COCO. For instance, in the COCO dataset, the left shoulder is usually represented by the index 5.

Here’s a brief snippet on how you could access the left shoulder keypoint:

```python
left_shoulder_index = 5  # Typically for COCO aligned models
results = model('your_image.jpg')
keypoints = results[0].keypoints.xyn.cpu().numpy()
left_shoulder = keypoints[:, left_shoulder_index, :2]  # assuming x, y coordinates needed
```

Remember, the exact indexing might vary based on the model and dataset. Always good to check the specific model documentation for precise details. Happy coding! ✨

**Comment by orzthecat** [comment]
Hey there, thank you @JANARDHANAREDDYMS and @yildizyakup for raising this, and to yourself @glenn-jocher for the great replies. 

I'm particularly grateful for the very last code example you posted, that on accessing the left shoulder keypoint; it's just what I've been looking for. I've run it here and it works really nicely - however whenever that particular keypoint does not exist on the webcam or video, the program quits running, with the message 
``
left_shoulder = keypoints[:, left_shoulder_index, :2]  # assuming x, y coordinates needed
IndexError: index 5 is out of bounds for axis 1 with size 0
``
Sorry for such a basic question: how do I prevent that from happening, so that it's happy to keep watching and waiting for a left shoulder (for instance) to show up, even when there's nobody in the shot?

**Comment by glenn-jocher** [comment]
Hey @orzthecat, thrilled to hear you found the code snippet useful! 🚀 It looks like you're encountering an `IndexError` because there are times when no keypoints are detected, resulting in an empty array. A simple solution is to check if any keypoints are detected before trying to access them. Here's a small tweak to handle such cases gracefully:

```python
if keypoints.size > 0:  # Check if any keypoints were detected
    left_shoulder = keypoints[:, left_shoulder_index, :2]  # Safe to access
else:
    left_shoulder = None  # No keypoints detected, handle accordingly
```

This way, your program will continue running smoothly, waiting for that elusive left shoulder keypoint to appear in the frame. Keep up the great explorations! 🌟

**Comment by orzthecat** [comment]
That did the trick. Many thanks @glenn-jocher . Much respect for looking after the noobs! 😎

**Comment by glenn-jocher** [comment]
@orzthecat you're welcome! We're all in this learning journey together, so never hesitate to ask questions, no matter how small. Glad I could help you out. Keep experimenting and coding! 🚀 If you stumble upon any more queries, you know where to find us. Happy coding!

**Comment by orzthecat** [comment]
Will do. Thank you!

**Comment by glenn-jocher** [comment]
You're welcome! If you have more questions down the road, don't hesitate to reach out. Happy coding! 😊
