### ISSUE TITLE
Kill zombie processes

### ISSUE THREAD

**Issue by johnnynunez** [ultralytics/ultralytics#8232]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

If train fails on ddp there are zombie processes in the back ground.
example to kill them:
```python
try: 
    mp.spawn(run, args=args, nprocs=world_size, join=True)
except KeyboardInterrupt:
    print('Interrupted')
    try: 
        dist.destroy_process_group()  
    except KeyboardInterrupt: 
        os.system("kill $(ps aux | grep multiprocessing.spawn | grep -v grep | awk '{print $2}') ")
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@johnnynunez hi there! 👋 It looks like you've encountered an issue with zombie processes when training with DDP fails. Thanks for sharing your solution to kill them. Your approach to handle the `KeyboardInterrupt` and clean up using `dist.destroy_process_group()` is spot on. Additionally, using `os.system` to kill remaining processes is a practical workaround.

If you consistently encounter this issue, you might want to wrap your training loop in a `with` statement to ensure cleanup is executed even when an exception occurs. Here's a quick example:

```python
import torch.distributed as dist

try:
    with mp.spawn(run, args=args, nprocs=world_size, join=True) as _:
        pass  # Your training loop here
except KeyboardInterrupt:
    print('Training interrupted, cleaning up...')
finally:
    if dist.is_initialized():
        dist.destroy_process_group()
```

This should help manage the cleanup more effectively. If you have any more details or need further assistance, feel free to share! 😊

**Comment by glenn-jocher** [comment]
@johnnynunez we actually have a similar process in place:

https://github.com/ultralytics/ultralytics/blob/8aa73c447022d022016bf7c7e0084786bf554111/ultralytics/engine/trainer.py#L197-L206

I think you could add your cleanup code to the cleanup function here:
https://github.com/ultralytics/ultralytics/blob/8aa73c447022d022016bf7c7e0084786bf554111/ultralytics/utils/dist.py#L68-L71

Can you please submit a PR for this after testing to see if this helps kill the zombie processes?

**Comment by johnnynunez** [comment]
I will check it! Thanks

**Comment by glenn-jocher** [comment]
@johnnynunez it seems like you're encountering an issue where zombie processes are left running in the background after a distributed data parallel (DDP) training session is interrupted, particularly when using PyTorch's `multiprocessing` module.

The code snippet you provided is a good starting point for handling this situation. It attempts to gracefully shut down the process group when a `KeyboardInterrupt` (Ctrl+C) is detected. If that fails and another `KeyboardInterrupt` is detected, it resorts to killing the processes using a system call that filters processes by name and uses their process IDs to terminate them.

Here's a slightly modified and more detailed version of your snippet that includes comments for clarity:

```python
import os
import torch.distributed as dist
import torch.multiprocessing as mp

def run(rank, args):
    # Your training code here
    pass

# Set the number of processes (world_size) to the number of available GPUs or any desired number
world_size = torch.cuda.device_count()  # Example: number of GPUs

# Arguments to be passed to the training function
args = (arg1, arg2, arg3)  # Replace with actual arguments

try:
    # Spawn the processes for DDP training
    mp.spawn(run, args=args, nprocs=world_size, join=True)
except KeyboardInterrupt:
    print('Training interrupted. Attempting to clean up...')
    try:
        # Attempt to destroy the process group to clean up DDP resources
        dist.destroy_process_group()
    except Exception as e:
        print(f'Error while destroying process group: {e}')
        print('Attempting to kill zombie processes...')
        # If the process group destruction fails, kill the zombie processes using a system call
        os.system("kill $(ps aux | grep 'your_training_script.py' | grep -v grep | awk '{print $2}') ")
        # Replace 'your_training_script.py' with the actual name of your training script
```

Please replace `'your_training_script.py'` with the actual name of your training script to ensure that the correct processes are targeted. Also, make sure to replace `arg1, arg2, arg3` with the actual arguments you need to pass to your training function.

This approach should help you manage and terminate any zombie processes that may arise from an interrupted DDP training session. However, please use caution when using `os.system` to kill processes, as it can terminate unintended processes if not filtered correctly.

**Comment by glenn-jocher** [comment]
@johnnynunez just checking in here, also be careful that your proposed solution doesn't adversely affect other DDP trainings on the same instance, i.e. if a user has two 4x GPU trainings ongoing would your logic also kill the other training?
