### ISSUE TITLE
NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend.

### ISSUE THREAD

**Issue by CCccccccc98** [ultralytics/ultralytics#8238]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to use GPU to run training, but I encountered an error. The following is my original code and the error I encountered. I am using python3.9.6, the graphics card is NVIDIA GeForce MX130, and the downloaded torch version is CUDA12.1, and then The content of the computer graphics card says NVIDLA CUDA 12.3.106 driver. I am not sure if this is the reason because I executed print("CUDA available:",torch.cuda.is_available())
print("cuDNN enabled",torch.backends.cudnn.enabled) are all true. Please help me with the answer. Thank you.
![螢幕擷取畫面 2024-02-16 144320](https://github.com/ultralytics/ultralytics/assets/160203768/b6986262-2862-410b-a75d-5c08687361ae)
![螢幕擷取畫面 2024-02-16 144744](https://github.com/ultralytics/ultralytics/assets/160203768/c4bb4533-e8ac-4e84-9dfa-b696bf2f9164)
![螢幕擷取畫面 2024-02-16 144921](https://github.com/ultralytics/ultralytics/assets/160203768/2f50e827-3fc3-4dbc-8d47-b36a18b6d675)
![螢幕擷取畫面 2024-02-16 145028](https://github.com/ultralytics/ultralytics/assets/160203768/40e0fba8-4d8e-4573-a82f-83a7b6971db7)

**Comment by PiyushKamboj1503** [comment]
Just 'pip uninstall torchvision' and install the pytorch again from the pytorch website with CUDA backend. It will resolve.

**Comment by Burhan-Q** [comment]
@CCccccccc98 you have to ensure that `torch` and `torchvision` _both_ have CUDA enabled, but also are compatible versions; see [here for the compatible versions](https://github.com/pytorch/vision#installation)

**Comment by CCccccccc98** [comment]
Resolved thanks

**Comment by glenn-jocher** [comment]
@CCccccccc98 great to hear that your issue is resolved! If you have any more questions or run into other issues in the future, don't hesitate to reach out. Happy coding! 😊🚀
