### ISSUE TITLE
Multi GPU Training on Windows

### ISSUE THREAD

**Issue by PiyushKamboj1503** [ultralytics/ultralytics#8239]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

As per the Documentation, data_parallel argument should help multi gpu training but it is not available anymore. On windows the multi GPU Training is not working and linux is recommended. Is there any workaround?

**Comment by glenn-jocher** [comment]
@PiyushKamboj1503 hello! 👋

For multi-GPU training on Windows, you can use the `device` argument to specify multiple GPU IDs. Here's a quick example of how you might set it up:

```bash
yolo detect train data=coco128.yaml model=yolov8n.pt device=0,1
```

This command will initiate training on GPUs 0 and 1. If you encounter any issues or have further questions, feel free to reach out! 🚀

**Comment by PiyushKamboj1503** [comment]
> @PiyushKamboj1503 hello! 👋
> 
> For multi-GPU training on Windows, you can use the `device` argument to specify multiple GPU IDs. Here's a quick example of how you might set it up:
> 
> ```bash
> yolo detect train data=coco128.yaml model=yolov8n.pt device=0,1
> ```
> 
> This command will initiate training on GPUs 0 and 1. If you encounter any issues or have further questions, feel free to reach out! 🚀

Hey @glenn-jocher, I tried the same using CLI and Python code as well. But the training doesn't start and throws out a torch error.

I am using i9 14900k + 2x Rtx 4090

**Comment by glenn-jocher** [comment]
@PiyushKamboj1503 multi-GPU training on Windows can indeed be challenging due to various limitations and lack of support for certain features that are available on Linux. While the recommended approach for multi-GPU training with Ultralytics YOLO models is to use a Linux-based system, there are a few potential workarounds you can try on Windows:

1. **Use PyTorch Distributed Data Parallel (DDP):**
   PyTorch's Distributed Data Parallel (DDP) is designed to scale up the use of multiple GPUs across multiple nodes. While it's typically used in a Linux environment with support for the NCCL backend, you can try using the Gloo backend on Windows. However, this may require significant changes to the training script and is not officially supported by Ultralytics for YOLOv8.

2. **Windows Subsystem for Linux (WSL):**
   If you're on Windows 10 or later, you can try using the Windows Subsystem for Linux (WSL) to create a Linux environment on your Windows machine. WSL2, in particular, has improved support for GPU acceleration, which might allow you to use multi-GPU training as you would on a native Linux system.

3. **Third-Party Tools:**
   Some third-party tools and libraries are designed to facilitate multi-GPU training on Windows. These tools abstract away some of the complexities of setting up distributed training. However, compatibility with Ultralytics YOLOv8 would need to be verified.

4. **Virtual Machine or Cloud Environment:**
   You can set up a Linux virtual machine on your Windows host that can access the GPUs. This approach may come with some performance overhead. Alternatively, you can use cloud-based services that offer Linux environments with multi-GPU support.

5. **Native Support in Future Releases:**
   Keep an eye on future releases of Ultralytics YOLOv8 and PyTorch. There may be updates that improve or add support for multi-GPU training on Windows.

For now, if none of these workarounds are suitable or if you encounter significant difficulties, the most straightforward solution would be to use a Linux-based system for multi-GPU training. This could be on a local machine with a Linux OS or a cloud-based virtual machine with GPU support.

**Comment by glenn-jocher** [comment]
Hi @PiyushKamboj1503,

Sorry to hear you're encountering issues with multi-GPU training on Windows. It seems like there might be a compatibility problem with the PyTorch version and the RTX 4090 cards. Could you please ensure you're using the latest PyTorch version compatible with your CUDA version? Also, double-check that both GPUs are visible to PyTorch with:

```python
import torch
print(torch.cuda.device_count())
```

If the issue persists, it might be helpful to post the exact error message you're getting. We'll do our best to help you troubleshoot this! 🛠️

**Comment by piyush-evigway** [comment]
```
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\admin\\.conda\\envs\\Yolo\\python.exe', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '50033', 'C:\\Users\\admin\\AppData\\Roaming\\Ultralytics\\DDP\\_temp_en26e7ko2064988770576.py']' returned non-zero exit status 1.
```

The following error is encountered.

Also, the above code gives the count as 2

**Comment by glenn-jocher** [comment]
@piyush-evigway hey there,

Thanks for sharing the details of the error you're encountering. It looks like there might be an issue with the distributed training setup. Since your GPU count is correctly identified as 2, the hardware seems to be recognized properly.

A few things you could check:
- Ensure that the PyTorch distributed package is correctly installed and configured.
- Verify that the master port `50033` is not being used by another process.
- Sometimes, firewall or antivirus software can interfere with distributed training. You might want to check those settings as well.

If the problem persists, could you please run the training with the `--verbose` flag and share any additional output? That might give us more context to pinpoint the issue.

Keep me posted, and we'll get to the bottom of this! 🛠️

**Comment by piyush-evigway** [comment]
`C:\Users\admin\.conda\envs\Yolo\python.exe E:\Yolo\workspace.py 
New https://pypi.org/project/ultralytics/8.1.16 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.1.14 🚀 Python-3.11.7 torch-2.2.0+cu121 CUDA:0 (NVIDIA GeForce RTX 4090, 24564MiB)
                                                           CUDA:1 (NVIDIA GeForce RTX 4090, 24564MiB)
engine\trainer: task=detect, mode=train, model=yolov8l.yaml, data=coco.yaml, epochs=300, time=None, patience=50, batch=-1, imgsz=640, save=True, save_period=-1, cache=False, device=[0, 1], workers=8, project=None, name=train18, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\train18

                   from  n    params  module                                       arguments                     
  0                  -1  1      1856  ultralytics.nn.modules.conv.Conv             [3, 64, 3, 2]                 
  1                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  2                  -1  3    279808  ultralytics.nn.modules.block.C2f             [128, 128, 3, True]           
  3                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  4                  -1  6   2101248  ultralytics.nn.modules.block.C2f             [256, 256, 6, True]           
  5                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]              
  6                  -1  6   8396800  ultralytics.nn.modules.block.C2f             [512, 512, 6, True]           
  7                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]              
  8                  -1  3   4461568  ultralytics.nn.modules.block.C2f             [512, 512, 3, True]           
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  3   4723712  ultralytics.nn.modules.block.C2f             [1024, 512, 3]                
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  3   1247744  ultralytics.nn.modules.block.C2f             [768, 256, 3]                 
 16                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  3   4592640  ultralytics.nn.modules.block.C2f             [768, 512, 3]                 
 19                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  3   4723712  ultralytics.nn.modules.block.C2f             [1024, 512, 3]                
 22        [15, 18, 21]  1   5644480  ultralytics.nn.modules.head.Detect           [80, [256, 512, 512]]         
YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs

WARNING ⚠️ 'batch=-1' for AutoBatch is incompatible with Multi-GPU training, setting default 'batch=16'
DDP: debug command C:\Users\admin\.conda\envs\Yolo\python.exe -m torch.distributed.run --nproc_per_node 2 --master_port 57662 C:\Users\admin\AppData\Roaming\Ultralytics\DDP\_temp_66d_tzit2755049227216.py
[2024-02-21 13:01:24,155] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[W socket.cpp:697] [c10d] The client socket has failed to connect to [admin-main]:57662 (system error: 10049 - The requested address is not valid in its context.).
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\admin\.conda\envs\Yolo\Lib\site-packages\torch\distributed\run.py", line 816, in <module>
    main()
  File "C:\Users\admin\.conda\envs\Yolo\Lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\Yolo\Lib\site-packages\torch\distributed\run.py", line 812, in main
    run(args)
  File "C:\Users\admin\.conda\envs\Yolo\Lib\site-packages\torch\distributed\run.py", line 803, in run
    elastic_launch(
  File "C:\Users\admin\.conda\envs\Yolo\Lib\site-packages\torch\distributed\launcher\api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\Yolo\Lib\site-packages\torch\distributed\launcher\api.py", line 259, in launch_agent
    result = agent.run()
             ^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\Yolo\Lib\site-packages\torch\distributed\elastic\metrics\api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\Yolo\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 727, in run
    result = self._invoke_run(role)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\Yolo\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 862, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "C:\Users\admin\.conda\envs\Yolo\Lib\site-packages\torch\distributed\elastic\metrics\api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\Yolo\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 699, in _initialize_workers
    self._rendezvous(worker_group)
  File "C:\Users\admin\.conda\envs\Yolo\Lib\site-packages\torch\distributed\elastic\metrics\api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\Yolo\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 542, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\Yolo\Lib\site-packages\torch\distributed\elastic\rendezvous\static_tcp_rendezvous.py", line 55, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.distributed.DistNetworkError: Unknown error
Traceback (most recent call last):
  File "E:\Yolo\workspace.py", line 11, in <module>
    training()
  File "E:\Yolo\workspace.py", line 7, in training
    history = model.train(data="coco.yaml", epochs=300, batch=-1, device=[0,1], save=True, verbose=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\Yolo\Lib\site-packages\ultralytics\engine\model.py", line 601, in train
    self.trainer.train()
  File "C:\Users\admin\.conda\envs\Yolo\Lib\site-packages\ultralytics\engine\trainer.py", line 203, in train
    raise e
  File "C:\Users\admin\.conda\envs\Yolo\Lib\site-packages\ultralytics\engine\trainer.py", line 201, in train
    subprocess.run(cmd, check=True)
  File "C:\Users\admin\.conda\envs\Yolo\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\admin\\.conda\\envs\\Yolo\\python.exe', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '57662', 'C:\\Users\\admin\\AppData\\Roaming\\Ultralytics\\DDP\\_temp_66d_tzit2755049227216.py']' returned non-zero exit status 1.

Process finished with exit code 1`

@glenn-jocher here is the output with verbose flag

**Comment by glenn-jocher** [comment]
Hey @piyush-evigway,

It looks like there's an issue with the distributed training setup, possibly related to the network configuration on your system. The error message indicates a problem with connecting to the master port `57662`.

Here are a couple of things you could try:
- Make sure the specified master port is not blocked by a firewall or already in use by another process.
- Try using a different port number by setting the `--master_port` flag to a different value.

If these suggestions don't resolve the issue, it might be helpful to check the network settings or consider running the training on a different machine or environment where distributed training is known to work well.

Keep me updated, and we'll work through this together!

**Comment by piyush-evigway** [comment]
@glenn-jocher 
I have tried using the fresh install of windows 11 Pro as well. There is no program blocking the port. The firewall has the port open as well. The `--master_port` flag doesn't work.

**Comment by glenn-jocher** [comment]
Hi @piyush-evigway,

Thanks for the update and for trying out those steps. It's puzzling that the `--master_port` flag isn't making a difference. Could you try setting the `GLOO_SOCKET_IFNAME` environment variable to your network interface name before running the training? Here's how you can do it:

```bash
set GLOO_SOCKET_IFNAME=eth0
yolo detect train data=coco128.yaml model=yolov8n.pt device=0,1
```

Replace `eth0` with your actual network interface name. You can find it by running `ipconfig` in your command prompt.

If this doesn't help, it might be worth trying to run the training without distributed training just to isolate the issue:

```bash
yolo detect train data=coco128.yaml model=yolov8n.pt device=0 --single-gpu
```

Let's see if this gets things moving! 🤞

**Comment by piyush-evigway** [comment]
hey @glenn-jocher The `GLOO_SOCKET_NAME` workaround is not working.
As for the other `--single-gpu` flag, here is the output:
![image](https://github.com/ultralytics/ultralytics/assets/148423184/86c49636-50b1-40fa-b6f5-4ba6d6cc4a3e)

**Comment by glenn-jocher** [comment]
@piyush-evigway hi there,

Thanks for giving that a try. It seems we're still facing some challenges with the multi-GPU setup on Windows. The `--single-gpu` flag is actually not a recognized argument in our system, so my apologies for any confusion there.

From the screenshot, it looks like there might be an issue with the script or command you're running. Unfortunately, the image link is broken, so I can't see the exact error message. Could you please copy and paste the error text here?

In the meantime, you might want to ensure that your environment is set up correctly for distributed training. This includes having the correct versions of PyTorch and CUDA installed, and that they are compatible with your GPUs.

Let's keep working on this together, and we'll find a solution soon! 🛠️

**Comment by ZHAIXINGZHAIYUE** [comment]
same problem on windows

**Comment by glenn-jocher** [comment]
@ZHAIXINGZHAIYUE hi there,

I'm sorry to hear you're experiencing the same issue on Windows. Could you please ensure that you're using the latest versions of PyTorch and CUDA that are compatible with your system? Sometimes, updating these can resolve multi-GPU training issues.

If the problem persists, it might be helpful to share the error message you're encountering. This way, we can provide more targeted assistance. 🛠️

Thanks for reaching out, and we're here to help you get back on track!

**Comment by piyush-evigway** [comment]
> @piyush-evigway hi there,
> 
> Thanks for giving that a try. It seems we're still facing some challenges with the multi-GPU setup on Windows. The `--single-gpu` flag is actually not a recognized argument in our system, so my apologies for any confusion there.
> 
> From the screenshot, it looks like there might be an issue with the script or command you're running. Unfortunately, the image link is broken, so I can't see the exact error message. Could you please copy and paste the error text here?
> 
> In the meantime, you might want to ensure that your environment is set up correctly for distributed training. This includes having the correct versions of PyTorch and CUDA installed, and that they are compatible with your GPUs.
> 
> Let's keep working on this together, and we'll find a solution soon! 🛠️

hey @glenn-jocher , as suggested by you, I have throughly checked everything.
I have dual booted the same system in ubuntu and multi gpu training works perfectly. We can rule out the hardware issues. Also, I used the identical environments by using pip freeze.

**Comment by glenn-jocher** [comment]
Hey @piyush-evigway,

Great to hear that multi-GPU training works well on Ubuntu! This indeed helps us rule out hardware issues. 🎉 Since the setup works on Ubuntu but not on Windows with an identical environment, it points towards a platform-specific challenge with Windows.

For now, it seems like the best workaround for utilizing multi-GPU capabilities might be to stick with Ubuntu for your training tasks. We'll continue to investigate the Windows-specific issues and aim to enhance support in future updates.

Thanks for your patience and for providing these insights! If you have any more questions or run into other issues, feel free to reach out. Happy training!

**Comment by RyanSunn** [comment]
> Hey @piyush-evigway,
> 
> Great to hear that multi-GPU training works well on Ubuntu! This indeed helps us rule out hardware issues. 🎉 Since the setup works on Ubuntu but not on Windows with an identical environment, it points towards a platform-specific challenge with Windows.
> 
> For now, it seems like the best workaround for utilizing multi-GPU capabilities might be to stick with Ubuntu for your training tasks. We'll continue to investigate the Windows-specific issues and aim to enhance support in future updates.
> 
> Thanks for your patience and for providing these insights! If you have any more questions or run into other issues, feel free to reach out. Happy training!

I set device='0,1', and then printed out the information of loading the model, and the following problems occurred:

DDP:  debug command C:\Users\Administrator\Documents\Projects\LTWY\Yolov8\.venv\Scripts\python.exe -m torch.distributed.run  --nproc_per_node 2 --master_port 53623  C:\Users\Administrator\AppData\Roaming\Ultralytics\DDP\_temp_w0k_hgaf2212817842960.py
[the 2024-05-31 16:43:35, 023] torch. Distributed. Elastic. Multiprocessing. Redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.

And then the program just keeps running, but nothing happens.
This seems to be a similar problem to the above, and I would like to ask whether there is a solution to my problem now.

**Comment by PiyushKamboj1503** [comment]
> > Hey @piyush-evigway,
> > 
> > Great to hear that multi-GPU training works well on Ubuntu! This indeed helps us rule out hardware issues. 🎉 Since the setup works on Ubuntu but not on Windows with an identical environment, it points towards a platform-specific challenge with Windows.
> > 
> > For now, it seems like the best workaround for utilizing multi-GPU capabilities might be to stick with Ubuntu for your training tasks. We'll continue to investigate the Windows-specific issues and aim to enhance support in future updates.
> > 
> > Thanks for your patience and for providing these insights! If you have any more questions or run into other issues, feel free to reach out. Happy training!
> 
> I set device='0,1', and then printed out the information of loading the model, and the following problems occurred:
> 
> DDP:  debug command C:\Users\Administrator\Documents\Projects\LTWY\Yolov8\.venv\Scripts\python.exe -m torch.distributed.run  --nproc_per_node 2 --master_port 53623  C:\Users\Administrator\AppData\Roaming\Ultralytics\DDP\_temp_w0k_hgaf2212817842960.py
> [the 2024-05-31 16:43:35, 023] torch. Distributed. Elastic. Multiprocessing. Redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
> 
> And then the program just keeps running, but nothing happens.
> This seems to be a similar problem to the above, and I would like to ask whether there is a solution to my problem now.

The problem is still there as per my latest testing. Kindly try using multi gpu training on linux
