### ISSUE TITLE
Custom YOLOv8 Activation Function From Python File

### ISSUE THREAD

**Issue by DevMSri** [ultralytics/ultralytics#8243]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

What if I wanted to use a custom activation function defined in a Python file, how would I modify the yolov8.yaml file such that this works? I have ensured my_yolov8.yaml file and my custom_activation_func.py files are in the same directory whilst a python file called custom_YOLO_act.py runs these two files. my_yolov8.yaml file looks like this: #`# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80  # number of classes
activation: Mish()  # Using custom Mish activation function
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]  # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024]  # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768]   # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512]   # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512]   # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 12

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 21 (P5/32-large)

  - [[15, 18, 21], 1, Detect, [nc]]  # Detect(P3, P4, P5), import torch
`, whilst my python file called mish.py looks like this: `import torch
import torch.nn as nn

class Mish(nn.Module):
    def __init__(self):
        super(Mish, self).__init__()

    def forward(self, x):
        return x * torch.tanh(torch.log(1 + torch.exp(x)))
`. And to run my custom yolov8.yaml file the custom_YOLO_act.py file looks like this: `import torch
import torch.nn as nn
from ultralytics import YOLO
from mish import Mish  # Import the Mish class from mish.py

# Load the YOLO model from YAML configuration and transfer weights
model = YOLO(r"/home/dev/Documents/Object detection/my_yolov8n.yaml").load('yolov8n.pt')

# Train the model for 5 epochs on the COCO128 dataset with image size 640
results = model.train(data='coco128.yaml', epochs=2, imgsz=640)

# Get the mean results which include precision and loss
mean_results = results.mean_results()

# Extract precision and loss
final_accuracy = mean_results[0]  # Precision
final_loss = mean_results[-1]     # Loss (assuming it's the last value)

# Display the final accuracy and loss
print("Final Training Accuracy:", final_accuracy)
print("Final Training Loss:", final_loss)
`. Please help.

### Additional

[Custom Activation Func.zip](https://github.com/ultralytics/ultralytics/files/14309465/Custom.Activation.Func.zip)

**Comment by glenn-jocher** [comment]
@DevMSri hello! To use a custom activation function defined in a Python file, you'll need to make sure that the function is accessible by the YOLO model during runtime. Here's a quick guide on how to do it:

1. Ensure your custom activation function, like `Mish`, is defined in a Python file that's accessible to your script.
2. Import your custom activation function into your main script where you're setting up the YOLO model.
3. In your YAML configuration file, specify the activation function by its name as a string, without parentheses. For example, use `activation: Mish` instead of `activation: Mish()`.

Here's a corrected snippet of your YAML file:

```yaml
# Parameters
nc: 80  # number of classes
activation: 'Mish'  # Custom Mish activation function as a string
```

And in your Python script, make sure to import the custom activation function:

```python
from custom_activation_func import Mish  # Ensure this matches your file and class name

# Rest of your script...
```

By following these steps, your YOLO model should be able to recognize and use the custom activation function during training. If you encounter any issues, feel free to reach out again. Good luck with your model training! 🚀

**Comment by DevMSri** [comment]
When I do that then I get the following error: Traceback (most recent call last):
  File "/home/dev/Documents/Object detection/customYOLOact.py", line 7, in <module>
    model = YOLO(r"/home/dev/Documents/Object detection/my_yolov8n.yaml").load('yolov8n.pt')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/anaconda3/lib/python3.11/site-packages/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/home/dev/anaconda3/lib/python3.11/site-packages/ultralytics/engine/model.py", line 132, in __init__
    self._new(model, task=task, verbose=verbose)
  File "/home/dev/anaconda3/lib/python3.11/site-packages/ultralytics/engine/model.py", line 197, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/anaconda3/lib/python3.11/site-packages/ultralytics/nn/tasks.py", line 281, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/anaconda3/lib/python3.11/site-packages/ultralytics/nn/tasks.py", line 818, in parse_model
    Conv.default_act = eval(act)  # redefine default activation, i.e. Conv.default_act = nn.SiLU()
                       ^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'NovelActivation' is not defined

**Comment by DevMSri** [comment]
I have attached my python files and custom yolov8.yaml files to this post.
[Custom Activation Function.zip](https://github.com/ultralytics/ultralytics/files/14314554/Custom.Activation.Function.zip)

**Comment by Burhan-Q** [comment]
@DevMSri I believe if you add this key-value pair to the model YAML file, it will enable that activation function. To use a custom activation function, you may either have to patch/override or modify the source code

```yaml

activation: nn.Mish()
```

You can see on this line it looks for the `activation` key in the YAML file:

https://github.com/ultralytics/ultralytics/blob/2f22ff4ae66e86c53def72d52eb2e61ec924172e/ultralytics/nn/tasks.py#L808

Then on this line,
https://github.com/ultralytics/ultralytics/blob/2f22ff4ae66e86c53def72d52eb2e61ec924172e/ultralytics/nn/tasks.py#L818
it will enable the function from the value
