### ISSUE TITLE
I have a .pt file for yolov8 trained with an image size of 1280, how do I convert it to 320?

### ISSUE THREAD

**Issue by shihgg** [ultralytics/ultralytics#8253]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a .pt file for yolov8 trained with an image size of 1280, how do I convert it to 320?

**Comment by Burhan-Q** [comment]
You can run inference at any size no matter what it was trained at.

```py
from ultralytics import YOLO

model = YOLO("path/to/weights.pt")

results = model.predict(source="path/to/image.png", imgsz=320)
```

**Comment by Burhan-Q** [comment]
If you _must_ save the model so that it defaults to this image size, you can use this
```py
from ultralytics import YOLO

model = YOLO("path/to/weights.pt")
model.ckpt["train_args"]["imgsz"] = 320
model.save("path/to/weights_320.pt")
```

**Comment by shihgg** [comment]
> You can run inference at any size no matter what it was trained at.
> 
> ```python
> from ultralytics import YOLO
> 
> model = YOLO("path/to/weights.pt")
> 
> results = model.predict(source="path/to/image.png", imgsz=320)
> ```

Thanks for your help!

**Comment by Burhan-Q** [comment]
Happy to help @shihgg!
