### ISSUE TITLE
Visualization arguments: Suggest adding color customization

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#8261]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

https://docs.ultralytics.com/modes/predict/#inference-arguments

label  boxes  mask
I want it all in red
I don't know how to adjust it

### Use case

`results[0].plot(colour=[0,0,255])`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@monkeycc thank you for the suggestion! Custom color customization for labels, boxes, and masks is a great idea. Currently, the `plot()` method doesn't support direct color customization through arguments. However, this is something we can consider for future updates. 

In the meantime, you can modify the source code where the plotting function is defined and set your desired color. For red, you would set the color parameter to `[0, 0, 255]` in BGR format. Here's a quick example of how you might change the color to red when plotting:

```python
# Assuming 'results' is your Results object from model prediction
for r in results:
    r.render(color=(0, 0, 255))  # Set color to red in BGR format
    img = r.imgs[0]  # Rendered image with predictions
    # Display or save 'img' as needed
```

Keep in mind that this change will apply globally to all labels, boxes, and masks. If you need more granular control, you'll need to dive deeper into the rendering code.

We appreciate your input and encourage you to keep an eye on our updates or consider contributing to the project with a PR! 😊🚀

**Comment by baxtrax** [comment]
@glenn-jocher I would be willing to implement this, feel like it would be a good step to dipping my toes into contributing to the repo. Looks like a pretty straightforward implementation! 

Figure it would be adding new parameters `box_color` and `font_color` to the `plot()` function of the `Results` class. These parameters would be a tuple of BGR format and conditionally passed into the `Annotater` object.

[Repo code reference](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/results.py#L281)
```python
color = colors(c,True) if box_color is None else box_color
annotator.box_label(box, label, color=color, rotated=is_obb)
```
[Repo code reference](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/results.py#L287)
```python
color = (255,255,255) if font_color is None else font_color
annotator.text([x, x], text, txt_color=color)
```

etc...

Let me know if you have any feedback or input. Otherwise, I feel fine taking this on and submitting a PR!

**Comment by glenn-jocher** [comment]
@baxtrax thank you for your suggestion regarding color customization for visualization in YOLOv8. Currently, the ability to customize colors for labels, boxes, and masks directly via the `plot()` method is not a built-in feature in the Ultralytics YOLO documentation.

However, you can achieve color customization by modifying the source code where the plotting is handled. The color is typically defined in BGR (Blue, Green, Red) format in OpenCV, which is used for visualization in YOLOv8. The color `[0, 0, 255]` corresponds to red.

Here's a general approach to customize the plotting color:

1. Locate the `plot()` method within the YOLOv8 source code. This is usually found in the file where results are processed and visualized (e.g., `results.py` or similar).

2. Identify where the colors are set for drawing the boxes, labels, and masks. It might look something like `color = (255, 0, 0)` for blue.

3. Replace the default color with your desired BGR values. For red, you would use `color = (0, 0, 255)`.

4. Save the changes and use the modified `plot()` method to visualize your results with the new color settings.

Please note that modifying the source code might affect future updates or maintenance of the YOLOv8 repository. It's a good practice to keep track of such changes or consider contributing to the repository if you believe this feature would be beneficial for others.

If you're not comfortable modifying the source code, another option is to post-process the images after they have been plotted by YOLOv8. You can use OpenCV to redraw the boxes, labels, and masks with your desired colors on the output images.

If you have further questions or need assistance with the code changes, feel free to ask, and I'll be glad to help.

**Comment by glenn-jocher** [comment]
@baxtrax That sounds like a fantastic contribution, and we'd be thrilled to have you dive into the codebase! 🎉 Your approach to adding `box_color` and `font_color` parameters to the `plot()` function is spot on. It's a user-friendly enhancement that many will find useful.

Your proposed code snippets look like they're on the right track. Just make sure to update the `Annotator` class as well to handle the new color parameters. Once you're ready, go ahead and submit a PR. We're here to support you through the process if you need any help.

Looking forward to seeing your PR, and welcome to the Ultralytics community! 🚀

**Comment by baxtrax** [comment]
Created PR, lemme me know how it looks!

**Comment by glenn-jocher** [comment]
@baxtrax thanks for submitting the PR! 🚀 We'll review it shortly and provide feedback or merge it if everything looks good. Great job on taking the initiative to contribute! If there are any changes needed, we'll guide you through them. Keep an eye on your PR for updates.
