### ISSUE TITLE
Can't use gpu accelleration

### ISSUE THREAD

**Issue by dvdcjw** [ultralytics/ultralytics#8263]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I can't use gpu accelleration, 
torch.cuda.is_available() says True,
and  model.device.type says CUDA, but in task manager, the python process just use one of my cpu cores to 100% and No gpu at all.

### Environment

certifi==2022.12.7
charset-normalizer==2.1.1
colorama==0.4.6
comtypes==1.3.0
contourpy==1.2.0
cycler==0.12.1
Cython==3.0.8
dxcam==0.0.5
filelock==3.9.0
fonttools==4.49.0
fsspec==2023.4.0
idna==3.4
Jinja2==3.1.2
kiwisolver==1.4.5
lapx==0.5.5
MarkupSafe==2.1.3
matplotlib==3.8.3
mpmath==1.3.0
networkx==3.2.1
numpy==1.26.3
opencv-python==4.9.0.80
packaging==23.2
pandas==2.2.0
pillow==10.2.0
psutil==5.9.8
py-cpuinfo==9.0.0
pyparsing==3.1.1
python-dateutil==2.8.2
pytz==2024.1
PyYAML==6.0.1
requests==2.28.1
scipy==1.12.0
seaborn==0.13.2
six==1.16.0
sympy==1.12
thop==0.1.1.post2209072238
torch==2.2.0+cu118
torchaudio==2.2.0+cu118
torchvision==0.17.0+cu118
tqdm==4.66.2
typing_extensions==4.8.0
tzdata==2024.1
ultralytics==8.1.14
urllib3==1.26.13

### Minimal Reproducible Example

import torch
print('CUDA:', torch.cuda.is_available())
torch.device('cuda')
from ultralytics import YOLO
model = YOLO('yolov8n.pt')
tart = time.perf_counter()
frame = cv2.cvtColor(raw_pic, cv2.COLOR_BGR2RGB)
results = model.predict(0, device=0)
annotated_frame = results[0].plot()
print('Yolo', time.perf_counter() - start)
print(model.device.type)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by dvdcjw** [comment]
I'm sure I've already set up cuda and cudnn 1.18 correctly, since the other projects use my gpu just fine.

**Comment by glenn-jocher** [comment]
@dvdcjw it seems like you've checked that CUDA is available and you're attempting to use the GPU for inference with YOLOv8. However, the GPU is not being utilized according to your task manager.

Here are a few things you can try to resolve the issue:

1. **Ensure CUDA device is set correctly**: When you create the `torch.device`, you should assign it to a variable and ensure that it's passed correctly to the model. For example:

```python
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)
```

2. **Explicitly set the device for prediction**: In your code snippet, you're passing `0` and `device=0` to `model.predict()`. Instead, try using the `device` variable you've created:

```python
results = model.predict(0, device=device)
```

3. **Check your PyTorch and CUDA versions**: Make sure that the installed versions of PyTorch and CUDA are compatible with your GPU. You can check the compatibility on the [PyTorch website](https://pytorch.org/get-started/previous-versions/).

4. **Update your NVIDIA drivers**: Outdated GPU drivers can sometimes cause issues with CUDA not being utilized properly. Make sure your NVIDIA drivers are up to date.

5. **Check for other processes**: Ensure that no other processes are occupying the GPU. You can check this with the `nvidia-smi` command in the terminal.

6. **Restart your system**: Sometimes, a simple restart can resolve issues with hardware not being recognized or used properly.

7. **Check your model's `.to(device)` call**: Ensure that the model and any tensors you're using are moved to the GPU. This is done with the `.to(device)` method, as shown in the first point.

8. **Check for errors in the output**: Sometimes, errors related to CUDA might not stop the execution but will print out warnings or errors. Check the console output for any such messages.

If you've tried all of the above and the issue persists, it could be a bug or a system-specific issue. In that case, you might want to open an issue on the Ultralytics YOLOv8 GitHub repository with detailed information about your system, GPU model, and the steps you've taken to debug the issue.

**Comment by glenn-jocher** [comment]
@dvdcjw hello! Thanks for reaching out and providing detailed information about your issue. It's great to hear that CUDA is available in your environment. Let's try to resolve the GPU utilization problem you're experiencing with YOLOv8.

Firstly, it seems there might be a small oversight in your code snippet. When you're setting the device to use CUDA, you should assign it to a variable and then pass that variable when calling `model.predict()`. Here's a corrected version of your code:

```python
import torch
from ultralytics import YOLO
import cv2
import time

print('CUDA:', torch.cuda.is_available())
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = YOLO('yolov8n.pt', device=device)

start = time.perf_counter()
frame = cv2.cvtColor(raw_pic, cv2.COLOR_BGR2RGB)
results = model.predict(frame)
annotated_frame = results[0].plot()
print('Yolo', time.perf_counter() - start)
print(model.device.type)
```

Please ensure that `raw_pic` is defined in your script and contains the image data you want to process.

If after this change your GPU is still not being utilized, it might be helpful to check if there are any other processes occupying the GPU. You can do this by running `nvidia-smi` in your command line.

If the issue persists, please feel free to share any additional details or error messages you might be encountering, and we'll be happy to help you further. 😊

**Comment by zyy-xy** [comment]
> @dvdcjw hello! Thanks for reaching out and providing detailed information about your issue. It's great to hear that CUDA is available in your environment. Let's try to resolve the GPU utilization problem you're experiencing with YOLOv8.
> 
> Firstly, it seems there might be a small oversight in your code snippet. When you're setting the device to use CUDA, you should assign it to a variable and then pass that variable when calling `model.predict()`. Here's a corrected version of your code:
> 
> ```python
> import torch
> from ultralytics import YOLO
> import cv2
> import time
> 
> print('CUDA:', torch.cuda.is_available())
> device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
> model = YOLO('yolov8n.pt', device=device)
> 
> start = time.perf_counter()
> frame = cv2.cvtColor(raw_pic, cv2.COLOR_BGR2RGB)
> results = model.predict(frame)
> annotated_frame = results[0].plot()
> print('Yolo', time.perf_counter() - start)
> print(model.device.type)
> ```
> 
> Please ensure that `raw_pic` is defined in your script and contains the image data you want to process.
> 
> If after this change your GPU is still not being utilized, it might be helpful to check if there are any other processes occupying the GPU. You can do this by running `nvidia-smi` in your command line.
> 
> If the issue persists, please feel free to share any additional details or error messages you might be encountering, and we'll be happy to help you further. 😊

Hello! Excuse me,
The code you supplied reported an error at 

model = YOLO('yolov8n.pt', device=device) 

TypeError: __init__() got an unexpected keyword argument 'device'

**Comment by zyy-xy** [comment]
> @glenn-jocher  hello! Thanks for reaching out and providing detailed information about your issue. It's great to hear that CUDA is available in your environment. Let's try to resolve the GPU utilization problem you're experiencing with YOLOv8.
> 
> Firstly, it seems there might be a small oversight in your code snippet. When you're setting the device to use CUDA, you should assign it to a variable and then pass that variable when calling `model.predict()`. Here's a corrected version of your code:
> 
> ```python
> import torch
> from ultralytics import YOLO
> import cv2
> import time
> 
> print('CUDA:', torch.cuda.is_available())
> device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
> model = YOLO('yolov8n.pt', device=device)
> 
> start = time.perf_counter()
> frame = cv2.cvtColor(raw_pic, cv2.COLOR_BGR2RGB)
> results = model.predict(frame)
> annotated_frame = results[0].plot()
> print('Yolo', time.perf_counter() - start)
> print(model.device.type)
> ```
> 
> Please ensure that `raw_pic` is defined in your script and contains the image data you want to process.
> 
> If after this change your GPU is still not being utilized, it might be helpful to check if there are any other processes occupying the GPU. You can do this by running `nvidia-smi` in your command line.
> 
> If the issue persists, please feel free to share any additional details or error messages you might be encountering, and we'll be happy to help you further. 😊

**Comment by zyy-xy** [comment]
> @glenn-jocher  hello! Thanks for reaching out and providing detailed information about your issue. It's great to hear that CUDA is available in your environment. Let's try to resolve the GPU utilization problem you're experiencing with YOLOv8.
> 
> Firstly, it seems there might be a small oversight in your code snippet. When you're setting the device to use CUDA, you should assign it to a variable and then pass that variable when calling `model.predict()`. Here's a corrected version of your code:
> 
> ```python
> import torch
> from ultralytics import YOLO
> import cv2
> import time
> 
> print('CUDA:', torch.cuda.is_available())
> device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
> model = YOLO('yolov8n.pt', device=device)
> 
> start = time.perf_counter()
> frame = cv2.cvtColor(raw_pic, cv2.COLOR_BGR2RGB)
> results = model.predict(frame)
> annotated_frame = results[0].plot()
> print('Yolo', time.perf_counter() - start)
> print(model.device.type)
> ```
> 
> Please ensure that `raw_pic` is defined in your script and contains the image data you want to process.
> 
> If after this change your GPU is still not being utilized, it might be helpful to check if there are any other processes occupying the GPU. You can do this by running `nvidia-smi` in your command line.
> 
> If the issue persists, please feel free to share any additional details or error messages you might be encountering, and we'll be happy to help you further. 😊

---
Hello! Excuse me,
The code you supplied reported an error at

model = YOLO('yolov8n.pt', device=device)

TypeError: init() got an unexpected keyword argument 'device'

**Comment by glenn-jocher** [comment]
@zyy-xy hi there! Thanks for the quick follow-up. My apologies for the confusion earlier. 🙏 You're right; the `YOLO` class initialization doesn't directly accept a `device` argument. Instead, you should set the device after initializing the model like so:

```python
import torch
from ultralytics import YOLO

# Ensure CUDA is available
print('CUDA:', torch.cuda.is_available())

# Load the model
model = YOLO('yolov8n.pt')

# Set the device
device = 'cuda' if torch.cuda.is_available() else 'cpu'
model.to(device)
```

This should correctly allocate your model to the GPU. If there's anything else you need, feel free to ask!
