### ISSUE TITLE
How to obtain the count value of YOLOv8 tracking?

### ISSUE THREAD

**Issue by HugoSun** [ultralytics/ultralytics#8275]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to know how to obtain the in /out counts values and return them.

**Comment by glenn-jocher** [comment]
@HugoSun to obtain the in/out counts of objects when using YOLOv8 tracking, you can analyze the `id` attribute of the `Boxes` object in the tracking results. Here's a simple example of how you might implement a counter:

```python
from ultralytics import YOLO

# Initialize the model
model = YOLO('yolov8n.pt')

# Initialize a dictionary to hold counts for each unique ID
counts = {}

# Process video frames (pseudo-code, replace with your video processing loop)
for frame in video_frames:
    # Run tracking
    results = model.track(frame, persist=True)
    
    # Update counts
    for track_id in results.boxes.id:
        counts[track_id] = counts.get(track_id, 0) + 1

# At this point, 'counts' holds the total count of each unique object ID
```

This code will give you a running total of how many times each unique object ID has been detected. To get in/out counts, you would need to define zones or conditions that determine when an object is considered "in" or "out" and update the counts accordingly. 📊

**Comment by glenn-jocher** [comment]
@HugoSun to obtain the count of objects tracked by YOLOv8, you can access the `id` attribute of the `Boxes` object after performing tracking. Here's a simple example to get you started:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('path/to/your/model.pt')

# Perform tracking on your source
results = model.track(source='path/to/your/video.mp4')

# Get unique track IDs to count distinct objects
unique_ids = set()
for frame_results in results:
    track_ids = frame_results.boxes.id.cpu().tolist()
    unique_ids.update(track_ids)

# The count of unique objects tracked
object_count = len(unique_ids)
print(f'Unique objects tracked: {object_count}')
```

This will give you the total count of unique objects tracked throughout the video. If you're looking to count objects entering or exiting a scene, you'll need to define the entry/exit zones and increment counts based on object trajectories crossing these zones. 😊👍
