### ISSUE TITLE
Why is torchscript export is providing output shape [1, 84, 8400] ?

### ISSUE THREAD

**Issue by boussad83** [ultralytics/ultralytics#828]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The model is supposed to output for one image a shape [1, 1 + 4 + C, 8400], C being the number of classes but it is not the case with a torchscript model obtained using the export function. It provides [1, 84, 8400] for coco with 80 classes. Any idea about this problem ?

**Comment by JustasBart** [comment]
Hi @boussad83 yolov8 doesn't have the Confidence dimension. It has an output of:

`(batchSize, 84,  8400) (Num classes + box[x,y,w,h])`

I have a C++ based example [here](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX.git) it might be useful for you to see the differences in running Inference for **yolov5** and **yolov8**.

Good luck! :rocket:

**Comment by boussad83** [comment]
@JustasBart , this is indeed what I thought (confidence not considered anymore) but I was not sure since a quick look at the code shows the term "confidence" is still there. I wanted to be sure that it was not a bug somewhere. Thanks for the reply!

**Comment by JustasBart** [comment]
@boussad83 yolov8 checks only the confidence of a particular class belonging in a particular possible detection (But considers every possible detection) and if that class confidence is over the threshold will it actually consider that class as a candidate to be later processed by NMS.
Whereas yolov5 checks the confidence of a detection being there in the first place and then works out if also there is a particular class that is over the threshold to belong to that detection before again proceeding to do NMS.

Good luck! :rocket:

**Comment by boussad83** [comment]
@JustasBart I have checked that and indeed, Yolov8 does not have a confidence score at the output. The confidence score is simply the max proba among the classes. Thanks!
