### ISSUE TITLE
How to save the timestamp at which the YOLOv8 detects an object.

### ISSUE THREAD

**Issue by dataScience-noob** [ultralytics/ultralytics#8284]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello all, 
I am new to YOLOv8 and to object detection in general. I am trying to use YOLOv8 as part of a project. For this purpose, I want to get the timestamp at which YOLOv8 detects an object during live inference. It would be great if its possible to save the timestamp and the name/class of the object detected to a .csv file. 

If not, saving it to a .txt file would also be helpful. I passed the 'save_txt=True'  parameter to save a .txt file each time an object is detected, but this does not contain information about time. It only contains the object class and location information of the bounding box. How can I add a timestamp to this file?

Any advice would be really helpful. Thanks in advance!Q

**Comment by glenn-jocher** [comment]
@dataScience-noob hello! 👋

To save the timestamp along with the detected object's class, you can modify the code where detections are processed. Here's a simple example using Python:

```python
from datetime import datetime
import csv

# Assuming 'results' is the output from your YOLOv8 model
for result in results:
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    class_name = result.names[result.cls]  # Get the class name of the detected object
    with open('detections.csv', 'a', newline='') as file:
        writer = csv.writer(file)
        writer.writerow([timestamp, class_name])

# This will append a new row with the current timestamp and class name to 'detections.csv'
```

This code snippet uses the `datetime` module to get the current timestamp and writes it to a CSV file along with the class name of the detected object. Make sure to include this snippet where the detections are being processed in your live inference loop.

Happy coding, and best of luck with your project! 😊 If you have any more questions, feel free to ask.

**Comment by glenn-jocher** [comment]
@dataScience-noob hello! 👋 To save the timestamp along with the detected object's class to a CSV file during live inference, you can modify the code where detections are processed. Here's a small example using Python:

```python
import csv
import time
from ultralytics import YOLO

# Initialize YOLOv8 model
model = YOLO('yolov8n.pt')

# Define source, e.g., '0' for webcam
source = '0'

# Run inference
for frame, results in model(source):
    # Get current timestamp
    timestamp = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime())

    # Process results
    for result in results:
        for c in result.boxes.cls:
            # Get class name
            class_name = model.names[int(c)]
            # Save to CSV
            with open('detections.csv', 'a', newline='') as file:
                writer = csv.writer(file)
                writer.writerow([timestamp, class_name])

# Note: This is a simplified example. You may need to adapt it to your specific use case.
```

This script will append the timestamp and class name of each detected object to a CSV file called `detections.csv`. Make sure to handle the file opening and closing appropriately to avoid data loss, especially when working with live streams. Happy coding! 😊

**Comment by dataScience-noob** [comment]
@glenn-jocher Thank you so much for your help. The explanation was very precise :)

This code worked for me:
"from datetime import datetime
import csv

# Assuming 'results' is the output from your YOLOv8 model
for result in results:
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    class_name = result.names[result.cls]  # Get the class name of the detected object
    with open('detections.csv', 'a', newline='') as file:
        writer = csv.writer(file)
        writer.writerow([timestamp, class_name])'"

I now have a CSV file with the required information. However, both class_name and timestamp are now saved in the same column (column A), separated by a coma. I tried saving it to two separate columns, but couldn´t achieve it. Could you maybe help in saving the class_name to column A and timestamp to column B?

Thanks in advance!

**Comment by glenn-jocher** [comment]
@dataScience-noob hey there! 😄 I'm glad to hear the code is working well for you.

To save the `class_name` and `timestamp` in separate columns, you just need to ensure they are passed as separate elements of a list to the `writerow()` method. Here's the corrected snippet:

```python
from datetime import datetime
import csv

for result in results:
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    class_name = result.names[result.cls]  # Get the class name of the detected object
    with open('detections.csv', 'a', newline='') as file:
        writer = csv.writer(file)
        writer.writerow([class_name, timestamp])  # Pass class_name and timestamp as separate list elements
```

This should place the `class_name` in column A and the `timestamp` in column B of your CSV file. Happy coding! 🚀

**Comment by dataScience-noob** [comment]
Unfortunately, it is the same code as above and therefore it didn't make a difference :)

**Comment by dataScience-noob** [comment]
Hey @glenn-jocher ! This actually worked for me now. The problem is that it's still in a single column when I open it in my laptop. But when I opened the same CSV file in another laptop, surprisingly it worked! So, it seems it is an issue with the 'regional settings' in my laptop (the period ('.') and comma (',') are interpreted differently!). I will figure it out later. 

So, your solution worked pretty well. Thank you for the support!
