### ISSUE TITLE
How to calculate the area value of the segmented object

### ISSUE THREAD

**Issue by dyhisbig** [ultralytics/ultralytics#8286]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to calculate the area value of the segmented object

**Comment by Kayzwer** [comment]
```
for mask in result.masks.data:
    mask.sum() # area in pixel
```

**Comment by glenn-jocher** [comment]
@Kayzwer to calculate the area of a segmented object using a YOLOv8 model, you can follow these steps:

1. **Perform Segmentation**: Run the YOLOv8 model with segmentation capabilities (such as YOLOv8n-seg) on your image to obtain the segmentation masks for the objects.

2. **Extract Masks**: The segmentation output will include masks for each detected object. These masks are typically binary images where the pixels belonging to the object are set to 1 (or 255 for an 8-bit image), and the background pixels are set to 0.

3. **Calculate Area**: The area of the segmented object can be calculated by summing the values of the pixels in the mask. Since the mask is binary, this sum will give you the total number of pixels that belong to the object, which is equivalent to the area of the object in pixel units.

Here's an example of how you might do this in Python using the Ultralytics YOLOv8 API:

```python
from ultralytics import YOLO

# Load a pretrained segmentation model
model = YOLO('yolov8n-seg.pt')

# Run inference on an image
results = model('path/to/image.jpg')

# Process results
for result in results:
    masks = result.masks  # Masks object for segmentation masks outputs
    for i, mask in enumerate(masks):
        # Calculate the area of each mask (segmented object)
        area = mask.sum().item()  # Sum of all pixels in the mask
        print(f"Object {i} area (in pixels): {area}")
```

In this code snippet, `masks` is a `Masks` object containing the segmentation masks for each detected object. The `sum()` method is called on each mask to calculate the area, and `item()` is used to get the value as a Python scalar.

Keep in mind that the area calculated here is in pixel units. If you need the area in physical units (such as square centimeters), you'll need to know the scaling factor, which depends on the resolution of the image and the physical size of the area represented by each pixel.

**Comment by dyhisbig** [comment]
> @Kayzwer to calculate the area of a segmented object using a YOLOv8 model, you can follow these steps:@Kayzwer使用YOLOv 8模型计算分割对象的面积，可以按照以下步骤操作：
> 
>     1. **Perform Segmentation**: Run the YOLOv8 model with segmentation capabilities (such as YOLOv8n-seg) on your image to obtain the segmentation masks for the objects.执行分割：在您的图像上运行具有分割功能（如YOLOv 8 n-seg）的YOLOv 8模型，以获取对象的分割蒙版。
> 
>     2. **Extract Masks**: The segmentation output will include masks for each detected object. These masks are typically binary images where the pixels belonging to the object are set to 1 (or 255 for an 8-bit image), and the background pixels are set to 0.提取遮罩：分割输出将包括每个检测到的对象的遮罩。这些遮罩通常是二进制图像，其中属于对象的像素设置为1（或对于8位图像为255），背景像素设置为0。
> 
>     3. **Calculate Area**: The area of the segmented object can be calculated by summing the values of the pixels in the mask. Since the mask is binary, this sum will give you the total number of pixels that belong to the object, which is equivalent to the area of the object in pixel units.计算面积：分割对象的面积可以通过对蒙版中的像素值求和来计算。由于遮罩是二进制的，因此此和将给予您属于对象的像素总数，它相当于以像素为单位的对象面积。
> 
> 
> Here's an example of how you might do this in Python using the Ultralytics YOLOv8 API:下面是一个如何在Python中使用Ultralytics YOLOv8 API执行此操作的示例：
> 
> ```python
> from ultralytics import YOLO
> 
> # Load a pretrained segmentation model
> model = YOLO('yolov8n-seg.pt')
> 
> # Run inference on an image
> results = model('path/to/image.jpg')
> 
> # Process results
> for result in results:
>     masks = result.masks  # Masks object for segmentation masks outputs
>     for i, mask in enumerate(masks):
>         # Calculate the area of each mask (segmented object)
>         area = mask.sum().item()  # Sum of all pixels in the mask
>         print(f"Object {i} area (in pixels): {area}")
> ```
> 
> In this code snippet, `masks` is a `Masks` object containing the segmentation masks for each detected object. The `sum()` method is called on each mask to calculate the area, and `item()` is used to get the value as a Python scalar.在此代码片段中，`masks`是一个`Masks`对象，包含每个检测到的对象的分割掩码。在每个掩码上调用`sum()`方法来计算面积，而`item()`用于获取Python标量形式的值。
> 
> Keep in mind that the area calculated here is in pixel units. If you need the area in physical units (such as square centimeters), you'll need to know the scaling factor, which depends on the resolution of the image and the physical size of the area represented by each pixel.请记住，这里计算的面积是以像素为单位的。如果需要以物理单位（如平方厘米）表示的面积，则需要知道缩放因子，该因子取决于图像的分辨率和每个像素表示的面积的物理大小。

Traceback (most recent call last):
  File "C:\dyh\ultralytics\分割测试.py", line 14, in <module>
    area = mask.sum().item()  # Sum of all pixels in the mask
  File "C:\dyh\ultralytics\ultralytics\utils\__init__.py", line 156, in __getattr__
    raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
AttributeError: 'Masks' object has no attribute 'sum'. See valid attributes below.

    A class for storing and manipulating detection masks.

    Attributes:
        xy (list): A list of segments in pixel coordinates.
        xyn (list): A list of normalized segments.

    Methods:
        cpu(): Returns the masks tensor on CPU memory.
        numpy(): Returns the masks tensor as a numpy array.
        cuda(): Returns the masks tensor on GPU memory.
        to(device, dtype): Returns the masks tensor with the specified device and dtype.
    

Process finished with exit code 1

**Comment by dyhisbig** [comment]
> @Kayzwer to calculate the area of a segmented object using a YOLOv8 model, you can follow these steps:@Kayzwer使用YOLOv 8模型计算分割对象的面积，可以按照以下步骤操作：
> 
>     1. **Perform Segmentation**: Run the YOLOv8 model with segmentation capabilities (such as YOLOv8n-seg) on your image to obtain the segmentation masks for the objects.执行分割：在您的图像上运行具有分割功能（如YOLOv 8 n-seg）的YOLOv 8模型，以获取对象的分割蒙版。
> 
>     2. **Extract Masks**: The segmentation output will include masks for each detected object. These masks are typically binary images where the pixels belonging to the object are set to 1 (or 255 for an 8-bit image), and the background pixels are set to 0.提取遮罩：分割输出将包括每个检测到的对象的遮罩。这些遮罩通常是二进制图像，其中属于对象的像素设置为1（或对于8位图像为255），背景像素设置为0。
> 
>     3. **Calculate Area**: The area of the segmented object can be calculated by summing the values of the pixels in the mask. Since the mask is binary, this sum will give you the total number of pixels that belong to the object, which is equivalent to the area of the object in pixel units.计算面积：分割对象的面积可以通过对蒙版中的像素值求和来计算。由于遮罩是二进制的，因此此和将给予您属于对象的像素总数，它相当于以像素为单位的对象面积。
> 
> 
> Here's an example of how you might do this in Python using the Ultralytics YOLOv8 API:下面是一个如何在Python中使用Ultralytics YOLOv8 API执行此操作的示例：
> 
> ```python
> from ultralytics import YOLO
> 
> # Load a pretrained segmentation model
> model = YOLO('yolov8n-seg.pt')
> 
> # Run inference on an image
> results = model('path/to/image.jpg')
> 
> # Process results
> for result in results:
>     masks = result.masks  # Masks object for segmentation masks outputs
>     for i, mask in enumerate(masks):
>         # Calculate the area of each mask (segmented object)
>         area = mask.sum().item()  # Sum of all pixels in the mask
>         print(f"Object {i} area (in pixels): {area}")
> ```
> 
> In this code snippet, `masks` is a `Masks` object containing the segmentation masks for each detected object. The `sum()` method is called on each mask to calculate the area, and `item()` is used to get the value as a Python scalar.在此代码片段中，`masks`是一个`Masks`对象，包含每个检测到的对象的分割掩码。在每个掩码上调用`sum()`方法来计算面积，而`item()`用于获取Python标量形式的值。
> 
> Keep in mind that the area calculated here is in pixel units. If you need the area in physical units (such as square centimeters), you'll need to know the scaling factor, which depends on the resolution of the image and the physical size of the area represented by each pixel.请记住，这里计算的面积是以像素为单位的。如果需要以物理单位（如平方厘米）表示的面积，则需要知道缩放因子，该因子取决于图像的分辨率和每个像素表示的面积的物理大小。

This method won't work

**Comment by Kayzwer** [comment]
> > @Kayzwer to calculate the area of a segmented object using a YOLOv8 model, you can follow these steps:@Kayzwer使用YOLOv 8模型计算分割对象的面积，可以按照以下步骤操作：
> > 
> >     1. **Perform Segmentation**: Run the YOLOv8 model with segmentation capabilities (such as YOLOv8n-seg) on your image to obtain the segmentation masks for the objects.执行分割：在您的图像上运行具有分割功能（如YOLOv 8 n-seg）的YOLOv 8模型，以获取对象的分割蒙版。
> > 
> >     2. **Extract Masks**: The segmentation output will include masks for each detected object. These masks are typically binary images where the pixels belonging to the object are set to 1 (or 255 for an 8-bit image), and the background pixels are set to 0.提取遮罩：分割输出将包括每个检测到的对象的遮罩。这些遮罩通常是二进制图像，其中属于对象的像素设置为1（或对于8位图像为255），背景像素设置为0。
> > 
> >     3. **Calculate Area**: The area of the segmented object can be calculated by summing the values of the pixels in the mask. Since the mask is binary, this sum will give you the total number of pixels that belong to the object, which is equivalent to the area of the object in pixel units.计算面积：分割对象的面积可以通过对蒙版中的像素值求和来计算。由于遮罩是二进制的，因此此和将给予您属于对象的像素总数，它相当于以像素为单位的对象面积。
> > 
> > 
> > Here's an example of how you might do this in Python using the Ultralytics YOLOv8 API:下面是一个如何在Python中使用Ultralytics YOLOv8 API执行此操作的示例：
> > 
> > ```python
> > from ultralytics import YOLO
> > 
> > # Load a pretrained segmentation model
> > model = YOLO('yolov8n-seg.pt')
> > 
> > # Run inference on an image
> > results = model('path/to/image.jpg')
> > 
> > # Process results
> > for result in results:
> >     masks = result.masks  # Masks object for segmentation masks outputs
> >     for i, mask in enumerate(masks):
> >         # Calculate the area of each mask (segmented object)
> >         area = mask.sum().item()  # Sum of all pixels in the mask
> >         print(f"Object {i} area (in pixels): {area}")
> > ```
> > 
> > In this code snippet, `masks` is a `Masks` object containing the segmentation masks for each detected object. The `sum()` method is called on each mask to calculate the area, and `item()` is used to get the value as a Python scalar.在此代码片段中，`masks`是一个`Masks`对象，包含每个检测到的对象的分割掩码。在每个掩码上调用`sum()`方法来计算面积，而`item()`用于获取Python标量形式的值。
> > 
> > Keep in mind that the area calculated here is in pixel units. If you need the area in physical units (such as square centimeters), you'll need to know the scaling factor, which depends on the resolution of the image and the physical size of the area represented by each pixel.请记住，这里计算的面积是以像素为单位的。如果需要以物理单位（如平方厘米）表示的面积，则需要知道缩放因子，该因子取决于图像的分辨率和每个像素表示的面积的物理大小。
> 
> This method won't work
> 

what kind of unit do you want?

**Comment by dyhisbig** [comment]
> > > @Kayzwer to calculate the area of a segmented object using a YOLOv8 model, you can follow these steps:@Kayzwer使用YOLOv 8模型计算分割对象的面积，可以按照以下步骤操作：
> > > ```
> > > 1. **Perform Segmentation**: Run the YOLOv8 model with segmentation capabilities (such as YOLOv8n-seg) on your image to obtain the segmentation masks for the objects.执行分割：在您的图像上运行具有分割功能（如YOLOv 8 n-seg）的YOLOv 8模型，以获取对象的分割蒙版。
> > > 
> > > 2. **Extract Masks**: The segmentation output will include masks for each detected object. These masks are typically binary images where the pixels belonging to the object are set to 1 (or 255 for an 8-bit image), and the background pixels are set to 0.提取遮罩：分割输出将包括每个检测到的对象的遮罩。这些遮罩通常是二进制图像，其中属于对象的像素设置为1（或对于8位图像为255），背景像素设置为0。
> > > 
> > > 3. **Calculate Area**: The area of the segmented object can be calculated by summing the values of the pixels in the mask. Since the mask is binary, this sum will give you the total number of pixels that belong to the object, which is equivalent to the area of the object in pixel units.计算面积：分割对象的面积可以通过对蒙版中的像素值求和来计算。由于遮罩是二进制的，因此此和将给予您属于对象的像素总数，它相当于以像素为单位的对象面积。
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Here's an example of how you might do this in Python using the Ultralytics YOLOv8 API:下面是一个如何在Python中使用Ultralytics YOLOv8 API执行此操作的示例：
> > > ```python
> > > from ultralytics import YOLO
> > > 
> > > # Load a pretrained segmentation model
> > > model = YOLO('yolov8n-seg.pt')
> > > 
> > > # Run inference on an image
> > > results = model('path/to/image.jpg')
> > > 
> > > # Process results
> > > for result in results:
> > >     masks = result.masks  # Masks object for segmentation masks outputs
> > >     for i, mask in enumerate(masks):
> > >         # Calculate the area of each mask (segmented object)
> > >         area = mask.sum().item()  # Sum of all pixels in the mask
> > >         print(f"Object {i} area (in pixels): {area}")
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > In this code snippet, `masks` is a `Masks` object containing the segmentation masks for each detected object. The `sum()` method is called on each mask to calculate the area, and `item()` is used to get the value as a Python scalar.在此代码片段中，`masks`是一个`Masks`对象，包含每个检测到的对象的分割掩码。在每个掩码上调用`sum()`方法来计算面积，而`item()`用于获取Python标量形式的值。
> > > Keep in mind that the area calculated here is in pixel units. If you need the area in physical units (such as square centimeters), you'll need to know the scaling factor, which depends on the resolution of the image and the physical size of the area represented by each pixel.请记住，这里计算的面积是以像素为单位的。如果需要以物理单位（如平方厘米）表示的面积，则需要知道缩放因子，该因子取决于图像的分辨率和每个像素表示的面积的物理大小。
> > 
> > 
> > This method won't work
> 
> what kind of unit do you want?

I want to get the pixel unit, get the pixel value area of the split result, thank you very much

**Comment by Kayzwer** [comment]
> *Perform

the code does exactly what you want, since 1 represents that the object appears in that pixel, therefore the sum of the mask is the total area of the object

**Comment by dyhisbig** [comment]
I understand what you said. I would like to ask how to calculate the size of mask specifically, such as counting the number of pixels, so as to obtain the pixel area of the target.  thank you very much

**Comment by Kayzwer** [comment]
@dyhisbig here is a simple example
```
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 1 1 0 0 0 0 0
0 0 1 1 0 0 0 0
0 0 1 1 0 0 0 0
0 1 1 0 0 0 0 0
0 0 0 0 0 0 0 0
```
this is a 8x8 image, and the mask is this tensor, and are area of this mask of the obj is 8.

**Comment by ana111todorova** [comment]
Dear @glenn-jocher, @Kayzwer, @dyhisbig 

This is the code that I am running, the exact one as send before:

from ultralytics import YOLO
import cv2

# Load a pretrained segmentation model


img = cv2.imread("dog.jpg")

# Run inference on an image
model = YOLO('yolov8n-seg.pt')
results = model(img)

# Process results
for result in results:
    masks = result.masks  # Masks object for segmentation masks outputs
    for i, mask in enumerate(masks):
        # Calculate the area of each mask (segmented object)
        area = mask.sum().item()  # Sum of all pixels in the mask
        print(f"Object {i} area (in pixels): {area}")

cv2.imshow("mask", masks)
cv2.waitKey(0)
----------------------------------------------------------------------------------------------------------------------------------
**But I get this error:**

0: 640x608 1 dog, 141.3ms
Speed: 2.0ms preprocess, 141.3ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 608)
Traceback (most recent call last):
  File "c:\Users\z5493030\OneDrive - UNSW\Desktop\YOLO\try.py", line 18, in <module>
    **area = mask.sum().item()  # Sum of all pixels in the mask**
           ^^^^^^^^
  File "C:\Users\z5493030\OneDrive - UNSW\Desktop\YOLO\venv\Lib\site-packages\ultralytics\utils\__init__.py", line 156, in __getattr__
    raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
**AttributeError: 'Masks' object has no attribute 'sum'. See valid attributes below.**

    A class for storing and manipulating detection masks.

    Attributes:
        xy (list): A list of segments in pixel coordinates.
        xyn (list): A list of normalized segments.

    Methods:
        cpu(): Returns the masks tensor on CPU memory.
        numpy(): Returns the masks tensor as a numpy array.
        cuda(): Returns the masks tensor on GPU memory.
        to(device, dtype): Returns the masks tensor with the specified device and dtype.



        
Have you sorted this error, since apparently some has sent it before?
Thank tou

**Comment by glenn-jocher** [comment]
@ana111todorova hey there! It looks like you encountered an error because the `Masks` object doesn't directly support the `sum()` method as used in your code. To calculate the area, you first need to convert the mask to a format where `sum()` can be applied, such as a numpy array. Here's a quick fix to your code:

```python
from ultralytics import YOLO
import cv2
import numpy as np

# Load a pretrained segmentation model
model = YOLO('yolov8n-seg.pt')

# Run inference on an image
img = cv2.imread("dog.jpg")
results = model(img)

# Process results
for result in results:
    masks = result.masks.numpy()  # Convert masks to numpy array for processing
    for i, mask in enumerate(masks):
        # Calculate the area of each mask (segmented object)
        area = np.sum(mask)  # Now sum() will work as expected
        print(f"Object {i} area (in pixels): {area}")
```

This minor modification converts the masks to a numpy array, making it compatible with the `sum()` function. Hope this helps! If you have any more questions, feel free to ask. 😊

**Comment by ana111todorova** [comment]
@glenn-jocher, thank you for your reply, however when I run the code this is the error that I get now :

```
line 17, in <module>
    area = np.sum(mask)  # Now sum() will work as expected
           ^^^^^^^^^^^^
  File "C:\Users\z5493030\OneDrive - UNSW\Desktop\YOLO\venv\Lib\site-packages\numpy\core\fromnumeric.py", line 2313, in sum
    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\z5493030\OneDrive - UNSW\Desktop\YOLO\venv\Lib\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 32.

```

Also I ran it to see the type of the masks, and even after # Convert masks to numpy array for processing they are returned as <class 'ultralytics.engine.results.Masks'>, not numpy array !!
```
for result in results:
    masks = result.masks.numpy()  
    print(f"type : {type(masks)}")
    
Returns : **type : <class 'ultralytics.engine.results.Masks'>** 
```

Waiting for your solution. 
Thank you

**Comment by ana111todorova** [comment]
@glenn-jocher, This is how I managed to print the pixels (code bellow), However on the terminal as output is  displayed like there are many object detected (with their pixels) when in reality the only detection there is is a dog. 
![dog2](https://github.com/ultralytics/ultralytics/assets/121057630/b35b1027-99b5-4677-b7ef-24c9743e75cc)
Why that happens and how to solve it?

```
from ultralytics import YOLO
import cv2
import numpy as np

# Load a pretrained segmentation model
model = YOLO('yolov8n-seg.pt')

# Run inference on an image
img = cv2.imread("dog2.jpg")
results = model(img)

# Process results
for idx, result in enumerate(results):
    masks = result.masks.xy[0] # Convert masks to numpy array for processing
    for i, mask in enumerate(masks):
        # Calculate the area of each mask (segmented object)
        area = np.sum(mask)  
        print(f"Object {i} area (in pixels): {area}")
        
    total_area = sum(np.sum(mask) for mask in masks)
    print(f"Object area (in pixels): {total_area}")
```
```
Output : 
.
.
.
Object 308 area (in pixels): 180.09373474121094
Object 309 area (in pixels): 179.15623474121094
Object 310 area (in pixels): 178.21873474121094
Object 311 area (in pixels): 177.28123474121094
Object 312 area (in pixels): 176.81248474121094
Object 313 area (in pixels): 175.87498474121094
Object 314 area (in pixels): 174.46873474121094
Object 315 area (in pixels): 173.53123474121094
Object area (in pixels): 80116.02770996094
```

**Comment by glenn-jocher** [comment]
@ana111todorova hi there! It looks like your code might be iterating over the individual segments or polygons that make up the segmentation masks for each detected object, rather than the objects themselves. This could be why you're seeing a larger number of "objects" than expected. 

To focus only on distinct object detections, you should ensure you're iterating over each detected object and its corresponding mask once. Try this adjustment:

```python
# Assuming 'masks' are numpy arrays representing segmented objects
for idx, result in enumerate(results):
    mask = result.masks.numpy()  # Convert masks to numpy array
    if mask.any():  # Check if there is at least one mask
        area = np.sum(mask)  # Calculate the total area
        print(f"Object {idx} area (in pixels): {area}")
```

This code snippet considers each detection result as a unique object and calculates its area. If you're still seeing many outputs for a single dog detection, it might be worth verifying the segmentation mask visualization to ensure that the mask correlates correctly with the detected object.

Hope this helps clear things up! If you have more questions or need further clarification, don't hesitate to ask. 😊

**Comment by ana111todorova** [comment]
@glenn-jocher, thank you for your assistance, but when I execute that, following error pops up :
```
 area = np.sum(mask)  # Now sum() will work as expected
           ^^^^^^^^^^^^
  File "C:\Users\z5493030\OneDrive - UNSW\Desktop\YOLO\venv\Lib\site-packages\numpy\core\fromnumeric.py", line 2313, in sum
    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\z5493030\OneDrive - UNSW\Desktop\YOLO\venv\Lib\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 32.
```
That's why I have modified the code and it is executing, but the masks don't make logical sense. :

```
from ultralytics import YOLO
import cv2
import numpy as np

# Load a pretrained segmentation model
model = YOLO('yolov8n-seg.pt')

# Run inference on an image
img = cv2.imread("2dogs.jpeg")
results = model(img)

Pixel_to_cm = 80                       #80 pixels are 1cm (assumption, needs to be calibrated in real time) 
Pixel_to_square_cm = 80*80



# Assuming 'masks' are numpy arrays representing segmented objects
for idx, result in enumerate(results):
    mask = result.masks.xy[0]  # Convert masks to numpy array
    if mask.any():  # Check if there is at least one mask
        area = np.sum(mask)  # Calculate the total area
        print(f"Object {idx} area (in pixels): {area}")
```

**Comment by ana111todorova** [comment]
@glenn-jocher Thank you, the code finally works properly :

```
from ultralytics import YOLO
import cv2
import numpy as np

Pixel_to_cm = 25                       #xx pixels are 1cm (assumption, needs to be calibrated in real time) 
Pixel_to_square_cm = 25*25
# Load a pretrained segmentation model
model = YOLO('yolov8n-seg.pt')

# Run inference on an image
img = cv2.imread("4.png")
H, W, _ = img.shape
results = model(img)


for result in results:
    for j, mask in enumerate(result.masks.data):
        mask = mask.numpy() 
        mask_output = mask *255

        mask = cv2.resize(mask, (W, H))

        area = np.sum(mask)
        print(f"Object {j} area (in pixels): {area}")
        
        total_area_cm = round(area / Pixel_to_square_cm, 0)
        print(f"Object area (in cm2): {total_area_cm}")
        
        cv2.imwrite('./output .png', mask_output)
```

Thank you, all the best :D

**Comment by glenn-jocher** [comment]
@ana111todorova That's great to hear! 😊 I'm glad the code is working well for you now. If you have any more questions or need further tweaks, feel free to reach out. All the best with your project! 🚀
