### ISSUE TITLE
Does the image size reduction to default 640 value affects the labels generated for higher dimensional image in the training?

### ISSUE THREAD

**Issue by naveenvj25** [ultralytics/ultralytics#8295]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

@glenn-jocher Hi ..! I have done labeling in the actual image dimension(2000*4000 range) but while passing to the yolo model for training I am providing image size as 640 which is  considerably lower compared to the actual data size.  Does this image resize reduction affect the input yolo labels position?

**Comment by L-MASTERS** [comment]
@naveenvj25 I have also scaled down my images. As far as I understand, the resizing is applied to the bounding boxes as well, just as if you were carrying out data augmentation, which would also have to be applied to the labels.

**Comment by Wang-Yu-Qing** [comment]
The bbox coords and sizes in labels txt is relative value which ranges from [0, 1], so I think it can handle img resize.

**Comment by naveenvj25** [comment]
> The bbox coords and sizes in labels txt is relative values which range from 0 to 1, so I think it can handle img resize.

I also think so, hence the label position will not change even in resized image.

**Comment by glenn-jocher** [comment]
@naveenvj25 you're absolutely right! The bounding box coordinates in the label files are indeed normalized relative values between 0 and 1. This means that they are proportionally scaled to the image dimensions. So when the image is resized during training, the labels are automatically adjusted to match the new image size, ensuring the label positions remain accurate. No worries there! 😊 If you have any more questions or need further clarification, feel free to ask.

**Comment by naveenvj25** [comment]
Thanks for the comments..!

**Comment by glenn-jocher** [comment]
@naveenvj25 you're spot on! The label coordinates are indeed relative, so they adapt seamlessly to image resizes. This ensures that your bounding boxes will still accurately represent the objects in your images, regardless of the size change during training. Keep up the great work, and if you hit any snags or have more questions, I'm here to help! 😊👍
