### ISSUE TITLE
yolv8 Pose - Coco Whole body

### ISSUE THREAD

**Issue by CesareDavidePace** [ultralytics/ultralytics#8300]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I've been working on adapting YOLOv8 for a project where precise whole-body detection is crucial, including detailed keypoints for feet, which are not originally specified in the standard COCO dataset keypoints set. To achieve this, I've edited both the architecture YAML file and the dataset YAML file to include new keypoints for feet.

Here are the steps I followed:

- Edit the Architecture YAML: Added new keypoints for feet in the architecture configuration, ensuring they align with YOLOv8's framework for processing keypoints.

nc: 1 # number of classes
kpt_shape: [23, 3] # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)

- Edit the Dataset YAML: Modified the COCO dataset configuration to include annotations for the new feet keypoints, following the format used for other body parts.

kpt_shape: [23, 3] # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)
#flip_idx: [0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15]
flip_idx: [0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15, 18, 17, 20, 19, 22, 21] # COCO wholebody keypoints

After training, when conducting inference tests, the keypoints for the feet do not appear in the detection results, despite the model showing reasonable performance on other keypoints and having been trained with the intention of recognizing these new keypoints.

**Comment by glenn-jocher** [comment]
@CesareDavidePace hello!

Great to hear about your project and your initiative to extend YOLOv8 for whole-body detection with additional keypoints for feet. It looks like you've made the necessary changes to the architecture and dataset YAML files, which is a solid start.

Since the feet keypoints are not showing up in the inference results, here are a couple of suggestions you might want to consider:

1. **Data Annotation Check**: Ensure that the feet keypoints are correctly annotated in your dataset. The annotations should match the format expected by the model.

2. **Model Output Layer**: Verify that the output layer of your model is correctly configured to predict the additional keypoints. The number of outputs should correspond to the total keypoints (including the new ones for feet).

3. **Post-processing**: Check the post-processing steps to ensure that the additional keypoints are being handled correctly after the model's predictions.

Here's a quick code snippet to check the output layer dimensions:

```python
from ultralytics import YOLO

# Load your custom-trained model
model = YOLO('path/to/your/custom-model.pt')

# Check the output layer shape
print(model.model[-1].shape)  # Replace -1 with the correct index of your output layer
```

If you're still facing issues, feel free to share more details or error logs, and we'll be happy to help you troubleshoot further. Keep up the good work! 👍

**Comment by CesareDavidePace** [comment]
I already checked that the feet keypoints are correctly annotated. Each row of the txt file are: class xyhw keypoint(23x2).
Where 23 are 17 of the standard pose and 6 of the additional feet.

Model output layer from file yaml:   [15, 18, 21]  1   1173580  ultralytics.nn.modules.head.Pose             [1, [23, 3], [64, 128, 256]]  
But if I check the model output layer I have got this error:  TypeError: 'PoseModel' object is not subscriptable
I try with the default weight from the repository and is the same.

In post-processing there are the keypoint of the feet but are all 0s.

**Comment by glenn-jocher** [comment]
@CesareDavidePace hey there!

It's good to hear that you've verified the annotations are correct. The error you're encountering when trying to access the model's output layer suggests that we might be trying to index into the model object incorrectly. Instead of using `model[-1]`, you should access the specific layer you're interested in. For example, if you want to check the output of the Pose head, you might need to reference it by its attribute name, like so:

```python
print(model.model.head)  # Assuming 'head' is the attribute name for the Pose head
```

Regarding the post-processing step, if the keypoints for the feet are all zeros, it could indicate that the model isn't learning to predict them correctly. This could be due to various reasons, such as the model not being trained for enough epochs, the learning rate not being optimal, or the need for more data with feet annotations.

Since you mentioned that using default weights also results in zeros for the feet keypoints, it could also be a sign that there's an issue with how the keypoints are being handled during inference. Double-checking the inference code, especially the parts that handle the keypoints, might shed some light on this.

Keep at it, and I'm sure you'll crack it! 😊🔍

**Comment by CesareDavidePace** [comment]
Hi, then for the output of the network with this code
`import os
# set cuda device
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="0"

from ultralytics import YOLO

# Load your custom-trained model
model = YOLO('/home/pace/yolov8-wholebody/runs/pose/train3/weights/best.pt',)

# Check the output layer shape
print(model.model.model[-1])  `

I've got this: 
`
Pose(
  (cv2): ModuleList(
    (0): Sequential(
      (0): Conv(
        (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (2): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
    )
    (1): Sequential(
      (0): Conv(
        (conv): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (2): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
    )
    (2): Sequential(
      (0): Conv(
        (conv): Conv2d(256, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (2): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
    )
  )
  (cv3): ModuleList(
    (0): Sequential(
      (0): Conv(
        (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (2): Conv2d(64, 1, kernel_size=(1, 1), stride=(1, 1))
    )
    (1): Sequential(
      (0): Conv(
        (conv): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (2): Conv2d(64, 1, kernel_size=(1, 1), stride=(1, 1))
    )
    (2): Sequential(
      (0): Conv(
        (conv): Conv2d(256, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (2): Conv2d(64, 1, kernel_size=(1, 1), stride=(1, 1))
    )
  )
  (dfl): DFL(
    (conv): Conv2d(16, 1, kernel_size=(1, 1), stride=(1, 1), bias=False)
  )
  (cv4): ModuleList(
    (0): Sequential(
      (0): Conv(
        (conv): Conv2d(64, 69, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(69, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(69, 69, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(69, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (2): Conv2d(69, 69, kernel_size=(1, 1), stride=(1, 1))
    )
    (1): Sequential(
      (0): Conv(
        (conv): Conv2d(128, 69, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(69, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(69, 69, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(69, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (2): Conv2d(69, 69, kernel_size=(1, 1), stride=(1, 1))
    )
    (2): Sequential(
      (0): Conv(
        (conv): Conv2d(256, 69, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(69, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(69, 69, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(69, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (2): Conv2d(69, 69, kernel_size=(1, 1), stride=(1, 1))
    )
  )
)
`

And I think that's okay

for the training phase i train for 50 epochs and default learning rate.

**Comment by glenn-jocher** [comment]
@CesareDavidePace hey there!

Thanks for sharing the details of your network output and training setup. The output you've posted looks like a standard Pose module configuration, which seems to be in order. 👍

For a 50-epoch training with the default learning rate, it's a good initial run, but depending on the complexity of the task and the dataset, you might need more training time or data augmentation to improve the detection of those new keypoints.

If you're still not seeing the expected results for the feet keypoints, consider experimenting with longer training, different learning rates, or even more data if possible. Sometimes these tweaks can make all the difference!

Keep up the great work, and don't hesitate to reach out if you have more questions or updates. 😊🚀

**Comment by CesareDavidePace** [comment]
I'm using the coco whole-body dataset by filtering the foot keypoints in the labels. At this point, I try 100 epochs and see what happens.
