### ISSUE TITLE
 How do you get the result using pandas?

### ISSUE THREAD

**Issue by muhaha211** [ultralytics/ultralytics#8302]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

```
model = YOLO("asd.pt")
results = model.predict("a44.png", verbose=True)
print (results[0].boxes.data.tolist())
```

Even after reviewing the YOLOv8 documentation, it doesn't seem like there's a way to fetch the result using pandas. Is there a method that I'm unaware of? YOLOv5 had one, but I couldn't find it for YOLOv8. (I'm using the above source code instead..)

**Comment by glenn-jocher** [comment]
@muhaha211 hello! To fetch the results using pandas in YOLOv8, you can convert the results to a list and then create a DataFrame. Here's a quick example:

```python
import pandas as pd
from ultralytics import YOLO

# Load your model and run prediction
model = YOLO("asd.pt")
results = model.predict("a44.png")

# Convert results to a list and then to a DataFrame
df = pd.DataFrame(results[0].pandas().xyxy)
print(df)
```

This will give you a pandas DataFrame with the bounding box coordinates, confidence scores, and class predictions. Let me know if you need any more help! 😊👍

**Comment by Shadowfear36** [comment]
@glenn-jocher This does not appear to work. 
**Code:**
`model = YOLO("./ls-ds-v1.pt")

results = model.predict("./images/almond.bmp", imgsz=1216, save=True)

df = pd.DataFrame(results[0].pandas().xyxy)
print(df)`

**Error:**
`images\almond.bmp: 384x1216 42 Others, 210.6ms
Speed: 4.8ms preprocess, 210.6ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 1216)
Results saved to runs\detect\predict34
Traceback (most recent call last):
  File "C:\yolov8\detect.py", line 16, in <module>
    df = pd.DataFrame(results[0].pandas().xyxy)
                      ^^^^^^^^^^^^^^^^^
  File "C:\yolov8\venv\Lib\site-packages\ultralytics\utils\__init__.py", line 153, in __getattr__
    raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
AttributeError: 'Results' object has no attribute 'pandas'. See valid attributes below.

    A class for storing and manipulating inference results.

    Args:
        orig_img (numpy.ndarray): The original image as a numpy array.
        path (str): The path to the image file.
        names (dict): A dictionary of class names.
        boxes (torch.tensor, optional): A 2D tensor of bounding box coordinates for each detection.
        masks (torch.tensor, optional): A 3D tensor of detection masks, where each mask is a binary image.
        probs (torch.tensor, optional): A 1D tensor of probabilities of each class for classification task.
        keypoints (List[List[float]], optional): A list of detected keypoints for each object.

    Attributes:
        orig_img (numpy.ndarray): The original image as a numpy array.
        orig_shape (tuple): The original image shape in (height, width) format.
        boxes (Boxes, optional): A Boxes object containing the detection bounding boxes.
        masks (Masks, optional): A Masks object containing the detection masks.
        probs (Probs, optional): A Probs object containing probabilities of each class for classification task.
        keypoints (Keypoints, optional): A Keypoints object containing detected keypoints for each object.
        speed (dict): A dictionary of preprocess, inference, and postprocess speeds in milliseconds per image.
        names (dict): A dictionary of class names.
        path (str): The path to the image file.
        _keys (tuple): A tuple of attribute names for non-empty attributes.`

**Comment by glenn-jocher** [comment]
@Shadowfear36 hey there! It looks like there's been a small mix-up with accessing the results. In YOLOv8, the `pandas()` method is no longer used. Instead, you can directly access the attributes of the `Results` object. Here's how you can modify your code to create a DataFrame:

```python
from ultralytics import YOLO
import pandas as pd

# Load your model and run prediction
model = YOLO("./ls-ds-v1.pt")
results = model.predict("./images/almond.bmp", imgsz=1216, save=True)

# Convert results to a list of dictionaries and then to a DataFrame
data = [{'xmin': box[0], 'ymin': box[1], 'xmax': box[2], 'ymax': box[3], 
         'confidence': box[4], 'class': box[5]} for box in results[0].boxes.xyxy]
df = pd.DataFrame(data)
print(df)
```

This should give you the DataFrame you're looking for. Give it a try and let me know if it works out! 😊👍

**Comment by Shadowfear36** [comment]
These GPT responses are rough, lol. Here's the result with that code.
**Error:**
```
Speed: 5.9ms preprocess, 88.1ms inference, 294.5ms postprocess per image at shape (1, 3, 384, 1216)
Results saved to /yolov8/runs/detect/predict
Traceback (most recent call last):
  File "/yolov8/test.py", line 9, in <module>
    data = [{'xmin': box[0], 'ymin': box[1], 'xmax': box[2], 'ymax': box[3], 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sort/yolov8/test.py", line 10, in <listcomp>
    'confidence': box[4], 'class': box[5]} for box in results[0].boxes.xyxy]
                  ~~~^^^
IndexError: index 4 is out of bounds for dimension 0 with size 4
```
I managed to get it into the pandas dataframe on my own, so I dont really need an answer anymore. But @glenn-jocher might want to update your personal GPT with the latest docs for these issues. Only causing more issues to be created lol.


Here's how I resolved this issue, may not be the most efficient but it gets the job done:

`const class_names = { 0: "Class 1", 1: "Class 2"}`
```
    def detections_to_dataframe(results, class_names, thres):
        thres = thres / 100
    	# Initialize lists to store detection data
        all_boxes = []
        all_confidences = []
        all_class_ids = []
        all_class_names = []

    	# Iterate over each detection in the results
        for box in results[0].boxes:
            xmin, ymin, xmax, ymax = box.xyxy[0].cpu().numpy()
            cls_id = box.cls[0].item()  # Extract class ID
            conf = round(box.conf[0].item(), 2)  # Extract confidence score

            if conf >= thres:  # Apply threshold
                    all_boxes.append([xmin, ymin, xmax, ymax])
                    all_confidences.append(conf)
                    all_class_ids.append(cls_id)
                    all_class_names.append(class_names[cls_id])  # Convert class ID to class name

    	# Create a DataFrame
        df = pd.DataFrame(all_boxes, columns=['xmin', 'ymin', 'xmax', 'ymax'])
        df['confidence'] = all_confidences
        df['class'] = all_class_ids
        df['name'] = all_class_names

        return df
```

```
    def detect(img, thres, dist):
        start = time.time()
        results = model(img, imgsz=1216) 
        end = time.time()
        runtime = end - start
        # Convert detections to a DataFrame
        detections_df = detections_to_dataframe(results, class_names, thres)
        return detections_df
```

**Comment by glenn-jocher** [comment]
Hey @Shadowfear36! 😄 I'm glad to hear you've found a solution to convert the detection results into a pandas DataFrame. Your approach looks solid, and it's great that you're applying a confidence threshold to filter the results.

Thanks for sharing your code snippet – it could definitely be helpful for others facing similar issues. And you're right, keeping the GPT models updated with the latest documentation is crucial for providing accurate support. I'll make sure to pass on your feedback.

If you have any more questions or run into other issues, feel free to reach out. Happy coding! 🚀

**Comment by GenieV19** [comment]
@Shadowfear36 thank you so much for sharing your code on how to do this - I'm just trying to amend it slightly so that it will create a df for the result of processing images stored in several folders. 
I have:
`source = "/my/directory/**/*" # captures all images in sub-directories
results = model.predict(source, stream=True) # successfully predicts on all images
`
But then I can't seem to work this into your code above as my 'results' is a 'generator' object... just wondering if you could give any pointers!
