### ISSUE TITLE
Hello, I need to use YOLOv8 to count

### ISSUE THREAD

**Issue by AllenGitHub1** [ultralytics/ultralytics#8303]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I need to use YOLOv8 to count, specifically by using a trained model to count all images in a folder and obtain the number of objects in each category.
When I use model-predict, although it tells me the number of targets in each image, I need to know the total number of targets in all images. How should I modify the code

**Comment by glenn-jocher** [comment]
@AllenGitHub1 hello! To count the total number of objects across all images in a category, you can accumulate the counts from each image. Here's a simple way to do it using Python:

```python
from ultralytics import YOLO
from collections import Counter

# Load your trained model
model = YOLO('path/to/your/trained_model.pt')

# Directory containing your images
image_dir = 'path/to/your/image_folder'

# Run prediction on the entire directory
results = model.predict(image_dir)

# Initialize a counter for all categories
category_counts = Counter()

# Loop through results and update counts
for result in results:
    category_counts.update(result.boxes.cls)

# Convert category IDs to names and print the total counts
total_counts = {model.names[k]: v for k, v in category_counts.items()}
print(total_counts)
```

This code will give you a dictionary with the total count of detected objects for each category across all images in the specified folder. Hope this helps! 😊🚀

**Comment by AllenGitHub1** [comment]
Hello @glenn-jocher ,    thank you very much for your help, but there have been some errors with the code on my device. The details are as follows

![1708405463903](https://github.com/ultralytics/ultralytics/assets/113035146/a4363e07-7024-4edc-8f2d-becfe6370b73)

**Comment by glenn-jocher** [comment]
@AllenGitHub1 hi there! I'm glad to assist you. It seems like the image link you've provided isn't working, so I can't see the exact errors you're encountering. Could you please provide the error messages as text or ensure the image link is correct? This will help me understand the issue better and provide you with a more accurate solution. 😊🛠️

**Comment by Skillnoob** [comment]
@AllenGitHub1 use this code:
```python
from collections import Counter
from ultralytics import YOLO

model = YOLO()

results = model()

category_counts = Counter()
for result in results:
    category_counts.update(result.boxes.cls.cpu().numpy())

total_counts = {model.names[i]: count for i, count in category_counts.items()}

print(total_counts)
```

Though you still need to modify it to your needs.
