### ISSUE TITLE
Predictions results

### ISSUE THREAD

**Issue by amira-essawy** [ultralytics/ultralytics#8304]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, 
I want to know what are the postprocessing is used for predictions? can I not use it? Also, I want to stop showing the speed how can I turn off this option?

**Comment by glenn-jocher** [comment]
@amira-essawy hello! 👋

For postprocessing during predictions, YOLOv8 typically applies Non-Maximum Suppression (NMS) to filter overlapping detections and ensure each object is only detected once. If you wish to bypass this, you can set the NMS `iou` threshold to `1.0`, which effectively turns it off, though this is generally not recommended as it may result in multiple detections for the same object.

Regarding the speed display, if you're using the Python API, you can avoid printing the speed by not accessing the `speed` attribute in the `Results` object. If you're using the CLI and referring to the inference speed displayed in the terminal, currently there's no built-in option to disable this output. However, it should not affect the performance or the results of your predictions.

Here's a quick Python example to set the NMS `iou` threshold to `1.0`:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('path/to/your/model.pt')

# Run predictions with NMS iou threshold set to 1.0
results = model.predict('path/to/your/image.jpg', iou=1.0)
```

Hope this helps! Let us know if you have any more questions. 😊
