### ISSUE TITLE
Data Augmentation yolov8

### ISSUE THREAD

**Issue by HannahAlexander** [ultralytics/ultralytics#8308]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I'm trying to implement data augmentation for the yolov8 model. 
I searched the documentation and landed on the following page: https://docs.ultralytics.com/usage/cfg/#augmentation
This suggests change the parameters in the model.train() function, however other tutorials that i have found have suggested that you need to do the augmentation outside of the model. This is my code:

```
model.train(data='src/models/aerial_objects.yaml',
                augment = True,
                epochs = v8_hyperparameters["epochs"], 
                imgsz = v8_hyperparameters["imgsz"], 
                batch = v8_hyperparameters["batch"], 
                device = v8_hyperparameters["device"], 
                patience = v8_hyperparameters["batch"], # epochs to wait for no observable improvement for early stopping of training
                lr0 = v8_hyperparameters["lr0"], # initial learning rate
                # project = project name,
                name = experiment_name,
                optimizer = v8_hyperparameters["optimizer"], # Adam, Adamax, AdamW, NAdam, RAdam, RMSProp, auto,
                weight_decay = v8_hyperparameters["weight_decay"],
                hsv_h = 0.015, # image HSV-Hue augmentation (fraction)
                hsv_s = 0.7, # image HSV-Saturation augmentation (fraction)
                hsv_v = 0.4, # image HSV-Value augmentation (fraction)
                degrees = 0,
                translate= 0.1,
                scale = 0,
                shear = 0,
                perspective = 0,
                flipud = 0.5,
                fliplr = 0.5,
                mosaic = 1.0,
                mixup = 0,
                copy_paste = 0,
                auto_augmnet = "randaugment",
                val = True)
```
                
Would you be able to let me know if this is correct?

Many thanks,

Hannah

**Comment by glenn-jocher** [comment]
@HannahAlexander hi Hannah 👋,

Great to hear you're exploring data augmentation with YOLOv8! Your approach to implementing augmentations directly in the `model.train()` function is indeed correct. YOLOv8's training pipeline is designed to handle various augmentations internally, so you don't need to preprocess your images for augmentation separately.

The parameters you've set, such as `hsv_h`, `hsv_s`, `hsv_v`, `degrees`, `translate`, `scale`, `shear`, `perspective`, `flipud`, `fliplr`, `mosaic`, `mixup`, `copy_paste`, and `auto_augment`, are all valid and will be applied during training. Just make sure that the values you assign to these parameters are within the expected ranges and suit your specific dataset and use case.

Here's a small tip: the `patience` parameter should be the number of epochs to wait for improvement, not the batch size. So you might want to adjust that.

Your code snippet looks good to go! If you have any more questions or need further assistance, feel free to ask.

Happy training! 🚀

**Comment by tjasmin111** [comment]
So `mosaic = 1.0`  defines the probability. How can I specify using 9 images instead of 4 for mosaic augmentation?

**Comment by glenn-jocher** [comment]
@tjasmin111 currently, YOLOv8's mosaic augmentation is designed to use 4 images. Customizing it to use 9 images would require modifying the underlying code.
