### ISSUE TITLE
Is Yolov8 ready?

### ISSUE THREAD

**Issue by paolocomis** [ultralytics/ultralytics#831]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I just finished annotating about 30k images for my use case. I started labeling in early December with the idea of training the model with yolov5l/x. Instead, I learned with happiness of the release of Yolov8 in early January, whose results seem even better than Yolov5.
And so like perhaps many, I face the crucial dilemma: Do I train my model with Yolov8 or with Yolov5?

The question arises from the fact that, like everyone else, I want to avoid wasting time and resources.

So I ask you:
Has up-and-comer Yolov8 already outperformed veteran Yolov5 in any custom object recognition use case, or still in its infancy, does Yolov5 remain the top pick for absolute accuracy for now?

I should deliver the work by the end of February, so I have to make a decision quickly.

Thanks in advance.

**Comment by glenn-jocher** [comment]
@paolocomis depends on your risk/early adopter tolerance. If you need to deliver a reliable product to market in a short timeframe, YOLOv5 is the right choice.

If you're leaning towards R&D and willing to do a little debugging and submit a few bug reports then try YOLOv8.

The good news is YOLOv8 works with the same exact dataset formats as YOLOv5, so in the future you can transition relatively seamlessly.

**Comment by paolocomis** [comment]
> @paolocomisdipende dalla tua tolleranza al rischio / all'adozione anticipata. Se hai bisogno di fornire un prodotto affidabile sul mercato in un breve lasso di tempo, YOLOv5 è la scelta giusta.
> 
> Se sei propenso alla ricerca e sviluppo e sei disposto a fare un po' di debugging e inviare alcune segnalazioni di bug, prova YOLOv8.
> 
> La buona notizia è che YOLOv8 funziona con gli stessi esatti formati di set di dati di YOLOv5, quindi in futuro potrai eseguire la transizione in modo relativamente fluido.

Thanks as always for the quick and comprehensive response! The best!
