### ISSUE TITLE
I have upload the dataset on google drive, while when I training the YOLO model on colab, the scanning spped is too slow, and always at 2% progress.

### ISSUE THREAD

**Issue by Ares-cz** [ultralytics/ultralytics#8316]
I have upload the dataset on google drive, while when I training the YOLO model on colab, the scanning spped is too slow, and always at 2% progress.
Before this training, I was using a smaller dataset to train the same model, the scanning is very fast.
I'm not sure if this is related to the fact that I used a larger data set, but even so, why does the scan progress always stay at 2%?
Thanks in advance.

<img width="1392" alt="image" src="https://github.com/ultralytics/yolov5/assets/33047738/1a7995e0-e445-43be-98e6-bddfd88907ea">

_Originally posted by @Ares-cz in https://github.com/ultralytics/yolov5/issues/1145#issuecomment-1953440752_

**Comment by glenn-jocher** [comment]
Hi @Ares-cz 👋,

The slow scanning speed you're experiencing on Colab with a larger dataset could be due to a few factors. Here are a couple of suggestions you might find helpful:

1. **Dataset Caching**: Ensure that your dataset is cached properly before training starts. You can do this by setting the `cache` argument in your training command. For example:
   ```python
   model.train(data='your_dataset.yaml', cache=True)
   ```
   This will preload your dataset into memory, which can speed up the scanning process.

2. **Google Drive I/O**: Accessing data directly from Google Drive can be slow. Consider copying your dataset to the Colab VM local storage before training:
   ```bash
   !cp -r /content/drive/MyDrive/your_dataset /content/
   ```
   Then, point your dataset path to the local copy.

If the issue persists, it might be worth checking if there's a specific bottleneck in the data loading process. Keep an eye on the Colab VM's RAM and disk usage to ensure you're not hitting any limits there.

Hope this helps! Let us know if you have any more questions. 😊

**Comment by Ares-cz** [comment]
thank you very much @glenn-jocher 
I have know how to fix it.

**Comment by glenn-jocher** [comment]
@Ares-cz you're welcome! I'm glad to hear you figured it out. If you have any more questions or need further assistance down the road, don't hesitate to reach out. Happy coding! 😊🚀

**Comment by Ares-cz** [comment]
Hi @glenn-jocher

I have a question. I used the method you mentioned yesterday to copy the data set to /content, which reduced the scanning time. this works very well.

According to my understanding, after delete runtime, the copied content will be released. Not sure if my understanding is correct.

But yesterday I found that the disk size was 140G, but today there is only 78G left (I have delete runtime which yesterday used. And in the /content direction, cannot found the dataset used in yesterday). Today, the data set I used reached 88G, which seems impossible to copy into /content.

I don’t know if you have ever encountered this situation. Thanks in advance.

<img width="274" alt="image" src="https://github.com/ultralytics/ultralytics/assets/33047738/54e1a87e-c503-4d9c-b1e1-ef1715c67325">

**Comment by Ares-cz** [comment]
And when I using the `!cp -r /content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/ /content/` to copy the dataset to the `/content` direction. There are some error:

> cp: error reading '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000007.PNG': Transport endpoint is not connected
cp: failed to close '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000007.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000023.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000055.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000069.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000056.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000008.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000084.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000054.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000034.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000050.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000001.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000081.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000076.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000071.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000060.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000046.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000031.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000092.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000149.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000146.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000206.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000166.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000183.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000114.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000201.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000191.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000162.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000147.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000193.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000164.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000165.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000159.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000184.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000175.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000187.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000134.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000154.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000158.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000174.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000181.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000348.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000284.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000240.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000234.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000345.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000253.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000328.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000286.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000309.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000263.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000314.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000303.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000271.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000317.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000289.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000325.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000350.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000283.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000230.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000344.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000353.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000398.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000368.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000463.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000359.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000461.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000388.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000475.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000378.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000372.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000419.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000382.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000376.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000443.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000478.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000442.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000370.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000428.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000449.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000381.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000409.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000403.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000390.PNG': Transport endpoint is not connected
cp: cannot stat '/content/drive/MyDrive/Data/Grape_bunch_yolo_dataset_PathPlanning_mix/images/valid/PathPlanning_1_frame_000540.PNG': Transport endpoint is not connected

**Comment by glenn-jocher** [comment]
@Ares-cz hi there,

It seems like you're encountering a common issue where the Google Drive mount point is disconnecting during the copy operation. This can happen if the operation takes too long or if there's a hiccup in the network connection.

To resolve this, you can try the following steps:

1. Remount your Google Drive and ensure it's connected properly.
2. Break down your copy operation into smaller chunks if possible, to avoid timeouts.
3. Use the `gdown` command to download files directly to your Colab instance, which can be more reliable for large files.

Here's a quick example of how you might use `gdown`:

```bash
!gdown --id YOUR_FILE_ID -O /content/
```

Replace `YOUR_FILE_ID` with the actual file ID from Google Drive.

Regarding the disk space issue, Colab provides a limited amount of disk space that can vary from session to session. If you're running out of space, you might need to upgrade to Colab Pro for more disk space or work with a smaller subset of your data.

Hope this helps!
