### ISSUE TITLE
Macbook Air (M2) can not train yolov8 on custom data with mps

### ISSUE THREAD

**Issue by PhuongBui712** [ultralytics/ultralytics#8319]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I have tried to train yolov8 on my custom dataset. Initially, I've ran without any hardware defining and it run on my cpu as default by the following code:
```python
model = YOLO('yolov8s.pt')

# train
results = model.train(
    data=data,
    epochs=epochs,
    batch=batch_size,
    imgsz=img_size,
    project=project_name,
    name=model_name,
)
```
Consequencely, it ran too slowly, about 1 hour and half per epoch.

<img width="1301" alt="Screenshot 2024-02-20 at 14 10 53" src="https://github.com/ultralytics/ultralytics/assets/111408861/84e161ce-3f3b-4d51-a985-96c0964fe36c">

Hence, I have explored the way how to optimize it and known that using MPS backend on macbook is the best way when I just need to define `device='mps'` in train method.

```python
results = model.train(
    data=data,
    epochs=epochs,
    batch=batch_size,
    imgsz=img_size,
    project=project_name,
    name=model_name,
    device='mps'
)
```

However, it didn't work as expected:

<img width="1138" alt="Screenshot 2024-02-20 at 14 40 32" src="https://github.com/ultralytics/ultralytics/assets/111408861/3fa9c4ec-3ac3-48a8-80a4-d32453a9c7e0">

I have already checked whether my laptop support MPS backend by [this instruction](https://medium.com/@brainhj/yolov8-train-m1-m2-e0b40f3b0952), even on [official yolo page](https://docs.ultralytics.com/modes/train/#apple-m1-and-m2-mps-training)

### Environment

Ultralytics YOLOv8.1.15 🚀 Python-3.11.7 torch-2.2.0 CPU (Apple M2)
Setup complete ✅ (8 CPUs, 16.0 GB RAM, 153.0/460.4 GB disk)

### Minimal Reproducible Example

```python
model = YOLO('yolov8s.pt')

# train
results = model.train(
    data=data,
    epochs=epochs,
    batch=batch_size,
    imgsz=img_size,
    project=project_name,
    name=model_name,
    device='mps'
)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@PhuongBui712 this works correctly for me on an M2 Macbook:
<img width="1215" alt="Screenshot 2024-02-20 at 13 16 13" src="https://github.com/ultralytics/ultralytics/assets/26833433/b6396c4b-4034-49fd-abf7-af34efba9d66">
