### ISSUE TITLE
'save_period' is not a valid YOLO argument

### ISSUE THREAD

**Issue by Davisonyeas** [ultralytics/ultralytics#8322]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Hyperparameter Tuning

### Bug

'save_period' is not a valid YOLO argument. Similar arguments are ['save_hybrid', 'save_crop', 'save_json'].

### Environment

Google Colab (Driver Version: 535.104.05   CUDA Version: 12.2) GPU

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Burhan-Q** [comment]
@Davisonyeas what is the version of `ultralytics` you're using? The argument `save_period` is a training argument from the [cfg/default.yaml](https://github.com/ultralytics/ultralytics/blob/61088b43d763a91c614134f295cf762f5beaba76/ultralytics/cfg/default.yaml#L16) file and should be accepted as an input argument.

**Comment by Davisonyeas** [comment]
ultralytics version 8.0.20
Kindly find the attached image that shows the error message and code
<img width="1700" alt="Screenshot 2024-02-20 at 1 42 46 PM" src="https://github.com/ultralytics/ultralytics/assets/72320718/0c33975f-707c-4ba9-b1af-e38b7178301f">

**Comment by Burhan-Q** [comment]
@Davisonyeas `8.0.20` is nearly over a year old. I highly recommend updating the version you're using. You can also reference the official Colab tutorial notebook <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>

**Comment by Davisonyeas** [comment]
@Burhan-Q I upgraded the version, and it now works. Thank you

**Comment by Burhan-Q** [comment]
You're very welcome @Davisonyeas happy to hear it's working now!
