### ISSUE TITLE
How can i extract coordinates of the bounding  boxes from YOLOv8 AGP3.0 license version ?

### ISSUE THREAD

**Issue by Aflexg** [ultralytics/ultralytics#8323]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello.I know how to extract coordinates of the bounding  boxes only from YOLOv8 GPL3.0 license version.There is  a variable xywh in the predict.py which has all necessarry coordintates.
![image](https://github.com/ultralytics/ultralytics/assets/153363231/13a9f11e-7685-4b47-8916-e092eb694e25)

But i dont see this variable in the predict.py (AGPL3.0 version) and i also dont see it in the predictor.py.Is it still exist in the AGPL3.0 version?If so, how can i find it and how can i extract coordinates from it ?
![image](https://github.com/ultralytics/ultralytics/assets/153363231/9c480e48-08f5-4d2d-858b-f2e580782cbc)
![image](https://github.com/ultralytics/ultralytics/assets/153363231/ca2991ec-8517-48a1-ab19-bcfe8fa14ffa)

How can i  extract coordinates of the bounding  boxes from YOLOv8 in AGPL3.0 license version ?I want to use these coordinates in the next step of my programm, so extraction of the text file with the coordinates is not enough for me.I need to find variable such as xywh in GPL3.0 version and work with it.I want to be able to extract part of the image with a detected object to apply another detection neural network on it.

**Comment by Burhan-Q** [comment]
Note the _only_ valid license for Ultralytics is AGPL-3.0. See the [documentation website](https://docs.ultralytics.com/) for reference and examples of how to use the `ultralytics` python library. Specifically the Predict Mode page will be the most helpful, and although I do recommend reviewing the entire page, the section on [Working with Results](https://docs.ultralytics.com/modes/predict/#working-with-results) will be the most relevant to your question.
