### ISSUE TITLE
I want to perform object detection using Yolov8(TFLite)

### ISSUE THREAD

**Issue by AlaaArboun** [ultralytics/ultralytics#8329]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

How are bounding box coordinates and class probabilities extracted from the output tensor?
How does the code convert normalized bounding box coordinates to pixel coordinates?
and how to draw bounding boxes and labels on the original image?

### Minimal Reproducible Example

from PIL import Image, ImageDraw
import numpy as np
import tflite_runtime.interpreter as tflite
from tflite_runtime.interpreter import load_delegate

# Load the TensorFlow Lite model with Edge TPU delegate
model_path = 'yolov8m_saved_model/yolov8m_float32.tflite'
interpreter = tflite.Interpreter(model_path=model_path, experimental_delegates=[load_delegate('edgetpu.dll')])
interpreter.allocate_tensors()

# Preprocess input image
def preprocess_image(image_path, input_shape):
    image = Image.open(image_path)
    resized_image = image.resize(input_shape, Image.LANCZOS)  # Use Image.LANCZOS for high-quality downsampling
    resized_image = np.array(resized_image, dtype=np.float32)
    resized_image /= 255.0  # Normalize
    resized_image = np.expand_dims(resized_image, axis=0)  # Add batch dimension
    return resized_image

# Extract bounding box coordinates and class probabilities
def extract_boxes_classes(output_data):
    # Process the output tensors
    boxes = []
    classes = []
    scores = []
    for detection in output_data:
        # Each detection is [y_min, x_min, y_max, x_max, score, class]
        for detected_object in detection:
            boxes.append(detected_object[:4])
            classes.append(int(detected_object[5]))
            scores.append(detected_object[4])

    return boxes, classes, scores

# Run inference on input image
def run_inference(image_path):
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    # Preprocess input image
    input_shape = tuple(input_details[0]['shape'][1:3])
    input_data = preprocess_image(image_path, input_shape)

    # Set input tensor
    interpreter.set_tensor(input_details[0]['index'], input_data)

    # Run inference
    interpreter.invoke()

    # Get output tensor
    output_data = [interpreter.get_tensor(output_details[i]['index']) for i in range(len(output_details))]

    # Extract bounding box coordinates and class probabilities
    boxes, classes, scores = extract_boxes_classes(output_data[0])

    print((output_data[0].shape))

    return boxes, classes, scores

# Example usage
image_path = 'dog.png'
original_image = Image.open(image_path)
original_width, original_height = original_image.size

# Run inference
boxes, classes, scores = run_inference(image_path)

# Create a drawing object
draw = ImageDraw.Draw(original_image)

# Draw bounding boxes on the image
for box, cls, score in zip(boxes, classes, scores):
    # Convert normalized coordinates to pixel coordinates
    y_min, x_min, y_max, x_max = box
    y_min_pixel = int(y_min * original_height)
    x_min_pixel = int(x_min * original_width)
    y_max_pixel = int(y_max * original_height)
    x_max_pixel = int(x_max * original_width)

    # Draw the bounding box rectangle
    draw.rectangle([x_min_pixel, y_min_pixel, x_max_pixel, y_max_pixel], outline='red')

    # Draw label
    draw.text((x_min_pixel, y_min_pixel), f'Class: {cls}, Score: {score}', fill='red')

# Save or display the image
original_image.show()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Burhan-Q** [comment]
@AlaaArboun you can use the Ultralytics `Autobackend` to load your `tflite` exported YOLOv8 model.

```python
from ultralytics import YOLO

model = YOLO("yolov8n.tflite", task="detect")
results = model.predict("path/to/image.png")

results[0].boxes
```

You can reference the docs [here](https://docs.ultralytics.com/modes/predict/#working-with-results) for additional methods and attributes available for the `results` object.

**Comment by AlaaArboun** [comment]
@Burhan-Q   Thanks a lot! The purpose is to create code that can detect objects and visualize the predicted bounding boxes in the original image using YOLOv8 TensorFlow Lite running on Coral.

**Comment by AlaaArboun** [comment]
I'm encountering a peculiar issue with the bounding box values generated by the model. When I inspect the predictions, I find that the bounding box coordinates and associated confidence scores are extremely small. Here's a snippet of the output I'm seeing:                                                                                                                                                                                               
(1, 84, 8400)                                                                                                                                                                                    
Box: [   0.021675    0.023994    0.055886    0.067794], Class: 0, Score: 0.06562820076942444
Box: [   0.012235    0.012138    0.012582    0.012547], Class: 0, Score: 0.011931846849620342
Box: [   0.043408     0.04755     0.11067     0.13549], Class: 0, Score: 0.13044670224189758
Box: [   0.024357    0.024403    0.025215     0.02496], Class: 0, Score: 0.02368740551173687
Box: [ 3.3784e-06  3.7238e-06  7.6792e-06  1.9926e-05], Class: 0, Score: 1.7310614566667937e-05
Box: [ 3.3835e-07  3.6066e-07   6.434e-07  1.5073e-06], Class: 0, Score: 1.250493255611218e-06
Box: [ 2.8035e-06  3.1386e-06  5.6632e-06  1.4311e-05], Class: 0, Score: 1.0994585863954853e-05
Box: [ 2.6301e-07  2.5312e-07  3.9358e-07  9.2785e-07], Class: 0, Score: 7.732421636319486e-07
Box: [ 4.4538e-07  3.8776e-07  6.9737e-07  2.0477e-06], Class: 0, Score: 1.94178824131086e-06
Box: [  2.717e-07  2.7011e-07  4.4488e-07  1.4614e-06], Class: 0, Score: 1.5128380255191587e-06
Box: [ 4.0102e-07  3.4274e-07  5.6701e-07  1.6611e-06], Class: 0, Score: 1.5579086038997048e-06
Box: [   6.79e-07  6.5574e-07  1.0515e-06  3.0828e-06], Class: 0, Score: 2.913793650805019e-06
Box: [  4.749e-07   5.101e-07  8.9466e-07   2.273e-06], Class: 0, Score: 2.2537742552231066e-06
Box: [  3.301e-07  4.2411e-07  5.3076e-07  8.4003e-07], Class: 0, Score: 7.738367457932327e-07
Box: [ 2.5833e-07  2.7761e-07  5.4771e-07  1.1591e-06], Class: 0, Score: 1.2418378219081205e-06
Box: [ 2.8349e-07   3.255e-07  4.9876e-07  9.1221e-07], Class: 0, Score: 7.852346470826888e-07
Box: [ 1.9054e-07  1.8523e-07  2.4247e-07  3.7872e-07], Class: 0, Score: 3.5505556184034504e-07
Box: [ 7.5267e-07  5.9967e-07  1.2622e-06  3.6009e-06], Class: 0, Score: 3.928018941223854e-06
Box: [ 2.8287e-06  4.1155e-06  1.0056e-05  2.1385e-05], Class: 0, Score: 1.7543567082611844e-05
Box: [ 4.6242e-07  3.7581e-07  8.5341e-07  2.8738e-06], Class: 0, Score: 2.9442965114867548e-06
Box: [ 8.8232e-07  8.1332e-07  2.0351e-06  7.2124e-06], Class: 0, Score: 6.935787951078964e-06
Box: [ 2.0771e-06  2.4036e-06  5.1318e-06  1.5771e-05], Class: 0, Score: 1.239973607880529e-05
Box: [ 9.2897e-06  1.3432e-05  3.1049e-05   7.982e-05], Class: 0, Score: 6.462412420660257e-05
Box: [ 4.4716e-06  5.3318e-06  1.0235e-05  2.8654e-05], Class: 0, Score: 2.5273195205954835e-05
Box: [ 1.5316e-06  1.5087e-06  3.1447e-06  9.2704e-06], Class: 0, Score: 1.0090517207572702e-05
...
Box: [ 8.4391e-08  6.5966e-08  8.9524e-08  1.6874e-07], Class: 0, Score: 1.6422342241639853e-07
Box: [ 3.6733e-07  4.1892e-07  8.4163e-07  2.3024e-06], Class: 0, Score: 2.3628763301530853e-06
Box: [ 2.5082e-07   2.453e-07  3.2223e-07  5.2943e-07], Class: 0, Score: 4.1650650928204414e-07
Box: [ 1.9114e-07  1.9583e-07  2.7325e-07  4.4875e-07], Class: 0, Score: 3.897986573520029e-07

**Comment by Burhan-Q** [comment]
@AlaaArboun The bounding boxes are image normalized, meaning they are divided by the width and height of the image. If you're using:

```py
from ultralytics import YOLO

model = YOLO("yolov8m_saved_model/yolov8m_float32.tflite", task="detect")
results = model.predict("path/to/image.png")

results[0].boxes
```

You'll find a method on the [link I shared above](https://docs.ultralytics.com/modes/predict/#working-with-results) that show you can use `results[0].boxes.xyxy` to view them using pixel values. Also, if you're using a Coral TPU on something like a RPi I would recommend checking out [this guide written by one of the members of our Discord](https://docs.ultralytics.com/guides/coral-edge-tpu-on-raspberry-pi/).

I see you have `(1, 84, 8400)` which means you're likely inspecting the prediction _candidates_, and will need to use some method to narrow the scope for your final detections. The process that is inherently executed to do this for `YOLO` is called `non-max suppression`  but you may implement whatever method you choose if attempting to write your own code. It is recommended that you use the `Autobackend` as shown to load the model, otherwise you'll have to engineer a solution on your own.
