### ISSUE TITLE
4-bit quantisation or support for .gguf 

### ISSUE THREAD

**Issue by Fritskee** [ultralytics/ultralytics#8337]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Support for `int4` quantized models, or models that can be exported to `.gguf` which can also be inferred in `int4`. 

### Use case

I am currently running a yolo-v8 small model with 1024x1024 resolution. For our solution, the resolution is very important and we notice that the achieved results decay rapidly as we decrease the resolution. Similarly, going for a nano model results in lesser accuracy.

When I quantise this model to `uint8` and run inference, the edge device that we run on goes out of memory (SOM with a Cortex a53 chip - similar to a Raspberry pi 3b+). This is because the device has 927MB of available RAM. When I run experiments on a similar device with 2GB or RAM, we see that memory usage peaks at 1044MB.

Having a feature that allows for `int4` quantisation, or allows us to export a model to `.guff` where we can run an `int4` quantised model, would solve this issue and open up a wide range of possibilities for new edge use cases where the Ultralytics Yolo model could be used for. 

### Additional

1. With the current advancements that are being made around quantisation, I find it strange that there is so little to find about it for the widely used YOLO repository. With LLMs there are plenty of cases where they do `int2` or `int4` quantisation with decent results. I wonder if there have been efforts or experiments with this for the YOLO repository? 
2. Another thing I've been thinking about is that it could be interesting to add a feature that allows for model distillation. Since a yolo-v8 small model at 1024x1024 yields us good results, but a yolo-v8 nano at 1024x1024 is too weak. Being able to do model distillation could be another interesting option, but seems to be tricky to do, since your loss is already calculated in the `forward()` function. 
3. If you have any other suggestions for me that could be interesting to stay within the 927MB bounds, please let me know! 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Fritskee hi there! 👋

Thanks for reaching out with your feature request regarding `int4` quantization and `.gguf` export support. We understand the importance of running models on edge devices with limited memory, and your use case for maintaining high resolution is certainly a valid one.

Currently, YOLOv8 does not support `int4` quantization or `.gguf` format export. However, we're always looking to improve and expand the capabilities of our models, especially in the context of edge deployment. We'll take your suggestion into consideration for future updates.

Regarding your points:
1. Quantization is indeed an area of active research. While we haven't yet experimented with `int4` quantization for YOLO, it's something we can explore as the field advances.
2. Model distillation is a great idea for enhancing performance on smaller models. It's a bit complex but definitely worth investigating further.
3. As an immediate suggestion, you might consider using model pruning to reduce the size and memory footprint of your model, or exploring different hardware that can accommodate larger models within your memory constraints.

We appreciate your input and encourage you to keep an eye on our repository for updates. If you have any more questions or ideas, feel free to share!

**Comment by hm782178911** [comment]
Can yolov8 runs on RTX50xx gpus with nvfp4 ?

**Comment by glenn-jocher** [comment]
Not through Ultralytics at the moment—`NVFP4` is an NVIDIA Blackwell/TensorRT capability, but our current [TensorRT export docs](https://docs.ultralytics.com/integrations/tensorrt/) only expose `FP16` and `INT8`, and the supported [export formats](https://docs.ultralytics.com/modes/export/) do not include `GGUF`; if you’d like this tracked, please open a new feature request since this issue is closed/stale.
