### ISSUE TITLE
Cannot run training more than once! "SyntaxError: 'v5loader' is not a valid YOLO argument." when using model.train with resume=True

### ISSUE THREAD

**Issue by openSourcerer9000** [ultralytics/ultralytics#8342]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I began fine tuning the detector model, running train for some epochs.  I tried to later continue where I left off but it seemed to begin the training process from scratch.  According to the docs:
```By setting resume=True, the train function will continue training from where it left off, using the state stored in the 'path/to/last.pt' file. If the resume argument is omitted or set to False, the train function will start a new training session.```
However, this is impossible. When passing that argument, it takes some minutes to load in all the training data, and then throws this very long error (ultralytics.__version__ '8.1.16'):

```
WARNING ⚠️ 'boxes' is deprecated and will be removed in 'ultralytics 8.299999999999999' in the future. Please use 'show_boxes' instead.
Traceback (most recent call last):
  File "...\finetune\yolo.py", line 125, in <module>
    model.train(data=pth/"config.yaml",
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\openSourcerer\AppData\Local\anaconda3\envs\samgeo\Lib\site-packages\ultralytics\engine\model.py", line 645, in train
    self.trainer.train()
  File "C:\Users\openSourcerer\AppData\Local\anaconda3\envs\samgeo\Lib\site-packages\ultralytics\engine\trainer.py", line 208, in train
    self._do_train(world_size)
  File "C:\Users\openSourcerer\AppData\Local\anaconda3\envs\samgeo\Lib\site-packages\ultralytics\engine\trainer.py", line 322, in _do_train
    self._setup_train(world_size)
  File "C:\Users\openSourcerer\AppData\Local\anaconda3\envs\samgeo\Lib\site-packages\ultralytics\engine\trainer.py", line 292, in _setup_train
    self.validator = self.get_validator()
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\openSourcerer\AppData\Local\anaconda3\envs\samgeo\Lib\site-packages\ultralytics\models\yolo\detect\train.py", line 96, in get_validator
    return yolo.detect.DetectionValidator(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\openSourcerer\AppData\Local\anaconda3\envs\samgeo\Lib\site-packages\ultralytics\models\yolo\detect\val.py", line 33, in __init__
    super().__init__(dataloader, save_dir, pbar, args, _callbacks)
  File "C:\Users\openSourcerer\AppData\Local\anaconda3\envs\samgeo\Lib\site-packages\ultralytics\engine\validator.py", line 77, in __init__
    self.args = get_cfg(overrides=args)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\openSourcerer\AppData\Local\anaconda3\envs\samgeo\Lib\site-packages\ultralytics\cfg\__init__.py", line 210, in get_cfg
    check_dict_alignment(cfg, overrides)
  File "C:\Users\openSourcerer\AppData\Local\anaconda3\envs\samgeo\Lib\site-packages\ultralytics\cfg\__init__.py", line 308, in check_dict_alignment
    raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'v5loader' is not a valid YOLO argument.

    Arguments received: ['yolo']. Ultralytics 'yolo' commands use the following syntax:

        yolo TASK MODE ARGS

        Where   TASK (optional) is one of ('detect', 'segment', 'classify', 'pose', 'obb')
                MODE (required) is one of ('train', 'val', 'predict', 'export', 'track', 'benchmark')
                ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
                    See all ARGS at https://docs.ultralytics.com/usage/cfg or with 'yolo cfg'

    1. Train a detection model for 10 epochs with an initial learning_rate of 0.01
        yolo train data=coco128.yaml model=yolov8n.pt epochs=10 lr0=0.01

    2. Predict a YouTube video using a pretrained segmentation model at image size 320:
        yolo predict model=yolov8n-seg.pt source='https://youtu.be/LNwODJXcvt4' imgsz=320

    3. Val a pretrained detection model at batch-size 1 and image size 640:
        yolo val model=yolov8n.pt data=coco128.yaml batch=1 imgsz=640

    4. Export a YOLOv8n classification model to ONNX format at image size 224 by 128 (no TASK required)
        yolo export model=yolov8n-cls.pt format=onnx imgsz=224,128

    6. Explore your datasets using semantic search and SQL with a simple GUI powered by Ultralytics Explorer API
        yolo explorer

    5. Run special commands:
        yolo help
        yolo checks
        yolo version
        yolo settings
        yolo copy-cfg
        yolo cfg

    Docs: https://docs.ultralytics.com
    Community: https://community.ultralytics.com
    GitHub: https://github.com/ultralytics/ultralytics
    


```

### Environment

Ultralytics YOLOv8.1.16 🚀 Python-3.11.7 torch-2.2.0 CUDA:0 (NVIDIA RTX A4000, 16376MiB)
Setup complete ✅ (24 CPUs, 63.8 GB RAM, 921.5/921.6 GB disk)

### Minimal Reproducible Example

model.train(...,
            resume=True,
            )

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@openSourcerer9000 hey there! 👋 It looks like you've encountered an issue with resuming training using the `resume=True` argument. The error message you're seeing suggests there might be a misconfiguration or an unexpected argument being passed.

To resolve this, could you please try the following steps?

1. Ensure that the `resume` argument is set to `True` without any typos.
2. Verify that the path to the checkpoint file (`'path/to/last.pt'`) is correct and accessible.
3. Double-check that there are no unsupported or deprecated arguments in your training script.

If the issue persists, it would be helpful to see the exact command or script you're using to initiate the training with the `resume` option. This way, we can pinpoint the cause more accurately.

Here's a quick example of how to resume training with a YOLOv8 model:

```python
from ultralytics import YOLO

# Load the model
model = YOLO('path/to/last.pt')  # Load the last checkpoint

# Resume training
model.train(resume=True)
```

If you continue to face difficulties, please feel free to share more details or reach out on our [community forum](https://community.ultralytics.com) for further assistance. We're here to help! 😊

**Comment by openSourcerer9000** [comment]
Yes your code is exactly what doesn't work. Retraining the model loaded from the checkpoint works for me if I don't pass `resume=True`. Please test on your end and let me know if it works. 

It says specifically that the `v5loader` arg  is the issue.  My guess is that you deprecated this  but forgot to remove it from some code that gets triggered when `resume=True`.

**Comment by glenn-jocher** [comment]
Hey @openSourcerer9000! Thanks for the update. It does sound like there might be a lingering reference to `v5loader` somewhere in the code. I'll take a closer look at the latest version and see if I can replicate the issue with the `resume=True` parameter. In the meantime, it's great to hear that reloading the model from the checkpoint without `resume=True` is working for you. I'll get back to you as soon as I have some news. Stay tuned! 😊🔍

**Comment by openSourcerer9000** [comment]
It seems I misunderstood the docs. `resume=True`  seems to only be for resuming an interrupted training session. https://github.com/ultralytics/ultralytics/issues/802#issuecomment-1616618273 Trying with ultralytics=8.0.122,  it doesn't throw the v5loader error,  but I'm unable to train for additional epochs using `resume=True`.  in the issue above,  someone suggests using `model.resume = True`.  however, this gives me the same result as  just loading the checkpoint and calling the train method:
```model = YOLO('path/to/last.pt')  # Load the last checkpoint
model.train()```
it starts all over from scratch rather than continuing to fine tune  the model for additional  epochs.  this can be seen because the loss curve is identical. 

 is there any  way to  continue fine-tuning the model for additional epochs?  it seems this is impossible with the library.

**Comment by trongvanhpkt99** [comment]
I have the same problem. Has someone fixed it yet?

**Comment by glenn-jocher** [comment]
Hello @trongvanhpkt99,

Thank you for reaching out! It sounds like you're encountering an issue with resuming training using the `resume=True` parameter. This parameter is specifically designed to continue an interrupted training session from the last saved state.

To help us better understand and address your issue, could you please provide a minimal reproducible example? This will allow us to diagnose the problem more effectively. You can find guidelines for creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

In the meantime, please ensure you are using the latest version of the Ultralytics package, as updates often include important bug fixes and improvements.

If you are looking to continue fine-tuning your model for additional epochs, you can load the last checkpoint and specify the additional epochs directly:

```python
from ultralytics import YOLO

# Load the last checkpoint
model = YOLO('path/to/last.pt')

# Continue training for additional epochs
model.train(epochs=additional_epochs)
```

This approach should continue the training process from where it left off, including the loss curve.

If the issue persists, please share more details or any error messages you encounter. We're here to help! 😊
