### ISSUE TITLE
how to visualize one of class labels bbox center coord

### ISSUE THREAD

**Issue by toula018** [ultralytics/ultralytics#8346]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

i have a project working with yolov8 and i found difficulties ( i want extract center coord of bbox of class label 'weed' ) so if u can help me i will be grateful  .
this is my attempt :

### Minimal Reproducible Example

import os
from PIL import Image, ImageDraw
from ultralytics import YOLO

# Load your custom trained YOLO model
model = YOLO("best.pt")

# Path to the folder containing images
folder_path = r"C:\Users\derra\OneDrive\Desktop\dataset0\test\weed"

# Create a directory to save processed images
output_folder = os.path.join(folder_path, "processed")
os.makedirs(output_folder, exist_ok=True)

# Iterate over the files in the folder
for filename in os.listdir(folder_path):
    if filename.endswith((".jpg", ".png", ".jpeg")):
        # Full path to the image file
        image_path = os.path.join(folder_path, filename)
        
        # Perform inference on the image
        results = model(source=image_path, conf=0.5, save=False)

        # Load the image using Pillow
        image = Image.open(image_path)

        # Get the bounding boxes from the YOLO results
        boxes = results[0].pred.xyxy.tolist()  # Access bounding boxes from results

        # Create a drawing object
        draw = ImageDraw.Draw(image)

        # Define the radius of the filled circle
        radius = 5

        # Loop over each detection in the first image of the batch
        for detection in results[0]:
            class_index = detection.cls  # Get the class index of the detection

            # Check if the class index corresponds to the class you want to visualize (e.g., "weed")
            if class_index == 1:  # Assuming "weed" class has index 1
                # Get the bounding box coordinates
                x1, y1, x2, y2 = detection.xyxy

                # Calculate the center coordinates of the bounding box
                x_center = (x1 + x2) / 2
                y_center = (y1 + y2) / 2

                # Draw a filled circle at the center coordinates
                draw.ellipse([(x_center - radius, y_center - radius), (x_center + radius, y_center + radius)], fill="red")

        # Save the image with filled circles drawn at the center coordinates
        processed_image_path = os.path.join(output_folder, filename)
        image.save(processed_image_path)

        print(f"Processed and saved: {processed_image_path}")

print("All images processed and saved.")

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@toula018 hi there! 👋 It looks like you're on the right track with your code to visualize the center coordinates of bounding boxes for the 'weed' class label. However, I noticed a small issue in the way you're accessing the bounding boxes and class index. Here's a corrected snippet:

```python
# ... [previous code]

# Loop over each detection in the first image of the batch
for *xyxy, conf, cls in results.xyxy[0]:  # results.xyxy is a list of tensors
    # Check if the class index corresponds to the class you want to visualize (e.g., "weed")
    if cls == 1:  # Assuming "weed" class has index 1
        # Get the bounding box coordinates
        x1, y1, x2, y2 = xyxy

        # Calculate the center coordinates of the bounding box
        x_center = (x1 + x2) / 2
        y_center = (y1 + y2) / 2

        # Draw a filled circle at the center coordinates
        draw.ellipse([(x_center - radius, y_center - radius), (x_center + radius, y_center + radius)], fill="red")

# ... [rest of your code]
```

Make sure to replace `results[0].pred.xyxy.tolist()` with `results.xyxy[0]` as `results.xyxy` is the correct attribute to access the detections. Also, ensure that the class index for 'weed' matches the one in your dataset. Let me know if this helps or if you have any more questions! 😊

**Comment by toula018** [comment]
hi @glenn-jocher 
i changed it but same error 


import os
from PIL import Image, ImageDraw
from ultralytics import YOLO

# Load your custom trained YOLO model
model = YOLO("best.pt")

# Path to the folder containing images
folder_path = r"C:\Users\derra\OneDrive\Desktop\dataset0\test\weed"

# Create a directory to save processed images
output_folder = os.path.join(folder_path, "processed")
os.makedirs(output_folder, exist_ok=True)

# Iterate over the files in the folder
for filename in os.listdir(folder_path):
    if filename.endswith((".jpg", ".png", ".jpeg")):
        # Full path to the image file
        image_path = os.path.join(folder_path, filename)
        
        # Perform inference on the image
        results = model(source=image_path, conf=0.5, save=False)

        # Load the image using Pillow
        image = Image.open(image_path)

        # Get the bounding boxes from the YOLO results
        boxes = results.xyxy  # Access bounding boxes from results

        # Create a drawing object
        draw = ImageDraw.Draw(image)

        # Define the radius of the filled circle
        radius = 5

        # Loop over each detection in the first image of the batch
        for *xyxy, conf, cls in results.xyxy[0]:  # results.xyxy is a list of tensors
        # Check if the class index corresponds to the class you want to visualize (e.g., "weed")
          if cls == 1:  # Assuming "weed" class has index 1
        # Get the bounding box coordinates
           x1, y1, x2, y2 = xyxy

        # Calculate the center coordinates of the bounding box
           x_center = (x1 + x2) / 2
           y_center = (y1 + y2) / 2

        # Draw a filled circle at the center coordinates
           draw.ellipse([(x_center - radius, y_center - radius), (x_center + radius, y_center + radius)], fill="red")


        # Save the image with filled circles drawn at the center coordinates
        processed_image_path = os.path.join(output_folder, filename)
        image.save(processed_image_path)

        print(f"Processed and saved: {processed_image_path}")

print("All images processed and saved.")


 the error occured 'AttributeError: 'list' object has no attribute 'xyxy'

**Comment by toula018** [comment]
hi @glenn-jocher
Thank you for your suggestion!

I tried implementing the solution you provided, but I'm still encountering the same AttributeError on the line where I attempt to access results.xyxy

the error occured 'AttributeError: 'list' object has no attribute 'xyxy'

I'm wondering if you have any additional insights or if there's something specific I should check to resolve this issue.

Thank you again for your help

**Comment by glenn-jocher** [comment]
@toula018 hi there! 😊 It seems like there might be a slight mix-up with accessing the results. The `results` object should have an attribute `xyxy` if it's the output of the `model()` call. However, if `results` is a list, it might mean that you're trying to access the attribute on the list itself rather than the individual result objects within the list.

Here's a quick check you can do:

```python
# Perform inference
results = model(source=image_path)

# Check if results is a list and has the correct attribute
if isinstance(results, list) and hasattr(results[0], 'xyxy'):
    # Access the xyxy attribute
    detections = results[0].xyxy
    # Now you can loop through the detections
    for detection in detections:
        # Your processing code here
else:
    print("The results object doesn't have the 'xyxy' attribute. Please check the model output.")
```

This code snippet checks if `results` is a list and if the first item has the `xyxy` attribute. If it doesn't, it prints a message to help you debug further.

Let me know if this resolves the issue or if you need more assistance!

**Comment by toula018** [comment]
ok , thank u 
i found the sol and it worked

**Comment by glenn-jocher** [comment]
Hey @toula018, glad to hear you found a solution that worked! 👍

To visualize all bounding box centers for class ID 1, you'll want to make sure you're drawing on the same image for each detection. Here's a small tweak to your code:

```python
# ... [previous code]

# Load the image using Pillow just once per image
image = Image.open(image_path)
draw = ImageDraw.Draw(image)

# Iterate over the results
for result in results:
    boxes = result.boxes  # Boxes object for bbox outputs
    class_indices = boxes.cls  # Retrieve class indices

    # Iterate over the detected objects
    for i, class_index in enumerate(class_indices):
        # Check if the detected object corresponds to "weed" (class ID 1)
        if int(class_index) == 1:  # Make sure this matches your class ID for 'weed'
            # Extract bounding box coordinates
            box_coordinates = boxes.xyxy[i].tolist()

            # Calculate center coordinates
            x_center = (box_coordinates[0] + box_coordinates[2]) / 2
            y_center = (box_coordinates[1] + box_coordinates[3]) / 2

            # Define the radius of the filled circle
            radius = 5

            # Draw a filled circle at the center coordinates
            draw.ellipse([(x_center - radius, y_center - radius), 
                          (x_center + radius, y_center + radius)], 
                         fill="red")

# Save the image with filled circles drawn at the center coordinates
processed_image_path = os.path.join(output_folder, filename)
image.save(processed_image_path)

print(f"Processed and saved: {processed_image_path}")

# ... [rest of your code]
```

This way, you're drawing all the centers on one image and then saving it. Let me know if this helps or if you have any more questions! 😊
