### ISSUE TITLE
YOLOv8 Extra Large Segmenation Model Visual

### ISSUE THREAD

**Issue by zshariff6506** [ultralytics/ultralytics#8348]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi there, hope you are doing well.

I am working on a research project, and I am looking for a visual that I could use to show the framework of a YOLOv8 extra large segmentation model using the default settings. I found this when running the model in CLI, which if i'm not wrong, shows the framework of the model.

![Screenshot 2024-02-20 at 6 18 02 PM](https://github.com/ultralytics/ultralytics/assets/102487652/903d1bda-a4b8-4f44-88e3-760a308f4ba2)

**Comment by zshariff6506** [comment]
Thank you so much!
It’s going to help me A TON!

**Comment by glenn-jocher** [comment]
@zshariff6506 you're welcome! 😊 If you need any more help or have questions along the way, just drop a message. Happy to assist! Good luck with your project! 🚀
