### ISSUE TITLE
fail to export classify model to paddle format

### ISSUE THREAD

**Issue by mrljwlm** [ultralytics/ultralytics#835]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I got failure when i try to export a classify model yolov8s-cls.pt to paddle format:
PaddlePaddle: export failure  1.5s: list assignment index out of range
![image](https://user-images.githubusercontent.com/23266835/217048993-a27a12d6-63b5-4ce7-b880-34ddb339bb10.png)

**How to export this paddle format model successfully?**

**Comment by pderrenger** [comment]
@mrljwlm hi there! It seems like you're encountering an issue while trying to export the classify model yolov8s-cls.pt to paddle format. The error message "list assignment index out of range" typically indicates that the index being accessed is outside the bounds of the list. 

To successfully export the model to paddle format, you might want to double-check the input specifications and ensure that the model is compatible with the export format. Additionally, reviewing the documentation on model export and format compatibility might provide some insights on resolving this issue.

Let me know if you need further assistance! Good luck with the export process!

**Comment by glenn-jocher** [comment]
Hi @pderrenger! It looks like you've run into a hiccup while exporting to the PaddlePaddle format. This error usually points to a mismatch between the expected data structure and what's being provided. I recommend revisiting the export documentation to ensure all prerequisites are met and the model is indeed exportable to the PaddlePaddle format.

If the problem persists, please provide more details on the steps you've taken so we can better assist you. We're here to help you through the process! 🛠️
