### ISSUE TITLE
How to track two images

### ISSUE THREAD

**Issue by SSTato** [ultralytics/ultralytics#8354]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to track two images? I have two images, which can be understood as adjacent frames of a video. How can I use model.track to track these two images and make the target IDs in them continuous.
like this:
```
from ultralytics import YOLO
import cv2
# Load a model
model = YOLO('yolov8n.pt')  # pretrained YOLOv8n model

# Run batched inference on a list of images
results = model.track(['frame.jpg', 'frame1.jpg'], persist=True)  # return a list of Results objects

# Process results list
for result in results:
    out = result.plot()
    cv2.imwrite(result.path.split('/')[1], out)
```
But the IDs of the two images in the obtained results are not continuous, what should I do?
![image](https://github.com/ultralytics/ultralytics/assets/93987794/dff1c925-f9c1-4349-8aa7-bc20710f3564)
![image](https://github.com/ultralytics/ultralytics/assets/93987794/31b1097c-6f23-469d-b4b2-8bc249de9638)

**Comment by SSTato** [comment]
Also, I would like to know if a model file similar to. pt was used when using BOTrack for target tracking?

**Comment by glenn-jocher** [comment]
@SSTato to ensure continuous tracking IDs across multiple images, you should use the `persist=True` argument within a loop that processes the images sequentially. Here's a modified version of your code that should maintain continuous IDs:

```python
from ultralytics import YOLO
import cv2

# Load a model
model = YOLO('yolov8n.pt')  # pretrained YOLOv8n model

# Initialize tracking
model.track(persist=True)  # initialize persistent tracking

# List of image paths
image_paths = ['frame.jpg', 'frame1.jpg']

# Process each image sequentially
for path in image_paths:
    # Read image
    img = cv2.imread(path)
    
    # Run tracking on the image
    result = model.track(img, persist=True)  # track and maintain IDs
    
    # Plot and save results
    out = result[0].plot()
    cv2.imwrite(path.split('/')[1], out)

# Reset tracking when done
model.track(persist=False)  # reset tracking
```

Regarding your additional question, when using BOTrack for target tracking, you would typically use a model file that has been trained for object detection tasks, such as a `.pt` file in the case of YOLOv8. This file contains the weights and architecture information necessary for the model to perform detection, which is the first step in the tracking process. The tracking algorithm then uses the detections to maintain object identities over time.
