### ISSUE TITLE
I can't load the Coco-Pose dataset because the github page gives me a 404. Where can I download it?

### ISSUE THREAD

**Issue by RamesChan** [ultralytics/ultralytics#8355]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Can't download label of coco-pose dataset.
![Screenshot 2024-02-21 152330](https://github.com/ultralytics/ultralytics/assets/128948774/eee87b74-00eb-4257-bf1f-9d1fdee72576)

### Environment

On google Colab T4 GPU

### Minimal Reproducible Example

```
url = 'https://github.com/ultralytics/yolov5/releases/download/v1.0/'
urls = [url + 'coco2017labels-pose.zip']  # labels
download(urls, dir=dir.parent)

```
```
WARNING ⚠️ Skipping /coco2017labels-pose.zip unzip as destination directory /coco-pose is not empty.
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@RamesChan COCO-Pose autodownload works for me. If you're getting a warning that your destination directory is not empty then delete your destination directory.

<img width="1372" alt="Screenshot 2024-02-21 at 11 18 09" src="https://github.com/ultralytics/ultralytics/assets/26833433/4c1aca44-62ad-4429-ae18-eb723b1436e2">
