### ISSUE TITLE
add webcam feature

### ISSUE THREAD

**Issue by himanshushukla12** [ultralytics/ultralytics#8367]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Need webcam feature

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@himanshushukla12 hi there! 👋

Great to hear that you're interested in contributing a webcam feature to YOLOv8! You can actually use webcams right now by setting the `source` to `0` for your system's default webcam, or `1`, `2`, etc., for additional webcams. Here's a quick example using the CLI:

```bash
yolo detect predict model=yolov8n.pt source=0
```

And here's how you can do it in Python:

```python
from ultralytics import YOLO

# Load the model
model = YOLO('yolov8n.pt')

# Run prediction on the default webcam
results = model.predict(source=0)
```

If you have a specific feature in mind that enhances the webcam functionality, we'd love to see it! Feel free to fork the repo, add your feature, and submit a PR. If you need any assistance, don't hesitate to ask. Looking forward to your contribution! 🚀
