### ISSUE TITLE
The value of the loss function during training suddenly decreases to 0

### ISSUE THREAD

**Issue by laogonggong847** [ultralytics/ultralytics#8369]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hello @glenn-jocher :
There is no doubt that YOLO V8 is one of the most advanced methods available in the field of object detection.

**YOLO V8 is very powerful, but for me I only needed the "detection" part of it, so I rewrote and simplified the whole project. In all my previous detection tasks, the overall performance of the model trained with YOLO v8 and the model trained with my own rewrite was about the same, because all my network structure and loss function as well as the pre-trained model were consistent with the official one.**

I can make sure that the whole project I rewrote should be fine, because I got a result that was pretty much the same as the official YOLO V8 when I trained it on a lot of different training sets.

But when I train on a batch of images of size "4096x3000" I get an error, and my rewritten model changes the value of the loss function to 0 after some time of training. ***But the official YOLO V8 code for training the same batch of samples and keeping the data exactly the same doesn't show this situation***

The sample set specifics are as follows: 100 sheets for the training set and 30 sheets for the validation set. The size of each image is 4096x3000. we have only one class, while the class will appear only once on each 4096x3000 image, but randomly in any position.

We use visdom to visualize the return value of the loss function ```loss.sum() * batch_size```, please refer to the following link for the specific code.
https://github.com/ultralytics/ultralytics/blob/2945cfc6ef9e99df2d6589982283d6c68c1d461b/ultralytics/utils/loss.py#L339

The resulting graph is shown below:
----
(a) YOLO V8 official training code and without using the pre-trained model
![V8未加载预训练模型-train20](https://github.com/ultralytics/ultralytics/assets/81297486/d47f74c2-edc5-459a-9b99-68911aa28780)

----
(b) Own training code and not using pre-trained models
![1b9d0f37035c9fcecd2964a9588ddb68](https://github.com/ultralytics/ultralytics/assets/81297486/fc4b42f3-4687-46df-902e-eabc7f904567)

----
(c) YOLO V8 official training code that uses pre-trained models
![80b93439e30f93e254e51d162509486a](https://github.com/ultralytics/ultralytics/assets/81297486/b1875b48-c156-4f33-acef-951b77f2cb54)
 is too large resulting in what appears to be 0, but is actually still a normal value of about 3.**

----
(d) own training code that uses pre-trained models
![9d492a965751c5b93e5cb696f2047807](https://github.com/ultralytics/ultralytics/assets/81297486/c26a27ae-bc22-400b-bb1e-55e2fe009601)

----
My specific questions are as follows:
My rewritten code based on V8 should not be wrong, because we achieve the same results as V8 in many different detection tasks. But this time the task is essentially a small sample detection and the target (50x50) is a really small percentage of the whole image (). But while V8 was able to detect my trained images at very low confidence, my own trained model was completely unusable in this task.
So I would like to ask what factors could be the cause of it being 0 and how should I locate and fix it. And looking at the four images it's easy to see that the trend is exactly the same at the beginning of the training, but after a certain point of training my network shows a clear error.

It's worth noting that the sample set is exactly the same, the parameters during training are the same, the network and loss function are the same, and lowering the learning rate my network still does this.
I hope to hear your professional analysis and constructive comments!

Thank you very much

**Comment by laogonggong847** [comment]
hello @glenn-jocher 
Thank you very much for your patience and professional opinion on the advice you gave:
**(1):** Thank you very much, I overlooked this point in my previous troubleshooting, and I am very grateful to you for pointing it out, but I am still puzzled. Assuming that there is indeed an inconsistency in numerical accuracy, why did I not find any difference in the other sample sets before, but this problem appeared in the detection of such a very small target?
**(2):** You are really awesome, indeed when I augmented the data I didn't use the V8 code exclusively but used some simple augmentation methods based on the original YOLO V5, could this have caused the problem? Do the different data enhancement methods have less impact in large object detection and huge impact in small object?
**(3, 4, 5, 6):** Yes all the training parameters are the same and I used the same ```"nn.utils.clip_grad_norm_"``` as V8. The learning rate and optimizer I keep with the official is the same, I will follow up with further modifications and testing, and I will further detailed debugging for problem (1) and problem (2).
Thank you very much for your reply, and I would also appreciate your answers to the new questions (1) and (2). I apologize for the delay and thank you again!

**Comment by glenn-jocher** [comment]
Hello @laogonggong847,

Glad to hear the suggestions were helpful! 🌟

Regarding your new questions:
- **(1):** The issue with numerical precision might not have been apparent in other datasets due to the relative scale of objects to the image size. With very small objects, the gradients can become quite small, and if the precision isn't high enough, they might underflow to zero. It's a bit like looking for a needle in a haystack; the smaller the needle, the harder it is to find unless you're very meticulous.

- **(2):** Absolutely, data augmentation can have a different impact depending on the object size. For small objects, even minor changes in augmentation can lead to significant differences in the input to the model, potentially affecting the loss. It's always good to ensure that augmentation techniques are suitable for the scale of objects you're working with.

Keep experimenting and debugging, and you're likely to pinpoint the issue. If you need further assistance, feel free to reach out. Happy coding! 🚀

**Comment by laogonggong847** [comment]
Hello @glenn-jocher 
I have further analyzed my YOLO V8 detection code after rewriting it from the source code:
Thank you very much for your many constructive comments at the time, which were very helpful.
Now I seem to have localized the problem, but I can't figure out the reason for this problem, and would like to hear your answer, thank you very much！

I print all the results before ```return loss.sum() * batch_size, loss.detach()  # loss(box, cls, dfl)```(https://github.com/ultralytics/ultralytics/blob/2945cfc6ef9e99df2d6589982283d6c68c1d461b/ultralytics/utils/loss.py#L243-L247)

The new code is as follows:
```
        loss[0] *= 7.5  # box gain
        loss[1] *= 0.5  # cls gain
        loss[2] *= 1.5  # dfl gain

        print("loss:", round(loss.sum().detach().item() * batch_size, 3),
              "   box_loss:", round(loss[0].detach().item(), 3),
              "   cls_loss:", round(loss[1].detach().item(), 3),
              "   dfl_loss:", round(loss[2].detach().item(), 3),
              )

        return loss.sum() * batch_size
```

The results at the beginning of the training are as follows
```
loss: 2126.606    box_loss: 0.0    cls_loss: 265.826    dfl_loss: 0.0
loss: 2121.116    box_loss: 0.0    cls_loss: 265.139    dfl_loss: 0.0
loss: 2121.452    box_loss: 0.0    cls_loss: 265.181    dfl_loss: 0.0
loss: 2131.094    box_loss: 0.0    cls_loss: 266.387    dfl_loss: 0.0
loss: 2128.647    box_loss: 0.0    cls_loss: 266.081    dfl_loss: 0.0
loss: 2124.07    box_loss: 0.0    cls_loss: 265.509    dfl_loss: 0.0
loss: 2112.179    box_loss: 0.0    cls_loss: 264.022    dfl_loss: 0.0
loss: 2118.858    box_loss: 0.0    cls_loss: 264.857    dfl_loss: 0.0
loss: 2128.658    box_loss: 0.0    cls_loss: 266.082    dfl_loss: 0.0
loss: 2113.097    box_loss: 0.0    cls_loss: 264.137    dfl_loss: 0.0
loss: 2124.653    box_loss: 0.0    cls_loss: 265.582    dfl_loss: 0.0
loss: 2117.872    box_loss: 0.0    cls_loss: 264.734    dfl_loss: 0.0
loss: 2133.667    box_loss: 0.0    cls_loss: 266.708    dfl_loss: 0.0
loss: 2120.084    box_loss: 0.0    cls_loss: 265.01    dfl_loss: 0.0
```

But when it's trained for a while, it looks like this
```
loss: 0.004    box_loss: 0.0    cls_loss: 0.001    dfl_loss: 0.0
loss: 0.005    box_loss: 0.0    cls_loss: 0.001    dfl_loss: 0.0
loss: 0.005    box_loss: 0.0    cls_loss: 0.001    dfl_loss: 0.0
loss: 0.005    box_loss: 0.0    cls_loss: 0.001    dfl_loss: 0.0
loss: 0.005    box_loss: 0.0    cls_loss: 0.001    dfl_loss: 0.0
loss: 0.005    box_loss: 0.0    cls_loss: 0.001    dfl_loss: 0.0
loss: 0.002    box_loss: 0.0    cls_loss: 0.0    dfl_loss: 0.0
loss: 0.001    box_loss: 0.0    cls_loss: 0.0    dfl_loss: 0.0
loss: 0.0    box_loss: 0.0    cls_loss: 0.0    dfl_loss: 0.0
loss: 0.0    box_loss: 0.0    cls_loss: 0.0    dfl_loss: 0.0
loss: 0.0    box_loss: 0.0    cls_loss: 0.0    dfl_loss: 0.0
loss: 0.0    box_loss: 0.0    cls_loss: 0.0    dfl_loss: 0.0
loss: 0.0    box_loss: 0.0    cls_loss: 0.0    dfl_loss: 0.0
loss: 0.0    box_loss: 0.0    cls_loss: 0.0    dfl_loss: 0.0
loss: 0.0    box_loss: 0.0    cls_loss: 0.0    dfl_loss: 0.0
loss: 0.0    box_loss: 0.0    cls_loss: 0.0    dfl_loss: 0.0
loss: 0.0    box_loss: 0.0    cls_loss: 0.0    dfl_loss: 0.0
loss: 0.0    box_loss: 0.0    cls_loss: 0.0    dfl_loss: 0.0
loss: 0.0    box_loss: 0.0    cls_loss: 0.0    dfl_loss: 0.0
```
**That's what I was talking about before I showed up.**
----

But I tested it using the source code of YOLO V8, and when I did a print of the same parameters I found that：
```
loss: 15.711    box_loss: 0.0    cls_loss: 15.711    dfl_loss: 0.0
loss: 498.489    box_loss: 2.128    cls_loss: 121.214    dfl_loss: 1.28
loss: 15.785    box_loss: 0.003    cls_loss: 15.781    dfl_loss: 0.001
loss: 16.086    box_loss: 0.074    cls_loss: 15.992    dfl_loss: 0.02
loss: 480.223    box_loss: 1.919    cls_loss: 117.075    dfl_loss: 1.063
```
**Q1: At the very beginning the loss values of A and B are also 0 but later the official code updates these values but not in my code. This is my first question**


----
----
Another problem I have is this, during validation, for the following code:
https://github.com/ultralytics/ultralytics/blob/59ed47c4482a09d0261b8801791258a241e562d8/ultralytics/engine/validator.py#L180-L82

I ignored this code during the rewrite process because at the time I didn't think it would have any effect on the model I was training, I wonder if this is the right idea?

**Q2: My second question is what is the effect of this code and is it because it is causing my loss function not to be updated**


I'm sorry to bother you again and thank you very much for your careful and professional help!

**Comment by glenn-jocher** [comment]
Hello @laogonggong847,

I'm glad to hear the previous suggestions were helpful! Let's dive into your new findings:

**Q1:** The initial zero values for `box_loss` and `dfl_loss` indicate that the model might not be detecting objects correctly at the start, which is not uncommon. The official YOLOv8 code likely updates these values as the model begins to learn and detect objects. If your code doesn't update these values, it might be due to differences in how the model is initialized, trained, or how the losses are accumulated and backpropagated. Double-checking the training loop and ensuring that gradients are correctly computed and applied could help.

**Q2:** The code snippet you mentioned is crucial for ensuring that the model's predictions are aligned with the ground truth during validation. It adjusts the model's predictions based on the input size, which can significantly impact the model's perceived performance and the calculated loss. Skipping this step might lead to inaccurate validation results, making it seem like the model isn't learning as expected. Including this step in your validation process should provide a more accurate assessment of your model's performance.

No bother at all! It's great to see your dedication to understanding and improving your model. Keep up the good work, and feel free to reach out if you have more questions. 🚀

**Comment by laogonggong847** [comment]
hello @glenn-jocher 👍
Thank you for your patience, but for the same dataset, I have now rewritten my data augmentation method (transform) and made sure that the transform is exactly the same as the official one. Although there may be randomness in the transform, why the official "box loss" and "cls_loss" can be updated but not mine. This still confuses me, how can I better localize this issue further, or which part of the code should I troubleshoot more carefully so that I can better solve this issue?
Thanks again for your patient help and professional answers! Thank you very much！！

**Comment by glenn-jocher** [comment]
@laogonggong847 hello there! 👋

Great to hear you've aligned your data augmentation method with the official one! If you're still facing issues with the "box loss" and "cls_loss" not updating, here are a couple of quick tips:

- **Check Gradient Flow:** Ensure gradients are flowing through your network. You can do this by printing gradients after a backward pass to see if they're non-zero.
  
  ```python
  for name, param in model.named_parameters():
      if param.grad is not None:
          print(name, param.grad.abs().sum())  # Sum of absolute gradients
  ```

- **Inspect Learning Rate:** Sometimes, if the learning rate is too low or too high, it might affect loss updates. Double-check your learning rate settings.

- **Review Loss Calculation:** Make sure the loss calculation in your code matches the official implementation. Pay special attention to any weighting or normalization applied.

- **Data Loader Check:** Verify that your data loader correctly applies the transformations and that the batches are correctly formed.

Troubleshooting these areas should help you get closer to resolving the issue. Keep up the good work, and don't hesitate to reach out if you need more assistance. Happy coding! 🚀

**Comment by laogonggong847** [comment]
Hello @glenn-jocher :
Thank you very much for all the help you have given me so many days! And thanks to you and your team for contributing to YOLO V8 having such an active and productive community:

Thinking that I may have tentatively found the problem, I rechecked the issue in question along your lines, and in the end I found an interesting phenomenon:

With the same sample set and the same hyperparameters, and iterating through 200 epochs with my code, I found an interesting phenomenon. Three times, using my rewritten code, at one of the epochs (randomly and not regularly), both "box_loss" and "cls_loss" went to 0, and after that, these two parameters always stayed at 0 and never changed. 
With the same dataset, the same code, and the same super parameter, except for these three times, "box_loss" and "cls_loss" are very normal in other times of training, and have never appeared to be 0 until the end of the training. (It's worth emphasizing that the random inside each tranform is not fixed)

I think the difference may be caused by the randomness in the transform, may I ask YOLO V8 in the detection of particularly small targets, the random enhancement of the transform may have caused the phenomenon that the gradient is 0 during training.

I apologize for taking up your valuable time again and look forward to your reply, thank you very much!

**Comment by glenn-jocher** [comment]
@laogonggong847 hello there! 🌟

I'm thrilled to hear about your progress and the insights you've gained into your issue. It's fantastic that you've narrowed down the potential cause to the randomness in the transform. Indeed, randomness in data augmentation can sometimes lead to unexpected behaviors, especially with small targets where slight changes can have a significant impact.

One way to further investigate this could be to temporarily reduce or eliminate the randomness in your transforms and observe if the issue persists. This could help confirm if the randomness is the root cause. For example:

```python
# Example of reducing randomness in transforms
transform = transforms.Compose([
    transforms.Resize((640, 640)),
    # Potentially problematic random transform commented out
    # transforms.RandomCrop(512),
    transforms.ToTensor(),
])
```

If the problem disappears with less randomness, you might consider adjusting the parameters of your random transforms or applying them conditionally based on the target size.

Thank you for your kind words and for being part of the YOLOv8 community. Your detailed observations and willingness to dive deep into troubleshooting are invaluable. Keep up the great work, and don't hesitate to reach out if you have more questions or findings! 🚀

**Comment by laogonggong847** [comment]
Thank you very much for your professional answers and patience, I think I have tentatively solved the problem. This is thanks to your selfless help and guidance for so many days, thank you again!

I now have a new problem, and it's not for small object detection, but this occurs occasionally for both large and small objects.
In fact this may not be a problem, but a normal occurrence. It's just that I'd like to confirm why this occurs and if it can be circumvented~

I use **visdom** to display ```Precision``` and ```Recall``` in real time during validation. The horizontal coordinate is the epoch and the vertical coordinate is the corresponding value of the epoch. The horizontal coordinate is the epoch and the vertical coordinate is the value corresponding to ```Precision``` and ```Recall```

I will specify my problem below in relation to the graphs, which are for the same sample set (the training and validation sets also have exactly the same number of images and number of images) and exactly the same hyperparameters for training.
![de3d57f7eda7477c7da25ce1ff52fe66](https://github.com/ultralytics/ultralytics/assets/81297486/096476b1-6ec6-406c-a03a-aa16b5d10842)
![b8ac45d3e9bbb8630b1cf3cafcfafecd](https://github.com/ultralytics/ultralytics/assets/81297486/47350ce3-192f-45a8-9850-1b2354f8bb7e)

My first question is why do the P and R values suddenly drop to 0 during training, not only at the beginning but often in the middle of training. I would like to know if this phenomenon is normal, and why sometimes the P and R values suddenly drop to 0 when they are already at a high level, and why this sudden drop to 0 may occur several times during a training session. What are the reasons for this phenomenon and how can I avoid it?

My second question is in the actual training, these two plots are under the same parameters for the same sample of the training results, but why their final difference is relatively large, the validation process should not exist in the training of the various enhancement operations on the data set of the pit of the randomness of the impact. This leads to a large difference in the performance of the model I trained twice, and I want to know if this is normal!

**Comment by glenn-jocher** [comment]
@laogonggong847 hello there! 🌟

I'm thrilled to hear you've made progress with your previous issue, and it's great to have you back with new questions. Let's dive in:

1. **Sudden Drops in Precision and Recall:** The sudden drops to 0 for Precision (P) and Recall (R) during training could be attributed to several factors, including learning rate spikes, data augmentation anomalies, or even rare instances in your dataset that momentarily confuse the model. It's not entirely uncommon, especially with stochastic training processes. To mitigate this, you might consider employing learning rate schedulers or adjusting your data augmentation strategies. Also, closely monitoring the loss values during these drops could provide additional insights.

2. **Variability Between Training Sessions:** The differences you're observing between training sessions, despite using the same parameters and dataset, highlight the inherent randomness in deep learning training processes. This can stem from initial weight randomization, data shuffling, or augmentation techniques. While some variability is normal, significant differences might suggest that the model is sensitive to these initial conditions. Ensuring a stable and robust model might involve more extensive hyperparameter tuning or even increasing your dataset size to reduce variance.

Remember, deep learning models can sometimes be a bit unpredictable, but with careful tuning and patience, you'll find the right balance. Keep experimenting, and feel free to share any further observations or questions! 🚀

**Comment by laogonggong847** [comment]
Hello @glenn-jocher 👍 
With your selfless help and efficient guidance I have a better understanding of the YOLO V8 detection code, thank you for your patience and professionalism!

After the model loading pre-training model is done, I printed the corresponding ```"self.model.state_dict()"```: as follows
https://github.com/ultralytics/ultralytics/blob/7451ca1f541f502f7df1c500a2f5f60fc35a0a84/ultralytics/engine/model.py#L639

When training with the official code, I ran the code twice without making any changes. At the same time, I saved the result of ```"self.model.state_dict()"``` in the same position in both runs in two txts for comparison, My pre-trained model is "yolov8m.pt" (This is the official pre-trained model).


Oddly enough, I was surprised to find that there was a discrepancy between the two results I got from the printout. And this difference is mainly in the following three places:

```'model.22.cv3.0.2.weight'```
![0cb42415290a3b11173b99de25dc0b3f](https://github.com/ultralytics/ultralytics/assets/81297486/6f640787-d3d3-492c-be61-c0278e258628)

----
``` 'model.22.cv3.1.2.weight'```
![bd4a6b96eca719b5f225c2f830be7daa](https://github.com/ultralytics/ultralytics/assets/81297486/264bba92-aafa-4382-ba24-5d3d1dab1a5c)

----
```'model.22.cv3.2.2.weight'```
![e1d6f1b0bfac9c1e778851462fec0f43](https://github.com/ultralytics/ultralytics/assets/81297486/416e1c3a-bf0e-46a2-9ea9-4ce55a2943b6)


**I checked the location of the three of them in the corresponding ```"yolov8m.onnx".```**

![35002b0d5e03d08bde2070b52c73547f](https://github.com/ultralytics/ultralytics/assets/81297486/0c2e886e-6d4c-4c9d-9c1f-5e8dab3e518a)

----

![afe04b4008ab5c71268703799bbfd9a9](https://github.com/ultralytics/ultralytics/assets/81297486/7f858a41-66d6-42ce-9bf7-fe5a07ac2868)

----

![7f68752b667f9d3b7a5ef59e0457ae95](https://github.com/ultralytics/ultralytics/assets/81297486/aef1e1a7-0afc-46d8-a757-f9824d841ffb)

I found that they seem to happen in two "Convs" directly before the "Contact" operation.

But to my surprise, for the different "Convs" in the three diagrams, the parameters in the "state_dict" corresponding to the previous "Conv" (Blue rectangle box) are the same! 

What is the reason for this, I am surprised, I thought that the "state_dict" of the model should be identical until I print this parameter.

**Comment by caoxulei921** [comment]
We encountered the same problem and eventually solved it. Hopefully, it can provide some help to others.In summary, the gradient needs to be turned off for the following parts when calculating the loss.

![image](https://github.com/user-attachments/assets/20018a3b-5263-474f-a9e4-da68789286e6)

![image](https://github.com/user-attachments/assets/16bce742-fa02-4e8a-bb71-01b23055a1b3)

**Comment by pderrenger** [comment]
Thank you for sharing your solution. It's great to hear you resolved the issue by turning off gradients for specific parts when calculating the loss. This insight could indeed be valuable for others facing similar challenges. If anyone else encounters this problem, please ensure you're using the latest version of the package to verify reproducibility. If the issue persists, feel free to provide additional details for further assistance.
