### ISSUE TITLE
val_batch*.jpg not displaying the same as Ultralytics HUB

### ISSUE THREAD

**Issue by eqsmy** [ultralytics/ultralytics#837]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My images and labels are displaying correctly on the Ultralytics HUB (as shown in the second and third screenshots below) but not on the val_batch*.jpg output created during training (as shown in the first image below). 

It appears that the label number (in this example, 54905.jpg) may be indicating the image two above it in the grid and the label right above it in the grid. I read other issues that say that the label files must be wrong if they're showing up incorrectly in val_batch*.jpg, but I've quadruple checked the formatting, it looks correct on the HUB, and the image numbers on that val_batch output simply don't align with the images shown. Any explanation/guidance would be much appreciated. 

<img width="1470" alt="Screen Shot 2023-02-06 at 12 11 27 PM" src="https://user-images.githubusercontent.com/34151362/217075576-05c66111-c656-482b-a92b-1f7484d5a0ef.png">
<img width="437" alt="Screen Shot 2023-02-06 at 12 13 57 PM" src="https://user-images.githubusercontent.com/34151362/217075663-1aa3e19a-78e5-4c3e-a0c6-a36503e00889.png">
<img width="1271" alt="Screen Shot 2023-02-06 at 12 14 05 PM" src="https://user-images.githubusercontent.com/34151362/217075667-5dc7eb35-53b2-4f66-9a9b-25e2e976b038.png">

**Comment by AyushExel** [comment]
@kalenmike might be able to provide some information on this

**Comment by kalenmike** [comment]
@AyushExel I missed this thread. I believe the OP is saying that the plotting is correct on HUB, that means that the validation plotting in YOLOv8 is off, as the HUB is reading the same label files.

**Comment by glenn-jocher** [comment]
@eqsmy @kalenmike @AyushExel we recently fixed a bug in both YOLOv5 and YOLOv8 in https://github.com/ultralytics/yolov5/pull/11134 first raised in https://github.com/ultralytics/yolov5/issues/11133

This will be resolved in HUB once we migrate to the latest YOLOv8 code, which should occur at the end of this month.
