### ISSUE TITLE
How to Sorting Bonding Box 

### ISSUE THREAD

**Issue by arifalbastomi** [ultralytics/ultralytics#8372]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

how to sort result (bonding box [x,y,w,h]) from left to right than down and left to right again
like picture below
![Capture](https://github.com/ultralytics/ultralytics/assets/11969360/8816a86c-1747-4cf7-9e28-7035198098ae)
and also sort from top to bottom than to right and from top to bottom again
![Capture2](https://github.com/ultralytics/ultralytics/assets/11969360/5816318f-c7ff-4eb0-a2b4-af3795542c67)
Thanks

**Comment by glenn-jocher** [comment]
@arifalbastomi hi there! 👋 Sorting bounding boxes can be done by manipulating the results after detection. Here's a quick example of how you might sort the bounding boxes from left to right and then top to bottom:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('yolov8n.pt')

# Run inference
results = model('path/to/image.jpg')

# Get bounding boxes
boxes = results.boxes.xyxy[0]  # Assuming first image in batch

# Sort boxes left to right, then top to bottom
sorted_boxes = sorted(boxes, key=lambda x: (x[1], x[0]))

# Now sorted_boxes contains the bounding boxes sorted as requested
```

For sorting top to bottom and then left to right, you would adjust the key in the sorted function:

```python
# Sort boxes top to bottom, then left to right
sorted_boxes = sorted(boxes, key=lambda x: (x[0], x[1]))
```

Remember to replace `'path/to/image.jpg'` with the path to your actual image. Hope this helps! 😊 Let us know if you have any more questions.
