### ISSUE TITLE
New version of DDP training error--YOLOv8.1.17

### ISSUE THREAD

**Issue by Hongru0306** [ultralytics/ultralytics#8383]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Multi-GPU

### Bug

When I turn on DDP training, it creates a new config script in the home folder by default, which is temporary when I want to specify the path with os. The same training code I trained with version 8.02 was fine, after updating the obb I had problems.
```
Ultralytics YOLOv8.1.17 🚀 Python-3.8.18 torch-1.13.1+cu116 CUDA:0 (NVIDIA GeForce RTX 3090 Ti, 24248MiB)
                                                            CUDA:1 (NVIDIA GeForce RTX 3090, 24260MiB)
WARNING ⚠️ Upgrade to torch>=2.0.0 for deterministic training.
engine/trainer: task=detect, mode=train, model=yolov8s.yaml, data=dataset/DOTAv1.yaml, epochs=300, time=None, patience=100, batch=8, imgsz=1280, save=True, save_period=-1, cache=False, device=0, 1, workers=8, project=runs/train, name=exp6, exist_ok=False, pretrained=False, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=False, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/train/exp6
Overriding model.yaml nc=80 with nc=15

                   from  n    params  module                                       arguments                     
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]                 
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]             
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]           
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]              
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]           
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]                 
 22        [15, 18, 21]  1   2121853  ultralytics.nn.modules.head.Detect           [15, [128, 256, 512]]         
YOLOv8s summary: 225 layers, 11141405 parameters, 11141389 gradients, 28.7 GFLOPs

DDP: debug command /CV/anaconda3/envs/rtdetr/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 47755 /home/xhr/.config/Ultralytics/DDP/_temp_o53uk8jg139849945195328.py
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/home/xhr/.config/Ultralytics/DDP/_temp_o53uk8jg139849945195328.py", line 6, in <module>
    from ultralytics.models.yolo.detect.train import DetectionTrainer
ModuleNotFoundError: No module named 'ultralytics'
Traceback (most recent call last):
  File "/home/xhr/.config/Ultralytics/DDP/_temp_o53uk8jg139849945195328.py", line 6, in <module>
    from ultralytics.models.yolo.detect.train import DetectionTrainer
ModuleNotFoundError: No module named 'ultralytics'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 134623) of binary: /CV/anaconda3/envs/rtdetr/bin/python
Traceback (most recent call last):
  File "/CV/anaconda3/envs/rtdetr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/CV/anaconda3/envs/rtdetr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/torch/distributed/run.py", line 766, in <module>
    main()
  File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/xhr/.config/Ultralytics/DDP/_temp_o53uk8jg139849945195328.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-02-22_19:32:14
  host      : xhr11223
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 134624)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-22_19:32:14
  host      : xhr11223
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 134623)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    results = model.train(data='dataset/DOTAv1.yaml', epochs=300, batch=8, imgsz=1280, pretrained=False, device='0, 1', 
  File "/CV/xhr_project/yolov8-obb/ultralytics/engine/model.py", line 644, in train
    self.trainer.train()
  File "/CV/xhr_project/yolov8-obb/ultralytics/engine/trainer.py", line 203, in train
    raise e
  File "/CV/xhr_project/yolov8-obb/ultralytics/engine/trainer.py", line 201, in train
    subprocess.run(cmd, check=True)
  File "/CV/anaconda3/envs/rtdetr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/CV/anaconda3/envs/rtdetr/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '47755', '/home/xhr/.config/Ultralytics/DDP/_temp_o53uk8jg139849945195328.py']' returned non-zero exit status 1.
```

### Environment

Ultralytics YOLOv8.1.17 🚀 Python-3.8.18 torch-1.13.1+cu116 CUDA:0 (NVIDIA GeForce RTX 3090 Ti, 24248MiB)
                                                            CUDA:1 (NVIDIA GeForce RTX 3090, 24260MiB)
                                                         

### Minimal Reproducible Example

from ultralytics import YOLO
model = YOLO('yolov8s-obb.yaml')
# Train the model
results = model.train(data='dataset/DOTAv1.yaml', epochs=300, batch=8, imgsz=1280, pretrained=False, device='0, 1', 
                      project='runs/train', name='exp', amp=False)

### Additional

This error has been bothering me for a long time and I would like to have your answer!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Hongru0306 hey there! 👋 It looks like you're encountering a `ModuleNotFoundError` after updating to YOLOv8.1.17 and attempting DDP training. This error typically indicates that Python can't find the `ultralytics` module in your environment.

Could you please try the following steps to see if it resolves the issue?

1. Ensure that the `ultralytics` package is installed in your current Python environment.
2. Verify that your Python environment is activated when running the training script.
3. Check if the PYTHONPATH environment variable includes the path to the `ultralytics` package.

Here's a quick way to check and install the `ultralytics` package:

```bash
pip install ultralytics
```

And to verify the PYTHONPATH:

```bash
echo $PYTHONPATH
```

If the issue persists, it might be helpful to provide the full directory structure of where the `ultralytics` package is installed, as well as the output of `pip list` to ensure the package is indeed present.

Let's get this sorted out! 🛠️

**Comment by Hongru0306** [comment]
> @Hongru0306 hey there! 👋 It looks like you're encountering a `ModuleNotFoundError` after updating to YOLOv8.1.17 and attempting DDP training. This error typically indicates that Python can't find the `ultralytics` module in your environment.@hongru0306 嘿那里！ 👋 更新到 YOLOv8.1.17 并尝试 DDP 训练后，您似乎遇到了 `ModuleNotFoundError` 。此错误通常表示 Python 在您的环境中找不到 `ultralytics` 模块。
> 
> Could you please try the following steps to see if it resolves the issue?您能否尝试以下步骤看看能否解决问题？
> 
> 1. Ensure that the `ultralytics` package is installed in your current Python environment.确保 `ultralytics` 包已安装在您当前的 Python 环境中。
> 2. Verify that your Python environment is activated when running the training script.运行训练脚本时验证您的 Python 环境是否已激活。
> 3. Check if the PYTHONPATH environment variable includes the path to the `ultralytics` package.检查 PYTHONPATH 环境变量是否包含 `ultralytics` 包的路径。
> 
> Here's a quick way to check and install the `ultralytics` package:这是检查和安装 `ultralytics` 包的快速方法：
> 
> ```shell
> pip install ultralytics
> ```
> 
> And to verify the PYTHONPATH:并验证 PYTHONPATH：
> 
> ```shell
> echo $PYTHONPATH
> ```
> 
> If the issue persists, it might be helpful to provide the full directory structure of where the `ultralytics` package is installed, as well as the output of `pip list` to ensure the package is indeed present.如果问题仍然存在，提供 `ultralytics` 软件包安装位置的完整目录结构以及 `pip list` 的输出可能会有所帮助，以确保该软件包确实存在。
> 
> Let's get this sorted out! 🛠️让我们来解决这个问题吧！ 🛠️

Thank you very much for your reply, but I want to do my own algorithm improvement experiments and will change some of the code, I don't want to change the source code inside Anaconda's environment, after I add some of my own changes, I still have a single card that is able to run, but the DDP will look for the code in the environment again and report that what I changed does not exist. I would like to ask if you have a better idea of how to solve this?
```
WARNING ⚠️ Upgrade to torch>=2.0.0 for deterministic training.
Traceback (most recent call last):
  File "/home/xhr/.config/Ultralytics/DDP/_temp__o31zs9u140556094763072.py", line 12, in <module>
    results = trainer.train()
  File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 208, in train
    self._do_train(world_size)
  File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 322, in _do_train
    self._setup_train(world_size)
  File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 236, in _setup_train
    ckpt = self.setup_model()
  File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 521, in setup_model
    self.model = self.get_model(cfg=cfg, weights=weights, verbose=RANK == -1)  # calls Model(cfg, weights)
  File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/models/yolo/obb/train.py", line 33, in get_model
    model = OBBModel(cfg, ch=3, nc=self.data["nc"], verbose=verbose and RANK == -1)
  File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 349, in __init__
    super().__init__(cfg=cfg, ch=ch, nc=nc, verbose=verbose)
  File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 274, in __init__
    self.yaml = cfg if isinstance(cfg, dict) else yaml_model_load(cfg)  # cfg dict
  File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 923, in yaml_model_load
    yaml_file = check_yaml(unified_path, hard=False) or check_yaml(path)
  File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/utils/checks.py", line 506, in check_yaml
    return check_file(file, suffix, hard=hard)
  File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/utils/checks.py", line 498, in check_file
    raise FileNotFoundError(f"'{file}' does not exist")
FileNotFoundError: 'yolov8s-modify-obb.yaml' does not exist
```

**Comment by Burhan-Q** [comment]
@Hongru0306 we have (at least) two instances of models training using 2x GPUs for experiments that use the code from `8.1.17`. We're not seeing the same issue, and if you've modified the code then there's really not much we can do to provide support.

I will point out that the first error text you provided does mention `ModuleNotFoundError: No module named 'ultralytics'` for the file `"/home/xhr/.config/Ultralytics/DDP/_temp_o53uk8jg139849945195328.py"` running in the environment `/CV/anaconda3/envs/rtdetr/bin/python` which may be a factor to the error you're experiencing. Again, if you modify the code, we can't help provide support.

```
Traceback (most recent call last):
  File "/home/xhr/.config/Ultralytics/DDP/_temp_o53uk8jg139849945195328.py", line 6, in <module>
    from ultralytics.models.yolo.detect.train import DetectionTrainer
ModuleNotFoundError: No module named 'ultralytics'
Traceback (most recent call last):
  File "/home/xhr/.config/Ultralytics/DDP/_temp_o53uk8jg139849945195328.py", line 6, in <module>
    from ultralytics.models.yolo.detect.train import DetectionTrainer
ModuleNotFoundError: No module named 'ultralytics'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 134623) of binary: /CV/anaconda3/envs/rtdetr/bin/python
```

**Comment by ucas-dx** [comment]
> > @Hongru0306 hey there! 👋 It looks like you're encountering a `ModuleNotFoundError` after updating to YOLOv8.1.17 and attempting DDP training. This error typically indicates that Python can't find the `ultralytics` module in your environment.@Hongru0306 嘿那里！ 👋 更新到 YOLOv8.1.17 并尝试 DDP 训练后，您似乎遇到了 `ModuleNotFoundError` 。此错误通常表示 Python 在您的环境中找不到 `ultralytics` 模块。
> > Could you please try the following steps to see if it resolves the issue?您能否尝试以下步骤看看能否解决问题？
> > 
> > 1. Ensure that the `ultralytics` package is installed in your current Python environment.确保 `ultralytics` 包已安装在您当前的 Python 环境中。
> > 2. Verify that your Python environment is activated when running the training script.运行训练脚本时验证您的 Python 环境是否已激活。
> > 3. Check if the PYTHONPATH environment variable includes the path to the `ultralytics` package.检查 PYTHONPATH 环境变量是否包含 `ultralytics` 包的路径。
> > 
> > Here's a quick way to check and install the `ultralytics` package:这是检查和安装 `ultralytics` 包的快速方法：
> > ```shell
> > pip install ultralytics
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And to verify the PYTHONPATH:并验证 PYTHONPATH：
> > ```shell
> > echo $PYTHONPATH
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If the issue persists, it might be helpful to provide the full directory structure of where the `ultralytics` package is installed, as well as the output of `pip list` to ensure the package is indeed present.如果问题仍然存在，提供 `ultralytics` 软件包安装位置的完整目录结构以及 `pip list` 的输出可能会有所帮助，以确保该软件包确实存在。
> > Let's get this sorted out! 🛠️让我们来解决这个问题吧！ 🛠️
> 
> Thank you very much for your reply, but I want to do my own algorithm improvement experiments and will change some of the code, I don't want to change the source code inside Anaconda's environment, after I add some of my own changes, I still have a single card that is able to run, but the DDP will look for the code in the environment again and report that what I changed does not exist. I would like to ask if you have a better idea of how to solve this?
> 
> ```
> WARNING ⚠️ Upgrade to torch>=2.0.0 for deterministic training.
> Traceback (most recent call last):
>   File "/home/xhr/.config/Ultralytics/DDP/_temp__o31zs9u140556094763072.py", line 12, in <module>
>     results = trainer.train()
>   File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 208, in train
>     self._do_train(world_size)
>   File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 322, in _do_train
>     self._setup_train(world_size)
>   File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 236, in _setup_train
>     ckpt = self.setup_model()
>   File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 521, in setup_model
>     self.model = self.get_model(cfg=cfg, weights=weights, verbose=RANK == -1)  # calls Model(cfg, weights)
>   File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/models/yolo/obb/train.py", line 33, in get_model
>     model = OBBModel(cfg, ch=3, nc=self.data["nc"], verbose=verbose and RANK == -1)
>   File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 349, in __init__
>     super().__init__(cfg=cfg, ch=ch, nc=nc, verbose=verbose)
>   File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 274, in __init__
>     self.yaml = cfg if isinstance(cfg, dict) else yaml_model_load(cfg)  # cfg dict
>   File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 923, in yaml_model_load
>     yaml_file = check_yaml(unified_path, hard=False) or check_yaml(path)
>   File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/utils/checks.py", line 506, in check_yaml
>     return check_file(file, suffix, hard=hard)
>   File "/CV/anaconda3/envs/rtdetr/lib/python3.8/site-packages/ultralytics/utils/checks.py", line 498, in check_file
>     raise FileNotFoundError(f"'{file}' does not exist")
> FileNotFoundError: 'yolov8s-modify-obb.yaml' does not exist
> ```

请问同学解决这个事了吗

**Comment by ucas-dx** [comment]
你可以尝试修改ultralytics/engine/trainer.py以下代码：
`        if world_size > 1:
            self.model = DDP(self.model, device_ids=[RANK],find_unused_parameters=True)`
 如果有其它问题也可一起交流

**Comment by glenn-jocher** [comment]
@ucas-dx hey there! 👋 It looks like you're exploring multi-GPU training with DDP. Your suggestion to modify the `trainer.py` file by adding `find_unused_parameters=True` to the `DDP` initialization is a good approach when encountering issues with unused parameters during distributed training. This change can help ensure smoother training across multiple GPUs by handling any parameters that aren't used in every forward pass. 

Here's a quick example based on your suggestion:

```python
if world_size > 1:
    self.model = DDP(self.model, device_ids=[RANK], find_unused_parameters=True)
```

If you encounter any further issues or have more insights to share, feel free to reach out. Happy coding! 😊

**Comment by 2584191127** [comment]
> 你可以尝试修改ultralytics/engine/trainer.py以下代码： ` if world_size > 1: self.model = DDP(self.model, device_ids=[RANK],find_unused_parameters=True)` 如果有其它问题也可一起交流

你好，我在kaggle上遇到了这个问题，应该怎么做呢？

**Comment by ucas-dx** [comment]
你可以直接加我qq联系，出现这个问题的主要原因是你网络前馈层设置不合理，前馈层中返回了非训练参数，导致并行失败。



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 11, 2024 09:46 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ultralytics/ultralytics] New version of DDP trainingerror--YOLOv8.1.17 (Issue #8383)




  
你可以尝试修改ultralytics/engine/trainer.py以下代码：  if world_size &gt; 1: self.model = DDP(self.model, device_ids=[RANK],find_unused_parameters=True) 如果有其它问题也可一起交流
  
你好，我在kaggle上遇到了这个问题，应该怎么做呢？

**Comment by glenn-jocher** [comment]
@ucas-dx hey there! 👋 It looks like the issue you're encountering with DDP training might be due to the setup of your network's forward layers. If these layers return non-trainable parameters, it could indeed lead to parallel training failures.

A quick fix might involve reviewing your model's architecture to ensure that only trainable parameters are involved in the forward pass. This might require a bit of tweaking in your model definition.

For Kaggle environments, direct modifications to source files like `ultralytics/engine/trainer.py` might not be straightforward due to the containerized setup. However, if you're working on a local setup or have the ability to modify the source, you could try the suggested change:

```python
if world_size > 1:
    self.model = DDP(self.model, device_ids=[RANK], find_unused_parameters=True)
```

This adjustment tells DDP to ignore any unused parameters during the forward pass, which might help in your case.

If you're still stuck, feel free to share more details about your model architecture or the specific error messages you're seeing. Happy to help further! 😊

**Comment by Hongru0306** [comment]
> 你可以直接加我qq联系，出现这个问题的主要原因是你网络前馈层设置不合理，前馈层中返回了非训练参数，导致并行失败。
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Mar 11, 2024 09:46 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [ultralytics/ultralytics] New version of DDP trainingerror--YOLOv8.1.17 (Issue #8383) 你可以尝试修改ultralytics/engine/trainer.py以下代码： if world_size &gt; 1: self.model = DDP(self.model, device_ids=[RANK],find_unused_parameters=True) 如果有其它问题也可一起交流 你好，我在kaggle上遇到了这个问题，应该怎么做呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

十分感谢您的解答！请问如何添加您的联系方式？希望能够buy u a coffee!

**Comment by Hongru0306** [comment]
> 你可以直接加我qq联系，出现这个问题的主要原因是你网络前馈层设置不合理，前馈层中返回了非训练参数，导致并行失败。
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Mar 11, 2024 09:46 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [ultralytics/ultralytics] New version of DDP trainingerror--YOLOv8.1.17 (Issue #8383) 你可以尝试修改ultralytics/engine/trainer.py以下代码： if world_size &gt; 1: self.model = DDP(self.model, device_ids=[RANK],find_unused_parameters=True) 如果有其它问题也可一起交流 你好，我在kaggle上遇到了这个问题，应该怎么做呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

十分感谢您的解答！不过我这里还没有解决，请问如何添加您的联系方式？希望能够buy u a coffee!

**Comment by Gary2018X** [comment]
> @Hongru0306 we have (at least) two instances of models training using 2x GPUs for experiments that use the code from `8.1.17`. We're not seeing the same issue, and if you've modified the code then there's really not much we can do to provide support.
> 
> I will point out that the first error text you provided does mention `ModuleNotFoundError: No module named 'ultralytics'` for the file `"/home/xhr/.config/Ultralytics/DDP/_temp_o53uk8jg139849945195328.py"` running in the environment `/CV/anaconda3/envs/rtdetr/bin/python` which may be a factor to the error you're experiencing. Again, if you modify the code, we can't help provide support.
> 
> ```
> Traceback (most recent call last):
>   File "/home/xhr/.config/Ultralytics/DDP/_temp_o53uk8jg139849945195328.py", line 6, in <module>
>     from ultralytics.models.yolo.detect.train import DetectionTrainer
> ModuleNotFoundError: No module named 'ultralytics'
> Traceback (most recent call last):
>   File "/home/xhr/.config/Ultralytics/DDP/_temp_o53uk8jg139849945195328.py", line 6, in <module>
>     from ultralytics.models.yolo.detect.train import DetectionTrainer
> ModuleNotFoundError: No module named 'ultralytics'
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 134623) of binary: /CV/anaconda3/envs/rtdetr/bin/python
> ```

I also encountered the same problem. The difference between me and him is that I did not make any changes to the source code

**Comment by Burhan-Q** [comment]
The original post shows the `model.train` command running from `/CV/xhr_project/yolov8-obb/ultralytics/` and the DDP command that's instigated by `torch` runs from `/CV/anaconda3/envs/rtdetr/bin/python -m torch.distributed.run ` which are certainly different directories and possibly different `env`. This would mean that `ultralytics` and `torch` are not installed in the same `env` or if using a clone of the GitHub repo, means that `ultralytics` is just not installed at all for the active `env`. 

I can assure you both from personal experience and from speaking with others from our Discord community, DDP _does_ work correctly. You can always try updating to a more recent version of `ultralytics` as well. My recommendation would be to create a new `env` and install `ultralytics` using `pip` or `conda` and try again.

**Comment by ucas-dx** [comment]
okay 你可以发送你的联系方式到我的邮箱：38694034@qq.com

**Comment by glenn-jocher** [comment]
Hey there! 👋 I've just sent you an email with my contact details. Looking forward to connecting and resolving your issue! 😊

**Comment by wanyne-yyds** [comment]
If you modify or add a model, you can try adding a line "sys.path.insert(0, "/home/ultralytics")" to the function generate_ddp_file in /ultralytics/utils/dist.py, /home/ultralytics: It's you The program path is enough.

**Comment by glenn-jocher** [comment]
Thank you for your suggestion! Adding `sys.path.insert(0, "/home/ultralytics")` to the `generate_ddp_file` function in `/ultralytics/utils/dist.py` can indeed help resolve module path issues when modifying or adding models. This ensures the correct path is included during DDP execution. If you encounter any further issues, feel free to reach out. 😊

**Comment by Love-syntacticSugar** [comment]
@wanyne-yyds 好兄弟，中国人吧。
我就觉得这bug是路径的问题，看了你说的我就觉得靠谱，试了一下确实ok了，非常感谢嘞！
（真不明白为什么别的评论说改find_unused_parameters=True参数的，这参数和这报错八竿子打不着边啊。。）

**Comment by zhangbohnu** [comment]
I tried the solution of "sys.path.insert"  but it didn't work. I later solved it by creating a soft link.

**Comment by pderrenger** [comment]
Thank you for sharing your experience. It's great to hear that creating a soft link resolved the issue for you. If you encounter any further problems, please ensure you're using the latest version of the Ultralytics package, as updates often include important fixes and improvements. If the issue persists, feel free to provide more details, and we'll do our best to assist you.

**Comment by glenn-jocher** [comment]
I'm glad you found a solution with a soft link. If you have any more questions, feel free to ask!

**Comment by glenn-jocher** [comment]
Glad to hear you found a solution! If you have any more questions, feel free to ask.

**Comment by glenn-jocher** [comment]
Glad to hear you found a solution by creating a soft link! If you have any more questions, feel free to ask.

**Comment by xxh-zcl** [comment]
@zhangbohnu Can you explain how to add a soft link
