### ISSUE TITLE
bring back "--cls" : Specifying a list of specific classes to test on

### ISSUE THREAD

**Issue by fennecinspace** [ultralytics/ultralytics#839]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hello,

I used to use the cls flag to specify a group of classes to test on, is there any way to do that ?

Thank you !

### Use case

Testing pretrained model on a specific global class. For example `-cls=[2, 3, 7]` (car, motorcycle, truck) to test on a vehicules dataset.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@fennecinspace hi, please refer to your docs. [https://docs.ultralytics.com/cfg/#prediction](https://docs.ultralytics.com/cfg/#prediction)
There's a arg `classes` to filter classes. 
usage:
```bash
yolo detect predict classes='[0,1]'
```

**Comment by fennecinspace** [comment]
@Laughing-q  thanks for the response. 

We need this behavior in the validation operation, where GT labels are taken into account and metrics are returned at the end. (This is present in the yolov5 solution)

PS: It should also be coupled with the 'task' flag that lets us run testing on the test folder instead of the val folder by doing --task 'test'. (I have already added this myself)

**Comment by Laughing-q** [comment]
@fennecinspace hi, I made a PR to return maps here. #846 Then you can get class-specify map by:
```python
metrics = model.val(data=...)
map_car = metrics.box.maps[2]
```

**Comment by fennecinspace** [comment]
Thank you for getting back to this so quickly .... So to get the mAP for 3 coco classes I would do mean of sum of the metrics.box.maps[0:3] for example ?

**Comment by Laughing-q** [comment]
@fennecinspace True! The PR could be merged later today or tomorrow then you're able to test it. :)
