### ISSUE TITLE
RTDETR parameters

### ISSUE THREAD

**Issue by IamShubhamGupto** [ultralytics/ultralytics#8390]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Where can I find a complete list of tunable parameters while training RTDETR?

I noticed it has options like `half` which I am assuming is half precision? I would like more inference related flags enabled while training

```
[34m[1mengine/trainer: [0mtask=detect, mode=train, model=rtdetr-l.pt, data=data-v8.yaml, epochs=300, time=None, patience=50, batch=64, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train4, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train4
Overriding model.yaml nc=80 with nc=3
```

### Additional

I am training a RTDETR model using ultralytics

**Comment by IamShubhamGupto** [comment]
@glenn-jocher what does dnn flag do?

**Comment by glenn-jocher** [comment]
@IamShubhamGupto hi there! The `dnn` flag is used to enable inference with OpenCV's Deep Neural Network (DNN) module when using the `predict` mode. This is particularly useful if you're running inference on a CPU or a system where CUDA is not available. It allows you to leverage the highly optimized DNN routines built into OpenCV for running predictions. Here's a quick example of how you might use it:

```bash
yolo detect predict model=yolov8n.pt source='path/to/image.jpg' dnn=True
```

This will run the model using OpenCV's DNN backend. Hope this helps! 😊
