### ISSUE TITLE
Problem with download any model.

### ISSUE THREAD

**Issue by robsouza2101** [ultralytics/ultralytics#8396]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Well, I'm trying to test the yolov8 with the examples mentioned on ultralytics github but when I press enter with the command on anaconda prompt it can't download.
![imagem_2024-02-22_195103075](https://github.com/ultralytics/ultralytics/assets/46307339/2ed1a6d8-2809-4a55-82a4-c38f199d37da)

This image show the error of it. I have installed following all the instructions on the github.

**Comment by glenn-jocher** [comment]
@robsouza2101 hi there! 👋 It looks like there might be an issue with the model download process. Could you please try the following steps to see if it resolves the issue?

1. Ensure you have an active internet connection without any restrictions that might block the download.
2. Check if there's enough disk space for the model.
3. Try clearing any existing cached models by deleting the contents of the `~/.cache/torch/hub/checkpoints/` directory.

If the problem persists, could you run the following command and share the output?

```bash
yolo detect predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg' --verbose
```

This will provide more detailed logs that might help us diagnose the issue. Thanks for reaching out, and we'll work to get this sorted out! 🛠️

**Comment by Burhan-Q** [comment]
@robsouza2101 this is not reproducible.

![image](https://github.com/ultralytics/ultralytics/assets/62214284/87e9c35a-afc9-4354-924c-dcccabcaf535)

You can also visit the [Releases page](https://github.com/ultralytics/assets/releases/v8.1.0/) and scroll to the Assets section to directly download the model weights or visit the [Models/YOLOv8 page of the docs](https://docs.ultralytics.com/models/yolov8/) as well.

**Comment by robsouza2101** [comment]
> @robsouza2101 hi there! 👋 It looks like there might be an issue with the model download process. Could you please try the following steps to see if it resolves the issue?
> 
> 1. Ensure you have an active internet connection without any restrictions that might block the download.
> 2. Check if there's enough disk space for the model.
> 3. Try clearing any existing cached models by deleting the contents of the `~/.cache/torch/hub/checkpoints/` directory.
> 
> If the problem persists, could you run the following command and share the output?
> 
> ```shell
> yolo detect predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg' --verbose
> ```
> 
> This will provide more detailed logs that might help us diagnose the issue. Thanks for reaching out, and we'll work to get this sorted out! 🛠️

Well, yesterday I was in college using them internet that probably has some restriction that might was blocking the download. And now that i'm home and tried again using: 

```shell
# Install the ultralytics package from GitHub
pip install git+https://github.com/ultralytics/ultralytics.git@main
```
And after uninstalled and installed I tried the piece of code with the verbose argument that you provide me and didn't work, but when I tried with the path of the weight and the image it works. And i think that the actual path that i was trying to run on this test was restricted, and I moved to another path with public access and it worked without the paths and also downloaded the weight and the image. 

![imagem_2024-02-23_134111447](https://github.com/ultralytics/ultralytics/assets/46307339/81cf2a20-f048-4b41-87df-ef1f7519b890)


I'm really grateful for the helps guys, it helped me to understand the problem, and that was a silly one. 
And I forgot but, it's a pleasure to be part of this community. I'm using since 2022 with the yolov5 for a project at the college to apply this in the industry context to turn them more automated. If I have any further questions I will contact you again.

Again, thank you for your attention.
