### ISSUE TITLE
How to mask region of images to be ignored?

### ISSUE THREAD

**Issue by ruckc** [ultralytics/ultralytics#840]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have video feeds were I need to ignore detections in various regions of the images.  How can I mask these regons out?  I've tried turning those pixels black, but I keep getting detections on the edges of those regions... especially an island in the middle I'm trying to mask out.

**Comment by FnSK4R17s** [comment]
filter the detection after processing the images using IoU matching @ruckc

**Comment by knoppmyth** [comment]
Perhaps [this](https://www.youtube.com/watch?v=l_kf9CfZ_8M) will give you some ideas.

**Comment by aayushsingla** [comment]
Any updates on this @ruckc ?

**Comment by ruckc** [comment]
No.  Trying to filter detections by IoU is cumbersome.  Was hoping YOLO had a better process that uses either a bitmap mask or polygon masking to filter detections before being returned.

**Comment by aayushsingla** [comment]
Yeah, was hoping for something similar. I couldn't find it either.

**Comment by pderrenger** [comment]
@aayushsingla for image regions you want to ignore during object detection, you can use a bitmap mask or polygon masking to filter out detections before they are returned. YOLOv8 does not currently have a built-in function for this, but it's a common request that the Ultralytics team is aware of and might consider for future updates. In the meantime, filtering the detections after processing the images using IoU matching might be a workaround, although it can be cumbersome. Thank you for your patience and understanding.
