### ISSUE TITLE
YOLO World custom category not recognized

### ISSUE THREAD

**Issue by SSTato** [ultralytics/ultralytics#8402]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to use the following code to detect license plates, but he hasn't detected anything：
```
from ultralytics import YOLOWorld

model = YOLOWorld('yolov8l-world.pt')
model.set_classes(["license plate"])
results = model.predict('frame.jpg', conf=0.05)

results[0].show()

Speed: 2.0ms preprocess, 30.0ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)
```
But when I use YOLO-World from AILab-CVC or https://huggingface.co/spaces/stevengrove/YOLO-World At that time, he could detect the license plate.

![image](https://github.com/ultralytics/ultralytics/assets/93987794/439ca548-2ab8-46d2-b989-1ea150134319)

When I use a known category, it can detect the target.

![image](https://github.com/ultralytics/ultralytics/assets/93987794/0e33c793-907e-4ed9-9433-e3b7bbad8f4b)

Is there an issue with the method I am using, or is it currently unable to detect targets of unknown categories?

**Comment by Burhan-Q** [comment]
@SSTato try using `model.set_classes(["license plate", ""])` as including a "background class"(an empty string) has been found to help with improving detection results.

**Comment by hylarucoder** [comment]
@Burhan-Q 

hi, burhan, love your work. saving my life. thanks. 

Just solve this with a `background class ""`, If some reminders could be added here, it would help a lot of beginners

![image](https://github.com/ultralytics/ultralytics/assets/5625783/ebfd9489-976b-4b91-a9ee-7e59f594dd8c)
