### ISSUE TITLE
about merge the local  id and global in same place meansd top of the object .

### ISSUE THREAD

**Issue by Vinrub** [ultralytics/ultralytics#8403]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

from collections import defaultdict
import cv2
import numpy as np

from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('yolov8n.pt')

# Open the video file
video_path = "/media/XavierSSD250/22_08_23/output_video_09_02_2024_12_51_17.avi"
cap = cv2.VideoCapture(video_path)

# Store the track history
track_history = defaultdict(lambda: [])

# Define the maximum track ID
max_track_id = 25

# Loop through the video frames
while cap.isOpened():
    try:
        # Read a frame from the video
        success, frame = cap.read()

        if success:
            # Run YOLOv8 tracking on the frame, persisting tracks between frames
            results = model.track(frame, persist=True)

            # Get the boxes and track IDs
            boxes = results[0].boxes.xywh.cpu()
            track_ids = results[0].boxes.id.int().cpu().tolist()

            # Visualize the results on the frame
            annotated_frame = results[0].plot()

            # Plot the tracks
            for box, track_id in zip(boxes, track_ids):
                x, y, w, h = box
                track = track_history[track_id % max_track_id]  # Limit the track ID within 1 to 50
                track.append((float(x), float(y)))  # x, y center point
                if len(track) > 30:  # retain 90 tracks for 90 frames
                    track.pop(0)

                # Draw the tracking lines
                points = np.hstack(track).astype(np.int32).reshape((-1, 1, 2))
                print("points",points)

                # Calculate the position relative to the frame center
                frame_center = frame.shape[1] // 2
                object_center = (points[0][0][0] + points[-1][0][0]) // 2
                if object_center < frame_center:
                    frame_side = "L"  # Left side
                else:
                    frame_side = "R"  # Right side

                # Assign frame ID based on the number of points
                frame_id = frame_side + str(track_id % max_track_id)  # Limit the track ID within 1 to 50

                # Draw the tracking lines
                cv2.polylines(annotated_frame, [points], isClosed=False, color=(230, 230, 230), thickness=10)

                # Display the frame ID
                cv2.putText(annotated_frame, frame_id, (points[0][0][0], points[0][0][1]), cv2.FONT_HERSHEY_SIMPLEX, 4, (255, 255, 255), 2)

            # Display the annotated frame
            cv2.imshow("YOLOv8 Tracking", cv2.resize(annotated_frame, None, fx=.3, fy=.3))

            # Break the loop if 'q' is pressed
            if cv2.waitKey(1) & 0xFF == ord("q"):
                break
        else:
            # Break the loop if the end of the video is reached
            break

    except Exception as e:
        print("An error occurred:", e)

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()

### Additional

In this i added the local id for left and right side ,i want to local id with the global id .

**Comment by glenn-jocher** [comment]
@Vinrub hey there! 👋 It looks like you're trying to merge local and global track IDs for object tracking. If you want to display both IDs on top of the object, you can modify the `cv2.putText` line in your loop to include both the local `frame_id` and the global `track_id`. Here's a quick example:

```python
# Inside your loop after calculating frame_id
global_id = str(track_id)  # Global track ID as a string
display_id = f"{frame_id} | Global: {global_id}"  # Combine local and global IDs

# Update the cv2.putText line to use display_id
cv2.putText(annotated_frame, display_id, (int(x), int(y)), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)
```

This will display both the local side-based ID and the global track ID on top of each tracked object. Let me know if this helps or if you have any more questions! 😊

**Comment by Vinrub** [comment]
Thankyou i got it .

**Comment by glenn-jocher** [comment]
@Vinrub you're welcome! I'm glad to hear that you got it working. If you have any more questions or need further assistance down the road, don't hesitate to reach out. Happy coding! 😊🚀
