### ISSUE TITLE
tensorrt model

### ISSUE THREAD

**Issue by karunakr** [ultralytics/ultralytics#8405]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I converted yolov8x model to tensorrt engine. Though it gives good performance gain, detection is not good, especially in a few frames. We used yolo export command in the same machine to convert the model to an engine. We are using tensorrt 8.6 library.

Please let me know if there are any possibilities to get more quality outcomes. We are using the model to detect persons.

Thanks
Karunakar

**Comment by Burhan-Q** [comment]
@karunakr it's recommend to load your TensorRT model with the `ultralytics.Autobackend` which is the same as running a normal model.

```py

from ultralytics import YOLO

model = YOLO("yolov8n.engine", task="detect")

results = model.predict("path/to/source.png")
```
