### ISSUE TITLE
YOLOv8 prediction on multiple threads with one GPU

### ISSUE THREAD

**Issue by TrinhNhatTuyen** [ultralytics/ultralytics#8406]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

**Here my GPU Configuration:**
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 551.52                 Driver Version: 551.52         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Quadro K2200                 WDDM  |   00000000:08:00.0 Off |                  N/A |
| 59%   74C    P0             31W /   39W |    1348MiB /   4096MiB |     85%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
**My code:**
```
from ultralytics import YOLO
import cv2, os, time
from threading import Thread
def predict_video(i):
    video_path = f'test/test{i+1}.mp4'
    scale = 0.5
    t_oldframe = 0
    fire_model = YOLO('mymodel.pt')
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print("Cannot open video file.")
        return
```

    while True:
        ret, frame = cap.read()
        
        timer =time.time()
        fps = 1/(timer-t_oldframe)
        t_oldframe = timer
        
        if not ret:
            break
        
        results = fire_model.predict(source=frame, device=0, save=False)
        annotated_frame = results[0].plot()
        
        cv2.putText(annotated_frame, "fps: {:.2f}".format(fps), (20,50),cv2.FONT_HERSHEY_SIMPLEX, 1, (23, 155, 255), 2)
        cv2.imshow(video_path, 
                   cv2.resize(annotated_frame, (int((annotated_frame.shape[1])*scale),int((annotated_frame.shape[0])*scale))))

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()`

```
def main():
    threads = []
    num_threads = 3
    for i in range(num_threads):  
        thread = Thread(target=predict_video, args=([i]))
        threads.append(thread)
    for thread in threads:
        thread.start()
    for thread in threads:
        thread.join()

main()
```
Even though I've divided the threads, initially with 1 video-1 thread the fps is around ~6, then with 2 videos-2 threads it drops to ~3, and with 3 videos-3 threads it's around ~2? It feels like the code is still processing sequentially. Ideally, with 3 videos, the fps should be around ~6 for all videos.
When using only one GPU with this code, the fps decreases as the number of threads increases. Is there a way to achieve high fps when running multiple threads, similar to when running a single thread?

**Comment by Burhan-Q** [comment]
@TrinhNhatTuyen you may want to consider reviewing the guide from the docs about [Thread Safe Inference](https://docs.ultralytics.com/guides/yolo-thread-safe-inference/)

**Comment by TrinhNhatTuyen** [comment]
@Burhan-Q I read it and my code is similar to [Thread Save Example](https://docs.ultralytics.com/vi/guides/yolo-thread-safe-inference/#thread-safe-example). Can you point out the problem in my code?

**Comment by sunmooncode** [comment]
The multiprocessing I use to handle multiple models reasoning at the same time

**Comment by TrinhNhatTuyen** [comment]
@sunmooncode can you share your code?

**Comment by sunmooncode** [comment]
This is a multi-process modification based on the code provided.

```
import multiprocessing as mp
import time
import cv2
from ultralytics import YOLO


def infer_model(frame):
    fire_model = YOLO('mymodel.pt')
    results = fire_model.predict(source=frame, device=0, save=False)
    if results:
        return results[0].plot()
    else:
        return None


if __name__ == '__main__':
    video_path = 'test/test1.mp4'
    scale = 0.5
    global_time = 0
    global_count = 0
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print("Cannot open video file.")
        exit()

    pool = mp.Pool(2)

    while True:
        ret, frame = cap.read()

        if not ret:
            break

        time1 = time.time()
        results = pool.map(infer_model, args=(frame,))
        time2 = time.time()

        global_time += time2 - time1
        global_count += 1

        fps = global_count / global_time

        for annotated_frame in results:
            if annotated_frame is not None:
                cv2.putText(annotated_frame, "fps: {:.2f}".format(
                    fps), (20, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (23, 155, 255), 2)
                cv2.imshow(video_path,
                           cv2.resize(annotated_frame,
                                      (int((annotated_frame.shape[1]) * scale),
                                       int((annotated_frame.shape[0]) * scale))))

                if cv2.waitKey(1) & 0xFF == ord('q'):
                    break

    cap.release()
    cv2.destroyAllWindows()
```

**Comment by sunmooncode** [comment]
But in my usage scenario, which is multi-process, multi-model, multi-GPU, I'm not sure if you're getting an error that way.

**Comment by Burhan-Q** [comment]
@TrinhNhatTuyen it's difficult to tell for certain, but it appears that your code contains the loop _inside_ the function. This means you're attempting to process an **entire** video with each model simultaneously. This means that frames have to be opened by your CPU and then passed to GPU for each video, the model on the GPU has to execute inference, then to plot the results pass an image _back_ to the CPU. 

So your system will be constrained by the CPU <--> GPU transfer ops. It also appears your GPU may be approaching a power constraint as the snapshot you shared shows you're at 31/39 W. I suspect that parallel inference using multiple models will place a burden on the GPU that may cause it to slow down as a protective measure (thermal or power based), so remember that the code is only a component of performance, limited hardware will have limited performance.

**Comment by TrinhNhatTuyen** [comment]
@sunmooncode Actually there was no error, I just thought the fps would be higher regardless of the number of videos

**Comment by sunmooncode** [comment]
Suggest you convert pt to engine for reasoning, speed cargo will be much faster.

**Comment by glenn-jocher** [comment]
@sunmooncode hi there! 😊

Absolutely, converting your `.pt` model to a TensorRT `.engine` format can indeed significantly boost inference speed, especially on NVIDIA GPUs. Here's a quick example on how you can do it using the Ultralytics YOLO CLI:

```bash
yolo export model=your_model.pt format=engine
```

This command will generate a `.engine` file that you can then use for faster inference. Let us know how it goes or if you need further assistance!

Happy coding!
