### ISSUE TITLE
Suggest adding yolov9

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#8408]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

https://arxiv.org/pdf/2402.13616.pdf

https://github.com/WongKinYiu/yolov9

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Burhan-Q** [comment]
@monkeycc this has been added to the Roadmap and is in the works.

**Comment by Burhan-Q** [comment]
## Punchlist
- [ ] docs Model page for YOLOv9
- [ ] `yolov9.yaml` configuration
- [ ] `yolov9` pretrained models (?)
- [ ] ...

**Comment by TheNobody-12** [comment]
@Burhan-Q  @glenn-jocher Can I work on this issue. I would like to contribute to this community by integrating yolov9 into ultralytics codebase. 
Can you suggest how one should start ?

**Comment by Ali-Doggaz** [comment]
hey @Laughing-q ,I just checked your PR, let me know if you need help on this I'd love to contribute!
