### ISSUE TITLE
Could you tell me where I can see your update log?

### ISSUE THREAD

**Issue by z1069614715** [ultralytics/ultralytics#841]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Could you tell me where I can see your update log?

**Comment by AyushExel** [comment]
We're not putting out detailed release notes yet. We'll start doing that soon on a weekly basis

**Comment by z1069614715** [comment]
ok， thanks！

**Comment by pderrenger** [comment]
@z1069614715 you're welcome! If you have any other questions or need further assistance, feel free to ask. Happy to help!
