### ISSUE TITLE
trying to access results to store them in a database 

### ISSUE THREAD

**Issue by LuisCarrascoLara** [ultralytics/ultralytics#8410]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm trying to access the results (count people) but I cannot find the way to access it. I am doing model.track(im0 ....) in a For bucle for each frame I get from a S3 bucket, and when I run it I see this in my terminal
<img width="703" alt="image" src="https://github.com/ultralytics/ultralytics/assets/140614303/96f9b580-32c3-49f9-90ea-34672cd28d0a">
I want to access that person count on the results but I don't find the way. 
I was trying this way but it also don't let me 
<img width="715" alt="image" src="https://github.com/ultralytics/ultralytics/assets/140614303/a1dfa48d-c310-4d60-848e-e0282f6c0325">

any help on how to access predictions and count the predictions on every image?

**Comment by Burhan-Q** [comment]
@LuisCarrascoLara I also replied to you via the Discord server, but figured I can share here as well. The information you're looking for is in the docs under the [Predict Mode Working with Results](https://docs.ultralytics.com/modes/predict/#working-with-results). When using (example from that section of the docs)

```py
from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO('yolov8n.pt')

# Run inference on an image
results = model('bus.jpg')  # list of 1 Results object
```

As noted in the trailing comment of the last line, the model prediction returns a `list` of a single `Results` object. You will need to either use a `for`-loop or `results[0]` to access the `Results` methods and attributes. A `for`-loop is more flexible for cases when you might pass multiple images into a model at once for prediction.

**Comment by Burhan-Q** [comment]
Closing based on reply on Discord 🚀 hope to chat more in the Discord!
