### ISSUE TITLE
segmentation

### ISSUE THREAD

**Issue by farukalamai** [ultralytics/ultralytics#8413]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

**Comment by glenn-jocher** [comment]
@farukalamai yes you can use masks.xyn to retrieve normalized predicted segments:
https://docs.ultralytics.com/modes/predict/

<img width="1199" alt="Screenshot 2024-02-23 at 14 30 26" src="https://github.com/ultralytics/ultralytics/assets/26833433/dd204949-3894-48e6-9e75-92f120f7443b">

**Comment by farukalamai** [comment]
> @farukalamai yes you can use masks.xyn to retrieve normalized predicted segments: https://docs.ultralytics.com/modes/predict/
> 
> <img alt="Screenshot 2024-02-23 at 14 30 26" width="1199" src="https://private-user-images.githubusercontent.com/26833433/307335722-dd204949-3894-48e6-9e75-92f120f7443b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTU0MjgsIm5iZiI6MTcwODY5NTEyOCwicGF0aCI6Ii8yNjgzMzQzMy8zMDczMzU3MjItZGQyMDQ5NDktMzg5NC00OGU2LTllNzUtOTJmMTIwZjc0NDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDEzMzIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNDBiY2ZiZGUyOTBiOTBlMTMwNmY3YmY5ZGJhYmUzNmYxM2JkZjYxNTI5YjI3NDRjZWZlMDQxNzU3MDg5YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o70OBAF0G3bBx3jKc5TSnWQQqZEWs90VlahkUFhdSLI">

Hi, thanks for your reply. Let me clear everything up again,
1. Cropping detected car from a image
2. taking reference points like the top left point of the bounding box coordinate 
3. segmenting the wheel of that car, getting the normalization point of the segmented wheel. I have used Ultralytics xyn. 
4. then multiply the width of the crop car image with the segmented point "x" value and height with the "y" value 
5. then again add the reference point x  value with the segmented point x value and reference point y value with segmented point y values. 
6. and finally when I am drawing the segment point on the main image. it's not drawing the point on top of the wheel. 

My question is why it's happening? Is there any problem with my steps?

**Comment by glenn-jocher** [comment]
Hi @farukalamai, it seems like you're on the right track with your process. However, the issue might be with the coordinate space transformation. When you resize the cropped car image to 256x256 and then segment the wheel, the normalized points you get are relative to the 256x256 image. When you scale these points back up to the original image size, you need to ensure that the scaling is done proportionally to the original car crop size before resizing, not the resized dimensions.

Here's a quick rundown of what you might consider:

- Ensure that the scaling factor is based on the original crop size of the car.
- When adding the reference point coordinates, make sure they are the coordinates of the top-left point of the car crop in the original image.

If the points still don't align, you might want to double-check the order of operations and make sure that all transformations maintain the aspect ratio. If you can share a code snippet, I'd be happy to take a closer look! 👀
