### ISSUE TITLE
Should I use an image size of 1080 for training segmentation model

### ISSUE THREAD

**Issue by Muthukumar4796** [ultralytics/ultralytics#8414]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I have decided to use 1280-pixel images for our model instead of the 640-pixel images used in the YOLOv8 model. I believe that using higher quality images will improve the accuracy of object detection. By testing different resolutions and configurations, we can determine the most suitable setup for our specific object detection task.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Muthukumar4796 hi there! 👋

Using a larger image size like 1080 for training your segmentation model can indeed help improve accuracy, especially if your dataset contains high-resolution images with fine details. Just keep in mind that higher resolutions will require more memory and computational power, so make sure your hardware can handle it. If you encounter any resource limitations, you might consider using a smaller image size or applying techniques like tiling.

Here's a quick example of how to set the image size in your training command:

```bash
yolo detect train data=your_dataset.yaml model=yolov8n-seg.pt imgsz=1080
```

Remember to adjust your dataset configuration file (`your_dataset.yaml`) accordingly. Best of luck with your model training, and we're here to help if you have any further questions! 😊

And thank you for offering to contribute with a PR! Contributions are always welcome. 🚀

**Comment by Muthukumar4796** [comment]
Thank you for your response. I am willing to sacrifice computational power for increased accuracy. I will update you after our model has been trained. Thank you again.

**Comment by glenn-jocher** [comment]
@Muthukumar4796 you're welcome! It sounds like you're on the right track, and I'm glad to hear you're prioritizing accuracy for your project. If you need any assistance or have questions during your training process, don't hesitate to reach out. Looking forward to hearing about your model's performance. Happy training! 😊🚀
