### ISSUE TITLE
Training YOLOv8-model on GPU-cluster, RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

### ISSUE THREAD

**Issue by simon-webwookies** [ultralytics/ultralytics#8416]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi!

We are trying to run our training of a yolov8 model on a GPU cluster. We want to put as much computation as possible on cuda. 

We managed to set the default device with: 

`torch.set_default_device("cuda")`

But we still get the following RuntimeError from /ultralytics/data/build.py:

`RuntimeError: Expected a 'cuda' device type for generator but found 'cpu' `

Locally, we were able to get around the issue by adding "cuda" to line 112 in /ultralytics/data/build.py. 

`generator = torch.Generator("cuda")`

and additionally setting

`torch.multiprocessing.set_start_method("spawn")`

before training. 

Is there another way of changing the generator's device to use "cuda", that would not involve changing the source files (and allow for use in a docker container on a GPU cluster)? 

This is in our main.py:

```
def main():
    if torch.cuda.is_available():
         torch.set_default_device("cuda")
         torch.multiprocessing.set_start_method("spawn")
    
    model = YOLO('yolov8x-seg.pt')
    
    model.train(data='dataset.yaml', epochs=30, imgsz=(640, 320), device=0, batch=4)

if __name__ == "__main__":
    main()
```

**Comment by glenn-jocher** [comment]
@simon-webwookies hi there! 👋

It looks like you're on the right track with setting the default device to CUDA. However, to ensure that all tensors and generators are created on the GPU, you might want to explicitly set the device for your model training as well. 

Instead of modifying the source files, you can specify the device when calling the `train` method. Here's a small tweak to your `main.py`:

```python
def main():
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    torch.multiprocessing.set_start_method("spawn", force=True)
    
    model = YOLO('yolov8x-seg.pt', device=device)
    
    model.train(data='dataset.yaml', epochs=30, imgsz=(640, 320), device=device, batch=4)

if __name__ == "__main__":
    main()
```

This should direct all operations to the GPU without altering the source code. Give it a try and let us know if it resolves the issue! 🚀

If you encounter any further problems, feel free to reach out. Happy training!

**Comment by Burhan-Q** [comment]
@simon-webwookies if you're using Docker, maybe check out the Ultralytics Dockerfile example commands to ensure GPUs are available to the running container.

https://github.com/ultralytics/ultralytics/blob/60b6cab6cfba0e6420f249cd2bb1eadc6b04deaf/docker/Dockerfile#L54-L58

Our GPU server runs training with `ultralytics` without any changes made to the code from the public repository. Normally for single GPU usage, I add `device="cuda"` for multi-GPU I use `device=(5,6)` when setting up training.

**Comment by Burhan-Q** [comment]
Glad to hear @simon-webwookies! Just an FYI in case you hadn't seen it, we do have an [ARM specific Dockerfile as well](https://github.com/ultralytics/ultralytics/blob/main/docker%2FDockerfile-arm64) which would also bypass the line you mentioned.
