### ISSUE TITLE
CLI Detection prediction outputs

### ISSUE THREAD

**Issue by NMVRodrigues** [ultralytics/ultralytics#8420]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I have gone through the issues and documentation and I can't seem to find information on this.

I am doing inference on yolov8 using the CLI, so `yolo detect predict (...)`, and I was under the impression that when using `save_txt` it would save the `x y height width` values of the bounding boxes, however, it is saving values between `[0,1]` (example below for a 2 object detection image).
I can't seem to find anything explaining the CLI output, and it seems to differ from the expected output when running using the Python package, so if anyone could explain it I would be extremely grateful.

Best regards,
Nuno

Example:
```
Image size=1920x1080
2 objects
txt output from predict:

0 0.504541 0.654552 0.759235 0.332613
0 0.504233 0.293347 0.758845 0.334131
```

**Comment by glenn-jocher** [comment]
Yes these are xywh normalized boxes, equivalent to `Result.boxes.xywhn` in the documentation.
https://docs.ultralytics.com/modes/predict/#boxes
 
<img width="2011" alt="Screenshot 2024-02-23 at 19 48 24" src="https://github.com/ultralytics/ultralytics/assets/26833433/d52b12f6-a824-4a48-a967-45c71a5afac0">

**Comment by NMVRodrigues** [comment]
@glenn-jocher Thanks!

The Docs for `save_txt` say
```
Saves detection results in a text file, following the format [class] [x_center] [y_center] [width] [height] [confidence]. Useful for integration with other analysis tools.
```

Is there any reason why it is saving the normalized version, instead of the "regular" version?
I cant see any argument that would cause that

**Comment by glenn-jocher** [comment]
@NMVRodrigues hi there,

The `save_txt` option indeed saves the bounding box coordinates in a normalized format, which is the standard practice for consistency across various image sizes. This way, the coordinates are relative to the image dimensions, ranging from 0 to 1, regardless of the actual pixel dimensions of the image.

If you need the absolute pixel values, you can easily convert them by multiplying the normalized values by the respective image dimensions. For example:

```python
x_center_abs = x_center_normalized * image_width
y_center_abs = y_center_normalized * image_height
width_abs = width_normalized * image_width
height_abs = height_normalized * image_height
```

This conversion allows you to work with the bounding boxes in terms of pixels rather than relative proportions. 😊

Hope this helps! If you have any more questions, feel free to ask.

**Comment by NMVRodrigues** [comment]
@glenn-jocher Thanks!

That makes sense yes, was just confused with the different output. I'm not sure if it is something that has happened before, but personally, I believe it would be clearer if the Docs mentioned that `save_txt` saved the normalized boxes, just for clarity.

Again, thanks for the help!

**Comment by glenn-jocher** [comment]
@NMVRodrigues You're welcome! I totally understand the confusion, and I appreciate your suggestion about the documentation. Clarity is key, and we'll consider making a note about the normalized format in the `save_txt` section. Thanks for bringing this to our attention, and if you need further assistance, feel free to reach out. Happy coding! 😊
