### ISSUE TITLE
Failed to load delegate from edgetpu.dll

### ISSUE THREAD

**Issue by AlaaArboun** [ultralytics/ultralytics#8426]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Encountered a 'ValueError: Failed to load delegate from edgetpu.dll' when attempting to load the Edge TPU delegate in TensorFlow Lite. Has anyone experienced similar issues while working with TensorFlow Lite and the Edge TPU, and how did you resolve them?

import tkinter as tk
import cv2
import numpy as np
from PIL import Image, ImageTk
from tkinter import filedialog
import tensorflow as tf
import tflite_runtime.interpreter as tflite
from tflite_runtime.interpreter import load_delegate
import json
import os

# Load the TensorFlow Lite model with Edge TPU delegate
model_path = 'yolov8m_saved_model/yolov8m_float32.tflite'
interpreter = tflite.Interpreter(model_path=model_path, experimental_delegates=[load_delegate('edgetpu.dll')])
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
input_shape = input_details[0]['shape'][1:]
print("Expected Input Dimensions:", input_details[0]['shape'][1:])

# Print input and output details
print("Input Details:")
print(input_details)
print("Output Details:")
print(output_details)

# Threshold Setting
threshold = 0.6

# Load the class labels from the JSON file
with open('C:\object-detection-coral\label_files\labels_coco.json', 'r') as json_file:
    class_labels = json.load(json_file)

# Create a tkinter window
root = tk.Tk()
root.title("Object Detection")

# save_image_with_boxes
output_directory = "output_images"
os.makedirs(output_directory, exist_ok=True)
def save_image_with_boxes(image, file_path):
    output_path = os.path.join(output_directory, os.path.basename(file_path))
    cv2.imwrite(output_path, image)
    print(f"Image enregistrée avec succès : {output_path}")

# Preprocessing function using TensorFlow
def preprocess(image_path, input_shape):
    # Read image file
    raw = tf.io.read_file(image_path)
    # Decode image
    image = tf.image.decode_image(raw, channels=3)
    # Resize image
    image_resized = tf.image.resize(image, (input_shape[0], input_shape[1]))
    # Convert image to float32
    image_float32 = tf.cast(image_resized, tf.float32)
    # Normalize image
    image_normalized = image_float32 / 255.0
    # Add batch dimension
    image_with_batch = tf.expand_dims(image_normalized, 0)

    return image_with_batch

# Function to open a file dialog and select an image
def open_image():
    file_path = filedialog.askopenfilename()
    if file_path:
        # Preprocess the image
        image_np = preprocess(file_path, input_shape)

        # Perform inference
        interpreter.set_tensor(input_details[0]['index'], image_np)
        interpreter.invoke()
        output = interpreter.get_tensor(output_details[0]['index'])
        output = output[0]
        print(output.shape)

        # Read the image with OpenCV to draw bounding boxes
        image = cv2.imread(file_path)
        orig_h, orig_w = image.shape[:2]

        for i in range(output.shape[1]):
            detection = output[:, i]
            x_center, y_center, width, height = detection[:4]
            x1 = max(0, int((x_center - width / 2) * orig_w))
            y1 = max(0, int((y_center - height / 2) * orig_h))
            x2 = min(orig_w - 1, int((x_center + width / 2) * orig_w))
            y2 = min(orig_h - 1, int((y_center + height / 2) * orig_h))
           
            score = np.max(detection[4:])
         
            cls = np.argmax(detection[4:])
            if score >= threshold:
                class_name = class_labels[str(cls)]  # Obtain the class name using the class index
                cv2.rectangle(image, (x1, y1), (x2, y2), (0, 0, 255), thickness=2)  # Draw bounding box
                cv2.putText(image, f"{class_name}: {score:.2f}", (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

        # Convert the image to RGB format for display with Tkinter
        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image_pil = Image.fromarray(image_rgb)
        tk_image = ImageTk.PhotoImage(image_pil)

        # Update the image label with the new image
        image_label.config(image=tk_image)
        image_label.image = tk_image
        save_image_with_boxes(image, file_path)

# Button to select an image
select_button = tk.Button(root, text="Select Image", command=open_image)
select_button.pack()

# Create a label to initially display the image
image_label = tk.Label(root)
image_label.pack()

# Run the tkinter event loop
root.mainloop()

ValueError                                Traceback (most recent call last)
File [c:\object-detection-coral\myenv\Lib\site-packages\tflite_runtime\interpreter.py:166](file:///C:/object-detection-coral/myenv/Lib/site-packages/tflite_runtime/interpreter.py:166), in load_delegate(library, options)
    [165](file:///C:/object-detection-coral/myenv/Lib/site-packages/tflite_runtime/interpreter.py:165) try:
--> [166](file:///C:/object-detection-coral/myenv/Lib/site-packages/tflite_runtime/interpreter.py:166)   delegate = Delegate(library, options)
    [167](file:///C:/object-detection-coral/myenv/Lib/site-packages/tflite_runtime/interpreter.py:167) except ValueError as e:

File [c:\object-detection-coral\myenv\Lib\site-packages\tflite_runtime\interpreter.py:104](file:///C:/object-detection-coral/myenv/Lib/site-packages/tflite_runtime/interpreter.py:104), in Delegate.__init__(self, library, options)
    [103](file:///C:/object-detection-coral/myenv/Lib/site-packages/tflite_runtime/interpreter.py:103) if self._delegate_ptr is None:
--> [104](file:///C:/object-detection-coral/myenv/Lib/site-packages/tflite_runtime/interpreter.py:104)   raise ValueError(capture.message)

ValueError: 

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[7], [line 14](vscode-notebook-cell:?execution_count=7&line=14)
     [12](vscode-notebook-cell:?execution_count=7&line=12) # Load the TensorFlow Lite model with Edge TPU delegate
     [13](vscode-notebook-cell:?execution_count=7&line=13) model_path = 'yolov8m_saved_model/yolov8m_float32.tflite'
---> [14](vscode-notebook-cell:?execution_count=7&line=14) interpreter = tflite.Interpreter(model_path=model_path, experimental_delegates=[load_delegate('edgetpu.dll')])
     [15](vscode-notebook-cell:?execution_count=7&line=15) interpreter.allocate_tensors()
     [17](vscode-notebook-cell:?execution_count=7&line=17) input_details = interpreter.get_input_details()

File [c:\object-detection-coral\myenv\Lib\site-packages\tflite_runtime\interpreter.py:168](file:///C:/object-detection-coral/myenv/Lib/site-packages/tflite_runtime/interpreter.py:168), in load_delegate(library, options)
    [166](file:///C:/object-detection-coral/myenv/Lib/site-packages/tflite_runtime/interpreter.py:166)   delegate = Delegate(library, options)
...
    [169](file:///C:/object-detection-coral/myenv/Lib/site-packages/tflite_runtime/interpreter.py:169)       library, str(e)))
    [170](file:///C:/object-detection-coral/myenv/Lib/site-packages/tflite_runtime/interpreter.py:170) return delegate

ValueError: Failed to load delegate from edgetpu.dll

**Comment by Burhan-Q** [comment]
@AlaaArboun you should use the `ultralytics` library to load your `.tflite` model instead. There is an `Autobackend` class that will allow you to use any export model type. Make sure you use the compatible version of the `tflite` and `tensorflow` libraries

```py
from ultralytics import YOLO

model = YOLO("yolov8n.tflite")
result = model.predict("path/to/image.png")
```
