### ISSUE TITLE
it is always out of memory

### ISSUE THREAD

**Issue by alicera** [ultralytics/ultralytics#843]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

command
```
yolo detect train data=coco128.yaml model=yolov8n.pt epochs=100 imgsz=640 device=0,1,2,3
```

I command the train and the runs/detect/train/weights/ is empty
what the step do I lose?

```
RuntimeError: CUDA out of memory. Tried to allocate 1.33 GiB 
Traceback (most recent call last):
  File "/opt/conda/bin/yolo", line 33, in <module>
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())
  File "/work/AI/YOLOv8/ultralytics/ultralytics/yolo/cfg/__init__.py", line 266, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/work/AI/YOLOv8/ultralytics/ultralytics/yolo/engine/model.py", line 217, in train
    self.model, _ = attempt_load_one_weight(str(self.trainer.best))
  File "/work/AI/YOLOv8/ultralytics/ultralytics/nn/tasks.py", line 390, in attempt_load_one_weight
    ckpt = torch_safe_load(weight)  # load ckpt
  File "/work/AI/YOLOv8/ultralytics/ultralytics/nn/tasks.py", line 336, in torch_safe_load
    return torch.load(file, map_location='cpu')  # load
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/work/AI/YOLOv8/ultralytics/runs/detect/train/weights/best.pt'

```

**Comment by alicera** [comment]
It was out of memory.

Assume my GPU is 12000Mib
First, I use 11000Mib. A few minute, it will out of memory.

**Comment by knoppmyth** [comment]
Try reducing the batch size.

**Comment by alicera** [comment]
I have a question that
Is there a way to control the memory under  +- 500Mib ? ( avoid  out of memory)

**Comment by EdisionWew** [comment]
Hi, bud, did you solved it ? I met it, too, when I use multi-gpus. It seems working well just when a single-gpu used.

**Comment by alicera** [comment]
batch size 20   
imgsize 640  
4 gpu 1080ti  
yolov8s

It will be out of memory

**Comment by Laughing-q** [comment]
@alicera it also depends on your number of instances per image. Also It seems that 1080ti doesn't support amp training so it takes more memory for fp32 training. 
BTW please give a try of our new arg `min_memory` which can save memory but may slow down the training speed. Just use the latest version and add `min_memory=True` to launch training.

**Comment by alicera** [comment]
```
yolo detect train data=custom.yaml model=yolov8m.pt epochs=100 imgsz=640 batch=24 device=0,1,2,3 min_memory=True
```
At the 27 epoch, it was still out of memory with new arg min_memory

**Comment by ExtReMLapin** [comment]
Alright, i'm having the same kind-ish of issue, the issue is it crashed at the epoch#70 (out of 400) which took 5 hours to reach

![](https://i.imgur.com/aqRX82q.png)

**Comment by pderrenger** [comment]
@ExtReMLapin it looks like your system is running out of memory during training at epoch 70. This could be due to a variety of factors such as batch size, image size, number of GPUs, or the specific architecture of the model. It may be worth trying a smaller batch size or reducing the image size to see if that helps alleviate the memory issue. Additionally, optimizing the model architecture or exploring memory-efficient training strategies could potentially address the problem.

Would you mind sharing more details about your hardware setup, the exact command you're using for training, and any specific customizations you've made to the YOLOv8 model? This information could help in diagnosing the issue more effectively.
