### ISSUE TITLE
when predicting a video.mp4, GPU overflows

### ISSUE THREAD

**Issue by wisrovi** [ultralytics/ultralytics#8433]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

because when I use yolo, in particular version 8), to make the prediction of a video.mp4, it overflows on the GPU and the process stops, is there a way to control that it does not stop? In training can I use the batch and with this I control that it does not overflow in the GPU, but in predict I don't know how to do it?

overflow = uses the entire GPU and since there is no more, the process stops

why??

**Comment by glenn-jocher** [comment]
@wisrovi hello! It seems like you're encountering GPU memory overflow issues during inference on a video. This can happen if the video frames are too large or if there's not enough GPU memory available. Here's a quick tip to help manage GPU memory usage during prediction:

You can try reducing the `--imgsz` (image size) parameter to lower the resolution at which the model processes each frame. This will reduce the GPU memory required for each prediction. Additionally, you can process the video in batches by setting the `--batch-size` parameter to a value greater than 1, which can help manage memory usage.

Here's an example of how to use these parameters in the CLI:
```bash
yolo detect predict model=yolov8n.pt source=video.mp4 imgsz=640 batch-size=4
```

Adjust the `imgsz` and `batch-size` values according to your GPU's capabilities. Hope this helps! 😊👍

**Comment by Burhan-Q** [comment]
@wisrovi in addition to what Glenn shared, you can see some of the examples from the docs on using stream or how to [iterate the video frames](https://docs.ultralytics.com/modes/predict/#streaming-source-for-loop) and run prediction on each frame to lower the demand on the GPU.
