### ISSUE TITLE
AttributeError: 'Results' object has no attribute 'save'. See valid attributes below.

### ISSUE THREAD

**Issue by tang-yt** [ultralytics/ultralytics#8434]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

`from ultralytics import YOLO

model = YOLO("runs/detect/train/weights/best.pt")
results = model(['img/bus.jpg', 'img/zidane.jpg'],  stream=True)  # return a list of Results objects

for result in results:
    print(f"res = {result}")
    boxes = result.boxes  # Boxes object for bounding box outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Probs object for classification outputs
    result.save()  # save to disk`

![image](https://github.com/ultralytics/ultralytics/assets/85331892/ce62d391-179f-44fe-b9bf-c7985c3bb29c)

### Environment

Ultralytics YOLOv8.1.2 🚀 Python-3.10.13 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce RTX 4050 Laptop GPU, 6140MiB)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@tang-yt hello! It looks like you're trying to save the results to disk using a `save()` method on the `Results` object, which isn't available. To save the results, you can use the `save()` method on each `result` within the loop, but you need to specify the filename. Here's a corrected version of your code:

```python
from ultralytics import YOLO

model = YOLO("runs/detect/train/weights/best.pt")
results = model(['img/bus.jpg', 'img/zidane.jpg'], stream=True)

for i, result in enumerate(results):
    print(f"res = {result}")
    boxes = result.boxes  # Boxes object for bounding box outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Probs object for classification outputs
    result.save(filename=f'result_{i}.jpg')  # specify filename to save to disk
```

This will save each result as an image with the filename `result_i.jpg`, where `i` is the index of the result in the list. If you have any more questions or need further assistance, feel free to ask! 😊👍

**Comment by Burhan-Q** [comment]
@tang-yt the `.save()` method was added in a more recent version of Ultralytics. Try updating your installation `pip install -U ultralytics` and the `.save()` method will be available.

**Comment by shy0625** [comment]
> @tang-yt hello! It looks like you're trying to save the results to disk using a `save()` method on the `Results` object, which isn't available. To save the results, you can use the `save()` method on each `result` within the loop, but you need to specify the filename. Here's a corrected version of your code:
> 
> ```python
> from ultralytics import YOLO
> 
> model = YOLO("runs/detect/train/weights/best.pt")
> results = model(['img/bus.jpg', 'img/zidane.jpg'], stream=True)
> 
> for i, result in enumerate(results):
>     print(f"res = {result}")
>     boxes = result.boxes  # Boxes object for bounding box outputs
>     masks = result.masks  # Masks object for segmentation masks outputs
>     keypoints = result.keypoints  # Keypoints object for pose outputs
>     probs = result.probs  # Probs object for classification outputs
>     result.save(filename=f'result_{i}.jpg')  # specify filename to save to disk
> ```
> 
> This will save each result as an image with the filename `result_i.jpg`, where `i` is the index of the result in the list. If you have any more questions or need further assistance, feel free to ask! 😊👍

#################
it doesn't work :

    result.save(filename=f'result_{i}.jpg')  # specify filename to save to disk
  File "E:\anaconda\envs\yolov8\lib\site-packages\ultralytics\utils\__init__.py", line 156, in __getattr__
    raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
AttributeError: 'Results' object has no attribute 'save'. See valid attributes below.
