### ISSUE TITLE
How to detect moving objects only

### ISSUE THREAD

**Issue by nati223** [ultralytics/ultralytics#8439]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi all.

For a project of mine, I film streets with traffic of cars, buses etc...and there are also parking cars in the frame.
For my project I am interested only in moving vehicles, and actually the detection data of static cars can impair my project results (as I am extracting all detection data into a data frame for further processing). The scale I am dealing with is hours of filmed street traffic.

I tried to remove the background with cv2, but it really imparis the detections by YOLOv8.

Is there a reliable way to make YOLO track only objects that move? 

Thanks!

**Comment by glenn-jocher** [comment]
@nati223 hi there! 👋

To detect only moving objects with YOLOv8, you can combine YOLO's object detection capabilities with a motion detection algorithm like background subtraction. Here's a simplified approach using OpenCV for motion detection:

```python
import cv2
from ultralytics import YOLO

# Initialize YOLOv8 and background subtractor
model = YOLO('yolov8n.pt')
back_sub = cv2.createBackgroundSubtractorMOG2(history=500, varThreshold=100, detectShadows=True)

# Process video
cap = cv2.VideoCapture('your_video.mp4')
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Apply background subtraction
    fg_mask = back_sub.apply(frame)

    # Detect objects with YOLOv8
    results = model(frame)

    # Filter out static objects
    moving_objects = []
    for *box, conf, cls in results.xyxy[0].cpu().numpy():
        x1, y1, x2, y2 = map(int, box)
        # Check if the detected object has motion
        if fg_mask[y1:y2, x1:x2].mean() > 25:  # Adjust the threshold value as needed
            moving_objects.append((x1, y1, x2, y2, conf, cls))

    # Now `moving_objects` contains only moving objects
    # You can further process `moving_objects` as needed

cap.release()
```

This code snippet uses a background subtractor to create a foreground mask, which helps in identifying moving objects. Then, it filters YOLOv8 detections based on the mask. Adjust the threshold value in the `if` condition to fine-tune the sensitivity to motion.

Hope this helps with your project! Let us know if you have any more questions. 😊

**Comment by nati223** [comment]
Thanks! It helped me a lot!

Do you think that for a more accurate detection using YOLOv8-OBB will perform better? Or they are basically the same for such task?

**Comment by glenn-jocher** [comment]
@nati223 Glad to hear the solution was helpful! 😊

Regarding your question, YOLOv8-OBB (Oriented Bounding Boxes) can indeed provide more precise detection for objects that have a specific orientation, such as vehicles on a road. It captures the object's orientation, which might be beneficial for analyzing traffic patterns or vehicle dynamics more accurately.

For moving object detection, both YOLOv8 and YOLOv8-OBB can be effective. The choice between them would depend on whether the orientation information adds value to your project. If orientation plays a crucial role in your analysis, YOLOv8-OBB could offer that extra layer of detail.

Here's a quick example of how you might use YOLOv8-OBB:

```python
from ultralytics import YOLO

# Initialize YOLOv8-OBB model
model = YOLO('yolov8n-obb.pt')

# Process an image
img = 'path/to/your/image.jpg'
results = model(img)

# Use results as needed
```

Hope this helps, and best of luck with your project!
