### ISSUE TITLE
Object detection model on custom dataset set has many errors

### ISSUE THREAD

**Issue by GR899** [ultralytics/ultralytics#8451]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Trying to train a custom data set and am receiving the following errors:

```
% yolo detect train data=YOLOV8-SS.yaml model=yolov8n.pt epochs=10
Ultralytics YOLOv8.1.18 🚀 Python-3.12.1 torch-2.2.0 CPU (Apple M1)
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=YOLOV8-SS.yaml, epochs=10, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train4, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train4
Traceback (most recent call last):
  File "/Users/CT/miniforge3/envs/apple-yoloSS/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 133, in __init__
    self.data = check_det_dataset(self.args.data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/CT/miniforge3/envs/apple-yoloSS/lib/python3.12/site-packages/ultralytics/data/utils.py", line 295, in check_det_dataset
    data["nc"] = len(data["names"])
                 ^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/CT/miniforge3/envs/apple-yoloSS/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/Users/CT/miniforge3/envs/apple-yoloSS/lib/python3.12/site-packages/ultralytics/cfg/__init__.py", line 568, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/CT/miniforge3/envs/apple-yoloSS/lib/python3.12/site-packages/ultralytics/engine/model.py", line 625, in train
    self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/CT/miniforge3/envs/apple-yoloSS/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 137, in __init__
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
RuntimeError: Dataset 'YOLOV8-SS.yaml' error ❌ object of type 'NoneType' has no len()
(apple-yoloSS)
```

### Environment

yolo checks
Ultralytics YOLOv8.1.18 🚀 Python-3.12.1 torch-2.2.0 CPU (Apple M1)
Setup complete ✅ (8 CPUs, 16.0 GB RAM, 374.7/460.4 GB disk)

OS                  macOS-14.3.1-arm64-arm-64bit
Environment         Darwin
Python              3.12.1
Install             pip
RAM                 16.00 GB
CPU                 Apple M1
CUDA                None

matplotlib          ✅ 3.8.2>=3.3.0
opencv-python       ✅ 4.9.0>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.2.0>=1.8.0
torchvision         ✅ 0.17.0>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.0>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
(apple-yoloSS)

### Minimal Reproducible Example

 yolo detect train data=YOLOV8-SS.yaml model=yolov8n.pt epochs=10

### Additional

.yaml file is as follows. NOTE: have redacted complete directory for privacy/security reasons however full directory is listed within the file:

```
path:{redacted}/YOLOV8-TESTS/HUGE-SUB/datasets
train: {redacted}/YOLOV8-TESTS/HUGE-SUB/datasets/train/images
val: {redacted}/YOLOV8-TESTS/HUGE-SUB/datasets/train/images

names:
```

Any assistance, suggestions, etc. will be greatly appreciated. Thanks.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@GR899 hey there! 👋 It looks like the issue might be related to the `names` field in your YAML file being empty or not properly defined. The error message indicates that the `names` list, which should contain your class names, is not being correctly read, leading to a `NoneType` error when trying to determine its length.

Please ensure that your `names` field in the `YOLOV8-SS.yaml` file is correctly populated with a list of class names, like so:

```yaml
names: ['class1', 'class2', 'class3']  # Example class names
```

Make sure there are no formatting issues in your YAML file and that the `names` field is not empty or commented out. Once you've updated your YAML file, try running your training command again.

If you continue to face issues, feel free to share more details or reach out again! 🚀

**Comment by GR899** [comment]
Hi @glenn-jocher - thanks for the suggestion, I did find garbage text in my file, removed it and re-ran. 

I'm having other issues with a predict detect issue and will submit separately. Many thanks for your quick reply and good suggestions.

**Comment by glenn-jocher** [comment]
@GR899 hi there! 😊 I'm glad to hear that removing the garbage text resolved the initial issue. If you encounter any more problems or have questions, feel free to open a new issue for the predict detect issue you mentioned. We're here to help. Thanks for reaching out and for your kind words!
