### ISSUE TITLE
how to use embed

### ISSUE THREAD

**Issue by Erhaiboy** [ultralytics/ultralytics#8454]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

SyntaxError: 'embed' is not a valid YOLO argument. Similar arguments are i.e. ['seed=0'].
how to use embed to get feature

**Comment by glenn-jocher** [comment]
@Erhaiboy hello! It looks like you're trying to extract features using the `embed` argument, which is indeed a great way to get model embeddings. The correct usage involves specifying the layers from which you want to extract features. Here's a quick example on how to use it in Python:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('yolov8n.pt')  # Example with YOLOv8n

# Specify the layers you want embeddings from
results = model.predict('path/to/image.jpg', embed=[137, 148])
```

In this example, `[137, 148]` are the indices of the layers from which we want to extract features. Make sure to replace `'path/to/image.jpg'` with the path to your image and adjust the layer indices according to your specific model architecture.

If you're using the CLI and encountering this error, please note that feature extraction via embeddings is primarily designed for use within the Python environment. For more detailed guidance on extracting features or embeddings, I recommend checking our documentation or discussions for specific examples and use cases. Happy coding! 😊

**Comment by TianyuCuiOvO** [comment]
> @Erhaiboy hello! It looks like you're trying to extract features using the `embed` argument, which is indeed a great way to get model embeddings. The correct usage involves specifying the layers from which you want to extract features. Here's a quick example on how to use it in Python:
> 
> ```python
> from ultralytics import YOLO
> 
> # Load your model
> model = YOLO('yolov8n.pt')  # Example with YOLOv8n
> 
> # Specify the layers you want embeddings from
> results = model.predict('path/to/image.jpg', embed=[137, 148])
> ```
> 
> In this example, `[137, 148]` are the indices of the layers from which we want to extract features. Make sure to replace `'path/to/image.jpg'` with the path to your image and adjust the layer indices according to your specific model architecture.
> 
> If you're using the CLI and encountering this error, please note that feature extraction via embeddings is primarily designed for use within the Python environment. For more detailed guidance on extracting features or embeddings, I recommend checking our documentation or discussions for specific examples and use cases. Happy coding! 😊

@glenn-jocher thank u for the example ,when i apply this example i notice the output with "one2many" and "one2one", if i want the objective feature for downstream application, what should i do? Cause i still confused with the model indices and structure. Thank you a lot  for your continued support in answering questions for the Yolo series models!!!!

**Comment by glenn-jocher** [comment]
@TianyuCuiOvO you're welcome! For downstream applications, you can use the "one2one" embeddings, which provide a direct mapping from input to output features. If you're unsure about the model indices and structure, you can inspect the model layers using `model.model` to identify the appropriate layers for embedding extraction. If you need further assistance, please refer to our documentation for detailed guidance.

**Comment by huaiguang233** [comment]
> @Erhaiboy hello! It looks like you're trying to extract features using the argument, which is indeed a great way to get model embeddings. The correct usage involves specifying the layers from which you want to extract features. Here's a quick example on how to use it in Python:`embed`
> 
> ```python
> from ultralytics import YOLO
> 
> # Load your model
> model = YOLO('yolov8n.pt')  # Example with YOLOv8n
> 
> # Specify the layers you want embeddings from
> results = model.predict('path/to/image.jpg', embed=[137, 148])
> ```
> 
> In this example, are the indices of the layers from which we want to extract features. Make sure to replace with the path to your image and adjust the layer indices according to your specific model architecture.`[137, 148]``'path/to/image.jpg'`
> 
> If you're using the CLI and encountering this error, please note that feature extraction via embeddings is primarily designed for use within the Python environment. For more detailed guidance on extracting features or embeddings, I recommend checking our documentation or discussions for specific examples and use cases. Happy coding! 😊

Hello, I'm not quite sure what "[137, 148]" means in your example. Can you explain it? Are they the layers of the neural network?

**Comment by ysig** [comment]
Hi @glenn-jocher,

I'm also interested in this functionality. I'm trying to use it for fastsam. Problem is:

a) I'm having a hard time locating where the layers are defined in your codebase so I can select the one I want
b) if I use the default one what I get is one dimensional vector but what I need is a spatial embedding so I can then interpolate and multiply it with the segmented region.

How can I do this?
Thank you,

**Comment by glenn-jocher** [comment]
To locate the layers in the FastSAM model, you can inspect the `model.model` attribute after loading the model, which will display the architecture and allow you to identify the layers for embedding extraction. For spatial embeddings, ensure you're selecting a feature map layer rather than a fully connected (linear) output. If further guidance is needed, feel free to share specific details of your implementation challenge.
