### ISSUE TITLE
When I transfer the yolo world to coreml with customised vocabulary, it works in intel chip, but not in M1, M2 chip 

### ISSUE THREAD

**Issue by qihuijia** [ultralytics/ultralytics#8461]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

Hi, guys, thanks very much to support the yolo world model so quickly. But I find something wrong when I export the coreml model.

### Environment

Ultralytics YOLOv8.1.18 🚀 Python-3.11.4 torch-2.2.1 CPU (Apple M2)
Setup complete ✅ (8 CPUs, 16.0 GB RAM, 190.9/228.3 GB disk)

### Minimal Reproducible Example

```python
import torch
from ultralytics import YOLO  # Assuming you have Ultralytics installed

with torch.no_grad():
    # Initialize a YOLO-World model
    model = YOLO("yolov8s-world.pt")  # or select yolov8m/l-world.pt
    # Define custom classes
    model.set_classes(
        [
            "ball",
            "object",
            "painting",
            "flower",
            "vase",
            "lavander",
            "rabbit",
        ]
    )
    # # Save the model with the defined offline vocabulary (modified code)
    model.save("custom_yolov8s.pt")  # Save extra metadata for CoreML
    model = YOLO("custom_yolov8s.pt")
    # Export the model to CoreML format
    model.export(format="coreml", nms=True)

    print("Model exported successfully to custom_yolov8s.mlpackage for CoreML inference!")
```

### Additional

After I got the custom_yolov8s.mlpackage, then I open it directly in my M2 macbook, then tap `Preview`, upload an image, but the result is `No objects detected`.

![Screenshot 2024-02-26 at 09 54 33](https://github.com/ultralytics/ultralytics/assets/138494515/6c2c1009-8c6b-4a28-8567-f3a42b79453d)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@qihuijia hi there! Thanks for reaching out and for your kind words about the YOLO world model support. 🌍

It seems like you're encountering an issue with CoreML on Apple's M1 and M2 chips. This could be related to the CoreML model's compatibility with the neural engine on these chips. Here's a quick suggestion you might find helpful:

Ensure your CoreML model is using the latest format compatible with the M1 and M2 chips. You can specify the target iOS version when exporting to CoreML to ensure compatibility. For example:

```python
model.export(format="coreml", nms=True, target_ios='15.0')
```

Adjust `target_ios` to match the minimum iOS version that supports the features you need, considering the M1 and M2 chip capabilities.

If the issue persists, it might be helpful to check the CoreML model's specifications and ensure they align with what the M1 and M2 neural engine expects. Sometimes, specific layers or configurations might not be fully supported, leading to unexpected behavior.

Let us know if this helps or if you're still facing issues. We're here to help! 🚀

**Comment by qihuijia** [comment]
there is an error:
`SyntaxError: 'target_ios' is not a valid YOLO argument` when I add the parameter: `target_ios `

**Comment by glenn-jocher** [comment]
@qihuijia hi there! 😊 It looks like there was a misunderstanding in my previous suggestion. My apologies for the confusion. The `target_ios` parameter isn't a valid argument for the `model.export()` function in the Ultralytics YOLOv8 library. 

For CoreML exports, the library automatically handles compatibility to the extent possible within the CoreML model's constraints. If you're targeting specific iOS versions or Apple chips, adjustments might need to be made post-export using Apple's CoreML tools directly.

For now, you can simply use:
```python
model.export(format="coreml", nms=True)
```
And then, if necessary, use Apple's Core ML tools for any further optimizations or compatibility adjustments. 

Sorry for the mix-up, and thanks for your understanding! 🙏

**Comment by glenn-jocher** [comment]
@qihuijia hi there! 😊 Sorry to hear you're still facing issues. Could you please share a bit more detail about what specifically isn't working? Any error messages or unexpected behavior descriptions would be really helpful. In the meantime, here's a quick check you can do:

Ensure your model is correctly loaded and the export command is executed without errors:

```python
from ultralytics import YOLO

model = YOLO('custom_yolov8s.pt')
model.export(format='coreml')
```

If you're encountering specific errors during this process, please let us know! We're here to help.

**Comment by qihuijia** [comment]
I think it works for this code in M1/M2
```python
def yolo_world_export():
    with torch.no_grad():
        # Initialize a YOLO model with pretrained weights
        model = YOLO(
            "yolov8s-world.pt"
        )  # You can also choose yolov8m/l-world.pt based on your needs

        # Define custom classes specific to your application
        custom_classes = [
            "ball",
            "flower",
            "vase",
            "lavander",
            "boy",
            "car",
        ]
        model.set_classes(custom_classes)

        # Save the model with the custom classes defined (modified code)
        model.save(
            "custom_yolov8s.pt"
        )  # This saves extra metadata required for CoreML conversion

        # # Load the saved model with custom classes
        model = YOLO("custom_yolov8s.pt")

        # # Export the model to CoreML format with non-maximum suppression enabled
        model.export(format="coreml", nms=True)
```
but if I set the custom_classes count more than 7, it will not work in M1/M2 chip macbook. But it still work in intel chip macbook

**Comment by glenn-jocher** [comment]
@qihuijia hi there! 😊 Thanks for sharing your findings and the code snippet. It's interesting to note the behavior you observed regarding the `custom_classes` count affecting the CoreML model's performance on M1/M2 chips.

The issue you're encountering might be related to how the CoreML model is optimized for the neural engine on Apple's M1/M2 chips. These chips have specific optimizations that might behave differently depending on the model's complexity and the number of classes.

A potential workaround could be to ensure that your model is as optimized as possible before exporting it to CoreML. This includes pruning and quantization if applicable. However, since these options are more nuanced within the Ultralytics export functionality, focusing on the model's architecture and the export process might offer some clues.

For now, you might want to experiment with the following:
- Ensure your environment and all libraries are up to date, especially `torch`, `coremltools`, and `ultralytics`.
- After exporting to CoreML, use Apple's CoreML tools to further inspect and potentially optimize the model for M1/M2 compatibility.

```python
# Example: Load and optimize the CoreML model using coremltools (pseudo-code)
import coremltools

model = coremltools.models.MLModel('custom_yolov8s.mlmodel')
model.optimize()  # This is a pseudo-method. Use actual optimization methods from coremltools.
```

Please keep in mind that the above code is just a placeholder to illustrate the approach. Refer to the `coremltools` [documentation](https://coremltools.readme.io/docs) for actual optimization techniques.

If the issue persists, it might be helpful to reach out to the CoreML community or Apple's developer forums for more targeted advice on M1/M2 optimizations.

Hope this helps a bit! Let us know if you have any more questions or updates. 🚀

**Comment by pierre1618** [comment]
Hey @qihuijia,

I encountered the same issue with the M1 Mac (your original code works on Intel MacBook). I've found a workaround, albeit a bit crude, that might solve your problem. The only caveat is that you're limited to 80 custom classes—no more, no less.

To elaborate on the solution: it appears that the original YOLO-World model with COCO classes converts seamlessly to CoreML. However, when we introduce `set_classes`, it's only detected on Intel MacBooks. My workaround involves utilizing the CoreML specification of the model without custom classes and integrating the weights of the model with custom classes. I believe this issue will be resolved soon, but in the meantime, this workaround might be of immediate assistance to you.

```python
import torch
from ultralytics import YOLO 
import coremltools as ct

def list_to_dict_string(lst):
    result = "{" + ", ".join([f"{i}: '{item}'" for i, item in enumerate(lst)]) + "}"
    return result


model = YOLO('yolov8l-world.pt')
model.export(format="coreml", nms=True,half=True)
with torch.no_grad():
    # Define custom classes
    classes=  ['goldfish', 'keyboard', 'lamp', "underwear", "sofa", "stool", "picture frame", "pen", "monitor",  "eraser", "Remote control", "iPad", "Gloves", "Printer", "Speaker", 'cat', 'dog', 'horse', 'flower', 'flower', 'flower', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'flower', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']
    model.set_classes(classes)
    
    model.save("custom_yolov8l_custom.pt")  
    model=YOLO("custom_yolov8l_custom.pt")
    model.export(format="coreml", nms=True,half=True)
    
model = ct.models.MLModel('yolov8l-world.mlpackage')
model2 = ct.models.MLModel('custom_yolov8l_custom.mlpackage')
spec = model.get_spec()
spec.description.metadata.userDefined["names"]=list_to_dict_string(classes)
for k in range(len(classes)):
    spec.pipeline.models[1].nonMaximumSuppression.stringClassLabels.vector[k]=classes[k]
spec.pipeline.models[1].nonMaximumSuppression.iouThreshold=0.45 #default 0.45
spec.pipeline.models[1].nonMaximumSuppression.confidenceThreshold=0.25 #default 0.25

model = ct.models.MLModel(spec, weights_dir=model2.weights_dir)
model.save("MyModel.mlpackage")

```

**Comment by pierre1618** [comment]
After further testing, I've come to realize that all my previous efforts were unnecessary. All that's needed is to set 80 classes using the set_classes method. That's it, your orginal code will work with 80 classes. 

```python 
import torch
from ultralytics import YOLO 
import coremltools as ct

def list_to_dict_string(lst):
    result = "{" + ", ".join([f"{i}: '{item}'" for i, item in enumerate(lst)]) + "}"
    return result

def pad_classes(classes, total_classes=80):
    while len(classes) < total_classes:
        classes.append('')
    return classes



with torch.no_grad():
    # Define custom classes
    model = YOLO('yolov8l-world.pt')
    classes=[ 
            "ball",
            "object",
            "painting",
            "flower",
            "vase",
            "lavander",
            "rabbit",
        ]
    model.set_classes(pad_classes(classes))
    model.save("custom_yolov8l_custom.pt")  
    model=YOLO("custom_yolov8l_custom.pt")
    model.export(format="coreml", nms=True,half=True)
    
model = ct.models.MLModel('custom_yolov8l_custom.mlpackage')
spec = model.get_spec()
#spec.description.metadata.userDefined["names"]=list_to_dict_string(classes)
#for k in range(len(classes)):
#    spec.pipeline.models[1].nonMaximumSuppression.stringClassLabels.vector[k]=classes[k]
spec.pipeline.models[1].nonMaximumSuppression.iouThreshold=0.45 #default 0.45
spec.pipeline.models[1].nonMaximumSuppression.confidenceThreshold=0.25 #default 0.25

model = ct.models.MLModel(spec, weights_dir=model.weights_dir)
model.save("MyModel.mlpackage")
```

**Comment by glenn-jocher** [comment]
@pierre1618 hey there! 😊

Thanks for sharing your insights! It's great to hear you've found a straightforward solution by padding the class list to 80 for the CoreML export. This approach simplifies the process significantly and ensures compatibility across different chip architectures.

Your code snippet is a handy reference for anyone looking to adapt their model with a custom class list. It's a clever workaround to pad the classes and maintain the required format for CoreML models. 

Keep up the great work, and feel free to reach out if you have more discoveries or need further assistance. Happy coding! 🚀

**Comment by wixphotos** [comment]
> @pierre1618 hey there! 😊
> 
> Thanks for sharing your insights! It's great to hear you've found a straightforward solution by padding the class list to 80 for the CoreML export. This approach simplifies the process significantly and ensures compatibility across different chip architectures.
> 
> Your code snippet is a handy reference for anyone looking to adapt their model with a custom class list. It's a clever workaround to pad the classes and maintain the required format for CoreML models.
> 
> Keep up the great work, and feel free to reach out if you have more discoveries or need further assistance. Happy coding! 🚀

Hi, may I know whether this works for Apple M3 as well. After pip install clip, I seem to get error msg below:
 module 'clip' has no attribute 'load'
 Any help is appreciated to point me to the right direction. Basically I am trying to run below but I wonder if I need some packages installed first after I executed: !git clone https://github.com/ultralytics/yolov5
 -------------------
 import torch
from ultralytics import YOLO 
import coremltools as ct

def list_to_dict_string(lst):
    result = "{" + ", ".join([f"{i}: '{item}'" for i, item in enumerate(lst)]) + "}"
    return result

def pad_classes(classes, total_classes=80):
    while len(classes) < total_classes:
        classes.append('')
    return classes



with torch.no_grad():
    # Define custom classes
    model = YOLO('yolov8l-world.pt')
    classes=[ 
            "ball",
            "object",
            "painting",
            "flower",
            "vase",
            "lavander",
            "rabbit",
        ]
    model.set_classes(pad_classes(classes))
    model.save("custom_yolov8l_custom.pt")  
    model=YOLO("custom_yolov8l_custom.pt")
    model.export(format="coreml", nms=True,half=True)

**Comment by wixphotos** [comment]
> I think it works for this code in M1/M2
> 
> ```python
> def yolo_world_export():
>     with torch.no_grad():
>         # Initialize a YOLO model with pretrained weights
>         model = YOLO(
>             "yolov8s-world.pt"
>         )  # You can also choose yolov8m/l-world.pt based on your needs
> 
>         # Define custom classes specific to your application
>         custom_classes = [
>             "ball",
>             "flower",
>             "vase",
>             "lavander",
>             "boy",
>             "car",
>         ]
>         model.set_classes(custom_classes)
> 
>         # Save the model with the custom classes defined (modified code)
>         model.save(
>             "custom_yolov8s.pt"
>         )  # This saves extra metadata required for CoreML conversion
> 
>         # # Load the saved model with custom classes
>         model = YOLO("custom_yolov8s.pt")
> 
>         # # Export the model to CoreML format with non-maximum suppression enabled
>         model.export(format="coreml", nms=True)
> ```
> 
> but if I set the custom_classes count more than 7, it will not work in M1/M2 chip macbook. But it still work in intel chip macbook

Hi, may I check whether this also works with M3 chip MacBook?

**Comment by qihuijia** [comment]
> > I think it works for this code in M1/M2
> > ```python
> > def yolo_world_export():
> >     with torch.no_grad():
> >         # Initialize a YOLO model with pretrained weights
> >         model = YOLO(
> >             "yolov8s-world.pt"
> >         )  # You can also choose yolov8m/l-world.pt based on your needs
> > 
> >         # Define custom classes specific to your application
> >         custom_classes = [
> >             "ball",
> >             "flower",
> >             "vase",
> >             "lavander",
> >             "boy",
> >             "car",
> >         ]
> >         model.set_classes(custom_classes)
> > 
> >         # Save the model with the custom classes defined (modified code)
> >         model.save(
> >             "custom_yolov8s.pt"
> >         )  # This saves extra metadata required for CoreML conversion
> > 
> >         # # Load the saved model with custom classes
> >         model = YOLO("custom_yolov8s.pt")
> > 
> >         # # Export the model to CoreML format with non-maximum suppression enabled
> >         model.export(format="coreml", nms=True)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but if I set the custom_classes count more than 7, it will not work in M1/M2 chip macbook. But it still work in intel chip macbook
> 
> Hi, may I check whether this also works with M3 chip MacBook?

Yes, you are right. But if when you try more than 18 classes, it will not work

**Comment by glenn-jocher** [comment]
@wixphotos hi there! 😊

Yes, the approach you've outlined should theoretically work on an M3 chip MacBook as well, as the process of exporting a model to CoreML and defining custom classes isn't directly dependent on the chip but rather on the CoreMLtools compatibility and Python environment setup. That being said, the actual compatibility can depend on the specific versions of the libraries (torch, coremltools, etc.) you're using and whether they fully support the new M3 architecture yet. 

If you're encountering any specific errors or issues, updating your libraries to their latest versions might help: 

```bash
pip install --upgrade torch coremltools ultralytics
```

Regarding the error message `module 'clip' has no attribute 'load'`, it seems unrelated to the YOLOv8 exporting process. This error might indicate an issue with how CLIP is installed or imported in your environment. If CLIP is necessary for your project, please ensure it's correctly installed and that there's no naming conflict with your files or folders named `clip.py` that could be causing an import mismatch.

For YOLOv5 cloning and YOLOv8 usage, just ensure that you've installed Ultralytics YOLOv8 package as per the documentation, since YOLOv5 and YOLOv8 are managed as separate projects under the Ultralytics banner.

Let me know if there's anything else I can help with. Keep experimenting, and happy coding! 🚀

**Comment by wixphotos** [comment]
Hi Glenn,

Thank you for your guidance. I’ve tested it and it does work with M3 chip as well. The clip was not working because I did "pip install clip”. But after I "pip uninstall clip" followed by "pip install git+https://github.com/openai/CLIP.git” then the clip is working.

I first used YOLOv5 for computer vision since last year. Can you help me understand the following:
1) How would you explain to a newbie when to use opencv and when YOLO, or is YOLO superior in all aspects?
2) There are many versions of YOLO, can I say just use the highest one (eg YOLOv8?) because of improvements in accuracy and speed, or not necessary?
3) Is YOLO-World Zero-Shot Object Detection main purpose to detect objects without training? Is it also developed by you?

Thank you so much for helping me understand YOLO.

**Comment by wixphotos** [comment]
When I did model.predict, the output has confidence output for 80 classes. Are you saying the objects from 19 to 80 won’t be detected?

**Comment by glenn-jocher** [comment]
Hey there! 😊

When you set custom classes and use `model.set_classes(custom_classes)`, the model will indeed prioritize these custom classes during prediction. However, it doesn't mean objects belonging to classes 19 to 80 won't be detected at all. It's about the focus given to the specified custom classes during prediction. 

The model's ability to detect other classes not defined in `custom_classes` might be reduced, depending on the overlap or similarity with the custom classes you've defined. If a class outside of your custom set appears very clearly in an image, there's still a chance the model could recognize it, but the confidence for classes not in your custom list may generally be lower.

If you need to detect a broader range of objects, you might consider not setting custom classes or expanding your custom class list to include those additional objects of interest. 

Let me know if you need further clarification! Happy to help. 🚀

**Comment by akaomerr** [comment]
> After further testing, I've come to realize that all my previous efforts were unnecessary. All that's needed is to set 80 classes using the set_classes method. That's it, your orginal code will work with 80 classes.
> 
> ```python
> import torch
> from ultralytics import YOLO 
> import coremltools as ct
> 
> def list_to_dict_string(lst):
>     result = "{" + ", ".join([f"{i}: '{item}'" for i, item in enumerate(lst)]) + "}"
>     return result
> 
> def pad_classes(classes, total_classes=80):
>     while len(classes) < total_classes:
>         classes.append('')
>     return classes
> 
> 
> 
> with torch.no_grad():
>     # Define custom classes
>     model = YOLO('yolov8l-world.pt')
>     classes=[ 
>             "ball",
>             "object",
>             "painting",
>             "flower",
>             "vase",
>             "lavander",
>             "rabbit",
>         ]
>     model.set_classes(pad_classes(classes))
>     model.save("custom_yolov8l_custom.pt")  
>     model=YOLO("custom_yolov8l_custom.pt")
>     model.export(format="coreml", nms=True,half=True)
>     
> model = ct.models.MLModel('custom_yolov8l_custom.mlpackage')
> spec = model.get_spec()
> #spec.description.metadata.userDefined["names"]=list_to_dict_string(classes)
> #for k in range(len(classes)):
> #    spec.pipeline.models[1].nonMaximumSuppression.stringClassLabels.vector[k]=classes[k]
> spec.pipeline.models[1].nonMaximumSuppression.iouThreshold=0.45 #default 0.45
> spec.pipeline.models[1].nonMaximumSuppression.confidenceThreshold=0.25 #default 0.25
> 
> model = ct.models.MLModel(spec, weights_dir=model.weights_dir)
> model.save("MyModel.mlpackage")
> ```
Hi, When I use the above codes for my own trained model, it does not work. When I type "best.pt" instead of "yolov8l-world.pt", I get the following error:
AttributeError: 'YOLO' object has no attribute 'set_classes'
How can I solve this problem?

**Comment by carlosmariacaraccia** [comment]
Hey! Guys, thanks a lot for all your effort, it's really awesome how much some of us outsiders can learn.
I have been following all of your documentation, so I downloaded a dataset with the Yolov11 labeling format and I was able to train a model and make predictions without an issue (cli). The model consists on beverage_detection. 
The model is converted without any problem to core ml, but I'm encountering issues when I want to run it. When I place it in an Xcode project it throughs not output. But what's really even more weird is that when I run a performance test (built in Xcode for the model), it works well in Mac, but it does not perform any test in an iPhone (left images below)

One more thing, it looks like the current and latest ultralytics package has the set_classes method removed, so I cannot perform any of the suggested solutions.
I've also tried two different PyTorch installations and had the same results.
torch==2.5.0, torch==2.4.0

Thanks a lot for your time and effort and if someone can hint me on what might be going on it will be great.

<img width="1243" alt="Screenshot 2024-12-11 at 10 33 02 AM" src="https://github.com/user-attachments/assets/21e8b502-af1b-492f-a8b2-2150e5890db8" />

<img width="1243" alt="Screenshot 2024-12-11 at 10 33 08 AM" src="https://github.com/user-attachments/assets/b3f16c56-f151-44c3-a81d-e681087a4325" />

**Comment by glenn-jocher** [comment]
Thank you for your detailed explanation! The issue with the CoreML model not producing output in your Xcode project but performing well on Mac could be linked to device-specific compatibility or the model's setup.

Regarding `set_classes`, it has been deprecated in the latest Ultralytics package. If you need class customization, you can modify your dataset or labels before training. For CoreML-specific issues, ensure your iPhone is running a compatible iOS version, and verify the CoreML model is not exceeding device hardware limitations. You may also try optimizing the model using Apple's CoreML tools.

For further debugging, consider consulting Apple's CoreML documentation or forums for project-specific guidance. Let us know if there's anything else you'd like assistance with!

**Comment by carlosmariacaraccia** [comment]
Thanks a lot for your answer, I'll try Apple's documentation and let you know.

**Comment by glenn-jocher** [comment]
Thanks for the update! Yes, please do check Apple's CoreML documentation and feel free to let us know if you have any other questions about implementing YOLO models in your iOS projects.
