### ISSUE TITLE
predict Yolov8-obbn with Numpy array buffer instead of JPegs?

### ISSUE THREAD

**Issue by GISScience** [ultralytics/ultralytics#8463]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I hope inferencing should also work in same way.

can anyone confirm that inferencing on numpy arrays is also possible for pre-trained networks ? 

results = model.predict(np.load('image1.npy'))  # will it work?

### Additional

i have checked 
https://github.com/ultralytics/ultralytics/issues/8199

**Comment by glenn-jocher** [comment]
@GISScience absolutely, you can directly use Numpy arrays for inference with YOLOv8 models. Your approach is almost correct. However, you might need to ensure that the Numpy array is in the correct format (HWC, RGB) before passing it to the `predict()` method. Here's a small tweak to your code:

```python
import numpy as np
from ultralytics import YOLO

# Load your model
model = YOLO('yolov8n.pt')  # Example model

# Load and preprocess your numpy array
image_np = np.load('image1.npy')
image_np = image_np[:, :, ::-1]  # Convert BGR to RGB if necessary

# Predict
results = model.predict([image_np])  # Note the list wrapping

# Process results
results.show()
```

Make sure your Numpy array is in the correct shape and color format. The model expects images in RGB format. If your array is in BGR (common with OpenCV), you'll need to convert it as shown above. Happy inferencing! 🚀
