### ISSUE TITLE
about predict  results question

### ISSUE THREAD

**Issue by QzYER** [ultralytics/ultralytics#847]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i get results is  results=model.predict(source=img,save=true,device="cpu")  ,
but output is :
Ultralytics YOLOv8.0.5 🚀 Python-3.8.15 torch-1.12.1 CPU
Fusing layers... 
YOLOv8x-seg summary: 295 layers, 71721619 parameters, 0 gradients, 343.7 GFLOPs
image 1/1 /test/202211220940238078176.jpg: 384x640 1 table, 301.2ms
Speed: 0.3ms pre-process, 301.2ms inference, 4.1ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/segment/predict2
Traceback (most recent call last):
  File "/home/bowen/下载/yolo8/YOLOv8_Efficient/test.py", line 27, in <module>
    boxes = results[0].boxes
TypeError: 'NoneType' object is not subscriptable
None

Process finished with exit code 1
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
but  results are normal  on GPU !
on GPU is :
 WARNING ⚠️ Ultralytics settings reset to defaults. 
This is normal and may be due to a recent ultralytics package update, but may have overwritten previous settings. 
You may view and update settings directly in '/home/bowen/.config/Ultralytics/settings.yaml'
加载模型时间 0.205033540725708
Ultralytics YOLOv8.0.7 🚀 Python-3.8.15 torch-1.12.1+cu113 CPU
Fusing layers... 
YOLOv8x-seg summary: 295 layers, 71721619 parameters, 0 gradients, 343.7 GFLOPs
[Ultralytics YOLO <class 'ultralytics.yolo.engine.results.Results'> instance
Ultralytics YOLO <class 'ultralytics.yolo.engine.results.Boxes'> masks
type: <class 'torch.Tensor'>
shape: torch.Size([1, 6])
dtype: torch.float32
Ultralytics YOLO <class 'ultralytics.yolo.engine.results.Masks'> masks
type: <class 'torch.Tensor'>
shape: torch.Size([1, 384, 640])
dtype: torch.float32
original size: (1080, 1920)
]
Ultralytics YOLO <class 'ultralytics.yolo.engine.results.Boxes'> masks
type: <class 'torch.Tensor'>
shape: torch.Size([1, 6])
dtype: torch.float32

**Comment by QzYER** [comment]
Is there anyone who has the same problem as me? Reasoning to get the box print on the CPU is different from that on the GPU

**Comment by AyushExel** [comment]
Please update to the latest version of ultralytics package where this issue might've been solved. Let me know if it still occurs

**Comment by QzYER** [comment]
> Thank you for your reply. After updating to the latest version, this bug has been fixed. Thanks again to the official team.

**Comment by pderrenger** [comment]
@QzYER you're welcome! I'm glad to hear that the issue has been resolved with the latest update. If you have any more questions or need further assistance, feel free to ask. Thank you for your support!
