### ISSUE TITLE
Image Quality Degradation with YOLOv8n-seg Compared to YOLOv8n

### ISSUE THREAD

**Issue by zhanghx0905** [ultralytics/ultralytics#8472]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello YOLOv8 Team,

I've been experimenting with the YOLOv8n-seg model for image processing, and I've noticed a significant degradation in the quality of the generated images compared to when I use the standard YOLOv8n model. 
The issue seems to be specific to the segmentation variant, as the standard model does not exhibit this problem.

That's the input image：

![input](https://github.com/ultralytics/ultralytics/assets/50790281/60003a18-d85b-4472-b10b-b05683c4450e)

That's what I got from YOLOv8n-seg:

![cv2](https://github.com/ultralytics/ultralytics/assets/50790281/e08f1cdf-4e10-4817-953a-91dfef3232d8)

That's output of YOLOv8n:

![image](https://github.com/ultralytics/ultralytics/assets/50790281/2b2464f2-e8af-4a45-9075-23a64ae2a345)

That‘s my code
```
import cv2
from ultralytics import YOLO

from ultralytics.engine.results import Results

# Load a pretrained YOLOv8n model
model = YOLO('yolov8n-seg.pt')
results: list[Results] = model.predict('input.png')  # list of 1 Results object
for r in results:
    im_array = r.plot()  # plot a BGR numpy array of predictions
    cv2.imwrite("cv2.jpg", im_array)
```

YOLOv8 version: ultralytics 8.1.18
Operating system and version: Windows 11 and Ubuntu 22.04

**Comment by zhanghx0905** [comment]
I find my solution from https://github.com/ultralytics/ultralytics/blob/main/examples/YOLOv8-Segmentation-ONNXRuntime-Python/main.py#L266

```
from typing import Optional

import cv2
import numpy as np
from ultralytics import YOLO
from ultralytics.engine.results import Results
from ultralytics.utils import yaml_load
from ultralytics.utils.checks import check_yaml
from ultralytics.utils.plotting import Colors


def draw_segment_results(im, r: Results, classes: dict, saveto: Optional[str] = None):
    """
    Draw and visualize results.

    Args:
        im (np.ndarray): original image, shape [h, w, c].
        r (Results): Results of segments.
        save (bool): save image annotated.

    Returns:
        None
    """
    assert r.boxes is not None and r.masks is not None

    color_palette = Colors()
    im_canvas = im.copy()
    if not isinstance(r.boxes.conf, np.ndarray):
        bboxes = zip(r.boxes.xyxy, r.boxes.conf.cpu().numpy(), r.boxes.cls.cpu().numpy())
    else:
        bboxes = zip(r.boxes.xyxy, r.boxes.conf, r.boxes.cls)
    segments = r.masks.xy
    for (box, conf, cls_), segment in zip(bboxes, segments):
        # draw contour and fill mask
        # white borderline
        cv2.polylines(im, np.int32([segment]), True, (255, 255, 255), 2) 
        cv2.fillPoly(im_canvas, np.int32([segment]), color_palette(int(cls_), bgr=True))

        # draw bbox rectangle
        cv2.rectangle(
            im,
            (int(box[0]), int(box[1])),
            (int(box[2]), int(box[3])),
            color_palette(int(cls_), bgr=True),
            1,
            cv2.LINE_AA,
        )
        cv2.putText(
            im,
            f"{classes[cls_]}: {conf:.3f}",
            (int(box[0]), int(box[1] - 9)),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.7,
            color_palette(int(cls_), bgr=True),
            2,
            cv2.LINE_AA,
        )

    # Mix image
    im = cv2.addWeighted(im_canvas, 0.3, im, 0.7, 0)

    # Save image
    if saveto is not None:
        cv2.imwrite(saveto, im)
    return im


# Load a pretrained YOLOv8n model
model = YOLO("yolov8n-seg.onnx")

im = cv2.imread("input.png")
results: list[Results] = model.predict(im)  # list of 1 Results object
for r in results:
    classes = yaml_load(check_yaml("coco128.yaml"))["names"]
    draw_segment_results(im, r, classes, saveto="demo.jpg")
```

**Comment by glenn-jocher** [comment]
@zhanghx0905 hey there! 🌟

I'm glad you found a solution that works for you! The code snippet you've shared from the YOLOv8-Segmentation example is indeed a great way to visualize segmentation results with bounding boxes, class labels, and confidence scores. It's a neat approach to overlaying the segmentation masks on the original image, enhancing the visual output.

If you have any more questions or need further assistance, feel free to reach out. Happy coding! 🚀
