### ISSUE TITLE
WandB support for YOLOv8

### ISSUE THREAD

**Issue by FnSK4R17s** [ultralytics/ultralytics#848]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I used to use WandB extensively with YOLOv5 but WandB support is not available for YOLOv8. Please add the support for WandB back into YOLOv8.

### Use case

WandB was really useful for rapid model training and evaluation. Plus all my models were available as artifacts on the WandB platform.

### Additional

I will be adding WandB logging support back in my fork of this repository and I would like to send a pull request to the main repository if needed.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by awarebayes** [comment]
Nice, would love to see it done!

**Comment by AyushExel** [comment]
Hi. We're constantly working with external partners to provide the best experience for users. These collaborations sometimes are time-bound. You can see all the active integrations including experiment tracking on the readme here - https://github.com/ultralytics/ultralytics#integrations

**Comment by ChrCoello** [comment]
@FnSK4R17s do you have a fork where you have started implementing back WandB ? Also a highly required feature here.

**Comment by FnSK4R17s** [comment]
@ChrCoello not yet, but I am working on it.

**Comment by AyushExel** [comment]
@ChrCoello wandb is added by default in the latest version

**Comment by ChrCoello** [comment]
Damn, all this work for nothing :)

**Comment by glenn-jocher** [comment]
@ChrCoello great news! I am glad to inform you that WandB support has already been added by default in the latest version of YOLOv8. So, you don't need to spend any time adding WandB tracking functionality to your YOLOv8 fork. You can now take advantage of this built-in feature. Please feel free to check out the updated documentation for implementation details and examples. If you have any further questions or concerns, please don't hesitate to ask.

**Comment by jam244** [comment]
> @ChrCoello great news! I am glad to inform you that WandB support has already been added by default in the latest version of YOLOv8. So, you don't need to spend any time adding WandB tracking functionality to your YOLOv8 fork. You can now take advantage of this built-in feature. Please feel free to check out the updated documentation for implementation details and examples. If you have any further questions or concerns, please don't hesitate to ask.

Hi, I am not able to find from documentation on how to train YOLOV8 with the  integrated Wandb support that is newly added. It would be great if you could post a link here. 

Till yesterday training was working fine. Now I am getting the following error : 

File "/opt/conda/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 1149, in getpass
"getpass was called, but this frontend does not support input requests."
IPython.core.error.StdinNotImplementedError: getpass was called, but this frontend does not support input requests.
wandb: ERROR Abnormal program exit

**Comment by glenn-jocher** [comment]
@jam244 hello, glad to hear that you are excited about WandB support in YOLOv8. You can find the implementation details and examples for the feature in the updated documentation. Regarding the error you are facing, it seems to be related to the IPython library and the Jupyter environment you are working on. To resolve this, please try running your code outside of Jupyter or try using a different front-end environment. If the error persists, please let us know and we will investigate further.

**Comment by jam244** [comment]
I resolved the issue. Just needed to login to wandb. But it came as a surprise. Just to confirm is it now not possible at all to train a YOLOV8 model without logging in to wandb? Sounds like a dependency. I would have expected wandb feature to be introduced as optional triggered by a flag.

**Comment by glenn-jocher** [comment]
@jam244 great to hear that you were able to resolve the issue. Regarding your question, while WandB is now integrated into YOLOv8, logging into WandB is still optional. However, tracking metrics during training or validation, as well as saving models and charts to the platform, require authentication with WandB. You can choose to authenticate with WandB when you wish to take advantage of these features, or you can choose not to and simply use YOLOv8 for training and inferencing. Hope that helps clarify things for you.

**Comment by heitorrapela** [comment]
Hello, it would be good to see an update on documentation about the usage of the wandb with yolov8.

**Comment by glenn-jocher** [comment]
@heitorrapela hello there, we appreciate your interest in utilizing WandB with YOLOv8. The good news is that support for WandB has been added by default in YOLOv8. To get started, you can log in to WandB, instantiate your YOLOv8 model object, and then utilize the built-in callbacks to track your training metrics, log your model artifacts, and generate charts. As for the specific details, we are actively working on updating the documentation to provide more information on WandB integration. Please stay tuned for updates, and feel free to reach out with any further questions or concerns in the meantime.

**Comment by AyushExel** [comment]
We'll work on Integration docs soon which will include wandb too

**Comment by heitorrapela** [comment]
Nice, thanks for the comments @glenn-jocher and @AyushExel

**Comment by ChanifRusydi** [comment]
Hi, any wandb integration related documentation that i can read? Im trying to train yolov8n. But nothing about wandb was shown up  after starting the training process using this command :
''' ps
yolo detect train data='C:\Users\User\Documents\machine_learning\yolov7\data\coco_traffic.yaml' model=yolov8n.yaml epochs=1 imgsz=640 device=0
'''
![Screenshot 2023-06-28 233943](https://github.com/ultralytics/ultralytics/assets/62838892/4e4a80ff-221d-4790-8a91-1667bdbd23c0)

Compared to when I train yolov7 model, I got this
![image](https://github.com/ultralytics/ultralytics/assets/62838892/14f90f8e-7919-4730-b44a-3ae51e04c6c5)

and the project (yolov7 training) shows up on my wandb account page. So, is there any configuration that I miss or something? thanks in advance

**Comment by RedBlaze42** [comment]
What version are you using ?

**Comment by ChanifRusydi** [comment]
> What version are you using ?

ultralytics = 8.0.73
wandb = 0.15.3

**Comment by ChanifRusydi** [comment]
Nevermind, after updating to version 8.0.124 wandb show up with no issues. At first,I thought I already have the latest version

> > What version are you using ?
> 
> ultralytics = 8.0.73 wandb = 0.15.3

**Comment by glenn-jocher** [comment]
@ChanifRusydi thank you for updating your version to 8.0.124. It's great to hear that WandB is now showing up without any issues. Sometimes having the latest version can resolve compatibility problems. If you encounter any further difficulties or have any other questions, please don't hesitate to reach out. We're here to help!

**Comment by bhasker412** [comment]
How to integrate yolov8 with wandb
https://wandb.ai/geekyrakshit/ultralytics/reports/Supercharging-Ultralytics-with-Weights-Biases--Vmlldzo0OTMyMDI4#🐝-using-weights-&-biases-with-ultralytics

ultralytics==8.0.186 
https://github.com/wandb/wandb/issues/6412#issuecomment-1746850406

**Comment by glenn-jocher** [comment]
@bhasker412 hello,

WandB integration is available out of the box in YOLOv8, so there's no need for an additional setup. To use it, you just need the wandb library installed in your working environment. When it's present, YOLOv8 will automatically detect it and log your training runs to your WandB account. 

This automatic logging includes metrics like loss and accuracy, along with other training and validation statistics. It's a powerful tool for tracking your model's performance over time, experimenting with hyperparameters, and comparing different models.

Ensure you're logged into WandB through your command line before starting your training for your runs to be tracked. Do note that different versions could influence the way YOLOv8 interacts with WandB, so make sure to keep your packages updated.

I hope this information helps! If you encounter any issue, please feel free to provide specific details so we can give you more targeted guidance. Happy training!

**Comment by dimka11** [comment]
@glenn-jocher but for yolov5 wandb already deprecated:
`wandb: WARNING ⚠️ wandb is deprecated and will be removed in a future release. See supported integrations at https://github.com/ultralytics/yolov5#integrations.`

**Comment by glenn-jocher** [comment]
@dimka11 thank you for bringing this to our attention. Currently, we have no plans to deprecate WandB for YOLOv8. The warning message you're seeing is specific to another project. For YOLOv8, WandB will continue to be fully supported to provide users with effective tools for tracking model metrics and statistics during training. We will frequently update you with any changes regarding this in our future updates. Please let us know if you have any other questions or concerns!

**Comment by Buckler89** [comment]
Hello @glenn-jocher 
As of now, I noticed that only the version ultralytics==8.0.186 is listed as supported on the [Weights & Biases documentation page](https://docs.wandb.ai/guides/integrations/ultralytics). Could you please provide any available updates or an estimated timeframe for when the newer version will be supported?

**Comment by glenn-jocher** [comment]
@Buckler89 hello,

The Weights & Biases documentation may not always reflect the most current state of integrations. We continuously work to ensure compatibility with WandB for the latest versions of YOLOv8. I recommend always using the latest version of YOLOv8 for the best experience with WandB. If you encounter any issues, please report them on our GitHub issues page, and we'll address them promptly. Thank you for your support and patience! 🚀
