### ISSUE TITLE
Why does yolov8s.yaml still download yolov8n.pt when I type it?

### ISSUE THREAD

**Issue by wjli-debug** [ultralytics/ultralytics#8491]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why does yolov8s.yaml still download yolov8n.pt when I type it? How can I choose different model weights, or train one directly on a custom data set without using the weights of the pre-trained model?
I run the command is as follows: yolo task = detect mode = "train" model. = / CFG/models/v8 / yolov8s yaml data =. / data. The yaml batch 16 epochs = 300 workers = = 2
![image](https://github.com/ultralytics/ultralytics/assets/116251731/596a3fc7-37a1-4254-83a1-bf80945ffbc2)
![image](https://github.com/ultralytics/ultralytics/assets/116251731/5d727d6d-1eb2-49cb-8773-8f7fefa20ded)

**Comment by wjli-debug** [comment]
yolo task=detect mode=train model=./cfg/models/v8/yolov8s.yaml data=./data.yaml batch=16 epochs=300 workers=2

**Comment by glenn-jocher** [comment]
This model is used for AMP checks.

**Comment by wjli-debug** [comment]
So he won't make a difference? When the parameter is model=./cfg/models/v8/yolov8s.yaml, does it actually use the model structure of yolov8s for training?

**Comment by glenn-jocher** [comment]
@wjli-debug absolutely! When you specify `model=./cfg/models/v8/yolov8s.yaml`, it indeed uses the YOLOv8s model structure for training. This YAML file defines the architecture of YOLOv8s, including layers and configurations, which are then used to build the model for training on your dataset. If you're starting without pre-trained weights, it initializes the model based on this structure and learns from your data during training. Happy training! 🚀

**Comment by wjli-debug** [comment]
Ok, thanks for the answer

**Comment by wjli-debug** [comment]
The last question, if I were in weight training, then the model=./cfg/models/v8/yolov8s.pt, how do I modify the corresponding nc parameters of the model yaml? Because when the output categories are inconsistent, don't you want to change the number of nc in the model yaml? So whether in ./cfg/models/v8/yolov8.yaml changes in it?
![image](https://github.com/ultralytics/ultralytics/assets/116251731/44fdd78b-3d7b-4c07-bff8-3c588026e90a)

**Comment by glenn-jocher** [comment]
@wjli-debug absolutely, if you're training with pre-trained weights and your dataset has a different number of classes (`nc`) than the pre-trained model, you'll indeed need to adjust the `nc` parameter in the model's YAML configuration to match your dataset's class count. For YOLOv8s, you would modify the `nc` value in the `./cfg/models/v8/yolov8s.yaml` file. Here's a quick example:

```yaml
# Example modification in yolov8s.yaml
nc: 80  # Change this to match the number of classes in your dataset
```

Just ensure the `nc` value in your YAML file matches the number of classes in your `data.yaml`. This step is crucial for aligning the model's output dimensions with your dataset. Happy training! 🚀

**Comment by wjli-debug** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/116251731/002f1764-d507-4382-b0d9-e10bf34e52c2)
But in the project file yolov8 I found no yolov8s.yaml file, I only discovered ./cfg/models/v8/yolov8.yaml, is the need to write your own? Or do you modify it directly in yolov8.yaml?

**Comment by glenn-jocher** [comment]
@wjli-debug hey there! 😊 If you're not finding the `yolov8s.yaml` in the `./cfg/models/v8/` directory, it's likely that the specific configuration file for YOLOv8s hasn't been included in the version of the repo you're working with. You can indeed modify the `yolov8.yaml` directly to match the YOLOv8s specifications or create your own `yolov8s.yaml` based on your requirements. 

For creating or modifying to a YOLOv8s configuration, you'd adjust parameters like `depth_multiple` and `width_multiple` to scale the model size, and most importantly, ensure `nc` (number of classes) matches your dataset. Here's a quick example snippet you might adjust in `yolov8.yaml`:

```yaml
# This is an example snippet - adjust values as needed!
nc: 80  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple
```

Remember, the key is to align the model architecture with your specific use case. Happy coding! 🚀
