### ISSUE TITLE
Dataset '/content/datasets/project_name/data.yaml' not found in google colab env.

### ISSUE THREAD

**Issue by salmonsush** [ultralytics/ultralytics#850]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug
Yolo trainer couldn't find my dataset's data.yaml file and images. The paths were set right.

※ I've searched issues and I found [this issue](https://github.com/ultralytics/ultralytics/issues/628) was experiencing the same problem. But at last, this issue was solved by making the 'datasets' directory under the project's folder and saving training data inside the 'datasets' folder. I already used that folder, so I issued my problem.

Command
`!yolo task=segment mode=train model=yolov8m-seg.pt data={dataset.location}/data.yaml epochs={epoch} imgsz=640 save=runs/segment/{train_sequence} plots=False`
**Error**

> Ultralytics YOLOv8.0.30 🚀 Python-3.8.10 torch-1.13.1+cu116 CUDA:0 (Tesla T4, 15110MiB)
> yolo/engine/trainer: task=segment, mode=train, model=yolov8m-seg.pt, data=/content/datasets/scaffolding-distance--6/data.yaml, epochs=10, patience=50, batch=16, imgsz=640, save=runs/segment/train7, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=False, val=True, save_json=False, save_hybrid=False, conf=0.001, iou=0.7, max_det=300, half=False, dnn=False, plots=False, source=ultralytics/assets/, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.001, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.9, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.1, copy_paste=0.1, cfg=None, v5loader=False, save_dir=runs/segment/train6
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/trainer.py", line 123, in __init__
>     self.data = check_det_dataset(self.args.data)
>   File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/data/utils.py", line 238, in check_det_dataset
>     raise FileNotFoundError(msg)
> FileNotFoundError: 
> Dataset '/content/datasets/scaffolding-distance--6/data.yaml' not found ⚠️, missing paths ['/content/datasets/scaffolding-distance--6/scaffolding-distance--6/valid/images']
> 

Runtime environment and file systems
`%pwd`

> /content

`!ls -a`

>  .  ..  .config	datasets  drive  runs  scaffolding-distance--6	yolov8m-seg.pt

```
%cd datasets
!ls -a
```

> /content/datasets
> .  ..  scaffolding-distance--6
> 

```
%cd scaffolding-distance--6
!ls -a
```

> /content/datasets/scaffolding-distance--6
> .  ..  data.yaml  README.dataset.txt  README.roboflow.txt  test  train	valid

### Environment

YOLO : Ultralytics YOLOv8.0.30 🚀 Python-3.8.10 torch-1.13.1+cu116 CUDA:0 (Tesla T4, 15110MiB)
OS : Ubuntu 20.04.5 LTS(Colab environment)
Python : 3.8.10 (Colab environment)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by salmonsush** [comment]
The reason was that the roboflow yaml file was updated(or may be changed), and the test, train, val paths was set wrong. I found something wrong in data.yaml and changed data.yaml to right way.

**Comment by pderrenger** [comment]
@salmonsush it's great to hear that you identified the root cause of the issue! It seems like updating the roboflow yaml file and correcting the paths in data.yaml resolved the problem. Well done! If you encounter any further challenges or have any other questions, feel free to ask. Good luck with your YOLOv8 project! 🚀
