### ISSUE TITLE
yolov8 segmentation: same class have consistent color 

### ISSUE THREAD

**Issue by Lmr213** [ultralytics/ultralytics#8503]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi, could anyone please guide me on ensuring that masks belonging to the same class have a consistent color during prediction, rather than different colors?

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Lmr213 hi there! 👋

Absolutely, to ensure masks of the same class have consistent colors during prediction, you can modify the color palette used for visualization. Each class index can be mapped to a specific color. Here's a quick example on how you might adjust the visualization code:

```python
from ultralytics import YOLO, Colors

# Load your model
model = YOLO('yolov8n-seg.pt')

# Define colors for each class index, e.g., for 3 classes
colors = [Colors.RED, Colors.GREEN, Colors.BLUE]

# Run prediction
results = model('path/to/your/image.jpg')

# Modify the plotting function to use your colors
results.plot(colors=colors)
```

In this example, `Colors.RED`, `Colors.GREEN`, and `Colors.BLUE` are placeholders. You'll need to define your own RGB tuples like `(255, 0, 0)` for red. Adjust the `colors` list to match the number of classes your model detects.

Hope this helps! If you're ready to dive into submitting a PR with an enhancement or utility function for consistent coloring, that sounds fantastic! 🚀

Let us know if you need further assistance.
