### ISSUE TITLE
WandB metrics

### ISSUE THREAD

**Issue by kais-bedioui** [ultralytics/ultralytics#8517]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

HI community!
I would like some guidance in understanding where are the metrics logged to WandB defined?
And How can I customize them?
Specifically, when training I would like to log (in the run table) the best and last mAP values, Precision, Recall, just like it does in Yolov5.

Thanks ;)

**Comment by glenn-jocher** [comment]
@kais-bedioui hello! 😊

Great question! Metrics logged to Weights & Biases (WandB) are defined within the training script, typically in the `train.py` file for YOLOv8. To customize them, you can modify this script to log additional metrics.

For logging specific metrics like best and last mAP values, Precision, and Recall, you can use the `wandb.log()` function. Here's a quick example on how you might log these metrics:

```python
import wandb

# Assuming 'results' is a dict holding your metrics
wandb.log({'Best mAP': results['best_map'], 
           'Last mAP': results['last_map'], 
           'Precision': results['precision'], 
           'Recall': results['recall']})
```

Make sure this logging happens inside your training loop where these metrics are updated. This way, they'll be logged to your WandB dashboard for each epoch.

Hope this helps! Let us know if you have any more questions.

**Comment by baxtrax** [comment]
@kais-bedioui 
Within Ultralytics the wandb logging happens in the [ultralytics/utils/callbacks/wb.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/callbacks/wb.py)

You can either override the callback methods or make your own (see below)

Example:
```python
def on_fit_epoch_end(trainer):
    """
    Log metrics for learning rate, and "metrics" (mAP etc. and val losses).
    Triggered at the end of each fit epoch.
    """
    wandb.log({**trainer.lr,
               **trainer.metrics})

model = YOLO("yolov8n.yaml")
model.add_callback("on_fit_epoch_end", on_fit_epoch_end)

```

To see a list of all available callbacks, please see the [Ultralytics Documentation on them](https://docs.ultralytics.com/usage/callbacks/?h=callbacks#validator-callbacks)

**Comment by baxtrax** [comment]
To disable all internal ultralytics logging, you can set the settings to disable the integration (so you can manually setup your own):

```python
from ultralytics.utils import (SETTINGS)
SETTINGS["wandb"] = False  # Disable Ultralytics internal wandb logging
```

**Comment by glenn-jocher** [comment]
@baxtrax hey there! 👋

Absolutely, you can disable the internal Ultralytics WandB logging by setting the `SETTINGS["wandb"]` to `False` as you've shown. This allows you to manually configure your own logging preferences. Here's how you can do it:

```python
from ultralytics import YOLO, SETTINGS

# Disable Ultralytics internal WandB logging
SETTINGS["wandb"] = False

# Now you can setup your own WandB logging or any other logging mechanism as needed
model = YOLO("yolov8n.yaml")
# Your custom logging setup here
```

Hope this helps! Let us know if you have any more questions. Happy coding! 😊

**Comment by kais-bedioui** [comment]
Hi @baxtrax, @glenn-jocher 
Thank you guys for your input. I apologize for getting back to you late, I got busy.
Actually my question was more about these metrics:

**Comment by glenn-jocher** [comment]
Hi @kais-bedioui! No worries about the timing, we're here to help whenever you're ready. 😊 

For customizing the WandB table metrics like you've shown in the image, you would typically adjust the logging directly in your training script or the relevant callback method handling WandB integration. 

To define or customize what metrics to log in the WandB table, you can use the `wandb.log()` function. Here's an example snippet that adds custom metrics to the WandB table:

```python
import wandb

# Let's say we're logging at the end of an evaluation epoch
wandb.log({'custom_metric_1': value_1,
           'custom_metric_2': value_2})
```

Just replace `'custom_metric_1'`, `'custom_metric_2'` with the names of the metrics you'd like to log, and `value_1`, `value_2` with the variables storing those metrics. 

The modification for where and what metrics are logged to WandB would be done in the callback or part of the script that is integrated with WandB, potentially within a custom callback if you're automating this process beyond the basic setup.

Hope this clarifies your question! Let us know if you need further assistance.

**Comment by Petros626** [comment]
@baxtrax thank you for the explanation and the short snippets. I don't want to deactivate `wandb` metrics, but use specific functions (`ap50` or `map50`) to be logged during my training session.

How can I achieve that?

**Comment by glenn-jocher** [comment]
To include specific metrics like `ap50` or `ap70` from `metrics.py` in your WandB logging, you can modify the `trainer.metrics` dictionary. The `trainer.metrics` is populated during training and contains standard metrics. To add or customize metrics, you can create a custom callback:

```python
from ultralytics import YOLO

def custom_metrics(trainer):
    trainer.metrics['ap50'] = trainer.validator.metrics['ap50']
    trainer.metrics['ap70'] = trainer.validator.metrics['ap70']
    wandb.log({'ap50': trainer.metrics['ap50'], 'ap70': trainer.metrics['ap70']}, step=trainer.epoch + 1)

model = YOLO("yolo11n.yaml")
model.add_callback("on_fit_epoch_end", custom_metrics)
model.train(data="coco.yaml", epochs=10)
```

This will log the desired metrics with WandB at the end of each epoch. For more details, refer to the [callbacks documentation](https://docs.ultralytics.com/usage/callbacks/).

**Comment by Petros626** [comment]
can't I just update the `keys` in class OBBMetrics with `metrics/AP50(B)` and `mean_results` with `self.ap50` in class Metric?

```python
@property
def keys(self):
    """Returns a list of keys for accessing specific metrics."""
    return ["metrics/precision(B)", "metrics/recall(B)", "metrics/mAP50(B)", "metrics/mAP50-95(B)", "metrics/AP50(B)"] # TODO: add here metrics

def mean_results(self):
    """Calculate mean of detected objects & return precision, recall, mAP50, and mAP50-95."""
    return self.box.mean_results()
    
def mean_results(self):
    """Mean of results, return mp, mr, map50, map."""
    return [self.mp, self.mr, self.map50, self.map, self.ap50]
```

The current problem is that `def fitness` can't handle that.
```txt
return (np.array(self.mean_results()) * w).sum()
wandb: ERROR ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.
```

**Comment by Petros626** [comment]
> @kais-bedioui Within Ultralytics the wandb logging happens in the [ultralytics/utils/callbacks/wb.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/callbacks/wb.py)
> 
> You can either override the callback methods or make your own (see below)
> 
> Example:
> 
> ```python
> def on_fit_epoch_end(trainer):
>     """
>     Log metrics for learning rate, and "metrics" (mAP etc. and val losses).
>     Triggered at the end of each fit epoch.
>     """
>     wandb.log({**trainer.lr,
>                **trainer.metrics})
> 
> model = YOLO("yolov8n.yaml")
> model.add_callback("on_fit_epoch_end", on_fit_epoch_end)
> ```
> 
> To see a list of all available callbacks, please see the [Ultralytics Documentation on them](https://docs.ultralytics.com/usage/callbacks/?h=callbacks#validator-callbacks)

`**trainer.metrics` include the default metrics, which are already displayed?

**Comment by wordman2** [comment]
I encountered the same issue as @Petros626 . It'd be cool to log other metrics than the default ones.
Has anyone found a solution?
