### ISSUE TITLE
https://docs.ultralytics.com unresponsive

### ISSUE THREAD

**Issue by jkh1** [ultralytics/ultralytics#8518]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

https://docs.ultralytics.com returns a blank page.
A bunch of 502 errors show up in the browser console.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jkh1 hi there! 👋 Thanks for bringing this to our attention. It seems like there might be a temporary issue with the documentation site. We're looking into it right away to get it back up and running smoothly. In the meantime, if there's something specific you need help with, feel free to ask here or check out the [GitHub repo](https://github.com/ultralytics/ultralytics) for more resources. We appreciate your patience! 🚀

**Comment by jkh1** [comment]
Thanks for looking into it. I'll just wait until the site is up again.

**Comment by glenn-jocher** [comment]
@jkh1 You're welcome! We're on it and hope to have everything running smoothly soon. If you have any urgent questions or need assistance in the meantime, don't hesitate to reach out here. Thanks for your patience! 😊
