### ISSUE TITLE
NotImplementedError: Could not run 'torchvision::nms' (Cuda IS enabled and functioning in the python env) on Windows

### ISSUE THREAD

**Issue by rlewkowicz** [ultralytics/ultralytics#8527]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I feel like getting a functioning environment is always a hurdle lol. I've been using yolo since the darknet days, and can generally debug and trouble shoot, but I cannot get this to work for the life of me. 

There's a lot of issues with this recently by the looks of it. Idk if it's just because ultralytics is more popular (go glenn!) or if torch is having issues under the hood.

I have tried many package install methods, including and currently:
```
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
```

I'm 99% sure I'm not making a goofy mistake. 

### Environment

```
(yolo) C:\Repos\ultralytics\heads>python --version
Python 3.10.13

(yolo) C:\Repos\ultralytics\heads>python
Python 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
```
```
(yolo) C:\Repos\ultralytics\heads>where yolo
C:\Users\ryan\miniconda3\envs\yolo\Scripts\yolo.exe
```
```
(yolo) C:\Repos\ultralytics\heads>yolo checks
Ultralytics YOLOv8.1.19 🚀 Python-3.10.13 torch-2.2.1 CUDA:0 (NVIDIA GeForce RTX 4090 Laptop GPU, 16376MiB)
Setup complete ✅ (16 CPUs, 63.7 GB RAM, 1541.6/1907.0 GB disk)

OS                  Windows-10-10.0.22621-SP0
Environment         Windows
Python              3.10.13
Install             pip
RAM                 63.70 GB
CPU                 13th Gen Intel Core(TM) i9-13950HX
CUDA                12.1

matplotlib          ✅ 3.8.3>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.2.1+cu121>=1.8.0
torchvision         ✅ 0.17.1>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.1>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
```

### Minimal Reproducible Example

Set up a fresh environment on windows with cuda then:
```
yolo detect train model=yolov8s.yaml imgsz=1024 data=dataset.yaml epochs=5000 batch=10 device=0
```

### Additional

I'm always working on a ton of different projects. I know I recently used yolo with a poetry env and it worked. I just wanted a fresh conda env for this project. Worst case is I need to go find all the files in that env and just copy them, but this should work.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by rlewkowicz** [comment]
```
conda install pytorch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 pytorch-cuda=12.1 -c pytorch -c nvidia
```
Fixes the issue.
I'll leave this open. I think the docs all say grab the latest. If this is issue is good enough record, that works form.

**Comment by rlewkowicz** [comment]
Actually I'll just close it anyhow.

**Comment by glenn-jocher** [comment]
@rlewkowicz thank you for sharing your solution! It's great to hear you were able to resolve the issue by specifying the package versions. Your contribution is valuable to the community, and it helps improve the experience for everyone using YOLOv8. If you encounter any more challenges or have further insights to share, please don't hesitate to reach out. Happy detecting! 🚀
