### ISSUE TITLE
runs\detect folder hardcoded when using streamlit

### ISSUE THREAD

**Issue by garyfoohw** [ultralytics/ultralytics#853]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

The save directory of runs\detect always defaults to **yolov8-streamlit-app** no matter what directory you use.

Tried a very basic streamlit app to run yolov8 detection.
In my sample, the stream lit app is run from **E:\uld_streamlit\main.py**
However, the output is saved to **E:\yolov8-streamlit-app\runs\detect** instead, not the original folder the main.py was in.

Is this somehow hardcoded? How to change this behaviour?

![image](https://user-images.githubusercontent.com/86142858/217258907-996c0c49-8fe9-4fd2-ad3b-fe2af770b96f.png)

### Environment

- Ultralytics YOLOv8.0.30  Python-3.10.2 torch-1.13.1+cpu CPU
- Windows 11
- Python 3.10.2

### Minimal Reproducible Example

```
from ultralytics import YOLO
import streamlit as st
from PIL import Image

if __name__ == '__main__':
    
    st.title('Sample')

    uploaded_file = st.sidebar.file_uploader("Load File")
    if uploaded_file is not None:
        is_valid = True
        with st.spinner(text='Loading...'):
            st.image(uploaded_file)
            picture = Image.open(uploaded_file)
            picture = picture.save(f'data/images/{uploaded_file.name}')
            source = f'data/images/{uploaded_file.name}'
    else:
        is_valid = False
   
    if is_valid:
        model=YOLO('yolov8n.pt')
        model.predict(task="detect",source=source,conf=0.25,save_crop=True,save=True)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@garyfoohw runs directories are initialized as relative for pip installs and absolute for git clone installs in your settings, which can be viewed and modified with `yolo settings`

**Comment by garyfoohw** [comment]
Thanks @glenn-jocher for the response.
Is there any docs on this behaviour, or how to change the `runs_dir` ?

Not sure if I'm doing in the right way, whenever I do `pip install ultralytics` in a `venv` virtual environment,
the `settings.yaml` file is written globally to `C:\Users\Gary\AppData\Roaming\Ultralytics\settings.yaml` instead of a local environment. Is there anyway to have a `settings.yaml` for each virtual environment instead of globally?

**Comment by buzzysin** [comment]
> Thanks @glenn-jocher for the response. Is there any docs on this behaviour, or how to change the `runs_dir` ?
> 
> Not sure if I'm doing in the right way, whenever I do `pip install ultralytics` in a `venv` virtual environment, the `settings.yaml` file is written globally to `C:\Users\Gary\AppData\Roaming\Ultralytics\settings.yaml` instead of a local environment. Is there anyway to have a `settings.yaml` for each virtual environment instead of globally?
> 
> For clarity, what Glenn recommended - to use a pip install instead of git clone indeed solves the problem. The `settings.yaml` now has a relative `runs_dir: runs` instead of an absolute path.

I'm having much the same issue with `conda` on Windows 11:

![image](https://user-images.githubusercontent.com/41271986/224181623-3ba88e1a-15bb-45a4-a0d6-c8db571237ee.png)

I had refreshed my environment after goofing up some setup, but my old config was pointing to my `notebooks` folder when I had since moved to using the CLI. "Why is the dataset dir persisting?" I asked myself. I stumbled across this unobvious solution by accident. A local, or per-environment config would be great as mentioned by @garyfoohw.

**Comment by glenn-jocher** [comment]
@buzzysin you can edit your settings.yaml directly. The defaults are local directories for pip installs and global for git clone installs. 

On my computer for example I see this using `yolo settings`, but you're free to change any of these directories to any relative or absolute directories you'd like:

<img width="621" alt="Screenshot 2023-03-10 at 00 22 04" src="https://user-images.githubusercontent.com/26833433/224183105-2383a3ea-18a6-4a12-9378-30b561edf8cf.png">

**Comment by glenn-jocher** [comment]
In Colab this looks like this. Ah I see the datasets dir is still absolute. 


@buzzysin @garyfoohw do you guys think we should have an easy way to update these, i.e. maybe `yolo settings KEY VALUE`?

<img width="626" alt="Screenshot 2023-03-10 at 00 25 10" src="https://user-images.githubusercontent.com/26833433/224183398-2fbbf72d-5b02-43c2-8c61-0f0da2849ab9.png">

**Comment by buzzysin** [comment]
@glenn-jocher I actually tried that! I was surprised when it didn't work. I assumed that you could do something like `yolo settings KEY VALUE` but there was nothing listed in `yolo help`. It would be good to change on the fly should it happen that we work/download datasets in another folder, or have another similar project somewhere else on the filesystem.

**Comment by Youssefkhaled55** [comment]
Ultralytics now use the flag "save=True" to save results. to save the output results by making runs folder
automatically and saving the image in it for example code be like this:
yolo task=detect mode=predict model=yolov8n.pt source=t.jpg conf=0.5 save=True

**Comment by Dineth9D** [comment]
# accepts all formats - image/dir/Path/URL/video/PIL/ndarray. 0 for webcam
results = model.predict(source="0")

**Comment by MaxLevinsky** [comment]
@buzzysin  if you want to change runs_dir or any other params in settings try smth like this
import from ultralytics.yolo.utils import set_settings

set_settings({'runs_dir': <your path>})
