### ISSUE TITLE
Meaning of mode=predict output from CLI

### ISSUE THREAD

**Issue by GR899** [ultralytics/ultralytics#8530]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Apologies if this is very basic / fundamental -- I couldn't find a basic overview in the docs, online or via others resources and am trying to put together a plain tutorial for others.

running CLI and issued the following from a terminal window against a video file:

`yolo task=detect mode=predict model=../workspace/runs/detect/train/weights/best.pt source=myvideo.mov`

Output includes the following:

`video 1/1 (1/469) myvideo.mov: 384x640 1 cat, 1 dog, 1 bike, 1 car, 1 ball, 41.5ms`

Can someone please confirm or correct what each means? 

- **video** = the source is a video file
- **1/1** = there is only 1 video to process and 1 was processed
- **(1/469)** = this is the analysis of the first frame (1) of the 496 frames in the video
- **385 x 640** = size of the image (frame) being processed 
- [note the video is actually 1920 x 1060 so assuming yolov8 is down sizing -- please confirm / explain - why is the size 384x680?)
- **1 cat, 1 dog, 1 bike, 1 car, 1 ball** = number of each object found in the frame
- **41.5ms** = ???

Also, can someone kindly point me to where in the docs I can explore further?  Specifically, deciphering CLI output. 

Many thanks for the time and courtesy of helping.

**Comment by glenn-jocher** [comment]
@GR899 hello! No worries, happy to clarify these points for you! 😊

- **video**: Correct, it indicates the source is a video file.
- **1/1**: Exactly right, it means there's only 1 video to process and this is the first one.
- **(1/469)**: Spot on, this shows the analysis of the first frame out of a total of 469 frames in the video.
- **384x640**: This is the size of the frame being processed. YOLOv8 automatically resizes images to a certain dimension for processing. The resizing helps in maintaining a balance between speed and accuracy. The original video resolution is higher (1920x1060), but YOLOv8 downsizes it for efficient processing.
- **1 cat, 1 dog, 1 bike, 1 car, 1 ball**: Correct, this indicates the number of each object detected in the frame.
- **41.5ms**: This refers to the inference time, or how long it took the model to process this particular frame.

For more detailed explanations on CLI output and other aspects, our documentation is continuously evolving. While we strive to cover everything, some specifics like CLI output details might not be explicitly documented yet. For now, discussions and issues on our [GitHub](https://github.com/ultralytics/ultralytics) are great places to ask such questions. Your query itself could help improve our docs!

Thanks for reaching out, and I hope this helps! If you have more questions or need further clarification, feel free to ask. Happy to help!
