### ISSUE TITLE
Detect on small object with YOLOv8 but not pretrained

### ISSUE THREAD

**Issue by NBTailee** [ultralytics/ultralytics#8534]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Detect on small object with YOLOv8 but i want it on size medium or above. can you guy give me some method or model to help boost YOLOv8 performance on detecting small object

**Comment by DroneAIRecognition** [comment]
Привет. В данном случае, вам необходимо будет сделать свой датасэт на котором вы обучите свою модель. Только так это будет работать.

**Comment by glenn-jocher** [comment]
@DroneAIRecognition привет! Да, для улучшения детекции маленьких объектов с YOLOv8, создание и обучение модели на собственном датасете, содержащем маленькие объекты, будет лучшим решением. Это поможет модели лучше адаптироваться к вашим уникальным требованиям. Удачи в обучении! 🚀
