### ISSUE TITLE
Are there plans to support new models for YOLO-World?

### ISSUE THREAD

**Issue by yeyupiaoling** [ultralytics/ultralytics#8536]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

YOLO-World released two new models. Is there any support plan? Is there any code for conversion? I want to try conversion.

![image](https://github.com/ultralytics/ultralytics/assets/26297768/343a511d-f2b4-43a0-843e-68ee1ba66cfb)

**Comment by yeyupiaoling** [comment]
@Laughing-q 请问有没有YOLO-World转换为ultralytics模型的Python脚本，我想转换这两个模型。谢谢

**Comment by Laughing-q** [comment]
@yeyupiaoling 不好意思，转这个模型需要手动调整一些地方，脚本不是完全自动化的。
我等会可以把这两个模型转了上传一下

**Comment by yeyupiaoling** [comment]
@Laughing-q 好的，谢谢，在线等 🙂

**Comment by Laughing-q** [comment]
@yeyupiaoling ok yolov8x-world.pt 已经上传le：https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8x-world.pt
但是由于命名问题这个新的yolov8l-world.pt命名为yolov8l-world-cc3m.pt: https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8l-world-cc3m.pt

**Comment by yeyupiaoling** [comment]
@Laughing-q 不知道是否能分享一下转换的流程。方便为之后对微调的模型转换。

**Comment by Laughing-q** [comment]
@yeyupiaoling 基本上就是通过`model.state_dict()`找到两个模型对应的键值对，然后替换一下：
```python
ori_dict = ori_model.state_dict()
model = WorldModel("yolov8.yaml")
model.load_state_dict(ori_dict)
```
但是load之前需要把键值对都对应上
