### ISSUE TITLE
Commercial License Usage

### ISSUE THREAD

**Issue by KaranBhuva22** [ultralytics/ultralytics#8544]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

@glenn-jocher, could you kindly inform me about the scenarios where I would require a commercial license?

Scenario 1: If I fine-tune the YOLOv8 model using YOLOv8 pretrained weights on custom dataset and utilize the resulting trained weights for commercial purposes.

Scenario 2: If I conduct YOLOv8 training from scratch, without utilizing any YOLOv8 pretrained weights, on a custom dataset and utilize the trained weights commercially.

**Comment by Burhan-Q** [comment]
> Scenario 1: If I fine-tune the YOLOv8 model using YOLOv8 pretrained weights on custom dataset and utilize the resulting trained weights for commercial purposes.

Yes, if opting to not publicly release all data, code, models, exports, etc. related to the project under AGPL-3.0.

> Scenario 2: If I conduct YOLOv8 training from scratch, without utilizing any YOLOv8 pretrained weights, on a custom dataset and utilize the trained weights commercially.

Yes, same as above.

If you want legal advise for your specific situation, you should seek legal counsel. As an Ultralytics employee, I can answer your question but if you need specifics regarding your particular options, then reviewing it with a lawyer is your best course of action.

The terms of AGPL-3.0 have more to do about what you do with the work than how you got there. When you use Ultralytics for a project, you need to make **all related and derivative works** publicly available under the same AGPL-3.0 permissions. You may instead directly obtain an [Enterprise License Agreement from Ultralytics](https://www.ultralytics.com/license) that would permit you to keep all related works and code private.

**Comment by KaranBhuva22** [comment]
thanks @Burhan-Q

**Comment by RizwanMunawar** [comment]
@KaranBhuva22 I hope @Burhan-Q cleared your doubts about the Ultralytics commercial License Usage. 

I am closing this issue. However, feel free to open a new issue if you encounter any problems or have concerns about Ultralytics' code or package. 😊

Thanks and regards,
The Ultralytics Team!
