### ISSUE TITLE
MPS prediction bug for segmentation + detection

### ISSUE THREAD

**Issue by mooch443** [ultralytics/ultralytics#8555]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I was experiencing issues when using ultralytics >=8.0.235 (introducing rotated bboxes) to predict basically anything. Specifically bounding box calculations are affected. I am sure this must be some kind of mps bug, but there is also an easy fix we can use here that shouldn't change much in terms of performance. It would be great if this could be added to the official repo.

In the below output I am confirming that the code (while it should be equivalent), produces different outcomes (see minimal example) depending on how dimensions are accessed. For this I only changed a few lines in ops.scale_boxes, indexing dimensions via index arrays (see in minimal example) and comparing to the current implementation results (accessing dims directly via integer).

```python
[ops.py:136] before: pad =  (0, 9)  boxes =  [[     160.12      173.75      177.28      201.86]]
[ops.py:137] after (current):  [[     160.12      173.75      177.28      201.86]]
[ops.py:138] after (new):  [[     160.12      164.75      177.28      192.86]]

[ops.py:136] before: pad =  (11, 0)  boxes =  [[     17.488     0.53688      109.48      153.62]]
[ops.py:137] after (current):  [[      6.488     0.53688      109.48      153.62]]
[ops.py:138] after (new):  [[      6.488     0.53688      98.476      153.62]]
...
```

Indeed we see there are differences between new / current after states and the current implementation produces wrong results. Running the same code purely on the CPU does not run into the same issues. This seems to purely be an MPS bug.

I have a similar issue predicting segmentations, which can be fixed in the same way:

```python
    downsampled_bboxes[:, [0]] *= width_ratio
    downsampled_bboxes[:, [2]] *= width_ratio
    downsampled_bboxes[:, [3]] *= height_ratio
    downsampled_bboxes[:, [1]] *= height_ratio
```
in [ops.py:693](https://github.com/ultralytics/ultralytics/blob/f8e681c2be251562633d424f4a1a1cc7da526bed/ultralytics/utils/ops.py#L693)

The idea for this solution is essentially an adapted copy of how this was done before v8.0.235 (see [here](https://github.com/ultralytics/ultralytics/commit/072291bc78da3a6ebff5c2a84eed49cb4547d50b#diff-4c045e45231b1287ae6222068d75c8a96d1e2bf450c5ecf9dc0959eaec04dfe6R111)).

### Environment

```
Ultralytics YOLOv8.1.19 🚀 Python-3.10.13 torch-2.1.2 CPU (Apple M1 Max)
Setup complete ✅ (10 CPUs, 64.0 GB RAM, 1619.1/1858.2 GB disk)

OS                  macOS-14.3.1-arm64-arm-64bit
Environment         Darwin
Python              3.10.13
Install             pip
RAM                 64.00 GB
CPU                 Apple M1 Max
CUDA                None

matplotlib          ✅ 3.8.3>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.1.2>=1.8.0
torchvision         ✅ 0.16.2>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.1>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
```

### Minimal Reproducible Example

in [ops.py:117](https://github.com/ultralytics/ultralytics/blob/f8e681c2be251562633d424f4a1a1cc7da526bed/ultralytics/utils/ops.py#L117):
```python
# in ops.scale_boxes, using mps device:
# ...
if padding:
  clone = boxes.clone()
  original = boxes.clone().cpu().numpy()

  # using index arrays for accessing dimensions (new):
  if not xywh:
      boxes[..., [0, 2]] -= pad[0]  # x padding
      boxes[..., [1, 3]] -= pad[1]  # y padding
  else:
      boxes[..., [0]] -= pad[0]  # x padding
      boxes[..., [1]] -= pad[1]  # y padding

  # using indexes (non-array) for accessing dimensions (current ultralytics):
  clone[..., 0] -= pad[0]  # x padding
  clone[..., 1] -= pad[1]  # y padding
  if not xywh:
      clone[..., 2] -= pad[0]  # x padding
      clone[..., 3] -= pad[1]  # y padding

  if (clone.cpu().numpy() != boxes.cpu().numpy()).any():
      print("before: pad = ", pad, " boxes = ", original)
      print("after (current): ", clone.cpu().numpy())
      print("after (new): ", boxes.cpu().numpy())

# rest of the code remains the same...
boxes[..., :4] /= gain
return clip_boxes(boxes, img0_shape)
```

Where the required change to the original code is only the way dims are accessed:
```python
  if not xywh:
      boxes[..., [0, 2]] -= pad[0]  # x padding
      boxes[..., [1, 3]] -= pad[1]  # y padding
  else:
      boxes[..., [0]] -= pad[0]  # x padding
      boxes[..., [1]] -= pad[1]  # y padding
```

Instead of:
```python
  boxes[..., 0] -= pad[0]  # x padding
  boxes[..., 1] -= pad[1]  # y padding
  if not xywh:
      boxes[..., 2] -= pad[0]  # x padding
      boxes[..., 3] -= pad[1]  # y padding
```

### Additional

I will update once I have tested -pose.
EDIT: I have tested <8.0.235 for segmentation models and it seems that this way of indexing produces the same incorrect results there. I have also tested with pytorch 2.1 and 2.2.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mooch443 hey there! 👋 Thanks for the detailed report and for diving into the issue. It's great to see community members actively engaging and proposing solutions. Your findings regarding the MPS bug and the workaround you've suggested are indeed intriguing. 

We appreciate the effort you've put into identifying this issue and coming up with a potential fix. The difference in outcomes based on dimension access methods is quite surprising, and your minimal reproducible example clearly demonstrates the problem.

Given the impact of this bug on bounding box calculations and potentially on segmentation predictions, integrating a fix like the one you've proposed could benefit many users, especially those working with MPS devices. We'll review the changes you've suggested and consider them for inclusion in the official repo. Your contribution could help improve the robustness of YOLOv8 on MPS devices.

If you're willing to submit a PR, that would be fantastic! 🚀 Please feel free to do so, and we'll make sure to review it promptly. Your initiative to help improve YOLOv8 is greatly appreciated by the team and the community. 

Looking forward to your PR, and let's make YOLOv8 even better together!

**Comment by mooch443** [comment]
I have submitted a pull request - not sure I linked it correctly to this issue, but feel free to have a look. It's only a few characters that changed.

**Comment by glenn-jocher** [comment]
@mooch443 thanks! I see the PR, I'm checking it out now.

**Comment by glenn-jocher** [comment]
@mooch443 I tried Pose and Segment models with MPS and everything is working correctly for me:

```
yolo predict model=yolov8l-pose.pt device=mps
WARNING ⚠️ 'source' is missing. Using default 'source=/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets'.
WARNING ⚠️ Apple MPS known Pose bug. Recommend 'device=cpu' for Pose models. See https://github.com/ultralytics/ultralytics/issues/4031.
Ultralytics YOLOv8.1.23 🚀 Python-3.11.2 torch-2.2.0 MPS (Apple M2)
YOLOv8l-pose summary (fused): 287 layers, 44465580 parameters, 0 gradients, 168.6 GFLOPs

image 1/2 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus.jpg: 640x480 4 persons, 318.6ms
image 2/2 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/zidane.jpg: 384x640 2 persons, 306.8ms
Speed: 8.1ms preprocess, 312.7ms inference, 115.9ms postprocess per image at shape (1, 3, 384, 640)
Results saved to /Users/glennjocher/PycharmProjects/ultralytics/runs/pose/predict3
💡 Learn more at https://docs.ultralytics.com/modes/predict
```

![bus](https://github.com/ultralytics/ultralytics/assets/26833433/fddfc689-2c1a-4322-9a36-a7b67a652388)

**Comment by glenn-jocher** [comment]
MPS Segment example:

```
yolo predict model=yolov8l-seg.pt device=mps
WARNING ⚠️ 'source' is missing. Using default 'source=/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets'.
Ultralytics YOLOv8.1.23 🚀 Python-3.11.2 torch-2.2.0 MPS (Apple M2)
YOLOv8l-seg summary (fused): 295 layers, 45973568 parameters, 0 gradients, 220.5 GFLOPs

image 1/2 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus.jpg: 640x480 4 persons, 1 bus, 325.0ms
image 2/2 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/zidane.jpg: 384x640 2 persons, 1 tie, 372.5ms
Speed: 8.0ms preprocess, 348.8ms inference, 143.0ms postprocess per image at shape (1, 3, 384, 640)
Results saved to /Users/glennjocher/PycharmProjects/ultralytics/runs/segment/predict2
💡 Learn more at https://docs.ultralytics.com/modes/predict
```

![bus](https://github.com/ultralytics/ultralytics/assets/26833433/76a780d7-90ec-4216-ac86-8083f347cace)

**Comment by glenn-jocher** [comment]
@mooch443 I've added a non-reproducible tag as MPS inference is working correctly for me. Please submit a minimum reproducible example that shows an error here for us to try to independently reproduce the issue.

My `yolo checks` shows this:

```
yolo checks
Ultralytics YOLOv8.1.23 🚀 Python-3.11.2 torch-2.2.0 CPU (Apple M2)
Setup complete ✅ (8 CPUs, 16.0 GB RAM, 318.3/460.4 GB disk)

OS                  macOS-14.2.1-arm64-arm-64bit
Environment         Darwin
Python              3.11.2
Install             git
RAM                 16.00 GB
CPU                 Apple M2
CUDA                None

matplotlib          ✅ 3.8.2>=3.3.0
numpy               ✅ 1.26.2>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 2.2.0>=1.8.0
torchvision         ✅ 0.17.0>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.7
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.1.4>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
```

**Comment by mooch443** [comment]
Okay, here's what I am using (keep in mind that this is research and I am only able to post censored data, but it still does have the same problem):

`yolo predict source=sample.jpg model=480-yolov8n.pt imgsz=480 device=mps`

This is the command. Now in an unpatched version of your package I get this:
![sample](https://github.com/ultralytics/ultralytics/assets/2864719/a276458a-8a75-4e1e-a691-0d9b43331c87)

And after the patch (or alternatively, using the CPU) I get this:
![sample](https://github.com/ultralytics/ultralytics/assets/2864719/cc5457c5-30db-44c7-a50f-ea8403e66185)

For some input images it seems to work properly, while others fail. This is also why I had the comparison in my original post, checking whether the result was wrong and only then outputting the difference. However, a large number of frames fails and it isn't hard to find them. I would say >60%.

Note that we have trained a yolov8n on 480px resolution with our custom dataset. I am cautious to publish the .pt file here, since technically this also doesn't belong to me entirely - happy to send it privately if you like. I will also ask my colleagues if it would be fine to post here.

---
BTW regarding speed: I get around ~12-13ms/frame prediction speed, no matter which version I use. So in the end, maybe the performance impact isn't that great in reality. Potentially because reading from a video is the slow part?

**Comment by glenn-jocher** [comment]
@mooch443 hey there! 🌟 Thanks for sharing the detailed observations and the code snippet. It's really helpful to see the specific examples and the differences you're encountering. Your approach to debugging and providing a potential fix is much appreciated!

Regarding the issue with the MPS device and the discrepancies in bounding box calculations, it's intriguing to see how the indexing method impacts the results. Your findings suggest that there might indeed be a subtle bug affecting MPS computations, especially considering the difference in outcomes between the CPU and MPS device.

Sending the `.pt` file privately for further investigation sounds like a good plan. We can definitely take a closer look to understand the root cause of the issue better. Feel free to send it over, and we'll keep the details confidential as per your requirements.

In the meantime, I'll experiment with the code snippet you've provided in `ops.py` to see if I can replicate the warning messages and further analyze the behavior. It's also interesting to note the consistent prediction speed you're observing, which suggests that the performance impact might be minimal in practical scenarios.

I'll keep you updated on any findings or insights from our side. Thanks again for your contribution and for helping us improve YOLOv8! 🚀

**Comment by mooch443** [comment]
I can publish the (censored) data here, containing the model and the sample.jpg:
[model_and_sample.zip](https://github.com/ultralytics/ultralytics/files/14575031/model_and_sample.zip)

The environment was created using these commands:
```bash
conda create -n clean_yolo -c pytorch python=3.11.8 pytorch=2.2.0 torchvision=0.17 numpy=1.26.2 pip
conda activate clean_yolo
python -m pip install ultralytics==8.1.24 numpy==1.26.2
```

These are the two files that I have used to create the results above, together with the command:

```bash
# this produces a faulty result:
yolo predict source=sample.jpg model=480-yolov8n.pt imgsz=480 device=mps

# this produces a good result:
yolo predict source=sample.jpg model=480-yolov8n.pt imgsz=480 device=cpu
```

Results:

![sample](https://github.com/ultralytics/ultralytics/assets/2864719/8facc1ee-b715-42c0-bbc7-ad9da1c14e9a)
![sample](https://github.com/ultralytics/ultralytics/assets/2864719/85bbed89-0fab-481b-aabf-28fc101a9402)

**Comment by mooch443** [comment]
@glenn-jocher I can publish the data here after all:
[model_and_sample.zip](https://github.com/ultralytics/ultralytics/files/14575151/model_and_sample.zip)
This contains both the .pt file and the image I used.

MInimal series of commands to reproduce the issue:
```bash
conda create -n clean_yolo -c pytorch python=3.11.8 pytorch=2.2.0 torchvision=0.17 numpy=1.26.2 pip
conda activate clean_yolo
python -m pip install ultralytics==8.1.24 numpy==1.26.2

# produces faulty image (because using mps):
yolo predict source=/Users/tristan/Desktop/sample.jpg model=/Users/tristan/Desktop/480-yolov8n.pt imgsz=480 device=mps

# produces good image (using cpu)
yolo predict source=/Users/tristan/Desktop/sample.jpg model=/Users/tristan/Desktop/480-yolov8n.pt imgsz=480 device=cpu
```

This produces these two images:
![sample](https://github.com/ultralytics/ultralytics/assets/2864719/0eb404ad-05cc-4706-9997-6f7b38766def)
![sample](https://github.com/ultralytics/ultralytics/assets/2864719/7f1fee37-e333-4b55-8f05-8b84c18bedb4)

---

Hopefully this will help. Thanks for any advice! I would really like to be running models on MPS acceleration, but it seems that even in mundane prediction tasks it produces mistakes sometimes (even though more rarely than with this model, but that might just be chance).

**Comment by mooch443** [comment]
Do my messages here need to be approved first? Seems like my previous two comments didn't get through (yet).

**Comment by glenn-jocher** [comment]
@mooch443 Thanks for sharing the model and sample data! 🌟 This will definitely help in diagnosing the issue more effectively. I appreciate you providing the detailed steps to reproduce the problem as well. It's clear and straightforward, which is great for pinpointing where things might be going awry with MPS acceleration.

I'll dive into the files you've shared and run some tests based on the commands you've outlined. It's intriguing that the MPS device produces different results compared to the CPU, and I'm keen to understand why that's happening. Rest assured, we're on it and will explore every avenue to resolve this.

In the meantime, if you discover any more patterns or additional insights that might help, please don't hesitate to share. Your collaboration is invaluable, and together, I'm confident we can get to the bottom of this. Thanks again for your patience and assistance! 🚀

**Comment by mooch443** [comment]
@glenn-jocher Problem still persists in .37 at the moment. It means I cannot use MPS on my Mac for YOLO predictions unfortunately. So let me know if there is something that I can provide to help solve this issue!

**Comment by glenn-jocher** [comment]
Hey there! Thanks for keeping us updated on the situation with MPS on your Mac. We're sorry to hear the issue persists in .37. Your offer to help is much appreciated! 🙏 Could you please share any error logs or specific behavior you're noticing when attempting MPS predictions? Also, a concise code snippet that reproduces the problem would be super helpful. This info will greatly assist us in troubleshooting more effectively. Thanks for your patience and collaboration!

**Comment by mooch443** [comment]
> @glenn-jocher I can publish the data here after all: [model_and_sample.zip](https://github.com/ultralytics/ultralytics/files/14575151/model_and_sample.zip) This contains both the .pt file and the image I used.
> 
> MInimal series of commands to reproduce the issue:
> 
> ```shell
> conda create -n clean_yolo -c pytorch python=3.11.8 pytorch=2.2.0 torchvision=0.17 numpy=1.26.2 pip
> conda activate clean_yolo
> python -m pip install ultralytics==8.1.24 numpy==1.26.2
> 
> # produces faulty image (because using mps):
> yolo predict source=~/Desktop/sample.jpg model=~/Desktop/480-yolov8n.pt imgsz=480 device=mps
> 
> # produces good image (using cpu)
> yolo predict source=~/Desktop/sample.jpg model=~/Desktop/480-yolov8n.pt imgsz=480 device=cpu
> ```
> 
> This produces these two images: ![sample](https://private-user-images.githubusercontent.com/2864719/312146373-0eb404ad-05cc-4706-9997-6f7b38766def.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzY1NTQsIm5iZiI6MTcxMjY3NjI1NCwicGF0aCI6Ii8yODY0NzE5LzMxMjE0NjM3My0wZWI0MDRhZC0wNWNjLTQ3MDYtOTk5Ny02ZjdiMzg3NjZkZWYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMTUyNDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2RhZDBjNGJhNmQ4NzQ0NmNlNjM0YzM5Zjg2OGQ0NmNmM2FhZjgwM2NhNGYzYjJmNGJhODQ5YTU2ZjhjYmZkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qOtcUQom0IevJBuiBTbk1D5PuPctlnZEUBBLc77p9aI) ![sample](https://private-user-images.githubusercontent.com/2864719/312146507-7f1fee37-e333-4b55-8f05-8b84c18bedb4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzY1NTQsIm5iZiI6MTcxMjY3NjI1NCwicGF0aCI6Ii8yODY0NzE5LzMxMjE0NjUwNy03ZjFmZWUzNy1lMzMzLTRiNTUtOGYwNS04Yjg0YzE4YmVkYjQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMTUyNDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODA1NzRjMWZlMGFkODA5MDVmNjc3N2ZlMDQ1NDZmNWVmYjAwOTI3M2MxNGM3NzBjN2M0MTVhOGIzZWYyNGUwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.V1f2nYcCXXcyg-xng3bTscPam_zTchUb9Eu2MaDKjzQ)
> 
> Hopefully this will help. Thanks for any advice! I would really like to be running models on MPS acceleration, but it seems that even in mundane prediction tasks it produces mistakes sometimes (even though more rarely than with this model, but that might just be chance).

Yes, that is what I provided here I think. Let me know if you need more information.

**Comment by glenn-jocher** [comment]
Hey @mooch443! 🙌 Thanks so much for providing the model and sample image, that's extremely helpful. 🚀 I've downloaded the `model_and_sample.zip` and will dive into testing with the steps you've outlined to investigate the discrepancies between MPS and CPU predictions further.

Your effort to detail the reproducible steps is much appreciated and makes our job a lot easier. Rest assured, we'll closely look into this and strive to understand the underlying cause of the differences observed. MPS acceleration should indeed offer a seamless experience, and we're on it to ensure it lives up to that promise.

I'll reach back out as soon as I have updates or if any additional info is needed. Thanks again for your patience and assistance! 💪

**Comment by mooch443** [comment]
This is very much still an issue and I have pushed commits in the pull requests. Kindly have a look and maybe we can resolve this :)

**Comment by glenn-jocher** [comment]
Hey there! Thanks for pushing those commits and bringing this to our attention. 🌟 I'll review the pull requests right away and get back to you with any suggestions or questions. Let's collaborate to get this resolved quickly. Appreciate your contribution! 😊

**Comment by stri8ed** [comment]
Any updates on this? Experiencing the same issue on `8.2.32` on `M3 Max`. CPU validation matches the results of Cuda validation, MPS gives much worse results.

**Comment by glenn-jocher** [comment]
Hi @stri8ed,

Thanks for reaching out and for your patience! 😊

We are aware of the MPS discrepancies and are actively investigating the issue. To help us further, could you please confirm the following:
1. Are you using the latest versions of `torch` and `ultralytics`? If not, please upgrade and try again.
2. Could you provide a minimum reproducible code example? This will greatly assist us in diagnosing the problem. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

Your collaboration is invaluable, and we're committed to resolving this as swiftly as possible. Thank you for your understanding and support! 🚀

**Comment by mooch443** [comment]
I have already provided one that you are free to use :)

**Comment by glenn-jocher** [comment]
Hi @mooch443,

Thank you for providing the minimum reproducible example! 😊

To ensure we're on the same page, could you please confirm that you're using the latest versions of `torch` and `ultralytics`? If not, please upgrade and try again to see if the issue persists.

Your detailed input is invaluable, and we're committed to resolving this swiftly. If you have any additional observations or logs, feel free to share them here.

Thanks for your patience and collaboration! 🚀
