### ISSUE TITLE
Activation function

### ISSUE THREAD

**Issue by Viseenn** [ultralytics/ultralytics#8558]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is the same activation function used for both the objectness score and the class probabilities in multi-object detection with YOLOv8?

**Comment by glenn-jocher** [comment]
@Viseenn yes, YOLOv8 uses the same activation function, specifically a sigmoid function, for both the objectness score and the class probabilities in multi-object detection. This ensures that both scores are normalized between 0 and 1, providing a consistent approach to interpreting the model's outputs. Here's a quick example of how it's applied in the code:

```python
objectness_score = torch.sigmoid(raw_objectness_score)
class_probabilities = torch.sigmoid(raw_class_scores)
```

Hope this clarifies your question! 😊
