### ISSUE TITLE
custom detection for pre-trained model 

### ISSUE THREAD

**Issue by anishka07** [ultralytics/ultralytics#8570]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

the object tracking and heatmap works fine but i wan the model to detect custom objects, like vehicles only even if there is a person on the frame how do i do that 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by anishka07** [comment]
i want to detect only specific classes using the pre trained yolov8 model

**Comment by glenn-jocher** [comment]
@anishka07 hello! 👋

To detect only specific classes, such as vehicles, using a pre-trained YOLOv8 model, you can filter the results based on class IDs after the detection. Each object class detected by YOLOv8 is assigned a unique class ID. For example, in the COCO dataset, 'car' is class ID 2, 'motorcycle' is 3, 'bus' is 5, and 'truck' is 7.

Here's a quick example on how you can do this in Python:

```python
from ultralytics import YOLO

# Load the pre-trained YOLOv8 model
model = YOLO('yolov8n.pt')

# Run detection
results = model('path/to/your/image.jpg')

# Filter detections to only vehicles (assuming class IDs 2, 3, 5, 7 are vehicles)
vehicle_ids = [2, 3, 5, 7]
vehicles_only = results.pred[0][results.pred[0][:, -1].isin(vehicle_ids)]

# Now `vehicles_only` contains only the detections for vehicles
```

Make sure to adjust the `vehicle_ids` list based on the specific classes you're interested in and according to the dataset your model was trained on.

Hope this helps! Let us know if you have any more questions. 😊
