### ISSUE TITLE
Export a model to tensorrt with dynamic=True and half=True

### ISSUE THREAD

**Issue by crmelicio** [ultralytics/ultralytics#8573]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey everyone,

I exported a model to tensorrt with `dynamic=True` and `half=True`  following this issue(https://github.com/ultralytics/ultralytics/pull/7870). However the datatype of the input and output bindings is `DataType.Float` and not `DataType.Half`. 

Following the issue(https://github.com/ultralytics/ultralytics/issues/5188) the input and output bindings are `DataType.Half`.

Is there any reason for this? Shouldn't it be Half?

**Comment by glenn-jocher** [comment]
@crmelicio hey there! 👋

Great question! When exporting a model to TensorRT with `dynamic=True` and `half=True`, the expectation is indeed for the input and output bindings to be `DataType.Half`. However, the actual data type can depend on several factors, including the specific TensorRT version and the capabilities of your GPU.

To ensure `DataType.Half` is used, please double-check that your GPU supports FP16 operations. Additionally, you might want to explicitly set the data type in your export code if possible. Here's a quick example on how you might do this during the export process:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('path/to/your/model.pt')

# Export the model specifying half precision and dynamic axes
model.export(format='engine', half=True, dynamic=True)
```

If you're still encountering issues, it might be helpful to share more details about your environment (e.g., TensorRT version, GPU model). This way, the community can provide more targeted advice. 🚀

Hope this helps!

**Comment by Burhan-Q** [comment]
The data type will still be a float. Enabling `half` converts from `floating point 32-bit precision` or `FP32` to `floating point 16-bit precision` or `FP16` which is _half_ of the full-size bit-precision
