### ISSUE TITLE
[Request] Share for mAP improvement for coco-val small size compared to yolov5-7.0

### ISSUE THREAD

**Issue by youngjae-avikus** [ultralytics/ultralytics#858]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I can see that the overall mAP has increased through the index compare to v5, but did you see a lot of improvements in small size?

**Comment by AyushExel** [comment]
You can see the comparison chart of all models on the readme

**Comment by youngjae-avikus** [comment]
@AyushExel 
I'm talking about the comparison of mAP numerical information for small area output from **cocoeval summarize.**
