### ISSUE TITLE
1.58 bit quantization

### ISSUE THREAD

**Issue by joelwebb** [ultralytics/ultralytics#8587]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

1.58 bit quantization is now out: https://arxiv.org/abs/2402.17764 --- Agora is implementing this BitNet: https://github.com/kyegomez/BitNet?tab=readme-ov-file 

Would it be possible to add the feature for exporting a 1.58 bit quantized model for YoloV8? 

### Use case

Based on the microsoft research paper, quantizing models to 1.58 bit format we can potentially see an 11X increase in possible batch sizes and 9X increase in inference speed, and a 7X decrease in required vRAM so these models can process more data, faster on smaller hardware! Oh, Also a very cool 41X reduction in energy consumption. 

This would theoretically allow for more ML practitioners to switch to using YOLOv8 models that have optimized performance on CPUs and they could potentially run significantly faster on GPU workloads as well. This would be similar to the export functionality for int8 but instead we could export using 1.5 bit format. 

This would go well with your existing INT8 quantization

Assuming an implementation could be similar to:
`
# Export the model
model.export(bit_quantize = True)
`

### Additional

There are examples here: https://github.com/kyegomez/BitNet/blob/main/bitnet/bitbnet_b158.py 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@joelwebb hey there! 🌟

Thanks for bringing up the intriguing concept of 1.58 bit quantization and its potential benefits for YOLOv8. The research you've mentioned indeed shows promising advancements in model efficiency and performance. 

Currently, YOLOv8 supports various export formats and quantizations, including INT8, which has been beneficial for optimizing model size and inference speed. Incorporating 1.58 bit quantization could further enhance these aspects, making YOLOv8 even more versatile and accessible for a wider range of hardware, especially in resource-constrained environments.

We're always looking to improve and stay at the forefront of AI and ML advancements. While we don't have immediate plans to implement 1.58 bit quantization, we're open to exploring new features that align with our community's needs and the evolving landscape of ML models. 

Your suggestion is valuable, and we encourage contributions from the community. If you or anyone else is interested in experimenting with or contributing to this feature, we'd be thrilled to see the outcomes and potentially integrate them into future versions of YOLOv8.

For now, I'll mark this as a feature request and keep it on our radar. Stay tuned for updates, and thanks again for your input! 🚀

**Comment by rolson24** [comment]
@joelwebb I was looking at this paper too, but I read some papers from a few years ago that tried 2 bit quantization with tiny-YOLO-v3 and they saw quite a big drop in accuracy. TBF tiny-YOLO-v3 really is tiny, so that might have been the reason, but I wonder if the same issue would apply because YOLO is a relatively small model compared to 3B param LLM where each weight is individually doing less work in theory. The other issue is that the implementation suggested in this paper requires the model to be _pre-trained_ at 1.58 bit, so you would need to re-write the whole YOLOv8 architecture to use the 1.58bit feed-forward layers. Could be a very cool and possibly extremely rewarding project, and I might try it if you would be interested on working on it with me.

**Comment by nathanjzhao** [comment]
@glenn-jocher 

Hi Glenn! I'm interested in possibly working on a 1.58 implementation of YOLO, and was wondering what space there was to work on the project. I can only find an open source version of YOLOv5, but I do think it would especially interesting to possibly explore on the more recent models.

I look forward to your response!

**Comment by rolson24** [comment]
@nathanjzhao 

This seems pretty interesting, I'm wondering how you plan to implement this. Are you thinking of taking the bitlinear implementation and adapting it to a convolution kernel? 
I would also take a look at the paper I mentioned before, which quantized YOLOv5 into 1-bit, to see what they did. They had to use 4-bit quantization in the neck of the model to achieve good accuracy.
