### ISSUE TITLE
SpeedEstimator: how to get speed data for each tracked object?

### ISSUE THREAD

**Issue by johnohagan** [ultralytics/ultralytics#8593]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm happily using pretrained yolov8 models for detection and tracking of live video, and would like to try out the speed estimation features. My goal is to get speed estimation data for each tracked object, as opposed to annotating frames.

My detector/tracker class has the following lines in \_\_init\_\_:
         
```
from ultralytics.solutions import speed_estimation
self.speed_estimator = speed_estimation.SpeedEstimator()
```

. . . and has a method that reads the video frames in a loop like this (simplified):

```
while 1:
    image = self.get_next_frame()
    results = self.model.track(image, persist=True)[0]
    boxes, masks = results.boxes, results.masks
    for box, mask in zip(boxes.data, masks.data):
        #do stuff with data
```
I'm hoping I can call a SpeedEstimator method on self.speed_estimator somewhere in the while loop above to get the speed data for each object. 

A possible candidate seem to be `calculate_speed`, which the docs say is a "[c]alculation of object speed" and takes a list of "tracking history for tracks path drawing". But I haven't been able to work out from this exactly what the method does or what the argument is. 

Of course, I could be looking in the wrong place altogether.

I'd appreciate some guidance here, preferably some example code of how to create or obtain the necessary argument and derive the speed data for each tracked object, if that's currently possible.

Thanks!

**Comment by glenn-jocher** [comment]
@johnohagan hey there! 🚀 It's great to hear you're exploring the speed estimation features with YOLOv8. You're on the right track with using the `SpeedEstimator` class. To integrate speed estimation into your loop, you'll indeed use the `calculate_speed` method. This method requires the tracking history, which you can obtain from the tracking results.

Here's a simplified example to guide you:

```python
# Assuming you have initialized your SpeedEstimator as self.speed_estimator

while 1:
    image = self.get_next_frame()
    results = self.model.track(image, persist=True)[0]
    boxes = results.boxes

    # Assuming you have a way to store and update track histories
    # track_histories should be a dict with track_id as keys and lists of (x, y) positions as values
    track_histories = {}

    for box in boxes.data:
        track_id = box.id.item()  # Get track ID
        center = box.xyxy[0:2].mean(axis=0)  # Calculate center point of the box
        if track_id not in track_histories:
            track_histories[track_id] = []
        track_histories[track_id].append(center.cpu().numpy())  # Update track history with new center point

    # Now, calculate speed for each track
    for track_id, history in track_histories.items():
        speed = self.speed_estimator.calculate_speed(history)
        print(f"Track ID: {track_id}, Speed: {speed}")

    # Do other stuff...
```

This example assumes you're maintaining a history (`track_histories`) of center points for each tracked object. The `calculate_speed` method then uses this history to estimate the speed. Make sure to adapt the tracking history storage and update mechanism according to your specific requirements.

Hope this helps! Let us know if you have any more questions.

**Comment by johnohagan** [comment]
Thanks [@glenn-jocher](https://github.com/glenn-jocher) for your reply. Sorry for my slow reply but I'm afraid this has opened a small can of worms!

In summary, I think there may be some errors in the code of the `calculate_speed` method of the `SpeedEstimator` class (or I am doing it wrong).

To test the method, I started with the sample code you kindly provided above, but I gather it was untested as it didn't run. This doesn't matter but more importantly, in the process of debugging this I looked at the `SpeedEstimator` code, and noticed a couple of things:

- The module already contains a `store_track_info` method that creates and manages track histories, so manually saving center points to a dictionary is unnecessary.
- The `calculate_speed` method doesn't return anything, but writes the calculated speed to an instance attribute, a dictionary called `dist_data`. 

So here is the code I ended up up using to test  the `calculate_speed` method:

```
import cv2
from ultralytics import YOLO
from ultralytics.solutions import speed_estimation

speed_estimator = speed_estimation.SpeedEstimator()
model = YOLO()
capture = cv2.VideoCapture(0)

#Print id and speed of each tracked object over ten video frames
for _ in range(10):
    image=capture.read()[1]
    results = model.track(image, persist=True, verbose=False)[0]
    for box in results.boxes:
        track_id = box.id.item()
        speed_estimator.store_track_info(track_id, box.xyxy[0])
        hist = speed_estimator.trk_history[track_id]
        speed_estimator.calculate_speed(track_id, hist)
        print(f"Track ID: {track_id} "
        f"Speed: {speed_estimator.dist_data.get(track_id)}")
```
This still resulted in a number of errors (also seen with manual track history), which I think may stem from the `calculate_speed` code:

```
    def calculate_speed(self, trk_id, track):
        """
        Calculation of object speed.

        Args:
            trk_id (int): object track id.
            track (list): tracking history for tracks path drawing
        """

        if not self.reg_pts[0][0] < track[-1][0] < self.reg_pts[1][0]:
            return
        if self.reg_pts[1][1] - self.spdl_dist_thresh < track[-1][1] < self.reg_pts[1][1] + self.spdl_dist_thresh:
            direction = "known"

        elif self.reg_pts[0][1] - self.spdl_dist_thresh < track[-1][1] < self.reg_pts[0][1] + self.spdl_dist_thresh:
            direction = "known"
        else:
            direction = "unknown"

        if self.trk_previous_times[trk_id] != 0 and direction != "unknown" and trk_id not in self.trk_idslist:
            self.trk_idslist.append(trk_id)

            time_difference = time() - self.trk_previous_times[trk_id]
            if time_difference > 0:
                dist_difference = np.abs(track[-1][1] - self.trk_previous_points[trk_id][1])
                speed = dist_difference / time_difference
                self.dist_data[trk_id] = speed

        self.trk_previous_times[trk_id] = time()
        self.trk_previous_points[trk_id] = track[-1]
```
I think there are at least three problems with this line:
`        if self.trk_previous_times[trk_id] != 0 and direction != "unknown" and trk_id not in self.trk_idslist:`

1. It tests for `self.trk_previous_times[trk_id] != 0`  before that key has been added so it raises a KeyError.
2. The direction variable is always set to 'unknown' (at least with default `reg_pts` values), so the test for  `direction != "unknown"` is always False and the speed calculation never happens.
3. The test for `trk_id not in self.trk_idslist` is only True the first time because the next line adds `trk_id` to the list, so the speed is only calculated once for each id.

If the method is cut down to the below, my test code works and produces plausible results. I'm not suggesting this as a patch because I have no idea whether the results are correct or how this affects other code.

```
    def calculate_speed(self, trk_id, track):
        """
        Calculation of object speed.

        Args:
            trk_id (int): object track id.
            track (list): tracking history for tracks path drawing
        """

        if self.trk_previous_times.get(trk_id):
            time_difference = time() - self.trk_previous_times[trk_id]
            if time_difference > 0:
                dist_difference = np.abs(track[-1][1] - self.trk_previous_points[trk_id][1])
                speed = dist_difference / time_difference
                self.dist_data[trk_id] = speed

        self.trk_previous_times[trk_id] = time()
        self.trk_previous_points[trk_id] = track[-1]

```

**Comment by glenn-jocher** [comment]
Hey @johnohagan, thanks for diving deep into the `SpeedEstimator` class and sharing your findings! 🌟 Your observations are invaluable, and it looks like you've done some excellent detective work here.

You're right about the `store_track_info` method handling track histories, making manual tracking unnecessary. Also, your discovery about how `calculate_speed` updates the `dist_data` attribute instead of returning a value directly is spot on. This design choice aims to keep track of speed data internally for potential future enhancements or integrations.

Regarding the issues you encountered:
1. The `KeyError` you mentioned is indeed something that needs addressing. Initializing `trk_previous_times` with default values for new track IDs could be a solution.
2. The `direction` variable's logic seems to be too restrictive or not aligned with the default `reg_pts` values, as you've noticed. Adjusting this logic or the default `reg_pts` could help.
3. Your point about `trk_id not in self.trk_idslist` preventing multiple speed calculations is insightful. This part of the logic might need reevaluation to allow for continuous speed updates.

Your simplified `calculate_speed` method is a great starting point for addressing these issues. It removes some of the problematic checks and focuses on the core functionality of calculating speed based on time and distance differences.

I'll take your feedback to the team for further discussion and potential improvements to the `SpeedEstimator` class. Your hands-on testing and suggestions are incredibly helpful for enhancing the functionality and usability of our solutions.

If you have any more insights or questions as you continue exploring, please don't hesitate to share. Thanks again for your contribution to making Ultralytics YOLOv8 even better! 🚀

**Comment by Chiroyce1** [comment]
@glenn-jocher Sorry for pinging you in this issue, but I'm really quite stuck with making changes to the base code given from the docs. You had provided an example above
```py
    for track_id, history in track_histories.items():
        speed = self.speed_estimator.calculate_speed(history)
        print(f"Track ID: {track_id}, Speed: {speed}")
```
But calculate_speed takes 2 arguments apart from self, track id and track.
```py
    def calculate_speed(self, trk_id, track):
        """
        Calculation of object speed
        Args:
            trk_id (int): object track id.
            track (list): tracking history for tracks path drawing
        """
```
**What I'm trying to do**: Every frame being read from a video, get an array of dictionaries, that contain the tracked items with their calculated speeds, and the bounding box for it, so that I can export the bounding box as a picture if the speed meets a certain criteria.

The docs provide a great example to visualize the tracking and speed estimation but I feel its really lacking some info on how we can use the estimated speed data along with the tracking bounds.

**Comment by johnohagan** [comment]
@Chiroyce1 Your requirement seems similar to mine. 

Based on looking at the code it seems to me that the SpeedEstimator class in its current form it doesn't keep track of calculated speeds for every detected object. It is currently focused on visualising tracked trajectories of detected objects and showing their speed only when a specified region of the frame is crossed, e.g. vehicles crossing a horizontal line on the frame. This makes sense because otherwise it's going to be hard to consistently translate changes in frame position to velocity estimates.

If you're willing to ignore that issue, here's a way to do something like what you want, using a function to make the SpeedEstimator object keep track of all objects' speeds. The function is a simplified version of the calculate_speed method that doesn't require a region, and the for loop creates a dictionary for each frame with object-id keys and (speed, bounding-box) tuples as values.

```
from time import time
from cv2 import VideoCapture
from ultralytics import YOLO
from ultralytics.solutions.speed_estimation import SpeedEstimator

def my_calculate_speed(speedest, trk_id, track):
    """
    Modified calculate_speed to store speed of all tracked objects
    """
    if speedest.trk_previous_times.get(trk_id):
        time_difference = time() - speedest.trk_previous_times[trk_id]
        if time_difference > 0:
            dist_difference = abs(track[-1][1] -
                        speedest.trk_previous_points[trk_id][1])
            speed = dist_difference / time_difference
            speedest.dist_data[trk_id] = speed
    speedest.trk_previous_times[trk_id] = time()
    speedest.trk_previous_points[trk_id] = track[-1]

speed_estimator = SpeedEstimator()
model = YOLO()
capture = VideoCapture(0)

#Print dict of id keys and tuple of (speed, bounding box) values
#over ten frames
for _ in range(10):
    image=capture.read()[1]
    results = model.track(image, persist=True, verbose=False)[0]
    id_speedboxes = {}
    for box in results.boxes:
        track_id = box.id.item()
        box = box.xyxy[0]
        speed_estimator.store_track_info(track_id, box)
        track = speed_estimator.trk_history[track_id]
        my_calculate_speed(speed_estimator, track_id, track)
        id_speedboxes[track_id] = (speed_estimator.dist_data.get(track_id), box)

    print(id_speedboxes)
```

**Comment by Chiroyce1** [comment]
@glenn-jocher Sorry for the ping again but the reason I don't want to hack up a solution is because it requires modifying code in the SpeedEstimator class itself, it would be extremely helpful if it allowed us to access the speeds and boxes from it, rather than just for visualisation purposes.

**Comment by glenn-jocher** [comment]
Hey @Chiroyce1, no worries about the ping! I completely understand your need for a more accessible way to retrieve speeds and bounding boxes directly from the `SpeedEstimator`. Enhancing the class to support this functionality without requiring internal modifications sounds like a valuable improvement for many users.

For now, you might consider extending the `SpeedEstimator` class in your own codebase to add this functionality. Here's a quick example of how you might do it:

```python
class MySpeedEstimator(SpeedEstimator):
    def get_speeds_and_boxes(self):
        return self.dist_data, self.trk_history

# Usage
my_estimator = MySpeedEstimator()
# After processing frames
speeds, boxes = my_estimator.get_speeds_and_boxes()
```

This way, you can keep track of the modifications locally without altering the base class. Meanwhile, I'll bring this up as a feature request to see if we can incorporate it into future releases. Thanks for your suggestion! 🚀

**Comment by Chiroyce1** [comment]
Hi @glenn-jocher, I see that #12790 has refactored all the solutions - has this been included in that? Thanks for the solution you had given but the speeds object is always blank, tracks work as usual. Thanks a lot for refactoring all the solutions as it truly improves the developer experience for everyone using ultralytics' quick and easy solutions for various computer vision problems, but the thing is I've tried a lot of solutions for this and most of them don't work :(

```py
# suggested in the github comments in the docs page (https://docs.ultralytics.com/guides/speed-estimation/#arguments-modeltrack)

while cap.isOpened():
    success, img = cap.read()
    if not success:
        break

    # Track objects in the frame
    tracks = model.track(img, persist=True, show=False)
    
    # Estimate the speed of detected objects
    img = speed_obj.estimate_speed(img, tracks)
    
    # Check if any car exceeds the speed limit
    for track in tracks: # ERROR HERE
        if track.label == 'car' and track.speed > speed_limit:
            # Process the snippet e.g., save or alert
            print(f"Car exceeding speed: {track.speed}")
            
 ```
 ```
 AttributeError: 'Results' object has no attribute 'label'. See valid attributes below.
 ```
 
And another
```py


# Example extension to capture speeds
    while cap.isOpened():
        success, img = cap.read()
        if not success:
            break

        # Track objects in the frame
        tracks = model.track(img, persist=True, show=False)

        # Estimate the speed of detected objects
        img = speed_estimator.estimate_speed(img, tracks)
        speeds = []

        # Assuming `track` objects contain speed, extract and store it
        for track in tracks:
            if hasattr(track, 'speed'):
                speeds.append(track.speed)  # Store or process the speed

        print(speeds[-1])
```


But this seems to return
```
Speed: 3.6ms preprocess, 11.4ms inference, 0.6ms postprocess per image at shape (1, 3, 640, 640)
{'preprocess': 3.629922866821289, 'inference': 11.443853378295898, 'postprocess': 0.6492137908935547}
```
 
When the actual speeds shown on the frame were around ~130-150km/h

I'm just a bit confused as the types that are returned are a bit weird and after a bit of digging around I still can't figure out where those calculate speeds in km/h are stored - and how I can actually map them to the bounding boxes of each tracked objects. Ideal solution would be something like this

```py
speeds, boxes = speed_estimator.return_estimated()
# speeds is an list of floats with the calculated km/h value (same as the one displayed in the frame)
# boxes is an list of bounding box coordinates for each track, in the same order as speeds
```
I know I am asking for a very rudimentary and simplified solution but I feel its a valid question as the built in solutions should be able to return the estimated data in a pretty simple form, maybe as simple as a list.
Thank you for the help!

**Comment by glenn-jocher** [comment]
Hi @Chiroyce1,

Thank you for your detailed feedback and for highlighting the issues you're facing with speed estimation. I appreciate your patience and understanding as we work to improve our solutions.

### Addressing Your Concerns

1. **Refactored Solutions**: The recent refactor in #12790 aims to enhance the developer experience, but it seems the specific functionality you need might not be fully addressed. Let's ensure you're using the latest versions of `torch` and `ultralytics`. If not, please upgrade and try again:
    ```bash
    pip install --upgrade torch ultralytics
    ```

2. **Speed Data Retrieval**: The `SpeedEstimator` class currently focuses on visualizing speeds rather than providing them in a structured format. However, I understand the need for a more accessible way to retrieve speeds and bounding boxes. Here's a modified approach to achieve this:

### Example Code

Below is an example of how you can extend the `SpeedEstimator` to retrieve speeds and bounding boxes for each tracked object:

```python
import cv2
from ultralytics import YOLO
from ultralytics.solutions import speed_estimation
from time import time

class MySpeedEstimator(speed_estimation.SpeedEstimator):
    def get_speeds_and_boxes(self):
        speeds = []
        boxes = []
        for trk_id, track in self.trk_history.items():
            if len(track) > 1:
                self.calculate_speed(trk_id, track)
                speeds.append(self.dist_data.get(trk_id, 0))
                boxes.append(track[-1])
        return speeds, boxes

def my_calculate_speed(speedest, trk_id, track):
    if speedest.trk_previous_times.get(trk_id):
        time_difference = time() - speedest.trk_previous_times[trk_id]
        if time_difference > 0:
            dist_difference = abs(track[-1][1] - speedest.trk_previous_points[trk_id][1])
            speed = dist_difference / time_difference
            speedest.dist_data[trk_id] = speed
    speedest.trk_previous_times[trk_id] = time()
    speedest.trk_previous_points[trk_id] = track[-1]

# Initialize model and speed estimator
model = YOLO("yolov8n.pt")
speed_estimator = MySpeedEstimator()

# Open video capture
cap = cv2.VideoCapture("path/to/video/file.mp4")
assert cap.isOpened(), "Error reading video file"

while cap.isOpened():
    success, img = cap.read()
    if not success:
        break

    # Track objects in the frame
    results = model.track(img, persist=True, show=False)[0]

    # Store track info and calculate speeds
    for box in results.boxes:
        track_id = box.id.item()
        speed_estimator.store_track_info(track_id, box.xyxy[0])
        track = speed_estimator.trk_history[track_id]
        my_calculate_speed(speed_estimator, track_id, track)

    # Retrieve speeds and bounding boxes
    speeds, boxes = speed_estimator.get_speeds_and_boxes()
    for speed, box in zip(speeds, boxes):
        print(f"Speed: {speed}, Box: {box}")

cap.release()
cv2.destroyAllWindows()
```

### Explanation

1. **Custom SpeedEstimator**: The `MySpeedEstimator` class extends `SpeedEstimator` to include a method `get_speeds_and_boxes` that retrieves the speeds and bounding boxes.
2. **Speed Calculation**: The `my_calculate_speed` function is used to calculate speeds without relying on the region points.
3. **Main Loop**: The main loop captures video frames, tracks objects, stores track info, calculates speeds, and retrieves the speeds and bounding boxes.

This approach should help you get the speed data for each tracked object along with their bounding boxes. If you encounter any further issues or have additional questions, feel free to ask. We're here to help! 😊

**Comment by Chiroyce1** [comment]
@glenn-jocher thank you! This fixed most of my issues, but one last question is about the bounding boxes, an example from the code is this
```
(745.1380615234375, 800.7694091796875)
```

I assume this is the X and Y coordinate - without the height and width, how do I obtain that? Also with the extra `my_calculate_speed` function in place, can I still obtain the annotated frame from the `speed_estimator` instance?
