### ISSUE TITLE
Python using a classification model for inference has high CPU usage, reaching up to 50%. Is it possible to choose GPU for inference? Can you provide an example code? On the other hand, using object detection for inference only has 15% CPU usage

### ISSUE THREAD

**Issue by xiaobaixuejava** [ultralytics/ultralytics#8598]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Python using a classification model for inference has high CPU usage, reaching up to 50%. Is it possible to choose GPU for inference? Can you provide an example code? On the other hand, using object detection for inference only has 15% CPU usage

**Comment by glenn-jocher** [comment]
@xiaobaixuejava absolutely, you can specify the GPU for inference to reduce CPU usage. Here's a quick example on how to do this with a classification model using YOLOv8:

```python
from ultralytics import YOLO

# Load your model and specify the device as 'cuda' for GPU
model = YOLO('path/to/your/classification_model.pt', device='cuda')

# Perform inference on an image
results = model('path/to/your/image.jpg')

# Process your results here
```

This should help in leveraging your GPU for inference tasks, potentially reducing the high CPU usage you're experiencing. If you're still facing issues, ensure your CUDA environment is correctly set up and that PyTorch is utilizing the GPU. 🚀
