### ISSUE TITLE
YOLOv8 COCO Metrics

### ISSUE THREAD

**Issue by justin-fun** [ultralytics/ultralytics#860]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to convert YOLOv8 to COCO style evaluation metric.

### Additional

No

**Comment by Laughing-q** [comment]
@justin-fun please add `save_json=True`.

**Comment by justin-fun** [comment]
Whether to add only test.py

**Comment by pderrenger** [comment]
@justin-fun yes, to enable COCO-style evaluation metrics in YOLOv8, you just need to add `save_json=True` to the `test.py` script.
