### ISSUE TITLE
IOU and Conf value during training evaluation

### ISSUE THREAD

**Issue by erminkev1** [ultralytics/ultralytics#8606]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

What are the values of IOU and confidence for evaluation during training? I can see that by default in the validation script it is 0.6 and 0.001 respectively. But is this the default for during training?

**Comment by glenn-jocher** [comment]
@erminkev1 hello! 😊

Yes, during training evaluation, the default Intersection Over Union (IOU) threshold is set to `0.6`, and the confidence threshold is set to `0.001`. These values are used to evaluate the model on the validation dataset at the end of each training epoch. 

If you wish to adjust these values for your training evaluations, you can modify them directly in your training script or use the command line arguments `--iou-thres` and `--conf-thres` when running your training command. For example:

```bash
yolo train data=coco128.yaml model=yolov8n.yaml --iou-thres 0.65 --conf-thres 0.01
```

This would set the IOU threshold to `0.65` and the confidence threshold to `0.01` for the duration of the training.

Hope this helps! Let us know if you have any more questions.
