### ISSUE TITLE
trouble using YOLO prediction model in QGIS

### ISSUE THREAD

**Issue by MohammadMr** [ultralytics/ultralytics#8609]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi. i try to use yolov8 on qgis to segment the selected area and i get some unknown error. when the code line "YOLO.prediction" a new QGIS window get open and show me the errors that are in screenshots. after i close the new window the plugin give me the following error as well.

Traceback (most recent call last):
File "C:\Users/MrMe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\acvs\ACVS_algorithm.py", line 453, in processAlgorithm
if not self.YoloModelPrediction(YOLO_model,feedback):
File "C:\Users/MrMe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\acvs\ACVS_algorithm.py", line 567, in YoloModelPrediction
predict = YOLO_model(self.batch_input)
File "C:\Users\MrMe\AppData\Roaming\Python\Python39\site-packages\ultralytics\engine\model.py", line 169, in __call__
return self.predict(source, stream, **kwargs)
File "C:\Users\MrMe\AppData\Roaming\Python\Python39\site-packages\ultralytics\engine\model.py", line 422, in predict
self.predictor.setup_model(model=self.model, verbose=is_cli)
File "C:\Users\MrMe\AppData\Roaming\Python\Python39\site-packages\ultralytics\engine\predictor.py", line 343, in setup_model
device=select_device(self.args.device, verbose=verbose),
File "C:\Users\MrMe\AppData\Roaming\Python\Python39\site-packages\ultralytics\utils\torch_utils.py", line 154, in select_device
s += f"CPU ({get_cpu_info()})\n"
File "C:\Users\MrMe\AppData\Roaming\Python\Python39\site-packages\ultralytics\utils\torch_utils.py", line 63, in get_cpu_info
info = cpuinfo.get_cpu_info() # info dict
File "C:\Users\MrMe\AppData\Roaming\Python\Python39\site-packages\cpuinfo\cpuinfo.py", line 2762, in get_cpu_info
output = json.loads(output, object_hook = _utf_to_str)
File "C:\PROGRA~1\QGIS33~2.0\apps\Python39\lib\json\__init__.py", line 359, in loads
return cls(**kw).decode(s)
File "C:\PROGRA~1\QGIS33~2.0\apps\Python39\lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\PROGRA~1\QGIS33~2.0\apps\Python39\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

i checked out all the approaches to fix this error and even  checked it on other computers.

QGIS    = 3.36.0
Python = 3.9.18

![4](https://github.com/ultralytics/ultralytics/assets/22716646/7c7d8833-b0c4-4839-90de-3b7f6b007147)

![3](https://github.com/ultralytics/ultralytics/assets/22716646/07b80e80-b907-46a5-8c8f-f4569340f73f)

**Comment by glenn-jocher** [comment]
@MohammadMr hello! It looks like you're encountering a JSON decoding error when trying to use YOLOv8 with QGIS. This issue might be related to the environment or how the data is being processed before it reaches the JSON decoder. Here are a couple of suggestions that might help:

1. **Environment Check**: Ensure that your environment is set up correctly. Sometimes, discrepancies between the environment where YOLOv8 is running and QGIS can cause unexpected issues.

2. **Data Inspection**: Before passing data to `YOLO_model`, inspect it to ensure it's in the expected format. A simple print statement or logging the data can help identify if there's something unexpected with the input.

3. **Try Catch Block**: Implement a try-catch block around the JSON decoding operation to catch the error and print/log the problematic data. This might give you more insight into what's causing the issue.

```python
import json

try:
    # Your JSON decoding logic here
except json.decoder.JSONDecodeError as e:
    print("JSON decoding failed:", e)
    # Log or print the data that caused the error
```

4. **Dependencies**: Make sure all dependencies, especially `cpuinfo` and related libraries, are correctly installed and compatible with your Python version.

If these steps don't resolve the issue, could you please provide more details about the data being passed to `YOLO_model`? This might help in diagnosing the problem further. 😊

**Comment by oyupanqui** [comment]
@MohammadMr were you able to solve this issue? I have the same problem as well...

**Comment by MohammadMr** [comment]
Hi. 
yes i solved it temporarily. i edited  /ultralytics/engine/predictor.py file 
in setup_model function i changed device line:

def setup_model(self, model, verbose=True):

        """Initialize YOLO model with given parameters and set it to evaluation mode."""
        self.model = AutoBackend(
            weights=model or self.args.model,
           device=select_device(self.args.device, verbose=verbose),         <----------------
            dnn=self.args.dnn,
            data=self.args.data,
            fp16=self.args.half,
            batch=self.args.batch,
            fuse=True,
            verbose=verbose,
        )`
`
i change it to 
`device = torch.device("cpu")`

this change solve my problem.

**Comment by glenn-jocher** [comment]
Hi @MohammadMr,

Thanks for sharing your solution. While setting the device to CPU can be a temporary fix, I recommend ensuring that your environment is correctly set up for GPU usage. Please verify if the issue persists with the latest package version. If you continue to face problems, feel free to provide more details.

**Comment by oyupanqui** [comment]
@MohammadMr thank you very much, that solves the issue, I've been looking for the root of the problem and I think it's the `cpuinfo` python library, for some reason it opens another QGIS instance when trying to run the function `get_cpu_info()`. This behavior does not happen when using the OSGeo4W Shell.

**Comment by MohammadMr** [comment]
yes its so strange to me too. i didn't face this problem in Linux version of QGIS only in Windows.
I try to update the ultralytics version but my model that i currently use, was trained in version "8.1.19"  and when i update the python package, the post processing that i used on the segment points become obsolete. if i find a new way to maintain the GPU option i will get you posted.

**Comment by glenn-jocher** [comment]
I recommend testing with the latest Ultralytics version in a separate environment to see if the issue persists. This way, you can explore updated features without affecting your current setup. If you find a solution for maintaining GPU support, feel free to share it here.
