### ISSUE TITLE
HOW TO EXPORT MULTI-OBJECT TRACKING MODEL ONNX？

### ISSUE THREAD

**Issue by Li-Whasaka** [ultralytics/ultralytics#8612]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

HOW TO EXPORT MULTI-OBJECT TRACKING MODEL ONNX？
 I want to deploy it with tensorRT

**Comment by glenn-jocher** [comment]
@Li-Whasaka hello! 😊 To export a multi-object tracking model to ONNX, you can use the following command:

```bash
yolo export model=path/to/your/tracking_model.pt format=onnx
```

After exporting to ONNX, you can then use tools like `onnx2trt` to convert the ONNX model to a TensorRT engine for deployment. Here's a quick example:

```bash
onnx2trt your_model.onnx -o your_model.trt
```

Make sure you have the necessary dependencies installed for ONNX and TensorRT conversions. Happy deploying! 🚀
