### ISSUE TITLE
cant find cfg file and yaml file.

### ISSUE THREAD

**Issue by AtriBh** [ultralytics/ultralytics#8615]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

as title suggest,i am not able to find yaml file need to change the backbone for yolov8 + cfg file which needs to pointed yaml file.
Please can anyone tell me where in which directory it may be in? 
i am new to object detection so  i am having trouble find it.

**Comment by glenn-jocher** [comment]
@AtriBh hello! 👋

No worries, we're here to help! If you're looking to modify the model's architecture, such as changing the backbone for YOLOv8, you'll typically work with a `.yaml` file that defines the model structure.

For YOLOv8, the model configuration files are usually located within the `models` directory of the repository. However, please note that the exact structure might vary based on the version of the repository you're working with.

To modify the backbone, you would edit the corresponding `.yaml` file. For example, if you're working with YOLOv8n, you might look for a file named something like `yolov8n.yaml`.

Here's a quick example of how you might change the backbone in a `.yaml` file:

```yaml
# Example modification in yolov8n.yaml
backbone:
  # Your custom backbone configuration here
```

As for the `cfg` file you mentioned, it sounds like you might be referring to additional configuration settings. In YOLOv8, most configurations are handled directly through `.yaml` files or passed as arguments when running your model training or inference commands.

If you're still unable to find the files or if the directory structure seems different, could you please specify which version of the YOLOv8 repository you're using? This will help us guide you more accurately. 🛠️

Feel free to ask more questions if you have any. Happy detecting!

**Comment by AtriBh** [comment]
in given repository ->https://github.com/ultralytics/ultralytics/tree/main

as you said,i have navigated to this path ultralytics/models/yolo/detect
there are no yaml files there only .py format files.
Where are the yaml files located then?

**Comment by AtriBh** [comment]
> @AtriBh hello! 👋
> 
> No worries, we're here to help! If you're looking to modify the model's architecture, such as changing the backbone for YOLOv8, you'll typically work with a `.yaml` file that defines the model structure.
> 
> For YOLOv8, the model configuration files are usually located within the `models` directory of the repository. However, please note that the exact structure might vary based on the version of the repository you're working with.
> 
> To modify the backbone, you would edit the corresponding `.yaml` file. For example, if you're working with YOLOv8n, you might look for a file named something like `yolov8n.yaml`.
> 
> Here's a quick example of how you might change the backbone in a `.yaml` file:
> 
> ```yaml
> # Example modification in yolov8n.yaml
> backbone:
>   # Your custom backbone configuration here
> ```
> 
> As for the `cfg` file you mentioned, it sounds like you might be referring to additional configuration settings. In YOLOv8, most configurations are handled directly through `.yaml` files or passed as arguments when running your model training or inference commands.
> 
> If you're still unable to find the files or if the directory structure seems different, could you please specify which version of the YOLOv8 repository you're using? This will help us guide you more accurately. 🛠️
> 
> Feel free to ask more questions if you have any. Happy detecting!

in given repository ->https://github.com/ultralytics/ultralytics/tree/main

as you said,i have navigated to this path ultralytics/models/yolo/detect
there are no yaml files there only .py format files.
Where are the yaml files located then?

**Comment by glenn-jocher** [comment]
Hey @AtriBh! 😊

Apologies for the confusion earlier. It seems there was a mix-up in the directions provided. In the YOLOv8 repository, the model configuration files you're looking for are indeed in YAML format, but they're not located under `ultralytics/models/yolo/detect`. 

For YOLOv8, you should find the YAML files directly in the `models` directory or possibly in a `configs` directory, depending on the exact structure of the version you're using. These YAML files define the model architecture, including the backbone, and are used for specifying the model you wish to train or modify.

If you're still having trouble locating them, it might be helpful to use the repository's search feature or look through the documentation for any references to these configuration files. 

Again, sorry for the mix-up, and thanks for your patience! If you have any more questions or need further assistance, feel free to ask. Happy to help!

**Comment by baxtrax** [comment]
@AtriBh 
The config files for the different YOLO models are in the [ultralytics/cfg/models/v8/](https://github.com/ultralytics/ultralytics/tree/main/ultralytics/cfg/models/v8)

To make your changes (such as modifying the backbone) copy the contents of the yaml, and make a new yaml which you will then pass into the YOLO class:

```python
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.yaml')  # build a new model from YAML
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)
model = YOLO('yolov8n.yaml').load('yolov8n.pt')  # build from YAML and transfer weights
```
[Example source](https://docs.ultralytics.com/modes/train/#usage-examples)
