### ISSUE TITLE
Training fails when results.csv file is open

### ISSUE THREAD

**Issue by bit-scientist** [ultralytics/ultralytics#862]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Detection

### Bug

Have been training my custom dataset, and then just opened its `results.csv` located in `my_trainings` folder out of curiousity. To my surprise, the training got interrupted by this, throwing the error below:

```
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    147/200      11.2G     0.5492     0.2587     0.8572        130        320: 100%|██████████| 44/44 [00:27<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:5
                   all        327       1662      0.979      0.979      0.983       0.87
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\yolov8\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\anaconda3\envs\yolov8\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\anaconda3\envs\yolov8\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\anaconda3\envs\yolov8\lib\site-packages\ultralytics\yolo\cfg\__init__.py", line 237, in entrypoint
    func(cfg)
  File "C:\Users\user\anaconda3\envs\yolov8\lib\site-packages\ultralytics\yolo\v8\detect\train.py", line 205, in train
    model.train(**vars(cfg))
  File "C:\Users\user\anaconda3\envs\yolov8\lib\site-packages\ultralytics\yolo\engine\model.py", line 201, in train
    self.trainer.train()
  File "C:\Users\user\anaconda3\envs\yolov8\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 183, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "C:\Users\user\anaconda3\envs\yolov8\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 343, in _do_train
    self.save_metrics(metrics={**self.label_loss_items(self.tloss), **self.metrics, **self.lr})
  File "C:\Users\user\anaconda3\envs\yolov8\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 500, in save_metrics
    with open(self.csv, 'a') as f:
PermissionError: [Errno 13] Permission denied: 'my_trainings\\v8n_320_\\results.csv'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-Break to quit
```
I couldn't recall seeing this phenomenon before with yolov5, so I thought it might be helpful to amend this. 

### Environment

Ultralytics YOLOv8.0.18  Python-3.8.13 torch-1.13.1 CUDA:0 (NVIDIA GeForce RTX 3080 Ti, 12288MiB) on Windows 10

### Minimal Reproducible Example

There's no code to reproduce, just train normally and open the `results.csv`.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@bit-scientist I'm unable to reproduce any issues here. I opened results.csv in colab and see the results and training continues unaffected.

<img width="1773" alt="Screenshot 2023-02-08 at 11 22 07" src="https://user-images.githubusercontent.com/26833433/217461517-8d9439ee-d112-4345-8cb1-15befa1e9f67.png">

**Comment by bit-scientist** [comment]
Interesting, I tried it once again and got the same error:

---

![image](https://user-images.githubusercontent.com/26497571/217673792-e02f2a90-82fb-4b04-b10e-c6b4010e9d0b.png)
---

Could you (or someone else) try on a Windows machine just to check if that's not specific to me? 
I am only using Windows Security and [AhnLab Safe Transaction](https://global.ahnlab.com/site/main.do) firewalls if that matters at all.

**Comment by mustafaausama** [comment]
Hey, @bit-scientist this is not an Ultralytics problem. This is an Excel problem. Excel locks the file when you open it; hence, no other program can change it. One workaround is to open this file in read-only mode. Here's how you might do that.

```powershell
[HKEY_CLASSES_ROOT\Excel.CSV\shell\Open_in_read_only_Excel]
@="Open read-only in Excel"

[HKEY_CLASSES_ROOT\Excel.CSV\shell\Open_in_read_only_Excel\command]
@="\"C:\\Program Files (x86)\\Microsoft Office\\Office12\\EXCEL.EXE\" /r \"%1\""
```

More info here: https://superuser.com/a/491191

Or you could just open it in VSCode and preview the csv as a table.
