### ISSUE TITLE
Bug in mGPU mode.

### ISSUE THREAD

**Issue by mandal4** [ultralytics/ultralytics#8622]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

1. Do not call ultralytics package in the directory(cwd/ultralytics/*). It needs what is set with `pip install ultralytics` (call local ultralytics succesfully in 1-gpu mode)
2. Do not load pre-trained weight file in following code lines. (load succesfully in 1-gpu mode)

> model = YOLO("yolov8m.yaml)
> model.load("yolov8m-oiv7.pt)
> model.train()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mandal4 hello! Thanks for bringing this to our attention. 🌟 It seems like you're encountering issues with multi-GPU (mGPU) mode that don't appear in single-GPU mode. This could be related to how the environment is set up for mGPU training. 

A common pitfall is the working directory or the way the package is imported when using multiple GPUs. Ensure that your working directory is correctly set and that the `ultralytics` package is installed and imported from the environment, not from a local directory. 

For the issue with loading pre-trained weights, it's crucial to ensure that the file path is accessible from all GPUs and that the file permissions allow reading the weights. 

Here's a quick check you can perform:
- Ensure `ultralytics` is installed in your environment: `pip list | grep ultralytics`
- Verify the file path to your weights is correct and accessible.

If the problem persists, could you please provide more details about your environment (e.g., OS, Python version, PyTorch version, and how you're initiating mGPU training)? This will help us diagnose the issue more effectively.

Thanks for your cooperation, and looking forward to resolving this together!

**Comment by cozeybozey** [comment]
I can confirm I have the same issue.

**Comment by glenn-jocher** [comment]
@cozeybozey hi there! 👋 Thanks for confirming that you're experiencing the same issue. It's really helpful to know it's not an isolated case. Could you please ensure that the `ultralytics` package is correctly installed in your environment? You can check this with:

```bash
pip list | grep ultralytics
```

Also, double-check the file path to your weights to ensure it's accessible. If the issue persists, sharing a bit more about your setup (OS, Python version, etc.) would be great for further assistance. Thanks for reaching out, and we're here to help get this sorted! 🚀

**Comment by cozeybozey** [comment]
The package is correctly installed:
![image](https://github.com/ultralytics/ultralytics/assets/71214958/523c1508-1877-4be2-b60d-c738404fe269)

As for my setup, I am using linux through debian and I am using python version 3.10.10. But I have a branch in which I am using an older version of yolov8 and there I do not experience the problems with training on multiple gpu's. So I don't think that linux or the python version have anything to do with the issue.

**Comment by glenn-jocher** [comment]
@cozeybozey hey there! 🌟 Thanks for the update and for confirming that the `ultralytics` package is correctly installed. Given your setup on Debian with Python 3.10.10 and the fact that an older version of YOLOv8 works fine on multiple GPUs, it sounds like the issue might be specific to the newer version of YOLOv8 you're using.

Could you try updating to the latest version of YOLOv8 (if you haven't already) to see if that resolves the issue? Sometimes, bugs related to mGPU training are addressed in newer releases. Here's how you can update:

```bash
pip install ultralytics --upgrade
```

If the problem persists after updating, it might be helpful to compare the configurations or any changes in the codebase between the two versions you're using. This could provide some clues as to what's causing the issue with mGPU training in the newer version.

Let's keep the conversation going, and we'll do our best to help you sort this out! 🚀

**Comment by mandal4** [comment]
Thanks to your kind reply @glenn-jocher 
But i want to call ultralytics package in local path because i modifed implementation of the model and dataloader.
With pip install ultralytics, it neglect my customized code in mGPU mode.

**Comment by glenn-jocher** [comment]
Hey @mandal4! 😊 Totally understand your need to work with a modified version of YOLOv8 for your specific project requirements. When working in multi-GPU mode with local changes, setting `PYTHONPATH` to your local repository can help ensure your environment picks up the modified code instead of the installed package. Before running your training script, try this in your terminal:

```bash
export PYTHONPATH=/path/to/your/ultralytics_repo:$PYTHONPATH
```

Replace `/path/to/your/ultralytics_repo` with the actual path to your modified ultralytics YOLOv8 directory. This should force Python to use your local changes. If issues persist, ensuring all nodes in your multi-GPU setup can access the modified code is also key. Looking forward to hearing how it goes! 🚀

**Comment by mandal4** [comment]
I found that with DDP mode, it runs `/data/user/.config/Ultralytics/DDP/some_temp_script.py`. 
And the temp script is from Ultralytics from pip installed. 
I guess this design makes it neglect custom script.

**Comment by glenn-jocher** [comment]
Hi there! 😊 It seems like you've pinpointed the source of the issue. DDP indeed uses a temporary script for distributed training, which might not account for locally modified scripts. A workaround could involve explicitly pointing to your modified script or integrating your custom changes directly into the DDP temp script for consistency. This approach ensures your custom modifications are considered during distributed training. Here's a quick example of how you could modify the DDP command:

```python
# Before running DDP, set the path to your custom script
import os
os.environ["ULTRALYTICS_TEMP_SCRIPT"] = "/path/to/your/custom_script.py"
```

This way, your customized model and dataloader should be acknowledged in a DDP environment. Hope this helps, and let's keep the great observations coming! 🌟
