### ISSUE TITLE
Is there a YOLOv8 TensorFlow version?

### ISSUE THREAD

**Issue by Developer-Moon** [ultralytics/ultralytics#8624]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there a YOLOv8 TensorFlow version? 
If so, can I modify it and use it commercially?

**Comment by glenn-jocher** [comment]
@Developer-Moon hello! 😊

Currently, YOLOv8 is primarily developed for PyTorch. However, you can export YOLOv8 models to TensorFlow formats like SavedModel or TF Lite for deployment. Here's how you can export to a TensorFlow SavedModel:

```bash
yolo export model=yolov8n.pt format=saved_model
```

Regarding commercial use, if you're using the AGPL-3.0 licensed version, any modifications or derivative works must also be open-sourced under AGPL-3.0. For commercial product development without open-source requirements, you would need an Ultralytics Enterprise License. Feel free to reach out for more details on licensing!

Hope this helps!
