### ISSUE TITLE
detect return result do not have pre_class

### ISSUE THREAD

**Issue by Hammer-888** [ultralytics/ultralytics#8630]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

**yolo.detect.DetectionPredictor** 's **Results** class don't have pre_class, this is not flexible.
![image](https://github.com/ultralytics/ultralytics/assets/82921242/80bb287e-22f9-4f9d-8834-7a0fea7b44d3)

**Comment by glenn-jocher** [comment]
@Hammer-888 hello! Thanks for reaching out with your question. 😊

The `Results` class indeed does not directly contain a `pre_class` attribute. However, you can easily access the predicted class IDs for each detection through the `classes` attribute in the `Boxes` object, which is part of the `Results` object. Here's a quick example on how you can do this:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('yolov8n.pt')

# Run inference
results = model('path/to/your/image.jpg')

# Access predicted class IDs
predicted_classes = results[0].boxes.cls

print("Predicted class IDs:", predicted_classes)
```

This will give you the class IDs of the detected objects, which you can then map to class names using the `names` attribute if needed. Hope this helps! Let us know if you have any more questions.
