### ISSUE TITLE
IndexError: index 1 is out of bounds for dimension 1 with size 1

### ISSUE THREAD

**Issue by MarjanNoushinfar** [ultralytics/ultralytics#8636]
### Search before asking

- [ ] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

hello, I think I have the same poroblem. I try to train yolov8 object detection on a custom dataset (https://github.com/nicolaihaeni/MinneApple). so I only have 1 calss. after creating the annotations in this form: 1 0.3916666805744171 0.5289062261581421 0.4305555522441864 0.551562488079071 I try to start the training but I get the following error:in get_box_metrics(self, pd_scores, pd_bboxes, gt_labels, gt_bboxes, mask_gt)
111 # ind[1] = gt_labels.squeeze(-1) # b, max_num_obj
112 # # Get the scores of each grid for each gt cls
--> 113 # bbox_scores[mask_gt] = pd_scores[ind[0], :, ind[1]][mask_gt] # b, max_num_obj, hw
114
115 # # (b, max_num_obj, 1, 4), (b, 1, hw, 4)

IndexError: index 1 is out of bounds for dimension 1 with size 1
thanks in advance

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MarjanNoushinfar** [comment]
thank you, with class index 0 and single-cls=True, the problem is solved

**Comment by glenn-jocher** [comment]
@MarjanNoushinfar That's great to hear! 😊 If you encounter any more issues or have further questions, don't hesitate to reach out. Happy training with YOLOv8!
