### ISSUE TITLE
Inconsistent functions outputs: NumPy vs. Torch tensors for xyxyxyxy2xywhr and xywhr2xyxyxyxy

### ISSUE THREAD

**Issue by YuriGagarine** [ultralytics/ultralytics#8652]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I discovered inconsistent outputs if given numpy array or torch Tensor when chaining the two funcs.

### Environment

NA

### Minimal Reproducible Example

```
import numpy as np
import torch

from ultralytics.utils.ops import xyxyxyxy2xywhr, xywhr2xyxyxyxy

x1, y1 = 1, 2
x2, y2 = 7, 2
x3, y3 = 7, 4
x4, y4 = 1, 4

corners_numpy = np.array([[x1, y1, x2, y2, x3, y3, x4, y4]])
corners_torch = torch.Tensor([[x1, y1, x2, y2, x3, y3, x4, y4]])

xywhr_numpy = xyxyxyxy2xywhr(corners_numpy)
xywhr_torch = xyxyxyxy2xywhr(corners_torch)

print(xywhr2xyxyxyxy(xywhr_numpy))
print(xywhr2xyxyxyxy(xywhr_torch))


>>> [[[     2.0159      5.4624]
  [     7.0647      2.2206]
  [     5.9841     0.53762]
  [    0.93528      3.7794]]]
tensor([[[1.0000, 4.0000],
         [7.0000, 4.0000],
         [7.0000, 2.0000],
         [1.0000, 2.0000]]])
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by wanyne-yyds** [comment]
Have you analyzed the reason?

**Comment by glenn-jocher** [comment]
@YuriGagarine @wanyne-yyds bug is reproducible, I've added a TODO tag to queue for a fix. Thank you for your patience.

@Laughing-q can you investigate this please? I can reproduce with OPs code, I get this. I was thinking might be due to radians vs degrees but not sure.

```
[[[     2.0159      5.4624]
  [     7.0647      2.2206]
  [     5.9841     0.53762]
  [    0.93528      3.7794]]]
tensor([[[1.0000, 4.0000],
         [7.0000, 4.0000],
         [7.0000, 2.0000],
         [1.0000, 2.0000]]])
```
