### ISSUE TITLE
Yolov9c performance

### ISSUE THREAD

**Issue by tjasmin111** [ultralytics/ultralytics#8657]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I did some tests with the `yolov9c.pt`. I see it is almost the size of yolov8m (49MB). Is it fair to compare these two together?
But I noticed the runtime of yolov9c is 2x than that of the yolov8m. What is the reason?
Both predicted the same number of classes correctly, with very similar confidence scores.

yolov8m:
```
717.1ms
Speed: 5.9ms preprocess, 717.1ms inference, 4.1ms postprocess per image at shape (1, 3, 448, 640)

```
yolov9c:
```
1455.3ms
Speed: 4.0ms preprocess, 1455.3ms inference, 15.4ms postprocess per image at shape (1, 3, 448, 640)
```

**Comment by sunmooncode** [comment]
An auxiliary reversible branch is included in the yolov9-c.pt model, which can be removed in the actual reasoning process. Reasoning with the [yolov9-convert-c.pt](https://github.com/WongKinYiu/yolov9/releases/download/v0.1/yolov9-c-converted.pt) model.

**Comment by minhhotboy9x** [comment]
@sunmooncode if we get v8 model from yaml, does it include this reversible branch in training. I checked the yolov9c.yaml and yolov9e.yaml and didn't see any auxiliary branches with additional detect heads.

**Comment by sunmooncode** [comment]
@minhhotboy9x You want to train the model with auxiliary reversible branches, you need to switch the DDetect in the yolov9-c.yaml configuration file to [DualDDetect ](https://github.com/WongKinYiu/yolov9/blob/9660d127cf5a4f8d51d19b09ba299f98a0672ca7/models/yolo.py#L190)(1 auxiliary branch + 1 master branch).

**Comment by tjasmin111** [comment]
> An auxiliary reversible branch is included in the yolov9-c.pt model, which can be removed in the actual reasoning process. Reasoning with the [yolov9-convert-c.pt](https://github.com/WongKinYiu/yolov9/releases/download/v0.1/yolov9-c-converted.pt) model.

I was trying to use that converted .pt model. I got this error:

```
TypeError: ERROR  yolov9-c-converted.pt appears to be an Ultralytics YOLOv5 model originally trained with https://github.com/ultralytics/yolov5.
This model is NOT forwards compatible with YOLOv8 at https://github.com/ultralytics/ultralytics.
```

**Comment by glenn-jocher** [comment]
@tjasmin111 hey there! It looks like you're trying to load a model that was trained with a different version of YOLO. To resolve this, please ensure you're using the correct repository and version that matches the model. For models trained with YOLOv9, you should use the YOLOv9 repository and codebase. If you're working within the Ultralytics ecosystem and want to use a model across different versions, you might need to convert the model to the appropriate format or retrain it using the desired version's training script. If you need further assistance, feel free to ask! 😊
