### ISSUE TITLE
.engine loading issue

### ISSUE THREAD

**Issue by fdcqqqq** [ultralytics/ultralytics#866]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

  File "/home/benteng/miniconda3/envs/yolov7/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 62, in __init__
    raise NotImplementedError(f"'{suffix}' model loading not implemented")
NotImplementedError: '.engine' model loading not implemented
Sentry is attempting to send 2 pending error messages

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@fdcqqqq TensorRT export and inference should now be working! Please try again with the latest version and let us know if your issue is resolved.

**Comment by AdamRoden** [comment]
@glenn-jocher There are lots of issues with yolov8 and TensorRT and it is really hard to troubleshoot first and foremost because I can't find any documentation for yolov8 compatibility with TensorRT, PyTorch, CUDA Toolkit, onnx-runtime, etc..

What setup is necessary to use this with TensorRT?
Yesterday I was finally able to use yolov8 to export a model to trt. Hint: (CUDA Toolkits > 11.7 do not work, but 11.7 does.) Even after exporting a trt model, I'm still unable to run inference with it using any version of code I've found or tweaked. Can anyone share their working package versions and code?

I also tried the code from @triple-Mu and it didn't work out for me as I ran into issues with that as well.

**Comment by Laughing-q** [comment]
@AdamRoden I'd like to share you my local env info:
- cuda-11.1
- cudnn-8.4.1.50
- Tensorrt-8.4.1.5
- pytorch-1.10.2+cu111
- onnxruntime-gpu-1.14.0
all of them are not the latest version, but works to me. hope this will help you. :)

**Comment by Rm1n90** [comment]
Hi @glenn-jocher, I have exported my segmentation model successfully to TensorRT however Im getting following error during validation of tensorRT model

```
yolo val task=segment model=/home/Documents/yolov8/runs/segment/weights/best.engine imgsz=640 data=/home/data/segment/seg.yaml
WARNING ⚠️ 'task=segment' conflicts with detect model /home/Documents/yolov8/runs/segment/weights/best.engine. Inheriting 'task=detect' from /home//yolov8/runs/segment/weights/best.engine and ignoring 'task=segment'.
Ultralytics YOLOv8.0.43 🚀 Python-3.8.16 torch-1.12.1+cu116 CUDA:0 (NVIDIA GeForce RTX 3090, 24265MiB)
Loading /home/yolov8/runs/segment/weights/best.engine for TensorRT inference...
[02/23/2023-10:29:53] [TRT] [I] [MemUsageChange] Init CUDA: CPU +327, GPU +0, now: CPU 446, GPU 10191 (MiB)
[02/23/2023-10:29:53] [TRT] [I] Loaded engine size: 24 MiB
[02/23/2023-10:29:53] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +934, GPU +414, now: CPU 1433, GPU 10631 (MiB)
[02/23/2023-10:29:53] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.3.2
[02/23/2023-10:29:53] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +23, now: CPU 0, GPU 23 (MiB)
[02/23/2023-10:29:53] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +32, now: CPU 1409, GPU 10631 (MiB)
[02/23/2023-10:29:53] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.3.2
[02/23/2023-10:29:53] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +20, now: CPU 0, GPU 43 (MiB)
val: Scanning /home/FT/labels/valid... 109 images, 11 backgrounds, 0 corrupt: 100%|██████████| 120/120 [00:00<00:00, 3013.29it/s]
val: New cache created: /home/datasets/seg/labels/valid.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/120 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/anaconda3/envs/analytic/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/anaconda3/envs/analytic/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 304, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/anaconda3/envs/analytic/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/anaconda3/envs/analytic/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 235, in val
    validator(model=self.model)
  File "/home/anaconda3/envs/analytic/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/anaconda3/envs/analytic/lib/python3.8/site-packages/ultralytics/yolo/engine/validator.py", line 173, in __call__
    self.update_metrics(preds, batch)
  File "/home/anaconda3/envs/analytic/lib/python3.8/site-packages/ultralytics/yolo/v8/detect/val.py", line 105, in update_metrics
    self.confusion_matrix.process_batch(predn, labelsn)
  File "/home/anaconda3/envs/analytic/lib/python3.8/site-packages/ultralytics/yolo/utils/metrics.py", line 212, in process_batch
    self.matrix[detection_classes[m1[j]], gc] += 1  # correct
IndexError: index 8 is out of bounds for axis 0 with size 6

```


This is how I export my model to engine file. 

```
model = YOLO("/home/weights/best.pt")
model.info(verbose=True)
model.fuse()
model.export(format='TensorRT', verbose=True, device=0, half=True, opset=12, workspace=30)
```

**Comment by Laughing-q** [comment]
@Rm1n90 Thanks for the reporting! I can reproduce it and we'll fix it soon. :)

**Comment by Laughing-q** [comment]
@Rm1n90 BTW I think you can rename the `best.engine` to `best-seg.engine` for now as a temporary solution. The code is guessing the task by the suffix i.e `-seg` and `-cls` in model name for now when the model is not a pt file.

**Comment by glenn-jocher** [comment]
@Laughing-q so this is happening because we are trying to assign a task to a model before the user has a chance to define a task, i.e. both CLI and python workflows require us to 1) build a model, then 2) execute a mode with a task. What's happening is that we are guessing the task in step 1 and then using that, ignoring task argument in step 2. 

I think we may want to leave task unknown in step 1, and then only try to resolve in step 2.

**Comment by AdamRoden** [comment]
> @AdamRoden I'd like to share you my local env info:
> 
> * cuda-11.1
> * cudnn-8.4.1.50
> * Tensorrt-8.4.1.5
> * pytorch-1.10.2+cu111
> * onnxruntime-gpu-1.14.0
> 
> all of them are not the latest version, but works to me. hope this will help you. :)

@Laughin-q Thanks for the response! I wonder if you could also run `pip list` and share the results? I've had compatibility issues on so many other packages at one point or another and think a full list would help. Also, are you willing to share a few lines of code on how you load the engine model and run prediction. I tried triple-Mu's approach but it didn't work for me.

**Comment by glenn-jocher** [comment]
@AdamRoden TensorRT export and inference are very simple. You can run these in a normal Colab notebook, everything works correctly, i.e.:
https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb

```python
!yolo export model=yolov8n.pt format=engine device=0
!yolo predict task=detect model=yolov8n.engine imgsz=640
```

<img width="1352" alt="Screenshot 2023-02-23 at 15 18 03" src="https://user-images.githubusercontent.com/26833433/221053275-1e36d2b8-623c-4956-97ac-3295c0d7fe56.png">

**Comment by AdamRoden** [comment]
@glenn-jocher Thanks for pointing that out. I had been doing it all exclusively in a local environment and didn't realize I could simply look at Colab to get the versions used to build everything. I've confirmed that the code you suggested works in Colab, and in my local environment. I also confirmed that I can run it in my python script, (sample code below.) Using .engine rather than .pt gave me a 10-30% boost in overall speed with a very high variance depending on what else I may be doing while the script is running. I can process get 30-40 images per second.
```model = YOLO('yolov8l.engine')
frame = np.array(myImage)
results = model(frame, stream=False, device=0, conf=.25, iou=.25, verbose=False```

**Comment by Laughing-q** [comment]
> @Laughing-q so this is happening because we are trying to assign a task to a model before the user has a chance to define a task, i.e. both CLI and python workflows require us to 1) build a model, then 2) execute a mode with a task. What's happening is that we are guessing the task in step 1 and then using that, ignoring task argument in step 2.
> 
> I think we may want to leave task unknown in step 1, and then only try to resolve in step 2.
> 
> EDIT: the complicated part is that we are trying to also define trainer, validator, predictor, etc for the model in step 1, and these definitions depend on task. We might want to leave them undefined also in step 1.
> 
> @AyushExel

@glenn-jocher @AyushExel how about we support the functionality of guessing task only when it's a pt file no matter what the mode is(train, val, predict)?
I just realized that users might also have their modified `model.yaml` for custom training, they'll encounter the same issue as they don't know how the `guess_model_task` works.

So the usage will be like this:
```bash
# works correctly
yolo train model=yolov8n-seg.pt data=...
yolo val model=best.pt data=...
yolo predict model=best.pt data=...

# throw an error says "can't read the task from model, please point a task."
yolo train model=yolov8n-seg.yaml data=...
yolo val model=best.engine data=...
yolo predict model=best.engine data=...
```
