### ISSUE TITLE
Yolov9 different model sizes

### ISSUE THREAD

**Issue by tjasmin111** [ultralytics/ultralytics#8661]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I noticed there is support for yolov9 through 2 different sizes: yolov9c (is it M?) and yolov9e.
Can we add a Nano version of yolov9 as well?

**Comment by glenn-jocher** [comment]
@tjasmin111 hello! 😊

Thanks for reaching out with your question. Currently, YOLOv9 offers the `yolov9c` and `yolov9e` model sizes. The idea of introducing a Nano version sounds intriguing and could potentially benefit applications requiring even lighter models for faster inference on resource-constrained devices.

While we don't have a Nano version available at the moment, we're always looking to improve and expand our model offerings based on community feedback. I'll definitely pass your suggestion to our development team for consideration in future updates.

In the meantime, if you're looking for smaller, efficient models, I recommend exploring the YOLOv8 series, which includes several lightweight options that might suit your needs.

Stay tuned for updates, and feel free to contribute ideas or requests on our GitHub discussions page! 🚀

**Comment by nhyman** [comment]
Thanks @glenn-jocher , I'm also interested in the nano or small model. Hoping you can add them soon!

**Comment by glenn-jocher** [comment]
@nhyman hi there! 👋

Thanks for expressing your interest in smaller models like a nano version! We're always exploring ways to cater to diverse needs, including efficiency and speed for various devices. While we don't have a nano model in the YOLOv9 series just yet, your feedback is invaluable and helps guide our development priorities.

Keep an eye on our updates; we're continuously working on enhancing our model offerings. Thanks for being part of our community! 🌟

**Comment by MoAbbasid** [comment]
also hoping for the smaller models implementation to be released

**Comment by glenn-jocher** [comment]
@MoAbbasid absolutely, we appreciate your enthusiasm for smaller models! 🚀 We're on the same page about the importance of having more size-efficient models for various applications. While we're exploring options, stay tuned for future releases that may include what you're seeking. Thanks for your support!

**Comment by glenn-jocher** [comment]
@hahouari hey there! 😊

We totally understand the need for models that are friendlier on GPUs with smaller VRAM. It's awesome that you're eager to dive into training models like `gelan-c`! The mention of M or S versions in our docs is indeed a nudge towards what's possibly on the horizon.

As for the VRAM issue, here's a quick tip that might help you train on your 6GB GPU:

```python
# Reduce batch size
yolo detect train data=your_dataset.yaml model=gelan-c.yaml batch=4
```

Reducing the batch size can significantly lower VRAM requirements. 

We're constantly working on expanding our model offerings. Keep an eye out for updates; smaller models could be coming soon! Thanks for being part of our community and for your valuable feedback. 🌟

**Comment by hahouari** [comment]
Thank you so much for your kind reply., indeed that's what I did with the batch, I trained my gelan-c-det with batch size 3 and that was my sweet point.✅

**Comment by glenn-jocher** [comment]
@hahouari That's fantastic to hear! 😊 It sounds like you found just the right setting for your setup. Training with a batch size of 3 is a great way to manage VRAM efficiently. If you have more insights or questions as you continue your work with YOLOv8, we're here to help. Keep up the great work! 🚀

**Comment by tjasmin111** [comment]
How do Yolov9 models compare with a yolov8? Can I compare v9-m with a v8-m and v9-T with a v8-Nano? Would it be a valid comparison?

**Comment by glenn-jocher** [comment]
@tjasmin111 absolutely, you can compare YOLOv9 models with their YOLOv8 counterparts! Comparing `v9-m` with `v8-m` and `v9-T` with `v8-Nano` would indeed provide insights into performance and efficiency improvements between the versions. Keep in mind the differences in architecture and features might influence their performance on specific tasks or datasets. Happy experimenting! 🚀

**Comment by Soorajkumar3** [comment]
how to access v9 T model

**Comment by glenn-jocher** [comment]
@Soorajkumar3 hi there! 👋

Currently, only the `YOLOv9c` and `YOLOv9e` models are available for public use. We're working on releasing other model scales, including the `YOLOv9t`, so please stay tuned for updates. Your interest is much appreciated, and we're excited to bring you more options soon!

Thanks for reaching out! 😊

**Comment by Soorajkumar3** [comment]
No worries, thanks for the update!

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance in the future, feel free to reach out. Happy coding! 😊
