### ISSUE TITLE
About Video configuration

### ISSUE THREAD

**Issue by ozankavcu38** [ultralytics/ultralytics#8668]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello by the way , i am training and using YOLOv8 with pose attributes like that model = YOLO("yolov8n-pose.pt")

results = model(source="C://Users//Hp//Desktop//videolar//operation_room_1.mp4", show=True, conf=0.3, save=False,
                verbose=False, stream=True,show_conf=False) 
The question i wanna ask you is i wanna show the video however i dont want to see anything about on that video i dont want to see pose graphics but on the back my codes must be continue to execute , and to this i want to write something on this video that i  find out from my code like i just want to write some values that i figured out .

**Comment by glenn-jocher** [comment]
@ozankavcu38 hello! 👋 It sounds like you're looking to process a video with YOLOv8 for pose estimation but want to customize the output display. If you're looking to hide the pose graphics while still running the detection in the background and display custom text (like certain values you've computed), you can achieve this by manipulating the results before displaying the video.

Here's a simplified approach to customize your video output:

1. Run your model as you're currently doing but with `show=False` to prevent automatic display.
2. Process the `results` to extract or compute the values you're interested in.
3. Use OpenCV to write your custom text on the frames and display them.

```python
import cv2
from ultralytics import YOLO

# Load your model
model = YOLO("yolov8n-pose.pt")

# Run detection without showing the video
results = model(source="C://Users//Hp//Desktop//videolar//operation_room_1.mp4", show=False, conf=0.3, save=False, verbose=False, stream=True, show_conf=False)

# Assuming you have a function to process results and return text
# def process_results(results): return "Your Text Here"

# Open video source
cap = cv2.VideoCapture("C://Users//Hp//Desktop//videolar//operation_room_1.mp4")

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    
    # Process your results to get the text you want to display
    custom_text = process_results(results)
    
    # Write custom text on frame
    cv2.putText(frame, custom_text, (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
    
    # Display the frame
    cv2.imshow('Frame', frame)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
```

This example assumes you have a function `process_results` that can take your `results` and return a string of the custom text you want to display. Adjust the text position and styling as needed. Press 'q' to quit the video window. Hope this helps!

**Comment by ozankavcu38** [comment]
It sounds great i have done this however when i save already appeared with lines and boxes i just want saved with just custom lines sir can you help me

**Comment by glenn-jocher** [comment]
Hello @ozankavcu38! 😊 I'm glad to hear the previous suggestions worked out for you. To save the video without the default YOLO annotations (like lines and boxes) but with your custom text, you can follow a modified approach. Essentially, you'll still process your video frame-by-frame as before, but you'll save the frames with only your custom annotations into a new video file. Here's a quick example using OpenCV:

```python
import cv2

# Prepare for video saving
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('output.avi', fourcc, 20.0, (640,  480))  # Adjust the FPS and frame size as needed

cap = cv2.VideoCapture("path_to_your_video.mp4")

while(cap.isOpened()):
    ret, frame = cap.read()
    if not ret:
        break

    # Your custom processing and text drawing happens here
    custom_text = "Your dynamic text here!"  # Example placeholder
    cv2.putText(frame, custom_text, (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
  
    # Save the frame to the new video
    out.write(frame)
  
    # Optionally show the frame
    # cv2.imshow('frame', frame)
    # if cv2.waitKey(1) & 0xFF == ord('q'):
        # break

cap.release()
out.release()
cv2.destroyAllWindows()
```

This code will create a new video file (`output.avi`) that contains only your custom annotations. Make sure to adjust the frame size `(640, 480)` to match your source video's resolution. Hope this helps you get the exact output you're looking for! 🚀
