### ISSUE TITLE
How to get the data from the tracked objects in yolov8?

### ISSUE THREAD

**Issue by anishka07** [ultralytics/ultralytics#8671]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Im working on a vehicle detection project and i have made a script that detects vehicles. The thing is i dont want the code to track the vehicles from my main file rather, I want to it to track and plot it on another sub-file. My question is how do i extract all the information about all the objects i tracked and use that data to track and plot it on my sub file.
`from ultralytics.solutions.heatmap import Heatmap
from ultralytics import YOLO
import cv2

class VehicleTracker:
    def __init__(self, video_path):
        self.video_path = video_path
        self.model = YOLO('yolov8x.pt')
        self.read_video()

    def read_video(self):
        self.cap = cv2.VideoCapture(self.video_path)
        self.w, self.h, self.fps = self.get_video_properties()
        self.heatmap_object = Heatmap()
        self.heatmap_object.set_args(
            imw=self.w, imh=self.h, colormap=cv2.COLORMAP_HOT, heatmap_alpha=0.4, view_img=True, shape='rect'
        )
        # self.classes = classes

    def get_video_properties(self):
        return (int(self.cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

    def get_trackable_objects(self):
        return self.model.names

    def get_indices(self, obj_to_track: []):
        self.obj_to_track = obj_to_track
        self.classes_dict = self.get_trackable_objects()
        self.reverse_dict = {v:k for k, v in self.classes_dict.items()}
        self.indices = [self.reverse_dict[class_name] for class_name in self.obj_to_track if class_name in self.reverse_dict]
        return self.indices

    # def get_data(self, results, frame):
    #     xyxys = []
    #     confidences = []
    #     class_ids = []
    #     for result in results:
    #         boxes = result.boxes.cpu().numpy()
    #         xyxys.append(boxes.xyxy)
    #         confidences.append(boxes.conf)
    #         class_ids.append(boxes.classes)
    #     return xyxys, confidences, class_ids, frame

    def vehicle_tracker(self, classes, conf=.5):
        xyxys = []
        confidences = []
        class_ids = []
        self.classes = self.get_indices(classes)
        while self.cap.isOpened():
            ret, frame = self.cap.read()
            if not ret:
                print("Error reading video stream or file")

            results = self.model(frame)
            for result in results:
                boxes = result.boxes.cpu().numpy()
                xyxys.append(boxes.xyxy)
                confidences.append(boxes.conf)
                class_ids.append(boxes.classes)

        return xyxys, confidences, class_ids, frame
            # frame_ = results[0].plot()
            # cv2.imshow("Frame", frame_)

            # if cv2.waitKey(1) & 0xFF == ord('q'):
                # break
        # self.cap.release()
        # cv2.destroyAllWindows()

`
this is the code i've been using, please help

**Comment by glenn-jocher** [comment]
@anishka07 hey there! 👋 It looks like you're on the right track with your vehicle detection project. To extract and use the tracking data in a sub-file, you can follow a simplified approach. Here's a quick guide:

1. **Extract Tracking Data**: Modify your `vehicle_tracker` method to store tracking data (like bounding boxes, confidences, and class IDs) in a structured format, such as a list of dictionaries. Each dictionary can represent a detected object in a frame.

2. **Return Data for External Use**: Ensure your `vehicle_tracker` method returns this structured data. This way, you can easily access and manipulate it outside of your `VehicleTracker` class.

3. **Use Data in Sub-file**: Pass the returned data to your sub-file functions or classes where you can further process it, such as plotting heatmaps or tracking movements.

Here's a simplified version of how you might adjust your `vehicle_tracker` method:

```python
def vehicle_tracker(self, classes, conf=.5):
    tracked_objects = []  # List to store tracking data
    self.classes = self.get_indices(classes)
    while self.cap.isOpened():
        ret, frame = self.cap.read()
        if not ret:
            print("Error reading video stream or file")
            break

        results = self.model(frame)
        for result in results:
            boxes = result.boxes.cpu().numpy()
            # Store each detected object's data in a dictionary
            for i, box in enumerate(boxes.xyxy):
                obj_data = {
                    'bbox': box,
                    'confidence': boxes.conf[i],
                    'class_id': boxes.classes[i]
                }
                tracked_objects.append(obj_data)

    return tracked_objects  # Return the list of dictionaries
```

This approach simplifies data handling and makes it more straightforward to use the tracking data in your sub-file for further analysis or visualization. Feel free to adjust the structure of the `obj_data` dictionary based on the specific data you need for your project. 🚀

Hope this helps! Let us know if you have any more questions.

**Comment by anishka07** [comment]
Hi thank you for replying! I was wondering if you could show me how I can use that data in my sub file for tracking and heatmap generation. This us the code snippet of my sub-file.
`if __name__ == "__main__":
    classes = ["person","car","motorcycle","airplane"]
    tracker_obj = VehicleTracker(video_path=video_path)`

**Comment by anishka07** [comment]
Also, @glenn-jocher, I found out that you have to use cls instead of classes. But thanks though, this helped me a lot. The only thing left to do is to use the extracted data to track the objects and also generate heatmaps. Can you please help me with that? Thank you!
