### ISSUE TITLE
Adding agnostic_nms to auto_annotate method

### ISSUE THREAD

**Issue by Davisonyeas** [ultralytics/ultralytics#8674]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

While passing the yolov8 detection model. It will be good to be able to set the agnostic_nms=True. So that it can prevent multiple predictions on the same instance of an object while the sam_model is auto-annotating based on the detection model

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Davisonyeas hello! 👋

Thank you for your suggestion regarding the addition of `agnostic_nms` to the `auto_annotate` method. It's great to see your willingness to contribute by submitting a PR!

Integrating `agnostic_nms=True` into the `auto_annotate` method sounds like a valuable enhancement. This feature would indeed help in reducing duplicate detections on the same object instance, making the auto-annotation process more efficient and accurate.

Here's a brief example of how you might adjust the method signature to include `agnostic_nms`:

```python
def auto_annotate(model, images, agnostic_nms=True):
    # Your implementation here
```

And then, within your method, you can utilize the `agnostic_nms` flag accordingly to refine the detection results.

We're looking forward to your PR! If you need any guidance or have further questions as you work on this, please feel free to reach out.

Happy coding! 😊
