### ISSUE TITLE
Resume training issue

### ISSUE THREAD

**Issue by devendraswamy** [ultralytics/ultralytics#868]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Issue with Resuming Model training -

 I am training a model for 1000 epochs with 100 patience. Unfortunately, my aws session connection got lost.SO, I resume training from the last epoch.TO my observation, the delta value for the patience has overwriten with "0" and the class early stopping is not checking the best MaP value before resume instead overwriten with new map value.
 
Also once we resume the training , the results are logged into new save_dir.

Need assistance to resume  my training without overwriting the values and fetch the last values from results.csv . Thank you in advance.   

### Environment

Ultralytics YOLOv8.0.25 🚀 Python-3.7.13 torch-1.7.1+cu92 CUDA:0 (Tesla K80, 11441MiB)
linux
python3.7.13

### Minimal Reproducible Example

    def __call__(self, epoch, fitness):
        """
        Check whether to stop training

        Args:
            epoch (int): Current epoch of training
            fitness (float): Fitness value of current epoch

        Returns:
            bool: True if training should stop, False otherwise
        """
        print("Calling EarlyStopping")
        if fitness is None:  # check if fitness=None (happens when val=False)
            return False
        if fitness >= self.best_fitness:  # >= 0 to allow for early zero-fitness stage of training
            self.best_epoch = epoch
            self.best_fitness = fitness
        #print(best_fitness ,"best_fitness")
        #print(fitness ,"fitness")
        delta = epoch - self.best_epoch  # epochs without improvement
        print(delta , "Delta value ********")
        self.possible_stop = delta >= (self.patience - 1)  # possible stop may occur next epoch
        stop = delta >= self.patience  # stop training if patience exceeded
        if stop:
            LOGGER.info(f'Stopping training early as no improvement observed in last {self.patience} epochs. '
                        f'Best results observed at epoch {self.best_epoch}, best model saved as best.pt.\n'
                        f'To update EarlyStopping(patience={self.patience}) pass a new patience value, '
                        f'i.e. `patience=300` or use `patience=0` to disable EarlyStopping.')
        return stop

### Are you willing to submit a PR?
NO
- [x] I'd like to help by submitting a PR!

**Comment by devendraswamy** [comment]
Any one can Please reply on this?

**Comment by Laughing-q** [comment]
@devendraswamy 
can you provide your resume training command?

**Comment by devendraswamy** [comment]
@Laughing-q 

BOFORE RESUME CMD:-  yolo task=detect mode=train model=yolov8n.pt" data="/home/ec2-user/data2/data/ultralytics_v1/datasets/ASB_V26/train_ASB_03022023.yaml" iou=0.45 epochs=1000 imgsz=640 device=0 name=ASB_V26 batch=16 patience=100 augment=True project=/home/ec2-user/data2/data/ultralytics/runs/detect/BOTTOM/ 


RESUME CMD :- yolo task=detect mode=train model="/home/ec2-user/data2/data/ultralytics/runs/detect/BOTTOM/ASB_V26/weights/last.pt" data="/home/ec2-user/data2/data/ultralytics_v1/datasets/ASB_V26/train_ASB_03022023.yaml" iou=0.45 epochs=1000 imgsz=640 device=0 name=ASB_V26 batch=16 patience=100 augment=True project=/home/ec2-user/data2/data/ultralytics/runs/detect/BOTTOM/ resume=True


> @devendraswamy can you provide your resume training command?

**Comment by Laughing-q** [comment]
@devendraswamy hi the `save_dir` issue has been solved in this PR which would be merged later today. :) #940 
about the patience, as the current code is not remembering the `best_epoch` in stopper so it has to be reset in your case...

**Comment by sidb236** [comment]
@Laughing-q Hi, I am facing the same issue today. Has the issue been solved in the PR merged?

**Comment by Laughing-q** [comment]
@sidb236 `save_dir` has been fixed, resume is re-using the existed `save_dir` now.

**Comment by sidb236** [comment]
@Laughing-q 
The command I have used to resume training is:
`!yolo task=detect mode=train model='/gdrive/MyDrive/ultralytics/runs/detect/train12/weights/last.pt' data='/gdrive/MyDrive/yolov5/dataset/data.yaml' epochs=300 imgsz=640 resume=True`

![image](https://user-images.githubusercontent.com/44775711/218681379-a9b52359-acae-4553-804c-e1fb3daa2052.png).

In the command I have used epochs = 300, I have already trained it for 100 epochs but I am getting the error as to model trained for 100 epochs, nothing to resume. Please help. Where am I going wrong?

**Comment by Laughing-q** [comment]
@sidb236 hi looks like your `last.pt` is from a finished training process, so the info .i.e epochs has been removed. You can't resume a model which is finished.
