### ISSUE TITLE
break when putting object_counter class functions in while loop

### ISSUE THREAD

**Issue by shaimaahamam** [ultralytics/ultralytics#8682]

**Comment by glenn-jocher** [comment]
@shaimaahamam hello! It seems like you're encountering an issue when trying to use `object_counter` class functions within a while loop. To better assist you, could you please provide a bit more context or share a snippet of your code where the issue occurs? This will help us understand the problem more clearly and offer a precise solution. 😊

In general, ensure your while loop has a proper condition to prevent infinite loops, and check that all objects and functions are correctly defined and accessible within the loop. Here's a simple example of how to structure a loop with function calls:

```python
class ObjectCounter:
    def count(self):
        # Your counting logic here
        return 42

object_counter = ObjectCounter()

while some_condition:
    count = object_counter.count()
    print(f"Object count: {count}")
    # Update some_condition to eventually break the loop
```

Looking forward to your response!
