### ISSUE TITLE
Tracking start

### ISSUE THREAD

**Issue by AlexandreWu** [ultralytics/ultralytics#8684]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello i have just start coding with yolov8 to track luggage, backpack, handpack and person but i wanted to know how to save those data in a database like SQL or mongo and in a python list too. I have just started with the code below:

from ultralytics import YOLO

model = YOLO('yolov8n.pt')

results = model.track(source='suitcase_2.mp4', show=True, tracker="bytetrack.yaml", classes = [0,28,24,26], save=True, name='test')

I have seen also multiple code whitch make a lot of loop should i make loop too or can i stay with this start.
Thx for the help

**Comment by glenn-jocher** [comment]
@AlexandreWu hello! It's great to see you're using YOLOv8 for tracking objects. To save the tracking data into a database and a Python list, you can process the `results` object returned by the `model.track()` method. Here's a simplified example to get you started:

```python
from ultralytics import YOLO

# Initialize the model
model = YOLO('yolov8n.pt')

# Run tracking
results = model.track(source='suitcase_2.mp4', show=True, tracker="bytetrack.yaml", classes=[0, 28, 24, 26], save=True, name='test')

# Initialize an empty list to store tracking data
tracking_data = []

# Process results
for result in results:
    for box in result.boxes:
        # Extract tracking information
        track_id = box.id.item()
        class_id = box.cls.item()
        x, y, w, h = box.xywh
        conf = box.conf.item()
        
        # Append to the Python list
        tracking_data.append((track_id, class_id, x, y, w, h, conf))
        
        # Here you can also insert the data into your database
        # For SQL, it would be something like:
        # cursor.execute("INSERT INTO tracking (track_id, class_id, x, y, w, h, conf) VALUES (?, ?, ?, ?, ?, ?, ?)", (track_id, class_id, x, y, w, h, conf))
        # For MongoDB, it would be something like:
        # collection.insert_one({"track_id": track_id, "class_id": class_id, "bbox": [x, y, w, h], "conf": conf})

# Don't forget to commit your changes if you're using SQL
# connection.commit()

# Now, `tracking_data` contains all your tracking information
print(tracking_data)
```

This example demonstrates how to extract tracking information from each detected object and store it in a Python list. You can also insert this data into a database using SQL or MongoDB commands as shown in the comments.

Regarding loops, the `for result in results:` loop is necessary to process each frame's results when tracking objects in a video. The inner loop `for box in result.boxes:` processes each detected object in the frame. This structure is efficient and should serve your purpose well.

Hope this helps! If you have any more questions, feel free to ask. 😊

**Comment by glenn-jocher** [comment]
@AlexandreWu That's great to hear! 😊 If you have any more questions or need further assistance as you continue with your project, don't hesitate to reach out. Happy coding!

**Comment by AlexandreWu** [comment]
Hello, got another question can we save also the frame into my data base like from which frame is one information. 
thanks

**Comment by glenn-jocher** [comment]
@AlexandreWu hello! Yes, you can save the frame information along with your tracking data. Each `result` object contains frame metadata. Here's a quick example to help you get started:

```python
for i, result in enumerate(results):
    frame_number = i  # This will be your frame index
    for box in result.boxes:
        track_id = box.id.item()
        class_id = box.cls.item()
        # ... extract other box properties

        # Now, in addition to track_id, class_id, etc., 
        # you can also save 'frame_number' to your database
```

Make sure to adjust your database schema accordingly to include a column or field for storing the frame number. Let me know if you have any more questions. Happy coding! 😊
