### ISSUE TITLE
Get model information 

### ISSUE THREAD

**Issue by martin0496** [ultralytics/ultralytics#8688]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi all , 

After training a custom yolov8 and getting the file best.pt. 
how to get the metadata of the model from this file ? ( image size , number of channels , class labels , stretch , norm_mean , norm_std) 

Thank you

**Comment by glenn-jocher** [comment]
@martin0496 hello! 😊

To retrieve model metadata from your `best.pt` file, you can use the following code snippet:

```python
from ultralytics import YOLO

# Load your trained model
model = YOLO('path/to/best.pt')

# Access model metadata
metadata = model.metadata
print(metadata)
```

This will print out the metadata including image size, number of channels, class labels, etc. If you need to access specific attributes, you can do so directly, for example, `model.metadata['imgsz']` for the image size.

Hope this helps! Let us know if you have any more questions.

**Comment by martin0496** [comment]
@glenn-jocher Thank you for your reply. 

I tried this function but I get this error: 

  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'YOLO' object has no attribute 'metadata'

**Comment by martin0496** [comment]
Hi @glenn-jocher 

I am still not able to get the metadata with this method. Can you please help me with this ? 

Thank you in advance

**Comment by glenn-jocher** [comment]
Hi @martin0496,

I'm sorry for the confusion earlier. It seems there was a misunderstanding regarding accessing model metadata directly from the `YOLO` object. Here's a corrected approach to extract the information you're looking for:

```python
from ultralytics import YOLO

# Load your trained model
model = YOLO('path/to/best.pt')

# Accessing specific model attributes
img_size = model.imgsz  # Image size
num_classes = len(model.names)  # Number of classes
class_labels = model.names  # Class labels

print(f"Image Size: {img_size}")
print(f"Number of Classes: {num_classes}")
print(f"Class Labels: {class_labels}")
```

This should give you the image size, number of classes, and class labels directly. For other attributes like `norm_mean` and `norm_std`, these are typically set during training and might not be directly accessible from the model object. They are often part of the dataset preprocessing steps.

Let me know if this helps or if you need further assistance! 😊
