### ISSUE TITLE
Masks numpy() not returning ndarray

### ISSUE THREAD

**Issue by charlielito** [ultralytics/ultralytics#8690]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

According to the documentation https://docs.ultralytics.com/modes/predict/#masks or https://docs.ultralytics.com/reference/engine/results/#ultralytics.engine.results.Masks  the `numpy` method of the object Masks should return the tensor as a numpy array. Nonetheless, the return object is of type `<class 'ultralytics.engine.results.Masks'>` which is very confusing. The `cpu` returns also a `<class 'ultralytics.engine.results.Masks'>` which is also is a little bit confusing since you'll expect a torch tensor

### Environment

Ultralytics YOLOv8.1.23 🚀 Python-3.8.18 torch-2.2.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3070 Laptop GPU, 7974MiB)
Setup complete ✅ (8 CPUs, 15.3 GB RAM, 697.8/778.0 GB disk)

OS                  Linux-6.0.12-76060012-generic-x86_64-with-glibc2.17
Environment         Linux
Python              3.8.18
Install             git
RAM                 15.32 GB
CPU                 11th Gen Intel Core(TM) i7-11370H 3.30GHz
CUDA                12.1

matplotlib          ✅ 3.7.1>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 9.5.0>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.0>=1.4.1
torch               ✅ 2.2.0>=1.8.0
torchvision         ✅ 0.17.0>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Minimal Reproducible Example

![car](https://github.com/ultralytics/ultralytics/assets/8033598/02bf992a-e636-4c87-8f34-568bbe4d7fd5)

```python
from ultralytics import YOLO

model = YOLO("yolov8s-seg.pt")

result = model("car.png", verbose=False)[0]
masks_numpy = result.masks.cpu().numpy()
masks_cpu = result.masks.cpu()
print(f".numpy() return type: {type(masks_numpy)}")
print(f".cpu() return type: {type(masks_cpu)}")
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@charlielito Masks has attributes xy and xyn, which are lists of tensors. The above methods will convert those tensors to numpy arrays, i.e.

```
type(result.masks.xy[0])
Out[5]: numpy.ndarray
```

**Comment by charlielito** [comment]
The documentation is missleading, since it says explicitly that that method returns a numpy array...

**Comment by glenn-jocher** [comment]
@charlielito hey there! 😄 Thanks for pointing this out. You're right, the `.numpy()` method's naming might suggest it directly returns a numpy array of the masks. However, it actually converts the tensors within the `Masks` object to numpy arrays. To access these, you'd look into the `xy` or `xyn` attributes of the `Masks` object after calling `.numpy()`. Here's a quick example:

```python
masks_numpy = result.masks.numpy()
first_mask_array = masks_numpy.xy[0]  # This is a numpy array
```

We'll make sure to clarify this in the documentation. Thanks for helping us improve! 🚀
