### ISSUE TITLE
Error while using Yolov8 with Flower framework

### ISSUE THREAD

**Issue by Pedrolmsantos** [ultralytics/ultralytics#8695]
- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi There,

I'm currently working on a project that involves creating a YOLOv8 model in a federated environment. I'm testing the Flower framework as the basis for this.

I've encountered the following error while testing my code: 
![fed](https://github.com/ultralytics/ultralytics/assets/79088138/f4b503a1-ec01-45b5-9443-e1164f852382)

I'll provide the relevant part of the code, which I use to update and get parameters from the model..

`def get_parameters(model: YOLO) -> List[np.ndarray]:
    params = [param.data.cpu().numpy()
    for param in model.parameters()]
    return params

def set_parameters(model: YOLO, parameters: List[np.ndarray]) -> None:
    for i, param in enumerate(model.parameters()):
        param_ = torch.from_numpy(parameters[i]).cuda()
        param.data.copy_(param_)
`

If you need any more information, please feel free to ask!

**Comment by glenn-jocher** [comment]
@Pedrolmsantos hello there! 👋

Thanks for reaching out and for providing detailed information about the issue you're encountering with integrating YOLOv8 and the Flower framework. From the code snippet and the error screenshot you've shared, it seems like there might be a mismatch or an issue with how the model parameters are being handled between updates.

One potential issue could be related to the device on which the parameters are being loaded. If your environment is set up to use GPUs, ensure that the parameters are correctly transferred to the same device as your model. Here's a slightly modified version of your `set_parameters` function that ensures the parameters are loaded onto the correct device:

```python
def set_parameters(model: YOLO, parameters: List[np.ndarray]) -> None:
    for i, param in enumerate(model.parameters()):
        param_ = torch.from_numpy(parameters[i]).to(param.device)
        param.data.copy_(param_)
```

This modification uses `.to(param.device)` to ensure that the new parameters are loaded onto the same device as the existing model parameters.

If this doesn't resolve the issue, could you please provide more details about the error message you're seeing? That might help in pinpointing the exact cause of the problem.

Feel free to share any additional information or questions you might have! 😊
