### ISSUE TITLE
> 嗨，你好！👋

### ISSUE THREAD

**Issue by AliasChenYi** [ultralytics/ultralytics#8698]
> 嗨，你好！👋
> 
> 感谢您伸出援手并试用 YOLOv8 Pose 模型。很高兴听到您的努力！如果您没有达到预期的结果，需要检查的几个常见方面包括：
> 
> * **数据集完整性：**确保 COCO 数据集已正确下载和访问。
> * **培训配置：**仔细检查您的训练配置 （） 是否与用于报告结果的配置匹配。`yolov8n-pose.yaml`
> * **环境：**确保您的训练环境（软件版本、硬件）设置正确。
> 
> 下面是一个快速片段，以确保您的训练设置正确无误：
> 
> ```python
> from ultralytics import YOLO
> 
> model = YOLO('yolov8n-pose.yaml')
> model.train(data='coco.yaml', epochs=100, imgsz=640)
> ```
> 
> 如果一切看起来都井井有条，但您仍然面临问题，您能否分享有关您的设置和您获得的确切结果的更多详细信息？这有助于更有效地查明问题。
> 
> 感谢您的耐心等待，并期待帮助您充分利用 YOLOv8 Pose！🚀
1. Data set: As for the data set you mentioned, the data set I used is the coco-pose.yaml file you officially gave me. In addition, relevant pictures and comments are also made according to what you said, and then it can run normally.
2.  The training configuration and environment are OK. So I am very upset at the moment, all this seems to be in good order, but it is very different from the result you give.

I'm a little suspicious of my hyper-parameter Settings, and I don't know how you set them when you run, but here's my list of parameters:

```python
task: pose
mode: train
model: ultralytics/cfg/models/v8pose/yolov8-pose.yaml
data: ultralytics/cfg/datasets/coco-pose.yaml
epochs: 300
time: null
patience: 50
batch: 300
imgsz: 640
save: true
save_period: -1
cache: true
device: '0'
workers: 8
project: runs/train
name: yolov8s-pose
exist_ok: false
pretrained: true
optimizer: SGD
verbose: false
seed: 0
deterministic: true
single_cls: true
rect: false
cos_lr: false
close_mosaic: 10
resume: false
amp: true
fraction: 1.0
profile: false
freeze: null
multi_scale: false
overlap_mask: true
mask_ratio: 4
dropout: 0.0
val: true
split: val
save_json: false
save_hybrid: false
conf: null
iou: 0.7
max_det: 300
half: false
dnn: false
plots: true
source: null
vid_stride: 1
stream_buffer: false
visualize: false
augment: false
agnostic_nms: false
classes: null
retina_masks: false
embed: null
show: false
save_frames: false
save_txt: false
save_conf: false
save_crop: false
show_labels: true
show_conf: true
show_boxes: true
line_width: null
format: torchscript
keras: false
optimize: false
int8: false
dynamic: false
simplify: false
opset: null
workspace: 4
nms: false
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 7.5
cls: 0.5
dfl: 1.5
pose: 12.0
kobj: 1.0
label_smoothing: 0.0
nbs: 64
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.0
copy_paste: 0.0
auto_augment: randaugment
erasing: 0.4
crop_fraction: 1.0
cfg: null
tracker: botsort.yaml
save_dir: runs/train/yolov8s-pose

```

The following code is the code I trained:

```python
import warnings
warnings.filterwarnings('ignore')
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO('ultralytics/cfg/models/v8pose/yolov8-pose.yaml')
    model.load('pre-training/yolov8s-pose.pt') 
    model.train(data=r'ultralytics/cfg/datasets/coco-pose.yaml',
                cache=True,
                imgsz=640,
                epochs=300,
                single_cls=True, 
                batch=300,
                close_mosaic=10,
                workers=8,
                device='0',
                optimizer='SGD',
                amp=True,  
                project='runs/train',
                name='yolov8s-pose',
                )
```

Recently, I have been looking for the reason, but no results, so I am really troubled, why there is such a big difference with the results you gave me, I hope you can give me some help, looking forward to your reply again.

_Originally posted by @AliasChenYi in https://github.com/ultralytics/ultralytics/issues/1915#issuecomment-1979918310_

**Comment by glenn-jocher** [comment]
嗨， @AliasChenYi 👋，

首先，非常感谢您提供了详细的配置和训练代码，这对于我们理解您的情况非常有帮助。从您提供的信息来看，您的设置和训练过程看起来都配置得很好。

关于超参数设置，您的配置与我们的推荐设置相当接近。但是，我注意到您使用了`single_cls=True`，这意味着您将所有类别视为一个单一类别进行训练。这在某些特定场景下是有用的，但如果您的目标是在多类别的姿态估计任务上达到最佳性能，这可能会限制模型的表现。除非您的任务确实是单类别的，否则建议您考虑将此设置为`False`。

此外，您的`batch`大小设置为300，这可能对于大多数硬件来说都相当大。除非您有足够的GPU内存来支持这样的批量大小，否则可能需要减小批量大小以避免内存溢出错误。通常，我们建议根据您的硬件配置适当调整批量大小。

如果在调整上述设置后仍然遇到问题，建议您尝试以下步骤进行故障排除：

1. **验证数据集**：确保`coco-pose.yaml`文件中指定的数据路径正确无误，并且数据集已经按照预期格式准备好。
2. **模型预热**：在开始大规模训练之前，先用较小的数据集或较少的epochs进行预训练，以验证模型是否能够学习和改进。
3. **日志和可视化**：利用TensorBoard等工具，监控训练过程中的损失和性能指标，以便及时发现潜在问题。

希望这些建议能够帮助您解决问题。如果您有任何进一步的问题或需要更多帮助，请随时回复。我们期待看到您使用YOLOv8 Pose模型取得成功！🚀

**Comment by AliasChenYi** [comment]
对于姿态识别任务中只检测人物 不就是只识别人物的吗，所以我single_cls就设置为了True，非常感谢你的回答，我现在对代码进行修改一下，然后再训练一遍，非常的感谢你的回答，如果还有其他建议还望能继续告诉我，这对我刚入门学习yolo真的帮助很大。

---原始邮件---
发件人: "Glenn ***@***.***&gt;
发送时间: 2024年3月6日(周三) 晚上6:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ultralytics/ultralytics] &gt; 嗨，你好！👋 (Issue #8698)




 
嗨， @AliasChenYi 👋，
 
首先，非常感谢您提供了详细的配置和训练代码，这对于我们理解您的情况非常有帮助。从您提供的信息来看，您的设置和训练过程看起来都配置得很好。
 
关于超参数设置，您的配置与我们的推荐设置相当接近。但是，我注意到您使用了single_cls=True，这意味着您将所有类别视为一个单一类别进行训练。这在某些特定场景下是有用的，但如果您的目标是在多类别的姿态估计任务上达到最佳性能，这可能会限制模型的表现。除非您的任务确实是单类别的，否则建议您考虑将此设置为False。
 
此外，您的batch大小设置为300，这可能对于大多数硬件来说都相当大。除非您有足够的GPU内存来支持这样的批量大小，否则可能需要减小批量大小以避免内存溢出错误。通常，我们建议根据您的硬件配置适当调整批量大小。
 
如果在调整上述设置后仍然遇到问题，建议您尝试以下步骤进行故障排除：
  
验证数据集：确保coco-pose.yaml文件中指定的数据路径正确无误，并且数据集已经按照预期格式准备好。
 
模型预热：在开始大规模训练之前，先用较小的数据集或较少的epochs进行预训练，以验证模型是否能够学习和改进。
 
日志和可视化：利用TensorBoard等工具，监控训练过程中的损失和性能指标，以便及时发现潜在问题。
  
希望这些建议能够帮助您解决问题。如果您有任何进一步的问题或需要更多帮助，请随时回复。我们期待看到您使用YOLOv8 Pose模型取得成功！🚀

**Comment by glenn-jocher** [comment]
嗨 @AliasChenYi 👋，

很高兴看到您积极调整代码并重新训练！对于只检测人物的姿态识别任务，`single_cls=True` 的确是合理的选择。您的理解完全正确，这样设置可以专注于人物的检测和姿态估计。

如果您在调整后仍有疑问或需要进一步的帮助，随时欢迎回来询问。祝您训练顺利，期待您在使用YOLOv8 Pose模型上取得出色的成果！🚀

再次感谢您的积极反馈，您的进步也是我们前进的动力！

**Comment by AliasChenYi** [comment]
Hello, I have a question, is your pre-training obtained after pre-training all the pictures on coco2017(118287)? I followed the download link you gave me, and only 56,599 were used for pose estimation. Finally, I would like to ask you to look at the image below, I highlighted whether the pre-trained weight file. Thank you very much for your patient answer. It really helped me a lot.



&nbsp;


散了流年﹋淡了曾经
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Glenn ***@***.***&gt;; 
发送时间: 2024年3月7日(星期四) 凌晨4:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ultralytics/ultralytics] &gt; 嗨，你好！👋 (Issue #8698)





 
嗨 @AliasChenYi 👋，
 
很高兴看到您积极调整代码并重新训练！对于只检测人物的姿态识别任务，single_cls=True 的确是合理的选择。您的理解完全正确，这样设置可以专注于人物的检测和姿态估计。
 
如果您在调整后仍有疑问或需要进一步的帮助，随时欢迎回来询问。祝您训练顺利，期待您在使用YOLOv8 Pose模型上取得出色的成果！🚀
 
再次感谢您的积极反馈，您的进步也是我们前进的动力！

**Comment by glenn-jocher** [comment]
@AliasChenYi hello! 😊

Yes, the pre-training you mentioned is indeed based on a subset of the COCO2017 dataset, specifically tailored for pose estimation tasks, which includes 56,599 images. This focused approach helps in optimizing the model's performance for pose-related detections.

Regarding the pre-trained weight file you highlighted, it seems like you're on the right track! If you're referring to the file obtained from our provided download link, that's exactly what you should use for initializing your training to leverage the benefits of pre-training on pose estimation tasks.

If there's anything more you need or further questions, feel free to ask. Happy to help, and best of luck with your training! 🚀
