### ISSUE TITLE
How to modify yolov8 prediction confidence to retain two decimal points

### ISSUE THREAD

**Issue by RRRRxxxx** [ultralytics/ultralytics#8705]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How do I modify the yolov8 prediction confidence to retain two decimal points when I train my own data set?
<img width="402" alt="图片1" src="https://github.com/ultralytics/ultralytics/assets/141219294/bc60ad52-4cc2-4a70-8f00-f66c14463554">

**Comment by glenn-jocher** [comment]
@RRRRxxxx hello! 👋

To adjust the prediction confidence output to retain two decimal points, you can format the confidence score as a string with the desired precision. Here's a quick example assuming you're processing the model's output in Python:

```python
# Assuming 'confidences' is a list of confidence scores from YOLOv8 predictions
formatted_confidences = [f"{conf:.2f}" for conf in confidences]

# Now 'formatted_confidences' will have confidence scores as strings with two decimal points
print(formatted_confidences)
```

This way, you can control the number of decimal points displayed in any output or logging mechanism you're using. If you're directly modifying the source code, look for the part where predictions are printed or logged and apply similar formatting.

Hope this helps! Let us know if you have any more questions. 😊
