### ISSUE TITLE
Generate Precision, Accuracy, Recall, F1 Score for Every Class YOLOv8

### ISSUE THREAD

**Issue by eddmar1993** [ultralytics/ultralytics#8709]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am new to this field. I am training a YOLOv8 model for posture detection in pig. I used Google Colab for the training and this is the code I used "!yolo task=detect mode=train model=yolov8s.pt data={dataset.location}/data.yaml epochs=50 imgsz=800". My question is, how to generate Precision, Accuracy, Recall, and F1 Score for every class in every epoch? After the training, I would also generate these parameters using Validation and Test datasets. The data should be saved in CSV format. 

I have 3 classes (lying, sitting, and standing). My database can be downloaded from this link: 

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="fO9YXbyncsl6s1IUimKy")
project = rf.workspace("sunchon-national-university").project("pigs-posture-detection")
version = project.version(1)
dataset = version.download("yolov8")

Thank you very much.

**Comment by eddmar1993** [comment]
> 👋 Hello @eddmar1993, thank you for your interest in Ultralytics YOLOv8 🚀! We recommend a visit to the [Docs](https://docs.ultralytics.com) for new users where you can find many [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples and where many of the most common questions may already be answered.
> 
> If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us debug it.
> 
> If this is a custom training ❓ Question, please provide as much information as possible, including dataset image examples and training logs, and verify you are following our [Tips for Best Training Results](https://docs.ultralytics.com/yolov5/tutorials/tips_for_best_training_results/).
> 
> Join the vibrant [Ultralytics Discord](https://ultralytics.com/discord) 🎧 community for real-time conversations and collaborations. This platform offers a perfect space to inquire, showcase your work, and connect with fellow Ultralytics users.
> 
> ## Install
> Pip install the `ultralytics` package including all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/).
> 
> ```shell
> pip install ultralytics
> ```
> 
> ## Environments
> YOLOv8 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):
> 
> * **Notebooks** with free GPU: [![Run on Gradient](https://camo.githubusercontent.com/7c47520d799373030a5bc16f03365634982e82a5547167167cb1e00bb972d640/68747470733a2f2f6173736574732e706170657273706163652e696f2f696d672f6772616469656e742d62616467652e737667)](https://console.paperspace.com/github/ultralytics/ultralytics) [![Open In Colab](https://camo.githubusercontent.com/f5e0d0538a9c2972b5d413e0ace04cecd8efd828d133133933dfffec282a4e1b/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/1398db766d8ca60e6f296aac9ac429e344705c6c2c7e1ceb024230aac69fd6be/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/ultralytics/yolov8)
> * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
> * **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) [![Docker Pulls](https://camo.githubusercontent.com/3aba317f5cc4948ed3007a4dcb5a4dfbdd499ca824993974b713eb1c0967104e/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f756c7472616c79746963733f6c6f676f3d646f636b6572)](https://hub.docker.com/r/ultralytics/ultralytics)
> 
> ## Status
> [![Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg)](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule)
> 
> If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing. CI tests verify correct operation of all YOLOv8 [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) on macOS, Windows, and Ubuntu every 24 hours and on every commit.

Thank you for an immediate response.
Yes. This is a custom training. Below is the sample image of a predicted image. 
![image](https://github.com/ultralytics/ultralytics/assets/148829286/c7bb4f97-7bd0-4d02-906e-93525f73ed35)

Precision, Recall, Accuracy, and F1 score are generated but in graph form as shown in the image below. I also want the results per class in CSV.
![image](https://github.com/ultralytics/ultralytics/assets/148829286/630800ab-cac4-4331-a459-e775796a80d0)

The results in csv format contain the overall, not per class as shown below.
![image](https://github.com/ultralytics/ultralytics/assets/148829286/7e326825-dbb1-4f37-92ec-af14990daa37)

**Comment by glenn-jocher** [comment]
Hello @eddmar1993 👋, glad to see you're making progress with your custom training on YOLOv8 for posture detection in pigs! 🐖

To generate Precision, Accuracy, Recall, and F1 Score for every class in every epoch and save them in CSV format, you can utilize the `--save-csv` flag during your training or validation process. This will output a detailed CSV file including metrics for each class. Here's how you can modify your training command to include this:

```shell
!yolo task=detect mode=train model=yolov8s.pt data={dataset.location}/data.yaml epochs=50 imgsz=800 --save-csv
```

For validation and testing to generate these metrics in CSV format, you can use a similar approach:

```shell
!yolo task=detect mode=val model=yolov8s.pt data={dataset.location}/data.yaml --save-csv
```

If the `--save-csv` option does not provide the per-class breakdown as expected, you might need to write a custom script to parse the logs or the output JSON (if available) to extract these metrics per class and save them to a CSV file. The JSON files generated during validation contain detailed metrics that can be parsed for this purpose.

For further assistance and real-time discussions, don't hesitate to join our [Ultralytics Discord](https://ultralytics.com/discord) community. Many users share their experiences and solutions that might be helpful for your case.

Keep up the great work, and we're excited to see your project on posture detection in pigs develop! 🚀

**Comment by eddmar1993** [comment]
> Hello @eddmar1993 👋, glad to see you're making progress with your custom training on YOLOv8 for posture detection in pigs! 🐖
> 
> To generate Precision, Accuracy, Recall, and F1 Score for every class in every epoch and save them in CSV format, you can utilize the `--save-csv` flag during your training or validation process. This will output a detailed CSV file including metrics for each class. Here's how you can modify your training command to include this:
> 
> ```shell
> !yolo task=detect mode=train model=yolov8s.pt data={dataset.location}/data.yaml epochs=50 imgsz=800 --save-csv
> ```
> 
> For validation and testing to generate these metrics in CSV format, you can use a similar approach:
> 
> ```shell
> !yolo task=detect mode=val model=yolov8s.pt data={dataset.location}/data.yaml --save-csv
> ```
> 
> If the `--save-csv` option does not provide the per-class breakdown as expected, you might need to write a custom script to parse the logs or the output JSON (if available) to extract these metrics per class and save them to a CSV file. The JSON files generated during validation contain detailed metrics that can be parsed for this purpose.
> 
> For further assistance and real-time discussions, don't hesitate to join our [Ultralytics Discord](https://ultralytics.com/discord) community. Many users share their experiences and solutions that might be helpful for your case.
> 
> Keep up the great work, and we're excited to see your project on posture detection in pigs develop! 🚀

Hi, I tried this, but it is not working. The "save-csv- argument is not valid, as shown in the image below. I tried the "save=True" argument, the training ran successfully but the csv data are similar to the  previous one. Not per class. Thank you.
![image](https://github.com/ultralytics/ultralytics/assets/148829286/1e10522a-83a0-47b3-8f42-0c882a417054)

**Comment by glenn-jocher** [comment]
Hey @eddmar1993! 🌟 My apologies for the confusion earlier. It seems there was a mix-up with the `--save-csv` flag. Currently, YOLOv8 doesn't directly support exporting per-class metrics to CSV via a single flag in the CLI. 

For now, you might consider parsing the `.json` files generated during validation for detailed metrics. Here's a quick Python snippet to help you extract and save these metrics per class into a CSV:

```python
import json
import csv

# Load the JSON file
with open('results.json') as f:
    data = json.load(f)

# Open a CSV file for writing
with open('metrics_per_class.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    # Write the header
    writer.writerow(['Class', 'Precision', 'Recall', 'F1-score', 'Accuracy'])

    # Write the metrics for each class
    for cls, metrics in data['metrics'].items():
        writer.writerow([cls, metrics['precision'], metrics['recall'], metrics['f1-score'], metrics['accuracy']])
```

Make sure to replace `'results.json'` with the path to your actual JSON file containing the validation results. This script assumes your JSON structure contains a `metrics` dictionary with per-class metrics. Adjust the keys accordingly based on your actual JSON structure.

For more tailored support and to share your progress, consider joining our [Discord community](https://ultralytics.com/discord). We're here to help! 🚀

**Comment by eddmar1993** [comment]
> Hey @eddmar1993! 🌟 My apologies for the confusion earlier. It seems there was a mix-up with the `--save-csv` flag. Currently, YOLOv8 doesn't directly support exporting per-class metrics to CSV via a single flag in the CLI.
> 
> For now, you might consider parsing the `.json` files generated during validation for detailed metrics. Here's a quick Python snippet to help you extract and save these metrics per class into a CSV:
> 
> ```python
> import json
> import csv
> 
> # Load the JSON file
> with open('results.json') as f:
>     data = json.load(f)
> 
> # Open a CSV file for writing
> with open('metrics_per_class.csv', 'w', newline='') as file:
>     writer = csv.writer(file)
>     # Write the header
>     writer.writerow(['Class', 'Precision', 'Recall', 'F1-score', 'Accuracy'])
> 
>     # Write the metrics for each class
>     for cls, metrics in data['metrics'].items():
>         writer.writerow([cls, metrics['precision'], metrics['recall'], metrics['f1-score'], metrics['accuracy']])
> ```
> 
> Make sure to replace `'results.json'` with the path to your actual JSON file containing the validation results. This script assumes your JSON structure contains a `metrics` dictionary with per-class metrics. Adjust the keys accordingly based on your actual JSON structure.
> 
> For more tailored support and to share your progress, consider joining our [Discord community](https://ultralytics.com/discord). We're here to help! 🚀

Hi! I ran these codes but my JSON file does not contain the metrics. See the image attached.
![image](https://github.com/ultralytics/ultralytics/assets/148829286/a3f56d99-b95d-43d8-9178-ad01dcffc263)

**Comment by glenn-jocher** [comment]
Hey @eddmar1993! 😊 It looks like the JSON file might not be the one containing the detailed metrics from your training/validation sessions. Usually, YOLOv8 generates a `results.json` file after validation that includes detailed metrics. If it's not present or doesn't contain the expected data, it's possible that the validation step might need to be rerun with the correct settings to generate this file.

Could you double-check if you're looking at the correct JSON file generated post-validation? If you're still facing issues, running a validation step like this should help generate the detailed metrics:

```shell
!yolo task=detect mode=val model=path/to/your/model.pt data=path/to/your/data.yaml
```

This command should produce a `results.json` in your working directory with the metrics. If you're still stuck, feel free to share more details or reach out on our [Discord](https://ultralytics.com/discord) for quicker assistance. We're here to help you get this sorted! 🚀

**Comment by curtis18** [comment]
I have the similar issue that cannot find the Recall, F1 Score for every class. I use python code results = model.val(data=yaml_path, conf=0.001, iou=iou, save_json=True, split='val') to retrieve the json file.

**Comment by glenn-jocher** [comment]
Hi @curtis18, to get Recall and F1 Score for each class, you can parse the `results.json` file generated during validation. If the file doesn't contain the metrics, ensure you're using the latest version of the Ultralytics package and rerun the validation. For detailed guidance, please refer to the [Ultralytics documentation](https://docs.ultralytics.com/guides/yolo-common-issues/).

**Comment by curtis18** [comment]
Hi @glenn-jocher . Thank you for being so helpful. I am now using the latest version of the Ultralytics package and applying coco128-seg.yaml dataset for trial. Now I can find the F1, R, and P in results.box, but I don't know why their lengths are not the same. P, R, F1 have values of 71 classes, but mAP has values of 80 classes. data = {
        'class_name': [class_name[int(cls)] for cls in range(len(results.box.maps))],
        'Precision': results.box.p,
        'Recall': results.box.r,
        'F1': results.box.f1,
        'mAP': results.box.maps
    }


[    0.88482     0.74988     0.84885     0.88739           1     0.61374      0.6591     0.64293     0.59152     0.79801     0.86513     0.88006     0.97738     0.85254     0.92043     0.75978     0.95582     0.62362     0.85618      0.9181     0.70996     0.84159     0.78789     0.83731     0.86282     0.64481
     0.54941     0.77161     0.63543     0.60085      0.9048     0.78985     0.66925     0.82048     0.78098     0.91672     0.87714     0.58662     0.85291      0.7582     0.79872     0.60094     0.53445           1           1           1     0.57415     0.87856      0.7355      0.6324     0.60023     0.86885
     0.75249     0.99389       0.775     0.75271     0.68151           1           1           1     0.83531     0.52161     0.38423     0.34673     0.83207     0.79969     0.68207     0.50614           1     0.91378     0.92618]
Precision count: 71
-------
[    0.74409     0.49977     0.24447           1     0.96437     0.57143           1     0.41667     0.66667     0.28287           1     0.55556           1           1           1           1     0.94118           1           1     0.88889     0.83333     0.88889     0.39238     0.71429           1         0.8
           1     0.71429         0.5         0.3           1     0.54243         0.6     0.65919     0.59515     0.68805     0.59525         0.5      0.7259     0.57079        0.75           1           1           0     0.27119     0.24258           1           1           1           1         0.6     0.83333
      0.6521           1     0.76923           1           1     0.52715           0     0.68425         0.5           1         0.4     0.33333      0.9924     0.24138     0.88889           1           0     0.50567           1]
Recall count: 71
-------
[    0.80838     0.59979     0.37961     0.94033     0.98186     0.59183     0.79453     0.50564     0.62685     0.41768     0.92769     0.68113     0.98856      0.9204     0.95856     0.86349     0.94844     0.76818     0.92252     0.90326     0.76671     0.86459     0.52386     0.77092     0.92636     0.71407
     0.70919     0.74184     0.55964     0.40019     0.95002     0.64316     0.63273     0.73104     0.67552     0.78609     0.70921     0.53986     0.78429     0.65128     0.77359     0.75073      0.6966           0     0.42667     0.39045     0.72947     0.93535      0.8476     0.77481     0.60011     0.85072
     0.69871     0.99693     0.77211     0.85891     0.81059     0.69037           0     0.81253     0.62555      0.6856     0.39196      0.3399     0.90519     0.37083     0.77187     0.67211           0     0.65105     0.96167]
F1 score count: 71
-------
[    0.67129     0.44807     0.31274     0.82587     0.98013     0.65051     0.95161     0.36326     0.53671     0.26902     0.63778      0.8955     0.63778      0.5249     0.69916     0.90587     0.84382     0.62523     0.63778     0.63778     0.85202      0.8955     0.97279     0.65662     0.50151     0.70547
      0.4322     0.66423       0.699     0.73107       0.995     0.79131     0.37797     0.12499       0.445     0.40509     0.43587     0.63778     0.34307     0.50394     0.54983     0.59684     0.46612     0.58759     0.52456     0.69865       0.995     0.63778       0.995     0.65504      0.2862     0.58707
     0.82833     0.89861     0.93404     0.90851      0.4966     0.72426     0.53637     0.80405     0.57764      0.8984      0.8955     0.56206     0.26724      0.6726     0.63778      0.4289     0.88667     0.32446     0.63778     0.25225     0.68228     0.36267     0.81907       0.995      0.0995     0.58742
     0.63778     0.86193]
mAP count: 80

**Comment by glenn-jocher** [comment]
Hi @curtis18, thank you for your question. The discrepancy you're seeing is likely because the COCO dataset has 80 classes, but not all classes may be present in your validation set, leading to fewer classes being evaluated for Precision, Recall, and F1 Score. This is why you see 71 values for these metrics but 80 for mAP.

To address this, you can filter out the classes that are not present in your dataset when creating your CSV. Here's a modified version of your code snippet to handle this:

```python
import pandas as pd

# Assuming results is your validation result object
class_names = [class_name[int(cls)] for cls in range(len(results.box.maps))]

# Filter out classes that are not present in the dataset
valid_classes = [i for i, val in enumerate(results.box.p) if val is not None]

data = {
    'class_name': [class_names[i] for i in valid_classes],
    'Precision': [results.box.p[i] for i in valid_classes],
    'Recall': [results.box.r[i] for i in valid_classes],
    'F1': [results.box.f1[i] for i in valid_classes],
    'mAP': [results.box.maps[i] for i in valid_classes]
}

df = pd.DataFrame(data)
df.to_csv('metrics_per_class.csv', index=False)
```

This should ensure that only the classes present in your dataset are included in the CSV file. Let me know if you need further assistance!

**Comment by curtis18** [comment]
Hi @glenn-jocher, the issue is resolved completely, thank you very much for your help. I found there is another useful list results.ap_class_index that contains filtered valid classes.

**Comment by glenn-jocher** [comment]
@curtis18 glad to hear the issue is resolved! Yes, `results.ap_class_index` is indeed useful for identifying valid classes. If you have any more questions, feel free to ask.

**Comment by brain657** [comment]
Hi @glenn-jocher, I faced the same problem when trying to get the f1 score, P and R for each class of my model where I only get the results.csv file.

> Hey @eddmar1993! 😊 It looks like the JSON file might not be the one containing the detailed metrics from your training/validation sessions. Usually, YOLOv8 generates a `results.json` file after validation that includes detailed metrics. If it's not present or doesn't contain the expected data, it's possible that the validation step might need to be rerun with the correct settings to generate this file.
> 
> Could you double-check if you're looking at the correct JSON file generated post-validation? If you're still facing issues, running a validation step like this should help generate the detailed metrics:
> 
> ```shell
> !yolo task=detect mode=val model=path/to/your/model.pt data=path/to/your/data.yaml
> ```
> 
> This command should produce a `results.json` in your working directory with the metrics. If you're still stuck, feel free to share more details or reach out on our [Discord](https://ultralytics.com/discord) for quicker assistance. We're here to help you get this sorted! 🚀

I run the same code with you but I have trouble finding the generated "results.json" and I'm using the latest version of the Ultralytics package.

**Comment by glenn-jocher** [comment]
Hi @brain657, if you're not finding the `results.json` file, ensure you're running the validation step with `save_json=True` like this:

```python
results = model.val(data='path/to/your/data.yaml', save_json=True)
```

This should generate the `results.json` file in your working directory. If the issue persists, please verify your working directory and try again.

**Comment by jannatulmourey** [comment]
The command is giving "predictions.json" not results.json

I used this command 

yolo task=detect mode=val model="model_path" data="data.yaml" save_json=True conf=0.206 iou=0.5

**Comment by brain657** [comment]
> The command is giving "predictions.json" not results.json
> 
> I used this command
> 
> yolo task=detect mode=val model="model_path" data="data.yaml" save_json=True conf=0.206 iou=0.5

yes I have the same output

**Comment by glenn-jocher** [comment]
The `predictions.json` file contains the detailed metrics you're looking for. You can parse this file to extract Precision, Recall, and F1 Score for each class. If you need further assistance, please let us know.

**Comment by jannatulmourey** [comment]
From the "predictions.json" I am getting a list of data that contains {'image_id': '', 'category_id': , 'bbox': , 'score':}, I am not sure if that's what you mean by "detailed metrics".


Best Regards,

Jannatul Mourey | AI Project Architect

Precision AI Inc. | #200 – 1965 Broad St. | Regina, SK, S4P 1Y1

1.306.530.5661 | precision.ai<http://www.precision.ai/>

[cid:6c2d16e7-9379-4370-b097-5dbb11a01cb4]
________________________________
From: Glenn Jocher ***@***.***>
Sent: August 20, 2024 7:14 AM
To: ultralytics/ultralytics ***@***.***>
Cc: Jannatul Mourey ***@***.***>; Comment ***@***.***>
Subject: [Ext] Re: [ultralytics/ultralytics] Generate Precision, Accuracy, Recall, F1 Score for Every Class YOLOv8 (Issue #8709)


The predictions.json file contains the detailed metrics you're looking for. You can parse this file to extract Precision, Recall, and F1 Score for each class. If you need further assistance, please let us know.

**Comment by glenn-jocher** [comment]
The `predictions.json` file contains raw prediction data. To get Precision, Recall, and F1 Score for each class, you need to process these predictions against your ground truth labels. You can use tools like the COCO API or custom scripts to compute these metrics. If you need further assistance, feel free to ask.

**Comment by jannatulmourey** [comment]
Thank you for your response. I have utilized the code below to extract precision, recall, and other relevant metrics. However, I would appreciate if your could guidance me on how to obtain and save the data points used to plot the curves (such as Precision-Recall and Confidence-F1) into a CSV file.


 import csv
 from ultralytics import YOLO

 # Load the YOLO model
 model = YOLO("detect/train8/weights/best.pt")

 # Validate the model with Test-Time Augmentation (TTA)
 metrics = model.val(conf=0.206, iou=0.5, data= "yolov10/custom_data.yaml", augment=True)


 # Define class names (replace with your actual class names)
 class_names = ["B", "S", "M", "Br", "Gr"]


 # Function to format the metrics to 3 decimal places
 def format_metrics(metrics):
     return [f"{metric:.3f}" for metric in metrics]


 # Open a CSV file for writing
 with open('model_metrics.csv', mode='w', newline='') as file:
     writer = csv.writer(file)

     # Write the header row
     writer.writerow(["Class", "Precision", "Recall", "mAP50", "mAP50-95"])

     # Write the metrics for each class
     for i, c in enumerate(metrics.ap_class_index):
         class_result = format_metrics(metrics.class_result(i))
         writer.writerow([class_names[c]] + class_result)

     # Write the mean results for all classes
     mean_results = format_metrics(metrics.mean_results())
     writer.writerow(["average"] + mean_results)

Sent from my Bell Samsung device over Canada’s largest network.
________________________________
From: Glenn Jocher ***@***.***>
Sent: Tuesday, August 20, 2024 6:03:14 PM
To: ultralytics/ultralytics ***@***.***>
Cc: Jannatul Mourey ***@***.***>; Comment ***@***.***>
Subject: [Ext] Re: [ultralytics/ultralytics] Generate Precision, Accuracy, Recall, F1 Score for Every Class YOLOv8 (Issue #8709)


The predictions.json file contains raw prediction data. To get Precision, Recall, and F1 Score for each class, you need to process these predictions against your ground truth labels. You can use tools like the COCO API or custom scripts to compute these metrics. If you need further assistance, feel free to ask.

**Comment by glenn-jocher** [comment]
To save the data points used to plot Precision-Recall and Confidence-F1 curves into a CSV file, you can extract these metrics from the validation results and write them to a CSV. Here's a minimal example to guide you:

```python
import csv
from ultralytics import YOLO

# Load the YOLO model
model = YOLO("detect/train8/weights/best.pt")

# Validate the model
metrics = model.val(conf=0.206, iou=0.5, data="yolov10/custom_data.yaml", augment=True)

# Save Precision-Recall and Confidence-F1 data to CSV
with open('pr_f1_metrics.csv', mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["Confidence", "Precision", "Recall", "F1"])
    for conf, pr, rec, f1 in zip(metrics.confidence, metrics.precision, metrics.recall, metrics.f1):
        writer.writerow([conf, pr, rec, f1])
```

This script will generate a CSV file containing the required data points. If you need further assistance, feel free to ask.

**Comment by glenn-jocher** [comment]
The `predictions.json` file provides detection results, not the metrics directly. You'll need to calculate Precision, Recall, and F1 Score from these detections using ground truth data. If you need further guidance, feel free to ask.

**Comment by glenn-jocher** [comment]
The `predictions.json` file provides detection results. To calculate Precision, Recall, and F1 Score, you'll need to compare these predictions with your ground truth data. If you need further guidance, please refer to the documentation or community resources.

**Comment by jannatulmourey** [comment]
Thank you so much!



Sent from my Bell Samsung device over Canada’s largest network.
________________________________
From: Glenn Jocher ***@***.***>
Sent: Tuesday, October 15, 2024 11:31:15 PM
To: ultralytics/ultralytics ***@***.***>
Cc: Jannatul Mourey ***@***.***>; Comment ***@***.***>
Subject: [Ext] Re: [ultralytics/ultralytics] Generate Precision, Accuracy, Recall, F1 Score for Every Class YOLOv8 (Issue #8709)


The predictions.json file provides detection results. To calculate Precision, Recall, and F1 Score, you'll need to compare these predictions with your ground truth data. If you need further guidance, please refer to the documentation or community resources.

**Comment by glenn-jocher** [comment]
The `predictions.json` file provides detection results. To calculate Precision, Recall, and F1 Score, you'll need to compare these predictions with your ground truth labels. If you need further guidance, feel free to ask.

**Comment by glenn-jocher** [comment]
The `predictions.json` file provides detection results. For metrics like Precision, Recall, and F1 Score, you'll need to calculate them using these results and your ground truth data. If you need further guidance, feel free to ask.

**Comment by glenn-jocher** [comment]
The `predictions.json` provides raw detection outputs. For metrics like Precision, Recall, and F1 Score, you'll need to calculate them using these outputs and your ground truth data. If you need further guidance, feel free to ask.

**Comment by glenn-jocher** [comment]
The `predictions.json` file provides the raw detection outputs. To derive metrics like Precision, Recall, and F1 Score, you'll need to compare these predictions against your ground truth annotations. If you have further questions, feel free to ask here.

**Comment by froth0203** [comment]
You can use this code and replace the function plot_pr_curve in metrics.py. After running validation of your model (model.val()), then you get a .csv file with precision and recall per class: 

@plt_settings()
def plot_pr_curve(px, py, ap, save_dir=Path("pr_curve.png"), names={}, on_plot=None):
    import pandas as pd
    """Plots a precision-recall curve."""
    fig, ax = plt.subplots(1, 1, figsize=(9, 6), tight_layout=True)
    py = np.stack(py, axis=1)
    pr_data = []
    if 0 < len(names) < 21:  # display per-class legend if < 21 classes
        for i, y in enumerate(py.T):
            ax.plot(px, y, linewidth=1, label=f"{names[i]} {ap[i, 0]:.3f}")  # plot(recall, precision)
            # Add precision, recall, and AP to CSV data
            for recall, precision in zip(px, y):
                pr_data.append([names[i], recall, precision, ap[i, 0]])
    else:
        ax.plot(px, py, linewidth=1, color="grey")  # plot(recall, precision)
        # Add precision, recall, and AP to CSV data for all classes
        for recall, precision in zip(px, py.mean(1)):
            pr_data.append(['All Classes', recall, precision, ap[:, 0].mean()])

    ax.plot(px, py.mean(1), linewidth=3, color="blue", label=f"all classes {ap[:, 0].mean():.3f} mAP@0.5")
    ax.set_xlabel("Recall")
    ax.set_ylabel("Precision")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.legend(bbox_to_anchor=(1.04, 1), loc="upper left")
    ax.set_title("Precision-Recall Curve")
    fig.savefig(save_dir, dpi=250)
    plt.close(fig)
    # Save precision, recall, and AP data to CSV
    columns = ['Class', 'Recall', 'Precision', 'AP']
    df = pd.DataFrame(pr_data, columns=columns)
    csv_save_dir=Path("pr_curve_data.csv")
    df.to_csv(csv_save_dir, index=False)

    if on_plot:
        on_plot(save_dir)

**Comment by glenn-jocher** [comment]
Hi @froth0203, thank you for sharing this useful code snippet! This is a great approach for extracting precision-recall data for each class and saving it to CSV format.

For users looking for a more direct API approach without modifying source code, you can also access this information programmatically:

```python
from ultralytics import YOLO

# Load model and run validation
model = YOLO("your_model.pt")
results = model.val(data="your_data.yaml")

# Access curve data points
px = results.curves.px  # x-values (recall)
py = results.curves.py  # y-values (precision)
class_indices = results.ap_class_index  # indices of classes present in validation
class_names = [model.names[i] for i in class_indices]  # names of classes present

# Create your CSV with these values
import pandas as pd
import numpy as np

# Create dataframe for PR curve data
pr_data = []
for i, cls_idx in enumerate(class_indices):
    for x, y in zip(px, py[i]):
        pr_data.append([model.names[cls_idx], x, y, results.box.maps[cls_idx]])

df = pd.DataFrame(pr_data, columns=['Class', 'Recall', 'Precision', 'mAP'])
df.to_csv('pr_curve_data.csv', index=False)
```

This demonstrates how to leverage the built-in attributes of the validation results object to extract the necessary metrics data without modifying the source code.

**Comment by froth0203** [comment]
@glenn-jocher This is not possible, as results.curves or results.curves_results does not contain the attribute px or py.  According to your documentation, the px and py attribute are only considerd in the plot function: 

plot_pr_curve(
    px, py, ap, save_dir=Path("pr_curve.png"), names={}, on_plot=None
)

**Comment by glenn-jocher** [comment]
@froth0203 You're absolutely right, and I apologize for the error in my previous response. The `px` and `py` attributes aren't directly accessible through the API as I incorrectly suggested.

The best approach without modifying source code would be to access the metrics after validation and use the data available through `results.box` and related attributes. Here's a corrected approach:

```python
# After validation:
results = model.val(data="your_data.yaml")

# Access available metrics
precision = results.box.p
recall = results.box.r
f1_scores = results.box.f1
maps = results.box.maps
valid_classes = results.ap_class_index
class_names = [model.names[i] for i in valid_classes]

# Create DataFrame with available metrics
import pandas as pd
df = pd.DataFrame({
    'Class': class_names,
    'Precision': precision,
    'Recall': recall,
    'F1': f1_scores,
    'mAP': [maps[i] for i in valid_classes]
})
df.to_csv('class_metrics.csv', index=False)
```

I agree that having direct access to curve data would be valuable. Your suggestion to add an argument to the validation function to output this data is excellent and would benefit many users. I'll note this as a potential enhancement for the Ultralytics team to consider.
