### ISSUE TITLE
How can I acquire OBB result boxes

### ISSUE THREAD

**Issue by zydisney** [ultralytics/ultralytics#8712]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In the normal model, the result contains  `boxes: ultralytics.engine.results.Boxes object` . So I can plot the box with `results[0].boxes.xyxy`
However, if i use obb model, the `results[0].boxes` is none. How can I get the position of the boundary boxes?

**Comment by MosbehBarhoumi** [comment]
@zydisney Just replace **boxes** with **obb** and use **results[0].obb.xyxyxyxy** to obtain the coordinates of the oriented bounding boxes. Try printing **results[0].obb** to explore other attributes.
