### ISSUE TITLE
How to suppress inference logs about detection and speed

### ISSUE THREAD

**Issue by charlielito** [ultralytics/ultralytics#872]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to suppress inference logs about detection and speed?

I am using the following code:

```python
from ultralytics import YOLO
detector = YOLO("yolov8s-seg.pt")
# ... load img
output = detector(img)[0]
```
Every time I call it i got the following logs:

```
0: 384x640 1 person, 10.4ms
Speed: 0.5ms pre-process, 10.4ms inference, 1.8ms postprocess per image at shape (1, 3, 640, 640)
```

How can this be avoided?

**Comment by AyushExel** [comment]
Pass verbose=False in the inference function

**Comment by charlielito** [comment]
> Pass verbose=False in the inference function

It indeed stopped the logs, but now the masks are not being drawn

**Comment by Laughing-q** [comment]
@charlielito the masks will be drawn with one of these condition is True.
[https://github.com/ultralytics/ultralytics/blob/254adfa652eb9abc41a8b7bdef7d6420c81a6217/ultralytics/yolo/engine/predictor.py#L174](https://github.com/ultralytics/ultralytics/blob/254adfa652eb9abc41a8b7bdef7d6420c81a6217/ultralytics/yolo/engine/predictor.py#L174)
the following usage works to me:
```python
import cv2
model = YOLO("weights/yolov8s-seg.pt")
img = cv2.imread("./ultralytics/assets/bus.jpg")
output = model(img, save=True, verbose=True)[0]
```
the saved img is:
![image0](https://user-images.githubusercontent.com/61612323/218027228-bb2b868b-e9ea-49a9-9157-fada1731b538.jpg)

**Comment by charlielito** [comment]
I am using it to do online predictions so I don't want to serialize the results as an image.

With `model(img, verbose=True)` the masks are drawn in the image without bounding boxes (what I want) but a lot of logs are shown in the console.
With `model(img, verbose=False)` nothing is drawn and no logs
With `model(img, verbose=False, show=True)` on the contrary, the masks and also the bounding boxes are shown

The behavior of those flags doesn't seem very intuitive :sweat_smile:  How can I only have the masks drawn?

**Comment by charlielito** [comment]
I am still waiting for a response :smile:

**Comment by Laughing-q** [comment]
@charlielito add `boxes=False` then these will be no boxes drawn.
```python
from ultralytics import YOLO
import cv2

img = cv2.imread("ultralytics/assets/bus.jpg")
detector = YOLO("yolov8s-seg.pt")
# ... load img
output = detector(source=img, save=True, boxes=False, verbose=False, show=True)[0]
```

**Comment by charlielito** [comment]
> @charlielito add `boxes=False` then these will be no boxes drawn.
> 
> ```python
> from ultralytics import YOLO
> import cv2
> 
> img = cv2.imread("ultralytics/assets/bus.jpg")
> detector = YOLO("yolov8s-seg.pt")
> # ... load img
> output = detector(source=img, save=True, boxes=False, verbose=False, show=True)[0]
> ```

this works thanks!

**Comment by glenn-jocher** [comment]
@charlielito glad to hear that `boxes=False` worked for you to draw only the masks without the bounding boxes. This argument specifies whether or not to draw the bounding boxes around the detected objects. By setting it to `False`, you can suppress the bounding boxes from being drawn, and obtain only the segmentation masks. This is usually the preferred way to visualize semantic segmentations, where only the class labels denoting each pixel are of interest.
