### ISSUE TITLE
How to interpret output shape of [1,53,2100]

### ISSUE THREAD

**Issue by KingAsperin** [ultralytics/ultralytics#8729]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello can someone please help me to interpret this outputshape from yolo

![image](https://github.com/ultralytics/ultralytics/assets/147014969/0f7af984-66da-4627-98c9-413363a41877)

I trained my model in Yolov8 with 1 object detection with 1 class and 24 landmarks.

in interpreting the output shape, I want to ignore the bounding box and just extract the coordinates of the landmark.

the problem is I do not know how to interpret the output shape and if possible, can you please show me sample code to be use in android studio to successfully interpret the output shape.

**Comment by glenn-jocher** [comment]
@KingAsperin hello! 👋 It's great to see you're diving into the details of YOLOv8's output. Let's break down the output shape `[1, 53, 2100]` you're seeing:

1. **1**: This represents the batch size, indicating you're processing one image at a time.
2. **53**: This is the number of anchor boxes used by the model for predictions.
3. **2100**: For a model trained with 1 class and 24 landmarks, this dimension can be interpreted as follows: each anchor box predicts a class score, objectness score, 4 bounding box attributes, and 2 coordinates for each of the 24 landmarks. The formula to calculate this dimension is `(1 class + 1 objectness + 4 bbox + 24 landmarks * 2) * 53 = 2100`.

To extract just the landmark coordinates and ignore the bounding box, you would focus on the last 48 values (24 landmarks * 2 coordinates) for each of the 53 anchor boxes.

Here's a simplified Python snippet that demonstrates how to extract landmark coordinates from the output tensor. While this is not directly applicable in Android Studio, it should give you an idea of the logic that you can adapt to Java/Kotlin:

```python
import torch

# Assuming 'output' is your model's output tensor with shape [1, 53, 2100]
output = torch.rand(1, 53, 2100)  # Example tensor

# Extract landmark coordinates
landmarks = output[..., -48:]  # Take the last 48 values for each anchor box

# Now, 'landmarks' contains the coordinates of the 24 landmarks for each anchor box
```

For integrating this logic into Android Studio, you would typically use a deep learning library compatible with Android, such as TensorFlow Lite, and translate the above logic into Java or Kotlin. The key part is to correctly index into your model's output array to extract the landmark coordinates.

I hope this helps! If you have more questions or need further assistance, feel free to ask. Happy coding! 🚀

**Comment by KingAsperin** [comment]
> @KingAsperin hello! 👋 It's great to see you're diving into the details of YOLOv8's output. Let's break down the output shape `[1, 53, 2100]` you're seeing:
> 
> 1. **1**: This represents the batch size, indicating you're processing one image at a time.
> 2. **53**: This is the number of anchor boxes used by the model for predictions.
> 3. **2100**: For a model trained with 1 class and 24 landmarks, this dimension can be interpreted as follows: each anchor box predicts a class score, objectness score, 4 bounding box attributes, and 2 coordinates for each of the 24 landmarks. The formula to calculate this dimension is `(1 class + 1 objectness + 4 bbox + 24 landmarks * 2) * 53 = 2100`.
> 
> To extract just the landmark coordinates and ignore the bounding box, you would focus on the last 48 values (24 landmarks * 2 coordinates) for each of the 53 anchor boxes.
> 
> Here's a simplified Python snippet that demonstrates how to extract landmark coordinates from the output tensor. While this is not directly applicable in Android Studio, it should give you an idea of the logic that you can adapt to Java/Kotlin:
> 
> ```python
> import torch
> 
> # Assuming 'output' is your model's output tensor with shape [1, 53, 2100]
> output = torch.rand(1, 53, 2100)  # Example tensor
> 
> # Extract landmark coordinates
> landmarks = output[..., -48:]  # Take the last 48 values for each anchor box
> 
> # Now, 'landmarks' contains the coordinates of the 24 landmarks for each anchor box
> ```
> 
> For integrating this logic into Android Studio, you would typically use a deep learning library compatible with Android, such as TensorFlow Lite, and translate the above logic into Java or Kotlin. The key part is to correctly index into your model's output array to extract the landmark coordinates.
> 
> I hope this helps! If you have more questions or need further assistance, feel free to ask. Happy coding! 🚀

i sucessfuly converted it to tflite and it gives me this output shape now my problem is i am often getting an shape mismatch when i try to display what is the content of the output 

![image](https://github.com/ultralytics/ultralytics/assets/147014969/0fd3bed6-3307-41e3-81a0-87ad1a20197e)

is it possible for you to show me how to plot the landmark on my image here and ignore to plot the bounding box..

i am new in computer vision and i have a little to no knowledge about it.

![image](https://github.com/ultralytics/ultralytics/assets/147014969/e7349124-5e8d-4ddf-a01c-dbb9fba7fb30)


can you please help me to plot the landmarks only on the images..

Thank you so much for the help.

**Comment by glenn-jocher** [comment]
Hey @KingAsperin! 🌟 It's awesome to see you making progress with your YOLOv8 model and converting it to TensorFlow Lite. For the shape mismatch issue, it's crucial to ensure that the output shape you're working with matches the expected format for landmark extraction.

Given your output shape, let's assume you've correctly identified the landmark coordinates section. To plot these landmarks on your image without including the bounding box, you can use a simple loop to draw each point. Here's a quick example in Python using OpenCV, which you might find helpful as a starting point. You can adapt this logic to your Android application:

```python
import cv2
import numpy as np

# Load your image
image = cv2.imread('path/to/your/image.jpg')

# Assuming 'landmarks' is a flat array [x1, y1, x2, y2, ..., x24, y24]
# Reshape for easier handling: 24 landmarks, each with x and y coordinates
landmarks = np.array(landmarks).reshape(-1, 2)

# Loop through the landmarks and draw each one
for x, y in landmarks:
    cv2.circle(image, (int(x), int(y)), radius=5, color=(0, 255, 0), thickness=-1)

# Display the result
cv2.imshow('Landmarks Only', image)
cv2.waitKey(0)
cv2.destroyAllWindows()
```

This code assumes `landmarks` is your array of landmark coordinates extracted from the model's output. You'll need to adjust the path to your image and possibly the way you extract and format `landmarks` based on your actual output data structure.

For integrating this into Android Studio, you'd use similar logic but with Android's drawing APIs or OpenCV for Android if you're using it. The key steps are iterating through the landmarks, converting their coordinates to integer values (if necessary), and drawing circles at those coordinates on your image.

I hope this helps you move forward! If you have more questions or run into any issues, just let me know. Keep up the great work! 🚀
