### ISSUE TITLE
Can model.train use wandb's dataset artifact as traing dataset?

### ISSUE THREAD

**Issue by jpointchoi** [ultralytics/ultralytics#8731]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I think one of key driver for ML automation is to use artifact as much as we can. 
Tried to pass dataset artifact(consisting of train and validattion dataset) generated by wandb to pass to model.train. However, this seems not be possible. Please advise if this is feasible or not. 

Thanks in advance

```# pip3 install -U wandb
from ultralytics import YOLO
# from wandb.integration.yolov8 import add_callbacks as add_wandb_callbacks
import argparse
import wandb
from types import SimpleNamespace

defaults = SimpleNamespace(
    # data='dota8.yaml',
    data='./hd_hbb_dataset.yaml',
    epochs=5,
    imgsz=640,
    #patience=100000,
)

def parse_args(default_cfg):
    #"Override default hyper-parameters using argparse"
    parser = argparse.ArgumentParser(description="Process hyper-parameters")
    parser.add_argument('--data', type=str, default=defaults.data)
    parser.add_argument('--epochs', type=int, default=defaults.epochs)
    parser.add_argument('--imgsz', type=int, default=defaults.imgsz)
    # parser.add_argument('--patience', type=int, default=defaults.patience)

    args = vars(parser.parse_args())

    # update config with parsed args
    for k, v in args.items():
        setattr(default_cfg, k, v)

# parse_args(defaults)

config = {
    "project": "YOLOv8",
    "data": "./hd_hbb_dataset.yaml",
    "epochs": 5,
    "imgsz": 640
}

# wandb
run = wandb.init(
       project=config["project"],
       job_type="train",
       config=config,
       settings={"disable_git": True}
)

# Extract wandb config
wandb_config = run.config
run.log_code(name="train_visualize",
                 include_fn=lambda path: path.endswith(".py") or path.endswith(".txt") or path.endswith("hd_hbb_dataset.yaml"))

model = YOLO("yolov8n.yaml")
# add_wandb_callbacks(model, project = "YOLOv8")

# import wandb
# run = wandb.init()
artifact = run.use_artifact('qisenskaist/YOLOv8/hd-hbb-data:v0', type='dataset')
artifact_dir = artifact.download()
print(artifact_dir)
# can you advise how to pass this to model.train?

# results = model.train(data = "../wildlife_dataset.yaml",epochs = 1000, device = 0, save_period = 10)
# results = model.train(data=defaults.data, epochs=defaults.epochs, imgsz=defaults.imgsz, patience=defaults.patience)
results = model.train(data=wandb_config.data, epochs=wandb_config.epochs, imgsz=wandb_config.imgsz)


```

**Comment by glenn-jocher** [comment]
@jpointchoi hey there! 👋

Great question! Currently, directly using a wandb dataset artifact with `model.train` isn't supported out-of-the-box. However, you're on the right track by downloading the artifact to a local directory. Once you have the dataset locally, you can point your dataset YAML file (`data` argument in `model.train`) to the local paths where the artifact was downloaded.

Here's a quick example to adjust your code snippet for using the downloaded artifact directory:

```python
# Assuming artifact_dir contains the path to the downloaded dataset
data_yaml = f"{artifact_dir}/hd_hbb_dataset.yaml"  # Update this path if needed

# Now, you can pass this updated YAML file path to model.train
results = model.train(data=data_yaml, epochs=wandb_config.epochs, imgsz=wandb_config.imgsz)
```

Make sure your dataset YAML file (`hd_hbb_dataset.yaml` in this case) has the correct paths to the training and validation data relative to where you've downloaded the artifact.

Hope this helps! Let us know if you have any more questions. 😊

**Comment by jpointchoi** [comment]
hey glen 
this deos work. thanks!

**Comment by glenn-jocher** [comment]
@jpointchoi hey there! 😊

You're welcome! I'm glad to hear it worked out for you. If you have any more questions or need further assistance, feel free to reach out. Happy coding!
