### ISSUE TITLE
Dual GPU training and startup

### ISSUE THREAD

**Issue by runner-9** [ultralytics/ultralytics#8733]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

When using dual GPU training, an error message may break at some point. Then, when restarting, the same error is reported.Checked, it's not a CPU/GPU memory issue.Looking forward to your reply.Thanks.

### Environment

Ultralytics YOLOv8.1.20 🚀 Python-3.10.13 torch-1.11.0 CUDA:0 (NVIDIA TITAN X (Pascal), 12196MiB)
                                                       CUDA:1 (NVIDIA TITAN X (Pascal), 12196MiB)

### Minimal Reproducible Example

(yolov8) dourenyin@server:~/hfli/yolo/ultralytics$ python train.py
WARNING ⚠️ no model scale passed. Assuming scale='l'.
New https://pypi.org/project/ultralytics/8.1.24 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.1.20 🚀 Python-3.10.13 torch-1.11.0 CUDA:0 (NVIDIA TITAN X (Pascal), 12196MiB)
                                                       CUDA:1 (NVIDIA TITAN X (Pascal), 12196MiB)
engine/trainer: task=detect, mode=train, model=/home/dourenyin/hfli/YOLO_V8/ultralytics/ultralytics/cfg/models/v8/yolov8-1280-p6.yaml, data=/home/dourenyin/hfli/YOLO_V8/ultralytics/ultralytics/cfg/datasets/coco.yaml, epochs=200, time=None, patience=100, batch=2, imgsz=1280, save=True, save_period=1, cache=False, device=0,1, workers=2, project=None, name=train56, exist_ok=False, pretrained=False, optimizer=auto, verbose=False, seed=0, deterministic=False, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=False, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=False, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=2, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=0.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train56
WARNING ⚠️ no model scale passed. Assuming scale='l'.

                   from  n    params  module                                       arguments
  0                  -1  1      1856  ultralytics.nn.modules.conv.Conv             [3, 64, 3, 2]
  1                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  2                  -1  3    279808  ultralytics.nn.modules.block.C2f             [128, 128, 3, True]
  3                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  4                  -1  6   2101248  ultralytics.nn.modules.block.C2f             [256, 256, 6, True]
  5                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  6                  -1  6   8396800  ultralytics.nn.modules.block.C2f             [512, 512, 6, True]
  7                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
  8                  -1  3   4461568  ultralytics.nn.modules.block.C2f             [512, 512, 3, True]
  9                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
 10                  -1  3   4461568  ultralytics.nn.modules.block.C2f             [512, 512, 3, True]
 11                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 12                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 13             [-1, 8]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 14                  -1  3   4330496  ultralytics.nn.modules.block.C2              [1024, 512, 3, False]
 15                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 16             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 17                  -1  3   4330496  ultralytics.nn.modules.block.C2              [1024, 512, 3, False]
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 19             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 20                  -1  3   1149440  ultralytics.nn.modules.block.C2              [768, 256, 3, False]
 21                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 22             [-1, 2]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 23                  -1  3    288000  ultralytics.nn.modules.block.C2              [384, 128, 3, False]
 24                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 25            [-1, 20]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 26                  -1  3   1051136  ultralytics.nn.modules.block.C2              [384, 256, 3, False]
 27                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 28            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 29                  -1  3   4199424  ultralytics.nn.modules.block.C2              [768, 512, 3, False]
 30                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
 31            [-1, 14]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 32                  -1  3   4330496  ultralytics.nn.modules.block.C2              [1024, 512, 3, False]
 33                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
 34            [-1, 11]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 35                  -1  3   4330496  ultralytics.nn.modules.block.C2              [1024, 512, 3, False]
 36[23, 26, 29, 32, 35]  1   4315616  ultralytics.nn.modules.head.Detect           [80, [128, 256, 512, 512, 512]]
YOLOv8-1280-p6 summary: 557 layers, 60414752 parameters, 60414736 gradients, 205.7 GFLOPs

DDP: debug command /home/dourenyin/anaconda3/envs/yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 55649 /home/dourenyin/.config/Ultralytics/DDP/_temp_y3mddenq140447711880064.py
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Ultralytics YOLOv8.1.22 🚀 Python-3.10.13 torch-1.11.0 CUDA:0 (NVIDIA TITAN X (Pascal), 12196MiB)
                                                       CUDA:1 (NVIDIA TITAN X (Pascal), 12196MiB)
WARNING ⚠️ no model scale passed. Assuming scale='l'.
Freezing layer 'model.36.dfl.conv.weight'
[34m[1mAMP: [0mrunning Automatic Mixed Precision (AMP) checks with YOLOv8n...
yolov8n.pt
[34m[1mAMP: [0mchecks passed ✅

[34m[1mtrain: [0mScanning /home/dourenyin/DATA/coco/labels/train2017.cache... 118287 images, 1021 backgrounds, 0 corrupt: 100%|██████████| 118287/118287 [00:00<?, ?it/s]
[34m[1mtrain: [0mScanning /home/dourenyin/DATA/coco/labels/train2017.cache... 118287 images, 1021 backgrounds, 0 corrupt: 100%|██████████| 118287/118287 [00:00<?, ?it/s]
[34m[1mtrain: [0mWARNING ⚠️ /home/dourenyin/DATA/coco/images/train2017/000000099844.jpg: 2 duplicate labels removed
[34m[1mtrain: [0mWARNING ⚠️ /home/dourenyin/DATA/coco/images/train2017/000000201706.jpg: 1 duplicate labels removed
[34m[1mtrain: [0mWARNING ⚠️ /home/dourenyin/DATA/coco/images/train2017/000000214087.jpg: 1 duplicate labels removed
[34m[1mtrain: [0mWARNING ⚠️ /home/dourenyin/DATA/coco/images/train2017/000000522365.jpg: 1 duplicate labels removed
[34m[1mval: [0mScanning /home/dourenyin/DATA/coco/labels/val2017.cache... 5000 images, 48 backgrounds, 0 corrupt: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
[34m[1mval: [0mScanning /home/dourenyin/DATA/coco/labels/val2017.cache... 5000 images, 48 backgrounds, 0 corrupt: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
Plotting labels to runs/detect/train3/labels.jpg... 
[34m[1moptimizer:[0m 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
[34m[1moptimizer:[0m SGD(lr=0.01, momentum=0.9) with parameter groups 148 weight(decay=0.0), 159 weight(decay=0.0005), 158 bias(decay=0.0)
200 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
1/200      10.1G      3.336      6.923      4.267         37       1280:  37%|███▋      | 10998/29572 [2:38:45<4:20:56,  1.19it/s]
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 25301 closing signal SIGTERM                     [76/1844]
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 25302 closing signal SIGTERM
Traceback (most recent call last):
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__in
it__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 241, in laun
ch_agent
    result = agent.run()
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 129, 
in wrapper
    result = f(*args, **kwargs)
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 
723, in run
    result = self._invoke_run(role)
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 
864, in _invoke_run
    time.sleep(monitor_interval)
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/api.py", li
ne 62, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 25274 got signal: 15
Traceback (most recent call last):
  File "/home/dourenyin/hfli/yolo/ultralytics/train.py", line 14, in <module>
    model.train(data='/home/dourenyin/hfli/YOLO_V8/ultralytics/ultralytics/cfg/datasets/coco128.yaml')
  File "/home/dourenyin/hfli/yolo/ultralytics/ultralytics/engine/model.py", line 644, in train
    self.trainer.train()
  File "/home/dourenyin/hfli/yolo/ultralytics/ultralytics/engine/trainer.py", line 203, in train
    raise e
  File "/home/dourenyin/hfli/yolo/ultralytics/ultralytics/engine/trainer.py", line 201, in train
    subprocess.run(cmd, check=True)
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/dourenyin/anaconda3/envs/yolov8/bin/python', '-m', 'torch.distributed.run', '--n proc_per_node', '2', '--master_port', '34809', '/home/dourenyin/.config/Ultralytics/DDP/_temp_9y95ifcg140396525136304.py']' returned non-zero exit status 1.

(yolov8) dourenyin@server:~/hfli/yolo/ultralytics$ python train.py
WARNING ⚠️ no model scale passed. Assuming scale='l'.
New https://pypi.org/project/ultralytics/8.1.24 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.1.20 🚀 Python-3.10.13 torch-1.11.0 CUDA:0 (NVIDIA TITAN X (Pascal), 12196MiB)
                                                       CUDA:1 (NVIDIA TITAN X (Pascal), 12196MiB)
engine/trainer: task=detect, mode=train, model=/home/dourenyin/hfli/YOLO_V8/ultralytics/ultralytics/cfg/models/v8/yolov8-1280-p6.yaml, data=/home/dourenyin/hfli/YOLO_V8/ultralytics/ultralytics/cfg/datasets/coco.yaml, epochs=200, time=None, patience=100, batch=2, imgsz=1280, save=True, save_period=1, cache=False, device=0,1, workers=2, project=None, name=train56, exist_ok=False, pretrained=False, optimizer=auto, verbose=False, seed=0, deterministic=False, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=False, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=False, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=2, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=0.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train56
WARNING ⚠️ no model scale passed. Assuming scale='l'.

                   from  n    params  module                                       arguments
  0                  -1  1      1856  ultralytics.nn.modules.conv.Conv             [3, 64, 3, 2]
  1                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  2                  -1  3    279808  ultralytics.nn.modules.block.C2f             [128, 128, 3, True]
  3                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  4                  -1  6   2101248  ultralytics.nn.modules.block.C2f             [256, 256, 6, True]
  5                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  6                  -1  6   8396800  ultralytics.nn.modules.block.C2f             [512, 512, 6, True]
  7                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
  8                  -1  3   4461568  ultralytics.nn.modules.block.C2f             [512, 512, 3, True]
  9                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
 10                  -1  3   4461568  ultralytics.nn.modules.block.C2f             [512, 512, 3, True]
 11                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 12                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 13             [-1, 8]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 14                  -1  3   4330496  ultralytics.nn.modules.block.C2              [1024, 512, 3, False]
 15                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 16             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 17                  -1  3   4330496  ultralytics.nn.modules.block.C2              [1024, 512, 3, False]
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 19             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 20                  -1  3   1149440  ultralytics.nn.modules.block.C2              [768, 256, 3, False]
 21                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 22             [-1, 2]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 23                  -1  3    288000  ultralytics.nn.modules.block.C2              [384, 128, 3, False]
 24                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 25            [-1, 20]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 26                  -1  3   1051136  ultralytics.nn.modules.block.C2              [384, 256, 3, False]
 27                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 28            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 29                  -1  3   4199424  ultralytics.nn.modules.block.C2              [768, 512, 3, False]
 30                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
 31            [-1, 14]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 32                  -1  3   4330496  ultralytics.nn.modules.block.C2              [1024, 512, 3, False]
 33                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
 34            [-1, 11]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 35                  -1  3   4330496  ultralytics.nn.modules.block.C2              [1024, 512, 3, False]
 36[23, 26, 29, 32, 35]  1   4315616  ultralytics.nn.modules.head.Detect           [80, [128, 256, 512, 512, 512]]
YOLOv8-1280-p6 summary: 557 layers, 60414752 parameters, 60414736 gradients, 205.7 GFLOPs

DDP: debug command /home/dourenyin/anaconda3/envs/yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 55649 /home/dourenyin/.config/Ultralytics/DDP/_temp_y3mddenq140447711880064.py
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Ultralytics YOLOv8.1.22 🚀 Python-3.10.13 torch-1.11.0 CUDA:0 (NVIDIA TITAN X (Pascal), 12196MiB)
                                                       CUDA:1 (NVIDIA TITAN X (Pascal), 12196MiB)
WARNING ⚠️ no model scale passed. Assuming scale='l'.
Freezing layer 'model.36.dfl.conv.weight'
WARNING:torch.distributed.elastic.agent.server.api:Received 15 death signal, shutting down workers
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 6465 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 6466 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.errors.error_handler:{
  "message": {
    "message": "SignalException: Process 6447 got signal: 15",
    "extraInfo": {
      "py_callstack": "Traceback (most recent call last):\n  File \"/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 345, in wrapper\n    return f(*args, **kwargs)\n  File \"/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/run.py\", line 724, in main\n    run(args)\n  File \"/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/run.py\", line 715, in run\n    elastic_launch(\n  File \"/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/launcher/api.py\", line 131, in __call__\n    return launch_agent(self._config, self._entrypoint, list(args))\n  File \"/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/launcher/api.py\", line 236, in launch_agent\n    result = agent.run()\n  File \"/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py\", line 709, in run\n    result = self._invoke_run(role)\n  File \"/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py\", line 850, in _invoke_run\n    time.sleep(monitor_interval)\n  File \"/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/api.py\", line 60, in _terminate_process_handler\n    raise SignalException(f\"Process {os.getpid()} got signal: {sigval}\", sigval=sigval)\ntorch.distributed.elastic.multiprocessing.api.SignalException: Process 6447 got signal: 15\n",
      "timestamp": "1709776125"
    }
  }
}
Traceback (most recent call last):
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/run.py", line 728, in <module>
    main()
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/run.py", line 724, in main
    run(args)
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 236, in launch_agent
    result = agent.run()
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 850, in _invoke_run
    time.sleep(monitor_interval)
  File "/home/dourenyin/anaconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 60, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 6447 got signal: 15

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@runner-9 hey there! 👋 It seems like you're encountering an issue with dual GPU training and encountering errors upon restart. This could be related to the distributed data parallel (DDP) setup or an environment-specific issue. Here are a couple of suggestions:

1. **Ensure DDP Setup is Correct**: Double-check your DDP setup and ensure that it's correctly configured for multi-GPU training. The error logs hint at a potential issue with the DDP process being terminated unexpectedly.

2. **Environment Variables**: Sometimes, setting the `NCCL_SOCKET_IFNAME` environment variable helps with multi-GPU setups. You can try setting it to your network interface name (usually `eth0` or `ens5`):
   ```bash
   export NCCL_SOCKET_IFNAME=^docker0,lo
   ```

3. **Update and Retry**: Ensure your Ultralytics YOLOv8, PyTorch, and CUDA toolkit are up to date. Sometimes, compatibility issues might cause unexpected errors:
   ```bash
   pip install -U ultralytics torch torchvision
   ```

4. **Simplify the Test Case**: Try running a minimal training session with a very small dataset on your dual GPU setup to see if the issue persists. This can help isolate whether the problem is data-related or setup-related.

If these steps don't resolve the issue, it would be great to have more details on the error message you're encountering. Since you're willing to submit a PR, it sounds like you might have some insights into the issue! If you've identified a specific bug or have a fix in mind, feel free to share more details or open a PR directly on the GitHub repo. We appreciate your contribution to improving YOLOv8! 🚀

**Comment by runner-9** [comment]
@glenn-jocher Hello,rebooting the computer solves the problem, but training interruptions still occur.How to solve this problem.

**Comment by glenn-jocher** [comment]
We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
