### ISSUE TITLE
AttributeError: 'YoloNAS_S' object has no attribute 'model'

### ISSUE THREAD

**Issue by jrsebastian** [ultralytics/ultralytics#8741]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! When i tried to eval `yolov_nas_s.pt`, i met some errors, can anybody help me??
```python
$yolo val model=yolo_nas_s.pt data=coco8.yaml

The console stream is logged into /data/shijiarong/sg_logs/console.log
[2024-03-07 14:47:33] INFO - crash_tips_setup.py - Crash tips is enabled. You can set your environment variable to CRASH_HANDLER=FALSE to disable it
[2024-03-07 14:47:33] WARNING - __init__.py - Failed to import pytorch_quantization
[2024-03-07 14:47:35] WARNING - calibrator.py - Failed to import pytorch_quantization
[2024-03-07 14:47:35] WARNING - export.py - Failed to import pytorch_quantization
[2024-03-07 14:47:35] WARNING - selective_quantization_utils.py - Failed to import pytorch_quantization
WARNING ⚠️ The file 'yolo_nas_s.pt' appears to be improperly saved or formatted. For optimal results, use model.save('filename.pt') to correctly save YOLO models.
Traceback (most recent call last):
  File "/data/shijiarong/.local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/data/shijiarong/.local/lib/python3.9/site-packages/ultralytics/cfg/__init__.py", line 541, in entrypoint
    model = YOLO(model, task=task)
  File "/data/shijiarong/.local/lib/python3.9/site-packages/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/data/shijiarong/.local/lib/python3.9/site-packages/ultralytics/engine/model.py", line 142, in __init__
    self._load(model, task=task)
  File "/data/shijiarong/.local/lib/python3.9/site-packages/ultralytics/engine/model.py", line 229, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/data/shijiarong/.local/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 782, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/data/shijiarong/.local/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 736, in torch_safe_load
    ckpt = {"model": ckpt.model}
  File "/data/shijiarong/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'YoloNAS_S' object has no attribute 'model'


```

Thanks in advance

### Additional
ultralytics   8.1.17
torch  2.2.0
torchvision  0.17.0
python  3.9.18

**Comment by glenn-jocher** [comment]
@jrsebastian hi there! 👋 It looks like you're encountering an issue with loading the `yolo_nas_s.pt` model. The error message suggests that the model file might not have been saved correctly. 

To resolve this, please ensure that the model file you're trying to load is correctly saved and is compatible with the current version of Ultralytics YOLO you're using. If you have the training script or the model creation script, you can try re-saving the model using `torch.save(model.state_dict(), 'filename.pt')` for state dictionaries or `torch.save(model, 'filename.pt')` for the entire model.

If the issue persists, it might be helpful to check if there are any updates or patches for the Ultralytics YOLO that address this issue, or consider re-downloading or re-training the model if possible.

Here's a quick example on how to save a model correctly:
```python
# Assuming 'model' is your trained model
torch.save(model.state_dict(), 'yolo_nas_s_correct.pt')
```

And to load it back:
```python
model.load_state_dict(torch.load('yolo_nas_s_correct.pt'))
```

Let us know if this helps or if you have any more questions!

**Comment by jrsebastian** [comment]
> @jrsebastian hi there! 👋 It looks like you're encountering an issue with loading the `yolo_nas_s.pt` model. The error message suggests that the model file might not have been saved correctly.
> 
> To resolve this, please ensure that the model file you're trying to load is correctly saved and is compatible with the current version of Ultralytics YOLO you're using. If you have the training script or the model creation script, you can try re-saving the model using `torch.save(model.state_dict(), 'filename.pt')` for state dictionaries or `torch.save(model, 'filename.pt')` for the entire model.
> 
> If the issue persists, it might be helpful to check if there are any updates or patches for the Ultralytics YOLO that address this issue, or consider re-downloading or re-training the model if possible.
> 
> Here's a quick example on how to save a model correctly:
> 
> ```python
> # Assuming 'model' is your trained model
> torch.save(model.state_dict(), 'yolo_nas_s_correct.pt')
> ```
> 
> And to load it back:
> 
> ```python
> model.load_state_dict(torch.load('yolo_nas_s_correct.pt'))
> ```
> 
> Let us know if this helps or if you have any more questions!

@glenn-jocher hi! Thanks for your advice. Unfortunately, i got the `yolo_nas_s.pt` from [Ultralytics](https://github.com/ultralytics/assets/releases/download/v8.1.0/yolo_nas_s.pt), which is from [yolo-nas.md](https://github.com/ultralytics/ultralytics/blob/main/docs/en/models/yolo-nas.md). I don't have my own trained model. Maybe I can re-save above model like your example? Or is there has a correct version of yolo_nas_s.pt from Ultralytics ? Thank you!

**Comment by glenn-jocher** [comment]
Hi @jrsebastian! 🌟 Thanks for reaching out. If you've downloaded `yolo_nas_s.pt` directly from our releases, it should indeed be correctly formatted. However, it seems like there might be a compatibility issue with the version of Ultralytics YOLO you're using.

No need to re-save the model on your end. Instead, could you please ensure that you're using the latest version of our Ultralytics YOLO package? Sometimes, updating to the latest version can resolve these types of issues. You can update using:

```bash
pip install ultralytics --upgrade
```

If after updating, the problem still exists, it might be a specific issue with the `yolo_nas_s.pt` file. In that case, we'll look into it and make sure to provide a fix or an updated model file as soon as possible.

Please keep us posted on your progress, and don't hesitate to reach out if you have any more questions or concerns!

**Comment by jrsebastian** [comment]
Hi @glenn-jocher! Yes, i'm sure that i'm using the latest version of Ultralytics package. In fact, before i raise this issue, i have already update Ultralytics by ``` pip install ultralytics --upgrade ```. Some infos:
```python
$ pip install ultralytics --upgrade
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: ultralytics in /data/shijiarong/.local/lib/python3.9/site-packages (8.1.24)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.9/dist-packages (from ultralytics) (3.5.2)
Requirement already satisfied: opencv-python>=4.6.0 in /data/shijiarong/.local/lib/python3.9/site-packages (from ultralytics) (4.9.0.80)
Requirement already satisfied: pillow>=7.1.2 in /data/shijiarong/.local/lib/python3.9/site-packages (from ultralytics) (10.2.0)
Requirement already satisfied: pyyaml>=5.3.1 in /data/shijiarong/.local/lib/python3.9/site-packages (from ultralytics) (6.0.1)
Requirement already satisfied: requests>=2.23.0 in /data/shijiarong/.local/lib/python3.9/site-packages (from ultralytics) (2.31.0)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.9/dist-packages (from ultralytics) (1.9.3)
Requirement already satisfied: torch>=1.8.0 in /data/shijiarong/.local/lib/python3.9/site-packages (from ultralytics) (2.2.1)
Requirement already satisfied: torchvision>=0.9.0 in /data/shijiarong/.local/lib/python3.9/site-packages (from ultralytics) (0.17.1)
Requirement already satisfied: tqdm>=4.64.0 in /data/shijiarong/.local/lib/python3.9/site-packages (from ultralytics) (4.66.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.9/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: py-cpuinfo in /data/shijiarong/.local/lib/python3.9/site-packages (from ultralytics) (9.0.0)
Requirement already satisfied: thop>=0.1.1 in /data/shijiarong/.local/lib/python3.9/site-packages (from ultralytics) (0.1.1.post2209072238)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.9/dist-packages (from ultralytics) (1.4.2)
Requirement already satisfied: seaborn>=0.11.0 in /data/shijiarong/.local/lib/python3.9/site-packages (from ultralytics) (0.13.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.33.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.4.2)
Requirement already satisfied: numpy>=1.17 in /data/shijiarong/.local/lib/python3.9/site-packages (from matplotlib>=3.3.0->ultralytics) (1.23.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.0->ultralytics) (21.3)
Requirement already satisfied: pyparsing>=2.2.1 in /data/shijiarong/.local/lib/python3.9/site-packages (from matplotlib>=3.3.0->ultralytics) (2.4.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /data/shijiarong/.local/lib/python3.9/site-packages (from pandas>=1.1.4->ultralytics) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests>=2.23.0->ultralytics) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests>=2.23.0->ultralytics) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests>=2.23.0->ultralytics) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests>=2.23.0->ultralytics) (2022.5.18.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.9/dist-packages (from torch>=1.8.0->ultralytics) (3.9.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /data/shijiarong/.local/lib/python3.9/site-packages (from torch>=1.8.0->ultralytics) (4.10.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.9/dist-packages (from torch>=1.8.0->ultralytics) (1.11.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.9/dist-packages (from torch>=1.8.0->ultralytics) (2.8.8)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.9/dist-packages (from torch>=1.8.0->ultralytics) (3.1.2)
Requirement already satisfied: fsspec in /data/shijiarong/.local/lib/python3.9/site-packages (from torch>=1.8.0->ultralytics) (2024.2.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /data/shijiarong/.local/lib/python3.9/site-packages (from torch>=1.8.0->ultralytics) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /data/shijiarong/.local/lib/python3.9/site-packages (from torch>=1.8.0->ultralytics) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /data/shijiarong/.local/lib/python3.9/site-packages (from torch>=1.8.0->ultralytics) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /data/shijiarong/.local/lib/python3.9/site-packages (from torch>=1.8.0->ultralytics) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /data/shijiarong/.local/lib/python3.9/site-packages (from torch>=1.8.0->ultralytics) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /data/shijiarong/.local/lib/python3.9/site-packages (from torch>=1.8.0->ultralytics) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /data/shijiarong/.local/lib/python3.9/site-packages (from torch>=1.8.0->ultralytics) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /data/shijiarong/.local/lib/python3.9/site-packages (from torch>=1.8.0->ultralytics) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /data/shijiarong/.local/lib/python3.9/site-packages (from torch>=1.8.0->ultralytics) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /data/shijiarong/.local/lib/python3.9/site-packages (from torch>=1.8.0->ultralytics) (2.19.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /data/shijiarong/.local/lib/python3.9/site-packages (from torch>=1.8.0->ultralytics) (12.1.105)
Requirement already satisfied: triton==2.2.0 in /data/shijiarong/.local/lib/python3.9/site-packages (from torch>=1.8.0->ultralytics) (2.2.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /data/shijiarong/.local/lib/python3.9/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.8.0->ultralytics) (12.3.101)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.9/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (2.1.1)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.9/dist-packages (from sympy->torch>=1.8.0->ultralytics) (1.3.0)

```

I would like to provide some relevant package's version that i'm using:
```python
ultralytics                   8.1.24
torch                         2.2.1
torchvision                   0.17.1
super-gradients               3.6.0

```
Thanks a lot in advance!

**Comment by glenn-jocher** [comment]
Hi @jrsebastian! Thanks for confirming that you're on the latest version of the Ultralytics package and providing the additional package versions. It's helpful to know that you've already taken steps to ensure everything is up to date. 🚀

Given the error and your setup, it seems like there might be a specific issue with the `yolo_nas_s.pt` model file compatibility with the current Ultralytics version you're using. Since you've already ensured that your environment is up to date, the next step would be for us to investigate this particular model file's compatibility.

In the meantime, as a workaround, you might consider trying a different model from our collection to see if the issue persists. This could help determine if the problem is isolated to the `yolo_nas_s.pt` model file.

We'll look into the `yolo_nas_s.pt` model file issue and aim to provide a fix or an updated model file as soon as possible. Your patience and understanding are greatly appreciated! 🙏

If you have any more questions or run into further issues, please don't hesitate to reach out.

**Comment by jrsebastian** [comment]
@glenn-jocher Hi! I'm Sorry, Is there any update of this issue?

 I tried to find some other version of `yolo_nas_s.pt`  , but i can't find it from [ultralytics/assets/releases/](https://github.com/ultralytics/assets/releases/) ,If there is another version of `yolov_nas_s` (maybe compatible with the current Ultralytics version), Could you please provide to me? Thank you very much.

Or if there is a version of Ultralytics that is compatible with current `yolo_nas_s.pt`, could you please tell me the version of Ultralytics? Thanks a lot.

**Comment by glenn-jocher** [comment]
@jrsebastian hi there! 😊 We're currently looking into the compatibility issue with the `yolo_nas_s.pt` model. Unfortunately, there isn't an alternative version of the model available at the moment. 

As for the Ultralytics version compatible with the current `yolo_nas_s.pt`, we're working to identify and possibly provide a workaround or fix. We'll update the community as soon as we have a solution.

In the meantime, exploring other models available on our [releases page](https://github.com/ultralytics/assets/releases/) might be beneficial. We appreciate your patience and understanding! If you have further questions or need assistance with anything else, feel free to ask. 🌟

**Comment by joe248** [comment]
Hi @glenn-jocher ,

Five months later and this is still an issue.

```bash
$ yolo export model=yolo_nas_s.pt format=edgetpu
The console stream is logged into /root/sg_logs/console.log
[2024-08-18 23:49:05] INFO - crash_tips_setup.py - Crash tips is enabled. You can set your environment variable to CRASH_HANDLER=FALSE to disable it
[WARNING]No module named 'pycocotools'
WARNING ⚠️ The file 'yolo_nas_s.pt' appears to be improperly saved or formatted. For optimal results, use model.save('filename.pt') to correctly save YOLO models.
Traceback (most recent call last):
  File "/srv/yolo-env/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/srv/yolo-env/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 807, in entrypoint
    model = YOLO(model, task=task)
  File "/srv/yolo-env/lib/python3.10/site-packages/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/srv/yolo-env/lib/python3.10/site-packages/ultralytics/engine/model.py", line 142, in __init__
    self._load(model, task=task)
  File "/srv/yolo-env/lib/python3.10/site-packages/ultralytics/engine/model.py", line 294, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/srv/yolo-env/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 855, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/srv/yolo-env/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 809, in torch_safe_load
    ckpt = {"model": ckpt.model}
  File "/srv/yolo-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'YoloNAS_S' object has no attribute 'model'
```

This happens for all three of the `yolo_nas` models in the 8.2 release.  Are there plans to fix this?  Thanks!

**Comment by glenn-jocher** [comment]
Hi @joe248,

Thank you for bringing this to our attention. Please verify if the issue persists with the latest version of the Ultralytics package. If it does, we are actively working on a fix for the `yolo_nas` models and will update the community as soon as possible. Thank you for your patience.

**Comment by joe248** [comment]
Correct, I just updated to Ultralytics 8.2.79 and the issue persists.

**Comment by glenn-jocher** [comment]
Thank you for the update. We are aware of the issue with the `yolo_nas` models and are actively working on a fix. Please stay tuned for updates.

**Comment by TtopsBo** [comment]
> Thank you for the update. We are aware of the issue with the `yolo_nas` models and are actively working on a fix. Please stay tuned for updates.

Hello, could you provide an example for exporting yolo_nas? Either module YOLO or NAS couldn`t export it.

**Comment by glenn-jocher** [comment]
@TtopsBo thank you for your patience. Unfortunately, exporting `yolo_nas` models is currently not supported due to ongoing compatibility issues. We recommend using other YOLO models for export tasks until a fix is released.

**Comment by glenn-jocher** [comment]
Thank you for reporting this issue. Unfortunately, the `yolo_nas` models (`yolo_nas_s.pt`, `yolo_nas_m.pt`, and `yolo_nas_l.pt`) currently have compatibility issues with the latest Ultralytics package, and they are not fully supported at this time. We recommend using other YOLO models, such as YOLOv8 or YOLO11, for your tasks. If you need further assistance, feel free to ask.
