### ISSUE TITLE
When will high-resolution YOLO-World be added to repository? 

### ISSUE THREAD

**Issue by VasilevGrigoriy** [ultralytics/ultralytics#8745]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi there! 

When will high-resolution YOLO-World, which supports 1280x1280 resolution, be added? It appeared at 03.03.2024 in https://github.com/AILab-CVC/YOLO-World.

It would be great to try this model!

**Comment by glenn-jocher** [comment]
@VasilevGrigoriy hi! Thanks for reaching out and for doing your homework before asking. 🙌

We're always excited to incorporate new advancements into our repository. The high-resolution YOLO-World model you mentioned is indeed an interesting development. While we don't have a specific timeline for its addition to the Ultralytics YOLOv8 repo at the moment, we're constantly evaluating and integrating new models that can benefit the community.

Keep an eye on our [GitHub releases](https://github.com/ultralytics/ultralytics/releases) for updates. We appreciate your enthusiasm and suggestion! 🚀

Feel free to contribute or share any further thoughts you might have. Happy coding!
