### ISSUE TITLE
Is there function to visualise labeling for picture and txt with labeling ?

### ISSUE THREAD

**Issue by medphisiker** [ultralytics/ultralytics#8751]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Let's say our dataset had a fairly long transformation path:
Annotation in CVAT -> export to MS COCO keypoints dataset format -> convert to YOLOv8-pose format.

I get my dataset for YOLOv8-pose training.
But before that, I want to make sure that the markup has been converted in the right way =)

When we have a trained yolov8l-pose model, we can predict keypoints for some image and save yolov8l-pose result to text file with labeling for this image, and we can save a picture with visualisation of predicted bboxes and keypoint for this image.

```
from ultralytics import YOLO

model = YOLO("runs/pose/train/weights/best.pt")

# Predict with the model
results = model("path_to_image/img_000030.PNG", save=True, conf=0.15)
```
and I get output
```
image 1/1 /home/admin-gpu/Downloads/datasets/treska_points/train/images/frame_000030.PNG: 384x640 2 treskas, 71.9ms
Speed: 2.6ms preprocess, 71.9ms inference, 214.8ms postprocess per image at shape (1, 3, 384, 640)
Results saved to runs/pose/predict2
```

And I get image with visualisation of yolov8 prediction saved in catalog `runs/pose/predict2/frame_000030.PNG`.

Is there a function to render the labeling in a similar way for the path to the image and the text markup file passed to it?
The function would be useful for pre-visualization of the labeling from the dataset to make sure that everything is converted correctly =)

**Comment by glenn-jocher** [comment]
@medphisiker hello! 😊

It sounds like you're looking for a way to visually verify your dataset's annotations after conversion, which is a great practice for ensuring data quality. Currently, YOLOv8 doesn't include a built-in function specifically for rendering annotations directly from text files alongside images. However, you can achieve this by using some custom code.

A simple approach is to read the annotations from your text file and then use a library like OpenCV or Matplotlib to draw the keypoints and bounding boxes on the images. Here's a quick example using OpenCV:

```python
import cv2

def visualize_annotations(image_path, annotation_path):
    # Load the image
    image = cv2.imread(image_path)

    # Read annotations
    with open(annotation_path, 'r') as f:
        annotations = f.readlines()

    for ann in annotations:
        # Parse annotation, this will need to be adjusted based on your format
        x, y, w, h = map(int, ann.split()[1:5])  # Example for bbox, adjust for keypoints
        # Draw bounding box
        cv2.rectangle(image, (x, y), (x + w, y + h), (255, 0, 0), 2)

    # Display the image
    cv2.imshow('Annotated Image', image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

# Example usage
visualize_annotations('path_to_image/img_000030.PNG', 'path_to_annotations/img_000030.txt')
```

This code is a basic starting point and might need adjustments based on the exact format of your annotations. For keypoints, you'd adjust the parsing and drawing sections accordingly.

While this isn't a built-in YOLOv8 feature, it's a flexible method to check your annotations visually. Hope this helps! If you have further questions or need more assistance, feel free to ask.

**Comment by medphisiker** [comment]
The result of the script is shown below
![viz](https://github.com/ultralytics/ultralytics/assets/4876436/b6f793b2-fc9c-4ff4-9890-0a3383750838)

**Comment by medphisiker** [comment]
I was glad to do it and you gave me a great starting point.
Thank you, Glenn )

**Comment by glenn-jocher** [comment]
@medphisiker you're very welcome! 😊 I'm thrilled to hear that you found the starting point helpful. If you have any more questions or need further assistance as you continue working with YOLOv8, don't hesitate to reach out. Happy coding!
