### ISSUE TITLE
Yolo -  Package Import Keeps Crashing, Jupyter notebook Issue

### ISSUE THREAD

**Issue by nishantgautam020** [ultralytics/ultralytics#8758]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Install, Train, Other

### Bug

Hello, 
Unable to run Yolo Model via Jupyter Notebook

Kernel dies as soon as I execute the following command

<from ultralytics import YOLO>

And everytime I tried to execute the command jupyer kernel fails and restarts itself.

Only once the first time when I ran this command it ran successfully, I had to stop the training midway and after that unable to execute it.

Please advice here

### Environment

Laptop Macbook Pro
IDE : Jupyter Notebook

### Minimal Reproducible Example

from ultralytics import YOLO>

### Additional

N/A

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@nishantgautam020 hello! 👋 It seems like you're encountering an issue where your Jupyter Notebook kernel crashes when trying to import the YOLO model from Ultralytics. This can be frustrating, but let's see if we can resolve it together.

A common reason for such behavior could be related to resource constraints or installation issues. Here are a couple of steps you might consider:

1. **Ensure your environment is correctly set up**: Sometimes, reinstalling the Ultralytics YOLO package can help. Try running:
   ```bash
   pip install ultralytics --upgrade
   ```
   to make sure you have the latest version.

2. **Check for resource limitations**: Running deep learning models, especially during training, can be resource-intensive. Ensure your Jupyter Notebook has enough available resources. You might want to restart your computer to free up any locked resources.

3. **Use a virtual environment**: If not already doing so, using a virtual environment can help manage dependencies more effectively and could resolve the issue. You can create one using:
   ```bash
   python3 -m venv yolov8-env
   source yolov8-env/bin/activate
   pip install notebook ultralytics
   ```
   Then, try running your Jupyter Notebook from this environment.

If these steps don't resolve the issue, it might be helpful to check the Jupyter Notebook logs for any specific error messages that could give more insight into what's going wrong. 

Feel free to share any error messages or further details you encounter after trying these steps. We're here to help! 🚀

**Comment by glenn-jocher** [comment]
@nishantgautam020 That's fantastic news! 🎉 I'm thrilled to hear creating a separate environment resolved the issue. If you have any more questions or run into further challenges, don't hesitate to reach out. Happy coding with YOLOv8!

**Comment by nishantgautam020** [comment]
@glenn-jocher 

I have one additional thing to ask you.

I have trained yolo for epochs=20, and the model & results are saved in the runs folder/directory.

Is it possible to further train this model with additional epochs (lets say I want to train this model again for additional 20 epochs). --  IS IT POSSIBLE ??

I saw your **RESUME functionality** for the Interrupted training, not sure if this can work here (shown below):

```
from ultralytics import YOLO
**# Load a model
model = YOLO('path/to/last.pt')  # load a partially trained model
# Resume training
results = model.train(resume=True)**
```
```

As this functionality does not specifies number of additional epochs to be given.

Please advice

**Comment by glenn-jocher** [comment]
@nishantgautam020 Absolutely, you can continue training your model for additional epochs! 🚀 The `resume=True` option will continue training from where it left off, keeping track of the previous epoch count. To train for an additional 20 epochs after the initial 20, you just need to set your total epochs to 40 in your case. Here’s how you can do it:

```python
from ultralytics import YOLO

# Load the partially trained model
model = YOLO('path/to/last.pt')

# Resume training with the total epochs now set to 40
results = model.train(data='your_dataset.yaml', epochs=40, resume=True)
```

This way, the model picks up training from epoch 21 and continues up to epoch 40. Let me know if you have more questions!
