### ISSUE TITLE
Issue with the display of concrete class names when running on the server

### ISSUE THREAD

**Issue by zncj2fdx** [ultralytics/ultralytics#8763]
> model = YOLO(f`http://localhost:8000/yolo`, task=`detect`)
> results = model([image.jpg])

Output log:
![image](https://github.com/ultralytics/ultralytics/assets/138029282/46920f40-968e-4cd5-a639-dc2e023a7e2d)

In the names list are class1, class2, class3... Not specific class names, like dog, bike, car。

![image](https://github.com/ultralytics/ultralytics/assets/138029282/522ea8b3-2e60-479d-a49b-e8100705ba92)

What causes this problem and how can it be solved？

**Comment by glenn-jocher** [comment]
@zncj2fdx hello! It looks like the issue you're encountering is related to the model not loading the class names properly from your dataset's `*.yaml` file. This can happen if the path to your dataset's `*.yaml` file is not correctly specified or if the model is unable to access it. 🤔

To solve this, please ensure that your dataset's `*.yaml` file is correctly referenced in your model configuration. Here's a quick example of how you might specify the dataset configuration:

```python
model = YOLO('path/to/your/model.pt', task='detect', data='path/to/your/dataset.yaml')
results = model(['image.jpg'])
```

Make sure `'path/to/your/dataset.yaml'` correctly points to your dataset configuration file, which should include the class names under a `names` key, like so:

```yaml
# Example dataset.yaml content
train: path/to/train/images
val: path/to/val/images

nc: 3  # number of classes
names: ['dog', 'bike', 'car']
```

If your dataset's `*.yaml` file and class names are correctly set up and the issue persists, please double-check the server's access permissions to the file. 😊

Hope this helps! Let us know if you have any more questions.

**Comment by zncj2fdx** [comment]
> @zncj2fdx hello! It looks like the issue you're encountering is related to the model not loading the class names properly from your dataset's `*.yaml` file. This can happen if the path to your dataset's `*.yaml` file is not correctly specified or if the model is unable to access it. 🤔
> 
> To solve this, please ensure that your dataset's `*.yaml` file is correctly referenced in your model configuration. Here's a quick example of how you might specify the dataset configuration:
> 
> ```python
> model = YOLO('path/to/your/model.pt', task='detect', data='path/to/your/dataset.yaml')
> results = model(['image.jpg'])
> ```
> 
> Make sure `'path/to/your/dataset.yaml'` correctly points to your dataset configuration file, which should include the class names under a `names` key, like so:
> 
> ```yaml
> # Example dataset.yaml content
> train: path/to/train/images
> val: path/to/val/images
> 
> nc: 3  # number of classes
> names: ['dog', 'bike', 'car']
> ```
> 
> If your dataset's `*.yaml` file and class names are correctly set up and the issue persists, please double-check the server's access permissions to the file. 😊
> 
> Hope this helps! Let us know if you have any more questions.

Thank you for your reply. I have modified the code based on your suggestions
model = YOLO(f'http://localhost:8000/yolo', task='detect' ,data='D:\slze\demo\coco.yaml')
results = model(['D:\\slze\\demo\\yolov8_deploy\\dog.jpg'])
results[0].show()

output log:
TypeError: __init__() got an unexpected keyword argument 'data'

**Comment by glenn-jocher** [comment]
@zncj2fdx hey there! 😊 It seems like there's a little mix-up with the `data` parameter usage. In the current setup of YOLOv8, especially when initializing the model directly with a URL or local path, the `data` parameter isn't directly used in the `YOLO` class constructor. Instead, the class names and other dataset-specific configurations are expected to be part of the model file or accessible to the model in its environment.

If you're working with a custom dataset and need to specify class names, you might consider ensuring that the class names are correctly set up within your model's training configuration or within the model file itself if it supports that.

For loading custom class names for display purposes after loading the model, you might need to manually adjust the `names` attribute of your model object. Here's a quick workaround:

```python
model = YOLO(f'http://localhost:8000/yolo', task='detect')
model.names = ['dog', 'bike', 'car']  # Manually setting class names
results = model(['D:\\slze\\demo\\yolov8_deploy\\dog.jpg'])
results[0].show()
```

This approach manually sets the class names after the model is loaded. Please adjust the `model.names` list to match your actual class names.

Let me know if this helps or if you have any more questions!

**Comment by zncj2fdx** [comment]
> @zncj2fdx hey there! 😊 It seems like there's a little mix-up with the `data` parameter usage. In the current setup of YOLOv8, especially when initializing the model directly with a URL or local path, the `data` parameter isn't directly used in the `YOLO` class constructor. Instead, the class names and other dataset-specific configurations are expected to be part of the model file or accessible to the model in its environment.
> 
> If you're working with a custom dataset and need to specify class names, you might consider ensuring that the class names are correctly set up within your model's training configuration or within the model file itself if it supports that.
> 
> For loading custom class names for display purposes after loading the model, you might need to manually adjust the `names` attribute of your model object. Here's a quick workaround:
> 
> ```python
> model = YOLO(f'http://localhost:8000/yolo', task='detect')
> model.names = ['dog', 'bike', 'car']  # Manually setting class names
> results = model(['D:\\slze\\demo\\yolov8_deploy\\dog.jpg'])
> results[0].show()
> ```
> 
> This approach manually sets the class names after the model is loaded. Please adjust the `model.names` list to match your actual class names.
> 
> Let me know if this helps or if you have any more questions!

model = YOLO(f'http://localhost:8000/yolo', task='detect')
model.names = ['dog']
output log：
can't set attribute.

I did not use a custom dataset, I only need the category information of the Coco dataset.Is there any other solution available？thank u！

**Comment by glenn-jocher** [comment]
Hey @zncj2fdx! 😊 It looks like you're trying to use the COCO dataset's class names directly. If you're not using a custom dataset and just need the COCO class names, they should already be integrated within the YOLOv8 model you're using, especially if it's pretrained on COCO.

If you're encountering issues with class names not displaying correctly, it might be due to how the model is being loaded or accessed. Since directly setting `model.names` didn't work due to it being a read-only attribute, you shouldn't need to set class names manually for a COCO-pretrained model.

Could you try running your prediction again without modifying `model.names`? The COCO class names should automatically be used for predictions. Here's a simplified example:

```python
model = YOLO(f'http://localhost:8000/yolo', task='detect')
results = model(['D:\\slze\\demo\\yolov8_deploy\\dog.jpg'])
results[0].show()
```

If the class names still aren't displaying correctly, please ensure that the model file you're loading (`http://localhost:8000/yolo`) is indeed the correct and complete pretrained model. Sometimes, issues with class names can arise if the model file is incomplete or not properly configured.

Let me know how it goes or if there's anything else I can help with!

**Comment by zncj2fdx** [comment]
> Hey @zncj2fdx! 😊 It looks like you're trying to use the COCO dataset's class names directly. If you're not using a custom dataset and just need the COCO class names, they should already be integrated within the YOLOv8 model you're using, especially if it's pretrained on COCO.
> 
> If you're encountering issues with class names not displaying correctly, it might be due to how the model is being loaded or accessed. Since directly setting `model.names` didn't work due to it being a read-only attribute, you shouldn't need to set class names manually for a COCO-pretrained model.
> 
> Could you try running your prediction again without modifying `model.names`? The COCO class names should automatically be used for predictions. Here's a simplified example:
> 
> ```python
> model = YOLO(f'http://localhost:8000/yolo', task='detect')
> results = model(['D:\\slze\\demo\\yolov8_deploy\\dog.jpg'])
> results[0].show()
> ```
> 
> If the class names still aren't displaying correctly, please ensure that the model file you're loading (`http://localhost:8000/yolo`) is indeed the correct and complete pretrained model. Sometimes, issues with class names can arise if the model file is incomplete or not properly configured.
> 
> Let me know how it goes or if there's anything else I can help with!
    
This is the code I sent the request to the Triton server：
    triton_client = httpclient.InferenceServerClient(url='localhost:8000')

    image = Image.open('./dog.jpg')
    
    image = image.resize((640, 640), Image.Resampling.LANCZOS)
    image = np.asarray(image)
    image = image / 255
    image = np.expand_dims(image, axis=0)
    image = np.transpose(image, axes=[0, 3, 1, 2])
    image = image.astype(np.float32)

    inputs = []
    inputs.append(httpclient.InferInput('images', image.shape, "FP32"))
    inputs[0].set_data_from_numpy(image, binary_data=False)
    outputs = []
    outputs.append(httpclient.InferRequestedOutput('output0', binary_data=False,class_count=3))

    results = triton_client.infer('yolo', inputs=inputs, outputs=outputs)
    output_data0 = results.as_numpy('output0')
    print(output_data0.shape)
I hope the Triton server returns me the recognition result, how should I modify the code? thank u!

**Comment by KiSchnelle** [comment]
I found this to also happen.

When exporting as onnx and running with triton inference server the classes will be 0:class0 to 998:class998 unless you specify the data.yaml in the model.predict(data=data.yaml).

This obviously is quite troublesome if a use of the inference server is not having acess to the data.yaml file path.

I have so far not found a valid way to include or export the model correctly with the class name data.

Also for the segment task, the inference will even fail without data specified.

From all the issues i found here and posts i can not find a proper solution, LLM answers are apperently failing to provide a solution.

Anyone has one?
