### ISSUE TITLE
Create a numpy.ndarray from the result

### ISSUE THREAD

**Issue by merhovon** [ultralytics/ultralytics#877]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to get from the result a numpy.ndarray (similar to what is created by loading images with OpenCV) or tuple (pixels, width, height) where the image data is eight bits-per-pixel.

My program code is:

```
model = YOLO("yolov8n.pt")

cap = cv2.VideoCapture(0)
while True:
    ret, frame = cap.read()
    results = model.predict(source=frame, show=True, conf=0.70, stream=True, device=0)
    decode(results.numpy())
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()
```
When I do this, I get the following error message:

`AttributeError: 'generator' object has no attribute 'numpy'`

**Comment by Laughing-q** [comment]
@merhovon hi please refer to the usage in our docs. [https://docs.ultralytics.com/predict/](https://docs.ultralytics.com/predict/)
```python
model = YOLO("yolov8n.pt")

cap = cv2.VideoCapture(0)
while True:
    ret, frame = cap.read()
    results = model.predict(source=frame, show=True, conf=0.70, stream=True, device=0)
    for r in results:
        decode(r.numpy())
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()
```

**Comment by merhovon** [comment]
I had already tried this and received the following error message:
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by Laughing-q** [comment]
@merhovon oh you have to move tensors to cpu first.
```python
model = YOLO("yolov8n.pt")

cap = cv2.VideoCapture(0)
while True:
    ret, frame = cap.read()
    results = model.predict(source=frame, show=True, conf=0.70, stream=True, device=0)
    for r in results:
        decode(r.cpu().numpy())
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()
```
