### ISSUE TITLE
avi videos are not fully displayed in Apple Quicktime

### ISSUE THREAD

**Issue by lonnylundsten** [ultralytics/ultralytics#8770]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I've been running tracking on video using a custom yolov8 model. The saved video is avi format and, while the original video is 15 minutes long, the output from ultralytics is displayed as being 01:42 in QuickTime and will only play that length of video.

After re-running the model several times, I decided to try to play the saved output with a different video player. Using IINA or VLC (https://iina.io/ and https://www.videolan.org) the video plays fine and is displayed as a whole 15 minutes -- i.e., its correct! I am currently using macOS Sonoma 14.3.1 (23D60). So this is a comment just to let others know that if they have a similar problem, it may be the result of the video player used and not the output from ultralytics. 

Along these lines, can I specify which format to save the video in? I suspect that mov or mp4 may not have the same issue as the avi file does. AVI should probably not be the default format....

Inference run on colab:
```
Ultralytics YOLOv8.1.24 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
Setup complete ✅ (8 CPUs, 51.0 GB RAM, 26.4/201.2 GB disk)
```

**Comment by glenn-jocher** [comment]
@lonnylundsten hello! Thanks for sharing your experience and insights. It's indeed possible that the issue you encountered with the AVI format in QuickTime is related to the player's compatibility with certain video formats. 

To specify a different output format for your videos, such as MP4, which generally has broader support across video players including QuickTime, you can adjust the video saving part of your code. If you're using the `cv2.VideoWriter` in your script, you can specify the output format through the filename extension and the appropriate FourCC code. Here's a quick example on how to save your video as MP4:

```python
fourcc = cv2.VideoWriter_fourcc(*'mp4v')  # For MP4 format
out = cv2.VideoWriter('output.mp4', fourcc, 20.0, (640, 480))
```

Make sure to replace `(640, 480)` with the actual resolution of your frames. This should help you get your videos in a format that's more universally compatible, like MP4, which might not exhibit the same issues as AVI in QuickTime.

Hope this helps! Let us know if you have any more questions or if there's anything else we can do for you. 😊
