### ISSUE TITLE
Yolov8 C++ inference

### ISSUE THREAD

**Issue by Thunderzen** [ultralytics/ultralytics#8775]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Does yolov8 c++ inference contain the agnostic nms parameter used during inference in python?

**Comment by glenn-jocher** [comment]
@Thunderzen hello! 😊

Yes, YOLOv8 C++ inference supports the agnostic NMS parameter similar to its Python counterpart. You can enable it by setting the `agnostic` flag to `true` in your NMS function call. Here's a quick example:

```cpp
auto results = Detect(image, confThreshold, nmsThreshold, true); // The last 'true' is for agnostic NMS
```

Make sure to adjust `Detect` function parameters according to your actual function signature. Happy coding!
