### ISSUE TITLE
Yolov8n int8 quantized model is not performing inference on Google Coral USB TPU

### ISSUE THREAD

**Issue by vmukund36** [ultralytics/ultralytics#8776]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I had recently converted the yolov8n model to int8 tflite quantized model to perform a person detection inference on Coral USB TPU. However upon execution it threw a load error where it wasn't able to perform inference on the video using the said model. What could be the possible reasons for this to occur?

**Comment by glenn-jocher** [comment]
@vmukund36 hello! 😊 It seems like you're facing an issue with running an int8 quantized YOLOv8n model on the Google Coral USB TPU. A common reason for load errors in such scenarios could be compatibility issues between the model format and the TPU's requirements. 

Ensure that:
- The model is fully compatible with the Edge TPU runtime. This often involves not only quantization but also making sure the model operations are supported by the TPU.
- The TFLite model is compiled specifically for the Edge TPU using the [Edge TPU Compiler](https://coral.ai/docs/edgetpu/compiler/).

If you haven't already, try compiling your quantized TFLite model with the Edge TPU Compiler:

```bash
edgetpu_compiler -s your_model.tflite
```

This process will generate a `.tflite` file optimized for the Coral TPU. If there are operations in your model not supported by the TPU, the compiler will notify you.

If the issue persists, please share the exact error message you're encountering for more specific guidance.
