### ISSUE TITLE
Yolov8: obtain probabilities from inference

### ISSUE THREAD

**Issue by lesept777** [ultralytics/ultralytics#8780]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I try to run an inference with my trained model in python, I get an error.
Here is what I do:

```
from ultralytics import YOLO
model = YOLO('yolov8n-cls.yaml').load('runs/classify/yolov8n-cls-lr1e-3/weights/last.pt')
print('Predictions:')
files = ['data/test/bus/bus.jpg',  'data/test/metro/metro.jpg',  'data/test/shopping_mall/shopping.jpg',  'data/test/street_pedestrian/street.jpg']
for file in files:
    print(file)
    pred = model(file)
    print(pred)
    print(pred.probs)
```
I get the following error message:

> YOLOv8n-cls summary: 56 layers, 153866 parameters, 153866 gradients, 2.4 GFLOPs
> Transferred 86/86 items from pretrained weights
> Predictions:
> data/test/bus/bus.jpg
> 
> image 1/1 /data1/is156025/fa125436/Confluence/Yolo/data/test/bus/bus.jpg: 640x640 1 0.57, 9 0.37, 2 0.04, 7 0.01, 5 0.00, 1.7ms
> Speed: 19.0ms preprocess, 1.7ms inference, 0.1ms postprocess per image at shape (1, 3, 640, 640)
> [ultralytics.engine.results.Results object with attributes:
> 
> boxes: None
> keypoints: None
> masks: None
> names: {0: '0', 1: '1', 2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9'}
> obb: None
> orig_img: array([[[246, 255, 254],
>         [248, 255, 254],
>         [253, 255, 255],
>         ...,
>         [255, 255, 252],
>         [255, 255, 255],
>         [255, 255, 255]]], dtype=uint8)
> orig_shape: (597, 1182)
> path: '/data1/is156025/fa125436/Confluence/Yolo/data/test/bus/bus.jpg'
> probs: ultralytics.engine.results.Probs object
> save_dir: None
> speed: {'preprocess': 18.96977424621582, 'inference': 1.748800277709961, 'postprocess': 0.10561943054199219}]
> Traceback (most recent call last):
>   File "train_yolo.py", line 49, in <module>
>     print(pred.probs)
> AttributeError: 'list' object has no attribute 'probs'

What is the correct syntax?
Thanks for your help.

**Comment by HichTala** [comment]
Hi, 
Here `model` output a list, all you need to do is iterate through this list to get all you need, bellow the correct syntax:

```python
from ultralytics import YOLO
model = YOLO('yolov8n-cls.yaml').load('runs/classify/yolov8n-cls-lr1e-3/weights/last.pt')
print('Predictions:')
files = ['data/test/bus/bus.jpg',  'data/test/metro/metro.jpg',  'data/test/shopping_mall/shopping.jpg',  'data/test/street_pedestrian/street.jpg']
for file in files:
    print(file)
    preds= model(file)
    print(preds)
    for pred in preds:
        print(pred.probs)
```

**Comment by lesept777** [comment]
Thanks a lot, I'll try this very soon!

**Comment by glenn-jocher** [comment]
@lesept777 you're welcome! 😊 If you encounter any further questions or need assistance, don't hesitate to reach out. Happy coding!

**Comment by lesept777** [comment]
It works very well : I can get the class number with `pred.probs.top1`
Thanks a lot for your help!

**Comment by glenn-jocher** [comment]
@lesept777 that's great to hear! 😊 If you need further assistance or have more questions, feel free to ask. Happy coding!

**Comment by lesept777** [comment]
Sorry: another short question...
Is it possible not to have any information displayed during inference? I just need to get the result.

**Comment by glenn-jocher** [comment]
@lesept777 absolutely, you can achieve a silent inference by setting the `verbose` parameter to `False` when calling your model. Here's how you can do it:

```python
preds = model(file, verbose=False)
```

This will ensure that the inference runs quietly, giving you just the results you need. If there's anything else you need, just let me know! 😊

**Comment by lesept777** [comment]
Yes, it makes sense, thanks Glenn!

**Comment by glenn-jocher** [comment]
@lesept777 you're welcome! If you have any more questions or need assistance, feel free to ask. Happy coding! 😊
