### ISSUE TITLE
Tune weights dir will always be `last.pt`

### ISSUE THREAD

**Issue by finlaymorrison** [ultralytics/ultralytics#8791]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Hyperparameter Tuning

### Bug

When tuning the weights in `last.pt` will always be chosen. This is because [This line](https://github.com/ultralytics/ultralytics/blob/e45146f25d68fbb3d744c180e3f615653ce1be99/ultralytics/engine/tuner.py#L191) of code is run before the subprocess to run a training run is started, so `best.pt` will never exist, therefore `ckpt_file` will always point to `last.pt`

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@finlaymorrison good point, great fix, thank you for the PR!
