### ISSUE TITLE
onnx_inference in python 

### ISSUE THREAD

**Issue by DWendou** [ultralytics/ultralytics#880]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

where is onnx_inference.py？how to use python

### Additional

onnx python inference

**Comment by JustasBart** [comment]
Hi @DWendou I don't think that this is supported yet as of **8.0.32**:

![image](https://user-images.githubusercontent.com/40023722/217754575-d41cb344-6742-4e7c-aa85-61b75cc8b4ee.png)

You can find C++ ONNX inference code [here](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX) or else you'll have to wait for it to be implemented with python, good luck! :rocket:

**Comment by lavender-ling** [comment]
this is onnx-seg python inference
`import numbers
import os
import re

import cv2
import time
import torchvision
import random
import numpy as np
import onnxruntime as ort
import torch
import torch.nn.functional as F

def letterbox(im, new_shape=(1280, 1280), color=(114, 114, 114), auto=True, scaleup=True, stride=32):
    # Resize and pad image while meeting stride-multiple constraints
    shape = im.shape[:2]  # current shape [height, width]
    if isinstance(new_shape, int):
        new_shape = (new_shape, new_shape)

    # Scale ratio (new / old)
    r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])
    if not scaleup:  # only scale down, do not scale up (for better val mAP)
        r = min(r, 1.0)

    # Compute padding
    new_unpad = int(round(shape[1] * r)), int(round(shape[0] * r))
    dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]  # wh padding

    if auto:  # minimum rectangle
        dw, dh = np.mod(dw, stride), np.mod(dh, stride)  # wh padding

    dw /= 2  # divide padding into 2 sides
    dh /= 2

    if shape[::-1] != new_unpad:  # resize
        im = cv2.resize(im, new_unpad, interpolation=cv2.INTER_LINEAR)
    top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
    left, right = int(round(dw - 0.1)), int(round(dw + 0.1))
    im = cv2.copyMakeBorder(im, top, bottom, left, right, cv2.BORDER_CONSTANT, value=color)  # add border
    return im, r, (dw, dh)


def overlay(image, mask, color, alpha, resize=None):

    color = color[::-1]
    colored_mask = np.expand_dims(mask, 0).repeat(3, axis=0)
    colored_mask = np.moveaxis(colored_mask, 0, -1)
    masked = np.ma.MaskedArray(image, mask=colored_mask, fill_value=color)
    image_overlay = masked.filled()

    if resize is not None:
        image = cv2.resize(image.transpose(1, 2, 0), resize)
        image_overlay = cv2.resize(image_overlay.transpose(1, 2, 0), resize)

    image_combined = cv2.addWeighted(image, 1 - alpha, image_overlay, alpha, 0)

    return image_combined


def crop_mask(masks, boxes):

    n, h, w = masks.shape
    x1, y1, x2, y2 = torch.chunk(boxes[:, :, None], 4, 1)  # x1 shape(1,1,n)
    r = torch.arange(w, device=masks.device, dtype=x1.dtype)[None, None, :]  # rows shape(1,w,1)
    c = torch.arange(h, device=masks.device, dtype=x1.dtype)[None, :, None]  # cols shape(h,1,1)

    return masks * ((r >= x1) * (r < x2) * (c >= y1) * (c < y2))


def scale_image(im1_shape, masks, im0_shape, ratio_pad=None):

    # Rescale coordinates (xyxy) from im1_shape to im0_shape
    if ratio_pad is None:  # calculate from im0_shape
        gain = min(im1_shape[0] / im0_shape[0], im1_shape[1] / im0_shape[1])  # gain  = old / new
        pad = (im1_shape[1] - im0_shape[1] * gain) / 2, (im1_shape[0] - im0_shape[0] * gain) / 2  # wh padding
    else:
        pad = ratio_pad[1]
    top, left = int(pad[1]), int(pad[0])  # y, x
    bottom, right = int(im1_shape[0] - pad[1]), int(im1_shape[1] - pad[0])

    if len(masks.shape) < 2:
        raise ValueError(f'"len of masks shape" should be 2 or 3, but got {len(masks.shape)}')
    masks = masks[top:bottom, left:right]
    masks = cv2.resize(masks, (im0_shape[1], im0_shape[0]))

    if len(masks.shape) == 2:
        masks = masks[:, :, None]
    return masks


def process_mask(protos, masks_in, bboxes, shape, upsample=False):

    c, mh, mw = protos.shape  # CHW
    ih, iw = shape
    masks = (masks_in @ protos.float().view(c, -1)).sigmoid().view(-1, mh, mw)  # CHW

    downsampled_bboxes = bboxes.clone()
    downsampled_bboxes[:, 0] *= mw / iw
    downsampled_bboxes[:, 2] *= mw / iw
    downsampled_bboxes[:, 3] *= mh / ih
    downsampled_bboxes[:, 1] *= mh / ih

    masks = crop_mask(masks, downsampled_bboxes)  # CHW
    if upsample:
        masks = F.interpolate(masks[None], shape, mode='bilinear', align_corners=False)[0]  # CHW
    return masks.gt_(0.5)


def xywh2xyxy(x):
    """
    Convert bounding box coordinates from (x, y, width, height) format to (x1, y1, x2, y2) format where (x1, y1) is the
    top-left corner and (x2, y2) is the bottom-right corner.

    Args:
        x (np.ndarray) or (torch.Tensor): The input bounding box coordinates in (x, y, width, height) format.
    Returns:
        y (np.ndarray) or (torch.Tensor): The bounding box coordinates in (x1, y1, x2, y2) format.
    """
    y = x.clone() if isinstance(x, torch.Tensor) else np.copy(x)
    y[..., 0] = x[..., 0] - x[..., 2] / 2  # top left x
    y[..., 1] = x[..., 1] - x[..., 3] / 2  # top left y
    y[..., 2] = x[..., 0] + x[..., 2] / 2  # bottom right x
    y[..., 3] = x[..., 1] + x[..., 3] / 2  # bottom right y
    return y


def non_max_suppression(
        prediction,
        conf_thres=0.25,
        iou_thres=0.45,
        classes=None,
        agnostic=False,
        multi_label=False,
        labels=(),
        max_det=300,
        nm=0,  # number of masks
):

    # Checks
    assert 0 <= conf_thres <= 1, f'Invalid Confidence threshold {conf_thres}, valid values are between 0.0 and 1.0'
    assert 0 <= iou_thres <= 1, f'Invalid IoU {iou_thres}, valid values are between 0.0 and 1.0'
    if isinstance(prediction, (list, tuple)):  # YOLOv8 model in validation model, output = (inference_out, loss_out)
        prediction = prediction[0]  # select only inference output

    device = prediction.device
    mps = 'mps' in device.type  # Apple MPS
    if mps:  # MPS not fully supported yet, convert tensors to CPU before NMS
        prediction = prediction.cpu()
    bs = prediction.shape[0]  # batch size
    nc = prediction.shape[1] - nm - 4  # number of classes
    mi = 4 + nc  # mask start index
    xc = prediction[:, 4:mi].amax(1) > conf_thres  # candidates

    # Settings
    # min_wh = 2  # (pixels) minimum box width and height
    max_wh = 7680  # (pixels) maximum box width and height
    max_nms = 30000  # maximum number of boxes into torchvision.ops.nms()
    time_limit = 0.5 + 0.05 * bs  # seconds to quit after
    redundant = True  # require redundant detections
    multi_label &= nc > 1  # multiple labels per box (adds 0.5ms/img)
    merge = False  # use merge-NMS

    t = time.time()
    output = [torch.zeros((0, 6 + nm), device=prediction.device)] * bs
    for xi, x in enumerate(prediction):  # image index, image inference
        # Apply constraints
        x = x.transpose(0, -1)[xc[xi]]  # confidence

        # Cat apriori labels if autolabelling
        if labels and len(labels[xi]):
            lb = labels[xi]
            v = torch.zeros((len(lb), nc + nm + 5), device=x.device)
            v[:, :4] = lb[:, 1:5]  # box
            v[range(len(lb)), lb[:, 0].long() + 4] = 1.0  # cls
            x = torch.cat((x, v), 0)

        # If none remain process next image
        if not x.shape[0]:
            continue

        # Detections matrix nx6 (xyxy, conf, cls)
        box, cls, mask = x.split((4, nc, nm), 1)
        box = xywh2xyxy(box)  # center_x, center_y, width, height) to (x1, y1, x2, y2)
        if multi_label:
            i, j = (cls > conf_thres).nonzero(as_tuple=False).T
            x = torch.cat((box[i], x[i, 4 + j, None], j[:, None].float(), mask[i]), 1)
        else:  # best class only
            conf, j = cls.max(1, keepdim=True)
            x = torch.cat((box, conf, j.float(), mask), 1)[conf.view(-1) > conf_thres]

        # Filter by class
        if classes is not None:
            x = x[(x[:, 5:6] == torch.tensor(classes, device=x.device)).any(1)]

        # Apply finite constraint
        # Check shape
        n = x.shape[0]  # number of boxes
        if not n:  # no boxes
            continue
        x = x[x[:, 4].argsort(descending=True)[:max_nms]]  # sort by confidence and remove excess boxes

        # Batched NMS
        c = x[:, 5:6] * (0 if agnostic else max_wh)  # classes
        boxes, scores = x[:, :4] + c, x[:, 4]  # boxes (offset by class), scores
        i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
        i = i[:max_det]  # limit detections
        if merge and (1 < n < 3E3):  # Merge NMS (boxes merged using weighted mean)
            # update boxes as boxes(i,4) = weights(i,n) * boxes(n,4)
            iou = box_iou(boxes[i], boxes) > iou_thres  # iou matrix
            weights = iou * scores[None]  # box weights
            x[i, :4] = torch.mm(weights, x[:, :4]).float() / weights.sum(1, keepdim=True)  # merged boxes
            if redundant:
                i = i[iou.sum(1) > 1]  # require redundancy

        output[xi] = x[i]
        if mps:
            output[xi] = output[xi].to(device)
        if (time.time() - t) > time_limit:
            break  # time limit exceeded

    return output


def box_iou(box1, box2, eps=1e-7):
    # inter(N,M) = (rb(N,M,2) - lt(N,M,2)).clamp(0).prod(2)
    (a1, a2), (b1, b2) = box1.unsqueeze(1).chunk(2, 2), box2.unsqueeze(0).chunk(2, 2)
    inter = (torch.min(a2, b2) - torch.max(a1, b1)).clamp(0).prod(2)

    # IoU = inter / (area1 + area2 - inter)
    return inter / ((a2 - a1).prod(2) + (b2 - b1).prod(2) - inter + eps)


def scale_boxes(img1_shape, boxes, img0_shape, ratio_pad=None):

    if ratio_pad is None:  # calculate from img0_shape
        gain = min(img1_shape[0] / img0_shape[0], img1_shape[1] / img0_shape[1])  # gain  = old / new
        pad = (img1_shape[1] - img0_shape[1] * gain) / 2, (img1_shape[0] - img0_shape[0] * gain) / 2  # wh padding
    else:
        gain = ratio_pad[0][0]
        pad = ratio_pad[1]

    boxes[..., [0, 2]] -= pad[0]  # x padding
    boxes[..., [1, 3]] -= pad[1]  # y padding
    boxes[..., :4] /= gain
    clip_boxes(boxes, img0_shape)
    return boxes


def clip_boxes(boxes, shape):

    if isinstance(boxes, torch.Tensor):  # faster individually
        boxes[..., 0].clamp_(0, shape[1])  # x1
        boxes[..., 1].clamp_(0, shape[0])  # y1
        boxes[..., 2].clamp_(0, shape[1])  # x2
        boxes[..., 3].clamp_(0, shape[0])  # y2
    else:  # np.array (faster grouped)
        boxes[..., [0, 2]] = boxes[..., [0, 2]].clip(0, shape[1])  # x1, x2
        boxes[..., [1, 3]] = boxes[..., [1, 3]].clip(0, shape[0])  # y1, y2


def predict(pred):
    for i, det in enumerate(pred):
        if len(det):
            masks = process_mask(proto[i], det[:, 6:], det[:, :4], im.shape[2:], upsample=True)
            masks = masks.cpu().numpy()
            masks = np.moveaxis(masks, 0, -1)  # masks, (H, W, N)
            masks = scale_image(masks.shape[:2], masks, img.shape)
            masks = np.moveaxis(masks, -1, 0)  # masks, (N, H, W)

    return masks


def clip_segments(segments, shape):
    """
    It takes a list of line segments (x1,y1,x2,y2) and clips them to the image shape (height, width)

    Args:
      segments (list): a list of segments, each segment is a list of points, each point is a list of x,y
    coordinates
      shape (tuple): the shape of the image
    """
    if isinstance(segments, torch.Tensor):  # faster individually
        segments[:, 0].clamp_(0, shape[1])  # x
        segments[:, 1].clamp_(0, shape[0])  # y
    else:  # np.array (faster grouped)
        segments[:, 0] = segments[:, 0].clip(0, shape[1])  # x
        segments[:, 1] = segments[:, 1].clip(0, shape[0])  # y


def scale_segments(img1_shape, segments, img0_shape, ratio_pad=None, normalize=False):

    if ratio_pad is None:  # calculate from img0_shape
        gain = min(img1_shape[0] / img0_shape[0], img1_shape[1] / img0_shape[1])  # gain  = old / new
        pad = (img1_shape[1] - img0_shape[1] * gain) / 2, (img1_shape[0] - img0_shape[0] * gain) / 2  # wh padding
    else:
        gain = ratio_pad[0][0]
        pad = ratio_pad[1]

    segments[:, 0] -= pad[0]  # x padding
    segments[:, 1] -= pad[1]  # y padding
    segments /= gain
    clip_segments(segments, img0_shape)
    if normalize:
        segments[:, 0] /= img0_shape[1]  # width
        segments[:, 1] /= img0_shape[0]  # height

    return segments


def masks2segments(masks, strategy='largest'):

    segments = []
    for x in masks.int().cpu().numpy().astype('uint8'):
    # for x in masks.cpu().numpy().astype('uint8'):
        c = cv2.findContours(x, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)[0]
        if c:
            if strategy == 'concat':  # concatenate all segments
                c = np.concatenate([x.reshape(-1, 2) for x in c])
            elif strategy == 'largest':  # select largest segment
                c = np.array(c[np.array([len(x) for x in c]).argmax()]).reshape(-1, 2)
        else:
            c = np.zeros((0, 2))  # no segments found
        segments.append(c.astype('float32'))
    return segments


if __name__ == '__main__':
    w = ""
    imgdir = r''
    savedir = r''

    for imgname in os.listdir(imgdir):
        img = cv2.imread(imgdir + imgname)
        name = ['rectangle', 'circle', 'triangle', 'dimond', 'pentagon', 'octagon', 'other']

        cuda = torch.cuda.is_available()
        providers = ['CUDAExecutionProvider', 'CPUExecutionProvider'] if cuda else ['CPUExecutionProvider']
        session = ort.InferenceSession(w, providers=providers)

        image = img.copy()
        image, ratio, dwdh = letterbox(image, auto=False)
        image = image.transpose((2, 0, 1))
        image = np.expand_dims(image, 0)
        image = np.ascontiguousarray(image)
        im = image.astype(np.float32)
        im /= 255

        # ONNX inference
        input_name = session.get_inputs()[0].name
        pred = session.run(None, {input_name: im})[0]
        out = session.run(None, {input_name: im})[1]
        pred = torch.from_numpy(pred).cuda()
        proto = torch.from_numpy(out).cuda()
        pred = non_max_suppression(pred, conf_thres=0.5, iou_thres=0.5, nm=32)

        # overlay masks on original image
        masks = predict(pred)
        image_with_masks = np.copy(img)
        for mask_i in masks:
            image_with_masks = overlay(image_with_masks, mask_i,  color = [random.randint(0, 255)for _ in range(3)], alpha=0.3)
    
        cv2.imwrite(savedir + imgname, image_with_masks)



`

**Comment by DWendou** [comment]
> this is onnx-seg python inference `import numbers import os import re
> 
> import cv2 import time import torchvision import random import numpy as np import onnxruntime as ort import torch import torch.nn.functional as F
> 
> def letterbox(im, new_shape=(1280, 1280), color=(114, 114, 114), auto=True, scaleup=True, stride=32): # Resize and pad image while meeting stride-multiple constraints shape = im.shape[:2] # current shape [height, width] if isinstance(new_shape, int): new_shape = (new_shape, new_shape)
> 
> ```
> # Scale ratio (new / old)
> r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])
> if not scaleup:  # only scale down, do not scale up (for better val mAP)
>     r = min(r, 1.0)
> 
> # Compute padding
> new_unpad = int(round(shape[1] * r)), int(round(shape[0] * r))
> dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]  # wh padding
> 
> if auto:  # minimum rectangle
>     dw, dh = np.mod(dw, stride), np.mod(dh, stride)  # wh padding
> 
> dw /= 2  # divide padding into 2 sides
> dh /= 2
> 
> if shape[::-1] != new_unpad:  # resize
>     im = cv2.resize(im, new_unpad, interpolation=cv2.INTER_LINEAR)
> top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
> left, right = int(round(dw - 0.1)), int(round(dw + 0.1))
> im = cv2.copyMakeBorder(im, top, bottom, left, right, cv2.BORDER_CONSTANT, value=color)  # add border
> return im, r, (dw, dh)
> ```
> 
> def overlay(image, mask, color, alpha, resize=None):
> 
> ```
> color = color[::-1]
> colored_mask = np.expand_dims(mask, 0).repeat(3, axis=0)
> colored_mask = np.moveaxis(colored_mask, 0, -1)
> masked = np.ma.MaskedArray(image, mask=colored_mask, fill_value=color)
> image_overlay = masked.filled()
> 
> if resize is not None:
>     image = cv2.resize(image.transpose(1, 2, 0), resize)
>     image_overlay = cv2.resize(image_overlay.transpose(1, 2, 0), resize)
> 
> image_combined = cv2.addWeighted(image, 1 - alpha, image_overlay, alpha, 0)
> 
> return image_combined
> ```
> 
> def crop_mask(masks, boxes):
> 
> ```
> n, h, w = masks.shape
> x1, y1, x2, y2 = torch.chunk(boxes[:, :, None], 4, 1)  # x1 shape(1,1,n)
> r = torch.arange(w, device=masks.device, dtype=x1.dtype)[None, None, :]  # rows shape(1,w,1)
> c = torch.arange(h, device=masks.device, dtype=x1.dtype)[None, :, None]  # cols shape(h,1,1)
> 
> return masks * ((r >= x1) * (r < x2) * (c >= y1) * (c < y2))
> ```
> 
> def scale_image(im1_shape, masks, im0_shape, ratio_pad=None):
> 
> ```
> # Rescale coordinates (xyxy) from im1_shape to im0_shape
> if ratio_pad is None:  # calculate from im0_shape
>     gain = min(im1_shape[0] / im0_shape[0], im1_shape[1] / im0_shape[1])  # gain  = old / new
>     pad = (im1_shape[1] - im0_shape[1] * gain) / 2, (im1_shape[0] - im0_shape[0] * gain) / 2  # wh padding
> else:
>     pad = ratio_pad[1]
> top, left = int(pad[1]), int(pad[0])  # y, x
> bottom, right = int(im1_shape[0] - pad[1]), int(im1_shape[1] - pad[0])
> 
> if len(masks.shape) < 2:
>     raise ValueError(f'"len of masks shape" should be 2 or 3, but got {len(masks.shape)}')
> masks = masks[top:bottom, left:right]
> masks = cv2.resize(masks, (im0_shape[1], im0_shape[0]))
> 
> if len(masks.shape) == 2:
>     masks = masks[:, :, None]
> return masks
> ```
> 
> def process_mask(protos, masks_in, bboxes, shape, upsample=False):
> 
> ```
> c, mh, mw = protos.shape  # CHW
> ih, iw = shape
> masks = (masks_in @ protos.float().view(c, -1)).sigmoid().view(-1, mh, mw)  # CHW
> 
> downsampled_bboxes = bboxes.clone()
> downsampled_bboxes[:, 0] *= mw / iw
> downsampled_bboxes[:, 2] *= mw / iw
> downsampled_bboxes[:, 3] *= mh / ih
> downsampled_bboxes[:, 1] *= mh / ih
> 
> masks = crop_mask(masks, downsampled_bboxes)  # CHW
> if upsample:
>     masks = F.interpolate(masks[None], shape, mode='bilinear', align_corners=False)[0]  # CHW
> return masks.gt_(0.5)
> ```
> 
> def xywh2xyxy(x): """ Convert bounding box coordinates from (x, y, width, height) format to (x1, y1, x2, y2) format where (x1, y1) is the top-left corner and (x2, y2) is the bottom-right corner.
> 
> ```
> Args:
>     x (np.ndarray) or (torch.Tensor): The input bounding box coordinates in (x, y, width, height) format.
> Returns:
>     y (np.ndarray) or (torch.Tensor): The bounding box coordinates in (x1, y1, x2, y2) format.
> """
> y = x.clone() if isinstance(x, torch.Tensor) else np.copy(x)
> y[..., 0] = x[..., 0] - x[..., 2] / 2  # top left x
> y[..., 1] = x[..., 1] - x[..., 3] / 2  # top left y
> y[..., 2] = x[..., 0] + x[..., 2] / 2  # bottom right x
> y[..., 3] = x[..., 1] + x[..., 3] / 2  # bottom right y
> return y
> ```
> 
> def non_max_suppression( prediction, conf_thres=0.25, iou_thres=0.45, classes=None, agnostic=False, multi_label=False, labels=(), max_det=300, nm=0, # number of masks ):
> 
> ```
> # Checks
> assert 0 <= conf_thres <= 1, f'Invalid Confidence threshold {conf_thres}, valid values are between 0.0 and 1.0'
> assert 0 <= iou_thres <= 1, f'Invalid IoU {iou_thres}, valid values are between 0.0 and 1.0'
> if isinstance(prediction, (list, tuple)):  # YOLOv8 model in validation model, output = (inference_out, loss_out)
>     prediction = prediction[0]  # select only inference output
> 
> device = prediction.device
> mps = 'mps' in device.type  # Apple MPS
> if mps:  # MPS not fully supported yet, convert tensors to CPU before NMS
>     prediction = prediction.cpu()
> bs = prediction.shape[0]  # batch size
> nc = prediction.shape[1] - nm - 4  # number of classes
> mi = 4 + nc  # mask start index
> xc = prediction[:, 4:mi].amax(1) > conf_thres  # candidates
> 
> # Settings
> # min_wh = 2  # (pixels) minimum box width and height
> max_wh = 7680  # (pixels) maximum box width and height
> max_nms = 30000  # maximum number of boxes into torchvision.ops.nms()
> time_limit = 0.5 + 0.05 * bs  # seconds to quit after
> redundant = True  # require redundant detections
> multi_label &= nc > 1  # multiple labels per box (adds 0.5ms/img)
> merge = False  # use merge-NMS
> 
> t = time.time()
> output = [torch.zeros((0, 6 + nm), device=prediction.device)] * bs
> for xi, x in enumerate(prediction):  # image index, image inference
>     # Apply constraints
>     x = x.transpose(0, -1)[xc[xi]]  # confidence
> 
>     # Cat apriori labels if autolabelling
>     if labels and len(labels[xi]):
>         lb = labels[xi]
>         v = torch.zeros((len(lb), nc + nm + 5), device=x.device)
>         v[:, :4] = lb[:, 1:5]  # box
>         v[range(len(lb)), lb[:, 0].long() + 4] = 1.0  # cls
>         x = torch.cat((x, v), 0)
> 
>     # If none remain process next image
>     if not x.shape[0]:
>         continue
> 
>     # Detections matrix nx6 (xyxy, conf, cls)
>     box, cls, mask = x.split((4, nc, nm), 1)
>     box = xywh2xyxy(box)  # center_x, center_y, width, height) to (x1, y1, x2, y2)
>     if multi_label:
>         i, j = (cls > conf_thres).nonzero(as_tuple=False).T
>         x = torch.cat((box[i], x[i, 4 + j, None], j[:, None].float(), mask[i]), 1)
>     else:  # best class only
>         conf, j = cls.max(1, keepdim=True)
>         x = torch.cat((box, conf, j.float(), mask), 1)[conf.view(-1) > conf_thres]
> 
>     # Filter by class
>     if classes is not None:
>         x = x[(x[:, 5:6] == torch.tensor(classes, device=x.device)).any(1)]
> 
>     # Apply finite constraint
>     # Check shape
>     n = x.shape[0]  # number of boxes
>     if not n:  # no boxes
>         continue
>     x = x[x[:, 4].argsort(descending=True)[:max_nms]]  # sort by confidence and remove excess boxes
> 
>     # Batched NMS
>     c = x[:, 5:6] * (0 if agnostic else max_wh)  # classes
>     boxes, scores = x[:, :4] + c, x[:, 4]  # boxes (offset by class), scores
>     i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
>     i = i[:max_det]  # limit detections
>     if merge and (1 < n < 3E3):  # Merge NMS (boxes merged using weighted mean)
>         # update boxes as boxes(i,4) = weights(i,n) * boxes(n,4)
>         iou = box_iou(boxes[i], boxes) > iou_thres  # iou matrix
>         weights = iou * scores[None]  # box weights
>         x[i, :4] = torch.mm(weights, x[:, :4]).float() / weights.sum(1, keepdim=True)  # merged boxes
>         if redundant:
>             i = i[iou.sum(1) > 1]  # require redundancy
> 
>     output[xi] = x[i]
>     if mps:
>         output[xi] = output[xi].to(device)
>     if (time.time() - t) > time_limit:
>         break  # time limit exceeded
> 
> return output
> ```
> 
> def box_iou(box1, box2, eps=1e-7): # inter(N,M) = (rb(N,M,2) - lt(N,M,2)).clamp(0).prod(2) (a1, a2), (b1, b2) = box1.unsqueeze(1).chunk(2, 2), box2.unsqueeze(0).chunk(2, 2) inter = (torch.min(a2, b2) - torch.max(a1, b1)).clamp(0).prod(2)
> 
> ```
> # IoU = inter / (area1 + area2 - inter)
> return inter / ((a2 - a1).prod(2) + (b2 - b1).prod(2) - inter + eps)
> ```
> 
> def scale_boxes(img1_shape, boxes, img0_shape, ratio_pad=None):
> 
> ```
> if ratio_pad is None:  # calculate from img0_shape
>     gain = min(img1_shape[0] / img0_shape[0], img1_shape[1] / img0_shape[1])  # gain  = old / new
>     pad = (img1_shape[1] - img0_shape[1] * gain) / 2, (img1_shape[0] - img0_shape[0] * gain) / 2  # wh padding
> else:
>     gain = ratio_pad[0][0]
>     pad = ratio_pad[1]
> 
> boxes[..., [0, 2]] -= pad[0]  # x padding
> boxes[..., [1, 3]] -= pad[1]  # y padding
> boxes[..., :4] /= gain
> clip_boxes(boxes, img0_shape)
> return boxes
> ```
> 
> def clip_boxes(boxes, shape):
> 
> ```
> if isinstance(boxes, torch.Tensor):  # faster individually
>     boxes[..., 0].clamp_(0, shape[1])  # x1
>     boxes[..., 1].clamp_(0, shape[0])  # y1
>     boxes[..., 2].clamp_(0, shape[1])  # x2
>     boxes[..., 3].clamp_(0, shape[0])  # y2
> else:  # np.array (faster grouped)
>     boxes[..., [0, 2]] = boxes[..., [0, 2]].clip(0, shape[1])  # x1, x2
>     boxes[..., [1, 3]] = boxes[..., [1, 3]].clip(0, shape[0])  # y1, y2
> ```
> 
> def predict(pred): for i, det in enumerate(pred): if len(det): masks = process_mask(proto[i], det[:, 6:], det[:, :4], im.shape[2:], upsample=True) masks = masks.cpu().numpy() masks = np.moveaxis(masks, 0, -1) # masks, (H, W, N) masks = scale_image(masks.shape[:2], masks, img.shape) masks = np.moveaxis(masks, -1, 0) # masks, (N, H, W)
> 
> ```
> return masks
> ```
> 
> def clip_segments(segments, shape): """ It takes a list of line segments (x1,y1,x2,y2) and clips them to the image shape (height, width)
> 
> ```
> Args:
>   segments (list): a list of segments, each segment is a list of points, each point is a list of x,y
> coordinates
>   shape (tuple): the shape of the image
> """
> if isinstance(segments, torch.Tensor):  # faster individually
>     segments[:, 0].clamp_(0, shape[1])  # x
>     segments[:, 1].clamp_(0, shape[0])  # y
> else:  # np.array (faster grouped)
>     segments[:, 0] = segments[:, 0].clip(0, shape[1])  # x
>     segments[:, 1] = segments[:, 1].clip(0, shape[0])  # y
> ```
> 
> def scale_segments(img1_shape, segments, img0_shape, ratio_pad=None, normalize=False):
> 
> ```
> if ratio_pad is None:  # calculate from img0_shape
>     gain = min(img1_shape[0] / img0_shape[0], img1_shape[1] / img0_shape[1])  # gain  = old / new
>     pad = (img1_shape[1] - img0_shape[1] * gain) / 2, (img1_shape[0] - img0_shape[0] * gain) / 2  # wh padding
> else:
>     gain = ratio_pad[0][0]
>     pad = ratio_pad[1]
> 
> segments[:, 0] -= pad[0]  # x padding
> segments[:, 1] -= pad[1]  # y padding
> segments /= gain
> clip_segments(segments, img0_shape)
> if normalize:
>     segments[:, 0] /= img0_shape[1]  # width
>     segments[:, 1] /= img0_shape[0]  # height
> 
> return segments
> ```
> 
> def masks2segments(masks, strategy='largest'):
> 
> ```
> segments = []
> for x in masks.int().cpu().numpy().astype('uint8'):
> # for x in masks.cpu().numpy().astype('uint8'):
>     c = cv2.findContours(x, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)[0]
>     if c:
>         if strategy == 'concat':  # concatenate all segments
>             c = np.concatenate([x.reshape(-1, 2) for x in c])
>         elif strategy == 'largest':  # select largest segment
>             c = np.array(c[np.array([len(x) for x in c]).argmax()]).reshape(-1, 2)
>     else:
>         c = np.zeros((0, 2))  # no segments found
>     segments.append(c.astype('float32'))
> return segments
> ```
> 
> if **name** == '**main**': w = "" imgdir = r'' savedir = r''
> 
> ```
> for imgname in os.listdir(imgdir):
>     img = cv2.imread(imgdir + imgname)
>     name = ['rectangle', 'circle', 'triangle', 'dimond', 'pentagon', 'octagon', 'other']
> 
>     cuda = torch.cuda.is_available()
>     providers = ['CUDAExecutionProvider', 'CPUExecutionProvider'] if cuda else ['CPUExecutionProvider']
>     session = ort.InferenceSession(w, providers=providers)
> 
>     image = img.copy()
>     image, ratio, dwdh = letterbox(image, auto=False)
>     image = image.transpose((2, 0, 1))
>     image = np.expand_dims(image, 0)
>     image = np.ascontiguousarray(image)
>     im = image.astype(np.float32)
>     im /= 255
> 
>     # ONNX inference
>     input_name = session.get_inputs()[0].name
>     pred = session.run(None, {input_name: im})[0]
>     out = session.run(None, {input_name: im})[1]
>     pred = torch.from_numpy(pred).cuda()
>     proto = torch.from_numpy(out).cuda()
>     pred = non_max_suppression(pred, conf_thres=0.5, iou_thres=0.5, nm=32)
> 
>     # overlay masks on original image
>     masks = predict(pred)
>     image_with_masks = np.copy(img)
>     for mask_i in masks:
>         image_with_masks = overlay(image_with_masks, mask_i,  color = [random.randint(0, 255)for _ in range(3)], alpha=0.3)
> 
>     cv2.imwrite(savedir + imgname, image_with_masks)
> ```
> 
> `

Thank you very much for your reply, this is very useful for me, thank you

**Comment by DWendou** [comment]
> Hi @DWendou I don't think that this is supported yet as of **8.0.32**:
> 
> ![image](https://user-images.githubusercontent.com/40023722/217754575-d41cb344-6742-4e7c-aa85-61b75cc8b4ee.png)
> 
> You can find C++ ONNX inference code [here](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX) or else you'll have to wait for it to be implemented with python, good luck! rocket

Thank you very much for your reply.

**Comment by DWendou** [comment]
> Hi @DWendou I don't think that this is supported yet as of **8.0.32**:
> 
> ![image](https://user-images.githubusercontent.com/40023722/217754575-d41cb344-6742-4e7c-aa85-61b75cc8b4ee.png)
> 
> You can find C++ ONNX inference code [here](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX) or else you'll have to wait for it to be implemented with python, good luck! rocket

Thank you very much for your reply.

**Comment by AyushExel** [comment]
See this official example for YOLOv8 ONNX opencv python inference https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-OpenCV-ONNX-Python
