### ISSUE TITLE
multiclass tracking

### ISSUE THREAD

**Issue by Sujie1528** [ultralytics/ultralytics#8806]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Does this repo's code support multiclass ByteTrack? Thanks in advance.

**Comment by glenn-jocher** [comment]
@Sujie1528 hello! Yes, our repository supports multiclass tracking with ByteTrack. You can easily use it by specifying the tracker configuration when using the `track` mode. Here's a quick example on how to do it:

```bash
yolo track model=yolov8n.pt source='your_video.mp4' tracker='bytetrack.yaml'
```

Make sure to adjust the `model` and `source` parameters to fit your needs. Happy tracking! 😊
