### ISSUE TITLE
Support to access the training logs when using the `model.train()` method

### ISSUE THREAD

**Issue by aaparikh** [ultralytics/ultralytics#881]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### What is currently there:
Currently, I am able to get the metrics after training the entire model. I do this by using the `model.val()` method.
A similar functionality to get the metrics for each epoch during the training process would be helpful.

Currently I am accessing the metrics in the following way:
```python
metrics = model.val()
print(f'Mean Average precision: {metrics.box.map}')
print(f'Mean Average precision 50: {metrics.box.map50}')
print(f'Mean Average precision 75: {metrics.box.map75}')
print(f'Mean precision: {metrics.box.mp}')
print(f'Mean recall: {metrics.box.mr}')
```

### What is requested:
I want to be able to get the training metrics such as `precision`, `recall`, `map` score for each epoch during the training process.

I want to be able to do something like this (just an example)
```python
#here metrics will have the metrics and other details stored per epoch
metrics = model.train(data=data, epochs=epochs, imgsz=imgsz)
for epoch_count, metric in enumerate(metrics):
    print(f'For epoch: {epoch_count}, Mean Average precision: {metrics.box.map}')
    print(f'For epoch: {epoch_count}, Mean Average precision 50: {metrics.box.map50}')
    print(f'For epoch: {epoch_count}, Mean Average precision 75: {metrics.box.map75}')
    print(f'For epoch: {epoch_count}, Mean precision: {metrics.box.mp}')
    print(f'For epoch: {epoch_count}, Mean recall: {metrics.box.mr}')
````

### Use case

This access to training logs would prove very useful when a user wants to visualise the training process.
For example: plotting the value of metrics against the number of epochs to understand how training is progressing.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@aaparikh hi, you can find the related metrics in your `save_dir/results.csv` file. Also you can find the plotted metrics here `save_dir/results.png`.

**Comment by aaparikh** [comment]
Alright thank you.

**Comment by Tengoles** [comment]
> @aaparikh hi, you can find the related metrics in your `save_dir/results.csv` file. Also you can find the plotted metrics here `save_dir/results.png`.

@Laughing-q You know a way of getting the path to the results.csv file?

**Comment by Laughing-q** [comment]
@Tengoles it's in `savd_dir`. And save_dir is composed of `project` and `name`. You can change save_dir by modify these two args. :)
`save_dir=project/name`.
like:
```python
results = model.train(data=xxx, project="xxx", name="xxx")
```
