### ISSUE TITLE
YOLO models architecture/structure

### ISSUE THREAD

**Issue by mmr689** [ultralytics/ultralytics#8813]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello everyone,

I would like to compare the structure of different YOLO models and also versions like `n`, `s` or `l`.

Is there a python command or document where I can see these?

Are the models based on papers or have they been modified? I want to write an article and need to know more about them.

Thank you very much!

**Comment by glenn-jocher** [comment]
@mmr689 hello! 😊

Great to hear about your interest in comparing the structure of different YOLO models and versions! You can easily view the architecture of any YOLO model directly in Python. Here's how you can do it for a YOLOv8 model, for example:

```python
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')  # You can replace 'yolov8n.pt' with any other model version like 'yolov8s.pt', 'yolov8l.pt', etc.

# Print the model architecture
print(model)
```

Regarding the basis of these models, YOLO versions are initially inspired by the concepts introduced in various research papers. However, at Ultralytics, we continuously innovate and optimize beyond the original papers to enhance performance, accuracy, and efficiency. This means the models you see, such as YOLOv8 `n`, `s`, `l`, etc., include modifications and improvements that might not be directly described in the original YOLO papers.

For detailed insights and updates on model improvements, I recommend keeping an eye on our [GitHub repository](https://github.com/ultralytics/ultralytics) and [documentation](https://docs.ultralytics.com/). These resources are continually updated with the latest information on our models and their development.

Good luck with your article! If you have more questions or need further assistance, feel free to ask. 📚

**Comment by mmr689** [comment]
Lol, I was in search of something more difficult than a simple print. 😅 Thanks a lot for your help!

One more question, is there a "tiny" or "n" version of your v3 model? Actually, what I'm doing is comparing the pre-trained model of different versions and additionally creating my own custom dataset focusing on power comsumptions for low power devices. Therefore, a small v3 needs to be included in this study.

Thank you very much for all your efforts.

**Comment by glenn-jocher** [comment]
@mmr689 hey there! 😄

Absolutely, for YOLOv3, we do have a "tiny" version which is perfect for scenarios like yours, focusing on low power consumption. You can load and use the YOLOv3 tiny model with the following code snippet:

```python
from ultralytics import YOLO

# Load YOLOv3 tiny model
model = YOLO('yolov3-tiny.pt')

# Now you can use the model for your tasks
```

This should fit right into your study comparing pre-trained models and analyzing their performance on low-power devices. If you have any more questions or need further assistance, feel free to reach out. Happy to help!

Good luck with your research! 🚀
