### ISSUE TITLE
Adding data that Yolo shouldn't detect

### ISSUE THREAD

**Issue by EVNN304** [ultralytics/ultralytics#8830]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello. A small question has appeared. Is it possible to add data to Yolov8 that the neural network should not react to (an image and an empty txt file without markup)? Thanks in advance for your answer.

**Comment by glenn-jocher** [comment]
@EVNN304 hello! 👋 Great question! Yes, you can indeed add images that YOLOv8 should not react to by including them in your dataset with corresponding empty `.txt` files (assuming you're using the YOLO format for annotations). This approach helps the model learn about "negative samples" or backgrounds without objects of interest. Just ensure that for each image with no objects, there's an empty `.txt` file with the same name in your annotations folder. Here's a quick example:

If you have an image named `image123.jpg` with no objects to detect, you should also have an empty file named `image123.txt` in your annotations directory.

This method is quite effective for improving the robustness of your model by teaching it what not to detect. Happy training! 🚀
