### ISSUE TITLE
Image resolution issue

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#8835]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

image

1240 * 300

Small object detection

During training
How to modify the training size reasonably

**Comment by glenn-jocher** [comment]
@monkeycc hello! 👋 For detecting small objects, you might want to consider using a higher resolution during training, as it can help the model learn finer details. However, keep in mind that increasing the resolution will also increase the computational cost.

You can adjust the training image size (`imgsz`) in your training command. For example, if you're aiming for a higher resolution, you might try setting it to 640 or even higher, depending on your hardware capabilities:

```bash
yolo train data=your_dataset.yaml model=yolov8n.pt imgsz=640
```

Just ensure that your chosen `imgsz` is divisible by 32 (which is a requirement for YOLO models). Experiment with different sizes to find the best balance between accuracy and performance for your specific use case. Happy training! 🚀
