### ISSUE TITLE
YOLOv9 training error

### ISSUE THREAD

**Issue by hu874** [ultralytics/ultralytics#8838]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I made an error while training YOLOv9, which prevented me from training. Could you please help me take a look
YOLOv9-c summary: 618 layers, 25549278 parameters, 25549262 gradients, 103.8 GFLOPs

DDP: debug command /root/anaconda3/envs/py38/bin/python -m torch.distributed.launch --nproc_per_node 2 --master_port 53799 /root/.config/Ultralytics/DDP/_temp_v3av50nt139691406037536.py
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Ultralytics YOLOv8.0.222 ? Python-3.8.13 torch-1.8.1+cu111 CUDA:0 (NVIDIA GeForce RTX 3090, 24253MiB)
                                                            CUDA:1 (NVIDIA GeForce RTX 3090, 24253MiB)
WARNING ?? Upgrade to torch>=2.0.0 for deterministic training.
TensorBoard: Start with 'tensorboard --logdir basedata0228/yolov9', view at http://localhost:6006/
Traceback (most recent call last):
  File "/root/.config/Ultralytics/DDP/_temp_v3av50nt139691406037536.py", line 12, in <module>
    results = trainer.train()
  File "/opt/data/private/huqian/ultralytics-main/ultralytics/engine/trainer.py", line 190, in train
Traceback (most recent call last):
  File "/root/.config/Ultralytics/DDP/_temp_v3av50nt139691406037536.py", line 12, in <module>
    results = trainer.train()
  File "/opt/data/private/huqian/ultralytics-main/ultralytics/engine/trainer.py", line 190, in train
    self._do_train(world_size)
  File "/opt/data/private/huqian/ultralytics-main/ultralytics/engine/trainer.py", line 286, in _do_train
    self._do_train(world_size)
  File "/opt/data/private/huqian/ultralytics-main/ultralytics/engine/trainer.py", line 286, in _do_train
    self._setup_train(world_size)
  File "/opt/data/private/huqian/ultralytics-main/ultralytics/engine/trainer.py", line 209, in _setup_train
    self._setup_train(world_size)
  File "/opt/data/private/huqian/ultralytics-main/ultralytics/engine/trainer.py", line 209, in _setup_train
    ckpt = self.setup_model()
  File "/opt/data/private/huqian/ultralytics-main/ultralytics/engine/trainer.py", line 460, in setup_model
    ckpt = self.setup_model()
  File "/opt/data/private/huqian/ultralytics-main/ultralytics/engine/trainer.py", line 460, in setup_model
    self.model = self.get_model(cfg=cfg, weights=weights, verbose=RANK == -1)  # calls Model(cfg, weights)
  File "/opt/data/private/huqian/ultralytics-main/ultralytics/models/yolo/detect/train.py", line 71, in get_model
    self.model = self.get_model(cfg=cfg, weights=weights, verbose=RANK == -1)  # calls Model(cfg, weights)
  File "/opt/data/private/huqian/ultralytics-main/ultralytics/models/yolo/detect/train.py", line 71, in get_model
    model = DetectionModel(cfg, nc=self.data['nc'], verbose=verbose and RANK == -1)
  File "/opt/data/private/huqian/ultralytics-main/ultralytics/nn/tasks.py", line 225, in __init__
    model = DetectionModel(cfg, nc=self.data['nc'], verbose=verbose and RANK == -1)
  File "/opt/data/private/huqian/ultralytics-main/ultralytics/nn/tasks.py", line 225, in __init__
    self.yaml = cfg if isinstance(cfg, dict) else yaml_model_load(cfg)  # cfg dict
  File "/opt/data/private/huqian/ultralytics-main/ultralytics/nn/tasks.py", line 743, in yaml_model_load
    self.yaml = cfg if isinstance(cfg, dict) else yaml_model_load(cfg)  # cfg dict
  File "/opt/data/private/huqian/ultralytics-main/ultralytics/nn/tasks.py", line 743, in yaml_model_load
    yaml_file = check_yaml(unified_path, hard=False) or check_yaml(path)
  File "/opt/data/private/huqian/ultralytics-main/ultralytics/utils/checks.py", line 468, in check_yaml
    yaml_file = check_yaml(unified_path, hard=False) or check_yaml(path)
  File "/opt/data/private/huqian/ultralytics-main/ultralytics/utils/checks.py", line 468, in check_yaml
    return check_file(file, suffix, hard=hard)
  File "/opt/data/private/huqian/ultralytics-main/ultralytics/utils/checks.py", line 460, in check_file
    return check_file(file, suffix, hard=hard)
  File "/opt/data/private/huqian/ultralytics-main/ultralytics/utils/checks.py", line 460, in check_file
    raise FileNotFoundError(f"'{file}' does not exist")
FileNotFoundError: 'yolov9-c.yaml' does not exist
    raise FileNotFoundError(f"'{file}' does not exist")
FileNotFoundError: 'yolov9-c.yaml' does not exist
Killing subprocess 92024
Killing subprocess 92025
Traceback (most recent call last):
  File "/root/anaconda3/envs/py38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/py38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/anaconda3/envs/py38/bin/python', '-u', '/root/.config/Ultralytics/DDP/_temp_v3av50nt139691406037536.py', '--local_rank=1']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/data/private/huqian/dms/ultralytics-yolov9/train.py", line 4, in <module>
    results = model.train(data="coco.yaml")
  File "/opt/data/private/huqian/dms/ultralytics-yolov9/ultralytics/engine/model.py", line 644, in train
    self.trainer.train()
  File "/opt/data/private/huqian/dms/ultralytics-yolov9/ultralytics/engine/trainer.py", line 203, in train
    raise e
  File "/opt/data/private/huqian/dms/ultralytics-yolov9/ultralytics/engine/trainer.py", line 201, in train
    subprocess.run(cmd, check=True)
  File "/root/anaconda3/envs/py38/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/root/anaconda3/envs/py38/bin/python', '-m', 'torch.distributed.launch', '--nproc_per_node', '2', '--master_port', '53799', '/root/.config/Ultralytics/DDP/_temp_v3av50nt139691406037536.py']' returned non-zero exit status 1.

Process finished with exit code 1

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@hu874 hey there! 👋 It looks like the error you're encountering is due to the `yolov9-c.yaml` file not being found. This could happen if the file path is incorrect or the file is missing from the expected directory. 

To resolve this, please ensure that:
1. The `yolov9-c.yaml` file exists in your project directory.
2. The file path specified in your training script is correct.

For example, if your `yolov9-c.yaml` is located in the `configs` folder, your training command should look something like this:

```bash
model.train(data="configs/yolov9-c.yaml")
```

If the file is indeed missing, you might need to create it or download it from the appropriate source. 

Hope this helps! Let me know if you have any more questions. 😊

**Comment by jabedala** [comment]
I have a program training with yolov9 in a conda and vscode environment. In both environments it sends the same error:

this is the command:
!python yolov9/train.py --batch 16 --epochs 50 --img 640 --device 0 --min-items 0 --close-mosaic 15 --data data_images_yolov9/data.yaml --weights yolov9/weights/yolov9-c.pt --cfg yolov9/models/detect/yolov9-c.yaml --hyp hyp.scratch-high.yaml

and this is the error:
 File "C:\Users\MSI\yolov9\utils\dataloaders.py", line 791, in load_mosaic
    img4, labels4, segments4 = copy_paste(img4, labels4, segments4, p=self.hyp['copy_paste'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI\yolov9\utils\augmentations.py", line 248, in copy_paste
    l, box, s = labels[j], boxes[j], segments[j]
                                     ~~~~~~~~^^^
IndexError: list index out of range

Could someone help me with this error, or any suggestion, thank you very much.

**Comment by glenn-jocher** [comment]
@jabedala hey there! 👋 It looks like the error you're encountering is related to the `copy_paste` augmentation function in your training script. The `IndexError: list index out of range` typically occurs when the code tries to access an index in a list that doesn't exist.

For this particular scenario, you might want to check if the `segments` list contains the same number of elements as the `labels` and `boxes` lists before calling the `copy_paste` function. This check will help ensure that you're not trying to access an index in the `segments` list that isn't available.

Here's a quick example of how you might implement this check:

```python
if len(segments) > j:
    l, box, s = labels[j], boxes[j], segments[j]
```

This conditional check ensures that you only try to access `segments[j]` if `j` is a valid index within the `segments` list.

Let me know if this helps or if you need further assistance! 😊

**Comment by MuhammadBilal848** [comment]
> @jabedala hey there! 👋 It looks like the error you're encountering is related to the `copy_paste` augmentation function in your training script. The `IndexError: list index out of range` typically occurs when the code tries to access an index in a list that doesn't exist.
> 
> For this particular scenario, you might want to check if the `segments` list contains the same number of elements as the `labels` and `boxes` lists before calling the `copy_paste` function. This check will help ensure that you're not trying to access an index in the `segments` list that isn't available.
> 
> Here's a quick example of how you might implement this check:
> 
> ```python
> if len(segments) > j:
>     l, box, s = labels[j], boxes[j], segments[j]
> ```
> 
> This conditional check ensures that you only try to access `segments[j]` if `j` is a valid index within the `segments` list.
> 
> Let me know if this helps or if you need further assistance! 😊

It worked but then came another error:
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 100.00 MiB. GPU 0 has a total capacity of 6.00 GiB of which 2.62 GiB is free. Of the allocated memory 2.24 GiB is allocated by PyTorch, and 78.16 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)`

PS: I am running this on my laptop, here is the GPU details.
![image](https://github.com/ultralytics/ultralytics/assets/57318407/3d9019fc-7fe4-4447-84e9-d20c00c79784)

**Comment by jabedala** [comment]
Hello Glenn Jocher, thanks for your prompt response, your code works, but I was also able to run it by putting the variable copy_paste: 0.0 in the hyp.scratch-high.yaml file. For the gelan-c architecture, but it did not work for the yolov9-c architecture.

**Comment by glenn-jocher** [comment]
@jabedala hey there! 🚀 Glad to hear the initial solution helped, and good job on also finding an alternative by adjusting `copy_paste: 0.0` in the `hyp.scratch-high.yaml` file. If it's not working for the yolov9-c architecture specifically, it might be due to architectural differences between models. Each architecture may handle data augmentation differently.

As a quick workaround, you could temporarily disable the copy-paste augmentation for yolov9-c by setting it to 0.0, just as you did, or delve into the architecture's handling of such augmentations to find a more tailored solution. 

If specific details of the yolov9-c handling are needed, feel free to share more info or snippets from that architecture's related code, and we could explore further! Keep up the great work! 🌟

**Comment by kha98led** [comment]
detect: weights=['/content/weights/gelan-c.pt'], source=/content/data/dog.jpeg, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.1, iou_thres=0.45, max_det=1000, device=0, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 1e33dbb Python-3.12.12 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

Traceback (most recent call last):
  File "/content/yolov9/detect.py", line 232, in <module>
    main(opt)
  File "/content/yolov9/detect.py", line 227, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 124, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/content/yolov9/detect.py", line 68, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/yolov9/models/common.py", line 684, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/yolov9/models/experimental.py", line 75, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/serialization.py", line 1548, in load
    raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
_pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, do those steps only if you trust the source of the checkpoint. 
	(1) In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL models.yolo.DetectionModel was not an allowed global by default. Please use `torch.serialization.add_safe_globals([models.yolo.DetectionModel])` or the `torch.serialization.safe_globals([models.yolo.DetectionModel])` context manager to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.
 I nned help please

**Comment by glenn-jocher** [comment]
@kha98led this traceback is coming from the **YOLOv9 repo `detect.py`**, where `torch.load()` is being called without specifying `weights_only`; on newer PyTorch the default changed and you’ll hit this unpickling error unless you explicitly allow full checkpoint loading (only do this if you trust the `.pt` source), e.g.:

```python
ckpt = torch.load(attempt_download(w), map_location="cpu", weights_only=False)
```

Ultralytics handles this automatically via our `torch_load()` wrapper (see the [Ultralytics `torch_load` reference](https://docs.ultralytics.com/reference/utils/patches/)), but since this GitHub issue is closed/stale, please open a new issue (ideally in the YOLOv9 repo you’re using) and include a text traceback plus a minimal repro per our [MRE guide](https://docs.ultralytics.com/help/minimum-reproducible-example/).
