### ISSUE TITLE
0 images, 400 backgrounds, 0 corrupt

### ISSUE THREAD

**Issue by AI-Specialist-Steph** [ultralytics/ultralytics#8839]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm expecting 400 images, at least 0 backgrounds and 0 corrupt. But the model does the opposite and its also unable to read the .txt files in the label folder. Any suggestions on what may be wrong?

Data was downloaded from open images dataset v7
console output: `/Dataset/train/Airplane... 0 images, 400 backgrounds, 0 corrupt: 100%|██████████|`
data structure: This is how my data directory is structured
data/
|-- Dataset/

|   |-- train/
        |  |-- airplane/
        |  |  |-- label/
        |  |  |  |-- image1.txt
        |  |  |  |-- image2.txt
        |  |  |-- image1.jpg
        |  |  |-- image2.jpg
|   |-- val/
...

format of image1.txt In the labels directory; 
Airplane 0.0 146.06531999999999 392.390656 325.405
Airplane 130.054144 112.877332 1022.476288 380.34121600000003

**Comment by glenn-jocher** [comment]
@AI-Specialist-Steph hello! It seems like there might be an issue with how the dataset is being recognized by the model. Here are a couple of things you might want to check:

1. **Path Specification**: Ensure the dataset path in your configuration file (usually `data.yaml` or similar) correctly points to your `Dataset/train/` directory. It should look something like this:
   ```yaml
   train: path/to/your/Dataset/train/
   val: path/to/your/Dataset/val/
   ```

2. **Directory Structure**: YOLO expects images and their corresponding label files to be in the same directory or in parallel directories. Your structure seems correct, but ensure that the `data.yaml` reflects this structure accurately.

3. **Label Format**: The label format seems to be incorrect. YOLO expects labels in the format `[class_id x_center y_center width height]`, all normalized to the image size. Make sure your labels follow this format. For example:
   ```
   0 0.5 0.5 0.2 0.2
   ```
   This represents a class_id of `0`, with a bounding box centered in the middle of the image, taking up 20% of the image in both width and height.

4. **File Extensions**: Ensure that your dataset does not contain any non-image files (like `.txt` files) in the image directories. YOLO might interpret these as 'backgrounds'.

If after checking these points the issue persists, it might be helpful to manually verify a few image-label pairs to ensure they're being read correctly. Also, consider running a small subset of your dataset to isolate the issue.

Hope this helps! Let us know if you have any more questions. 😊

**Comment by AI-Specialist-Steph** [comment]
Hi, thanks for your reply and help. The problem was with my label format and now it works as expected!

**Comment by glenn-jocher** [comment]
Double-check your `data.yaml` `train` path to ensure it points directly to the `train` directory and not accidentally to the `val` or root directory, as even a small typo can cause this.

**Comment by SilviaMg-root** [comment]
Thanks a lot! sorry for the inconvenience. My folder was mistakenly named lables! now it works perfectly

**Comment by glenn-jocher** [comment]
Great to hear you resolved the issue! 🚀 For others encountering similar problems, ensure your folder names exactly match the expected "labels" (not "lables") and follow the YOLO dataset structure outlined in our [Dataset YAML documentation](https://docs.ultralytics.com/datasets/detect/open-images-v7/). Always verify path definitions in your YAML file match your directory hierarchy. Happy training!
