### ISSUE TITLE
Hello, I want to bring n custom data in the prediction. Is it supported? For example, the given label data provides 4 additional values, and we hope that the prediction output will be the same 4 values.

### ISSUE THREAD

**Issue by shoogoome** [ultralytics/ultralytics#8845]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I want to bring n custom data in the prediction. Is it supported? For example, the given label data provides 4 additional values, and we hope that the prediction output will be the same 4 values.

**Comment by glenn-jocher** [comment]
@shoogoome hello! 😊 Yes, YOLOv8 supports custom data for predictions, including additional values beyond the standard bounding box coordinates and class labels. To achieve this, you'll need to ensure your dataset is properly formatted and your model is trained to predict these additional values.

For instance, if your label data includes 4 additional values (let's call them `val1`, `val2`, `val3`, `val4`), your label files should include these values alongside the standard format. When training your model, it will learn to predict these values based on your training data.

Here's a simplified example of how your label file might look:

```
<class_id> <x_center> <y_center> <width> <height> <val1> <val2> <val3> <val4>
```

Ensure your custom dataset is prepared accordingly, and modify your model's architecture if necessary to output these additional values. For detailed guidance on custom datasets and model modification, please refer to our [documentation](https://docs.ultralytics.com/).

If you have any more questions or need further assistance, feel free to ask. Happy coding! 🚀
