### ISSUE TITLE
0 label saved to runs/detect/predict/labels

### ISSUE THREAD

**Issue by solJimmaa** [ultralytics/ultralytics#8849]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi everyone,
I am using YOLOv8n-based model for object detection. Everything went well until I do the prediction. I have used the following line of code to save the bounding box values:

!yolo task=detect mode=predict model=/best.pt save_txt=True conf=0.5 source=/images

I can see that it detects the object in the image, but it doesn't save the bounding box values. I was wondering if you could help me if the problem is in the syntax or else?
Thanks
![image](https://github.com/ultralytics/ultralytics/assets/24875076/93e8b46d-c5f3-47fd-a25d-9e656ee98013)

**Comment by Paulineemu** [comment]
I think this is a bug, I did some predictions with object detection last week and it worked. Saved a txt file for every input with the coordinates of the masks and when I rerun the code today the labels folder is empty and no txt file gets generated.

**Comment by Burhan-Q** [comment]
I'm able to replicate this issue on Linux and Windows 10. Likely stems from changes in #8817 and results are saved to a single `text` file for me. I used

```py
from ultralytics import YOLO

model = YOLO("yolov8n.pt")
results = model.predict(save=True, save_txt=True) # uses ultralytics/assets images
```

![image](https://github.com/ultralytics/ultralytics/assets/62214284/c030e11e-29be-4a2c-b6e5-7680a24a14da)
