### ISSUE TITLE
YOLOv8.1.26 save_crop() -> Save cropped predictions to save_dir/cls/file_name.jpg doesnt work correctly anymore

### ISSUE THREAD

**Issue by Paulineemu** [ultralytics/ultralytics#8852]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I have trained a model which detects a frame on images. I now want to use the model to crop images according to the frame on the images. I use the parameter save_crop = True and its saves the cropped images within a subfolder crops/frame but not with the right names of the files. It doesnt keep the original file names and just wrights "label.jpg", "label1jpg" and so on. I used the same code last week and it worked. 

### Environment

Ultralytics YOLOv8.1.26 🚀 Python-3.10.12 torch-2.1.0+cu121 CPU (Intel Xeon 2.20GHz)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 26.6/107.7 GB disk)

### Minimal Reproducible Example

preds=mymodel(predict_folder, save=True, save_txt=True, project=predict_folder, max_det=1, save_crop=True)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Burhan-Q** [comment]
Likely related to #8849 and probably stems from #8817 

Primary issue:
- original label name not used for crops filename(s)

Replicated on Windows 10

```py
from ultralytics import YOLO

model = YOLO("yolov8n.pt")
results = model.predict(save=True, save_txt=True, save_crops=True)
```

Predict output directory tree
```
predict/crops
  ├───bus
  │       labels.jpg
  │
  ├───person
  │       labels.jpg
  │       labels2.jpg
  │       labels3.jpg
  │       labels4.jpg
  │       labels5.jpg
  │       labels6.jpg
  │
  ├───stop sign
  │       labels.jpg
  │
  └───tie
          labels.jpg
```

Thumbnails from `predict/crops/person` 
![image](https://github.com/ultralytics/ultralytics/assets/62214284/8d6f4ab8-abe5-4097-91a7-70d9fb2f4314)

**Comment by Houangnt** [comment]
> Likely related to #8849 and probably stems from #8817
> 
> Primary issue:
> 
> * original label name not used for crops filename(s)
> 
> Replicated on Windows 10
> 
> ```python
> from ultralytics import YOLO
> 
> model = YOLO("yolov8n.pt")
> results = model.predict(save=True, save_txt=True, save_crops=True)
> ```
> 
> Predict output directory tree
> 
> ```
> predict/crops
>   ├───bus
>   │       labels.jpg
>   │
>   ├───person
>   │       labels.jpg
>   │       labels2.jpg
>   │       labels3.jpg
>   │       labels4.jpg
>   │       labels5.jpg
>   │       labels6.jpg
>   │
>   ├───stop sign
>   │       labels.jpg
>   │
>   └───tie
>           labels.jpg
> ```
> 
> Thumbnails from `predict/crops/person` ![image](https://private-user-images.githubusercontent.com/62214284/311707120-8d6f4ab8-abe5-4097-91a7-70d9fb2f4314.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODI1MzIsIm5iZiI6MTcxMDM4MjIzMiwicGF0aCI6Ii82MjIxNDI4NC8zMTE3MDcxMjAtOGQ2ZjRhYjgtYWJlNS00MDk3LTkxYTctNzBkOWZiMmY0MzE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAyMTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwYTE5ZDhmOGZjY2Q0MWEzNzg1YWM4MGQ3ZDQ3NWRlZjQ2NzAyZDE2ZjRiNWI4YzJkNjE1NWNiMmZjYmFhY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jBhn_b_LP7twZ5BgE18V0efqTg77d2E7pRQk0NSCZG4)

https://github.com/Houangnt/yolov8_tracking/blob/main/save_crop_obb.py. You can try my code
