### ISSUE TITLE
Ascend devices 

### ISSUE THREAD

**Issue by johnnynunez** [ultralytics/ultralytics#8865]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Add to huawei devices

Example: https://medium.com/huawei-developers/adapting-the-yolov7-model-to-ascend-processors-baae63d7d5a3
https://www.reddit.com/user/HDGTurkey/comments/10vzwyz/core_components_of_ascend_processors/

for example YOLO(yolov8s.om) format

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@johnnynunez thank you for bringing up the idea of adapting YOLOv8 for Huawei Ascend devices! 🚀 While we currently don't have native support for Ascend processors, the articles you shared are indeed insightful for understanding how models like YOLO can be adapted for these devices.

For YOLOv8, exporting the model to ONNX format (`yolov8.onnx`) and then converting it to a compatible format for Ascend devices might be a viable pathway. Here's a quick example of how you can export a YOLOv8 model to ONNX:

```bash
yolo export model=yolov8n.pt format=onnx
```

After obtaining the ONNX model, you would typically use Huawei's Model Conversion Tool to convert the `.onnx` file to a `.om` format suitable for Ascend processors. While we don't have direct integration or a step-by-step guide for this process, the community or Huawei's developer resources might offer some guidance.

We appreciate your interest and suggestion! Keep an eye on our GitHub repo for any future updates or integrations. 🌟

**Comment by glenn-jocher** [comment]
Hi @johnnynunez, good news — native Huawei Ascend export and inference support has now shipped in Ultralytics. You can export directly to an Ascend `.om` model with:

```bash
yolo export model=yolo26n.pt format=ascend name=Ascend310B4
```

The exported model directory can then be loaded with Ultralytics for prediction or validation on Ascend hardware. Local export supports any Ascend SoC for which the matching CANN operator kernels are installed.

We have also launched managed Huawei exports on [Ultralytics Platform](https://platform.ultralytics.com) for Ascend310P1, Ascend310P3, Ascend310B1, and Ascend310B4. Full setup and usage details are in the [Huawei Ascend integration guide](https://docs.ultralytics.com/integrations/ascend/).

![Ultralytics Platform Huawei Ascend export](https://gist.githubusercontent.com/glenn-jocher/ddb7e1146039d729ddb891c6bc261e6b/raw/0af8f891222ccd17f783f8185b7c36f690e5b87d/ultralytics-platform-huawei-ascend-export.png)
