### ISSUE TITLE
trying to save only the mask without background image in yolov8 segmentation

### ISSUE THREAD

**Issue by coder-glitche** [ultralytics/ultralytics#8870]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hey @glenn-jocher  is there a way to only save the segmented mask part of image removing the background while using yolov8 segmentation?

**Comment by glenn-jocher** [comment]
@coder-glitche hello! 😊 Yes, you can save just the segmented mask without the background using YOLOv8 segmentation. After running the prediction and obtaining the `results`, you can access the `masks` attribute and save it. Here's a quick example:

```python
from ultralytics import YOLO
import cv2

# Load your model
model = YOLO('yolov8n-seg.pt')  # Adjust model path as needed

# Run prediction
results = model('path/to/your/image.jpg')

# Access the masks
masks = results[0].masks.numpy()

# Assuming single class segmentation for simplicity, adjust as needed
mask = masks[0]  # For multi-class, iterate over masks

# Save the mask
cv2.imwrite('segmented_mask.png', mask * 255)  # Convert mask to uint8 if needed
```

This will save the mask as a binary image where the segmented area is white, and the background is black. Adjust the indexing and saving logic based on your specific needs, especially if dealing with multi-class segmentation. Hope this helps!

**Comment by coder-glitche** [comment]
hey @glenn-jocher instead of saving binary mask is it possible to save original colored mask image


also this what i modified above code for unint8
# from ultralytics import YOLO
# import cv2

# # Load your model
# model = YOLO('/home/yogesh/yolov8/ultralytics/runs/detect/shape_seg/weights/best.pt')  # Adjust model path as needed
# input="/home/yogesh/yolov8/ultralytics/work/output1/test4/crops/Target/bluh"
# # Run prediction
# results = model.predict(source=input)  # Predict on a single image

# # Loop through the results
# for result in results:
#     # Access the masks
#     masks = result.masks.data.numpy()

#     # Assuming single class segmentation for simplicity, adjust as needed
#     mask = masks[0]  # For multi-class, iterate over masks

#     # Save the mask
#     cv2.imwrite('segmented_mask.png', mask.astype('uint8') * 255)

**Comment by coder-glitche** [comment]
hey @glenn-jocher i just found the answer in documentation...
from pathlib import Path

import cv2
import numpy as np
from ultralytics import YOLO

m = YOLO('yolov8n-seg.pt')
res = m.predict()

# iterate detection results 
for r in res:
    img = np.copy(r.orig_img)
    img_name = Path(r.path).stem

    # iterate each object contour 
    for ci,c in enumerate(r):
        label = c.names[c.boxes.cls.tolist().pop()]

        b_mask = np.zeros(img.shape[:2], np.uint8)

        # Create contour mask 
        contour = c.masks.xy.pop().astype(np.int32).reshape(-1, 1, 2)
        _ = cv2.drawContours(b_mask, [contour], -1, (255, 255, 255), cv2.FILLED)

        # Choose one:

        # OPTION-1: Isolate object with black background
        mask3ch = cv2.cvtColor(b_mask, cv2.COLOR_GRAY2BGR)
        isolated = cv2.bitwise_and(mask3ch, img)

        # OPTION-2: Isolate object with transparent background (when saved as PNG)
        isolated = np.dstack([img, b_mask])

        # OPTIONAL: detection crop (from either OPT1 or OPT2)
        x1, y1, x2, y2 = c.boxes.xyxy.cpu().numpy().squeeze().astype(np.int32)
        iso_crop = isolated[y1:y2, x1:x2]

        # TODO your actions go here

**Comment by glenn-jocher** [comment]
@coder-glitche hey there! 😊 Great to hear you found what you were looking for in the documentation! Your code snippet for isolating objects with their original colors either against a black or transparent background (and creating a detection crop) looks solid. If you have any more questions or need further assistance, feel free to reach out. Keep up the awesome work! 🚀

**Comment by z-mahmud22** [comment]
> @coder-glitche hello! 😊 Yes, you can save just the segmented mask without the background using YOLOv8 segmentation. After running the prediction and obtaining the `results`, you can access the `masks` attribute and save it. Here's a quick example:
> 
> ```python
> from ultralytics import YOLO
> import cv2
> 
> # Load your model
> model = YOLO('yolov8n-seg.pt')  # Adjust model path as needed
> 
> # Run prediction
> results = model('path/to/your/image.jpg')
> 
> # Access the masks
> masks = results[0].masks.numpy()
> 
> # Assuming single class segmentation for simplicity, adjust as needed
> mask = masks[0]  # For multi-class, iterate over masks
> 
> # Save the mask
> cv2.imwrite('segmented_mask.png', mask * 255)  # Convert mask to uint8 if needed
> ```
> 
> This will save the mask as a binary image where the segmented area is white, and the background is black. Adjust the indexing and saving logic based on your specific needs, especially if dealing with multi-class segmentation. Hope this helps!

Hi @glenn-jocher, thank you for the code snippet. I just wanted to add a correction. Running this code directly throws an error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-8-46aa0f28cf06>](https://localhost:8080/#) in <cell line: 17>()
     15 
     16 # Save the mask
---> 17 cv2.imwrite('segmented_mask.png', mask * 255)  # Convert mask to uint8 if needed

TypeError: unsupported operand type(s) for *: 'Masks' and 'int'
```
After a bit debugging, I found that even after this: 
```
# Access the masks
masks = results[0].masks.cpu().numpy()

# Assuming single class segmentation for simplicity, adjust as needed
mask = masks[0]  # For multi-class, iterate over masks 
```
The `mask` variable remains as a `Masks` object:
```
[1]: type(mask)
# prints out:
ultralytics.engine.results.Masks
def __init__(masks, orig_shape) -> None
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/results.py](https://localhost:8080/#)
A class for storing and manipulating detection masks.

Attributes:
    xy (list): A list of segments in pixel coordinates.
    xyn (list): A list of normalized segments.

Methods:
    cpu(): Returns the masks tensor on CPU memory.
    numpy(): Returns the masks tensor as a numpy array.
    cuda(): Returns the masks tensor on GPU memory.
    to(device, dtype): Returns the masks tensor with the specified device and dtype.
```
Hence, instead of this `masks = results[0].masks.numpy()`, **we can parse the data this way**: 
```
# Access the masks
masks = results[0].masks

# Assuming single class segmentation for simplicity, adjust as needed
mask = masks[0].data.squeeze().cpu().numpy() * 255  # For multi-class, iterate over masks
mask = mask.astype(np.uint8)

# Save the mask
cv2.imwrite('segmented_mask.png', mask)  # Convert mask to uint8 if needed
```
The above helped me get my desired binary mask.

**Comment by glenn-jocher** [comment]
Hey @z-mahmud22! 😄 Thanks for catching that! Your clarification and code correction are spot-on. Indeed, the proper way to access, convert to numpy, and save the mask involves calling `.data.squeeze().cpu().numpy()`. This ensures we're working with a numpy array that cv2 can handle for saving as an image. Your added `.astype(np.uint8)` is crucial for properly formatting the mask as a binary image. Great job and happy coding! 🚀

**Comment by NewerZeus** [comment]
May I ask if I have two segment classes such as `0: good  1:bad`,  does the `results[0].masks.xyn[0]` represent good? If not, what is the oder of this array?

**Comment by glenn-jocher** [comment]
Hi there! 😊 When you're working with multiple segment classes like `0: good`, `1: bad` in YOLOv8, the order of masks in `results[0].masks.xyn` corresponds to the order in which they were detected, not necessarily sorted by classes. 

To identify the class of each mask, you'd also want to check `results[0].boxes.cls` along with `results[0].masks.xyn`. Each mask is associated with a class in `results[0].boxes.cls` by index. So, to find masks specifically for "good" objects:

```python
good_indices = [i for i, cls in enumerate(results[0].boxes.cls) if cls == 0]
good_masks = [results[0].masks.xyn[i] for i in good_indices]
```

This way, you filter out masks for "good" objects. Hope that helps! Let me know if you have more questions.
