### ISSUE TITLE
Yolov8-p2 and Yolov8-rtdetr

### ISSUE THREAD

**Issue by deepukr007** [ultralytics/ultralytics#8872]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I was going through the model configurations and I saw several models other than standard ones.
Is there any document which is already present to know more about them or the problems they are trying to solve ?

If not , most models conf is easy to understand and I can imagine why are they present by looking at the names given for the model.

However , I quite didnt get what does these models do 
1) yolov8-rtdetr - as they both are detectors with different family. I saw configuration file and saw that rtdetr decoder is used in head for detection. Correct me if I am wrong
2)  yolov8-p2

**Comment by glenn-jocher** [comment]
@deepukr007 hello! 😊

Great questions! Let's dive into the specifics of these models:

1) **YOLOv8-RTDETR**: You're correct in observing that this model integrates aspects of the RTDETR (Real-Time Detection Transformer) architecture into the YOLO framework. The idea here is to leverage the strengths of transformer-based decoders for object detection tasks, aiming to improve accuracy and efficiency in real-time scenarios. The configuration you've seen specifies how the RTDETR decoder is incorporated into the detection head, enhancing the model's ability to handle complex scenes and varied object sizes.

2) **YOLOv8-P2**: This model is part of our efforts to explore different pyramid levels for feature extraction. "P2" refers to using features from a specific pyramid level, focusing on achieving a balance between speed and accuracy, particularly for smaller objects or fine-grained details. It's designed to optimize performance for specific use cases where such characteristics are crucial.

Unfortunately, as of now, we might not have extensive documentation on these experimental models, as they are part of ongoing research and development. We appreciate your understanding and patience as we work towards providing more detailed information and benchmarks for these models in the future.

If you have more questions or need further clarification, feel free to ask! 🚀

**Comment by wsy-yjys** [comment]
@glenn-jocher  Can you provide the performance of YOLOv8-RTDETR?

**Comment by glenn-jocher** [comment]
@wsy-yjys hello! 👋

The performance specifics for YOLOv8-RTDETR, including metrics like mAP, FPS, and resource utilization, are still being finalized as we continue to optimize the model. We aim to provide detailed benchmarks and comparisons as soon as they are available. Stay tuned to our updates!

Thank you for your interest and patience! 🚀
