### ISSUE TITLE
 ValueError: Cannot set tensor: Got value of type FLOAT32 but expected type UINT8 for input 0, name: serving_default_images:0

### ISSUE THREAD

**Issue by RafaelAndradeDEV** [ultralytics/ultralytics#8875]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

718       ValueError: If the interpreter could not set the tensor.
    719     """
--> 720     self._interpreter.SetTensor(tensor_index, value)
    721 
    722   def resize_tensor_input(self, input_index, tensor_size, strict=False):

ValueError: Cannot set tensor: Got value of type FLOAT32 but expected type UINT8 for input 0, name: serving_default_images:0 

I did quantized my tflite model, following this section: https://www.tensorflow.org/lite/performance/post_training_integer_quant#convert_using_integer-only_quantization
here is the code:
def representative_data_gen():

    dataset_size = 1
    data = os.listdir("/content/data/train")
    data = data[0:100]
    for i in data:
        if i.endswith(".txt"):
          continue
        else:
          im = imageio.imread((f'/content/data/train/{i}')) #data = imageio.imread("/content/data/test" + str(i) + ".jpg")
          data = [tf.image.resize_with_crop_or_pad(im, 1280, 1280)]
          data = np.reshape(data, [1, 1280, 1280, 3]
          yield [data.astype(np.float32)]

converter = tf.lite.TFLiteConverter.from_saved_model('/content/drive/MyDrive/ColabNotebooks/train_tf1280/weights/best_saved_model/')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
# Ensure that if any ops can't be quantized, the converter throws an error
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
# Set the input and output tensors to uint8 (APIs added in r2.3)
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

tflite_model_quant = converter.convert()
representative_data_gen()

When i try to use this quantizedd model in YOLO code, it's says that must be UINT8, but i already transformed the np.array from the img to UINT8, the model just don't accept

### Environment

Ultralytics YOLOv8.1.27 🚀 Python-3.10.12 torch-2.1.0+cu121 CPU (Intel Xeon 2.20GHz)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 29.0/107.7 GB disk)

### Minimal Reproducible Example

image = cv2.imread("/content/data/test/dd67c55c-bf20-4e7a-a9ba-401be5d3d635.jpg")
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image_rgb = np.uint8(image_rgb)

model = ultralytics.YOLO("/content/content/tflite_models/model_quant.tflite")
results = model(source=image_rgb, imgsz=1280, conf=0.4, line_width=1) #save_txt=True, save=True)
result = results[0].plot(line_width=1, conf=False)
cv2_imshow(result)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by RafaelAndradeDEV** [comment]
I'm still encountering same problem, even after test many forms to use "ultralytics.YOLO()", but every attempt failed. checked this line "assert image_rgb.dtype == np.uint8, "Image data must be UINT8"" and confirms that image_rgb is uint8 before a assign as source in model.

I've tried using tflite.interpreter to make this job and successfully achieve what was looking for, but other problem appeared, excess of box in predict results. Will implement some algorithms to reduce boxes like, NMS and others(try to use utils/ops.py from YOLO structure)

Thank you for your response in quite time!

**Comment by glenn-jocher** [comment]
@RafaelAndradeDEV hey there! 😊

It's great to hear you made some progress with `tflite.interpreter` and successfully managed to process your images! Regarding the excess boxes in predict results, implementing NMS (Non-Maximum Suppression) is indeed a solid approach to filter out overlapping boxes and reduce clutter.

If you're planning to use YOLO's `utils/ops.py` for NMS, here's a little snippet on how you might incorporate it with your detections:

```python
from ultralytics.utils import nms

# Assuming 'boxes' and 'scores' are your detections and their confidence scores
filtered_indices = nms(boxes, scores, iou_thresh=0.5)
filtered_boxes = boxes[filtered_indices]
```

Adjust the `iou_thresh` parameter to tune the NMS performance according to your needs.

Let me know if this works out for you or if you bump into more questions. I'm here to help! 🚀
