### ISSUE TITLE
Error reported while exporting to tensorrt

### ISSUE THREAD

**Issue by Sparklexa** [ultralytics/ultralytics#8877]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

`E:\Project\pythonProject\yolov8>yolo` export model=runs/detect/train11/weights/best.pt format=engine imgsz=(1365,1000) half=True``
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 64 but got size 63 for tensor number 1 in the list.

**Comment by Sparklexa** [comment]
Note: I deleted the last two detection heads and only kept the small target detection heads

**Comment by glenn-jocher** [comment]
@Sparklexa hello! It looks like the issue you're encountering might be related to the modifications you've made to the detection heads. When you remove detection heads, it can affect the tensor sizes expected during the export process, especially when exporting to formats like TensorRT which are sensitive to input and output tensor sizes.

Given that you've focused on small target detection heads by removing the last two detection heads, you'll need to ensure that the model's architecture defined in the code matches these changes. This includes adjusting any layers or operations that depend on the number of detection heads.

A quick suggestion would be to double-check the model definition and ensure that all references and dimensions are correctly adjusted to account for the removed detection heads. This might involve revisiting the model's `.yaml` configuration file or the script where the model architecture is defined.

If you're still facing issues, could you provide more details about the modifications you've made? This could help in pinpointing the exact cause of the size mismatch error. 🛠️

Hope this helps!
