### ISSUE TITLE
Why?The ReLU activation function is simpler than the SiLU activation function. But  the ReLU activation function is the inference speed slower  than the SiLU activation function.SiLU activation function. 

### ISSUE THREAD

**Issue by FAFUzxf** [ultralytics/ultralytics#8883]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hello! I did a simple experiment today, replacing the activation function SiLU() in YOLOv8 with ReLU(). From the experimental results, SiLU activation function has better training results and faster inference speed, but my question is: why is the inference speed slower when ReLU activation function is simpler? Thank you.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by FAFUzxf** [comment]
ok，Thank you!I will check the relevant information.

**Comment by glenn-jocher** [comment]
@FAFUzxf you're welcome! 😊 If you have any more questions or need assistance after checking the information, feel free to reach out. Happy coding!
