### ISSUE TITLE
Why couldn't I run multiprocessing?

### ISSUE THREAD

**Issue by kbratsy** [ultralytics/ultralytics#8884]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I want to perform multitasking on my detection tasks. I aim to divide my data set according to the number of transactions and start the detection processes accordingly. But you can increase the number of transactions by 1 or 2, 3, 4 etc. Changing it to does not make any difference in terms of processing time. I cannot perform these multiprocessing tasks with YOLOv8. I can only achieve multiprocessing operations by running two separate terminals. Sample code is below. Can you help me understand why?

```
import os
from ultralytics import YOLO
import time
import multiprocessing 
from random import shuffle

start_time = time.time()

def measure_elapsed_time(num_processes):
    end_time = time.time()
    elapsed_time = end_time - start_time
    minutes, seconds = divmod(elapsed_time, 60)
    hours, minutes = divmod(minutes, 60)
    log_content = f"Process started at: {time.ctime(start_time)}\n"
    log_content += f"Process ended at: {time.ctime(end_time)}\n"
    log_content += f"Elapsed time: {int(hours):02d}:{int(minutes):02d}:{int(seconds):02d}\n"
    file_name = f"multi_log_content_{num_processes}.txt"
    with open(file_name, 'w') as file:
        file.write(log_content)
    print(f"Log content for num_processes={num_processes} written to {file_name}")
def preprocess(main_directory):
    img_patterns = ['2_B_0_1', '2_B_1_1', '2_B_2_1', '2_F_0_1', '2_F_1_1', '2_F_2_1', '2_R_0_1', '2_R_1_1', '2_R_2_1',
                        '2_L_0_1', '2_L_1_1', '2_L_2_1']
    folder_list = [klasor for klasor in os.listdir(main_directory) if os.path.isdir(os.path.join(main_directory, klasor))]
    image_list = []
    for folder in folder_list:
        folder_path = os.path.join(main_directory, folder)
        for file in os.listdir(folder_path):
            if file.endswith('.jpg') and any(pattern in file for pattern in img_patterns):
                file_path = os.path.join(folder_path, file)
                image_list.append(file_path)
    return image_list
def YOLOprocess(images): 
    model = YOLO(r"..\runs\detect\train\weights\best.pt")
    for img in images:
        model.predict(source=os.path.join(images, img), conf=0.40, save=True, save_txt=True)
if __name__ == "__main__":
    num_processes=2
    main_directory =r"..\Dataset"
    all_images=preprocess(main_directory)
    processing = []
    images_subsets = [all_images[i::num_processes] for i in range(num_processes)]

    for i in range(len(images_subsets)):
        process = multiprocessing.Process(target=YOLOprocess, args=(images_subsets[i],))
        processing.append(process)
    for process in processing:
        process.start()
        process.join()
    measure_elapsed_time(num_processes)
```

In approximately 6 thousand images, when the multiprocess number is 1, the detection process takes 3 minutes and 3 seconds. With the same data, when the multiprocess number is 2, the detection process takes 3 minutes and 4 seconds, which is a similar time. While we expect a visible difference, it is approximately the same between periods.

**Comment by glenn-jocher** [comment]
@kbratsy hello! 👋

It looks like you're encountering an issue with multiprocessing in Python, specifically when trying to parallelize YOLOv8 detection tasks. From your code snippet, the issue might be related to how the processes are being joined. Currently, you're starting a process and immediately joining it within the same loop, which essentially makes the operations sequential rather than parallel.

Try adjusting your code to start all processes first and then join them after all have been started. Here's a small adjustment:

```python
for process in processing:
    process.start()
for process in processing:
    process.join()
```

This change ensures that all processes are started before any are joined, allowing them to run in parallel.

Additionally, keep in mind that multiprocessing has overhead, especially when dealing with I/O bound tasks or when the overhead of starting a process outweighs the parallel execution benefits. For tasks involving heavy I/O operations, such as loading images from disk, the gains from multiprocessing might be minimal.

Hope this helps! Let us know if you have further questions. 😊

**Comment by kbratsy** [comment]
Thank you so much @glenn-jocher for your quick response. I understood what you meant and made the correction, but unfortunately there doesn't seem to be any difference in terms of time. As you mentioned, multiprocessing may not make much of a difference due to loading from disk.

**Comment by glenn-jocher** [comment]
@kbratsy hi there! 😊

Thanks for giving that a try and sharing your findings. It's indeed possible that the disk I/O is the bottleneck here, limiting the benefits of multiprocessing. If the tasks are heavily I/O bound, parallelizing CPU computations won't significantly reduce the overall time. 

One suggestion could be to look into optimizing how images are loaded or consider using SSDs if not already doing so, as they can offer faster data access times compared to traditional HDDs. Additionally, ensuring your images are preloaded or using a faster data format might help.

Keep experimenting, and feel free to reach out if you have more questions or need further assistance!

**Comment by kbratsy** [comment]
Hello,
I have a quick question. Is there already multiprocessing in YOLOv8 itself for detection tasks? If so, would it make sense to implement multiprocessing tasks again in my detection code?

Thank you from now.

**Comment by glenn-jocher** [comment]
Hello! 👋

Yes, YOLOv8 inherently utilizes multiprocessing capabilities, especially when using GPUs, to efficiently process detection tasks. It's generally not necessary to implement additional multiprocessing in your detection code, as YOLOv8 is optimized to handle parallel processing internally. This should help you avoid the complexity and potential overhead of managing multiprocessing yourself.

If you have specific performance issues, it might be more beneficial to look into optimizing other parts of your workflow or adjusting YOLOv8's configuration settings.

Hope this helps! Let us know if you have any more questions. 😊
