### ISSUE TITLE
BiFPN implementation

### ISSUE THREAD

**Issue by Thorwig** [ultralytics/ultralytics#8886]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I wanted to try and set up YOLOv8 with a BiFPN.
Is it already implemented somewhere in the code? Because I saw closed commits about it.

 
Thank you !

**Comment by glenn-jocher** [comment]
@Thorwig hi there! 😊

Thanks for reaching out! Currently, YOLOv8 does not include a pre-implemented BiFPN within the main codebase. While there have been discussions and commits related to BiFPN, these are part of exploratory work and not directly integrated into YOLOv8's official release.

If you're interested in experimenting with BiFPN and YOLOv8, you might consider custom modifications to the network architecture. This would involve adjusting the model's configuration files and potentially the source code to incorporate BiFPN layers.

We're always excited to see community members pushing the boundaries with new ideas, so feel free to share your progress or ask for advice in our discussions section!

Happy coding! 🚀

**Comment by deepukr007** [comment]
@Thorwig Interesting , what is the idea behind using Bi-FPN is it better than v8 neck ?

**Comment by Thorwig** [comment]
@deepukr007 Well, that's what I am trying to test. I've came across research papers that benchmarks BiFPN and FPN+PAN and the results were slightly better with less FLOPs. 
Here are the papers: 
- https://arxiv.org/pdf/1911.09070v7.pdf 
- https://www.mdpi.com/1424-8220/23/20/8361

**Comment by Thorwig** [comment]
@glenn-jocher Can I concat three entries like this ? 
`  - [[-1, 11, 19], 1, Concat, [1]]  `
