### ISSUE TITLE
make it go to 1000 epoch

### ISSUE THREAD

**Issue by zur000** [ultralytics/ultralytics#8892]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

how can i make it got to 1000 epoch without stoping?
![image](https://github.com/ultralytics/ultralytics/assets/163043253/4e67c767-30a4-4573-bf8d-0bedb1e5fdb0)

**Comment by glenn-jocher** [comment]
@zur000 hello! To train your model for 1000 epochs without stopping, you can simply set the `epochs` argument to `1000` when you start your training. Here's how you can do it using the command line interface (CLI):

```bash
yolo train data=your_dataset.yaml model=yolov8n.pt epochs=1000
```

Just replace `your_dataset.yaml` with the path to your dataset configuration file and `yolov8n.pt` with the model you're training. This will ensure your training runs for 1000 epochs. Happy training! 😊
