### ISSUE TITLE
YOLOv8 Training summary and missing extra information (e.g. confusion matrix)

### ISSUE THREAD

**Issue by t0wgster** [ultralytics/ultralytics#8895]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello everyone, 

I was doing some training with YOLOv8 for my master thesis. And I always look at the training summary as well as the data, e.g. the confusion matrix. But sometimes I get the training summary as well as the confusion matrix (as well as extra information) but sometimes I dont. Is there any parameter I can adjust to make it always appear after training?

Image 1: Training summary (ignore values)
![image](https://github.com/ultralytics/ultralytics/assets/125188064/758e29d9-8276-46ef-be62-54645a1888f4)

Image 2: No Training summary after 3,5h of training
![image](https://github.com/ultralytics/ultralytics/assets/125188064/af055407-93bb-4ac3-8c71-587d9875d151)

Image 3:  Missing Confusion matrix after training

![image](https://github.com/ultralytics/ultralytics/assets/125188064/8035610e-a68f-4756-b18b-dd6c6a28e385)

Any help is appreciated. Thanks in advance!

**Comment by glenn-jocher** [comment]
@t0wgster hello! 👋

It sounds like you're encountering some inconsistency with the training summary and confusion matrix outputs. To ensure these are always generated, you can use the `--save-conf` flag during training to save the confusion matrix and other detailed metrics. Additionally, make sure you're validating (`val`) your model after training, as these summaries are generated during the validation step.

Here's a quick example on how to include it in your training command:

```bash
yolo detect train data=your_dataset.yaml model=yolov8n.pt --save-conf
```

And don't forget to run validation if it's not automatically set:

```bash
yolo detect val model=your_trained_model.pt data=your_dataset.yaml
```

This should help ensure you always get the detailed training summary and confusion matrix. If the issue persists, it might be worth checking the logs for any errors or warnings that could give more insight. 

Hope this helps, and best of luck with your master thesis! 🚀
