### ISSUE TITLE
yolov8 on-screen detection

### ISSUE THREAD

**Issue by Saare-k** [ultralytics/ultralytics#8899]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I created a code that captures the screen and detects the object I am interested in, the problem is that it is slow (it refreshes on average every 1 second and it is not a stream like in the case of a camera image). Can you help me somehow, tell me what to use to improve the smoothness?

`import cv2
import numpy as np
import pyautogui
from ultralytics import YOLO
import os

window_width = 1920
window_height = 1080

# model YOLOv8
model_path = os.path.join('.', 'runs', 'detect', 'train4', 'weights', 'last.pt')
model = YOLO(model_path) 

threshold = 0.5
scale_factor = 1.5

while True:
    screenshot = pyautogui.screenshot()
    frame = np.array(screenshot)
    frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
    H, W, _ = frame.shape

    results = model(frame)[0]

    for result in results.boxes.data.tolist():
        x1, y1, x2, y2, score, class_id = result

        if score > threshold:
            color = (0, 255, 0)
            color_rgb = (color[2], color[1], color[0])

            cv2.rectangle(frame, (int(x1), int(y1)), (int(x2), int(y2)), color_rgb, 4)

    cv2.imshow("frame", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cv2.destroyAllWindows()`

**Comment by glenn-jocher** [comment]
@Saare-k hey there! 👋 It looks like you're doing great with on-screen object detection using YOLOv8. If you're experiencing a bit of lag and aiming for smoother detection, here are a couple of suggestions:

1. **Reduce Image Size:** Before passing the screenshot to the model, you might want to resize it to a smaller size. This can significantly speed up the detection process. For example:

```python
frame = cv2.resize(frame, (int(W / scale_factor), int(H / scale_factor)))
```

2. **Optimize Model for Inference:** If you haven't already, consider exporting your model to an optimized format like ONNX or TensorRT, which can offer better inference speeds. For example, to export to ONNX:

```bash
yolo export model=your_model.pt format=onnx
```

Then, load the ONNX model for inference.

3. **Use a Faster Screenshot Method:** Sometimes, the method used to capture the screen can be a bottleneck. You might want to explore alternative libraries or methods that offer faster screen capture capabilities.

4. **Batch Processing:** If applicable, processing multiple frames at once instead of one by one can also improve overall throughput.

Remember, achieving real-time performance might require some experimentation with these suggestions to find the best balance for your specific setup. Hope this helps, and happy coding! 🚀

**Comment by Saare-k** [comment]
yolo does not have such a built-in option like the "show" function in the case of the camera:

`model.predict(source=0, imgsz=640, conf=0.6, show=True)`

**Comment by glenn-jocher** [comment]
@Saare-k hey there! 😊 YOLOv8 indeed supports a `source` parameter in its `predict` method, allowing you to specify various input sources, including live camera feeds by setting `source=0`. For on-screen detection or capturing your screen as a source, you'd typically use an external library (like `pyautogui` for screenshots, as you've mentioned) to capture the screen and then pass the frames to the model for prediction.

For smoother screen capture and display, consider using a more efficient screen capture library if available for your platform, and ensure you're processing frames at a size that balances speed and accuracy, as resizing can significantly impact performance. Here's a quick example of how you might structure your code for real-time predictions with YOLOv8:

```python
from ultralytics import YOLO
import cv2

# Initialize the model
model = YOLO('path/to/your/model.pt', imgsz=640, conf=0.6)

# Capture from your default camera (just as an example)
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Make predictions
    results = model.predict(frame, show=True)

    # Display the frame with detections
    cv2.imshow('YOLOv8 Predictions', np.squeeze(results.render()))

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
```

This example uses a camera feed, but you can adapt it to use screen capture frames. The key is to capture the screen efficiently and pass those frames to `model.predict()`. Hope this helps, and happy coding! 🚀

**Comment by ClementFranger** [comment]
Hello, I see there is a source='screen' source built in that does what you want (it uses mss behind the scene). My problem is that I didn't find any way to parametrize it, I have a dual screen and would like to capture only one, but I am unable to do it using the screen source of ultralytics. Must i do a custom screenshot grab ?

**Comment by glenn-jocher** [comment]
@ClementFranger hey there! 😊

You're right that YOLOv8 uses `mss` for the `source='screen'` option, which is pretty neat for on-screen detection. For your dual-screen setup, customizing the screen capture to target a specific monitor is the way to go, as the built-in `screen` source doesn't directly support multi-monitor configurations.

You could capture a specific monitor with `mss` and then pass the image to the model like this:

```python
from mss import mss
from ultralytics import YOLO
import numpy as np
import cv2

model = YOLO('path/to/your/model.pt')

with mss() as sct:
    # Monitor 1 would be sct.monitors[1]
    monitor = sct.monitors[1]  # Adjust the monitor index as needed
    screenshot = sct.grab(monitor)
    frame = np.array(screenshot)

    # Convert to correct color format
    frame = cv2.cvtColor(frame, cv2.COLOR_BGRA2BGR)

    # Process frame
    results = model(frame)

    # To display the predictions
    cv2.imshow('Monitor 1', results.render()[0])
    cv2.waitKey(0)
    cv2.destroyAllWindows()
```

This approach gives you flexibility to select any of your screens for capturing. 👍 If you've got any more questions or need further assistance, don't hesitate to ask!

**Comment by AndroidAddict92** [comment]
> ```python
> from mss import mss
> from ultralytics import YOLO
> import numpy as np
> import cv2
> 
> model = YOLO('path/to/your/model.pt')
> 
> with mss() as sct:
>     # Monitor 1 would be sct.monitors[1]
>     monitor = sct.monitors[1]  # Adjust the monitor index as needed
>     screenshot = sct.grab(monitor)
>     frame = np.array(screenshot)
> 
>     # Convert to correct color format
>     frame = cv2.cvtColor(frame, cv2.COLOR_BGRA2BGR)
> 
>     # Process frame
>     results = model(frame)
> 
>     # To display the predictions
>     cv2.imshow('Monitor 1', results.render()[0])
>     cv2.waitKey(0)
>     cv2.destroyAllWindows()
> ```

Is it possible to implement something like this. I have my monitor set as source but I need the tracking to be more in real-time, whereas the above method seems to have a drastic delay. I basically want it to read my monitor source, and detect in real-time, create the boxes in real-time. I am using yolov8m.pt

**Comment by glenn-jocher** [comment]
Hey there! 😊 It looks like you've made a great start with screen capture and YOLOv8 for real-time object detection. If you're experiencing delays, optimizing the frame processing loop for speed might help. Try this slightly adjusted snippet for more real-time performance:

```python
from mss import mss
from ultralytics import YOLO
import numpy as np
import cv2

# Load YOLO model
model = YOLO('yolov8m.pt')  # Make sure it's the correct path

with mss() as sct:
    monitor = sct.monitors[1]  # Target monitor

    while True:
        screenshot = sct.grab(monitor)
        frame = np.array(screenshot, dtype=np.uint8)
        frame = cv2.cvtColor(frame, cv2.COLOR_BGRA2BGR)

        # Detect and render
        results = model(frame)
        cv2.imshow('Monitor 1', np.squeeze(results.render()))

        # Press 'q' to quit
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

cv2.destroyAllWindows()
```

Reducing the `imgsz` parameter when instantiating your YOLO model might also improve speed if you're okay with a slight decrease in accuracy. Keep the detection running in a loop for real-time updates, and ensure your model file path is correct (`yolov8m.pt`). 

I hope this helps get you closer to real-time detection on your monitor source! If you have further questions, feel free to ask. Happy coding! 🚀

**Comment by kayraaytug** [comment]
@glenn-jocher well i got an error at `cv2.imshow('Monitor 1', np.squeeze(results.render()))
AttributeError: 'list' object has no attribute 'render'`

And found a simple workaround, works ok for me
`from mss import mss
import cv2
import numpy as np
from ultralytics import YOLO
from ultralytics.utils.plotting import Annotator, colors


model = YOLO("yolov8n.pt")
names = model.model.names


with mss() as sct:
    monitor = sct.monitors[1]
    while True:
        screenshot = sct.grab(monitor)
        frame = np.array(screenshot)
        frame = cv2.cvtColor(frame, cv2.COLOR_BGRA2BGR)
        if monitor:
            results = model.track(frame, persist=True, verbose=False)
            boxes = results[0].boxes.xyxy.cpu()

            if results[0].boxes.id is not None:

                # Extract prediction results
                clss = results[0].boxes.cls.cpu().tolist()
                track_ids = results[0].boxes.id.int().cpu().tolist()
                confs = results[0].boxes.conf.float().cpu().tolist()

                # Annotator Init
                annotator = Annotator(frame, line_width=2)

                for box, cls, track_id in zip(boxes, clss, track_ids):
                    annotator.box_label(box, color=colors(int(cls), True), label=names[int(cls)])
            cv2.imshow('Frame', frame)
            if cv2.waitKey(1) & 0xFF == ord("q"):
                break
        else:
            break
    cv2.destroyAllWindows()
     `

**Comment by glenn-jocher** [comment]
Hey @kayraaytug! 👋 Thanks for sharing your workaround, it looks neat! 🚀

Just a quick note on the error you encountered: it seems like the `results` object returned from the model prediction is a list, and each item in the list is a `Results` object that you can call `.render()` on. For a quick fix, you might want to adjust your original code to:

```python
cv2.imshow('Monitor 1', np.squeeze(results[0].render()))
```

This ensures you're accessing the `render()` method of the first `Results` object in the list. Your workaround using `Annotator` is also a great approach for more control over the visualization! Keep up the good work! 🌟
