### ISSUE TITLE
The problem of dual GPU training

### ISSUE THREAD

**Issue by indulgence1** [ultralytics/ultralytics#8910]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Multi-GPU

### Bug

DDP: debug command /data2/qts/Program/miniconda3/envs/yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 36249 /home/qts/.config/Ultralytics/DDP/_temp_9ziqch4m140028345960192.py
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Ultralytics YOLOv8.1.20 🚀 Python-3.10.13 torch-1.12.1 CUDA:1 (NVIDIA GeForce RTX 2080 Ti, 11019MiB)
                                                       CUDA:3 (NVIDIA GeForce RTX 2080 Ti, 11019MiB)
WARNING ⚠️ Upgrade to torch>=2.0.0 for deterministic training.
TensorBoard: Start with 'tensorboard --logdir /data2/qts/project/ultralytics/runs/detect/seadrones(v8sImgsz2400RectSGD)7', view at http://localhost:6006/
Traceback (most recent call last):
  File "/home/qts/.config/Ultralytics/DDP/_temp_9ziqch4m140028345960192.py", line 12, in <module>
    results = trainer.train()
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 208, in train
    self._do_train(world_size)
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 322, in _do_train
    self._setup_train(world_size)
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 236, in _setup_train
    ckpt = self.setup_model()
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 521, in setup_model
    self.model = self.get_model(cfg=cfg, weights=weights, verbose=RANK == -1)  # calls Model(cfg, weights)
  File "/data2/qts/project/ultralytics/ultralytics/models/yolo/detect/train.py", line 88, in get_model
    model = DetectionModel(cfg, nc=self.data["nc"], verbose=verbose and RANK == -1)
  File "/data2/qts/project/ultralytics/ultralytics/nn/tasks.py", line 274, in __init__
    self.yaml = cfg if isinstance(cfg, dict) else yaml_model_load(cfg)  # cfg dict
  File "/data2/qts/project/ultralytics/ultralytics/nn/tasks.py", line 916, in yaml_model_load
    path = Path(path)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/home/qts/.config/Ultralytics/DDP/_temp_9ziqch4m140028345960192.py", line 12, in <module>
    results = trainer.train()
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 208, in train
    self._do_train(world_size)
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 322, in _do_train
    self._setup_train(world_size)
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 236, in _setup_train
    ckpt = self.setup_model()
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 521, in setup_model
    self.model = self.get_model(cfg=cfg, weights=weights, verbose=RANK == -1)  # calls Model(cfg, weights)
  File "/data2/qts/project/ultralytics/ultralytics/models/yolo/detect/train.py", line 88, in get_model
    model = DetectionModel(cfg, nc=self.data["nc"], verbose=verbose and RANK == -1)
  File "/data2/qts/project/ultralytics/ultralytics/nn/tasks.py", line 274, in __init__
    self.yaml = cfg if isinstance(cfg, dict) else yaml_model_load(cfg)  # cfg dict
  File "/data2/qts/project/ultralytics/ultralytics/nn/tasks.py", line 916, in yaml_model_load
    path = Path(path)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 71601) of binary: /data2/qts/Program/miniconda3/envs/yolov8/bin/python
Traceback (most recent call last):
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/run.py", line 765, in <module>
    main()
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/qts/.config/Ultralytics/DDP/_temp_9ziqch4m140028345960192.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-03-13_22:10:34
  host      : localhost.localdomain
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 71602)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-13_22:10:34
  host      : localhost.localdomain
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 71601)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/data2/qts/project/ultralytics/seadrones.py", line 9, in <module>
    results = model.train(cfg='ultralytics/cfg/seadrones.yaml',data='dataset/seadrones.yaml')
  File "/data2/qts/project/ultralytics/ultralytics/engine/model.py", line 644, in train
    self.trainer.train()
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 203, in train
    raise e
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 201, in train
    subprocess.run(cmd, check=True)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/data2/qts/Program/miniconda3/envs/yolov8/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '36249', '/home/qts/.config/Ultralytics/DDP/_temp_9ziqch4m140028345960192.py']' returned non-zero exit status 1.

### Environment

Ultralytics YOLOv8.1.20 🚀 Python-3.10.13 torch-1.12.1 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11019MiB)
Setup complete ✅ (20 CPUs, 98.2 GB RAM, 80.6/198.7 GB disk)

OS                  Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.17
Environment         Linux
Python              3.10.13
Install             git
RAM                 98.18 GB
CPU                 Intel Xeon Silver 4210R 2.40GHz
CUDA                11.3

matplotlib          ✅ 3.8.3>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 1.12.1>=1.8.0
torchvision         ✅ 0.13.1>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.1>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Minimal Reproducible Example

from ultralytics import YOLO

# Load a model
model = YOLO('yolov8m.yaml')
model = YOLO('yolov8m.pt')  # load a pretrained model 

# Train the model
results = model.train(cfg='ultralytics/cfg/dataset.yaml',data='dataset/dataset.yaml')

dataset.yaml file :
task: detect # (str) YOLO task, i.e. detect, segment, classify, pose
mode: train # (str) YOLO mode, i.e. train, val, predict, export, track, benchmark

# Train settings -------------------------------------------------------------------------------------------------------
model: # (str, optional) path to model file, i.e. yolov8n.pt, yolov8n.yaml
data: # (str, optional) path to data file, i.e. coco128.yaml
epochs: 60 # (int) number of epochs to train for
time: # (float, optional) number of hours to train for, overrides epochs if supplied
patience: 100 # (int) epochs to wait for no observable improvement for early stopping of training
batch: 2 # (int) number of images per batch (-1 for AutoBatch)
imgsz: 2400 # (int | list) input images size as int for train and val modes, or list[w,h] for predict and export modes
save: True # (bool) save train checkpoints and predict results
save_period: -1 # (int) Save checkpoint every x epochs (disabled if < 1)
cache: False # (bool) True/ram, disk or False. Use cache for data loading
device: [1,3] # (int | str | list, optional) device to run on, i.e. cuda device=0 or device=0,1,2,3 or device=cpu
workers: 8 # (int) number of worker threads for data loading (per RANK if DDP)
project: # (str, optional) project name
name:  # (str, optional) experiment name, results saved to 'project/name' directory
exist_ok: False # (bool) whether to overwrite existing experiment
pretrained: True # (bool | str) whether to use a pretrained model (bool) or a model to load weights from (str)
optimizer: auto # (str) optimizer to use, choices=[SGD, Adam, Adamax, AdamW, NAdam, RAdam, RMSProp, auto]
verbose: True # (bool) whether to print verbose output
seed: 0 # (int) random seed for reproducibility
deterministic: True # (bool) whether to enable deterministic mode
single_cls: False # (bool) train multi-class data as single-class
rect: True # (bool) rectangular training if mode='train' or rectangular validation if mode='val'
cos_lr: False # (bool) use cosine learning rate scheduler
close_mosaic: 10 # (int) disable mosaic augmentation for final epochs (0 to disable)
resume: False # (bool) resume training from last checkpoint
amp: True # (bool) Automatic Mixed Precision (AMP) training, choices=[True, False], True runs AMP check
fraction: 1.0 # (float) dataset fraction to train on (default is 1.0, all images in train set)
profile: False # (bool) profile ONNX and TensorRT speeds during training for loggers
freeze: None # (int | list, optional) freeze first n layers, or freeze list of layer indices during training
multi_scale: False # (bool) Whether to use multi-scale during training
# Segmentation
overlap_mask: True # (bool) masks should overlap during training (segment train only)
mask_ratio: 4 # (int) mask downsample ratio (segment train only)
# Classification
dropout: 0.0 # (float) use dropout regularization (classify train only)

### Additional

My program can train normally on a single GPU。My system is Centos Linux version 7

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@indulgence1 hey there! 👋 It looks like you're encountering an issue with multi-GPU training using Distributed Data Parallel (DDP). The error message suggests there might be a problem with the configuration file path being passed as `None`. This often happens when the model configuration (`cfg`) or dataset configuration (`data`) paths are not correctly specified or found.

To resolve this, please ensure the following:
- The paths to your `cfg` and `data` files are correctly specified and accessible from your script.
- When specifying paths in your script, use absolute paths or paths relative to the script's execution directory to avoid any ambiguity.

Here's a corrected snippet of your code with explicit paths for `cfg` and `data`:

```python
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8m.yaml')
model = YOLO('yolov8m.pt')  # load a pretrained model 

# Train the model with explicit paths
results = model.train(cfg='/absolute/path/to/ultralytics/cfg/dataset.yaml', data='/absolute/path/to/dataset/dataset.yaml')
```

Make sure to replace `'/absolute/path/to/ultralytics/cfg/dataset.yaml'` and `'/absolute/path/to/dataset/dataset.yaml'` with the actual paths to your configuration files.

If the issue persists, double-check that your environment is correctly set up for DDP training, including ensuring that all nodes can communicate over the network and that your PyTorch version supports DDP.

Hope this helps! Let us know if you have any more questions. 😊

**Comment by indulgence1** [comment]
@glenn-jocher hey! 👋 Thank you for your help, but it doesn't work.
from ultralytics import YOLO

#here is the new Python file
`# Load a model
model = YOLO('yolov8m.yaml')
model = YOLO('yolov8m.pt')  # load a pretrained model 

# Train the model
results = model.train(cfg='/data2/qts/project/ultralytics/ultralytics/cfg/dataset.yaml',data='/data2/qts/project/ultralytics/dataset/dataset.yaml')`

and this is a part of config file dataset.yaml:
`task: detect # (str) YOLO task, i.e. detect, segment, classify, pose
mode: train # (str) YOLO mode, i.e. train, val, predict, export, track, benchmark

# Train settings -------------------------------------------------------------------------------------------------------
model: # (str, optional) path to model file, i.e. yolov8n.pt, yolov8n.yaml
data: # (str, optional) path to data file, i.e. coco128.yaml
epochs: 60 # (int) number of epochs to train for
time: # (float, optional) number of hours to train for, overrides epochs if supplied
patience: 100 # (int) epochs to wait for no observable improvement for early stopping of training
batch: 4 # (int) number of images per batch (-1 for AutoBatch)
imgsz: 2400 # (int | list) input images size as int for train and val modes, or list[w,h] for predict and export modes
save: True # (bool) save train checkpoints and predict results
save_period: -1 # (int) Save checkpoint every x epochs (disabled if < 1)
cache: False # (bool) True/ram, disk or False. Use cache for data loading
device: [1,3] # (int | str | list, optional) device to run on, i.e. cuda device=0 or device=0,1,2,3 or device=cpu
workers: 8 # (int) number of worker threads for data loading (per RANK if DDP)
project: # (str, optional) project name
name: seadrones(v8mImgsz2400RectSGD) # (str, optional) experiment name, results saved to 'project/name' directory
exist_ok: False # (bool) whether to overwrite existing experiment
pretrained: True # (bool | str) whether to use a pretrained model (bool) or a model to load weights from (str)
optimizer: auto # (str) optimizer to use, choices=[SGD, Adam, Adamax, AdamW, NAdam, RAdam, RMSProp, auto]
verbose: True # (bool) whether to print verbose output
seed: 0 # (int) random seed for reproducibility
deterministic: True # (bool) whether to enable deterministic mode
single_cls: False # (bool) train multi-class data as single-class
rect: True # (bool) rectangular training if mode='train' or rectangular validation if mode='val'
cos_lr: False # (bool) use cosine learning rate scheduler
close_mosaic: 10 # (int) disable mosaic augmentation for final epochs (0 to disable)
resume: False # (bool) resume training from last checkpoint
amp: True # (bool) Automatic Mixed Precision (AMP) training, choices=[True, False], True runs AMP check
fraction: 1.0 # (float) dataset fraction to train on (default is 1.0, all images in train set)
profile: False # (bool) profile ONNX and TensorRT speeds during training for loggers
freeze: None # (int | list, optional) freeze first n layers, or freeze list of layer indices during training
multi_scale: False # (bool) Whether to use multi-scale during training
# Segmentation
overlap_mask: True # (bool) masks should overlap during training (segment train only)
mask_ratio: 4 # (int) mask downsample ratio (segment train only)
# Classification
dropout: 0.0 # (float) use dropout regularization (classify train only)`

#the pytorch verision  
`pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3`

#bug
`New https://pypi.org/project/ultralytics/8.1.27 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.1.20 🚀 Python-3.10.13 torch-1.12.1 CUDA:1 (NVIDIA GeForce RTX 2080 Ti, 11019MiB)
                                                       CUDA:3 (NVIDIA GeForce RTX 2080 Ti, 11019MiB)
WARNING ⚠️ Upgrade to torch>=2.0.0 for deterministic training.
engine/trainer: task=detect, mode=train, model=None, data=/data2/qts/project/ultralytics/dataset/seadrones.yaml, epochs=60, time=None, patience=100, batch=4, imgsz=2400, save=True, save_period=-1, cache=False, device=[1, 3], workers=8, project=None, name=seadrones(v8mImgsz2400RectSGD), exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=True, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=True, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=/data2/qts/project/ultralytics/ultralytics/cfg/seadrones.yaml, tracker=botsort.yaml, save_dir=/data2/qts/project/ultralytics/runs/detect/seadrones(v8mImgsz2400RectSGD)
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments                     
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]                 
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]                
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]             
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]               
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]           
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]              
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]           
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]              
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]           
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]                 
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]                 
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]                 
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]          
Model summary: 295 layers, 25859794 parameters, 25859778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
WARNING ⚠️ 'rect=True' is incompatible with Multi-GPU training, setting 'rect=False'
DDP: debug command /data2/qts/Program/miniconda3/envs/yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 38128 /home/qts/.config/Ultralytics/DDP/_temp_jv16tqxs140587778049792.py
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Ultralytics YOLOv8.1.20 🚀 Python-3.10.13 torch-1.12.1 CUDA:1 (NVIDIA GeForce RTX 2080 Ti, 11019MiB)
                                                       CUDA:3 (NVIDIA GeForce RTX 2080 Ti, 11019MiB)
WARNING ⚠️ Upgrade to torch>=2.0.0 for deterministic training.
TensorBoard: Start with 'tensorboard --logdir /data2/qts/project/ultralytics/runs/detect/seadrones(v8mImgsz2400RectSGD)', view at http://localhost:6006/
Traceback (most recent call last):
  File "/home/qts/.config/Ultralytics/DDP/_temp_jv16tqxs140587778049792.py", line 12, in <module>
    results = trainer.train()
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 208, in train
    self._do_train(world_size)
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 322, in _do_train
    self._setup_train(world_size)
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 236, in _setup_train
    ckpt = self.setup_model()
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 521, in setup_model
    self.model = self.get_model(cfg=cfg, weights=weights, verbose=RANK == -1)  # calls Model(cfg, weights)
  File "/data2/qts/project/ultralytics/ultralytics/models/yolo/detect/train.py", line 88, in get_model
    model = DetectionModel(cfg, nc=self.data["nc"], verbose=verbose and RANK == -1)
  File "/data2/qts/project/ultralytics/ultralytics/nn/tasks.py", line 274, in __init__
    self.yaml = cfg if isinstance(cfg, dict) else yaml_model_load(cfg)  # cfg dict
  File "/data2/qts/project/ultralytics/ultralytics/nn/tasks.py", line 916, in yaml_model_load
    path = Path(path)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/home/qts/.config/Ultralytics/DDP/_temp_jv16tqxs140587778049792.py", line 12, in <module>
    results = trainer.train()
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 208, in train
    self._do_train(world_size)
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 322, in _do_train
    self._setup_train(world_size)
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 236, in _setup_train
    ckpt = self.setup_model()
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 521, in setup_model
    self.model = self.get_model(cfg=cfg, weights=weights, verbose=RANK == -1)  # calls Model(cfg, weights)
  File "/data2/qts/project/ultralytics/ultralytics/models/yolo/detect/train.py", line 88, in get_model
    model = DetectionModel(cfg, nc=self.data["nc"], verbose=verbose and RANK == -1)
  File "/data2/qts/project/ultralytics/ultralytics/nn/tasks.py", line 274, in __init__
    self.yaml = cfg if isinstance(cfg, dict) else yaml_model_load(cfg)  # cfg dict
  File "/data2/qts/project/ultralytics/ultralytics/nn/tasks.py", line 916, in yaml_model_load
    path = Path(path)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 38837) of binary: /data2/qts/Program/miniconda3/envs/yolov8/bin/python
Traceback (most recent call last):
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/run.py", line 765, in <module>
    main()
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/qts/.config/Ultralytics/DDP/_temp_jv16tqxs140587778049792.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-03-14_17:35:42
  host      : localhost.localdomain
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 38838)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-14_17:35:42
  host      : localhost.localdomain
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 38837)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/data2/qts/project/ultralytics/seadrones.py", line 9, in <module>
    results = model.train(cfg='/data2/qts/project/ultralytics/ultralytics/cfg/seadrones.yaml',data='/data2/qts/project/ultralytics/dataset/seadrones.yaml')
  File "/data2/qts/project/ultralytics/ultralytics/engine/model.py", line 644, in train
    self.trainer.train()
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 203, in train
    raise e
  File "/data2/qts/project/ultralytics/ultralytics/engine/trainer.py", line 201, in train
    subprocess.run(cmd, check=True)
  File "/data2/qts/Program/miniconda3/envs/yolov8/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/data2/qts/Program/miniconda3/envs/yolov8/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '38128', '/home/qts/.config/Ultralytics/DDP/_temp_jv16tqxs140587778049792.py']' returned non-zero exit status 1.`

**Comment by glenn-jocher** [comment]
Hey @indulgence1 👋, thanks for the update! It seems like the issue might be related to how the configuration files are being loaded. Could you double-check that the paths specified in your `cfg` and `data` parameters are correct and accessible? Also, ensure that the YAML files are correctly formatted and contain all necessary fields.

If everything seems correct with the paths and files, try a simple test by hardcoding some values directly in your script to rule out any issues with file reading or parsing. Here’s a small snippet to help with debugging:

```python
from ultralytics import YOLO

# Load a model directly with hardcoded parameters for testing
model = YOLO('yolov8m.yaml', nc=80)  # Adjust 'nc' as per your class count

# Attempt to train the model with hardcoded values
try:
    results = model.train(cfg='path/to/your/cfg.yaml', data='path/to/your/data.yaml')
except Exception as e:
    print(f"An error occurred: {e}")
```

Replace `'path/to/your/cfg.yaml'` and `'path/to/your/data.yaml'` with the actual paths to your configuration files. This might give us more insight into what's going wrong. Let me know how it goes! 😊
