### ISSUE TITLE
argument save_dir doesn't work

### ISSUE THREAD

**Issue by PanJinquan** [ultralytics/ultralytics#8912]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

The save_dir argument doesn't work, probably because the command isn't added; adding this argument to the file(`ultralytics/cfg/default.yaml`) can fix this problem.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@PanJinquan hello! Thanks for bringing this to our attention. 🌟

The `save_dir` argument should indeed direct where your output files are saved. If it's not working as expected, it might be an oversight on our part. For a quick workaround, you can specify the output directory in your command like this:

```bash
yolo detect predict model=yolov8n.pt source='path/to/your/image.jpg' --save-dir 'path/to/your/save/directory'
```

Make sure to replace `'path/to/your/image.jpg'` and `'path/to/your/save/directory'` with your actual file and desired output directory paths.

We appreciate your suggestion to add this argument to the `default.yaml` for clarity and ease of use. While we review this internally, feel free to use the above method. 

And although you've indicated you're not up for submitting a PR, anyone in the community who feels inclined to contribute is always welcome! Contributions help make YOLOv8 better for everyone. 🚀

Let us know if you have any more questions or suggestions!
