### ISSUE TITLE
Is there any arguement to turn off the output infomation during prediction?

### ISSUE THREAD

**Issue by TrinityNeo99** [ultralytics/ultralytics#892]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Dear author. is there any argument for turning off the output information during prediction?
I want to leverage YOLO v8 in a web project, but too much information during prediction may look strange. Thank you very much
![image](https://user-images.githubusercontent.com/49897919/217823856-2504034e-cbf8-4428-8afb-bc75678b987f.png)

**Comment by AyushExel** [comment]
pass `verbose=False` with inference call

**Comment by TrinityNeo99** [comment]
Thanks a lot, I think there would be some documents for such arguments, could you please paste some links here, thanks a lot.

**Comment by AyushExel** [comment]
Here you go https://docs.ultralytics.com/cfg/

**Comment by TrinityNeo99** [comment]
Thank you very much, the "verbose" is so covert to be found in this document
![image](https://user-images.githubusercontent.com/49897919/217867262-b6748b1c-2f80-4063-acb8-97f5acf85be1.png)
