### ISSUE TITLE
BaseTrainer for Custom Model

### ISSUE THREAD

**Issue by Halafz7** [ultralytics/ultralytics#8920]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I've read the engine/trainer.py and classify/train.py that allows to use another model beside YOLO (example: resnet18). So, I give it a try with Vision Transformer Model with code like this :

from ultralytics.models.yolo.classify import ClassificationTrainer

args = dict(model='vit_b_16', data='cifar100', epochs=10, imgsz=32, project="/content/gdrive/MyDrive/models/vit", name="vit10")
trainer = ClassificationTrainer(overrides=args)
trainer.train()

and got error like this

![image](https://github.com/ultralytics/ultralytics/assets/79700580/47dcb6d9-5ec2-45df-bd46-5a7abda078d9)

Can someone help to fix this?

**Comment by glenn-jocher** [comment]
@Halafz7 hello! It looks like you're exploring custom model training with YOLOv8, which is fantastic! 🚀 From the error screenshot you've shared (unfortunately, the image didn't load, but that's okay), it seems there might be a compatibility issue or a missing configuration for the Vision Transformer Model.

To start troubleshooting, ensure that the Vision Transformer Model (`vit_b_16`) is correctly implemented and accessible in your environment. Also, verify that all required dependencies for running Vision Transformer models are installed.

If everything seems in place but you're still facing issues, it could be helpful to look into the specific error message you're receiving. Sometimes, the error could be related to the input size or an unsupported feature in the custom model.

As a quick check, you might want to ensure your custom model is compatible with the input size (`imgsz=32`) and the dataset (`cifar100`) you're using. Vision Transformer models often have specific requirements for input dimensions.

If you continue to face difficulties, could you please provide more details about the error message? That would help in pinpointing the exact issue.

Here's a simplified version of your code with added comments for clarity:

```python
from ultralytics.models.yolo.classify import ClassificationTrainer

# Define training arguments
args = {
    'model': 'vit_b_16',  # Specify your model
    'data': 'cifar100',  # Dataset
    'epochs': 10,  # Number of training epochs
    'imgsz': 32,  # Input image size
    'project': "/content/gdrive/MyDrive/models/vit",  # Project directory
    'name': "vit10"  # Experiment name
}

# Initialize the trainer with your arguments
trainer = ClassificationTrainer(overrides=args)

# Start training
trainer.train()
```

Please ensure the model name and parameters are correctly specified. Looking forward to hearing back from you!

**Comment by Halafz7** [comment]
Hi Glenn, I'm definitely use the same code as you were wrote down there. I think the issue was not on that code but in somewhere else because it says like this everytime I tried to ran it

AttributeError                            Traceback (most recent call last)
[<ipython-input-3-ce72884a0b77>](https://localhost:8080/#) in <cell line: 17>()
     15 
     16 # Start training
---> 17 trainer.train()

5 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py](https://localhost:8080/#) in train(self)
    211 
    212         else:
--> 213             self._do_train(world_size)
    214 
    215     def _setup_scheduler(self):

[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py](https://localhost:8080/#) in _do_train(self, world_size)
    379                 with torch.cuda.amp.autocast(self.amp):
    380                     batch = self.preprocess_batch(batch)
--> 381                     self.loss, self.loss_items = self.model(batch)
    382                     if RANK != -1:
    383                         self.loss *= world_size

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _wrapped_call_impl(self, *args, **kwargs)
   1509             return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1510         else:
-> 1511             return self._call_impl(*args, **kwargs)
   1512 
   1513     def _call_impl(self, *args, **kwargs):

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1518                 or _global_backward_pre_hooks or _global_backward_hooks
   1519                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1520             return forward_call(*args, **kwargs)
   1521 
   1522         try:

[/usr/local/lib/python3.10/dist-packages/torchvision/models/vision_transformer.py](https://localhost:8080/#) in forward(self, x)
    289     def forward(self, x: torch.Tensor):
    290         # Reshape and permute the input tensor
--> 291         x = self._process_input(x)
    292         n = x.shape[0]
    293 

[/usr/local/lib/python3.10/dist-packages/torchvision/models/vision_transformer.py](https://localhost:8080/#) in _process_input(self, x)
    267 
    268     def _process_input(self, x: torch.Tensor) -> torch.Tensor:
--> 269         n, c, h, w = x.shape
    270         p = self.patch_size
    271         torch._assert(h == self.image_size, f"Wrong image height! Expected {self.image_size} but got {h}!")

AttributeError: 'dict' object has no attribute 'shape'


I realized that something wrong with the shape bcs Vision Transformer has 4D shape (N, C, W, H), how I am supposed to do?

**Comment by glenn-jocher** [comment]
@Halafz7 hi there! 👋 It looks like the issue stems from the input format expected by the Vision Transformer model. The error indicates that the model is receiving a `dict` instead of a tensor with the expected 4D shape `(N, C, W, H)`.

To resolve this, ensure that your dataset loader is correctly preprocessing the input images into the expected format before they're passed to the model for training. Here's a quick example of how you might adjust your dataset or dataloader to ensure the input is correctly shaped:

```python
from torchvision import transforms

# Define your transformations
transform = transforms.Compose([
    transforms.Resize((224, 224)),  # Adjust to your required input size
    transforms.ToTensor(),
])

# Apply the transformation within your dataset loading logic
# Ensure that your dataset loader applies this transform to each image
```

This example assumes you're using `torchvision` datasets or a custom dataset that can apply transformations. The key is to ensure that each image fed into the model is a tensor with the shape `(C, W, H)` and wrapped in a batch `(N, C, W, H)` where `N` is the batch size.

If you're already doing this and still encountering issues, it might be helpful to inspect the batch just before it's passed to the model to ensure it's correctly formatted. You can do this with a simple print statement or by using a debugger.

Hope this helps! Let me know if you have any more questions. 😊
