### ISSUE TITLE
after using  ultralytics.data/split_dota split datav1 images, part of the labels are out of bounds coordinates(<0 or >1))

### ISSUE THREAD

**Issue by Myreaeee** [ultralytics/ultralytics#8929]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![20240314-161606](https://github.com/ultralytics/ultralytics/assets/127958257/dcfcc94a-7cf5-47a3-9304-c3db645e17bd)

**Comment by Myreaeee** [comment]
@glenn-jocher thx for your advice！ after meeting this issue, i have looked through data/split_dota.py, and found that the labels of target after splitting is obtained by directly subtracting x_start, y_start from the original label, according to this calculation, when it exceeds the cropping area there will be >1 or <0, so adding this code truly solved the problem

**Comment by glenn-jocher** [comment]
That's fantastic to hear, @Myreaeee! It sounds like you've managed to tackle the issue head-on by adjusting the label coordinates during the splitting process. 🚀 Your approach to modifying the labels to ensure they stay within bounds is spot on. 

For anyone else encountering a similar scenario, here's a quick snippet that mirrors @Myreaeee's solution:

```python
# Adjust labels to ensure they're within bounds after cropping
label_x, label_y = original_label  # Assuming these are the original label coordinates
x_start, y_start = crop_start  # Assuming these mark the top-left corner of your crop

# Adjusting label coordinates to fit within the cropped image
adjusted_x = max(0, min(label_x - x_start, 1))
adjusted_y = max(0, min(label_y - y_start, 1))
```

This ensures that any labels for cropped images stay within the valid range. Kudos on your quick fix and thanks for sharing your solution with the community! If there are any more questions down the road, feel free to reach out. Happy coding! 🌟

**Comment by xxxyyynnn** [comment]
@glenn-jocher Hello! Thank you for your suggestion. Could you please update the split_dota.py?
