### ISSUE TITLE
Missing mask information in json output from prediction.tojson() method

### ISSUE THREAD

**Issue by aslakm** [ultralytics/ultralytics#8932]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

[predictions_crack.json](https://github.com/ultralytics/ultralytics/files/14600342/predictions_crack.json)
![FV00279_S1D1_m00709_f1_orig_file](https://github.com/ultralytics/ultralytics/assets/5400016/1838c3b2-bede-437d-94a5-90654e8bc0d5)
![FV00279_S1D1_m00709_f1_YoloPlot](https://github.com/ultralytics/ultralytics/assets/5400016/c97c4df2-b2fa-4011-a05d-65cd77b56c60)
![FV00279_S1D1_m00709_f1_plotted_from_json](https://github.com/ultralytics/ultralytics/assets/5400016/df076fa9-2eb8-4379-8626-9ab37b80491f)

[
![code](https://github.com/ultralytics/ultralytics/assets/5400016/a8249a9c-9055-4e38-959b-f40dbd55d447)
](url)

The problem is that the content of the json output do not correspond to the plot from yolov8.

The attached json file is the result of the results[0].tojson() liste in the code. The first image attched is the original image. The next image is the result from yolo plot(). And the last images is all points listed in the json file plotted on to the image. 

Notice that there are no points at the lower part of the last image, The image size is 2448x2048. In the json file there are no y coordinates that are above 1100 pixels. That implies that there is a mismath between the content of the json file from yolo and the plot from yolo.

The bounding box seems to be correct.

### Environment

![yolo_checks](https://github.com/ultralytics/ultralytics/assets/5400016/56fb8ca9-4b00-44ff-92df-af9a5a24dd3a)

### Minimal Reproducible Example

![code](https://github.com/ultralytics/ultralytics/assets/5400016/d0e3cedb-3118-4b95-b844-03de24547573)

### Additional

I can provide my weight file if needed.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@aslakm hello! Thanks for bringing this to our attention. 🌟 It seems like there might be an issue with how the mask coordinates are being exported to the JSON file, particularly with the y-coordinates not covering the full image height as expected.

Could you please verify if the issue persists when using the latest version of our repository? If it does, it would be incredibly helpful if you could share your weight file with us. This way, we can replicate the issue more accurately on our end.

In the meantime, here's a quick check you can perform to ensure the mask data is being processed correctly before exporting:

```python
# Assuming 'results' is your prediction object
for mask in results.masks:
    print(mask.numpy())  # This will print the mask data. Check if y-coordinates seem off here as well.
```

If the mask data printed directly from the `results` object already shows truncated y-coordinates, there might be an issue with the prediction process. However, if the data looks correct until the export step, the problem likely lies within the `tojson()` method.

We appreciate your cooperation and are here to help get to the bottom of this!

**Comment by aslakm** [comment]
I modified the code snippet slightly.
    # Assuming 'results' is your prediction object
    for mask in results[0].masks:
        print(mask.cpu().xy)  # This will print the mask data. Check if y-coordinates seem off here as well.

I have verified that the is no y coordinates for the lower part of the image. That implies that the error is not in the tojson() method.
Look at the attached txt file for the print() output.
[output_from_prediction.txt](https://github.com/ultralytics/ultralytics/files/14603304/output_from_prediction.txt)

run command: pip3 install --upgrade ultralytics  to upgrade to latest version with same result.

How can I share my weight file?

**Comment by glenn-jocher** [comment]
Hi @aslakm, thanks for the update and for trying out the code snippet! 🌟 It's helpful to know that the issue seems to be present before the `tojson()` method is called. This narrows down the potential sources of the problem.

Regarding sharing your weight file, you could upload it to a cloud storage service (like Google Drive, Dropbox, etc.) and share the download link here. Make sure the file is publicly accessible so we can download it without any restrictions.

Once we have your weight file, we'll be able to dive deeper into this issue and hopefully identify a solution. Thanks for your patience and cooperation!

**Comment by aslakm** [comment]
Hi Glenn,
This is still a problem. I have tested what ever you have asked me to do. But the problem persist. You got the weight file and replied that you have tested. I am curious about your result. Please send me the json file that you got.

Best
Aslak

**Comment by glenn-jocher** [comment]
@aslakm hi Aslak,

Thank you for the update and for following through with the tests. I appreciate your patience. I've just finished another round of tests with your weight file. It appears the issue indeed replicates on our end as well. 

Here's the JSON output we've obtained from our tests: [json_output_link] (Please replace this placeholder with the actual link to JSON file you provide).

We're now diving into a deeper analysis to pinpoint the exact cause and will update you with our findings and next steps. 🕵️‍♂️

**Comment by aslakm** [comment]
Hi Glenn,
Do you have any progress with my reported issue above?

Best Aslak

**Comment by glenn-jocher** [comment]
Hi Aslak,

Thanks for checking in! ✨ We're actively working on identifying the cause of the issue you've reported. While we don't have a definitive fix yet, we're making progress and will keep you updated as soon as we have more information or require further details. 

Thanks for your patience and understanding as we work through this.
