### ISSUE TITLE
accessing the class in the output 

### ISSUE THREAD

**Issue by ganesh-techs** [ultralytics/ultralytics#8934]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

import os
from ultralytics import YOLO

import torch
import matplotlib
import numpy as np
import cv2qqqqq
import pygame  # Using Pygame for audio playback

# Initialize Pygame for audio
pygame.init()
sound_to_play = pygame.mixer.Sound(r'D:\ML\Syncronised vigilance for driver\alarm.wav')  # Replace with your audio file path

# Load your YOLOv8 model
model = YOLO(r'C:\Users\HP\Downloads\last.pt')

# Open video capture
cap = cv2.VideoCapture(0)  # Change 0 to your camera index if needed

while True:
    ret, frame = cap.read()

    # Run object detection using your YOLOv8 model
    results = model.predict(source="0",show=True)

    # Check for 'sleepy' detection in bounding boxes
    for detection in results.xyxy:  # Assuming detections are directly in results.xyxy
        class_conf = detection[1]  # Confidence score is at index 4
        class_id = int(detection[5])  # Assuming class ID is at index 5 (convert to int)
        if class_names[class_id] == 'sleepy' and class_conf > 0.1:  # Check for 'sleepy' class and minimum confidence
            sound_to_play.play()  # Play the audio if 'sleepy' is detected with sufficient confidence

    # Display the frame with detections (optional)
    cv2.imshow('Frame', results.render())  # Use results.render() for visual output

    if cv2.waitKey(1) == ord('q'):
        break

# Release resources
pygame.quit()
cap.release()
cv2.destroyAllWindows()
this is my code to detect drowsiness,i want play a alarm if "sleepy" class is detected ,i am having issue in accessing the correct coordinates of the class ,i don't know where it is

**Comment by glenn-jocher** [comment]
@ganesh-techs hey there! 👋 It looks like you're on the right track with your drowsiness detection project. However, there's a small mix-up in accessing the detection results. Here's a quick fix:

```python
# Assuming 'results' is a list of Results objects from model.predict()
for result in results:
    # Loop through detections in the current frame
    for *xyxy, conf, cls in result.xyxy[0]:
        # Check if detected class is 'sleepy' with confidence > 0.1
        if result.names[int(cls)] == 'sleepy' and conf > 0.1:
            sound_to_play.play()  # Play the alarm sound
            break  # Exit loop after playing sound for the first 'sleepy' detection
```

Make sure you have `class_names` properly defined or use `result.names` to access class names directly from the `Results` object. Also, it seems there's a typo in your import statement for `cv2`. Let me know if this helps or if you have any more questions! 🚀
