### ISSUE TITLE
Keypoint landmarks and data augmentation

### ISSUE THREAD

**Issue by medmabcf** [ultralytics/ultralytics#8936]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When applying data augmentation like rotation in YOLOv8, the key points do not automatically adjust to the new positions is that right?

**Comment by mzillag** [comment]
My workaround for augmentations like **rotation** while waiting for official way to add custom augs

`from ultralytics import YOLO
from ultralytics.data.augment import Albumentations
from ultralytics.utils import LOGGER, colorstr

img_scale = (640, 640)


def __init__(self, p=1.0):
    """Initialize the transform object for YOLO bbox formatted params."""
    self.p = p
    self.transform = None
    prefix = colorstr("albumentations: ")
    try:
        import albumentations as A

        # check_version(A.__version__, "1.0.3", hard=True)  # version requirement

        # Transforms
        T = [
            A.ShiftScaleRotate(scale_limit=(0.5, 1.5)),
            A.ToGray(p=0.01),
            A.RandomBrightnessContrast(p=0.0),
            A.RandomGamma(p=0.0),
            A.HueSaturationValue(hue_shift_limit=20, sat_shift_limit=30, val_shift_limit=20, p=0.5),
            A.HorizontalFlip(p=0.5),
            A.ImageCompression(quality_lower=75, p=0.0),
            A.Resize(height=img_scale[0], width=img_scale[1]),
            A.PadIfNeeded(min_height=img_scale[0], min_width=img_scale[1], value=(114.0, 114.0, 114.0), p=1)
        ]
        self.transform = A.Compose(T, bbox_params=A.BboxParams(format="yolo", label_fields=["class_labels"]))

        LOGGER.info(prefix + ", ".join(f"{x}".replace("always_apply=False, ", "") for x in T if x.p))
    except ImportError:  # package not installed, skip
        pass
    except Exception as e:
        LOGGER.info(f"{prefix}{e}")


Albumentations.__init__ = __init__
model = YOLO('yolov8s.pt')
save_dir = "runs"
results = model.train(data='../datasets/ds/config.yaml',
                      epochs=1000, imgsz=640, patience=100, seed=42,
                      batch=-1, augment=True, save_dir=save_dir,
                      mosaic=0.5, scale=0.3, hsv_h=0.0, hsv_s=0.0, hsv_v=0.0
                      )
model.export()
`

**Comment by medmabcf** [comment]
@mzillag  thanks
