### ISSUE TITLE
How are the COCO-images  trained?

### ISSUE THREAD

**Issue by dmddmd** [ultralytics/ultralytics#894]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, 
are the pretrained models trained only on single objects 
OR
if there are 10 apples, it takes the apples altogether as apple

**Comment by glenn-jocher** [comment]
Each object is a unique instance in the labelled dataset.
