### ISSUE TITLE
 A bug when exporting YOLOv8-World.pt to ONNX 

### ISSUE THREAD

**Issue by jamjamjon** [ultralytics/ultralytics#8940]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

`names` metadata in ONNX model exported from modified YOLOv8-World.pt(After setting custom classes) will always be assigned with default COCO class names.

### Minimal Reproducible Example

# Details
## Step one: Customize and save my own `YOLOv8-World.pt` model
```python
from ultralytics import YOLO
model = YOLO('yolov8s-worldv2.pt')  
model.set_classes(["shoes"])
model.save("custom_yolov8s-worldv2.pt")
``` 
## Step two: Export to ONNX
```bash
yolo export model=custom_yolov8s-worldv2.pt format=onnx simplify dynamic
```
## Step 3: visualize ONNX model
`names` has been assigned with coco class names.
![image](https://github.com/ultralytics/ultralytics/assets/51357717/7cfea303-db83-4656-9a00-34f28e90da2f)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jamjamjon hey there! 👋 Thanks for bringing this to our attention. It seems like the `names` metadata isn't updating as expected when exporting to ONNX after setting custom classes. This is indeed something we need to look into. 

For a quick workaround, you might consider manually setting the `names` attribute in your exported ONNX model as a temporary solution. Here's a small snippet on how you could potentially do this using the `onnx` Python package:

```python
import onnx
from onnx import helper

# Load your ONNX model
model_path = 'path_to_your_exported_model.onnx'
onnx_model = onnx.load(model_path)

# Assuming 'names' is stored as a StringStringEntryProto in the metadata_props
# Update 'names' to your custom classes
for prop in onnx_model.metadata_props:
    if prop.key == 'names':
        prop.value = '["shoes"]'  # Update this to your custom classes

# Save the modified model
onnx.save(onnx_model, model_path)
```

Please note, this is a generic example and might need adjustments based on how the `names` metadata is structured in your specific ONNX model.

We appreciate your willingness to contribute! If you have insights or a more permanent fix for this issue, feel free to start a discussion or submit a PR. We're all ears! 🚀

**Comment by glenn-jocher** [comment]
@jamjamjon hey there! 🌟

Thanks for taking the time to detail this issue with exporting the YOLOv8-World.pt model to ONNX. It looks like the custom class names aren't carrying over to the ONNX export. We appreciate you bringing this to our attention!

To ensure your custom class names are properly exported to the ONNX model, you might use the metadata alongside the exported model as a workaround. Currently, the export process does not modify the ONNX `names` attribute directly. Here's a brief code snippet for a potential temporary solution:

```python
# Save class names to a file
class_names = ["shoes"]
with open("custom_classes.txt", "w") as file:
    for name in class_names:
        file.write(f"{name}\n")

# Use this custom_classes.txt for further reference in your application
```

This way, you can maintain a record of your custom classes, and then use this as a reference in your applications or systems that utilize the exported ONNX model. 

Regarding fixing this behavior directly in the export process, we'll look into this issue further. Your willingness to help with a PR is greatly appreciated! If you've identified a potential fix, feel free to start a discussion on the PR or share more details, and we'll be happy to collaborate. 

For now, keeping a separate reference for class names might be a practical interim solution. Thanks for your support and contribution to making YOLOv8 even better!
