### ISSUE TITLE
SPD-Conv with YOLOv8

### ISSUE THREAD

**Issue by zeobec** [ultralytics/ultralytics#8942]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Currently, im trying to implement SPD-Conv into yolov8 by replacing with Conv. Does anyone have try it cause mine, the params is 0 for SPD-Conv. Is it correct? 
Anw, this implementation I referred here [https://github.com/LabSAINT/SPD-Conv/tree/main/YOLOv5-SPD](url)
 
![image](https://github.com/ultralytics/ultralytics/assets/96353364/ebed1d06-4b4a-4263-80ee-cd6786cb99d3)

**Comment by zeobec** [comment]
here is the modification that I made

.yaml file 
![image](https://github.com/ultralytics/ultralytics/assets/96353364/9c3f65ac-a1c6-479c-8775-bebe8fc3ad96)

task.py
![image](https://github.com/ultralytics/ultralytics/assets/96353364/b1e45c79-585d-49da-bf3b-b0ad4156514a)

![image](https://github.com/ultralytics/ultralytics/assets/96353364/d9c5671c-33b4-4fd9-bd2e-ecc0a93c8d75)

init.py 
![image](https://github.com/ultralytics/ultralytics/assets/96353364/01ba8cc6-8d99-4c77-a6ff-3b2e091b5acc)

conv.py
![image](https://github.com/ultralytics/ultralytics/assets/96353364/2d18ac40-301d-48f2-ba46-b8d5e5540368)

![image](https://github.com/ultralytics/ultralytics/assets/96353364/a5b505fe-8cd0-485c-938e-93a419b648fe)

**Comment by glenn-jocher** [comment]
@zeobec hey there! 👋 It looks like you're venturing into customizing YOLOv8 with SPD-Conv, a very innovative path to take! From your modification, it's pretty clear you've put in a good effort to incorporate SPD-Conv into YOLOv8. However, seeing the parameters count as 0 might imply that the SPD-Conv layers aren't being recognized correctly or initialized properly.

One quick thing to check is making sure that your `spdconv2d` class in `conv.py` properly extends from PyTorch's `nn.Module` and that parameters within it are correctly set as module parameters (using `nn.Parameter`) or using layers/modules that automatically track their parameters (like `nn.Conv2d`). This ensures PyTorch recognizes and counts them during model summary computations.

```python
import torch.nn as nn

class SPDConv2d(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, stride=1, padding=0):
        super(SPDConv2d, self).__init__()
        # Initialize your SPD-Conv parameters or sub-modules here
        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size, stride, padding)
        # Additional SPD-specific parameters

    def forward(self, x):
        # Your forward pass implementation
        return self.conv(x)  # Example forward pass
```

Ensure that all custom layers or operations in SPD-Conv directly use `nn.Parameter` or base layers (`nn.Conv2d`, `nn.Linear`, etc.) that inherently account for tracking parameters. 

If these are correctly set but you still encounter the parameter count issue, you might need to delve deeper into how the parameters are being registered in your custom implementations or if there's an oversight in the `__init__` method of your custom modules.

Keep pushing the limits! 🔥 Let us know if adjusting these configurations helped or if there's anything else we can assist you with.

**Comment by zeobec** [comment]
@glenn-jocher I have modified the class: 
![image](https://github.com/ultralytics/ultralytics/assets/96353364/e00ffea5-b93e-46cd-9f11-31b22e9e54d8)

but since I got error :TypeError: space_to_depth.__init__() missing 1 required positional argument: 'out_channels'
![image](https://github.com/ultralytics/ultralytics/assets/96353364/29e79df4-6c65-4806-b131-558d60ad1a52)


so, here will be the issue : 
![image](https://github.com/ultralytics/ultralytics/assets/96353364/0dc949c8-f8d9-4dd6-a838-778f180078bc)

**Comment by zeobec** [comment]
Ive found out that actually conv2d is equivalent as spd-conv concept. so, I also tried using the same code as you suggested 
![image](https://github.com/ultralytics/ultralytics/assets/96353364/0bd67a61-e33e-4642-8636-cebad685160e)
but got error: 
![image](https://github.com/ultralytics/ultralytics/assets/96353364/d14906b0-ba62-48de-ae08-5670b9e4faf1)


do you think the issue is because arguments that I set are incorrect:
![image](https://github.com/ultralytics/ultralytics/assets/96353364/499fde65-d337-47ce-ae24-ac05fa6dad8d)

**Comment by glenn-jocher** [comment]
@zeobec hey there! 😊 It's great to see your enthusiasm for exploring and implementing SPD-Conv concepts in YOLOv8. From the snippets you've provided, it looks like the core issue you're encountering relates to the incorrect setup of arguments for your modified `conv2d` class. 

It seems like you're passing an `out_channels` argument in a place where it's not expected according to your custom class definition. If `conv2d` is indeed equivalent to SPD-Conv as per your finding, ensure that your class `__init__` method and where you're instantiating the class match in terms of the arguments being passed.

For example, if your class definition requires an `out_channels` argument:

```python
class CustomConv2d(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, stride=1):
        super(CustomConv2d, self).__init__()
        # Your initialization code
```

Make sure when you create an instance of `CustomConv2d`, you include `out_channels` in your arguments:

```python
# Incorrect
self.conv = CustomConv2d(in_channels=32, kernel_size=3, stride=2)

# Correct
self.conv = CustomConv2d(in_channels=32, out_channels=64, kernel_size=3, stride=2)
```

Double-check the definition of your custom `conv2d` or SPD-Conv class and the parameters you're passing when creating its instance. Aligning them should help you resolve the error.

Keep up the good work! Reach out if you need more help. 👍

**Comment by StuffyMonkey** [comment]
I've reproduced steps above but with yolov10 version [https://github.com/THU-MIG/yolov10] based on ultralytics, but after loading model like below I see no difference with default architecture:
```
from ultralytics import YOLO

model = YOLO(model='yolov10l')
```
I suppose, that after initializing YOLO like above we just load pretrained weights, not modified model. So, how can I load modified model and use it?

**Comment by pderrenger** [comment]
@StuffyMonkey thank you for your question. When you initialize the YOLO model as shown, it loads the default architecture and pretrained weights. To load a modified model, you need to ensure that the custom architecture is defined and available in your environment. You can then specify the path to your custom model's configuration file or weights when initializing the model. If you encounter any issues, please verify that your custom model files are correctly formatted and accessible.

**Comment by glenn-jocher** [comment]
@StuffyMonkey thank you for your input. You're correct that the "Focus" layer in YOLO serves a similar purpose to SPD-Conv2d, and it's already implemented in the Ultralytics models. If you have further questions or need assistance, feel free to ask!

**Comment by furycurry** [comment]
Hello @zeobec .
I am also trying to implement a similar approach. May I ask if you were able to accomplish the task successfully.

**Comment by zeobec** [comment]
Hello @furycurry. Im not sure the implementation is correct or not but I managed to train it. Just replaced the Conv with Focus

**Comment by furycurry** [comment]
May I have a look at your yaml file? @zeobec

**Comment by furycurry** [comment]
> @StuffyMonkey thank you for your input. You're correct that the "Focus" layer in YOLO serves a similar purpose to SPD-Conv2d, and it's already implemented in the Ultralytics models. If you have further questions or need assistance, feel free to ask!

When I am trying to implement it in my code base, I am facing this error:
```
line 2416, in _verify_batch_size
    raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])
```
Here is the yaml file:
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Focus, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Focus, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Focus, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Focus, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2f, [512]] # 12
  - [-1, 1, EMA, [8]] #13

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2f, [256]] # 16 (P3/8-small)
  - [-1, 1, EMA, [8]] #17

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 13], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2f, [512]] # 20 (P4/16-medium)
  - [-1, 1, EMA, [8]] # 21

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2f, [1024]] # 24 (P5/32-large)
  - [-1, 1, EMA, [8]] #24

  - [[17, 21, 25], 1, Detect, [nc]] # Detect(P3, P4, P5)
@glenn-jocher @zeobec

**Comment by furycurry** [comment]
@glenn-jocher I want to mention the `Focus` implementation in my research work. How can I do that or how can I describe the structure of how it works? Shall I mention the [`SPDConv`](https://link.springer.com/chapter/10.1007/978-3-031-26409-2_27) as you mentioned `Focus` is similar to [`SPDConv`](https://link.springer.com/chapter/10.1007/978-3-031-26409-2_27)?

**Comment by glenn-jocher** [comment]
You can describe `Focus` as a layer that reduces spatial dimensions by slicing the input into four parts and concatenating them along the channel dimension, followed by a convolution operation. While it shares similarities with SPDConv, you should focus on the specific mechanics of `Focus` as implemented in the [Ultralytics codebase](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/modules/conv.py) to ensure accuracy in your research work.

**Comment by furycurry** [comment]
@glenn-jocher can you refer any source from which I will be able to understand how `Focus` layer in ultralytics functions?

**Comment by glenn-jocher** [comment]
You can refer to the official implementation of the `Focus` layer in the Ultralytics codebase here: [Focus Layer in ultralytics/nn/modules/conv.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/modules/conv.py#L141). It includes the source code and explanation of its functionality.

**Comment by furycurry** [comment]
> You can refer to the official implementation of the `Focus` layer in the Ultralytics codebase here: [Focus Layer in ultralytics/nn/modules/conv.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/modules/conv.py#L141). It includes the source code and explanation of its functionality.

Thanks @glenn-jocher

**Comment by glenn-jocher** [comment]
You're welcome! If you have any further questions or need clarification, feel free to ask. The YOLO community and Ultralytics team are here to help.

**Comment by absit23** [comment]
is SPD-conv mathematically same as Focus Conv ?

**Comment by glenn-jocher** [comment]
They’re closely related but not strictly “mathematically the same” in all implementations: Ultralytics `Focus` is a specific `space-to-depth` (downsample by 2, channels ×4 via slicing/concat) followed by a convolution, so it matches SPD-Conv only if your SPD-Conv uses the exact same rearrangement (and the same conv settings). See the exact `Focus.forward()` definition in the [Ultralytics `Focus` layer reference](https://docs.ultralytics.com/reference/nn/modules/conv/).
