### ISSUE TITLE
Read every nth frame from RTSP for object tracking

### ISSUE THREAD

**Issue by pornpra** [ultralytics/ultralytics#8951]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi

I am currently using a pre-trained yolov8s model to run object tracking inference on RTSP, the problem is that the source are streamed at 30 FPS , I actually don't want to process each frame for object detection and tracking and just process every nth frame. My questions are 

1. Do I need to adjust **vid_stride** parameter to process every nth frame ?
2. Does Ultralytics version 8.0.200 support the adjustment of vid_stride when loading a source ?
3. Can I adjust vid_stride for MP4 source ?

![image](https://github.com/ultralytics/ultralytics/assets/59501173/afb4165e-b7d7-4f76-b5f1-2ccb80eda497)

Thanks

**Comment by glenn-jocher** [comment]
@pornpra hello! 👋

Indeed, to process every nth frame from your RTSP streamed video, you can adjust the `vid_stride` parameter. For instance, to process every 3rd frame, you would set `vid_stride=3`. This is applicable to both RTSP streams and MP4 files. As of Ultralytics YOLOv8 version 8.0.200, you can use `vid_stride` in your command like so:

```bash
yolo track model=yolov8s.pt source=rtsp://example.com/stream vid_stride=3
```

or for MP4:

```bash
yolo track model=yolov8s.pt source='path/to/video.mp4' vid_stride=3
```

This way, the model will only process every 3rd frame, potentially reducing computation overhead and speeding up inference on high FPS sources. 🚀

Let me know if this answers your questions or if there's anything else you'd like to know!

Cheers!

**Comment by pornpra** [comment]
Thanks for your response.

Can I pass vid_stride as parameter in the below Python code ?

results = model.track(source="https://youtu.be/LNwODJXcvt4", conf=0.3, iou=0.5, show=True,  **vid_stride=3**)

**Comment by glenn-jocher** [comment]
@pornpra hello! 😊 

Yes, you can absolutely pass `vid_stride` as a parameter in your Python code for tracking, just like you've shown. However, please replace the `**` with a regular assignment like this:

```python
results = model.track(source="https://youtu.be/LNwODJXcvt4", conf=0.3, iou=0.5, show=True, vid_stride=3)
```

This will ensure that every 3rd frame is processed, helping you manage high FPS sources more efficiently. 

Let me know if you need further assistance! Happy coding! 🚀
