### ISSUE TITLE
Are there plans to support YOLO-World training?

### ISSUE THREAD

**Issue by lxjhunan** [ultralytics/ultralytics#8954]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

NotImplementedError: WARNING ⚠️ 'YOLOWorld' model does not support 'train' mode for 'detect' task yet.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@lxjhunan thanks for checking in about the YOLO-World training support and for your willingness to contribute! 🌟 Currently, training support for the YOLO-World model isn't implemented yet. However, we're always keen to expand our model capabilities and your interest in submitting a PR is highly appreciated. For contributing, I recommend starting by familiarizing yourself with the contributing guidelines in our repository. If you have a specific implementation plan or need further discussion on how this feature could be integrated, feel free to open a discussion thread. Let's make YOLO even better together!

**Comment by CaffeineLiqueur** [comment]
Looking forward to the implementation of YOLO-World training support!

**Comment by glenn-jocher** [comment]
@CaffeineLiqueur hey there! 🎉 We're equally excited about the possibility of adding training support for YOLO-World. It's on our radar, and updates will be shared as we make progress. Stay tuned, and don't hesitate to share any thoughts or preliminary work you might have - every bit helps. Thanks for being a part of our journey! 🚀
