### ISSUE TITLE
Is there a plan to support yolo-world training?

### ISSUE THREAD

**Issue by lxjhunan** [ultralytics/ultralytics#8963]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

the yolo-world model is now support inference in ultralytics framework, but finetune and training is not supported.

**Comment by glenn-jocher** [comment]
@lxjhunan thanks for your inquiry about YOLO-World training support! 🌍

As of now, we focus on robust inference support for YOLO-World within the Ultralytics framework. Training and fine-tuning capabilities for YOLO-World are indeed areas we're excited about exploring in the future. 

Stay tuned for updates on this, and your feedback is always appreciated in guiding our roadmap! Feel free to contribute ideas or express your specific needs in the [discussions](https://github.com/ultralytics/ultralytics/discussions) section. Happy detecting!
