### ISSUE TITLE
can i change the train parameter when resume?

### ISSUE THREAD

**Issue by bovo1** [ultralytics/ultralytics#8969]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I resumed training, but I want to change parameters such as lr0. What should I do?
Setting resume=True and changing lr0 to a different value has no effect.

**Comment by glenn-jocher** [comment]
@bovo1 sure, when resuming training in YOLOv8 and you want to adjust parameters like `lr0`, you should use the `--hyp` argument along with your custom hyperparameters YAML file where you've defined the new `lr0` value. Unfortunately, directly changing `lr0` or other hyperparameters via command line args won't work when using `resume=True`. Here's a quick example:

1. First, update or create a YAML file (e.g., `new_hyp.yaml`) with your desired hyperparameters including `lr0`.

```yaml
# new_hyp.yaml
lr0: 0.002  # new learning rate
```

2. Then, resume training with the `--hyp` argument pointing to your new hyperparameters file.

```bash
yolo detect train --resume --hyp new_hyp.yaml
```

Hope this helps! Let us know if you have any more questions. 😊

**Comment by bovo1** [comment]
I tried what you told me, but I got a warning.

!yolo task=segment mode=train resume=True model=/content/drive/MyDrive/PetHealth/skin_disease/Dog/runs/segment/2024-03-13-t2/weights/best.pt cfg=/content/new_hyperparameter.yaml


---------------------------

Overriding /usr/local/lib/python3.10/dist-packages/ultralytics/cfg/default.yaml with /content/new_hyperparameter.yaml
WARNING ⚠️ 'mode' is missing. Valid modes are ('train', 'val', 'predict', 'export', 'track', 'benchmark'). Using default 'mode=train'.
WARNING ⚠️ 'model' is missing. Using default 'model=yolov8n.pt'.
WARNING ⚠️ 'data' is missing. Using default 'data=coco8.yaml'.
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla T4, 15102MiB)
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=coco8.yaml, epochs=500, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train, exist_ok=True, pretrained=True, optimizer=Adam, verbose=True, seed=0, deterministic=True, single_cls=False, rect=True, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.001, lrf=0.01, momentum=0.937, weight_decay=0.001, warmup_epochs=5.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=90.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.3, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train

**Comment by glenn-jocher** [comment]
@bovo1 hey there! It seems like there was a slight mix-up in the command syntax. 🤔 The warning messages indicate that some of the required arguments like `mode` were not recognized correctly, and some defaults were used instead.

When using the CLI, make sure each argument follows the format `ARG=value`. In your case, try modifying your command as follows:

```bash
!yolo task=segment mode=train resume=True model=/content/drive/MyDrive/PetHealth/skin_disease/Dog/runs/segment/2024-03-13-t2/weights/best.pt --hyp=/content/new_hyperparameter.yaml
```

Note the use of `--hyp` to specify the hyperparameter file. 😊 Also, ensure all arguments are separated by spaces and correctly labeled. Give it another go and let us know if the issue persists!

**Comment by bovo1** [comment]
@glenn-jocher 
Thank you for your answer.
But, there is an error as below.

----------------------

Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 501, in entrypoint
    check_dict_alignment(full_args_dict, overrides)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 308, in check_dict_alignment
    raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'hyp' is not a valid YOLO argument.

**Comment by glenn-jocher** [comment]
@bovo1 hey there! 😊 It looks like there's been a little mix-up with the usage of `hyp` in the CLI command. At the moment, `hyp` isn't directly used as a CLI argument to adjust hyperparameters when resuming training or making other modifications. 

Instead of using `--hyp`, you should directly modify your `new_hyperparameter.yaml` file with the desired learning rates or other hyperparameters and then refer to this modified file in your initial training command or ensure it's correctly set up in your training script.

If adjustments are needed after training has started or to resume with different parameters, those changes are typically made within the hyperparameter file itself, or training is resumed with adjustments in the script rather than through CLI arguments for `hyp`.

Hope this helps clarify things a bit! If you need further assistance or examples, just let us know.
