### ISSUE TITLE
Video prediction/tracking skips first (0th) frame

### ISSUE THREAD

**Issue by memben** [ultralytics/ultralytics#8976]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict, Other

### Bug

It seems that the first (or rather 0th) frame is not predicted when using yolo predict/track.

Compare the first frame of this [video](https://www.vecteezy.com/video/28257904-people-walking-across-the-road-on-zebra) with the tracked version (using vid_stride=30 to highlight the difference). Using vid_stride = 1, the output video is one frame shorter than the original.

<img width="614" alt="image" src="https://github.com/ultralytics/ultralytics/assets/59774249/73c85025-cb36-48d4-84f9-298c15e975fa">

<img width="1258" alt="image" src="https://github.com/ultralytics/ultralytics/assets/59774249/9812552c-4db6-4fde-bacb-2dd8a893ffe0">

### Minimal Reproducible Example

```python
from ultralytics import YOLO

model = YOLO("path/to/yolo")
video = "path/to/video"
model.track(video, save=True, vid_stride=30)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@memben hey there! 👋 Thanks for bringing this to our attention. It looks like you've encountered an interesting behavior regarding frame handling during video processing with YOLO predict/track. 

It's possible that this issue could be related to how frames are initially loaded and processed. As a quick workaround, you might consider manually adjusting the start frame for processing if feasible, ensuring that all frames, including the 0th one, are accounted for.

However, this surely needs a deeper look to ensure a more robust and automatic handling of all frames, especially the first one, in future updates. 🛠️

Your detailed observation and example are super helpful! We'll look into this and keep you posted. Feel free to keep any additional info coming, and if there's a fix or patch, we'll update the thread here. Thanks for being a part of the YOLO community! 😊 

For now, if you're directly manipulating video data, adding a placeholder or adjusting frame count could be a temporary fix:
```python
# Pseudocode for adding a placeholder frame
video = "path/to/video"  # Your video
placeholder_frame = some_function_to_get_placeholder_frame()
frames = [placeholder_frame] + extract_frames(video)
process_frames_as_usual(frames)
```
Let's keep the dialogue open for any updates or shared solutions from others encountering the same!

**Comment by memben** [comment]
Hey, thank you for your quick reply! My temporary solution is using cv2.VideoCapture:
```python
def video_frame_iterator(cap: cv2.VideoCapture, frame_step: int) -> Generator[cv2.typing.MatLike, None, None]:
    frame_nr = 0
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        if frame_nr % frame_step == 0:
            yield VideoFrame(frame_nr, frame)
        frame_nr += 1

cap = cv2.VideoCapture(video_path)
for frame in video_frame_iterator(cap, 10):
    yolo.track(frame, persist=True)
cap.release()
```

**Comment by glenn-jocher** [comment]
@memben hey there! 👋 That's a great workaround using `cv2.VideoCapture`! It gives you fine-grained control over frame iteration and processing, nicely done. 🎉 Your approach of iterating through frames with a custom step is a good way to manage what frames to process, especially helpful for long videos or when looking to reduce computation.

Your solution also intuitively skirts around the issue by pulling frames directly, ensuring you start exactly where intended without missing any. If you encounter any more questions or have insights to share as you go along, don't hesitate to drop a note. Happy coding! 😊
