### ISSUE TITLE
Getting error after changing reg_pts value for Coordinate of line of object counter file

### ISSUE THREAD

**Issue by ImranAhsan15** [ultralytics/ultralytics#8979]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hi. Hope you are well. I am facing an issue about changing the Line. When i am going to move the line downward the entire video stopped running after some time.
I mean reg_pts value for single line. When i use reg_pts = [(0,314),(1000,314)] it works fine but when i use reg_pts = [(0,315),(1000,315)] it stopped working. I need to move the line more downward by increasing y value. But when i am going to increase the y1 and y2 value the code stopped working after passing some seconds..

**Comment by glenn-jocher** [comment]
@ImranAhsan15 hello! 👋 Thanks for reaching out with your question. 

It seems like the issue might be tied to the specific position of `reg_pts` in the video frame. When you adjust the y-coordinate for the line, it may be surpassing the maximum height of your video frames, leading to the error or the video stopping. 

Here's something you can try to debug and ensure the `reg_pts` coordinates are within the video frame bounds:
1. Check the resolution of your video to get the `height` and `width`.
2. Ensure that the `y` value in `[(x1, y1), (x2, y2)]` does not exceed the `height` of the video.

Example to check video resolution:
```python
import cv2

# Load your video
cap = cv2.VideoCapture('path/to/your/video.mp4')
width = cap.get(cv2.CAP_PROP_FRAME_WIDTH)
height = cap.get(cv2.CAP_PROP_FRAME_HEIGHT)

print(f"Video resolution: {width}x{height}")
cap.release()
```

Make sure your `reg_pts` y-values are less than the `height` obtained. I hope this helps! If the issue persists, please share more details such as the error message you see when the code stops working. 🛠️
