### ISSUE TITLE
How can I smooth the masks of my segmentation model?

### ISSUE THREAD

**Issue by sism96** [ultralytics/ultralytics#8986]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I smooth the masks of my segmentation model?

Precisely that. I have a fish segmentation model and I need the masks to look smoother on the outline of the fish. Is it possible to apply some type of filter that softens the masks so that they look good in inference?

Help me please :(
![imagen](https://github.com/ultralytics/ultralytics/assets/106342989/a79cf214-146a-45ae-8228-0c6667e38dce)

### Additional

I'm working with some videos and I would like to make the inference look clean and stable. Plus I can't get the masks to be clarified. Actually I am looking to have a stable, clean inference, and with the masks as tight as possible to the edge of the fish.

_No response_

**Comment by glenn-jocher** [comment]
@sism96 hi there! 🐠 Smoothing the masks for your segmentation model can indeed enhance the visual quality of your inferences. One common approach to achieve smoother masks is to utilize morphological operations like erosion and dilation, or applying Gaussian blur. Here's a quick example leveraging OpenCV in Python:

```python
import cv2
import numpy as np

# Assuming 'mask' is your binary segmentation mask output
mask = cv2.imread('path_to_your_mask.jpg', 0)

# Apply Gaussian blur
smoothed_mask = cv2.GaussianBlur(mask, (5, 5), 0)

# Convert back to binary
_, smoothed_mask = cv2.threshold(smoothed_mask, 127, 255, cv2.THRESH_BINARY)
```

Remember to adjust the `(5, 5)` kernel size in `cv2.GaussianBlur` for blur intensity and experiment with values to find the best fit for your model. 

For achieving stable and clean inference, especially in video data, you might also explore temporal consistency techniques, which are more advanced and could require custom implementations.

Hope this helps you get started towards cleaner, smoother segmentation! If you have further questions or run into any issues, feel free to reach out. Happy coding!

**Comment by sism96** [comment]
> @sism96 hi there! 🐠 Smoothing the masks for your segmentation model can indeed enhance the visual quality of your inferences. One common approach to achieve smoother masks is to utilize morphological operations like erosion and dilation, or applying Gaussian blur. Here's a quick example leveraging OpenCV in Python:
> 
> ```python
> import cv2
> import numpy as np
> 
> # Assuming 'mask' is your binary segmentation mask output
> mask = cv2.imread('path_to_your_mask.jpg', 0)
> 
> # Apply Gaussian blur
> smoothed_mask = cv2.GaussianBlur(mask, (5, 5), 0)
> 
> # Convert back to binary
> _, smoothed_mask = cv2.threshold(smoothed_mask, 127, 255, cv2.THRESH_BINARY)
> ```
> 
> Remember to adjust the `(5, 5)` kernel size in `cv2.GaussianBlur` for blur intensity and experiment with values to find the best fit for your model.
> 
> For achieving stable and clean inference, especially in video data, you might also explore temporal consistency techniques, which are more advanced and could require custom implementations.
> 
> Hope this helps you get started towards cleaner, smoother segmentation! If you have further questions or run into any issues, feel free to reach out. Happy coding!

Thank you for your previous response. I've successfully applied Gaussian blur to the entire video frames to smooth out the segmentation masks. However, this approach also blurs the background and other elements, which is not desirable. My goal is to apply the Gaussian blur filter exclusively to the segmentation masks for each frame of the video, enhancing the visual quality of the masks without affecting the clarity of the rest of the image. Could you advise on whether it's possible to apply Gaussian blur specifically and only to the segmentation masks? If so, how might I implement this to affect only the masks in each video frame?

**Comment by glenn-jocher** [comment]
Hi @sism96! Great to hear that you've successfully applied Gaussian blur to your frames! 😊 To exclusively blur the masks without affecting the rest of the frame, you can simply apply the blur to your binary mask and then combine it back with the original frame. Here's a quick way to do it:

```python
import cv2
import numpy as np

# Load your original frame and mask
frame = cv2.imread('path_to_your_frame.jpg')
mask = cv2.imread('path_to_your_mask.jpg', 0)  # Load mask as grayscale

# Apply Gaussian blur to the mask only
blurred_mask = cv2.GaussianBlur(mask, (5, 5), 0)

# Create a 3-channel mask to apply over the original frame
blurred_mask_3ch = cv2.cvtColor(blurred_mask, cv2.COLOR_GRAY2BGR)

# Use the mask to blend with the original frame
final_frame = np.where(blurred_mask_3ch == 255, cv2.GaussianBlur(frame, (5, 5), 0), frame)

# Save or show the final frame
cv2.imwrite('path_to_final_frame.jpg', final_frame)
```

This implementation blurs just the areas of the frame corresponding to your segmentation masks. Make sure to adjust the Gaussian blur parameters (i.e., the kernel size) as needed to achieve the desired smoothness.

Hope this helps achieve that crisp yet smooth look for your masked regions! 🌟 Let me know if you have any more questions!

**Comment by sism96** [comment]
> @sism96 hi there! 🐠 Smoothing the masks for your segmentation model can indeed enhance the visual quality of your inferences. One common approach to achieve smoother masks is to utilize morphological operations like erosion and dilation, or applying Gaussian blur. Here's a quick example leveraging OpenCV in Python:
> 
> ```python
> import cv2
> import numpy as np
> 
> # Assuming 'mask' is your binary segmentation mask output
> mask = cv2.imread('path_to_your_mask.jpg', 0)
> 
> # Apply Gaussian blur
> smoothed_mask = cv2.GaussianBlur(mask, (5, 5), 0)
> 
> # Convert back to binary
> _, smoothed_mask = cv2.threshold(smoothed_mask, 127, 255, cv2.THRESH_BINARY)
> ```
> 
> Remember to adjust the `(5, 5)` kernel size in `cv2.GaussianBlur` for blur intensity and experiment with values to find the best fit for your model.
> 
> For achieving stable and clean inference, especially in video data, you might also explore temporal consistency techniques, which are more advanced and could require custom implementations.
> 
> Hope this helps you get started towards cleaner, smoother segmentation! If you have further questions or run into any issues, feel free to reach out. Happy coding!

Thank you for your previous response. I've successfully applied Gaussian blur to the entire video frames to smooth out the segmentation masks. However, this approach also blurs the background and other elements, which is not desirable. My goal is to apply the Gaussian blur filter exclusively to the segmentation masks for each frame of the video, enhancing the visual quality of the masks without affecting the clarity of the rest of the image. Could you advise on whether it's possible to apply Gaussian blur specifically and only to the segmentation masks? If so, how might I implement this to affect only the masks in each video frame?

> ```python
> blurred_mask = cv2.GaussianBlur(mask, (5, 5), 0)
> 
> # Create a 3-channel mask to apply over the original frame
> blurred_mask_3ch = cv2.cvtColor(blurred_mask, cv2.COLOR_GRAY2BGR)
> 
> # Use the mask to blend with the original frame
> final_frame = np.where(blurred_mask_3ch == 255, cv2.GaussianBlur(frame, (5, 5), 0), frame)
> ```

Thank you very much for answering me again.

I have not been able to correctly apply the solution you gave me because it gives me an error that there is a problem when trying to convert blurred_mask from grayscale to BGR with cv2.cvtColor(blurred_mask, cv2.COLOR_GRAY2BGR). Specifically it mentions that the number of channels in the input image is invalid because scn (number of channels in the source image) is 3. This means that blurred_mask is already in color or for some reason OpenCV thinks it is dealing with a 3 channel image at this point in the code.

The truth is I'm not working with images, as I mentioned there are a few videos and I make inferences this way:

def run_tracker_in_thread(filename, model, file_index):
     video = cv2.VideoCapture(filename)
    
     cv2.namedWindow("Tracking Stream smooth", cv2.WINDOW_NORMAL)
     while True:
         ret, frame = video.read() # Read the video frames

         if not ret:
             break

         results = model.predict(frame)
         res_plotted = results[0].plot(labels=False,boxes=False)
        
         out.write(res_plotted)

         cv2.imshow("Tracking Stream smooth", frame_with_mask)

         key = cv2.waitKey(5)

         if key & 0xFF == ord('q'):
             break
    
     video.release()

I would appreciate it if you could help me in this context. Thank you so much

**Comment by glenn-jocher** [comment]
Hi @sism96! It seems like there was a little misunderstanding in applying the blur exclusively to the masks. My apologies for the confusion. 🙏 Here’s a refined approach that you can integrate directly into your tracking function. Essentially, we'll blur the mask and then apply it to the original frame:

1. First, ensure your mask is a single channel binary image (white for the object, black for the background).
2. Apply Gaussian blur to your mask.
3. Convert the blurred mask back to binary if necessary.
4. Finally, apply the blurred mask to your frame.

```python
import cv2
import numpy as np

def apply_blurred_mask(frame, mask):
    # Ensure mask is single channel, apply Gaussian blur
    blurred_mask = cv2.GaussianBlur(mask, (21, 21), 0)
    
    # Threshold blurred mask to convert back to binary
    _, binary_mask = cv2.threshold(blurred_mask, 127, 255, cv2.THRESH_BINARY)
    
    # Convert binary mask to 3 channel format to work with the original frame
    binary_mask_3ch = cv2.cvtColor(binary_mask, cv2.COLOR_GRAY2BGR)
    
    # Apply mask to frame: where mask is white, apply Gaussian blur to frame
    blurred_frame = cv2.GaussianBlur(frame, (21, 21), 0)
    final_frame = np.where(binary_mask_3ch == 255, blurred_frame, frame)
    
    return final_frame

# Inside your loop where you read the frame and the mask
# frame = ... # Your original frame
# mask = ... # Your segmentation mask, ensure it's binary
final_frame = apply_blurred_mask(frame, mask)
```
This function blurs only the areas defined by the mask, leaving the rest of the frame untouched. In your tracking function, you'd need to supply the `frame` and the corresponding `mask` for each frame. Ensure `mask` is the binary segmentation mask for best results.

Regarding the error you encountered, it suggests an issue with the input mask format to `cvtColor()`. Ensure `mask` is indeed single-channel. Adjust the `(21, 21)` kernel size for both the `GaussianBlur` calls to fine-tune the blur effect.

Hope this clears things up and you're able to achieve the desired effect on your video segmentation masks! Keep me posted if there's more I can help with. 😊

**Comment by senthurram03** [comment]
@glenn-jocher 
I am applying the masks generated by YOLO-v8 segmentation model on the actual image foe further reference, is there any way to smooth the output mask as that will improve my post processes??
![image0](https://github.com/ultralytics/ultralytics/assets/113022836/c08938f7-c7c4-4ef1-a5e6-a4eaee14789f)

**Comment by glenn-jocher** [comment]
@senthurram03 hi there! Absolutely, to smooth out your masks and reduce the rough edges, applying a slight Gaussian blur to your mask before using it for further processing can be very helpful. Here's a quick snippet:

```python
import cv2

# Assuming 'mask' is your binary segmentation mask
mask = cv2.imread('path_to_your_mask.jpg', 0)

# Apply Gaussian blur
blurred_mask = cv2.GaussianBlur(mask, (5, 5), 0)

# Optional: Convert back to binary to maintain mask sharpness
_, final_mask = cv2.threshold(blurred_mask, 127, 255, cv2.THRESH_BINARY)
```
Tweak the `(5, 5)` kernel size to find the perfect balance for your needs. 😊 Happy coding!

**Comment by senthurram03** [comment]
@glenn-jocher   I think you misunderstood the question, I want to smooth out the YOLO segments generated by the model to have smooth edges, can it be done??

**Comment by glenn-jocher** [comment]
@senthurram03 hi there! 😊 My apologies for any confusion earlier. To smooth out the edges of YOLOv8 segmentation masks, you can indeed use operations like Gaussian blur specifically on the mask. Here's a quick example:

```python
import cv2

# Load your mask
mask = cv2.imread('your_mask.jpg', 0)

# Apply Gaussian blur
smooth_mask = cv2.GaussianBlur(mask, (5, 5), 0)

# Ensure mask is binary
_, smooth_mask = cv2.threshold(smooth_mask, 127, 255, cv2.THRESH_BINARY)
```

This should help you get smoother edges on your segments. Adjust the `(5, 5)` kernel size as needed. Happy coding!

**Comment by senthurram03** [comment]
@glenn-jocher  can YOLO segmentation gives any relevant data based on the segmentation, like if the segmentation is done fully or partially??

**Comment by glenn-jocher** [comment]
@senthurram03 hey there! 😊 YOLO segmentation models primarily output masks corresponding to detected objects, so direct quantitative analysis like partial/complete segmentation or measuring specific quantities (e.g., urine volume) isn't provided out-of-the-box.

However, you can analyze the masks post-segmentation for such insights. For volume or quantity estimation, consider additional steps like pixel-to-real-world unit conversion based on known parameters or calibration data. Here’s a simplified approach:

1. Get the segmentation mask for the intended object.
2. Calculate the mask area (count non-zero pixels if binary mask).
3. Convert the area to real-world volume using a pre-determined scale.

```python
import cv2
import numpy as np

# Assuming mask is a binary mask of your segmented object
mask = cv2.imread('segmentation_mask.jpg', 0)
non_zero_pixels = cv2.countNonZero(mask)

# Convert pixels to real-world units (this scale would depend on your setup)
scale = 0.1  # Example scale: 0.1 ml per pixel
volume_ml = non_zero_pixels * scale

print(f"Estimated volume: {volume_ml} ml")
```

This example offers a basic route for such analysis. The specific scale and method may need adjustments based on your application's details. Happy coding!

**Comment by senthurram03** [comment]
@glenn-jocher We have tried pixel counting methods and they don't work good on rotated images, can you recommend which deep learning method can be used for this?? We tried CNN and RESNET and they work good but fail in some cases, is there any particular deep learning method that suits this use case?? Like detecting a regression number from the shape of the segment

**Comment by glenn-jocher** [comment]
@senthurram03 hi there! For challenges with rotated images, I recommend exploring models that inherently handle rotation well. Transformers, especially those tailored for vision tasks (like ViT or DETR), can be quite effective due to their attention mechanisms which are less sensitive to object orientation. Additionally, investigating Rotation Invariant CNNs which are designed to handle rotations gracefully might also prove beneficial. 

If you're looking into regression from shapes, incorporating geometric deep learning principles, which focus on understanding shapes and structures, could provide promising results.

For segmentation tasks, U-Net models might also be worth exploring due to their effectiveness in image segmentation across various domains.

Here's a quick example with a vision transformer:

```python
from torchvision.models import vit_b_16
model = vit_b_16(pretrained=True)  # Load a pre-trained Vision Transformer
```

Adjust depending on your specific task and libraries! Happy experimenting! 😊

**Comment by senthurram03** [comment]
@glenn-jocher think I might be bugging you a lot, but I couldn't do the pre-training in the vit_b_16 models, there is a issue in  replacing the final layer with regression head,

```
class RegressionViT(nn.Module):
    def __init__(self, in_features=224 * 224 * 3, num_classes=1):
        super(RegressionViT, self).__init__()
        self.vit_b_16 = vit_b_16(pretrained=True)

        # Freeze pre-trained layers (optional)
        for param in self.vit_b_16.parameters():
            param.requires_grad = False

        # Add new regression head
        self.regression_head = nn.Linear(self.vit_b_16.head.in_features, num_classes)

    def forward(self, x):
        x = self.vit_b_16(x)  # Extract features using pre-trained model
        x = self.regression_head(x)  # Apply regression head
        return x
```
There is this issue here,
**AttributeError: 'VisionTransformer' object has no attribute 'head'**

Can you guide me in this??

**Comment by glenn-jocher** [comment]
@senthurram03 hey there! No worries at all, happy to help 😊. It looks like the issue arises because the Vision Transformer model (`vit_b_16`) does not have an attribute named `'head'`. Normally, the final classification layer is named differently, perhaps `'fc'` or similar.

If you're working with the `torchvision` models, you might want to replace the final layer like this:

```python
from torchvision.models import vit_b_16
import torch.nn as nn

class RegressionViT(nn.Module):
    def __init__(self, num_classes=1):
        super(RegressionViT, self).__init__()
        self.vit_b_16 = vit_b_16(pretrained=True)

        # Freeze pre-trained layers (optional)
        for param in self.vit_b_16.parameters():
            param.requires_grad = False

        # Replace the classifier head
        self.vit_b_16.heads = nn.Linear(self.vit_b_16.heads[0].in_features, num_classes)

    def forward(self, x):
        x = self.vit_b_16(x)  # Extract features using the pre-trained model
        return x
```

This should set you up with a regression head on top of the pre-trained `vit_b_16` model. Just double-check the exact name of the final classification layer (it could be `heads`, `fc`, etc., depending on how your model is structured). Hope this points you in the right direction! 🚀

**Comment by senthurram03** [comment]
Hello @glenn-jocher, thanks for the above answer, the architecture became trainable.
But for this model architecture the training loss is persistent at 40k and does not come down
```

train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(degrees=15),
    # transforms.RandomResizedCrop((224, 224)),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1),
    transforms.ToTensor(),
    # transforms.Grayscale(num_output_channels=3),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]) ])

validation_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    # transforms.Grayscale(num_output_channels=3),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]) ])
# Load datasets
train_dataset = RegressionDataset(train_img_dir, train_path, transform=transform)
val_dataset = RegressionDataset(val_image_dir, val_path, transform=transform)

batch_size = 32

# Assuming you have a DataLoader for training and testing, update accordingly
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=4)
test_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=4)

class RegressionViT(nn.Module):
    def __init__(self, num_classes=1):
        super(RegressionViT, self).__init__()
        self.vit_b_16 = vit_b_16(pretrained=True)

        # Freeze pre-trained layers if it needs to be un-trained
        for param in self.vit_b_16.parameters():
            param.requires_grad = True

        # Replace the classifier head
        self.vit_b_16.heads = nn.Linear(self.vit_b_16.heads[0].in_features, num_classes)

    def forward(self, x):
        x = self.vit_b_16(x)  # Extract features using the pre-trained model
        return x


# Model, Loss function, and Optimizer
model = RegressionViT(num_classes=1)  # Adjust num_classes for multiple outputs
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

least_loss = 10000
best_model = None
train_loss_li = []
valid_loss_li = []

criterion = nn.MSELoss()  # Use appropriate loss function for regression
optimizer = optim.Adam(model.parameters(), lr=0.001)  # Adjust learning rate as needed

num_epochs = 100  # Adjust based on dataset size and convergence
for epoch in range(num_epochs):
    # Train on your training data loader
    train_loss = 0.0
    model.train()

    for images, targets in train_loader:
        images, targets = images.to(device), targets.to(device)
        # print('Targets shape', targets.view(-1, 1).float().shape)
        # Forward pass, calculate loss, and perform backward pass
        outputs = model(images)
        # print(outputs.shape)
        loss = criterion(outputs, targets.view(-1, 1).float())  # Ensure targets are float for regression
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        train_loss += loss.item()
    train_loss_li.append(train_loss)

    # Validate on your validation data loader
    model.eval()
    with torch.no_grad():
        val_loss = 0.0
        for images, targets in test_loader:
            images, targets = images.to(device), targets.to(device)
            outputs = model(images)
            val_loss += criterion(outputs, targets.view(-1, 1).float()).item()

        valid_loss_li.append(val_loss)
        if val_loss < least_loss:
            lease_loss = val_loss
            best_model = model

    # Print training and validation loss
    print(f'Epoch [{epoch+1}/{num_epochs}], Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}')

```
What are the changes that I can do to have good training??

**Comment by glenn-jocher** [comment]
Hello there! 👋 Glad to hear the architecture is trainable now. Persistently high loss could be due to several factors. Here are a few quick suggestions you might explore:

1. **Learning Rate Adjustment**: Sometimes, the initial learning rate might be too high. Try reducing it gradually.

2. **Data Normalization**: Ensure your input data is normalized properly. It looks good in your code, but double-checking the dataset specifics can't hurt.

3. **Complexity of the Model vs. Data**: The model might be too complex for the data or vice versa. Evaluate if you're overfitting or underfitting.

4. **Loss Function**: For regression tasks, MSELoss is a common choice, but you might also explore other options like L1Loss depending on your data characteristics.

5. **Regularization**: Adding some form of regularization (like Dropout in your ViT model) might help if the model is overfitting.

6. **Batch Size**: Experiment with the batch size to see if it impacts training dynamics.

7. **Data Augmentation**: Your current transformations look good, but consider experimenting with the intensity of augmentations or trying different ones to see if it affects the learning positively.

Experimentation is key here! Adjust one parameter at a time to isolate its impact. Happy experimenting! 😊

**Comment by Tensing2009** [comment]
@glenn-jocher I often struggle applying these augmentations like Gaussian blur or just adding each mask to the frame as overlay when the application is real time.
Any tips on how to handle this?
Especially when each class should be a different color segment.
Thanks for the help.

**Comment by glenn-jocher** [comment]
Hi @StefanNa3Shape — this thread is closed/stale; for visibility please open a new issue with a short repro video. For real-time per-class mask overlays, use the built-in renderer (fast and color-coded by class), and only blur within masks when needed:

```python
import cv2, numpy as np
from ultralytics import YOLO
from ultralytics.utils.plotting import colors

model = YOLO("yolo11n-seg.pt")

for r in model.predict(source=0, stream=True, imgsz=640, half=True, conf=0.25, verbose=False):
    im = r.orig_img
    out = r.plot(labels=False, boxes=False)  # per-class colored masks

    # Optional: blur only inside masks (keep small kernels for speed)
    if r.masks is not None:
        im_blur = cv2.GaussianBlur(im, (7, 7), 0)
        for m, cls in zip(r.masks.data, r.boxes.cls.int()):
            mask = (m.cpu().numpy() * 255).astype(np.uint8)
            # color overlay example
            col = colors(int(cls), bgr=True)
            overlay = np.full_like(im, col, dtype=np.uint8)
            mixed = cv2.addWeighted(im, 0.3, overlay, 0.7, 0)
            out = np.where(mask[..., None] > 128, mixed, out)
            # or blur instead of color:
            # out = np.where(mask[..., None] > 128, im_blur, out)

    cv2.imshow("seg", out)
    if cv2.waitKey(1) == 27:
        break
cv2.destroyAllWindows()
```

If you also need fast region-only blurring, the approach used in our ObjectBlurrer solution is a good reference: see the [Object blurring guide](https://docs.ultralytics.com/guides/object-blurring/) and the [ObjectBlurrer reference](https://docs.ultralytics.com/reference/solutions/object_blurrer/).

**Comment by Leon-Cheung-CQ** [comment]
> [@glenn-jocher](https://github.com/glenn-jocher) I think you misunderstood the question, I want to smooth out the YOLO segments generated by the model to have smooth edges, can it be done??

this can be solved by apply "Douglas-Peucker", provide by opencv(approxPolyDP), to reduce the points of segmentation.

**Comment by glenn-jocher** [comment]
Thanks, that’s a reasonable approach for post-processing polygon contours: applying `cv2.approxPolyDP()` to `r.masks.xy` can reduce jagged vertices and give cleaner segment outlines, although it simplifies the extracted contour rather than improving the underlying mask itself; for anyone continuing this, please open a new issue since this thread is stale/closed, and see the [Masks results reference](https://docs.ultralytics.com/reference/engine/results/#ultralytics.engine.results.Masks.xy) and [isolating segmentation objects guide](https://docs.ultralytics.com/guides/isolating-segmentation-objects/) for how to access `masks.xy`.
