### ISSUE TITLE
Augementations are applied anyway in "classify, train mode" even when it's disabled

### ISSUE THREAD

**Issue by Alyetama** [ultralytics/ultralytics#8987]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Hello, It seems like the model is using augmentations even when I set `augment: false` in  'ultralytics/cfg/default.yaml'.
![train_batch0_1_c0da9b9c9fbf05196de1](https://github.com/ultralytics/ultralytics/assets/56323389/59ab36ff-e7bb-4c9f-a782-fc7bb6f33216)

### Environment

```
Ultralytics YOLOv8.1.28 🚀 Python-3.10.13 torch-2.2.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4090, 24209MiB)
Setup complete ✅ (32 CPUs, 62.5 GB RAM, 120.3/960.2 GB disk)

OS                  Linux-6.5.0-25-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.13
Install             pip
RAM                 62.51 GB
CPU                 Intel Core(TM) i9-14900KF
CUDA                12.1

matplotlib          ✅ 3.8.3>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.2.1>=1.8.0
torchvision         ✅ 0.17.1>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.1>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
```

### Minimal Reproducible Example

```bash
yolo task=classify mode=train model=yolov8n-cls.pt data=dataset_by_class epochs=500 imgsz=640 patience=100 plots=True cache=memory
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Alyetama hey there! 👋 Thanks for reaching out with your observation. It's great that you've provided a detailed description alongside your development environment info. 

Regarding the issue of augmentations being applied despite setting `augment: false`, this sounds like something we need to look into more closely. A quick workaround would be to make sure you're directly setting the augmentation behavior in your command line call, as configurations via the CLI will take precedence over those set in your YAML files. Here's an example to try:

```bash
yolo task=classify mode=train model=yolov8n-cls.pt data=dataset_by_class epochs=500 imgsz=640 patience=100 plots=True cache=memory augment=False
```

If the problem persists, it could be beneficial to ensure you're on the latest version of Ultralytics YOLOv8, as updates may address such issues. Meanwhile, our team will dive deeper into this matter to understand what might be causing the augmentation settings not to be honored as expected.

Your involvement in spotting this helps improve YOLOv8 for everyone! Stay tuned for updates and, if possible, keep an eye on our GitHub issues section for a fix or workaround in the coming days. 🚀

**Comment by Laughing-q** [comment]
Hi @Alyetama ! Actually the `augment` arg we have is for predict mode and val mode, not for train mode, so augmentation can't be closed by setting it to False. Please checkout all the training arguments in our docs page: https://docs.ultralytics.com/modes/train/#train-settings

The augmentations would be applied be default during training, and can't be closed unless you manually modified the [code](https://github.com/ultralytics/ultralytics/blob/f9edac6a089db168fb17eaed6d3048a84cf92a50/ultralytics/data/build.py#L91) or set all the augmentation-related arguments to `0.0`, and here are the augmentation-related argument list: https://docs.ultralytics.com/modes/train/#augmentation-settings-and-hyperparameters

**Comment by Alyetama** [comment]
@Laughing-q Thank you for clarifying! It appears there's a discrepancy between how this works and the official [documentation on the Train mode](https://docs.ultralytics.com/modes/train/), which may lead users to believe that augmentations can be disabled by setting `augment` to False. I tried a workaround by setting all augmentation values to zero, effectively removing augmentations, and this resolved the issue for me.


@mirkopiani98 Thank you for starting a PR!

**Comment by Alyetama** [comment]
I started having this issue again even after turning all augmentation options to zero. I fixed it after changing `augment=mode == "train"` to `augment=self.args.augment` as referenced [here](https://github.com/ultralytics/ultralytics/pull/9026#issuecomment-2003893435).

**Comment by mirkopiani98** [comment]
@Alyetama you are welcome!
