### ISSUE TITLE
Saving the best model

### ISSUE THREAD

**Issue by mehran66** [ultralytics/ultralytics#899]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I did notice that the best.pt has saved into disk at the same time of saving the last.pt, though the best model happens around epoch 100 out of 300 epoch. I was taking a look at the source code for any potential  and found this line of code `if not self.best_fitness or self.best_fitness < fitness:` that does not make sense!!!

https://github.com/ultralytics/ultralytics/blob/254adfa652eb9abc41a8b7bdef7d6420c81a6217/ultralytics/yolo/engine/trainer.py#:~:text=if%20not%20self.best_fitness%20or%20self.best_fitness%20%3C%20fitness%3A

### Environment

N/A

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by mehran66** [comment]
reading the code more carefully, it makes sense now.

**Comment by pderrenger** [comment]
@mehran66 i'm glad to hear that you were able to resolve the confusion! If you have any further questions or need assistance with anything else related to YOLOv8, feel free to ask. We're here to help! 😊
