### ISSUE TITLE
Not able resume the training. 

### ISSUE THREAD

**Issue by senhorinfinito** [ultralytics/ultralytics#8993]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I'm using version 8.1.0 of the code for training the YOLOv8n model. I trained the model until the 25th epoch. However, due to an unavoidable system issue, it went down. When I tried to resume from where it last left off, it started from scratch. Upon debugging the code, I found that there is no proper provision for resuming training from where it left off.  
here are following points need to implemented, 
1. if project or name of experiment present consider only directory  for search latest_run. 
2. if both are not provided can take entire current directory for search.  

### Environment

:/usr/src/ultralytics# yolo checks 
Ultralytics YOLOv8.1.0 🚀 Python-3.10.13 torch-2.2.0 CUDA:0 (NVIDIA A100-SXM4-40GB, 40338MiB)
Setup complete ✅ (24 CPUs, 167.0 GB RAM, 330.3/387.5 GB disk)

OS                  Linux-6.5.0-1015-gcp-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.13
Install             git
RAM                 167.03 GB
CPU                 Intel Xeon 2.20GHz
CUDA                12.1

matplotlib          ✅ 3.8.3>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.0.1>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.2.0>=1.8.0
torchvision         ✅ 0.17.0>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.1>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Minimal Reproducible Example

```
from ultralytics import YOLO
# Load a model
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)

# Train the model
results = model.train( name="yolov8n-e50", project="yolov8-verifed-data", resume=True)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@senhorinfinito hello! Thanks for reaching out and providing detailed information on your issue with resuming training in YOLOv8 version 8.1.0. 😊

It looks like you've taken the right steps to resume training but encountered unexpected behavior. To address the issue of resuming training, we recently made some improvements.

For resuming training from the last checkpoint, your approach seems correct. You just need to make sure that the `last.pt` file from your previous training exists in the `project/name` directory. The `resume` flag is designed to look for this file automatically and should pick up training from the last saved epoch.

Make sure the `last.pt` exists in `yolov8-verifed-data/yolov8n-e50` directory. If it's not there or if there was any path issue during the previous training's abrupt stop, YOLOv8 might start over.

If the issue persists, please ensure all paths are correctly specified and accessible, and you might also want to check the write permissions in the specified directory.

```python
results = model.train(name="yolov8n-e50", project="yolov8-verifed-data", resume=True)
```

If you're confident that everything is set up correctly, but it still doesn't resume, it would be a great help if you could open a PR with your proposed fixes or any further details on the issue. 🚀

Your contribution is much appreciated, and we're looking forward to your PR to make YOLOv8 even better for everyone! Let me know if there's anything else I can help with.

**Comment by Laughing-q** [comment]
@senhorinfinito Hi! for resuming a interrupted training, you could load the model from your last checkpoint then start training with `resume=True`:
```python
from ultralytics import YOLO

# Load a model
model = YOLO('path/to/last.pt')  # load a partially trained model

# Resume training
results = model.train(resume=True)
```
More info about resume please checkout our docs page: https://docs.ultralytics.com/modes/train/#resuming-interrupted-trainings

**Comment by senhorinfinito** [comment]
Okay 
Thanks
