### ISSUE TITLE
Saving the best model

### ISSUE THREAD

**Issue by mehran66** [ultralytics/ultralytics#900]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I did notice that the best.pt has saved into disk at the same time of saving the last.pt, though the best model happens around epoch 100 out of 300 epoch. I was taking a look at the source code for any potential issue and found this line of code `if not self.best_fitness or self.best_fitness < fitness` here that means my best_fitness is None:

https://github.com/ultralytics/ultralytics/blob/254adfa652eb9abc41a8b7bdef7d6420c81a6217/ultralytics/yolo/engine/trainer.py#:~:text=if%20not%20self.best_fitness%20or%20self.best_fitness%20%3C%20fitness%3A

loading the model and checking the checkpoint, I found it correct:
{'epoch': -1,
 'best_fitness': None, 
...
 
Here is the result csv and everything seems normal:
[results.csv](https://github.com/ultralytics/ultralytics/files/10702790/results.csv)

what is the reason of having the best_fitness as None? everything else looks normal with this model and training.

### Environment

Ultralytics YOLOv8.0.6 🚀 Python-3.10.6 torch-1.13.0 CUDA:0 (NVIDIA A10G, 22732MiB)
                                                     CUDA:1 (NVIDIA A10G, 22732MiB)
                                                     CUDA:2 (NVIDIA A10G, 22732MiB)
                                                     CUDA:3 (NVIDIA A10G, 22732MiB)
                                                     CUDA:4 (NVIDIA A10G, 22732MiB)
                                                     CUDA:5 (NVIDIA A10G, 22732MiB)
                                                     CUDA:6 (NVIDIA A10G, 22732MiB)
                                                     CUDA:7 (NVIDIA A10G, 22732MiB)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@mehran66 don't worry, I think it's because `strip_optimizer` in the final_eval. :) It'll remove these extra info as the training is finished.
[https://github.com/ultralytics/ultralytics/blob/254adfa652eb9abc41a8b7bdef7d6420c81a6217/ultralytics/yolo/engine/trainer.py#L511](https://github.com/ultralytics/ultralytics/blob/254adfa652eb9abc41a8b7bdef7d6420c81a6217/ultralytics/yolo/engine/trainer.py#L511)

**Comment by mehran66** [comment]
Thanks @Laughing-q
yep after running some predictions, I can confirm that the last and best pth files are having different predictions.
