### ISSUE TITLE
How to export the obb rotating box of yolov8 so that it can be used by Android ncnn, and what files need to be modified?

### ISSUE THREAD

**Issue by joken5** [ultralytics/ultralytics#9017]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to export the obb rotating box of yolo so that it can be used by Android ncnn, and what files need to be modified?

**Comment by joken5** [comment]
I exported the onnx file using the following command：
     yolo obb  mode=export model=runs\obb\train13\weights\best.pt format=onnx imgsz=160
Then convert the onnx file to an ncnn file using the URL below：
     https://convertmodel.com/
Then put them into the Android project to use, Tencent's ncnn code recognizes many targets, but it should be only one target

**Comment by joken5** [comment]
[Uploading file.zip…]()
There are onnx and ncnn files in this zip package. What's the problem?

**Comment by joken5** [comment]
There are onnx and ncnn files in this zip package. What's the problem?
[Uploading file.zip…]()

**Comment by glenn-jocher** [comment]
@joken5 it looks like the link to the zip package didn't fully upload before you submitted your comment. Could you please try re-uploading the file so we can take a closer look at the onnx and ncnn files you mentioned? This will help us better understand the issue and provide more specific assistance. 🛠️

**Comment by joken5** [comment]
[file1.zip](https://github.com/ultralytics/ultralytics/files/14643971/file1.zip)

**Comment by joken5** [comment]
This is the reuploaded zip.

**Comment by glenn-jocher** [comment]
Thanks for re-uploading the zip, @joken5! I'll dive into your files to better understand what might be happening. It sounds like your OBB (Oriented Bounding Box) model's conversion from ONNX to NCNN might be experiencing some discrepancies in detection when deployed on Android. 

Firstly, ensure that the post-processing steps (such as NMS for OBB) are correctly implemented in your application code. Since ONNX to NCNN conversion could potentially alter or omit some layers, you might need to manually implement certain functionalities that were inherently handled within the PyTorch model. 

Additionally, verify the input preprocessing (like normalization) and output processing (decoding of the bounding boxes) steps in your Android code match those expected by the model.

If you're seeing multiple detections for what should be a single target, it's crucial to inspect the aforementioned post-processing steps.

For more tailored support, feel free to share snippets of your Android application code where you handle the model's output. This would help in pinpointing the adjustment needed to correct the multiple detections issue. 🛠️

**Comment by glenn-jocher** [comment]
Thanks for sharing your NCNN processing code, @joken5! I've looked at your `yolo.cpp` file from the zip package 📦 and the way you're using `detectPicture`. Given that you're encountering multiple detections for a single target, it sounds like it might be related to the post-processing stages in your code.

A common issue in object detection models when deployed in real-world applications like on Android with NCNN is ensuring that Non-Maximum Suppression (NMS) or a similar mechanism is correctly applied to filter out overlapping detections. Ensure that after detections are retrieved from the NCNN output, you apply NMS based on the confidence scores and the intersection-over-union (IOU) of the bounding boxes. Here's a pseudocode snippet indicating where this might fit in:

```cpp
std::vector<Obj> objects; // Assuming this is your structure for holding detected objects
g_yolo->detectPicture(1, env, bitmap, width, height, objects);

// Apply NMS or other filtering mechanisms
filterDetections(objects);
```

The implementation details of `filterDetections` will depend on your specific requirements and OBB handling logic.

If your model is specifically trained to produce oriented bounding boxes (OBB), make sure the conversion process from the model output to the final detection coordinates respects the orientation of each bounding box, as this might not be straightforward compared to axis-aligned boxes.

Without the exact implementation details of `detectPicture`, it's challenging to pinpoint the issue, but starting from ensuring the post-processing part might help solve the multiple detection issue. If the problem persists, it may be helpful to further inspect how the model's output is parsed and converted into detections within your `detectPicture` method. Hope this helps, and feel free to reach out if you have more questions or details to share! 🛠️

**Comment by zhaodongyang2016** [comment]
I export ncnn models using the method provided in the project. There is a segmentation fault during inference. When the new version is released, will the exported models be tested? As far as I know, not all versions can successfully export trained models. What is the version number when you tested, Should I use the initially adapted version? @glenn-jocher

**Comment by glenn-jocher** [comment]
@zhaodongyang2016 hi there! 😊

We're sorry to hear you're encountering a segmentation fault during inference with NCNN models. We aim to ensure compatibility and stability with each release. The process includes testing model export functionalities, but sometimes edge cases can slip through.

For the most stable experience, it's generally a good idea to use the version explicitly mentioned in our documentation or the one initially adapted for NCNN export compatibility. However, we're continually improving, so the latest versions often include fixes and enhancements.

Could you try using the initially recommended version and see if that resolves your issue? If not, please feel free to open an issue with detailed error logs, and we'll take a closer look!

Here's a quick check you can perform to ensure compatibility:
```bash
yolo export model=your_model.pt format=ncnn
```

Replace `your_model.pt` with your model file. If you're still facing issues, sharing error logs or more details would greatly help us troubleshoot. 🛠️

Thanks for reaching out, and we appreciate your patience!
