### ISSUE TITLE
Unconsistent prediction speed

### ISSUE THREAD

**Issue by Androix777** [ultralytics/ultralytics#9025]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

For some reason my prediction speed varies a lot. Processing the same image can take from 6 to 200 ms.

For example, with code like this:
```python
from ultralytics import YOLO
import time

model = YOLO('models/yolov8n.pt')
time.sleep(10)
print('sleep 1')
model('1.png')
model('1.png')
model('1.png')
time.sleep(10)
print('sleep 2')
model('1.png')
model('1.png')
model('1.png')
time.sleep(10)
print('sleep 3')
model('1.png')
model('1.png')
time.sleep(10)
print('sleep 4')
model('1.png')
```

I'm getting results:
```
sleep 1

image 1/1 1.png: 640x640 1 clock, 7.0ms
Speed: 2.0ms preprocess, 7.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 1.png: 640x640 1 clock, 6.0ms
Speed: 3.0ms preprocess, 6.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 1.png: 640x640 1 clock, 7.0ms
Speed: 2.0ms preprocess, 7.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)
sleep 2

image 1/1 1.png: 640x640 1 clock, 128.0ms
Speed: 13.0ms preprocess, 128.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 1.png: 640x640 1 clock, 76.0ms
Speed: 3.8ms preprocess, 76.0ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 1.png: 640x640 1 clock, 47.0ms
Speed: 9.0ms preprocess, 47.0ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)
sleep 3

image 1/1 1.png: 640x640 1 clock, 99.6ms
Speed: 68.0ms preprocess, 99.6ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 1.png: 640x640 1 clock, 33.0ms
Speed: 8.0ms preprocess, 33.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)
sleep 4

image 1/1 1.png: 640x640 1 clock, 110.0ms
Speed: 4.0ms preprocess, 110.0ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)
```

As I understood the speed depends on how often I send images and how much time passes between sending. I observe a similar problem on my server: images are processed at 8ms, but at some point the processing time starts to increase up to 150-200, but then again returning to 8ms. When processing video there is no problem and each frame is processed at 6-7ms. I have reproduced this problem on 2 different machines.

### Environment

Ultralytics YOLOv8.1.16 🚀 Python-3.10.13 torch-2.2.1 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)
Setup complete ✅ (12 CPUs, 31.8 GB RAM, 830.9/930.9 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.10.13
Install             pip
RAM                 31.79 GB
CPU                 AMD Ryzen 5 5600G with Radeon Graphics
CUDA                12.1

matplotlib          ✅ 3.8.3>=3.3.0
opencv-python       ✅ 4.9.0>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.2.1>=1.8.0
torchvision         ✅ 0.17.1>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ❌ (not installed)>=0.1.1
pandas              ✅ 2.2.1>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Androix777** [comment]
Problem solved. It was all about power management mode.
![aid_3130_01](https://github.com/ultralytics/ultralytics/assets/19364479/066f0904-ba16-4c94-8c64-33aafb7d458a)

**Comment by glenn-jocher** [comment]
@Androix777 great to hear the problem was resolved, and thank you for sharing the solution! Indeed, the power management mode can significantly impact inference speeds by throttling GPU performance to save energy. Switching to a high-performance mode should help maintain consistent and optimal processing speeds. If anyone else encounters similar issues, checking the power management settings as demonstrated could be a helpful first step. Happy coding! 😊🚀
