### ISSUE TITLE
xl note:how to place data? 

### ISSUE THREAD

**Issue by keepgoing365** [ultralytics/ultralytics#9027]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

1.how to place data? 
2.how to prepare data on yolo8-seg?

**Comment by keepgoing365** [comment]
1.like this:
base_dir
  --train
    --images
      img1
      imgn
    --labels
      label1
      labeln
  --val
  .....

2.like this
norm : 
    if idx % 2 == 0:
        norm_num = num / img_w
    else:
        norm_num = num / img_h
result:
0 0.681 0.485 0.670 0.487 0.676 0.487   
1 0.504 0.000 0.501 0.004 0.498 0.004 0.493 0.010 0.492 0.0104

**Comment by keepgoing365** [comment]
complete!

**Comment by glenn-jocher** [comment]
@keepgoing365 absolutely! For YOLOv8, including YOLOv8-seg, your dataset structure looks spot-on 🎯. Here's a quick recap for clarity:

```
base_dir/
  └───train/
  │   ├───images/
  │   │    ├── img1.jpg
  │   │    └── imgn.jpg
  │   └───labels/
  │        ├── label1.txt
  │        └── labeln.txt
  └───val/ (similar structure to train/)
```

For YOLOv8-seg segmentation data, your label normalization approach is correct. Important to normalize the points relative to the width and height of the image. Your result format aligns with what's expected:

```plaintext
<class_id> <x1> <y1> <x2> <y2> <x3> <y3> ...
```
Points (`<x>`, `<y>`) should be normalized (`0` to `1`) relative to img width or height. This format helps YOLOv8-seg effectively learn from your data. Keep up the good prep work! 👍
