### ISSUE TITLE
How does Yolov8 handle images with no bounding boxes?

### ISSUE THREAD

**Issue by AzizInstadeep** [ultralytics/ultralytics#9029]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I was wondering how does Yolov8 handle images with no bounding boxes. Does it ignore them? or does it penalize the model for predicting bounding boxes in images with no targets?

**Comment by glenn-jocher** [comment]
@AzizInstadeep hello! Great question! 😊 YOLOv8 handles images with no bounding boxes by considering them valuable negative examples. It doesn't ignore these images but instead uses them to train the model to correctly learn when not to predict any bounding boxes. It doesn't penalize the model for these images per se; rather, it teaches the model that not every image contains objects of interest. This helps in improving the model's accuracy and reducing false positives.

In your training dataset, you can include images without objects, just ensure their label files are present but empty (0 KB), signifying no bounding boxes.

Happy training with YOLOv8! ✨

**Comment by AzizInstadeep** [comment]
@glenn-jocher Thank you for your prompt and great answer! I am curious now how does it exactly "teach the model that not every image contains object of interests". Can you please give me more details of how YOLOv8 implements that?

**Comment by glenn-jocher** [comment]
@AzizInstadeep Hello! YOLOv8 handles images with no objects by using them as negative samples during training. When the model predicts bounding boxes where there are none, it incurs a loss specifically designed to penalize such false positives. This loss component helps the model learn to distinguish between scenes with and without objects, effectively teaching it when not to predict. This approach enhances the model's ability to generalize across various scenarios. Happy coding! 😊

**Comment by bighan123** [comment]
@glenn-jocher Hi,I also encountered a similar problem, in my own dataset there are a large number of images that do not contain the target object, so I wondered how YOLOv8 would treat them, when I read the relevant code I found that the calculations regarding bbox loss and dfl loss would only be performed when fg_mask.sum() > 0 (as shown in the figure below), does this mean that YOLOv8  handles the negative samples will only calculate the classification loss?
![image](https://github.com/user-attachments/assets/d1999a78-d202-46df-85c6-d040af553f32)

**Comment by glenn-jocher** [comment]
Hello! Yes, you're correct. When there are no foreground objects (i.e., `fg_mask.sum() == 0`), YOLOv8 focuses on calculating the classification loss for those negative samples. This helps the model learn to avoid false positives. If you have further questions, feel free to ask!
