### ISSUE TITLE
Hello, may I ask how can YOLO v8, when performing classification tasks, output confidence rate of each tag independently, so that the sum of confidence rate of each tag is not restricted by 1?

### ISSUE THREAD

**Issue by HYSzuibai** [ultralytics/ultralytics#9032]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, may I ask how can YOLO v8, when performing classification tasks, output confidence rate of each tag independently, so that the sum of confidence rate of each tag is not restricted by 1? For example, three labels: A,B,C. Output confidence
A: 0.88
B: 0.78
C: 0.80
If I'm not easy to understand, just ask me. Thank you very much

**Comment by MosbehBarhoumi** [comment]
@HYSzuibai This may help you! #4149
