### ISSUE TITLE
Image recognition using camera basler and Yolo

### ISSUE THREAD

**Issue by ManoelVictor9** [ultralytics/ultralytics#9035]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am implementing a hardware trigger capture system with 4 images that are combined using basler camera, and I am aiming to develop image recognition using YOLOv8 for each of the 4 captured images, however, when I run the program, it prints that recognition has occurred of the images, but the bounding boxes do not appear in the images sampled in real time.
Could anyone help me with this error?

### Additional

Code used:
from pypylon import pylon
import cv2
import numpy as np
from ultralytics import YOLO

camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())

model = YOLO('best2.pt') 

# changing this to True changes the Trigger to Line1 instead of the SpaceKey
EXTERNAL_TRIGGER = True

try:
    # setup camera aoi
    camera.Open()
    camera.Width.Value = camera.Width.Max
    camera.Height.Value = camera.Height.Max

    # set camera to frame trigger mode on Line1
    camera.TriggerSelector.Value = "FrameStart"
    if EXTERNAL_TRIGGER:
        camera.TriggerSource.Value = "Line1"
    else:
        camera.TriggerSource.Value = "Software"
    camera.TriggerMode.Value = "On"

except Exception as e:
    print(f"Error when configuring the camera: {e}")

# constant values
num_images = 4
screen_width, screen_height = 1080  , 720

# runtime values
resized_images = []
current_image_index = 0
combined_image = np.zeros((screen_height, screen_width, 3), dtype=np.uint8)

# configure image converter
converter = pylon.ImageFormatConverter()
converter.OutputPixelFormat = pylon.PixelType_BGR8packed
converter.OutputBitAlignment = pylon.OutputBitAlignment_MsbAligned

camera.StartGrabbing(pylon.GrabStrategy_LatestImageOnly)

while camera.IsGrabbing():
    while current_image_index < num_images:

        cv2.imshow('Combined Images', combined_image)
        key = cv2.waitKey(1)
        if key == 27:  # Esc key to exit
            camera.StopGrabbing()
            break
        elif not EXTERNAL_TRIGGER and key == ord(" "):
            camera.ExecuteSoftwareTrigger()

        # you cant check your key entry and wait for the next image in one thread at the same time,
        # so you can use this wait-object to check for new images and skip the 5 sec Timeout during RecieveResult
        if not camera.GetGrabResultWaitObject().Wait(10):
            continue

        try:
            # use the context handler, so you dont have to call "grabResult.Release" at the end
            with camera.RetrieveResult(5000, pylon.TimeoutHandling_ThrowException) as grabResult:
                assert grabResult.GrabSucceeded()
                # Accessing image data
                image = converter.Convert(grabResult)
                img = image.GetArray()
        except pylon.TimeoutException as timeout_error:
            raise AssertionError("Timeout error, this should not happen, "
                                 "because we waited for the image in the wait object before!") from timeout_error

        except AssertionError as assertion_error:
            raise AssertionError("Unsuccessful grab, this should not happen at all!") from assertion_error

         # Detect objects using YOLO
        detections = model.predict(img)

        # Draw bounding boxes on resized image
        try:
            for detection in detections:
                x1, y1, x2, y2, conf, cls = detection
                x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
                cv2.rectangle(resized_images[current_image_index], (x1, y1), (x2, y2), (0, 255, 0), 2)
                cv2.putText(resized_images[current_image_index], cls, (x1, y1), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)
        except ValueError:
            pass  

        # every image is grabbed on purpose, just add every incoming image
        if len(resized_images) < num_images:
            resized_images.append(img.copy())
        else:
            resized_images[current_image_index] = img.copy()
            current_image_index = (current_image_index + 1) % num_images

        for i in range(len(resized_images)):
            h, w, _ = resized_images[i].shape
            h_ratio = screen_height // 2
            w_ratio = screen_width // 2
            row = i // 2
            col = i % 2

            resized_images[i] = cv2.resize(resized_images[i], (w_ratio, h_ratio))
            combined_image[row * h_ratio: (row + 1) * h_ratio, col * w_ratio: (col + 1) * w_ratio, :] = resized_images[
                i]

cv2.waitKey(0)
cv2.destroyAllWindows()
camera.Close()

**Comment by glenn-jocher** [comment]
@ManoelVictor9 hello! It looks like the issue might stem from drawing the bounding boxes on the `resized_images[current_image_index]`, which is done after potentially resizing and re-assigning `img.copy()` to `resized_images[current_image_index]`. Essentially, you might be drawing on the image before resizing and combining, but displaying after these operations. 

Try adjusting your bounding box drawing code to apply directly on `img`, like this:

```python
# Detect and draw bounding boxes directly on the grabbed images
detections = model.predict(img)
try:
    for detection in detections[0].boxes.xyxy[0]:
        x1, y1, x2, y2, conf, cls_id = detection
        x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
        cls = detections.names[int(cls_id)]
        cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.putText(img, cls, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 255, 255), 2)
except ValueError:
    pass
```

Please ensure that bounding box drawing operations are applied to `img` after performing predictions but before resizing and assigning images into `resized_images`. This change should make your detections visible. Let me know if this helps or if you encounter any other issues! 🚀

**Comment by ManoelVictor9** [comment]
> @ManoelVictor9 hello! It looks like the issue might stem from drawing the bounding boxes on the `resized_images[current_image_index]`, which is done after potentially resizing and re-assigning `img.copy()` to `resized_images[current_image_index]`. Essentially, you might be drawing on the image before resizing and combining, but displaying after these operations.
> 
> Try adjusting your bounding box drawing code to apply directly on `img`, like this:
> 
> ```python
> # Detect and draw bounding boxes directly on the grabbed images
> detections = model.predict(img)
> try:
>     for detection in detections[0].boxes.xyxy[0]:
>         x1, y1, x2, y2, conf, cls_id = detection
>         x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
>         cls = detections.names[int(cls_id)]
>         cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
>         cv2.putText(img, cls, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 255, 255), 2)
> except ValueError:
>     pass
> ```
> 
> Please ensure that bounding box drawing operations are applied to `img` after performing predictions but before resizing and assigning images into `resized_images`. This change should make your detections visible. Let me know if this helps or if you encounter any other issues! 🚀



> @ManoelVictor9 hello! It looks like the issue might stem from drawing the bounding boxes on the `resized_images[current_image_index]`, which is done after potentially resizing and re-assigning `img.copy()` to `resized_images[current_image_index]`. Essentially, you might be drawing on the image before resizing and combining, but displaying after these operations.
> 
> Try adjusting your bounding box drawing code to apply directly on `img`, like this:
> 
> ```python
> # Detect and draw bounding boxes directly on the grabbed images
> detections = model.predict(img)
> try:
>     for detection in detections[0].boxes.xyxy[0]:
>         x1, y1, x2, y2, conf, cls_id = detection
>         x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
>         cls = detections.names[int(cls_id)]
>         cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
>         cv2.putText(img, cls, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 255, 255), 2)
> except ValueError:
>     pass
> ```
> 
> Please ensure that bounding box drawing operations are applied to `img` after performing predictions but before resizing and assigning images into `resized_images`. This change should make your detections visible. Let me know if this helps or if you encounter any other issues! 🚀

Hi Glenn, thanks for your help!!
When i tried your change sugestion, i got some errors like this:

0: 416x640 (no detections), 258.9ms
Speed: 4.0ms preprocess, 258.9ms inference, 1.0ms postprocess per image at shape (1, 3, 416, 640)
Traceback (most recent call last):
  File "c:/...", line 88, in <module>
    for detection in detections[0].boxes.xyxy[0]:
IndexError: index 0 is out of bounds for dimension 0 with size 0

and sometimes like this:

0: 416x640 1 -, 287.3ms
Speed: 4.0ms preprocess, 287.3ms inference, 1.7ms postprocess per image at shape (1, 3, 416, 640)
Traceback (most recent call last):
  File "c:/...", line 89, in <module>
    x1, y1, x2, y2, conf, cls_id = detection
  File "C:\...", line 990, in __iter__
    raise TypeError("iteration over a 0-d tensor")
TypeError: iteration over a 0-d tensor

Could this case be an error when there is no detection?

**Comment by glenn-jocher** [comment]
Hey @ManoelVictor9! Awesome that you tried out the suggestion. 👍 From the errors you're encountering, it indeed seems like the issue crops up when there are no detections made by the model. In such cases, iterating over `detections[0].boxes.xyxy[0]` might lead to an `IndexError` or a `TypeError` because there's nothing to iterate over.

To handle cases with no detections gracefully, you can check if there are any detections before iterating, like so:

```python
# Detect and draw bounding boxes directly on the grabbed images
detections = model.predict(img)

if len(detections[0].boxes) > 0:  # Check if any boxes were detected
    for detection in detections[0].boxes.xyxy[0]:
        x1, y1, x2, y2, conf, cls_id = detection
        x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
        cls = detections[0].names[int(cls_id)]
        cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.putText(img, cls, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 255, 255), 2)
```

This will only attempt to draw bounding boxes if there are actual detections, and thus avoid the errors you observed. Give this a go and let us know if it clears up the issues! 🌟

**Comment by ManoelVictor9** [comment]
Hey @glenn-jocher , thanks for your time again, I tried your sugestion, and i got the same error:

0: 512x640 3 -s, 441.2ms
Speed: 18.4ms preprocess, 441.2ms inference, 14.6ms postprocess per image at shape (1, 3, 512, 640)
Traceback (most recent call last):
  File "c:..", line 90, in <module>
    x1, y1, x2, y2, conf, cls_id = detection
  File "C:..\Python\Python38\lib\site-packages\torch\_tensor.py", line 990, in __iter__
    raise TypeError("iteration over a 0-d tensor")
TypeError: iteration over a 0-d tensor

After some research, I got some good results with this:

                 detections = model.predict(img)
                
                detections_boxes = detections[0].boxes.xyxy[0]
                if isinstance(detections_boxes, torch.Tensor) and detections_boxes.dim() > 0:
                    detections_boxes = detections_boxes.tolist()  # Convert tensor to list
                    for detection in detections_boxes:
                        if isinstance(detection, list) and len(detection) == 6:
                            x1, y1, x2, y2, conf, cls_id = detection
                            x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
                            cls = detections[0].names[int(cls_id)]
                            cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
                            cv2.putText(img, cls, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 255, 255), 2)
                            
Now I have the image, and in my terminal it showed that YOLO found something. However, the bounding box isn't appearing on the images, any suggestion?

(Sorry for the delay, I can only perform tests at very specific times here)

**Comment by glenn-jocher** [comment]
Hey @ManoelVictor9, no worries about the delay! I'm glad to hear you've been getting some progress 🚀. Based on your update, it looks like you're on the right track with converting tensor to list and ensuring detections are there before iterating. 

If the bounding boxes still aren't appearing, it could be related to how and when you're displaying the image. Ensure you're displaying `img` **after** drawing the bounding boxes, with something like: `cv2.imshow('Detections', img)` followed by `cv2.waitKey(1)` (assuming this is in a loop), or `cv2.waitKey(0)` (for single images) after the bounding box drawing loop. 

Also, double-check that `img` isn't being overwritten or reset anywhere after drawing your bounding boxes but before displaying or saving. If everything seems correct there, you might also want to verify the dimensions and types of `x1, y1, x2, y2` are as expected, and that `img` is the correct image being manipulated. 

Hope this helps you move forward - let's keep troubleshooting 🛠️!

**Comment by ManoelVictor9** [comment]
> Hey @ManoelVictor9, no worries about the delay! I'm glad to hear you've been getting some progress 🚀. Based on your update, it looks like you're on the right track with converting tensor to list and ensuring detections are there before iterating.
> 
> If the bounding boxes still aren't appearing, it could be related to how and when you're displaying the image. Ensure you're displaying `img` **after** drawing the bounding boxes, with something like: `cv2.imshow('Detections', img)` followed by `cv2.waitKey(1)` (assuming this is in a loop), or `cv2.waitKey(0)` (for single images) after the bounding box drawing loop.
> 
> Also, double-check that `img` isn't being overwritten or reset anywhere after drawing your bounding boxes but before displaying or saving. If everything seems correct there, you might also want to verify the dimensions and types of `x1, y1, x2, y2` are as expected, and that `img` is the correct image being manipulated.
> 
> Hope this helps you move forward - let's keep troubleshooting 🛠️!

Hey Gleen, thanks for your help, i finally got it, after hours trying new things hahaha, I used this simple code below and It worked perfectly!!

threshold = 0.7 # Confiability level

                for d in detections:
                    if d.boxes and len(d.boxes) > 0:  # Verify if there's any detections and if it's empty
                        for box in d.boxes:
                            x1, y1, x2, y2 = box.xyxy[0]  # Colect cordenates
                            confiab = float(box.conf)
                            if confiab > threshold:
                                cv2.rectangle(img, (int(x1), int(y1)), (int(x2), int(y2)), (0, 255, 0), 2)
                                print("High Confiability:", confiab )
                            else:
                                print("Low Confiability")
                    else:
                        print("Nothing found")
                        
I remembered a cool quote with all this, "Keep it simple, stupid" hahaha
I can now close this issue.
Thanks for all your help @glenn-jocher, you're the best!!

**Comment by glenn-jocher** [comment]
Hey @ManoelVictor9, that's fantastic news! 🎉 The KISS principle ("Keep It Simple, Stupid") indeed often proves to be the best approach in software development. So glad to hear you've cracked it with a straightforward solution. Your perseverance paid off, and it’s awesome you shared your discovery - it might just be the guiding light for someone else in the community facing a similar challenge.

Remember, YOLOv8 and the community are here for you. Don't hesitate to reach out if you embark on new adventures or need further assistance. Happy coding, and here's to many more eureka moments like this one! 🚀
