### ISSUE TITLE
the map of validation are different

### ISSUE THREAD

**Issue by alicera** [ultralytics/ultralytics#904]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

For the first, it will generate the val.cache
the map is correct (0.5)

but I try to validate it again 
the map is wrong (0.26)

so I delete the val.cache and try it
the map is also 0.5

**Comment by Laughing-q** [comment]
@alicera already made a PR #902 to fix it which could be merged later today. :)
