### ISSUE TITLE
Add text if there is a label

### ISSUE THREAD

**Issue by BaptistPossenier** [ultralytics/ultralytics#9040]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I am working on YOLOv8 for a project, but am currently stuck. The model has been trained and works on new data. But my question is whether it is possible to add text on the new video, if a class is detected, for example a needle?

This is my code I have so far:

`from ultralytics  import YOLO`

`model = YOLO("YOLO_detection_demo_video_step_8/MODELS/demo_video_step_8.pt")`
`path_shorted_demo_step_7_8_9 = ("YOLO_detection_demo_video_step_8/DATASET_step_8_open_wound_needle/videos/temp.mp4")`

`model.predict(path_shorted_demo_step_7_8_9, save=True, save_txt=True, conf=0.50)`

**Comment by glenn-jocher** [comment]
@BaptistPossenier hey,

Great to hear you're making progress with YOLOv8 on your project! 🚀 To add text to your video when a specific class (e.g., a needle) is detected, you might consider modifying the output frames as they're processed. Here's a quick example on how you could implement this using OpenCV:

```python
import cv2
from ultralytics import YOLO

# Load the model
model = YOLO("YOLO_detection_demo_video_step_8/MODELS/demo_video_step_8.pt")

# Predict and get frames with detections
results = model.predict("YOLO_detection_demo_video_step_8/DATASET_step_8_open_wound_needle/videos/temp.mp4", save=False)

# Iterate over results to add text to frames where a needle is detected
for i, result in enumerate(results):
    if 'needle' in result.names[result.boxes.cls]:  # Check if 'needle' class is detected
        frame = result.render()[0]  # Get the rendered frame with detections
        cv2.putText(frame, "Needle Detected", (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2, cv2.LINE_AA)
        cv2.imwrite(f"frame_{i}.jpg", frame)  # Save or further process the frame
```

This example checks if the 'needle' class is detected in each frame and adds "Needle Detected" text to those frames. It uses `result.render()` to get the frame with detections drawn, then adds text with `cv2.putText()` and saves each frame as an image. You might need to adjust frames saving/loading if working directly with video streams.

Hope this helps! Let us know if you have any other questions.

**Comment by Burhan-Q** [comment]
To add on to what Glenn shared, when you enable model.predict(...,`save=True`) it should save a video in the results directory with the annotations drawn for all detections. Check the output directory to see if there is a video saved, then play it, it should have drawn the annotations with the labels for you. You can also read more about the inference arguments on the [documentation site](https://docs.ultralytics.com/modes/predict/#inference-arguments).

**Comment by BaptistPossenier** [comment]
Okay, thanks in advance for the quick response. Needle/open wound detection works and the video is not saved as indicated by the parameter.

But when the code enters the for loop I get this error message:

`Traceback (most recent call last):
File"c:\Users\Bapti\Desktop\BP_Gastric_Bypass\YOLO_detection_demo_video_step_8\inference.py", line 12, in <module>
    if 'needle' in result.names[result.boxes.cls]:  # Check if 'needle' class is detected
KeyError: tensor([0., 1., 1., 1.])`

Any idea how I can solve this?

**Comment by BaptistPossenier** [comment]
@Burhan-Q dit klopt inderdaad, dat heb ik getest en dit werkt perfect. Maar mijn doel is op een specifieke tekst op de video te plaatsen als bijvoorbeeld een 'naald' detecteerd wordt.

**Comment by Burhan-Q** [comment]
@BaptistPossenier the error is because the `results.boxes.cls` is a float tensor. I think you can use 

```py
detect_classes = [result.names.get(c) for c in result.boxes.cls.tolist()]
if 'needle' in detect_classes:
    ...
```

instead

**Comment by BaptistPossenier** [comment]
@Burhan-Q this indeed worked, but I still don't get any text on my video. The frames open with bounding boxes, but the text "Needle Detected" is not displayed.

**Comment by Burhan-Q** [comment]
@BaptistPossenier make sure you are viewing the image you are using `cv2.putText` with, in the example from Glenn it would be `frame`. Aside from this, you will need to read the OpenCV documentation on using `cv2.putText` to ensure the configuration works specifically for your use case.

**Comment by BaptistPossenier** [comment]
@Burhan-Q I will, thanks for the help
