### ISSUE TITLE
 What metrics/precision(B), metrics/recall(B), metrics/precision(M), and metrics/recall(M)?

### ISSUE THREAD

**Issue by Wang-taoshuo** [ultralytics/ultralytics#9043]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would like to ask what metrics/precision(B), metrics/recall(B), metrics/precision(M), and metrics/recall(M) mean (what do B and M stand for)? Also, I would like to know the significance of these four figures.
![image](https://github.com/ultralytics/ultralytics/assets/119144468/244ef924-a205-473b-91cf-c0abced39d8d)
![image](https://github.com/ultralytics/ultralytics/assets/119144468/ebad4e28-e735-4b09-ad69-dc4a4280544a)
![image](https://github.com/ultralytics/ultralytics/assets/119144468/fd1658a5-41ef-4540-aeff-8d27cb2d7894)
![image](https://github.com/ultralytics/ultralytics/assets/119144468/c733dba1-e099-4979-97b7-aece89844b8c)

**Comment by Burhan-Q** [comment]
@Wang-taoshuo there is a [guide on the documentation site](https://docs.ultralytics.com/guides/yolo-performance-metrics/) all about the metrics

**Comment by Wang-taoshuo** [comment]
@Burhan-Q After reading the documents you provided, I still do not know what (B) and (M) mean. Could you please clarify?
THANKS

**Comment by Johan154** [comment]
@Wang-taoshuo the B and M stand for Box and Mask. For instance segmentation, you have metrics for both bounding boxes and masks as an instance segmentation provides both. The metrics should be highly correlated between box and mask, but there can be some minor differences.
