### ISSUE TITLE
Use YOLOv8 tracking with Coral TPU?

### ISSUE THREAD

**Issue by joshglens** [ultralytics/ultralytics#9054]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have been able to successfully export the YoloV8n model to the Google Coral TPU following the other discussions in this repo. However, I'm not able to find any information about integrating an exported model with the tracking options (such as bytetrack). Does anyone have any information or a tutorial on how to do this?

It looks like model.track(frame, persist=True) works only on models created to yolo. Is there a way to use a model running on TPU as a YOLO model, or otherwise interact with the tracking system without making it an Ultralytics Yolo import?

**Comment by glenn-jocher** [comment]
@joshglens hello! Great to hear about your success in exporting the YOLOv8n model to Google Coral TPU. 🚀 For integrating tracking with models running on TPU, the tracking system provided (`model.track(frame, persist=True)`) is designed to work seamlessly within the YOLO framework and expects models loaded and managed by the Ultralytics YOLO API.

For models running on TPUs outside of the direct Ultralytics YOLO pipeline, you'd typically handle the tracking logic separately. While we don't have a built-in method for integrating TPU models directly with our tracking methods, one possible approach is to:

1. **Run inference with your TPU model** to detect objects and retrieve their bounding boxes.
2. **Pass the bounding boxes to a custom tracking algorithm** or adapt a tracking solution such as ByteTrack to accept your input format.

This would involve writing or adapting a tracking layer that can interface with the outputs your TPU-inferred model provides. While this requires some manual setup, it's a flexible way to integrate sophisticated tracking into your TPU-based deployment.

Here's a very basic outline of what that process might look like in code:
```python
def custom_track(results, tracker):
    # results: Bounding boxes from your TPU model
    # tracker: An instance of your tracking algorithm, could be ByteTrack or similar
    
    # Preprocess results for tracker if necessary
    processed_results = preprocess_for_tracker(results)

    # Update the tracker with the new frame's results
    tracker.update(processed_results)

    # Use tracker's output as needed
    tracked_objects = tracker.get_tracked_objects()
    return tracked_objects
```

Remember, integrating custom logic requires a solid understanding of both the tracking algorithm you choose and the data your model outputs. 

Wishing you the best with your project! If further discussions or detailed implementations arise, we would be delighted to see contributions or more specific queries in our repo discussions. Happy coding! ☺️
