### ISSUE TITLE
Prediction on gpu

### ISSUE THREAD

**Issue by binn77** [ultralytics/ultralytics#906]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, how to perform processing on the gpu?
This code loads the CPU heavily.

`from ultralytics import YOLO

model = YOLO("C:/temp/1.pt")

for number in range(5000):
    results = model("C:/temp/car/000C9C84D5A1DDC22A772385D126518B.jpg")
    results = results[0].probs
    print(results)`
![Снимок](https://user-images.githubusercontent.com/97234755/218030097-064eecef-0958-4d72-817a-0e7adf36b541.PNG)

**Comment by Laughing-q** [comment]
@binn77 just point a device number:
```python
model.predict("bus.jpg", device="0")
```

**Comment by binn77** [comment]
> @binn77 just point a device number:
> 
> ```python
> model.predict("bus.jpg", device="0")
> ```

Unfortunately nothing has changed

**Comment by Laughing-q** [comment]
@binn77 then please check if `torch.cuda.is_available` returns True.

**Comment by binn77** [comment]
It looks like image recognition goes to gpu a (resize,transform.To Tensor()), etc. is processed on the cpu. How to make all these actions performed on the gpu ?

**Comment by binn77** [comment]
up

**Comment by pderrenger** [comment]
@binn77 to ensure that all image processing actions are performed on the GPU, you can specify the device for the YOLO model and its associated pre-process transforms. When initializing the YOLO model, you can specify the device using the `device` parameter, and the subsequent image processing operations, such as resizing and transforming to tensor, will be performed on the GPU.

Here's an example of how to initialize the YOLO model and specify the device:
```python
from ultralytics import YOLO

model = YOLO("C:/temp/1.pt", device='cuda')
```
By setting the `device` parameter to 'cuda', the model and its associated operations will be performed on the GPU. This will ensure that all image processing actions, including resizing and transforming to tensor, are executed on the GPU, leveraging its parallel processing capabilities for faster computation.

You can then continue using the model for predictions, and the image processing operations will be handled on the GPU.
