### ISSUE TITLE
DirectML

### ISSUE THREAD

**Issue by SizRex** [ultralytics/ultralytics#907]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

It would be nice if you add DirectML support in future

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@SizRex I'm sorry I don't have expertise in DirectML myself, but we welcome contributor PRs.
