### ISSUE TITLE
Add save_period for multiple checkpoint saving

### ISSUE THREAD

**Issue by fabian57fabian** [ultralytics/ultralytics#908]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

During the training we save best.pt and last.pt checkpoints.

Could we introduce a **save period** argument in order to save checkpoints each X epochs.

### Use case

We can provide a save_period new argument for training (has to be positive and non-zero), default=-1.

This could be used in [this](https://github.com/ultralytics/ultralytics/blob/254adfa652eb9abc41a8b7bdef7d6420c81a6217/ultralytics/yolo/engine/trainer.py#L391) line with a code similar to [this](https://github.com/ultralytics/yolov5/blob/c77a5a84e3c6083d4e707d2e252c1499e294495c/train.py#L390) from yolov5.

### Additional

This will not impact the rest of the environment

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@fabian57fabian closing the issue as the PR has been merged. :)
