### ISSUE TITLE
Why I cant detect anything in seg task？

### ISSUE THREAD

**Issue by divided7** [ultralytics/ultralytics#9085]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I train a simple segmentation task and get result in training:
![image](https://github.com/ultralytics/ultralytics/assets/72434716/f841d59a-f4e2-4200-91a3-2fbbe7eeecba)
But in the val set result:
![image](https://github.com/ultralytics/ultralytics/assets/72434716/5045fc3d-66d8-487c-9cd5-a224ae627277)

**Comment by Abandon-ht** [comment]
If you train a customised model , Please "Build a new model from YAML"



# Build a new model from YAML and start training from scratch
yolo segment train data=coco128-seg.yaml model=yolov8n-seg.yaml epochs=100 imgsz=640

# Start training from a pretrained *.pt model
yolo segment train data=coco128-seg.yaml model=yolov8n-seg.pt epochs=100 imgsz=640

# Build a new model from YAML, transfer pretrained weights to it and start training
yolo segment train data=coco128-seg.yaml model=yolov8n-seg.yaml pretrained=yolov8n-seg.pt epochs=100 imgsz=640

**Comment by glenn-jocher** [comment]
@Abandon-ht hi there! 👋 It looks like you're on the right track with your segmentation task. If you're training a customized model, indeed building a new model from a YAML configuration file is a recommended approach. This way, you ensure that the model's architecture is tailored to your specific segmentation task.

Here's a quick reminder on how to do it:

```bash
# Build and train a new model from YAML
yolo segment train data=coco128-seg.yaml model=yolov8n-seg.yaml epochs=100 imgsz=640
```

If you've already got a pretrained model and want to leverage its weights for improved performance, you can do so as follows:

```bash
# Train a new model from YAML with transferred pretrained weights
yolo segment train data=coco128-seg.yaml model=yolov8n-seg.yaml pretrained=yolov8n-seg.pt epochs=100 imgsz=640
```

This will allow you to customize and fine-tune your segmentation model's architecture while also benefiting from the weight initialization of a pretrained model. Let us know if you have any more questions or if there's anything else we can help with! Good luck with your segmentation task. 🚀
