### ISSUE TITLE
Getting bounding box details after prediction has already been done on a dataset

### ISSUE THREAD

**Issue by mdtanvir001** [ultralytics/ultralytics#9099]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I have basically trained a dataset using the yolov8, and I have done the prediction on the validation set one with and one without tracking (bot-sort). I want to make a comparison so I want to export the bounding box data (xyxy, conf and cls) of each frame for the video that was already gone through the prediction mode. Can i check if there a way to do that?

**Comment by glenn-jocher** [comment]
@mdtanvir001 certainly! After running predictions on your validation set, you can access and export the bounding box details (including coordinates, confidence scores, and class IDs) using the results object. Here's a quick code snippet on how to extract this information:

```python
from ultralytics import YOLO

# Load your trained model
model = YOLO('path/to/your/trained/model.pt')

# Run prediction
results = model.predict('path/to/your/validation/videos/or/images')

# Loop through results to extract bounding box details
for result in results:
    boxes = result.boxes  # Access the bounding boxes
    for i, box in enumerate(boxes.xyxy):
        # Each `box` contains [xmin, ymin, xmax, ymax, confidence, class]
        print(f"Box {i}: {box[:4]}, Confidence: {box[4]}, Class: {box[5]}")
```

This will print out the details for each detected object. To save this information, you might consider appending it to a list or directly writing it to a file within the loop. Hopefully, this helps with your comparison between the non-tracked and tracked predictions! 🙌

**Comment by mdtanvir001** [comment]
thank you so much managed to twig it from there and gather what i need :)

**Comment by glenn-jocher** [comment]
@mdtanvir001 fantastic to hear that you found what you needed! 😊 If you have any more questions down the road or need further assistance, don't hesitate to reach out. Happy detecting with YOLOv8!
