### ISSUE TITLE
Accessing class probability distribution for an object detected

### ISSUE THREAD

**Issue by EashanVytla** [ultralytics/ultralytics#9116]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,
I am working on a project where there are 5 objects given to me out of 64 possibilities. The 5 objects are given to me 10 minutes before I start. So I am trying to train a YOLOv8 model on the 64 classes. Then during inference, I want to compare the probabilities of the 5 objects and see if I can pick out the max out of the 5. If my understanding is correct, this would involve modifying the source code to obtain the softmax layer of the classifier. However, I am still trying to understand everything in the codebase. Is there any way of doing this? I am fine with attempting to modify the source code. Thank you!

**Comment by glenn-jocher** [comment]
@EashanVytla hello!

Thanks for reaching out with your question, and I'm glad to see you're diving into using YOLOv8 for your project! 😊

Indeed, your project's requirement to selectively focus on the probabilities of certain objects among a larger set is a bit specific. For your scenario, while extracting class probabilities directly from the model's output layers is possible, you might not need to modify the source code deeply. Here's a concise way to approach this using YOLOv8's Python API:

Assuming you've successfully trained your model on the 64 classes, you can obtain the detection results (including class probabilities) during inference like so:

```python
from ultralytics import YOLO

# Load your trained model
model = YOLO('path/to/your/trained/model.pt')

# Perform inference
results = model('path/to/your/image.jpg')

# Results.boxes contains the detection bounding boxes and class confidences
for box in results.boxes:
    # box.cls: detected class ID
    # box.conf: confidence score for the detected class
    if box.cls in [list_of_your_5_class_ids]:
        # Do your comparison or processing here
        print(f'Class {box.cls} detected with confidence {box.conf}')
```

This snippet assumes `"path/to/your/trained/model.pt"` is the path to your trained YOLOv8 model and that `list_of_your_5_class_ids` is a Python list containing the class IDs of your 5 objects of interest. `results.boxes` will contain all detected objects along with their classes (`cls`) and confidence scores (`conf`), allowing you to filter and compare as needed.

I hope this helps to move your project forward without needing to delve too deeply into source modifications! If you have any more questions or need further assistance, feel free to ask.

Happy coding! 🚀

**Comment by mohaliyet** [comment]
> @EashanVytla hello!
> 
> Thanks for reaching out with your question, and I'm glad to see you're diving into using YOLOv8 for your project! 😊
> 
> Indeed, your project's requirement to selectively focus on the probabilities of certain objects among a larger set is a bit specific. For your scenario, while extracting class probabilities directly from the model's output layers is possible, you might not need to modify the source code deeply. Here's a concise way to approach this using YOLOv8's Python API:
> 
> Assuming you've successfully trained your model on the 64 classes, you can obtain the detection results (including class probabilities) during inference like so:
> 
> ```python
> from ultralytics import YOLO
> 
> # Load your trained model
> model = YOLO('path/to/your/trained/model.pt')
> 
> # Perform inference
> results = model('path/to/your/image.jpg')
> 
> # Results.boxes contains the detection bounding boxes and class confidences
> for box in results.boxes:
>     # box.cls: detected class ID
>     # box.conf: confidence score for the detected class
>     if box.cls in [list_of_your_5_class_ids]:
>         # Do your comparison or processing here
>         print(f'Class {box.cls} detected with confidence {box.conf}')
> ```
> 
> This snippet assumes `"path/to/your/trained/model.pt"` is the path to your trained YOLOv8 model and that `list_of_your_5_class_ids` is a Python list containing the class IDs of your 5 objects of interest. `results.boxes` will contain all detected objects along with their classes (`cls`) and confidence scores (`conf`), allowing you to filter and compare as needed.
> 
> I hope this helps to move your project forward without needing to delve too deeply into source modifications! If you have any more questions or need further assistance, feel free to ask.
> 
> Happy coding! 🚀

"Is this reply still valid? `results.boxes` is causing an error."

**Comment by Mattia-Nardon** [comment]
> > @EashanVytla hello!
> > Thanks for reaching out with your question, and I'm glad to see you're diving into using YOLOv8 for your project! 😊
> > Indeed, your project's requirement to selectively focus on the probabilities of certain objects among a larger set is a bit specific. For your scenario, while extracting class probabilities directly from the model's output layers is possible, you might not need to modify the source code deeply. Here's a concise way to approach this using YOLOv8's Python API:
> > Assuming you've successfully trained your model on the 64 classes, you can obtain the detection results (including class probabilities) during inference like so:
> > ```python
> > from ultralytics import YOLO
> > 
> > # Load your trained model
> > model = YOLO('path/to/your/trained/model.pt')
> > 
> > # Perform inference
> > results = model('path/to/your/image.jpg')
> > 
> > # Results.boxes contains the detection bounding boxes and class confidences
> > for box in results.boxes:
> >     # box.cls: detected class ID
> >     # box.conf: confidence score for the detected class
> >     if box.cls in [list_of_your_5_class_ids]:
> >         # Do your comparison or processing here
> >         print(f'Class {box.cls} detected with confidence {box.conf}')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This snippet assumes `"path/to/your/trained/model.pt"` is the path to your trained YOLOv8 model and that `list_of_your_5_class_ids` is a Python list containing the class IDs of your 5 objects of interest. `results.boxes` will contain all detected objects along with their classes (`cls`) and confidence scores (`conf`), allowing you to filter and compare as needed.
> > I hope this helps to move your project forward without needing to delve too deeply into source modifications! If you have any more questions or need further assistance, feel free to ask.
> > Happy coding! 🚀
> 
> "Is this reply still valid? `results.boxes` is causing an error."

If you're encountering an AttributeError with results.boxes, 'list' object has no attribute 'boxes', it means that results is returning a list rather than a single object.

To resolve this, you can iterate over the first element of the results list to access the boxes. Here's how you can adjust the loop:

```python
for box in results[0].boxes:
```
