### ISSUE TITLE
About COCO Evaluation

### ISSUE THREAD

**Issue by Hezey** [ultralytics/ultralytics#912]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

@plashchynski @onuralpszr @adrianboguszewski @mehran66 @RangiLyu 
I'm sorry, I have a small problem.
The instances labeled in my training data are small target signals.
But why do the coco evaluation indicators have APm and APl results，not just APs？

### Additional

I obtained coco evaluation index by comparing predication.json and GT.json

**Comment by glenn-jocher** [comment]
@plashchynski The COCO evaluation metrics include three different Average Precision (AP) values: APs, APm, and APl, corresponding to small, medium, and large objects, respectively. The APs measures the precision for small objects, APm measures the precision for medium-sized objects, and APl measures the precision for large objects. Therefore, even if your training data mainly contains small target signals, the COCO evaluation will still provide metrics for medium and large objects as well.

**Comment by Hezey** [comment]
@glenn-jocher 
Thank you for your reply!
But I have only small targets in my dataset, so what are APm and  APl calculated based on?

**Comment by tongchangD** [comment]
> 


how to get APm and APl results data
