### ISSUE TITLE
Xview training failed 

### ISSUE THREAD

**Issue by vidsgr** [ultralytics/ultralytics#9127]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

yolo train data=xView.yaml
WARNING ⚠️ 'model' is missing. Using default 'model=yolov8n.pt'.
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (NVIDIA GeForce RTX 2060, 5920MiB)
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=xView.yaml, epochs=100, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train2, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train2
Overriding model.yaml nc=80 with nc=60

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]           
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]                  
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]                
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]                 
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 22        [15, 18, 21]  1    763012  ultralytics.nn.modules.head.Detect           [60, [64, 128, 256]]          
Model summary: 225 layers, 3022548 parameters, 3022532 gradients, 8.3 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning /home/ubuntu/datasets/xView/labels/train... 0 images, 760 backgrounds, 0 corrupt: 100%|██████████| 760/760 [00:03<
train: WARNING ⚠️ No labels found in /home/ubuntu/datasets/xView/labels/train.cache. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
train: WARNING ⚠️ Cache directory /home/ubuntu/datasets/xView/labels is not writeable, cache not saved.
WARNING ⚠️ No labels found in /home/ubuntu/datasets/xView/labels/train.cache, training may not work correctly. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
val: Scanning /home/ubuntu/datasets/xView/labels/train... 0 images, 86 backgrounds, 0 corrupt: 100%|██████████| 86/86 [00:00<00:00
val: WARNING ⚠️ No labels found in /home/ubuntu/datasets/xView/labels/train.cache. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
val: WARNING ⚠️ Cache directory /home/ubuntu/datasets/xView/labels is not writeable, cache not saved.
WARNING ⚠️ No labels found in /home/ubuntu/datasets/xView/labels/train.cache, training may not work correctly. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
Plotting labels to runs/detect/train2/labels.jpg... 
zero-size array to reduction operation maximum which has no identity
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.000156, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs/detect/train2
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      2.51G          0      124.7          0          0        640: 100%|██████████| 48/48 [00:12<00:00,  3.94it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 3/3 [00:00<00:00,  6.76
Traceback (most recent call last):
  File "/home/ubuntu/venv/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/ubuntu/venv/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 568, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/ubuntu/venv/lib/python3.10/site-packages/ultralytics/engine/model.py", line 655, in train
    self.trainer.train()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 213, in train
    self._do_train(world_size)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 429, in _do_train
    self.metrics, self.fitness = self.validate()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 551, in validate
    metrics = self.validator(self)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/ultralytics/engine/validator.py", line 195, in __call__
    stats = self.get_stats()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/ultralytics/models/yolo/detect/val.py", line 168, in get_stats
    stats = {k: torch.cat(v, 0).cpu().numpy() for k, v in self.stats.items()}  # to numpy
  File "/home/ubuntu/venv/lib/python3.10/site-packages/ultralytics/models/yolo/detect/val.py", line 168, in <dictcomp>
    stats = {k: torch.cat(v, 0).cpu().numpy() for k, v in self.stats.items()}  # to numpy
RuntimeError: torch.cat(): expected a non-empty list of Tensors

### Minimal Reproducible Example

To reproduce, just follow the steps to train the view dataset as explained here.
https://raw.githubusercontent.com/ultralytics/ultralytics/a5390de2f1091847b1036de9b11e82ca79772651/ultralytics/cfg/datasets/xView.yaml

### Additional

I have also tested this on different Python versions, 3.8/3.9/3.10, and RTX 3080-based GPUs. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@vidsgr hey there! Thanks for reaching out. Based on the error logs you've shared, it seems like the root cause of the issue is related to the `xView.yaml` file and specifically, to how labels are being detected (or, more accurately, not detected) during training. The warnings and final error suggest that no labels are found or considered valid during the dataset processing phase, likely resulting in the zero-size array error during validation.

A few things to check and try:

1. **Dataset Structure:** Ensure your dataset structure matches what YOLO expects. Typically, labels should be in a corresponding `labels` folder with a structure mirroring that of your images. Each label file should match its corresponding image name.

2. **Label Formats:** YOLO expects labels in a specific text format: `[class_id] [center_x] [center_y] [width] [height]`, where coordinates are normalized. Verify your labels follow this convention.

3. **Path Permissions:** The warning about the cache directory not being writeable could point to permission issues. Ensure the dataset directory is writeable by your user or the environment running the training process.

4. **Dataset Configuration:** Double-check the `xView.yaml` paths for both training and validation sets are correct and pointing to the right directories.

As a starting point, you might want to manually verify the format and existence of a few label files in the expected directory to rule out structure and formatting issues. 

Given the specifics of your message regarding different Python versions and GPU types, it seems the issue is firmly within the dataset preparation or configuration side of things.

Here's a quick example check you could perform on your dataset structure and label content:

```plaintext
/datasets/xView/
    /images/train/
        - img1.jpg
        - img2.jpg
    /labels/train/
        - img1.txt  # Make sure this file follows the correct format
        - img2.txt
```

And for a `img1.txt` example (ensure class IDs are correctly mapped as well):

```plaintext
0 0.5 0.5 1.0 1.0  # Example assuming a full-image bounding box for class '0'
```

I hope this helps! If you're still encountering issues after confirming the above, it might be beneficial to provide a snippet of your label file format and dataset directory structure for further assistance. 🚀

**Comment by vidsgr** [comment]
> @vidsgr hey there! Thanks for reaching out. Based on the error logs you've shared, it seems like the root cause of the issue is related to the `xView.yaml` file and specifically, to how labels are being detected (or, more accurately, not detected) during training. The warnings and final error suggest that no labels are found or considered valid during the dataset processing phase, likely resulting in the zero-size array error during validation.
> 
> A few things to check and try:
> 
> 1. **Dataset Structure:** Ensure your dataset structure matches what YOLO expects. Typically, labels should be in a corresponding `labels` folder with a structure mirroring that of your images. Each label file should match its corresponding image name.
> 2. **Label Formats:** YOLO expects labels in a specific text format: `[class_id] [center_x] [center_y] [width] [height]`, where coordinates are normalized. Verify your labels follow this convention.
> 3. **Path Permissions:** The warning about the cache directory not being writeable could point to permission issues. Ensure the dataset directory is writeable by your user or the environment running the training process.
> 4. **Dataset Configuration:** Double-check the `xView.yaml` paths for both training and validation sets are correct and pointing to the right directories.
> 
> As a starting point, you might want to manually verify the format and existence of a few label files in the expected directory to rule out structure and formatting issues.
> 
> Given the specifics of your message regarding different Python versions and GPU types, it seems the issue is firmly within the dataset preparation or configuration side of things.
> 
> Here's a quick example check you could perform on your dataset structure and label content:
> 
> ```
> /datasets/xView/
>     /images/train/
>         - img1.jpg
>         - img2.jpg
>     /labels/train/
>         - img1.txt  # Make sure this file follows the correct format
>         - img2.txt
> ```
> 
> And for a `img1.txt` example (ensure class IDs are correctly mapped as well):
> 
> ```
> 0 0.5 0.5 1.0 1.0  # Example assuming a full-image bounding box for class '0'
> ```
> 
> I hope this helps! If you're still encountering issues after confirming the above, it might be beneficial to provide a snippet of your label file format and dataset directory structure for further assistance. 🚀

Thanks for the quick reply. After spending a lot of time. I realized that the validation script is failing because of newer numpy. 

pip install numpy==1.23.0

This simply worked for me.

**Comment by glenn-jocher** [comment]
Hey @vidsgr! 🎉 Great to hear you've found the solution, and thanks for sharing it with the community! Versioning conflicts can be tricky to navigate, and it's super helpful to know that pinning `numpy` to `1.23.0` resolves the issue. Your experience will undoubtedly assist others encountering similar problems. If you stumble upon any more questions or need further assistance down the road, don't hesitate to reach out. Happy detecting with YOLOv8!
