### ISSUE TITLE
pandas.errors.ParserError: Error tokenizing data

### ISSUE THREAD

**Issue by Anzhc** [ultralytics/ultralytics#9129]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Exception has occurred: ParserError
Error tokenizing data. C error: Expected 14 fields in line 418, saw 20
  File "G:\YOLO\main.py", line 26, in main
    results = model.train(
  File "G:\YOLO\main.py", line 137, in <module>
    main()
pandas.errors.ParserError: Error tokenizing data. C error: Expected 14 fields in line 418, saw 20

### Environment

Ultralytics YOLOv8.1.29 🚀 Python-3.10.9 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce RTX 4070, 12282MiB)
Setup complete ✅ (12 CPUs, 63.2 GB RAM, 786.4/931.5 GB disk)

OS                  Windows-10-10.0.22631-SP0
Environment         Windows
Python              3.10.9
Install             pip
RAM                 63.16 GB
CPU                 AMD Ryzen 5 7600 6-Core Processor
CUDA                12.1

matplotlib          ✅ 3.8.3>=3.3.0
opencv-python       ✅ 4.6.0.66>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.1.0+cu121>=1.8.0
torchvision         ✅ 0.16.0+cu121>=0.9.0
tqdm                ✅ 4.64.1>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.1.4>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Minimal Reproducible Example

Just run training, i guess? Didn't do anything out of ordinary e-e

### Additional

Started getting this error when trying to train yolov8-seg models. yolov8 basic model works. It appears after first epoch. Specifically seem to be either on post-epoch update, or right after...

Im really at a loss, especially because right before that training of common yolov8 did run, but now that i checked if it does now - it didn't. Previously working datasets don't run now either.

I did try to reinstall pandas separately, delete pandas and ultralytics and install from zero, didn't work.
I did try various versions of pandas like 2.2.1, 2.2.0, 2.1.4, 2.0.3, none worked.
I did also try to install older version of Ultralytics, 8.1.0, it produced same error as well.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Anzhc** [comment]
Well... Solution was stupid. There is no error in Ultralytics and Pandas in my case.
But for anyone who would encounter it:

I think it tries to overwrite all files in project directory, if you save into existing one, and if you trained different model types, they produce different metrics, and there will be more files to read than expected, and it will error out.
This probably can happen with combination of set project and exist_ok variables, i.e.:
project="Muh Good Model",
...
exist_ok=True,
...

This is dead stupid issue that took way too long to figure out xD I submitted bug report 5 minutes before i did get to solution, welp. But hopefully it will help someone like me in future...

**Comment by glenn-jocher** [comment]
@Anzhc thank you so much for sharing your solution! 🎉 It's amazing how sometimes what seems like a deep technical issue can have a straightforward solution. Your experience underscores the importance of directory management when training multiple models, especially in the same project directory. 

It's a great reminder for all of us to be mindful of the `project` and `exist_ok` parameters to avoid unintended overwrites and mismatches in the files. Your insight is indeed valuable and will definitely help others facing similar issues. 

Thank you again for taking the time to come back and explain the resolution. It's contributions like yours that make the community stronger and more informed. Happy modeling! 🚀
