### ISSUE TITLE
Having more flexible data augmentations!

### ISSUE THREAD

**Issue by Justin900429** [ultralytics/ultralytics#913]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

The current v8 data augmentation is not flexible and requires users to modify the source code to achieve different augmentations. Add the user interface that will let people choose between using the default augmentations or their own. 

### Use case

If an image has lots of noise such as Impulse noise or Laplacian noise, adding noise into data augmentation can eliminate the discrepancy between the perdition and the ground truth.

### Additional

Working on this right now !!!!!!!

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@Justin900429 Looking forward to the PR!!! :)

**Comment by Justin900429** [comment]
Solved with PR #956

**Comment by pderrenger** [comment]
@Justin900429 great job on the PR #956! Your contribution is valuable to the YOLOv8 community! Keep up the good work!
