### ISSUE TITLE
Use V8 without API

### ISSUE THREAD

**Issue by Laudarisd** [ultralytics/ultralytics#9136]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would like to train my dataset just calling the train.py file which I saw in engine folder. 
Is it possible?

### Additional

Hello, 
Thanks for the amazing work. 
I was looking for an option to train custom dataset without using API. What I mean is, I would like to train my dataset just calling the train.py file which I saw in engine folder. 
Is it possible?
Further, I am trying to see my input image pixels during training session if it makes sense. At least from last layers or somewhere in the mid one. Because, my bboxes are really small. 
Can I get some idea?

Thanks

**Comment by Burhan-Q** [comment]
@Laudarisd there are [CLI commands](https://docs.ultralytics.com/usage/cli/#train) you can use. As an example:

```bash
yolo detect train data=coco128.yaml model=yolov8n.pt epochs=100 imgsz=640
```

You can find all valid arguments/settings for training [here](https://docs.ultralytics.com/modes/train/#train-settings). You could try to see if `visualize` would provide the insight you're looking for, or when you run `train` check the results directory for `batchN.jpg` (`N` can be any number) to see examples of the data during training.

**Comment by Laudarisd** [comment]
Thanks for your quick response. 
If I am not wrong, this still usages `yolo` which means yolo API.
My question is, instead of this, can I just use `python3 train.py -- .....--....--` as we used to use in previous versions.
During training I have really sensitive dataset with small boxes. So, i will have to avoid using many tuner such as augmentations, flip, and more...

**Comment by Burhan-Q** [comment]
> have to avoid using many tuner such as augmentations, flip, and more

You can manually disable augmentations for training via arguments or by using a custom config YAML. There is no "tuner" used unless you run `model.tune` or `yolo tune` and it is not specifically for training but to find optimal hyperparameters.

The augmentations are enabled to help improve your model's performance on changes that are likely to be present in deployment. Some common ones are translation (slight shift in the image and object location), flip-left/right (mirroring objects), or scale (increase the object size to simulate different sizes or distances). Disabling augmentations will likely result in a low performing model, but if you wish to disable augmentations it's possible to do so.

You can write your own `train.py` file but you must use the `ultralytics` library. There is no way around it for training a model without it.
