### ISSUE TITLE
Is there a way to get map values at different IOU threshold (map60, map70, etc)?

### ISSUE THREAD

**Issue by anggapark** [ultralytics/ultralytics#9138]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thank you for this excellent open-source YOLO project. I and I'm sure many others have benefit a lot from this!

I'm working on my final project using YOLOv8 object detection. I'm trying to get mAP values at each different threshold (0.5-0.95) beside mAP50, for example mAP60, mAP70, etc. for analysis purpose.

I tried. 
```ruby
ious = [0.5, 0.6, 0.7, 0.8, 0.9]
for iou in ious:
    print('#'*50)
    print(f'IOU {iou}')
    print('#'*50)

    models = YOLO(os.path.join(results_dir, batch16_img640, f'weights/best.pt'))
    data = f'{dataset.location}/dataset.yaml'
    results = models.val(
        data=data,
        split='val',
        conf=0.35,
        iou=iou
        )

```
All of the iteration returned similar/same metric values.

From this [issues](https://github.com/ultralytics/ultralytics/issues/5986), I found that mAP50 returned from results is not directly influenced by IoU threshold parameter in model.val(). 

Is there any built-in method to get these values (mAP60, mAP70, etc.)? if not, what file in source code that I have to modify to get these values?

Looking forward to your reply, thanks very much!

**Comment by glenn-jocher** [comment]
@anggapark hey there! 🙌

Thanks for the kind words and for diving deep into YOLOv8 for your project. It's awesome to see such engagement with the community. To answer your question, currently, YOLOv8 does not provide a direct method to obtain mAP values at specific IoU thresholds (like mAP60, mAP70, etc.) through a single function call in its API. The mAP values reported are calculated across a range of IoU thresholds (0.5 - 0.95 as per COCO standards) during validation.

However, you can modify the evaluation script to calculate mAP for custom IoU thresholds. This would involve adjusting the area under precision-recall calculations at the desired IoUs. You'll need to dive into `engine/val.py` or the corresponding evaluation script used in your project setup, precisely where the evaluation metrics are computed.

For a custom approach, ensure you're comfortable with tweaking the codebase and re-running your evaluations. Keep an eye on potential updates or feature requests in the GitHub repo that might introduce this functionality directly.

Let's keep pushing the boundaries of what's possible with YOLOv8! 💫 If you have more questions or need further assistance, feel free to reach out.

**Comment by anggapark** [comment]
Hello, thank you for your fast response, really appreciate it!

I think I've found the solution in `utils/metrics.py` file, In __class Metric(SimpleClass)__, there are two methods

https://github.com/ultralytics/ultralytics/blob/8617fcf32d36a798a24631c4d495a3fcfc456145/ultralytics/utils/metrics.py#L696-L714


from the class Attributes docs, it says that 

https://github.com/ultralytics/ultralytics/blob/8617fcf32d36a798a24631c4d495a3fcfc456145/ultralytics/utils/metrics.py#L628

So, I just need to change self.all_ap columns. If IOU 0.5 is self.all_ap[:, 0] and IOU 0.75 is self.all_ap[:, 5], then 
- IOU 0.6 is self.all_ap[:, 2]
- IOU 0.7 is self.all_ap[:, 4]

Is it the correct solution?

**Comment by anggapark** [comment]
I've tried it and it's correct, thanks for your help

**Comment by glenn-jocher** [comment]
Hey there!

You're absolutely on the right track 👍. Accessing `self.all_ap` at the specified columns to obtain mAP values for different IoU thresholds is indeed the correct approach. Your understanding matches the structure of the `metrics.py` file perfectly.

For a quick reference, the mAP at specific IoU thresholds can be obtained as follows:
- IOU 0.6 (mAP @anggapark.6) --> `self.all_ap[:, 2]`
- IOU 0.7 (mAP@0.7) --> `self.all_ap[:, 4]`

Glad to hear it worked out for you! If you have any more questions or need further assistance, feel free to ask. Keep up the great work with YOLOv8! 🚀

**Comment by Petros626** [comment]
```python
@property
    def ap70(self):
        """
        Returns the Average Precision (AP) at an IoU threshold of 0.7 for all classes.

        Returns:
            (np.array, list): Array of shape (nc,) with AP70 values per class, or an empty list if not available.
        """
        return self.all_ap[:, 4].mean() if len(self.all_ap) else 0.0
```

0.5 corresponds to index 0
0.55 corresponds to index 1
0.6 corresponds to index 2
0.65 corresponds to index 3
0.7 corresponds to index 4
and so on until 0.95

**Comment by Petros626** [comment]
> I've tried it and it's correct, thanks for your help

did you extend these line too?
https://github.com/ultralytics/ultralytics/blob/cf9ab17426d5bf36ed614caedf5b398ac6009ed6/ultralytics/utils/metrics.py#L733

**Comment by glenn-jocher** [comment]
If you're referring to extending the `class_result` method in `metrics.py`, it's not mandatory for retrieving mAP values at specific IoU thresholds. The mAP values can already be accessed directly via `self.all_ap` as you described earlier. However, if you aim to explicitly include specific IoU thresholds in the method's return values, you can modify it accordingly. Let me know if you need further clarification!

**Comment by Petros626** [comment]
@glenn-jocher if I want for the validation of a model also the `ap70` method, which is called during the training (param `val=True`) or at the end (`val=False`) I have to add it here or not? `class_result` gives the metrics in between/end iof training? https://github.com/ultralytics/ultralytics/blob/e336d87a685fa8c5f1960edd5cdd0fd3559c36ef/ultralytics/utils/metrics.py#L733

**Comment by glenn-jocher** [comment]
The `class_result` method provides class-specific metrics (precision, recall, AP50, and AP50-95) during or after validation. If you want to include `ap70` specifically, you can extend the `class_result` method to return `self.all_ap[:, 4]` (corresponding to IoU 0.7) along with the existing metrics. This would allow you to access `ap70` during validation or at the end of training.

**Comment by Petros626** [comment]
That's nearly the way I did. I created a new method `def ap70` and extended it to the return of `class result`.

```python
def ap70(self): # NOTE: https://github.com/ultralytics/ultralytics/issues/9138
    """
    Returns the Average Precision (AP) at an IoU threshold of 0.7 for all classes.
    
    Returns:
    (np.array, list): Array of shape (nc,) with AP70 values per class, or an empty list if not available.
    """
    # [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
    print(f'class Metric: using ap70')
    return self.all_ap[:, 4] if len(self.all_ap) else 0.0
```
```python
def class_result(self, i):
    """Class-aware result, return p[i], r[i], ap50[i], ap[i]."""
    return self.p[i], self.r[i], self.ap50[i], self.ap70[i], self.ap[i] # 04.01.2025 add method ap70
```

**Comment by glenn-jocher** [comment]
@Petros626 your implementation looks great! Extending the `class_result` method to include `ap70` is a clean and effective way to integrate it with the metric outputs. If you encounter further issues or need additional insights, feel free to ask. Keep up the great work!

**Comment by Petros626** [comment]
@glenn-jocher can you help at https://github.com/ultralytics/ultralytics/issues/18551

**Comment by glenn-jocher** [comment]
Thank you for reaching out. For assistance with your issue, please comment directly on the thread at https://github.com/ultralytics/ultralytics/issues/18551 to ensure visibility and support from the community and maintainers.
