### ISSUE TITLE
How can I use the mask data faster?

### ISSUE THREAD

**Issue by soohwan-justin** [ultralytics/ultralytics#914]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I want to use the both of bounding boxes and segmentation result of YOLO V8 on ROS environment.

One of my plan is, I want to use the mask data to get rid of data at the out of ROI.

I will use depth image, and I want to read only points in the mask from YOLO V8 result.

I think I can do it if I use bitwise_and with the depth image and mask.

So I tried this issue : https://github.com/ultralytics/ultralytics/issues/561, but it looks it takes too much time.

Is there any solution for what I want to do?

**Comment by AyushExel** [comment]
You can just pass `boxes=False` in the model inference call to only get mask data.

**Comment by soohwan-justin** [comment]
I mean, it looks it takes too much time while it is processing the mask data with original(depth) image.

I have a plan to use bounding box as well.

I am looking for some kind of... to process segmentation in the V8 pipeline, not as the result of the model.

I think I am processing the same thing which is already processed in the V8 model with result of V8 model.

**Comment by pderrenger** [comment]
@soohwan-justin i understand your concern. When using the YOLOv8 model, you could improve the performance by only processing segmentation with the depth image after getting the result of the model. Alternatively, if you want to combine the masks, you can use standard OpenCV functions like `cv2.addWeighted()` to blend the mask with the depth image.
