### ISSUE TITLE
ONNX question

### ISSUE THREAD

**Issue by HouseWei** [ultralytics/ultralytics#9140]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I use exported onnx model to predict, it default resizes my input image size to 640x640.
I want to input with orginal iamge size
How do I do it?
(I guess there is a preprocess that will resize my image when I input a iimage)

### Additional

I use `model.export(format='onnx', imgsz=5120, dynamic=True)` 
No matter what imgsz I set, the result is always 640x640
![捕获](https://github.com/ultralytics/ultralytics/assets/57085720/92c472a7-790a-47c6-9a24-6a64d640c7d8)

**Comment by HouseWei** [comment]
I solved it.
'onnx_model.predict(image_path, imgsz=5120)'
haha, I used 'onnx_model(image_path)' before,

**Comment by glenn-jocher** [comment]
@HouseWei that's great news, I'm glad to hear you solved it! 🎉 It looks like explicitly specifying the `imgsz` parameter during prediction was the key. Thank you for sharing your solution as well; it might help others who encounter the same situation. Keep up the good work, and don't hesitate to reach out if you have more questions. Happy coding!
