### ISSUE TITLE
Annotated images are displayed where you want them to be.

### ISSUE THREAD

**Issue by Zzzxi** [ultralytics/ultralytics#9141]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

    def show(self, *args, **kwargs):
        """Show annotated results image."""
        self.plot(show=True, *args, **kwargs)
   results = model.predict(source, save=True, show_conf=False,show=True)  # predict on an image

When I use this function, the image displayed by show will appear at the bottom of the screen, if I want the image to appear in a fixed position on the screen, how should I change it?

**Comment by glenn-jocher** [comment]
@Zzzxi hey there! 😊 To control where your annotated image appears on the screen, you'll need to handle the window positioning directly with OpenCV, as the default `show()` method doesn't support specifying window positions. Here's a quick example on how you can do this:

```python
import cv2
from ultralytics import YOLO

# Load your model
model = YOLO('yolov8n.pt')

# Predict an image
results = model.predict('path/to/image.jpg', save=True, show_conf=False)

# Get the annotated image
annotated_image = results[0].plot(show=False)  # Ensure show is set to False

# Set the window name
window_name = "Annotated Image"

# Create a window and move it to a desired position (x=100, y=100 for example)
cv2.namedWindow(window_name)
cv2.moveWindow(window_name, 100, 100)  # Adjust these values as per your need

# Show the image
cv2.imshow(window_name, annotated_image)
cv2.waitKey(0)  # Wait for key press to close
cv2.destroyAllWindows()
```

In this code, we first create a window using `cv2.namedWindow()` and then use `cv2.moveWindow()` to specify its position on the screen. Adjust the `(100, 100)` values in the `cv2.moveWindow(window_name, 100, 100)` line to place the window wherever you'd like. 🖼️

Hope this helps! Let us know if you have any more questions.

**Comment by Zzzxi** [comment]
You're right!

**Comment by glenn-jocher** [comment]
@Zzzxi Absolutely, you've got it! To have the image appear at a specific position on your screen, you can use OpenCV's window management functions. Here's a sleek example to put your image at coordinates (100, 100) on your display:

```python
import cv2
from ultralytics import YOLO

# Initialize and predict
model = YOLO('yolov8n.pt')
results = model.predict('path/to/your/image.jpg')

# Grab the annotated frame
annotated_frame = results[0].plot(show=False)

# Create a window and position it
window_name = "YOLOv8 Prediction"
cv2.namedWindow(window_name)
cv2.moveWindow(window_name, 100, 100)

# Show it off!
cv2.imshow(window_name, annotated_frame)
cv2.waitKey(0)
cv2.destroyAllWindows()
```

This will pop the window right where you want it. If there's anything else, just ping! 🚀
