### ISSUE TITLE
AttributeError: 'Image' object has no attribute 'shape'.

### ISSUE THREAD

**Issue by janardan-ds** [ultralytics/ultralytics#9145]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

@glenn-jocher 

_I'm using two models at the same time first one is of classifier and second is of obb, when I'm running the script with the Ultrlytics version of 8.1.28 then I'm getting the error for classification model throwing the error :_

> File "/home/techvamp/anaconda3/envs/yolov5/lib/python3.9/site-packages/ultralytics/engine/model.py", line 155, in __call__
>     return self.predict(source, stream, **kwargs)
>   File "/home/techvamp/anaconda3/envs/yolov5/lib/python3.9/site-packages/ultralytics/engine/model.py", line 406, in predict
>     return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
>   File "/home/techvamp/anaconda3/envs/yolov5/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 204, in __call__
>     return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
>   File "/home/techvamp/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
>     response = gen.send(None)
>   File "/home/techvamp/anaconda3/envs/yolov5/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 279, in stream_inference
>     im = self.preprocess(im0s)
>   File "/home/techvamp/anaconda3/envs/yolov5/lib/python3.9/site-packages/ultralytics/models/yolo/classify/predict.py", line 46, in preprocess
>     [self.transforms(Image.fromarray(cv2.cvtColor(im, cv2.COLOR_BGR2RGB))) for im in img], dim=0
>   File "/home/techvamp/anaconda3/envs/yolov5/lib/python3.9/site-packages/ultralytics/models/yolo/classify/predict.py", line 46, in <listcomp>
>     [self.transforms(Image.fromarray(cv2.cvtColor(im, cv2.COLOR_BGR2RGB))) for im in img], dim=0
>   File "/home/techvamp/anaconda3/envs/yolov5/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
>     img = t(img)
>   File "/root/miniconda3/envs/v8/lib/python3.9/site-packages/ultralytics/data/augment.py", line 1114, in __call__
> AttributeError: 'Image' object has no attribute 'shape'

_And if I'm downgrading the ultralytics version 8.0.222 so that the classifier model will work then getting the error for obb as obb was not present in the older version and it is throwing the error:_

> File "/home/techvamp/anaconda3/envs/yolo_test/lib/python3.8/site-packages/ultralytics/engine/model.py", line 94, in __init__
>     self._load(model, task)
>   File "/home/techvamp/anaconda3/envs/yolo_test/lib/python3.8/site-packages/ultralytics/engine/model.py", line 146, in _load
>     self.model, self.ckpt = attempt_load_one_weight(weights)
>   File "/home/techvamp/anaconda3/envs/yolo_test/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 628, in attempt_load_one_weight
>     ckpt, weight = torch_safe_load(weight)  # load ckpt
>   File "/home/techvamp/anaconda3/envs/yolo_test/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 567, in torch_safe_load
>     return torch.load(file, map_location='cpu'), file  # load
>   File "/home/techvamp/anaconda3/envs/yolo_test/lib/python3.8/site-packages/torch/serialization.py", line 1026, in load
>     return _load(opened_zipfile,
>   File "/home/techvamp/anaconda3/envs/yolo_test/lib/python3.8/site-packages/torch/serialization.py", line 1438, in _load
>     result = unpickler.load()
>   File "/home/techvamp/anaconda3/envs/yolo_test/lib/python3.8/site-packages/torch/serialization.py", line 1431, in find_class
>     return super().find_class(mod_name, name)
> AttributeError: Can't get attribute 'OBBModel' on <module 'ultralytics.nn.tasks' from '/home/techvamp/anaconda3/envs/yolo_test/lib/python3.8/site-packages/ultralytics/nn/tasks.py'>
> 
> 

_Using only one version as of now I didn't found any stable version on which both are working, I have only one option now if I have to use both simultaneously then I have to create two different docker images._

**Apart from that is there any stable version available where the issue with the classifier has been resolved with the one where obb is also working?**

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@janardan-ds hey there! Thanks for bringing this detailed issue to our attention. 🙇‍♂️ It looks like you're encountering a compatibility issue across different Ultralytics YOLO versions related to classifier and obb (Oriented Bounding Box) models. At the moment, ensuring full backward compatibility or forward support for all features across versions can be challenging.

For the `AttributeError: 'Image' object has no attribute 'shape'.` error, it seems there might be a version-specific handling of the image object in the transform or preprocess step. This could likely be an issue with the torchvision transforms expecting a PIL Image, while somewhere along the way, it's being passed an ndarray without shape attribute or vice versa.

To troubleshoot this, a specific fix could entail ensuring the input to the classifier or OBB model is in the expected format. Here's a quick example to ensure your image is in the right format before prediction:

```python
import cv2
from PIL import Image
from ultralytics import YOLO

# Load your models as per your setup
classifier_model = YOLO('path/to/classifier_model.pt')
obb_model = YOLO('path/to/obb_model.pt')

# Assuming you have loaded an image using cv2
cv2_image = cv2.imread('path/to/image.jpg')
# Convert to PIL Image for classifier
pil_image = Image.fromarray(cv2.cvtColor(cv2_image, cv2.COLOR_BGR2RGB))

# Now you can safely run predictions
classifier_results = classifier_model(pil_image)
obb_results = obb_model(cv2_image)
```

Regarding running both models in the same environment: if there's no immediate release addressing your specific scenario, creating two different execution environments (like Docker containers, as you mentioned) is your safest bet for now. This approach ensures each model runs with its compatible library versions without interference.

We're constantly working on improving the models and addressing compatibility issues. Keep an eye on our [GitHub releases](https://github.com/ultralytics/ultralytics/releases) for updates that might include a unified solution!

🛠 In the meantime, if you have a specific enhancement in mind or a proposed fix, we'd love to see community contributions, even though I notice you're currently not looking to submit a PR. Anyone else in the community who encounters this and feels like contributing, please know your support is invaluable!

**Comment by JairajJangle** [comment]
Facing the same issue after upgrading Ultralytics from **8.0.x** to **8.1.x** as well as on **8.2.x**. 

**Error logs:**
```shell
---> 12     results = model.predict(
     13         source          = image,
     14         conf            = conf,
     15         
     16         save            = True,
     17         show_labels     = True,
     18         line_width      = 2 if save else None,
     19         
     20         retina_masks    = True,
     21         # imgsz           = imgsz,
     22         augment         = True,
     23         max_det         = max_det,
     24         iou             = 0.1,
     25         half            = half,
     26     )
     28     return results

File /usr/local/lib/python3.9/dist-packages/ultralytics/engine/model.py:452, in Model.predict(self, source, stream, predictor, **kwargs)
    450 if prompts and hasattr(self.predictor, "set_prompts"):  # for SAM-type models
    451     self.predictor.set_prompts(prompts)
--> 452 return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)

File /usr/local/lib/python3.9/dist-packages/ultralytics/engine/predictor.py:168, in BasePredictor.__call__(self, source, model, stream, *args, **kwargs)
    166     return self.stream_inference(source, model, *args, **kwargs)
    167 else:
--> 168     return list(self.stream_inference(source, model, *args, **kwargs))

File /usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py:43, in _DecoratorContextManager._wrap_generator.<locals>.generator_context(*args, **kwargs)
     40 try:
     41     # Issuing `None` to a generator fires it up
     42     with self.clone():
---> 43         response = gen.send(None)
     45     while True:
     46         try:
     47             # Forward the response to our caller and get its next request

File /usr/local/lib/python3.9/dist-packages/ultralytics/engine/predictor.py:244, in BasePredictor.stream_inference(self, source, model, *args, **kwargs)
    242 # Preprocess
    243 with profilers[0]:
--> 244     im = self.preprocess(im0s)
    246 # Inference
    247 with profilers[1]:

File /usr/local/lib/python3.9/dist-packages/ultralytics/models/yolo/classify/predict.py:46, in ClassificationPredictor.preprocess(self, img)
     43         img = torch.stack([self.transforms(im) for im in img], dim=0)
     44     else:
     45         img = torch.stack(
---> 46             [self.transforms(Image.fromarray(cv2.cvtColor(im, cv2.COLOR_BGR2RGB))) for im in img], dim=0
     47         )
     48 img = (img if isinstance(img, torch.Tensor) else torch.from_numpy(img)).to(self.model.device)
     49 return img.half() if self.model.fp16 else img.float()

File /usr/local/lib/python3.9/dist-packages/ultralytics/models/yolo/classify/predict.py:46, in <listcomp>(.0)
     43         img = torch.stack([self.transforms(im) for im in img], dim=0)
     44     else:
     45         img = torch.stack(
---> 46             [self.transforms(Image.fromarray(cv2.cvtColor(im, cv2.COLOR_BGR2RGB))) for im in img], dim=0
     47         )
     48 img = (img if isinstance(img, torch.Tensor) else torch.from_numpy(img)).to(self.model.device)
     49 return img.half() if self.model.fp16 else img.float()

File /usr/local/lib/python3.9/dist-packages/torchvision/transforms/transforms.py:94, in Compose.__call__(self, img)
     92 def __call__(self, img):
     93     for t in self.transforms:
---> 94         img = t(img)
     95     return img

File /usr/local/lib/python3.9/dist-packages/ultralytics/data/augment.py:1355, in CenterCrop.__call__(self, im)
   1345 def __call__(self, im):
   1346     """
   1347     Resizes and crops the center of the image using a letterbox method.
   1348 
   (...)
   1353         (numpy.ndarray): The center-cropped and resized image as a numpy array.
   1354     """
-> 1355     imh, imw = im.shape[:2]
   1356     m = min(imh, imw)  # min dimension
   1357     top, left = (imh - m) // 2, (imw - m) // 2

File /usr/local/lib/python3.9/dist-packages/PIL/Image.py:517, in Image.__getattr__(self, name)
    515     deprecate("Image categories", 10, "is_animated", plural=True)
    516     return self._category
--> 517 raise AttributeError(name)

AttributeError: shape
```
FYI: I have ensured that the image is indeed a numpy image. 

The exact same code works perfectly fine on ultralytics version 8.0.x. I have been facing this issue since months but I got around this by using the older version of ultralytics(8.0.x). But, now I really want to use v8.2.x to take advantage of the massive improvements in the latest version.

**Comment by glenn-jocher** [comment]
Hey there! It seems like you've encountered an issue when transitioning from **Ultralytics v8.0.x** to newer versions **8.1.x** and **8.2.x**. 

From your error logs, the problem appears to be with how images are being preprocessed before being passed to the model for predictions. The section of the code causing the error is attempting to access the `.shape` attribute on what it expects to be a numpy array, but it seems a PIL Image object is being passed instead.

To resolve this, ensure that you're converting your images into the expected format (a numpy array) before they reach the `predict()` function. Here's a small piece of code that demonstrates making sure your image is in the right format:

```python
import cv2
import numpy as np
from PIL import Image

# Assuming 'image' is your input image in PIL format
if isinstance(image, Image.Image):
    image = np.array(image)

# Then continue with your existing predict code
results = model.predict(
    source          = image,
    conf            = conf,
    save            = True,
    show_labels     = True,
    line_width      = 2 if save else None,
    retina_masks    = True,
    augment         = True,
    max_det         = max_det,
    iou             = 0.1,
    half            = half,
)
```

The key here is to perform a type check and convert the PIL image to a numpy array using `np.array(image)` before it's passed into the `predict()` function. Ensure this conversion right before making predict calls should help maintain compatibility with the newer Ultralytics versions.

We're constantly working to improve and document such changes better. Thank you for your patience and for keeping up with the updates! Feel free to reach out if you face any more issues or have further questions. Happy coding! 😊

**Comment by JairajJangle** [comment]
Thank you for the quick response @glenn-jocher. I tried the solution you provided, but unfortunately, I get the same error:

```shell
... in run_detection(model, image, imgsz, save, max_det, conf, half)
     16 if isinstance(image, Image.Image):
     17     image = np.array(image)
---> 19 results = model.predict(
     20     source          = image,
     21     conf            = conf,
     22     
     23     save            = True,
     24     show_labels     = True,
     25     line_width      = 2 if save else None,
     26     
     27     retina_masks    = True,
     28     # imgsz           = imgsz,
     29     augment         = True,
     30     max_det         = max_det,
     31     iou             = 0.1,
     32     half            = half,
     33 )
     35 return results
.
.
.
<< Same error trace as above >>
```

**Comment by glenn-jocher** [comment]
@JairajJangle hey there! 😊 It looks like we're still hitting a snag, but no worries, let's dig a bit further into this. Given the snippet and error, the issue seems rooted around the image format expected by the predictor. Here are a couple of checks and adjustments we can try:

1. After converting the `PIL.Image` to a numpy array, verify that it's in the expected BGR color format, as `cv2` and some Ultralytics processing might expect it this way.

2. Double-check the `source=` parameter in `model.predict`. It's designed to accept a path to the image or a list of numpy images. Ensure the image is appropriately wrapped in a list if it's not a path string.

Here's a snippet reflecting these points:

```python
# Convert PIL image to numpy array and ensure it's in BGR format
if isinstance(image, Image.Image):
    image = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)

# Wrap the image in a list if directly passing the numpy array
results = model.predict(
    source          = [image],  # Note the wrapping list here
    conf            = conf,
    save            = True,
    ...
)
```

Try this out and see if it helps. If the issue persists, could you share more about the context or setup where `image` is originating from? Sometimes the devil is in the details. Looking forward to getting this resolved together! 🚀

**Comment by JairajJangle** [comment]
Thank you for the help, @glenn-jocher. I have multiple models trained on custom datasets, and I perform predictions synchronously using these models, one after another. After hours of debugging, it turns out that the problem might be with one of my custom-trained models, rather than the format of the source image.

There is one key difference between this problematic model and the other "good" models: the problematic model is trained for classification tasks, while the others are trained for detection tasks. This could be why `predict` is failing 🤔.

However, I can't understand why predictions using this classification model fail on the newer Ultralytics version while they work perfectly fine on older versions. As mentioned earlier, I tried to run predictions using other custom-trained models designed for detection tasks, and `model.predict` works perfectly fine for those. As you pointed out, I have ensured that the image I pass as `source` to the `predict` function is indeed a numpy array (as shown below).

---

As requested, here’s how my `image` is initiated; it’s a simple empty image of 16 x 16 size:
```python
empty_img = np.zeros((16, 16, 3), dtype=np.uint8)
```

I then pass this `empty_image` to the `run_detection` function, which executes `model.predict(...)` on that image.

---

Thank you again for the support and hoping to get this issue resolved soon.

**Comment by glenn-jocher** [comment]
@JairajJangle hey there! 👋 Thanks for the detailed breakdown of your issue, and for your patience during the debugging process. It's intriguing to see how different model types interact with our newer version. 

Since your classification model behaves differently across versions, while detection models work fine, it hints at changes in handling classification tasks in newer versions. Perhaps updates or optimizations specific to classification could be at play here.

One workaround, for now, could be tweaking how you prepare your `source` just for the classification model. Since the error persists even with a numpy array, we might want to double-check if the model expects a certain image format or preprocessing step that's handled differently in the newer version. Also, ensuring your model is loaded and called in the right context for classification tasks could help. Here's a quick sanity check you could perform:

```python
# Ensuring the source image is correctly prepared
source_img = np.zeros((16, 16, 3), dtype=np.uint8)  # Your empty image
source_img_list = [source_img]  # Wrapping in list if not already

# Now, using your classification model
results = classification_model.predict(source=source_img_list, ...)
```

Given how different tasks might have slightly varied expectations for inputs, it might also be worth revisiting any updated documentation or release notes for hints on changes relevant to classification models.

Let's keep the conversation going, and please don't hesitate to reach out if this approach sheds any light or if the issue persists. We're here to help you navigate through it! 🚀

**Comment by JairajJangle** [comment]
Hi @glenn-jocher! I tried wrapping the image in a list, but unfortunately, the same error persists. I then replaced my custom-trained classification model with a pre-trained model (`yolov8n-cls.pt`), and it did not throw any error. This suggests the issue might be related to backwards compatibility.

The custom dataset classification model that I trained was developed using Ultralytics `8.0.x`. For further investigation and possibly to reproduce this issue, we might need to train a simple model using the `8.0.x` version and then check if we can execute `predict` using this model on the newer: `8.2.x` or `8.1.x` versions.

---

Meanwhile, as a workaround, I will need to re-train the classification model using the `8.2.x` version of Ultralytics. I will keep this thread posted if I have any updates related to the reproducibility of the issue by training a classification model using v8.0.x as described above.

**Comment by glenn-jocher** [comment]
Hi there! 🙋‍♂️ Thanks for sharing your findings with the community. It's indeed insightful to learn that the pre-trained `yolov8n-cls.pt` worked seamlessly, while the issue seems to be tied to the custom-trained classification model from an older version. Your approach to testing backward compatibility by training a simple model on `8.0.x` and evaluating it on newer versions like `8.2.x` or `8.1.x` sounds like a solid plan to pinpoint the issue.

Meanwhile, retraining your classification model on `8.2.x` could indeed serve as a good workaround. I'm looking forward to hearing back about your progress and any discoveries related to model compatibility. Your contributions are invaluable to enhancing Ultralytics YOLOv8 for everyone! 🚀

**Comment by hariouat** [comment]
> Hi @glenn-jocher! I tried wrapping the image in a list, but unfortunately, the same error persists. I then replaced my custom-trained classification model with a pre-trained model (`yolov8n-cls.pt`), and it did not throw any error. This suggests the issue might be related to backwards compatibility.
> 
> The custom dataset classification model that I trained was developed using Ultralytics `8.0.x`. For further investigation and possibly to reproduce this issue, we might need to train a simple model using the `8.0.x` version and then check if we can execute `predict` using this model on the newer: `8.2.x` or `8.1.x` versions.
> 
> Meanwhile, as a workaround, I will need to re-train the classification model using the `8.2.x` version of Ultralytics. I will keep this thread posted if I have any updates related to the reproducibility of the issue by training a classification model using v8.0.x as described above.

This solution worked for me. 

https://github.com/ultralytics/ultralytics/issues/7473

**Comment by glenn-jocher** [comment]
Hi there! 👋 Thanks for the update and for diligently testing different scenarios. It does seem like a backward compatibility issue with the custom-trained model from `8.0.x`. Retraining on `8.2.x` sounds like a practical approach for now.

Your plan to further investigate by training a simple model on `8.0.x` and testing it on newer versions is a great way to help us pinpoint any specific compatibility issues. We appreciate your efforts in keeping us informed and helping improve YOLOv8. Looking forward to your findings! 🚀

**Comment by kssion** [comment]
我也遇到了同样的问题，我认为以下代码逻辑错误，条件永远不成立，这个问题最初在8.0.233（ PR #4546 ）版本中出现并延续至今。

同样的问题 #7473

请确认这部分代码是否存在问题。

file: ultralytics/models/yolo/classify/predict.py
```py
# line: 34
self._legacy_transform_name = "ultralytics.yolo.data.augment.ToTensor"

# lines: 39-41
is_legacy_transform = any(
    self._legacy_transform_name in str(transform) for transform in self.transforms.transforms
)
# Always false
```

**Comment by pderrenger** [comment]
@kssion thank you for bringing this to our attention. To help us investigate further, could you please confirm if the issue persists with the latest version of the Ultralytics package? We continuously update our codebase, and it's possible that recent changes may have addressed this problem. If the issue remains, we'll look into it more closely.

**Comment by kssion** [comment]
> @kssion感谢您向我们报告此问题。为了帮助我们进一步调查，您能否确认该问题是否仍然存在于最新版本的 Ultralytics 软件包中？我们会不断更新代码库，最近的更改可能已经解决了此问题。如果问题仍然存在，我们会更仔细地调查。

@pderrenger 感谢您的评论！是的，我使用的是最新版本8.2.72，训练模型所用的版本是8.0.230，在预测时出现此问题。

Demo：
```
from ultralytics import YOLO

model = YOLO('orientation-cls-20240409-3/weights/best.pt')
results = model.predict('10023-1-1701593029095178600.jpg')
for r in results:
    print(r.probs)
```

Out
```
Traceback (most recent call last):
  File "/Users/kssion/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/Users/kssion/Desktop/ultralytics/ultralytics/engine/predictor.py", line 250, in stream_inference
    im = self.preprocess(im0s)
  File "/Users/kssion/Desktop/ultralytics/ultralytics/models/yolo/classify/predict.py", line 49, in preprocess
    [self.transforms(Image.fromarray(cv2.cvtColor(im, cv2.COLOR_BGR2RGB))) for im in img], dim=0
  File "/Users/kssion/Desktop/ultralytics/ultralytics/models/yolo/classify/predict.py", line 49, in <listcomp>
    [self.transforms(Image.fromarray(cv2.cvtColor(im, cv2.COLOR_BGR2RGB))) for im in img], dim=0
  File "/Users/kssion/miniconda3/envs/yolo/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
  File "/home/deeplearning/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/data/augment.py", line 1114, in __call__
AttributeError: 'Image' object has no attribute 'shape'
```

问题的原因在于输入的参数不兼容旧版本（<8.0.233）训练的模型。
在不重新训练的情况下，我如何将旧版本训练的模型转换为新版本？

详情如下：
`ultralytics/data/augment.py`
`Version：8.0.230`
<img width="916" alt="image" src="https://github.com/user-attachments/assets/815c32cd-6862-4d5a-9467-5569b8005486">

`ultralytics/models/yolo/classify/predict.py`
`Version：8.2.72`
<img width="930" alt="image" src="https://github.com/user-attachments/assets/56ceac2b-d8a7-43b6-8778-9fb6598ceadb">

**Comment by pderrenger** [comment]
Thank you for providing the detailed information. Given that you're using the latest version (8.2.72) and encountering issues with a model trained on version 8.0.230, it does seem like a backward compatibility issue. Unfortunately, there isn't a direct way to convert models trained on older versions to be fully compatible with the latest version without retraining. 

For now, the best approach would be to retrain your classification model using the latest version of Ultralytics. This should resolve the compatibility issues you're facing. If you continue to encounter problems, please let us know, and we'll investigate further.
