### ISSUE TITLE
Can the exported model have custom labels

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#9157]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Some label names are not needed and I want to remove them from the model. Can I customize the export model label names

For example, exporting onnx model custom label names

**Comment by glenn-jocher** [comment]
@monkeycc sure! When you export a YOLOv8 model, the labels are based on the classes the model is trained on. To modify these labels in the exported model, you can adjust the `names` list in your dataset's YAML file before training. For example:

```yaml
# coco128.yaml
...
names: ['person', 'bicycle', 'car']  # Your custom list of class names
```

When you export your model (e.g., to ONNX), it retains this custom class information:

```bash
yolo export model=yolov8n.pt format=onnx
```

After export, the model's recognition capabilities are aligned with the classes you defined. 😊 Let us know if you have more questions!

**Comment by monkeycc** [comment]
Unfortunately, it was not implemented
Still the original label name

**Comment by glenn-jocher** [comment]
@monkeycc hi there! It seems there might have been a misunderstanding regarding label customization for the exported model. 🤔 When exporting a YOLOv8 model, the labels correspond to the classes defined in your dataset YAML file during training. If you're looking to customize labels:

1. Before training, modify your dataset's YAML to include your custom labels:
```yaml
# example_dataset.yaml
...
names: ['custom_label_1', 'custom_label_2']
```
2. Train your model with this dataset.
3. Export your model:
```bash
yolo export model=your_trained_model.pt format=onnx
```

The resulting model should use the custom labels specified. If this doesn't work as expected, please ensure the dataset with custom labels was indeed used for training. Sometimes, a mix-up in configurations can lead to such issues. 

Hope this helps clear things up! Let me know if there's anything else I can assist with. 😊
