### ISSUE TITLE
tflite example does not work

### ISSUE THREAD

**Issue by ivanstepanovftw** [ultralytics/ultralytics#9159]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

`examples/YOLOv8-OpenCV-int8-tflite-Python/main.py`:
```python
scale, zero_point = input_details[0]["quantization"]
print(f'{input_details[0]["quantization"]=}')
interpreter.set_tensor(input_details[0]["index"], img_data)

# Run inference
interpreter.invoke()

# Get the output tensor from the interpreter
output = interpreter.get_tensor(output_details[0]["index"])
scale, zero_point = output_details[0]["quantization"]
print(f'{output_details[0]["quantization"]=}')
output = (output.astype(np.float32) - zero_point) * scale
```

output:
```
...
input_details[0]["quantization"]=(0.0, 0)
output_details[0]["quantization"]=(0.0, 0)
output=array([[[          0,           0,           0, ...,           0,           0,           0],
        [          0,           0,           0, ...,           0,           0,           0],
        [          0,           0,           0, ...,           0,           0,           0],
        [          0,           0,           0, ...,           0,           0,           0],
        [          0,           0,           0, ...,           0,           0,           0],
        [          0,           0,           0, ...,           0,           0,           0]]], dtype=float32)
```

No detections found.

Model is `best_saved_model/best_float16.tflite`.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ivanstepanovftw** [comment]
Hotfix for now:
```diff
-output = (output.astype(np.float32) - zero_point) * scale
+# output = (output.astype(np.float32) - zero_point) * scale
```

**Comment by ivanstepanovftw** [comment]
Also there is `if score > 0.25:`, I guess it should be removed entirely.

**Comment by ivanstepanovftw** [comment]
CC @wamiqraza

**Comment by wamiqraza** [comment]
> CC @wamiqraza

@ivanstepanovftw Thank you for highlighting it. With regards to the code that is for int8 and not float16, as can be seen in the readme, choose ``best_full_integer_quant`. With that being said, I will check if it can also be extended to `best_float16`, as you highlighted. Moreover, I will also check the second suggestion; if it is not relevant, I will update accordingly.
