### ISSUE TITLE
Unable to export YOLOv8 model to openvino format (with int8 quantization) when input shape is rectangular

### ISSUE THREAD

**Issue by camhpj** [ultralytics/ultralytics#9164]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

I trained a YOLO model (is a v9 model but I don't think that impacts this at all) and attempted to convert it to the `openvino` format using int8 quantization. This was done using the minimal reproducible example at the bottom of this post.

In `Exporter.export_openvino()` a `YOLODataset` instance is created and then used to created an `nnfc.Dataset`. When `nncf.quantize()` is called (line 484 in `exporter.py`) it leads to the error below. 

```
OpenVINO: export failure ❌ 9.1s: Exception from src/inference/src/cpp/infer_request.cpp:116:
Exception from src/inference/src/cpp/infer_request.cpp:66:
Exception from src/plugins/intel_cpu/src/infer_request.cpp:384:
Can't set the input tensor with name: x, because the model input (shape=[1,3,512,640]) and the tensor (shape=(1.3.512.512)) are incompatible
```

The core of this issue is that YOLODataset resizes images to a square shape. I was able to fix this by subclassing `YOLODataset` and overloading two functions as seen below and then replacing line 462 of `exporter.py` with `dataset = OpenvinoDataset(data["val"], data=data, imgsz=self.imgsz, augment=False)`.

The changes to the overloaded functions if they are not obvious are:
- `load_image()`
    - `rect_mode` default is set to `False`
    - The resize call that results when `rect_mode == False` is modified to use first and second value of self.imgsz
- `build_transforms()`
    - Instance of `Letterbox` is created using first and second value of self.imgsz
```
class OpenvinoDataset(YOLODataset):
    def __init__(self, *args, data=None, **kwargs):
        super().__init__(*args, data=data, **kwargs)

    def load_image(self, i, rect_mode=False):
        """Loads 1 image from dataset index 'i', returns (im, resized hw)."""
        im, f, fn = self.ims[i], self.im_files[i], self.npy_files[i]
        if im is None:  # not cached in RAM
            if fn.exists():  # load npy
                try:
                    im = np.load(fn)
                except Exception as e:
                    LOGGER.warning(f"{self.prefix}WARNING ⚠️ Removing corrupt *.npy image file {fn} due to: {e}")
                    Path(fn).unlink(missing_ok=True)
                    im = cv2.imread(f)  # BGR
            else:  # read image
                im = cv2.imread(f)  # BGR
            if im is None:
                raise FileNotFoundError(f"Image Not Found {f}")

            h0, w0 = im.shape[:2]  # orig hw
            if rect_mode:  # resize long side to imgsz while maintaining aspect ratio
                r = self.imgsz / max(h0, w0)  # ratio
                if r != 1:  # if sizes are not equal
                    w, h = (min(math.ceil(w0 * r), self.imgsz), min(math.ceil(h0 * r), self.imgsz))
                    im = cv2.resize(im, (w, h), interpolation=cv2.INTER_LINEAR)
            else:
                im = cv2.resize(im, (self.imgsz[0], self.imgsz[1]), interpolation=cv2.INTER_LINEAR)

            # Add to buffer if training with augmentations
            if self.augment:
                self.ims[i], self.im_hw0[i], self.im_hw[i] = im, (h0, w0), im.shape[:2]  # im, hw_original, hw_resized
                self.buffer.append(i)
                if len(self.buffer) >= self.max_buffer_length:
                    j = self.buffer.pop(0)
                    self.ims[j], self.im_hw0[j], self.im_hw[j] = None, None, None

            return im, (h0, w0), im.shape[:2]

        return self.ims[i], self.im_hw0[i], self.im_hw[i]

    def build_transforms(self, hyp=None):
        """Builds and appends transforms to the list."""
        if self.augment:
            hyp.mosaic = hyp.mosaic if self.augment and not self.rect else 0.0
            hyp.mixup = hyp.mixup if self.augment and not self.rect else 0.0
            transforms = v8_transforms(self, self.imgsz, hyp)
        else:
            transforms = Compose([LetterBox(new_shape=(self.imgsz[0], self.imgsz[1]), scaleup=False)])
        transforms.append(
            Format(
                bbox_format="xywh",
                normalize=True,
                return_mask=self.use_segments,
                return_keypoint=self.use_keypoints,
                return_obb=self.use_obb,
                batch_idx=True,
                mask_ratio=hyp.mask_ratio,
                mask_overlap=hyp.overlap_mask,
            )
        )
        return transforms
```

A regression test (computing Jaccard index) on my test set of images showed expected performance.

### Environment

```
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3070, 7959MiB)
Setup complete ✅ (20 CPUs, 31.3 GB RAM, 185.6/218.5 GB disk)

OS                  Linux-5.15.0-100-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             git
RAM                 31.26 GB
CPU                 Intel Core(TM) i9-10850K 3.60GHz
CUDA                12.1

matplotlib          ✅ 3.8.3>=3.3.0
opencv-python       ✅ 4.7.0.72>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.2.1>=1.8.0
torchvision         ✅ 0.17.1>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.1.4>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
```

### Minimal Reproducible Example

```
from ultralytics import YOLO

RUNS_DIR = /path/to/runs

run = 'baseline'
split = 'test'

model_path = f'{RUNS_DIR}/{run}/weights/best.pt'

model = YOLO(model_path, task='detect')
model.export(format='openvino', imgsz=[512, 640], **{'int8': True, 'data': '/path/to/data.yaml'})
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@camhpj thanks for the detailed issue report and your willingness to help by submitting a PR! Your investigation into the issue with exporting a model to OpenVINO with INT8 quantization and a rectangular input shape is much appreciated. 🙌

Your solution to subclass `YOLODataset` for compatibility with rectangular inputs and updating `exporter.py` appears sound. For those encountering a similar issue, you can utilize the approach described above to modify the dataset loader for the OpenVINO export process.

As you've already looked into the matter deeply, a contribution in the form of a PR would be fantastic. Your experience could greatly aid others facing similar challenges. When preparing your PR, kindly ensure that it can accommodate both square and rectangular input shapes dynamically, based on the model configuration.

Additionally, it might be beneficial to include an option or automatically detect the necessity of this adjustment during the export procedure, ensuring a smooth experience for all users regardless of their model format preferences.

Looking forward to your PR and extending our toolbox with this enhanced functionality! If you have any questions or need guidance during the process, feel free to reach out. Thanks again! 🚀

**Comment by pstephenwille** [comment]
I think I have the same basic problem.  
`values are sent as int, but the model was trained on float input. You would either need to make a change to the code or wait for frigate to support different input configurations`

https://github.com/blakeblackshear/frigate/discussions/12348

**Comment by glenn-jocher** [comment]
Hi @pstephenwille,

Thank you for your detailed report and for providing a potential solution! It seems like you've identified a key issue with the `YOLODataset` resizing images to a square shape, which conflicts with the rectangular input shape during the OpenVINO export with INT8 quantization.

Your approach to subclass `YOLODataset` and modify the `load_image` and `build_transforms` methods to handle rectangular shapes is a great workaround. Here's a brief summary for others who might encounter a similar issue:

1. **Subclass `YOLODataset`** to handle rectangular input shapes.
2. **Override `load_image` and `build_transforms` methods** to ensure images are resized correctly.
3. **Replace the dataset instantiation** in `exporter.py` with your custom dataset class.

For those looking to implement this, here's a snippet of the key changes:

```python
class OpenvinoDataset(YOLODataset):
    def load_image(self, i, rect_mode=False):
        # Custom implementation to handle rectangular shapes
        ...

    def build_transforms(self, hyp=None):
        # Custom implementation to handle rectangular shapes
        ...
```

Then, update `exporter.py` to use `OpenvinoDataset`:

```python
dataset = OpenvinoDataset(data["val"], data=data, imgsz=self.imgsz, augment=False)
```

If you haven't already, please ensure you're using the latest version of the Ultralytics packages to verify if the issue persists.

Feel free to submit a PR with your changes. Your contribution could greatly benefit the community! If you need any assistance during the process, don't hesitate to ask. 🚀
