### ISSUE TITLE
Segementation masks with cavities

### ISSUE THREAD

**Issue by anish2197** [ultralytics/ultralytics#917]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Dear authors,

Thank you for creating and maintaining such a valuable resource for the computer vision community.

I am currently working on instance segmentation in images and would like to know if it is possible to annotate masks with objects that have cavities (or holes) in them. Currently, the annotations are limited to the coordinates of the polygon nodes, but this may not accurately reflect the shape of objects with cavities.

For example, I have uploaded an image of a Printed Circuit Board (PCB) with a hole in the center. The hole is a crucial feature of the PCB and it is important to accurately annotate it in the mask.

![SEG_DVD_430_-_Printed_circuit_board-4276](https://user-images.githubusercontent.com/16228282/218122085-819f9c8c-def8-4e28-af85-acef964be885.jpg)

Any guidance or suggestions you could provide would be greatly appreciated.

Thank you again for your hard work and dedication.

Best regards.

**Comment by Laughing-q** [comment]
@anish2197 in my opinion I think it could be done, but it'll need more coordinates when labeling it to make the edge more smooth. Or probably you can use some traditional opencv function to make the edge more smooth first then use the labels to launch a training.

**Comment by dvagala** [comment]
@anish2197 to my knowledge it's even not possible to have a polygon with a hole inside with the current YOLO8 annotation specification. Did you somehow manage to make it happen?

It would be really cool to have option to use RLE anotations, or bitmap masks, but apparently only polygon notation is currently supported.

SImilar discussion #871

**Comment by ryouchinsa** [comment]
How about labeling a board and a hole separately using the polygon tool.
After training and predicting, you can subtract the hole mask from the board mask.

![スクリーンショット 2023-02-28 13 04 28](https://user-images.githubusercontent.com/1954306/221753477-e88adac0-6559-4be4-be5f-d519670f7b15.png)

If YOLOv5/v8 could support the RLE mask, you can label the board with hole using the pixels tool.

![スクリーンショット 2023-02-28 13 04 36](https://user-images.githubusercontent.com/1954306/221753511-070bfefa-9a38-46c5-81d6-83ee129c2ddb.png)

[RectLabel](https://rectlabel.com) is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can label polygons and pixels.

**Comment by pderrenger** [comment]
@ryouchinsa That's a great suggestion! Labeling the board and the hole separately using the polygon tool and then subtracting the hole mask from the board mask after predicting is a feasible approach. While YOLOv8 currently supports polygon annotations, you can indeed use external tools like RectLabel to label polygons and pixels, as well as to accomplish the subtraction process. However, as of now, RLE mask support is not available in YOLOv8.

Your input and suggestions are valuable, and we thank you for sharing your approach with the community. If you have any further questions or need assistance, feel free to ask!

**Comment by ryouchinsa** [comment]
We updated our [general_json2yolo.py](https://github.com/ryouchinsa/Rectlabel-support/blob/master/general_json2yolo.py) script so that the RLE mask with holes can be converted to the YOLO segmentation format correctly.
This script originates from Ultralytics [JSON2YOLO](https://github.com/ultralytics/JSON2YOLO) repository.
We hope this script would help your business.

The RLE mask.

![スクリーンショット 2023-11-22 1 57 52](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/df2dfad5-a13f-49c6-818a-8aba1d3ce83c)

The converted YOLO segmentation format.

![スクリーンショット 2023-11-22 2 11 14](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/cc34027a-075f-4b67-8de7-bd2dddddac59)

On [RectLabel](https://rectlabel.com), you have 2 options to label the polygon with holes.

Label the polygon with holes using Segment Anything models.

![hole_sam](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/8fc6646d-ca00-4fba-89b0-33f1872fd957)

Label the polygon and erase inside the polygon using the Erase polygon tool.

![hole_erase](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/31d4dd29-2d89-44f1-a6c3-f72624f65f53)

**Comment by glenn-jocher** [comment]
@ryouchinsa it's great to see contributions like yours that help bridge the gap between different annotation formats and YOLOv8's training capabilities. The updated `general_json2yolo.py` conversion script from your repository seems to facilitate users who have RLE mask annotations and wish to train their models using the YOLO segmentation format. It's a valuable tool for those needing to convert annotations with holes or complex shapes.

For those in the community who might find this relevant, you'll want to explore these conversion processes further if your project involves segmentation with detailed shape requirements like holes within objects.

While I can't comment on the external RectLabel tool's features in depth here in the YOLOv8 repo discussion, users who are interested in the capabilities you've described may consider exploring it.

Keep in mind, however, that external tools and scripts should be reviewed for compatibility and adherence to the licensing policies of both Ultralytics software and any other software you choose to use in conjunction with it.

Thank you for taking the time to share this information, and thank you for supporting the YOLOv8 community with practical tools and approaches. If there are any more questions or further points of discussion, the community and I are here to engage.

**Comment by ryouchinsa** [comment]
@glenn-jocher, we will make a PR about this script to your official repository. Please let us contribute to your official repository if this script would be useful for your company and users.

**Comment by glenn-jocher** [comment]
@ryouchinsa I appreciate your enthusiasm to contribute to the Ultralytics YOLOv8 project. It's always refreshing to see community members actively seeking to enhance the toolset for everyone's benefit. Your proposed script for converting RLE masks to YOLO segmentation format could be a valuable addition, especially for users dealing with complex annotation scenarios.

Please feel free to submit a PR with your script to the repository. The Ultralytics team and the community will review it. Such contributions undergo a thorough review process to ensure compatibility, effectiveness, and adherence to the project's structure and coding standards.

The involvement of community members like yourself is what makes open source projects thrive and evolve. Once again, thank you for your contribution and looking forward to seeing your PR! If you have further inquiries or need assistance, don't hesitate to ask.
