### ISSUE TITLE
Extra data printed in yolov8 training loop

### ISSUE THREAD

**Issue by MYahya18** [ultralytics/ultralytics#9173]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am training yolov8 for the object detection task. At the end of the training loop, I get some extra sort of printed detail on it. how can I stop it?
![image](https://github.com/ultralytics/ultralytics/assets/129146431/fdc2bbae-493b-4d1a-9fea-e7d5f615233b)

**Comment by glenn-jocher** [comment]
@yahya-ifiveo hello! 😊 It looks like you're encountering additional output details at the end of the training loop. By default, YOLOv8 provides a summary of the training process for evaluation and monitoring purposes. However, if you're looking to minimize this, you might consider adjusting the verbosity of your training session.

Please take a look at the training script or command you're using to start the training process. If you're using a Python script, ensure you're not setting any logger or verbosity parameters to high levels. Also, check if there's a specific argument to tweak the level of output details directly related to YOLOv8's training process. Currently, the standard YOLOv8 setup doesn't include a direct parameter to suppress these end-of-training summaries, but focusing on the logging configuration might help.

In the meantime, if the additional details are not hindering your training or evaluation process, they can provide insightful information regarding the performance and outcomes of your training session. 

Let us know how it goes, or if there's anything more specific you'd like to adjust! 🚀
