### ISSUE TITLE
Multiple calls, model automatically releases issues

### ISSUE THREAD

**Issue by jacksinofn** [ultralytics/ultralytics#9174]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have called the following method multiple times and found it to be very slow. The GPU memory repeatedly loads and unloads the model. How to keep the model in GPU memory

import sys
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8x.pt')  # pretrained YOLOv8n model

# Check if images are passed as command line arguments
if len(sys.argv) > 1:
    # Get the list of image paths from command line arguments
    image_paths = sys.argv[1:]

# Run batched inference on the list of images
results =  model(image_paths)  # return a list of Results objects

# Process results list
for result in results:
    print(result.tojson())

**Comment by glenn-jocher** [comment]
@jacksinofn hello! Thanks for bringing this to our attention. 😊 It seems like you're facing an issue with GPU memory management when repeatedly calling the model for inference. To maintain the model loaded in GPU memory and avoid reloading it multiple times, you can try initializing your model once and then call the `.predict()` method on your list of images. Here's a small adjustment to your code which should help:

```python
import sys
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8x.pt')  # pretrained YOLOv8 model

# Check if images are passed as command line arguments
if len(sys.argv) > 1:
    # Get the list of image paths from command line arguments
    image_paths = sys.argv[1:]

    # Run batched inference on the list of images
    results = model.predict(image_paths)  # advisable to use predict() for multiple images

    # Process and output results
    for result in results:
        print(result.tojson())

```
By using the `.predict()` method, your model stays loaded in GPU memory, effectively handling multiple inference calls without the need to reload it each time. If you're still encountering issues, feel free to reach out again!
