### ISSUE TITLE
 Issue Encountered: Dynamic Batch Size in YOLOv8x Model Export to .engine File

### ISSUE THREAD

**Issue by NakotiYashwanthraj** [ultralytics/ultralytics#9177]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey everyone,

I'm currently facing an issue while attempting to export a YOLOv8x model to a .engine file. My goal is to enable dynamic adjustment of batch size during inference, so I set the parameter dynamic=True during the export process. However, upon inference, the exported TensorRT model is throwing an input shape error:
Input size torch.Size([4, 3, 640, 640]) not equal to max model size (1, 3, 640, 640)

I've double-checked the configuration, and it seems that the input size is not aligning with the expected maximum model size. This discrepancy is causing the error during inference.

Any insights or suggestions on how to address this issue would be greatly appreciated.

Thanks!

### Additional

The Command that i have used to export:
yolo export model=yolov8x.pt format = engine device=0  dynamic =True half = Ture int8=True

Loding TRT engine and predection:
model= YOLO('yolov8x.engine',task='detect')

model.predict(batch)

The exported TensorRT model is throwing an input shape error:
Input size torch.Size([4, 3, 640, 640]) not equal to max model size (1, 3, 640, 640)

**Comment by glenn-jocher** [comment]
@NakotiYashwanthraj hello!

It looks like there's a slight misunderstanding regarding the use of the `dynamic=True` parameter during the export process. When setting `dynamic=True` for TensorRT engine export, it allows for variable input sizes in terms of width and height but not the batch size.

To address the error you're encountering, you have two options:

1. **Export with a fixed batch size:** If you know the batch size you'll primarily be using, you can export the model specifying that batch size. Unfortunately, after the export, the batch size is fixed and can't be changed during inference.

2. **Modify and recompile your TensorRT model:** You might be able to modify the TensorRT engine (after initial export) to support dynamic batch sizes using TensorRT's APIs, although this is advanced and outside the scope of simple export commands.

Currently, for varying the batch size dynamically at inference time without re-exporting the model, you might need to look into custom modifications on the TensorRT engine directly or explore other deployment options that natively support dynamic batching.

For the command you used, there's also a typo in `half = Ture` which should be `half=True`. 

Here is an adjusted version of your export command:
```bash
yolo export model=yolov8x.pt format=engine device=0 dynamic=True half=True int8=True
```
Please ensure there are no additional spaces around the equals sign in your commands.

Let me know if you have further questions or issues. We're here to help! 😊
