### ISSUE TITLE
multi gpu training closing signal SIGHUP

### ISSUE THREAD

**Issue by mehran66** [ultralytics/ultralytics#918]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I wanted to report an issue and its solution for training models using muti-gps. I have been getting the following error and noticed that the issue arrises as soon as I close the terminal, though I have been running the process in the background using `nohup`. the solution that works for me is to add `& disown` at the end of of the nohup command like this:

```nohup yolo task=segment mode=train model=yolov8x-seg.pt data=test.yaml epochs=300 imgsz=1152 batch=32 cache=True workers=20 mask_ratio=1 name='full_data_test' device=\'0,1,2,3,4,5,6,7\'   > ./runs/test.out & disown```

Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
     39/100      13.9G      2.252      3.897      2.851      1.791         48        768:  43%|████▎     | 496/1155 [05:07<06:48,  1.61it/s]WARNING:torch.distributed.elastic.agent.server.api:Received 1 death signal, shutting down workers
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4193 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4194 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4195 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4196 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4197 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4198 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4199 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4200 closing signal SIGHUP
Traceback (most recent call last):
  File "/opt/conda/envs/geopandas-env/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/geopandas-env/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/geopandas-env/lib/python3.10/site-packages/torch/distributed/run.py", line 766, in <module>
    main()
  File "/opt/conda/envs/geopandas-env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
...
FileNotFoundError: [Errno 2] No such file or directory: 'runs2/test/weights/best.pt'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@mehran66 hey I'm not sure this is a ultralytics-related issue, actually I've also encountered this issue while using another repo to launch DDP training...
`nohup` works properly to me before but this issue happens after I use a new server, so It's mroe like a linux-related or machine-related issue to me. 
I never have time to go deep for this but please let me know if you solve the issue. :)

**Comment by mehran66** [comment]
@Laughing-q that's been kind of the opposite for me...I've never had this issue with other DDP trainings like YoloV5 and 7 and my custom code...This issue only happens when running YoloV8 ddp training.

The solution for me has been using `& disown` at the end of `nohup` command.
