### ISSUE TITLE
Do you consider adding Faster RCNN and Cascade RCNN

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#9183]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

ultralytics as a universal framework
Do you consider adding Faster RCNN and Cascade RCNN

**Comment by glenn-jocher** [comment]
@monkeycc hello! 😊

Thanks for your interest in expanding the capabilities of the Ultralytics framework. At present, our focus is on optimizing and enhancing the YOLO architecture for real-time object detection and related computer vision tasks. Incorporating models like Faster RCNN and Cascade RCNN isn't in our immediate roadmap.

That said, we're always evaluating how we can improve and diversify the toolkit available to our users. Feel free to keep an eye on our [GitHub updates](https://github.com/ultralytics/ultralytics) or join the [discussions](https://github.com/ultralytics/ultralytics/discussions) for any future announcements regarding new model integrations.

Happy coding! 🚀
