### ISSUE TITLE
How to obtain the eigenvector of the target frame for cosine similarity calculation

### ISSUE THREAD

**Issue by MMa321** [ultralytics/ultralytics#9186]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I have a picture, I want to know how to use yolov8 video detection to detect whether the video contains the picture I provided. If I want to use cosine similarity for operation, how to do it? In addition, I used yolov8 to detect the bounding box, how can I get the feature vector to perform cosine similarity matching? Looking forward to your reply

**Comment by MMa321** [comment]
If I use the BoT-SORT tracker, how do I get the eigenvector

**Comment by glenn-jocher** [comment]
@MMa321 hello! To utilize the BoT-SORT tracker with YOLOv8 for obtaining eigenvectors (feature vectors) of detected objects, you can follow this intuitive approach:

1. **Detect and Track**: Use YOLOv8 with BoT-SORT to detect objects and track them across frames. The tracking implementation typically provides object IDs maintaining identity over different frames.

2. **Extract Features**: YOLOv8 does not natively output feature vectors for cosine similarity directly. For feature extraction, you might consider using an additional neural network specifically designed for generating feature vectors, such as an embedding or a recognition network trained on a relevant dataset.

3. **Match Features**: Once you have the feature vectors, calculate the cosine similarity between your target frame's feature vector and the vectors from video frames. Higher similarity scores indicate a match.

Here's a simplified code example on how you might approach feature extraction:

```python
from your_feature_extractor import FeatureExtractor
from ultralytics import YOLO

# Initialize YOLOv8 with BoT-SORT and your feature extractor
model = YOLO('yolov8n.pt', tracker='botsort.yaml')
feature_extractor = FeatureExtractor()

# Load your target image and extract its feature
target_feature = feature_extractor.extract('path/to/your/target_image.jpg')

for frame in video_frames:  # Assuming video_frames is a list of your video frames
    # Detect and track objects in the frame
    results = model(frame)
    
    # For each detected object in the frame
    for bbox in results.boxes:
        obj_img = crop_object_from_frame(frame, bbox)  # Define this function to crop the object based on bbox
        obj_feature = feature_extractor.extract(obj_img)
        
        # Calculate cosine similarity between target and object feature
        cosine_sim = calculate_cosine_similarity(target_feature, obj_feature)  # Define this function for the calculation
        
        if cosine_sim > threshold:  # Define an appropriate threshold value
            print("Target object found in frame!")
```

Remember, this is a highly simplified scenario. The specific details of cropping detected objects from frame (`crop_object_from_frame`) and calculating cosine similarity (`calculate_cosine_similarity`) depend on the additional packages/functions you choose to implement these functionalities.

Let me know if you need further clarification or assistance. Happy coding! 😊
