### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by oneprofittips** [ultralytics/ultralytics#9189]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

` CUDA out of memory. Tried to allocate 2.75 GiB. GPU 0 has a total capacity of 15.73 GiB of which 2.36 GiB is free. Process 1551 has 6.69 GiB memory in use. Including non-PyTorch memory, this process has 6.67 GiB memory in use. Of the allocated memory 5.31 GiB is allocated by PyTorch, and 19.78 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PITCH_CUDA_MALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)`

**Comment by oneprofittips** [comment]
Good afternoon. I run 2 perdictors in different processes on different models. How can I get away from this mistake? UBUNTU 22.04 system, GPU 1080 11Gb, batch size 100

**Comment by oneprofittips** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/34815812/528cb0ff-1705-4bfb-b907-00d5863cbd75)

**Comment by oneprofittips** [comment]
How can it be done if it took up all the memory, it did not fall, but it worked?

**Comment by glenn-jocher** [comment]
@oneprofittips hello!

Facing a CUDA out of memory error can indeed be frustrating, especially when running multiple predictors parallelly. 😓 Here are a couple of strategies to help mitigate this issue without your process falling over:

1. **Reduce Batch Size**: Although you're currently using a batch size of 100, reducing this size can significantly decrease memory usage. Consider experimenting with smaller batch sizes to find a good balance between memory usage and performance.
   
2. **Use torch.cuda.empty_cache()**: If you're working within a loop or between predictions, you can manually free up unused memory by calling `torch.cuda.empty_cache()`. This might help release memory that's not actively being used by your model but hasn't been cleared by the garbage collector.

3. **Dynamic Allocation**: Utilize PyTorch's support for dynamic memory allocation by setting the environment variable `PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:50`, for example. This configuration can help manage how the memory is allocated and may reduce fragmentation.

4. **Gradual Allocation**: Consider manually managing your GPU's memory by gradually increasing the batch size from a small number until you hit your upper limit. This can sometimes allow for better memory management.

5. **Subprocess Handling**: Ensure that each subprocess running a predictor is correctly cleaning up its GPU memory footprint after completion. This might involve manually moving tensors to CPU and freeing up GPU memory.

6. **Streamline Model and Data**: Ensure your model architecture and data pipeline are as efficient as possible. Extra data processing steps or oversized models can unnecessarily tie up GPU memory.

Unfortunately, there's no way to make the process "not fall" without ensuring that the memory usage does not exceed your GPU's capacity. The strategies above aim at preventing the out-of-memory situation from occurring in the first place. 

I hope this helps! If you continue to face issues, consider sharing more specifics about your implementation, and we might be able to offer more targeted advice. 🚀

**Comment by theB22B** [comment]
I also encountered the same problem. May I know how to solve it in the end

**Comment by glenn-jocher** [comment]
@theB22B hi there! 👋

To tackle the CUDA out of memory issue, you might try reducing your batch size first, as it's one of the most effective immediate solutions. For instance:

```python
model.train(data='coco128.yaml', epochs=100, imgsz=640, batch=16)  # Adjust the batch size here
```

Additionally, ensuring efficient cleanup after each prediction can help, like invoking `torch.cuda.empty_cache()` to free up unused memory. If your scenario involves running multiple models or processes, carefully manage the memory usage of each to avoid overlapping high memory demands.

I hope this helps! If you've tried these and still face issues, could you share more details about your setup? 😊
