### ISSUE TITLE
Custom Augmentations

### ISSUE THREAD

**Issue by omar-abdelgawad** [ultralytics/ultralytics#9192]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a transforms.Compose augmentation by Albumentations that I want to incorporate as the part of the augmentations during training. After reading the previous questions, I believe there is no easy way to incorporate augmentations by Albumentations that is not one of the few supported by ultralytics through the default.yaml file which contains all hyperparameters. If that is true, What is the best way to implement this feature? Should I write a custom trainer or custom Dataset/Dataloader? Which part should I tinker with in the package to add custom augmentations? 

### Additional

First I want to mention that I did search the YOLOv8 issues and discussions and did find similar questions. However, I didn't find the answers appropriate for my needs.

**Comment by glenn-jocher** [comment]
@omar-abdelgawad hello! 👋 Thank you for your question regarding the integration of custom Albumentations augmentations into the YOLOv8 training process. You're correct that currently, the integration of custom augmentation libraries such as Albumentations isn't directly supported through the `default.yaml` configuration file.

To incorporate your custom augmentations, adjusting the Dataset/Dataloader would be the most straightforward approach. This allows you to apply your augmentations right at the point where images are loaded and preprocessed for training.

Here is a simple example to give you an idea:

```python
from torch.utils.data import Dataset
import albumentations as A
from albumentations.pytorch import ToTensorV2

class CustomDataset(Dataset):
    def __init__(self, ...):  # your initialization, including paths to images
        self.augment = A.Compose([
            # your Albumentations augmentations here
            A.RandomCrop(width=450, height=450),
            A.HorizontalFlip(p=0.5),
            A.RandomBrightnessContrast(p=0.2),
            ToTensorV2(),
        ])
    
    def __getitem__(self, index):
        # logic to load your image
        image = ...  # your code to load an image as a numpy array

        # Apply augmentations
        augmented = self.augment(image=image)
        image = augmented['image']

        # your code to handle annotations
        # return your image and labels here
        return image, ...

# Remember to replace the dataset part in your training code
# dataset = CustomDataset(...)
```

By leveraging a custom dataset class as shown, you maintain the flexibility to incorporate any data augmentation or manipulation strategy you need, including those from Albumentations.

For further customization or specific integration challenges, you might want to delve into the codebase, specifically looking into the data loading and preprocessing segments where datasets are handled.

I hope this helps guide you in the right direction! If you have more detailed needs or run into specific issues, feel free to share more details. Happy coding! 😊

**Comment by MaxPolak97** [comment]
I have a question related to implementing custom augmentations using Albumentations, similar to an issue previously discussed. In the augment.py file (see image below), the augmentations are predefined, and the function doesn't provide an option to modify or replace these augmentations directly. Is there an alternative method to define and use custom augmentations without the need to clone the repository or store the augmented images locally?

![image](https://github.com/ultralytics/ultralytics/assets/87903719/aad3df29-035f-4a29-9d56-69df89344093)

**Comment by glenn-jocher** [comment]
@MaxPolak97 hey there! 😊 To integrate custom Albumentations augmentations into your YOLOv8 workflow without directly modifying the `augment.py`, you can utilize a custom Dataset class.

Here's a quick example:

```python
import cv2
from torch.utils.data import Dataset
import albumentations as A
from albumentations.pytorch.transforms import ToTensorV2

class CustomDataset(Dataset):
    def __init__(self, image_paths):
        self.image_paths = image_paths
        self.augment = A.Compose([
            # Add your custom augmentations here
            A.Flip(),
            A.RandomRotate90(),
            ToTensorV2()
        ])

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        # Apply augmentations
        augmented = self.augment(image=image)
        image = augmented['image']

        # Return image tensor and whatever other information you need (e.g., labels)
        return image
```

You then substitute this `CustomDataset` for the default dataset loader in your training script. This way, you can enjoy the flexibility of Albumentations or any other data-augmentation library without altering the core YOLOv8 files or storing augmented images. It keeps your workflow clean and adheres to the principle of keeping the original source code unchanged. 🚀

I hope this guides you well! If more questions or specifics arise, feel free to ask. Happy coding!

**Comment by ternaus** [comment]
I am not familiar with Ultralytics, but if someone will point me to the documentation on how to train models:
- classification
- detection
- segmentation
etc 

with Ultalytics with Custom Dataset I will implement examples, write tutorials and add them to https://albumentations.ai/docs

And hopefully, we could work with @glenn-jocher to add something similar to the documentation of Ultralitics.

**Comment by glenn-jocher** [comment]
@ternaus hey there! 😊 We really appreciate your enthusiasm and willingness to contribute to both the Albumentations and Ultralytics communities! For training models with custom datasets using Ultralytics YOLOv8, the starting point would be our comprehensive documentation and tutorials available [here](https://docs.ultralytics.com/). 

For a quick start, here's a brief example of how you might setup training with a custom dataset for detection tasks:

```python
from ultralytics import YOLO  # Import YOLO class

# Load a YOLOv8 model
model = YOLO('yolov8n.yaml', device='cuda')  

# Train the model on your custom dataset
results = model.train(data='custom_dataset.yaml', epochs=100, imgsz=640)
```

Your `custom_dataset.yaml` should look something like this, tailored to where your dataset is stored:

```yaml
train: /path/to/your/train/images
val: /path/to/your/val/images

# Classes
nc: 20  # Number of classes
names: ['class1', 'class2', ...]  # Class names
```

This is a very simplified example, but it should give you a good jumping off point. Each task (classification, detection, segmentation) would follow a similar pattern, with configuration and setup detailed in our documentation.

We're thrilled about the idea of collaborating on tutorials or examples that bridge Ultralytics and Albumentations. Let's make it happen! 😄 Feel free to reach out directly or via GitHub to discuss this further.

And thanks for reaching out – looking forward to what we can accomplish together! 🚀

**Comment by ternaus** [comment]
Thanks!

Actually I wanted to ask on how to create a Custom Dataloader? Could you please share a link? :)

As it is where I would like to add preprocessing with Albumentations and show it's power in the application to image + mask + bounding boxes + keypoints.

**Comment by glenn-jocher** [comment]
@ternaus hey there! 😊 Great to hear about your interest in enhancing your data loading process with Albumentations!

Creating a custom DataLoader in PyTorch (which Ultralytics YOLOv8 utilizes) involves defining your dataset by subclassing `torch.utils.data.Dataset` and using `torch.utils.data.DataLoader` to load the data. Below is a simplified example tailored for images, where you could include Albumentations for preprocessing:

```python
import torch
from torch.utils.data import DataLoader, Dataset
import cv2
from albumentations.pytorch import ToTensorV2
import albumentations as A

class CustomDataset(Dataset):
    def __init__(self, image_paths, transforms=None):
        self.image_paths = image_paths
        self.transforms = transforms

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        image = cv2.imread(img_path)
        if self.transforms:
            augmented = self.transforms(image=image)
            image = augmented['image']
        return image

transforms = A.Compose([
    # Your Albumentations augmentations here
    A.RandomCrop(width=450, height=450),
    A.HorizontalFlip(p=0.5),
    ToTensorV2(),
])

# Assuming you have a list of image paths
image_paths = ['/path/to/image1.jpg', '/path/to/image2.jpg']
dataset = CustomDataset(image_paths, transforms=transforms)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

# Now you can loop through the dataloader
#for images in dataloader:
    # Process batches
```

This is just a starting point! You can customize your `CustomDataset` further to load masks, bounding boxes, keypoints, etc., and apply Albumentations transformations accordingly.

For in-depth guidance on PyTorch datasets and dataloaders, the official [PyTorch documentation](https://pytorch.org/docs/stable/data.html#) is a fantastic resource.

Hope this helps set you on the right path! If you have more questions or need further clarification, feel free to ask. Happy coding! 🚀

**Comment by glenn-jocher** [comment]
Hey @ternaus! 👋

To inject a custom dataset into the Ultralytics YOLOv8 pipeline, you'll indeed need to customize the data loader. Here’s a simple example to help you integrate a custom dataset that includes images, bounding boxes, and keypoints:

```python
from ultralytics import YOLO, Dataset

class CustomDataset(Dataset):
    def __getitem__(self, idx):
        # Load your data here (images, boxes, keypoints)
        image, boxes, keypoints = your_data_loading_function(idx)
        
        # Apply any specific transformations or preprocessing
        image, boxes, keypoints = your_preprocess(image, boxes, keypoints)
        
        # Normalize and return
        return {'img': image, 'labels': boxes, 'keypoints': keypoints}

# Initialize YOLO model
model = YOLO('yolov8n.yaml')

# Replace the default dataset with your custom dataset
model.dataset = CustomDataset()

# Train the model
model.train()
```

In this setup:
- `__getitem__` should return a dictionary with keys `'img'`, `'labels'`, and `'keypoints'`, where:
  - `'img'` is a normalized image tensor,
  - `'labels'` are the bounding boxes, typically normalized to `[class, x_center, y_center, width, height]` format,
  - `'keypoints'` are the keypoints, if applicable, formatted similarly to bounding boxes.

For image normalization, it's common to scale pixel values to `[0, 1]` by dividing by 255.

This should get you started on integrating custom datasets with different types of annotations into the YOLOv8 training pipeline. For more details, definitely check out the [documentation](https://docs.ultralytics.com/usage/engine/#customizing-the-detectiontrainer) or reach out if you need further clarification! 🚀

**Comment by ternaus** [comment]
@glenn-jocher 

Could you please answering yourself, without delegating answers to LLMs. They are not good enough to replace you and your knowledge of the package.

```python
from ultralytics import YOLO, Dataset
```

Does not work. 

```python
In [1]: import ultralytics
^[[
In [2]: ultralytics.__version__
Out[2]: '8.2.19'

In [3]: from ultralytics import YOLO, Dataset
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[3], line 1
----> 1 from ultralytics import YOLO, Dataset

ImportError: cannot import name 'Dataset' from 'ultralytics' (/Users/vladimiriglovikov/anaconda3/envs/ultralytics/lib/python3.8/site-packages/ultralytics/__init__.py)
```

**Comment by glenn-jocher** [comment]
Hey @ternaus,

Thanks for reaching out! It looks like there's a slight misunderstanding in the import statement. In the current YOLOv8 setup, `YOLO` and `Dataset` classes are not directly importable from the `ultralytics` namespace. Instead, you should import `YOLO` from `ultralytics.yolov8` and use the appropriate dataset class for your task. Here’s how you can do it:

```python
from ultralytics.yolov8 import YOLO  # Correct import for YOLO
# For datasets, you might need to use specific classes or create your own.
```

If you're looking to use a custom dataset, you'd typically subclass from a base dataset class provided in the documentation or examples. Make sure to check the latest docs or examples in the repo for the most accurate guidance!

Let me know if this helps or if you have any more questions! 😊

**Comment by ternaus** [comment]
@Andredance Thanks.

Is it similar to how they describe in docs?

https://docs.ultralytics.com/integrations/albumentations/

**Comment by Andredance** [comment]
@ternaus It is not. In the docs, they describe a little bit of how good the library is and add some examples with images. But there is no way to configure them without downloading the whole repo and changing the source code. They define augs as:
```
 T = [
                A.Blur(p=0.01),
                A.MedianBlur(p=0.01),
                A.ToGray(p=0.01),
                A.CLAHE(p=0.01),
                A.RandomBrightnessContrast(p=0.0),
                A.RandomGamma(p=0.0),
                A.ImageCompression(quality_range=(75, 100), p=0.0),
            ]
```
With very low probabilities (sure, there is a reason for it). But if you want to train with custom augs and without changes in source code - you will need to do something similar to what I did above (at least I didn't find a better solution)
You can understand it better by looking at this class implementation https://github.com/ultralytics/ultralytics/blob/d79a7332db43d341c9fd1b1cec0de4596365ea07/ultralytics/data/augment.py#L1737

**Comment by ternaus** [comment]
@Andredance If you could provide jupyter notebook / google collab that shows how albumentations could be used with Ultralytics, will be happy to add this to docs of Albumentations with credit to your authorship.
