### ISSUE TITLE
Tracker Generates New IDs for Same Object

### ISSUE THREAD

**Issue by userkw** [ultralytics/ultralytics#9197]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I am using the provided tracker with YOLOv8, and I'm encountering an issue where the tracker generates new IDs for the same object, even when it briefly disappears and reappears in the video. This behavior is not desirable, as it leads to incorrect tracking.

Upon investigating the code and YAML configuration provided, it seems that the tracker's behavior is not considering the continuity of the object across frames. Instead, it treats the re-detected object as a new track and assigns it a new ID.

I expect the tracker to maintain the same ID for an object unless it disappears for a certain number of frames (e.g., 7 frames consecutively). This would ensure more consistent tracking behavior and avoid unnecessary ID changes for the same object.

**YAML Configuration**:
```yaml
# Ultralytics YOLO 🚀, AGPL-3.0 license
# Default YOLO tracker settings for ByteTrack tracker https://github.com/ifzhang/ByteTrack

tracker_type: bytetrack # tracker type, ['botsort', 'bytetrack']
track_high_thresh: 0.5 # threshold for the first association
track_low_thresh: 0.1 # threshold for the second association
new_track_thresh: 0.7 # threshold for init new track if the detection does not match any tracks
track_buffer: 60 # buffer to calculate the time when to remove tracks
match_thresh: 0.9 # threshold for matching tracks
# min_box_area: 10  # threshold for min box areas(for tracker evaluation, not used for now)
# mot20: False  # for tracker evaluation(not used for now)

### Environment

_No response_

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Burhan-Q** [comment]
You must use `persist=True` when using the `track()` method. See the [examples in the docs](https://docs.ultralytics.com/modes/track/#python-examples)

**Comment by userkw** [comment]
@Burhan-Q Does ByteTrack not work like Deep SORT in terms of parameters? I didn't see 'n_init' to control the tracker to assign a new ID to the same object. Is there another way?

**Comment by Burhan-Q** [comment]
These are the active parameters for each tracker.

https://github.com/ultralytics/ultralytics/blob/8617fcf32d36a798a24631c4d495a3fcfc456145/ultralytics/cfg/trackers/botsort.yaml#L4-L9

https://github.com/ultralytics/ultralytics/blob/8617fcf32d36a798a24631c4d495a3fcfc456145/ultralytics/cfg/trackers/bytetrack.yaml#L4-L9

The tracker assigns new IDs based on the logic written, which I honestly am not very familiar with. You can browse the [code here](https://github.com/ultralytics/ultralytics/tree/main/ultralytics/trackers). If iterating frames, you use `model.track(frame, tracker="tracker.yaml")` a new ID will be assigned to all detections, if you instead use `model.track(frame, persist=True, tracker="tracker.yaml")` then the code will re-assign the same ID to objects detected based on the configurations. The same goes for when using `model.track("video.mp4", tracker="tracker.yaml")` vs `model.track("video.mp4", persist=True, tracker="tracker.yaml")`
