### ISSUE TITLE
How to update code to save yolov8 prediction Boxes instead of raw camera feed.

### ISSUE THREAD

**Issue by Nicknick203** [ultralytics/ultralytics#9205]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thankyou for your help! I was able to get images to save only when a person is detected. I do have another question, I want to be able to view a camera feed with yolov8 prediction boxes while the program is running and I would like to be able to view the prediction boxes around the saved image frames. Currently it just displayes the raw camera feed and saves raw images without prediction boxes when I run the program. Could you help me to update my code in order to have a pop up window with yolov8 prediction boxes and saves the frames with prediction boxes around them?

Here is my current code.

from ultralytics import YOLO
import cv2
import os
import time

def save_detected_frames(source=0, save_dir="C:\Users\Nick\Desktop\Detected frames", max_images=float('inf')):
model = YOLO("yolov8n.pt")
cap = cv2.VideoCapture(source)

if not os.path.exists(save_dir):
    os.makedirs(save_dir)
    print(f"Created directory: {save_dir}")

detected_frame_count = 0

last_capture_time = time.time()

while True:
    ret, frame = cap.read()
    if not ret:
        break

    results = model.predict(frame)
    # Check for person detection (class_id for person usually is 0)
    if any(x.cls == 0 for x in results[0].boxes):
        # Only capture an image once every second
        current_time = time.time()
        if current_time - last_capture_time >= 1:
            # Construct filename with format detected_frame_<frame_number>.jpg
            filename = f"{save_dir}\\detected_frame_{detected_frame_count}.jpg"
            cv2.imwrite(filename, frame)
            print(f"Frame saved to {filename}")
            
            detected_frame_count += 1
            last_capture_time = current_time
        
        # Break the loop if the maximum number of images has been reached
        if detected_frame_count >= max_images:
            break
    
    # Display camera feed
    cv2.imshow('Camera Feed', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break  # Break the loop if 'q' is pressed

cap.release()
cv2.destroyAllWindows()

save_detected_frames()

### Additional

Previous thread for context:

@Nicknick203 hello there! 👋 Saving captured frames when a person is detected can definitely be managed with the YOLOv8 model. Here’s a concise way to save images from your webcam video feed when a person is detected:

from ultralytics import YOLO
import cv2

def save_detected_frames(source=0, save_dir="detected_frames"):
    model = YOLO("yolov8n.pt")
    cap = cv2.VideoCapture(source)
    
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        
        results = model.predict(frame)
        # Check for person detection (class_id for person usually is 0)
        if any(x.cls == 0 for x in results[0].boxes):
            # Construct filename with format detected_frame_<frame_number>.jpg
            filename = f"{save_dir}/detected_frame_{cap.get(cv2.CAP_PROP_POS_FRAMES):.0f}.jpg"
            cv2.imwrite(filename, frame)
            print(f"Frame saved to {filename}")

save_detected_frames()

Make sure that the save_dir exists before running the script or add code to create it if it doesn't. This script checks every frame for a person, and when it finds one, it saves the frame to the specified folder.

Feel free to adjust the model.predict arguments, and ensure your yolov8n.pt model is correctly pathed. Let me know if this helps or if you have further questions. Happy coding! 🚀

**Comment by glenn-jocher** [comment]
@Nicknick203 hey there! 😊 It's awesome to hear you've made progress with detecting and saving images. To display and save frames with YOLOv8 prediction boxes, you'll need to modify the part where you handle results from `model.predict()` and use the `results.plot()` method. Here's an updated snippet from your code:

```python
while True:
    ret, frame = cap.read()
    if not ret:
        break

    results = model.predict(frame)
    if any(x.cls == 0 for x in results[0].boxes):
        current_time = time.time()
        if current_time - last_capture_time >= 1:
            filename = f"{save_dir}\\detected_frame_{detected_frame_count}.jpg"
            # Use results.plot() to draw the prediction boxes on the frame
            annotated_frame = results[0].plot()
            # Save the annotated frame instead of the original frame
            cv2.imwrite(filename, annotated_frame[..., ::-1])  # Convert RGB (matplotlib) to BGR (OpenCV)
            print(f"Frame saved to {filename}")
            detected_frame_count += 1
            last_capture_time = current_time

        if detected_frame_count >= max_images:
            break
    
    # Show the annotated frame in the 'Camera Feed' window
    cv2.imshow('Camera Feed', results[0].plot()[..., ::-1])  # Convert RGB to BGR
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
```

This update uses `results.plot()` to generate annotated frames with detection boxes, which are then both displayed and saved. Remember, `plot()` returns an RGB image, so use `[..., ::-1]` to convert it to BGR format for OpenCV to display or save correctly.

Let me know if this helps or if there's anything else I can assist you with. Keep up the good work! 🚀
