### ISSUE TITLE
how to output the best value

### ISSUE THREAD

**Issue by binn77** [ultralytics/ultralytics#921]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to output the best value?
cat 0.75

image 1/1 C:\temp\cat\DC0188DA1FE4CEDF9BFDEA9FE8FF577C.jpg: 128x128 **cat 0.75**, dog 0.25, 8.9ms
Speed: 0.0ms pre-process, 8.9ms inference, 0.0ms postprocess per image at shape (1, 3, 128, 128)

```
from ultralytics import YOLO
model = YOLO("C:/temp/1.pt")
results = model("C:\temp\cat\DC0188DA1FE4CEDF9BFDEA9FE8FF577C.jpg")
```

**Comment by glenn-jocher** [comment]
The best value for object detection in this example would be the highest confidence score among the detected classes. In this case, the object detected is a cat with a confidence score of 0.75. So the output for the best value in this case would be "cat 0.75".

**Comment by binn77** [comment]
> The best value for object detection in this example would be the highest confidence score among the detected classes. In this case, the object detected is a cat with a confidence score of 0.75. So the output for the best value in this case would be "cat 0.75".

You misunderstood my question, I need to output only the best result from the entire log, i.e. **cat 0.75**

Now I'm pulling out these values using regex.

**Comment by pderrenger** [comment]
@binn77 i see, my apologies for the misunderstanding. If you're using regex to extract the best result from the entire log, then you can look for the line that contains the highest confidence score and extract that line as the best result. In this case, the line "cat 0.75, dog 0.25, 8.9ms" contains the highest confidence score for the cat class, so extracting that line using regex would provide the best result "cat 0.75".
