### ISSUE TITLE
How to store the tracked objects and their particular frequency into a sqlite database 

### ISSUE THREAD

**Issue by anishka07** [ultralytics/ultralytics#9214]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

So I figured out a way to store the data (class_id, class_name, confidence etc.) into a sqlite database but i dont think that this is an ideal way to store the data into a database as when you query and filter out the data based on certain timestamps, it gives me the total sum of the classes and their respective frequencies.
LIke this:
`Table created and connection established successfully!
Class name  car
Frequency  7830
Class name  motorcycle
Frequency  4234
Class name  person
Frequency  17841
`
I want a way to store the data shown in the terminal
Like this one:
`0: 384x640 18 persons, 7 cars, 3 motorcycles, 1001.8ms
Speed: 3.3ms preprocess, 1001.8ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 19 persons, 7 cars, 4 motorcycles, 981.4ms
Speed: 3.9ms preprocess, 981.4ms inference, 2.2ms postprocess per image at shape (1, 3, 384, 640)
`
into the database, so that when i run a query on the database, I can get the actual number of classes and their respective frequencies and not some absurd number.
This is the code:
`    def insert_values(self, classes, conf=0.5):
        obj_track_dict = self.trackable_dict
        while self.cap.isOpened():
            ret, frame = self.cap.read()
            if not ret:
                break
            results = self.model([frame], classes=self.get_indices(classes))
            for result in results:
                boxes = result.boxes.cpu().numpy()
                for i, box in enumerate(boxes.xyxy):
                    video_timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                    bbox = [int(x) for x in box]
                    bbox_str = ','.join(map(str, bbox))
                    confidence = round(float(boxes.conf[i]), 2)
                    class_id = int(boxes.cls[i])
                    class_name = str(obj_track_dict[class_id])
                    self.cursor.execute(f"""
                    insert into {self.table_name} (video_timestamp, bbox, confidence, class_id, class_name) values
                    (?, ?, ?, ?, ?);
                    """, (video_timestamp, bbox_str, confidence, class_id, class_name))
            self.conn.commit()

    def filter_results(self, start_timestamp: str, end_timestamp: str):
        try:
            conn = sqlite3.connect(Settings.DB_NAME)
            cursor = conn.cursor()
            query = f"""
            select class_name, count(*) as frequnecy from {self.table_name}
            where video_timestamp between ? and ?
            group by class_name;
            """
            cursor.execute(query, (start_timestamp, end_timestamp))
            rows = cursor.fetchall()
            for item in rows:
                class_name, freq = item
                print("Class name ", class_name)
                print("Frequency ", freq)
        except sqlite3.Error as e:
            print("Error: ", e)`
Thank you!

**Comment by glenn-jocher** [comment]
@anishka07 hey there! 👋 It looks like you've made great progress with integrating tracking data into SQLite, nice job!

For storing the data in the format you described while avoiding inflated counts, you might consider logging each detection instance separately, rather than updating counts directly in the database. This way, you log every occurrence of a class detection and can later aggregate these records based on timestamps or other criteria right in your query. 

Here's a simplified version of adjusting your `insert_values` function to log every detection:

```python
def insert_values(self, classes, conf=0.5):
    while self.cap.isOpened():
        ret, frame = self.cap.read()
        if not ret:
            break
        results = self.model([frame], classes=self.get_indices(classes))
        video_timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        for result in results:
            detections = zip(result.boxes.cls, result.boxes.conf)  # Example: [('car', 0.95), ...]
            for class_id, confidence in detections:
                class_name = self.trackable_dict.get(class_id, "Unknown")
                self.cursor.execute(f"""
                INSERT INTO {self.table_name} (video_timestamp, class_id, class_name, confidence) VALUES
                (?, ?, ?, ?);
                """, (video_timestamp, class_id, class_name, confidence))
        self.conn.commit()
```

When you run your query to get the frequency, it should now reflect the actual number of detections without aggregation issues as you're dealing with discrete records.

For your `filter_results` function, ensure your query selects counts by grouping over both `class_name` and a suitable time bucket if you want more granular control over the time intervals. That would give you the flexibility to analyze the frequency of detections over any period.

Hope this helps! Let us know if you have any further questions. Keep up the great work! 🚀

**Comment by anishka07** [comment]
@glenn-jocher  how can I insert these values on a database ? can you plase provide me with the code snippet?

**Comment by glenn-jocher** [comment]
@anishka07 hi there! 😊 Sure, I'd be happy to help you with a basic example of how to insert values into a SQLite database. If you're tracking objects with YOLOv8 and want to insert the tracking information into a database, here's a simple Python snippet:

```python
import sqlite3

# Connect to your SQLite database (or create it if it doesn't exist)
conn = sqlite3.connect('tracking_data.db')
cursor = conn.cursor()

# Create a table (do this once)
cursor.execute('''CREATE TABLE IF NOT EXISTS tracking
              (timestamp TEXT, class_id INT, class_name TEXT, confidence REAL)''')

# Example data to insert
timestamp = '2023-04-01 12:00:00'
class_id = 1
class_name = 'person'
confidence = 0.98

# Insert a row of data
cursor.execute("INSERT INTO tracking VALUES (?, ?, ?, ?)", (timestamp, class_id, class_name, confidence))

# Save (commit) the changes
conn.commit()

# Close the connection when done
conn.close()
```

This snippet demonstrates how to connect to a SQLite database, create a table, and insert a single row of data. You'll need to adapt the insert part to loop through your YOLO results.

Hope this helps! Feel free to reach out if you have more questions. 🚀
