### ISSUE TITLE
Support multi-label nms in CoreML export

### ISSUE THREAD

**Issue by jameslahm** [ultralytics/ultralytics#9219]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

It seems that the coreml export of yolov8 now supports class-aware single-label nms by default. However, when validating the performance on COCO, multi-label nms is used. Is there any way to export yolov8 in coreml with multi-label nms? Thank you!

**Comment by glenn-jocher** [comment]
@jameslahm hello! Thanks for reaching out with your question. 🌟

Currently, the CoreML export of YOLOv8 is set up to support class-aware single-label NMS by default, as you've noted. For exporting with multi-label NMS, a custom implementation would be needed after the model is converted to CoreML format. This involves modifying the CoreML model to handle multi-label NMS, which might require manual coding and manipulation of the CoreML model layers.

While we do not provide an out-of-the-box solution for multi-label NMS in CoreML at the moment, your interest is definitely noted for our roadmap! For now, you may need to employ post-processing scripts externally to achieve multi-label NMS functionality.

Keep an eye on our updates; we're always working on enhancing the capabilities of our models! If you have further technical queries or need assistance, feel free to continue the discussion here. 

Happy coding! 🚀
