### ISSUE TITLE
How to disable the output of this information?

### ISSUE THREAD

**Issue by binn77** [ultralytics/ultralytics#922]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to disable the output of this information?
![Screenshot](https://user-images.githubusercontent.com/97234755/218136293-232f91ef-9088-4878-be05-39ef4e79b252.png)

**Comment by glenn-jocher** [comment]
@binn77 starting in `ultralytics>=8.0.46` you can completely disable the YOLO logger by settings the YOLO_VERBOSE environment variable to false, i.e.

```bash
export YOLO_VERBOSE=false
yolo predict
```
