### ISSUE TITLE
[YOLO World] Loading CLIP during `set_classes` makes changing labels slow

### ISSUE THREAD

**Issue by rxavier** [ultralytics/ultralytics#9227]
Because CLIP is loaded when calling `set_clases`, changing target labels takes multiple seconds. Is there a reason why the CLIP requirements check and model loading are not handled during `__init__` and saved to an attribute?

In my use case the labels are set dynamically by the client, so each request might require calling `set_classes`.

[Relevant code](https://github.com/ultralytics/ultralytics/blob/8617fcf32d36a798a24631c4d495a3fcfc456145/ultralytics/nn/tasks.py#L574)

**Comment by glenn-jocher** [comment]
@rxavier thanks for the feedback, super useful info. I'll see if there's an update we can do to address this, probably still loading CLIP on demand but then assigning to an attribute to avoid re-loading for subsequent class changes.

**Comment by glenn-jocher** [comment]
@rxavier should be resolved now in https://github.com/ultralytics/ultralytics/pull/9235/commits/17116450d1e3fe583ae552057c38c45138ccb935, though this does also mean that the YOLO World models will use more steady state CUDA memory or RAM as the CLIP model will remain in memory.

**Comment by rxavier** [comment]
Thank you so much @glenn-jocher! That was super fast. I think the memory compromise is reasonable for the flexibility.

One option could be adding some kind of "fuse" method that effectively locks the text features to a set of classes and deletes the CLIP attribute.

**Comment by rxavier** [comment]
@glenn-jocher I tried running YOLO World on Colab after installing 8.1.31. I noticed that if I initialized the class with the .pt files it failed saying that. `WorldModel`does not have a `clip_model` attr.

```
Downloading https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8s-world.pt to 'yolov8s-world.pt'...
100%|██████████| 25.9M/25.9M [00:00<00:00, 226MB/s]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-5-2916ca1afe45>](https://localhost:8080/#) in <cell line: 5>()
      3 # Initialize a YOLO-World model
      4 model = YOLOWorld('yolov8s-world.pt')  # or choose yolov8m/l-world.pt
----> 5 model.set_classes(["person", "bus"])
      6 # Define custom classes

2 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/model.py](https://localhost:8080/#) in set_classes(self, classes)
     94             classes (List(str)): A list of categories i.e ["person"].
     95         """
---> 96         self.model.set_classes(classes)
     97         # Remove background if it's given
     98         background = " "

[/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py](https://localhost:8080/#) in set_classes(self, text)
    573             import clip
    574 
--> 575         if not self.clip_model:
    576             self.clip_model = clip.load("ViT-B/32")[0]
    577         device = next(self.clip_model.parameters()).device

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in __getattr__(self, name)
   1686             if name in modules:
   1687                 return modules[name]
-> 1688         raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
   1689 
   1690     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'WorldModel' object has no attribute 'clip_model'
```

If I initialized with the .yaml it worked as expected, and inference was fast as CLIP was not reloaded. Could it be that it's downloading the checkpoint from the 8.1.0 release?

**Comment by rxavier** [comment]
I see this was fixed in https://github.com/ultralytics/ultralytics/pull/9253, I'll test and comment here.

**Comment by Burhan-Q** [comment]
New CI tests also added in #9253 and all CI tests showing as passing.

**Comment by rxavier** [comment]
Yep, working great!

**Comment by glenn-jocher** [comment]
@rxavier fantastic to hear that! 😊 If you have any more queries or need further assistance, feel free to reach out. Happy coding!
