### ISSUE TITLE
cli command vs python

### ISSUE THREAD

**Issue by alicera** [ultralytics/ultralytics#923]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

https://docs.ultralytics.com/cli/
https://github.com/ultralytics/yolov5/issues/475

Can I direct use the v8/train.py to train?
like this
```
$ python -m torch.distributed.run --nproc_per_node 2 train.py --batch 64 --data coco.yaml --weights yolov5s.pt --device 0,1

```

**Comment by glenn-jocher** [comment]
@alicera the equivalent YOLOv8 train command for 2 GPUs is simpler than what you have above and is done like this:

```
yolo train model=yolov5s.pt batch=64 device=0,1
```

**Comment by alicera** [comment]
Can it use the python command without yolo train cli?

**Comment by pderrenger** [comment]
@alicera yes, you can also use the Python command directly without the YOLOv8 CLI by importing the `train` module from YOLOv8 and calling the necessary functions in your Python script. This allows for more flexibility and customization in your training process.
