### ISSUE TITLE
Training on 8k dataset concerns

### ISSUE THREAD

**Issue by jpestrifork** [ultralytics/ultralytics#9232]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi!

I need to train a model with yolov8 on a dataset where the image resolution is `5496x3672`. The end goal is to detect very little objects in the image, some objects may have a length of `1 mm` (that's actually why the images has such high resolution).

I know that i can train a model with that resolution changing the `imgsz` parameter. But I have some questions, mainly about the performance:

1. Once the model is already trained, will the inference time be significantly degradated?
2. Will it be able to detect the small objects? any recommendations on the training? Does the `imgsz` needs to be `5496x3672` or can it be less and still detect the small objects?
3. Does it make more sense to train the model with less resolution and split the image to do the inference in the splited images?

**Comment by glenn-jocher** [comment]
@jpestrifork hi there! 🙌

Great questions! Here's a brief reply to address your concerns:

1. **Inference Time:** Yes, training and inferring at the native resolution of `5496x3672` might significantly increase inference time. Modern GPUs can handle high-res images well, but the increase is usually linear with the number of pixels.
   
2. **Detecting Small Objects:** To accurately detect tiny objects, high-resolution training can be beneficial. You don't necessarily need to train at `5496x3672`. Instead, consider starting with a smaller `imgsz` like `2048` or `4096` and evaluate performance. Augmentations that zoom into the images can also help the model learn to detect smaller objects.

3. **Training and Inference Strategy:** Splitting the image and inferring on the split images could be a smart move. It allows you to maintain high resolution for small object detection while keeping inference times more manageable. You can train the model with a smaller `imgsz` and apply a sliding window technique during inference, ensuring overlap between splits to avoid cutting through objects of interest.

Each application can be unique, so experimentation with these settings will likely yield the best results for your specific use case.

Hope this helps, and happy experimenting with YOLOv8! 🚀
