### ISSUE TITLE
how to extract YOLOv7 instance segmentation TXT files

### ISSUE THREAD

**Issue by utokyo-sm96** [ultralytics/ultralytics#9237]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi there,
Can anyone suggest me how can I save the predicted bounding box and segmented mask in the format of :
<class_id> <bbox_center_x> <bbox_center_y> <bbox_width> <bbox_height> <polygon_x1> <polygon_y1> <polygon_x2> <polygon_y2> ... <polygon_xN> <polygon_yN>
which has labels of both bounding box and segmentation mask

**Comment by glenn-jocher** [comment]
@utokyo-sm96 hello!

For saving both the bounding boxes and segmentation masks from YOLOv7 (assuming an interest in YOLOv8 though, as mentioned) in the desired format, you would typically need to post-process the model's predictions. Here's a quick outline in Python, assuming you have the results object from your YOLOv8 prediction:

```python
# Assuming 'results' is your model prediction
for i, det in enumerate(results.xyxy[0]):  # results.xyxy[0] is the detections for the first image
    class_id = int(det[-1])
    bbox = det[:4]
    bbox_center_x = (bbox[0] + bbox[2]) / 2
    bbox_center_y = (bbox[1] + bbox[3]) / 2
    bbox_width = bbox[2] - bbox[0]
    bbox_height = bbox[3] - bbox[1]
    # Assuming mask polygons are stored in a list of lists with each sub-list corresponding to a detected object
    mask_polygons = results.masks[i]  # This is a placeholder, your method to get masks may differ

    # Format the output string
    output_line = f"{class_id} {bbox_center_x} {bbox_center_y} {bbox_width} {bbox_height}"
    for polygon in mask_polygons:
        output_line += " " + " ".join(map(str, polygon.flatten()))

    # Save or print the output_line
    print(output_line)
```

Please note:
- `results.xyxy[0]` is used to access bounding box predictions for the first image in your batch. You might need to adjust this according to your prediction setup.
- The way masks are retrieved (`results.masks[i]`) is hypothetical and will depend on how your model outputs segmentation masks. You might need to adjust this based on actual outputs or use additional processing to get polygons from raw masks.
- This example prints the output lines to the console. You might want to append these to a list and then write them to a `.txt` file as per your requirements.

📝 Make sure to adjust `results.xyxy[0]` and `results.masks[i]` based on how your model's output is structured for bounding boxes and masks, respectively. The code assumes you're working with YOLO architecture for instance segmentation, but the principle should be similar across other architectures as well.
