### ISSUE TITLE
val stage shape is invalid for input of size

### ISSUE THREAD

**Issue by SeaLu** [ultralytics/ultralytics#9247]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to fix the image size to 640 in the model verification stage

**Comment by glenn-jocher** [comment]
@SeaLu hi there! 👋

It looks like you need to set the image size for the validation stage. You can achieve this by using the `imgsz` argument in your validation command. For example:

```bash
yolo val model=yolov8n.pt data=coco128.yaml imgsz=640
```

This command will validate your model `yolov8n.pt` on the `coco128.yaml` dataset with images resized to `640x640`. Adjust your model path and dataset file as necessary. Let us know if you need further assistance!
