### ISSUE TITLE
How to obtain the Sahi result graph

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#9263]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

https://docs.ultralytics.com/zh/guides/sahi-tiled-inference/#visualize-results

```python
detection_model = AutoDetectionModel.from_pretrained(
    model_type='yolov8',
    model_path=yolov8_model_path,
    confidence_threshold=0.3,
    device="cpu",  # or 'cuda:0'
)

result = get_sliced_prediction(
    "demo_data/small-vehicles1.jpeg",
    detection_model,
    slice_height=256,
    slice_width=256,
    overlap_height_ratio=0.2,
    overlap_width_ratio=0.2
)

```

```python
result.export_visuals(export_dir="demo_data/")
Image("demo_data/prediction_visual.png")
```

How to obtain the result graph
Do not want to export files, but directly obtain images

```python
cv2.imshow('visuals_image', visuals_image)  
cv2.waitKey(0)  
cv2.destroyAllWindows()  
```

**Comment by glenn-jocher** [comment]
@monkeycc hey there! 👋 You can directly display the result images using the `cv2.imshow` method without exporting files. After generating the `result` with `get_sliced_prediction`, use `result` to create an image array that `cv2` can display, like this:

```python
# Assuming result is obtained from get_sliced_prediction as shown in your code snippet
visuals_image = result.to_masked_image()  # This converts your result into a visual image array

# Now display this image array with cv2
cv2.imshow('Result', visuals_image)
cv2.waitKey(0)
cv2.destroyAllWindows()
```

Make sure you've obtained the visualization as a NumPy array compatible with OpenCV. Adjust `result.to_masked_image()` or similar functions to match your actual results object's method for getting the image if needed. Happy coding! 🚀

**Comment by monkeycc** [comment]
```
result = get_sliced_prediction(
    "demo_data/small-vehicles1.jpeg",
    detection_model,
    slice_height=256,
    slice_width=256,
    overlap_height_ratio=0.2,
    overlap_width_ratio=0.2
)
```

`'PredictionResult' object has no attribute 'to_masked_image'`

Unfortunately, this function is not available
