### ISSUE TITLE
The number of iterations per epoch!!

### ISSUE THREAD

**Issue by abdalluhahmed** [ultralytics/ultralytics#927]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In the training process, we can see the number of iterations is equal to 293, it's True, because if divided the dataset/minibatch =293, but the number of iterations in the Validation process is not True (14)! Why?  because the Val data/ minibatch = 27 , not 14??

** MiniBatch = 16
Training Data = 4686
Val data = 432 

### Additional

[
![Capture](https://user-images.githubusercontent.com/75636835/218175114-64b419ac-0845-4006-bb66-315dc7f183e2.PNG)
](url)

**Comment by glenn-jocher** [comment]
@abdalluhahmed val uses a 2x batch size compared to training for improved speed.

**Comment by abdalluhahmed** [comment]
oh thank you so much brother :)

**Comment by pderrenger** [comment]
@abdalluhahmed you're welcome! If you have any more questions or need further assistance, feel free to ask. Happy to help!
