### ISSUE TITLE
 How to save weights & resume yolov8 training using kaggle?

### ISSUE THREAD

**Issue by ViniciusRosa1** [ultralytics/ultralytics#9278]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I´m using kaggle to train my model with yolov8 and I don't want to overload my available hours during the week, so I want to know if it's possible (I know there's some way to do this) to train my model for a certain number of epochs, save it somewhere, and then use 'last.pt' to resume. For example, I want to train for a total of 300 epochs, dividing the training into sets of 50 epochs to avoid overloading my available time. Does anyone know how to do this using Kaggle?

**Comment by glenn-jocher** [comment]
@ViniciusRosa1 absolutely, you can break down your training on Kaggle into sets and resume training using the 'last.pt' checkpoint. Here's a simple way to do it:

1. **For the initial training**, specify the number of epochs (e.g., 50 for the first segment) and ensure you have set up your Kaggle workspace to save weights in the `/kaggle/working` directory. Use the command:

   ```bash
   yolo train data=your_dataset.yaml epochs=50
   ```

2. **Before ending your Kaggle session**, download the `last.pt` file from `/kaggle/working` to your local machine.

3. **For subsequent training sessions**, upload the `last.pt` file back to your Kaggle workspace and use it to resume training with the `--resume` flag or by specifying it as the model:

   ```bash
   yolo train --resume last.pt --epochs=100
   ```
   Or, specify the additional epochs to train for:
   ```bash
   yolo train data=your_dataset.yaml model=last.pt epochs=100
   ```

Kaggle sessions have a time limit, and your approach is smart to manage this constraint! Just remember to keep track of your epochs count manually to reach your total of 300 epochs. 😉

**Comment by glenn-jocher** [comment]
@ViniciusRosa1 absolutely, you can follow a similar approach with YOLOv9 for dividing and resuming your training sessions! Just as with YOLOv8, ensure you save your `last.pt` (or equivalent) after each training segment and use it to resume in subsequent sessions. If you have the `last.pt` file, simply resume like this:

```bash
yolo train data=your_dataset.yaml model=last.pt epochs=total_epochs_you_want
```

Happy training! 😊

**Comment by Gnoot01** [comment]
does the epochs have to be specified from the start? After the 300 epochs, can I increase the number of epochs to resume training for more epochs? Thanks

**Comment by Y-T-G** [comment]
@Gnoot01 Epochs can't be increased after you start training.

https://github.com/ultralytics/ultralytics/issues/802#issuecomment-2404251798

**Comment by Gnoot01** [comment]
Ah I see, very informative, thank you! Just want to add, would it be okay if I just used that same last.pt before or after it has fully finished training all epochs, to then train for more epochs than the initial one?

Eg. 
```
# Model that has / hasn't finished training from initial 30 epochs, not using resume
init_epochs = 30
model = YOLO("last.pt")
model.train(data=..., epochs= 50)
```

**Comment by Y-T-G** [comment]
@Gnoot01 Yes. But you will have to change the hyperparameters.

https://www.reddit.com/r/Ultralytics/comments/1eolwl8/the_correct_way_to_train_from_a_previously/
