### ISSUE TITLE
Not specifying the task when building YOLODataset in function export_openvino()

### ISSUE THREAD

**Issue by sifan-intel** [ultralytics/ultralytics#9284]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

![bug](https://github.com/ultralytics/ultralytics/assets/109498696/25129c9e-6a65-4de7-bdae-66b287afd669)

### Minimal Reproducible Example

import os
from ultralytics import YOLO

model_path = 'yolov8n-pose.pt'
model = YOLO(model_path)
data_conf = 'data_whole_det_17kpts.yaml'

model.export(format = "openvino", half=False, int8 = True, data = data_conf)

### Additional

In function export_openvino(), please change:
dataset = YOLODataset(data["val"], data=data, imgsz=self.imgsz[0], augment=False)
to:
dataset = YOLODataset(data["val"], data=data, task = self.model.task, imgsz=self.imgsz[0], augment=False)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sifan-intel hello! 👋

Thank you for pointing out this issue. Specifying the `task` parameter when building the `YOLODataset` in the `export_openvino` function indeed seems necessary for the correct dataset initialization related to the model's task type.

The suggested change you've provided looks spot-on. Incorporating the model's task into the `YOLODataset` initialization like this:

```python
dataset = YOLODataset(data["val"], data=data, task=self.model.task, imgsz=self.imgsz[0], augment=False)
```

is a concise and effective way to ensure that the dataset is correctly configured for the model's specific task, whether it's detection, segmentation, classification, or pose estimation.

We appreciate your willingness to help by contributing a PR! Feel free to reach out if you need any assistance or further clarification during the process. 😊
