### ISSUE TITLE
zsh: command not found: ultralytics

### ISSUE THREAD

**Issue by projects-g** [ultralytics/ultralytics#9292]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I pip installed the package on my MacOS. python 3.11.
I get command not found.

### Additional

NA

**Comment by Burhan-Q** [comment]
Use a venv to install python packages.
