### ISSUE TITLE
What algorithm is pose estimation based on

### ISSUE THREAD

**Issue by y200504040u** [ultralytics/ultralytics#9293]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

"Is the pose estimation using a top-down approach or a bottom-up approach? Please provide a more detailed documentation link, including the paper." Thanks a lot.

**Comment by glenn-jocher** [comment]
@y200504040u hello! 👋

YOLOv8 pose estimation utilizes a top-down approach. Each detected person is first identified, and then keypoints are estimated for each individual. While we don't have a specific paper dedicated to the pose estimation part of YOLOv8, our overall architecture and methodologies are elaborated in the YOLOv8 documentation [here](https://docs.ultralytics.com/models/yolov8).

Feel free to dive into the docs, and if you have any more questions or require further clarifications, don't hesitate to ask. Happy coding! 😊

**Comment by y200504040u** [comment]
Thank you very much for your reply.
I would like to know how the YOLOv8-pose training phase performs data augmentation.
For example, I expect my data to undergo random transformations, including rotation, scaling, and cropping, before being fed into the network. Where should I set these custom parameters for the transformations, including the probability of these transformations and the range of values for the transformations?
Thanks a lot.

**Comment by y200504040u** [comment]
> @y200504040u hello! 👋
> 
> YOLOv8 pose estimation utilizes a top-down approach. Each detected person is first identified, and then keypoints are estimated for each individual. While we don't have a specific paper dedicated to the pose estimation part of YOLOv8, our overall architecture and methodologies are elaborated in the YOLOv8 documentation [here](https://docs.ultralytics.com/models/yolov8).
> 
> Feel free to dive into the docs, and if you have any more questions or require further clarifications, don't hesitate to ask. Happy coding! 😊

Thank you very much for your reply.
I would like to know how the YOLOv8-pose training phase performs data augmentation.
For example, I expect my data to undergo random transformations, including rotation, scaling, and cropping, before being fed into the network. Where should I set these custom parameters for the transformations, including the probability of these transformations and the range of values for the transformations?
Thanks a lot.

**Comment by y200504040u** [comment]
> > @y200504040u hello! 👋
> > YOLOv8 pose estimation utilizes a top-down approach. Each detected person is first identified, and then keypoints are estimated for each individual. While we don't have a specific paper dedicated to the pose estimation part of YOLOv8, our overall architecture and methodologies are elaborated in the YOLOv8 documentation [here](https://docs.ultralytics.com/models/yolov8).
> > Feel free to dive into the docs, and if you have any more questions or require further clarifications, don't hesitate to ask. Happy coding! 😊
> 
> Thank you very much for your reply. I would like to know how the YOLOv8-pose training phase performs data augmentation. For example, I expect my data to undergo random transformations, including rotation, scaling, and cropping, before being fed into the network. Where should I set these custom parameters for the transformations, including the probability of these transformations and the range of values for the transformations? Thanks a lot.

**Comment by y200504040u** [comment]
I have found some implementations of data augmentation classes in "ultralytics/data/augment.py", but it seems that most of them have not been referenced.

**Comment by glenn-jocher** [comment]
@y200504040u hello again! 😊

For customizing data augmentation in the YOLOv8-pose training phase, you can adjust the augmentation parameters directly in your dataset YAML file. Here's a quick example to give you an idea:

```yaml
# Example of custom augmentation settings in your dataset.yaml
train: path/to/train/images
val: path/to/val/images

# Augmentation parameters
augment:
  rotation: 45  # degrees
  scale: 1.2  # scale factor
  translate: 0.1  # fraction of total image size
  shear: 15  # degrees
  perspective: 0.0  # perspective transform
  flipud: 0.5  # probability of vertical flip
  fliplr: 0.5  # probability of horizontal flip
```

This will be applied during training. Remember, the values provided here are just examples; you should adjust them to match the needs of your specific project. The adjustments allow you to control how much and what kind of transformations are applied.

If you need anything else or have more questions, feel free to reach out. Good luck with your project! 🚀

**Comment by y200504040u** [comment]
> @y200504040u hello again! 😊
> 
> For customizing data augmentation in the YOLOv8-pose training phase, you can adjust the augmentation parameters directly in your dataset YAML file. Here's a quick example to give you an idea:
> 
> ```yaml
> # Example of custom augmentation settings in your dataset.yaml
> train: path/to/train/images
> val: path/to/val/images
> 
> # Augmentation parameters
> augment:
>   rotation: 45  # degrees
>   scale: 1.2  # scale factor
>   translate: 0.1  # fraction of total image size
>   shear: 15  # degrees
>   perspective: 0.0  # perspective transform
>   flipud: 0.5  # probability of vertical flip
>   fliplr: 0.5  # probability of horizontal flip
> ```
> 
> This will be applied during training. Remember, the values provided here are just examples; you should adjust them to match the needs of your specific project. The adjustments allow you to control how much and what kind of transformations are applied.
> 
> If you need anything else or have more questions, feel free to reach out. Good luck with your project! 🚀

Thanks a lot. 😊😊😊

**Comment by glenn-jocher** [comment]
@y200504040u You're welcome! 😊 If you have any more queries down the road or if there's anything else we can help you with as you progress with your project, just drop a message here. Best of luck, and happy coding! 🚀

**Comment by glenn-jocher** [comment]
Hi @y200504040u! 😊 Great follow-up question.

To set the probability of applying a specific augmentation, such as 'scale', you can add a probational statement within the augmentation code. However, the current YAML format doesn't support directly specifying probabilities for each augmentation. This would require modifying the augmentation logic in the training script itself or creating a custom augmentation pipeline.

Regarding the 'scale' factor, setting it to `1.2` means that the image will be scaled by a factor randomly chosen in the range [1.0, 1.2]. It does not directly support specifying a +/- range around 1.0. If you want a range like (0.8, 1.2), you would again need to customize the augmentation logic to support this directly.

For advanced customizations, you might need to dive into the source code for your specific requirements. Always happy to help if you have more questions! 🚀

**Comment by y200504040u** [comment]
> Hi @y200504040u! 😊 Great follow-up question.
> 
> To set the probability of applying a specific augmentation, such as 'scale', you can add a probational statement within the augmentation code. However, the current YAML format doesn't support directly specifying probabilities for each augmentation. This would require modifying the augmentation logic in the training script itself or creating a custom augmentation pipeline.
> 
> Regarding the 'scale' factor, setting it to `1.2` means that the image will be scaled by a factor randomly chosen in the range [1.0, 1.2]. It does not directly support specifying a +/- range around 1.0. If you want a range like (0.8, 1.2), you would again need to customize the augmentation logic to support this directly.
> 
> For advanced customizations, you might need to dive into the source code for your specific requirements. Always happy to help if you have more questions! 🚀

Thank you for your previous response!
I have read the following code in ./ultralytics/yolo/data/augment.py, and it seems to implement (1 - scale, 1 + scale).
`def affine_transform(self, img, border):
        """Center."""
        C = np.eye(3, dtype=np.float32)

        C[0, 2] = -img.shape[1] / 2  # x translation (pixels)
        C[1, 2] = -img.shape[0] / 2  # y translation (pixels)

        # Perspective
        P = np.eye(3, dtype=np.float32)
        P[2, 0] = random.uniform(-self.perspective, self.perspective)  # x perspective (about y)
        P[2, 1] = random.uniform(-self.perspective, self.perspective)  # y perspective (about x)

        # Rotation and Scale
        R = np.eye(3, dtype=np.float32)
        a = random.uniform(-self.degrees, self.degrees)
        # a += random.choice([-180, -90, 0, 90])  # add 90deg rotations to small rotations
        s = random.uniform(1 - self.scale, 1 + self.scale)
        # s = 2 ** random.uniform(-scale, scale)
        R[:2] = cv2.getRotationMatrix2D(angle=a, center=(0, 0), scale=s)`

**Comment by glenn-jocher** [comment]
Hey @y200504040u! 👋

Thanks for pointing that out! You're absolutely correct. In the code snippet from `./ultralytics/yolo/data/augment.py`, it does indeed implement the scale as you described, applying a scaling factor randomly chosen in the range `(1 - scale, 1 + scale)`. This flexibility allows for diverse scaling during augmentation helping improve model robustness.

For probabilities for each augmentation, diving into the code to add custom logic based on your project needs is the go-to strategy. If you have any more insights or need further clarifications, I'm here to assist! Keep exploring 🚀😊

**Comment by y200504040u** [comment]
> Hey @y200504040u! 👋
> 
> Thanks for pointing that out! You're absolutely correct. In the code snippet from `./ultralytics/yolo/data/augment.py`, it does indeed implement the scale as you described, applying a scaling factor randomly chosen in the range `(1 - scale, 1 + scale)`. This flexibility allows for diverse scaling during augmentation helping improve model robustness.
> 
> For probabilities for each augmentation, diving into the code to add custom logic based on your project needs is the go-to strategy. If you have any more insights or need further clarifications, I'm here to assist! Keep exploring 🚀😊

Thank you for your consistent and patient assistance！

**Comment by glenn-jocher** [comment]
Hey @y200504040u! 😊

You're welcome! I'm glad I could help. Should you run into more questions or need further assistance as you dive into your project, don't hesitate to reach out. Happy coding, and best of luck with your augmentation experiments! 🚀
