### ISSUE TITLE
Can i merge custom model with pretrained model

### ISSUE THREAD

**Issue by harimukundh** [ultralytics/ultralytics#9294]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

how can i merge my custom model which has 4 classes with the pretrained model so that my new model has totally 84 classes

**Comment by glenn-jocher** [comment]
@harimukundh absolutely, you can merge your custom model with a pretrained model. Here's a simplified approach:

1. **Load Pretrained Model**: Load the pretrained model you wish to extend.
2. **Modify the Output Layer**: Adjust the number of classes in the output layer to `84`, combining your custom classes with the existing ones.

```python
from ultralytics import YOLO

# Load the pretrained model
model = YOLO('path/to/pretrained/model.pt')

# Adjust the output layer to the new number of classes
model.model[-1].nc = 84  # Where 84 is the new total number of classes

# Optionally, load the weights for your custom classes into the model
# Make sure to align the weights appropriately for your custom classes

# Continue training or save the modified model
model.save('path/to/save/extended_model.pt')
```
Keep in mind that directly merging models requires careful handling of the output layer's weights to appropriately integrate the knowledge from both models. Happy modeling! 🚀
