### ISSUE TITLE
yolo8 hyperparameter optimization

### ISSUE THREAD

**Issue by noahweber1-debug** [ultralytics/ultralytics#930]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am aware that with the evolve argument yolo5 can optimize the hyperparameters.

But I cant see this features in yolo8?

Are there plans to integrate this too?

**Comment by walter2482** [comment]
We need the optimization for paper aplicattions

**Comment by ichsan2895** [comment]
yes you can, for example
```
yolo task=segment mode=train model=yolov8m-seg.pt optimizer='Adam' lr0=0.001 epochs=100 data=my_config.yml
```
Please see [this docs](https://docs.ultralytics.com/cfg/) for detailed information

**Comment by MrMaynard** [comment]
@ichsan2895 that's a 404
