### ISSUE TITLE
Save counts

### ISSUE THREAD

**Issue by rick13xe** [ultralytics/ultralytics#9308]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey, im using this code to to count the fish that pass from one side of the screen to the other, but I cannot save the count in txt format, If I use save_txt=True the labels are saved, how can I save the fish that pass? (the in count and out count)

from ultralytics import YOLO
from ultralytics.solutions import object_counter
import cv2

model = YOLO("C:/Users/Ricardo/runs/segment/train22/weights/best.pt")
cap = cv2.VideoCapture(r"C:\Users\Ricardo\Pictures\vidloina\videos para capturas\GX022495.MP4")
assert cap.isOpened(), "Error reading video file"
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

rect_width = w // 6
rect_height = h
rect_x1 = w // 6 * 3
rect_y1 = 0
rect_x2 = w // 6 * 4
rect_y2 = h

point1 = (rect_x1, rect_y1)  
point2 = (rect_x2, rect_y1)  
point3 = (rect_x2, rect_y2)  
point4 = (rect_x1, rect_y2)  
line_points = [point1, point2, point3, point4]  
classes_to_count = [1, 3]  

video_writer = cv2.VideoWriter(r"C:\Users\Ricardo\Pictures\vidloina\videos para capturas\output.avi",
                       cv2.VideoWriter_fourcc(*'mp4v'),
                       fps,
                       (w, h))

counter = object_counter.ObjectCounter()
counter.set_args(view_img=True,
                 reg_pts=line_points,
                 classes_names=model.names,
                 draw_tracks=True)

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break
    tracks = model.track(im0, persist=True, show=False,
                         classes=classes_to_count)
 
    im0 = counter.start_counting(im0, tracks)
    video_writer.write(im0)

cap.release()
video_writer.release()
cv2.destroyAllWindows()

And another case also to save the data that the interference gives me for  example this next code gives me this: 0: 384x640 2 Cachuelos, 21 Loinas, 216.6ms Speed: 0.0ms preprocess, 216.6ms inference, 22.1ms postprocess per image at shape (1, 3, 384, 640) I want to save this part in txt format 2 Cachuelos, 21 Loinas.
Thanks for the help in advance.

import cv2
from ultralytics import YOLO

model = YOLO("C:/Users/Ricardo/runs/segment/train22/weights/best.pt")
confidence_threshold = 0.4  
overlap_threshold = 0.4   
video_path = r"C:\Users\Ricardo\Pictures\vidloina\Cabriel\Loinas\transecto7\GX052378.MP4"
track_history = defaultdict(lambda: [])

cap = cv2.VideoCapture(video_path)
cv2.namedWindow("YOLOv8 Inference", cv2.WINDOW_NORMAL)
while cap.isOpened():
    success, frame = cap.read()
    if success:
        results = model.track(frame, persist=True, conf=confidence_threshold, iou=overlap_threshold, save_crop=True)
        annotated_frame = results[0].plot()
        cv2.imshow("YOLOv8 Inference", annotated_frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()

**Comment by glenn-jocher** [comment]
@rick13xe hi there! 😊 It looks like you're doing some fantastic work with tracking passing fish in your video streams! Saving counts and data in a text format alongside your detections can indeed be very useful for analysis.

For saving counts (in count and out count) specifically, unfortunately, directly saving these as text files isn't a built-in feature. However, you can easily implement a custom solution by writing the counts to a file within your loop. Here's a small example of how you might modify your `object_counter` code snippet to include this:

```python
# Open a text file to write counts
with open('fish_counts.txt', 'w') as f:
    while cap.isOpened():
        success, im0 = cap.read()
        if not success:
            print("Video frame is empty or video processing has been successfully completed.")
            break
            
        tracks = model.track(im0, persist=True, show=False, classes=classes_to_count)
        im0 = counter.start_counting(im0, tracks)
        
        # Write the in count and out count to the file
        f.write(f"In count: {counter.in_count}, Out count: {counter.out_count}\n")
        
        video_writer.write(im0)
```
This will write the counts to `fish_counts.txt` every frame, ensuring you have a detailed account of passing fish.

For your second case, where you aim to save the detected classes and their counts to a text file, you can similarly leverage Python's file write operations. You might retrieve counts from the `results` object and write them to a file as shown below:

```python
# Open a text file to write detections
with open('detected_fish.txt', 'w') as f:
    while cap.isOpened():
        success, frame = cap.read()
        if not success:
            break
            
        results = model.track(frame, persist=True, conf=confidence_threshold, iou=overlap_threshold, save_crop=True)
        # Extract class counts
        class_counts = results[0].pandas().xyxy[0]['name'].value_counts().to_dict()
        
        # Write detected class counts to file
        f.write(f"{class_counts}\n")
        
        annotated_frame = results[0].plot()
        cv2.imshow("YOLOv8 Inference", annotated_frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
```

This approach writes a dictionary with counts of each detected class per frame into `detected_fish.txt`.

I hope this helps! Keep up the great work! 🚀

**Comment by rick13xe** [comment]
@glenn-jocher Hey, thank you :) , at the moment I'm doing some experiments with a small model to see how it works.
The first code go well, I had to only change in_count and out_count for counts, the second code gives me this error
raise AttributeError(f"'{name}' object has no attribute '{attr}'.  and AttributeError: 'Results' object has no attribute 'pandas'., a while ago I tried similar codes but they gave me that same error even changing pandas for other attributes.

**Comment by glenn-jocher** [comment]
@rick13xe hey there! 😊 I'm glad to hear your first code modification worked well with the small model experiments. For the second issue, it seems like accessing class counts directly from the `Results` object is causing the trouble due to the absence of a `pandas` attribute there.

To fix the error, we can iterate over detected objects and manually count class occurrences. Here's a concise way to do it:

```python
class_counts = {}
for detection in results[0].pred[0]:  # Assuming 'results' is your Results object from YOLOv8 inference
    class_id = int(detection[-1])  # Getting class_id from detection
    class_name = model.names[class_id]  # Converting class_id to class_name
    if class_name in class_counts:
        class_counts[class_name] += 1
    else:
        class_counts[class_name] = 1

# Now you can write class_counts to your file
with open('detected_fish.txt', 'a') as f:
    f.write(f"{class_counts}\n")
```

This approach manually tallies occurrences of each detected class in the frame, avoiding the need for a `pandas` attribute and should work as expected. 😀 Let me know if this resolves your issue or if there's anything else I can help with!

**Comment by rick13xe** [comment]
I have used the code in the following way, the saving part didn't work but the interference did work.
It gives me this error:
(And is there a way that in the other code you can make the in count and on count separate the classes as well?)
Thanks for ur time!

File "C:\Users\Ricardo\Desktop\lista.txt", line 22, in <module>
    for detection in results[0].pred[0]:
                     ^^^^^^^^^^^^^^^
  File "C:\Users\Ricardo\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\__init__.py", line 156, in __getattr__
    raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
AttributeError: 'Results' object has no attribute 'pred'. See valid attributes below.

#Code:
import cv2
from ultralytics import YOLO
from collections import defaultdict

model = YOLO("C:/Users/Ricardo/runs/segment/train22/weights/best.pt")
confidence_threshold = 0.4  # 60% de confianza
overlap_threshold = 0.4   # 10% de solapamiento
video_path = r"C:\Users\Ricardo\Pictures\vidloina\GX032503.MP4"
class_counts = {}

cap = cv2.VideoCapture(video_path)
cv2.namedWindow("YOLOv8 Inference", cv2.WINDOW_NORMAL)
while cap.isOpened():
    success, frame = cap.read()
    if success:
        results = model.track(frame, persist=True, conf=confidence_threshold, iou=overlap_threshold)
        annotated_frame = results[0].plot()
        cv2.imshow("YOLOv8 Inference", annotated_frame)

        # Contar las detecciones de cada clase
        for detection in results[0].pred[0]:
            class_id = int(detection[-1])  # Obtener el ID de clase de la detección
            class_name = model.names[class_id]  # Convertir el ID de clase en nombre de clase
            if class_name in class_counts:
                class_counts[class_name] += 1
            else:
                class_counts[class_name] = 1

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break

# Escribir class_counts en el archivo
with open(r"C:\Users\Ricardo\Pictures\vidloina\asdasd", 'a') as f:
    f.write(f"{class_counts}\n")

# Liberar los recursos y cerrar las ventanas al final del bucle
cap.release()
cv2.destroyAllWindows()

**Comment by glenn-jocher** [comment]
Hey @rick13xe 😊! Thanks for reaching out and sharing the snippet. Looks like there's been a small mix-up with accessing attributes from the `Results` object. The `Results` object indeed does not have a `pred` attribute directly accessible as you've discovered.

Here's a quick fix:

Instead of using `results[0].pred[0]` to iterate over detections, you should access the predictions through the `.xyxy[0]` attribute if you're working with YOLOv8 which provides a tensor of detections in `[x_min, y_min, x_max, y_max, confidence, class]` format. Here's how you could change your loop:

```python
if success:
    results = model.track(frame, persist=True, conf=confidence_threshold, iou=overlap_threshold)
    annotated_frame = results[0].plot()
    cv2.imshow("YOLOv8 Inference", annotated_frame)
    
    detections = results.xyxy[0]  # Detections tensor
    for detection in detections:
        class_id = int(detection[-1])  # Getting class_id from detection
        class_name = model.names[class_id]  # Converting class_id to class_name
        class_counts[class_name] = class_counts.get(class_name, 0) + 1
```

Regarding separating the counts by class for "in" and "out" specifically, you could extend the `class_counts` dictionary to track these counts separately within each loop iteration.

Hope this helps clear things up! Let me know if there's more I can help with. 🚀

**Comment by rick13xe** [comment]
@glenn-jocher It keeps giving me attribute error :(, also with the other code I will be able to do some good tests, thank you!!
I also have another, slightly more general question, is there a recommended number of epochs, images per class and pre trained model depending on the size of the dataset?
I am using the pre-trained model yolov8-s.seg.pt with 120 epochs with a dataset of 800 annotated images and 500 backgrownd, the model has 5 classes.
The information I have seen is very general.

**Comment by glenn-jocher** [comment]
Hey @rick13xe! 😊 Sorry to hear about the attribute error. Could you please share the exact line of code or error message? That'll help me pinpoint the issue more accurately.

Regarding your question on training configurations: For a dataset with 800 annotated images and 500 background images across 5 classes, using a pre-trained model like `yolov8-s.seg.pt` is a good start. Training for 120 epochs sounds reasonable, but the optimal number depends on how your model's performance evolves during training. Keep an eye on the validation loss and accuracy; if they plateau or start to degrade, it might be time to stop training. Generally, more images per class can help improve the model's accuracy, especially in complex or varied scenarios. If you find performance lacking, consider increasing the dataset size or experimenting with data augmentation to enhance the diversity of your training data.

Hope this helps! Let me know if you have any more questions. 🚀
