### ISSUE TITLE
Retrieving the path of predicted images in YOLOv8

### ISSUE THREAD

**Issue by Souheil-b** [ultralytics/ultralytics#931]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would like to know how to retrieve the path of the images being predicted. Could you please provide guidance on how this can be done?

I am using the following code:

````py
from ultralytics import YOLO

model = YOLO("yolov8n-seg.pt")
results = model("../../Data/", stream=True, show=False, box=False)

for result in results:
    for box in result.boxes:
        print(model.names[int(box.cls)], box.conf[0].numpy())
````

I have been using the **save_txt** attribute to save the predictions, but it only saves the predicted class and not the path of the image being predicted. I could not find a method to retrieve the path of the image.

Could you please provide guidance on how this can be done?

**Comment by glenn-jocher** [comment]
@Souheil-b thanks for the question, this is a good point.

@AyushExel @Laughing-q see above, we should try to add original image path to Results if available, else None. Autoshape Detections results include this here:
https://github.com/ultralytics/ultralytics/blob/977fd8f0b8764e83d7da964ba87477df6492735d/ultralytics/nn/autoshape.py#L135

**Comment by Souheil-b** [comment]
Oh great! You have added the image path to the Results in the latest version of ultralytics. Thank you so much for your help and support!

**Comment by pderrenger** [comment]
@Souheil-b you're welcome, but I must clarify that the credit goes to the Ultralytics team and the entire YOLO community for their valuable input and support. 😊 Let me know if there's anything else I can assist with!

**Comment by Souheil-b** [comment]
Thanks to the entire Ultralytics team ! ❤

**Comment by glenn-jocher** [comment]
@Souheil-b we deeply appreciate your kind words and support! Remember that the excellent progress we make with our models at Ultralytics is a collaborative effort, with valuable feedback and insights from users like you. Feel free to reach out anytime you need further assistance or have more feedback. Happy coding! ❤️
