### ISSUE TITLE
How to load multiple inputs at once for classification task

### ISSUE THREAD

**Issue by DucHai972** [ultralytics/ultralytics#9314]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am using a weather dataset that contains many different feature inputs (Such as: wind speed, temperature, humidity, ... ) that recorded at different days.
I want to use all these features to feed YOLO to classify whether there is typhoon at that day. However, YOLO seems to only classify every image independently

**Comment by glenn-jocher** [comment]
@DucHai972 hello there! Great question. YOLO models are primarily designed for tasks like object detection and classification from images. They take image inputs and can classify or detect objects within those images. For classification tasks involving multiple non-image features (like wind speed, temperature, humidity, etc.), you may need to adapt or preprocess your data into a format that a YOLO model can process, such as transforming feature data into an image-like array.

However, for tasks more aligned with tabular data or time-series data (like predicting weather events from various features), traditional YOLO may not be the best fit without significant adaptation. You might want to consider models specifically designed for sequence prediction or tabular data, such as LSTM (Long Short-Term Memory) networks for time-series data, or even a structured deep learning approach that can handle multiple input features directly.

If you're specifically interested in leveraging YOLO for this task and have image data related to the weather conditions (satellite images, for example), you could use those images directly as input for classification/detection tasks relevant to identifying typhoons.

Still, if you're set on using YOLO, converting your feature data into a form that's interpretable as an image to the model would be a necessary step. This approach, however, is quite unconventional and might not yield the most accurate results for the task at hand.

For accurate and efficient predictions on tabular or feature-rich datasets like weather data, exploring models beyond YOLO that are tailored to handling such data types directly might be more beneficial. 😊

**Comment by DucHai972** [comment]
Thank you very much @glenn-jocher

**Comment by glenn-jocher** [comment]
Hi @DucHai972! 👋 Absolutely, YOLO models, including YOLOv8, are primarily tailored for image-based tasks like object detection and image classification. They're optimized to understand and interpret visual data. For a dataset with numerical features like weather conditions (wind speed, temperature, humidity, etc.), a different model architecture might be more suitable.

For your specific need to classify weather events from various features, considering models designed for tabular data or even time-series predictions, if these events are temporal, might be more effective. Deep learning models like LSTMs or GRUs are great for time-series forecasting, while simpler neural networks or even algorithms like Random Forests can perform well on structured tabular data.

However, if you have associated weather condition images, YOLOv8 can classify or detect specific patterns related to typhoons from those images. For purely feature-based data without images, transforming the problem into an image-based one just to fit YOLO might not yield optimal results.

For weather forecasting from numerical features, you might explore:

```python
from sklearn.ensemble import RandomForestClassifier

# Assuming X_train contains your features and y_train contains weather labels
classifier = RandomForestClassifier(n_estimators=100)
classifier.fit(X_train, y_train)

# Predict on new data
predictions = classifier.predict(X_test)
```

This snippet uses a RandomForestClassifier, but exploring neural networks for structured data or LSTM for time-series could be beneficial paths too! 🌤️

Best of luck with your project!
