### ISSUE TITLE
is yolov8 support support tracking multiple videos simultaneously ? 

### ISSUE THREAD

**Issue by Abhijeet241093** [ultralytics/ultralytics#9320]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

1. For one video_ work fine:    for index, result in enumerate(model.track(source=VID_PATH,conf=0.85,iou=0.9,show=False, stream=True, verbose=True, persist=True)):

2. For Two video_its fail:     for index, (result1, result2) in enumerate(model.track(source=[VID_PATH, VID_PATH2],conf=0.85,iou=0.9,show=False, stream=True, verbose=True, persist=True)):

Erro Ecounter : 

![image](https://github.com/ultralytics/ultralytics/assets/38974232/31012309-28ec-4573-80a7-0f9196cf6b12)

**Comment by tricubicsGithub** [comment]
I got same error. Any fix?

**Comment by glenn-jocher** [comment]
@tricubicsGithub hello! It appears from your description that you're encountering issues when trying to track objects in multiple videos simultaneously using YOLOv8. The current version of YOLOv8 is designed to track objects in a single video stream out of the box. To track objects in multiple videos simultaneously, you'll need to manage parallel processing yourself, for example, by using threading or multiprocessing in Python.

Here's a quick example of how you might set it up using threading:

```python
import threading
from ultralytics import YOLO

# Define a function to track objects in a video
def track_video(video_path):
    model = YOLO('yolov8n.pt')
    for result in model.track(source=video_path, conf=0.85, iou=0.9, show=False, stream=True, verbose=True, persist=True):
        print(result)

# Paths to your video files
video_paths = ['path_to_video1.mp4', 'path_to_video2.mp4']

# Create and start a thread for each video
threads = [threading.Thread(target=track_video, args=(path,)) for path in video_paths]
for thread in threads:
    thread.start()

# Wait for all threads to finish
for thread in threads:
    thread.join()
```

This code creates a separate thread for each video stream, allowing them to be processed in parallel. Note that managing resources and synchronizing the output can get complex with multiple threads, especially with real-time video streams. 

I hope this helps! Let us know if you have further questions. 🙂

**Comment by tricubicsGithub** [comment]
Thanks for this @glenn-jocher!

However, I tested the code, and added line of code to visualize frames. However it seems not to be working and only showing a black frame. Any reason this is happening? 

Appreciated for the response.

**Comment by glenn-jocher** [comment]
@tricubicsGithub hey there! I'm happy to help. 😊 

It sounds like the frame might not be rendering correctly before it's displayed. Make sure you're correctly capturing and visualizing the frame within the thread. Here's a quick snippet showing how to capture and display a frame with OpenCV:

```python
import cv2

cap = cv2.VideoCapture(video_path)
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    
    # Process the frame with YOLOv8 
    # Assuming 'result.plot()' method for visualization
    processed_frame = result.plot()

    cv2.imshow('Frame', processed_frame)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
```

Ensure `result.plot()` correctly returns a frame (not just modifies it in-place) and that you're using `cv2.imshow()` right after processing the frame. If you're still staring at a dark abyss, double-check the path to your video to ensure it's correctly loaded. 

Hope this lights up your frames! Let me know if you need more help.
