### ISSUE TITLE
Here the fixed output YOLOv8n will mislead trainer

### ISSUE THREAD

**Issue by flyinghu123** [ultralytics/ultralytics#9322]
https://github.com/ultralytics/ultralytics/blob/6a2fddfb46aea45dd26cb060157d22cf14cd8c64/ultralytics/utils/checks.py#L648C79-L648C86

**Comment by glenn-jocher** [comment]
@flyinghu123 thanks for pointing this out! We appreciate your feedback and strive to ensure our tools are as useful and accurate as possible. The specific line you've highlighted indeed needs a review to better guide users during training. We'll look into updating it to remove any potential confusion. Here's a quick fix you can apply if you're manually adjusting the code:

Replace the snippet with:
```python
if not any(x in model.yaml for x in ('anchors', 'anchor_grid')):
    logger.info(f'WARNING: {model.yaml} lacks anchor definitions, using default anchors.')
```
This should provide clearer information about anchors during the training startup phase. Let us know if you have further suggestions or questions! 🚀
