### ISSUE TITLE
Train over the my pretrained model

### ISSUE THREAD

**Issue by SedatUnalCointral** [ultralytics/ultralytics#9325]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello everyone i wonder can i train over the my pretrained model ? For example lets say i have a model which can detect 3 objects (model name old.pt) . One day i need to add new object detection. Can i train over the old.pt model ? I try train over old model but new model cant find anything else my new class. If i can do it how can i please help me

**Comment by glenn-jocher** [comment]
@SedatUnalCointral hello! 🙋‍♂️ Definitely, you can continue training your model (`old.pt`) to detect additional objects. This process is often referred to as "fine-tuning." Here's a concise way to do it:

1. Update your dataset to include examples of the new object class you'd like to detect.
2. Update your `.yaml` file to include the new class in the classes list.
3. When training, use your pre-trained model (`old.pt`) as the starting point:

```bash
yolo train --data updated_dataset.yaml --model old.pt --epochs 100
```
Make sure your dataset includes enough examples of the new class and keep the existing ones to avoid forgetting previously learned classes. If the new model struggles with the old classes, consider revisiting your dataset or adjusting training hyperparameters.

Good luck with your model enhancement! If you hit any bumps, the community here is always willing to help out. 🚀
