### ISSUE TITLE
Segmentation fault fine-tuning pretrained model

### ISSUE THREAD

**Issue by Sigoloh** [ultralytics/ultralytics#9328]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

So, I made a dataset from a collection of frames I have to do some fine-tuning on the `yolov8x.pt` model. To do the labeling I used a software named [deeplabel](https://github.com/jveitchmichaelis/deeplabel) and converted to the YOLO dataset format using JSON2YOLO. After that, I wrote a script to fine-tune the model I was using as follow:
```python
from ultralytics import YOLO
model = YOLO('yolov8x.pt')

results = model.train(data="<my-model>.yaml", epochs=30, imgsz=480)
```

And the model yaml file is:
```yaml
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: .  # dataset root dir
train: ./train  # train images (relative to 'path') 4 images
val: ./val

# Classes (80 COCO classes)
names:
  0: motorcyle
  1: person
  2: car
```

After running `python fine-tuning.py`, I get the following log:
```
Ultralytics YOLOv8.1.34 🚀 Python-3.11.0 torch-2.2.1+cpu CPU (11th Gen Intel Core(TM) i5-1135G7 2.40GHz)
engine\trainer: task=detect, mode=train, model=yolov8x.pt, data=belleville.yaml, epochs=30, time=None, patience=100, batch=16, imgsz=480, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train4, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\train4
Overriding model.yaml nc=80 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1      2320  ultralytics.nn.modules.conv.Conv             [3, 80, 3, 2]
  1                  -1  1    115520  ultralytics.nn.modules.conv.Conv             [80, 160, 3, 2]
  2                  -1  3    436800  ultralytics.nn.modules.block.C2f             [160, 160, 3, True]
  3                  -1  1    461440  ultralytics.nn.modules.conv.Conv             [160, 320, 3, 2]
  4                  -1  6   3281920  ultralytics.nn.modules.block.C2f             [320, 320, 6, True]
  5                  -1  1   1844480  ultralytics.nn.modules.conv.Conv             [320, 640, 3, 2]
  6                  -1  6  13117440  ultralytics.nn.modules.block.C2f             [640, 640, 6, True]
  7                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]
  8                  -1  3   6969600  ultralytics.nn.modules.block.C2f             [640, 640, 3, True]
  9                  -1  1   1025920  ultralytics.nn.modules.block.SPPF            [640, 640, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  3   7379200  ultralytics.nn.modules.block.C2f             [1280, 640, 3]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  3   1948800  ultralytics.nn.modules.block.C2f             [960, 320, 3]
 16                  -1  1    922240  ultralytics.nn.modules.conv.Conv             [320, 320, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  3   7174400  ultralytics.nn.modules.block.C2f             [960, 640, 3]
 19                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   7379200  ultralytics.nn.modules.block.C2f             [1280, 640, 3]
 22        [15, 18, 21]  1   8720857  ultralytics.nn.modules.head.Detect           [3, [320, 640, 640]]
Model summary: 365 layers, 68155497 parameters, 68155481 gradients, 258.1 GFLOPs

Transferred 589/595 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
train: Scanning <my path>\yolo\datasets\train.cache... 4425 images, 0 backgrounds, 0 corrupt: 100%
val: Scanning <my path>\yolo\datasets\val.cache... 0 images, 4425 backgrounds, 0 corrupt: 100%|███
Plotting labels to runs\detect\train4\labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001429, momentum=0.9) with parameter groups 97 weight(decay=0.0), 104 weight(decay=0.0005), 103 bias(decay=0.0)
Image sizes 480 train, 480 val
Using 0 dataloader workers
Logging results to runs\detect\train4
Starting training for 30 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/277 [00:00<?, ?it/s]Segmentation fault
```

I found some similar problems in the issues from YoloV5, but no way to solve it.

### Environment

Intel i5, 16Gb RAM, 500GB SSD

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Sigoloh hey there! 👋 It looks like you're encountering a segmentation fault while trying to fine-tune a YOLOv8 model. Segmentation faults in Python, especially when using complex libraries like PyTorch, can sometimes be tricky to pin down. However, there are a few common areas we can explore:

1. **Software Versions**: Ensure you're using compatible versions of Python, PyTorch, and the Ultralytics YOLO package. Sometimes, version mismatches can lead to unexpected issues.

2. **Hardware Usage**: Although it looks like your system should handle the process fine, monitor your RAM and CPU usage during the training process to ensure there's no overload.

3. **Dataset Integrity**: Make sure there are no issues with your dataset. Corrupted or improperly formatted images might cause the process to fail.

4. **Library Dependencies**: Update your dependencies, as fixes in newer versions might resolve your issue.

5. **Try a smaller dataset**: As a test, try running your script on a smaller subset of your data to see if the issue persists. This can help isolate if the problem is data-related.

If none of these steps help, it might be beneficial to run your script in a debugger or with `gdb` to pinpoint where the segmentation fault occurs. Here’s a simple gdb command example to run your Python script:
```bash
gdb --args python3 your_script.py
```

And don't hesitate to provide more details if the issue persists, such as specific logs or debug information. The community is here to help!

**Comment by Sigoloh** [comment]
> @Sigoloh hey there! 👋 It looks like you're encountering a segmentation fault while trying to fine-tune a YOLOv8 model. Segmentation faults in Python, especially when using complex libraries like PyTorch, can sometimes be tricky to pin down. However, there are a few common areas we can explore:
> 
>     1. **Software Versions**: Ensure you're using compatible versions of Python, PyTorch, and the Ultralytics YOLO package. Sometimes, version mismatches can lead to unexpected issues.
> 
>     2. **Hardware Usage**: Although it looks like your system should handle the process fine, monitor your RAM and CPU usage during the training process to ensure there's no overload.
> 
>     3. **Dataset Integrity**: Make sure there are no issues with your dataset. Corrupted or improperly formatted images might cause the process to fail.
> 
>     4. **Library Dependencies**: Update your dependencies, as fixes in newer versions might resolve your issue.
> 
>     5. **Try a smaller dataset**: As a test, try running your script on a smaller subset of your data to see if the issue persists. This can help isolate if the problem is data-related.
> 
> 
> If none of these steps help, it might be beneficial to run your script in a debugger or with `gdb` to pinpoint where the segmentation fault occurs. Here’s a simple gdb command example to run your Python script:
> 
> ```shell
> gdb --args python3 your_script.py
> ```
> 
> And don't hesitate to provide more details if the issue persists, such as specific logs or debug information. The community is here to help!

So, after some research I found the problem. By default the `.train()` set the value of the parameter `batch` to 16 when using `cpu`, and this was trying to allocate more RAM than my computer could offer to the process. I tested with some random numbers and found a good middle term with `batch=4`. After that, the training process is running smoothly. I hope this helps other people geting the same problem. Thanks for you answer.

**Comment by glenn-jocher** [comment]
Hi @Sigoloh! 😊 Glad you figured it out and thanks for sharing your solution! Using a smaller `batch=4` is a great approach to manage memory usage, especially on systems with limited RAM. Your insights will undoubtedly be helpful for others encountering similar issues. If you run into any more questions or need further assistance, feel free to reach out. Happy training! 🚀

**Comment by yangezhuanjia** [comment]
大概是torch版本的问题，原来是torch=2.2.0+cu118,torchaudio=2.2.0+cu118,torchvision=0.17.0+cu118会报错。重新创建conda后安装了torch=2.1.1+cu118,torchaudio=2.1.1+cu118,torchvision=0.16.0+cu118,没有再出现这个问题。

**Comment by glenn-jocher** [comment]
@Sigoloh thanks for sharing your experience and the solution! 🌟 It looks like downgrading to `torch=2.1.1+cu118`, `torchaudio=2.1.1+cu118`, and `torchvision=0.16.0+cu118` resolved the issue for you. This could be really valuable info for anyone else running into similar troubles. We appreciate your input! If there's anything more you'd like to discuss or if you encounter any further issues, please feel free to reach out. Happy coding! 🚀
