### ISSUE TITLE
Changing device with resume

### ISSUE THREAD

**Issue by mnoroozii** [ultralytics/ultralytics#9329]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

How can I change the devices for multiple gpu training with resume??

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mnoroozii hey there! 👋

To change the devices during multi-GPU training with `resume`, you can specify the `device` argument along with `resume=True` in your training command. Here's a quick example if you wish to switch to GPUs `0` and `1`:

```bash
yolo detect train data=coco128.yaml model=yolov8n.pt epochs=100 imgsz=640 device=0,1 resume=True
```

This tells YOLOv8 to pick up where it left off and utilize GPUs 0 and 1 for training. Hope this helps! Happy training! 🚀

**Comment by glenn-jocher** [comment]
@mnoroozii I've opened PR #9453 for this functionality. We should have this resolved this week.
