### ISSUE TITLE
Tuner

### ISSUE THREAD

**Issue by Ricardo-Gomez-4-113** [ultralytics/ultralytics#9331]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Could you please provide me with a document containing the default tuner configuration parameters and its associated genetic algorithm for modifying hyperparameters? I require this information to substantiate certain aspects of my thesis. Thank you in advance.

### Additional
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/tuner.py

**Comment by glenn-jocher** [comment]
@Ricardo-Gomez-4-113 hello! Thank you for reaching out. 😊 Regarding the default tuner configuration parameters and the genetic algorithm for hyperparameter tuning, you can find the core details directly in the source code, specifically in the `tuner.py` file you referenced.

Here's a concise example of how the genetic algorithm might be initialized within the file:

```python
class GeneticAlgorithm:
    def __init__(self, mutation_rate=0.01, crossover_rate=0.7, ...):
        self.mutation_rate = mutation_rate
        self.crossover_rate = crossover_rate
        # Other parameters and initializations
```
Please note, the parameters and their values in the code snippet above are illustrative and may not directly mirror the current state of the `tuner.py` file. For the most accurate and up-to-date information, thoroughly review the [tuner.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/tuner.py) file in the Ultralytics GitHub repo.

For any specifics not covered in the code (such as detailed descriptions or rationale behind certain default values), it might be helpful to explore the [Ultralytics documentation](https://docs.ultralytics.com/) or to post detailed questions in the [GitHub discussions](https://github.com/ultralytics/ultralytics/discussions) for insights from the developers and the community.

Best of luck with your thesis! If you have further questions or need more detailed assistance, feel free to ask. 👍

**Comment by Ricardo-Gomez-4-113** [comment]
Good morning, thank you very much for the information. Just one more thing: what is it called or what method is used to search for the best hyperparameters? Thank you very much in advance.

**Comment by glenn-jocher** [comment]
@Ricardo-Gomez-4-113 good morning! 😊 For searching the best hyperparameters in YOLOv8, we use a genetic algorithm as part of our tuning process. This method iteratively adjusts hyperparameters over several generations to find a set that optimizes performance. Here's a very simplified pseudocode to give you the idea:

```python
initialize_population()
for generation in range(max_generations):
    evaluate_fitness(population)
    select_for_crossover(population)
    crossover(selected)
    mutate(crossover_population)
    population = crossover_population
best_hyperparameters = select_best(population)
```

This algorithm adapts and improves hyperparameters by mimicking natural selection processes. Hope this clears things up! If you have any more questions, feel free to ask. 👍

**Comment by Ricardo-Gomez-4-113** [comment]
Good morning, I understand that tuner uses ASHA for the selection of hyperparameters when the argument use_ray=True is used, my question is when this argument is not set, what method or algorithm does it use for the selection, I understand that it is some type of genetic algorithm but I want to know what type its name is or where I can enter bases on it.

**Comment by glenn-jocher** [comment]
@Ricardo-Gomez-4-113 good morning! Indeed, when `use_ray=True`, the tuner employs ASHA (Asynchronous Successive Halving Algorithm) for hyperparameter selection. If you don't set this argument, a custom genetic algorithm is used by default for the tuning process. 

This genetic algorithm iteratively evolves the hyperparameters through processes akin to natural selection, including mutation and crossover, to find optimal values. While we don't use a named variant of a genetic algorithm, the basis of our approach follows the standard genetic algorithm structure. Unfortunately, specific literature or base documents on the exact implementation are not provided, but understanding basic genetic algorithms concepts provides a good foundation. Here's a snippet to illustrate the idea generically:

```python
initialize_population()
for generation in range(max_generations):
    evaluate_fitness(population)
    parents = select_for_crossover(population)
    offspring = crossover(parents)
    mutate(offspring)
    population = offspring
```

Feel free to explore more about genetic algorithms in general to get a grasp on the methodology we adapt for hyperparameters tuning in YOLOv8. Hope this helps! 😊
