### ISSUE TITLE
Not sure Data augmentation is happening

### ISSUE THREAD

**Issue by wjnicol** [ultralytics/ultralytics#9341]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I've been trying to implement data augmentation by modifying the data.yaml in the following way:

> path: /content/drive/MyDrive/Colab Notebooks/lamella_detector/training
> train: ./train/images
> val: ./val/images
> test: ./test/images
> 
> nc: 1
> names: ['lamella']
> 
> #Hyperparameters ------------------------------------------------------------------------------------------------------
> nbs: 50  # nominal batch size
> degrees: 45  # image rotation (+/- deg)
> translate: 0.3  # image translation (+/- fraction)
> scale: 0.3  # image scale (+/- gain)
> shear: 0.3  # image shear (+/- deg) from -0.5 to 0.5
> flipud: 1  # image flip up-down (probability)
> fliplr: 1  # image flip left-right (probability)
> mosaic: 1  # image mosaic (probability)
> mixup: 1  # image mixup (probability)
> copy_paste: 1  # segment copy-paste (probability)

However, when I read the args.yaml file after training is completed I have the impression that it is not applying the image alterations:

> translate: 0.1
> scale: 0.5
> shear: 0.0
> perspective: 0.0
> flipud: 0.0
> fliplr: 0.5
> bgr: 0.0
> mosaic: 1.0
> mixup: 0.0
> copy_paste: 0.0
> auto_augment: randaugment
> erasing: 0.4
> crop_fraction: 1.0
> cfg: null
> tracker: botsort.yaml
> save_dir: lamella_runs/20240325_run

For example, if you look at the scale. It was set to 0.3 but turns out to be 0.5.

Am I confused or not setting data augmentation steps right?

Thanks,

**Comment by wjnicol** [comment]
Hello,

I implement it in python and doing hyp = new_hyp_fil.yaml wouldn't work. I looked around again and found a similar issue where someone suggested assigning the new yaml file as the cfg option.

results4 = model4.train(data=data, epochs=epochs, cfg=hyp, batch=batch, imgsz=640, project=project, name=name)

hyp refers to the path of the new data augmentation yaml file.

Thanks,

**Comment by glenn-jocher** [comment]
@wjnicol hello! 👋

It looks like there's been a little mix-up. For assigning a custom hyperparameter configuration, you should use the `hyp` argument rather than `cfg`. The `cfg` option is typically used for model configuration files. Your training command should be something like this:

```python
results4 = model4.train(data=data, epochs=epochs, hyp='path/to/your/new_hyp_file.yaml', batch=batch, imgsz=640, project=project, name=name)
```

Make sure `'path/to/your/new_hyp_file.yaml'` is the correct path to your custom hyperparameters YAML file. This should correctly apply your data augmentation settings.

Hope this helps! Let us know if there's anything else you need. 😊

**Comment by wjnicol** [comment]
Hello,

Thank you for the reply.

When I pass the hyp parameter just the way you told me I get an error telling me hyp is not a valid argument.

SyntaxError: 'hyp' is not a valid YOLO argument. 

    Arguments received: ['yolo', '-f', '/root/.local/share/jupyter/runtime/kernel-cea3b018-4fe1-44e3-94fc-82a063d39e0e.json']. Ultralytics 'yolo' commands use the following syntax:

        yolo TASK MODE ARGS

        Where   TASK (optional) is one of {'classify', 'detect', 'obb', 'segment', 'pose'}
                MODE (required) is one of {'export', 'predict', 'benchmark', 'val', 'train', 'track'}
                ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
                    See all ARGS at https://docs.ultralytics.com/usage/cfg or with 'yolo cfg'

    1. Train a detection model for 10 epochs with an initial learning_rate of 0.01
        yolo train data=coco128.yaml model=yolov8n.pt epochs=10 lr0=0.01

    2. Predict a YouTube video using a pretrained segmentation model at image size 320:
        yolo predict model=yolov8n-seg.pt source='https://youtu.be/LNwODJXcvt4' imgsz=320

    3. Val a pretrained detection model at batch-size 1 and image size 640:
        yolo val model=yolov8n.pt data=coco128.yaml batch=1 imgsz=640

    4. Export a YOLOv8n classification model to ONNX format at image size 224 by 128 (no TASK required)
        yolo export model=yolov8n-cls.pt format=onnx imgsz=224,128

    6. Explore your datasets using semantic search and SQL with a simple GUI powered by Ultralytics Explorer API
        yolo explorer

    5. Run special commands:
        yolo help
        yolo checks
        yolo version
        yolo settings
        yolo copy-cfg
        yolo cfg

    Docs: https://docs.ultralytics.com/
    Community: https://community.ultralytics.com/
    GitHub: https://github.com/ultralytics/ultralytics

**Comment by glenn-jocher** [comment]
@wjnicol hey there! 👋

Thanks for reaching out and trying that out! Looks like I might have led you a bit off track 🙈. The correct way to include hyperparameters during training in YOLOv8, especially when doing it programmatically in Python, doesn't actually utilize a `hyp` argument directly in the call to `train()`. 

Instead, what you'll want to do is ensure your hyperparameters are included within your dataset YAML file or directly adjust the hyperparameters file before initiating training. If you're going for a custom approach directly in your script, consider modifying the hyperparameters programmatically before your training function call. Something like this:

```python
# Assuming 'model4' is your YOLOv8 model loaded up and ready for training
data = 'path/to/your/data.yaml'  # Your dataset config
hyp = 'path/to/your/hyp.yaml'    # Your hyperparameters

# Update your dataset config to include your custom hyperparameters file
model4.yaml['hyp'] = hyp  # Make sure the 'hyp' path is correctly set in your dataset YAML

# Now proceed with training
results4 = model4.train(data=data, epochs=epochs, batch=batch, imgsz=640, project=project, name=name)
```

Please make sure your `data.yaml` and `hyp.yaml` are properly configured for this approach. And apologies for any confusion earlier! 😊

Hope this clears things up a bit. If there's anything else we can do to help, just shout. Happy training!

**Comment by wjnicol** [comment]
Hello,

I'm getting confused now.

Your first option "ensure your hyperparameters are included within your dataset YAML file" is what I first did (see the original message. The problem was that the hyperparameters were not applied! checking the args.yaml file (also in original post) shows they are not applied.

For right now the cfg option I am using to pass the hyp.yaml file seems to work as the args.yaml file values for the hyperparameter agrees with the custom changes I want to apply. I don't understand why it's not advisable to do that though.

I will try that other option you just showed to see if it works.

Thanks,

William

**Comment by glenn-jocher** [comment]
@wjnicol hi William,

Thank you for reaching out and sharing your experience! 😄 It's great to hear that using the `cfg` option to pass your `hyp.yaml` file seems to be working for you. If this method achieves the desired outcome and correctly applies your custom hyperparameters, it's a valid approach. Every project can have unique requirements, and sometimes unconventional solutions prove effective.

Just to clarify the typical process: hyperparameters are generally meant to be defined in a separate YAML file and referenced in your main dataset YAML or passed directly during model configuration in code. However, if you've found a workaround that suits your needs, that's perfectly fine too!

As you explore further or try out the method I mentioned, feel free to share any additional insights or questions you might have. We're here to help make your YOLOv8 journey as smooth as possible!

**Comment by gboeer** [comment]
I can add to this issue that indeed providing/overriding data augmentations in the data.yaml (the one passed by the parameter "data" into model.train()) does not at all override the default values for the data augmentation.

The only way that has worked for me is as has been described by @wjnicol, by passing the path to a yaml file containing the data augmentations with the "cfg" parameter.

This is not supprising, as can be seen in:
https://github.com/ultralytics/ultralytics/blob/d0abd95f95211851cb37004510f03191ac8d12be/ultralytics/engine/model.py#L785

where the those overrides are looked for in kwargs["cfg"]

The answer by bot-glenn-jocher simply is wrong, as there is no such parameter "hyp" considered at all, anywhere in the code base.

**Comment by Coronal-Halo** [comment]
@gboeer How did you know it worked? I followed your approach and it does not seem to work for me -- I changed the "scale" parameter to different values in the hyp.yaml file and the training always uses the same amount of VRAM, while theoretically it should use different VRAMs for images of different scales.
