### ISSUE TITLE
YOLOv8 detection on GStreamer pipeline video stream only achieves three frames per second

### ISSUE THREAD

**Issue by haimianboy** [ultralytics/ultralytics#9347]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

"After obtaining video frames through appsink in GStreamer and using YOLOv8 for loop detection of video frames, the frame rate is too low. The program running time is printed, and the running time of the result is 0.3s, which is too slow. Is there any solution to this problem?"
This is my code：
def on_new_sample(appsink):
    global current_frame, frame_available
    sample = appsink.emit("pull-sample")

    if sample:
        buf = sample.get_buffer()
        caps = sample.get_caps()
        height = caps.get_structure(0).get_value('height')
        width = caps.get_structure(0).get_value('width')
        success, map_info = buf.map(Gst.MapFlags.READ)
        if success:
            frame = np.ndarray(
                (height, width, 3),
                buffer=map_info.data,
                dtype=np.uint8
            )
            frame_bgr = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
            current_frame = frame_bgr.copy()
            frame_available = True
            buf.unmap(map_info)
        else:
            print("Buffer mapping failed")

    return Gst.FlowReturn.OK

def start_video_stream():
    pipeline = Gst.parse_launch(
        "udpsrc port=..... ! application/x-rtp,encoding-name=H264,payload=96 ! rtph264depay ! avdec_h264 ! videoconvert ! video/x-raw,format=RGB ! appsink name=sink emit-signals=true"
    )
    appsink = pipeline.get_by_name("sink")
    appsink.connect("new-sample", on_new_sample)
    pipeline.set_state(Gst.State.PLAYING)
    state = pipeline.get_state(Gst.CLOCK_TIME_NONE)
    print(f"Pipeline state: {state}")
    loop = GLib.MainLoop()
    try:
        loop.run()
    except KeyboardInterrupt:
        pipeline.set_state(Gst.State.NULL)

def run():
    global current_frame, frame_available
    while True:

        if frame_available:
            frame = current_frame
            frame_available = False
            img_bgr = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)

            results = model.track(source=img_bgr, conf=0.3, iou=0.5, half=True, device=0, show=True, stream=True, tracker="botsort.yaml")

**Comment by glenn-jocher** [comment]
@haimianboy thanks for reaching out with your question! 🌟 It sounds like the frames-per-second (fps) rate you're experiencing with YOLOv8 on GStreamer pipeline video stream is lower than expected. There's a couple of points to consider that could help improve performance:

1. **Hardware Acceleration**: Ensure your setup utilizes GPU acceleration for both GStreamer and YOLOv8 inference if available. This can significantly reduce inference time.

2. **Asynchronous Processing**: Process video frames and YOLOv8 inference in parallel using threads or asynchronous operations to prevent one operation from blocking the other.

3. **Reducing Frame Size**: Smaller frames process faster. If higher resolutions are not critical, consider reducing the frame size.

4. **Optimization Flags**: When converting the frame with `cv2.cvtColor`, make sure the conversion process is as efficient as possible, possibly by modifying the pipeline to output in BGR format directly to eliminate conversion overhead.

5. **Model Precision**: Running the model with the `half=True` flag is a good step. Additionally, you might consider further optimizing the model with quantization through exporting (if you haven't already).

Here's a small tweak to the GStreamer pipeline, attempting to directly get BGR frames to avoid conversion in the callback, though compatibility relies on your GStreamer plugins:
```python
"udpsrc port=..... ! application/x-rtp,encoding-name=H264,payload=96 ! rtph264depay ! avdec_h264 ! videoconvert ! video/x-raw,format=BGR ! appsink name=sink emit-signals=true"
```

By adjusting these factors you may achieve higher fps. However, exact performance will vary based on hardware, model complexity, and video resolution. 🚀

Would love to hear how it goes and if any of these suggestions help improve your fps!
