### ISSUE TITLE
Is there a way to hide/suppress the YOLO model's internal logging mechanism?

### ISSUE THREAD

**Issue by APAKGRUP** [ultralytics/ultralytics#9351]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,
I'm currently using a YOLOv8 model, and it automatically generates continuous output like this:
```
Speed: 1.0ms preprocess, 9.0ms inference, 0.0ms postprocess per image at shape (1, 3, 128, 128)

0: 128x128 (no detections), 9.5ms
Speed: 0.0ms preprocess, 9.5ms inference, 0.0ms postprocess per image at shape (1, 3, 128, 128)

0: 128x128 (no detections), 9.0ms
Speed: 0.0ms preprocess, 9.0ms inference, 0.0ms postprocess per image at shape (1, 3, 128, 128)

0: 128x128 (no detections), 9.0ms
Speed: 0.0ms preprocess, 9.0ms inference, 0.0ms postprocess per image at shape (1, 3, 128, 128)

```

Is there a way to stop this output? It's interfering with other statements I want to see, but I can't because of these lengthy YOLO-generated lines. Any help, please?

**Comment by s5377689** [comment]
I also want to know how to hide

**Comment by glenn-jocher** [comment]
@s5377689 hello! 😊 You can easily suppress those log messages by setting the `verbose` parameter to `False` when calling the model for predictions. Here's how you can do it:

```python
results = model(frame, verbose=False)
```

This should keep your console cleaner and focus on the output you're interested in. Let us know if there's anything else we can help with!

**Comment by APAKGRUP** [comment]
Thank you so much guys, it worked as you told me.

**Comment by glenn-jocher** [comment]
@APAKGRUP that's fantastic to hear! 🎉 If you have any more questions or need further assistance, feel free to reach out. Happy detecting!
