### ISSUE TITLE
quanto support for further model optimisation 

### ISSUE THREAD

**Issue by Fritskee** [ultralytics/ultralytics#9354]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Huggingface recently released their `quanto` package. This is a toolkit that allows you to "easily" quantize models in Pytorch.

More on it can be found here: https://huggingface.co/blog/quanto-introduction

### Use case

For the moment, ultralytics only supports int8 at best for some niche back-ends. Most often we're forced to `fp16` as the best quantisation that can be done. It would be very interesting to be able to quantize to `int4` and `int8` such that we can run the different ultralytics models on even smaller hardware than currently is possible.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Fritskee hey there! Thanks for bringing "quanto" to our attention. 😊 We're always looking for ways to optimize YOLOv8 models further, especially regarding quantization for deployment on various hardware. The introduction of `quanto` by Huggingface for easier model quantization in PyTorch sounds promising!

We haven't integrated `quanto` support yet, but we're definitely open to exploring new tools that can enhance model efficiency. For now, our models support `fp16` and `int8` quantization for specific deployment environments, but the idea of extending this to `int4` and wider `int8` use cases is intriguing.

While we consider how `quanto` could potentially fit into our roadmap, we encourage our community and contributors to experiment and share their findings. 🚀

For those looking to experiment with quantization using current capabilities, here's a quick example for fp16:

```python
from ultralytics import YOLO

model = YOLO('yolov8n.pt')
model.export(format='onnx', half=True)
```

This converts the model to ONNX format with `fp16` precision. Adapting and testing with `quanto` or contributing insights would be highly appreciated! Let's keep pushing the boundaries of what's possible with YOLOv8 together.
