### ISSUE TITLE
Resume YOLOv8 Training On GPU

### ISSUE THREAD

**Issue by HuzaifaEhsan421** [ultralytics/ultralytics#9356]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

can i resume training yolov8 on gpu, when i start training it is on CPU now I want to shift to Gpu, is there a way doing it?

I have tried one approach 
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

model = YOLO("last.pt")
model.to(device)
model.train(resume=True)

But above approach gives me error on line model.train(resume=True)

AssertionError: Invalid device id

Can anyone helpme out in resolving this issue.

**Comment by glenn-jocher** [comment]
@HuzaifaEhsan421 hello! 👋 

Absolutely, you can resume training your YOLOv8 model on a GPU if it started on a CPU. The approach you tried is on the right track but slightly misaligned with how YOLOv8's API is structured for training operations. To resume training on a GPU, you can use the CLI command or adjust your script slightly. Here's a simpler way to achieve this using the CLI, which automatically handles device allocation:

```bash
yolo train model=last.pt resume=True
```

This command will automatically detect and use your GPU if it's available. No need to manually manage the device in your code. If you're using a script and want to explicitly set the device, ensure your CUDA device ID is correct or simply use `'cuda'` if using the first available GPU. Also, `resume` functionality is handled directly by the `train` method without manually moving your model to the device:

```python
from ultralytics import YOLO

# Load your model, specifying device at load time if needed
model = YOLO('last.pt', device='cuda')

# Resume training
model.train(resume=True)
```

This should get you back on track without the `AssertionError`. If you continue to experience issues, ensure your CUDA environment is correctly set up and accessible to PyTorch. 🚀

Hope this helps! Let us know if you have any more questions.

**Comment by HuzaifaEhsan421** [comment]
Hi @glenn-jocher 
I have also tried this approach but this also raises an error.
TypeError: YOLO.__init__() got an unexpected keyword argument 'device'

**Comment by glenn-jocher** [comment]
@HuzaifaEhsan421 hi there! 👋 

Ah, my apologies for the confusion. It appears I provided incorrect guidance regarding the device argument. In YOLOv8's current API, the device is selected automatically based on availability, so there's no need to specify it directly when loading your model with `YOLO('last.pt')`.

If you're aiming to resume training and want to ensure it uses the GPU, you can directly call the `train` method with `resume=True` as you have been. The YOLOv8 API will handle device allocation for you, favoring the GPU when available:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('last.pt')

# Resume training, automatically utilizing GPU if available
model.train(resume=True)
```

Make sure your PyTorch installation has access to CUDA, and the training should automatically proceed on your GPU. 🚀

Hope this clears things up! Let us know if you have any other questions.

**Comment by jet-c-21** [comment]
@glenn-jocher 
can i change the arguments settings on resume mode? for example, my last.pt does not enable cache=True, now i want to resume it with cache enabled, how can i do?

**Comment by glenn-jocher** [comment]
Hey there! 👋

Absolutely, you can adjust certain arguments when resuming training in YOLOv8. For enabling caching during resume, you can directly specify it in the `train` method like so:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('last.pt')

# Resume training with cache enabled
model.train(resume=True, cache=True)
```

This command enables caching and resumes training from your checkpoint. Just ensure that this setting is appropriate for your dataset and hardware configuration for best performance.

Let us know if this works for you or if there's anything else we can help with!

**Comment by jet-c-21** [comment]
I've tried `model.train(resume=True, cache=True)`, but on version `8.2.8`, but the cache is not enabled in the resumed training

**Comment by glenn-jocher** [comment]
Hello! 👋 

Thanks for reaching out. If you’re experiencing issues with enabling cache in resumed training on version `8.2.8`, it might be due to how the caching configuration is handled. For an effective workaround, try enabling the cache manually in your dataset configuration file or pass the cache argument directly in your training command. 

Here's an example of modifying the training command:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('last.pt')

# Resume training with cache enabled
model.train(resume=True, cache='ram')  # Can also try cache='disk' depending on your preference and hardware setup
```

Make sure that your system has sufficient RAM if using `cache='ram'`. Let us know how it goes or if there’s anything else we can assist with! 🚀

**Comment by adesolasamuel** [comment]
I am experiencing same issue, training started with GPU automatically but uses CPU on setting resume=True

**Comment by glenn-jocher** [comment]
@adesolasamuel thanks for reporting this! When resuming training, you can explicitly specify the device to ensure GPU usage:

```python
from ultralytics import YOLO

model = YOLO('last.pt')
model.train(resume=True, device=0)  # Force GPU 0, or device='cuda' for auto GPU selection
```

The device argument can be overridden during resume, so this should resolve the CPU fallback issue you're experiencing.
