### ISSUE TITLE
Which file or files are used for prediction?

### ISSUE THREAD

**Issue by HunarAA** [ultralytics/ultralytics#9357]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I wounder which python file or files are used for doing prediction? I have already downloaded YOLOV8 and trained on my custom dataset but I want to play with the boxes a little bit. So, how can I locate the files?

**Comment by himalayo** [comment]
Hello, I'd recommend using the [predict mode](https://docs.ultralytics.com/modes/predict/) to perform predictions. It supports a wide variety of data sources, ranging from individual images to entire YouTube videos.
To do so, you'd first need to find where your trained model was saved. By default, they are saved in the `./runs/<model type>/<name of your model>/weights` folder, relative to the path you were in when you launched your training script.

So for example, in my case, I have trained my model in `/home/hima/dataset/RSCD`, and I used `yolov8n-cls.pt` as my weights when training, as such, my model type happens to be a classification model, and can be found in `/home/hima/dataset/RSCD/runs/classify/train/weights`
I can then run `yolo predict model=/home/hima/dataset/RSCD/runs/train/weights/best.pt data=./img.jpg` on my CLI and it performs a classification on the `img.jpg` file, and the results were then saved as an image in the `./runs/classify/predict` folder.
This is what I got:
![some](https://github.com/ultralytics/ultralytics/assets/46873233/65da792e-239c-4df3-969f-8854c00ae276)

**Comment by glenn-jocher** [comment]
@himalayo hey there! 👋 It looks like you're all set and have successfully trained your model. That's great! For predictions, especially if you're interested in adjusting the bounding boxes, you would typically interact with the results after running the `predict` mode.

Your command for using the trained model looks spot on. To play with the boxes, you might want to explore modifying the results in your script. After running a prediction, the `Results` object will contain the boxes, which you can then manipulate as needed.

Here's a basic example of how you might adjust the box dimensions in Python after predicting:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('/home/hima/dataset/RSCD/runs/train/weights/best.pt')

# Perform prediction
results = model.predict('img.jpg')

# Adjust the bounding boxes in results.boxes (this is just a placeholder for your adjustments)
for box in results[0].boxes.xyxy:
    # Example to increase box width by 10 pixels
    box[2] += 10

# Optionally, save or display the results with adjusted boxes
results[0].show()
results[0].save('adjusted_boxes.jpg')
```
Remember, the manipulation logic inside the loop is entirely up to what adjustments you're looking to make.

Hope this helps! Let me know if you have more questions.
