### ISSUE TITLE
Training aborts with 'Permission denied' exception while writing to 'events.out.tfevents' file(s)

### ISSUE THREAD

**Issue by LambertWM** [ultralytics/ultralytics#936]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

During training,  I get an occasional exception:
`PermissionError: [Errno 13] Permission denied: b'runs\\detect\\train14\\events.out.tfevents.1675772859.HP-DESKTOP-SPV6D76.4500.1'`
Looking at the call-stack (below), I suspect this is a race-condition where multiple threads are trying to write to a Tensorboard file at the same time. 

#### NOTE: 
I am on `torch-1.8.0+cu111`, so if this is a Tensorflow/Tensorboard issue, then it may have been fixed in later versions.

### Call stack:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File ".\PythonClean\venv\lib\site-packages\sentry_sdk\integrations\threading.py", line 69, in run
    reraise(*_capture_exception())
  File ".\PythonClean\venv\lib\site-packages\sentry_sdk\_compat.py", line 60, in reraise
    raise value
  File ".\PythonClean\venv\lib\site-packages\sentry_sdk\integrations\threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File ".\PythonClean\venv\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 233, in run
    self._record_writer.write(data)
  File ".\PythonClean\venv\lib\site-packages\tensorboard\summary\writer\record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File ".\PythonClean\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 766, in write
    self.fs.append(self.filename, file_content, self.binary_mode)
  File ".\PythonClean\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 160, in append
    self._write(filename, file_content, "ab" if binary_mode else "a")
  File ".\PythonClean\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 164, in _write
    with io.open(filename, mode, encoding=encoding) as f:
PermissionError: [Errno 13] Permission denied: b'runs\\detect\\train14\\events.out.tfevents.1675772859.HP-DESKTOP-SPV6D76.4500.1'
```

### Work-around
FYI - I provided a temporary 'hack-around' by modifying `.\PythonClean\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py` so that the exception is ignored when appending to "events.out.tfevents" file:

Added helper function:
```
# LWM
def is_precious_file(filename):
    filename = compat.as_str_any(filename)
    if "events.out.tfevents" in filename:
        #print("is_precious_file("+filename+") : False")
        return False
    else:
        #print("is_precious_file("+filename+") : True")
        return True
```

Which is used in `GFile.write( )` as follows:

```
    def write(self, file_content):
        [....]
        if self.fs_supports_append:
            if not self.write_started:
                # write the first chunk to truncate file if it already exists
                self.fs.write(self.filename, file_content, self.binary_mode)
                self.write_started = True

            else:
                # append the later chunks
                # LWM: ignore exception if the file isn't precious
                try:
                    self.fs.append(self.filename, file_content, self.binary_mode)
                except Exception as ex:
                    print("LWM: write(): exception for: " + compat.as_str_any(self.filename) + ":", ex)
                    if is_precious_file(self.filename):
                        raise
                    else:
                        print("LWM: write(): ignore exception for: " + compat.as_str_any(self.filename) )

```

### Config

- Ultralytics YOLOv8.0.26  
- Python-3.7.8 
- torch-1.8.0+cu111 
- CUDA:0 (NVIDIA GeForce RTX 2060 SUPER, 8192MiB)
- Windows 10

### Python script

```
from ultralytics import YOLO
model = YOLO("yolov8s.pt")
train_results = model.train(data="C:/bbi/DataRoot/TwitterLeach01NN/Export/YoloV8v09/ultralytics.yaml",epochs=20,batch=4,imgsz=480)
```

### Typical output

Ultralytics YOLOv8.0.26  Python-3.7.8 torch-1.8.0+cu111 CUDA:0 (NVIDIA GeForce RTX 2060 SUPER, 8192MiB)
yolo\engine\trainer: task=detect, mode=train, model=yolov8s.yaml, data=C:/bbi/DataRoot/TwitterLeach01NN/Export/YoloV8v09/ultralytics.yaml, epochs=20, patience=50, batch=4, imgsz=480, save=True, cache=False, device=, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=False, val=True, save_json=False, save_hybrid=False, conf=0.001, iou=0.7, max_det=300, half=False, dnn=False, plots=False, source=ultralytics/assets/, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.001, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=0.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, save_dir=runs\detect\train14

  0                  -1  1       928  ultralytics.nn.modules.Conv                  [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.C2f                   [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.C2f                   [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.Conv                  [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.C2f                   [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.SPPF                  [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]
 12                  -1  1    591360  ultralytics.nn.modules.C2f                   [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]
 15                  -1  1    148224  ultralytics.nn.modules.C2f                   [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.Conv                  [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]
 18                  -1  1    493056  ultralytics.nn.modules.C2f                   [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.Conv                  [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]
 21                  -1  1   1969152  ultralytics.nn.modules.C2f                   [768, 512, 1]
 22        [15, 18, 21]  1   2144686  ultralytics.nn.modules.Detect                [74, [128, 256, 512]]
Model summary: 225 layers, 11164238 parameters, 11164222 gradients, 28.8 GFLOPs

Transferred 70/355 items from pretrained weights
optimizer: SGD(lr=0.01) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.001), 63 bias
train: Scanning C:\bbi\DataRoot\TwitterLeach01NN\Export\YoloV8v09\UL\labels\train... 283484 images, 11394 backgrounds, 0 corrupt: 100%|██████████| 283484/283484 [06:59<00:00, 676.13it/s]
train: New cache created: C:\bbi\DataRoot\TwitterLeach01NN\Export\YoloV8v09\UL\labels\train.cache
val: Scanning C:\bbi\DataRoot\TwitterLeach01NN\Export\YoloV8v09\UL\labels\test... 22889 images, 0 backgrounds, 0 corrupt: 100%|██████████| 22889/22889 [00:34<00:00, 660.20it/s]
val: New cache created: C:\bbi\DataRoot\TwitterLeach01NN\Export\YoloV8v09\UL\labels\test.cache
Image sizes 480 train, 480 val
Using 4 dataloader workers
Logging results to runs\detect\train14
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/20     0.791G     0.6401      1.205      1.079          9        480: 100%|██████████| 70871/70871 [1:18:50<00:00, 14.98it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2862/2862 [04:35<00:00, 10.38it/s]
                   all      22889      88052      0.573       0.39      0.426      0.343

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/20      1.38G     0.5351     0.9983       1.01          9        480: 100%|██████████| 70871/70871 [1:11:44<00:00, 16.46it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2862/2862 [04:32<00:00, 10.51it/s]
                   all      22889      88052      0.631      0.405      0.461      0.379

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/20      1.38G     0.5393      1.031      1.007         20        480: 100%|██████████| 70871/70871 [1:10:46<00:00, 16.69it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2862/2862 [04:32<00:00, 10.49it/s]
                   all      22889      88052      0.629      0.402      0.457      0.381

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/20      1.38G     0.5429      1.052      1.006          6        480: 100%|██████████| 70871/70871 [1:10:04<00:00, 16.86it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2862/2862 [04:36<00:00, 10.36it/s]
                   all      22889      88052      0.598      0.375      0.426      0.359

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/20      1.38G     0.5375      1.025     0.9992         14        480:  23%|██▎       | 16067/70871 [15:52<56:32, 16.16it/s]Exception 

### Call-stack
in thread Thread-3:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\SyncplicityRoot\VisualStudioProjects\TEMP\PythonClean\venv\lib\site-packages\sentry_sdk\integrations\threading.py", line 69, in run
    reraise(*_capture_exception())
  File "C:\SyncplicityRoot\VisualStudioProjects\TEMP\PythonClean\venv\lib\site-packages\sentry_sdk\_compat.py", line 60, in reraise
    raise value
  File "C:\SyncplicityRoot\VisualStudioProjects\TEMP\PythonClean\venv\lib\site-packages\sentry_sdk\integrations\threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "C:\SyncplicityRoot\VisualStudioProjects\TEMP\PythonClean\venv\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 233, in run
    self._record_writer.write(data)
  File "C:\SyncplicityRoot\VisualStudioProjects\TEMP\PythonClean\venv\lib\site-packages\tensorboard\summary\writer\record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "C:\SyncplicityRoot\VisualStudioProjects\TEMP\PythonClean\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 766, in write
    self.fs.append(self.filename, file_content, self.binary_mode)
  File "C:\SyncplicityRoot\VisualStudioProjects\TEMP\PythonClean\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 160, in append
    self._write(filename, file_content, "ab" if binary_mode else "a")
  File "C:\SyncplicityRoot\VisualStudioProjects\TEMP\PythonClean\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 164, in _write
    with io.open(filename, mode, encoding=encoding) as f:
PermissionError: [Errno 13] Permission denied: b'runs\\detect\\train14\\events.out.tfevents.1675772859.HP-DESKTOP-SPV6D76.4500.1'

       5/20      1.38G     0.5375      1.025     0.9992         14        480:  23%|██▎       | 16067/70871 [16:11<56:32, 16.16it/s]

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@LambertWM thanks for the bug report! I would first upgrade to the latest torch 1.13.1, and if you are still seeing this then let us know and we may need to wrap TensorBoard methods in try: except handlers to allow training to proceed in the event of failed log updates.
