### ISSUE TITLE
How does 'auto' in letterbox work?

### ISSUE THREAD

**Issue by veronicamorelli** [ultralytics/ultralytics#9366]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, 
I am using `letterbox` function as a preprocessing step to resize an image to a specified shape. 
My image is smaller than the desired shape. Ex original shape = (114, 91, 3). Ex target shape (224, 224, 3). 
If I set the parameters: scaleup=True, scale_fill=False, auto=True, center=False, stride=32 I don't get the target shape (224, 224,3). Is it normal? What does 'auto' parameter do and why is it important. 
I assumed 'auto' enable the image output shape to be a multiple of the stride but if I change the stride, like to 20, and keep the parameters as I said I don't get a output shape multiple of 20. 

I appreciate the help.

**Comment by Burhan-Q** [comment]
@veronicamorelli there's no need to run the `Letterbox` function directly, it will be applied automatically (as needed) when you pass your data into the model for training.

**Comment by veronicamorelli** [comment]
@Burhan-Q Thank you for your answer. You are right but I am using `Letterbox` function in preprocessing step of a ML pipeline implemented by myself and I wanted to understand fully how the parameters work.

**Comment by Burhan-Q** [comment]
@veronicamorelli understood. Just to double check, you wrote the new shape should be `224` and expecting that the output would be a multiple of `20` but these are not evenly divisible, and later you showed `stride=32` as your argument. Maybe you had a different meaning here, but I assume you're target is a `stride=32` and image size `(224,224)` with the following. Here's what I found from some testing

```py
import cv2

from ultralytics import ASSETS
from ultralytics.data.augment import LetterBox

im = ASSETS / "bus.jpg"
img = cv2.imread(im)
img.shape
>>> (1080, 810, 3)

lb = LetterBox() # all default settings
img2 = lb(image=img)
img2.shape
>>> (640, 640, 3)

lb = LetterBox(auto=True)
img2 = lb(image=img)
img2.shape
>>> (640, 480, 3)

lb = LetterBox(auto=True, center=False)
img2 = lb(image=img)
img2.shape
>>> (640, 480, 3)

# Crop to same size you're using
img_crop = img[:114, :91, :]
img_crop.shape
>>> (114, 91, 3)

lb = LetterBox(new_shape=(224,224), auto=True, center=False)
img3 = lb(image=img_crop)
img3.shape 
>>> (224, 192, 3)

lb = LetterBox(new_shape=(224,224), auto=False, center=False)
img3 = lb(image=img_crop)
img3.shape 
>>> (224, 224, 3)
```

https://github.com/ultralytics/ultralytics/blob/3aeb058e824655650a21e1f447d8711990accdc7/ultralytics/data/augment.py#L715-L716

The `auto` parameter looks like it's used to figure out how much padding is needed to make the image square. When `auto=False` it uses the minimum rectangle (as shown in the comment) which would mean the image is _not_ made square but ends up padding to whatever the _next_ multiple of the `stride` is for both dimensions. In your case, the height would not be padded, but the image is resized to this new height. With `auto=False` the image is scaled to `(224, 179)` and then only padded in the width dimension up to the next multiple of the stride, which is `192`.

Why the argument is named `auto` I'm not certain, but suspect it could have to do with operations elsewhere in the Ultralytics code that I'm not offhandedly familiar with. Hopefully this helps you to better understand the `LetterBox` class and how it operates.

**Comment by veronicamorelli** [comment]
Thanks @Burhan-Q. I understood perfectly your explaination. Thanks for your answer. 

Only one thing, in this sentence "When auto=False it uses the minimum rectangle (as shown in the comment)..." did you mean "When auto=True..." right? Because it happens when auto=True, in fact later you explain me the case when auto=False. Just to be sure about the explaination :)

**Comment by veronicamorelli** [comment]
Thanks @Burhan-Q. Sorry but did you mean when `auto=True` right?

**Comment by Burhan-Q** [comment]
@veronicamorelli yes, I have updated my comment appropriately. Apologies for the mix-up!

**Comment by veronicamorelli** [comment]
Thank you very much @Burhan-Q. Your comments were very helpful!
