### ISSUE TITLE
The class filter does not work when classifying.

### ISSUE THREAD

**Issue by binn77** [ultralytics/ultralytics#937]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The class filter does not work when classifying.
In the model of class 2, I specify to use class 0, but there are 2 of them at the output

`res =model.predict(img_cv, device="0",classes=0)`

`tensor([0.00101, 0.99899], device='cuda:0')`

**Comment by glenn-jocher** [comment]
@binn77 yes that's correct. The `classes` filter is intended for filtering detect and segment model types and has no effect on classify model results.
