### ISSUE TITLE
YOLOV8 - Transfer learning

### ISSUE THREAD

**Issue by vvvlll93** [ultralytics/ultralytics#9379]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

First, thank you for your work ! I find it incredible.

I know there is currently similar question, but I didn't find anything that helped me solve my problem.

I'm currently trying to use transfer learning on a yolov8 model to adapt it to new datasets. Let me explain the context.

Let's say we have 3 datasets, with the following classes :

- Dataset 1:
    - A
    - B
    - C
- Dataset 2:
    - A
    - C
    - D
- Dataset 3:
    - A
    - C
    - D
    - E

What I want to do is, iterating over each dataset, to finally obtain a model that is capable of predicting each class of each dataset, well, apply transfer learning.

In my example, here is my `config.yaml` file which contains the configuration for the training : 
``` 
train: my_training_folder
val: my_val_folder
nc: 5
names:
  0: A
  1: B
  2: C
  3: D
  4: E
```

For each dataset, I changed the class index (i.e. the first value of each row for each label file) so that it matches the list of classes inside my `config.yaml`.
`my_training_folder` and `my_val_folder` are the folder containing the data for each dataset. So it can be Dataset 1, Dataset 2 or Dataset 3.

The first training, I used the following parameters (i'm launching it from a python script) : 
```
yolo = YOLO('yolov8n.yaml')
yolo.train(data='config.yaml', epochs=300, device=device, batch=12)
```
Doing so, i'm training a new model from scratch.
Then, when the first training is done, i'm simply changing the value for `my_training_folder` and `my_val_folder` with the new dataset (i.e. Dataset 2). I'm launching the training with the commands : 
```
yolo = YOLO('runs/detect/MYALREADYTRAINEDMODEL/weights/best.pt')
yolo.train(data='config.yaml', epochs=300, device=device, batch=12, freeze=10)
```

Now, my problem. 
When i'm doing this, I'm getting really poor performances (<10% precision), but I've already trained other models on each dataset, and I know it can perform pretty good (~> 90% precision and recall). 

What can I change/add/correct in order to use transfer learning with YOLOV8 on multiple dataset ?

Don't hesitate if you need more informations.

Thank you.

**Comment by Waariss** [comment]
Dear @vvvlll93,

I hope this message finds you well. I'm currently working on a graduate project involving YOLOv8, and I've encountered an issue related to transfer learning that I believe you can help me with. I came across your post regarding freezing layers during transfer learning, and I'm interested in implementing a similar approach in my project.

Could you please provide me with the complete Python script for the method you described? Specifically, I'm referring to the part where you use:

python

`yolo = YOLO('runs/detect/MYALREADYTRAINEDMODEL/weights/best.pt')
yolo.train(data='config.yaml', epochs=300, device=device, batch=12, freeze=10)`

I'm unsure how to correctly integrate the freezing of layers into my transfer learning process. Any guidance or additional code snippets you could share would be greatly appreciated.

Thank you in advance for your assistance.

Best regards,
Waris

**Comment by vvvlll93** [comment]
Hi @Waariss,

Hope you'll be able to go through your project. 

Considering the integration of the `freeze` parameter, this is exactly as i've write it. From what i've found around the internet, the freezing parameters will simply set the gradient at 0, so the freeze here means that the layers won't be updated. 

To be clear : the code i've put in my first message in this conversation is exactly how it is in my code (well just the `MYALREADYTRAINEDMODEL` that is different).

Hope this helps, feel free to ask other question if you need to.

Best regards,
V

**Comment by itsmefifa** [comment]
@vvvlll93 
Hi, I can't freeze the layer because it has an error SyntaxError: 'freeze' is not a valid YOLO argument.
Do you know why because I did the code same as you did but it can not work ?

**Comment by himalayo** [comment]
Could it perhaps be caused by overfitting? So on the first run it overfits and that's maybe why you're getting lower performances in the next run?

**Comment by vvvlll93** [comment]
@himalayo 
Hi,

It might be cause by overfitting, i'm working with different type of administrative document, but even if the layout is different, the underlying structure that might be capture by the model is, I believe, pretty similar between each type. 

But my main problem comes from the fact that when I train my second model, even if my first was performing pretty well, after the second training the model is no longer able to perform correctly on the first type of document, the type of document it is supposed to perform well.

**Comment by himalayo** [comment]
@vvvlll93
I have some YOLOv8 classification models that I have to retrain to keep consistency between other models that I've built using transfer learning in Keras.
This does seem to be a good opportunity to replicate your training process, so if I stumble across useful information, if I find useful information regarding your issue I'll let you know. :)

In my Keras models, I first trained the last layers of my model by freezing its first layers, and only then did I train the rest of the model. You could try something similar to this approach, but I cannot guarantee that this is the source of your problem.

**Comment by glenn-jocher** [comment]
@vvvlll93 hi there! 😊

Thanks for sharing your journey to successful transfer learning with YOLOv8! This concise summary is extremely valuable. Just to add a quick note, remember to ensure your `class labels` in the `.yaml` and `.txt` files are correctly matched and consistently ordered.

For those encountering 'nan' losses, double-checking the dataset and resource allocation can save a lot of headaches. Happy training, and keep sharing your insights!

**Comment by kanis777** [comment]
hi @vvvlll93 @glenn-jocher  .If possible can you tell me wt does freezing do - i have 20 layers (appx). should i freeze them all and send for training on another dataset or is there any criteria as to how many layers i can freeze?

**Comment by glenn-jocher** [comment]
Hi @kanis777,

Freezing layers in a neural network essentially means that the weights of those layers will not be updated during training. This is particularly useful in transfer learning, where you want to retain the learned features from a pre-trained model and only fine-tune the later layers on your new dataset.

Typically, you would freeze the initial layers (which capture more generic features like edges and textures) and leave the later layers (which capture more specific features) trainable. For a model with approximately 20 layers, freezing the first 10 layers is a common practice, but this can vary based on your specific use case and dataset.

Here's a quick example in YOLOv8:
```python
yolo = YOLO('path/to/pretrained_model.pt')
yolo.train(data='config.yaml', epochs=300, device=device, batch=12, freeze=10)
```

This command freezes the first 10 layers and trains the remaining layers on your new dataset.

For more detailed guidance, you might find the [Ultralytics documentation](https://docs.ultralytics.com/guides/model-training-tips/) helpful.

Feel free to experiment with different numbers of frozen layers to see what works best for your specific scenario. Happy training! 🚀

**Comment by kanis777** [comment]
> Hi @kanis777,
> 
> Freezing layers in a neural network essentially means that the weights of those layers will not be updated during training. This is particularly useful in transfer learning, where you want to retain the learned features from a pre-trained model and only fine-tune the later layers on your new dataset.
> 
> Typically, you would freeze the initial layers (which capture more generic features like edges and textures) and leave the later layers (which capture more specific features) trainable. For a model with approximately 20 layers, freezing the first 10 layers is a common practice, but this can vary based on your specific use case and dataset.
> 
> Here's a quick example in YOLOv8:
> 
> ```python
> yolo = YOLO('path/to/pretrained_model.pt')
> yolo.train(data='config.yaml', epochs=300, device=device, batch=12, freeze=10)
> ```
> 
> This command freezes the first 10 layers and trains the remaining layers on your new dataset.
> 
> For more detailed guidance, you might find the [Ultralytics documentation](https://docs.ultralytics.com/guides/model-training-tips/) helpful.
> 
> Feel free to experiment with different numbers of frozen layers to see what works best for your specific scenario. Happy training! 🚀

hey @glenn-jocher .So , is it enough if i directly add freeze=10 because in my runs-> args.yaml - freeze=null is present so doesn't that mean the freezing has not happened . And also should I unfreeze the obtained model or can i proceed?

**Comment by glenn-jocher** [comment]
Hi @kanis777,

Great questions! 

1. **Freezing Layers**: Yes, you can directly add `freeze=10` to your training command to freeze the first 10 layers. The `freeze=null` in your `args.yaml` simply means that no layers were frozen in that particular run. By specifying `freeze=10`, you override this setting for your current training session.

2. **Unfreezing Layers**: After training with frozen layers, you can choose to unfreeze some or all layers and continue training if you believe the model can benefit from further fine-tuning. This can help the model adapt better to your new dataset. Here's how you can do it:

   ```python
   yolo = YOLO('path/to/partially_trained_model.pt')
   yolo.train(data='config.yaml', epochs=100, device=device, batch=12, freeze=0)  # Unfreeze all layers
   ```

This command will unfreeze all layers and continue training the model.

Feel free to experiment with these settings to find the optimal configuration for your specific use case. If you encounter any issues, please ensure you are using the latest version of the Ultralytics packages.

Happy training! 🚀

**Comment by Nbn03** [comment]
> Hi,
> 
> I've finally achieve transfer learning with YOLOV8. For people trying to achieve it, here is what you need to do :
> 
> * Based on my context of data, you need to have a FULL .yaml file containing all class (they are ordered alphabetically)
> * You need to freeze (using the parameter `freeze` the first 10 layers of the already trained model)
> * In the training dataset : you need to include images (with their corresponding label) of all the previous run
> * Same for the validation dataset
> * You also need to change the label id inside your label.txt file so that it matches the label in the FULL .yaml file
> * Let it run for a high number of epoch (or check with your perf). I let it run for 600 epochs, the loss slowly decrease
> * If you get nan for loss and/or validation : there is a high chance that this come from your RAM. It might also be a problem with your ID.
> 
> Hope this helps

Hey @vvvlll93 
In the third point that you mentioned, does it mean that we have to include the images (and their corresponding labels) on which the previous weight was trained. For example: If I am training my data with 100 images on a pretrained dataset, and then use the weights obtained from that training in the next training which I will be doing with 200 images. So, do I have to use the 100 images which I used in my first training?
