### ISSUE TITLE
Request for Information About Article Publication on arXiv

### ISSUE THREAD

**Issue by BrasD99** [ultralytics/ultralytics#938]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Dear Ultralytics Team,

I would like to start by thanking you for creating YOLOv8. Your work has been invaluable in advancing the field of computer vision, and I am truly grateful for your contributions.
I am writing to inquire about the publication timeline for your article, which I understand is under consideration for publication on arXiv. I am currently working on a related research project, and I have a project deadline in the summer.
Given this timeline, I was hoping to ask if you have any information regarding the expected date of publication for the article on arXiv. I understand that the timeline for publication can be subject to change, and any rough estimate you can provide would be greatly appreciated.
Thank you for your time and assistance. I look forward to hearing back from you soon. ❤️

**Comment by AyushExel** [comment]
We'll work on the arxiv paper soon but can't provide a concrete date yet. Meanwhile you can use the following citation information available on the main page of the repo.
<img width="1437" alt="Screenshot 2023-02-13 at 1 48 09 PM" src="https://user-images.githubusercontent.com/15766192/218405671-49d984ac-d251-4b4c-808a-b258a62a3fa4.png">
