### ISSUE TITLE
OBB task do not support `save_crop`

### ISSUE THREAD

**Issue by goodfishboy** [ultralytics/ultralytics#9380]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would like to know if save crop is supported in obb mode now, and if not now, will it be supported later? Thank you!
![1$HXD$WF`$OYR_7NS9HDC7F](https://github.com/ultralytics/ultralytics/assets/116552903/1949e74d-9956-4422-88af-ec0db3a06894)

**Comment by glenn-jocher** [comment]
@goodfishboy hey there! 😊

Currently, the `save_crop` feature isn't supported in OBB (Oriented Bounding Box) mode. We're always working on improving and adding new features based on our community's feedback. Though there's no set timeline right now, we appreciate your interest, and I'll definitely pass this along to our team for consideration in future updates. 

Stay tuned for future releases, and your patience and support are much appreciated!
