### ISSUE TITLE
Training model

### ISSUE THREAD

**Issue by Viseenn** [ultralytics/ultralytics#9383]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is it possible to visualize the process happening in each layer during model training? If so, how can it be done?

**Comment by glenn-jocher** [comment]
@Viseenn hello! 😊 Yes, you can visualize layer activities during training using tools like TensorBoard. Here's a quick example on how you might log feature maps for visualization:

1. **TensorBoard Setup:** When training your YOLOv8 model, ensure you have TensorBoard logging enabled. This is usually achieved by specifying the `--tensorboard-dir` flag with your output directory.
   
2. **Custom Logging:** For more specific layer visualizations, you might need to modify your training script to log the desired layer outputs. Here's a tiny code snippet on logging feature maps of a specific layer:

    ```python
    from torch.utils.tensorboard import SummaryWriter
    writer = SummaryWriter('runs/feature_visualization')

    for i, data in enumerate(dataloader):
        images, labels = data  # Get your batch of images and labels
        features = model.extract_features(images)  # Function to extract features from a desired layer
        writer.add_images('features', features, i)  # Log the feature maps
    ```

3. **Visualizing in TensorBoard:** After your training session, run TensorBoard pointing it to your logs directory:

    ```bash
    tensorboard --logdir=runs
    ```

Navigate to the Images tab in TensorBoard to see the visualizations.

Please note, `model.extract_features()` is a placeholder for your method of extracting features from your chosen layer. You might need to dive into your specific model implementation to extract these. Happy visualizing! 🚀
