### ISSUE TITLE
tflite inference in segmentation wrongly scales the first 4 upper pixels of the image

### ISSUE THREAD

**Issue by charlesollion** [ultralytics/ultralytics#9385]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

The faulty code is in forward of`autobackend.py` for tflite as it updates **each** output by denormalizing. Instead it should not affect the mask output:

```python
for output in self.output_details:
    x = self.interpreter.get_tensor(output["index"])
    if integer:
        scale, zero_point = output["quantization"]
        x = (x.astype(np.float32) - zero_point) * scale  # re-scale
    if x.ndim > 2:  # if task is not classification
        # Denormalize xywh by image size. See https://github.com/ultralytics/ultralytics/pull/1695
        # xywh are normalized in TFLite/EdgeTPU to mitigate quantization error of integer models
        x[:, [0, 2]] *= w
        x[:, [1, 3]] *= h
    y.append(x)
```

You can see the problem in this picture, it only affects the very top of the masks, so it is often a silent problem. In the following I visualize just one of the 32 masks:

![Screenshot from 2024-03-28 17-54-53](https://github.com/ultralytics/ultralytics/assets/10595147/bf86c0ed-0d8d-492b-828f-6de2082e2ce6)

### Environment

only for tflite in segmentation

### Minimal Reproducible Example

self explanatory

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@charlesollion hi there! Thanks for bringing this to our attention 🙏. It seems like the issue stems from the denormalization process affecting segmentation mask outputs inappropriately. A quick workaround in `autobackend.py` would be to add a condition to skip this process for mask outputs. Something along these lines:

```python
if not output["name"].startswith("mask"):  # Assuming mask outputs have a 'mask' prefix
    if x.ndim > 2:  # if task is not classification
        x[:, [0, 2]] *= w
        x[:, [1, 3]] *= h
```

This is a temporary fix, and I'll be working on a more integrated solution for this issue. Your findings are incredibly helpful, and we appreciate your willingness to contribute with a PR! If you have any further insights or implement a solution, feel free to share it or discuss it further here before the PR. Happy coding!

**Comment by glenn-jocher** [comment]
@charlesollion TFLite Segmentation models are showing identical Val metrics/mAP50-95(M) vs every other format, so everything is likely working correctly:

https://github.com/ultralytics/ultralytics/actions/runs/8475291549/job/23223143167
<img width="1655" alt="Screenshot 2024-03-29 at 02 07 18" src="https://github.com/ultralytics/ultralytics/assets/26833433/6afef260-a2ea-469f-bc38-34d1b93c344d">

**Comment by glenn-jocher** [comment]
@charlesollion can you submit a PR with a proposed fix? The same CI will run on it and we can check the accuracy of the proposed changes in the PR.
