### ISSUE TITLE
How could I add new identify target？

### ISSUE THREAD

**Issue by BobbleHatkjh** [ultralytics/ultralytics#9389]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi team
I have done a train about "door" and a "stairs", its pretty well, but i want to train "chair" continue to identify, how could i do that?

have i must retrain from start

**Comment by glenn-jocher** [comment]
@BobbleHatkjh hi there! 😊 It's great to hear you've successfully trained models to detect "door" and "stairs"!

To add a new target like "chair" without starting from scratch, you can use your existing model as a pre-trained model and continue training it with a dataset that includes images of chairs. This way, you're leveraging the knowledge your model has already gained. Here's a quick guide on doing it:

1. Prepare your dataset with images of "chair" and their annotations, along with the images and annotations for "door" and "stairs" if you wish to maintain their recognition capabilities.
2. Update your dataset configuration file (e.g., `data.yaml`) to include the new "chair" class along with the existing classes.
3. Start the training using the command below, specifying your existing model file with the `--weights` argument to continue training on top of it:

```bash
yolo train --data data.yaml --cfg yolov8.yaml --weights path/to/your/existing/model.pt
```

This approach helps your model learn about the new "chair" class while retaining its ability to recognize "door" and "stairs". Good luck with your training! 🚀

**Comment by BobbleHatkjh** [comment]
very thanks! i will have a try
thanks alot again :)

**Comment by glenn-jocher** [comment]
@BobbleHatkjh you're welcome! 😊 If you have any further questions or need assistance as you proceed, feel free to reach out. Happy training and best of luck! 🚀
