### ISSUE TITLE
yolov8 anchor free

### ISSUE THREAD

**Issue by alicera** [ultralytics/ultralytics#939]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Do you know where is the process of the anchor free code for export onnx

**Comment by AyushExel** [comment]
@JustasBart again I think this is similar to what you've worked on recently with ONNX export right?

**Comment by JustasBart** [comment]
Hi @alicera if you mean processing the ONNX outputs then you can check out this [C++ example](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX.git) which mainly comes down to this:

```
float *classes_scores = data+4;

cv::Mat scores(1, classes.size(), CV_32FC1, classes_scores);
cv::Point class_id;
double maxClassScore;

minMaxLoc(scores, 0, &maxClassScore, 0, &class_id);

if (maxClassScore > modelScoreThreshold)
{
    confidences.push_back(maxClassScore);
    class_ids.push_back(class_id.x);

    float x = data[0];
    float y = data[1];
    float w = data[2];
    float h = data[3];

    int left = int((x - 0.5 * w) * x_factor);
    int top = int((y - 0.5 * h) * y_factor);

    int width = int(w * x_factor);
    int height = int(h * y_factor);

    boxes.push_back(cv::Rect(left, top, width, height));
}
```
There seems to be plenty of examples in Python as well such as [this](https://github.com/ibaiGorordo/ONNX-YOLOv8-Object-Detection).

Hope this helps :rocket:

**Comment by alicera** [comment]
Thanks a lot. 

I found the processing of the anchors.
Can I think that the the processing of anchors free just make the grid SxS and  set the grid coordinate?
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/modules.py#L381
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/utils/tal.py#L209


And the anchor free and the others decode  processing are export to onnx.  Follow your c++ code. It look like only do the x,y,w,h. It is so great

**Comment by pderrenger** [comment]
@alicera absolutely! The processing of anchor-free involves setting the grid coordinates within the SxS grid. The `modules.py` file you referenced handles this grid setup, while the `tal.py` file is involved in the anchor-free and other decoding processing, which is then exported to ONNX. Similar to the C++ code you shared, the ONNX export focuses on handling x, y, w, and h, resulting in a streamlined and efficient process. It's great to see how these components come together for effective deployment!

**Comment by glenn-jocher** [comment]
@pderrenger You've got it right! The anchor-free process indeed involves setting up the grid coordinates on an SxS grid. The code in `modules.py` takes care of this grid setup, and `tal.py` is used for decoding, which includes the anchor-free process. When exporting to ONNX, the focus is on the x, y, w, h outputs, simplifying the post-processing steps. It's fantastic to see you piecing together the workflow for deployment. Keep up the great work! 🚀
