### ISSUE TITLE
Example of Counting People by Line Crossing without CENTER ID Dependency on YOLOv8

### ISSUE THREAD

**Issue by Rasantis** [ultralytics/ultralytics#9398]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello YOLOv8 team and community,

Do you have an example where counting people by line crossing does not depend on the ID, but rather solely on the crossing of the bounding box? I'm working in a scenario where tracking/centerID does not remain constant due to the camera position, however, the detection works perfectly! Would you have a script illustrating this count without depending on the ID?

**Comment by glenn-jocher** [comment]
@Rasantis hi there! 👋

Thanks for reaching out! It sounds like you're looking for an approach that focuses on detecting line crossings without relying on tracking IDs. Here's a simplified example using Python that might help. The idea here is to monitor the centroid of the bounding box for each person and check if it crosses a predefined line:

```python
def check_line_crossing(bbox_center, line_start, line_end):
    # Assuming line_start and line_end are (x, y) tuples defining the line
    # bbox_center is a (x, y) tuple representing the centroid of the bounding box
    x, y = bbox_center
    x1, y1 = line_start
    x2, y2 = line_end
    
    # Calculate line equation parameters
    A = y2 - y1
    B = x1 - x2
    C = (x2 * y1) - (x1 * y2)
    
    # Substitute bbox_center into line equation
    position = (A * x) + (B * y) + C
    
    # If position is greater than 0, it means it has crossed the line
    return position > 0

# Define your line start and end points
line_start = (100, 150)  # Example values
line_end = (300, 150)

# Example usage during your detection loop
for detection in detections:
    x_center = (detection[0] + detection[2]) / 2
    y_center = (detection[1] + detection[3]) / 2
    bbox_center = (x_center, y_center)
    
    if check_line_crossing(bbox_center, line_start, line_end):
        print("Line crossed!")
```

This basic example checks if the center of a bounding box has crossed a predefined line by using the line equation. Adjustments might be needed based on your specific scenario, especially considering the orientation and position of the line.

I hope this helps! Let us know if you have more questions. 😊

Happy coding!
