### ISSUE TITLE
Multi-scale split of DOTA dataset 

### ISSUE THREAD

**Issue by LeiaJ520** [ultralytics/ultralytics#9401]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I downloaded DOTA dataset, but the following error occurred when I tried to do multi-scale cropping. 
![A_)(6UM1AEPOF2BS5`PXGS9](https://github.com/ultralytics/ultralytics/assets/95119550/54f23129-2677-424e-8e59-49468c66c7c9)
![Uploading A_)(6UM1AEPOF2BS5`PXGS9.png…]()

DOTAdataset's structure
![} 3%W_9 7L0LAR $N5J(4VG](https://github.com/ultralytics/ultralytics/assets/95119550/76bf8fb2-6243-4314-a388-727f296697ac)

python split.py
![G%T`6NS_5~13LM{ WWOHTZL](https://github.com/ultralytics/ultralytics/assets/95119550/12ded429-2a4d-43ed-9c45-2db0b6a04e0f)

The current DOTA dataset has not undergone label conversion.

**Comment by glenn-jocher** [comment]
@LeiaJ520 hey there! 👋 It looks like there was an issue with the image links in your post, so I couldn't see the specific error you encountered with the DOTA dataset multi-scale cropping. However, to help you get started, ensure that your dataset directory structure and paths in your script are correctly set up.

For example, if your DOTA dataset structure is as follows:
```
DOTA/
├── images/
│   ├── P0001.png
│   ├── P0002.png
│   ...
└── labels/
    ├── P0001.txt
    ├── P0002.txt
    ...
```

Make sure that your script is correctly pointing to the images and labels directories for processing. Also, ensure that your script handles the DOTA dataset format correctly, especially considering the unique aspects of satellite imagery and object orientations.

If you're using a custom script for multi-scale cropping, you might want to check paths, image extensions, and ensure the labels are in a format compatible with your processing script. Sometimes, a simple typo or path issue can cause errors.

Could you provide more details on the error message or describe what you see when the issue occurs? That would help in pinpointing the exact problem. 

Looking forward to helping you solve this! 🚀

**Comment by LeiaJ520** [comment]
Thank you for your answer. I would like to ask how the train, val and test dataset sets are placed in the DOTA dataset structure. When doing multi-scale cropping of DOTA dataset, should I crop the picture first and then convert it to yolo obb format label?  Or should I convert the label to yolo obb format first and then crop it?

**Comment by glenn-jocher** [comment]
@LeiaJ520 hey there! 😊

For the DOTA dataset and multi-scale cropping, it's generally more efficient to first convert your labels to the YOLO OBB format before cropping the images. This way, you ensure that the labels are correctly aligned with the cropped image sections.

Your dataset structure can be organized into separate directories for training, validation, and testing sets like so:

```
DOTA/
├── train/
│   ├── images/
│   └── labels/
├── val/
│   ├── images/
│   └── labels/
└── test/
    ├── images/
    └── labels/
```

After converting labels to YOLO OBB format, you can proceed with the cropping operation on the images. This order helps maintain consistency and accuracy in your dataset, especially important for precise object detection tasks with oriented bounding boxes (OBB).

Hope this helps! Let us know if you have any more questions. 🌟
