### ISSUE TITLE
Displaying frame settings

### ISSUE THREAD

**Issue by APAKGRUP** [ultralytics/ultralytics#9402]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I am working on a new project that uses a Yolo model for feature detection. To show out the detections, I used something similar to this bunch of code:

```
      annotated_frame = results[0].plot()

        # Display the annotated frame
        cv2.imshow("YOLOv8 Inference", annotated_frame)
```

the issue is that I could not edit some output frame settings like hiding the confidence score.
Any help, please?

**Comment by glenn-jocher** [comment]
@APAKGRUP hey there! 😊 Quick tip for customizing the display settings when plotting your annotated frames: You can control whether confidence scores are shown in the `plot()` method by tweaking its arguments. To hide the confidence scores on your detected objects, just set the `conf` argument to `False` like so:

```python
annotated_frame = results[0].plot(conf=False)
cv2.imshow("YOLOv8 Inference", annotated_frame)
```

This should give you the clean output you're looking for! Let me know if you need further assistance.

**Comment by APAKGRUP** [comment]
> @APAKGRUP hey there! 😊 Quick tip for customizing the display settings when plotting your annotated frames: You can control whether confidence scores are shown in the `plot()` method by tweaking its arguments. To hide the confidence scores on your detected objects, just set the `conf` argument to `False` like so:
> 
> ```python
> annotated_frame = results[0].plot(conf=False)
> cv2.imshow("YOLOv8 Inference", annotated_frame)
> ```
> 
> This should give you the clean output you're looking for! Let me know if you need further assistance.

Thank you so much, dear. I will try this. Sorry for my late response.

**Comment by glenn-jocher** [comment]
@APAKGRUP no worries about the late response! 😊 If you have any more questions or need further assistance after trying out the solution, feel free to reach out. Happy coding!
