### ISSUE TITLE
How to output prediction boxes based on different confidence thresholds for each class in yolov8

### ISSUE THREAD

**Issue by mgalDADUFO** [ultralytics/ultralytics#9403]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Could you please tell me how to make the confidence scores for different classes vary in the output of the predict function in YOLOv8 detect task, instead of having all classes output with the same confidence score?  like this picture?
![企业微信截图_17117025948199](https://github.com/ultralytics/ultralytics/assets/165372434/8bd11cf5-d140-4a8d-aeaf-1bda9d0a42d9)

### Additional

https://blog.csdn.net/FriendshipTang/article/details/134210530
https://liumin.blog.csdn.net/article/details/121034765?spm=1001.2101.3001.6650.2&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-2-121034765-blog-134210530.235%5Ev43%5Epc_blog_bottom_relevance_base9&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-2-121034765-blog-134210530.235%5Ev43%5Epc_blog_bottom_relevance_base9&utm_relevant_index=5

**Comment by glenn-jocher** [comment]
@mgalDADUFO hi there! 👋

To apply different confidence thresholds for each class with YOLOv8 during prediction, you can filter the results after predictions are made instead of applying different thresholds directly during prediction. Here's a brief way to do this:

1. Perform prediction normally without applying class-specific thresholds:
    ```python
    from ultralytics import YOLO

    model = YOLO('yolov8n.pt')  # Load your model
    results = model.predict('your_image.jpg')
    ```

2. Filter the results based on the class-specific thresholds:
    ```python
    class_thresholds = {0: 0.5, 1: 0.3}  # Example thresholds for class 0 and 1
    filtered_boxes = []

    for i, (cls, conf, box) in enumerate(zip(results.cls, results.conf, results.boxes)):
        if conf > class_thresholds.get(int(cls), 0.25):  # Use a default confidence of 0.25 for classes without specific thresholds
            filtered_boxes.append(box)
    ```

In this example, `class_thresholds` is a dictionary where keys are class indices, and values are the desired confidence thresholds. After prediction, results are filtered through a simple loop that checks thresholds from the `class_thresholds` dict.

This approach provides flexibility to adjust confidence levels per class after making predictions, rather than trying to modify the model's internal prediction mechanics to output variable confidence scores directly.

Let me know if you need any more help!

**Comment by mgalDADUFO** [comment]
@glenn-jocher  THANK YOU FOR YOUR REPLY!
THERE IS AN ERROR WHEN I TRY ABOVE METHODS, THAT IS 
"ATTRIBUTE ERROR: 'LIST' OBJECT HAS NO ATTRIBUTE 'CLS' ",WHAT SHOULD I DO TO SOLVE THIS PROBLEM?
HOPE YOU REPLY!

**Comment by glenn-jocher** [comment]
@mgalDADUFO hey there! 😊

It looks like there was a slight misunderstanding in the example provided. My apologies for that. Results from `.predict` are actually returned as a list of `Results` objects when multiple images are passed, or a single `Results` object for a single image.

To fix the error, ensure you're working with a single `Results` object or iterating over each `Results` object if you have a list. Here's a quick example for a single image scenario:

```python
from ultralytics import YOLO

# Assuming 'results' is a single 'Results' object from prediction
model = YOLO('yolov8n.pt')
results = model.predict('your_image.jpg')

# Access attributes like this for a single prediction
boxes = results.boxes
classes = results.boxes.cls
confidences = results.boxes.conf
```

And for multiple images:

```python
results = model.predict(['img1.jpg', 'img2.jpg'])
for result in results:
    boxes = result.boxes
    classes = result.boxes.cls
    confidences = result.boxes.conf
    # Your filtering logic here
```

This should solve the `AttributeError` issue you're facing. Don't hesitate to reach out if you need more help!

**Comment by mgalDADUFO** [comment]
@glenn-jocher   thanks,it helped a lot!
And another question is how to show the above new boxes and theirs labels on pictures like before? which code/where i can modify?

**Comment by glenn-jocher** [comment]
@mgalDADUFO Fantastic to hear that helped! 🎉 For displaying the filtered boxes and labels on your images, you can achieve this by leveraging the `.plot()` method available on the `Results` object. After filtering your boxes, use something like this:

```python
# Assuming 'results' is your filtered Results object
results.plot()  # This will display the image with detections

# If you want to save the image with detections instead of displaying it
results.save(filename='path_to_save/your_image_with_boxes.jpg')
```

If you manually filtered the boxes and have separate lists for boxes, confidences, and class labels, you might need to write a custom plot function using libraries like OpenCV or Matplotlib to draw the boxes and labels on your images.

Here's a quick starter example using OpenCV:

```python
import cv2

image = cv2.imread('your_image.jpg')
for box in filtered_boxes:  # Assuming 'filtered_boxes' is a list of your filtered bbox coordinates
    x1, y1, x2, y2 = box
    cv2.rectangle(image, (int(x1), int(y1)), (int(x2), int(y2)), color=(255, 0, 0), thickness=2)

cv2.imshow('Filtered Detections', image)
cv2.waitKey(0)
cv2.destroyAllWindows()
```

This example should guide you in the right direction. Feel free to adjust the box coordinates and drawing parameters as necessary! Hope this helps, and happy coding! 🚀
