### ISSUE TITLE
Convert *.pt files to *.weights

### ISSUE THREAD

**Issue by Swatun** [ultralytics/ultralytics#941]
Hello

I trained the model for segmentation, and now I want to use it in my Python code, but it is saved in .pt file. To use it with OpenCV I need *.weights and .cfg files. When i use it with ultralytics library and this code:

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/AI/AI_v0.pt')
results = model("/content/drive/MyDrive/AI/2.png")
print('\n\n\n')
print(results)

I getting this data:

[Ultralytics YOLO <class 'ultralytics.yolo.engine.results.Boxes'> masks
type: <class 'torch.Tensor'>
shape: torch.Size([12, 6])
dtype: torch.float32
 + tensor([[1.73000e+02, 6.05000e+02, 2.35000e+02, 8.27000e+02, 9.72734e-01, 0.00000e+00],
        [1.18000e+03, 1.78000e+02, 1.19800e+03, 2.24000e+02, 7.43283e-01, 0.00000e+00],
        [2.00000e+00, 2.46000e+02, 1.93000e+02, 6.27000e+02, 7.19931e-01, 0.00000e+00],
        [6.01000e+02, 2.00000e+02, 7.18000e+02, 2.67000e+02, 6.99744e-01, 0.00000e+00],
        [1.74000e+02, 1.75000e+02, 9.99000e+02, 8.91000e+02, 5.84899e-01, 0.00000e+00],
        [7.91000e+02, 5.43000e+02, 9.02000e+02, 6.28000e+02, 5.37030e-01, 0.00000e+00],
        [2.09000e+02, 8.70000e+01, 2.51000e+02, 1.88000e+02, 5.12727e-01, 0.00000e+00],
        [9.90000e+01, 8.74000e+02, 1.09000e+02, 8.94000e+02, 4.21027e-01, 0.00000e+00],
        [2.00000e+00, 2.42000e+02, 1.93000e+02, 9.27000e+02, 3.55947e-01, 0.00000e+00],
        [9.20000e+02, 6.18000e+02, 1.01900e+03, 7.11000e+02, 3.37368e-01, 0.00000e+00],
        [1.50000e+02, 6.05000e+02, 2.35000e+02, 8.37000e+02, 2.99827e-01, 0.00000e+00],
        [9.21000e+02, 0.00000e+00, 9.97000e+02, 1.84000e+02, 2.63442e-01, 0.00000e+00]], device='cuda:0')Ultralytics YOLO <class 'ultralytics.yolo.engine.results.Masks'> masks
type: <class 'torch.Tensor'>
shape: torch.Size([12, 480, 640])
dtype: torch.float32
 + tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0')]

and I can't decode it.

Thank you for your help in advance.

**Comment by AyushExel** [comment]
You probably need to convert the model to ONNX or other formats that can be directly loaded in opencv. I think @JustasBart tried something like that recently with ONNX. Can you help here?

**Comment by JustasBart** [comment]
Hi @Swatun, it's exactly what @AyushExel had said, OpenCVs DNN module supports ONNX models ```cv::dnn::readNetFromONNX("model.onnx")``` for C++ and:
```
import onnx

model = onnx.load("model.onnx")
```
In Python.

To export the .pt as .onnx use the following:

```
yolo export \
model=yolov8s-seg.pt \
imgsz=[640,640] \
format=onnx \
opset=12
```
Obviously use your own **best.pt** model instead of **yolov8s-seg.pt** do note that the resolution is implemented as [H,W] if you have a non-rectangular model.

The rest should just be running Inference and parsing the Segmentations.

I hope this helps, good luck :rocket:

**Comment by JustasBart** [comment]
@Swatun If you want a practical example using an ONNX model I can see examples such as [this](https://github.com/ibaiGorordo/ONNX-YOLOv8-Instance-Segmentation) and [this](https://github.com/BogdanMarghescu/YOLOv8-Object-Detection-and-Image-Segmentation), maybe one of those might be of use to you?

**Comment by Swatun** [comment]
@JustasBart after I load the model with "model = onnx.load("model.onnx")" how can I load image to it?

**Comment by dragan07-07** [comment]
You must create blob from image, and then use func net.setInput(blob).

**Comment by Swatun** [comment]
@dragan07-07  What is "blob", and how can I create it from image?

**Comment by dragan07-07** [comment]
here is example of CPP code :

 cv::dnn::blobFromImage(frame, blob, 0.00392, cv::Size(640, 640), cv::Scalar(), true, false, CV_32F);
 net.setInput(blob);

**Comment by Swatun** [comment]
@dragan07-07  Do you know how to code this in Python?

**Comment by dragan07-07** [comment]
# Using blob function of opencv to preprocess image
  blob = cv2.dnn.blobFromImage(img, 1 / 255.0, (416, 416), swapRB=True, crop=False)
#Detecting objects
    net.setInput(blob)

**Comment by Swatun** [comment]
I wrote this code:

`import cv2
import onnx

net = onnx.load("/content/drive/MyDrive/AI/AI_v0.onnx")
img = cv2.imread("/content/drive/MyDrive/AI/2.png")
blob = cv2.dnn.blobFromImage(img, 1 / 255.0, (416, 416), swapRB=True, crop=False)
net.setInput(blob)`

But when I run it I get this error:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-11-791e5928655d>](https://localhost:8080/#) in <module>
      5 img = cv2.imread("/content/drive/MyDrive/AI/2.png")
      6 blob = cv2.dnn.blobFromImage(img, 1 / 255.0, (416, 416), swapRB=True, crop=False)
----> 7 net.setInput(blob)

AttributeError: setInput`

**Comment by dragan07-07** [comment]
> 

You can't load onnx like you wrote.
Here is code
net = cv2.dnn.readNet("/content/drive/MyDrive/AI/AI_v0.onnx")

**Comment by Swatun** [comment]
Ok, now it's working.
How can i print results of predict?

**Comment by dragan07-07** [comment]
This is depends of model which one you using?

**Comment by Swatun** [comment]
YOLOv8 trained for custom segmentation

**Comment by dragan07-07** [comment]
You will have to find an example somewhere or write a prediction yourself. You have to see what your output is, and then make a prediction. I would help you, but I didn't do segmentation prediction.

**Comment by Swatun** [comment]
How can I see my output?

**Comment by dragan07-07** [comment]
Use Netron to see output of your onnx

**Comment by Alberto1404** [comment]
> e. To use it with OpenCV I need *.weights and .cfg files. When i use it with ultralytics library and this c

@Swatun Go to [this repo](https://github.com/marcoslucianops/DeepStream-Yolo) and execute [gen_wts_yolov8.py](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/utils/gen_wts_yoloV8.py). 
This takes as input the .pt file and returns as output the desired .wts and .cfg

**Comment by Swatun** [comment]
@Alberto1404  It may be the solution of my problem. Where can I input my model path or something like that?

**Comment by Swatun** [comment]
Ok, I've come to that myself and I succesfully generated wts and cfg files. But when I wsing them in this code:

`import cv2

net = cv2.dnn.readNet("/content/yolov8_custom.wts", "/content/yolov8_custom.cfg")
model = cv2.dnn_DetectionModel(net)
model.setInputParams(size=(320, 320), scale=1/255)

classes = []
with open('/content/classes.txt', 'r') as file_object:
    for class_name in file_object.readlines():
        class_name = class_name.strip()
        classes.append(class_name)


cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()

    (class_ids, scores, bboxes) = model.detect(frame)
    for class_id, score, bbox in zip(class_ids, scores, bboxes):
        (x, y, w, h) = bbox
        print(x, y, x, h)
        cv2.putText(frame, str(classes[class_id]), (x, y - 10), cv2.FONT_HERSHEY_PLAIN, 2, (255, 0, 0), 2)
        cv2.rectangle(frame, (x, y), (x + w, y + h), (255, 0, 0), 3)

    print("class ids", class_ids)
    print("scores", scores)
    print("bboxes", bboxes)

    cv2.imshow("Frame", frame)
    cv2.waitKey(1)`

I'm getting this error:

`---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
[<ipython-input-8-956a31651978>](https://localhost:8080/#) in <module>
      1 import cv2
      2 
----> 3 net = cv2.dnn.readNet("/content/yolov8_custom.wts", "/content/yolov8_custom.cfg")
      4 model = cv2.dnn_DetectionModel(net)
      5 model.setInputParams(size=(320, 320), scale=1/255)

error: OpenCV(4.6.0) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:250: error: (-212:Parsing error) Unsupported activation: silu in function 'setActivation'`

**Comment by pderrenger** [comment]
@Swatun i see that you're trying to use the YOLOv8 model in OpenCV, but it looks like there's an error related to unsupported activation ("silu"). This might be due to an incompatibility with the specific activation function used in your YOLOv8 model and the version of OpenCV you're using.

To resolve this issue, you can try converting the model to use a supported activation function before using it with OpenCV. You could also check if there's a newer version of OpenCV available that supports the "silu" activation function, or consider using a different activation function in your YOLOv8 model before converting it to a format compatible with OpenCV.

Additionally, you may want to reach out to the OpenCV community or the developers of the YOLOv8 model to see if there are any known workarounds or updates that address this compatibility issue.

Let me know if you need further assistance or clarification on this matter.

**Comment by Swatun** [comment]
@pderrenger Thank you for answer. I solved an issue a while ago, becouse new version of ultralytics library made things much easier. Also ultralytics docs was very helpful (Especially this part: https://docs.ultralytics.com/modes/predict/#inference-sources).
