### ISSUE TITLE
How to monitor images on the desktop in real time. Yolov8

### ISSUE THREAD

**Issue by Mger96** [ultralytics/ultralytics#9415]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I apologize in advance. English is not my native language.

How can I track objects from the monitor screen in real time? I was able to display the recording from the screen. But how can you make yolo find objects?

```
import cv2
import numpy
import time
from mss import mss
from datetime import datetime
from threading import Timer
from ultralytics import YOLO

model = YOLO('best.pt')

with mss() as sct:
    
    def screen_record_efficient():

        font = cv2.FONT_HERSHEY_SIMPLEX 
        last_time = time.time()                    
        mon = {"top": 100, "left": 0, "width": 1000, "height": 600}

        title = "[MSS] FPS benchmark"
        new_frame_time, prev_frame_time, fps=0,0,0
        
        wds = 0
        wdse = 0

        last_time = time.time()

        while time.time() - last_time < 100:

            img = numpy.asarray(sct.grab(mon))          
                       
            wds=wds+1
            new_frame_time=time.time()

            if (new_frame_time-prev_frame_time)!=0:     
                fps =1/(new_frame_time-prev_frame_time)                
                
            prev_frame_time=new_frame_time
            fps=int(fps)
            
            wdse=(wdse+fps)            

            cv2.putText(img,str(int(wdse/wds)),(7,40),font,1,(100,255,0),3, cv2.LINE_AA)
            
            imS= cv2.resize(img,(1000,600))
            
            model.track()
            cv2.imshow(title,imS)                        

            if cv2.waitKey(1) & 0xFF == ord("q"):
                cv2.destroyAllWindows()
                break
        
        return fps
    
    print("MSS:", screen_record_efficient())
```

![image](https://github.com/ultralytics/ultralytics/assets/45341922/4a78dd92-713e-4a48-bcd6-59cc08c746d1)

**Comment by glenn-jocher** [comment]
@Mger96 hey there! 😄👋 Your English is fine, and I'm here to help.

For tracking objects on your monitor using YOLOv8, you can modify your script slightly to predict on the captured screen frames. Just replace the `model.track()` with `results = model(imS)` to make predictions, and then use `results[0].plot()` to visualize the detections on your screen capture.

Here’s how you can adjust your loop for object detection:

```python
while time.time() - last_time < 100:
    img = numpy.asarray(sct.grab(mon))   
    imS = cv2.resize(img, (1000, 600))

    # Run YOLO inference on the screen capture
    results = model(imS)
    
    # Visualize the detections
    annotated_image = results[0].plot()
    cv2.imshow(title, annotated_image)

    if cv2.waitKey(1) & 0xFF == ord("q"):
        cv2.destroyAllWindows()
        break
```

This will allow YOLO to detect objects on your screen in real-time. Press 'q' to quit the display window. Hope this helps! Let me know if you have any more questions or need further assistance. 🚀

**Comment by Mger96** [comment]
[Гленн-Джокер]

Спасибо больше. Возникла проблема с каналами, но я решил проблему с помощью преобразования. cv2.cvtColor.

And everything worked.

**Comment by glenn-jocher** [comment]
@Mger96 hey there! 🎉

Fantastic news! I'm thrilled to hear you've successfully resolved the issue with the channels using `cv2.cvtColor`. Creative troubleshooting like yours is what keeps the community vibrant and resourceful. If you ever run into more puzzles or have insights to share, feel free to drop a message. Happy detecting with YOLOv8! 🚀
