### ISSUE TITLE
Tracking 

### ISSUE THREAD

**Issue by shimaamorsy** [ultralytics/ultralytics#9418]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can yolo be used to track objects in video ?

**Comment by glenn-jocher** [comment]
@shimaamorsy absolutely, YOLOv8 can be used for object tracking in videos! 👍 You can utilize YOLOv8's tracking capabilities by using the `track` mode in combination with a detection, segmentation, or pose model of your choice. Here's a quick example using Python:

```python
from ultralytics import YOLO

# Load your model (replace 'yolov8n.pt' with your model path if custom)
model = YOLO('yolov8n.pt')

# Track objects in a video (replace 'path/to/your/video.mp4' with your video path)
results = model.track(source='path/to/your/video.mp4', show=True)
```

Or, if you prefer using the command line interface (CLI):

```bash
yolo track model=yolov8n.pt source=path/to/your/video.mp4
```

Make sure to replace `'yolov8n.pt'` and `'path/to/your/video.mp4'` with the paths to your specific model and video, respectively. Happy tracking! 🚀
