### ISSUE TITLE
How to avoid using clearml during training

### ISSUE THREAD

**Issue by zhihuaji** [ultralytics/ultralytics#9420]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

My GPU is very slow to connect to Clearml due to regional reasons, which has caused me to get stuck in the process of loading Clearml during training

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by zhihuaji** [comment]
Solved, just write the code in train.py like this
![Uploading 1.png…]()

**Comment by glenn-jocher** [comment]
@zhihuaji hi there! It looks like your image didn't fully upload, but it seems you've found a solution to your issue related to avoiding ClearML during training. If you're sharing a code adjustment that helped, could you please try uploading the image again or, even better, paste the code snippet directly here? This can really benefit others in the community facing similar issues. Thanks for sharing your solution! 😊
