### ISSUE TITLE
Object detection from a folder where new images are constantly being written

### ISSUE THREAD

**Issue by Sparklexa** [ultralytics/ultralytics#9425]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I want to speed up the detection by parallel processing of camera and object detection. First of all, the pictures obtained by my camera will be temporarily stored in a folder, and new pictures will be added continuously. I need to read the files from the folder and detect them through yolov8. How do I write the code.

**Comment by glenn-jocher** [comment]
@Sparklexa hey there! 👋

Great to hear you're looking to leverage YOLOv8 for real-time detection with your camera setup. Here’s a quick Python script that continually monitors a folder for new images and processes them with YOLOv8 for object detection. This script uses a simple loop to check for new images and `ultralytics` library for detection.

```python
import os
import time
from ultralytics import YOLO
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

class NewImageHandler(FileSystemEventHandler):
    def __init__(self, model):
        self.model = model

    def on_created(self, event):
        # Making sure it's a file, not a directory
        if not event.is_directory:
            print(f"New image detected: {event.src_path}")
            results = self.model(event.src_path)
            # Visualization or further processing can be done here
            results.show()  # for example, to simply view the results

# Load the YOLOv8 model
model = YOLO('yolov8n.pt')

# Path to the folder being monitored
folder_path = 'path/to/your/images'

# Setting up the folder observer
event_handler = NewImageHandler(model=model)
observer = Observer()
observer.schedule(event_handler, path=folder_path, recursive=False)
observer.start()

try:
    while True:
        time.sleep(1)
except KeyboardInterrupt:
    observer.stop()
observer.join()
```

This script utilizes the `watchdog` package for monitoring directory changes, which you can install with `pip install watchdog` if you haven't already. It listens for any new files added to `folder_path` and processes them through the loaded YOLOv8 model. You may customize it further, depending on your specific requirements, like adjusting for batch processing or performing additional actions with detected results. Happy coding! 😊
