### ISSUE TITLE
 PyTorch to Torchscript with FP16 Quantization

### ISSUE THREAD

**Issue by tdengs** [ultralytics/ultralytics#9430]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, the export function did not offer FP16 quantization for Torchscript conversion. Would you be able to provide me some ideas on how I can achieve PyTorch to Torchscript with FP16 Quantization?

Thank you so much

**Comment by Chonemina** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> ### Question
> Hi, the export function did not offer FP16 quantization for Torchscript conversion. Would you be able to provide me some ideas on how I can achieve PyTorch to Torchscript with FP16 Quantization?
> 
> Thank you so much
> 
> ### Additional
> _No response_

Ive just got a similar question,any1 have a good idea:>?

**Comment by tdengs** [comment]
Hey @Chonemina , this is being further discussed in this thread (I have still yet to resolve it) - https://github.com/ultralytics/ultralytics/issues/9156#issuecomment-2030720263
