### ISSUE TITLE
Does pose training support multiple classifications with different key point numbers?

### ISSUE THREAD

**Issue by shoogoome** [ultralytics/ultralytics#9431]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I would like to ask, I hope to train two categories in one pose model, but the number of key points of the two categories is different. I see that the number of key points in the configuration file seems to be a global configuration? Can they be configured separately? Or do I need to fill in key point data by default for categories with a small number of key points?

**Comment by glenn-jocher** [comment]
@shoogoome hello! 😊

You're correct that the number of keypoints is defined globally in the configuration file for YOLOv8 pose models. If you're training a model with classes having different numbers of keypoints, all classes must conform to a "maximum" keypoint schema set in the configuration. For classes with fewer keypoints, you would indeed have to pad their keypoint data to match this schema. 

A common approach is to use non-visible/invalid keypoint markers (such as -1 for both x and y coordinates) for those extra points in classes with fewer keypoints. Here's a brief example assuming a maximum of 5 keypoints, where a class with only 3 would look something like this in your dataset annotations:

```plaintext
# For a class with 3 keypoints:
x1, y1, visible1, x2, y2, visible2, x3, y3, visible3, -1, -1, 0, -1, -1, 0
```

The `-1, -1` indicate non-existent keypoint positions, and `0` for visibility denotes these points should be ignored during training and inference.

Hope this helps! If you have more queries, feel free to ask.

**Comment by shoogoome** [comment]
> 你好！😊
> 
> 您说得对，关键点的数量是在 YOLOv8 姿态模型的配置文件中全局定义的。如果使用具有不同数量关键点的类来训练模型，则所有类都必须符合配置中设置的“最大”关键点架构。对于关键点较少的类，您确实必须填充其关键点数据以匹配此架构。
> 
> 一种常见的方法是对具有较少关键点的类中的那些额外点使用不可见/无效的关键点标记（例如 x 和 y 坐标的 -1）。下面是一个简短的示例，假设最多有 5 个关键点，其中只有 3 个关键点的类在数据集注释中如下所示：
> 
> ```
> # For a class with 3 keypoints:
> x1, y1, visible1, x2, y2, visible2, x3, y3, visible3, -1, -1, 0, -1, -1, 0
> ```
> 
> 表示不存在的关键点位置，并且为了可见性，表示在训练和推理期间应忽略这些点。`-1, -1``0`
> 
> 希望这会有所帮助！如果您有更多疑问，请随时提问。

Thank you for your reply. I have tried this method and have a few questions
1. When setting -1 to 10, an error message appears. I changed it to 0 0 0, but I am not sure if using 0 0 0 is correct
2. If I include two categories in one training session (one without keypoints (later referred to as category 0) (filled with 0 0 0), and one with four keypoints (later referred to as category 1), then category 0 is not trained, but if the same data removes the label of category 1, then category 0 can be recognized
May I ask how to handle the above issue? Thank you
<img width="867" alt="1711885174560" src="https://github.com/ultralytics/ultralytics/assets/34764574/28d74e41-1bf5-4aba-9834-6e89819822be">
![image](https://github.com/ultralytics/ultralytics/assets/34764574/00c9ddbb-a917-4563-83cb-fde0d2e984ec)

**Comment by glenn-jocher** [comment]
@shoogoome hey! 😊 Thanks for reaching out with your follow-up questions.

1. **Regarding `-1 -1 0` vs `0 0 0`:** It sounds like the system is indeed flagging negative values as corrupt data. Using `0 0 0` should be fine if it bypasses the error, and the visibility value (`0`) signals these keypoints should be ignored. However, to prevent potential ambiguity with valid (0, 0) keypoints, it's often recommended to configure the dataset and model to explicitly recognize and distinguish between missing and present but invisible keypoints. Adjusting your data pre-processing or post-processing strategies to handle this might be beneficial.

2. **Regarding the cls0 training issue:** This sounds like a more complex problem that might involve how your model and dataset are set up. Given cls0 (without keypoints) isn't training correctly when cls1 (with keypoints) is present, there might be an issue with how the model interprets classes with and without keypoints. If cls0 and cls1 are intended to learn very different features (one based on general appearance, the other on specific keypoints), combining them in a single model might require careful balancing of the loss contributions or even custom modifications to the training procedure.

Without seeing more about your setup and how your data is prepared, it's a bit tricky to give specific advice. However, a couple of general suggestions:
- Double-check your dataset annotations for consistency and correctness in both cls0 and cls1 scenarios.
- Consider experimenting with separate models for cls0 and cls1 or exploring strategies to weight or segment their contributions differently during training.

This is an intriguing challenge, and I'm here to help as you explore solutions! Sharing more details or examples of your data and setup could provide further insights. Keep experimenting, and let's keep the conversation going! 🚀
