### ISSUE TITLE
TPU Support (XLA)

### ISSUE THREAD

**Issue by OlaHulleberg** [ultralytics/ultralytics#944]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Adding built-in support for TPU (XLA devices) with the YOLO command.
Currently the only devices supported with --device is CUDA (GPU) and CPU.

This should be pretty straightforward to implement with torch-xla

### Use case

It would be super simple and **fast** to train models with GCP or AWS.
```python
import torch_xla.core.xla_model as xm
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO("modeltotrain.pt")
    model.train(data=yourdata, device=xm.xla_device(), ...)
    ...
```

**Comment by AyushExel** [comment]
I don't have a lot of experience working with TPUs but this seems interesting. Do you have an example that I can follow to build support for this? Or would you be interested in collaborating on this project? Thanks!

**Comment by OlaHulleberg** [comment]
I would imagine the samples provided in the **PyTorch/XLA repo** are a good start.

Here they train [**MNIST**](https://github.com/pytorch/xla/blob/master/test/test_train_mp_mnist.py)
Here they train [**ImageNet**](https://github.com/pytorch/xla/blob/master/test/test_train_mp_imagenet.py)

The [Google Docs](https://cloud.google.com/tpu/docs/pytorch-xla-ug-tpu-vm) on this runs the script(s) like this:
```
python3 xla/test/test_train_mp_imagenet.py --fake_data --model=resnet50 --num_epochs=1
```
<hr>

Not sure how much I am able to contribute right now, given time constraints.

**Comment by pderrenger** [comment]
@OlaHulleberg great, I'll take a look at the PyTorch/XLA repo and the Google Docs to get a better understanding of how to integrate TPU support into the YOLOv8 command. I'll keep you updated on my progress, and if you have any additional input or findings, feel free to share them. Thanks for pointing me in the right direction!

**Comment by miche1e** [comment]
@pderrenger has there been any progress on XLA support?

**Comment by singhsegv** [comment]
@pderrenger same question about XLA support. Is it done or in the pipeline? And if not then I'd love to pick this up and help.
