### ISSUE TITLE
How to call a custom model saved in personal github account other than ultralytics github?

### ISSUE THREAD

**Issue by LakshmySanthosh** [ultralytics/ultralytics#9441]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have forked the ultralytics repository and added a module in my forked repository. While doing training, I want to call these files instead of the original ultralytics files.
How to do this? 
I have cloned this github repository to my notebook where I'm working.

When I tried to do this without installing ultralytics, I'm not able to run code since I cannot import YOLO without ultralytics

When I install ultralytics(`!pip install ultralytics==8.0.196`) and then try to do training, I'm getting error that my `NewClass` is not found
![image](https://github.com/ultralytics/ultralytics/assets/121610033/c3302b85-e6f6-4e5a-b8cc-f2b1ddea17b5)
`KeyError: 'NewClass'`

Do I have to import YOLO from my forked repository? If yes, how to do that?

**Comment by glenn-jocher** [comment]
@LakshmySanthosh hello! 😊 It sounds like you're working on leveraging your custom modifications from your forked repo. Here's a concise way to use your modifications:

1. **Make sure your local clone is up to date** with your GitHub fork. You might need to pull changes if you've updated the fork online.

2. **Install your forked version** directly from GitHub using pip, pointing to your repository URL:

    ```bash
    !pip install git+https://github.com/<YourGitHubUsername>/ultralytics.git
    ```

Make sure to replace `<YourGitHubUsername>` with your actual GitHub username. This command uninstalls the Ultralytics package if it's already installed and replaces it with the version from your repository, including your new `NewClass` module.

Now, when you import `YOLO` or any other class/module from `ultralytics`, it should be importing from the version installed from your fork. 🚀

If you encounter any issues, double-check the path and name of your new class/module in your fork to ensure everything matches up. Happy coding!

**Comment by LakshmySanthosh** [comment]
Thankyou @glenn-jocher 
I tried doing this,
replaced `!pip install ultralytics` with `!pip install git+https://github.com/username/ultralytics.git` 
the whole code was running fine before, but after this change, 

I have saved my edited .yaml file as `yolov8m_custom.yaml` and used this code to run the training
```
# training YOLOv8
%time 
!yolo task=detect mode=train model=/kaggle/working/yolov8m_custom.yaml data={dataset.location}/data.yaml epochs=25 imgsz=416 plots=True
``` 
![image](https://github.com/ultralytics/ultralytics/assets/121610033/bfdddf2e-2919-4f5e-9e8f-2c4181b9aeae)

I have clearly given the yaml file name in the line for training as `yolov8m_custom.yaml`, byt the error shows `yolov8_custom.yaml not found.` 
When I changed the file name to `yolov8a_custom.yaml`, it is working. Not sure what is happening. 
But when I resolved this error, some other error arised related to dataset path. What will be the reason for these new errors. I did'nt make any change in the file except the installing part.

![image](https://github.com/ultralytics/ultralytics/assets/121610033/1047aa17-fe68-4488-afa6-d58efe43ae3a)
This is the new error that is coming.

**Comment by glenn-jocher** [comment]
@LakshmySanthosh, great observation! 😊 Yes, you can work with a specific version (tag) of the Ultralytics repository when you fork or clone it. While you cannot directly fork a specific branch or tag through GitHub's UI, you can certainly clone a specific tag to your local machine. 

To clone a specific version (for example, `8.0.196`), you would first clone the repository and then checkout the specific tag:

```bash
git clone https://github.com/username/ultralytics.git
cd ultralytics
git checkout tags/8.0.196 -b version-8.0.196-branch
```

Replace `username` with your GitHub username if you've already forked the repository. Otherwise, use `ultralytics` to clone the original repo. After that, you can push this local branch to your fork on GitHub:

```bash
git push origin version-8.0.196-branch
```

Now, you can install this specific version directly from your fork:

```bash
!pip install git+https://github.com/username/ultralytics.git@version-8.0.196-branch
```

Just make sure the version tag exists in the Ultralytics repository. Hope this helps!
