### ISSUE TITLE
Slow cv2.imread() with YOLOv8 TFLite on Coral Edge TPU for high-resolution images

### ISSUE THREAD

**Issue by AlaaArboun** [ultralytics/ultralytics#9454]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi everyone,

I'm working on object detection using the YOLOv8 TFLite model on a Coral Edge TPU, specifically for high-resolution images. I'm facing an issue where the cv2.imread() function from OpenCV is significantly slowing down the image preprocessing step.

According to my profiling, the cv2.imread() function is taking around 120ms to read each image, which is a substantial portion of the total preprocessing time. Here's the relevant code snippet:
```bash
def preprocess(self):
        """
        Preprocesses the input image before performing inference.

        Returns:
            image_data: Preprocessed image data ready for inference.
        """

        # Read the input image using OpenCV
        if isinstance(self.input_image, str):
            img = cv2.imread(self.input_image)
        else:
            img = self.input_image

        # Check if resizing is necessary
        if img.shape[:2] != (self.input_shape[1], self.input_shape[2]):
            # Resize the input image to match the model's input shape
            img = cv2.resize(img, (self.input_shape[1], self.input_shape[2]))

        # Convert image to float32 and normalize
        img = img.astype(np.float32) / 255.0

        # Apply normalization
        #img = (img - self.input_zero) / self.input_scale

        img = (img/self.input_scale) + self.input_zero

        img = img[np.newaxis].astype(np.int8)

        # Add batch dimension
        #img_data = np.expand_dims(img, axis=0).astype(np.int8)

        return img


Performing test run: 0%|
Read Image Time: 120.86868 ms
Resize Time: 3.98064 ms
Normalize Time: 0.99993 ms
Quantize Time: 0.00000 ms
Convert Time: 0.00000 ms
Preprocess Time: 125.84925 ms
Inference Time: 44.99745 ms
Postprocess Time: 9.02247 ms

I've tried using both string paths and numpy arrays as input to cv2.imread(), but the issue persists.

Can anyone provide advice or recommendations on how to address this issue? Is there a package or alternative method that can read images faster than OpenCV for this use case? Any suggestions or insights would be greatly appreciated.

Thank you in advance for your help!

### Additional

_No response_

**Comment by glenn-jocher** [comment]
@AlaaArboun hello! 👋 It sounds like you're working on a thrilling project with YOLOv8 and Coral Edge TPU! The `cv2.imread()` delay for high-res images can indeed influence your pipeline's overall speed.

A couple of quick thoughts:
- **Multithreading**: Consider loading images in a separate thread to decouple the image reading process from your main inference workflow. This way, the next image can load while the current one is being processed.
- **Alternative Libraries**: You might find PIL (`Pillow`) or `imageio` faster for your specific use case. Here's a sample snippet using `Pillow`:
  ```python
  from PIL import Image
  import numpy as np

  if isinstance(self.input_image, str):
      img = Image.open(self.input_image)
  img = img.resize((self.input_shape[1], self.input_shape[2]))
  img = np.array(img).astype(np.float32) / 255.0
  ```

Using an alternative library or method like above could potentially speed up the image loading process. Every environment is a bit different, so some experimentation to find the best approach for your setup will be key. Keep us posted on your progress or if you uncover another solution! Happy coding! 🚀
