### ISSUE TITLE
How to Process a Very Long Image

### ISSUE THREAD

**Issue by xulihang** [ultralytics/ultralytics#9457]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi there,

I have some very long images. Do I need to crop them into smaller ones for training and prediction?

![image](https://github.com/ultralytics/ultralytics/assets/5462205/2b0ddd49-5e18-46a6-a02f-fd2de6575ed5)
![image](https://github.com/ultralytics/ultralytics/assets/5462205/6bb0aa3d-57f4-4734-8351-0f8e77a655fa)

**Comment by glenn-jocher** [comment]
@xulihang hi there! 😊

For very long images, you don't necessarily have to crop them for training or prediction, but you might want to resize them to ensure they fit the model's expected input size (`imgsz` parameter) effectively.

Here's an example of how to adjust the `imgsz` parameter for predictions:

```python
from ultralytics import YOLO

# Load model
model = YOLO('yolov8n.pt')  # Replace 'yolov8n.pt' with your model

# Run prediction, adjust imgsz as needed for your images
results = model('path/to/your/long/image.jpg', imgsz=640)
results.show()  # Display the results
```

For training, ensure your dataset images get resized or augmented accordingly. The `imgsz` parameter in your training script can be adjusted in a similar manner. 

Keep in mind that maintaining aspect ratio could be beneficial for avoiding distortion. If aspect ratio concerns arise, consider custom data augmentation strategies that suit your specific use case.

Hope this helps! Let us know if you have more questions.

**Comment by xulihang** [comment]
I see. Thanks.

I also found this repo: https://github.com/obss/sahi 

Will the result be better using it for slicing the images?

**Comment by glenn-jocher** [comment]
@xulihang hey there! 🌟

Great find! The [SAHI repo](https://github.com/obss/sahi) could indeed be helpful for slicing images, especially for long or large ones where targets may be scattered. SAHI allows you to slice into smaller, manageable patches and then recombine detections from these slices. This can enhance detection performance for objects that might otherwise be too small or get distorted when resizing the entire image.

It's worth experimenting with SAHI slicing and seeing if it improves results for your specific use case. Here's a quick example to start with slicing:

```python
from sahi.utils.cv import read_image
from sahi.predict import get_sliced_prediction

# Read your large/long image
image = read_image("path/to/your/image.jpg")

# Perform prediction with slicing
result = get_sliced_prediction(
    image=image,
    model_path="path/to/your/yolov8/model",
    slice_height=640,
    slice_width=640,
)

# Visualize or process the result
```

Give it a try and let us know how it turns out! 🚀

**Comment by BirenMer** [comment]
@glenn-jocher sir,
I have images of size 1080 x 1920 px what happens to the label coordinates of this image, if I stick with the default size of 640 x 640 px. Do they get adjusted as well ?
Thank you

**Comment by glenn-jocher** [comment]
@BirenMer hey there! 🌟

Absolutely, when you resize your images from 1080x1920 px to the default size of 640x640 px for training or prediction with YOLOv8, the label coordinates automatically get adjusted to match the new size. They are scaled proportionally to ensure that the locations remain accurate relative to the resized image. 

For instance, if you originally had a label at (100,200) in a 1080x1920 image, it would be correctly transformed to match the resized dimensions. Here’s a quick example for clarity:

```python
# Original coordinate
x, y = 100, 200

# Image original and new sizes
orig_width, orig_height = 1920, 1080
new_width, new_height = 640, 640

# Adjusted coordinate
new_x = x * (new_width / orig_width)
new_y = y * (new_height / orig_height)
```

This makes sure your labeled objects stay properly aligned with the objects in the resized images. Let me know if there's anything else I can help with! 😊

**Comment by xulihang** [comment]
Based on my experiments, it is better to crop the image into small ones for training and detection.

I've added the similar feature of SAHI in my tool ImageTrans.

Here is a blog on how to use it: https://www.basiccat.org/how-to-train-yolov8-object-detection-model/

**Comment by glenn-jocher** [comment]
@xulihang That's fantastic to hear! 🎉 It's great that cropping images into smaller ones has improved your training and detection using YOLOv8, and incorporating a feature like that in ImageTrans sounds like a beneficial enhancement.

Thanks for sharing your blog post - it looks like a valuable resource for the community exploring similar avenues with YOLOv8. We appreciate your efforts in enhancing toolsets around YOLO and sharing your findings with the community. Keep up the great work!
