### ISSUE TITLE
An Example showing how to use Yolov8-pose tflite int 8 

### ISSUE THREAD

**Issue by Doquey** [ultralytics/ultralytics#9472]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

A brief Example just like the ones you have for the yolov8 detection, so that it is easier for the users to convert and use the pose model in the same manner.

### Use case

...

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hey there, @Doquey! 🌟 Thanks for sharing the details and your code snippets. It looks like you're on the right track with exporting and processing the model, but let's address the issue of getting 0 values for the confidences.

One common cause for confidence scores being set to 0, especially after quantization, might be related to the preprocessing and how inputs are fed into the TFLite model. For INT8 quantization, it’s essential that the input data closely matches the distribution used during the conversion phase, particularly when setting up the `representative_dataset`.

From your code, it seems like you're handling the preprocessing well. However, consider ensuring that the images used in `representative_dataset` function closely match your actual application scenarios in terms of content, lighting, etc.

A quick suggestion to try improving your results would be to adjust the quantization parameters or make sure that the scaling (`scale` and `zero_point`) applied to the output tensors correctly compensates for the quantization transformation.

For experimentation, you might also want to try disabling the `int8` conversion momentarily to check if the confidence values come out as expected in a `float` model:
```python
int8 = False # Temporarily set to False for testing
```

Let’s also pay close attention to how the output tensor is being interpreted. The decoding process for poses might also be affected by how you post-process these outputs. Ensure that this part considers the YOLOv8-pose specifics, especially if there are differences from the typical object detection model outputs.

If you're still facing issues, could you share more about the output post-processing steps you're using to interpret the keypoints from the output tensor? Understanding that might help pinpoint where the misinterpretation of confidence scores could be happening.

Keep me posted on your progress, happy to help further! 😊

**Comment by gerald-ftk** [comment]
@Doquey Did you ever manage to succeed with the yolov8-pose tflite inference? Am currently stuck on the same issue.

**Comment by Xuezha333** [comment]
@Doquey Did you ever manage to succeed with the yolov8-pose tflite inference? Am currently stuck on the same issue.

**Comment by glenn-jocher** [comment]
I'm sorry to hear that. If you decide to revisit this issue, please ensure you're using the latest version of the package, as updates may have resolved the problem. If the issue persists, feel free to open a new issue with detailed information.

**Comment by Xuezha333** [comment]
hi @glenn-jocher, can the reason be due to "metadata.yaml" is actually seperated from the tflite weights, and the model does not have access to preprocess and class info, eg keypoints shape, class name and etc?

**Comment by Xuezha333** [comment]
![image](https://github.com/user-attachments/assets/8c39f2a1-d2d2-4aba-af8e-a69b14c09103)
if it is so, can you please provide guidance on using this weights and yaml on the offical YOLO method, so that we can run inference. Thanks!

**Comment by glenn-jocher** [comment]
@Xuezha333 it’s possible that the separation of `metadata.yaml` from the TFLite weights is causing the issue. Ensure that the metadata is correctly integrated with the model. You can refer to the official YOLO documentation for guidance on using weights and YAML files for inference: https://docs.ultralytics.com.

**Comment by Xuezha333** [comment]
Hi @glenn-jocher, ive tried looking through the docs but didn't find any yaml usage with predict, especially metadata.yaml.

Thus, i tried looking into AutoBackend because i found this issue: "WARNING ⚠️ Metadata not found for 'model={weights}, and was able to load the metadata with this modification
![image](https://github.com/user-attachments/assets/17e04b61-5015-4961-8750-f8c1fc0dde98)

But, after doing such modification, a new error arrises and im still stuck
![image](https://github.com/user-attachments/assets/ac9e448e-0269-40df-8ee9-7998e479a989)

Appreciate any help, Thanks
