### ISSUE TITLE
Full INT8 TFLite Yolov8s losing a lot of performance compared to FP32 TFLite

### ISSUE THREAD

**Issue by Hrayo712** [ultralytics/ultralytics#9473]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

Thanks a lot for the amazing work.

I am exploring Fully quantizing Yolov8s for edge inference. However I am observing substantial performance degradation when evaluating Yolov8s full int8 in COCO2017. Here the performance numbers I am obtaining:

**- Yolov8s (Torch):** `0.449 mAP (IoU=0.50:0.95)`
**- Yolov8s (TFLite FP32):** `0.450 mAP (IoU=0.50:0.95)`
**- Yolov8s (TFLite INT8 - Full INT8):** `0.382 mAP (IoU=0.50:0.95)`

As you can see above, everything seems to go well with the conversion to TFLite (as shown by the FP32 TFLite performance), but there seems to be quite some degradation in the Full int8 version. As a reference, I've fully quantized Yolov5 and YoloX in the past, with rather little performance degradation ( YoloX -> 0.263 FP32 - 0.257 INT8)

**My question is:** Is this behavior expected? I've seen quite some references on other issues, suggesting using dynamic range quantization instead, as it preserves accuracy better. Is that the official route to support quantized inference on YoloV8? or is there any suggestion for preserving mAP better when doing full int8 quantization?

Here the code that I'm using for reproducing the behavior:

 ``` 
from ultralytics import YOLO
from ultralytics.utils import yaml_load
from ultralytics.utils.checks import check_yaml

# get model for evaluation
model = YOLO('yolov8s.pt')

# evaluate baseline performance
results = model.val(data="coco.yaml")

# evaluate to TFLite
model.export(format='tflite', int8=True)

# evaluate TFLite FP32
tflite_yolo = YOLO("yolov8s_saved_model/yolov8s_float32.tflite")
tflite_fp32_results = tflite_yolo.val(data="coco.yaml")

# evaluate TFLite Full INT8
tflite_yolo = YOLO("yolov8s_saved_model/yolov8s_full_integer_quant.tflite")
tflite_int8_results = tflite_yolo.val(data="coco.yaml")
 ``` 

Thanks in advance for your support!

**Comment by glenn-jocher** [comment]
@Hrayo712 hi there! 👋

Firstly, thank you for your kind words and for diving into quantization with YOLOv8 - it's exciting to see your work on edge inference!

Regarding the performance drop you're seeing with the Full INT8 quantization, it's somewhat expected to experience some degree of degradation as quantization reduces the model size and computational requirements at the expense of precision. The drop from FP32 to INT8 is consistent with the nature of aggressive quantization, although the extent can vary based on the model and dataset.

For minimizing the performance degradation:
- Ensure your dataset for calibration during the quantization process is representative of your use case. This can significantly impact the quality of the quantized model.
- Experiment with different quantization configurations. Sometimes, tweaking the parameters can help preserve more accuracy.
- Exploring dynamic range quantization as mentioned could indeed maintain better accuracy for some models. It's worth trying as an alternative if you haven't already.

Additionally, you're already following good practices by comparing performance across different formats and quantization levels. Continuing to compare YOLOv8's quantization outcomes with other models (like YOLOv5 and YoloX, as you've done) can also provide insights into expected behaviors or optimizations that might be specific to YOLOv8's architecture.

Integrating quantization-aware training during the model training phase, if not already done, could help mitigate some performance loss during post-training quantization.

Again, thanks for engaging with the YOLOv8 community, and I hope this helps! Keep exploring, and feel free to reach out for further clarification or share your progress! 🚀

**Comment by Hrayo712** [comment]
For reference, this is a known issue which is covered in this other issue. https://github.com/ultralytics/ultralytics/pull/1695#issuecomment-2030812658

**Comment by glenn-jocher** [comment]
@Hrayo712 hi! 👋 Thanks for reaching out. The performance drop with Full INT8 quantization you're experiencing ties back to a known issue we've discussed in [this thread](https://github.com/ultralytics/ultralytics/pull/1695#issuecomment-2030812658). We recommend exploring dynamic range quantization as it tends to preserve accuracy better for some models. If you have any specific questions or need further assistance after reviewing the thread, don't hesitate to ask! Happy coding! 🚀

**Comment by shashichilappagari** [comment]
Hi @Hrayo712 Performance loss for fully quantized YOLOv8 is a well-known and understood issue. However, the loss is mostly due to the way the model is exported and not an inherent weakness of YOLOv8 (compared to YOLOv5 or YOLOX). At DeGirum, we have solved this problem and shared our solution with the community. We maintain a fork of the ultralytics repo at https://github.com/DeGirum/ultralytics_yolov8.

After cloning our fork, if you run the following code, you will see that the mAP of fully quantized model is much better (0.441 mAP). Hope this helps.

``` python
from ultralytics import YOLO

model = YOLO('yolov8s.pt')

# DeGirum TFLite with simplify=True
model.export(format='tflite', 
             int8=True, 
             separate_outputs=True, 
             export_hw_optimized=True, 
             simplify=True, 
             uint8_io_dtype=True, 
             max_ncalib_imgs=100,
             data="coco128.yaml")

# TFLite FP32
tflite_yolo = YOLO("yolov8s_saved_model/yolov8s_float32.tflite")
tflite_fp32_results = tflite_yolo.val(data="coco.yaml", 
                                      rect=False, 
                                      separate_outputs=True)

# # TFLite Full INT8
tflite_yolo = YOLO("yolov8s_saved_model/yolov8s_full_integer_quant.tflite")
tflite_int8_results = tflite_yolo.val(data="coco.yaml", 
                                      rect=False, 
                                      separate_outputs=True)
```
