### ISSUE TITLE
Identification category and identification box confusion after converting yolo-world.pt to yolo-world.mlpackage using export_coreml

### ISSUE THREAD

**Issue by lizhiwen19900709** [ultralytics/ultralytics#9486]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Use export_coreml to convert yolo-world.pt to yolo-world.mlpackage and then call in yolo-ios-app, there is confusion between identification categories and identification boxes. How to solve this problem?

**Comment by glenn-jocher** [comment]
@lizhiwen19900709 hello! Thanks for reaching out and sharing your concern. 😊 It seems like there might be a mismatch or confusion in the prediction outputs after converting your model to CoreML format. 

A common step to troubleshoot this kind of issue is to verify the class labels and their order. Ensure that the class labels used in the YOLO-iOS-app exactly match those with which the `yolo-world.pt` model was trained. Misalignment here could cause category confusion.

For the identification box issue, it's essential to check that the output tensor sizes and formats are correctly interpreted by your application. CoreML sometimes requires explicit specification of output formats. You might need to process or reshape the output accordingly before using it.

If you're still facing issues, could you share a snippet of how you're handling the output in your iOS app? This might give more insight into what's happening. Here’s a basic structure for reference:

```swift
// Assuming 'modelOutput' is your CoreML model's output
let boundingBoxes = modelOutput.boxes // Check the actual property name based on your MLModel's output
let classProbabilities = modelOutput.scores // Similarly, verify the property name

// Process 'boundingBoxes' and 'classProbabilities' as per your app's logic
```

Remember to match your MLModel's output property names with those used in the app.

Looking forward to hearing from you!

**Comment by lizhiwen19900709** [comment]
> @lizhiwen19900709 hello! Thanks for reaching out and sharing your concern. 😊 It seems like there might be a mismatch or confusion in the prediction outputs after converting your model to CoreML format.
> 
> A common step to troubleshoot this kind of issue is to verify the class labels and their order. Ensure that the class labels used in the YOLO-iOS-app exactly match those with which the `yolo-world.pt` model was trained. Misalignment here could cause category confusion.
> 
> For the identification box issue, it's essential to check that the output tensor sizes and formats are correctly interpreted by your application. CoreML sometimes requires explicit specification of output formats. You might need to process or reshape the output accordingly before using it.
> 
> If you're still facing issues, could you share a snippet of how you're handling the output in your iOS app? This might give more insight into what's happening. Here’s a basic structure for reference:
> 
> ```swift
> // Assuming 'modelOutput' is your CoreML model's output
> let boundingBoxes = modelOutput.boxes // Check the actual property name based on your MLModel's output
> let classProbabilities = modelOutput.scores // Similarly, verify the property name
> 
> // Process 'boundingBoxes' and 'classProbabilities' as per your app's logic
> ```
> 
> Remember to match your MLModel's output property names with those used in the app.
> 
> Looking forward to hearing from you!

I replaced the yolov 8s model in the yolo-ios-app source code with the transformed yolo-world model, and there was an appeal problem. The model can be used, but the labels and boxes are not the actual ones. How do I modify the yolo-ios-app source code?

**Comment by lizhiwen19900709** [comment]
> Hi @lizhiwen19900709! 🌟 It sounds like the labels and boxes mismatch might be related to how the iOS app decodes the model's output. Since the conversion to CoreML and direct Python call works fine, the source code adjustment should focus on correctly parsing the model outputs.您好@lizhiwen19900709！transfIt听起来像标签和盒子不匹配可能与iOS应用程序如何解码模型的输出有关。由于到CoreML的转换和直接Python调用工作正常，因此源代码调整应该专注于正确解析模型输出。
> 
> Here are a couple of things you could look at:这里有几件事你可以看看：
> 
> 1. **Labels Mapping:** Ensure the app has the exact same labels in the same order as the model was trained with. Sometimes, a hardcoded list might not match the model's output.标签映射：确保应用具有与模型训练顺序完全相同的标签。有时，硬编码的列表可能与模型的输出不匹配。
> 2. **Output Parsing:** Double-check how the app parses output tensors from the model. Make sure `boundingBoxes` and `classProbabilities` are aligned with your model's outputs.输出解析：仔细检查应用如何解析模型的输出张量。确保`boundingBoxes`和`classProbabilities`与模型的输出一致。
> 
> A small code adjustment to align the labels could look something like this:一个小的代码调整，以对齐标签可能看起来像这样：
> 
> ```swift
> // Ensure your labels array matches the model's training labels
> let labels = ["label1", "label2", ..., "labelN"]
> 
> // When displaying:
> if let topLabelIndex = classProbabilities.maxIndex() {
>     let label = labels[topLabelIndex]
>     display(label: label, at: boundingBoxes[topLabelIndex])
> }
> ```
> 
> And for output parsing adjustment, closely check your model's output layer names and ensure they match in your decoding logic:对于输出解析调整，请仔细检查模型的输出层名称，并确保它们在解码逻辑中匹配：
> 
> ```swift
> // Adapt these names based on your specific model output
> let boundingBoxes = modelOutput.featureValue(for: "yourModelBoundingBoxesOutput").multiArrayValue
> let classProbabilities = modelOutput.featureValue(for: "yourModelClassProbOutput").multiArrayValue
> ```
> 
> Improper alignment in any of these could lead to the mentioned issues. Let me know if this helps or if you have the specific part of the code you're unsure about!其中任何一种不正确的对齐都可能导致上述问题。让我知道这是否有帮助，或者如果你有你不确定的代码的特定部分！



> 1. Ensure the app has the exact same labels in the same order as the model was trained with

yolov8s-worldv2.pt What is the model training label order?

**Comment by lizhiwen19900709** [comment]
@glenn-jocher

**Comment by lizhiwen19900709** [comment]
yolov8s-worldv2.pt（https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8s-worldv2.pt） What is the label order for model training?

**Comment by lizhiwen19900709** [comment]
Hello，yolov8s-worldv2.pt（[https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8s-worldv2.pt）](https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8s-worldv2.pt%EF%BC%89) What is the label order for model training?  @glenn-jocher

**Comment by glenn-jocher** [comment]
@lizhiwen19900709 hello there! 😊 For the `yolov8s-worldv2.pt` model you've mentioned, the label order matches the categories in the dataset it was trained on, typically arranged alphabetically or by the dataset's default order. To directly fetch the label order, you can load the model using our Python package and inspect the `names` attribute like so:

```python
from ultralytics import YOLO

# Load the model
model = YOLO("yolov8s-worldv2.pt")

# Get the labels
labels = model.names

print("Label order for the model:", labels)
```

This snippet will print out the exact order of labels the model uses for its predictions. Let me know if you need help with anything else!

**Comment by lizhiwen19900709** [comment]
Hello，yolov8s-worldv2.pt on github has only 80 recognition categories. How to customize recognition categories? Huggingface has an online custom recognition category, but it comes out as an onnx format model. How to convert onnx to corem format?
@glenn-jocher

**Comment by glenn-jocher** [comment]
@lizhiwen19900709 hey there! 😊 To customize recognition categories for `yolov8s-worldv2.pt`, you'd typically need to train the model on a dataset that includes your specific categories. This involves creating a custom dataset with your categories labeled, and then training a YOLOv8 model on it.

As for converting an ONNX model to CoreML format, you can use the `coremltools` package in Python. Here's a quick code example:

```python
import coremltools as ct

# Load ONNX model
model_onnx = ct.models.MLModel('path_to_your_model.onnx')

# Convert to CoreML
model_coreml = ct.convert(model_onnx, source='onnx')

# Save the CoreML model
model_coreml.save('custom_model.mlmodel')
```

Just replace `'path_to_your_model.onnx'` with the path to your ONNX file. Hope this helps! Let me know if you have more questions.

**Comment by lizhiwen19900709** [comment]
```
import onnx
import coremltools as ct

#image_inputs = ct.ImageType(shape=(1, 224, 224, 3))
classifier_config = ct.ClassifierConfig('imagenet_slim_labels.txt')

onnx_model = onnx.load_model("yolov8l-world.onnx")
#onnx_model = ct.models.MLModel('yolov8l-world.onnx')
try:
    coreml_model = ct.convert(onnx_model, inputs=[ct.ImageType(name="images", shape=[1, 3, 640, 640])],classifier_config = classifier_config,source='tensorflow',convert_to="mlprogram")
    coreml_model.save('yolov8l_world.mlpackage')
except Exception as e:
    print(e)
```

Unable to save yolov8l_world.mlpackage file successfully！
@glenn-jocher

**Comment by glenn-jocher** [comment]
@lizhiwen19900709 Hello there! 😊 It looks like your script is mostly on the right track. However, I noticed that the `source='tensorflow'` argument might be causing the issue since you're converting an ONNX model and not directly from TensorFlow. Also, ensure your ONNX model is correctly loaded. Try adjusting your `ct.convert` call like this:

```python
coreml_model = ct.convert(
    onnx_model, 
    inputs=[ct.ImageType(name="images", shape=(1, 3, 640, 640))],
    classifier_config=classifier_config,
    source='onnx',  # Use 'onnx' here
    convert_to="mlprogram"
)
```

Give this a shot and feel free to drop a message if you're still facing issues or have more questions!

**Comment by lizhiwen19900709** [comment]
Unrecognized value of argument "source": onnx. It must be one of ["auto", "tensorflow", "pytorch"].
@glenn-jocher

**Comment by lizhiwen19900709** [comment]
Unable to determine the type of the model, i.e. the source framework. Please provide the value of argument "source", from one of ["tensorflow", "pytorch", "milinternal"]. Note that model conversion requires the source package that generates the model. Please make sure you have the appropriate version of source package installed. E.g., if you're converting model originally trained with TensorFlow 1.14, make sure you have `tensorflow==1.14` installed.

**Comment by glenn-jocher** [comment]
Hey there! 😊 It seems like there's a bit of confusion with the `source` argument during the conversion process. Since your model originates from ONNX (which essentially is a format that could be exported from multiple frameworks), the direct source might not be clear for `coremltools`. Here's a quick way to tackle this:

Given you're working with an ONNX model, it might initially come from a PyTorch model (considering YOLOv8's background). Try setting `source='pytorch'`. Do make sure that the appropriate PyTorch version is installed in your environment. 

```python
try:
    coreml_model = ct.convert(
        model=onnx_model, 
        source='pytorch',  # Changed to 'pytorch'
        inputs=[ct.ImageType(name="images", shape=(1, 3, 640, 640))],
        classifier_config=classifier_config,
        convert_to="mlprogram"
    )
    coreml_model.save('yolov8l_world.mlpackage')
except Exception as e:
    print(e)
```

If this doesn't work and you're sure it's TensorFlow-based, adjust `source='tensorflow'` and ensure the correct TensorFlow version is installed. Hope this helps! Let me know if you have more questions.

**Comment by lizhiwen19900709** [comment]
source=‘pytorch’
error：@model must either be a TorchScript object (or .pt or .pth file) or an ExportedProgram object (if using torch.export based API), received: <class 'onnx.onnx_ml_pb2.ModelProto'>
@glenn-jocher

**Comment by glenn-jocher** [comment]
@lizhiwen19900709 hey there! 😊 It seems like we've hit a snag with the conversion. Given your ONNX model and the error message, let's tweak the approach a bit. Since you mentioned TensorFlow doesn't throw an error, let's stick with that route but ensure we load the ONNX model correctly using ONNX's tools before trying to convert. Here's a mini guide:

1. **Load your ONNX model properly**. It seems there was an issue with how `coremltools` was recognizing the model format. Let's make sure we're loading it correctly as an ONNX model.

```python
import onnx
from coremltools.converters.onnx import convert

# Load your ONNX model
onnx_model = onnx.load("yolov8l-world.onnx")

# Convert without specifying the source, as ONNX is inferred
coreml_model = convert(model=onnx_model, minimum_ios_deployment_target='13')
coreml_model.save('yolov8l_world.mlpackage')
```

This approach utilizes the explicit load function from the `onnx` package, ensuring the model is correctly recognized as ONNX. If `coremltools` still isn’t cooperating, we may need to delve into specifics regarding the ONNX model structure or consider the environment and package versions 🤔.

If you're still encountering issues, could you share a bit more about the version of `coremltools` and `onnx` you're using? Sometimes, slight version mismatches can lead to peculiar errors.

**Comment by lizhiwen19900709** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/15767823/b87e15dd-3024-4ea3-9143-3d611240f0dd)

Still no coreml model file output！

**Comment by glenn-jocher** [comment]
@lizhiwen19900709 hey there! 🌟 It looks like we're facing a bit of a challenge with the model conversion. Could you please double-check the following?
- Ensure `coremltools` and `onnx` are updated to their latest versions.
- Verify the path and permissions where you're trying to save the `.mlpackage` file.

If everything seems in place, let’s try simplifying the conversion call a bit, ensuring we have the correct setup:

```python
import coremltools as ct

# Assuming onnx_model is loaded correctly
model_coreml = ct.convert(onnx_model, source='onnx')
model_coreml.save('yolov8l_world.mlmodel')
```

Let us know how it goes! 🚀

**Comment by lizhiwen19900709** [comment]
coremltools 7.1
onnx 1.16.0
All the latest versions.
.mlpackage file path and permissions are also no problem, pt to coreml program can be executed normally, onnx to coreml can not output files normally.

**Comment by glenn-jocher** [comment]
Hey there! 🌟 Thanks for sharing the details. Given the versions and your setup seems good to go, it's odd the ONNX to Core ML conversion isn't outputting as expected. Let's try a slight tweak in how we process the conversion by explicitly using `convert` from the `coremltools.converters.onnx` package:

```python
import onnx
import coremltools.converters.onnx as onnx_converter

# Load your ONNX model directly
onnx_model = onnx.load("yolov8l-world.onnx")

# Try converting again with this approach
coreml_model = onnx_converter.convert(onnx_model)
coreml_model.save('yolov8l_world.mlmodel')
```

If the direct conversion still poses issues, examining the ONNX model for any unsupported layers or operations by Core ML might provide insights. Keep us posted!

**Comment by lizhiwen19900709** [comment]
Traceback (most recent call last):
  File "onnx-to-coreml.py", line 6, in <module>
    import coremltools.converters.onnx as onnx_converter
ModuleNotFoundError: No module named 'coremltools.converters.onnx'

@glenn-jocher

**Comment by Prasoon-Rai** [comment]
Hey, I'm using the following script:

import coremltools as ct
model_coreml = ct.convert(onnx_model, source='onnx')
model_coreml.save('yolov8l_world.mlmodel')

And encountering the error, 
ValueError: Unrecognized value of argument "source": onnx. It must be one of ["auto", "tensorflow", "pytorch", "milinternal"].

I have tried some workarounds but none of 'em work. Could someone please help?

**Comment by glenn-jocher** [comment]
It seems like the import path might be incorrect. Please try using `import coremltools as ct` and then `ct.convert()` for the conversion.

**Comment by glenn-jocher** [comment]
It seems like the `coremltools` package might not be installed correctly. Please ensure you have the latest version of `coremltools` installed using `pip install coremltools`.
