### ISSUE TITLE
Wrong path for dataset with relative path

### ISSUE THREAD

**Issue by PacificDou** [ultralytics/ultralytics#9503]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

There is a parameter `data` in train API: https://docs.ultralytics.com/modes/train/#train-settings, and we can pass the path of yaml file.

Let's assume the dataset has the following folder structure:
$HOME/myproject/cache/dataset/data.yaml
$HOME/myproject/cache/dataset/train  <-- a folder
$HOME/myproject/cache/dataset/test  <-- a folder
$HOME/myproject/cache/dataset/valid  <-- a folder
![image](https://github.com/ultralytics/ultralytics/assets/13517490/1b90cca1-c9fa-4367-b2e2-ae4b939c2c1e)

and the main contents of `data.yaml`:
```
train: ../train/images
val: ../valid/images
test: ../test/images

nc: 2
names: ['dog', 'cat']
```

Then under the project folder, we have a python script to call the trainer:
$HOME/myproject/test.py
```
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)

# Train the model with 2 GPUs
results = model.train(data='./cache/dataset/data.yaml', epochs=100, imgsz=640)
```

The following error will be thrown:
```
FileNotFoundError: 
Dataset 'cache/dataset/data.yaml' images not found ⚠️, missing path '/home/xxx/datasets/cache/dataset/valid/images'
Note dataset download directory is '/home/xxx/datasets'. You can update this in '/home/xxx/.config/Ultralytics/settings.yaml'
```

After checking the source code, I think this is due to the function `check_det_dataset` in `ultralytics.data.utils`:
```
path = Path(extract_dir or data.get("path") or Path(data.get("yaml_file", "")).parent)  # dataset root
if not path.is_absolute():
    path = (DATASETS_DIR / path).resolve()
```

In the previous test case, `path` will be firstly set to `PosixPath('cache/dataset')` (`Path` will remove the relative path `./`), and then appended the suffix as `/home/xxx/datasets/cache/dataset`.

One possible solution might be just to simply convert `args.data` to absolute path before passing to `check_det_dataset`.
However, I'm not sure whether this will cause other problems or not, because in this case, `if not path.is_absolute()` seems always be false.

### Environment

Ultralytics YOLOv8.1.28 🚀 Python-3.10.12 torch-2.2.1+cu118 CUDA:0 (NVIDIA L4, 22491MiB)
Setup complete ✅ (8 CPUs, 31.3 GB RAM, 140.2/484.4 GB disk)

OS                  Linux-6.5.0-1015-gcp-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             git
RAM                 31.33 GB
CPU                 Intel Xeon 2.20GHz
CUDA                11.8

matplotlib          ✅ 3.8.3>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.2.1+cu118>=1.8.0
torchvision         ✅ 0.17.1+cu118>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 1.3.5>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Minimal Reproducible Example

Please see above example.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@PacificDou thanks for the detailed report! 🌟 It seems like the issue is indeed related to how relative paths are resolved in the `train` API. Converting `args.data` to an absolute path before passing to `check_det_dataset` is a promising solution. To implement this fix, you might try modifying your script to pass an absolute path for `data`, like so:

```python
from pathlib import Path
from ultralytics import YOLO

# Define the absolute path for 'data.yaml'
data_path = str(Path('./cache/dataset/data.yaml').resolve())

# Load a model
model = YOLO('yolov8n.pt')

# Train the model with the absolute path
results = model.train(data=data_path, epochs=100, imgsz=640)
```

This approach ensures the `data` argument is always an absolute path, potentially avoiding conflicts with the existing logic for path resolution. If you encounter any issues or have further questions, feel free to ask! And since you're willing to submit a PR, it would be fantastic to have this improvement contributed back to the repository. 🚀

**Comment by PacificDou** [comment]
@glenn-jocher thanks a lot! 
Confirmed that passing an absolute path (as you suggested) works well!

>>And since you're willing to submit a PR, it would be fantastic to have this improvement contributed back to the repository.

Sure, I'm very happy to submit a PR later

**Comment by glenn-jocher** [comment]
That's fantastic news, @PacificDou! 🎉 I'm thrilled to hear the solution worked out for you. Your willingness to contribute back to the YOLOv8 repository with a PR is greatly appreciated by the entire community. Looking forward to seeing your contributions and how they'll help make YOLOv8 even better. If you need any guidance along the way, feel free to reach out. Happy coding! 🚀

**Comment by PacificDou** [comment]
Hi @glenn-jocher , thanks for your message, I've submitted a PR for this issue: https://github.com/ultralytics/ultralytics/pull/10238

**Comment by glenn-jocher** [comment]
Hi @PacificDou, that's great to hear! 🎉 Thank you for taking the time to contribute. We'll review your PR shortly and get back to you with any feedback or next steps. Keep up the awesome work!
