### ISSUE TITLE
how to get boxes from OBB model

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/ultralytics#9504]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i have OBB model and i doing inference and want to get the oriented output boxes ,

**Comment by glenn-jocher** [comment]
@VYRION-Ai hey there! 👋 To retrieve oriented bounding boxes (OBBs) from your OBB model after inference, you can access the `obb` attribute of the `Results` object. Here's a quick example in Python:

```python
from ultralytics import YOLO

# Load your OBB model
model = YOLO('path/to/your/obb_model.pt')

# Run inference
results = model('path/to/your/image.jpg')

# Access OBBs
obbs = results[0].obb.xyxyxyxy  # Retrieves OBBs in xyxyxyxy format

# Each OBB is in the form [x1, y1, x2, y2, x3, y3, x4, y4]
print(obbs)
```

This will give you the coordinates of the corners of each oriented bounding box detected in your image. Hope this helps! Let us know if you have any more questions. 😊
