### ISSUE TITLE
Accept cv2.cuda_GpuMat image for prediction

### ISSUE THREAD

**Issue by reaganch** [ultralytics/ultralytics#9505]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I would like to request the ability to pass an OpenCV GPU Matrix (cv2.cuda_GpuMat object) to the YOLO model in Python for prediction.

### Use case

1. I am using the OpenCV CUDA decoder (cv2.cudacodec.VideoReader) to read individual frames from an RTSP stream as GPU matrices (cv2.cuda_GpuMat objects). I would like to be able to perform object detection on these frames without having to copy them to the CPU first. I presume these frames will then only be copied back to the GPU for detection by YOLO, so this feature would save the frames the round trip.
2. I currently need to perform object detection on RTSP streams from 6 cameras simultaneously. YOLO currently does not accept a list of 6 RTSP streams as input, so 6 dedicated YOLO model instances are needed to monitor the 6 RTSP streams. Creating 6 instances of the YOLO model in memory occupies far too many resources and is rather inefficient. So instead, I would like to read individual frames from the 6 RTSP streams using the OpenCV CUDA decoder and pass a list of 6 cv2.cuda_GpuMat objects (one object per stream) to the YOLO model for detection each second (assuming I'm performing detection at the rate of 1 frame per second).
3. More specifically, I am using the TensorRT version of a YOLO model for prediction. So if there is any way a YOLO TensorRT engine can accept a cv2.cuda_GpuMat object either directly, or by converting it into another accessible format directly on the GPU, that would suffice.

### Additional

When I currently try to pass a cv2.cuda_GpuMat object to a YOLO model in Python, I get the following error message:
```
TypeError: Unsupported image type. For supported types see https://docs.ultralytics.com/modes/predict
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@reaganch hello there! 👋

Thanks for the detailed feature request. I understand the need to directly pass `cv2.cuda_GpuMat` objects to YOLO models for predictions, as this would indeed streamline the process by bypassing unnecessary CPU-GPU transfers. This is especially crucial when dealing with multiple video streams concurrently.

As of now, our YOLO models primarily accept NumPy arrays or file paths for predictions. Direct support for `cv2.cuda_GpuMat` objects is not available, which aligns with the error message you're encountering.

This feature implicates deeper integration with CUDA memory handling, which requires careful consideration and testing. It's a promising direction for enhancing performance efficiency and something we'll consider for future iterations of YOLO.

Regarding your request for passing multiple RTSP streams and efficiently using GPUs, a workaround, for now, could involve manually managing the GPU memory and converting `cv2.cuda_GpuMat` objects to a compatible format before prediction. It's not as efficient as direct support but could serve as a temporary measure.

While direct API support is lacking at this moment, we encourage contributions and discussions on how to support this effectively! Feel welcome to share any thoughts or partial implementations, even if it's not a complete solution. This way, we can collaboratively explore how to integrate such a feature more seamlessly.

For now, converting `cv2.cuda_GpuMat` to `numpy.ndarray` before predictions is the necessary step, as shown below:
```python
gpu_mat = # Your cv2.cuda_GpuMat object
frame = gpu_mat.download() # Convert to numpy ndarray
results = model(frame) # Perform detection
```

Stay tuned for updates on this feature, and don't hesitate to contribute ideas or code that could push this forward! Thanks for choosing YOLO for your object detection needs. 🚀

**Comment by buraktoker** [comment]
Hello, is there any update for using CV2 gpumat structure for YOLO input ?

**Comment by glenn-jocher** [comment]
@buraktoker hello, currently, direct support for `cv2.cuda_GpuMat` as YOLO input is not available, but it's a feature we're considering for future updates. For now, converting to `numpy.ndarray` is necessary.
