### ISSUE TITLE
Augmentation Configuration

### ISSUE THREAD

**Issue by ykwongaq** [ultralytics/ultralytics#9513]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

First of all, thank you for the great work on the ultralytics, really appreciate it!

I want to ask more about the setup for data augmentation. Here is the part of the configuration file:
```
hsv_h: 0.015 # (float) image HSV-Hue augmentation (fraction)
hsv_s: 0.7 # (float) image HSV-Saturation augmentation (fraction)
hsv_v: 0.4 # (float) image HSV-Value augmentation (fraction)
degrees: 0.0 # (float) image rotation (+/- deg)
```

It means that the HSV value will be modified by given fraction. However, I am thinking how to configure it such that the model will augment the HSV value with certain probability (just like some other augmentation). May I ask your kind assistance on configuring it?

Also, is there any set up for applying rotation with certain probability and random angle?

Thank you.

**Comment by glenn-jocher** [comment]
@ykwongaq hi there! 👋 Thanks for reaching out with your questions and for your kind words. Let's get straight to your queries about data augmentation.

The current configuration you've mentioned indeed modifies the HSV value by the specified fraction for every image. To introduce a probability for the HSV augmentation (or any similar operation) to occur, you'd typically require modifying the source code handling data augmentation, as the YAML configuration file alone doesn't directly support this functionality.

For applying rotation with a random angle and certain probability, this functionality would also involve code alterations. The current `degrees` parameter allows for a fixed degree of rotation but doesn’t inherently support randomization with a specific probability.

However, for both cases, adding such capabilities could be a great suggestion for future versions! Feel free to contribute to discussions and feature requests on our GitHub repo. We always welcome community input and contributions.

In the meantime, diving into the code base where augmentations are applied and introducing a random chance (using, for example, Python’s `random` library) before applying certain transformations could achieve what you're looking for. Example for a conditional augmentation application:

```python
import random

# Example check for applying HSV augmentation with a 50% probability
if random.random() < 0.5:
    # Apply HSV augmentation code here
```

Similar logic could be applied for randomly selecting degrees of rotation within your custom augmentation code.

Hope this helps! If you have more ideas or need further assistance, feel free to chime in on our discussions page. Cheers! 🚀
