### ISSUE TITLE
How do I save prediction results to a subfolder without creating a new subfolder?

### ISSUE THREAD

**Issue by mozu04** [ultralytics/ultralytics#9520]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I know there is this solution to save prediction results to a subfolder:
```
model = YOLO("yolov8n.pt")
model.predict(source=..., project="xx", name="xxx")
```
However, the above code does not save the prediction results to an already existing subfolder. Instead, it creates a new subfolder with the name "xxx" within the directory project "xx".
So, how do I save predictions results to an existing subfolder?

**Comment by glenn-jocher** [comment]
@mozu04 hey there! 😊

You can use the `exist_ok=True` argument in your `predict()` function call. This allows the results to be saved in an existing directory without creating a new subfolder. Here’s how you can modify your code:

```python
model = YOLO("yolov8n.pt")
model.predict(source=..., project="xx", name="xxx", exist_ok=True)
```

This will save the results to the existing "xxx" subfolder within the "xx" project. Happy coding! 🚀

**Comment by mozu04** [comment]
@glenn-jocher it works! thank you so much!

**Comment by glenn-jocher** [comment]
@mozu04 That's great to hear! If you have any more questions or need further assistance, feel free to ask. Happy detecting! 😊🚀
