### ISSUE TITLE
How to store filter the stored raw data from a sqlite database by using time buckets?

### ISSUE THREAD

**Issue by anishka07** [ultralytics/ultralytics#9523]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

So I figured out a way to store the raw data (the data of tracked objects which includes bounding box, confidence score, class name, class id and video time stamp) on each frame thanks to a code provided to me earlier. I tweaked the code a bit to make it do what i wanted it to do.

def insert_values(self, classes: List[str], conf: float = 0.5):
        try:
            track = self.trackable_dict
            while self.cap.isOpened():
                ret, frame = self.cap.read()
                if not ret:
                    break
                results = self.model([frame], classes=self.get_indices(classes), conf=conf)
                video_timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                for result in results:
                    detections = zip(result.boxes.cls, result.boxes.conf, result.boxes.cpu().numpy())
                    for class_id, confidence, bbox in detections:
                        confidence_val = round(confidence.item(), 2)
                        if confidence_val >= conf:
                            class_id = int(class_id.item())
                            class_name = track[class_id]
                            bbox_xyxy = bbox.xyxy.tolist()
                            bounding_box = [int(coord) for sublist in bbox_xyxy for coord in sublist]
                            bbox_json = ','.join(map(str, bounding_box))
                            print(f"confidence: {confidence_val}, class_id: {class_id}, class_name: {class_name}, bbox: {bbox_json}")
                            self.cursor.execute(f"""
                            insert into {self.table_name} (video_timestamp, class_name, bounding_box, confidence, class_id) values 
                            (?, ?, ?, ?, ?)""", (video_timestamp, class_name, bbox_json, confidence_val, class_id))
                self.conn.commit()
        except sqlite3.Error as e:
            print("Error: ", e)
            
Now I want to filter out the data which was stored using the above code ⬆️ 
I want the data to filter out in a way which will make me easier to visualize the frequency of the tracked objects at any given time period. 
For example: If I have a month of data (according to my video timestamp), if i filter out, it should give me data for each day using time buckets. If I have a weeks data, it should give me the tracked objects and their frequencies for each day and so on..

def filter_results(self, start_timestamp: str, end_timestamp: str, min_confidence: float = 0.5,
                       time_bucket: str = "1 minute"):
        try:
            conn = sqlite3.connect(Settings.DB_NAME)
            cursor = conn.cursor()
            time_bucket_expr = f"strftime('%Y-%m-%d %H:%M:%S', datetime({self.table_name}.video_timestamp, '{time_bucket}'))"
            query = f"""
            SELECT {time_bucket_expr} AS time_bucket, class_name, COUNT(*) AS frequency FROM {self.table_name}
            WHERE video_timestamp BETWEEN ? AND ? AND confidence > ?
            GROUP BY {time_bucket_expr}, class_name;
            """
            print("Executing query...")
            cursor.execute(query, (start_timestamp, end_timestamp, min_confidence))
            rows = cursor.fetchall()
            if not rows:
                raise "No rows found"
            else:
                for item in rows:
                    time_bucket, class_name, freq = item
                    print(f"Time Bucket: {time_bucket}, Class Name: {class_name}, Frequency: {freq}")
        except sqlite3.Error as e:
            print("Error: ", e)
        finally:
            conn.close()

This is the code I've been trying and its not doing what i want it to do. Can anyone please help me on this? Thank you!

### Additional
<img width="1116" alt="Screenshot 2024-04-03 at 2 16 35 PM" src="https://github.com/ultralytics/ultralytics/assets/109445504/7e783044-0ca1-4eee-94ae-594389a7c3ab">
<img width="1035" alt="Screenshot 2024-04-03 at 2 16 53 PM" src="https://github.com/ultralytics/ultralytics/assets/109445504/d8ef15c3-e120-4aeb-aa18-0e75775d5093">|
These are the screenshots for the code snippet as the code block doesnot seem to be working for me
_No response_

**Comment by glenn-jocher** [comment]
@anishka07 hi there! Thanks for providing detailed information about your issue. It seems like you're on the right track with your approach to filtering data by time buckets for visualization purposes. One possible adjustment to your filtering code might help achieve what you're looking for: the datetime manipulation for time buckets needs a bit of tweaking. 

The SQLite function `strftime` is being used to format datetimes, but for creating time buckets you might actually want to use it to round your timestamps to the nearest time bucket. Your current implementation seems to only reformat timestamps. You might consider calculating a rounded timestamp or a period start timestamp depending on your `time_bucket` value, to effectively group by these periods.

Here's a revised snippet focusing on daily buckets. Adjustments may be needed for other bucket sizes:

```python
def filter_results(self, start_timestamp: str, end_timestamp: str, min_confidence: float = 0.5,
                   time_bucket: str = "day"):
    try:
        conn = sqlite3.connect(Settings.DB_NAME)
        cursor = conn.cursor()
        # Assuming time_bucket can be "day", "hour", etc.
        time_bucket_expr = f"DATE(video_timestamp)" if time_bucket == "day" else f"STRFTIME('%Y-%m-%d %H:00:00', video_timestamp)"
        query = f"""
        SELECT {time_bucket_expr} AS time_bucket, class_name, COUNT(*) AS frequency FROM {self.table_name}
        WHERE video_timestamp BETWEEN ? AND ? AND confidence >= ?
        GROUP BY time_bucket, class_name;
        """
        print("Executing query...")
        cursor.execute(query, (start_timestamp, end_timestamp, min_confidence))
        rows = cursor.fetchall()
        if not rows:
            print("No rows found")
        else:
            for item in rows:
                time_bucket, class_name, freq = item
                print(f"Time Bucket: {time_bucket}, Class Name: {class_name}, Frequency: {freq}")
    except sqlite3.Error as e:
        print("Error: ", e)
    finally:
        conn.close()
```

In this adjustment, I'm using SQLite's `DATE` function directly for daily grouping, and a formatted datetime string for hourly rounding (you might need to adjust this part based on your exact requirements for `time_bucket`). Ensure your `video_timestamp` is correctly formatted and indexed to optimize query performance.

Please try this out and let us know if it works for you! 😊

**Comment by anishka07** [comment]
@glenn-jocher Hi thanks for replying. I copied the code provided and tried it out but i don't think that this is the correct frequency. 
<img width="1231" alt="Screenshot 2024-04-03 at 9 34 10 PM" src="https://github.com/ultralytics/ultralytics/assets/109445504/c45733eb-42ce-45ad-b13c-21af5987e793">
<img width="571" alt="Screenshot 2024-04-03 at 9 34 16 PM" src="https://github.com/ultralytics/ultralytics/assets/109445504/228bb445-c06d-422d-bf82-09bb2d1809cd">

**Comment by glenn-jocher** [comment]
@anishka07 hi there! Thanks for reaching out and trying the code 😊. From the screenshots, it seems like there might be a slight discrepancy in the frequency data. This could potentially be due to how the time buckets are being calculated or grouped in the query. 

Can you double-check the time bucket calculations in the SQL query? Ensuring the timestamps are rounded off or truncated correctly to match your intended time buckets can often solve this issue. Here's a quick example for daily grouping if you're aiming for that:

```python
time_bucket_expr = "DATE(video_timestamp)"
```

And if you're looking for hourly grouping, this snippet might help:

```python
time_bucket_expr = "STRFTIME('%Y-%m-%d %H:00:00', video_timestamp)"
```

Adjust this part of your SQL query accordingly and see if the frequencies look more accurate. Keep us posted on how it goes! 🚀

**Comment by anishka07** [comment]
@glenn-jocher Hi. can you help me now as I have modified the code and I still happen to get absurd results.
`    def test_filter(self, start_timestamp: str, end_timestamp: str, min_confidence: float = 0.5, time_bucket: str = None):
        try:
            start_unix_time = datetime.strptime(start_timestamp, "%Y-%m-%d %H:%M:%S").timestamp()
            end_unix_time = datetime.strptime(end_timestamp, "%Y-%m-%d %H:%M:%S").timestamp()
            if start_unix_time > end_unix_time:
                raise ValueError("Start time is greater than end time.")

            conn = sqlite3.connect(Settings.DB_NAME)
            cursor = conn.cursor()
            time_bucket_expressions_all = {
                "day": "DATE(video_timestamp)",
                "month": "%Y-%m",
                "year": "%Y",
                "week": "%Y-%U",
                "hour": "%Y-%m-%d %H:00:00",
                "minute": "%Y-%m-%d %H:%M:00"
            }
            if time_bucket not in time_bucket_expressions_all.keys():
                raise ValueError("Error: Time bucket not correct.")
            formatted_date = time_bucket_expressions_all[time_bucket]
            time_buck = f"strftime('{formatted_date}', video_timestamp)"
            query = f"""
            SELECT {time_buck} AS time_bucket, class_name, COUNT(*) AS frequency FROM {self.table_name}
            WHERE video_timestamp BETWEEN ? AND ? AND confidence >= ?
            GROUP BY class_name;
            """
            print("Executing query...")
            cursor.execute(query, (start_timestamp, end_timestamp, min_confidence))
            rows = cursor.fetchall()
            if not rows:
                print("No rows found")
            else:
                for item in rows:
                    time_bucket, class_name, freq = item
                    print(f"Time bucket: {time_bucket}, Class Name: {class_name}, Frequency: {freq}")
        except (sqlite3.Error, ValueError) as e:
            print(e)
        finally:
            conn.close()`

**Comment by glenn-jocher** [comment]
Hi @anishka07! It looks like you've put a lot of effort into refining your code. 🌟 However, if you're still getting unexpected results, let's try to troubleshoot a couple of things:

1. **Grouping Issue**: Your SQL query groups results by `class_name` only, which might be causing incorrect frequency counts. Try grouping by both `time_bucket` and `class_name` to ensure that counts are done correctly within each time bucket:
   ```python
   GROUP BY {time_buck}, class_name;
   ```

2. **Date Formatting**: Ensure that the `video_timestamp` in your database is stored in a format that SQLite can recognize as a datetime. If it's stored as a string that doesn't conform to recognized datetime formats, the `strftime` function might not work as expected.

3. **Error Handling**: It's great to see robust error handling! Just ensure that the error messages are informative enough to help you pinpoint the issue.

Give these adjustments a try and see if they help clear up the discrepancies in your results! If the issue persists, it might be helpful to log or print intermediate values to debug effectively. Keep going, you're close to solving this! 🚀
