### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by DANISHFAYAZNAJAR** [ultralytics/ultralytics#9528]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am currently training my YOLOv8 model and receiving training logs in local terminal. However, I aim to transmit the training duration or the number of epochs completed to the frontend of my application to display the training progress dynamically. I am seeking guidance on how to efficiently store the training time or the epoch count and then send this information as a response using Socket.IO to update the frontend interface

**Comment by glenn-jocher** [comment]
@DANISHFAYAZNAJAR hello! 🌟

For capturing the training duration or epoch count and sending this information to your frontend via Socket.IO, you could write a custom callback function within your training script that triggers at the end of each epoch. This function could then emit the required details through Socket.IO to the frontend. Here's a quick example assuming you're using Python for your backend:

```python
from flask import Flask, request
from flask_socketio import SocketIO, emit
from ultralytics import YOLO

app = Flask(__name__)
socketio = SocketIO(app)

def custom_callback(epoch, metrics):
    # This function will be called at the end of each epoch
    # You can add custom logic here to emit details via Socket.IO
    socketio.emit('updateProgress', {'epoch': epoch, 'metrics': metrics})

model = YOLO('yolov8n.pt')

# Assuming you've added support for a callback function in your train method (pseudo code)
model.train(data='your_dataset.yaml', epochs=50, callback=custom_callback)

if __name__ == '__main__':
    socketio.run(app, debug=True)
```

Please adapt the callback logic to fit the actual structure of your training function. This method provides an effective way to dynamically update the frontend with the training progress.

Hope this helps! If you have further questions or need assistance, feel free to ask. Good luck with your YOLOv8 model training! 🚀
