### ISSUE TITLE
Incorrect Conversion of yolov8l.pt to yolov8l.onnx

### ISSUE THREAD

**Issue by parsahemmasi** [ultralytics/ultralytics#9529]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

**Summary:**
When attempting to convert the yolov8l.pt model to yolov8l.onnx using the command:

`yolo export model=yolov8l.pt imgsz=640,640 format=onnx opset=12`

The resulting output data in the generated yolov8l.onnx file is NaN.

This issue does not occur when converting yolov8s.pt to yolov8s.onnx using the same command.

**Steps to Reproduce:**
1. Obtain the yolov8l.pt model.
2. Run the command:
          `yolo export model=yolov8l.pt imgsz=640,640 format=onnx opset=12`
to convert the model to ONNX format.

### Environment

-  Model: yolov8l.pt
- Conversion Command: 
`yolo export model=yolov8l.pt imgsz=640,640 format=onnx opset=12`
- Device: NVIDIA Tegra Orin (nvgpu)/integrated
- Framework: Ultralytics
- Operating System: Ubuntu 20.04.6 LTS

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by parsahemmasi** [comment]
Instead of using the command 

`yolo export model=yolov8l.pt imgsz=640,640 format=onnx opset=12`, 

the following command should be used: 

`yolo export model=yolov8l.pt imgsz=640,640 format=onnx opset=12 device=0`

( 'device=0' should be added!)
I think its related to the fact that yolov8l and other models like yolov8m are only GPU-based, while yolov8s and yolov8n are both CPU and GPU-based. Therefore, it is necessary to quantize based on the GPU device instead of the CPU.

However, it would be helpful to have a fix for the original command to ensure consistent behavior across all models.

Thank you!

**Comment by glenn-jocher** [comment]
@parsahemmasi thank you for bringing this to our attention! 🌟 You're right; specifying the device can sometimes influence the outcome of the export process, especially with models like `yolov8l` that are optimized differently compared to `yolov8s` and `yolov8n`.

For now, using `device=0` to ensure GPU-based quantization is a good workaround:

```bash
yolo export model=yolov8l.pt imgsz=640,640 format=onnx opset=12 device=0
```

We appreciate your suggestion for a fix to make the behavior more consistent across all models. I’ll forward this to our development team for further review. Stay tuned for updates, and thanks again for your contribution to improving YOLOv8! 💡
