### ISSUE TITLE
yolov9

### ISSUE THREAD

**Issue by HyeongD** [ultralytics/ultralytics#9540]
How = can I save and export yolov9 trained on a custom dataset?

**Comment by glenn-jocher** [comment]
@HyeongD hello! Great question 😊. Exporting your custom trained YOLOv9 model is straightforward. Assuming you've already trained your model, you can export it to various formats, including ONNX, TensorRT, CoreML, and more, with the following command:

```bash
yolo export model=path/to/your/yolov9_trained_model.pt format=onnx
```

Just replace `path/to/your/yolov9_trained_model.pt` with the actual path to your trained model file, and `onnx` with your desired export format. Don't forget to check out the [Model Export](https://docs.ultralytics.com/modes/export) section for additional export options and configurations 📦.

Happy deploying!
