### ISSUE TITLE
Export yolov8 pose results object as a single file

### ISSUE THREAD

**Issue by AdwaitMD** [ultralytics/ultralytics#9553]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have custom-trained the yolov8 pose model, which I used on a set of 1000 images. How can I covert/save the results object as a single file in JSON , npy or any other format. I would prefer COCO pose format.  Also, is it possible to same thing when the source is MP4 video and save prediction for every frame in a single file? Also, is it possible to do the same thing when the source is an MP4 video and save prediction for every frame in a single file?

**Comment by glenn-jocher** [comment]
@AdwaitMD sure, exporting your results to a desired file format such as JSON, especially in COCO pose format, can be quite straightforward!

For images, once you have your results object, you can iterate over it, extract the keypoints, and save them in the desired format. For JSON in particular, Python's `json` module will be very useful. Here's a quick example for images:

```python
import json
from ultralytics import YOLO

# Load your model and process images
model = YOLO('path/to/your/custom-trained-model.pt')
results = model('path/to/your/images')

# Prepare data in COCO format
coco_data = [{"image_id": i, "category_id": 1, "keypoints": result.keypoints.numpy().tolist(), "score": result.probs.numpy().tolist()} for i, result in enumerate(results)]

# Save to JSON
with open('results.json', 'w') as f:
    json.dump(coco_data, f)
```

For videos, the concept remains similar; you'd process the video frame by frame, keeping track of each frame's results in a list, and then save it all at once in the end. Handling an MP4 video and extracting keypoints for every frame would look like this:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('path/to/your/custom-trained-model.pt')

# For videos, process the video with .track() method
results = model.track('path/to/your/video.mp4')

# After processing, save results as before
# Note: You may need to adapt the saving code to handle the structure of your results from videos.
```

Make sure you adjust the saving part according to how you want your final data structured, especially if you're dealing with a large number of frames from videos. 

Finally, for the COCO pose format or any other format, you might need some preprocessing on the results to fit their exact structure requirements, but the basic idea would be similar to the examples above! 🚀

**Comment by AdwaitMD** [comment]
Thanks a lot !! I have another very related query... I am running the following code to save all detections to the single list.. however, I run out of RAM after 4000 frames... what is the best way to deal with this? is there a way to dump the result of every frame to the list and clean the RAM? 

```
results_list = []  # Initialize an empty list to store the results
results = model.predict(frames_dir, stream=True)
for result in results:
    # Here you can process the result if needed, for example:
    boxes = result.boxes  # Boxes object for bounding box outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Probs object for classification outputs
    results_list.append(result)

if results_list:  # Ensure the list is not empty
    print(results_list[0].tojson())
else:
    print("No results found.")

```

**Comment by glenn-jocher** [comment]
@AdwaitMD hey there! 😊 Absolutely, processing a large number of frames can indeed be intensive on memory. Here’s a strategy to continually dump your results to the disk and clear memory:

```python
import json

# Function to save partial results to disk and clear the list
def save_partial_results(results_list, filename="partial_results.json"):
    with open(filename, "a") as f:
        for result in results_list:
            # Convert each result to JSON and write to file
            json.dump(result.tojson(), f)
            f.write("\n")  # Newline for each result
    results_list.clear()  # Clear the processed results to free up RAM

results_list = []
results = model.predict(frames_dir, stream=True)

for i, result in enumerate(results, 1):
    results_list.append(result)
    if i % 1000 == 0:  # Save every 1000 frames
        save_partial_results(results_list)

# Do not forget to save the last batch if it's less than 1000.
if results_list:
    save_partial_results(results_list)

print("All results saved, and RAM is happy!")
```

This code appends results to a JSON file and clears the list every 1000 frames (adjustable as needed) to manage memory more efficiently. 👍 Hope this helps!

**Comment by AdwaitMD** [comment]
Great..!! It is very helpful for a newbie like me. Thanks a lot for the prompt reply.

**Comment by glenn-jocher** [comment]
@AdwaitMD you're welcome! 🌟 We're thrilled to hear you found the response helpful. If you have any more questions or need further assistance, feel free to reach out. Happy coding! 😊
