### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'yolv8m.pt'

### ISSUE THREAD

**Issue by MsAnitaAli** [ultralytics/ultralytics#9564]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I was going through yout supporting video at https://www.youtube.com/watch?v=LNwODJXcvt4 and succesfully followed each single step through Google Colab. 

**Working part of  the code is this.** 
!nvidia-smi

!pip install ultralytics

# Import YOLO
from ultralytics import YOLO
import os
from IPython.display import display, Image
from IPython import display
display.clear_output()
!yolo mode = checks

!pip install roboflow

from roboflow import Roboflow
rf=Roboflow(api_key="GuLzodbSc5KbiEI23crL") # 
project=rf.workspace("anitaali").project("hard-hat-sample-jaczm")
dataset=project.version(3).download("yolov8")

**Now stuck at this cell.** 
When I compile this line

!yolo task = detect mode= train model=yolv8m.pt data={dataset.location}/data.yaml epochs=20 imgsz=640

**I got this**
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 555, in entrypoint
    model = YOLO(model, task=task)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 151, in __init__
    self._load(model, task=task)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 240, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 806, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 732, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'yolv8m.pt'

**Now how to proceed?**

### Minimal Reproducible Example

!nvidia-smi

!pip install ultralytics

Import YOLO
from ultralytics import YOLO
import os
from IPython.display import display, Image
from IPython import display
display.clear_output()
!yolo mode = checks

!pip install roboflow

from roboflow import Roboflow
rf=Roboflow(api_key="GuLzodbSc5KbiEI23crL") #
project=rf.workspace("anitaali").project("hard-hat-sample-jaczm")
dataset=project.version(3).download("yolov8")

!yolo task = detect mode= train model=yolv8m.pt data={dataset.location}/data.yaml epochs=20 imgsz=640

### Additional

**I have mounted my drive using**

from google.colab import drive
drive.mount('/content/drive')

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MsAnitaAli it seems like there's a typo in your model file name (`yolv8m.pt`). The standard naming convention for YOLO models starts with `yolov` (not `yolv`). If you're attempting to use a pre-trained YOLOv8 model, you might want to try one of the following model names depending on the size and performance trade-offs you're looking for:
- `yolov8n.pt` (nano, smallest and fastest)
- `yolov8s.pt` (small)
- `yolov8m.pt` (medium)
- `yolov8l.pt` (large)
- `yolov8x.pt` (xlarge, largest and most accurate)

Your corrected command should look something like this, assuming you wanted the medium variant:
```bash
!yolo task = detect mode= train model=yolov8m.pt data={dataset.location}/data.yaml epochs=20 imgsz=640
```

Please ensure that the model you are trying to use exists or is correctly downloaded/placed in an accessible directory if you're using a custom trained model. If the typo correction does not resolve the issue, you may need to download the model file first or adjust the path to where your model file is located. 🚀
