### ISSUE TITLE
Some questions about video tracking

### ISSUE THREAD

**Issue by STITCHESHHH** [ultralytics/ultralytics#9565]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thank you for the codes, they have taught me a lot, especially the part about tracking a video and plotting the trajectory I found very interesting!
These tools can be used to analyze the behavior of pedestrians, car drivers, and so on.
I have some questions about video tracking. Is it possible that the tracking is done by a detector for feature extraction and a tracker for target tracking?
When tracking a video, does the detector split the video into pictures or does the tracker split the video into pictures to track the target frame by frame?
While tracking a video, can I change the size of the recognized image from its original size?
Sincerely looking forward to your help!😀

**Comment by glenn-jocher** [comment]
@STITCHESHHH hey!

I'm thrilled to hear you're finding the tracking features in YOLOv8 valuable and intriguing! 😊 To answer your questions succinctly:

1. **Feature Extraction and Tracking**: Yes, in video tracking, both a detector and a tracker work in tandem. The detector identifies objects in frames, outputting bounding boxes and classes, whereas the tracker uses these detections across frames to maintain identity and track the objects.

2. **Video Processing**: Typically, the video is processed frame by frame for tracking. The detector operates on individual frames to identify objects, and the tracker then uses the detection results to track these objects over time.

3. **Changing Recognized Image Size**: Yes, you can change the size of the image being processed. When initializing your model for detection/tracking, you can specify the desired input size. Here's a quick example:
   ```python
   from ultralytics import YOLO
   
   # Load the model with a specified image size
   model = YOLO('yolov8n.pt', imgsz=640)  # Here we set imgsz to 640 as an example
   
   # Now use this model for prediction or tracking
   results = model.track('path/to/your/video.mp4')
   ```

   Adjusting the `imgsz` parameter allows you to control the resolution at which the model processes images, which can affect both performance and accuracy.

I hope this clears up your queries! Feel free to reach out if you have more questions.
