### ISSUE TITLE
An error occurred when replacing the convolution module

### ISSUE THREAD

**Issue by leiouultraman** [ultralytics/ultralytics#9566]
Traceback (most recent call last):
  File "/media/ssq/code_run/ultralytics/train.py", line 7, in <module>
    model.train(model='/media/ssq/code_run/ultralytics/yolov8n.pt', data='/media/ssq/code_run/ultralytics/datasets/KITTI/KITTI.yaml', epochs=20, imgsz=640, batch=1)
  File "/media/ssq/code_run/ultralytics/ultralytics/engine/model.py", line 341, in train
    self.trainer.train()
  File "/media/ssq/code_run/ultralytics/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/media/ssq/code_run/ultralytics/ultralytics/engine/trainer.py", line 288, in _do_train
    self._setup_train(world_size)
  File "/media/ssq/code_run/ultralytics/ultralytics/engine/trainer.py", line 259, in _setup_train
    self.ema = ModelEMA(self.model)
  File "/media/ssq/code_run/ultralytics/ultralytics/utils/torch_utils.py", line 399, in __init__
    self.ema = deepcopy(de_parallel(model)).eval()  # FP32 EMA
  File "/home/ssq/anaconda3/envs/yolov8_1/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ssq/anaconda3/envs/yolov8_1/lib/python3.8/copy.py", line 269, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ssq/anaconda3/envs/yolov8_1/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ssq/anaconda3/envs/yolov8_1/lib/python3.8/copy.py", line 229, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ssq/anaconda3/envs/yolov8_1/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ssq/anaconda3/envs/yolov8_1/lib/python3.8/copy.py", line 295, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/ssq/anaconda3/envs/yolov8_1/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ssq/anaconda3/envs/yolov8_1/lib/python3.8/copy.py", line 269, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ssq/anaconda3/envs/yolov8_1/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ssq/anaconda3/envs/yolov8_1/lib/python3.8/copy.py", line 229, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ssq/anaconda3/envs/yolov8_1/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ssq/anaconda3/envs/yolov8_1/lib/python3.8/copy.py", line 295, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/ssq/anaconda3/envs/yolov8_1/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ssq/anaconda3/envs/yolov8_1/lib/python3.8/copy.py", line 269, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ssq/anaconda3/envs/yolov8_1/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ssq/anaconda3/envs/yolov8_1/lib/python3.8/copy.py", line 229, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ssq/anaconda3/envs/yolov8_1/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/home/ssq/anaconda3/envs/yolov8_1/lib/python3.8/site-packages/torch/_tensor.py", line 86, in __deepcopy__
    raise RuntimeError(
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment.  If you were attempting to deepcopy a module, this may be because of a torch.nn.utils.weight_norm usage, see https://github.com/pytorch/pytorch/pull/103001

When I replace the yolov8 convolution module, an error message like this will appear when running the training code.

**Comment by glenn-jocher** [comment]
@leiouultraman hi there! It looks like you're encountering an issue with `deepcopy` during model training, potentially related to replacing the convolution module in your YOLOv8 model. This error often arises from PyTorch's limited support for `deepcopy` on non-leaf Tensors, which can be an issue when using certain features like weight normalization.

One workaround might be to avoid using features that introduce non-leaf tensors into your module, or if you're using weight normalization, consider applying it in a way that doesn't interfere with `deepcopy`.

If weight normalization or similar features are essential for your use case, you could try manually managing the weight hooks rather than relying on PyTorch's built-in methods. PyTorch's discussion on [this pull request](https://github.com/pytorch/pytorch/pull/103001) might offer some insights.

If possible, could you share a bit more about how you're replacing the convolution module? Sometimes, the method of replacement could lead to unexpected behavior with certain PyTorch functionalities. Knowing more about your approach might help in suggesting a more specific solution. 😊

```python
# Example of manual management of weight normalization might go here
# But keep in mind, the actual solution would depend on your specific implementation.
```

Let's get to the bottom of this together!

**Comment by leiouultraman** [comment]
def _5d_to_4d(x, use_reshape=False):
    n, mc, c, h, w = x.shape
    if use_reshape:
        x = x.reshape(n, mc * c, h, w)
    else:
        x = x.view(n, mc * c, h, w)
    return x


def conv2d(x, weight, in_channel, out_channel,
           k_size=3, stride=2, padding=0, group=1):
    mc = x.size(1)
    x = _5d_to_4d(x, use_reshape=True)
    weight = weight.view(mc, k_size, k_size, in_channel, out_channel)
    weight = weight.permute(0, 4, 3, 1, 2)
    weight = weight.reshape(out_channel * mc, in_channel, k_size, k_size)

    result = F.conv2d(x, weight, stride=stride, groups=mc * group, padding=padding)

    r_n, _, r_h, r_w = result.shape
    result = result.view(r_n, mc, out_channel, r_h, r_w)
    return result
@glenn-jocher Hello, thank you very much for your answer. The following is the code of my replaced convolution module, where Conv_RFF is the convolution module.

class Conv_RFF(nn.Module):
    def __init__(self, in_channels, out_channels, k_size=2, stride=2, padding=0, mc=10, kernel_type='RBF',
                 group=1, F0=True):
        super(Conv_RFF, self).__init__()

        self.out_channels = int(out_channels / 2)
        self.in_channels = in_channels // group
        self.kernel_size = k_size
        self.stride = stride
        self.padding = padding
        self.mc = mc
        self.kernel_type = kernel_type
        self.group = group
        self.F0 = F0

        # theta:scaler
        self.theta_logsigma = nn.Parameter(torch.zeros(1), requires_grad=True)
        # scaler
        self.llscale = nn.Parameter(0.5 * torch.log(torch.tensor(self.in_channels * k_size * k_size).float()),
                                    requires_grad=True)
        # [C*k*k,C']
        self.theta_llscale = nn.Parameter(
            torch.ones([self.in_channels * k_size * k_size]) * self.llscale, requires_grad=True)
        # Omega:q
        # Omega:[C*k*k,C']
        self.Omega_mean = nn.Parameter(torch.zeros(self.in_channels * k_size * k_size, self.out_channels),
                                       requires_grad=True)
        # Omega:[C*k*k,C']
        self.Omega_logsigma = nn.Parameter(
            (self.theta_llscale * -2.)[..., None] * torch.ones(self.in_channels * k_size * k_size, self.out_channels),
            requires_grad=True)
        # Omega_eps:[mc,C*k*k,C']
        self.Omega_eps = nn.Parameter(
            torch.randn(self.mc, self.in_channels * self.kernel_size * self.kernel_size, self.out_channels),
            requires_grad=True)

    def get_prior_Omega(self):
        # [C*k*k,1]
        Omega_mean_prior = torch.zeros(self.in_channels * self.kernel_size * self.kernel_size, 1)
        # [C*k*k]
        Omega_logsigma_prior = self.theta_llscale * -2. * torch.ones(
            self.in_channels * self.kernel_size * self.kernel_size).cuda()
        return Omega_mean_prior, Omega_logsigma_prior

    def forward(self, x):
        # input:
        # original image:[batch_size,C,H,W]->[8,1,28,28]
        # or the output feature map of last layer:[batch_size,mc*channels,H,W]
        if self.F0:
            x = torch.unsqueeze(x, 0).repeat(self.mc, 1, 1, 1, 1)
            x = x.transpose(0, 1)  # 5d

        # local reparameter
        # self.Omega_from_q = Omega_eps * torch.exp(self.Omega_logsigma / 2) + self.Omega_mean
        self.Omega_from_q = self.Omega_eps * torch.exp(self.Omega_logsigma / 2) + self.Omega_mean

        # conv2d_rff
        # x:[batch_size,mc*channels,H,W]
        # weight:self.Omega_from_q [mc,C*k*k,C']
        # output:[batch,mc*channels,H,W]
        # new: r_n, mc, out_channel, r_h, r_w
        phi_half = conv2d(x, self.Omega_from_q, self.in_channels, self.out_channels, self.kernel_size, self.stride,
                          self.padding, self.group)
        ## RFF:[cos(F*x),sin(F*x)]
        phi_half_size = phi_half.shape[-1]
        N_rf = self.out_channels * phi_half_size * phi_half_size
        phi = torch.exp(0.5 * self.theta_logsigma)
        phi = phi / torch.sqrt(torch.tensor(1.) * N_rf)

        # phi_half = phi_half.view(-1, self.mc, self.out_channels, phi_half_size, phi_half_size)
        if self.kernel_type == "RBF":
            A = phi * torch.cos(phi_half)
            B = phi * torch.sin(phi_half)
            # output:[batch,mc*channels*2,H,W]
            phi = torch.cat([A, B], 2)
        else:
            # phi = phi * torch.cat([torch.maximum(phi_half, torch.tensor(0.))], 2)
            phi = phi * torch.cat([torch.relu(phi_half)], 2)
        # phi = phi.view(-1, self.mc * phi.shape[2], phi_half_size, phi_half_size)
        return phi.mean(dim=1)  # new: r_n, mc, out_channel, r_h, r_w

def _4d_to_5d(x, mc, use_reshape=False):
    n, c, h, w = x.shape
    assert c % mc == 0
    if use_reshape:
        x = x.reshape(n, mc, c // mc, h, w)
    else:
        x = x.view(n, mc, c // mc, h, w)
    return x

**Comment by glenn-jocher** [comment]
Hey @leiouultraman! Thanks for sharing your convolution module replacement code for YOLOv8. Your approach with `Conv_RFF` and the modification of the convolution to handle 5D tensors and random Fourier features seems intriguing! 🚀

Quick note on your custom convolution operation within `conv2d` function:
- It's great that you're deploying the `use_reshape=True` in `_5d_to_4d` for converting tensors. The reshape operation is generally safer for ensuring compatibility with operations expecting 4D tensors.
- Your approach to constructing `self.Omega_from_q` in the `forward` method integrates the reparameterization trick nicely, crucial for stochastic network layers.

Your custom module is well-aligned with advanced convolutional network applications, and it's these kinds of innovative approaches that drive the field forward. If you hit any performance bottlenecks or wish to explore further optimizations, consider reviewing the following:
- Memory management, particularly with large tensors in `self.Omega_eps` and the subsequent operations.
- Parallel computation opportunities, especially when operating over the `mc` (Monte Carlo?) dimension, to enhance computational efficiency.

For those diving into similar customizations, remember to check the shape of the tensors throughout the transformations to catch any potential mismatches early on. And, of course, keep an eye on potential numerical stability issues, especially when dealing with operations like exponentiation and division in the Fourier feature space.

Keep innovating, and feel free to reach out if you have further questions or insights to share! 🌟
