### ISSUE TITLE
Documentation on arguments and default values for .tune

### ISSUE THREAD

**Issue by marvijar** [ultralytics/ultralytics#9568]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi there, you are doing great work! I’m looking for documentation on the arguments of the `.tune` function of a model (class `model`: function: `.tune`). I found some parameters documented [here](https://docs.ultralytics.com/guides/hyperparameter-tuning/) and [here](https://docs.ultralytics.com/integrations/ray-tune/), but is there also a complete documentation of the allowed and default values? The same as for example there is on `.train` and `.val`.

**Comment by glenn-jocher** [comment]
@marvijar hi! Thank you for the kind words and for reaching out with your question 🚀. For the `.tune` function arguments and default values, you're correct that some details can be found in our hyperparameter tuning guides. Currently, a comprehensive list akin to what's provided for `.train` and `.val` might not be available in one place. However, the primary way to explore all arguments and their defaults comprehensively is by looking at the source code where the `.tune` function is defined. 

Here is a quick example to get the tune arguments programmatically:

```python
from ultralytics import YOLO

# Load model
model = YOLO('yolov8n.pt')

# Accessing the `.tune` method's docstring
help(model.tune)
```

This should provide you with some insights into available arguments and their intended use. We're always working on improving our documentation, so your feedback is valuable for future updates!

If anything specific is unclear or if you need further clarification, feel free to ask! 🙌
