### ISSUE TITLE
Conversion of Yolov8n to TFLite

### ISSUE THREAD

**Issue by Rahuldee** [ultralytics/ultralytics#959]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

ValueError: Exception encountered when calling layer "tf.math.subtract" (type TFOpLambda).

Dimensions must be equal, but are 8400 and 2 for '{{node tf.math.subtract/Sub}} = Sub[T=DT_FLOAT](tf.math.subtract/Sub/x, Placeholder)' with input shapes: [1,8400,2], [1,2,8400].

Call arguments received by layer "tf.math.subtract" (type TFOpLambda):
  • x=tf.Tensor(shape=(1, 8400, 2), dtype=float32)
  • y=tf.Tensor(shape=(1, 2, 8400), dtype=float32)
  • name='wa/model.22/Sub'
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
TensorFlow SavedModel: export failure ❌ 39.1s: SavedModel file does not exist at: yolov8n_saved_model/{saved_model.pbtxt|saved_model.pb}

### Environment

Colab Yolov8 Tutorial

### Minimal Reproducible Example

!yolo export model=yolov8n.pt format=tflite

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by macsmy** [comment]
got the same bug

**Comment by glenn-jocher** [comment]
@Rahuldee @macsmy all TF Saved Model, Protobuf and TFLite modes are now exporting and predicting correctly with ultralytics 8.0.46 via PR https://github.com/ultralytics/ultralytics/pull/1141 as verified in our latest CI benchmarks below. Please update your package with `pip install -U ultralytics` and let us know if this resolves your issue and if you have any other problems. Thank you! 
https://github.com/ultralytics/ultralytics/actions/runs/4271012395/jobs/7435190444

<img width="1139" alt="Screenshot 2023-02-25 at 09 22 15" src="https://user-images.githubusercontent.com/26833433/221370745-43697ce1-0792-43d3-b87b-d4a5fb434eb9.png">
