### ISSUE TITLE
Sort the bounding box coordinates before save_crops

### ISSUE THREAD

**Issue by NishaAkole** [ultralytics/ultralytics#9617]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I trained a box detector model using YOLOv8. But the save-crops save images randomly, by changing their sequence. It will help if save_crops follows the top-left corner to the bottom-right corner. For now, I am sorting the bbox coordinates and then manually saving those crops. 

### Use case

It can be used to sort the objects detected based on its location from image.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@NishaAkole hey there! 😊 It sounds like you're seeking a way to have the `save_crops` function in YOLOv8 save the detected object crops in a sorted manner, specifically from the top-left corner to the bottom-right corner of the image. This is indeed a helpful feature for many use cases, including organizing detected objects based on their spatial location in the image.

While the current implementation of YOLOv8's `save_crops` does not directly support this, your approach of sorting the bounding box (bbox) coordinates manually and then saving the crops is a great workaround. 

For anyone else interested, here's a quick snippet on how you might approach sorting the bboxes before saving the crops:

```python
# Assuming 'results' is your detection results from YOLOv8
bboxes = results.pandas().xyxy[0]  # get bboxes as a pandas DataFrame

# Sort based on xmin and ymin to follow top-left to bottom-right
sorted_bboxes = bboxes.sort_values(by=['xmin', 'ymin'])

# Now, you could use the sorted bbox coordinates to save the crops manually
```
**Note**: This is just a simple example; additional steps might be necessary depending on your exact needs.

I appreciate your suggestion and understand how this feature could be beneficial. If you're interested and have a working solution, we encourage and welcome contributions to the Ultralytics repository. Though you mentioned not submitting a PR, your idea could inspire future enhancements to YOLOv8.

Feel free to reach out if you have further questions or suggestions! 🌟
