### ISSUE TITLE
Save the resultant images or videos

### ISSUE THREAD

**Issue by Pawan7121** [ultralytics/ultralytics#963]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

While predicting the images the resultant images is not saving into the local directory.

### Minimal Reproducible Example

#

### Additional

#

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
pass save=True
