### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'metrics'

### ISSUE THREAD

**Issue by hyperf0cus** [ultralytics/ultralytics#964]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

QObject::moveToThread: Current thread (0x43ba970) is not the object's thread (0xc7fbd900).
Cannot move to target thread (0x43ba970)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/almatshakenov/environments/ash_env/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 1836964) of binary: /home/almatshakenov/environments/ash_env/bin/python3
/home/almatshakenov/environments/ash_env/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py:367: UserWarning: 

**********************************************************************
               CHILD PROCESS FAILED WITH NO ERROR_FILE                
**********************************************************************
CHILD PROCESS FAILED WITH NO ERROR_FILE
Child process 1836964 (local_rank 0) FAILED (exitcode -6)
Error msg: Signal 6 (SIGABRT) received by PID 1836964
Without writing an error file to <N/A>.
While this DOES NOT affect the correctness of your application,
no trace information about the error will be available for inspection.
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
**********************************************************************
  warnings.warn(_no_error_file_warning_msg(rank, failure))
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/almatshakenov/environments/ash_env/lib/python3.8/site-packages/torch/distributed/run.py", line 702, in <module>
    main()
  File "/home/almatshakenov/environments/ash_env/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 361, in wrapper
    return f(*args, **kwargs)
  File "/home/almatshakenov/environments/ash_env/lib/python3.8/site-packages/torch/distributed/run.py", line 698, in main
    run(args)
  File "/home/almatshakenov/environments/ash_env/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/home/almatshakenov/environments/ash_env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/almatshakenov/environments/ash_env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************************************************************
  /home/almatshakenov/.config/Ultralytics/DDP/_temp_fqw5zng8139780114513776.py FAILED  
=======================================================================================
Root Cause:
[0]:
  time: 2023-02-14_11:49:09
  rank: 0 (local_rank: 0)
  exitcode: -6 (pid: 1836964)
  error_file: <N/A>
  msg: "Signal 6 (SIGABRT) received by PID 1836964"
=======================================================================================
Other Failures:
  <NO_OTHER_FAILURES>
***************************************************************************************
Traceback (most recent call last):
  File "/home/almatshakenov/environments/ash_env/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/almatshakenov/environments/ash_env/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 303, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/almatshakenov/environments/ash_env/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 243, in train
    self.metrics_data = self.trainer.validator.metrics
AttributeError: 'NoneType' object has no attribute 'metrics'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

### Environment

Ultralytics YOLOv8.0.36 🚀 Python-3.8.10 torch-1.9.1+cu111 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11019MiB)
                                                                                                      CUDA:1 (NVIDIA GeForce RTX 2080 Ti, 11019MiB)

### Minimal Reproducible Example

 I can't finish my training on last epoch 500, even with resume. After progress bar finished it throws an error, and terminated.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@hyperf0cus this should be fixed here https://github.com/ultralytics/ultralytics/pull/961

**Comment by glenn-jocher** [comment]
@hyperf0cus thanks for the bug report! We've patched this in #961 which will deploy with 8.0.37 soon.

Let us know if this resolves your issue, thank you!
