### ISSUE TITLE
recall / auto anchor

### ISSUE THREAD

**Issue by Mehdi-1996-ai** [ultralytics/ultralytics#966]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hi
when training start auto anchor print best posible recall is 99.98 but even at the end training with 1000 epoch ,recall stop improving from 94

**Comment by JustasBart** [comment]
Hi @Mehdi-1996-ai I think the way how that works is that it's only theoretically possible to get to 99.98% but as anything to do with AI there are never any guarantees of success at all. Though one possible explanation that I could come up with is that if you don't have a huge dataset you might be over-augmenting your data and thus it might become impossible to recall of the objects correctly.

Perhaps try and reduce your augmentations something to around this:

hsv_h=0.010 \
hsv_s=0.3 \
hsv_v=0.2 \
degrees=0.0 \
translate=0.1 \
scale=0.2 \
shear=0.0 \
flipud=0.5 \
fliplr=0.5

Hope this helps, good luck! :rocket:

**Comment by Mehdi-1996-ai** [comment]
Hi @JustasBart  tnx for your respond i have a huge dataset with over 20 000 instance and i use default augmentation that yolo use,
i 'll try your hyps
tnx again

**Comment by JustasBart** [comment]
@Mehdi-1996-ai All the best!
