### ISSUE TITLE
What does the "pretrained" argument mean when training?

### ISSUE THREAD

**Issue by t-ozawa123** [ultralytics/ultralytics#967]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is the "pretrained" argument used when training?
Does it have a different meaning than "model"?

**Comment by t-ozawa123** [comment]
![docs](https://user-images.githubusercontent.com/44954821/218679765-9b7a86a0-3396-4b54-9582-3413fe0a0f00.png)

**Comment by AyushExel** [comment]
It's mostly used for classification. It dictates whether the model ckpt is being used directly for training or is it reset to random weights
