### ISSUE TITLE
Model error

### ISSUE THREAD

**Issue by Nioolek** [ultralytics/ultralytics#970]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

I download these two models from https://github.com/ultralytics/assets/releases
![8660f782135e333d385bc1f3a2be0b3](https://user-images.githubusercontent.com/40284075/218703041-e60b5e27-8dad-4e3f-9591-dc6ae3a168a8.png)

I wrote code to read train_args from model, but I found the `model` in `train_args` maybe is error.

![image](https://user-images.githubusercontent.com/40284075/218703333-4bd26e4d-611b-432f-9c7d-396e3ea984dd.png)
![image](https://user-images.githubusercontent.com/40284075/218703393-4abb1a49-10bd-4f88-a326-8f630e7c272b.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Nioolek hi, thanks for letting us know about this bug!

I checked the assets and realized I introduced a naming bug, I've re-uploaded y`olov8l-v8loader.pt` and `yolov8x-v8loader.pt` now, so this should be fixed.

Please let us know if you run into any other issues!

**Comment by glenn-jocher** [comment]
Closing as resolved. Please re-open if issue is not resolved.
