### ISSUE TITLE
engine model accuracy decline

### ISSUE THREAD

**Issue by wsy-yjys** [ultralytics/ultralytics#973]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I converted pt model to engine model by using the following code, the inference accuracy decreased.

```python
from ultralytics import YOLO
model = YOLO('yolov8n.pt')
results = model.export(format='engine', device=0, opset=11)
```

![image](https://user-images.githubusercontent.com/78601159/218744280-b216e391-3a31-4f7b-a4ca-172e4b76aa20.png)
the yolov8n.pt inference result

![image](https://user-images.githubusercontent.com/78601159/218744434-cbe0c03b-c921-499c-afdf-c15707e55d9a.png)
the yolov8n.engine inference result

who can tell me how to solve this problem?

**Comment by glenn-jocher** [comment]
@wsy-yjys inference is exactly the same. Exported formats run square inference while pt models run rectangular inference.

There is zero accuracy loss produced by export as you can see from this simple reproducible script:
```python
!yolo export format=engine device=0 imgsz=640,640
!yolo val model=yolov8n.pt imgsz=640,640
!yolo val model=yolov8n.engine imgsz=640,640
```
