### ISSUE TITLE
image size issue in prediction

### ISSUE THREAD

**Issue by MridulJain0771** [ultralytics/ultralytics#974]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained model on custom dataset on 640 img size for 100 epochs with model=yolov8x.pt for object detect but 
->  prediction for img size 640 its output for object having width greater than 1/2 of image width is not detecting properly (it just detect middle are of object only not complete object)  
-> prediction for img size 160 it give proper result for object having width greater than 1/2 of image width not for smaller object

**Comment by Laughing-q** [comment]
@MridulJain0771 can you reproduce the issue on coco images with the pretrained weights?
