### ISSUE TITLE
Errors with hyperparameter tuning a yolov9-c backbone model

### ISSUE THREAD

**Issue by zdri** [ultralytics/ultralytics#9747]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Hyperparameter Tuning

### Bug

Hi! I've been using the YOLOv9 file train-dual.py to train some object detection models from scratch on a custom dataset using the yolov9-c.yaml backbone. I am running into an issue, however, when I attempt to use the model.tune() function for hyperparameter training. I keep getting the error:
`TypeError: ERROR ❌️ runs/train/yolov9-c-GAL1_batch8_pat200/weights/best.pt appears to be an Ultralytics YOLOv5 model originally trained with https://github.com/ultralytics/yolov5.
This model is NOT forwards compatible with YOLOv8 at https://github.com/ultralytics/ultralytics.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'`

I've reinstalled my ultralytics and retrained a few times, however, I keep running into the same error. I'm wondering if the YOLOv9 train-dual.py file is incompatible with model.tune()?

Thanks!

### Environment

Ultralytics YOLOv8.1.42 🚀 Python-3.12.1 torch-2.2.1+cu121 CPU (Intel Xeon Gold 6150 2.70GHz)
Setup complete ✅ (36 CPUs, 163.2 GB RAM, 25.6/29.5 GB disk)

OS                  Linux-3.10.0-1160.71.1.el7.x86_64-x86_64-with-glibc2.17
Environment         Linux
Python              3.12.1
Install             pip
RAM                 163.17 GB
CPU                 Intel Xeon Gold 6150 2.70GHz
CUDA                None

matplotlib          ✅ 3.8.3>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 9.5.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.2.1>=1.8.0
torchvision         ✅ 0.17.1>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.1>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@zdri hey there!

It seems like you've encountered a compatibility issue with your model and the YOLOv8 environment. The error message indicates that the model you're trying to tune was originally trained with the YOLOv5 architecture, and YOLOv8 (including any `train_dual.py` or functionality from YOLOv9 you might refer to) might not be directly compatible due to differences in the model architecture and training methodology.

One immediate solution, as the error suggests, would be to train a fresh model directly using YOLOv8 or with the correct version you intend to use for hyperparameter tuning. Ensure you're indeed working with the YOLOv8 (or the version you're interested in) scripts and configurations. For example, retrain your model with:

```python
from ultralytics import YOLO  # Make sure you're using the correct Ultralytics package

# Suppose 'yolov8-c.yaml' is your desired configuration
model = YOLO('path/to/yolov8-c.yaml')
model.train()
```

And then proceed with the `model.tune()` approach.

If by any chance references to YOLOv9 or `train-dual.py` slipped in, it might indicate an inconsistency in the documentation or an unintended mix-up of different versions' files and functionalities. Double-check the documentation or the GitHub issues/commits to ensure you're not mixing versions.

Feel free to reach out again if you need more help or if something wasn't clear. Happy to assist further! 🚀

**Comment by zdri** [comment]
Hi, thank you for your response!

I'm trying to train a model from scratch with **yolov9-c.yaml**.

According to the yolov9 documentation, training should be performed using the train_dual.py file, however, the models generated were causing the error I've copied above.

In order to run the model.tune() function, I'm now trying to use the model.train() function with the yolov9-c.yaml file, but I'm encountering a new error:
`    model = YOLO('models/detect/yolov9-c.yaml', task='detect')
  File "/home/zacharid/ml20_scratch/miniconda3/envs/yolo/lib/python3.10/site-packages/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/home/zacharid/ml20_scratch/miniconda3/envs/yolo/lib/python3.10/site-packages/ultralytics/engine/model.py", line 149, in __init__
    self._new(model, task=task, verbose=verbose)
  File "/home/zacharid/ml20_scratch/miniconda3/envs/yolo/lib/python3.10/site-packages/ultralytics/engine/model.py", line 218, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "/home/zacharid/ml20_scratch/miniconda3/envs/yolo/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 287, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
  File "/home/zacharid/ml20_scratch/miniconda3/envs/yolo/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 855, in parse_model
    m = getattr(torch.nn, m[3:]) if "nn." in m else globals()[m]  # get module
KeyError: 'DualDDetect'`

I can't find any reference to this module or to the error anywhere online. I've also seen reference to a similar file **yolov9c.yaml** but I can't find that file available anywhere either. Is this a compatibility issue between the YOLOv8 and v9 methods, an issue with my own code, or a bug in the yolov9-c.yaml file?

**Comment by glenn-jocher** [comment]
@zdri hey there! 🌟

It sounds like you're pioneering some exciting work with YOLOv9! The error you're encountering with the "DualDDetect" class indeed seems perplexing, primarily if it's not readily found in documentation or codebase searches.

Given the complexities between YOLO version compatibility and the specific nuances of model training, here's a quick suggestion:

1. Ensure you're in the correct environment that supports YOLOv9, as it seems there might be a mix-up or an oversight regarding YOLOv8 and YOLOv9 functionalities and support.

2. If `yolov9-c.yaml` references custom classes or modules like "DualDDetect" that aren't part of the standard Ultralytics repo, double-check the YAML file for any typos or incorrect references, especially if it's a custom YAML configuration.

Here's a basic code snippet conforming to the standard Ultralytics setup, assuming you're working with a standard configuration:

```python
from ultralytics import YOLO  # Import the correct YOLO class

# Assuming `yolov9-c.yaml` is properly configured and path is correct
model = YOLO('path/to/yolov9-c.yaml', task='detect')  # Initialize your model for detection
model.train()  # Start the training process
```

In case `yolov9-c.yaml` and `train_dual.py` are specific to implementations not covered in the Ultralytics documentation I'm familiar with, it might be helpful to reach out directly to the contributors of those specific resources or check if there are any version-specific branches or forks of the repository that cater to YOLOv9.

If these steps don't resolve the issue, I'd recommend revisiting the Ultralytics documentation for the version you're working with, or potentially exploring forums or communities dedicated to YOLOv9 for more tailored advice.

Let me know how it goes, happy to help further if needed!

**Comment by glenn-jocher** [comment]
@zdri the message shown is correct. **Your model was trained with Wong's YOLOv9 repo which is based off of my older YOLOv5 repo, which is not compatible with the `ultralytics` repo.** 

Recommend you delete your old model and train directly with an Ultralytics-trained YOLOv9 model, which will auto-download, i.e. run

```
yolo predict model=yolov9.pt
```
