### ISSUE TITLE
opening stream method

### ISSUE THREAD

**Issue by faizelkDatapost** [ultralytics/ultralytics#976]
from yolov5 to yolov7 the default way of opening a stream supported reading a list of streams(videos/ips) from a text file.
But yolov8 does not, is there a reason why?

example in v5 and v7 this how you can execute:
track.py --source streams.txt

this would open multiple streams depending on your streams.txt file

**Comment by Laughing-q** [comment]
@faizelkDatapost I think we should have supported it, probably some updates broke it. I'll take a look.

**Comment by faizelkDatapost** [comment]
@Laughing-q chaning to .streams worked however only the first stream is visible on screen

**Comment by faizelkDatapost** [comment]
I made a git pull and the issue is resolved thanks.

**Comment by pderrenger** [comment]
@faizelkDatapost glad to hear the issue is resolved after the git pull! If you have any more questions or need further assistance, feel free to ask. Good luck with your YOLOv8 project!

**Comment by glenn-jocher** [comment]
@pderrenger great to hear the update resolved your issue! If you need further assistance, don't hesitate to reach out. Happy detecting with YOLOv8! 😊🚀
