### ISSUE TITLE
YOLOv8-Pose customization 

### ISSUE THREAD

**Issue by jjlee93** [ultralytics/ultralytics#9761]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi team, I have a question about the use of body parts.
The default configuration of the yolo-pose model is known to be composed of information about 17 keypoints. If I want to train the model only for specific parts of the body, such as excluding lower body information and focusing only on both arms, eyes, and nose, could you guys suggest how to modify it? I think I need to modify the yaml file first
kpt_shape: [17, 3]  # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)
flip_idx: [0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15]
Do I need to make any changes in the .py file other than modifying the yaml file?
Thanks.

**Comment by glenn-jocher** [comment]
@jjlee93 hi there! 😊

For customizing YOLOv8-Pose to focus on specific body parts like the arms, eyes, and nose, you will indeed start off by updating the `kpt_shape` in your YAML file to reflect the number of keypoints you're interested in. If you're focusing only on both arms (shoulder, elbow, wrist), eyes, and nose, your `kpt_shape` might change based on the keypoints you choose to keep.

Regarding the `flip_idx`, it’s used to pair keypoints for flipping augmentations. You'll need to adjust this based on the keypoints you retain.

**Example:**
If you reduce keypoints to 7 ([nose, eyes, shoulders, elbows, wrists]), your `kpt_shape` might look like `[7, 3]`, and you’d adjust `flip_idx` to mirror only these points, something like `[1, 2, 4, 3, 6, 5]` considering you're grouping left and right parts together.

You may also need to adjust the dataset preparation scripts to ensure only the keypoints of interest are included in your training data. This often does not require modifying .py files related to the model architecture but rather those involved in data preprocessing.

Make sure your annotation files (usually JSON for COCO format) only contain the keypoints you’re interested in. The model should then learn to detect only these keypoints during training.

Good luck with your project! Let us know if you have any further questions.
