### ISSUE TITLE
Benchmark failure for TensorFlow GraphDef: Graph execution error

### ISSUE THREAD

**Issue by Mirudhubashinirs** [ultralytics/ultralytics#9804]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

 Tried to run bench mark analysis on GPU for my custom dataset and I get error for TensorFlow GraphDef model format stating Graph execution error, I tried to reduce the image size to 480 and 320 from 640 and the Batch size is 1 but still the error remains the same. I have CUDA 11.8 PyTorch 2.0.0+cu118 and cuDNN 8.3 TensorFlow 2.13.1. 

### Additional

Detected at node 'PartitionedCall/model_1/tf.nn.convolution_91/convolution' defined at (most recent call last):
    File "/home/mirudhu/PycharmProjects/obj_counting/4_run_inference_gpu.py", line 12, in <module>
      benchmark(model='/home/mirudhu/Documents/Counting/CVAT/CVAT_New/ep_m_model.pt', data='/home/mirudhu/Documents/Counting/CVAT/CVAT_New/detect/detect.yaml', imgsz=480, half=False, device=0)
    File "/home/mirudhu/PycharmProjects/obj_counting/.venv/lib/python3.8/site-packages/ultralytics/utils/benchmarks.py", line 120, in benchmark
      exported_model.predict(ASSETS / "bus.jpg", imgsz=imgsz, device=device, half=half)
    File "/home/mirudhu/PycharmProjects/obj_counting/.venv/lib/python3.8/site-packages/ultralytics/engine/model.py", line 444, in predict
      self.predictor.setup_model(model=self.model, verbose=is_cli)
    File "/home/mirudhu/PycharmProjects/obj_counting/.venv/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 297, in setup_model
      self.model = AutoBackend(
    File "/home/mirudhu/PycharmProjects/obj_counting/.venv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
      return func(*args, **kwargs)
    File "/home/mirudhu/PycharmProjects/obj_counting/.venv/lib/python3.8/site-packages/ultralytics/nn/autobackend.py", line 292, in __init__
      frozen_func = wrap_frozen_graph(gd, inputs="x:0", outputs=gd_outputs(gd))
    File "/home/mirudhu/PycharmProjects/obj_counting/.venv/lib/python3.8/site-packages/ultralytics/nn/autobackend.py", line 287, in wrap_frozen_graph
      return x.prune(tf.nest.map_structure(ge, inputs), tf.nest.map_structure(ge, outputs))
Node: 'PartitionedCall/model_1/tf.nn.convolution_91/convolution'
CUDNN failed to allocate the scratch space for the runner or to find a working no-scratch runner.
	 [[{{node PartitionedCall/model_1/tf.nn.convolution_91/convolution}}]] [Op:__inference_pruned_25029]

**Comment by glenn-jocher** [comment]
@Mirudhubashinirs hey there! 👋 It looks like you're running into a CUDNN allocation issue while benchmarking your TensorFlow GraphDef model. This error often suggests that there isn’t enough GPU memory for the operations required by the model at the specified image size.

A couple of quick suggestions:
- **Reduce the image size further:** It seems you’ve already tried 480 and 320, but if your GPU memory is particularly constrained, you might need to go even lower.
- **Check GPU memory usage:** Use tools like `nvidia-smi` to monitor your GPU memory usage. Ensure other processes aren’t significantly consuming your GPU memory.

```bash
# Example command to check GPU memory usage
nvidia-smi
```
- **Try with CPU:** Temporarily switch to CPU to see if the issue persists. This can help isolate the problem to GPU memory constraints.

If the problem still isn’t resolved, please share more about your GPU specifications and the exact model structure if possible. That way, we could dive deeper into the issue.

Keep us posted! 🚀

**Comment by Mirudhubashinirs** [comment]
Hello Glenn,

1. As suggested i tried to reduce the size of the image even lower (120 and even 80) and tried but the error remains the same, also i check the memory usage and out of 4096 MiB 3340 Mib is being used. 
2. I switched to CPU to check the results and there were no issues. 

GPU specs
Description: VGA compatible controller
Product: TU117GLM [Quadro T1000 Mobile]
Vendor: NVIDIA Corporation

**Comment by glenn-jocher** [comment]
@Mirudhubashinirs hey there! 👋 Thanks for the update and for following up with those steps. It indeed sounds like a GPU memory constraint issue given that the error persists with lower image sizes and disappears when switched to CPU. With 3340 MiB out of 4096 MiB being used, there's not much room left for the operations required by the model, especially for TensorFlow GraphDef models which can be memory-intensive.

Given the specs of your Quadro T1000 Mobile, you’re pretty close to the limit of what your GPU can handle in this context. My suggestion would be to either:
- Optimize your model further, if possible, to reduce its memory footprint.
- Consider running your inference tasks on a GPU with more memory, if that's an option.

It’s always a balancing act with these models, especially on constrained resources. Keep up the great troubleshooting effort! Let us know how it goes or if there’s anything else we can help with. 🚀

**Comment by Mirudhubashinirs** [comment]
Okay Thank you :)

**Comment by glenn-jocher** [comment]
@Mirudhubashinirs hey there! You're welcome 😊 If you have any more questions or need further assistance, feel free to ask. Happy coding!
