### ISSUE TITLE
How do reset/empty the cache, where the dataset_path is being decided

### ISSUE THREAD

**Issue by running-machin** [ultralytics/ultralytics#9807]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to train to model using the following basic code
```from ultralytics import YOLO
model = YOLO('yolov8n.pt') 
results = model.train(data='open-images-v7.yaml', epochs=3)
results = model.val()
```
the issue is I can't control where the data is being downloaded and saved
```Dataset 'coco.yaml' images not found ⚠️, missing path '/workspace/persistent/PGL-SUM/datasets/coco/val2017.txt'
Downloading https://github.com/ultralytics/yolov5/releases/download/v1.0/coco2017labels-segments.zip to '/workspace/persistent/PGL-SUM/datasets/coco2017labels-segments.zip'...
100%|██████████| 169M/169M [00:00<00:00, 326MB/s]
```
I tried to uninstall the package and re-install it again, but it seems to take that specific directory location from a cache and starts downloading there. Please help to fix this, **I want to empty the so that I can change the download save directory where the dataset is saved in**. For further information, the code is being run from a jupyter notebook. The notebook was previously in the `/workspace/persistent/PGL-SUM` location but later has been changed to a different place due to hard disk space issue.

**Comment by glenn-jocher** [comment]
@running-machin hey there! 😊 It looks like you're looking to adjust the dataset download path for your training with YOLOv8. You can actually specify the download directory directly in your dataset YAML file. Here’s how you could adjust it:

1. Open your `open-images-v7.yaml` file.
2. Add or modify the `path:` attribute to specify your new directory path. For example:

```yaml
# open-images-v7.yaml
path: /new/path/for/datasets  # Your desired path
```

This will direct YOLOv8 to download the dataset to `/new/path/for/datasets`.

If this does not resolve the issue, ensure your environment (like Jupyter notebook) is pointing to the correct working directory, as it might also influence relative paths defined in your code or YAML files.

Hope this helps! Let us know if you encounter any more issues.

**Comment by running-machin** [comment]
Hi @glenn-jocher , I tried to follow your suggestion. I have copied the `open-images-v7.yaml` file to another directory from the ultralytics package(as i don't want mess the package)and edited the `yaml` file to a new path
```
path: /workspace/datasets/open-images-v7 # dataset root dir
train: images/train # train images (relative to 'path') 1743042 images
val: images/val # val images (relative to 'path') 41620 images
```
I updated the data path in train method
```
results = model.train(data='/workspace/[redacted]/open-images-v7.yaml', epochs=3)  # train the model
```
But the package seems to still like previous directory for some reason. I even moved the folder away but it creates the directory and downloads in the same directory. here is some output information from the jupyter notebook.
```
Ultralytics YOLOv8.1.42 🚀 Python-3.8.10 torch-2.2.2+cu121 CUDA:0 (NVIDIA H100 PCIe, 81231MiB)
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=/workspace/[redacted]/open-images-v7.yaml, epochs=3, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train4, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train4

Dataset '/workspace/[redacted]/open-images-v7.yaml' images not found ⚠️, missing path '/workspace/[redacted]/datasets/open-images-v7/images/val'
WARNING ⚠️ Open Images V7 dataset requires at least **561 GB of free space. Starting download...
Downloading split 'train' to '/workspace/persistent/PGL-SUM/datasets/fiftyone/open-images-v7/train' if necessary
Found 62776 images, downloading the remaining 1680266
```

**Comment by glenn-jocher** [comment]
Hi @running-machin! 😊 It seems like there's a specific cache location or a hard-coded path that's not being updated according to your changes in the YAML file. To troubleshoot, could you try executing your code in a new Jupyter notebook session? Sometimes, restarting the kernel ensures all changes are picked up accurately.

Also, please double-check the environmental variables or any configuration files for hardcoded paths that might be overriding your YAML settings. If your dataset has already been fully downloaded, you can try setting `cache=False` in your `train()` function to avoid using cached data, though this isn't directly related to download paths.
```python
results = model.train(data='/workspace/[redacted]/open-images-v7.yaml', epochs=3, cache=False)
```
If the problem persists, there might be deeper configurations within the Ultralytics package referencing the old path. Keep us posted on how it goes, and we'll dive deeper if needed!

**Comment by running-machin** [comment]
I did restart the kernel multiple times. The directory doesn't change. I tried updating `cache=False` still doesn't update to the new directory.

**Comment by glenn-jocher** [comment]
@running-machin hey there! 😊 Sorry to hear you're still facing issues. It seems like the path might be cached at a deeper level than we anticipated. Could you try cleaning any Ultralytics-specific cache directories, typically found under `~/.cache/ultralytics`? This might help eliminate any stubborn path settings. 

Additionally, you can explicitly set your dataset path in your code like this, just to ensure it's picking up the right directory:

```python
from ultralytics import YOLO, Datasets

Datasets.path = '/your/new/path'  # Set dataset path directly
model = YOLO('yolov8n.pt') 
results = model.train(data='open-images-v7.yaml', epochs=3)
```

Let's see if this helps! Keep us posted. 🚀

**Comment by running-machin** [comment]
I couldn't find `~/.cache/ultralytics` but i found `~/.cache/fiftyone` and deleted, so i couldn't find the cache file yet. I tried 
```
from ultralytics import YOLO, Datasets
Datasets.path = '/your/new/path' 
```
But I got an error. 
```
ImportError: cannot import name 'Datasets' from 'ultralytics'   (/workspace/persistent/biasenv/lib/python3.8/site-packages/ultralytics/__init__.py)
```
Hope you can help me with this.

**Comment by glenn-jocher** [comment]
@running-machin hi there! 😊 It looks like there's a slight misunderstanding with the suggestion I made earlier. My apologies for the confusion. Currently, Ultralytics YOLOv8 doesn't support directly setting the dataset path via a `Datasets` object as I incorrectly suggested.

For controlling the dataset download and storage path, you should ensure that your YAML file points to the correct location, and you're correctly passing this YAML to the `.train()` method. The approach should work as long as the YAML file's `path` key is set correctly. 

If you're still facing issues with dataset paths, it might be beneficial to manually download your dataset to the desired location and then simply reference it in your training script. 

Again, sorry for any confusion caused! Let's keep troubleshooting together if needed. 🌟
