### ISSUE TITLE
Error : while using custom block 

### ISSUE THREAD

**Issue by LakshmySanthosh** [ultralytics/ultralytics#9808]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I forked the version` 8.0.196` of ultralytics and then added a custom block to it, while trying to train with the custom block, this error is occuring.  Please help me figure out how to get rid of the error. Same happened when I added the custom block in the current up-to-date version of ultralytics too.
![image](https://github.com/ultralytics/ultralytics/assets/121610033/70e10c36-212d-4b0a-9a40-dbc88c5c9bb6)

**Comment by glenn-jocher** [comment]
@LakshmySanthosh hey there! 👋 It looks like you're diving into some advanced customization with a custom block in YOLOv8, which is awesome! To better assist, could you share a bit more detail on how you're integrating the custom block into the model? Specifically, the error message visible in the screenshot wasn't fully captured in the text. Could you describe the error, or even better, paste the error message here?

In general, when adding custom blocks, ensure:
- The block is correctly defined in the model configuration file (`.yaml`).
- Any necessary custom layers or functions are implemented and imported correctly in your model's Python files.

Here's a quick example of how to define a custom convolutional block in the YAML (assuming you have the necessary code in place to support it):
```yaml
# Define a simple custom block with convolutional layers
custom_block:
  from: -1  # from the previous layer
  number_of_filters: 64
  kernel_size: 3
  stride: 1
```
And in your model's Python file, you'd need to ensure this `custom_block` is recognized and properly utilized during the model instantiation.

Looking forward to more details, and we'll get this sorted! 🛠️

**Comment by LakshmySanthosh** [comment]
@glenn-jocher , thankyou for replying. 

I have used the same custom block on YOLOv5 and it was running properly
And also when I tried cloning my github repository and running the original yolov8m file, the same error is occurring. 
The error message is 
```
CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 7.39 µs

                   from  n    params  module                                       arguments                     
  0                  -1  1      1392  ultralytics.nn.modules.Conv                  [3, 48, 3, 2]                 
  1                  -1  1     41664  ultralytics.nn.modules.Conv                  [48, 96, 3, 2]                
  2                  -1  2    111360  ultralytics.nn.modules.C2f                   [96, 96, 2, True]             
  3                  -1  1    166272  ultralytics.nn.modules.Conv                  [96, 192, 3, 2]               
  4                  -1  4    813312  ultralytics.nn.modules.C2f                   [192, 192, 4, True]           
  5                  -1  1    664320  ultralytics.nn.modules.Conv                  [192, 384, 3, 2]              
  6                  -1  4   3248640  ultralytics.nn.modules.C2f                   [384, 384, 4, True]           
  7                  -1  1   1991808  ultralytics.nn.modules.Conv                  [384, 576, 3, 2]              
  8                  -1  2   3985920  ultralytics.nn.modules.C2f                   [576, 576, 2, True]           
  9                  -1  1    831168  ultralytics.nn.modules.SPPF                  [576, 576, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]                           
 12                  -1  2   1993728  ultralytics.nn.modules.C2f                   [960, 384, 2]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]                           
 15                  -1  2    517632  ultralytics.nn.modules.C2f                   [576, 192, 2]                 
 16                  -1  1    332160  ultralytics.nn.modules.Conv                  [192, 192, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]                           
 18                  -1  2   1846272  ultralytics.nn.modules.C2f                   [576, 384, 2]                 
 19                  -1  1    151680  ultralytics.nn.modules.DWSConv               [384, 384, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]                           
 21                  -1  2   4207104  ultralytics.nn.modules.C2f                   [960, 576, 2]                 
 22        [15, 18, 21]  1   3788434  ultralytics.nn.modules.Detect                [22, [192, 384, 576]]         
YOLOv8m_custom summary: 297 layers, 24692866 parameters, 24692850 gradients

New https://pypi.org/project/ultralytics/8.1.43 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.81 🚀 Python-3.10.13 torch-2.1.2+cpu CPU
yolo/engine/trainer: task=detect, mode=train, model=/kaggle/working/yolov8m_custom.yaml, data=/kaggle/working/datasets/thz-4/data.yaml, epochs=25, patience=50, batch=16, imgsz=416, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs/detect/train2
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 122, in __init__
    self.data = check_det_dataset(self.args.data)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/data/utils.py", line 251, in check_det_dataset
    raise FileNotFoundError(m)
FileNotFoundError: 
Dataset '/kaggle/working/datasets/thz-4/data.yaml' images not found ⚠️, missing paths ['/kaggle/working/datasets/thz-4/thz-4/valid/images']
Note dataset download directory is '/kaggle/working/datasets'. You can update this in '/root/.config/Ultralytics/settings.yaml'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/cfg/__init__.py", line 391, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 366, in train
    self.trainer = TASK_MAP[self.task][1](overrides=overrides, _callbacks=self.callbacks)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 126, in __init__
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
RuntimeError: Dataset '/kaggle/working/datasets/thz-4/data.yaml' error ❌ 
Dataset '/kaggle/working/datasets/thz-4/data.yaml' images not found ⚠️, missing paths ['/kaggle/working/datasets/thz-4/thz-4/valid/images']
Note dataset download directory is '/kaggle/working/datasets'. You can update this in '/root/.config/Ultralytics/settings.yaml'

```
And the lines of code I used are:

```
import os
HOME = os.getcwd()
print(HOME)
```

`!pip install git+https://github.com/LakshmySanthosh/yolov8_depthwise_separable_conv.git`


```
!mkdir {HOME}/datasets
%cd {HOME}/datasets

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="API_KEY")
project = rf.workspace("Project").project("projectname")
version = project.version(4)
dataset = version.download("yolov8")
```
`!git clone https://github.com/LakshmySanthosh/yolov8_depthwise_separable_conv`

```
#customize iPython writefile so we can write variables
from IPython.core.magic import register_line_cell_magic

@register_line_cell_magic
def writetemplate(line, cell):
    with open(line, 'w') as f:
        f.write(cell.format(**globals()))
```

```
%%writetemplate /kaggle/working/yolov8m_custom.yaml

# Parameters
nc: 22 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  #n: [0.33, 0.25, 1024] # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  #s: [0.33, 0.50, 1024] # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768] # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  #l: [1.00, 1.00, 512] # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  #x: [1.00, 1.25, 512] # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2f, [512]] # 12

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2f, [256]] # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2f, [512]] # 18 (P4/16-medium)

  - [-1, 1, DWSConv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2f, [1024]] # 21 (P5/32-large)

  - [[15, 18, 21], 1, Detect, [nc]] # Detect(P3, P4, P5)
```

```
# training YOLOv8
%time 
!yolo task=detect mode=train model=/kaggle/working/yolov8m_custom.yaml data={dataset.location}/data.yaml epochs=25 imgsz=416 plots=True 
```


Please help me with this error

**Comment by glenn-jocher** [comment]
Hey @LakshmySanthosh 👋, glad to assist you! From the error details and your described procedure, it seems like the core issue is related to the dataset path not being correctly found. The error:

```plaintext
FileNotFoundError: 
Dataset '/kaggle/working/datasets/thz-4/data.yaml' images not found ⚠️, missing paths ['/kaggle/working/datasets/thz-4/thz-4/valid/images']
```

suggests that the dataset directory structure or path in your `data.yaml` might not match the actual location of your images or the structure expected by YOLOv8.

Here are a couple of quick suggestions:
1. **Double-check your dataset path** in the `data.yaml` file to make sure it's correctly pointing to your dataset's directory. The path must be exact and correctly reflect your Kaggle notebook's file structure.

2. **Verify directory structure:** Ensure the dataset directory structure expected by YOLOv8 matches your current setup. It should look something like this:

    ```plaintext
    /kaggle/working/
    └── datasets/
        └── thz-4/
            ├── data.yaml
            ├── train/
            │   └── images/
            └── valid/
                └── images/
    ```

3. Since it seems you've transitioned this block successfully in YOLOv5, the YOLOv8 implementation should technically align. But, **double-check any version-specific adjustments or dependencies** in YOLOv8 that might affect this custom block.

4. If the issues persist even with the right paths, **consider permissions or path visibility** within the Kaggle environment, ensuring that the notebook has access to the locations specified in your commands.

Since the problem replicates even with the original `yolov8m` file, it points to the dataset path or environment setup in Kaggle as the potential culprit rather than your custom block integration. A closer examination of the dataset path in the Kaggle notebook against the expected structure in your `data.yaml` file should help identify and resolve the issue. 🛠️

Keep me posted on your progress!

**Comment by LakshmySanthosh** [comment]
Dataset directory structure is same as mentioned, I tried changing the dataset path from the data.yaml file as well, but then another error is showing up.  I used the same dataset and ran the model when I imported the ultralytics version 8.0.196 by `pip install ultralytics==8.0.196` from ultralytics and ran the model. The training was working properly at that time. But when I forked the repository and tried using that on my code, these errors are coming. The only change I made in my previous code is that.

**Comment by LakshmySanthosh** [comment]
@glenn-jocher 
The dataset directory structure is same as you mentioned, I tried changing the dataset path from the data.yaml file, that removed the error that was occurring before, but then another error is showing up.  

Using the same dataset I imported the ultralytics version 8.0.196 by `pip install ultralytics==8.0.196` from ultralytics and ran the model before, the training was working properly at that time. But when I forked the repository and tried using that on my code, these errors are coming. The only change I made in the code was changing that `pip install ultralytics==8.0.196` to 
`!pip install git+https://github.com/LakshmySanthosh/yolov8_depthwise_separable_conv.git` 
and `!git clone https://github.com/ultralytics/ultralytics` 
to `!git clone https://github.com/LakshmySanthosh/yolov8_depthwise_separable_conv`

**Comment by glenn-jocher** [comment]
Hey @LakshmySanthosh! 😊 It's great to hear the dataset path adjustment worked out. As for the new error popping up after forking and modifying the `pip install` line and the repository URL, it sounds like the environment or dependencies might be slightly different between the official Ultralytics version and your fork.

If the training was successful with the original Ultralytics version but failing with the fork, here are a couple of things you might want to check:

1. **Dependencies**: Ensure that all dependencies in your fork are aligned with the official version. A mismatch in the environment setup could cause unexpected issues.

2. **Code changes**: Double-check if any modifications, even outside of the `pip install` lines, could potentially affect the training process.

Here's a quick way to ensure your fork's environment matches the original:

```bash
# Original
!pip install ultralytics==8.0.196

# Your fork
!pip install git+https://github.com/LakshmySanthosh/yolov8_depthwise_separable_conv.git
```

To troubleshoot, you might also consider running the training with verbose or debug mode on (if available), to receive more detailed logs that could point to what's going wrong.

If you're still stuck, feel free to share the new error message here. Sometimes, a fresh pair of eyes can catch something you might have missed! 🤓

**Comment by LakshmySanthosh** [comment]
> Hey @LakshmySanthosh! 😊 It's great to hear the dataset path adjustment worked out. As for the new error popping up after forking and modifying the `pip install` line and the repository URL, it sounds like the environment or dependencies might be slightly different between the official Ultralytics version and your fork.
> 
> If the training was successful with the original Ultralytics version but failing with the fork, here are a couple of things you might want to check:
> 
> 1. **Dependencies**: Ensure that all dependencies in your fork are aligned with the official version. A mismatch in the environment setup could cause unexpected issues.
> 2. **Code changes**: Double-check if any modifications, even outside of the `pip install` lines, could potentially affect the training process.
> 
> Here's a quick way to ensure your fork's environment matches the original:
> 
> ```shell
> # Original
> !pip install ultralytics==8.0.196
> 
> # Your fork
> !pip install git+https://github.com/LakshmySanthosh/yolov8_depthwise_separable_conv.git
> ```
> 
> To troubleshoot, you might also consider running the training with verbose or debug mode on (if available), to receive more detailed logs that could point to what's going wrong.
> 
> If you're still stuck, feel free to share the new error message here. Sometimes, a fresh pair of eyes can catch something you might have missed! 🤓

@glenn-jocher Thankyou for taking your time to reply

The dependencies are same, and I tried running the same code using ultralytics 8.0.196 directly, it works. I think the problem might be caused by the method of installation. 

Is there any other way to train a yolov8 model by using a custom module other than this? In case of YOLOv5, just cloning the repository was enough. Please give some suggestion on this. I have been trying different things, but still not able to figure out what exactly is the cause of this series of errors. I even tried forking the present version of the repository.

**Comment by glenn-jocher** [comment]
Hey @LakshmySanthosh! 🌟 It's intriguing that everything runs smoothly with the direct use of Ultralytics 8.0.196 but not with your forked version. Since you've confirmed the dependencies align and forking the repository is where things start to get tricky, let's try a different approach similar to what worked for you with YOLOv5.

Instead of installing via `pip install git+...`, you could:
1. Clone your custom fork directly.
2. Install any required dependencies manually if they are not covered by the setup in your fork.
3. Import and use your customized YOLOv8 module directly in your scripts.

Here's a quick example:

```bash
!git clone https://github.com/LakshmySanthosh/yolov8_depthwise_separable_conv.git
%cd yolov8_depthwise_separable_conv
!pip install -r requirements.txt  # Assuming you have a requirements.txt
```

Then, in your Python code, you can import your custom YOLOv8 directly from this local repository:

```python
from yolov8_depthwise_separable_conv import YOLO  # Adjust the import statement based on your package structure
```

This approach ensures you're working with the exact environment of your fork, mimicking the successful setup you had with YOLOv5. If you face any troubles along this route or if there are specific errors thrown back, feel free to drop them here. We're all learning and troubleshooting together! 🛠️

**Comment by LakshmySanthosh** [comment]
@glenn-jocher Thankyou so much for your help.  The issue is resolved. The issue was really silly. I changed the dataset path in .yaml file associated with the data and uninstalled wandb. wandb was interrupting the training by asking for a (y/n) question for which there was no option to give input in kaggle notebook.

**Comment by glenn-jocher** [comment]
@LakshmySanthosh That's fantastic news! 🎉 I'm thrilled to hear the issue is resolved. Sometimes, it's the simplest changes that make all the difference. Good catch on the `wandb` interaction as well; those environment-specific quirks can indeed be tricky when working within notebook constraints. If you encounter any more questions or need further assistance down the road, don't hesitate to reach out. Happy coding! 😊
