### ISSUE TITLE
 inferenceSession on GPU

### ISSUE THREAD

**Issue by shimaamorsy** [ultralytics/ultralytics#9809]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In Javascript , how to inferenceSession on GPU ?

**Comment by glenn-jocher** [comment]
@shimaamorsy hey, great question! 🌟 To run an inference session on the GPU using JavaScript, you typically need to utilize a library like TensorFlow.js or ONNX.js, depending on your model format. If your model is ONNX and you're using ONNX.js, you'd set the backend to `webgl` for GPU acceleration like so:

```javascript
const session = new onnx.InferenceSession({ backendHint: 'webgl' });
```

Just ensure that the environment supports WebGL for GPU computation. Happy coding!

**Comment by shimaamorsy** [comment]
When I tried, I encountered this error 

<img width="366" alt="ll" src="https://github.com/ultralytics/ultralytics/assets/93089408/f09dcb91-e5f6-468d-9f7e-6df5910d3ca9">

in HTML page :
`<script src="onnxruntime-web-1.16.3/package/dist/ort.webgl.min.js"></script>
`
 script 
`ort.InferenceSession.create(
        "model/yolov" + modelType + modelVersion + "-seg.onnx",{ backendHint: 'webgl' }`)

**Comment by shimaamorsy** [comment]
And i have another question
What do I do if I want to quantize the the session ?

**Comment by glenn-jocher** [comment]
@shimaamorsy hey there! 🌟 It looks like you're facing an error when trying to run inference with ONNX.js. Can you please share the exact error message you're encountering? It would help in diagnosing the issue better.

Regarding applying quantization to `yolov8n.onnx`, you might want to use tools like the ONNX [Model Optimizer](https://github.com/onnx/optimizer) or [ONNX Runtime](https://www.onnxruntime.ai/docs/) which supports quantization. It typically involves converting the model to a lower precision format to reduce its size and potentially speed up inference, at the cost of a slight decrease in accuracy. Here's a basic outline of how you can do it with ONNX Runtime:

```python
import onnxruntime
from onnxruntime.quantization import quantize_dynamic, QuantType

# Path to your ONNX model
model_path = 'yolov8n.onnx'
quantized_model_path = 'yolov8n-quantized.onnx'

# Perform dynamic quantization
quantize_dynamic(model_input_path=model_path,
                 model_output_path=quantized_model_path,
                 weight_type=QuantType.QInt8)
```

This will produce a quantized version of your model, which you can then load similarly to your original model for inference. Keep in mind that appropriate hardware support might be necessary to fully leverage the advantages of quantization.
