### ISSUE TITLE
Finetune model on a category outside COCO80?

### ISSUE THREAD

**Issue by AndyWeasley2004** [ultralytics/ultralytics#9812]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to train a customized model for an object detection task. However, I found that the category I want does not appear in COCO80, and when I tried to convert my COCO format dataset into yolo, the converter encountered the error as the yolo build-in convert_coco method seems to assume the category_id has to be present in coco80. I am wondering if is there any way I can fine-tune the model on a category that is not in the pre-trained model.
![IMG_0533](https://github.com/ultralytics/ultralytics/assets/110661816/fe73810e-0d17-4fe2-b599-bc4d74cc63b2)

**Comment by AndyWeasley2004** [comment]
I have checked the code for convert_coco and the list of coco80, would the category and category_id mismatch with the coco80 cause a problem when training?

**Comment by glenn-jocher** [comment]
@AndyWeasley2004 hello! 😊 It sounds like you're running into an issue with categories not matching those in COCO80. Don't worry, you can indeed train your model on categories outside of COCO80. For your custom categories, you'll need to adjust your dataset's annotation file accordingly. 

Here's a small tip: when preparing your dataset, ensure that the `category_id` in your annotations matches the id you define in your `*.yaml` file for the dataset. The `category_id` doesn't need to align with COCO80 as long as it's consistent within your dataset. Here is an example of how to define classes in your dataset config file:

```yaml
# In your custom_data.yaml
nc: 1  # number of classes
names: ['your_custom_category']  # class names
```

Make sure your annotation file and this config file are correctly pointing to each other. This setup should guide the model to learn your custom category without expecting it to fit within the COCO80 framework.

If you're using the `convert_coco` method or similar tools that expect COCO80 classes, you might need to adapt the script slightly or create a custom preprocessing script that correctly maps your `category_id`s to your new class ids specified in your `*.yaml` file.

Happy training! 🚀

**Comment by weiwuxian1998** [comment]
@AndyWeasley2004 To leverage the pretrained model, you could replace the pretrained classifcation weights, and code can be here:
`model_esg = YOLO("yolov8_esg.yaml")  # build from YAML and transfer weights
model1 = YOLO("yolov8_esg.yaml")  # build from YAML and transfer weights
model_v8 = YOLO('./ultralytics/pt_models/yolov8m.pt')

ckpts = {}
esg = model_esg.state_dict()
v8 = model_v8.state_dict()
# import pdb
# pdb.set_trace()
for (n1,w1), (n2,w2) in zip(esg.items(),v8.items()):
    if 'cv3' in n2:
        print(n2)
        ckpts[n1] = w1
    else:
        ckpts[n1] = w2
model1.load_state_dict(ckpts)
torch.save(model1,'yolov8m_mix.pt')
# import pdb
# pdb.set_trace()
# del model1, model_v8
model_esg.load("yolov8m_mix.pt")`
