### ISSUE TITLE
The test result of COCO "test-dev2017" on the Codalab is 0

### ISSUE THREAD

**Issue by yao-zheng-yi** [ultralytics/ultralytics#9818]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The evaluation process for "test-dev2017" dataset using the specified steps is as follows:
‘’‘
model = YOLO('runs/detect/COCO-YOLOv8s/weights/best.pt')  # load a custom model
metrics = model.val(split='test',device=0, batch=64, iou=0.5, save_json=True, data='coco.yaml')
’‘’
I can also get val verification result normally. The problem is only in: compression prediction.json file uploaded to the Codalab server to get 0 result.

**Comment by yao-zheng-yi** [comment]
The same is true for the downloaded yolov8n.pt, and the result on codalab is 0

**Comment by yao-zheng-yi** [comment]
Part of predictions.json is as follows:
[{"image_id": 255037, "category_id": 19, "bbox": [415.359, 56.787, 42.416, 50.112], "score": 0.79147}, {"image_id": 255037, "category_id": 19, "bbox": [385.733, 59.841, 32.87, 47.976], "score": 0.64193}, {"image_id": 255037, "category_id": 19, "bbox": [485.992, 55.345, 40.795, 48.307], "score": 0.63716}, {"image_id": 255037, "category_id": 20, "bbox": [517.9, 62.141, 30.573, 32.196], "score": 0.32202}, {"image_id": 255037, "category_id": 19, "bbox": [518.111, 61.298, 31.122, 32.677], "score": 0.28702}, {"image_id": 255037, "category_id": 20, "bbox": [486.1, 55.189, 41.12, 48.351], "score": 0.14649}, {"image_id": 255037, "category_id": 19, "bbox": [359.063, 41.652, 89.049, 23.358], "score": 0.14467}, {"image_id": 255037, "category_id": 17, "bbox": [386.196, 59.786, 32.274, 48.332], "score": 0.12215}, {"image_id": 255037, "category_id": 19, "bbox": [330.683, 40.916, 124.344, 38.91], "score": 0.11539}, {"image_id": 255037, "category_id": 19, "bbox": [544.285, 60.667, 18.357, 10.19], "score": 0.10495}, {"image_id": 255037, "category_id": 19, "bbox": [262.516, 98.641, 8.903, 9.752], "score": 0.09798}, {"image_id": 255037, "category_id": 19, "bbox": [370.988, 62.116, 15.977, 13.338], "score": 0.06219}, {"image_id": 255037, "category_id": 19, "bbox": [335.567, 62.084, 20.579, 20.087], "score": 0.05964}, {"image_id": 255037, "category_id": 19, "bbox": [290.428, 67.637, 35.185, 12.617], "score": 0.0518}, {"image_id": 255037, "category_id": 19, "bbox": [355.646, 62.688, 10.617, 17.502], "score": 0.04907}, {"image_id": 255037, "category_id": 19, "bbox": [345.856, 61.754, 19.507, 20.036], "score": 0.04814}, {"image_id": 255037, "category_id": 17, "bbox": [485.798, 55.263, 41.474, 48.154], "score": 0.04542}, {"image_id": 255037, "category_id": 19, "bbox": [304.355, 67.371, 22.231, 16.888], "score": 0.03965}, {"image_id": 255037, "category_id": 19, "bbox": [331.682, 70.72, 17.745, 11.938], "score": 0.03778}, {"image_id": 255037, "category_id": 17, "bbox": [415.492, 57.312, 42.635, 49.203], "score": 0.03611}, {"image_id": 255037, "category_id": 19, "bbox": [357.803, 61.141, 29.708, 18.625], "score": 0.03593}, {"image_id": 255037, "category_id": 17, "bbox": [519.627, 62.633, 28.616, 31.882], "score": 0.03216}, {"image_id": 255037, "category_id": 19, "bbox": [306.804, 65.906, 19.43, 8.008], "score": 0.03049}, {"image_id": 255037, "category_id": 19, "bbox": [343.333, 53.0, 111.871, 48.39], "score": 0.03003}, {"image_id": 255037, "category_id": 19, "bbox": [308.528, 75.051, 16.275, 10.399], "score": 0.02971}, {"image_id": 255037, "category_id": 19, "bbox": [237.089, 65.941, 9.046, 9.702], "score": 0.02883}, {"image_id": 255037, "category_id": 19, "bbox": [411.591, 58.389, 26.247, 36.937], "score": 0.02836}, {"image_id": 255037, "category_id": 19, "bbox": [404.109, 59.505, 16.265, 44.282], "score": 0.02468}, {"image_id": 255037, "category_id": 19, "bbox": [330.462, 77.218, 17.361, 7.558], "score": 0.02335}, {"image_id": 255037, "category_id": 18, "bbox": [262.516, 98.641, 8.903, 9.752], "score": 0.02159}, {"image_id": 255037, "category_id": 7, "bbox": [327.329, 49.601, 39.193, 30.78], "score": 0.02083}, {"image_id": 255037, "category_id": 19, "bbox": [410.554, 60.27, 16.483, 42.779], "score": 0.01808}, {"image_id": 255037, "category_id": 20, "bbox": [386.196, 59.786, 32.274, 48.332], "score": 0.01794}, {"image_id": 255037, "category_id": 18, "bbox": [416.4, 56.787, 41.514, 49.256], "score": 0.01597}, {"image_id": 255037, "category_id": 19, "bbox": [385.482, 59.706, 18.352, 18.123], "score": 0.01497}, {"image_id": 255037, "category_id": 18, "bbox": [485.798, 55.263, 41.474, 48.154], "score": 0.01447}, {"image_id": 255037, "category_id": 19, "bbox": [378.559, 51.737, 60.274, 25.766], "score": 0.01401}, {"image_id": 255037, "category_id": 19, "bbox": [532.859, 60.962, 28.528, 22.016], "score": 0.01305}, {"image_id": 255037, "category_id": 18, "bbox": [544.285, 60.667, 18.357, 10.19], "score": 0.01236}, {"image_id": 255037, "category_id": 19, "bbox": [294.527, 71.865, 29.889, 13.688], "score": 0.01219}, {"image_id": 255037, "category_id": 19, "bbox": [386.694, 60.035, 24.084, 27.846], "score": 0.01117}, {"image_id": 255037, "category_id": 18, "bbox": [518.51, 62.232, 29.648, 32.191], "score": 0.01051}, {"image_id": 255037, "category_id": 14, "bbox": [262.516, 98.641, 8.903, 9.752], "score": 0.01008}, {"image_id": 255037, "category_id": 7, "bbox": [304.355, 67.371, 22.231, 16.888], "score": 0.00956}, {"image_id": 255037, "category_id": 7, "bbox": [333.703, 62.159, 23.893, 19.922], "score": 0.00922}, {"image_id": 255037, "category_id": 19, "bbox": [234.395, 66.208, 8.591, 9.642], "score": 0.00921}, {"image_id": 255037, "category_id": 19, "bbox": [327.603, 54.084, 39.765, 27.082], "score": 0.00909}, {"image_id": 255037, "category_id": 0, "bbox": [96.916, 94.365, 5.625, 10.165], "score": 0.00892}, {"image_id": 255037, "category_id": 17, "bbox": [544.285, 60.667, 18.357, 10.19], "score": 0.00887}, {"image_id": 255037, "category_id": 2, "bbox": [333.703, 62.159, 23.893, 19.922], "score": 0.00875}, {"image_id": 255037, "category_id": 19, "bbox": [290.396, 70.453, 10.952, 8.558], "score": 0.00874}, {"image_id": 255037, "category_id": 2, "bbox": [304.355, 67.371, 22.231, 16.888], "score": 0.00873}, {"image_id": 255037, "category_id": 19, "bbox": [419.319, 55.092, 37.746, 23.435], "score": 0.00828}, {"image_id": 255037, "category_id": 2, "bbox": [327.329, 49.601, 39.193, 30.78], "score": 0.00808}, {"image_id": 255037, "category_id": 0, "bbox": [262.516, 98.641, 8.903, 9.752], "score": 0.00806}, {"image_id": 255037, "category_id": 19, "bbox": [531.074, 62.527, 18.312, 26.48], "score": 0.00733}, {"image_id": 255037, "category_id": 19, "bbox": [327.248, 73.326, 16.044, 9.157], "score": 0.00623}, {"image_id": 255037, "category_id": 19, "bbox": [365.314, 59.597, 54.918, 32.151], "score": 0.00621}, {"image_id": 255037, "category_id": 16, "bbox": [262.516, 98.641, 8.903, 9.752], "score": 0.00557}, {"image_id": 255037, "category_id": 18, "bbox": [370.988, 62.116, 15.977, 13.338], "score": 0.00512}, {"image_id": 255037, "category_id": 2, "bbox": [331.682, 70.72, 17.745, 11.938], "score": 0.00511}, {"image_id": 255037, "category_id": 2, "bbox": [291.897, 65.711, 34.629, 13.468], "score": 0.00505}, {"image_id": 255037, "category_id": 7, "bbox": [331.682, 70.72, 17.745, 11.938], "score": 0.00493}, {"image_id": 255037, "category_id": 19, "bbox": [439.218, 57.723, 19.253, 22.772], "score": 0.0046}, {"image_id": 255037, "category_id": 18, "bbox": [385.59, 59.993, 33.087, 47.279], "score": 0.0044}, {"image_id": 255037, "category_id": 8, "bbox": [304.355, 67.371, 22.231, 16.888], "score": 0.00428}, {"image_id": 255037, "category_id": 17, "bbox": [335.567, 62.084, 20.579, 20.087], "score": 0.00427}, {"image_id": 255037, "category_id": 7, "bbox": [327.545, 41.58, 121.546, 39.16], "score": 0.00421}, {"image_id": 255037, "category_id": 20, "bbox": [330.683, 40.916, 124.344, 38.91], "score": 0.00398}, {"image_id": 255037, "category_id": 20, "bbox": [544.285, 60.667, 18.357, 10.19], "score": 0.00393}, {"image_id": 255037, "category_id": 19, "bbox": [257.107, 64.548, 8.309, 10.285], "score": 0.00385}, {"image_id": 255037, "category_id": 7, "bbox": [291.897, 65.711, 34.629, 13.468], "score": 0.00381}, {"image_id": 255037, "category_id": 22, "bbox": [544.285, 60.667, 18.357, 10.19], "score": 0.0038}, {"image_id": 255037, "category_id": 20, "bbox": [416.4, 56.787, 41.514, 49.256], "score": 0.00365}, {"image_id": 255037, "category_id": 17, "bbox": [262.516, 98.641, 8.903, 9.752], "score": 0.00343}, {"image_id": 255037, "category_id": 19, "bbox": [166.322, 95.729, 15.924, 6.627], "score": 0.00331}, {"image_id": 255037, "category_id": 20, "bbox": [359.063, 41.652, 89.049, 23.358], "score": 0.0033}, {"image_id": 255037, "category_id": 14, "bbox": [96.916, 94.365, 5.625, 10.165], "score": 0.00327}, {"image_id": 255037, "category_id": 22, "bbox": [519.249, 62.599, 28.155, 32.194], "score": 0.00315}, {"image_id": 255037, "category_id": 19, "bbox": [246.599, 64.936, 11.212, 10.304], "score": 0.00305}, {"image_id": 255037, "category_id": 14, "bbox": [137.739, 34.757, 17.992, 8.858], "score": 0.00299}, {"image_id": 255037, "category_id": 2, "bbox": [306.804, 65.906, 19.43, 8.008], "score": 0.00293}, {"image_id": 255037, "category_id": 17, "bbox": [290.428, 67.637, 35.185, 12.617], "score": 0.00292}, {"image_id": 255037, "category_id": 0, "bbox": [333.225, 69.115, 16.958, 13.411], "score": 0.00292}, {"image_id": 255037, "category_id": 17, "bbox": [345.856, 61.754, 19.507, 20.036], "score": 0.00291}, {"image_id": 255037, "category_id": 17, "bbox": [333.225, 69.115, 16.958, 13.411], "score": 0.00284}, {"image_id": 255037, "category_id": 19, "bbox": [262.406, 63.302, 8.551, 11.777], "score": 0.00282}, {"image_id": 255037, "category_id": 0, "bbox": [335.567, 62.084, 20.579, 20.087], "score": 0.00275}, {"image_id": 255037, "category_id": 16, "bbox": [518.111, 61.298, 31.122, 32.677], "score": 0.00273}, {"image_id": 255037, "category_id": 21, "bbox": [518.966, 61.906, 29.933, 33.074], "score": 0.00266}, {"image_id": 255037, "category_id": 18, "bbox": [237.089, 65.941, 9.046, 9.702], "score": 0.00266}, {"image_id": 255037, "category_id": 25, "bbox": [359.063, 41.652, 89.049, 23.358], "score": 0.00264}, {"image_id": 255037, "category_id": 25, "bbox": [306.804, 65.906, 19.43, 8.008], "score": 0.0026}, {"image_id": 255037, "category_id": 0, "bbox": [385.902, 60.046, 32.158, 47.861], "score": 0.00256}, {"image_id": 255037, "category_id": 18, "bbox": [308.528, 75.051, 16.275, 10.399], "score": 0.00255}, {"image_id": 255037, "category_id": 18, "bbox": [335.567, 62.084, 20.579, 20.087], "score": 0.00252}, {"image_id": 255037, "category_id": 5, "bbox": [327.329, 49.601, 39.193, 30.78], "score": 0.00248}

**Comment by glenn-jocher** [comment]
@yao-zheng-yi thank you for sharing the details of the issue you're encountering with the `predictions.json` file when submitting to Codalab. From the part of the `predictions.json` you've shared, the format seems to be correctly structured for COCO evaluation. Given that you're experiencing a result of 0 on Codalab, here are a couple of things you might want to double-check:

1. **Submission Format**: Ensure that the `predictions.json` file strictly follows the format expected by the Codalab COCO evaluation server. It looks correct from what you've posted, but it's good to revisit any guidelines provided by Codalab to ensure there's no deviation.

2. **Category IDs**: Verify that the `category_id` in each prediction precisely matches those expected by the COCO dataset. Mismatched or invalid `category_id` values could lead to incorrect scoring.

3. **Image IDs**: Confirm that the `image_id` corresponds accurately to the test images. An inaccurate mapping between `image_id` and the actual images could cause the evaluation to fail.

4. **Scores**: Although the scores in your predictions seem legitimate, double-check to see if there's any preprocessing or filtering step that might inadvertently alter or invalidate them.

If after checking these aspects you still face issues, it could be beneficial to directly reach out to the Codalab support or community forums for any known issues or additional insights specific to submission handling.

Here's a small sanity check you can perform on your JSON file to verify the IDs and scores correctness:

```python
import json

# Load your predictions
with open('predictions.json') as f:
    predictions = json.load(f)

# Quick sanity check
print("Number of predictions:", len(predictions))
print("Sample prediction:", predictions[0])

# Ensure there's no unexpected format or value
# Consider comparing against a subset of 'annotations' from the COCO 'test-dev' set if available for format verification
```
Let us know if you were able to find the issue or if there's any other way we can assist you. Best of luck! 🍀
