### ISSUE TITLE
why yolov8seg int8 quant is  slower than fp16?

### ISSUE THREAD

**Issue by luoshiyong** [ultralytics/ultralytics#9831]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i use pytorch-quant tools to quant(qat) yolov8s-seg,but i found that int8 precision is slower than fp16(only using --fp16 in trt), my device is nvidia NX
1.using trt --fp16
` /usr/src/tensorrt/bin/trtexec --onnx=best.onnx --workspace=4096 --saveEngine=best.engine  --fp16`
the result of infer speed is 36.8ms
![yolov8s_fp16_bs1_ns1](https://github.com/ultralytics/ultralytics/assets/38915327/65830bec-acac-4ab5-9ffe-7e2db162c5e9)

2. using pytorch_quant int8
`/usr/src/tensorrt/bin/trtexec --onnx=best.onnx --saveEngine=v8s_ptq.engine --int8 --workspace=4096`
the result of infer speed is : 39.5ms
![yoloint8_bs1_ns1](https://github.com/ultralytics/ultralytics/assets/38915327/29de3092-a15a-48d1-bdff-aac932b0919c)

**Comment by glenn-jocher** [comment]
@luoshiyong hi there! 🙌

Thanks for reaching out with your observations regarding the inference speed difference between FP16 and INT8 precision for YOLOv8-seg on your NVIDIA NX device. INT8 quantization is generally faster due to lower precision operations; however, the speed gains can sometimes be offset by the overhead of necessary kernel conversions or lack of optimization for certain operations in INT8. Each device's architecture and the specific operations used in the model can significantly influence the performance gains from different precision modes.

For your NVIDIA NX device, it's possible that the architecture benefits more from FP16 operations, or the model conversion to INT8 hasn't been fully optimized for your specific use case or hardware. I would recommend exploring TensorRT's optimization profiles or further tuning the quantization process, which might help to unlock the performance gains expected from INT8 precision. Also, ensuring that your TensorRT and PyTorch-Quant environment are fully up-to-date might bring improvements as newer versions often contain optimizations for different operations and precision modes.

Here’s a simple suggestion to update TensorRT and check for the latest updates:
```bash
sudo apt-get update
sudo apt-get upgrade tensorrt
```
And for PyTorch-Quant, make sure you’re working with the latest version compatible with your setup. It's always a good practice to consult the official NVIDIA documentation for optimization tips specific to your hardware.

Hope this helps! Let us know if you have further questions or updates on your progress. 😊

**Comment by XhHello** [comment]
> @luoshiyong hi there! 🙌
> 
> Thanks for reaching out with your observations regarding the inference speed difference between FP16 and INT8 precision for YOLOv8-seg on your NVIDIA NX device. INT8 quantization is generally faster due to lower precision operations; however, the speed gains can sometimes be offset by the overhead of necessary kernel conversions or lack of optimization for certain operations in INT8. Each device's architecture and the specific operations used in the model can significantly influence the performance gains from different precision modes.
> 
> For your NVIDIA NX device, it's possible that the architecture benefits more from FP16 operations, or the model conversion to INT8 hasn't been fully optimized for your specific use case or hardware. I would recommend exploring TensorRT's optimization profiles or further tuning the quantization process, which might help to unlock the performance gains expected from INT8 precision. Also, ensuring that your TensorRT and PyTorch-Quant environment are fully up-to-date might bring improvements as newer versions often contain optimizations for different operations and precision modes.
> 
> Here’s a simple suggestion to update TensorRT and check for the latest updates:
> 
> ```shell
> sudo apt-get update
> sudo apt-get upgrade tensorrt
> ```
> 
> And for PyTorch-Quant, make sure you’re working with the latest version compatible with your setup. It's always a good practice to consult the official NVIDIA documentation for optimization tips specific to your hardware.
> 
> Hope this helps! Let us know if you have further questions or updates on your progress. 😊

I used the YOLOv8 API on Jetson to convert pytorch to **engine** model using **Int8 quantization**, but the inference speed was not faster than FP16. May I ask how to solve this problem? Do we need to **calibrate the data**? So, how should we operate using the YOLOv8 API

**Comment by XhHello** [comment]
> > @luoshiyong hi there! 🙌
> > Thanks for reaching out with your observations regarding the inference speed difference between FP16 and INT8 precision for YOLOv8-seg on your NVIDIA NX device. INT8 quantization is generally faster due to lower precision operations; however, the speed gains can sometimes be offset by the overhead of necessary kernel conversions or lack of optimization for certain operations in INT8. Each device's architecture and the specific operations used in the model can significantly influence the performance gains from different precision modes.
> > For your NVIDIA NX device, it's possible that the architecture benefits more from FP16 operations, or the model conversion to INT8 hasn't been fully optimized for your specific use case or hardware. I would recommend exploring TensorRT's optimization profiles or further tuning the quantization process, which might help to unlock the performance gains expected from INT8 precision. Also, ensuring that your TensorRT and PyTorch-Quant environment are fully up-to-date might bring improvements as newer versions often contain optimizations for different operations and precision modes.
> > Here’s a simple suggestion to update TensorRT and check for the latest updates:
> > ```shell
> > sudo apt-get update
> > sudo apt-get upgrade tensorrt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And for PyTorch-Quant, make sure you’re working with the latest version compatible with your setup. It's always a good practice to consult the official NVIDIA documentation for optimization tips specific to your hardware.
> > Hope this helps! Let us know if you have further questions or updates on your progress. 😊



> > **Using YOLOv8 API**，But when the code is executed, it still shows the building **FP32 engine**
> > `model.export(format='engine', simplify=True， **int8=True**)`

**Comment by XhHello** [comment]
> > > @luoshiyong hi there! 🙌
> > > Thanks for reaching out with your observations regarding the inference speed difference between FP16 and INT8 precision for YOLOv8-seg on your NVIDIA NX device. INT8 quantization is generally faster due to lower precision operations; however, the speed gains can sometimes be offset by the overhead of necessary kernel conversions or lack of optimization for certain operations in INT8. Each device's architecture and the specific operations used in the model can significantly influence the performance gains from different precision modes.
> > > For your NVIDIA NX device, it's possible that the architecture benefits more from FP16 operations, or the model conversion to INT8 hasn't been fully optimized for your specific use case or hardware. I would recommend exploring TensorRT's optimization profiles or further tuning the quantization process, which might help to unlock the performance gains expected from INT8 precision. Also, ensuring that your TensorRT and PyTorch-Quant environment are fully up-to-date might bring improvements as newer versions often contain optimizations for different operations and precision modes.
> > > Here’s a simple suggestion to update TensorRT and check for the latest updates:
> > > ```shell
> > > sudo apt-get update
> > > sudo apt-get upgrade tensorrt
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And for PyTorch-Quant, make sure you’re working with the latest version compatible with your setup. It's always a good practice to consult the official NVIDIA documentation for optimization tips specific to your hardware.
> > > Hope this helps! Let us know if you have further questions or updates on your progress. 😊
> 
> > > **Using YOLOv8 API**，But when the code is executed, it still shows the building **FP32 engine**
> > > `model.export(format='engine', simplify=True， int8=True)`
