### ISSUE TITLE
模型转换错误 :TensorRT: export failure ❌ 0.0s: max() arg is an empty sequence    

### ISSUE THREAD

**Issue by abcc235** [ultralytics/ultralytics#9835]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

(yolov8_seg) wudengchao@wudengchao:~/ultralytics-main$ python
Python 3.8.18 (default, Sep 11 2023, 13:40:15) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ultralytics import YOLO
>>> model = YOLO('yolov8m.pt')
>>> model.export(format='engine')
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics YOLOv8.1.44 🚀 Python-3.8.18 torch-1.12.1+cu116 CUDA:0 (NVIDIA RTX A2000 12GB, 12036MiB)
YOLOv8m summary (fused): 218 layers, 25886080 parameters, 0 gradients, 78.9 GFLOPs

PyTorch: starting from 'yolov8m.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (49.7 MB)
ONNX: export failure ❌ 0.0s: max() arg is an empty sequence
TensorRT: export failure ❌ 0.0s: max() arg is an empty sequence
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wudengchao/ultralytics-main/ultralytics/engine/model.py", line 601, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/home/wudengchao/.conda/envs/yolov8_seg/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/wudengchao/ultralytics-main/ultralytics/engine/exporter.py", line 286, in __call__
    f[1], _ = self.export_engine()
  File "/home/wudengchao/ultralytics-main/ultralytics/engine/exporter.py", line 139, in outer_func
    raise e
  File "/home/wudengchao/ultralytics-main/ultralytics/engine/exporter.py", line 134, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/wudengchao/ultralytics-main/ultralytics/engine/exporter.py", line 657, in export_engine
    f_onnx, _ = self.export_onnx()  # run before trt import https://github.com/ultralytics/ultralytics/issues/7016
  File "/home/wudengchao/ultralytics-main/ultralytics/engine/exporter.py", line 139, in outer_func
    raise e
  File "/home/wudengchao/ultralytics-main/ultralytics/engine/exporter.py", line 134, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/wudengchao/ultralytics-main/ultralytics/engine/exporter.py", line 362, in export_onnx
    opset_version = self.args.opset or get_latest_opset()
  File "/home/wudengchao/ultralytics-main/ultralytics/utils/torch_utils.py", line 393, in get_latest_opset
    return max(int(k[14:]) for k in vars(torch.onnx) if "symbolic_opset" in k) - 1  # opset
ValueError: max() arg is an empty sequence

### Environment

Ultralytics YOLOv8.1.44 🚀 Python-3.8.18 torch-1.12.1+cu116 CUDA:0 (NVIDIA RTX A2000 12GB, 12036MiB)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by abcc235** [comment]
The yolov8m.pt used above are all just downloaded from the official website

**Comment by abcc235** [comment]
I reinstalled version 8.1.18 of ultralytics to solve the above issue, indicating a bug in model conversion using version 8.1.44.

**Comment by glenn-jocher** [comment]
@abcc235 thank you for sharing your experience and workaround with the community! It's great to hear that reverting to version 8.1.18 of Ultralytics solved the model conversion issue you encountered with version 8.1.44. 🚀

Your insight helps us identify areas for improvement. We appreciate your contribution and encourage you to continue engaging with us. If you have any more details that might help us replicate and address this bug, please feel free to share!

```bash
# For community members encountering a similar issue, here's how to install a specific version of Ultralytics YOLO:
pip install ultralytics==8.1.18
```

Thanks again for your valuable feedback! If there's anything else we can help with, please let us know.

**Comment by glenn-jocher** [comment]
Hey there! 👋 Sorry to hear you've encountered the same problem. 😢 A potential quick fix might be to revert to a version that works without this issue, say 8.1.18. You can do this by running:

```bash
pip install ultralytics==8.1.18
```

In the meantime, we'll look into the issue with version 8.2. Thanks for bringing this to our attention! Stay tuned for updates. 🚀

**Comment by IMhx233** [comment]
I had the same problem on jetson nano。
![image](https://github.com/ultralytics/ultralytics/assets/76209259/3b67daf1-e7de-4b6d-bd11-97b41a05aadc)
the latest version

**Comment by glenn-jocher** [comment]
Hey there! 😊 It looks like you've encountered a known issue with the `get_latest_opset()` function that occurs under specific configurations, particularly with certain versions of PyTorch and ONNX where the `symbolic_opset` entries aren't present as expected. Your workaround of manually specifying the opset version (`opset=11`) is spot-on! 

Here's how you can efficiently set the opset in your export call if others encounter this issue:

```python
from ultralytics import YOLO
model = YOLO('yolov8m.pt')
model.export(format='onnx', opset=11)
```

We appreciate this insight! We're looking into enhancing our version compatibility checks or updating the documentation to help navigate such issues more smoothly. 🚀 Thanks for sharing your solution!

**Comment by fkldhvu** [comment]
This happened to me in version 8.1.18,

**Comment by fkldhvu** [comment]
I specified opset=11 in export and the problem was solved

**Comment by fkldhvu** [comment]
from ultralytics import YOLO


model = YOLO("yolov8m-pose.pt")

model.export(format="engine", opset=11)

tensorrt_model = YOLO("yolov8m-pose.engine")

results = tensorrt_model("images/1.png")

**Comment by glenn-jocher** [comment]
Hey there! 👋 It looks like you've got everything set up correctly for exporting and running inference with your model. If you're experiencing any specific issues or have questions about the results, feel free to share more details. Happy coding! 🚀
