### ISSUE TITLE
Yolo v8 Batching is Processing in Series?

### ISSUE THREAD

**Issue by raunakdoesdev** [ultralytics/ultralytics#9838]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am passing in a list of images to Yolo v8 and the inference output looks like this:
```
0: 640x640 1 Caption, 3 List-items, 1 Picture, 1 Section-header, 9 Texts, 4521.4ms
1: 640x640 1 Caption, 3 List-items, 1 Picture, 1 Section-header, 9 Texts, 4521.4ms
Speed: 5.0ms preprocess, 4521.4ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 640)
```

It seems to be processing the images sequentially instead of making the shape (2, 3, 640, 640).

This occurs both with the pytorch version of the model and with the onnx version.

I'm sure I'm missing something, but I followed the docs instructions for batching and it seems that others get output with shape (N, 3, 640, 640) where N > 1. Not sure what is going wrong here.

### Additional

Reference notebook:
https://colab.research.google.com/drive/17saC4-RfiudvhW9ICU0zOKwpIUhg3nt1?usp=sharing

**Comment by glenn-jocher** [comment]
@raunakdoesdev hi there! 👋 It sounds like you're expecting to process your images in parallel (batching), but they're being processed in series. Let’s ensure a couple of things for batching to work correctly:

1. **Batch Size Adjustment**: Make sure your batch size is set to accommodate multiple images. For instance, if you're using the CLI, you can specify the batch size with `-b` or `--batch-size`. If you're using Python, ensure the `batch` argument is correctly set when initializing your model or calling the prediction method.

2. **Input Shape**: When passing a list of images, the input should indeed be reshaped to `(N, 3, H, W)` where `N` is the number of images. Verify how you're preprocessing your images before passing them to the model. You might need to stack them appropriately.

For Python API, here's a quick snippet to ensure you're setting things up correctly:

```python
from ultralytics import YOLO
model = YOLO('yolov8n.pt', device='cpu', batch=4)  # Adjust the batch size as needed

# Assuming 'images' is your list of preprocessed images
results = model.predict(images)  # 'images' should have the shape (N, 3, H, W)
```

This should allow you to process images in parallel within the defined batch size. If you continue facing issues, sharing a snippet of how you're preparing and passing the images might help diagnose further. 🕵️‍♂️

Happy detecting! 🚀

**Comment by kilimchoi** [comment]
@glenn-jocher i get 
TypeError: YOLO.__init__() got an unexpected keyword argument 'batch'
when i run 

```
from ultralytics import YOLO
model = YOLO('yolov8n.pt', batch=4)
```

my env: 

```
YOLOv8.1.45
Python-3.10.12 
torch-2.2.1+cu121 
```

**Comment by amlarraz** [comment]
Hi, 

I'm facing the same problem, an example of code:

```
from ultralytics import YOLO
import numpy as np
yolo = YOLO()
yolo(np.random.randint(0,255, (2, 3, 416,416,3)).astype(np.uint8))
```

Output:

```
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
Cell In[1], line 5
      3 yolo = YOLO()
      4 imgs = np.random.randint(0,255, (2,3,416,416)).astype(np.uint8)
----> 5 yolo.predict(imgs)

File [~/envs/face_detector/lib/python3.9/site-packages/ultralytics/engine/model.py:274](https://vscode-remote+ssh-002dremote-002bknuth.vscode-resource.vscode-cdn.net/home/alarraz/fc-ai-face-detector/notebooks/~/envs/face_detector/lib/python3.9/site-packages/ultralytics/engine/model.py:274), in Model.predict(self, source, stream, predictor, **kwargs)
    272 if prompts and hasattr(self.predictor, "set_prompts"):  # for SAM-type models
    273     self.predictor.set_prompts(prompts)
--> 274 return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)

File [~/envs/face_detector/lib/python3.9/site-packages/ultralytics/engine/predictor.py:204](https://vscode-remote+ssh-002dremote-002bknuth.vscode-resource.vscode-cdn.net/home/alarraz/fc-ai-face-detector/notebooks/~/envs/face_detector/lib/python3.9/site-packages/ultralytics/engine/predictor.py:204), in BasePredictor.__call__(self, source, model, stream, *args, **kwargs)
    202     return self.stream_inference(source, model, *args, **kwargs)
    203 else:
--> 204     return list(self.stream_inference(source, model, *args, **kwargs))

File [~/envs/face_detector/lib/python3.9/site-packages/torch/utils/_contextlib.py:35](https://vscode-remote+ssh-002dremote-002bknuth.vscode-resource.vscode-cdn.net/home/alarraz/fc-ai-face-detector/notebooks/~/envs/face_detector/lib/python3.9/site-packages/torch/utils/_contextlib.py:35), in _wrap_generator..generator_context(*args, **kwargs)
     32 try:
     33     # Issuing `None` to a generator fires it up
     34     with ctx_factory():
---> 35         response = gen.send(None)
     37     while True:
     38         try:
     39             # Forward the response to our caller and get its next request
...
    729 top, bottom = int(round(dh - 0.1)) if self.center else 0, int(round(dh + 0.1))
    730 left, right = int(round(dw - 0.1)) if self.center else 0, int(round(dw + 0.1))

error: OpenCV(4.6.0) [/io/opencv/modules/imgproc/src/resize.cpp:3689](https://vscode-remote+ssh-002dremote-002bknuth.vscode-resource.vscode-cdn.net/io/opencv/modules/imgproc/src/resize.cpp:3689): error: (-215:Assertion failed) !dsize.empty() in function 'resize'
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?6c2f4181-e9fe-4529-b42b-3013f155e027) or open in a [text editor](command:workbench.action.openLargeOutput?6c2f4181-e9fe-4529-b42b-3013f155e027). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
```
Ultralytics version: 8.1.0

The previous fix didn't worked for me:

```
from ultralytics import YOLO
import numpy as np
yolo = YOLO(batch=2)
imgs = np.random.randint(0,255, (2,3,416,416)).astype(np.uint8)
yolo.predict(imgs)
```

Output:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 3
      1 from ultralytics import YOLO
      2 import numpy as np
----> 3 yolo = YOLO(batch=2)
      4 imgs = np.random.randint(0,255, (2,3,416,416)).astype(np.uint8)
      5 yolo.predict(imgs)

TypeError: __init__() got an unexpected keyword argument 'batch'
```

**Comment by glenn-jocher** [comment]
Hey there! 👋 It looks like the issue is with the instantiation of the `YOLO` object, as `batch` is not an accepted parameter during initialization. Instead, you should set the batch size directly in the `predict()` method. Here's how you can modify your code:

```python
from ultralytics import YOLO
import numpy as np

yolo = YOLO('yolov8n.pt')  # Make sure to specify the model
imgs = np.random.randint(0, 255, (2, 3, 416, 416)).astype(np.uint8)
results = yolo.predict(imgs, batch=2)  # Set the batch size here
```

This should correctly process your images in batches. Give it a try and feel free to reach out if you have more questions! 🌟
