### ISSUE TITLE
the wrong "dtype" of exported fp16 TRT engine file 

### ISSUE THREAD

**Issue by itsrealkk** [ultralytics/ultralytics#9839]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

I am trying to export `yolov8x` model to trt engine file.
I found the `dtype` of both `fp32` and `fp16` models are the same `numpy.float32`.

```
Binding images: dtype=<class 'numpy.float32'>, shape=(1, 3, 640, 640)
Binding output0: dtype=<class 'numpy.float32'>, shape=(1, 84, 8400)
```
I think the `dtype` of `fp16` should be `<class 'numpy.float16'>`.

Why it is still `<class 'numpy.float32'>`?

### Environment

```
Ultralytics YOLOv8.1.37 🚀 Python-3.10.12 torch-2.2.2+cu118 CUDA:0 (NVIDIA GeForce RTX 3060, 12022MiB)           ░▒▓ ✔  took 3m 31s   algorithm-common-py3.10   at 18:11:17  
Setup complete ✅ (12 CPUs, 31.2 GB RAM, 132.4/439.0 GB disk)

OS                  Linux-6.5.0-26-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 31.17 GB
CPU                 12th Gen Intel Core(TM) i5-12400F
CUDA                11.8

```

### Minimal Reproducible Example

I use the following command to export the eninge file.
```shell
yolo export model=yolov8x.pt format=engine
```
and
```shell
yolo export model=yolov8x.pt format=engine half=True
```

And I use the follwing code to print the infos of bindings:
```python
import tensorrt as trt


trt_logger = trt.Logger(trt.Logger.ERROR)
trt_runtime = trt.Runtime(trt_logger)

with open("yolov8x_fp16.engine", "rb") as f:
    meta_len = int.from_bytes(f.read(4), byteorder="little")
    meta_data = f.read(meta_len).decode("utf-8")
    engine = trt_runtime.deserialize_cuda_engine(f.read())

context = engine.create_execution_context()

for i in range(engine.num_bindings):
    name = engine.get_tensor_name(i)
    dtype = trt.nptype(engine.get_tensor_dtype(name))
    shape = tuple(context.get_tensor_shape(name))

    print(f"Binding {name}: dtype={dtype}, shape={shape}")
```
Then I got the following prints for `yolov8x_fp16.engine`:
```
Binding images: dtype=<class 'numpy.float32'>, shape=(1, 3, 640, 640)
Binding output0: dtype=<class 'numpy.float32'>, shape=(1, 84, 8400)
```
and the same prints for `yolov8x_fp32.engine`:
```
Binding images: dtype=<class 'numpy.float32'>, shape=(1, 3, 640, 640)
Binding output0: dtype=<class 'numpy.float32'>, shape=(1, 84, 8400)
```

However , I have tested the speed of each engine file:

For `fp16`: 
```
Speed: 1.4ms preprocess, 12.2ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 640)
```
and for `fp32`: 
```
Speed: 1.4ms preprocess, 33.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)
```

Although `fp16` has shorter time for infering, I think the `dtype` of `fp16` should be `<class 'numpy.float16'>`.

Why it is still `<class 'numpy.float32'>`?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by itsrealkk** [comment]
The same for `ultralytics/nn/autobackend.py` file
from the line `242` in `autobackend.py` file
```python
            for i in range(model.num_bindings):
                name = model.get_binding_name(i)
                dtype = trt.nptype(model.get_binding_dtype(i))
                if model.binding_is_input(i):
                    if -1 in tuple(model.get_binding_shape(i)):  # dynamic
                        dynamic = True
                        context.set_binding_shape(i, tuple(model.get_profile_shape(0, i)[2]))
                    if dtype == np.float16:
                        fp16 = True
                else:  # output
                    output_names.append(name)
``` 
I have added a print command on line `245` which  #is
```python
            for i in range(model.num_bindings):
                name = model.get_binding_name(i)
                dtype = trt.nptype(model.get_binding_dtype(i))
                print(dtype)
                if model.binding_is_input(i):
                    if -1 in tuple(model.get_binding_shape(i)):  # dynamic
                        dynamic = True
                        context.set_binding_shape(i, tuple(model.get_profile_shape(0, i)[2]))
                    if dtype == np.float16:
                        fp16 = True
                else:  # output
                    output_names.append(name)
``` 
The dtype is also `<class 'numpy.float32'>`

**Comment by glenn-jocher** [comment]
@itsrealkk hello! Thanks for bringing up your observation regarding the data types of the exported TRT engines, which is indeed a keen insight. 🧐 

The behavior you're witnessing, where the data types of input and output bindings for both FP16 and FP32 models appear as `<class 'numpy.float32'>`, stems from a subtle aspect of how TensorRT works under the hood. When you export a model with FP16 precision, the computations within the model are indeed performed in FP16 to leverage the speed and efficiency gains. However, for ease of integration with other components and frameworks that may not universally support FP16, the inputs and outputs are often cast back to FP32. This casting ensures compatibility but does not negate the internal computational efficiency gained by using FP16.

The difference in inference speed you've noted between the FP32 and FP16 models demonstrates the internal efficiency gains from using FP16 precision. The apparent `dtype` for inputs and outputs does not directly reflect the precision of the internal calculations but rather the interface format for data input/output operations.

I hope this clarifies the situation! If you have further questions or insights, feel free to share. Happy coding! 🚀

**Comment by itsrealkk** [comment]
Thanks for the detailed explanation of TensorRT, issue closed.

**Comment by glenn-jocher** [comment]
@itsrealkk You're welcome! I'm glad the explanation helped. If you have any more questions in the future or need further assistance, feel free to reach out. Happy coding, and keep exploring YOLOv8! 🌟
