### ISSUE TITLE
# zh

### ISSUE THREAD

**Issue by san-kou7** [ultralytics/ultralytics#9841]
# zh

借于文档中的仔细指导，我已成功将数据集制作成yolo格式，修改完成配置文件，并完成了yolov8n-pose的训练。为了优化训练结果，我希望在数据集中加入负样本（人为制作），请问这个负样本是否需要使用labeling打标，如果需要请问如何标注；负样本图片和标签文件都与正样本同样放在train/images与train/labels路径中吗？
收到您的回复，我将感激不尽

**Comment by glenn-jocher** [comment]
@san-kou7 非常高兴听到您已经成功地将数据集转换为YOLO格式并完成了yolov8n-pose的训练！👏 关于负样本的加入，确实可以帮助模型更好地理解背景信息并降低假阳性率。对于负样本（即不包含您要检测的对象的图片），您无需进行标注。简言之，只需将这些没有目标对象的图片放入`train/images`目录下就可以了，无需对应的标签文件。这样做将直接告诉模型这些图片中不存在任何感兴趣的对象。

祝您的项目成功！🚀

**Comment by san-kou7** [comment]
非常感谢您的回复！我受益良多。
我想进一步请问您负样本内容相关的问题：请问您觉得负样本图像的使用是否需要跟正样本的场景相同甚至是图像背景相同（将需要处理的目标抠除或者裁剪？），以及正负样本的比例是否需要1:1或者是1:2？等候您的指导，十分感谢。

**Comment by glenn-jocher** [comment]
@san-kou7 很高兴能帮到您！😊 对于负样本的使用，我建议：

1. 负样本应尽可能地反映正样本的场景背景。这有助于模型学习在相同背景下区分有无目标对象。您无需将目标从图像中去除或裁剪，只需要选择自然中没有您要检测目标的图片即可。
2. 关于正负样本的比例，并没有绝对的规则，这很多时候取决于您的具体任务和数据集。一般来说，开始时可以尝试1:1的比例，然后根据验证集上的表现调整比例。如果发现模型对背景误判较多，可以适当增加负样本比例。

希望这些建议能对您有所帮助！继续加油！🚀

**Comment by ykhasia** [comment]
> [@san-kou7](https://github.com/san-kou7) 非常高兴听到您已经成功地将数据集转换为YOLO格式并完成了yolov8n-pose的训练！👏 关于负样本的加入，确实可以帮助模型更好地理解背景信息并降低假阳性率。对于负样本（即不包含您要检测的对象的图片），您无需进行标注。简言之，只需将这些没有目标对象的图片放入`train/images`目录下就可以了，无需对应的标签文件。这样做将直接告诉模型这些图片中不存在任何感兴趣的对象。
> 
> 祝您的项目成功！🚀


你好，关于你提到的【将这些没有目标对象的图片放入`train/images`目录下】，以下是我的训练目录，是把负样本放到截图中标红的目录中(train)吗？我的目录结构不是tran/images，而是images/train。 谢谢
<img width="1144" height="161" alt="Image" src="https://github.com/user-attachments/assets/0e156ac2-5d2b-49c5-8b95-ebfddb6ad14e" />

**Comment by glenn-jocher** [comment]
是的，按您现在的结构应把负样本放在 `images/train`，对应标签放在 `labels/train`；如果该图像里没有任何目标，通常保留同名空 `.txt` 标签文件最稳妥，目录可参考 [Tiger-Pose 数据集结构示例](https://docs.ultralytics.com/datasets/pose/tiger-pose/)；另外这个 issue 已是 `Stale`/closed，如还有后续问题请新开一个 issue 方便团队跟进。
