### ISSUE TITLE
GPU utilization  always zero

### ISSUE THREAD

**Issue by kutieling** [ultralytics/ultralytics#9843]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I used yolov8 to train cityscapes datasets, GPU utilization was always zero. Then I found that my CPU was underutilized, only CPU1 and CPU11 were at 100% utilization. The other cpus were not utilized, which resulted in my data enhancement being extremely slow during the training. I adjusted the works parameter of dataloader, but it doesn't work. Does anyone know the solution? Thank you very much
![Uploading 01934fd7fad7fbc773c64cb0697c7532.png…]()

**Comment by glenn-jocher** [comment]
@kutieling hello! It sounds like you're experiencing low GPU utilization while training on the cityscapes datasets with YOLOv8. This is often related to data loading and preprocessing steps being slower than the training itself, causing the GPU to wait. Here are a few suggestions to improve the situation:

1. Ensure you have the latest version of both PyTorch and YOLOv8 from the Ultralytics repository, as performance improvements are regularly added.
2. Increase the number of workers in the DataLoader if your system has the resources. Although you've mentioned adjusting the `workers` parameter without success, it's worth experimenting with different values higher than the default. For example:
   ```python
   model.train(data='cityscapes.yaml', epochs=100, imgsz=640, workers=16)
   ```
3. Consider using SSDs (Solid State Drives) for faster data loading if you're not already doing so.
4. Optimize your dataset storage format; for instance, storing images in a compressed archive could be slower to access than individual files on an SSD.
5. Lastly, monitor if other processes on your system could be affecting training. The high utilization on specific CPUs could indicate a system-level bottleneck.

If these steps don't lead to improvements, providing more details about your system configuration and a snippet of your training command could help diagnose the issue further. Thanks for reaching out! 🚀
