### ISSUE TITLE
GPU utilization always zero

### ISSUE THREAD

**Issue by kutieling** [ultralytics/ultralytics#9844]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When I used yolov8 to train cityscapes datasets, GPU utilization was always zero. Then I found that my CPU was underutilized, only CPU1 and CPU11 were at 100% utilization. The other cpus were not utilized, which resulted in my data enhancement being extremely slow during the training. I adjusted the works parameter of dataloader, but it doesn't work. Does anyone know the solution? Thank you very much
![IMG_3666](https://github.com/ultralytics/ultralytics/assets/133850573/fef7bf8f-7402-4cd1-9e30-669493fec593)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by BabyWaffles** [comment]
You will need to pip install torch==2.1.2+cu118. you get can the whole install script from Pytorch Get started page.

**Comment by kutieling** [comment]
> You will need to pip install torch==2.1.2+cu118. you get can the whole install script from Pytorch Get started page.

Thank you for your answer. Could you please tell me why? Why would changing the pytorch version fix this?

**Comment by BabyWaffles** [comment]
> > You will need to pip install torch==2.1.2+cu118. you get can the whole install script from Pytorch Get started page.
> 
> Thank you for your answer. Could you please tell me why? Why would changing the pytorch version fix this?

Since your GPU utilization is at 0% when training/inferencing, PyTorch might have not installed the package without cuda compiled inside. You will need to explicitly specify to install it with cuda and ultralytics package won't install PyTorch with cuda since it assumes that everybody will use CPU. To add on, if the training phase is using lesser CPU threads than anticipated, you can specify the number of threads you desire to use by adding the "workers=x" (Change the x to the amount of threads you want to use.) args in the training line.

**Comment by kutieling** [comment]
Thank you for your reply. I have installed pytorch through the command line: PIP install torch = = 2.0.0 torchvision = = 0.15.1 torchaudio = = 2.0.1 - index - the url https://download.pytorch.org/whl/cu118, To do the installation. I also changed the works parameter of dataloader from the default 2 to 8 and 16, but still only CPU1 and CPU11 are at 100% utilization, and the other cpus are not involved in data enhancement during training. Thank you for your reply.
![Uploading IMG_3666.png…]()

**Comment by kutieling** [comment]
> > > You will need to pip install torch==2.1.2+cu118. you get can the whole install script from Pytorch Get started page.
> > 
> > 
> > Thank you for your answer. Could you please tell me why? Why would changing the pytorch version fix this?
> 
> Since your GPU utilization is at 0% when training/inferencing, PyTorch might not have installed the package with cuda compiled inside. You will need to explicitly specify to install it with cuda and ultralytics package won't install PyTorch with cuda since it assumes that everybody will use CPU. To add on, if the training phase is using lesser CPU threads than anticipated, you can specify the number of threads you desire to use by adding the "workers=x" (Change the x to the amount of threads you want to use.) args in the training line.

Thank you for your reply. I have installed pytorch through the command line: PIP install torch = = 2.0.0 torchvision = = 0.15.1 torchaudio = = 2.0.1 - index - the url https://download.pytorch.org/whl/cu118, To do the installation. I also changed the works parameter of dataloader from the default 2 to 8 and 16, but still only CPU1 and CPU11 are at 100% utilization, and the other cpus are not involved in data enhancement during training. Thank you for your reply.
![IMG_3666](https://github.com/ultralytics/ultralytics/assets/133850573/dadb5228-3bb8-4a25-8958-5a88050d5a67)

**Comment by glenn-jocher** [comment]
@kutieling it sounds like you've taken the right steps by installing PyTorch with CUDA support to utilize the GPU and experimenting with the `workers` parameter to adjust CPU utilization. If the GPU still isn't being utilized, it could be that your environment or the PyTorch version isn't correctly recognizing the GPU.

One thing you could try is verifying if PyTorch can detect your GPU with the following command in your Python environment:

```python
import torch
print(torch.cuda.is_available())
```

This should return `True` if PyTorch is set up correctly to use the GPU. If it returns `False`, PyTorch isn't recognizing your GPU, which might mean a mismatch between the CUDA version installed and the CUDA version PyTorch expects, or another issue related to CUDA setup.

Furthermore, regarding the CPU utilization, it's worth noting that data loading and augmentation are typically not heavily parallelized processes. Although increasing the `workers` parameter should theoretically distribute the load more broadly across CPUs, the actual improvement varies depending on the specific operations performed and how I/O bound those operations are.

If you haven't yet, ensuring your dataset and any augmentation are optimized for parallel processing may help. This could involve pre-processing steps or leveraging libraries optimized for multi-threading. 

Lastly, it could also be beneficial to check if other system limitations or configurations might be affecting performance. For instance, ensuring your data is stored on fast-access storage like an SSD could alleviate bottlenecks related to data loading.

Hope this helps! Let me know how it goes or if you encounter any other issues. 🙂

**Comment by BabyWaffles** [comment]
You should try Glenn 's method first. From the looks of it, it seems like your GPUs support up to 12.2. May I know whether have you installed the Cuda Developer Kit 11.8? If yes, then the second problem, which gpu did you specify to train it on. Because from the looks of it, Ubuntu is reporting the utilization wrongly since from what i can see, it is using GPU 0 by looking at the wattage it is drawing and using GPU 1'S memory to train.

**Comment by glenn-jocher** [comment]
@BabyWaffles certainly! It looks like you might be right about the GPU utilization display issue. Additionally, ensuring compatibility with your NVIDIA CUDA version is crucial for optimal performance. If you haven't already, installing CUDA Toolkit 11.8 matched to your GPU's capability can help. Here's a quick check to see if PyTorch recognizes your GPU and to confirm the CUDA version it's using:

```python
import torch
print('CUDA Available:', torch.cuda.is_available())
print('CUDA Version:', torch.version.cuda)
```

For specifying which GPU to train on in PyTorch, you can set the `CUDA_VISIBLE_DEVICES` environment variable before running your script, for example:
```bash
export CUDA_VISIBLE_DEVICES=0  # For using only the first GPU
```

Or, directly in Python:
```python
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
```

This ensures you're training on the correct GPU. Also, using `nvidia-smi` can help monitor real-time GPU utilization. Keep us posted on how it goes! 😊
