### ISSUE TITLE
Both training and validation DFL_loss are zero.

### ISSUE THREAD

**Issue by shemil076** [ultralytics/ultralytics#9846]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I am currently working on detecting occluded objects in realtime using the YOLO v8 algorithm. To improve the accuracy of my detections, I have implemented a CBAM attention module and updated the traditional loss function from IoU to EIoU. Additionally, I am using soft_nms, which utilizes EIoU instead of IoU. To further enhance the robustness of my model, I have also incorporated data augmentations such as mosaic.

But I am having a couple of questions,

1. During the customized model training, both train and val dfl_loss values are zero. Can you help me figure out why?
![results](https://github.com/ultralytics/ultralytics/assets/85215233/c14f679f-603e-4909-8bd0-538e767d9996)

3. Furthermore, I tried to add CBAM modules to the architecture and included the CBAM layer in the parse_model() function. However, this approach resulted in some errors. Could you please provide me with some guidance on how to resolve this issue?

- Customized architecture
<img width="802" alt="Screenshot 2024-04-07 at 6 45 44 PM" src="https://github.com/ultralytics/ultralytics/assets/85215233/9a9d2d26-190c-41a1-ac8a-eae40af4ca00">

- How I add the CBAM to the parse_model() function
<img width="805" alt="Screenshot 2024-04-07 at 6 45 08 PM" src="https://github.com/ultralytics/ultralytics/assets/85215233/f2c92521-1a0c-45c1-89bd-384052369ce0">

- The error I am getting.
<img width="1042" alt="Screenshot 2024-04-07 at 6 45 23 PM" src="https://github.com/ultralytics/ultralytics/assets/85215233/986c40e0-dd63-4922-82f9-fad7d0764bbc">

**Comment by glenn-jocher** [comment]
@shemil076 hello there! 

For the dfl_loss being zero, it's possible that there might be an issue with how the EIoU is being computed or integrated with your loss function. Please double-check the loss function implementation, ensuring that it properly interacts with the CBAM and soft_nms modifications. Sometimes, zero loss can also result from numerical issues, so verifying the output of each component might help identify the problem. 😉

Regarding adding the CBAM module and encountering errors in the `parse_model()` function, it seems like there might be a mismatch or an oversight in how the CBAM layers are being integrated. Ensure that the CBAM layer inputs and outputs align with what the model expects at each point. It might also help to isolate the issue by testing the CBAM module separately to confirm it works as expected before integrating. Here's a simplified example of adding a custom module:

```python
class CustomModel(nn.Module):
    def __init__(self):
        super(CustomModel, self).__init__()
        self.cbam = CBAMModule(...)  # your CBAM module initialization

    def forward(self, x):
        x = self.cbam(x)  # Apply CBAM operation
        # proceed with other operations
        return x
```

Ensure that the integration of the CBAM layer within your architecture does not disrupt the expected input-output relationship among layers. Checking the dimensions and the data flow might give you a clue about what's going wrong.

If you continue to face issues, could you please share more detailed code snippets or error messages? This could help in diagnosing the problem more effectively. Keep up the great work on customizing YOLOv8! 🚀

**Comment by shemil076** [comment]
Hello @glenn-jocher 

Thank you for your valuable guidance.

I believe I have resolved the issues causing both the training and validation DFL loss to zero.
![results](https://github.com/ultralytics/ultralytics/assets/85215233/a592656e-f155-43f7-924c-04b021fa7c14)


However after training a custom YOLO model on a dataset of 2373 images, the resulting graphs were as below.

![confusion_matrix](https://github.com/ultralytics/ultralytics/assets/85215233/bc9acb48-7fcf-4b65-975e-86bfbdb8a143)
![F1_curve](https://github.com/ultralytics/ultralytics/assets/85215233/bb56179d-1ecd-408f-b805-93f1d3f3e3af)
![P_curve](https://github.com/ultralytics/ultralytics/assets/85215233/3d93b10f-600d-4453-bc46-8e13ed3f8772)
![PR_curve](https://github.com/ultralytics/ultralytics/assets/85215233/bf9c6814-a0f3-4996-8ee6-c3cebfea31a3)
![R_curve](https://github.com/ultralytics/ult
[results.csv](https://github.com/ultralytics/ultralytics/files/14908344/results.csv)
ralytics/assets/85215233/81ed2541-2b2b-49c9-8d9e-1e1c158b39a6)


Could you please help me figure out what is happening and how to fix this?

I made a small architectural change to the previously mentioned architecture.

`backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, CBAM, [512]] # CBAM after C2f block
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, CBAM, [1024]] # CBAM before SPPF for enhanced attention
  - [-1, 1, SPPF, [1024, 5]] # 9`
  
  This is the implementation of the CBAM module.
  
`class ChannelAttention(nn.Module):

    def __init__(self, in_planes, ratio=16):

        super().__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)
        self.f1 = nn.Conv2d(in_planes, in_planes // ratio, 1, bias=False)
        self.relu = nn.ReLU()
        self.f2 = nn.Conv2d(in_planes // ratio, in_planes, 1, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):

        avg_out = self.f2(self.relu(self.f1(self.avg_pool(x))))
        max_out = self.f2(self.relu(self.f1(self.max_pool(x))))
        out = self.sigmoid(avg_out + max_out)
        return out


class SpatialAttention(nn.Module):

    def __init__(self, kernel_size=7):
 
        super().__init__()
        assert kernel_size in (3, 7), 'kernel size must be 3 or 7'
        padding = 3 if kernel_size == 7 else 1
        self.conv = nn.Conv2d(2, 1, kernel_size, padding=padding, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):

        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        x = torch.cat([avg_out, max_out], dim=1)
        x = self.conv(x)
        return self.sigmoid(x)


class CBAM(nn.Module):
    # ch_in, ch_out, shortcut, groups, expansion, ratio, kernel_size
    def __init__(self, c1, c2, kernel_size=3, shortcut=True, g=1, e=0.5, ratio=8):

        super().__init__()
        c_ = int(c2 * e)  # hidden channels
        self.cv1 = Conv(c1, c_, 1, 1)
        self.cv2 = Conv(c_, c2, 3, 1, g=g)
        self.add = shortcut and c1 == c2
        self.channel_attention = ChannelAttention(c2, ratio)
        self.spatial_attention = SpatialAttention(kernel_size)

    def forward(self, x):

        x2 = self.cv2(self.cv1(x))
        out = self.channel_attention(x2) * x2
        out = self.spatial_attention(out) * out
        return x + out if self.add else out`
        
This is the bbox_eiou that is used for both the loss function and the soft-nms.
`def bbox_eiou(box1, box2, eps=1e-7):

    # Get the coordinates of bounding boxes
    b1_x1, b1_y1, b1_x2, b1_y2 = box1.chunk(4, -1)
    b2_x1, b2_y1, b2_x2, b2_y2 = box2.chunk(4, -1)
    w1, h1 = b1_x2 - b1_x1, b1_y2 - b1_y1 + eps
    w2, h2 = b2_x2 - b2_x1, b2_y2 - b2_y1 + eps

    # Intersection area
    inter = (b1_x2.minimum(b2_x2) - b1_x1.maximum(b2_x1)).clamp_(0) * \
            (b1_y2.minimum(b2_y2) - b1_y1.maximum(b2_y1)).clamp_(0)

    # Union Area
    union = w1 * h1 + w2 * h2 - inter + eps

    # IoU
    iou = inter / union

    cw = b1_x2.maximum(b2_x2) - b1_x1.minimum(b2_x1)  # convex (smallest enclosing box) width
    ch = b1_y2.maximum(b2_y2) - b1_y1.minimum(b2_y1)  # convex height

    c2 = cw ** 2 + ch ** 2 + eps  # convex diagonal squared
    rho2 = ((b2_x1 + b2_x2 - b1_x1 - b1_x2) ** 2 + (b2_y1 + b2_y2 - b1_y1 - b1_y2) ** 2) / 4  # center dist ** 2


    rho_w2 = ((b2_x2 - b2_x1) - (b1_x2 - b1_x1)) ** 2
    rho_h2 = ((b2_y2 - b2_y1) - (b1_y2 - b1_y1)) ** 2
    cw2 = cw ** 2 + eps
    ch2 = ch ** 2 + eps
    return iou - (rho2 / c2 + rho_w2 / cw2 + rho_h2 / ch2) # EIoU`
    
    `class BboxLoss(nn.Module):
    """Criterion class for computing training losses during training."""

    def __init__(self, reg_max, use_dfl=False):
        """Initialize the BboxLoss module with regularization maximum and DFL settings."""
        super().__init__()
        self.reg_max = reg_max
        self.use_dfl = use_dfl

    def forward(self, pred_dist, pred_bboxes, anchor_points, target_bboxes, target_scores, target_scores_sum, fg_mask):
        """IoU loss."""
        weight = target_scores.sum(-1)[fg_mask].unsqueeze(-1)

        iou = bbox_eiou(pred_bboxes[fg_mask], target_bboxes[fg_mask])
        
        if type(iou) is tuple:
            if len(iou) == 2:
                loss_iou = ((1.0 - iou[0]) * iou[1].detach() * weight).sum() / target_scores_sum
            else:
                loss_iou = (iou[0] * iou[1] * weight).sum() / target_scores_sum
        else:
            loss_iou = ((1.0 - iou) * weight).sum() / target_scores_sum

        # DFL loss
        if self.use_dfl:
            target_ltrb = bbox2dist(anchor_points, target_bboxes, self.reg_max)
            loss_dfl = self._df_loss(pred_dist[fg_mask].view(-1, self.reg_max + 1), target_ltrb[fg_mask]) * weight
            loss_dfl = loss_dfl.sum() / target_scores_sum
        else:
            loss_dfl = torch.tensor(0.0).to(pred_dist.device)

        return loss_iou, loss_dfl

    @staticmethod
    def _df_loss(pred_dist, target):
        """Return sum of left and right DFL losses."""
        # Distribution Focal Loss (DFL) proposed in Generalized Focal Loss https://ieeexplore.ieee.org/document/9792391
        tl = target.long()  # target left
        tr = tl + 1  # target right
        wl = tr - target  # weight left
        wr = 1 - wl  # weight right
        return (F.cross_entropy(pred_dist, tl.view(-1), reduction='none').view(tl.shape) * wl +
             F.cross_entropy(pred_dist, tr.view(-1), reduction='none').view(tl.shape) * wr).mean(-1, keepdim=True)`
             
       This is the implementation of soft-NMS
       
      `def soft_nms(bboxes, scores, iou_thresh=0.5, sigma=0.5,score_threshold=0.25):
    
    order = torch.arange(0, scores.size(0)).to(bboxes.device)
    keep = []

    while order.numel() > 1:
        if order.numel() == 1:
            keep.append(order[0])
            break
        else:
            i = order[0]
            keep.append(i)
        
        iou = bbox_eiou(bboxes[i:i+1], bboxes[order[1:]]).squeeze()
        
        idx = (iou > iou_thresh).nonzero().squeeze()
        if idx.numel() > 0: 
            iou = iou[idx] 
            newScores = torch.exp(-torch.pow(iou,2)/sigma)
            scores[order[idx+1]] *= newScores
        
        newOrder = (scores[order[1:]] > score_threshold).nonzero().squeeze() 
        if newOrder.numel() == 0: 
            break
        else:
            maxScoreIndex = torch.argmax(scores[order[newOrder+1]]) 
            if maxScoreIndex != 0: 
                newOrder[[0,maxScoreIndex],] = newOrder[[maxScoreIndex,0],]
            order = order[newOrder+1]
    
    return torch.LongTensor(keep)`
    
    
    
    Your valuable guidance is really helpful at this moment. Thank you.

**Comment by glenn-jocher** [comment]
Hey @shemil076,

It's great to hear you've made progress on the dfl_loss issue! 🎉 Regarding the architectural changes and the confusion around the resulting graphs, it seems the integration of CBAM and the adjustments to the loss function might need a closer look. Here are a few suggestions:

- Double-check the **dimensionality** and **flow** of inputs and outputs in your modified architecture, especially around the newly introduced CBAM blocks. Ensure that the feature maps maintain expected dimensions.
- Review the **CBAM module integration**. Sometimes, sophisticated modules like CBAM require careful positioning within the network to effectively capture the intended context without disrupting the training dynamics.
- For the custom loss function, ensure that **gradients are flowing** properly through the new components. Adding logging statements to monitor gradients or using tools like TensorBoard can help identify if certain parts are not contributing to the learning process efficiently.
- **Experiment** with different parameter settings for your loss function and CBAM module. These components can significantly affect training dynamics, and finding the right balance often requires some experimentation.

Since your custom modifications involve both architectural changes and loss adjustments, isolating the effects of these two factors could be beneficial. You might try **ablation studies** where you modify only one aspect at a time to better understand its influence.

Also, remember to check the **quality of your dataset** and ensure it's well-labeled and balanced. Sometimes, data issues can manifest as perplexing results during training.

Your experiment with architectural enhancements and advanced loss functions is definitely on an inspiring path! Keep iterating and fine-tuning. With persistence and careful adjustments, you'll likely overcome these hurdles. 🚀

If there's anything more specific you'd like guidance on or if there are further details you could share, feel free to reach out!

**Comment by shemil076** [comment]
Hello @glenn-jocher 


As you mentioned, I have tested each implementation by isolating them. Accordingly, I trained the model without using soft nms for 10 epochs. During this process, I noticed that the shape of the graphs were normal. However, when I used soft-nms, the shapes of the graphs became quite annoying.

**Graphs without soft-nms**
![without-Soft-nmsF1_curve](https://github.com/ultralytics/ultralytics/assets/85215233/09afbd88-c803-4e47-a3af-a11f37e66a5d)

![without-soft-nms-P_curve](https://github.com/ultralytics/ultralytics/assets/85215233/daac167d-ae43-4ec7-8f82-4b985520e36e)

**Graphs with soft-nms**
![with-soft-nms-F1_curve](https://github.com/ultralytics/ultralytics/assets/85215233/d624de5e-6672-40d8-89e6-1b8eb423a2ee)
![with-soft-nms-P_curve](https://github.com/ultralytics/ultralytics/assets/85215233/3e1fc7af-9f2b-4912-a83b-a72f27d30b15)

Implementation of soft-nms

`def box_iou_for_nms(box1, box2, GIoU=False, DIoU=False, CIoU=False, SIoU=False, EIou=False, eps=1e-7):
    # Returns Intersection over Union (IoU) of box1(1,4) to box2(n,4)

    b1_x1, b1_y1, b1_x2, b1_y2 = box1.chunk(4, -1)
    b2_x1, b2_y1, b2_x2, b2_y2 = box2.chunk(4, -1)
    w1, h1 = b1_x2 - b1_x1, (b1_y2 - b1_y1).clamp(eps)
    w2, h2 = b2_x2 - b2_x1, (b2_y2 - b2_y1).clamp(eps)

    # Intersection area
    inter = (b1_x2.minimum(b2_x2) - b1_x1.maximum(b2_x1)).clamp(0) * \
            (b1_y2.minimum(b2_y2) - b1_y1.maximum(b2_y1)).clamp(0)

    # Union Area
    union = w1 * h1 + w2 * h2 - inter + eps

    # IoU
    iou = inter / union
    if CIoU or DIoU or GIoU or EIou:
        cw = b1_x2.maximum(b2_x2) - b1_x1.minimum(b2_x1)  # convex (smallest enclosing box) width
        ch = b1_y2.maximum(b2_y2) - b1_y1.minimum(b2_y1)  # convex height
        if CIoU or DIoU or EIou:  # Distance or Complete IoU https://arxiv.org/abs/1911.08287v1
            c2 = cw ** 2 + ch ** 2 + eps  # convex diagonal squared
            rho2 = ((b2_x1 + b2_x2 - b1_x1 - b1_x2) ** 2 + (b2_y1 + b2_y2 - b1_y1 - b1_y2) ** 2) / 4  # center dist ** 2
            if CIoU:  # https://github.com/Zzh-tju/DIoU-SSD-pytorch/blob/master/utils/box/box_utils.py#L47
                v = (4 / math.pi ** 2) * (torch.atan(w2 / h2) - torch.atan(w1 / h1)).pow(2)
                with torch.no_grad():
                    alpha = v / (v - iou + (1 + eps))
                return iou - (rho2 / c2 + v * alpha)  # CIoU
            elif EIou:
                rho_w2 = ((b2_x2 - b2_x1) - (b1_x2 - b1_x1)) ** 2
                rho_h2 = ((b2_y2 - b2_y1) - (b1_y2 - b1_y1)) ** 2
                cw2 = cw ** 2 + eps
                ch2 = ch ** 2 + eps
                return iou - (rho2 / c2 + rho_w2 / cw2 + rho_h2 / ch2)
            return iou - rho2 / c2  # DIoU
        c_area = cw * ch + eps  # convex area
        return iou - (c_area - union) / c_area  # GIoU https://arxiv.org/pdf/1902.09630.pdf
    elif SIoU:
        # SIoU Loss https://arxiv.org/pdf/2205.12740.pdf
        s_cw = (b2_x1 + b2_x2 - b1_x1 - b1_x2) * 0.5 + eps
        s_ch = (b2_y1 + b2_y2 - b1_y1 - b1_y2) * 0.5 + eps
        sigma = torch.pow(s_cw ** 2 + s_ch ** 2, 0.5)
        sin_alpha_1 = torch.abs(s_cw) / sigma
        sin_alpha_2 = torch.abs(s_ch) / sigma
        threshold = pow(2, 0.5) / 2
        sin_alpha = torch.where(sin_alpha_1 > threshold, sin_alpha_2, sin_alpha_1)
        angle_cost = torch.cos(torch.arcsin(sin_alpha) * 2 - math.pi / 2)
        rho_x = (s_cw / cw) ** 2
        rho_y = (s_ch / ch) ** 2
        gamma = angle_cost - 2
        distance_cost = 2 - torch.exp(gamma * rho_x) - torch.exp(gamma * rho_y)
        omiga_w = torch.abs(w1 - w2) / torch.max(w1, w2)
        omiga_h = torch.abs(h1 - h2) / torch.max(h1, h2)
        shape_cost = torch.pow(1 - torch.exp(-1 * omiga_w), 4) + torch.pow(1 - torch.exp(-1 * omiga_h), 4)
        return iou - 0.5 * (distance_cost + shape_cost)
    return iou  # IoU

def soft_nms(bboxes, scores, iou_thresh=0.5,sigma=0.5,score_threshold=0.25):
    order = scores.argsort(descending=True).to(bboxes.device)
    keep = []
    
    while order.numel() > 1:
        if order.numel() == 1:
            keep.append(order[0])
            break
        else:
            i = order[0]
            keep.append(i)
        
        iou = box_iou_for_nms(bboxes[i], bboxes[order[1:]]).squeeze()
        
        idx = (iou > iou_thresh).nonzero().squeeze()
        if idx.numel() > 0: 
            iou = iou[idx] 
            newScores = torch.exp(-torch.pow(iou,2)/sigma)
            scores[order[idx+1]] *= newScores
        
        newOrder = (scores[order[1:]] > score_threshold).nonzero().squeeze() 
        if newOrder.numel() == 0: 
            break
        else:
            maxScoreIndex = torch.argmax(scores[order[newOrder+1]]) 
            if maxScoreIndex != 0: 
                newOrder[[0,maxScoreIndex],] = newOrder[[maxScoreIndex,0],]
            order = order[newOrder+1]
    
    return torch.LongTensor(keep)`
    
    
    
    Could you please help me figure out what's happening and how I could fix this?
    
    
    
Also, I have a small question. Can you tell me if it is appropriate to use the relevant model for an object detection project, based on these two graphs?


![custom_confusion_matrix_normalized](https://github.com/ultralytics/ultralytics/assets/85215233/31de2a76-67c7-46c0-8ce5-073ac2251499)
![custom_F1_curve](https://github.com/ultralytics/ultralytics/assets/85215233/1babcc63-529d-4992-90b1-9b7d0c229e15)
![custom_P_curve](https://github.com/ultralytics/ultralytics/assets/85215233/4dfd84e4-7579-477e-8201-f729e44a5aa2)

![custom_PR_curve](https://github.com/ultralytics/ultralytics/assets/85215233/48e7919f-a841-4ae3-aed1-32d0a724386c)

**Comment by glenn-jocher** [comment]
Hey there! 😊

It appears that incorporating **soft-NMS** has indeed altered the behavior of your model during inference, as seen in the graphical results you've shared. Soft-NMS, by design, modifies the detection scores based on IoU values, which could potentially lead to a change in the precision-recall dynamics. This might be what's reflected in your graphs, showing a deviation when soft-NMS is applied.

Here's a quick suggestion: try adjusting the **`sigma`** parameter within your soft-NMS implementation. A lower sigma value can lead to less suppression, while a higher value can cause more aggressive score diminishment. Experimenting with this parameter might help you fine-tune the trade-off between precision and recall to achieve more desirable results.

```python
# Example modification
def soft_nms(bboxes, scores, iou_thresh=0.5, sigma=0.3, score_threshold=0.25):
    ...
```
As for whether the model is suitable for an object detection project based on the provided graphs, it looks promising! 🌟 Your **confusion matrix** shows decent classification ability among different classes with some room for improvement which is normal. Meanwhile, the **F1, Precision, and Recall curves** suggest your model can generalize well on detecting various objects, asserting its applicability for object detection tasks. Of course, the decision also depends on the **specific requirements** and **performance thresholds** of your project.

Hope this helps! Feel free to play around with the parameters and share your progress. Excited to see how your model evolves! 🚀
