### ISSUE TITLE
Training on a custom dataset, what kind of model and yaml should be used? 

### ISSUE THREAD

**Issue by dmddmd** [ultralytics/ultralytics#985]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a dataset with 14 classes. (Some of this classes are the same as in coco, some not)
I have 2 questions

1.
According to the docs, loading a pretrained model is recommended for training:
`model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)
`
 Why is it recommended, when my classes aso are different? 

Should I do something else than:
```
% Load a model
model = YOLO("yolov8n.yaml")  # build a new model from scratch, but with a prepared yaml like yolov8n.yaml or with my own yaml like mydata.yaml?
% Train the model
model.train(data="mydata.yaml", epochs=100, imgsz=3024)

```

**Comment by JustasBart** [comment]
Hi @dmddmd if you pass in an existing model such as 'yolov8s.pt' you'll do what's called Transfer-Learning, meaning that it'll use all that it had learned for that model and it'll home-in faster on your data and your classes.

Whereas passing in the 'yolov8s.yaml' will result in the model starting from essentially just random noise (No prior smarts) which will take a lot longer to learn/converge on your data.

Hence a pre-trained model training (Transfer-Learning) is always recommended, unless if for whatever the reason you decide to start from sratch.

I hope this answer it for you :rocket:

**Comment by dmddmd** [comment]
Thanks for Your answer. But how to solve that I have some same and some different classes than coco?
 I can try to use the same classID for the same ones. But the different ones will have the same classID of a completely different class.

**Comment by JustasBart** [comment]
Hi @dmddmd that's totally fine! The class IDs don't matter in this case and they'll be re-arranged for 0 to x for you anyway and this will not affect Transfer Learning in any way.

However, be aware that if you want to re-use for example the COCO datasets Person class you'll have to download the people data and incorporate it alongside of your dataset and train on the combined dataset.

But don't worry about the class IDs in any other way.

Good luck! :rocket:

**Comment by dmddmd** [comment]
Thank You :)

**Comment by GangPingZ** [comment]
> Hi @dmddmd if you pass in an existing model such as 'yolov8s.pt' you'll do what's called Transfer-Learning, meaning that it'll use all that it had learned for that model and it'll home-in faster on your data and your classes.
> 
> Whereas passing in the 'yolov8s.yaml' will result in the model starting from essentially just random noise (No prior smarts) which will take a lot longer to learn/converge on your data.
> 
> Hence a pre-trained model training (Transfer-Learning) is always recommended, unless if for whatever the reason you decide to start from sratch.
> 
> I hope this answer it for you :rocket: 

if l want to use new net structure (.yaml file) meanwhile use yolov8 pretrained model ,how to write the train command in python env？thank you！😊😊😊
