### ISSUE TITLE
Suggestion: Increase the types of models

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#9853]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Suggestion: Increase the types of models
Need to determine the type of model to facilitate logical processing
The current framework does not provide this judgment

```
Attributes:

Name	Type	Description
orig_img	ndarray	Original image as a numpy array.
orig_shape	tuple	Original image shape in (height, width) format.
boxes	[Boxes](https://docs.ultralytics.com/reference/engine/results/?h=#ultralytics.engine.results.Boxes)	Object containing detection bounding boxes.
masks	[Masks](https://docs.ultralytics.com/reference/engine/results/?h=#ultralytics.engine.results.Masks)	Object containing detection masks.
probs	[Probs](https://docs.ultralytics.com/reference/engine/results/?h=#ultralytics.engine.results.Probs)	Object containing class probabilities for classification tasks.
keypoints	[Keypoints](https://docs.ultralytics.com/reference/engine/results/?h=#ultralytics.engine.results.Keypoints)	Object containing detected keypoints for each object.
speed	dict	Dictionary of preprocess, inference, and postprocess speeds (ms/image).
names	dict	Dictionary of class names.
path	str	Path to the image file.
```

`types`
`tasks`

```
Tasks
Detect
Segment
Classify
Pose
OBB
```

### Use case

`model.types`
perhaps
`model.tasks`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Kayzwer** [comment]
`model.task` is what you need I guess.

**Comment by glenn-jocher** [comment]
@Kayzwer yes, you're absolutely right! For your requirement, you can use the `model.task` attribute to determine the type of task the model is designed for (such as detection, segmentation, classification, pose estimation, or OBB). This attribute would facilitate logical processing based on the model's designated task. Here's a quick example to illustrate:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('yolov8n.pt')  # Example model

# Determine the task type
print(f"The model's task is: {model.task}")
```

This check will help you implement specific logic based on the task type, enhancing the framework's usability for your application. 😊

**Comment by monkeycc** [comment]
Thank you, I already have this feature

I didn't find this feature in the document and thought it wasn't there

**Comment by glenn-jocher** [comment]
@monkeycc hi there! Glad to hear you've found the feature you needed. 😊 We'll make sure to update the documentation to reflect this more clearly. Thanks for bringing this to our attention! If you need further assistance, feel free to ask. Happy coding!
