### ISSUE TITLE
Updated question on how to store and filter data from a database based on time buckets.

### ISSUE THREAD

**Issue by anishka07** [ultralytics/ultralytics#9860]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have figured out a way to store data of tracked objects (confidence, class name, class id, bounding box) in a sqlite database and previously I added a video timestamp to make the objects store in real time. The storing was done successfully and it worked for the most part. The problem is, when I wanted to filter out the data from start time to end time in time bucket format, I did not achieve much success.

This is my code for the object storing:
`
 def insert_values(self, classes: List[str], conf: float = 0.5):
        """
        :param classes: List of strings (class name) to be detected.
        :param conf: minimum confidence threshold for object detection.
        :return:
        """
        try:
            track = self.trackable_dict
            while self.cap.isOpened():
                ret, frame = self.cap.read()
                if not ret:
                    break
                results = self.model.track([frame], classes=self.get_indices(classes), conf=conf)
                for result in results:
                    detections = zip(result.boxes.cls, result.boxes.conf, result.boxes.cpu().numpy())
                    for class_id, confidence, bbox in detections:
                        confidence_val = round(confidence.item(), 2)
                        if confidence_val >= conf:
                            unix_timestamp = int(datetime.now().timestamp() * 1000)
                            video_timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                            class_id = int(class_id.item())
                            class_name = track[class_id]
                            bbox_xyxy = bbox.xyxy.tolist()
                            bounding_box = [int(coord) for sublist in bbox_xyxy for coord in sublist]
                            bbox_json = ','.join(map(str, bounding_box))
                            print(f"confidence: {confidence_val}, class_id: {class_id}, class_name: {class_name}, bbox: {bbox_json}")
                            self.cursor.execute(f"""
                            INSERT INTO 
                            {self.table_name} (video_timestamp, unix_timestamp, class_name, bounding_box, confidence, class_id) 
                            VALUES 
                            (?, ?, ?, ?, ?, ?)""", (video_timestamp, unix_timestamp, class_name, bbox_json, confidence_val, class_id))
                self.conn.commit()
        except sqlite3.Error as e:
            print("Error: ", e)
`

And this is my code for the object filtering in terms of time stamp(which does not work like  I intended it to):
`    
def test_filter(self, start_timestamp: str, end_timestamp: str, min_confidence: float = 0.5, time_bucket: str = None):
        """
        Args:
        :param start_timestamp: start timestamp
        :param end_timestamp: end timestamp
        :param min_confidence: minimum confidence threshold
        :param time_bucket: time bucket to filter the data
        :return:
        """
        try:
            start_unix_time = datetime.strptime(start_timestamp, "%Y-%m-%d %H:%M:%S").timestamp()
            end_unix_time = datetime.strptime(end_timestamp, "%Y-%m-%d %H:%M:%S").timestamp()
            if start_unix_time > end_unix_time:
                raise ValueError("Start time is greater than end time.")

            conn = sqlite3.connect(Settings.DB_NAME)
            cursor = conn.cursor()
            time_bucket_expressions_all = {
                "day": "DATE(video_timestamp)",
                "month": "%Y-%m",
                "year": "%Y",
                "week": "%Y-%U",
                "hour": "%Y-%m-%d %H:00:00",
                "minute": "%Y-%m-%d %H:%M:00"
            }
            if time_bucket not in time_bucket_expressions_all.keys():
                raise ValueError("Error: Time bucket not correct.")
            formatted_date = time_bucket_expressions_all[time_bucket]
            time_buck = f"strftime('{formatted_date}', video_timestamp)"
            query = f"""
            SELECT {time_buck} AS time_bucket, class_name, COUNT(*) AS frequency FROM {self.table_name}
            WHERE video_timestamp BETWEEN ? AND ? AND confidence >= ?
            GROUP BY class_name;
            """
            print("Executing query...")
            cursor.execute(query, (start_timestamp, end_timestamp, min_confidence))
            rows = cursor.fetchall()
            if not rows:
                print("No rows found")
            else:
                for item in rows:
                    time_bucket, class_name, freq = item
                    print(f"Time bucket: {time_bucket}, Class Name: {class_name}, Frequency: {freq}")
        except (sqlite3.Error, ValueError) as e:
            print(e)
        finally:
            conn.close()
`

Now, since the code does not work like I wanted it to using time buckets, I was wondering if I can store the "track id" and filter based on track id itself. It seems to be the more optimal way. 

I will be adding some pictures to make it more clear:

This is what I mean by track_id:
<img width="747" alt="Screenshot 2024-04-08 at 12 56 15 PM" src="https://github.com/ultralytics/ultralytics/assets/109445504/8cb722bd-0db2-42bc-b60b-1e96b572575c">
I want to store these track Id and query based on these.

These are the screenshots of my code snippets:

<img width="1046" alt="Screenshot 2024-04-08 at 12 57 33 PM" src="https://github.com/ultralytics/ultralytics/assets/109445504/2fffef16-2492-4068-b18c-ec2a2f923eb0">

This is the code for filtering which is not doing what i want it to:

<img width="970" alt="Screenshot 2024-04-08 at 12 58 20 PM" src="https://github.com/ultralytics/ultralytics/assets/109445504/e8368578-7a8d-46a6-8980-8a6393d41b6d">

### Additional
UPDATE:

I have figured out a way to store the unique track ids of each objects using this code:
` try:
            track = self.trackable_dict
            while self.cap.isOpened():
                ret, frame = self.cap.read()
                if not ret:
                    break
                results = self.model.track([frame], persist=True, classes=self.get_indices(classes), conf=conf)
                for result in results:
                    detections = zip(result.boxes.cls, result.boxes.conf, result.boxes.cpu().numpy(), result.boxes.id.int().cpu())
                    for class_id, confidence, bbox, obj_id in detections:
                        confidence_val = round(confidence.item(), 2)
                        if confidence_val >= conf:
                            unix_timestamp = int(datetime.now().timestamp() * 1000)
                            video_timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                            class_id = int(class_id.item())
                            object_unique_id = int(obj_id)
                            class_name = track[class_id]
                            bbox_xyxy = bbox.xyxy.tolist()
                            bounding_box = [int(coord) for sublist in bbox_xyxy for coord in sublist]
                            bbox_json = ','.join(map(str, bounding_box))
                            print(f"confidence: {confidence_val}, unique_id:{object_unique_id} , class_name: {class_name}, bbox: {bbox_json}")
                            self.cursor.execute(f"""
                            INSERT INTO 
                            {self.table_name} (video_timestamp, unix_timestamp, class_name, bounding_box, confidence, object_unique_id) 
                            VALUES 
                            (?, ?, ?, ?, ?, ?)""", (video_timestamp, unix_timestamp, class_name, bbox_json, confidence_val, object_unique_id))
                self.conn.commit()
        except sqlite3.Error as e:
            print("Error: ", e)`
_No response_

**Comment by glenn-jocher** [comment]
@anishka07 great job on implementing the storage and initial filtering for tracked object data! To enhance your filtering using "track id," you're on the right track by storing these alongside your other data. 🚀

For filtering based on "track id," consider adjusting your SQL query to filter and group by the `object_unique_id` field, ensuring you can retrieve results based on specific tracked objects. Here's a sample adjustment to your filtering function:

```python
def filter_by_track_id(self, track_id: int):
    try:
        conn = sqlite3.connect(Settings.DB_NAME)
        cursor = conn.cursor()
        query = f"""
        SELECT class_name, COUNT(*) AS frequency FROM {self.table_name}
        WHERE object_unique_id = ?
        GROUP BY class_name;
        """
        print("Executing query for track_id:", track_id)
        cursor.execute(query, (track_id,))
        rows = cursor.fetchall()
        if not rows:
            print("No rows found for track_id:", track_id)
        else:
            for class_name, freq in rows:
                print(f"Class Name: {class_name}, Frequency: {freq}")
    except sqlite3.Error as e:
        print(e)
    finally:
        conn.close()
```

This function will allow you to specifically retrieve data for a given "track id," summarizing the frequency of class names associated with it. Remember, this is just one way to approach it. Keep exploring and refining based on your application's needs! 😊
