### ISSUE TITLE
Only CPU1 and CPU11 participate in data enhancement

### ISSUE THREAD

**Issue by kutieling** [ultralytics/ultralytics#9862]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I have changed some codes in the data enhancement part of yolov8. Now the data enhancement part in my code loads slowly, only two cpus have been performing the data enhancement part, and the other cpus have not participated in it. As a result, the data sent to the GPU cannot keep up with the processing speed of the GPU, resulting in a slow training process. Does anyone know how to solve the problem that this CPU is not fully utilized? I've also adjusted the works parameter for dataloader, whether it's 2/4/8/16 or if only CPU1 and CPU11 are working.In the code, it's data = self._data_queue.get(timeout=timeout) in dataloader.py, where self._data_queue loads data very slowly.
![IMG_6888](https://github.com/ultralytics/ultralytics/assets/133850573/289f8b1f-a531-409d-b163-90d9586e0cef)
![IMG_6889](https://github.com/ultralytics/ultralytics/assets/133850573/94c9cf1f-a6ba-413b-b13a-98eb451d4e41)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kutieling if your dataloading is going slowly you may want to try caching the dataset on disk or in ram, i.e.:

```
model.train(data='path/to/data.yaml', cache='ram')
model.train(data='path/to/data.yaml', cache='disk')
```

Note that this requires significant available RAM or Disk space.

**Comment by kutieling** [comment]
> @kutieling if your dataloading is a bottleneck you may want to try caching the dataset on disk or in ram, i.e.:
> 
> ```
> model.train(data='path/to/data.yaml', cache='ram')
> model.train(data='path/to/data.yaml', cache='disk')
> ```
> 
> Note that this requires significant available RAM or Disk space.

Is there any way to use my other cpus for data enhancement? Thank you very much for your answer

**Comment by glenn-jocher** [comment]
Hi @kutieling, great question! 🌟

Yes, adjusting the number of workers can help utilize more CPUs for data loading and augmentation. You can do this by setting the `workers` parameter in your training command. For example:

```python
model.train(data='path/to/data.yaml', workers=16)
```

Adjust the `workers` value based on your system's CPU cores to optimize utilization. Keep in mind that the optimal number of workers might require some experimentation to find, as it's influenced by your specific hardware setup and the complexity of the data enhancement tasks.

Happy coding!
