### ISSUE TITLE
Training the whole Model / only the Head

### ISSUE THREAD

**Issue by FlorianRakos** [ultralytics/ultralytics#9867]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey there!
I'm currently writing my thesis on YOLOV8 and have got a specific question:

When I'm training a pretrained YOLO-V8 Model with Ultralytics, am I training all Parameters of the Model or only the Head Section of the Model?

Best regards
Florian

**Comment by glenn-jocher** [comment]
@FlorianRakos hey Florian!

Great question! 😊 When you train a pretrained YOLOv8 model with Ultralytics, by default, all parameters of the model, including both the backbone and the head, undergo training. This approach allows the model to fine-tune to your specific dataset across all layers.

If you're looking to train only the head of the model, you can freeze the backbone layers using the `freeze` argument, specifying the layers you want to freeze. For example:
```python
model.train(freeze=[0, 1, 2])  # Freezes the first three layers during training.
```

Hope this helps with your thesis, and best of luck with your research!

**Comment by glenn-jocher** [comment]
I'm glad my response was helpful! 😊

While I'm here to provide support and guidance on Ultralytics YOLO models, I'm not Glenn Jocher. However, I'm part of the dedicated team ensuring users like you get the assistance needed with our models. 

It's fantastic to hear about your research and that YOLOv8 is standing out in your comparisons! If you have any more questions or need further assistance as you continue with your thesis, feel free to ask. Good luck!
