### ISSUE TITLE
Detecting only whole objects

### ISSUE THREAD

**Issue by CySlider** [ultralytics/ultralytics#987]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

We want to detect only whole objects. So we figured, we would not label partial objects, or label them differently.

However when investigating the way Yolo learns the training data, it seems to me, that it will randomly cut images, and adjust the bounding boxes of cut objects accordingly, so even if we don't feed it partial images, it creates them itself.

Is this correct? And if it is, is there a way to prevent this? So it discards any boxes that gets cut, instead of adjusting them?

**Comment by JustasBart** [comment]
Hi @CySlider that's correct, by default yolov5 and yolov8 will crop about the bounding boxes for training.

You can disable this behaviour by suppressing that particular augmentation during training:
```
hsv_h=0.015 \
hsv_s=0.2 \
hsv_v=0.1 \
degrees=0.0 \
translate=0.0 \
perspective=0.0 \
scale=0.1 \
shear=0.0 \
flipud=0.5 \
fliplr=0.5 
```
Perhaps double check/experiment to see if there's anything else to add to this list etc...

Good luck! :rocket:

**Comment by CySlider** [comment]
Works good, but better would be an option to omit boxes that get cut by augmentations, then you can leave all augmentations turned on

**Comment by CySlider** [comment]
Can we relabel this as feature request?

**Comment by glenn-jocher** [comment]
Hi @CySlider, thank you for your question.

Yes, we can certainly relabel this as a feature request. Thanks for bringing it to our attention!

If you have any further questions or feature requests, please don't hesitate to let us know. We're always happy to help improve YOLOv8 and make it the best it can be.

Best regards!
