### ISSUE TITLE
Seems that images are not being cached in RAM when cache=ram

### ISSUE THREAD

**Issue by PacificDou** [ultralytics/ultralytics#9871]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When init the trainer, there is an option `cache` for switching on/off cache on ram/disk, acceptable values are ram/True, disk, False. https://docs.ultralytics.com/modes/train/#train-settings

For example, [DetectionTrainer](https://github.com/ultralytics/ultralytics/blob/f2ddc963342e944214dc9d459a1e1dc4bf599aa1/ultralytics/models/yolo/detect/train.py#L19) will init a YOLODataset object, and then wrap it in an InfiniteDataloader.
The `cache` parameter was set during initialling the YOLODataset object, which inherits [BaseDataset](https://github.com/ultralytics/ultralytics/blob/f2ddc963342e944214dc9d459a1e1dc4bf599aa1/ultralytics/data/base.py#L21). 

In [BaseDataset's constructor](https://github.com/ultralytics/ultralytics/blob/f2ddc963342e944214dc9d459a1e1dc4bf599aa1/ultralytics/data/base.py#L93), the image dataset will be cached to RAM/Disk.

For case of `cache=ram`, function [load_image](https://github.com/ultralytics/ultralytics/blob/f2ddc963342e944214dc9d459a1e1dc4bf599aa1/ultralytics/data/base.py#L144) will be called for each image: load to RAM, clear old buffer if `len(self.buffer) >= self.max_buffer_length`;
For case of `cache=disk`, function [cache_images_to_disk](https://github.com/ultralytics/ultralytics/blob/f2ddc963342e944214dc9d459a1e1dc4bf599aa1/ultralytics/data/base.py#L198) will be called for each image: load to RAM, save as numpy file.

Thus, in case of `cache=ram`, after initialisation of BaseDataset, there will be only `self.max_buffer_length` images in RAM (and buffer), not the whole dataset. 

In addition, because of the following instruction in the BaseDataset's constructor, the buffer size will be capped at 1000. So if a dataset has more than 1000 images (and sufficient RAM), we still can NOT benefit from `reduced disk IO`.
```
self.max_buffer_length = min((self.ni, self.batch_size * 8, 1000)) if self.augment else 0
```

**Comment by glenn-jocher** [comment]
@PacificDou thanks for raising an issue. This was resolved recently in 8.1.45 in https://github.com/ultralytics/ultralytics/pull/9828.

**Comment by PacificDou** [comment]
@glenn-jocher That's great!

As a follow-up, do you think it's a good idea to cache images in RAM up to user-specified limit?
For example, if the user specifies 4GB, then we only cache the dataset up to 4GB.

In current version, we only have two options: either load whole dataset to RAM, or give up RAM cache, because of function [check_cache_ram](https://github.com/ultralytics/ultralytics/blob/bc636d08b798412c7eecda974f0019b90566dc57/ultralytics/data/base.py#L204). It would be more flexible if user can specify the maximum RAM he wants to use.

If you agree with this idea, I can try to submit a PR later for this.

**Comment by PacificDou** [comment]
Hi @glenn-jocher , here is the PR for add memory cache limit control: https://github.com/ultralytics/ultralytics/pull/10258
