### ISSUE TITLE
Yolov8m error while training on gpu

### ISSUE THREAD

**Issue by BarsikArsik** [ultralytics/ultralytics#9877]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I'm very bad at everything related to programming and I'm trying to solve my bio;ogical research problem using AI,
I can’t run training model on the GPU.
Version CUDA 12.4 ![1](https://github.com/ultralytics/ultralytics/assets/101796859/b2c2b57b-a01f-4fcf-90a6-22e9fa263274)
PyTorch version 12.1 
![2](https://github.com/ultralytics/ultralytics/assets/101796859/a302872a-e09c-404f-b677-86ce020e5667)

Unfortunately I couldn't find how to install PyTorch 12.4

At the same time, CUDA it works and determines the GPU as accessible. 
![3](https://github.com/ultralytics/ultralytics/assets/101796859/1b498d0b-9714-4629-bd14-6a03b6e26fc9)

but if you run image analysis with parameter =0, it produces an error. 
![4](https://github.com/ultralytics/ultralytics/assets/101796859/ebc8286c-84ae-4940-9468-059f6e22405c)

**Comment by Kayzwer** [comment]
@BarsikArsik make sure your IDE is using the python environment that you have
