### ISSUE TITLE
Adding remarks to annotation files

### ISSUE THREAD

**Issue by yosikeller** [ultralytics/ultralytics#9882]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to add remarks to my annotation txt files for better comprehensibility.  
'#' character is supposed to allow adding any remarks.

This is my txt annotation file:
`# <class> <x_center> <y_center> <width> <height>`

1 0.7406656901 0.1689628329 0.0073339844 0.0775966913

and get an error message:
ignoring corrupt image/label: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

**Comment by yosikeller** [comment]
my annotation file is:
`# <class> <x_center> <y_center> <width>` <height>`

1 0.7406656901 0.1689628329 0.0073339844 0.0775966913

**Comment by Kayzwer** [comment]
the yolo txt label file is not python script, # wont serve the purpose of comment

**Comment by yosikeller** [comment]
Is there a way to add remarks to this file?

**Comment by glenn-jocher** [comment]
Unfortunately, the YOLO annotation txt files do not support the addition of remarks or comments directly within them. The format for these files is very specific, mainly containing bounding box annotations for object detection tasks, and does not allow for inline comments. For clarity and extra notes, you might consider maintaining a separate documentation file alongside your annotation files. This can help you keep track of any additional information or remarks related to your dataset. 😊
