### ISSUE TITLE
Incremental training of existing model classes for detection/segmentation

### ISSUE THREAD

**Issue by fuzzymango** [ultralytics/ultralytics#9885]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm looking to further train the existing "yolov8m.pt" model with the goal of having the model be better at classifying dogs and segmenting them out of a given image. I've created a dataset of only images of dogs and their locations in the frame using the Roboflow webapp. On Roboflow, I've created a single class, named "dog" and exported the dataset. Each label of the datatset looks something like this: 
`0 0.65 0.52734375 0.58203125 0.9453125`
With the first number representing the object class, and the following 4 numbers representing the location of the object within the corresponding image. 

I know that yolov8m comes pre-trained with 24 classes, with each class getting a unique identifier number.
Running this code shows the pre-trained classes:
```
model = YOLO("yolov8m.pt")
print(model.names)
```
```
{0: 'person',
 1: 'bicycle',
 2: 'car',
 3: 'motorcycle',
 4: 'airplane',
 5: 'bus',
 6: 'train',
 7: 'truck',
 8: 'boat',
 9: 'traffic light',
 10: 'fire hydrant',
 11: 'stop sign',
 12: 'parking meter',
 13: 'bench',
 14: 'bird',
 15: 'cat',
 16: 'dog',
 17: 'horse',
 18: 'sheep',
 19: 'cow',
 20: 'elephant',
 21: 'bear',
 22: 'zebra',
 23: 'giraffe',
 24: 'backpack',
```

When I'm fine tuning/incrementally training the yolo model on my custom dataset, how will the model know that I've annotated dogs in each of my provided images? Since my dataset labels have `0` as the first number for each image, does the model think that I've annotated a "person" in each image? 

I'm guessing I need to list every class that yolov8 has been trained on Roboflow such that when Roboflow exports its dataset, the labels for the dog images will all have the first number as `16` which matches yolov8's `model.names`. 

Looking for some confirmation here. Thanks!

**Comment by Kayzwer** [comment]
@fuzzymango you can try to train the model with the pre trained weights on the dog images you have, but you need to freeze all the layers except the last detection layer, the model will learn very fast I guess
