### ISSUE TITLE
Not found ultralytics.utils

### ISSUE THREAD

**Issue by SheeppLi** [ultralytics/ultralytics#9895]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![1712630298254](https://github.com/ultralytics/ultralytics/assets/94896151/95007c19-6ae8-495f-989f-0caed34b50a9)
I wrote the code last year and it ran without any warning, but now it reports a warning and I upgrade ultralytics to latest version but still cant run. Can you please inform me what should I do? Thank you!

**Comment by Kayzwer** [comment]
@SheeppLi please do an update by `pip install -U ultralytics` or `git pull` in the cloned repo

**Comment by SheeppLi** [comment]
> @SheeppLi please do an update by `pip install -U ultralytics` or `git pull` in the cloned repo

Thanks for replying! I tried it and it reports already in latest version 8.1.45, but the problem exists.

**Comment by glenn-jocher** [comment]
Hi @SheeppLi, thanks for the update! If you're already on the latest version, the issue might be related to changes in the package structure or dependencies. Could you try clearing your Python environment of the `ultralytics` package and reinstalling it? Sometimes, reinstalling can help resolve unexpected issues. Here's how you can do it:

```bash
pip uninstall ultralytics
pip install ultralytics
```

If this doesn't solve the problem, please provide us with the exact warning message you're getting for further assistance. Let's get this sorted out! 🛠️

**Comment by SheeppLi** [comment]
Hi @glenn-jocher , I also tried reinstalling ultralytics, and the problem exists. In detail, I want to get segmentation masks to analyze the length of objects. my code is:

**Comment by glenn-jocher** [comment]
@SheeppLi hi there! It seems like the warning is hinting at a specific requirement (`ultralytics.utils`) that isn't directly available in the `ultralytics` package. This could be a leftover import from a custom modification or an outdated version.

If you're working with segmentation models and need to manipulate the segmentation masks, the `ultralytics` package should have all the necessary functionalities built-in, without needing to explicitly import `ultralytics.utils`. Please ensure your segmentation model is compatible with the current `ultralytics` version you're using.

Here's a slightly modified approach you might want to try:

```python
from ultralytics import YOLO

model = YOLO('D:/ultralytics-main/runs/segment/train95/weights/best.pt')
results = model.predict(source=img_file, save=True)
segs = results[0].masks.numpy()  # Assuming you want numpy arrays for analysis
```

This will ensure you're accessing the masks directly via the results object returned by `predict()`. If you continue to see the warning, make sure your custom model is correctly exported and compatible with the latest `ultralytics` version. Let us know how it goes! 🚀

**Comment by SheeppLi** [comment]
Hi @glenn-jocher, all the methods seem not work. I think it is because when I run "model = YOLO('D:/ultralytics-main/runs/segment/train95/weights/best.pt')" it can't continue. I hope to obtain the coordinates of the boundary points of each object by running model.predict with pre-trained weights. So, I want to know if there are any other methods to obtain the coordinates of the object mask boundary points predicted by pre-trained weights. This is my code and the warning.
![_20240410190017](https://github.com/ultralytics/ultralytics/assets/94896151/0cce7b45-6e73-477c-9673-7b48ae0a7e50)
![_20240410190017](https://github.com/ultralytics/ultralytics/assets/94896151/87db1773-9b32-4f71-acf1-5ede525d665a)
![1712630298254](https://github.com/ultralytics/ultralytics/assets/94896151/e3017a27-84d0-46cd-8397-82ba7dcdf413)

**Comment by glenn-jocher** [comment]
Hi there! 👋 It looks like the issue might be with accessing the coordinates of segmentation mask boundary points directly. For segmentation models, `.predict()` will return segmentation masks, but extracting precise boundary coordinates requires a bit more work.

To obtain the contours (boundary points) from segmentation masks, you can utilize OpenCV functions like `cv2.findContours` after converting the masks to a suitable format. Here's a quick example on how you might do it:

```python
import cv2
import numpy as np
from ultralytics import YOLO

# Load your model
model = YOLO('D:/ultralytics-main/runs/segment/train95/weights/best.pt')

# Obtain predictions
results = model.predict(source='your_image.jpg')
masks = results[0].masks.numpy()

# Assuming your mask is in the first result for demonstration
mask = masks[0] * 255  # Convert mask to uint8 format
mask = mask.astype(np.uint8)

# Find contours
contours, _ = cv2.findContours(mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

# Now contours is a list of the boundary points of the first object
```

Remember, `cv2.findContours` returns a list where each element corresponds to the contour points of an object in the mask. Iterate over `masks` if you have multiple objects. Hope this helps you move forward! Let us know if you encounter any other issues. 🌟

**Comment by SheeppLi** [comment]
Hi @glenn-jocher, I tried to use model = YOLO(yolov8n-seg.pt), and the bug no longer exists, but when I use my custom weights, the bug raises again. Note that all the custom weights were trained based on yolov8n-seg.pt. So how can I apply my custom weight to model.predict to get numpy mask result?

**Comment by glenn-jocher** [comment]
Hi there! 🌟

Glad to hear you've managed to resolve the issue by cloning the YOLOv8 project into a new folder! It does sound like the problem was related to the project directory's location affecting the module loading process.

For future reference or if anyone else encounters a similar issue, here’s how you can use your custom weights for `model.predict` to get the numpy mask result:

```python
from ultralytics import YOLO

# Initialize the model with your custom trained weights
model = YOLO('path/to/your/custom_weights.pt')

# Perform prediction and get numpy mask results
results = model.predict(source='path/to/your/image.jpg')
masks = results[0].masks.numpy()  # This will give you the numpy array of masks
```

Remember, keeping your project's structure intact and mindful of paths can help avoid such loading issues. Feel free to reach out if anything else comes up! Happy coding! 🚀
