### ISSUE TITLE
how to process obb results data

### ISSUE THREAD

**Issue by zxjzzz** [ultralytics/ultralytics#9897]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i use yolov8n-obb.pt but it result with yolov8n.pt has some difference 

why yolov8n-obb.pt  result  boxes is None 

like
 yolov8n-obb.pt    
 
boxes: None
keypoints: None
masks: None

 yolov8n.pt
boxes: ultralytics.engine.results.Boxes object
keypoints: None
masks: None

**Comment by Kayzwer** [comment]
@zxjzzz try
```
result = model("/path/to/img")[0]
print(result.obb)
```

**Comment by zxjzzz** [comment]
> @zxjzzz try
> 
> ```
> result = model("/path/to/img")[0]
> print(result.obb)
> ```

thx

**Comment by glenn-jocher** [comment]
You're welcome, @zxjzzz! If you have any more questions or need further assistance, feel free to ask. Happy detecting! 😊
