### ISSUE TITLE
export to tflite core dumped?

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/ultralytics#9902]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question
the following code block testifle.py, and latest tensorflow installed.

python testfile.py yolov8n.pt

```
import sys
from ultralytics.engine.model import Model

ifile = sys.argv[1]
ofile = ifile.replace('.pt', '_.tflite')
model = Model()
model.load(ifile)
print(model.info(detailed=True, verbose=True))
model.export(format='tflite')
model.save(ofile)
```

```
YOLOv8n summary: 225 layers, 3157200 parameters, 0 gradients, 8.9 GFLOPs
(225, 3157200, 0, 8.8575488)
Ultralytics YOLOv8.1.20 🚀 Python-3.10.12 torch-2.2.1+cu121 CPU (Common KVM processor)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)
**Illegal instruction (core dumped)**
```

**Comment by glenn-jocher** [comment]
@apiszcz hey there! 😊

It looks like you're encountering an "Illegal instruction (core dumped)" error during the export to TFLite. This typically indicates a compatibility issue between TensorFlow and your current system's CPU instructions.

A quick tip: Make sure you have the latest version of TensorFlow compatible with your system's architecture. If you're on an older system, TensorFlow may attempt to use newer SIMD instructions (such as AVX2) that aren't supported.

As a workaround, you might want to try using TensorFlow in a Docker container optimized for your CPU architecture, or consider using TensorFlow on a different system or virtual machine that meets the TensorFlow requirements.

Additionally, double-check the `export(format='tflite')` usage. Ensure all dependencies are correctly installed and compatible. Sometimes, creating a fresh virtual environment can help isolate and resolve dependency issues.

Let us know how it goes or if there's more we can help with!

**Comment by apiszcz** [comment]
Thanks moved to an all INTEL CPU setup, making it farther. looks like versions are important.

PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)
requirements: Ultralytics requirements ['onnx2tf>=1.15.4,<=1.17.5', 'sng4onnx>=1.0.1', 'onnxsim>=0.4.33', 'onnx_graphsurgeon>=0.3.26', 'tflite_support'] not found, attempting AutoUpdate...
requirements: ❌ AutoUpdate skipped (offline)

TensorFlow SavedModel: starting export with tensorflow 2.16.1...
WARNING ⚠️ tensorflow<=2.13.1 is required, but tensorflow==2.16.1 is currently installed https://github.com/ultralytics/ultralytics/issues/5161
requirements: Ultralytics requirement ['onnxsim>=0.4.33'] not found, attempting AutoUpdate...
requirements: ❌ AutoUpdate skipped (offline)

**Comment by apiszcz** [comment]
Very close... I think

```
Ultralytics YOLOv8.1.10 🚀 Python-3.11.6 torch-2.1.0+cu121 CPU (Intel Xeon E5-2699 v4 2.20GHz)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

TensorFlow SavedModel: starting export with tensorflow 2.13.0...

ONNX: starting export with onnx 1.16.0 opset 17...
ONNX: simplifying with onnxsim 0.4.36...
ONNX: export success ✅ 2.4s, saved as 'yolov8n.onnx' (12.3 MB)
TensorFlow SavedModel: running 'onnx2tf -i "yolov8n.onnx" -o "yolov8n_saved_model" -nuo --non_verbose'
Traceback (most recent call last):
  File "/home/apiszcz/acv/bin/onnx2tf", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/apiszcz/acv/lib/python3.11/site-packages/onnx2tf/onnx2tf.py", line 2291, in main
    model = convert(
            ^^^^^^^^
  File "/home/apiszcz/acv/lib/python3.11/site-packages/onnx2tf/onnx2tf.py", line 881, in convert
    test_data: np.ndarray = download_test_image_data()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiszcz/acv/lib/python3.11/site-packages/onnx2tf/utils/common_functions.py", line 4129, in download_test_image_data
    test_image_data: np.ndarray = np.load(f)
                                  ^^^^^^^^^^
  File "/home/apiszcz/acv/lib/python3.11/site-packages/numpy/lib/npyio.py", line 438, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
TensorFlow SavedModel: export failure ❌ 9.8s: SavedModel file does not exist at: yolov8n_saved_model/{saved_model.pbtxt|saved_model.pb}
```

**Comment by glenn-jocher** [comment]
@apiszcz hey there! 🚀

It looks like you've made great progress with your export! The snip you've shared highlights a common issue with TensorFlow SavedModel exports involving pickled data. This can easily happen when working with certain dependencies and data formats.

For the specific error, we want to ensure that numpy's load function allows loading of the pickled object safely. When using `numpy.load`, try setting `allow_pickle=True` to bypass the restriction around loading pickled data. Here’s a small tweak you can try in the `common_functions.py` file or wherever the `np.load` is being called:

```python
test_image_data: np.ndarray = np.load(f, allow_pickle=True)
```

However, I strongly recommend proceeding with caution when enabling `allow_pickle=True`, especially with untrusted data, as it can be a security concern.

If you do not have direct control over the `onnx2tf` or other utility conversions, ensure all involved packages are up-to-date or consider applying patches where necessary.

Let us know how it goes or if you require further assistance!

**Comment by apiszcz** [comment]
I'll need to spend more time on the dependencies and versions. 

I did try the test you suggested.

```
  File "/home/apiszcz/acv/lib/python3.11/site-packages/onnx2tf/onnx2tf.py", line 881, in convert
    test_data: np.ndarray = download_test_image_data()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiszcz/acv/lib/python3.11/site-packages/onnx2tf/utils/common_functions.py", line 4129, in download_test_image_data
    test_image_data: np.ndarray = np.load(f, allow_pickle=True)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiszcz/acv/lib/python3.11/site-packages/numpy/lib/npyio.py", line 443, in load
    raise pickle.UnpicklingError(
_pickle.UnpicklingError: Failed to interpret file <_io.BytesIO object at 0x7f1ce43ad940> as a pickle

```
