### ISSUE TITLE
Understanding pose matching: Calculating OKS with multiple ground truths in images

### ISSUE THREAD

**Issue by enazari** [ultralytics/ultralytics#9915]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I'm seeking clarity on the process of computing Object Keypoint Similarity when multiple ground truth poses are present in an image. Particularly, how predicted poses are processed and matched with these ground truth poses? For instance, when dealing with outputs from YOLO, is the first step to apply Non-Maximum Suppression to filter the predictions? Following that, what procedures are undertaken to align these filtered predictions with the ground truth poses? 

Thank you for your assistance!

**Comment by glenn-jocher** [comment]
Hello! 🙌

Great question! For computing the Object Keypoint Similarity (OKS) when multiple ground truth poses exist in an image, the predicted poses are indeed first filtered using Non-Maximum Suppression (NMS) to reduce duplicate detections. This helps in isolating the best prediction for each potential pose.

After applying NMS, each remaining predicted pose is compared to all ground truths in the image to find the best match. The matching is typically done based on the highest OKS value between a prediction and the ground truths. OKS itself is calculated for each keypoint pair (prediction and corresponding ground truth keypoint) and then averaged over all keypoints.

Here is a simplified process:
1. Apply NMS on the predictions.
2. For each prediction post-NMS, calculate OKS with every ground truth pose in the image.
3. Match each prediction to the ground truth poses based on the highest OKS score.

I hope this clarifies the procedure for matching predicted poses with multiple ground truths regarding OKS calculation! If you have further questions or need more detailed examples, feel free to ask. Happy coding! 😊

**Comment by enazari** [comment]
Hi @glenn-jocher,

Thank you for the thorough response. Is there a related implementation in the repository? 

Also, how is OKS calculated for multiple ground truths as a part of the loss during training? It does not involve NMS, correct?

Thank you once more.

**Comment by glenn-jocher** [comment]
Hi there!

You're welcome! 😊 For the specific implementation related to your query, you could take a look at the pose estimation parts of the code. I can't point to a direct link without knowing your exact needs, but exploring the directories related to training and evaluation should be helpful.

Regarding OKS during training, you're right, NMS is typically used during inference, not training. For training, OKS might be calculated for each predicted pose against corresponding ground truth poses directly, contributing to the loss. The goal is to minimize the discrepancy between predicted keypoints and the ground truth, improving the model's predictions over time.

Hope this helps, and feel free to reach out if you have more questions!
