### ISSUE TITLE
Not able to export yolov8 model as .engine

### ISSUE THREAD

**Issue by yucath** [ultralytics/ultralytics#9918]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to export yolov8 model as .engine to run with tensorRT. I am running in a docker container inside Jetson AGX Orin. I am able to load the .pt model but when I try to export it as .engien using:

model.export(format='engine') 

I am getting this error
[TRT] [W] Unknown embedded device detected. Using 59656MiB as the allocation cap for memory on embedded devices

**Comment by glenn-jocher** [comment]
@yucath hello! 👋

It appears you're encountering an issue with exporting your YOLOv8 model to TensorRT `.engine` format. The warning you're encountering is related to TensorRT trying to infer the memory allocation for your device, which might not directly stop the exporting process but is worth noting.

First, ensure your environment in the Jetson AGX Orin Docker container is correctly set up with all necessary dependencies for TensorRT and PyTorch. Specifically, make sure the version of TensorRT installed is compatible with the PyTorch version you're using.

If the setup looks correct, try specifying the TensorRT workspace size explicitly during export to see if it mitigates the warning. You can set the workspace size in gigabytes (GB) using the `workspace` parameter. For example, for a 4 GB allocation, you'd use:

```python
model.export(format='engine', workspace=4)
```

If the issue persists or if the warning turns into an error that stops the export, it could be helpful to provide the full traceback. This might offer more context on what the underlying issue could be.

Don't hesitate to share additional details if the problem continues. Our community and the Ultralytics team are here to help! 🙌

**Comment by yucath** [comment]
Hi Glenn, thanks for your detailed reply! Turns out that was just a warning and it was running fine. But it is taking a very long time to complete. Is that expected? I am exporting a yolov8 - small obb model and its taking me from about 30mins to 1.5 hrs to export. Also, if I want to run the inferences in batches, do I need to specify the batch size while exporting? I am exporting with dynamic=True, but it only allows me to run inference with certain size image and on just a single image, no batch.

**Comment by glenn-jocher** [comment]
Hi there! You're welcome, glad to hear the export process is running, albeit with warnings. 🚀

Yes, the exporting process, especially to TensorRT formats, can indeed be time-consuming, depending on the model complexity and the device performing the export. The times you mentioned, from 30 mins to 1.5 hrs, can be within expected ranges for complex models and hardware with limited computing power.

For running inferences in batches, specifying the batch size during export is indeed necessary if you want fixed batch size inference. However, with `dynamic=True`, you're indicating dynamic axes, which should, in theory, allow batch size flexibility at inference time. If it's not behaving as expected, ensure your inference script is correctly handling batched input data.

For example, structured like this for a batch of images:

```python
# Assuming 'model' is your exported and loaded engine
batched_input = torch.stack([image1_tensor, image2_tensor], dim=0)  # A simple example for two images
results = model(batched_input)
```

Just ensure your images are correctly pre-processed before stacking into a batch. 😊 If you encounter specific errors or limitations with `dynamic=True` not allowing varied image sizes or batch inference as expected, it might be helpful to review the model's export and inference codes or reach out with more details.

Hope this helps! Keep exploring, and don't hesitate to ask if you have more questions.

**Comment by yucath** [comment]
I noticed that the majority of the time is being taken by `setup_source` inside predictor.py. Is there a better way of runnning inference/loading images, so that we get the benefit of increased inference time through .engine model?

**Comment by glenn-jocher** [comment]
Hey there! 😊 I'm glad to hear you've managed to improve the loading times!

Regarding your query on inference with original image sizes - if you've exported your model with `imgsz=1024`, inference will be conducted at that size. For handling higher resolution images like your 1920x1200 ones, you'd either need to pre-process (resize) them before feeding them to the model or post-process the model outputs to map back to the original dimensions.

If automatic resizing was happening when providing image paths, and you wish to maintain original sizes in annotations, then a bit of post-processing would be necessary. Here's a snippet for resizing detection boxes back to the original dimensions:

```python
# Assuming 'results' is your model output
for det in results:
    det[:, :4] = scale_coords((1024, 1024), det[:, :4], (1920, 1200)).round()
```

This `scale_coords` function would adjust your detection coordinates from the model's input size back to the original image size. Just ensure you handle this scaling correctly based on your specific output format.

Hope this helps! Keep the feedback coming.

**Comment by yucath** [comment]
Hi Glenn,
Thanks for all your help. I have one more question or curiosity. I am able to run my export and scale back the predictions to original sizes. However, the exporting is taking a lot of time, it is more than the time to train the model. It took me 6hrs 20 mins to export an obb model trained with yolov8s-obb backbone. Is that expected or I am doing something wrong. Also, is there anyway I could boost the time taken. I am exporting on Jetson AGX Orin 64GB. My export code looks like this: 

```
t1m = time.time()
fruitlet_model = YOLO('/mnt/storage/model_path.pt')
fruitlet_model.export(format='engine',half=True,dynamic=True,batch=32,imgsz=(768,480),workers=4)

print(f'Total time taken to export the model: {time.time()-t1m}')
```

**Comment by glenn-jocher** [comment]
Hi there! 🌟 Glad to see you're making progress with your model export and scaling the predictions back. Exporting a model, especially to TensorRT (`engine` format), can indeed take a significant amount of time. This is because the process involves intensive optimizations to ensure your model runs as efficiently as possible during inference.

Given the complexities involved in exporting an `obb` model with the `yolov8s-obb` backbone and considering you're doing this on a Jetson AGX Orin, a 6hrs 20 mins export time does seem on the higher side, but it's not entirely unexpected for such an intensive task.

To possibly reduce the export time, you could try:
- Ensuring the device is not running other resource-intensive processes concurrently.
- Experiment with not setting `half=True` and `dynamic=True` to see if it has a significant impact on export duration. These options can increase export time due to the additional complexities they introduce.
- Check if you're using the latest versions of the Ultralytics YOLOv8 libraries and dependent CUDA/TensorRT libraries, as optimizations in later versions might lead to shorter export times.

The export setting you're using looks solid otherwise. Just remember, the time taken for these optimizations during export is a trade-off for much faster inference times later on. 

Hope this helps a bit, and keep up the great work!
