### ISSUE TITLE
Can YOLOv8-OpenCV-ONNX-Python only detect one image at a time?

### ISSUE THREAD

**Issue by liuliwenqing** [ultralytics/ultralytics#9925]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When using YOLOv8-OpenCV-ONNX-Python, the default parameters are as follows:
`if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default="yolov8n.onnx", help="Input your ONNX model.")
    parser.add_argument("--img", default=str(ASSETS / "bus.jpg"), help="Path to input image.")
    args = parser.parse_args()
    main(args.model, args.img)
`
So you can only recognize one image at a time? It's a little inconvenient.

**Comment by glenn-jocher** [comment]
Hello! 😊

Yes, the code snippet you've posted is configured to process a single image per run. However, to process multiple images, you can easily modify the code to loop through a list of images. Here's a quick example:

```python
import argparse
from pathlib import Path

# Assuming the function for inference is named 'main'
def process_images(model, images):
    for img in images:
        main(model, img)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default="yolov8n.onnx", help="Input your ONNX model.")
    parser.add_argument("--imgs", nargs='+', default=[str(ASSETS / "bus.jpg")], help="Paths to input images.")
    args = parser.parse_args()

    # Call the new function to process multiple images
    process_images(args.model, args.imgs)
```
To run this, instead of passing a single image path, you can pass multiple paths like so:

```bash
python your_script.py --imgs path/to/image1.jpg path/to/image2.jpg
```

Hope this helps! Let us know if you have more questions.

**Comment by liuliwenqing** [comment]
Thank you very much for your answer, but it is still very troublesome to add pictures one by one, can you directly identify a folder?

**Comment by glenn-jocher** [comment]
Absolutely, you can modify the script to process all images within a folder. Here's a simple way to do that using the `glob` module to find all JPG files in the specified folder:

```python
import argparse
import glob
from pathlib import Path

def process_images(model, folder_path):
    img_paths = glob.glob(f"{folder_path}/*.jpg")  # Adjust the pattern as necessary
    for img_path in img_paths:
        main(model, img_path)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default="yolov8n.onnx", help="Input your ONNX model.")
    parser.add_argument("--folder", default=str(Path.cwd() / "images"), help="Path to images folder.")
    args = parser.parse_args()
    
    process_images(args.model, args.folder)
```

To run this script, simply point `--folder` to your target directory, and it will process all JPG images within. Hope this simplifies things a bit more for you! 🌟

**Comment by liuliwenqing** [comment]
Thank you very much for your answer.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to ask. We're here to help! 😊
