### ISSUE TITLE
How to change gpu in one program

### ISSUE THREAD

**Issue by youthong** [ultralytics/ultralytics#9930]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

"How to make a model run on two different GPUs sequentially within the same program?"
I write the following code:
device=str(1)
results=model(source,device=device,save=False,show_conf=True,show=False,save_txt=False,project='predict',name='111')
time.sleep(5)
device=str(0)
results2=model(source,device=device,save=False,show_conf=True,show=False,save_txt=False,project='predict',name='111')

but it only use device 1

**Comment by glenn-jocher** [comment]
Hello! Thanks for reaching out with your question about utilizing multiple GPUs sequentially within the same program using YOLOv8. 🚀

To run your model on different GPUs sequentially, you need to ensure each `YOLO` model instance is tied to the respective device you wish to use. Here's a simplified way to achieve this:

```python
from ultralytics import YOLO
import time

# Load the model for GPU 1
model1 = YOLO('path_to_model.pt', device='cuda:1')
results1 = model1(source, save=False, show_conf=True, show=False, save_txt=False, project='predict', name='on_gpu1')

time.sleep(5)

# Load the model for GPU 0
model2 = YOLO('path_to_model.pt', device='cuda:0')
results2 = model2(source, save=False, show_conf=True, show=False, save_txt=False, project='predict', name='on_gpu0')
```

This approach ensures each model instance (`model1`,`model2`) is explicitly associated with a separate GPU (`cuda:1` for GPU 1 and `cuda:0` for GPU 0).

Remember to replace `'path_to_model.pt'` with the actual path to your model file and `source` with your input data. 😊

Hope this helps! Let us know if you have any more questions.
