### ISSUE TITLE
Additional Epoch Training

### ISSUE THREAD

**Issue by Bronx0910** [ultralytics/ultralytics#9932]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi after doing additional research on adding additional epochs in my training once the training session is complete, there is some confusion on the train function that I want to clarify. I found some solutions online that suggested this:

```
from ultralytics import YOLO

model = YOLO('path to last.pt file')
model.resume = True 

results = model.train(
    epochs=20 # number of additional epochs you want to train on
)
```

However, once I initiated this code, it just ran the additional epochs without getting the data from my dataset. If I used the modifications I made is this the correct solution?

```
model = YOLO('path to last.pt file') 

results = model.train(
    data = 'path to yaml file',
    epochs = 20, #additional epochs
    device = [0,1],
    pretrained = True
)

```

**Comment by glenn-jocher** [comment]
Hello! 😊

Your modification looks good! When you start training with additional epochs, it's crucial to specify the dataset, especially if it wasn't embedded in the model file. Your approach correctly specifies the dataset through the `data` argument and indicates the additional epochs you wish to train on. Also, setting `pretrained=True` ensures that the model starts with the weights from your file. Here's a slightly adjusted version:

```python
from ultralytics import YOLO

# Load the model and specify the path to your last checkpoint and dataset
model = YOLO('path to last.pt file')

# Train the model with additional epochs
results = model.train(
    data='path to yaml file',
    epochs=20,  # Total epochs to train including previous sessions
    device=[0, 1],
    pretrained=True  # Ensure weights are loaded
)
```

Make sure that `'path to yaml file'` points to your dataset configuration file, and `'path to last.pt file'` is the correct path to your previously trained model checkpoint. This way, it should correctly utilize your dataset during the additional training sessions.

If you encounter further issues or have more questions, don't hesitate to ask. Good luck with your training! 🚀

**Comment by Bronx0910** [comment]
Thank you for the help @glenn-jocher!

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions as you progress with your project, feel free to reach out. Happy coding! 😊

**Comment by Bronx0910** [comment]
I have also a question for adding images in my custom model is this configuration correct?

```
model = YOLO('last.pt')  # load custom model from past training

results = model.train(data='directory to new yaml file for additional image training',
                      epochs=100,
                      patience=30,
                      imgsz=640,
                      save=True,
                      save_period=10,
                      batch=-1,
                      device = [0,1],
                      pretrained = True)
```

**Comment by glenn-jocher** [comment]
Hi there! Your configuration for adding images to your custom model and continuing training looks good! Just ensure `'directory to new yaml file for additional image training'` accurately points to your updated YAML file that includes the paths to your new images. Everything else in your setup appears set to continue training seamlessly. 🚀 Happy training!

**Comment by Soms637** [comment]
Hello, I have problems with my additional training. First I trained the 1000epoch .Then I set the path of 'last.pt'and resume parameters and the total epochs I wish to complete.with the following code
`model = YOLO("/home/zp/utralytics/runs/classify/train9/weights/last.pt")
result=model.train(data='/home/zp/datasets/Data/8classifydata_down',
            epochs=2000,
            batch=256,
            imgsz=112,
            resume=True,
            Pretrain=True,
            device="cuda:0,cuda:1")
`
However, once I initiated this code, 
`AssertionError: /home/zp/utralytics/runs/classify/train9/weights/last.pt training to 1000 epochs is finished, nothing to resume.
Start a new training without resuming, i.e. 'yolo train model=/home/zp/utralytics/runs/classify/train9/weights/last.pt'`

**Comment by Soms637** [comment]
Thank you for you help,it works!!!
but seems like my weights are loaded but the learning rate are not inherited, , what should I do

**Comment by curtis18** [comment]
@glenn-jocher I have similar issue. After 1000/1000 epochs, I would like to have additional 1000 epochs, but it starts from 1/2000 instead of 1001/2000. Is it normal? Thank you.

model = YOLO("/home/zp/utralytics/runs/classify/train9/weights/last.pt")
result = model.train(data='/home/zp/datasets/Data/8classifydata_down',
                     epochs=2000,  # Total desired epochs
                     batch=256,
                     imgsz=112,
                     pretrained=True,  # Load weights and train further
                     device="cuda:0,cuda:1")

![image](https://github.com/user-attachments/assets/c0444ef6-11df-49a8-babe-54037e3c6a89)

**Comment by glenn-jocher** [comment]
Yes, that's normal. The training starts from epoch 1 again because it's continuing from the saved weights, not the epoch count.

**Comment by curtis18** [comment]
> Yes, that's normal. The training starts from epoch 1 again because it's continuing from the saved weights, not the epoch count.

@glenn-jocher Thanks for your help. Is it possible to update the epochs value in the pt file so that "resume" parameter can be used? I tried to test the pretrained parameter with additional 1000 epochs, but the mAP is much lower than the original model and triggered EarlyStopping. I assume the new model using pretrained parameter should be the same or better than the original model since the dataset and hyperparameters are the same.

![image](https://github.com/user-attachments/assets/93a8524f-4695-40cb-8f58-89470868f739)

**Comment by glenn-jocher** [comment]
The `resume` parameter is designed to continue training from where it left off, including the epoch count. If you're seeing lower mAP with `pretrained`, it might be due to differences in training dynamics. Consider checking the learning rate and other hyperparameters for consistency.

**Comment by curtis18** [comment]
@glenn-jocher Thank you for your great help. I will try to resolve it.
