### ISSUE TITLE
why only use device=0

### ISSUE THREAD

**Issue by youthong** [ultralytics/ultralytics#9934]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

when I write these codes to check my gpus, the program can only use device=0 even though I make the device=1;but when I remove these codes , it becomes normal

def get_available_gpus():
    if torch.cuda.is_available():
        device_count = torch.cuda.device_count()
        gpus = []
        for i in range(device_count):
            gpu_name = torch.cuda.get_device_name(i)
            gpus.append((i, gpu_name))
        return gpus
    else:
        return []

**Comment by glenn-jocher** [comment]
Hello! It seems like you've encountered an issue where specifying `device=1` doesn't switch the GPU being used. By default, if you don't explicitly set your device in PyTorch, it'll use `device=0`. To use a different GPU, you need to ensure that your model and tensors are moved to the target device. Here's a quick example:

```python
import torch

# Your code to get available GPUs seems correct
def get_available_gpus():
    if torch.cuda.is_available():
        return [(i, torch.cuda.get_device_name(i)) for i in range(torch.cuda.device_count())]
    else:
        return []

# Let's say you want to use device=1
device = torch.device('cuda:1' if torch.cuda.is_available() else 'cpu')

# Now, ensure your model and data are moved to this device
model.to(device)
# And similarly, when you create tensors or load data, move them to the selected device
# For example:
x = torch.tensor([1.0, 2.0]).to(device)
```

Make sure every operation involving the model or data tensors is performed after moving them to the specified device. This should allow you to use GPUs other than the default `device=0`. Feel free to share if there are more details or if you face any other issues! 😊

**Comment by youthong** [comment]
Thank you for your answer. I am now able to switch GPUs. However, I encountered the following issues when I tried to make predictions using the same model in the same program after switching GPUs:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking arugment for argument weight in method wrapper_cudnn_convolution)

The functionality you want to achieve is to control the model to run on different GPUs in real-time through a button in a running program.

**Comment by glenn-jocher** [comment]
@youthong great to hear you're able to switch GPUs now! 🎉 The error you're encountering indicates that parts of your model or input data are still on different devices. When performing operations, ensure both the model and the data it operates on are on the same GPU. Here's a quick example on how to move your model and its input data to the same device:

```python
device = torch.device('cuda:1') # Target device
model.to(device) # Move model to target device
inputs = inputs.to(device) # Ensure input data is also moved to the same device
```

For real-time GPU switching in a running program, apply this pattern right before making predictions, ensuring both the model and the data it's predicting on are moved to the new device. Happy coding! 😊

**Comment by youthong** [comment]
thanks for your answer，but I can not find the code to move the inputs in the source code.
Here is my code:

import time
import torch
from ultralytics import YOLO

def get_available_gpus():
    if torch.cuda.is_available():
        device_count = torch.cuda.device_count()
        gpus = []
        for i in range(device_count):
            gpu_name = torch.cuda.get_device_name(i)
            gpus.append((i, gpu_name))
        return gpus
    else:
        return []


list=get_available_gpus()


model = YOLO("yolov8n.pt")  
source=_path

device=str(0)
results=model(source,device=device,save=False,show_conf=True,show=False,save_txt=False,project='predict',name='111')

time.sleep(5)

device=1
torch.cuda.set_device(int(device))
device = torch.device(f'cuda:{device}')
model.to(device)

results2=model(source,device=device,save=False,show_conf=True,show=False,save_txt=False,project='predict',name='111')#error

**Comment by youthong** [comment]
my requirement is to use cuda:0 when I inference “results” and to use cuda:1 when I inference “results2”.
if it is possible,I want to know how to achieve my requirement.
Thanks

**Comment by glenn-jocher** [comment]
Hey there! 👋 

Absolutely, it's possible to switch GPUs between inferences with YOLOv8. There seems to be a small issue with setting the device in your code. To ensure your model and inputs are on the correct device, please follow these steps:

1. **Set the device directly when initializing the model:** The YOLO model supports passing the `device` parameter during initialization, making it straightforward to set the desired GPU. 

2. **Switch GPUs by re-initializing the model on the new device:** To switch the GPU after the initial inference, you'll need to reload the model on the new device.

Here's a revised snippet:

```python
from ultralytics import YOLO

# Load model on cuda:0
model = YOLO("yolov8n.pt", device='cuda:0')  
results = model(source, save=False)

# For the next inference on cuda:1, reinitialize the model on cuda:1
model = YOLO("yolov8n.pt", device='cuda:1')  
results2 = model(source, save=False)
```

This approach ensures that your model operates on the correct GPU for each inference. Hope this helps! Let us know if you have more questions. 😊

**Comment by youthong** [comment]
Thsnks for your answer.
And I have another question. When I use the codes belowing: 
 


model = YOLO("yolov8n.pt")   
source=_path 
print(torch.cuda.device_count()) 
print(torch.cuda.is_available())  
 



device=str(1) 
results=model(source,device=device,save=False,show_conf=True,show=False,save_txt=False,project='predict',name='111') 


even though I make device=1,it only uses cuda:0. 
but if I remove these codes(print(torch.cuda.device_count()),print(torch.cuda.is_available()) ),it becomes normal and can use cuda:1. 
why?---Original---
From: "Glenn ***@***.***&gt;
Date: Sun, Apr 14, 2024 22:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ultralytics/ultralytics] why only use device=0 (Issue #9934)




 
Hey there! 👋
 
Absolutely, it's possible to switch GPUs between inferences with YOLOv8. There seems to be a small issue with setting the device in your code. To ensure your model and inputs are on the correct device, please follow these steps:
  
 
Set the device directly when initializing the model: The YOLO model supports passing the device parameter during initialization, making it straightforward to set the desired GPU.
 
 
 
Switch GPUs by re-initializing the model on the new device: To switch the GPU after the initial inference, you'll need to reload the model on the new device.
 
  
Here's a revised snippet:
 from ultralytics import YOLO # Load model on cuda:0 model = YOLO("yolov8n.pt", device='cuda:0')   results = model(source, save=False) # For the next inference on cuda:1, reinitialize the model on cuda:1 model = YOLO("yolov8n.pt", device='cuda:1')   results2 = model(source, save=False)
 
This approach ensures that your model operates on the correct GPU for each inference. Hope this helps! Let us know if you have more questions. 😊

**Comment by youthong** [comment]
And I have another question. When I use the codes belowing:

model = YOLO("yolov8n.pt")  
source=_path
print(torch.cuda.device_count())
print(torch.cuda.is_available()) 

device=str(1)
results=model(source,device=device,save=False,show_conf=True,show=False,save_txt=False,project='predict',name='111')

even though I make device=1,it only uses cuda:0.
but if I remove these codes(print(torch.cuda.device_count()),print(torch.cuda.is_available()) ),it becomes normal and can use cuda:1.
why?

**Comment by youthong** [comment]
It throws a error:TypeError: __init__() got an unexpected keyword argument 'device'

**Comment by glenn-jocher** [comment]
@youthong hey there! Apologies for the confusion earlier 🙏. It looks like my initial suggestion was off the mark. Indeed, the `YOLO()` class from Ultralytics doesn't accept a `device` argument directly in its constructor. To switch devices, the proper approach after loading the model is to use `.to(device)` method on the model like this:

```python
from ultralytics import YOLO

# Load model
model = YOLO("yolov8n.pt")

# For inference on cuda:1
device = 'cuda:1'
model.to(device)

# Now you can perform inference on the specified device
results = model(source, save=False, show_conf=True, show=False, save_txt=False, project='predict', name='111')
```

Sorry for the oversight. Hope this clears things up! Happy coding 😊.

**Comment by isarandi** [comment]
Apparently it's not possible to move a YOLOv8 model from one GPU to another after compilation to TorchScript. Is this true? I mean exporting as `yolo export model=yolov8x.pt format=torchscript imgsz=640 batch=8 device=cuda half=True` and then loading the TorchScript model and putting it on `cuda:1`. `.to('cuda:1')` does not work because the anchors are still on the original 'cuda:0' device.

```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/ultralytics/nn/tasks.py", line 74, in forward
    _35 = (_18).forward(act, _34, )
    _36 = (_20).forward((_19).forward(act, _35, ), _29, )
    _37 = (_22).forward(_33, _35, (_21).forward(act, _36, ), )
           ~~~~~~~~~~~~ <--- HERE
    return _37
  File "code/__torch__/ultralytics/nn/modules/head.py", line 45, in forward
    anchor_points = torch.to(torch.unsqueeze(CONSTANTS.c0, 0), dtype=6, layout=0, device=torch.device("cuda:0"))
    lt, rb, = torch.chunk(_13, 2, 1)
    x1y1 = torch.sub(anchor_points, lt)
           ~~~~~~~~~ <--- HERE
    x2y2 = torch.add(anchor_points, rb)
    c_xy = torch.div(torch.add(x1y1, x2y2), CONSTANTS.c1)
```

**Comment by glenn-jocher** [comment]
Thank you for raising this valid point about device flexibility in TorchScript exports. You're absolutely correct that anchor tensors should ideally be registered as buffers to enable proper device migration. This is a known consideration for future architectural improvements. 

As a immediate solution, we recommend exporting directly on the target device using `device=cuda:1` during export to ensure all tensors are properly associated with the desired GPU from the start. Our team will explore enhanced buffer registration patterns to improve device portability in future releases.
