### ISSUE TITLE
Quantization int8

### ISSUE THREAD

**Issue by johnnynunez** [ultralytics/ultralytics#9936]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Now that next generation of gpus and Jetson is coming with fp8, fp6, fp4, int8 etc it could be nice if onnx and tensorRT also has quantization export not only for half.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@johnnynunez hello there! 👋

Thanks for bringing up the idea of enhancing quantization support for ONNX and TensorRT exports! 🚀

Indeed, as newer generations of GPUs and Jetson hardware offer support for various data types like fp8, fp6, fp4, and int8, it makes a lot of sense to explore broader quantization options beyond the current `half` (FP16) precision.

Currently, YOLOv8 allows for exporting models in FP16 and INT8 precision, which can be achieved by setting the `half` and `int8` arguments respectively during the export process. For instance, to export a model to ONNX format with INT8 quantization, you can use the following command:

```bash
yolo export model=yolov8n.pt format=onnx int8=true
```

Expanding support to include other quantizations like fp8, fp6, fp4, etc., would indeed be an exciting enhancement. We highly appreciate your willingness to contribute through a PR! 🌟

Before starting, I'd recommend discussing specifics and implementation ideas by opening a discussion thread in the GitHub repo. Collaborating with the community can help streamline the development process.

If you have any further thoughts or require any guidance, feel free to reach out!

**Comment by johnnynunez** [comment]
> @johnnynunez hello there! 👋
> 
> Thanks for bringing up the idea of enhancing quantization support for ONNX and TensorRT exports! 🚀
> 
> Indeed, as newer generations of GPUs and Jetson hardware offer support for various data types like fp8, fp6, fp4, and int8, it makes a lot of sense to explore broader quantization options beyond the current `half` (FP16) precision.
> 
> Currently, YOLOv8 allows for exporting models in FP16 and INT8 precision, which can be achieved by setting the `half` and `int8` arguments respectively during the export process. For instance, to export a model to ONNX format with INT8 quantization, you can use the following command:
> 
> ```shell
> yolo export model=yolov8n.pt format=onnx int8=true
> ```
> 
> Expanding support to include other quantizations like fp8, fp6, fp4, etc., would indeed be an exciting enhancement. We highly appreciate your willingness to contribute through a PR! 🌟
> 
> Before starting, I'd recommend discussing specifics and implementation ideas by opening a discussion thread in the GitHub repo. Collaborating with the community can help streamline the development process.
> 
> If you have any further thoughts or require any guidance, feel free to reach out!

So,
is this documentation updated?
<img width="927" alt="image" src="https://github.com/ultralytics/ultralytics/assets/22727137/c4d9360f-79dc-4acc-85fa-07e2de038eed">

**Comment by NeuralAIM** [comment]
> > @johnnynunez hello there! 👋
> > Thanks for bringing up the idea of enhancing quantization support for ONNX and TensorRT exports! 🚀
> > Indeed, as newer generations of GPUs and Jetson hardware offer support for various data types like fp8, fp6, fp4, and int8, it makes a lot of sense to explore broader quantization options beyond the current `half` (FP16) precision.
> > Currently, YOLOv8 allows for exporting models in FP16 and INT8 precision, which can be achieved by setting the `half` and `int8` arguments respectively during the export process. For instance, to export a model to ONNX format with INT8 quantization, you can use the following command:
> > ```shell
> > yolo export model=yolov8n.pt format=onnx int8=true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Expanding support to include other quantizations like fp8, fp6, fp4, etc., would indeed be an exciting enhancement. We highly appreciate your willingness to contribute through a PR! 🌟
> > Before starting, I'd recommend discussing specifics and implementation ideas by opening a discussion thread in the GitHub repo. Collaborating with the community can help streamline the development process.
> > If you have any further thoughts or require any guidance, feel free to reach out!
> 
> So, is this documentation updated? <img alt="image" width="927" src="https://private-user-images.githubusercontent.com/22727137/321324645-c4d9360f-79dc-4acc-85fa-07e2de038eed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3OTA0MDAsIm5iZiI6MTcxMjc5MDEwMCwicGF0aCI6Ii8yMjcyNzEzNy8zMjEzMjQ2NDUtYzRkOTM2MGYtNzlkYy00YWNjLTg1ZmEtMDdlMmRlMDM4ZWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDIzMDE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYzQwZWQ2NzlhZmY5OTU4NGY5NjMzZDJjMWE4MTI0ZTVlZmQ2YTlmZjVkMWY2MDBiMDE0YzM3ZjhjNzhlYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M3JeCASQEH8QNDxvkVse1eP7yanoxe2rYlB_6eKkFoY">

This is a **GlenGPT**...
Documentation on the site is correct. onnx models can only be exported with half=True (int8 not working for onnx models)

**Comment by NeuralAIM** [comment]
I quantize model (int8), the weight of the model decreased to 3.5 MB, it became 5-10% faster on the CPU, but the speed dropped by 10-15% for the GPU : (

**Comment by glenn-jocher** [comment]
Hey there! Thanks for sharing your experience with quantizing to INT8 🚀. Quantization can yield different performance effects depending on the hardware. While you observed a speedup on CPU, GPU performance can vary due to how different architectures handle lower precision operations. For GPU acceleration, experimenting with FP16 quantization might be more beneficial, as many GPUs are optimized for these operations. Here's an example to export a model to FP16, which generally works well with GPUs:

```bash
yolo export model=yolov8n.pt format=onnx half=true
```

It's always intriguing to see how different optimizations impact model performance across various platforms. Keep experimenting! 🛠

**Comment by glenn-jocher** [comment]
Hi there! 👋

Looks great, I've taken a look at the pull request #9969. Thank you for contributing! I'll review the details and get back to you with any feedback or questions.

Cheers! 😊
