### ISSUE TITLE
 cannot import name 'yolo' from 'ultralytics'

### ISSUE THREAD

**Issue by shivangi1001** [ultralytics/ultralytics#9938]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Traceback (most recent call last):
  File "C:\Users\shivan\Desktop\Spot\try.py", line 1, in <module>
    from ultralytics import yolo
ImportError: cannot import name 'yolo' from 'ultralytics' (C:\Users\shivan\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\__init__.py).

I'm using windows and Visual studio code for my project and have sucessfully installed ultralytics still getting this error.

**Comment by yucath** [comment]
its capital, from ultralytics import YOLO

**Comment by glenn-jocher** [comment]
It looks like there's a little mix-up in the import statement. You should use `YOLO` instead of `yolo` with a capital `Y`. Here's the correct way to import it:

```python
from ultralytics import YOLO
```

Try this out, and you should be good to go! 😊
