### ISSUE TITLE
Segmentation mask

### ISSUE THREAD

**Issue by rzamarefat** [ultralytics/ultralytics#9939]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have visualized the segmentation mask for the class of "person" in an image. The code:

    res = model.predict(img)   
    for r in res:
        for xy in r.masks.xy:
            xy = xy.astype(int)
            for coords in xy:
                cv2.circle(img, (coords[0], coords[1]), 2, (255, 255, 11), -1)
    
    cv2.imwrite("example.png", img)

The visualization went like the following (The image illustrates a part of the person):
![Screenshot 2024-04-10 150712](https://github.com/ultralytics/ultralytics/assets/79300456/d58d31d3-9a50-4592-a7a9-94e950975c23)

I want to get the binary image of the predicted mask. How can I achieve it? Could you please provide a code snippet?

**Comment by glenn-jocher** [comment]
Absolutely, converting the predicted mask to a binary format can be straightforward. Given that you've already visualized the segmentation masks, converting these masks to a binary image involves a few extra steps. For a segmentation task where each pixel's value represents the presence or absence of the "person" class, you might consider the following approach:

```python
# Assuming 'res' is the results object from 'model.predict(img)'
# Initialize an empty binary mask with the same height and width as 'img' and dtype 'uint8'
binary_mask = np.zeros_like(img[...,0], dtype=np.uint8)  

for r in res:
    if 'masks' in r.__dict__:  # Ensure 'masks' attribute exists
        for mask in r.masks:  # Iterate over individual masks
            # Convert each mask's (x, y) coordinates into a polygon and draw it on 'binary_mask'
            cv2.fillPoly(binary_mask, pts=[mask.xy.astype(np.int32)], color=(255))

cv2.imwrite("binary_mask.png", binary_mask)
```

This code snippet creates a binary image where the areas covered by the "person" class segmentation masks are white (`255`), and the rest of the image is black (`0`). Do adapt the snippet as necessary based on the precise structure of your `results` object and the specifics of your task. 🚀

**Comment by johnohagan** [comment]
There's an easier way! `masks.data` already contains the binary masks as tensors.
```

for r in res:
    for mask in r.masks:
        xy = mask.xy.astype(int)
        binmask = mask.data[0].numpy() 
        . . .
```

**Comment by glenn-jocher** [comment]
That's a great point, and a neat shortcut to access the binary masks directly! 🌟 Utilizing `.data` simplifies the process significantly. Your code snippet effectively demonstrates how to iterate through the results to work with each mask individually. Thanks for sharing this tip! Here's a brief example to save a single binary mask:

```python
import cv2
import numpy as np

# Assuming 'res' is the output from 'model.predict(img)'
for r in res:
    for mask in r.masks:
        bin_mask = mask.data[0].numpy()  # Accessing the binary mask
        bin_mask = (bin_mask * 255).astype(np.uint8)  # Convert to uint8
        cv2.imwrite("binary_mask_example.png", bin_mask)  # Save mask
        break  # Example: breaks after the first mask for demonstration
```

This step demonstrates how you might transform the binary mask tensor into an image format and save it. 🚀 Keep those insights coming!
