### ISSUE TITLE
save_crop argument in (detect task, predict mode) writes the crops with visible bboxes with wrong base names

### ISSUE THREAD

**Issue by bit-scientist** [ultralytics/ultralytics#994]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Validation, Detection

### Bug

When I execute with the following: `yolo detect predict model=yolov8n.pt source="https://ultralytics.com/images/bus.jpg" save_crop` it behaves normally. 

```
Ultralytics YOLOv8.0.18  Python-3.8.13 torch-1.13.1 CUDA:0 (NVIDIA GeForce RTX 3080 Ti, 12288MiB)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
Found https://ultralytics.com/images/bus.jpg locally at bus.jpg
C:\Users\office\anaconda3\envs\yolov8\lib\site-packages\ultralytics\yolo\utils\plotting.py:160: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  xyxy = torch.tensor(xyxy).view(-1, 4)
image 1/1 S:\GITHUB\v8\bus.jpg: 640x480 4 persons, 1 bus, 1 stop sign, 28.0ms
Speed: 1.0ms pre-process, 28.0ms inference, 36.0ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs\detect\predict3
```

However, the saved crop images contain visual bboxes as below:
![image](https://user-images.githubusercontent.com/26497571/219223849-95802abc-0e03-4b37-8ab8-417d4a8ab051.png)
Also, the images are the crops from the person class which should match the base names of the crops as person1, person2, etc. 

### Environment

Ultralytics YOLOv8.0.18  Python-3.8.13 torch-1.13.1 CUDA:0 (NVIDIA GeForce RTX 3080 Ti, 12288MiB)
Windows 10.

### Minimal Reproducible Example

`yolo detect predict model=yolov8n.pt source="https://ultralytics.com/images/bus.jpg" save_crop`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@bit-scientist hi thanks for the reporting! I believe this issue had been fixed, please upgrade your package version. :)
here are my cropped images:
![bus2](https://user-images.githubusercontent.com/61612323/219246661-bbfb7614-d822-46cc-b767-078996f923a3.jpg)
![bus4](https://user-images.githubusercontent.com/61612323/219246672-cf26ecd1-14e5-473e-9db7-f87efe3b9157.jpg)

**Comment by bit-scientist** [comment]
thanks, could you confirm the base names are proper too?

**Comment by Laughing-q** [comment]
@bit-scientist ah the folder looks right but base names look incorrect, I'll fix it.
![image](https://user-images.githubusercontent.com/61612323/219253262-b2b921ed-c525-40a4-93b1-700366dd2e9e.png)

**Comment by Laughing-q** [comment]
@bit-scientist Actually the base names are correct as it's the name of predicted images, .i.e the person images are from bus.jpg so these names are `bus1.jpg`, `bus2.jpg`.

**Comment by bit-scientist** [comment]
I got what you mean now. Don't you think it would be more intuitive if the base names of the crops of a particular image were the incremented class names?

**Comment by Laughing-q** [comment]
@bit-scientist it could be, but in the current way users are able to know which cropped images belong to which original image.
