### ISSUE TITLE
Retraining the model on the new dataset without losing the old model

### ISSUE THREAD

**Issue by Harsh854311** [ultralytics/ultralytics#9944]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained the yolov8 model on a custom dataset on 150 epochs and training has been completed and the model is working fine. Now I have some new dataset and I want to retrain the model on the new dataset without starting from the scratch. I have tried every method that I can find on github community and stackoverflow but unable to resume the training. I have tried to change the file path to last.pt and number of epochs in the args.yaml but still no luck. I have changed the number of epochs to 200 and tried to resume the training for 50 epochs but it didn't work. Help me out here!!

The error:-
AssertionError: D:\AI\Fire_Model_Train\runs\detect\Fire1\weights\last.pt training to 150 epochs is finished, nothing to resume.
Start a new training without resuming, i.e. 'yolo train model=D:\AI\Fire_Model_Train\runs\detect\Fire1\weights\last.pt'

**Comment by glenn-jocher** [comment]
@Harsh854311 hey there! 👋

It looks like you're attempting to continue training your previously trained YOLOv8 model with additional data. The message you encountered typically occurs when attempting to resume training beyond the originally specified epoch count without adjusting it accordingly for the continuation.

To continue training your model on new data without starting from scratch, you can simply initiate a new training session while specifying your pre-trained model as the starting point. Here's an example command that should guide you in the right direction:

```bash
yolo train model=D:\AI\Fire_Model_Train\runs\detect\Fire1\weights\last.pt data=new_dataset.yaml epochs=200
```

In this command:
- Replace `new_dataset.yaml` with the path to your new dataset configuration file.
- Set `epochs` to the total you aim for by the end of training (old + new).

This approach doesn't use the resume option, avoiding the error and effectively continuing training with your extended epoch target.

Hope this helps and happy training with the new dataset!

**Comment by Harsh854311** [comment]
Thank you @glenn-jocher  for your valuable help.
I just have one doubt, if I enter 200 epochs then the training will be done for 200 epochs or for 50 epochs only as I have already trained the model for 150 epochs and do I have to change the epochs count in the args.yaml file too?

**Comment by glenn-jocher** [comment]
Hey there! 👋

Great question! If you set `epochs=200` and your model has already been trained for 150 epochs, then training will **continue for an additional 50 epochs**. There's no need to modify the `epochs` count in the `args.yaml` file for this; setting the epoch count in your training command suffices. 

Here's a quick example for clarity:

```bash
yolo train model=path_to_your/last.pt data=new_dataset.yaml epochs=200
```

This tells the model to train up to 200 epochs total, picking up right where it left off. Hope this clears things up for you! 😊

**Comment by Harsh854311** [comment]
Thanks @glenn-jocher  for the clarification. It clears all my doubt and my model retraining is working fine.

Thank you

**Comment by glenn-jocher** [comment]
@Harsh854311 you're welcome! 😊 I'm thrilled to hear your model retraining is going smoothly! If you have any more questions or need further assistance, feel free to reach out. Happy training! 👍
