### ISSUE TITLE
YOLOv8 classification metrics

### ISSUE THREAD

**Issue by noursa99** [ultralytics/ultralytics#9946]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained a custom model using YOLOv8 for image classification which contains 9 classes. I am using the following Python code for the validation:
from ultralytics import YOLO
model = YOLO('path/to/best.pt')
metrics = model.val() 

The problem is that I only get the values of accuracy_top1 and accuracy_top5. A confusion matrix is also saved as an image, but I need the precision and recall values. Is it possible to figure them out? Or is it at least possible to find out the number of tn, tp, fn and fp? so that I can calculate the precision and recall by myself.

**Comment by glenn-jocher** [comment]
Hello! 👋 Glad to see you're making great use of YOLOv8 for image classification!

To directly obtain precision and recall values or calculate them based on true positives (tp), true negatives (tn), false positives (fp), and false negatives (fn) from YOLOv8, you may need to delve a bit deeper, as these specifics are not directly provided via the simple `.val()` method.

However, you can directly access the confusion matrix results saved during validation to calculate these metrics. Although not as straightforward as having them calculated automatically, here's a basic approach to calculate precision and recall using the confusion matrix data:

```python
import numpy as np

# Assume 'cm' is your confusion matrix loaded from the saved image or directly if available
# cm = np.array([...]) # Your confusion matrix as a numpy array

# Calculating True Positives (TP), False Positives (FP), True Negatives (TN), False Negatives (FN)
TP = np.diag(cm)
FP = np.sum(cm, axis=0) - TP
FN = np.sum(cm, axis=1) - TP
TN = np.sum(cm) - (FP + FN + TP)

# Precision and Recall for each class
precision = TP / (TP + FP)
recall = TP / (TP + FN)

# For overall metrics, you might average or sum these depending on the context
precision_overall = np.mean(precision)
recall_overall = np.mean(recall)

print(f"Precision per class: {precision}")
print(f"Recall per class: {recall}")
print(f"Overall Precision: {precision_overall}")
print(f"Overall Recall: {recall_overall}")
```

Note: This code assumes you have access to the confusion matrix data in a suitable format. Depending on how the confusion matrix is saved or processed in your project, you might need to manually extract or convert this data.

I hope this helps you calculate the metrics you need! If you have any more questions or need further assistance, feel free to ask. ☺️

**Comment by noursa99** [comment]
Thank you very much :) It worked perfectly

**Comment by glenn-jocher** [comment]
I'm thrilled to hear it worked out for you! 😊 If you have any more questions or need further assistance down the road, don't hesitate to reach out. Happy coding!

**Comment by hariouat** [comment]
> I'm thrilled to hear it worked out for you! 😊 If you have any more questions or need further assistance down the road, don't hesitate to reach out. Happy coding!

I'm reaching out to seek clarification on the accuracy metric reported by the YOLOv8 model during validation. According to the documentation, the value should represent the model's accuracy. However, when I calculate the accuracy using the traditional formula based on true positives and false positives/negatives from my confusion matrix, I obtain an accuracy of 84%, which differs from the 91.3% reported by the model.
![image](https://github.com/ultralytics/ultralytics/assets/117453280/674699bd-1c2c-407c-b154-3f854c5bad84)


Here's the formula I've used for my calculation:
# Updated values from the confusion matrix
TP_dente = 125
TP_lisse = 127
FN_dente = 9
FP_lisse = 15
FP_dente = FN_dente  # False positives for Dente are the false negatives for Lisse
FN_lisse = FP_lisse  # False negatives for Lisse are the false positives for Dente

# Precision and Recall for each class
precision_dente = TP_dente / (TP_dente + FP_dente)
recall_dente = TP_dente / (TP_dente + FN_dente)

precision_lisse = TP_lisse / (TP_lisse + FP_lisse)
recall_lisse = TP_lisse / (TP_lisse + FN_lisse)

# F1 score for each class
f1_dente = 2 * (precision_dente * recall_dente) / (precision_dente + recall_dente)
f1_lisse = 2 * (precision_lisse * recall_lisse) / (precision_lisse + recall_lisse)

# Overall Precision, Recall, and F1 score
precision_overall = (precision_dente + precision_lisse) / 2
recall_overall = (recall_dente + recall_lisse) / 2
f1_overall = (f1_dente + f1_lisse) / 2

# Accuracy calculation
accuracy_overall = (TP_dente + TP_lisse) / (TP_dente + TP_lisse + FP_dente + FN_dente + FP_lisse + FN_lisse)
print(f"precision_dente: {precision_dente}")
print(f"precision_lisse: {precision_lisse}")
print(f"recall_dente: {recall_dente}")
print(f"recall_lisse: {recall_lisse}")
print(f"f1_dente: {f1_dente}")
print(f"f1_lisse: {f1_lisse}")
# Output the results
precision_overall, recall_overall, f1_overall, accuracy_overall

This is the result: 
precision_dente: 0.9328358208955224
precision_lisse: 0.8943661971830986
recall_dente: 0.9328358208955224
recall_lisse: 0.8943661971830986
f1_dente: 0.9328358208955224
f1_lisse: 0.8943661971830986

(0.9136010090393105, 0.9136010090393105, 0.9136010090393105, 0.84)

![confusion_matrix(2)](https://github.com/ultralytics/ultralytics/assets/117453280/f17923c8-b0f7-4f79-b73d-abbab02837a9)

**Comment by glenn-jocher** [comment]
@hariouat hello!

It looks like you've done a thorough calculation based on the confusion matrix. In YOLOv8, accuracy during `model.val()` is typically calculated as the ratio of correctly classified samples to the total number of samples. There might be a slight difference in how accuracy is computed or interpreted, especially if the model's prediction step involves specific thresholds or additional steps not captured in the traditional accuracy calculation.

Given the discrepancy you observed, it's also important to consider factors such as class imbalance or the specific accuracy metric reported by YOLOv8 (e.g., top-1 accuracy, weighted average, etc.) that might influence the overall accuracy. 

Please ensure that the comparison is done on the same basis. Accuracy can sometimes be reported differently depending on whether it's micro or macro-averaged, especially if there's a significant class imbalance. YOLOv8 might be using a different formula or including additional considerations in its validation calculations.

If you continue to see significant discrepancies, I'd suggest inspecting the validation set's annotations and reviewing how YOLOv8 discounts certain detections or misclassifications during validation, as it might shed some light on the observed differences.

If you can share more details about the dataset and the exact model configuration, I'd be happy to dive deeper into this. 😊

**Comment by hariouat** [comment]
> It looks like you've done a thorough calculation based on the confusion matrix. In YOLOv8, accuracy during `model.val()` is typically calculated as the ratio of correctly classified samples to the total number of samples. There might be a slight difference in how accuracy is computed or interpreted, especially if the model's prediction step involves specific thresholds or additional steps not captured in the traditional accuracy calculation.
> 
> Given the discrepancy you observed, it's also important to consider factors such as class imbalance or the specific accuracy metric reported by YOLOv8 (e.g., top-1 accuracy, weighted average, etc.) that might influence the overall accuracy.
> 
> Please ensure that the comparison is done on the same basis. Accuracy can sometimes be reported differently depending on whether it's micro or macro-averaged, especially if there's a significant class imbalance. YOLOv8 might be using a different formula or including additional considerations in its validation calculations.
> 
> If you continue to see significant discrepancies, I'd suggest inspecting the validation set's annotations and reviewing how YOLOv8 discounts certain detections or misclassifications during validation, as it might shed some light on the observed differences.
> 
> If you can share more details about the dataset and the exact model configuration, I'd be happy to dive deeper into this.

Thank you for your prompt response. I am reaching out again as there seems to be a misunderstanding regarding the accuracy metric. Let me provide additional context for clarity.

My test dataset consists of two classes: 'Dente' with 24 images and 'Lisse' with 27 images. Using the YOLOv8 model, I executed the following code to compute the accuracy on the test set:

from ultralytics import YOLO
import numpy as np
model = YOLO('SegM/weights/best.pt')
metrics = model.val(data='BordureWithout', split='test', workers=0, batch=8, imgsz=640, save=True)

The output accuracy from this code is 0.913.

Since YOLOv8 does not provide direct access to precision, recall, and F1 score calculations, I computed these metrics separately and attempted to verify the accuracy to see if it matched what model.val reported. Unfortunately, my calculations did not align with the reported accuracy.

Could you please advise on what additional information from my data or calculations I can provide to help us jointly review and resolve this discrepancy?

I appreciate your assistance on this matter.

**Comment by glenn-jocher** [comment]
Hey there! 👋 Thanks for the detailed follow-up. It's clear you're thoroughly analyzing your results, which is great!

The accuracy metric reported by `model.val()` in YOLOv8 indeed reflects the proportion of correct predictions over the total predictions. 🎯 However, the method of calculation can slightly differ due to factors like how YOLOv8 handles multi-class predictions, threshold settings for class probabilities, and possibly how dataset imbalance is taken into account.

Given your test dataset structure and the calculated accuracy, it seems there might be a nuance in the calculation method or a post-processing step influencing the reported accuracy. 

For a closer examination, could you provide:

- The threshold used for classifying predictions.
- Any specific preprocessing or augmentation applied to the test set.
- The version of YOLOv8 you're using, as updates might adjust performance metrics.

These pieces of information could shed some light on the observed discrepancy. Meanwhile, here’s a quick code snippet to calculate basic accuracy, considering a simple binary or multi-class scenario where predictions and labels are directly comparable:

```python
correct = (predictions == ground_truth_labels).sum().item()
total = ground_truth_labels.shape[0]
accuracy = correct / total
print(f"Calculated Accuracy: {accuracy}")
```

Remember, the specific classes and how model predictions align with ground_truth_labels can greatly influence this calculation. 😊 Let's pinpoint the mismatch together!

**Comment by hariouat** [comment]
> For a closer examination, could you provide:
> 
>     * The threshold used for classifying predictions.
> 
>     * Any specific preprocessing or augmentation applied to the test set.
> 
>     * The version of YOLOv8 you're using, as updates might adjust performance metrics.

Hello and thank you very much for your feedback. Here are my responses to the questions:

    The threshold used for classifying predictions: I did not set any threshold myself but rather used the default threshold in YOLOv8. After running model.val, I get both the normalized confusion matrix and the regular confusion matrix. (Here are the two images).
![confusion_matrix_normalized](https://github.com/ultralytics/ultralytics/assets/117453280/e32efb6f-11ca-4365-a154-83b8cdda5fc1)
![confusion_matrix](https://github.com/ultralytics/ultralytics/assets/117453280/ab6964b0-bc9d-48e5-a8af-ce6274a2d1d8)


    Any specific preprocessing or augmentation applied to the test set: No augmentation was used for the test set; however, augmentation was used during training, and here is my modified YAML.
    
    ------------------------------------------------------------------------------------------------------
lr0: 0.01  # (float) initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
lrf: 0.002  # (float) final learning rate (lr0 * lrf)
momentum: 0.937  # (float) SGD momentum/Adam beta1
weight_decay: 0.0005  # (float) optimizer weight decay 5e-4
warmup_epochs: 3.0  # (float) warmup epochs (fractions ok)
warmup_momentum: 0.8  # (float) warmup initial momentum
warmup_bias_lr: 0.1  # (float) warmup initial bias lr
box: 7.5  # (float) box loss gain
cls: 0.5  # (float) cls loss gain (scale with pixels)
dfl: 1.5  # (float) dfl loss gain
pose: 12.0  # (float) pose loss gain
kobj: 1.0  # (float) keypoint obj loss gain
label_smoothing: 0.0  # (float) label smoothing (fraction)
nbs: 64  # (int) nominal batch size
hsv_h: 0.015  # (float) image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # (float) image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # (float) image HSV-Value augmentation (fraction)
degrees: 0.5  # (float) image rotation (+/- deg)
translate: 0  # (float) image translation (+/- fraction)
scale: 1.0  # (float) image scale (+/- gain)
shear: 0.0  # (float) image shear (+/- deg)
perspective: 0.001  # (float) image perspective (+/- fraction), range 0-0.001
flipud: 1  # (float) image flip up-down (probability)
fliplr: 1  # (float) image flip left-right (probability)
mosaic: 0.0  # (float) image mosaic (probability)
mixup: 0.0  # (float) image mixup (probability)
copy_paste: 0.0  # (float) segment copy-paste (probability)
    

    The version of YOLOv8 you're using, as updates might adjust performance metrics: Ultralytics 8.1.14.

**Comment by glenn-jocher** [comment]
Hey there! 😊 Thanks for providing the details so promptly!

From what you've shared:

- **Threshold**: You're using the YOLOv8 default threshold for predictions. For future reference, the default thresholds often balance detection sensitivity and specificity well, but feel free to experiment with them for your specific use case.
- **Preprocessing and Augmentation**: No augmentation applied to the test set, which is standard practice to evaluate the model under more 'natural' conditions. Your training augmentations in the YAML seem well-thought-out, targeting a robust model capable of handling real-world variations.
- **YOLOv8 Version**: You're on Ultralytics 8.1.14, a recent version. Staying updated is good for catching the latest improvements and bug fixes!

Your confusion matrices look great! If you're still concerned about interpreting accuracy or other metrics, remember, direct comparison from the matrices can sometimes overlook the subtleties of how metrics are calculated, especially with specific configurations like yours. 

If you have further questions or need a deeper dive into any aspect, feel free to reach out. Wishing you success with your project! 🚀

**Comment by sarahsftri** [comment]
> Hello! 👋 Glad to see you're making great use of YOLOv8 for image classification!
> 
> To directly obtain precision and recall values or calculate them based on true positives (tp), true negatives (tn), false positives (fp), and false negatives (fn) from YOLOv8, you may need to delve a bit deeper, as these specifics are not directly provided via the simple `.val()` method.
> 
> However, you can directly access the confusion matrix results saved during validation to calculate these metrics. Although not as straightforward as having them calculated automatically, here's a basic approach to calculate precision and recall using the confusion matrix data:
> 
> ```python
> import numpy as np
> 
> # Assume 'cm' is your confusion matrix loaded from the saved image or directly if available
> # cm = np.array([...]) # Your confusion matrix as a numpy array
> 
> # Calculating True Positives (TP), False Positives (FP), True Negatives (TN), False Negatives (FN)
> TP = np.diag(cm)
> FP = np.sum(cm, axis=0) - TP
> FN = np.sum(cm, axis=1) - TP
> TN = np.sum(cm) - (FP + FN + TP)
> 
> # Precision and Recall for each class
> precision = TP / (TP + FP)
> recall = TP / (TP + FN)
> 
> # For overall metrics, you might average or sum these depending on the context
> precision_overall = np.mean(precision)
> recall_overall = np.mean(recall)
> 
> print(f"Precision per class: {precision}")
> print(f"Recall per class: {recall}")
> print(f"Overall Precision: {precision_overall}")
> print(f"Overall Recall: {recall_overall}")
> ```
> 
> Note: This code assumes you have access to the confusion matrix data in a suitable format. Depending on how the confusion matrix is saved or processed in your project, you might need to manually extract or convert this data.
> 
> I hope this helps you calculate the metrics you need! If you have any more questions or need further assistance, feel free to ask. ☺️

How to access cm??

**Comment by glenn-jocher** [comment]
Hello! 😊

To access the confusion matrix (`cm`) generated during the validation process, you can find it saved as an image in the `runs/detect/val` directory. You can manually extract the data from this image or, if available, directly from the validation results in your code.

If you need further assistance or have more questions, feel free to ask. Happy coding! 🚀

**Comment by AdityaBala05** [comment]
I have trained my Yolov8 multi class classification for 4 classes and validated the test data with an accuracy of 88% 

I tried getting Precision and recall using metrics.box() but got an error stating Classify metrics does not have .box 

How do I plot Roc curve and find f1 score, precision ,recall for this and are there any other metrics that I can show apart from Accuracy, precision,recall,f1 score,Roc plot

**Comment by Vlad188-1** [comment]
> Hello! 👋 Glad to see you're making great use of YOLOv8 for image classification!
> 
> To directly obtain precision and recall values or calculate them based on true positives (tp), true negatives (tn), false positives (fp), and false negatives (fn) from YOLOv8, you may need to delve a bit deeper, as these specifics are not directly provided via the simple `.val()` method.
> 
> However, you can directly access the confusion matrix results saved during validation to calculate these metrics. Although not as straightforward as having them calculated automatically, here's a basic approach to calculate precision and recall using the confusion matrix data:
> 
> import numpy as np
> 
> # Assume 'cm' is your confusion matrix loaded from the saved image or directly if available
> # cm = np.array([...]) # Your confusion matrix as a numpy array
> 
> # Calculating True Positives (TP), False Positives (FP), True Negatives (TN), False Negatives (FN)
> TP = np.diag(cm)
> FP = np.sum(cm, axis=0) - TP
> FN = np.sum(cm, axis=1) - TP
> TN = np.sum(cm) - (FP + FN + TP)
> 
> # Precision and Recall for each class
> precision = TP / (TP + FP)
> recall = TP / (TP + FN)
> 
> # For overall metrics, you might average or sum these depending on the context
> precision_overall = np.mean(precision)
> recall_overall = np.mean(recall)
> 
> print(f"Precision per class: {precision}")
> print(f"Recall per class: {recall}")
> print(f"Overall Precision: {precision_overall}")
> print(f"Overall Recall: {recall_overall}")
> Note: This code assumes you have access to the confusion matrix data in a suitable format. Depending on how the confusion matrix is saved or processed in your project, you might need to manually extract or convert this data.
> 
> I hope this helps you calculate the metrics you need! If you have any more questions or need further assistance, feel free to ask. ☺️

Hi! I would like to clarify this point. If I calculate the confusion matrix using ultralytics and want to manually calculate **TP, FP, FN**, then as far as I understand I need to change the summation index, since you give an example for situations when horizontally - these are **predicted values** and vertically - **ground true** ones. In the **ultralytics** package, the confusion matrix is ​​drawn in opposite axes, that is, horizontally (x-axis) - **true values**, and vertically (y-axis) - **predicted**. This means that all the values ​​**FP** are located horizontally, **FN** - vertically.

My example using **ultralytics** package:
```python
import numpy as np
from ultralytics.utils.metrics import ConfusionMatrix

yolo_confusion_matrix = ConfusionMatrix(nc=2, conf=0.3)

target_preds: list[tuple[np.ndarray, np.ndarray]]

for (_target, _pred) in target_preds:
    yolo_confusion_matrix.process_batch(detections=torch.Tensor(_pred),
                                        gt_bboxes=torch.Tensor(_target[:, :4]),
                                        gt_cls=torch.Tensor(_target[:, 4]))

calculated_matrix = yolo_confusion_matrix.matrix

TP = np.diag(calculated_matrix)
FP = calculated_matrix.sum(axis=1) - TP
FN = calculated_matrix.sum(axis=0) - TP
```
In my example, I changed the summation axis for **FP**, and **FN**, since the values ​​for **FP** are located horizontally in the confusion matrix, and **FN** - vertically. Is my understanding and implementation of counting **TP, FP, FN** using the ultralytics repository correct or not?

Thanks!

**Comment by AdityaBala05** [comment]
Thank you so much for solving this query, i saw this code earlier but was
pondering whether there was any way i can get these values automatically
while validation.Sorry to bother you but I have few doubts
1) Do I need to put bounding box on images for plotting ROC curve for image
classification in YoloV8, if yes how many images should be having
bounding box, my test data has 496 images.
2) If yes or if no for above, how do i plot that curve in my colab
3) Which are the best XAI models for the same and it would be helpful if
you share any resources

**Comment by glenn-jocher** [comment]
Thank you for your detailed questions! Here are the answers:

1. For image classification in YOLOv8, bounding boxes are **not required** since classification tasks involve classifying entire images, not detecting objects within them. The test dataset with 496 images is sufficient for generating metrics like ROC curves.

2. To plot an ROC curve for classification in Colab, you can use the confusion matrix saved during validation (`runs/classify/val/confusion_matrix.npy`) and libraries like `sklearn` to compute and visualize ROC curves. If you're unfamiliar, I can guide you further.

3. For explainability (XAI) in YOLOv8 classification models, techniques like Grad-CAM or SHAP can be useful. Grad-CAM highlights regions influencing the decision, while SHAP provides feature importance. You can explore resources like [SHAP](https://github.com/slundberg/shap) or Grad-CAM implementations in PyTorch for this purpose.

Let me know if you need further details!

**Comment by AdityaBala05** [comment]
Thank you for the clarification. It would be great if you could help me
with ROC curve,
Are there any metrics for explainable AI for Eigencam,gradcam,shap like
there is precision, recall for Yolo models

**Comment by glenn-jocher** [comment]
Thank you for your question. For plotting an ROC curve, you can use the confusion matrix data saved during validation (`runs/classify/val/confusion_matrix.npy`) and a library like `sklearn` to compute and visualize it. Regarding explainable AI (XAI), techniques like Grad-CAM, Eigen-CAM, and SHAP do not have predefined metrics like precision or recall but are used to provide qualitative insights into model predictions. You can find implementations of Grad-CAM and SHAP in PyTorch or explore the [SHAP repository](https://github.com/slundberg/shap) for further examples. Let us know if you have more questions!
