### ISSUE TITLE
Number of images predicted is not the same number as saved labels

### ISSUE THREAD

**Issue by wangworks1002** [ultralytics/ultralytics#9955]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

hi, is this a bug?
![image](https://github.com/ultralytics/ultralytics/assets/71052729/8b68f1db-6bab-4ff5-b1c9-758650d1a72a)
saved images also have missing labels

### Minimal Reproducible Example

# Run inference on the source
```
source = '/content/drive/MyDrive/dataset'
results = model(source, classes=[0], conf=0.3, show_boxes=False, save=True, save_txt=True)
```

# Saved images but missing labels
```
import os

def check_labels_for_jpg(jpg_folder, label_folder):
    # Get a list of JPG files
    jpg_files = [f for f in os.listdir(jpg_folder) if f.endswith('.jpg')]

    # Get a list of TXT files
    label_files = [f for f in os.listdir(label_folder) if f.endswith('.txt')]

    # Convert JPG filenames to set for faster lookup
    jpg_filenames = set(os.path.splitext(f)[0] for f in jpg_files)

    # Convert label filenames to set for faster lookup
    label_filenames = set(os.path.splitext(f)[0] for f in label_files)

    # Check if every JPG file has a corresponding TXT label
    missing_labels = [jpg for jpg in jpg_filenames if jpg not in label_filenames]

    return missing_labels

# JPG folder path
jpg_folder = '/content/drive/MyDrive/annotated_dataset'

# Label folder path
label_folder = '/content/drive/MyDrive/annotated_dataset/labels'

# Check if every JPG file has a corresponding TXT label
missing_labels = check_labels_for_jpg(jpg_folder, label_folder)

if missing_labels:
    print("The following JPG files are missing corresponding TXT labels:")
    for jpg in missing_labels:
        print(jpg + '.jpg')
else:
    print("All JPG files have corresponding TXT labels.")
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wangworks1002 not all images will have labels, therefore less labels than images is possible. It depends on your images of course.

**Comment by wangworks1002** [comment]
hi @glenn-jocher, can you explain more? what do you mean by "not all images will have labels"? is it because there is nothing detected?

**Comment by glenn-jocher** [comment]
Hi there! Exactly, if YOLOv8 does not detect any objects that meet the criteria (i.e., class IDs specified and confidence threshold) in some images, those images won't have corresponding label files after prediction. This scenario can occur when no objects are detected or all detections fall below the confidence threshold you've set. Hope that clarifies things! 😊
