### ISSUE TITLE
How to reduce YOLOv8  detection model parameters?

### ISSUE THREAD

**Issue by alaminbhuyan** [ultralytics/ultralytics#9974]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to assess the YOLOv8 model on my research. Now I want to reduce YOLOv8 model parameters and enhance the model performance. So, how can I achieve this?

**Comment by Kayzwer** [comment]
@alaminbhuyan you can try the nano version of v8
