### ISSUE TITLE
Convert yolov8 detection model to .mlpackage model use device=torch.device("mps")

### ISSUE THREAD

**Issue by gaowq2017** [ultralytics/ultralytics#9975]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Cannot convert a MPS Tensor to float64 dtype as the MPS framwork doesn't support float64

### Additional

I have trained the detection model on windows and transform it to macos mps

**Comment by glenn-jocher** [comment]
@gaowq2017 hello! Thanks for reaching out with your issue. 🌟 When converting a YOLOv8 detection model to a `.mlpackage` format for macOS MPS compatibility, it's necessary to ensure the tensor data types are supported by MPS. Currently, MPS does not support `float64` dtype.

If you're facing an issue with data type compatibility during conversion, you might try casting your model's tensors to a supported dtype like `float32` before the conversion process. Here's a small code snippet that could help you adjust your model's tensor dtype:

```python
import torch
from ultralytics import YOLO

# Assume 'model.pt' is your trained YOLOv8 model
model = YOLO('model.pt').to('mps')  # Load the model for conversion

# Casting all model parameters to float32 dtype
model = model.float()

# Proceed with your model conversion to .mlpackage here
# ...
```

This approach ensures your tensors are in a dtype that's compatible with MPS (`float32`), potentially resolving the dtype incompatibility issue. Let me know if this helps, or if there's anything else you need!

**Comment by gaowq2017** [comment]
@glenn-jocher Hello！ Thank you very much! I have successfuly converted it according to your test Demo!

**Comment by glenn-jocher** [comment]
@gaowq2017 Fantastic to hear that it worked for you! 🎉 If you have any more questions or hit another hurdle, feel free to reach out. Happy coding!
