### ISSUE TITLE
yolov8 training

### ISSUE THREAD

**Issue by yangtao0422** [ultralytics/ultralytics#998]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I'd like to ask you a question. After the yolov8s. yaml file network structure has been modified in yolov8 model, can I still use Yolov8s. pt pre-training weight during training?

**Comment by glenn-jocher** [comment]
@yangtao0422 If you have modified the network structure in the yolov8s.yaml file, the pre-training weights from yolov8s.pt may not be directly applicable. Pre-trained weights are trained on a specific network structure, so if the structure has been changed, it may not work as intended.

You may need to retrain the weights from scratch or fine-tune the pre-trained weights on your modified network structure to achieve optimal performance.
