### ISSUE TITLE
Obb, how to use opencv framing

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#9980]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

```python
        obbs = (
            results[0].obb.xywhr.cpu().tolist()
        )  # Get OBBs in [x_center, y_center, width, height, angle] format

        print("obbsobbs", obbs)
        for i, obb in enumerate(obbs):
            xc, yc, w, h, angle = obb  # Unpack the OBB

            # Calculate the four corners of the rotated rectangle
            rect = ((xc, yc), (w, h), angle)
            box = cv2.boxPoints(rect)
            box = np.int0(box)

            # Draw the rotated rectangle
            cv2.drawContours(cvImage, [box], 0, (0, 0, 255), 2)

```
```python

        obbs = (
            results[0].obb.xywhr.cpu().tolist()
        )  # Get OBBs in [x_center, y_center, width, height, angle] format

        for i, obb in enumerate(obbs):
            xc, yc, w, h, angle = obb  # Unpack the OBB

            angle_rad = np.deg2rad(angle)

            dx = w / 2 * np.cos(angle_rad)
            dy = w / 2 * np.sin(angle_rad)
            dhx = h / 2 * np.sin(angle_rad)
            dhy = h / 2 * np.cos(angle_rad)

            corners = [
                (int(xc - dx - dhx), int(yc - dy + dhy)),
                (int(xc + dx - dhx), int(yc + dy + dhy)),
                (int(xc + dx + dhx), int(yc + dy - dhy)),
                (int(xc - dx + dhx), int(yc - dy - dhy)),
            ]

            for ii in range(4):
                cv2.line(
                    cvImage, corners[ii], corners[(ii + 1) % 4], (0, 255, 0), 2
                ) 

```

Unfortunately
Unable to draw rotation box

**Comment by glenn-jocher** [comment]
Hey there! It looks like you're on the right track with your code to draw oriented bounding boxes (OBBs) using OpenCV. Your first code snippet using `cv2.boxPoints()` and `cv2.drawContours()` is generally the recommended way to draw rotated rectangles in OpenCV.

One minor correction might help if you're experiencing issues:

- Ensure that `cvImage` is properly defined and is an actual image array where you want to draw the OBBs.

If you're still facing issues with drawing the rotation box, could you please provide a bit more detail about the error or unexpected behavior you're encountering? Sometimes the devil is in the details. 🕵️‍♂️

Also, it would be helpful to know whether the rectangles appear incorrect in terms of orientation, size, or if they're not appearing at all. A common issue might be related to the data type or range of the coordinates and angles you’re working with.

Stay awesome, and let's solve this puzzle together! 🚀

**Comment by Petros626** [comment]
@monkeycc news?
