### ISSUE TITLE
Can YOLOv8-OpenCV-ONNX-Python be used to detect a video

### ISSUE THREAD

**Issue by liuliwenqing** [ultralytics/ultralytics#9982]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The current YOLOv8-OpenCV-ONNX-Python code only provides the option to detect a single image, how do I modify the code if I want to detect a video?

**Comment by glenn-jocher** [comment]
Certainly! You can modify the YOLOv8-OpenCV-ONNX-Python code to process video frames in a loop. Here is a concise example of how you can achieve video frame processing using OpenCV to read the video and process each frame with the YOLOv8 model:

```python
import cv2
import numpy as np
# Assume onnx_model and preprocess_input are already defined

# Load your video
cap = cv2.VideoCapture('path/to/your/video.mp4')

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Preprocess the frame before prediction
    preprocessed_frame = preprocess_input(frame)
    # Convert the frame to format expected by your onnx_model here and execute the prediction
    # e.g., preprocessed_frame = np.expand_dims(preprocessed_frame, axis=0) for batch dimension

    # Run the ONNX model on the frame
    detections = onnx_model.run(None, {'input': preprocessed_frame})

    # Process model output and draw detection boxes on the frame
    # This is dependent on the output format of your model
    
    # Display the resulting frame
    cv2.imshow('Frame', frame)

    # Press 'q' to exit the loop
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything is done, release the video capture object
cap.release()
cv2.destroyAllWindows()
```

Be sure to adjust `'path/to/your/video.mp4'`, `preprocess_input`, and model execution code (`onnx_model.run()`) to fit your actual setup. The crucial parts here involve reading the video frame by frame and preprocessing each frame as your model expects. Good luck and happy coding! 🚀

**Comment by liuliwenqing** [comment]
Thank you very much

**Comment by glenn-jocher** [comment]
You're welcome! 😊 If you have any more questions or need further assistance with your project, feel free to reach out. Happy coding! 🚀
