### ISSUE TITLE
Yolov8 -  Youtube Shorts URL.

### ISSUE THREAD

**Issue by nishantgautam020** [ultralytics/ultralytics#9987]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

ValueError                                Traceback (most recent call last)
Cell In[62], line 7
      4 # Define source as YouTube video URL
      5 source = 'https://www.youtube.com/shorts/i315dYuHme0'
----> 7 model4.predict(source, save= True)

File ~/opt/miniconda3/envs/od/lib/python3.8/site-packages/ultralytics/engine/model.py:439, in Model.predict(self, source, stream, predictor, **kwargs)
    437 if prompts and hasattr(self.predictor, "set_prompts"):  # for SAM-type models
    438     self.predictor.set_prompts(prompts)
--> 439 return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)

File ~/opt/miniconda3/envs/od/lib/python3.8/site-packages/ultralytics/engine/predictor.py:206, in BasePredictor.__call__(self, source, model, stream, *args, **kwargs)
    204     return self.stream_inference(source, model, *args, **kwargs)
    205 else:
--> 206     return list(self.stream_inference(source, model, *args, **kwargs))

File ~/opt/miniconda3/envs/od/lib/python3.8/site-packages/torch/utils/_contextlib.py:35, in _wrap_generator.<locals>.generator_context(*args, **kwargs)
     32 try:
     33     # Issuing `None` to a generator fires it up
     34     with ctx_factory():
---> 35         response = gen.send(None)
     37     while True:
     38         try:
     39             # Forward the response to our caller and get its next request

File ~/opt/miniconda3/envs/od/lib/python3.8/site-packages/ultralytics/engine/predictor.py:256, in BasePredictor.stream_inference(self, source, model, *args, **kwargs)
    252     self.setup_model(model)
    254 with self._lock:  # for thread-safe inference
    255     # Setup source every time predict is called
--> 256     self.setup_source(source if source is not None else self.args.source)
    258     # Check if save_dir/ label file exists
    259     if self.args.save or self.args.save_txt:

File ~/opt/miniconda3/envs/od/lib/python3.8/site-packages/ultralytics/engine/predictor.py:230, in BasePredictor.setup_source(self, source)
    220 self.imgsz = check_imgsz(self.args.imgsz, stride=self.model.stride, min_dim=2)  # check image size
    221 self.transforms = (
    222     getattr(
    223         self.model.model,
   (...)
    228     else None
    229 )
--> 230 self.dataset = load_inference_source(
    231     source=source, vid_stride=self.args.vid_stride, buffer=self.args.stream_buffer
    232 )
    233 self.source_type = self.dataset.source_type
    234 if not getattr(self, "stream", True) and (
    235     self.dataset.mode == "stream"  # streams
    236     or len(self.dataset) > 1000  # images
    237     or any(getattr(self.dataset, "video_flag", [False]))
    238 ):  # videos

File ~/opt/miniconda3/envs/od/lib/python3.8/site-packages/ultralytics/data/build.py:174, in load_inference_source(source, vid_stride, buffer)
    172     dataset = source
    173 elif webcam:
--> 174     dataset = LoadStreams(source, vid_stride=vid_stride, buffer=buffer)
    175 elif screenshot:
    176     dataset = LoadScreenshots(source)

File ~/opt/miniconda3/envs/od/lib/python3.8/site-packages/ultralytics/data/loaders.py:84, in LoadStreams.__init__(self, sources, vid_stride, buffer)
     81 st = f"{i + 1}/{n}: {s}... "
     82 if urlparse(s).hostname in ("www.youtube.com", "youtube.com", "youtu.be"):  # if source is YouTube video
     83     # YouTube format i.e. 'https://www.youtube.com/watch?v=Zgi9g1ksQHc' or 'https://youtu.be/LNwODJXcvt4'
---> 84     s = get_best_youtube_url(s)
     85 s = eval(s) if s.isnumeric() else s  # i.e. s = '0' local webcam
     86 if s == 0 and (is_colab() or is_kaggle()):

File ~/opt/miniconda3/envs/od/lib/python3.8/site-packages/ultralytics/data/loaders.py:522, in get_best_youtube_url(url, use_pafy)
    519     check_requirements(("pafy", "youtube_dl==2020.12.2"))
    520     import pafy  # noqa
--> 522     return pafy.new(url).getbestvideo(preftype="mp4").url
    523 else:
    524     check_requirements("yt-dlp")

File ~/opt/miniconda3/envs/od/lib/python3.8/site-packages/pafy/pafy.py:124, in new(url, basic, gdata, size, callback, ydl_opts)
    121     else:
    122        from .backend_youtube_dl import YtdlPafy as Pafy
--> 124 return Pafy(url, basic, gdata, size, callback, ydl_opts=ydl_opts)

File ~/opt/miniconda3/envs/od/lib/python3.8/site-packages/pafy/backend_youtube_dl.py:31, in YtdlPafy.__init__(self, *args, **kwargs)
     29 if ydl_opts:
     30     self._ydl_opts.update(ydl_opts)
---> 31 super(YtdlPafy, self).__init__(*args, **kwargs)

File ~/opt/miniconda3/envs/od/lib/python3.8/site-packages/pafy/backend_shared.py:62, in BasePafy.__init__(self, video_url, basic, gdata, size, callback, ydl_opts)
     60 """ Set initial values. """
     61 self.version = __version__
---> 62 self.videoid = extract_video_id(video_url)
     63 self.watchv_url = g.urls['watchv'] % self.videoid
     65 self.callback = callback

File ~/opt/miniconda3/envs/od/lib/python3.8/site-packages/pafy/backend_shared.py:51, in extract_video_id(url)
     48         return vidid
     50 err = "Need 11 character video id or the URL of the video. Got %s"
---> 51 raise ValueError(err % url)

ValueError: Need 11 character video id or the URL of the video. Got https://www.youtube.com/shorts/i315dYuHme0

### Environment

Laptop: Macbook Pro 
Chip: Apple M2

Environment: Conda Environment
Notebook: Jupyter Notebook

### Minimal Reproducible Example

from ultralytics import YOLO 

model4 = YOLO("yolov8x")
# Define source as YouTube video URL
source = 'https://www.youtube.com/shorts/i315dYuHme0'

model4.predict(source, save= True)

### Additional

Only been happening with Youtube Shorts (videos).
Unable to read them.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@nishantgautam020 thanks for the bug report. Yes, I'm able to reproduce. Not sure if there's any quick fix as we rely on `pafy` or `yt-dlp` for YouTube streaming, and they are both throwing errors on the shorts URL.

Can you please raise issues for this at the `yt-dlp` and `pafy` repositories?

**Comment by glenn-jocher** [comment]
@nishantgautam020 great news 😃! Your original issue may now be resolved ✅ in PR https://github.com/ultralytics/ultralytics/pull/13150.

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!
